### PR TITLE
Only sync tags after all migration release batches are completed

### LINKED ISSUE #8812: Migration stuck for some repos
- Gitea version (or commit ref): 1.11.0+dev-155-gdce22efbe
- Git version: whatever runs on try.gitea.io
- Operating system: whatever runs on try.gitea.io
- Database (use `[x]`): whatever runs on try.gitea.io
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) : https://try.gitea.io/pcsv/Pix-Art-Messenger
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Trying to migrate https://github.com/kriztan/Pix-Art-Messenger with issues, wiki, pull requests and releases to Gitea, the migration is stuck, and the repo inaccessible.

No `Settings` tab either, so it is impossible to cancel the migration or delete the broken repo.

## Screenshots
Bildschirmfoto vom 2019-11-03 15-04-29

### PR DESCRIPTION
**Pull request by jolheiser**
Fixes #8812 

Previously we were syncing tags after the first batch of releases, regardless of whether there were more batches to complete.

Screenshot from 2019-12-10 23-24-13

### CODE REVIEW

File: modules/migrations/migrate.go [hunk 1]
```diff
@@ -161,12 +161,16 @@ func migrateRepository(downloader base.Downloader, uploader base.Uploader, opts
 		}
 
 		relBatchSize := uploader.MaxBatchInsertSize("release")
+		syncTags := false
 		for len(releases) > 0 {
-			if len(releases) < relBatchSize {
-				relBatchSize = len(releases)
+			if len(releases) <= relBatchSize {
+				if len(releases) < relBatchSize {
```
Comment (lunny) [inline modules/migrations/migrate.go:167]: For a clean code, I think this line is unnecessary. Even if `len(releases) == relBatchSize`, you can still `relBatchSize = len(releases)`.

**Review by lunny — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]

**Comment by lunny** [comment]
I just merged this and will begin a new try to migration. Please send a back port to v1.10 and maybe you are interested in my comment https://github.com/go-gitea/gitea/pull/9319#discussion_r356413616 .

File: modules/migrations/migrate.go (hunk 1 above)
Comment (jolheiser) [reply modules/migrations/migrate.go:167]: Ah, okay. I will look at this when I re-add the tag sync when there are no releases.  
EDIT: This line will actually become irrelevant again once tags are synced regardless of release length
