### PR TITLE
Fix SSH signing key path will be displayed in the pull request UI

### LINKED ISSUE #35361: SSH signing key path will be displayed in the pull request UI
### Description

related to #34341 

After SSH signing key enabled, the `KeyID` now actually a path which will be displayed in the UI.
Image

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

local

### Database

None

### PR DESCRIPTION
**Pull request by ChristopherHX**
Closes #35361

### CODE REVIEW

**Comment by wxiaoguang** [comment]
FYI:

image

image

**Comment by silverwind** [comment]
Still WIP?

**Comment by ChristopherHX** [comment]
... I am validating my own change now, this is the reason for being a draft. I hope someone else can validate the gpg key case, do not currently have the required setup.

image

We could also mention this is an ssh key.

Now the mentioned case of wxiaoguang is still missing from my side.

**Comment by ChristopherHX** [comment]
The other case is this one: Editing a file, but this is hidden in the title.

image

**Comment by ChristopherHX** [comment]
GPG Screens

image
image

File: models/asymkey/display_key.go [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+package asymkey
+
+import (
+	"os"
+
+	"code.gitea.io/gitea/modules/git"
+)
+
+func GetDisplaySigningKey(key *git.SigningKey) (string, error) {
```
Comment (lunny) [inline models/asymkey/display_key.go]: The struct is sufficiently clear and readable, so we should use it directly.
```
type SigningKey struct {
	KeyID  string
	Format string
}
```
The issue is that KeyID should represent the fingerprint, not the file path of the SSH key. We probably shouldn’t be storing the SSH file path in the KeyID field.

Comment (wxiaoguang) [reply models/asymkey/display_key.go]: No, it is insufficient for other usages.

You will make a mess by " We probably shouldn’t be storing the SSH file path in the KeyID field."

Comment (ChristopherHX) [reply models/asymkey/display_key.go]: I agree, not sufficient for other usages.

git requires for ssh signing that we put the path to public key in the field that normally is the gpg keyid. Those are more usages than for displaying them.

To do this like this we would need more fields...
```go
type SigningKey struct {
	KeyID  string // ssh: Fingerprint / gpg: KeyID
	Key    string // git keyid, ssh: path to public key / gpg: KeyID
	Format string // ssh or openpgp
}
```

_I have been trapped by the dynamic connection between code and tmpl files, that ide intellisense do not understand_

Comment (wxiaoguang) [reply models/asymkey/display_key.go]: > I have been trapped by the dynamic connection between code and tmpl files, that ide intellisense do not understand

Will take a look

Comment (wxiaoguang) [reply models/asymkey/display_key.go]: All fixed now. I think.

**Review by lunny — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]
