### PR TITLE
Sync tags when adopting repos

### LINKED ISSUE #26138: Adopting a "packed-refs" repository with tags
### Feature Description

Lets say we have a repository (windows)
```
mkdir packed
cd packed
git init
echo test > test.txt
git status
git add test.txt
git commit
git tag tag1
git show tag1
git pack-refs
```

now we have a packed repository. lets convert it to bare

```
copy .git ../packed.git
cd ..
cd packed.git
git config --bool core.bare true
```

Now lets adopt this repository by Gitea

It is adopted, but I was unable to make Tags working. Tags remains 0, git push with force tags also says nothing to push. 
The only way - push this (non bare) repository to emptyv repo in Gitea with tags. Only this way it shows tags in UI and in repo itself.

Can anyone try to reproduce and verify if it is a bug.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Zettat123**
Fixes #26138

Sync the tags into database when adopting repos

### CODE REVIEW

**Review by puni9869 — APPROVED** [review]

File: services/repository/adopt.go [hunk 1]
```diff
@@ -195,6 +195,10 @@ func adoptRepository(ctx context.Context, repoPath string, u *user_model.User, r
 		return fmt.Errorf("updateRepository: %w", err)
 	}
 
+	if err = repo_module.SyncReleasesWithTags(repo, gitRepo); err != nil {
+		return fmt.Errorf("syncReleasesWithTags: %w", err)
```
Comment (KN4CK3R) [inline services/repository/adopt.go]:
```suggestion
		return fmt.Errorf("SyncReleasesWithTags: %w", err)
```

**Review by silverwind — APPROVED** [review]
