### PR TITLE
Fix wrong type on hooktask to convert typ from char(16) to varchar(16)

### LINKED ISSUE #14010: Matrix Webhook fails - attempt displays epoch as date
<!-- NOTE: If your issue is a security concern, please send an email to security@gitea.io instead of opening a public issue -->

<!--
    1. Please speak English, this is the language all maintainers can speak and write.
    2. Please ask questions or configuration/deploy problems on our Discord 
       server (https://discord.gg/gitea) or forum (https://discourse.gitea.io).
    3. Please take a moment to check that your issue doesn't already exist.
    4. Please give all relevant information below for bug reports, because 
       incomplete details will be handled as an invalid report.
-->

- Gitea version (or commit ref): 1.14.0+dev-388-gb8c58edf3
- Git version: 2.26.2
- Operating system: running in docker on debian 
  <!-- Please include information on whether you built gitea yourself, used one of our downloads or are using some other package -->
  <!-- Please also tell us how you are running gitea, e.g. if it is being run from docker, a command-line, systemd etc. --->
  <!-- If you are using a package or systemd tell us what distribution you are using -->
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:
```
2020/12/16 04:04:59 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] INSERT INTO "hook_task" 
("repo_id","hook_id","uuid","typ","url","signature","payload_content","http_method","content_type","event_type","is_ssl","is_delivered","delivered","is_succeed","request_content","response_content") VALUES 
($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING "id" [18 11 fe619173-2390-4bbb-b368-229eb5c161b2 matrix           https://***/_matrix/client/r0/rooms/***/send/m.room.message  {     
 "body": "***",
"msgtype": "m.notice",                                                                                                                                                                                           "format": "org.matrix.custom.html",   
"formatted_body": "***",   
"io.gitea.commits": [ 
{  
"id": "e642fcb81be5da12ad7bd04a771d7ab254ce513b", 
"message": "main: any origin", 
"url": "https://git.***/commit/e642fcb81be5da12ad7bd04a771d7ab254ce513b",                                                                                                  "author": {                                                                                                                                                                                                        "name": "***",                                                                                                                                                                                                "email": "****",                                                                                                                                                                                "username": ""                                                                                                                                                                                                 },                                                                                                                                                                                                               "committer": {                                                                                                                                                                                                     "name": "***",                                                                                                                                                                                                "email": "***",                                                                                                                                                                                "username": ""                                                                                                                                                                                                 },    
"verification": null,    
"timestamp": "0001-01-01T00:00:00Z",
"added": null,   
"removed": null,    
"modified": null
            }  
],                                                                                                                                                                                                               "access_token": "*****"   
 } PUT 1 push false false 0 false  ] - 13.554059ms   
2020/12/16 04:04:59 ...outers/routes/chi.go:95:1() [I] Completed POST /***/settings/hooks/11/test 0  in 58.843203ms
2020/12/16 04:04:59 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT "id", "repo_id", "hook_id", "uuid", "typ", "url", "signature", "payload_content", "http_method", "content_type", "event_type", "is_ssl", "is_delivered", "delivered", "is_succeed", "request_content", "response_content" FROM "hook_task" WHERE (repo_id=$1 AND is_delivered=$2) [18 false] - 762.601µs  
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2419] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2420] PUT 
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2425] PUT 
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2427] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2429] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2431] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2433] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2435] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2437] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2439] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2441] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2443] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2445] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2447] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2449] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2451] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2454] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2456] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2459] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2461] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2465] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2466] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2467] PUT
2020/12/16 04:04:59 ...s/webhook/deliver.go:222:DeliverHooks() [E] deliver: Invalid http method for webhook: [2468] PUT
```

## Description

We had working webhooks for matrix but after a recent update all of them started failing. 
The interface to edit the webhook is blank.
All the attempts to send the webhook have NA for request / response and display EPOCH as the attempt date.

## Screenshots

![image](https://user-images.githubusercontent.com/68085235/102304356-8354bb80-3f1a-11eb-80c6-6127d54f1696.png)

### PR DESCRIPTION
**Pull request by lunny**
Fix #14010

### CODE REVIEW

File: services/webhook/deliver.go [hunk 1]
```diff
@@ -78,7 +78,7 @@ func Deliver(t *models.HookTask) error {
 			return err
 		}
 	case http.MethodPut:
-		switch t.Typ {
+		switch strings.TrimSpace(t.Typ) {
```
Comment (CirnoT) [inline services/webhook/deliver.go]: Unnecessary

**Review by CirnoT — CHANGES_REQUESTED** [review]
- Please revert the other TrimSpace change that happened in #13960
- Please ensure migration trims existing whitespaces or it won't fix existing webhooks

File: services/webhook/deliver.go (hunk 1 above)
Comment (lunny) [reply services/webhook/deliver.go]: This is for wrong content on the database because the previous PR.

Comment (CirnoT) [reply services/webhook/deliver.go]: Please have migration fix the data in database instead of writing code that tries to work around this. In future, we won't remember of such edge case and it might cause unnecessary issues for users.

Comment (lunny) [reply services/webhook/deliver.go]: Will do that.

File: models/migrations/v163.go [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+	type HookTask struct {
+		Typ string `xorm:"VARCHAR(16) index"`
+	}
+
+	sess := x.NewSession()
+	defer sess.Close()
+	if err := sess.Begin(); err != nil {
+		return err
+	}
+	if err := recreateTable(sess, new(WebHook)); err != nil {
```
Comment (zeripath) [inline models/migrations/v163.go]:
```go
// recreateTable will recreate the table using the newly provided bean definition and move all data to that new table
// WARNING: YOU MUST PROVIDE THE FULL BEAN DEFINITION
// WARNING: YOU MUST COMMIT THE SESSION AT THE END
func recreateTable(sess *xorm.Session, bean interface{}) error {
```

This will destroy all data in the webhook and hooktask tables as this stands.

YOU MUST PROVIDE THE FULL BEAN DEFINITION

**Review by zeripath — DISMISSED** [review]

**Comment by lafriks** [comment]
@lunny migration fails on MSSQL:
```
[I] Migration[165]: Convert hook task type from char(16) to varchar(16) and trim the column
migration_test.go:259:
            	Error Trace:	migration_test.go:259
            	            				migration_test.go:296
            	Error:      	Received unexpected error:
            	            	migrate: do migrate: mssql: Incorrect syntax near 'MODIFY'.
```

**Comment by lunny** [comment]
> @lunny migration fails on MSSQL:
> 
> ```
> [I] Migration[165]: Convert hook task type from char(16) to varchar(16) and trim the column
> migration_test.go:259:
>             	Error Trace:	migration_test.go:259
>             	            				migration_test.go:296
>             	Error:      	Received unexpected error:
>             	            	migrate: do migrate: mssql: Incorrect syntax near 'MODIFY'.
> ```

Yes, I think this should be a bug of xorm for mssql

**Comment by zeripath** [comment]
just use recreatetable ...

File: models/migrations/v165.go [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+package migrations
+
+import (
+	"xorm.io/xorm"
+	"xorm.io/xorm/schemas"
+)
+
+func convertHookTaskTypeToVarcharAndTrim(x *xorm.Engine) error {
+	dbType := x.Dialect().URI().DBType
+	if dbType == schemas.SQLITE { // For SQLITE, varchar or char will always be represented as TEXT
```
Comment (6543) [inline models/migrations/v165.go:14]: shouldn't we still trim it on sqlite too?

Comment (lafriks) [reply models/migrations/v165.go:14]: No, sqlite is already working correctly as it does not have char type as in other databases

**Comment by lafriks** [comment]
> just use recreatetable ...

That could be expensive on servers with many webhook calls as I think webhook history table tends to be largest one of all 😅

**Comment by lunny** [comment]
depends on https://gitea.com/xorm/xorm/pulls/1849

**Comment by lunny** [comment]
blocked by #14246

**Comment by lafriks** [comment]
Looks like MSSQL needs separate session for alter table also

**Comment by CirnoT** [comment]
> > just use recreatetable ...
> 
> That could be expensive on servers with many webhook calls as I think webhook history table tends to be largest one of all 😅

Implying that this `UPDATE` won't cause `copy to tmp` on MySQL anyway...

**Comment by lunny** [comment]
@CirnoT @lafriks @zeripath Please review again.

File: models/migrations/v165.go [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+// Use of this source code is governed by a MIT-style
+// license that can be found in the LICENSE file.
+
+package migrations
+
+import (
+	"context"
+
+	"code.gitea.io/gitea/modules/log"
+	"xorm.io/xorm"
```
Comment (lafriks) [inline models/migrations/v165.go:8]:
```suggestion

	"xorm.io/xorm"
```

File: models/migrations/v165.go [hunk 5]
```diff
@@ -0,0 +1,105 @@
...
+import (
+	"context"
+
+	"code.gitea.io/gitea/modules/log"
+
+	"xorm.io/xorm"
+	"xorm.io/xorm/schemas"
+)
+
+func modifyColumn(x *xorm.Engine, tableName string, col *schemas.Column) error {
```
Comment (lafriks) [inline models/migrations/v165.go]: This should be moved to  `migrations.go` file as it can be reused later for other migrations

**Review by lafriks — APPROVED** [review]

File: models/migrations/migrations.go [hunk 6]
```diff
@@ -737,3 +741,39 @@ func dropTableColumns(sess *xorm.Session, tableName string, columnNames ...strin
 
 	return nil
 }
+
+// modifyColumn will modify column's type or other propertity. SQLITE is not supported
+func modifyColumn(x *xorm.Engine, tableName string, col *schemas.Column) error {
+	var indexes map[string]*schemas.Index
+	var err error
+	// MSSQL have to remove index at first, otherwise alter column will fail
```
Comment (6543) [inline models/migrations/migrations.go:749]: shouldn't this go into xorm too?

File: models/migrations/v161.go [hunk 7]
```diff
@@ -34,7 +34,7 @@ func convertTaskTypeToString(x *xorm.Engine) error {
 	}
 
 	type HookTask struct {
-		Typ string `xorm:"char(16) index"`
+		Typ string `xorm:"VARCHAR(16) index"`
```
Comment (CirnoT) [inline models/migrations/v161.go:37]: Should we modify prior migrations?

File: models/migrations/migrations.go [hunk 8]
```diff
@@ -737,3 +741,39 @@ func dropTableColumns(sess *xorm.Session, tableName string, columnNames ...strin
...
+	// ref. https://sqlzealots.com/2018/05/09/error-message-the-index-is-dependent-on-column-alter-table-alter-column-failed-because-one-or-more-objects-access-this-column/
+	if x.Dialect().URI().DBType == schemas.MSSQL {
+		indexes, err = x.Dialect().GetIndexes(x.DB(), context.Background(), tableName)
+		if err != nil {
+			return err
+		}
+
+		for _, index := range indexes {
+			_, err = x.Exec(x.Dialect().DropIndexSQL(tableName, index))
```
Comment (CirnoT) [inline models/migrations/migrations.go:758]: If we're dropping index and then re-creating it then we might as well just do recreatetable, there will be absolutely zero difference in performance between two.

Comment (lafriks) [reply models/migrations/migrations.go:758]: That won't be same and also this is only for MSSQL that is actually not so commonly used imho

File: models/migrations/v161.go (hunk 7 above)
Comment (lafriks) [reply models/migrations/v161.go:37]: Yes, this will help not to break them in the first place and help in case when you are migrating from v1.13.x to v1.14.0

File: models/migrations/migrations.go (hunk 8 above)
Comment (lunny) [reply models/migrations/migrations.go:758]: @CirnoT I think recreate indexes should have better performance than recreate the table. Recreate table contains insert data and generate index, recreate indexes will contain drop index and generate index. So we could compare drop index time and insert data time.

@zeripath Just got an idea. And I think recreatetable could have a performance optimization, we should copy data from original table and then create indexes but not create indexes and then copy data from original.

Comment (zeripath) [reply models/migrations/migrations.go:758]: > @zeripath Just got an idea. And I think recreatetable could have a performance optimization, we should copy data from original table and then create indexes but not create indexes and then copy data from original.

I think that might not be allowed on every db - I'm sure I tried it that way round too.

**Review by 6543 — APPROVED** [review]

File: models/migrations/migrations.go (hunk 8 above)
Comment (lunny) [reply models/migrations/migrations.go:758]: @zeripath It should be allowed. Sometimes, this is a tricky to insert plenty of data to database. A notice is we have to manually confirm no duplicated content on unique index columns when inserting data.

Comment (CirnoT) [reply models/migrations/migrations.go:758]: @lunny @lafriks This is still pointless, the `ALTER TABLE` statement here will cause `copy to tmp` (so, it will create temporary table with new schema, copy data to it and then rename it) on InnoDB engine anyway, so you are in fact doing what recreate table does, just in more lines of code for absolutely zero benefit on performance.

File: models/migrations/v161.go (hunk 7 above)
Comment (CirnoT) [reply models/migrations/v161.go:37]: How exactly will it help? The v165 will run anyway.

Comment (lunny) [reply models/migrations/v161.go:37]: It will let v165 faster because once database know the type of the modify column is the same as before, it will ignore that.

**Review by CirnoT — APPROVED** [review]
