### PR TITLE
Fix automerge will not work because of some events haven't been triggered

### LINKED ISSUE #20646: [v1.17.0]  Automerge / Admin merge sometimes doesn't work
### Description

I've two issues[^1] which are closely related with latest gitea v1.17.0

1. I can't see the automerge feature, but normally i can force merge as admin.

2. Today i couldn't merge PR's because they where blocked because they are outdated

[^1]: https://discourse.gitea.io/t/gitea-automerge-when-succeed-v1-17/5620

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

image

### Git Version

offical docker image

### Operating System

offical docker image

### How are you running Gitea?

2 node HA from official gitea chart with redis / nfs

### Database

PostgreSQL

### LINKED ISSUE #24445: Automerge does not work
### Description

I added next rules for merging PR
* All statuses of commit must be successful before merge
* PR must have one approve review 

### Gitea Version

1.19.2

### Can you reproduce the bug on the Gitea demo site?

I don't know (I can't check it)

### Log Gist

_No response_

### Screenshots

image
image

### Git Version

git version 2.25.1

### Operating System

ubuntu 20.04 (Linux beloved-pipefish 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)

### How are you running Gitea?

I run Gitea from prepared binary files 

### Database

SQLite

### LINKED ISSUE #30658: Can not create merge commit when checks succeed
### Description

image

reproduce:
user A: site admin
user B: normal user
- user A: create an individual repo
- user A: add user B as a contributor with write permission
- user A: push some code to this repo with an action workflow
- user A: add a branch rule to main with 
  push whitelisted (only user B), required approvals: 1, enable status check
- user B: create a new branch
- user B: create PR
- user B: push a commit to this new branch
- wait until required jobs finished with success status
  updated: important, if jobs are in pending, you will not get any error
- user B: click that blue button

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

build

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Replace #25741
Close #24445
Close #30658
Close #20646
~Depends on #30805~

Since #25741 has been rewritten totally, to make the contribution easier, I will continue the work in this PR. Thanks @6543

### CODE REVIEW

File: services/automerge/automerge.go [hunk 1]
```diff
@@ -62,16 +65,6 @@ func addToQueue(pr *issues_model.PullRequest, sha string) {
 // ScheduleAutoMerge if schedule is false and no error, pull can be merged directly
 func ScheduleAutoMerge(ctx context.Context, doer *user_model.User, pull *issues_model.PullRequest, style repo_model.MergeStyle, message string) (scheduled bool, err error) {
 	err = db.WithTx(ctx, func(ctx context.Context) error {
-		lastCommitStatus, err := pull_service.GetPullRequestCommitStatusState(ctx, pull)
```
Comment (lunny) [inline services/automerge/automerge.go:65]: The check is not enough, we at least call `pull_service.CheckPullMergable` to check whether the pull request is mergeable. If it returns false, we need to return a message to the UI.

**Comment by yp05327** [comment]
I think we need some tests.

**Comment by lunny** [comment]
> I think we need some tests.

Tests added.

File: services/automerge/automerge.go (hunk 1 above)
Comment (lunny) [reply services/automerge/automerge.go:65]: We should allow to start checking auto merge even if commit statuses not PASS.

**Review by wolfogre — APPROVED** [review]

**Review by wxiaoguang — DISMISSED** [review]

File: services/automerge/automerge.go [hunk 2]
```diff
@@ -111,6 +104,33 @@ func MergeScheduledPullRequest(ctx context.Context, sha string, repo *repo_model
 	return nil
 }
 
+// StartPRCheckAndAutoMerge start an automerge check and auto merge task for a pull request
+func StartPRCheckAndAutoMerge(ctx context.Context, pull *issues_model.PullRequest) {
```
Comment (wxiaoguang) [inline services/automerge/automerge.go:108]: Why not make `StartPRCheckAndAutoMergeBySHA` call `StartPRCheckAndAutoMerge` to avoid duplicate code?

Comment (lunny) [reply services/automerge/automerge.go:108]: They are two different functions. I think less code are duplicated.

Comment (wxiaoguang) [reply services/automerge/automerge.go:108]: Actually I don't see why `sha` should be passed into `addToQueue`

It seems that the `sha` is only used for logging. Ideally only call `addToQueue(pr.ID)` should be enough, and a lot of code could be simplified?

Comment (lunny) [reply services/automerge/automerge.go:108]: I think the SHA will prevent when both an automerge task and a newly push are triggered. So the previous triggered automerge task will be ignored.
```
if headCommitID != sha {
		log.Warn("Head commit id of auto merge %-v does not match sha [%s], it may means the head branch has been updated. Just ignore this request because a new request expected in the queue", pr, sha)
		return
	}
```

Comment (wxiaoguang) [reply services/automerge/automerge.go:108]: Actually such check doesn't seem right and only makes some problem harder to debug.

Because, the head commit ID could change again after that check.

**Review by wxiaoguang — APPROVED** [review]
Doesn't seem quite right, but just do it.

File: services/automerge/automerge.go [hunk 3]
```diff
@@ -111,6 +104,33 @@ func MergeScheduledPullRequest(ctx context.Context, sha string, repo *repo_model
...
+	}
+
+	gitRepo, err := gitrepo.OpenRepository(ctx, pull.BaseRepo)
+	if err != nil {
+		log.Error("OpenRepository: %v", err)
+		return
+	}
+
+	commitID, err := gitRepo.GetRefCommitID(pull.GetGitRefName())
+	gitRepo.Close()
```
Comment (wxiaoguang) [inline services/automerge/automerge.go]:
```suggestion
	defer gitRepo.Close()
	commitID, err := gitRepo.GetRefCommitID(pull.GetGitRefName())
```

File: services/automerge/automerge.go (hunk 2 above)
Comment (lunny) [reply services/automerge/automerge.go:108]: Yes, it's not perfect. It needs more refactor like I said before. But since it's a bugfix, I will not do it in this PR.
