### PR TITLE
fix: Admin can see all private repositories on Explore page.

### LINKED ISSUE #1022: Admin can't see all private repositories on Explore page.
Admin can't see all private repositories on explore page. Just see the self-repositories.

@lunny Please assign this issue to me.

### PR DESCRIPTION
**Pull request by appleboy**
fix #1022 

* Remove counter function in `RepoSearchOptions`
* Check IsAdmin Flag in search.

### CODE REVIEW

File: models/repo.go [hunk 1]
```diff
@@ -1719,40 +1721,61 @@ func GetUserMirrorRepositories(userID int64) ([]*Repository, error) {
...
+			ownerIds = append(ownerIds, org.ID)
 		}
+
+		cond = cond.Or(builder.In("owner_id", ownerIds))
+	}
+
+	sess = x.Where(cond)
+
+	var countSess xorm.Session
+	countSess = *sess
```
Comment (lunny) [inline models/repo.go]: It's not a good idea to copy Session. I think you can use cond?

File: models/repo.go [hunk 2]
```diff
@@ -1719,40 +1721,61 @@ func GetUserMirrorRepositories(userID int64) ([]*Repository, error) {
...
+	count, err := countSess.Count(new(Repository))
```
Comment (lunny) [inline models/repo.go]: `count, err := x.Where(cond).Cound(new(Repository))`

Comment (appleboy) [reply models/repo.go]: Done https://github.com/go-gitea/gitea/pull/1026/commits/e8924042e6596176ba79273181afeae0e16c8915

File: models/repo.go (hunk 1 above)
Comment (appleboy) [reply models/repo.go]: Done https://github.com/go-gitea/gitea/pull/1026/commits/e8924042e6596176ba79273181afeae0e16c8915

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
conflicted

**Comment by appleboy** [comment]
fixed conflicts.

File: models/repo.go [hunk 3]
```diff
@@ -1242,14 +1242,16 @@ func Repositories(opts *SearchRepoOptions) (_ RepositoryList, err error) {
...
+		return nil, 0, fmt.Errorf("Repo: %v", err)
 	}
 
 	if err = repos.loadAttributes(x); err != nil {
-		return nil, fmt.Errorf("LoadAttributes: %v", err)
+		return nil, 0, fmt.Errorf("LoadAttributes: %v", err)
 	}
 
-	return repos, nil
+	count = countRepositories(-1, opts.Private)
```
Comment (ethantkoenig) [inline models/repo.go:1252]: Here, we check `opts.Private` to see if we should include private repos, but when populating the `repos` slice, we always include private repos regardless of `opts.Private`

File: models/repo.go [hunk 4]
```diff
@@ -1231,7 +1231,7 @@ func CountUserRepositories(userID int64, private bool) int64 {
 }
 
 // Repositories returns all repositories
-func Repositories(opts *SearchRepoOptions) (_ RepositoryList, err error) {
+func Repositories(opts *SearchRepoOptions) (_ RepositoryList, count int64, err error) {
```
Comment (ethantkoenig) [inline models/repo.go:1234]: __EDITED__: Why does this function not examine the contents of `opts.Searcher`, and exclude repos accordingly (like `GetRecentUpdateRepositories(..)~`)?

**Review by ethantkoenig — CHANGES_REQUESTED** [review]

File: models/repo.go (hunk 4 above)
Comment (appleboy) [reply models/repo.go:1234]: Why need to examine the contents of `opts.Searcher`? 

https://github.com/go-gitea/gitea/blob/master/models/issue_indexer.go#L119
https://github.com/go-gitea/gitea/blob/master/routers/admin/repos.go#L28

File: models/repo.go (hunk 3 above)
Comment (appleboy) [reply models/repo.go:1252]: `Repositories` always returns all repositories. maybe we need to change `countRepositories(-1, true)`?

File: models/repo.go (hunk 4 above)
Comment (ethantkoenig) [reply models/repo.go:1234]: Since `Repositories(..)` only looks at `opts.PageSize`, `opts.Page`, and `opts.OrderBy`, would it be better to have it take those 3 values as separate arguments?

File: models/repo.go (hunk 3 above)
Comment (appleboy) [reply models/repo.go:1252]: I can create another PR to refactor the codes according to your suggestion.

**Review by ethantkoenig — APPROVED** [review]
LGTM

File: models/repo.go (hunk 4 above)
Comment (appleboy) [reply models/repo.go:1234]: NO. I think using `SearchRepoOptions` would be better than take 3 arguments if we want to extend the function.

**Comment by appleboy** [comment]
let L-G-T-M work
