### PR TITLE
Fix Bug in Issue/pulls list

### LINKED ISSUE #32080: Gitea always shows close button when I clicked multi select checkbox in issue list
### Description

Thanks to @sangcheol12 and @Lieslot I found some UI bug. 
When I check the multi-select checkbox in the issues list, the close button is always shown, even though I have selected closed issues.
This problem also occurs in pull requests list, because they share same logic. 

[This branch](https://github.com/cloudchamb3r/gitea/tree/fix/issues-is-show-closed) has a fix for this issue. 

## opened issues
Screenshot 2024-09-19 at 6 04 48 PM

## closed issues
Screenshot 2024-09-19 at 6 04 55 PM

### Gitea Version

1.22

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

OSX Sonoma

### Browser Version

Chrome 129.0.6668.58

### PR DESCRIPTION
**Pull request by cloudchamb3r**
fix #32080

### for opened issues 
Screenshot 2024-09-19 at 6 29 31 PM

### for closed issues 
Screenshot 2024-09-19 at 6 29 37 PM

### for all issues
Screenshot 2024-09-20 at 12 07 12 PM

### CODE REVIEW

File: routers/web/repo/issue.go [hunk 1]
```diff
@@ -467,6 +467,9 @@ func issues(ctx *context.Context, milestoneID, projectID int64, isPullOption opt
 	ctx.Data["AssigneeID"] = assigneeID
 	ctx.Data["PosterID"] = posterID
 	ctx.Data["Keyword"] = keyword
+	if isShowClosed.Has() {
+		ctx.Data["IsShowClosed"] = isShowClosed.Value()
```
Comment (lunny) [inline routers/web/repo/issue.go]: I think since `IsShowClosed` has 3 states, it's better to change the template. the current implementation has only two states. `ctx.Data["IsShowClosed"] = false` is equal to not set the template variable.

Comment (cloudchamb3r) [reply routers/web/repo/issue.go]: ~As far as I know when `state` query parameter is not setted (that also means `IsShowClosed` does not have a  value), issue list shows opened issues.
I think in that case, `ctx.Data["IsShowClosed"] = false` doesn't seemed to be error prone.
Is there are any edge cases that i'm missing?~

I found a edge case that select all issue. in that case I'll make not to show open or close button. Is that would be ok?

**Review by lunny — APPROVED** [review]

**Review by wolfogre — APPROVED** [review]
