### PR TITLE
Only show the latest version in the Arch index

### LINKED ISSUE #33534: Arch package registry: client error when two versions of a package are present
### Description

When a new version of a package is added, the database includes both old and new versions. This confuses pacman client. 

```
error: <repo> database is inconsistent: version mismatch on package <package name>
```
The default core and extra repos include only the latest version of each package.

### Gitea Version

1.23.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

archlinux

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by ExplodingDragon**
Only show the latest version of the package in the arch repo.

closes #33534

### CODE REVIEW

File: services/packages/arch/vercmp.go [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+	if res := compareSegments([]string{epochA}, []string{epochB}); res != 0 {
+		return res
+	}
+
+	if res := compareSegments(strings.Split(versionA, "."), strings.Split(versionB, ".")); res != 0 {
+		return res
+	}
+
+	return compareSegments([]string{releaseA}, []string{releaseB})
+}
```
Comment (ExplodingDragon) [inline services/packages/arch/vercmp.go:113]: It seems that this is a common feature,  this part of the code may already exist ?

Comment (lunny) [reply services/packages/arch/vercmp.go:113]: How about to reuse github.com/hashicorp/go-version

Comment (ExplodingDragon) [reply services/packages/arch/vercmp.go:113]: > How about to reuse github.com/hashicorp/go-version

`github.com/hashicorp/go-version` seems to implement a very complex comparison , and I'm not sure if it's compatible with [pacman vercmp](https://man.archlinux.org/man/vercmp.8.en).

Comment (lunny) [reply services/packages/arch/vercmp.go:113]: From the example.
```
Alphanumeric:
  1.0a < 1.0b < 1.0beta < 1.0p < 1.0pre < 1.0rc < 1.0 < 1.0.a < 1.0.1
Numeric:
  1 < 1.0 < 1.1 < 1.1.1 < 1.2 < 2.0 < 3.0.0
````
I think yes, they are compatible.

File: modules/setting/packages.go [hunk 2]
```diff
@@ -102,6 +104,7 @@ func loadPackagesFrom(rootCfg ConfigProvider) (err error) {
 	Packages.LimitSizeSwift = mustBytes(sec, "LIMIT_SIZE_SWIFT")
 	Packages.LimitSizeVagrant = mustBytes(sec, "LIMIT_SIZE_VAGRANT")
 	Packages.DefaultRPMSignEnabled = sec.Key("DEFAULT_RPM_SIGN_ENABLED").MustBool(false)
+	Packages.RepoLatestVersionArch = sec.Key("REPO_KEEP_LATEST_VERSION_ARCH").MustBool(false)
```
Comment (wxiaoguang) [inline modules/setting/packages.go]: Why it is called `REPO_KEEP_LATEST_VERSION_ARCH`? Isn't it just for every package? Is it really related to `repo`?

File: services/packages/arch/vercmp.go (hunk 1 above)
Comment (hiifong) [reply services/packages/arch/vercmp.go:113]: > Additionally, version strings can have an epoch value defined that will overrule any version comparison, unless the epoch values are equal. This is specified in an epoch:version-rel format. For example, 2:1.0-1 is always greater than 1:3.6-1.

Semantic versioning does not seem to support epoch value representation.

Comment (ExplodingDragon) [reply services/packages/arch/vercmp.go:113]: its not compatible with epoch.

File: modules/setting/packages.go (hunk 2 above)
Comment (ExplodingDragon) [reply modules/setting/packages.go]: `REPO_KEEP_LATEST_VERSION_ARCH` -> `KEEP_LATEST_VERSION_ARCH`.

**Review by hiifong — APPROVED** [review]

File: modules/setting/packages.go (hunk 2 above)
Comment (hiifong) [reply modules/setting/packages.go]: Also needed here

**Comment by wxiaoguang** [comment]
Actually I have some questions about the design.

* `KEEP_LATEST_VERSION` sounds like "only keep the package with latest version, and delete others"
* After reading code, I think it means that "only show the package with latest version in the package index"

So the questions are:

* Should we delete the old packages? Or not delete, just hide them from the index (this PR does)?
* Could it ("deleting old packages" or "not-deleting but just hide old packages from index") be a general behavior for other package registries?
* The config name sounds misleading: I think it should clarify what's the expected result in the name: deleting, or just hiding.

**Comment by ExplodingDragon** [comment]
> Actually I have some questions about the design.
> 
>     * `KEEP_LATEST_VERSION` sounds like "only keep the package with latest version, and delete others"
> 
>     * After reading code, I think it means that "only show the package with latest version in the package index"
> 
> 
> So the questions are:
> 
>     * Should we delete the old packages? Or not delete, just hide them from the index (this PR does)?
> 
>     * Could it ("deleting old packages" or "not-deleting but just hide old packages from index") be a general behavior for other package registries?
> 
>     * The config name sounds misleading: I think it should clarify what's the expected result in the name: deleting, or just hiding.


@wxiaoguang   Sorry, I misspoke. `KEEP_LATEST_VERSION` will change to `SHOW_LATEST_VERSION`.

**Comment by wxiaoguang** [comment]
Are there some reference documents for the "only show latest version in index" behavior? (The question is why it is needed to be done on server side, since client could always figure out the latest version)

**Comment by ExplodingDragon** [comment]
> Are there some reference documents for the "only show latest version in index" behavior? (The question is why it is needed to be done on server side, since client could always figure out the latest version)

@wxiaoguang  No, this comes from my subjective opinion. Having too many packages will make the index larger, and most of the time, there isn't much demand for downloading older versions of software packages. Other package registries are facing the same situation.

**Comment by wxiaoguang** [comment]
Thank you for the clarification. To be honest, I think it needs more time to make this PR mature.

1. We could/should learn from other package registries (and maybe arch official site) to see how they handle such requirements.
2. If there are too many out-dated packages (for example, some in-house usage, the packages would be published rapidly), I think it's better to delete them but not just hiding them.

**Comment by ExplodingDragon** [comment]
Thanks for your review.

> We could/should learn from other package registries (and maybe arch official site) to see how they handle such requirements.

In Arch Linux, older versions of packages are stored in the [Arch Linux Archive ](https://wiki.archlinux.org/title/Arch_Linux_Archive), and the index only contains the latest versions. e.g. [archlinux/core/os/x86_64](https://mirrors.ustc.edu.cn/archlinux/core/os/x86_64/) , Other packages are the same, like  [Alpine](https://mirrors.ustc.edu.cn/alpine/edge/community/x86_64/).

But for some software package repositories, like Kubernetes, keeping only the latest version isn't suitable because they need to install older versions to meet their requirements.

> If there are too many out-dated packages (for example, some in-house usage, the packages would be published rapidly), I think it's better to delete them but not just hiding them.

The old package cleanup feature already exists and meets the requirements (it cleans up outdated packages and rebuilds the index).

**Comment by wxiaoguang** [comment]
> > We could/should learn from other package registries (and maybe arch official site) to see how they handle such requirements.
> 
> In Arch Linux, older versions of packages are stored in the [Arch Linux Archive ](https://wiki.archlinux.org/title/Arch_Linux_Archive), and the index only contains the latest versions. e.g. [archlinux/core/os/x86_64](https://mirrors.ustc.edu.cn/archlinux/core/os/x86_64/) , Other packages are the same, like [Alpine](https://mirrors.ustc.edu.cn/alpine/edge/community/x86_64/).

So for this case, it doesn't need a new option, just "only show latest packages" for arch/alpine?

**Comment by ExplodingDragon** [comment]
> So for this case, it doesn't need a new option, just "only show latest packages" for arch/alpine?

@wxiaoguang As mentioned earlier (for some software package repositories like Kubernetes), there are users who need to keep historical versions. 

In fact, this option should be included in the `org/user` package configuration menu. maximum package upload size limit and custom package registry GPG signatures also need to be moved to the organization settings.

**Comment by wxiaoguang** [comment]
> > So for this case, it doesn't need a new option, just "only show latest packages" for arch/alpine?
> 
> @wxiaoguang As mentioned earlier (for some software package repositories like Kubernetes), there are users who need to keep historical versions.

Yes, so I said just "only show latest packages" for **arch/alpine**? It should follow the official behavior.

**Comment by wxiaoguang** [comment]
> In fact, this option should be included in the organization settings. maximum package upload size limit and custom package registry GPG signatures also need to be moved to the organization settings.

Maybe no one has interest/motivation to refactor the user (org) settings system at the moment ..... anyway, "open source".

**Comment by ExplodingDragon** [comment]
> what do you think? Should we follow the official behavior by default, or still introduce new config options?

@wxiaoguang Sorry for the late reply. I think adding the new option seems better. I’m not sure if anyone actually needs the old version installed—even if it’s just 1% of people.

**Comment by lunny** [comment]
> > what do you think? Should we follow the official behavior by default, or still introduce new config options?
> 
> @wxiaoguang Sorry for the late reply. I think adding the new option seems better. I’m not sure if anyone actually needs the old version installed—even if it’s just 1% of people.

How about make 99% as default? And we can have a break label.

**Comment by wxiaoguang** [comment]
Maybe we need to add a flexible org/user setting system first (https://github.com/go-gitea/gitea/pull/33262#issuecomment-2603494785) before introducing this change.

**Comment by wxiaoguang** [comment]
I think we need to merge it without the config option, only show the latest version.

-> Arch package registry: client error when two versions of a package are present #33534

**Comment by wxiaoguang** [comment]
I still do not understand why `SHOW_LATEST_VERSION_ARCH` must be introduced.

* Does any client really depends on "all versions" or does any other registry server show "all versions"?
* What would go wrong if we force to always show latest package?

If there is a must and a strong reasons to introduce `SHOW_LATEST_VERSION_ARCH`, it should be well documented: what's the real usage, how/why other clients/servers do it.

----

There are already too many config options, keep introducing unclear options would make the whole system more difficult to maintain.

**Comment by balki** [comment]
+1 to show only the latest version in db by default without config option. Also lets not delete old versions from gitea (at least have an option to prevent). It is possible to download the package using browser and install using `pacman -U`.

>services/packages/arch/vercmp.go

Not sure this is required. Just using the last uploaded package should be good (order by time of upload). This would also allow to revert back to older version by deleting and re-uploading old version.

**Comment by ExplodingDragon** [comment]
> There are already too many config options, keep introducing unclear options would make the whole system more difficult to maintain.

@wxiaoguang  There’s no good reason to keep this option, this is a bug in Gitea, it’s  intentional from upstream pacman. ( https://github.com/go-gitea/gitea/issues/33534#issuecomment-2646422920)

> Not sure this is required. Just using the last uploaded package should be good (order by time of upload). This would also allow to revert back to older version by deleting and re-uploading old version.

@balki  Keeping the latest version around makes way more sense. Using the last upload timestamp is just gonna cause chaos.

**Comment by ExplodingDragon** [comment]
Since this is a bug, we need to backport it to version 1.23.

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
@KN4CK3R do you have more suggestions for this change?

**Comment by KN4CK3R** [comment]
> > services/packages/arch/vercmp.go
> 
> Not sure this is required. Just using the last uploaded package should be good (order by time of upload). This would also allow to revert back to older version by deleting and re-uploading old version.

I would go with that easy approach too because it will cover most (but sure, not all) use cases. To get the latest package version the `SearchLatestVersions` function can be used. But if you insist to replicate the full version comparison I will not block it.

**Comment by ExplodingDragon** [comment]
> what do you think about it? Keep the current approach, or use `SearchLatestVersions`?

@wxiaoguang  I still believe that comparing the complete versions makes more sense.

 Simply using the last uploaded version goes against intuition. Reverting to a previous version should involve deleting the new version, rather than uploading the old version to overwrite the index of the new one.

Just like [Arch Wiki Downgrading packages](https://wiki.archlinux.org/title/Downgrading_packages) said, randomly downgrading can mess up dependencies: 

> If a downgrade involves a soname change, all dependencies may need downgrading or [rebuilding](https://wiki.archlinux.org/title/Frequently_asked_questions#What_if_I_run_a_full_system_upgrade_and_there_will_be_an_update_for_a_shared_library,_but_not_for_the_applications_that_depend_on_it?) too.

File: services/packages/arch/repository.go [hunk 3]
```diff
@@ -235,6 +235,25 @@ func buildPackagesIndex(ctx context.Context, ownerID int64, repoVersion *package
...
+	for _, pf := range pfs {
+		current := &entryOptions{
+			File: pf,
+		}
+		current.Version, err = packages_model.GetVersionByID(ctx, pf.VersionID)
+		if err != nil {
+			return err
+		}
+
+		if old, ok := vpfs[current.Version.PackageID]; ok {
```
Comment (wxiaoguang) [inline services/packages/arch/repository.go:251]:
```suggestion
		// here we compare the versions but not using SearchLatestVersions because we shouldn't allow "downgrading" to a older version by "latest" one.
		// https://wiki.archlinux.org/title/Downgrading_packages : randomly downgrading can mess up dependencies:
		// If a downgrade involves a soname change, all dependencies may need downgrading or rebuilding too.
		if old, ok := vpfs[current.Version.PackageID]; ok {
```

**Review by wxiaoguang — APPROVED** [review]

**Comment by KN4CK3R** [comment]
> Simply using the last uploaded version goes against intuition. Reverting to a previous version should involve deleting the new version, rather than uploading the old version to overwrite the index of the new one.

That's not intended. As you said, you delete the new version which makes the last version the newest. You don't upload an old version.
