### PR TITLE
Fix PR creation on forked repositories

### LINKED ISSUE #20475: Pull request creation to forked repository via web api fails
### Description

Gitea prevents pull request creation with the web api from the original repository to the fork with the error message: `<Response [404]> b'{"errors":null,"message":"GetForkedRepo","url":"https://try.gitea.io/api/swagger"}\n'`.

I managed to reproduce the issue on https://try.gitea.io/Lixfel/FreeSql .

Reproduction code:
```
token = "?"
import requests
response = requests.post(
        f'https://try.gitea.io/api/v1/repos/Lixfel/FreeSql/pulls?token={token}',
        json={
            "base": "master",
            "head": "huihuiyule:master",
            "title": "Update Upstream"
        })
print(f"{response} {response.content}")
```

Bug origin assumption:
https://github.com/go-gitea/gitea/blob/main/routers/api/v1/repo/pull.go#L967 seems to only allow PRs from the fork to the original repository, a method call `GetForkingRepo` is missing.

### Gitea Version

1.16.9

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/lixfel/e0c36e3b85a1b8ffbf994baf275e49bd

### Screenshots

_No response_

### Git Version

1:2.30.2-1 (apt version)

### Operating System

Debian

### How are you running Gitea?

Use of Gitea Downloads site; execution with systemd

### Database

MySQL

### PR DESCRIPTION
**Pull request by LordChunk**
Resolves #20475

### CODE REVIEW

File: routers/api/v1/repo/pull.go [hunk 1]
```diff
@@ -1110,9 +1110,18 @@ func parseCompareInfo(ctx *context.APIContext, form api.CreatePullRequestOption)
 	// Check if current user has fork of repository or in the same repository.
 	headRepo := repo_model.GetForkedRepo(ctx, headUser.ID, baseRepo.ID)
 	if headRepo == nil && !isSameRepo {
-		log.Trace("parseCompareInfo[%d]: does not have fork or in same repository", baseRepo.ID)
-		ctx.NotFound("GetForkedRepo")
-		return nil, nil, nil, "", ""
+		// Check if the base repository is a fork of the head repository.
+		headRepo, err = repo_model.GetRepositoryByID(ctx, baseRepo.ForkID)
```
Comment (lunny) [inline routers/api/v1/repo/pull.go]: If that, baseRepo should be headRepo and headRepo should be baseRepo.

Comment (LordChunk) [reply routers/api/v1/repo/pull.go]: Ah indeed, the check should be as the comment describes. Working on a revision right now.

Comment (LordChunk) [reply routers/api/v1/repo/pull.go]: I'm not sure what the policy is on resolving comments, so I'll leave this open for now commit 1c94e6d should address the comments you made :slightly\_smiling\_face:

File: routers/api/v1/repo/pull.go [hunk 2]
```diff
@@ -1110,9 +1110,20 @@ func parseCompareInfo(ctx *context.APIContext, form api.CreatePullRequestOption)
...
+		}
+
+		// Check if baseRepo's base repository is the same as headUser's repository.
+		if baseRepo.BaseRepo == nil || baseRepo.BaseRepo.OwnerID != headUser.ID {
+			log.Trace("parseCompareInfo[%d]: does not have fork or in same repository", baseRepo.ID)
+			ctx.NotFound("GetBaseRepo")
+			return nil, nil, nil, "", ""
+		}
+		// Assign headRepo so it can be used below.
+		headRepo = baseRepo.BaseRepo
```
Comment (lunny) [inline routers/api/v1/repo/pull.go:1140]: How about let 
headRepo = baseRepo
baseRepo = headRepo.BaseRepo
?

Comment (lunny) [reply routers/api/v1/repo/pull.go:1140]: Or do a redirection?

Comment (LordChunk) [reply routers/api/v1/repo/pull.go:1140]: > How about let 
> headRepo = baseRepo
> baseRepo = headRepo.BaseRepo
> ?

I don't think this would work with the code that follows after the block that I added. 

The variable names are a little confusing in this context because we're talking about the base repository of a fork as well as a base repository of a pull request.

**Comment by LordChunk** [comment]
@lunny It's not entirely clear to me what changes should still be made to this PR. Would you mind clarifying your previous comment?

**Comment by lunny** [comment]
> @lunny It's not entirely clear to me what changes should still be made to this PR. Would you mind clarifying your previous comment?

The logic looks right. Could you have a test for that change?

**Comment by LordChunk** [comment]
I found it quite complicated to work our exactly how the test suite works, since I could not get single tests to run without getting this error:

```logtalk
Running tool: /usr/local/go/bin/go test -timeout 30s -tags 'sqlite sqlite_unlock_notify' -run ^TestPullCreatePrFromBaseToFork$ code.gitea.io/gitea/tests/integration -v
Environment variable $GITEA_CONF not set, use default: tests/sqlite.ini

sqlite3 requires: import _ "github.com/mattn/go-sqlite3" or -tags sqlite,sqlite_unlock_notify

FAIL  code.gitea.io/gitea/tests/integration 0.069s
```

The test as I've set it up right now is about the best that I could figure out. In case it doesn't quite work as intended, I have added a description of what I tried to make in the comment above the newly added test.

**Comment by lunny** [comment]
You can use `make test-sqlite#Testxxxx` to run the test locally.

**Comment by LordChunk** [comment]
@lunny I've added a test which should cover the changes I've made. If you've got any comments or questions, please let me know 📨

**Review by lunny — APPROVED** [review]

**Review by denyskon — APPROVED** [review]

**Comment by techknowlogick** [comment]
Congrats on your first PR to the codebase, thanks so much!
