### PR TITLE
Fix code block style for code preview

### LINKED ISSUE #30292: Code markup style regression
The inner background is new. Don't know if that is intended but here it looks strange:
grafik

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #30292

To avoid unnecessary style overriding, use "div" instead of "code":

image

### CODE REVIEW

File: services/markup/processorhelper_codepreview_test.go [hunk 1]
```diff
@@ -63,7 +63,7 @@ func TestProcessorHelperCodePreview(t *testing.T) {
 	<table class="file-view">
 		<tbody><tr>
 				<td class="lines-num"><span data-line-number="1"></span></td>
-				<td class="lines-code chroma"><code class="code-inner"><span class="gh"># repo1</code></td>
+				<td class="lines-code chroma"><span class="code-inner"><span class="gh"># repo1</span></td>
```
Comment (delvh) [inline services/markup/processorhelper_codepreview_test.go]: Why `span` instead of `div`?

**Review by delvh — COMMENTED** [review]
Isn't the change to the alert parsing missing?

File: services/markup/processorhelper_codepreview_test.go (hunk 1 above)
Comment (wxiaoguang) [reply services/markup/processorhelper_codepreview_test.go]: <details>

Because "span" doesn't work .... (update: added some comments)

image

</details>



Oh I see, that's some intermediate code (Maybe I created the PR too fast before my push finished), I have changed all to "div" 🤣

**Comment by wxiaoguang** [comment]
> Isn't the change to the alert parsing missing?

Sorry but I didn't get the point. What missing?

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Much better this way. Rendering inside markup is always tricky and the less mismatching styles the better.

**Review by lunny — APPROVED** [review]
