### PR TITLE
Fix branch_protection api shows users/teams who has no readAccess

### LINKED ISSUE #27694: Rest API invalid output compared to UI
### Description

Hi all,

The Gitea REST API {{baseUrl}}/repos/:owner/:repo/branch_protections/:name returns invalid output compared to the data that is shown in UI. 
For instance, we have a repo with protected branch "master". Initially we have added several users for "merge_whitelist_usernames" with user "vasiliy.chipizhin" included into this list. Then this user was retired and we have deleted his account from "merge_whitelist_usernames". It was done several month ago and we have already restarted gitea instance since that time. In Gitea UI i do not see this user account in the whitelist section. But when i use REST API to get list of users, i do see this user account "vasiliy.chipizhin" in API respoce

Postman responce:
"vasiliy.chipizhin" account is presented
postman

Gitea UI:
"vasiliy.chipizhin" account is absent

master-1
master-2

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by edwardzhanged**
Add some logic in `convert.ToBranchProtection` to return only the names associated with readAccess instead of returning all names. This will ensure consistency in behavior between the frontend and backend.
Fixes: #27694

### CODE REVIEW

**Comment by edwardzhanged** [comment]
Any comment please?

**Comment by wxiaoguang** [comment]
ping @lunny

File: services/convert/convert.go [hunk 1]
```diff
@@ -106,30 +106,59 @@ func ToBranch(ctx context.Context, repo *repo_model.Repository, branchName strin
 }
 
 // ToBranchProtection convert a ProtectedBranch to api.BranchProtection
-func ToBranchProtection(ctx context.Context, bp *git_model.ProtectedBranch) *api.BranchProtection {
-	pushWhitelistUsernames, err := user_model.GetUserNamesByIDs(ctx, bp.WhitelistUserIDs)
+func ToBranchProtection(ctx context.Context, bp *git_model.ProtectedBranch, repo *repo_model.Repository) *api.BranchProtection {
+	pushWhitelistUsernamesRaw, err := access_model.GetRepoReadersFromIDs(ctx, repo, bp.WhitelistUserIDs)
```
Comment (lunny) [inline services/convert/convert.go]: Maybe we can borrow some ideas like web routers. We can get all users with `GetRepoReaders` and then filter `bp.WhitelistUserIDs`

Comment (edwardzhanged) [reply services/convert/convert.go]: Agreed. That's much more likely to completely synchronize the behavior with the frontend. I'll commit the new changes later today.

**Review by lunny — APPROVED** [review]

**Comment by edwardzhanged** [comment]
Need another approve.

File: services/convert/convert.go [hunk 2]
```diff
@@ -105,33 +105,60 @@ func ToBranch(ctx context.Context, repo *repo_model.Repository, branchName strin
...
-func ToBranchProtection(ctx context.Context, bp *git_model.ProtectedBranch) *api.BranchProtection {
-	pushWhitelistUsernames, err := user_model.GetUserNamesByIDs(ctx, bp.WhitelistUserIDs)
-	if err != nil {
-		log.Error("GetUserNamesByIDs (WhitelistUserIDs): %v", err)
-	}
-	mergeWhitelistUsernames, err := user_model.GetUserNamesByIDs(ctx, bp.MergeWhitelistUserIDs)
-	if err != nil {
-		log.Error("GetUserNamesByIDs (MergeWhitelistUserIDs): %v", err)
+// getWhitelistEntities returns the names of the entities that are in the whitelist
+func getWhitelistEntities(entities []any, whitelistIDs []int64) []string {
```
Comment (wxiaoguang) [inline services/convert/convert.go]: Could it use generic to avoid misuse?

```
func getWhitelistEntities[T *user_model.User|*organization.Team](entities []T ...)
```

File: services/convert/convert.go [hunk 3]
```diff
@@ -105,33 +105,60 @@ func ToBranch(ctx context.Context, repo *repo_model.Repository, branchName strin
...
+	whitelistIDsMap := make(map[int64]struct{})
```
Comment (wxiaoguang) [inline services/convert/convert.go]: `container.Set` is for this case.

File: services/convert/convert.go (hunk 2 above)
Comment (edwardzhanged) [reply services/convert/convert.go]: Generic was my first idea. Unfortunately, generics don't support `T.ID` and `T.Name`.

File: services/convert/convert.go (hunk 3 above)
Comment (edwardzhanged) [reply services/convert/convert.go]: https://pkg.go.dev/container

Comment (lunny) [reply services/convert/convert.go]: It's `code.gitea.io/gitea/modules/container` not that one.

File: services/convert/convert.go (hunk 2 above)
Comment (wxiaoguang) [reply services/convert/convert.go]:
```
type S1 struct {
	ID int
}
type S2 struct {
	Name string
}

func F[T *S1|*S2] (v T) {
	switch v :=  any(v).(type) {
	case *S1:
		println(v.ID)
	case *S2:
		println(v.Name)
	}
}
```

**Review by wxiaoguang — APPROVED** [review]
