### PR TITLE
Fix broken image when editing comment with non-image attachments

### LINKED ISSUE #32316: Minor visual glitch with file icon in comments
### Description

If I have a post with file attached, while editing post attachment`s part have wrong file icon

After I exit edit mode icon becomes normal

### Screenshots

Edit post mode
image

View mode
image

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

_No response_

### Browser Version

120

### PR DESCRIPTION
**Pull request by yp05327**
Fix #32316

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: web_src/js/features/dropzone.ts [hunk 1]
```diff
@@ -128,10 +128,12 @@ export async function initDropzone(dropzoneEl) {
       fileUuidDict = {};
       for (const attachment of respData) {
         const file = {name: attachment.name, uuid: attachment.uuid, size: attachment.size};
-        const imgSrc = `${attachmentBaseLinkUrl}/${file.uuid}`;
         dzInst.emit('addedfile', file);
-        dzInst.emit('thumbnail', file, imgSrc);
         dzInst.emit('complete', file);
+        if (isImageFile(attachment.name)) {
```
Comment (kemzeb) [inline web_src/js/features/dropzone.ts]: Super small nit: the code below and above this line seem to use `file`, so this could be `file.name` for consistency

**Review by kemzeb — APPROVED** [review]

File: web_src/js/features/dropzone.ts (hunk 1 above)
Comment (yp05327) [reply web_src/js/features/dropzone.ts]: > const file = {name: attachment.name, uuid: attachment.uuid, size: attachment.size};

They are equal.

https://github.com/go-gitea/gitea/pull/32319/commits/cd9febc522c93f29c208aade90f86b091cded30d

**Review by kemzeb — APPROVED** [review]

**Review by KN4CK3R — APPROVED** [review]
