### PR TITLE
Custom regexp external issues

### LINKED ISSUE #3468: Allow custom regex patterns for linking external issues
- Gitea version (or commit ref): 1.3.2
- Git version: 2.16.1
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
For external issue tracker: alphanumeric issue recognition does not work when:
- Key before the dash contains a number. Example: `BLG5-456`
- Key is enclosed in quotes. Example: `'BLG-456'` or `"BLG-456"`
- Key follows a slash: Example `BLG-123/BLG-564` (first key is recognized, second one not)

We think implementing so many additional 'rules' could lead to many false positives.
Thus we propose to add a third _External Issue Tracker Naming Style_ for specifying custom patterns to apply for matching issue keys. Then we could specify a pattern like `(WP-\d+)|(BLG5-\d+)` ourselves.
The matched group should then be used for replacing `{index}` in the _External Issue Tracker URL Format_.

### PR DESCRIPTION
**Pull request by strk**
This is a rebased version of #4265 with conflicts resolved.

\cc @AlexanderBeyn 

Supposedly fixes #3468 but I did not test as I'm currently unable to build Gitea (due to too new Go compiler dependency)

### CODE REVIEW

File: web_src/js/features/repo-legacy.js [hunk 1]
```diff
@@ -309,6 +309,15 @@ export function initRepository() {
         if (typeof $(this).data('context') !== 'undefined') $($(this).data('context')).addClass('disabled');
       }
     });
+    $('.enable-system-pick').change(function () {
```
Comment (silverwind) [inline web_src/js/features/repo-legacy.js]:
```suggestion
    $('.enable-system-pick').on('change', function () {
```

Comment (strk) [reply web_src/js/features/repo-legacy.js]: Thanks @silverwind - fixed with subsequent commit

**Comment by strk** [comment]
I'm letting this go for today and next few days, dunno if I'll have time to catch up again so please if @techknowlogick or @zeripath want to continue from here I'm happy :)

**Comment by 6543** [comment]
@strk can you enable maintainers to edit this pull - or resolve conflicts :)

**Comment by strk** [comment]
"Allow edits by maintainers" is checked already

**Comment by 6543** [comment]
hmm strange - I can't push to the pull head

**Comment by strk** [comment]
I'm afraid github concept of "maintainer" is different from Gitea one. For GitHub, "maintainers" are those with "write access to repository". I know I'm a Gitea mintainer while NOT having write access to it. Feel free to take over this PR by creating a new one, or send a pull request for my fork

**Comment by 6543** [comment]
well I do have write-access ... tldr: I'll create a pull

**Comment by luiscla27** [comment]
How is this going? :)

**Comment by 6543** [comment]
thanks for the ping ;)

**Comment by 6543** [comment]
@strk  https://github.com/strk/gitea/pull/2

**Comment by lunny** [comment]
CI failure is related.

**Comment by strk** [comment]
Sorry I'm unable to build Gitea at the moment so won't be able to check what's going on. The NodeJS requirement raised again and my Ubuntu 21.04 (from last year) doesn't package the newly required version (and I'm too lazy to maintain a separate installation)

**Comment by wxiaoguang** [comment]
You can manually edit https://github.com/go-gitea/gitea/blob/main/package.json#L7 to `"node": ">= 12"` locally if you still want to try nodejs 12, it might still work.

**Comment by strk** [comment]
On Wed, Jun 08, 2022 at 12:21:01AM -0700, wxiaoguang wrote:
> You can manually edit https://github.com/go-gitea/gitea/blob/main/package.json#L7 to `"node": ">= 12"` locally if you still want to try nodejs 12, it might still work.

Unfortunately it doesn't seem to work, lots of errors like:

		npm WARN EBADENGINE Unsupported engine {
		npm WARN EBADENGINE   package: ***@***.******@***.***',
		npm WARN EBADENGINE   required: { node: '^12.22.0 || ^14.17.0 || >=16.0.0' },
		npm WARN EBADENGINE   current: { node: 'v12.21.0', npm: '7.5.2' }
		npm WARN EBADENGINE }

A Go project relying on NodeJS is really frustrating, all the advantages
of Go ruined by NodeJS :P

**Comment by wxiaoguang** [comment]
That's just because the nodejs in Ubuntu 21 is too old. The same situation to Golang, you can not compile the Gitea's Go code with the Golang provided Ubuntu 21 either, so that's not related to advantages or running in my mind ......

**Comment by wxiaoguang** [comment]
Just did a quick search, https://packages.ubuntu.com/impish/nodejs

Ubuntu 21 provides nodejs 12.22.5, which satisfies  `required: { node: '^12.22.0 || ^14.17.0 || >=16.0.0' },`

**Comment by strk** [comment]
On Thu, Jun 09, 2022 at 02:26:45AM -0700, wxiaoguang wrote:
> Just did a quick search, https://packages.ubuntu.com/impish/nodejs
> 
> Ubuntu 21 provides nodejs 12.22.5, which satisfies  `required: { node: '^12.22.0 || ^14.17.0 || >=16.0.0' },`

Maybe you're looking at 21.10 ? This is what I get:

  # lsb_release -r
  Release:        21.04
  # sudo apt install nodejs
  Reading package lists... Done
  Building dependency tree... Done
  Reading state information... Done
  nodejs is already the newest version (12.21.0~dfsg-3ubuntu1).

**Comment by wxiaoguang** [comment]
OK, CI passes, and the frontend has been refactored together.

Maybe it's possible to get it in 1.17

**Review by wxiaoguang — APPROVED** [review]
I did a quick test, it works.

File: modules/regexplru/regexplru.go [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+	var err error
+	lruCache, err = lru.New(1000)
+	if err != nil {
+		log.Fatal("failed to new LRU cache, err: %v", err)
+	}
+}
+
+// GetCompiled works like regexp.Compile, the compiled expr or error is stored in LRU cache
+func GetCompiled(expr string) (r *regexp.Regexp, err error) {
+	v, ok := lruCache.Get(expr)
```
Comment (6543) [inline modules/regexplru/regexplru.go:27]: shouldnt we use our current cache infrastructure ?!?

or is this in this case always faster?

File: modules/markup/html_internal_test.go [hunk 3]
```diff
@@ -22,7 +22,7 @@ const (
 )
 
 // alphanumLink an HTML link to an alphanumeric-style issue
```
Comment (6543) [inline modules/markup/html_internal_test.go]:
```suggestion
// externalIssueLink an HTML link to an alphanumeric-style issue
```

**Comment by silverwind** [comment]
> Maybe you could do a `do-release-upgrade`, instead of using a EOL distro without security patches.
> 
> https://ubuntu.com/about/release-cycle , https://wiki.ubuntu.com/Releases
> Version 	Code name 	Release 	End of Life
> Ubuntu 21.04 	Hirsute Hippo 	April 22, 2021 	January 20, 2022

Or just use the [official nodesource repo](https://github.com/nodesource/distributions#installation-instructions) which is much better than the EOL versions that are in baseline Debian/Ubuntu repos.

File: modules/regexplru/regexplru.go (hunk 2 above)
Comment (wxiaoguang) [reply modules/regexplru/regexplru.go:27]: No. Here it must use an in-memory/in-program/object cache, to store the compiled regexp.

Other string/bytes cache can not be used.

**Review by 6543 — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work.

**Comment by strk** [comment]
On Thu, Jun 09, 2022 at 07:41:37AM -0700, wxiaoguang wrote:
> Maybe you could do a `do-release-upgrade`, instead of using a EOL distro without security patches.

Write error - write (28: No space left on device) Could not open file
Restoring original system state
