### PR TITLE
Fix compare link in active feeds for new branch

### LINKED ISSUE #19144: Broken "compare n commits" link in activity overview when pushing new branch
### Gitea Version

1.16.4

### Git Version

2.30.2

### Operating System

Debian bullseye

### How are you running Gitea?

Through the 3rd party debian package repo.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

Pushing to a branch which wasn't previously known to gitea leads to broken compare links like this in the activity overview

https://server/nidi/test-gitea-issues/compare/0000000000000000000000000000000000000000...f6f27fa74aaecedbcf4b4a3625ceafd6fc368ef6

This happens when doing

    git push --set-upstream origin branch_name

I wasn't able to reproduce this on try.gitea.io as I stumbled over #19143 instead.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by a1012112796**
When a new branch is pushed the old SHA is always listed as the empty sha and thus the compare link that is created does not work correctly.

Therefore when creating the compare link for new branches:

1. Attempt to get the parent of the first commit and use that as the basis
for the compare link.
2. If this is not possible make a comparison to the default branch
3. Finally if that is not possible simply do not show a compare link.

However, there are multiple broken compare links remaining therefore, in order for these to not break we will simply make the compare link redirect to the default branch.

Fix #19144

### CODE REVIEW

File: services/repository/push.go [hunk 1]
```diff
@@ -222,7 +222,25 @@ func pushUpdates(optsList []*repo_module.PushUpdateOptions) error {
...
+					for i := 0; i < oldCommit.ParentCount(); i++ {
+						commitID, _ := oldCommit.ParentID(i)
+						if !commitID.IsZero() {
+							oldCommitID = commitID.String()
+							break
+						}
+					}
+				}
+
+				commits.CompareURL = repo.ComposeCompareURL(oldCommitID, opts.NewCommitID)
```
Comment (zeripath) [inline services/repository/push.go]: this is still going to possibly leave an old commit ID equal to `git.EmptySHA` for absolutely new branch.

**Comment by zeripath** [comment]
I think we need to think a bit more about what the compare url should be doing for new branches.

Is it right to provide a compare url for an absolutely new branch? I would guess that the correct "compare" url for a new branch is supposed to be a compare to the default branch and if it is the default branch then no compare url?

**Review by zeripath — APPROVED** [review]
@a1012112796 I hope you don't mind that I just pushed another thing up here - we also needed to handle the already created broken links so I've just added a small change to compare.go to redirect to the default branch notation

File: services/repository/push.go [hunk 2]
```diff
@@ -222,7 +222,33 @@ func pushUpdates(optsList []*repo_module.PushUpdateOptions) error {
...
-				commits.CompareURL = repo.ComposeCompareURL(opts.OldCommitID, opts.NewCommitID)
+
+				oldCommitID := opts.OldCommitID
+				if oldCommitID == git.EmptySHA && len(commits.Commits) > 0 {
+					oldCommit, err := gitRepo.GetCommit(commits.Commits[len(commits.Commits)-1].Sha1)
+					if err != nil {
+						log.Error("gitRepo.GetCommit %s/%s failed: %v", repo.ID, oldCommitID, err)
+					}
+
+					for i := 0; i < oldCommit.ParentCount(); i++ {
```
Comment (wxiaoguang) [inline services/repository/push.go]: Is it correct to continue to use `oldCommit` if `gitRepo.GetCommit` fails?

Comment (zeripath) [reply services/repository/push.go]: yup that is gonna NPE.

**Review by wxiaoguang — APPROVED** [review]
