### PR TITLE
Fix mirror repository webhooks

### LINKED ISSUE #5441: Webhooks on mirrored repositories broken
- Gitea version (or commit ref): bc42b3a
- Git version: 2.18.1
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (try.gitea.io won't sync the mirror)
  - [ ] Not relevant
- Log gist:

## Description

Gitea synchronizes mirrors but triggering the webhooks fails with no error and the webhook does not get called, contuary to #4127. Pressing "Test Delivery" however, triggers the webhook successfully and causes previous failed webhooks to succeed.

### PR DESCRIPTION
**Pull request by akkowal2**
Fixes #5441 

I found that mirror syncs will properly create hook tasks, however, the hook queue that gitea is monitoring is never updated/notified of the hook task for the repo and thus the hook task is never fulfilled.  If you restart the gitea server, the goroutine first fulfills the current task list and then blocks on the hook queue.  This is why any mirror action webhooks are sent on restart and why any new hook tasks created by mirror actions do not get fulfilled automatically.

Signed-off-by: Drew Kowalski drewkowalski93@gmail.com

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

File: models/action.go [hunk 1]
```diff
@@ -896,6 +896,11 @@ func mirrorSyncAction(e Engine, opType ActionType, repo *Repository, refName str
 	}); err != nil {
 		return fmt.Errorf("notifyWatchers: %v", err)
 	}
+
```
Comment (lunny) [inline models/action.go:899]: You should move these to https://github.com/go-gitea/gitea/blob/master/models/action.go#L943 because it should be with webhook.
