### PR TITLE
Restore functionality for early gits

### LINKED ISSUE #7754: **Whitelist-Push** and **MergePullrequest** does not work when Branch-Protection is enabled
- Gitea version (or commit ref):
1.9.0+3-g6d441de
- Go Version
1.11.5
- Git version:
2.7.4 
- Operating system:
LXC container on ubuntu 16.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description
**Whitelist-Push** and **MergePullrequest** does not work when Branch-Protection is enabled:

```
Pushing develop
Enumerating objects: 7, done.
Delta compression using up to 12 threads
Total 4 (delta 3), reused 0 (delta 0)
POST git-receive-pack (530 bytes)
Remote: Gitea: Internal Server Error        
Remote: Fail to detect force push: exit status 128 - fatal: Not a git repository (or any parent up to mount point /srv/git)        
Remote: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).        
Remote: 
Pushing to myserver
To myserver
Error: failed to push some refs to 'myserver'
```

Merging Pullrequests returns 500 Error

With Gitea 1.8.3+2-g11f6ed4 everything works just fine.

## Screenshots
branch settings

### LINKED ISSUE #7862: Gitea no longer works on git 1.7.2
- Gitea version (or commit ref): master
- Git version: 1.7.2
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

There are multiple problems whereby options have been added to git commands which are unavailable in early git versions. 

* `git remote remove`. This is not available in git < 1.8.0 - `rm` is an alias for it.
* `git config --local`. This is not available in git < 1.8.0 - `config` is an appropriate alias.
* `git commit-tree -m`. This is not available in git < 1.8.0 - the message can simply be passed in as a stdin.
* `git check-attr --cached`. This is not available in git < 1.8.0. It will use the cached version in any case in 1.7 and this option is not used.
* `git fetch` and `git pull` do not behave the same way in git < 2.0.0 to the way expected in merge.go.

### LINKED ISSUE #7863: Cannot run integration tests on git 1.7.2, 1.8.0, 2.1.2+
- Gitea version (or commit ref): master
- Git version: 1.7.2, 1.8.0, 2.1.2
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

We cannot run the gitea integration tests locally on early gits due to a number of issues:

* For git 1.7.2 there are multiple issues in #7862 
* For git < 2.1.2 integration tests expect LFS to run
* For git < 2.3.0 integrations tests requiring SSH won't work because GIT_SSH_COMMAND doesn't exist - we need to use GIT_SSH instead.
* For git > 2.0.0 to some version of git TestDeleteRepoFile will not work due to commit-tree signing by default - this will need to have --no-gpg-sign passed in.
* There's also an issue with the merge - in that the behaviour of fetch etc are different in git < 2.0.0

### PR DESCRIPTION
**Pull request by zeripath**
This PR does a number of things.

* makes it possible to run the test suite on git 1.7.2 and should make gitea work again on git 1.7.2.
* makes it possible to run the test suite on git 2.1.2 making gitea work on git 2.1.2. 
* standardise the base, tracking and staging branches in the merge to simply be base, tracking and staging - thus getting rid of a potential branchname conflict (albeit an unlikely one.)

Fixes #7862
Fixes #7863

### CODE REVIEW

**Comment by zeripath** [comment]
Damn! That breaks the build.

Ok what needs to happen is that the temporary repo just fetches the base and head branches into standard named branches. Perhaps these could simply be master and tracking to keep with the names the system uses internally. That way there is no change that there can be a collision - at present there is a small chance of this.

I'm out of time to do this now so I'll have to leave this broken here for now.

**Comment by lafriks** [comment]
Great job tracking this one down! :tada:

**Comment by lunny** [comment]
How about extract merge bug to a separate PR?

**Comment by zeripath** [comment]
Hey @lunny, so feel free to extract out the second commit separately (which should fix #7754) - my thought process was that I couldn't replicate the problem until I had TestGit working again on my local machine and so I worked from there. Stupidly I forgot to run the full set of tests before pushing.

I won't be able to get to look again at fixing this PR until the evening UK time. The first three commits should be separately extractable - the problem lies in the fourth.

**Comment by jdehaan** [comment]
I think this is definitively solving a couple of issues, the whitelist problem is overcome. But in the following steps there are now issues.

```
2019/08/07 06:31:25 routers/repo/pull.go:629:MergePullRequest() [E] Merge: git checkout: From /srv/git/xxxx/yyyyyy.xxxx
	 * [new branch]      bug/6327-TargetArrayType -> head_repo/bug/6327-TargetArrayType
	 * [new branch]      bug/6327-TargetArrayType -> head_repo/bug/6327-TargetArrayType
	warning: refname 'head_repo/bug/6327-TargetArrayType' is ambiguous.
	warning: refname 'head_repo/bug/6327-TargetArrayType' is ambiguous.
	fatal: Ambiguous object name: 'head_repo/bug/6327-TargetArrayType'.
```

Noticeable is the double lines in the logging... Maybe a hint

**Comment by sharpSteff** [comment]
got problems with `rebase and merge` in 1.10.0+dev-144-gb5b7b67

```
2019/08/07 06:31:25 routers/repo/pull.go:629:MergePullRequest() [E] Merge: git checkout: From /srv/git/yyy/xxxx.git
	 * [new branch]      bug/6327-TargetArrayType -> head_repo/bug/6327-TargetArrayType
	 * [new branch]      bug/6327-TargetArrayType -> head_repo/bug/6327-TargetArrayType
	warning: refname 'head_repo/bug/6327-TargetArrayType' is ambiguous.
	warning: refname 'head_repo/bug/6327-TargetArrayType' is ambiguous.
	fatal: Ambiguous object name: 'head_repo/bug/6327-TargetArrayType'.
```

However `squash and merge` does the job

**Comment by zeripath** [comment]
@jdehaan if you can see if just the second commit solves the issue that would be good to know. The extra commits are to resolve issues with git <1.9

**Comment by jdehaan** [comment]
I understand. I will checkout & build 7ca5dd06688b85483eb42b1c702fc2152225c147 and report. I could take some time I got some urgent tasks on my desk. But I will definitively follow up this topic till the end ;-)

**Comment by jdehaan** [comment]
@sharpSteff  I deployed the version mentioned above (2nd commit of this PR). Could you please try out once again and report the result (at time of your convenience).

**Comment by sharpSteff** [comment]
@zeripath @jdehaan

looks good so far....
rebase works
merge works
push with/without protection  works as expected

**Comment by zeripath** [comment]
OK so there are number of other issues with running old git versions. (Unfortunately most of these are probably my fault.) I will open a PR to track fixes for old git versions.

File: modules/pull/merge.go [hunk 1]
```diff
@@ -100,13 +100,13 @@ func Merge(pr *models.PullRequest, doer *models.User, baseGitRepo *git.Repositor
 		return fmt.Errorf("git remote add [%s -> %s]: %s", headRepoPath, tmpBasePath, errbuf.String())
 	}
 
+	trackingBranch := "tracking"
```
Comment (lafriks) [inline modules/pull/merge.go]: imho this will conflict if two PR are merged at same time

Comment (zeripath) [reply modules/pull/merge.go]: Merging happens within an individual temporary repo:

https://github.com/zeripath/gitea/blob/499efda9d159bab311064d775ec1a2549342530b/modules/pull/merge.go#L56

This is simply an internal name.

Comment (zeripath) [reply modules/pull/merge.go]: https://github.com/go-gitea/gitea/blob/ce8de3533485eed0c56059d6334a5031a73eed67/models/helper_directory.go#L29-L37

Comment (lafriks) [reply modules/pull/merge.go]: But if there will be already branch named so?

Comment (zeripath) [reply modules/pull/merge.go]: You're right. I've just pushed a cleaned version up.

File: integrations/git_helper_for_declarative_test.go [hunk 2]
```diff
@@ -53,6 +60,24 @@ func createSSHUrl(gitPath string, u *url.URL) *url.URL {
 	return &u2
 }
 
+func allowLFSFilters() []string {
```
Comment (typeless) [inline integrations/git_helper_for_declarative_test.go]: Although this is only used in tests, I feel that maybe we can have a nicer way to deal with the situation.
For example, we can add a `git.NewCommandRaw()` or the alike where the global args are not attached implicitly.
So that we can have full control of the passed arguments whenever needed.

**Comment by lunny** [comment]
Please resolve the conflicts.

**Comment by guillep2k** [comment]
@zeripath Could you give me any hints about what was the nature of the incompatiblity to help me review your PR?

**Comment by zeripath** [comment]
Ok, so if you try to run Gitea and the test suite with git 1.7.2 on Gitea master it will fail.

Similarly for 1.8.

If you try to run Giteas integration test suite with lfs switched off it will currently fail.

I think there's a few other versions that I test for in the pr.

There's another slight efficiency change in that we won't get tags when doing pr merges and branch name conflicts are also now completely prevented during merges too.

**Comment by guillep2k** [comment]
@zeripath Sorry, I was looking for something more specific, like whether a specific breaking changes in git or so. For example, I see the usage of "git remove" vs. "git rm" is one of them. But now I realize my question was kinda silly. 😄

**Comment by zeripath** [comment]
No worries. It was a very boring PR finding when each option was added and if git required the option to be not present if it wasn't supported

(For example git fetch --no-tags seems to be simply ignored by gits too old to have that support.)

**Comment by zeripath** [comment]
The more interesting things are in services/pull/merge.go and that's where the potential breakages are. I will take another look at those tomorrow myself.

File: services/pull/merge.go [hunk 3]
```diff
@@ -91,25 +89,41 @@ func Merge(pr *models.PullRequest, doer *models.User, baseGitRepo *git.Repositor
...
 		return fmt.Errorf("addCacheRepo [%s -> %s]: %v", headRepoPath, tmpBasePath, err)
 	}
 
 	var errbuf strings.Builder
+	if err := git.NewCommand("remote", "add", "-t", pr.BaseBranch, "-m", pr.BaseBranch, "origin", baseGitRepo.Path).RunInDirPipeline(tmpBasePath, nil, &errbuf); err != nil {
+		return fmt.Errorf("git remote add [%s -> %s]: %s", baseGitRepo.Path, tmpBasePath, errbuf.String())
+	}
+
+	if err := git.NewCommand("fetch", "origin", "--no-tags", pr.BaseBranch+":"+baseBranch, pr.BaseBranch+":original_"+baseBranch).RunInDirPipeline(tmpBasePath, nil, &errbuf); err != nil {
+		return fmt.Errorf("git fetch [%s -> %s]: %s", headRepoPath, tmpBasePath, errbuf.String())
```
Comment (guillep2k) [inline services/pull/merge.go:102]: The previous repository at `tmpBasePath` should be deleted.

File: services/pull/merge.go [hunk 4]
```diff
@@ -91,25 +89,41 @@ func Merge(pr *models.PullRequest, doer *models.User, baseGitRepo *git.Repositor
...
+	}
+
+	if err := git.NewCommand("symbolic-ref", "HEAD", git.BranchPrefix+baseBranch).RunInDirPipeline(tmpBasePath, nil, &errbuf); err != nil {
+		return fmt.Errorf("git symbolic-ref HEAD base [%s]: %s", tmpBasePath, errbuf.String())
```
Comment (guillep2k) [inline services/pull/merge.go:106]: Here both temp repositories should be deleted.

File: services/pull/merge.go [hunk 5]
```diff
@@ -91,25 +89,41 @@ func Merge(pr *models.PullRequest, doer *models.User, baseGitRepo *git.Repositor
...
+	}
+
+	if err := addCacheRepo(tmpBasePath, headRepoPath); err != nil {
+		return fmt.Errorf("addCacheRepo [%s -> %s]: %v", headRepoPath, tmpBasePath, err)
```
Comment (guillep2k) [inline services/pull/merge.go:110]: And here.

File: services/pull/merge.go [hunk 6]
```diff
@@ -91,25 +89,41 @@ func Merge(pr *models.PullRequest, doer *models.User, baseGitRepo *git.Repositor
...
+	}
+
 	if err := git.NewCommand("remote", "add", remoteRepoName, headRepoPath).RunInDirPipeline(tmpBasePath, nil, &errbuf); err != nil {
 		return fmt.Errorf("git remote add [%s -> %s]: %s", headRepoPath, tmpBasePath, errbuf.String())
```
Comment (guillep2k) [inline services/pull/merge.go:114]: I guess this wasn't even contemplated in the previous code.

File: services/pull/merge.go [hunk 7]
```diff
@@ -91,25 +89,41 @@ func Merge(pr *models.PullRequest, doer *models.User, baseGitRepo *git.Repositor
...
 	}
 
+	trackingBranch := "tracking"
 	// Fetch head branch
-	if err := git.NewCommand("fetch", remoteRepoName, fmt.Sprintf("%s:refs/remotes/%s/%s", pr.HeadBranch, remoteRepoName, pr.HeadBranch)).RunInDirPipeline(tmpBasePath, nil, &errbuf); err != nil {
+	if err := git.NewCommand("fetch", "--no-tags", remoteRepoName, pr.HeadBranch+":"+trackingBranch).RunInDirPipeline(tmpBasePath, nil, &errbuf); err != nil {
```
Comment (guillep2k) [inline services/pull/merge.go:119]: [A notice](https://docs.gitea.io/en-us/#system-requirements) has ben added to Gitea docs stating a minimum git version of 1.7.2. Perhaps you shouldn't worry much about `--no-tags`, which has been there [at least since 1.5.4](https://git-scm.com/docs/git-fetch/1.5.4). 😉 

Or perhaps, after this PR is merged, you'd like to revise the minimum git version requirement.

Comment (zeripath) [reply services/pull/merge.go:119]: This isn't testing the existence of no tags it's just using it. I think I got confused in general about when it arrived in my comment earlier. (It's been a while since I wrote this code.)

File: modules/git/repo_tree.go [hunk 8]
```diff
@@ -78,20 +86,24 @@ func (repo *Repository) CommitTree(sig *Signature, tree *Tree, opts CommitTreeOp
 		cmd.AddArguments("-p", parent)
 	}
 
-	cmd.AddArguments("-m", opts.Message)
+	messageBytes := new(bytes.Buffer)
```
[the remark this answers is not in the document]
Comment (zeripath) [reply modules/git/repo_tree.go:89]: I think that's probably out of scope for this PR but you're right, there are numerous places (and bugs) where we're just assuming that people are using UTF-8. (Be that in code or commits.)

File: modules/repofiles/temp_repo.go [hunk 9]
```diff
@@ -328,14 +345,26 @@ func (t *TemporaryUploadRepository) DiffIndex() (diff *gitdiff.Diff, err error)
 
 // CheckAttribute checks the given attribute of the provided files
 func (t *TemporaryUploadRepository) CheckAttribute(attribute string, args ...string) (map[string]map[string]string, error) {
+	binVersion, err := git.BinVersion()
+	if err != nil {
+		log.Fatal("Error retrieving git version: %v", err)
```
[the remark this answers is not in the document]
Comment (zeripath) [reply modules/repofiles/temp_repo.go]: It's not only a panic but an os.Exit().

Not sure why I did that...

[the remark this answers is not in the document]
Comment (zeripath) [reply modules/repofiles/temp_repo.go]:
```suggestion
		log.Error("Error retrieving git version: %v", err)
		return nil, err
```

File: modules/repofiles/temp_repo.go [hunk 10]
```diff
@@ -328,14 +345,26 @@ func (t *TemporaryUploadRepository) DiffIndex() (diff *gitdiff.Diff, err error)
...
 	timeout := 5 * time.Minute
 	ctx, cancel := context.WithTimeout(context.Background(), timeout)
 	defer cancel()
 
-	cmdArgs := []string{"check-attr", "-z", attribute, "--cached", "--"}
+	cmdArgs := []string{"check-attr", "-z", attribute}
+
+	// git check-attr --cached first appears in git 1.8.0
+	if version.Compare(binVersion, "1.8.0", ">=") {
+		cmdArgs = append(cmdArgs, "--cached")
```
[the remark this answers is not in the document]
Comment (zeripath) [reply modules/repofiles/temp_repo.go:365]: Hmm... I was looking at the docs... Let's trust the changelog.

File: modules/repofiles/update.go [hunk 11]
```diff
@@ -341,16 +335,23 @@ func CreateOrUpdateRepoFile(repo *models.Repository, doer *models.User, opts *Up
 	opts.Content = content
 	var lfsMetaObject *models.LFSMetaObject
 
-	if setting.LFS.StartServer && filename2attribute2info[treePath] != nil && filename2attribute2info[treePath]["filter"] == "lfs" {
-		// OK so we are supposed to LFS this data!
-		oid, err := models.GenerateLFSOid(strings.NewReader(opts.Content))
+	if setting.LFS.StartServer {
+		// Check there is no way this can return multiple infos
```
[the remark this answers is not in the document]
Comment (zeripath) [reply modules/repofiles/update.go:339]: It has been. Let me remove that comment.
```suggestion
```

File: modules/repofiles/temp_repo.go [hunk 12]
```diff
@@ -328,14 +345,26 @@ func (t *TemporaryUploadRepository) DiffIndex() (diff *gitdiff.Diff, err error)
...
 
 	timeout := 5 * time.Minute
 	ctx, cancel := context.WithTimeout(context.Background(), timeout)
 	defer cancel()
 
-	cmdArgs := []string{"check-attr", "-z", attribute, "--cached", "--"}
+	cmdArgs := []string{"check-attr", "-z", attribute}
+
+	// git check-attr --cached first appears in git 1.8.0
+	if version.Compare(binVersion, "1.8.0", ">=") {
```
Comment (zeripath) [inline modules/repofiles/temp_repo.go]:
```suggestion
	if version.Compare(binVersion, "1.7.8", ">=") {
```

File: services/pull/merge.go (hunk 3 above)
Comment (zeripath) [reply services/pull/merge.go]: We're still using the repo. This is not a new tmp repo

Comment (zeripath) [reply services/pull/merge.go:102]: See line 62 the defer function does that for us.

File: services/pull/merge.go (hunk 4 above)
Comment (zeripath) [reply services/pull/merge.go:106]: See line 62 the defer function does that for us

File: services/pull/merge.go (hunk 5 above)
Comment (zeripath) [reply services/pull/merge.go:110]: See line 62 the defer function does that for us

File: services/pull/merge.go (hunk 6 above)
Comment (zeripath) [reply services/pull/merge.go:114]: See line 62 the defer function does that for us

Comment (guillep2k) [reply services/pull/merge.go:114]: Ha ha, I missed that alright. 😆

File: modules/repofiles/temp_repo.go [hunk 13]
```diff
@@ -328,14 +345,27 @@ func (t *TemporaryUploadRepository) DiffIndex() (diff *gitdiff.Diff, err error)
...
 	stdErr := new(bytes.Buffer)
 
 	timeout := 5 * time.Minute
 	ctx, cancel := context.WithTimeout(context.Background(), timeout)
 	defer cancel()
 
-	cmdArgs := []string{"check-attr", "-z", attribute, "--cached", "--"}
+	cmdArgs := []string{"check-attr", "-z", attribute}
+
+	// git check-attr --cached first appears in git 1.8.0
```
Comment (guillep2k) [inline modules/repofiles/temp_repo.go]: Hum... the comment became outdated

Comment (zeripath) [reply modules/repofiles/temp_repo.go]:
```suggestion
	// git check-attr --cached first appears in git 1.7.8
```

**Review by guillep2k — APPROVED** [review]

File: integrations/git_helper_for_declarative_test.go [hunk 14]
```diff
@@ -37,7 +39,12 @@ func withKeyFile(t *testing.T, keyname string, callback func(string)) {
 	err = ssh.GenKeyPair(keyFile)
 	assert.NoError(t, err)
 
+	err = ioutil.WriteFile(path.Join(tmpDir, "ssh"), []byte("#!/bin/bash\n"+
```
Comment (lunny) [inline integrations/git_helper_for_declarative_test.go:42]: This will only run on Unix-like system? It didn't support windows.

Comment (zeripath) [reply integrations/git_helper_for_declarative_test.go:42]: This is only for running the integration tests on git version <2.3.0

On all other git versions GIT_SSH_COMMAND will override GIT_SSH - you aren't able to run the integration tests on git 2.2.0 currently anyway on any system.

It's worth remembering that git should also run in an bash like environment, so it could actually work even on doze.

However, have you been unable to run the integration tests on windows with this change? It shouldn't have caused that - I guess I could stick a git version check around this though to be more explicit about what the hell it's actually doing.

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work

**Comment by lafriks** [comment]
Please send backport
