### PR TITLE
Don't error when branch's commit doesn't exist

### LINKED ISSUE #19541: /api/v1/repos/${org}/${repo}/branches fails with HTTP 500 when branch is being deleted
### Description

/api/v1/repos/${org}/${repo}/branches returns HTTP 500 when a branch is being deleted at the same time.

Our gitea instance is setup to automatically delete PR branch after merge by default. We use jenkins for CI, and when jenkins receives the webhook it fetches the list of branches via the API. Sometimes (not always) that API call fails with a HTTP 500 error.

In the logs:

`2022/04/28 15:34:58 ...pi/v1/repo/branch.go:270:ListBranches() [E] GetCommit: object does not exist [id: refs/heads/ujpr01-patch-2, rel_path: ]
`

I tried reproducing it on try.gitea.io but did not succeed.

### Gitea Version

1.16.6

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

_No response_

### PR DESCRIPTION
**Pull request by Gusted**
- If one of the branches no longer exists, don't throw an error, it's possible that the branch was destroyed during the process. Simply skip it and disregard it.
- Resolves #19541

### CODE REVIEW

File: routers/api/v1/repo/branch.go [hunk 1]
```diff
@@ -260,22 +260,29 @@ func ListBranches(ctx *context.APIContext) {
 	}
 
 	apiBranches := make([]*api.Branch, len(branches))
```
Comment (6543) [inline routers/api/v1/repo/branch.go]:
```suggestion
	apiBranches := make([]*api.Branch, 0, len(branches))
```
so you wont have `""` in your list if you skip one

Comment (Gusted) [reply routers/api/v1/repo/branch.go]: https://github.com/go-gitea/gitea/pull/19547/commits/949c848f9db4278c6e7b7b8b3b801d58cb7dfb6d one step ahead of you 😄

Comment (6543) [reply routers/api/v1/repo/branch.go]: I still think we should add this patch too

Comment (Gusted) [reply routers/api/v1/repo/branch.go]: Why? It doesn't add any value after that commit.

Comment (6543) [reply routers/api/v1/repo/branch.go]: since it's a pointer I think it's ok ... - if it would be []string - I would prefere that (asuming go dont init it fully here)

**Review by 6543 — APPROVED** [review]

**Review by lunny — APPROVED** [review]

File: routers/api/v1/repo/branch.go (hunk 1 above)
Comment (Gusted) [reply routers/api/v1/repo/branch.go]: Used it anyway, allows for shorter code.
