### PR TITLE
when using rules to delete packages, remove unclean bugs

### LINKED ISSUE #31961: Package Retention don't delete all version
### Description

I have a package (container-images) with 1805 versions uploaded to gitea.
I discovered, that not all versions are deleted.
So I tested the cleanup-regexes against the not deleted versions - short answer the regex is correct.

I turned on Debug-Logging and there is no matching log-entry logged, that those versions will be kept.

In the source code I discovered that in the cleanup job only the first 200 versions of each package are loaded.
So the regex is only applied to to those first 200 versions.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Ubuntu-Server 22.04.4 LTS

### How are you running Gitea?

Gitea is running from docker. The image is gitea/gitea:1.22.1-rootless.

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by anthony-zh**
By default, the code extracts 200 package versions. If too many packages are generated every day or if rule cleaning is enabled later, which means there are more than 200 versions corresponding to the library package, it may not be cleaned up completely, resulting in residue

Fix #31961

### CODE REVIEW

**Comment by lunny** [comment]
Please add some tests

**Review by lunny — APPROVED** [review]

**Review by hiifong — APPROVED** [review]

File: services/packages/cleanup/cleanup.go [hunk 1]
```diff
@@ -33,13 +33,7 @@ func CleanupTask(ctx context.Context, olderThan time.Duration) error {
...
 
 func ExecuteCleanupRules(outerCtx context.Context) error {
-	ctx, committer, err := db.TxContext(outerCtx)
-	if err != nil {
-		return err
-	}
-	defer committer.Close()
-
-	err = packages_model.IterateEnabledCleanupRules(ctx, func(ctx context.Context, pcr *packages_model.PackageCleanupRule) error {
+	return packages_model.IterateEnabledCleanupRules(outerCtx, func(ctx context.Context, pcr *packages_model.PackageCleanupRule) error {
```
Comment (wxiaoguang) [inline services/packages/cleanup/cleanup.go]: Why the `db.TxContext` is removed? `outerCtx` seems to be a bug

File: models/packages/package_version.go [hunk 2]
```diff
@@ -291,14 +291,14 @@ func SearchVersions(ctx context.Context, opts *PackageSearchOptions) ([]*Package
...
 		sess = db.SetSessionPagination(sess, opts)
+		count, err := sess.FindAndCount(&pvs)
+		return pvs, count, err
 	}
-
-	pvs := make([]*PackageVersion, 0, 10)
-	count, err := sess.FindAndCount(&pvs)
-	return pvs, count, err
+	err := sess.Find(&pvs)
+	return pvs, int64(len(pvs)), err
```
Comment (wxiaoguang) [inline models/packages/package_version.go:295]: Why the behavior is changed? The root problem is how we should treat the "count": does it have a clear meaning like "the total count in database"?

Comment (lunny) [reply models/packages/package_version.go:295]: If there is no pagination, this will avoid a database select count query because the count is equal to the length of pvs.

File: services/packages/cleanup/cleanup.go (hunk 1 above)
Comment (lunny) [reply services/packages/cleanup/cleanup.go]: Removing the transaction allows partial cleanup to succeed. In the previous implementation, the entire cleanup process would either fully succeed or completely fail.

Comment (wxiaoguang) [reply services/packages/cleanup/cleanup.go]: Why completely remove, at least, the transaction should be applied to single package?

File: models/packages/package_version.go (hunk 2 above)
Comment (wxiaoguang) [reply models/packages/package_version.go:295]: **does it have a clear meaning like "the total count in database"?**

Does `int64(len(pvs))` makes senses or is it used?

I don't understand why the returned `count` sometimes can be "the total count in database" while sometimes can be "the length of the slice"

Comment (wxiaoguang) [reply models/packages/package_version.go:295]: Hmm, I see I misunderstood.

File: services/packages/cleanup/cleanup.go (hunk 1 above)
Comment (wxiaoguang) [reply services/packages/cleanup/cleanup.go]: https://github.com/go-gitea/gitea/pull/34632/commits/fb79731d957e4d4004e1b36be5189defd8397885

File: services/packages/cleanup/cleanup.go [hunk 3]
```diff
@@ -32,127 +32,136 @@ func CleanupTask(ctx context.Context, olderThan time.Duration) error {
...
+			log.Debug("Rule[%d]: keep '%s/%s' (remove days) %v", pcr.ID, p.Name, pv.Version, pv.CreatedUnix.FormatDate())
+			continue
 		}
+		if pcr.RemovePatternMatcher != nil && !pcr.RemovePatternMatcher.MatchString(toMatch) {
+			log.Debug("Rule[%d]: keep '%s/%s' (remove pattern)", pcr.ID, p.Name, pv.Version)
+			continue
+		}
+		log.Debug("Rule[%d]: remove '%s/%s'", pcr.ID, p.Name, pv.Version)
+		if err := packages_service.DeletePackageVersionAndReferences(ctx, pv); err != nil {
+			log.Error("CleanupRule [%d]: DeletePackageVersionAndReferences failed: %w", pcr.ID, err)
```
Comment (wxiaoguang) [inline services/packages/cleanup/cleanup.go]:
```suggestion
			log.Error("CleanupRule [%d]: DeletePackageVersionAndReferences failed: %v", pcr.ID, err)
```
