### PR TITLE
Fix raw wiki links

### LINKED ISSUE #31395: Regression - 1.22 wiki links which contain dots point to "raw" media and only return plain text
### Description

**Steps to reproduce**

1. Create a wiki page with a hyphen `-` or a dot `.` in the name
2. Link to that page from another wiki page

**Result**

Clicking on the link will only return a plain text representation of the linked wiki page's content.

**Expected Result**

The whole wiki page html should be returned

**Additional info**

This was working in gitea 1.21.8.

The auto-generated URLs for the wiki pages with a hyphen end in `.-` and the ones for wiki pages with a `.` contain the dot.

I assume that [this change](https://github.com/go-gitea/gitea/pull/30273) caused the problem.

**Example project with wiki**

https://demo.gitea.com/reimer-atb/test/wiki/Home

**Example markdown with links that do not work**

```
Welcome to the Wiki.

- [Test](Test) => works
- [Test with spaces](Test-with-spaces) => works
- [Test-with-hyphen](Test-with-hyphen.-) => does **not** work
- [Test+with+spaces+2024-06-17.-](Test+with+spaces+2024-06-17.-) => does **not** work
- [2024-06-17](2024-06-17.-) => does **not** work
- [17-06-2024](17-06-2024.-) => does **not** work
- [17.06.2024](17.06.2024) => does **not** work
- [06/17/2024](06%2F17%2F2024) => works
- [17/06/2024](17%2F06%2F2024) => works
```

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Tested on demo.gitea.com and on a private gitea 1.22.0 instance (no idea how that is run because it is provided by someone else).

### Database

None

### PR DESCRIPTION
**Pull request by Zettat123**
Fix #31395

This regression is introduced by #30273. To find out how GitHub handles this case, I did [some tests](https://github.com/go-gitea/gitea/issues/31395#issuecomment-2278929115). 

I use redirect in this PR instead of checking if the corresponding `.md` file exists when rendering the link because GitHub also uses redirect. With this PR, there is no need to resolve the raw wiki link when rendering a wiki page. If a wiki link points to a raw file, access will be redirected to the raw link.

### CODE REVIEW

File: routers/web/repo/wiki.go [hunk 1]
```diff
@@ -215,18 +238,30 @@ func renderViewPage(ctx *context.Context) (*git.Repository, *git.TreeEntry) {
...
 
-	// lookup filename in wiki - get filecontent, gitTree entry , real filename
-	data, entry, pageFilename, noEntry := wikiContentsByName(ctx, commit, pageName)
+	// lookup filename in wiki - get gitTree entry , real filename
+	entry, pageFilename, noEntry, isRaw := wikiEntryByName(ctx, commit, pageName)
 	if noEntry {
 		ctx.Redirect(ctx.Repo.RepoLink + "/wiki/?action=_pages")
 	}
+	if isRaw {
+		ctx.Redirect(util.URLJoin(ctx.Repo.RepoLink, "wiki/raw", string(pageName)))
```
Comment (lunny) [inline routers/web/repo/wiki.go:247]: return? And also line 244.

Comment (Zettat123) [reply routers/web/repo/wiki.go:247]: These two `ctx.Redirect` can be handled by the `if` statement on line 249

**Review by lunny — APPROVED** [review]

**Review by wolfogre — APPROVED** [review]
