### PR TITLE
Ignore force pushes for changed files in a PR review

### LINKED ISSUE #34832: Internal server error when viewing a pull request while logged in
### Description

We hit a 500 Internal Server Error when viewing a pull request while one user is logged in. The same pull request is viewable for other users or when the user logs out of gitea.

I found this message in gitea.log:

2025/06/24 16:28:52 services/gitdiff/gitdiff.go:1361:SyncUserSpecificDiff() [E] Could not get changed files between e6b6c01d0dc37b0e52b20cb558f967219f3c07be and 284cc007c63d1a560da9dfd3cd7d62f5e5fc3121 for pull request 258 in repo with path .../repo.git. Assuming no changes. Error: %!w(*git.runStdError=&{0xc00e8af470 fatal: bad object e6b6c01d0dc37b0e52b20cb558f967219f3c07be

With some study of the repo, it appears that this pull request has been force-pushed, and commit e6b6c01 has been removed by the garbage collection.

Cross checking with pull.go, I think this may be where the problem lies: the call to SyncUserSpecificDiff() failed because of the non-existent commit, and the code just throws a ServerError(). (I'm not familiar with the code base, but the comment seems to match the symptom we are observing)

        // if we're not logged in or only a single commit (or commit range) is shown we
        // have to load only the diff and not get the viewed information
        // as the viewed information is designed to be loaded only on latest PR
        // diff and if you're signed in.
        var reviewState *pull_model.ReviewState
        if ctx.IsSigned && !willShowSpecifiedCommit && !willShowSpecifiedCommitRange {
                reviewState, err = gitdiff.SyncUserSpecificDiff(ctx, ctx.Doer.ID, pull, gitRepo, diff, diffOptions)
                if err != nil {
                        ctx.ServerError("SyncUserSpecificDiff", err)
                        return
                }
        }

### Gitea Version

1.24.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.42.0.345.gaab89be2eb.dirty

### Operating System

Rocky Linux release 8.10

### How are you running Gitea?

We run the prebuilt binary directly on the operating system without containers.

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by delvh**
Fixes #34832

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Should we also change `return review, err` to `return review, nil`? I think the `err` should only be used when it is generated.

At the point of last "return", it is uncertain where the `err` is from.

**Review by wxiaoguang — APPROVED** [review]

File: services/gitdiff/gitdiff.go [hunk 1]
```diff
@@ -1356,6 +1356,7 @@ func SyncUserSpecificDiff(ctx context.Context, userID int64, pull *issues_model.
 	// But as that does not work for all potential errors, we simply mark all files as unchanged and drop the error which always works, even if not as good as possible
 	if err != nil {
 		log.Error("Could not get changed files between %s and %s for pull request %d in repo with path %s. Assuming no changes. Error: %w", review.CommitSHA, latestCommit, pull.Index, gitRepo.Path, err)
+		err = nil
```
Comment (wxiaoguang) [inline services/gitdiff/gitdiff.go]:
```suggestion
		err = nil //nolint
```

**Review by hiifong — APPROVED** [review]

**Comment by silverwind** [comment]
BTW I strongly recommend to not place bare `//nolint` statements. always include which linter to disable:

```
//nolint:ineffassign
```

This has benefits of targeting exactly one linter instead of all because multiple linters could trigger on the same line, and you likely only want to disable one of them.

We will later enforce this with the [`specific` option in `nolintlint`](https://github.com/ashanbrown/nolintlint#flags).

**Comment by TheFox0x7** [comment]
got a bit bored so I did it https://github.com/go-gitea/gitea/pull/34851
