### PR TITLE
Only hide dropzone when no files have been uploaded

### LINKED ISSUE #35125: Issue templates with multiple textareas have multiple file upload fields that can disappear
### Description

When a issue template has multiple textareas, each of them have their own area for uploading files. However, once you click away from one of the textareas, the file upload field disappears.

Steps to reproduce:
- Deploy a Gitea instance
- Create a repository on your Gitea instance
- In your repository in the directory `.gitea/issue_template/` add this yaml file (you will need to rename it from `.txt` to `.yaml`): [test_template.txt](https://github.com/user-attachments/files/21326733/test_template.txt)
- Now in the `Issues` section of your repository, create a new issue and select the template we added in the previous step.
  - This template can be accessed on your demo site [here](https://gitea.com/Alaska-001/Bug-report-template-test/issues/new?template=.gitea%2fissue_template%2ftest_template.yaml), or on the Blender foundation's Gitea instance [here](https://projects.blender.org/Alaska/bug-report-testing/issues/new?template=.gitea%2fissue_template%2ftest_template.yaml)
- Notice there are two text area inputs. Upload a file to the first textarea. This works correctly.
- Now click on the second textarea and notice the file you previously uploaded disappears from the UI. This is unexpected, and I personally believe it's a bug.

### Screenshots

Here's a video demonstrating the issue on the demo website: https://github.com/user-attachments/assets/903ec6bc-68f8-425f-a6eb-109bd5a90e11

### Gitea Version

1.25+dev-301-g7413e8583d

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows

### Browser Version

Google Chrome 138.0.7204.97

### PR DESCRIPTION
**Pull request by bartvdbraak**
Instead of always hiding the dropzone when it's not active:
- hide it when when there are no uploaded files and it becomes inactive 
- don't hide it when there are uploaded files

Fixes #35125

### CODE REVIEW

File: web_src/js/features/repo-issue.ts [hunk 1]
```diff
@@ -542,7 +542,11 @@ function initIssueTemplateCommentEditors(commentForm: HTMLFormElement) {
       // deactivate all markdown editors
       showElem(commentForm.querySelectorAll('.combo-editor-dropzone .form-field-real'));
       hideElem(commentForm.querySelectorAll('.combo-editor-dropzone .combo-markdown-editor'));
-      hideElem(commentForm.querySelectorAll('.combo-editor-dropzone .form-field-dropzone'));
+      queryElems(commentForm, '.combo-editor-dropzone .form-field-dropzone', (dropzoneContainer) => {
+        const dropzone = dropzoneContainer.closest('.combo-editor-dropzone')?.querySelector('.dropzone');
+        const hasUploadedFiles = dropzone?.querySelector('.dz-preview') !== null;
```
Comment (wxiaoguang) [inline web_src/js/features/repo-issue.ts]: It is fragile (and doesn't work as it looks)

`null?.foo()` is always `undefined`. then `hasUploadedFiles` becomes `true` in this case.

And the `preview` also looks fragile.


-----

To avoid fragile selector-based logic, Dropzone has its own variable on the element, it can be used to correctly check whether there are uploaded files.

Image

Comment (bartvdbraak) [reply web_src/js/features/repo-issue.ts]: Fair point on the fragility and thanks for pointing me into the right direction!

Comment (bartvdbraak) [reply web_src/js/features/repo-issue.ts]: I have changed my implementation to be more in line with what you've suggested.

Let me know if there are still some issues.

File: web_src/js/features/repo-issue.ts [hunk 2]
```diff
@@ -542,7 +542,14 @@ function initIssueTemplateCommentEditors(commentForm: HTMLFormElement) {
       // deactivate all markdown editors
       showElem(commentForm.querySelectorAll('.combo-editor-dropzone .form-field-real'));
       hideElem(commentForm.querySelectorAll('.combo-editor-dropzone .combo-markdown-editor'));
-      hideElem(commentForm.querySelectorAll('.combo-editor-dropzone .form-field-dropzone'));
+      queryElems(commentForm, '.combo-editor-dropzone .form-field-dropzone', (dropzoneContainer) => {
+        const dropzoneEl = dropzoneContainer.closest<HTMLElement>('.combo-editor-dropzone')?.querySelector<HTMLElement>('.dropzone');
```
Comment (wxiaoguang) [inline web_src/js/features/repo-issue.ts]:
```suggestion
        const dropzoneEl = dropzoneContainer.closest<HTMLElement>('.combo-editor-dropzone').querySelector<HTMLElement>('.dropzone');
```

It is certain that `.combo-editor-dropzone` exists because this call is in `queryElems(commentForm, '.combo-editor-dropzone .form-field-dropzone'`

File: web_src/js/features/repo-issue.ts [hunk 3]
```diff
@@ -542,7 +542,14 @@ function initIssueTemplateCommentEditors(commentForm: HTMLFormElement) {
...
+        const dzInstance = dropzoneEl?.dropzone;
+
+        if (dzInstance && dzInstance.files.length === 0) {
+          hideElem(dropzoneContainer);
+        }
```
Comment (wxiaoguang) [inline web_src/js/features/repo-issue.ts]:
```suggestion
        const hasUploadedFiles = Boolean(dzInstance?.files.length);
        toggleElem(dropzoneContainer, hasUploadedFiles);
```

File: web_src/js/features/repo-issue.ts [hunk 4]
```diff
@@ -542,7 +542,12 @@ function initIssueTemplateCommentEditors(commentForm: HTMLFormElement) {
       // deactivate all markdown editors
       showElem(commentForm.querySelectorAll('.combo-editor-dropzone .form-field-real'));
       hideElem(commentForm.querySelectorAll('.combo-editor-dropzone .combo-markdown-editor'));
-      hideElem(commentForm.querySelectorAll('.combo-editor-dropzone .form-field-dropzone'));
+      queryElems(commentForm, '.combo-editor-dropzone .form-field-dropzone', (dropzoneContainer) => {
+        const dropzoneEl = dropzoneContainer.closest<HTMLElement>('.combo-editor-dropzone').querySelector<HTMLElement>('.dropzone');
+        const dzInstance = dropzoneEl?.dropzone;
+        const hasUploadedFiles = Boolean(dzInstance?.files.length);
+        toggleElem(dropzoneContainer, hasUploadedFiles);
```
Comment (wxiaoguang) [inline web_src/js/features/repo-issue.ts]:
```suggestion
        // if "form-field-dropzone" exists, then "dropzone" must also exist
        const dropzone = dropzoneContainer.querySelector('.dropzone').dropzone;
        const hasUploadedFiles = dropzone.files.length !== 0;
        toggleElem(dropzoneContainer, hasUploadedFiles);
```

File: web_src/js/features/repo-issue.ts [hunk 5]
```diff
@@ -542,7 +542,12 @@ function initIssueTemplateCommentEditors(commentForm: HTMLFormElement) {
       // deactivate all markdown editors
       showElem(commentForm.querySelectorAll('.combo-editor-dropzone .form-field-real'));
       hideElem(commentForm.querySelectorAll('.combo-editor-dropzone .combo-markdown-editor'));
-      hideElem(commentForm.querySelectorAll('.combo-editor-dropzone .form-field-dropzone'));
+      queryElems(commentForm, '.combo-editor-dropzone .form-field-dropzone', (dropzoneContainer) => {
+        // if "form-field-dropzone" exists, then "dropzone" must also exist
+        const dropzone = dropzoneContainer.querySelector('.dropzone').dropzone;
```
Comment (wxiaoguang) [inline web_src/js/features/repo-issue.ts]:
```suggestion
        const dropzone = dropzoneContainer.querySelector<HTMLElement>('.dropzone').dropzone;
```

**Review by wxiaoguang — COMMENTED** [review]
Made some changes via GitHub online editor.

I think we do not need to tolerate "null/undefined" for this case: if ".form-field-dropzone" exists, then ".dropzone" must exists, then "el.dropzone" must exist. If any of them doesn't exist, there must be something (more serious) wrong.

**Comment by silverwind** [comment]
Yeah, it's better to let the code crash than to hide bugs with `?.` etc. In the first case we may get a bug report. In the second, it silently fails to work.

**Comment by bartvdbraak** [comment]
> Made some changes via GitHub online editor.
> 
> 
> 
> I think we do not need to tolerate "null/undefined" for this case: if ".form-field-dropzone" exists, then ".dropzone" must exists, then "el.dropzone" must exist. If any of them doesn't exist, there must be something (more serious) wrong.

Are there any changes that still need to be made here?

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Review by delvh — APPROVED** [review]
