### PR TITLE
Fix v220 migration to be compatible for MSSQL 2008 r2

### LINKED ISSUE #20615: Migration 220 fails against MSSQL 2008R2 SP3 database
### Description

When upgrading to 1.17, the process failed.

### Gitea Version

1.17

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows 10

### How are you running Gitea?

On windows 10 as a service.  Using MSSQL 2008R2 SP3 for the database.  this is the minimum supported version according to the configuration | databases section of https://docs.gitea.io/en-us/   however CONCAT isn't supported by MSSQL till version 2016 I think.

```
2022/08/02 14:30:05 cmd/web.go:160:runWeb() [I] PING DATABASE mssql
2022/08/02 14:30:05 ...ations/migrations.go:501:Migrate() [I] Migration[220]: Add container repository property
2022/08/02 14:30:05 routers/common/db.go:33:InitDBEngine() [E] ORM engine initialization attempt #7/10 failed. Error: migrate: migration[220]: Add container repository property failed: mssql: 'CONCAT' is not a recognized built-in function name.
2022/08/02 14:30:05 routers/common/db.go:34:InitDBEngine() [I] Backing off for 3 seconds
2022/08/02 14:30:08 routers/common/db.go:27:InitDBEngine() [I] ORM engine initialization attempt #8/10...
```

### Database

MSSQL

### PR DESCRIPTION
**Pull request by lunny**
Fix #20615

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@lunny lint fail

**Review by lafriks — APPROVED** [review]

**Review by delvh — APPROVED** [review]

File: models/migrations/v220.go [hunk 1]
```diff
@@ -12,18 +12,17 @@ import (
...
 	default:
-		_, err := x.Exec("INSERT INTO package_property (ref_type, ref_id, name, value) SELECT ?, p.id, ?, CONCAT(u.lower_name, '/', p.lower_name) FROM package p JOIN `user` u ON p.owner_id = u.id WHERE p.type = ?", packages_model.PropertyTypePackage, container_module.PropertyRepository, packages_model.TypeContainer)
-		if err != nil {
-			return err
-		}
+		_, err = x.Exec("INSERT INTO package_property (ref_type, ref_id, name, value) SELECT ?, p.id, ?, CONCAT(u.lower_name, '/', p.lower_name) FROM package p JOIN `user` u ON p.owner_id = u.id WHERE p.type = ?",
+			packages_model.PropertyTypePackage, container_module.PropertyRepository, packages_model.TypeContainer)
 	}
-	return nil
+	return
```
Comment (6543) [inline models/migrations/v220.go]:
```suggestion
	return err
```

**Comment by 6543** [comment]
.
