### PR TITLE
Prevent simultaneous editing of comments and issues

### LINKED ISSUE #22907: Simultaneous edits to an issue/PR lead to data loss
### Description

TL;DR: When two people edit an issue/PR description simultaneously, the last one to save "wins".

This scenario is not uncommon:
- User files a bug report.
- Developer sees the report, and wants to edit it to clarify some wording or clean up some markdown.
- User sees a typo, and edits the report.
- Developer knows the system, so is faster, and saves their edits first.
- User saves their typo fix
- Now all the edits done by the developer are reverted by the edit from the user.

This problem is quite serious, because:
1. There is nothing at all that warns about overwriting someone else's changes.
2. There are no historical comments "user X changed the description".
3. There is no way to see the history of description changes.

So not only is there data loss, it remains undetected until someone revisits the page and actually notices their work is gone.

A possible first step could be to use an [etag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) to detect simultaneous edits. Then at least a user can be warned that they'll overwrite someone else's changes.

It would be better to have some way to merge those changes, but that's a whole different issue to solve. I think the most important is to prevent these losses; how to solve such collisions gracefully can be dealt with later.

### Gitea Version

00b18ab42fdd49a437249f57c0b9086fd0ee1d03

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Self-built from Git.

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by metiftikci**
fixes #22907 

Tested:
- [x] issue content edit
- [x] issue content change tasklist
- [x] pull request content edit
- [x] pull request change tasklist

issue-content-edit

### CODE REVIEW

File: models/issues/issue.go [hunk 1]
```diff
@@ -121,6 +123,7 @@ type Issue struct {
 	NumComments      int
 	Ref              string
 	PinOrder         int `xorm:"DEFAULT 0"`
+	Version          int `xorm:"NOT NULL DEFAULT 0"`
```
Comment (lunny) [inline models/issues/issue.go]: You can use an optimistic lock to do that.
https://xorm.io/docs/chapter-06/1.lock/

File: models/issues/issue_update.go [hunk 2]
```diff
@@ -235,7 +235,7 @@ func UpdateIssueAttachments(ctx context.Context, issueID int64, uuids []string)
 }
 
 // ChangeIssueContent changes issue content, as the given user.
-func ChangeIssueContent(ctx context.Context, issue *Issue, doer *user_model.User, content string) (err error) {
+func ChangeIssueContent(ctx context.Context, issue *Issue, doer *user_model.User, content string, version int) (err error) {
```
Comment (lunny) [inline models/issues/issue_update.go]: ~Why not just use `issue.Version` but adding a new parameter?~
Answer my question myself. The version should be stored in the HTML and back to the backend.

File: options/locale/locale_en-US.ini [hunk 3]
```diff
@@ -1443,6 +1443,7 @@ issues.new.clear_assignees = Clear assignees
 issues.new.no_assignees = No Assignees
 issues.new.no_reviewers = No reviewers
 issues.new.blocked_user = Cannot create issue because you are blocked by the repository owner.
+issues.edit.already_changed = Unable to change issue content because issue is already changed
```
Comment (metiftikci) [inline options/locale/locale_en-US.ini]: any suggestion on this message? this also shown on pull request page.

File: models/issues/issue.go (hunk 1 above)
Comment (metiftikci) [reply models/issues/issue.go]: done

File: web_src/js/features/repo-issue-edit.js [hunk 4]
```diff
@@ -121,14 +122,22 @@ async function onEditContent(event) {
...
       });
       for (const fileInput of dropzoneInst?.element.querySelectorAll('.files [name=files]')) params.append('files[]', fileInput.value);
 
       const response = await POST(editContentZone.getAttribute('data-update-url'), {data: params});
       const data = await response.json();
+      if (response.status === 400) {
+        showErrorToast(data.errorMessage);
+        return;
+      }
+      editContentZone.setAttribute('data-version', parseInt(version) + 1);
```
Comment (lunny) [inline web_src/js/features/repo-issue-edit.js]: Maybe we should get the new version from the response?

File: options/locale/locale_en-US.ini (hunk 3 above)
Comment (lunny) [reply options/locale/locale_en-US.ini]: Maybe have another locale for pull request?

File: web_src/js/features/repo-issue-edit.js (hunk 4 above)
Comment (metiftikci) [reply web_src/js/features/repo-issue-edit.js]: should refetch issue after update or just increment and send as response?

Comment (lunny) [reply web_src/js/features/repo-issue-edit.js]: I would like the latter.

File: models/issues/issue.go (hunk 1 above)
Comment (metiftikci) [reply models/issues/issue.go]: @lunny are we sure to use db/orm level versioning. Is not it too risky to handle correct version info for all operations like api calls, pr operations, and issue updates:  can not we use version column for only content change?

```go
func UpdateIssueCols(ctx context.Context, issue *Issue, cols ...string) error {
	affected, err := db.GetEngine(ctx).ID(issue.ID).Cols(cols...).Update(issue)
	if err != nil {
		return err
	}
	if affected == 0 {
		return ErrIssueAlreadyChanged
	}
	issue.Version++
	return nil
}
```

```go
	case CommentTypeComment:
		if _, err = db.Exec(ctx, "UPDATE `issue` SET num_comments=num_comments+1 WHERE id=?", opts.Issue.ID); err != nil {
			return err
		}
		opts.Issue.Version++
		fallthrough
```

```go
func repoStatsCorrectIssueNumComments(ctx context.Context, id int64) error {
	return StatsCorrectSQL(ctx, "UPDATE `issue` SET num_comments=(SELECT COUNT(*) FROM `comment` WHERE issue_id=? AND type=0) WHERE id=?", id)
}
```

```go
	if _, err := sess.Exec("UPDATE `issue` SET `repo_id` = `repo_id` WHERE `id` = ?", pr.IssueID); err != nil {
		return false, err
	}
```

File: options/locale/locale_en-US.ini (hunk 3 above)
Comment (metiftikci) [reply options/locale/locale_en-US.ini]: done

File: web_src/js/features/repo-issue-edit.js (hunk 4 above)
Comment (metiftikci) [reply web_src/js/features/repo-issue-edit.js]: done

File: models/issues/issue.go (hunk 1 above)
Comment (lunny) [reply models/issues/issue.go]: We can use `NoVersionCheck()` on `UpdateIssueCols`.
```db.GetEngine(ctx).ID(issue.ID).Cols(cols...).NoVersionCheck().Update(issue)```

Only `Update` function will check the version. For `db.Exec`, it will not check the previous version.

Comment (wxiaoguang) [reply models/issues/issue.go]: I do not think it's right to use XORM "version" here.

Otherwise, all issue-model code needs to call `NoVersionCheck`.

Actually, this PR's purpose is only to make "content" support version. And I think there are still many blocking problem, I will write a new comment.

**Comment by wxiaoguang** [comment]
Thank you for the feature! It is good for end users. However there are some blocking problems in my mind at the moment:

1. I do not think it's right to use XORM "version" here. Otherwise, all issue-model code needs to call NoVersionCheck again and again, and it might cause more breakings.
2. The comment content field is the same as issue content field, but comments are stored in another table.
    * Should we have a complete design before only "fixing" the issue?
3. The "version" is quite unclear and would mislead developers.
    * I can see the "version" is only for "content"
    * But there are still other fields like "title", which can be changed simultaneously
    * And there are still other "related models" like "labels", "assignees" can be changed simultaneously
    * So I do not think we should use "version" for "issue content"

**Comment by metiftikci** [comment]
@wxiaoguang thank you for review. do you have any suggestion? maybe a 'content hash' colum as @drsybren said? or any generic solution?

**Comment by wxiaoguang** [comment]
TBH I haven't thought about the details carefully.

Some brief ideas (just my opinion):

1. Use `ContentVersion`, add it for both `issue` and `comment` tables, and this field is only used for "content editing".
2. Re-use the "issue content history", use the last issue content history record as reference.
3. Hash (sha256) the issue/comment's content as reference.

For the frontend mechanism: I would strongly suggest to make it independent of backend and totally transparent (do not calculate "version+1" in frontend). It could use an abstracted variable like `data-content-version-tag`, and frontend code only gets it from backend and sends it back to backend, then frontend doesn't need to share any knowledge with backend, and all of these "ideas" above work with this mechanism.

**Comment by lunny** [comment]
> Thank you for the feature! It is good for end users. However there are some blocking problems in my mind at the moment:
> 
>     1. I do not think it's right to use XORM "version" here. Otherwise, all issue-model code needs to call NoVersionCheck again and again, and it might cause more breakings. (it is also related to point 3)
> 
>     2. The comment content field is the same as issue content field, but comments are stored in another table.
>        
>        * Should we have a complete design before only "fixing" the problem for "issue"?
> 
>     3. The "version" is quite unclear and would mislead developers.
>        
>        * I can see the "version" is only designed for "content"
>        * But there are still other fields like "title", which can be changed simultaneously
>        * And there are still other "related models" like "labels", "assignees" can be changed simultaneously
>        * So I do not think we should use "version" for "issue content"

I would agree since only content has the version, we should use a name like `content_version` column but not `version`. And looks like XORM based version will require careful changes in other places. Maybe just revert back to user-defined version. Sorry, @metiftikci .

But I don't think it's necessary to put `comment` content version changes in the same PR. Another PRs are better. Because most of the edit box needs column like this. i.e. comment, release note, user information, org information and etc.

**Comment by metiftikci** [comment]
@wxiaoguang changed `Version` to `ContentVersion` as int. Do i need to do something else? frontend gets new version number from backend

**Comment by wxiaoguang** [comment]
Overall it looks good to me. Thank you for the updates.

Actually, I still think we should make the "comment" also support "content version" in one PR: they share the same code, and I do not think it's worth to add another migration for "comment" table.

And one more thing, I think it's worth to write some test code to cover ChangeIssueContent's behavior.

**Comment by metiftikci** [comment]
@wxiaoguang added comment content version and some test but i am not familiar. waiting for any change request or suggestions

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by metiftikci** [comment]
@lunny i think fail is not related to pr, right ?

**Comment by lunny** [comment]
> @lunny i think fail is not related to pr, right ?

I think so. Let me restart the failed jobs.

**Comment by lunny** [comment]
Looks like the CI failures are related.

**Comment by metiftikci** [comment]
My bad. fixed migration. now looks like fixed

**Comment by wxiaoguang** [comment]
(ps: no need to merge with every main commit manually, maintainers and the Gitea bot will do that 😄 )
