### PR TITLE
Add migrations and doctor fixes

### LINKED ISSUE #33535: After upgrading Gitea to the latest version, the actions secrets are lost
### Description

After upgrading Gitea to the latest version, the pipeline keys are lost, but the database records are still present.

### Gitea Version

1.23.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

Image

Image

Image

Image

Image

 The screenshots show my YAML configuration and the historical execution records, which were working fine before the upgrade. After the upgrade, I found that the environment variables are missing, so I manually added one. Finally, there is a screenshot of the database.

### Git Version

_No response_

### Operating System

docker

### How are you running Gitea?

docker compose

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by lunny**
Fix #33535

### CODE REVIEW

**Comment by wolfogre** [comment]
No, runners don't have this issue. I was talking about secrets.

**Comment by lunny** [comment]
It's ready to review.

**Review by Zettat123 — APPROVED** [review]

File: models/migrations/v1_24/v314.go [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+func UpdateOwnerIDOfRepoLevelRunners(x *xorm.Engine) error {
+	if _, err := x.Exec("UPDATE `action_runner` SET `owner_id` = 0 WHERE `repo_id` > 0 AND `owner_id` > 0"); err != nil {
+		return err
+	}
+	if _, err := x.Exec("UPDATE `action_runner` SET `owner_id` = 0 WHERE `repo_id` > 0 AND `owner_id` > 0"); err != nil {
+		return err
+	}
+	_, err := x.Exec("UPDATE `action_runner` SET `owner_id` = 0 WHERE `repo_id` > 0 AND `owner_id` > 0")
+	return err
+}
```
Comment (wxiaoguang) [inline models/migrations/v1_24/v314.go:19]: What are these?

image

Comment (lunny) [reply models/migrations/v1_24/v314.go:19]: :(
febad275f8

File: models/migrations/v1_24/v314.go [hunk 2]
```diff
@@ -0,0 +1,19 @@
+// Copyright 2025 The Gitea Authors. All rights reserved.
+// SPDX-License-Identifier: MIT
+
+package v1_24 //nolint
+
+import (
+	"xorm.io/xorm"
+)
+
+func UpdateOwnerIDOfRepoLevelRunners(x *xorm.Engine) error {
```
Comment (ChristopherHX) [inline models/migrations/v1_24/v314.go]: Maybe rename to UpdateOwnerIDOfRepoLevelActionsTables?

This name and migration description doesn't imply for me to make changes to action_variable / secret.

**Review by ChristopherHX — COMMENTED** [review]
Otherwise looks good to me

File: models/migrations/v1_24/v314.go (hunk 2 above)
Comment (lunny) [reply models/migrations/v1_24/v314.go]: 4bf5911d2c

File: services/doctor/dbconsistency.go [hunk 3]
```diff
@@ -164,6 +165,24 @@ func prepareDBConsistencyChecks() []consistencyCheck {
 			Fixer:        repo_model.DeleteOrphanedTopics,
 			FixedMessage: "Removed",
 		},
+		{
+			Name:         "Repository level Runners with non-zero owner_id",
+			Counter:      actions_model.CountWrongRepoLevelRunners,
+			Fixer:        actions_model.UpdateWrongRepoLevelRunners,
+			FixedMessage: "Corrected",
+		},
```
Comment (ChristopherHX) [inline services/doctor/dbconsistency.go:173]: I looked up some code, could the fixer of "Action Runners without existing owner" cause data loss in a theoretical scenario as it's precondition repo_id is null is only ensured after the fixer "Repository level Runners with non-zero owner_id" ran.
This scenario idk if its possible would be
- Defect in database CountWrongRepoLevelRunners > 1
- Owner moved repo to org
- Original owner deleted
- CountRunnersWithoutBelongingOwner > 1 (just a guess if I understand right)
- gitea doctor is ran
- UpdateWrongRepoLevelRunners deletes runner before the runner is fixed in the database

Anyways a complex scenario that came in my mind due to review comments of my artifact PR that the owner_id is not well maintained for artifact objects during repository move, if this did really ever happend just register a new runner

**Review by ChristopherHX — APPROVED** [review]

File: services/doctor/dbconsistency.go (hunk 3 above)
Comment (lunny) [reply services/doctor/dbconsistency.go:173]: That's why we need to update `owner` as 0 for repository level runners to avoid similar scenario occupied. The doctor running should be at non working period.
