### PR TITLE
Fix issue templates when blank isses are disabled

### LINKED ISSUE #27060: Can't use issue templates on 1.20.4
### Description

Issue templates do not work on 1.20.4. When creating a new issue, we're taken to the template picker. However, picking a template does not work; It puts the template path in the URL, but then reloads the template picker. We downgraded back to 1.20.3, and it started working again.

The end of the URL the button links to hasn't changed; Both versions link to `/<org>/<repo>/issues/new?template=<template-path>`. However, when attempting to request that URL, Gitea responds with a `303 See Other` to `/<org>/<repo>/issues/new/choose?template=<template-path>`.

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

Have not tried

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.41.0.windows-3

### Operating System

Windows Server 2022

### How are you running Gitea?

As a Windows service. To upgrade/downgrade, we stop the service, overwrite the executable, and restart it.

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by JakobDev**
Fixes #27060

### CODE REVIEW

File: routers/web/repo/issue.go [hunk 1]
```diff
@@ -896,20 +896,15 @@ func setTemplateIfExists(ctx *context.Context, ctxDataKey string, possibleFiles
 		ctx.Data["label_ids"] = strings.Join(labelIDs, ",")
 		ctx.Data["Reference"] = template.Ref
 		ctx.Data["RefEndName"] = git.RefName(template.Ref).ShortName()
-		return templateErrs
+		return true, templateErrs
 	}
-	return templateErrs
+	return false, templateErrs
 }
```
Comment (silverwind) [inline routers/web/repo/issue.go:903]: Looking at this function, I have no immediate idea what the bool indicates. I guess this is one case where either a named return or a comment above the function would be good.

**Review by silverwind — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

File: routers/web/repo/issue.go [hunk 2]
```diff
@@ -830,10 +830,11 @@ func RetrieveRepoMetas(ctx *context.Context, repo *repo_model.Repository, isPull
 	return labels
 }
 
-func setTemplateIfExists(ctx *context.Context, ctxDataKey string, possibleFiles []string) map[string]error {
+// Trys to load a template and sets it. The first return value indicate if a template was loaded.
```
Comment (delvh) [inline routers/web/repo/issue.go]:
```suggestion
// Tries to load and set an issue template. The first return value indicates if a template was loaded.
```

**Review by delvh — APPROVED** [review]
