### PR TITLE
[API] Fix 9544 | return 200 when reaction already exist

### LINKED ISSUE #9544: [Bug Report] Reactions API throws 500 for duplicate reaction
## Description

If we post a same reaction more than one time via reaction API, it will throw 500.

https://gitea.com/api/swagger#/issue/issuePostCommentReaction

`POST /repos/{owner}/{repo}/issues/comments/{id}/reactions`

FYI, GitHub returns `201` for created, and returns `200` for duplicated

cc @6543 

## Screenshots

**First Time (OK)**

image

**Second Time (ERROR)**

image

image

### PR DESCRIPTION
**Pull request by 6543**
fix #9544

### CODE REVIEW

File: models/error.go [hunk 1]
```diff
@@ -1201,6 +1201,21 @@ func (err ErrForbiddenIssueReaction) Error() string {
...
+}
+
+// IsErrReactionAlreadyExist checks if an error is a ErrReactionAlreadyExist.
+func IsErrReactionAlreadyExist(err error) bool {
+	_, ok := err.(ErrReactionAlreadyExist)
+	return ok
+}
+
+func (err ErrReactionAlreadyExist) Error() string {
+	return fmt.Sprintf("reaction '%s' already exist", err.Reaction)
```
Comment (zeripath) [inline models/error.go]:
```suggestion
	return fmt.Sprintf("reaction '%s' already exists", err.Reaction)
```

**Comment by zeripath** [comment]
Is StatusOK really right here ? - I would have thought StatusConflict would have been better? However, I think there's a place for putting a 200 here.

**Comment by 6543** [comment]
We can still decide wich status we return - github does it the 200 way [reverence: link](https://developer.github.com/v3/reactions/#create-reaction-for-a-commit-comment)

But this is also a smal code/refactor <- now we can explicit handle dubble add and filter/find reactions by more options

File: routers/api/v1/repo/issue_reaction.go [hunk 2]
```diff
@@ -188,19 +190,20 @@ func changeIssueCommentReaction(ctx *context.APIContext, form api.EditReactionOp
 		if err != nil {
 			if models.IsErrForbiddenIssueReaction(err) {
 				ctx.Error(http.StatusForbidden, err.Error(), err)
+			} else if models.IsErrReactionAlreadyExist(err) {
+				ctx.JSON(http.StatusOK, api.Reaction{
+					User:     ctx.User.APIFormat(),
```
Comment (zeripath) [inline routers/api/v1/repo/issue_reaction.go:195]: shouldn't this be the reaction.User?

Comment (6543) [reply routers/api/v1/repo/issue_reaction.go:195]: Its the same ..

Comment (6543) [reply routers/api/v1/repo/issue_reaction.go:195]: but if I use ctx.User I dont have to query the DB

Comment (zeripath) [reply routers/api/v1/repo/issue_reaction.go:195]: Oh yeah sorry

**Review by zeripath — APPROVED** [review]

File: models/issue_reaction_test.go [hunk 3]
```diff
@@ -50,9 +50,10 @@ func TestIssueAddDuplicateReaction(t *testing.T) {
 		Type:  "heart",
 	})
 	assert.Error(t, err)
-	assert.Nil(t, reaction)
+	assert.Equal(t, ErrReactionAlreadyExist{Reaction: "heart"}, err)
```
Comment (bagasme) [inline models/issue_reaction_test.go:53]: Why did you choose `heart` for this test?

File: routers/api/v1/repo/issue_reaction.go [hunk 4]
```diff
@@ -114,8 +114,10 @@ func PostIssueCommentReaction(ctx *context.APIContext, form api.EditReactionOpti
 	//   schema:
 	//     "$ref": "#/definitions/EditReactionOption"
 	// responses:
+	//   "200":
+	//     "$ref": "#/responses/Reaction"
 	//   "201":
-	//     "$ref": "#/responses/ReactionResponse"
+	//     "$ref": "#/responses/Reaction"
```
Comment (bagasme) [inline routers/api/v1/repo/issue_reaction.go:120]: Return both 200 and 201?

File: models/issue_reaction_test.go (hunk 3 above)
Comment (6543) [reply models/issue_reaction_test.go:53]: @bagasme because it is already used [Link](https://github.com/go-gitea/gitea/blob/master/models/issue_reaction_test.go#L50)

File: routers/api/v1/repo/issue_reaction.go (hunk 4 above)
Comment (6543) [reply routers/api/v1/repo/issue_reaction.go]: no this is jus the swagger definition wich tell us that this API **is expect** to return this *vaules*
so it tells the programmer make sure you handle StatusOK and StatusCreated

Comment (6543) [reply routers/api/v1/repo/issue_reaction.go:120]: @bagasme 
no this is jus the swagger definition wich tell us that this API **is expect** to return this *vaules*
so it tells the programmer make sure you handle StatusOK and StatusCreated

File: models/issue_reaction.go [hunk 5]
```diff
@@ -112,13 +136,13 @@ func CreateReaction(opts *ReactionOptions) (reaction *Reaction, err error) {
 
 	reaction, err = createReaction(sess, opts)
 	if err != nil {
-		return nil, err
+		return
```
Comment (lafriks) [inline models/issue_reaction.go]: I would prefer it the way it was and removing return variable names from func definition

Comment (6543) [reply models/issue_reaction.go]: done

File: models/issue_reaction.go [hunk 6]
```diff
@@ -99,23 +123,23 @@ type ReactionOptions struct {
...
-	if err = sess.Begin(); err != nil {
+	if err := sess.Begin(); err != nil {
 		return nil, err
 	}
 
-	reaction, err = createReaction(sess, opts)
+	reaction, err := createReaction(sess, opts)
 	if err != nil {
-		return nil, err
+		return reaction, err
```
Comment (6543) [inline models/issue_reaction.go:139]: to return reaction is importent ...

**Comment by 6543** [comment]
@lafriks done

**Review by techknowlogick — APPROVED** [review]

**Comment by 6543** [comment]
@techknowlogick ready for merge :rocket:

**Comment by 6543** [comment]
@techknowlogick since reaction api is not in 1.10.0 I only backported error handling
