### PR TITLE
Fix PR, milestone and label functionality if issue unit is disabled

### LINKED ISSUE #2447: Closing a PR fails (404 web page) if external issue tracker enabled, or no issue tracker enabled
- Gitea version (or commit ref): 1.2.0-rc1 (binary install)
- Git version: 2.11.0
- Operating system: Ubuntu Linux 16.04 amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

```
2017/09/01 11:47:16 [...ules/context/repo.go:527 func1()] [E] CheckUnit: You are not allowed to visit this repository unit: 2
```

## Description

* Start with a repository that is configured for no issue tracker, or an external issue tracker
* Create a PR
* Press the Close button on the PR page
* Result: 404 web page, and log message shown above
* PR is not removed

The problem does not appear if the builtin issue tracker is enabled.  In fact, to close the PR I can:

* Change to the builtin issue tracker
* Go close the PR
* Return to original issue settings (either no issue tracker, or external issue tracker)

Thanks!

### PR DESCRIPTION
**Pull request by lafriks**
Fix PR, milestone and label functionality if issue unit is disabled or not available for user

Fixes #2447

### CODE REVIEW

**Review by ethantkoenig — APPROVED** [review]

**Comment by ethantkoenig** [comment]
LGTM

File: routers/repo/issue.go [hunk 1]
```diff
@@ -720,11 +720,16 @@ func ViewIssue(ctx *context.Context) {
...
-			ctx.Error(404, "GetIssueByIndex")
-		} else {
-			ctx.Handle(500, "GetIssueByIndex", err)
-		}
+		ctx.NotFoundOrServerError("GetIssueByIndex", models.IsErrIssueNotExist, err)
+		return nil
+	}
+	if issue.IsPull && !ctx.Repo.Repository.UnitEnabled(models.UnitTypePullRequests) ||
+		!issue.IsPull && !ctx.Repo.Repository.UnitEnabled(models.UnitTypeIssues) {
+		ctx.Handle(404, "UnitEnabled", nil)
```
Comment (daviian) [inline routers/repo/issue.go]: Error message should be UnitDisabled

**Review by daviian — CHANGES_REQUESTED** [review]

File: routers/repo/issue.go (hunk 1 above)
Comment (lafriks) [reply routers/repo/issue.go]: @daviian no, there should be function name that returned error so that from log entries it would be possible to understand what happened

Comment (daviian) [reply routers/repo/issue.go]: From that point of view yes, but it is confusing at the first moment.

Comment (lafriks) [reply routers/repo/issue.go]: That is how it is used in rest of the code :)

Comment (daviian) [reply routers/repo/issue.go]: @lafriks However in this case the UnitEnabled doesn't even return an error and 404 happens if the required unit is not enabled.

**Comment by lafriks** [comment]
@daviian updated ;)

**Review by daviian — APPROVED** [review]

**Comment by daviian** [comment]
@lafriks Update and delete on comments in PR without issue tracker don't work either.

**Comment by lafriks** [comment]
@daviian fixed

**Comment by daviian** [comment]
LGTM

**Comment by lafriks** [comment]
Make LG-TM work again
