### PR TITLE
Fix user settings sidebar showing disabled features on some pages

### LINKED ISSUE #36954: User settings sidebar shows disabled features on some pages for external/LDAP users
### Description

  When an external user (e.g. LDAP/LLDAP) navigates to certain User Settings pages, sidebar menu items that should be hidden by `EXTERNAL_USER_DISABLE_FEATURES` (or `USER_DISABLED_FEATURES`) reappear.         
   
  For example, with this configuration:                                                                                                                                                                          
                                                                                                                                                                                                               
  ```ini                                                                                                                                                                                                         
  [admin]                                                                                                                                                                                                      
  USER_DISABLED_FEATURES = deletion, manage_ssh_keys, manage_gpg_keys, manage_mfa, manage_credentials, change_username, change_full_name
  EXTERNAL_USER_DISABLE_FEATURES = deletion, manage_ssh_keys, manage_gpg_keys, manage_mfa, manage_credentials, change_username, change_full_name                                                                 
  ```                                                                                                                                                                                                               
  ## Steps to Reproduce                                                                                                                                                                                             
                                                            
  1. Configure EXTERNAL_USER_DISABLE_FEATURES                                                                                                                      
  2. Log in as an external/LDAP user
  3. Go to User Settings -> Profile - "Account", "Security" and "SSH / GPG Keys" are hidden                                                                                                                            
  4. Click "Notifications" - "Account", "Security" and "SSH / GPG Keys" reappear

Navigating to those pages will give a 404 Not Found

### Gitea Version

main branch @ ae0bc02

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

<img width="258" height="353" alt="Image" src="https://github.com/user-attachments/assets/aaa31b51-f171-4654-bcb0-4cbfeff44ff4" />

<img width="1340" height="442" alt="Image" src="https://github.com/user-attachments/assets/1a458a6d-2588-4fe6-a757-286fed06b665" />

<img width="786" height="363" alt="Image" src="https://github.com/user-attachments/assets/0e78ee59-a9bb-4da4-a328-f824e91f3d0f" />

### Git Version

_No response_

### Operating System

Fedora 44

### How are you running Gitea?

Self-hosted, podman container based deployment

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by bircni**
Move UserDisabledFeatures context data into a shared SettingsCtxData middleware for the /user/settings route group, so it is set consistently on all pages (including Notifications, Actions, etc.) instead of only on the handlers that remembered to set it individually.

Fixes #36954

### CODE REVIEW

File: routers/web/web.go [hunk 1]
```diff
@@ -721,7 +721,7 @@ func registerWebRoutes(m *web.Router, webAuth *AuthMiddleware) {
 			m.Get("", user_setting.BlockedUsers)
 			m.Post("", web.Bind(forms.BlockUserForm{}), user_setting.BlockedUsersPost)
 		})
-	}, reqSignIn, ctxDataSet("PageIsUserSettings", true, "EnablePackages", setting.Packages.Enabled, "EnableNotifyMail", setting.Service.EnableNotifyMail))
+	}, reqSignIn, ctxDataSet("PageIsUserSettings", true, "EnablePackages", setting.Packages.Enabled, "EnableNotifyMail", setting.Service.EnableNotifyMail), user_setting.SettingsCtxData)
```
Comment (wxiaoguang) [inline routers/web/web.go]: `ctxDataSet("PageIsUserSettings", true, "EnablePackages", setting.Packages.Enabled, "EnableNotifyMail", setting.Service.EnableNotifyMail)` can also be merged into `SettingsCtxData`

Then "routes" init code will become simpler and clearer.

Comment (bircni) [reply routers/web/web.go]: done

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]
