### PR TITLE
Fix various ImageDiff/SVG bugs

### LINKED ISSUE #19733: Some files are recognized as SVG incorrectly, make the diff UI unable to work.
### Description

When certain conditions are met gitea can't display the `blade.php` file diff when viewing the commit. It only works when I click "View source button". Second link is taken from network, it is causing the crash.

https://try.gitea.io/stuzer05/test-preview/commit/f97b3784f8c8efc222128f6dffd4e5abb5fda462
https://try.gitea.io/stuzer05/test-preview/raw/commit/e2f752e123151fea55959571d56d57462025f0f6/test.blade.php

image

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker

### Database

_No response_

### PR DESCRIPTION
**Pull request by wxiaoguang**
Replace #23310, Close #19733

And fix various UI problems, including regressions from #22959 #22950 and more.

## SVG Detection

The old regexp may mismatch non-SVG files. This PR adds new tests for those cases.

### Before

image

image

### After

image

image

image

image

image

image

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by stuzer05** [comment]
This should also not be detected as svg
image

**Comment by wxiaoguang** [comment]
> This should also not be detected as svg

I agree, I just thought nobody would write such HTML code 🤣  so I just kept the regexp like before.

If you think it's a must, I can do more fine tune.

**Comment by wxiaoguang** [comment]
ps: you could even write:

```html
<svg>...</svg>
<svg>...</svg>
```

that's still invalid, but it's difficult to be processed by regexp .... we can not make a 100% perfect solution by regexp.

**Comment by stuzer05** [comment]
> > This should also not be detected as svg
> 
> I agree, I just thought nobody would write such HTML code rofl so I just kept the regexp like before.
> 
> If you think it's a must, I can do more fine tune.

I mean you can rename this file to `test.html` and gitea will still shink it's svg. If you would make it so svg file should always end with `</svg>` that would fix it

**Comment by stuzer05** [comment]
> ps: you could even write:

In this case you can count if data string contains only one occurance of `<svg\s?`

**Comment by wxiaoguang** [comment]
> > ps: you could even write:
> 
> In this case you can count if data string contains only one occurance of `<svg\s?`

I just think it's not necessary to make it so complex. Users could even write invalid SVG files to pass the checks, it's impossible to make it perfect without a standard SVG processor.

**Comment by stuzer05** [comment]
> I just think it's not necessary to make it so complex. Users could even write invalid SVG files to pass the checks, it's impossible to make it perfect without a standard SVG processor.

At least, let's cover basic html false-positives such as text after `</svg>text`

**Comment by wxiaoguang** [comment]
See https://github.com/go-gitea/gitea/pull/23312/commits/be77cb87c526cca882ce401570716984f761cc7c, I think that's good enough.

Even if a user provide strange SVG-like contents, they could still switch to `Source Code` mode to see the diff and original code. The UI is flex enough.

**Comment by stuzer05** [comment]
> See [be77cb8](https://github.com/go-gitea/gitea/commit/be77cb87c526cca882ce401570716984f761cc7c), I think that's good enough.

Maybe last check for `<svg` count = 1? I thing that's the last one needed to detect html false-positives

**Comment by wxiaoguang** [comment]
https://stackoverflow.com/questions/5451135/embed-svg-in-svg

Or you can actually embed child svg in parent svg like this:

```html
<svg>
    <g>
        <svg>
            ...
        </svg>
    </g>
</svg>
```

Do not try to use regexp tricks to parse HTML/XML .... 😁

**Comment by stuzer05** [comment]
> Or you can actually embed child svg in parent svg like this

Oh my.. :exploding_head: Let's display it html, this is just weird. Html is far more used than nested svgs

**Comment by wxiaoguang** [comment]
I have confidence that these changes are good enough (for 99.99% ?). At least, the button of "display as code" is always there. If you have some real cases which need to be handled, let's discuss them in the future with real project code.

File: web_src/js/features/imagediff.js [hunk 1]
```diff
@@ -255,13 +255,10 @@ export function initImageDiff() {
...
       });
+
       sizes.image2.parent().parent().css({
         width: sizes.max.width * factor + 2,
-        height: sizes.max.height * factor + 2
-      });
-      $container.find('.onion-skin').css({
-        width: sizes.max.width * factor + 2,
-        height: sizes.max.height * factor + 4
+        height: sizes.max.height * factor + 2 + 20,
```
Comment (delvh) [inline web_src/js/features/imagediff.js]: Where is this `+20` coming from?
This looks like a magic constant to me.
I mean, I can at least guess that the `+2` everywhere else is so that a `1px` border can be drawn, but this `+20`?

**Review by delvh — COMMENTED** [review]
I don't quite understand why we can't just say that svgs are only files that end with `.svg`?
How often do you create a php/html document that does nothing else than declare an SVG?
Why should we support that, if the user said themselves that it shouldn't be treated as an SVG?
Why this heuristics-based approach?

File: web_src/js/features/imagediff.js (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/features/imagediff.js]: To fix "including regressions from https://github.com/go-gitea/gitea/pull/22959"

The inner element is `position: absolute`, so the container's height should be large enough. I will add a comment.

**Comment by wxiaoguang** [comment]
> Why should we support that, if the user said themselves that it shouldn't be treated as an SVG?
> Why this heuristics-based approach?

It's an enhanced `http.DetectContentType`, in some cases, you do not have the ext-name.

File: web_src/js/features/imagediff.js (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/features/imagediff.js]: Comments are added.

**Comment by wxiaoguang** [comment]
And after more thoughts, I removed the close tag checking. Because, the `DetectContentType` only checks some beginning bytes. In many cases, it won't see the close tag.

Let's just keep the old behavior as much as possible, and propose new solutions in the future with real project code.

**Review by delvh — APPROVED** [review]
