### PR TITLE
Convert EOL to UNIX-style to render MD properly

### LINKED ISSUE #8865: Paragraph rendering in comments is broken
- Gitea version (or commit ref): d5b1e6bc51f87eb1be07a4682798428bf4bbb9ce
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/guillep2k/charset-problem/issues/4

## Description

Gitea no longer recognizes paragraphs in a comment, making a single paragraph for all the contents.

I suspect #8560 as the source cause.

#### This is a three paragraph text:

image

#### But it's rendered as a single paragraph:

image

### PR DESCRIPTION
**Pull request by guillep2k**
Closes #8865 

- [x] Tested with Linux server
- [x] Tested with Windows server
- [x] Tested with MAC server

NOTE: Props to @zeripath for devising a super-fast parsing function. 👍

### CODE REVIEW

File: modules/markup/markdown/markdown.go [hunk 1]
```diff
@@ -157,7 +157,9 @@ func RenderRaw(body []byte, urlPrefix string, wikiMarkdown bool) []byte {
 		exts |= blackfriday.HardLineBreak
 	}
 
-	body = blackfriday.Run(body, blackfriday.WithRenderer(renderer), blackfriday.WithExtensions(exts))
+	// Need to normalize EOL to UNIX LF to have consistent results in rendering
+	// @zeripath please remove this line to co-author this PR ;)
```
Comment (zeripath) [inline modules/markup/markdown/markdown.go]:
```suggestion
```

File: modules/util/util.go [hunk 2]
```diff
@@ -63,3 +64,35 @@ func Min(a, b int) int {
...
+	if left != 0 {
+		copy(tmp[pos:pos+left], input[0:left])
+		pos = left
+	}
+
+	for left < len(input) {
+		if input[left] == '\n' {
+			left++
+		}
+		right := bytes.Index(input[left:], []byte{'\r'})
```
Comment (zeripath) [inline modules/util/util.go]:
```suggestion
		right := bytes.IndexByte(input[left:], '\r')
```

File: modules/util/util.go [hunk 3]
```diff
@@ -63,3 +64,35 @@ func Min(a, b int) int {
 func IsEmptyString(s string) bool {
 	return len(strings.TrimSpace(s)) == 0
 }
+
+// NormalizeEOL will convert Windows (CRLF) and Mac (CR) EOLs to UNIX (LF)
+func NormalizeEOL(input []byte) []byte {
+	tmp := make([]byte, len(input))
+	left := 0
+	pos := 0
+	for input[left] == '\n' {
```
Comment (zeripath) [inline modules/util/util.go]:
```suggestion
	for left < len(input) && input[left] == '\n' {
```

File: modules/util/util.go [hunk 4]
```diff
@@ -63,3 +64,35 @@ func Min(a, b int) int {
 func IsEmptyString(s string) bool {
 	return len(strings.TrimSpace(s)) == 0
 }
+
+// NormalizeEOL will convert Windows (CRLF) and Mac (CR) EOLs to UNIX (LF)
+func NormalizeEOL(input []byte) []byte {
+	tmp := make([]byte, len(input))
```
Comment (zeripath) [inline modules/util/util.go]:
```suggestion
	if bytes.IndexByte(input, '\r') == -1 {
		return input
	}
	tmp := make([]byte, len(input))
```

Comment (zeripath) [reply modules/util/util.go]: This makes it much faster for small unix files - but does slightly slow things down on big windows/mac files

**Comment by guillep2k** [comment]
image


Tested under Windows and Linux.

Ready for review. 😄

**Comment by zeripath** [comment]
I probably shouldn't review given my involvement in the development of this code.

File: modules/util/util.go [hunk 5]
```diff
@@ -63,3 +64,52 @@ func Min(a, b int) int {
...
+
+// NormalizeEOL will convert Windows (CRLF) and Mac (CR) EOLs to UNIX (LF)
+func NormalizeEOL(input []byte) []byte {
+	var right, left, pos int
+	if right = bytes.IndexByte(input, '\r'); right == -1 {
+		return input
+	}
+	tmp := make([]byte, len(input))
+	length := len(input)
+	for left < length && input[left] == '\n' {
```
Comment (gary-kim) [inline modules/util/util.go]: Is this faster then using something like `left = bytes.LastIndexByte(input, '\n') + 1`? My current system has `gccgo` so I'll check when I have a change to install `gc` instead for a second.

File: modules/util/util.go [hunk 6]
```diff
@@ -63,3 +64,52 @@ func Min(a, b int) int {
...
 }
+
+// NormalizeEOL will convert Windows (CRLF) and Mac (CR) EOLs to UNIX (LF)
+func NormalizeEOL(input []byte) []byte {
+	var right, left, pos int
+	if right = bytes.IndexByte(input, '\r'); right == -1 {
+		return input
+	}
+	tmp := make([]byte, len(input))
+	length := len(input)
```
Comment (gary-kim) [inline modules/util/util.go:74]: Nitpickest of nitpicks :)
```
length := len(input)
tmp := make([]byte, length)
```

**Review by gary-kim — COMMENTED** [review]
Wow, that's fast

**Comment by guillep2k** [comment]
[speed_test.zip](https://github.com/go-gitea/gitea/files/3833779/speed_test.zip)

Add speed tests for reference.

File: modules/util/util.go (hunk 6 above)
Comment (guillep2k) [reply modules/util/util.go:74]: It's not really different, since `len()` is not really a function but a language construct AFAIK. These are the numbers for 150,000 iterations (method9 is len before make):
```
==== Testing DOS conversion
     Method8: 733.420742ms
     Method9: 745.064906ms
==== Testing MAC conversion
     Method8: 740.482412ms
     Method9: 734.314871ms
==== Testing LINUX conversion
     Method8: 33.425224ms
     Method9: 33.219408ms
PASS
ok      speed   3.198s
```

I've attached my tests four your reference.

File: modules/util/util.go (hunk 5 above)
Comment (guillep2k) [reply modules/util/util.go]: > 
> 
> Is this faster then using something like `left = bytes.LastIndexByte(input, '\n') + 1`? My current system has `gccgo` so I'll check when I have a change to install `gc` instead for a second.

@gary-kim check the test file attached in another comment; somehow I can't attach files inside code review comments.

File: modules/util/util.go (hunk 6 above)
Comment (guillep2k) [reply modules/util/util.go:74]: @gary-kim Well, I stand corrected. I ran more tests and it seems it's slightly faster, go figure. Updated.

**Review by gary-kim — APPROVED** [review]

File: modules/markup/markdown/markdown_test.go [hunk 7]
```diff
@@ -294,3 +294,25 @@ func TestTotal_RenderString(t *testing.T) {
...
+	test := func(t *testing.T, str string, cnt int) {
+		unix := []byte(str)
+		res := string(RenderRaw(unix, "", false))
+		assert.Equal(t, strings.Count(res, "<p"), cnt)
+
+		mac := []byte(strings.ReplaceAll(str, "\n", "\r"))
+		res = string(RenderRaw(mac, "", false))
+		assert.Equal(t, strings.Count(res, "<p"), cnt)
+
+		dos := []byte(strings.ReplaceAll(str, "\n", "\r"))
```
Comment (guillep2k) [inline modules/markup/markdown/markdown_test.go]:
```suggestion
		dos := []byte(strings.ReplaceAll(str, "\n", "\r\n"))
```

File: modules/util/util.go [hunk 8]
```diff
@@ -63,3 +64,52 @@ func Min(a, b int) int {
...
+		copy(tmp[pos:pos+left], input[0:left])
+		pos = left
+		right -= left
+	}
+
+	if left < length {
+		if input[left] == '\n' {
+			left++
+			right--
+		}
```
Comment (zeripath) [inline modules/util/util.go]: We can drop this check. We know that `input[left]` is not a `\n` from line 76.

Comment (zeripath) [reply modules/util/util.go]: In fact now that we have unfurled the initial step we can drop lines 76-84 and lines 86-89

Comment (zeripath) [reply modules/util/util.go]: And you can drop the `if left < length {` test at line 85 because the only way that could happen would cause `right == -1`.

**Comment by zeripath** [comment]
OK at some point I'll actually stop improving this:

```go
// NormalizeEOL will convert Windows (CRLF) and Mac (CR) EOLs to UNIX (LF)
func NormalizeEOL(input []byte) []byte {
	var right, left, pos int
	if right = bytes.IndexByte(input, '\r'); right == -1 {
		return input
	}
	length := len(input)
	tmp := make([]byte, length)

	// We know that left < length because otherwise right would be -1 from IndexByte.
	copy(tmp[pos:pos+right], input[left:left+right])
	pos += right
	tmp[pos] = '\n'
	left += right + 1
	pos++

	for left < length {
		if input[left] == '\n' {
			left++
		}

		right = bytes.IndexByte(input[left:], '\r')
		if right == -1 {
			copy(tmp[pos:], input[left:])
			pos += length - left
			break
		}
		copy(tmp[pos:pos+right], input[left:left+right])
		pos += right
		tmp[pos] = '\n'
		left += right + 1
		pos++
	}
	return tmp[:pos]
}
```

File: modules/util/util.go (hunk 5 above)
Comment (zeripath) [reply modules/util/util.go]: So that code was munching initial `\n` to prevent them from being skipped. However, I've realised it's totally unnecessary, see below...

File: modules/util/util.go (hunk 8 above)
Comment (zeripath) [reply modules/util/util.go]: See https://github.com/go-gitea/gitea/pull/8925#issuecomment-552804972

File: modules/util/util.go [hunk 9]
```diff
@@ -63,3 +64,52 @@ func Min(a, b int) int {
...
+		left += right + 1
+		pos++
+	}
+
+	for left < length {
+		if input[left] == '\n' {
+			left++
+		}
+
+		right = bytes.IndexByte(input[left:], '\r')
```
Comment (zeripath) [inline modules/util/util.go:89]: In Java, the JVM JIT has a weird feature whereby it's actually quicker to assign names used inside loops rather than refer to things used outside the loops, e.g. `right := ...` would be quicker than `right = ...`. On testing, this does not appear to be the case for go's compiler.

File: modules/util/util.go (hunk 8 above)
Comment (guillep2k) [reply modules/util/util.go]: 👍 @zeripath done.

**Review by mrsdizzie — APPROVED** [review]
This makes my eyes hurt but seems exponentially better than ones that don't sadly :) 

Works fine on Mac.

**Review by sapk — APPROVED** [review]
