### PR TITLE
Always update expiration time when creating an artifact

### LINKED ISSUE #32256: Artifacts get lost, when re-running old workflows
### Description

I just tried to re-run a job that was executed 2 weeks ago. We have set `ARTIFACT_RETENTION_DAYS = 7` in the _actions_ section.

The build job actually says that artifact upload is succesful. But the next job, that tries to fetch the artifact fails:

```txt
Total number of files that will be downloaded: 540
A 500 response code has been received while attempting to download an artifact
Exponential backoff for retry #1. Waiting for 5[4](https://HIDDEN/actions/runs/860/jobs/1#jobstep-1-4)75 milliseconds before continuing the download
A 500 response code has been received while attempting to download an artifact
Exponential backoff for retry #1. Waiting for [5](https://HIDDEN/actions/runs/860/jobs/1#jobstep-1-5)482 milliseconds before continuing the download
```

I also tried downloading the artifact manually and get the error: 

> artifact not found

I also tried to delete the artifact manually in the web interface.  This also returns a 200 code for the `DELETE` request. However the artifact does not disappear.

Here a part of the response from the artifacts `GET` request after the deletion attempt:

```
{
    "artifacts": [
        {
            "name": "Bin.Unprotected",
            "size": 80032963,
            "status": "expired"
        }
    ]
}
```

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by Zettat123**
Fix #32256

### CODE REVIEW

**Comment by Zettat123** [comment]
I noticed another issue. If we re-run a job, the storage path of the old artifact will be overwritten by the storage path of the newly created artifact, which may cause the old artifact to never be cleaned up.

File: models/actions/artifact.go [hunk 1]
```diff
@@ -78,6 +78,12 @@ func CreateArtifact(ctx context.Context, t *ActionTask, artifactName, artifactPa
 	} else if err != nil {
 		return nil, err
 	}
+
+	artifact.ExpiredUnix = timeutil.TimeStamp(time.Now().Unix() + 3600*24*expiredDays)
```
Comment (yp05327) [inline models/actions/artifact.go]: image
we have this

Comment (Zettat123) [reply models/actions/artifact.go]: 374d323eaadaf555168fe3c4cb94ac39c2b14245

**Review by wolfogre — APPROVED** [review]

**Review by lunny — APPROVED** [review]
