### PR TITLE
Fix incorrect pull request counter

### LINKED ISSUE #35781: Pull requests show negative number -1 after merge
### Description

Image

not sure if this can be reproduced but I have never experienced this in earlier versions.

### Gitea Version

1.25.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

Image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Download binary

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by lunny**
Fix #35781, #27472

The PR will not correct the wrong numbers automatically. 

There is a cron task `check_repo_stats` which will be run when Gitea start or midnight. It will correct the numbers.

### CODE REVIEW

File: models/actions/run_test.go [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+)
+
+func TestUpdateRepoRunsNumbers(t *testing.T) {
+	assert.NoError(t, unittest.PrepareTestDatabase())
+
+	repo := unittest.AssertExistsAndLoadBean(t, &repo_model.Repository{ID: 4})
+	assert.Equal(t, 4, repo.NumActionRuns)
+	assert.Equal(t, 2, repo.NumClosedActionRuns)
+
+	err := UpdateRepoRunsNumbers(t.Context(), repo)
```
Comment (yp05327) [inline models/actions/run_test.go]: change issue num before update repo runs numbers, and check whether it will be changed?

File: models/issues/comment.go [hunk 2]
```diff
@@ -862,10 +862,6 @@ func updateCommentInfos(ctx context.Context, opts *CreateCommentOptions, comment
 		if err = UpdateCommentAttachments(ctx, comment, opts.Attachments); err != nil {
 			return err
 		}
-	case CommentTypeReopen, CommentTypeClose:
```
Comment (yp05327) [inline models/issues/comment.go:865]: maybe it is better to left a comment here

File: models/user/must_change_password.go [hunk 3]
```diff
@@ -45,5 +45,5 @@ func SetMustChangePassword(ctx context.Context, all, mustChangePassword bool, in
 		cond = cond.And(builder.NotIn("lower_name", exclude))
 	}
 
-	return db.GetEngine(ctx).Where(cond).MustCols("must_change_password").Update(&User{MustChangePassword: mustChangePassword})
+	return db.GetEngine(ctx).Where(cond).Cols("must_change_password").Update(&User{MustChangePassword: mustChangePassword})
```
Comment (yp05327) [inline models/user/must_change_password.go]: Why this should be changed?

File: services/issue/issue.go [hunk 4]
```diff
@@ -270,15 +271,17 @@ func deleteIssue(ctx context.Context, issue *issues_model.Issue) ([]string, erro
...
-		}
-		// if the issue is closed, update the closed issue numbers
+		colName := util.Iif(issue.IsPull, "num_pulls", "num_issues")
+		closedColName := util.Iif(issue.IsPull, "num_closed_pulls", "num_closed_issues")
+		dbSession := db.GetEngine(ctx)
 		if issue.IsClosed {
-			if err := repo_model.UpdateRepoIssueNumbers(ctx, issue.RepoID, issue.IsPull, true); err != nil {
-				return nil, err
-			}
+			dbSession.Decr(closedColName)
```
Comment (yp05327) [inline services/issue/issue.go]: Maybe we can add new function `DecrRepoIssueNumbers` and `IncRepoIssueNumbers`?

**Review by wolfogre — APPROVED** [review]

File: models/user/must_change_password.go (hunk 3 above)
Comment (lunny) [reply models/user/must_change_password.go]: This change reverted.

File: models/actions/run_test.go (hunk 1 above)
Comment (lunny) [reply models/actions/run_test.go]: a27061e269cc2d9c5c4033897b44e2046e5b2218

File: models/issues/comment.go (hunk 2 above)
Comment (lunny) [reply models/issues/comment.go:865]: a27061e269cc2d9c5c4033897b44e2046e5b2218

File: services/issue/issue.go (hunk 4 above)
Comment (lunny) [reply services/issue/issue.go]: a27061e269cc2d9c5c4033897b44e2046e5b2218

**Review by Zettat123 — APPROVED** [review]
