### PR TITLE
Fix `relative-time` error and improve global error handler

### LINKED ISSUE #37239: `relative-time` error `invalid language tag: "undefined"` in playwright
`relative-time` has a bug when ran in playwright firefox. It shows a global error message and below error is logged in the console. Likely this is a playwright-specific bug, not observable on a real browser.

```
Uncaught RangeError: invalid language tag: "undefined"
    _getFormattedTitle relative-time.ts:391
    update relative-time.ts:480
    attributeChangedCallback relative-time.ts:384
    attributeChangedCallback relative-time.ts:383
    LifecycleAttributeChangedCallback* relative-time.ts:506
    <anonymous> user-settings.ts:73
```

One related enhancement that could be done to the global error handler is to also print the stack trace which is helpful debugging information, currently only visible in the browse console. I recall asking users many times for error stack traces, so I think the UI should render them, even a stack trace from minified code without a source map is useful.

### PR DESCRIPTION
**Pull request by silverwind**
1. Fixes: #37239
2. Enhance global error message to show stack trace on click

image

---
This PR was written with the help of Claude Opus 4.7

### CODE REVIEW

File: web_src/js/modules/errors.ts [hunk 1]
```diff
@@ -12,14 +24,38 @@ export function showGlobalErrorMessage(msg: string, msgType: Intent = 'error') {
   let msgDiv = msgContainer.querySelector<HTMLDivElement>(`.js-global-error[data-global-error-msg-compact="${msgCompact}"]`);
   if (!msgDiv) {
     const el = document.createElement('div');
-    el.innerHTML = html`<div class="ui container js-global-error tw-my-[--page-spacing]"><div class="ui ${msgType} message tw-text-center tw-whitespace-pre-line"></div></div>`;
-    msgDiv = el.childNodes[0] as HTMLDivElement;
+    el.innerHTML = html`
+      <div class="ui container js-global-error tw-my-[--page-spacing]">
+        <div class="ui ${msgType} message tw-flex tw-justify-center tw-items-center">
+          <span class="js-global-error-msg"></span><span class="js-global-error-count"></span>
+          <button type="button" class="js-global-error-copy interact-bg tw-text-inherit tw-p-2 tw-rounded tw-ml-1" aria-label="${window.config.i18n.copy}"></button>
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/modules/errors.ts]: Dropped the copy button's `aria-label` entirely, so the error UI no longer reads `window.config.i18n.copy`. The bootstrap.ts fallback path (triggered precisely when `window.config` is missing) now renders cleanly. Also removed the newly-added `copy` i18n key since it's unused.

---
_Comment written by Claude Opus 4.7._

File: web_src/js/modules/errors.ts [hunk 2]
```diff
@@ -12,14 +24,38 @@ export function showGlobalErrorMessage(msg: string, msgType: Intent = 'error') {
   let msgDiv = msgContainer.querySelector<HTMLDivElement>(`.js-global-error[data-global-error-msg-compact="${msgCompact}"]`);
   if (!msgDiv) {
     const el = document.createElement('div');
-    el.innerHTML = html`<div class="ui container js-global-error tw-my-[--page-spacing]"><div class="ui ${msgType} message tw-text-center tw-whitespace-pre-line"></div></div>`;
-    msgDiv = el.childNodes[0] as HTMLDivElement;
+    el.innerHTML = html`
+      <div class="ui container js-global-error tw-my-[--page-spacing]">
+        <div class="ui ${msgType} message tw-flex tw-justify-center tw-items-center">
+          <span class="js-global-error-msg"></span><span class="js-global-error-count"></span>
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/modules/errors.ts]: Good catch. Added `tw-whitespace-pre-line` to `.js-global-error-msg` so multi-line warnings (ROOT_URL mismatch, HTTPS scheme) render with their line breaks preserved.

---
_Comment written by Claude Opus 4.7._

File: web_src/js/modules/errors.ts [hunk 3]
```diff
@@ -12,14 +24,38 @@ export function showGlobalErrorMessage(msg: string, msgType: Intent = 'error') {
...
-  const msgCount = Number(msgDiv.getAttribute(`data-global-error-msg-count`)) + 1;
-  msgDiv.setAttribute(`data-global-error-msg-compact`, msgCompact);
-  msgDiv.setAttribute(`data-global-error-msg-count`, msgCount.toString());
-  msgDiv.querySelector('.ui.message')!.textContent = msg + (msgCount > 1 ? ` (${msgCount})` : '');
+  const msgCount = Number(msgDiv.getAttribute('data-global-error-msg-count')) + 1;
+  msgDiv.setAttribute('data-global-error-msg-compact', msgCompact);
+  msgDiv.setAttribute('data-global-error-msg-count', String(msgCount));
+  msgDiv.querySelector('.js-global-error-msg')!.textContent = msg;
+  msgDiv.querySelector('.js-global-error-count')!.textContent = msgCount > 1 ? ` (${msgCount})` : '';
+  if (stack) msgDiv.querySelector('.js-global-error-stack')!.textContent = stack;
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/modules/errors.ts]: Changed to unconditional `textContent = stack ?? ''`. A subsequent call to the same compacted message with no stack now correctly clears any previously-stored stack instead of leaving it stale for copy.

---
_Comment written by Claude Opus 4.7._

File: web_src/js/modules/errors.ts [hunk 4]
```diff
@@ -1,8 +1,20 @@
 // keep this file lightweight, it's imported into IIFE chunk in bootstrap
+import {clippie} from 'clippie';
 import {html} from '../utils/html.ts';
+import octiconCheck from '../../../public/assets/img/svg/octicon-check.svg';
+import octiconCopy from '../../../public/assets/img/svg/octicon-copy.svg';
 import type {Intent} from '../types.ts';
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/modules/errors.ts]: Keeping `clippie` static — at roughly 500 bytes gzipped it's tiny and buys us the `execCommand` fallback for insecure contexts / older browsers. Lazy-loading would defer the load but adds async complexity and a potential load-failure path for a feature users specifically need when something has already gone wrong.

The two octicon SVGs together are another ~0.9KB raw but visible immediately when an error appears, so they can't be deferred.

---
_Comment written by Claude Opus 4.7._

File: tests/e2e/homepage.test.ts [hunk 5]
```diff
@@ -0,0 +1,7 @@
+import {test} from '@playwright/test';
+import {assertNoJsError} from './utils.ts';
+
+test('homepage renders without errors', async ({page}) => {
+  await page.goto('/');
```
[the remark this answers is not in the document]
Comment (silverwind) [reply tests/e2e/homepage.test.ts:5]: Added `await page.waitForLoadState('networkidle')` before the assertion so async errors have a chance to reach the global handler.

`assertNoJsError` already catches any JS error that goes through Gitea's `window.onerror` → `processWindowErrorEvent` pipeline (it shows up as a `.js-global-error` DOM element), so a separate `page.on('pageerror')` listener would be redundant for the common case.

Disabled `playwright/no-networkidle` globally for `tests/e2e/**` since that's the simplest way to capture "page has finished doing work" for this kind of smoke test.

---
_Comment written by Claude Opus 4.7._

File: web_src/js/modules/errors.ts [hunk 6]
```diff
@@ -1,8 +1,11 @@
 // keep this file lightweight, it's imported into IIFE chunk in bootstrap
+import {clippie} from 'clippie';
 import {html} from '../utils/html.ts';
+import octiconCheck from '../../../public/assets/img/svg/octicon-check.svg';
+import octiconCopy from '../../../public/assets/img/svg/octicon-copy.svg';
```
Comment (silverwind) [inline web_src/js/modules/errors.ts]: FYI this is still lightweight. ~1kB for those 3 imports.

**Review by wxiaoguang — DISMISSED** [review]
No, the error message prompt is just for development purpose.

It should not be that complex. The more complex it becomes, the more potential bugs it will have. What if the code causes new errors again?

Do not make things unnecessarily complex.


If you need to read more about the error details, just open the browser's console, just like all the frontend developers do.

**Comment by silverwind** [comment]
Stack trace must be accessible somehow because it's vital information and a small copy button achieves that in the least obtrusive way besides rendering it directly.

"Open the console" is bad, some browsers might not even have a console, think about tablets or phones. Don't assume every user is on a desktop.

**Comment by wxiaoguang** [comment]
> Stack trace must be accessible somehow because it's vital information and a small copy button achieves that in the least obtrusive way besides rendering it directly.

Do you remember that you had objection when I introduced such "js error message prompt"? But now why you keep making it unnecessarily complex. Developers should open their console, look into the real source code with source map.

In production build, your stack trace here is just garbled text


----


> "Open the console" is bad, some browsers might not even have a console, think about tablets or phones. Don't assume every user is on a desktop.

It is just your guess and imagination that "it needs to show stack for a user who uses a phone".

**Comment by silverwind** [comment]
It's more about that I always have to ask users to copy the error from the console than to screenshot/copy only the message because "Foo is undefined" is not debuggable without the stack trace. If you don't like the copy button, we could make it visible on-hover.

**Comment by wxiaoguang** [comment]
> It's more about that I always have to ask users to copy the error from the console

How many times? Where are the related issues?

>  If you don't like the copy button, we could make it visible on-hover.

I don't accept any more useless change.

**Comment by silverwind** [comment]
> How many times? Where are the related issues?

At least 4-5 times, some on GitHub, some on Discord.

> I don't accept any more useless change.

It is genuinely needed for debugging.

**Comment by silverwind** [comment]
Concrete example:

image

User posts only a screenshot of the error without any console output. Errors was deducable from the message via AI, but in case of `e is undefined`, this won't be possible.

**Comment by silverwind** [comment]
If copy button is not to your liking, we can use a `<details>`+`<summary>` that expands with the stack track on click and maybe add a "Click for details" in place of "Open browser console". Least obtrusive change possible.

**Comment by wxiaoguang** [comment]
> Concrete example:
> image
> 
> User posts only a screenshot of the error without any console output. Errors was deducable from the message via AI, but in case of `e is undefined`, this won't be possible.

1. They are contributors, they should know how to correctly report a bug without the "copy" button or duplicate "stack" message.
2. Most end users should never see the JS error, most JS errors should already have been handled by maintainers during the development.
3. Even if you have a "copy" button, almost all users still only show you a screenshot (just like your screenshot shows), you still need to tell them "please provide the stacktrace", the same as "open the console and show the stacktrace"

**Comment by wxiaoguang** [comment]
> If copy button is not to your liking, we can use a `<details>`+`<summary>` that expands with the stack track on click and maybe add a "Click for details" in place of "Open browser console". Least obtrusive change possible.

Can do with a general function like

```
export function showGlobalErrorMessage(msg: string, msgType: Intent = 'error', details?: string) {
...
}
```

**Comment by silverwind** [comment]
I will do the details+summary approach like that.

**Comment by silverwind** [comment]
Ready again. now uses `<details>`, diff is minimal. PR description updated with new screenshots.

File: tests/e2e/homepage.test.ts [hunk 7]
```diff
@@ -0,0 +1,8 @@
...
+  await page.waitForLoadState('networkidle'); // eslint-disable-line playwright/no-networkidle
+  await assertNoJsError(page);
+});
```
Comment (wxiaoguang) [inline tests/e2e/homepage.test.ts:8]: Why such a strange special test for "homepage"? No page should have JS error

**Comment by wxiaoguang** [comment]
It seems that you does't write correct and well-designed  code  anymore after you started using AI.

image

File: web_src/js/modules/errors.ts [hunk 8]
```diff
@@ -49,9 +60,8 @@ export function processWindowErrorEvent({error, reason, message, type, filename,
...
   if (!isGiteaError(filename ?? '', err?.stack ?? '')) return;
 
-  let msg = err?.message ?? message;
-  if (lineno) msg += ` (${filename} @ ${lineno}:${colno})`;
-  const dot = msg.endsWith('.') ? '' : '.';
   const renderedType = type === 'unhandledrejection' ? 'promise rejection' : type;
-  showGlobalErrorMessage(`JavaScript ${renderedType}: ${msg}${dot} Open browser console to see more details.`);
+  let msg = err?.message ?? message;
+  if (!err?.stack && lineno) msg += ` (${filename} @ ${lineno}:${colno})`;
+  showGlobalErrorMessage(`JavaScript ${renderedType}: ${msg}`, 'error', err?.stack);
```
Comment (wxiaoguang) [inline web_src/js/modules/errors.ts:66]: `Open browser console to see more details` is still useful, just keep teaching people how to debug and report frontend problem correctly.

Don't let them develop bad habits.

File: tests/e2e/homepage.test.ts (hunk 7 above)
Comment (silverwind) [reply tests/e2e/homepage.test.ts]: It's meant as a general "no errors" test. I think some other tests may already catch essentially the same, if that is the case we can remove it.

Comment (wxiaoguang) [reply tests/e2e/homepage.test.ts]: If every page already has "no errors" assert, then this separate test is not needed, it only confuses readers IMHO

Comment (silverwind) [reply tests/e2e/homepage.test.ts]: True, the name is misleading.

Comment (silverwind) [reply tests/e2e/homepage.test.ts]: I'll remove this test.

File: web_src/js/modules/errors.ts (hunk 8 above)
Comment (silverwind) [reply web_src/js/modules/errors.ts]: restored

File: tests/e2e/homepage.test.ts (hunk 7 above)
Comment (silverwind) [reply tests/e2e/homepage.test.ts]: removed

**Comment by silverwind** [comment]
All fixed, https://github.com/go-gitea/gitea/pull/37241#issue-4277538544 is up to date.

File: web_src/js/modules/errors.ts [hunk 9]
```diff
@@ -13,7 +13,7 @@ export function showGlobalErrorMessage(msg: string, msgType: Intent = 'error', d
   let msgContainer = parentContainer.querySelector<HTMLDivElement>(`.js-global-error[data-global-error-msg-compact="${msgCompact}"]`);
   if (!msgContainer) {
     const el = document.createElement('div');
-    el.innerHTML = html`<div class="ui container js-global-error tw-my-[--page-spacing]"><details class="ui ${msgType} message"><summary></summary></details></div>`;
+    el.innerHTML = html`<div class="ui container js-global-error tw-my-[--page-spacing]"><details class="ui ${msgType} message tw-text-center tw-whitespace-pre-line"><summary></summary></details></div>`;
```
Comment (wxiaoguang) [inline web_src/js/modules/errors.ts]: No , don't do this.

`tw-text-center` is ugly


`tw-whitespace-pre-line` is useless

File: web_src/js/modules/errors.ts [hunk 10]
```diff
@@ -27,9 +27,13 @@ export function showGlobalErrorMessage(msg: string, msgType: Intent = 'error', d
...
     let msgDetailsPre = msgElem.querySelector('pre');
-    if (!msgDetailsPre) msgDetailsPre = document.createElement('pre');
+    if (!msgDetailsPre) {
+      msgDetailsPre = document.createElement('pre');
+      msgElem.append(msgDetailsPre);
+    }
     msgDetailsPre.textContent = details;
-    msgElem.append(msgDetailsPre);
+  } else {
+    msgElem.querySelector('pre')?.remove();
```
Comment (wxiaoguang) [inline web_src/js/modules/errors.ts]: No, don't do this.

File: web_src/js/modules/errors.ts [hunk 11]
```diff
@@ -27,9 +27,13 @@ export function showGlobalErrorMessage(msg: string, msgType: Intent = 'error', d
   msgSummary.textContent = msg + (msgCount > 1 ? ` (${msgCount})` : '');
   if (details) {
     let msgDetailsPre = msgElem.querySelector('pre');
-    if (!msgDetailsPre) msgDetailsPre = document.createElement('pre');
+    if (!msgDetailsPre) {
+      msgDetailsPre = document.createElement('pre');
+      msgElem.append(msgDetailsPre);
+    }
     msgDetailsPre.textContent = details;
-    msgElem.append(msgDetailsPre);
```
Comment (wxiaoguang) [inline web_src/js/modules/errors.ts]: Old approach is pretty simple , clear and correct.

`append` is always right

**Comment by wxiaoguang** [comment]
Why the `tw-text-center` is added back, and then use such ugly layout? Just because your AI likes it?

image

File: web_src/js/modules/errors.ts (hunk 9 above)
Comment (silverwind) [reply web_src/js/modules/errors.ts]: > tw-text-center is ugly

It was centered before this change and I strongly prefer it centered, it just looks "balanced". Arent stuff like admin messages also centered?

**Comment by silverwind** [comment]
Stack trace needs to be aligned, I agree. Overall message I would keep centered as per comment above.

File: web_src/js/modules/errors.ts (hunk 9 above)
Comment (wxiaoguang) [reply web_src/js/modules/errors.ts]: > Arent stuff like admin messages also centered?

Take a look at the "toast-and-messge" devtest page again.

* https://github.com/go-gitea/gitea/pull/37179#issuecomment-4229686096

**Comment by wxiaoguang** [comment]
> Stack trace needs to be aligned, I agree. Overall message I would keep centered as per comment above.

No.

* https://github.com/go-gitea/gitea/pull/37179#issuecomment-4229686096

**Comment by silverwind** [comment]
All addressed, I guess left-aligned is fine after all. I just need to get used to it.

My only question: Why is single message still centered? Looks inconistent.

Screenshot 2026-04-21 at 01 34 32

File: web_src/js/modules/errors.test.ts [hunk 12]
```diff
@@ -25,3 +28,21 @@ test('showGlobalErrorMessage', () => {
...
+  const error = new Error('boom');
+  error.stack = `Error: boom\n    at fn (${window.location.origin}/assets/js/index.js:1:1)`;
+  processWindowErrorEvent({error, type: 'error'} as ErrorEvent & PromiseRejectionEvent);
+  expect(document.querySelector('.js-global-error summary')!.textContent).toContain('JavaScript error: boom');
+  expect(document.querySelector('.js-global-error pre')!.textContent).toContain('/assets/js/index.js:1:1');
+});
+
+test('processWindowErrorEvent falls back to message without stack', () => {
+  processWindowErrorEvent({
+    error: {message: 'script error'} as Error, type: 'error',
```
Comment (silverwind) [inline web_src/js/modules/errors.test.ts]:
```suggestion
    error: {message: 'script error'}, type: 'error',
```

**Review by wxiaoguang — APPROVED** [review]

File: web_src/css/modules/message.css [hunk 13]
```diff
@@ -12,6 +12,25 @@
...
+details.ui.message {
+  padding: 0;
+}
+
+details.ui.message summary {
+  padding: 1em 1.5em;
+}
+
+details.ui.message pre {
+  margin: -1.25em 0 0 0;
```
Comment (wxiaoguang) [inline web_src/css/modules/message.css]:
```suggestion
  margin: -1.25em 0 0;
```

**Review by bircni — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> My only question: Why is single message still centered? Looks inconistent.

Just because "it looks better" for "single line" (as you suggested).


For > 99% cases, the left-alignment and center-alignment won't appear on the same page at the same time, there won't be "inconsistent"


Also, for  > 99% cases, you will still only see single line message. The multiple line message is only for some serious errors, very rare cases.
