### PR TITLE
Fix 500 when deleting account with incorrect password or unsupported login type

### LINKED ISSUE #26210: Delete user account functionality broken.
### Description

Steps to repro.
1. Login to gitea
2. Go to settings.
3. Go to Accounts.
4. Go to `Delete Your Account`.
5. Now click on 
image without entring password. 
6. We get 500 error.

### Gitea Version

1.21.0+dev-412-gce27de4d4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image
image
image

### Git Version

1.21.0+dev-412-gce27de4d4

### Operating System

_No response_

### How are you running Gitea?

locally and try.gitea.io

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix #26210

### CODE REVIEW

File: modules/base/type.go [hunk 1]
```diff
@@ -0,0 +1,10 @@
+// Copyright 2024 The Gitea Authors. All rights reserved.
+// SPDX-License-Identifier: MIT
+
+package base
+
+// IsError checks if an error is a T error.
+func IsError[T any](err error) bool {
```
Comment (JakobDev) [inline modules/base/type.go]: You could simply use [errors.is](https://pkg.go.dev/errors#Is) from the Go standard lib

Comment (lunny) [reply modules/base/type.go]: I have tried. It's not the same. `errors.Is` will detect whether it has `UnWrap` method.

Comment (wxiaoguang) [reply modules/base/type.go]: I agree with JakobDev. I do not think it should introduce a new `IsError` here.

The Golang has a very bad "error" system. For example:

* `errors.New()` returns the same error type. So: the same error type doesn't mean the same error.
* `*ErrType` and `ErrType`  are different types. So: the same ErrType related variables isn't considered as the same error but they are indeed the same errors.

I think you need to clearly define the error types here, to avoid these quirks.

Comment (wxiaoguang) [reply modules/base/type.go]: What you need is `errors.As`:

If you really would like to introduce a new helper function, it could be called `IsErrorSameType`, to make it clear (and please call `errors.As`)

```

type ErrTest struct {
	v int
}

func (err ErrTest) Error() string {
	return "test error"
}

func (err ErrTest) Unwrap() error {
	return os.ErrInvalid
}

func main() {
	fmt.Printf("Is: %v\n", errors.Is(ErrTest{1}, ErrTest{2}))
	fmt.Printf("As: %v\n", errors.As(ErrTest{1}, &ErrTest{}))
}
```

```
Is: false
As: true
```

Comment (lunny) [reply modules/base/type.go]: 5a34c87c7afdddd35e4f8fa643088ac12457267e

File: options/locale/locale_en-US.ini [hunk 2]
```diff
@@ -654,7 +656,7 @@ block.note.title = Optional note:
 block.note.info = The note is not visible to the blocked user.
 block.note.edit = Edit note
 block.list = Blocked users
-block.list.none = You have not blocked any users. 
+block.list.none = You have not blocked any users.
```
Comment (silverwind) [inline options/locale/locale_en-US.ini]: Sidenote: `editorconfig-checker` might be able to lint for such trailing whitespace here in this file.

**Comment by yp05327** [comment]
Another question: why even it is marked as required, but can be empty when sending the request.
image

**Comment by lunny** [comment]
> Another question: why even it is marked as required, but can be empty when sending the request. image

That could be another problem. I think it needs the frontend changes before the model popup.

**Review by silverwind — APPROVED** [review]

**Review by wolfogre — APPROVED** [review]

File: routers/web/user/setting/account.go [hunk 3]
```diff
@@ -242,11 +244,24 @@ func DeleteAccount(ctx *context.Context) {
 	ctx.Data["PageIsSettingsAccount"] = true
 
 	if _, _, err := auth.UserSignIn(ctx, ctx.Doer.Name, ctx.FormString("password")); err != nil {
-		if user_model.IsErrUserNotExist(err) {
+		switch {
+		case user_model.IsErrUserNotExist(err):
+			loadAccountData(ctx)
+
+			ctx.RenderWithErr(ctx.Tr("form.user_not_exist"), tplSettingsAccount, nil)
+		case err == smtp.ErrUnsupportedLoginType:
```
Comment (wolfogre) [inline routers/web/user/setting/account.go]: Maybe
```suggestion
		case errors.Is(err, smtp.ErrUnsupportedLoginType):
```
?
