### PR TITLE
Use full output of git show-ref --tags to get tags for PushUpdateAddTag

### LINKED ISSUE #19038: Failed to synchronize tags to release in SyncMirror with error: "pushUpdateAddTag: GetTag: Length must be 40:"
### Feature Description

In gitea.log I see sometimes:

```
==> gitea.log <==
2022/03/09 12:06:37 ...irror/mirror_pull.go:261:runSync() [E] Failed to synchronize tags to releases for repository: pushUpdateAddTag: GetTag: Length must be 40:
        /source/services/mirror/mirror_pull.go:261 (0x1cdf3b8)
        /source/services/mirror/mirror_pull.go:376 (0x1ce10b8)
        /source/services/mirror/mirror.go:42 (0x1cdb344)
        /source/services/mirror/mirror.go:144 (0x1cdbe31)
        /source/modules/queue/unique_queue_channel.go:76 (0x14954b6)
        /source/modules/queue/workerpool.go:437 (0x149e1c5)
        /source/modules/queue/workerpool.go:280 (0x149d096)
        /usr/local/go/src/runtime/asm_amd64.s:1581 (0x471520)
```

But you can't see:

- which project
- which tag?
- how long is it?

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by zeripath**
Strangely #19038 appears to relate to an issue whereby a tag appears to
be listed in `git show-ref --tags` but then does not appear when `git
show-ref --tags -- short_name` is called.

As a solution though I propose to stop the second call as it is
unnecessary and only likely to cause problems.

I've also noticed that the tags calls are wildly inefficient and aren't using the common cat-files - so these have been added.

I've also noticed that the git commit-graph is not being written on mirroring - so I've also added writing this to the migration which should improve mirror rendering somewhat. 

Fix #19038

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: modules/git/repo_tag.go [hunk 1]
```diff
@@ -159,6 +95,20 @@ func (repo *Repository) GetTag(name string) (*Tag, error) {
 	return tag, nil
 }
 
+// GetTagWithID returns a Git tag by given name.
```
Comment (Gusted) [inline modules/git/repo_tag.go]:
```suggestion
// GetTagWithID returns a Git tag by given name and tag ID.
```

File: modules/git/repo_branch_gogit.go [hunk 2]
```diff
@@ -101,9 +102,42 @@ func WalkReferences(ctx context.Context, repoPath string, walkfn func(string) er
...
-		err := walkfn(string(ref.Name()))
+		err := walkfn(ref.Hash().String(), string(ref.Name()))
 		i++
 		return err
 	})
 	return i, err
 }
+
+// WalkReferences walks all the references from the repository
+func (repo *Repository) WalkReferences(arg string, skip, limit int, walkfn func(sha1, refname string) error) (int, error) {
```
Comment (6543) [inline modules/git/repo_branch_gogit.go]: one concern, I would rather have some "enum" const than arbitrary string

Comment (zeripath) [reply modules/git/repo_branch_gogit.go]: Yes, I didn't realise when I wrote this that I was leaking the --tags out of git modules.

I think we already have an appropriate type that we can use here.

File: modules/repository/repo.go [hunk 3]
```diff
@@ -80,6 +80,12 @@ func MigrateRepositoryGitData(ctx context.Context, u *user_model.User,
 		return repo, fmt.Errorf("Clone: %v", err)
 	}
 
+	if git.CheckGitVersionAtLeast("2.18") == nil {
+		if _, err := git.NewCommand(ctx, "commit-graph", "write").RunInDir(repoPath); err != nil {
```
Comment (zeripath) [inline modules/repository/repo.go]: This will likely represent a huge performance improvement across the board.

We need to force write the commit graph on run sync too

File: modules/repository/repo.go [hunk 4]
```diff
@@ -101,6 +107,11 @@ func MigrateRepositoryGitData(ctx context.Context, u *user_model.User,
 				}
 			}
 		}
+		if git.CheckGitVersionAtLeast("2.18") == nil {
```
Comment (6543) [inline modules/repository/repo.go]: this write commit graph code exists multible times - we should move it into a own func

Comment (6543) [reply modules/repository/repo.go]: beside this it has my ok :)

**Review by 6543 — APPROVED** [review]

**Review by Gusted — APPROVED** [review]

**Comment by 6543** [comment]
wake up :robot:
