### PR TITLE
Finally fix diff names

### LINKED ISSUE #13060: Images and other binary files not shown in diff
- Gitea version (or commit ref): 1.12.5
- Git version: 2.25.1
- Operating system: Ubuntu 20.04.1 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide [example URL](https://try.gitea.io/mleyen/diff-test/commit/fcf20472ea413ab6752516827a597274dab58513))
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Images no longer display in the Web interface when viewing a commit's diff. Instead, they only display an empty line with the "BIN" label, and no filename. This is true for any binary file, as well as [empty files](https://try.gitea.io/mleyen/diff-test/commit/9f09e9cfb54a655c102157a828066713dcd483e9).

## Screenshots

test

### PR DESCRIPTION
**Pull request by zeripath**
#12771 attempted to fix diff by avoiding the git diff line as
it is possible to have an ambiguous line here.

#12254 attempted to fix diff by assuming that names would quoted
if they needed to be and if one was quoted then both would be.

Both of these were wrong.

I have now discovered `--src-prefix` and `--dst-prefix` which
means that we can set this in such a way to force the git diff
to always be unambiguous.

Therefore this PR rollsback most of the changes in #12771 and
uses these options to fix this.

Fix #13060

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: services/gitdiff/gitdiff.go [hunk 1]
```diff
@@ -610,10 +571,43 @@ func ParsePatch(maxLines, maxLineCharacters, maxFiles int, reader io.Reader) (*D
...
+			// e.g. diff --git "a/xxx" "b/xxx"
+			var a string
+			var b string
+
+			rd := strings.NewReader(line[len(cmdDiffHead):])
+			char, _ := rd.ReadByte()
+			_ = rd.UnreadByte()
+			if char == '"' {
+				fmt.Fscanf(rd, "%q ", &a)
+				fmt.Printf("read %s", a)
```
Comment (zeripath) [inline services/gitdiff/gitdiff.go]:
```suggestion
```

File: services/gitdiff/gitdiff.go [hunk 2]
```diff
@@ -762,7 +716,7 @@ func GetDiffRangeWithWhitespaceBehavior(repoPath, beforeCommitID, afterCommitID
 			parentCommit, _ := commit.Parent(0)
 			actualBeforeCommitID = parentCommit.ID.String()
 		}
-		diffArgs := []string{"diff", "-M"}
+		diffArgs := []string{"diff", "--src-prefix=\\a/", "--dst-prefix=\\d/", "-M"}
```
Comment (zeripath) [inline services/gitdiff/gitdiff.go]:
```suggestion
		diffArgs := []string{"diff", "--src-prefix=\\a/", "--dst-prefix=\\b/", "-M"}
```

File: modules/repofiles/temp_repo.go [hunk 3]
```diff
@@ -292,7 +292,7 @@ func (t *TemporaryUploadRepository) DiffIndex() (*gitdiff.Diff, error) {
 	var diff *gitdiff.Diff
 	var finalErr error
 
-	if err := git.NewCommand("diff-index", "--cached", "-p", "HEAD").
+	if err := git.NewCommand("diff-index", "--src-prefix=\\a/", "--dest-prefix=\\b/", "--cached", "-p", "HEAD").
```
Comment (zeripath) [inline modules/repofiles/temp_repo.go]:
```suggestion
	if err := git.NewCommand("diff-index", "--src-prefix=\\a/", "--dst-prefix=\\b/", "--cached", "-p", "HEAD").
```

**Comment by lafriks** [comment]
Why are rename from and rename to cases removed?

**Comment by zeripath** [comment]
Because they're no longer needed. That code was added when we couldn't get the names from the git diff line - so I've stopped back to the code that was there before. I can add them back in if preferred. 

Parsepatch needs rewriting in any case as can't parse anything with -- or ++ at the start of a line

**Review by techknowlogick — APPROVED** [review]
I've confirmed that this works on git 1.8

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
:rocket:

**Comment by lafriks** [comment]
Please send backport
