### PR TITLE
Fix #732: Add LFS objects to base repository on merging 

### LINKED ISSUE #732: LFS: Error 500 when merging pull request
- Gitea version (or commit ref): 1.0.0+144-ga8048c1 (master branch)
- Git version: 2.5.4 (Apple Git-61)
- Operating system: MacOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: 
```
2017/01/23 12:12:17 [...routers/repo/pull.go:420 MergePullRequest()] [E] Merge: git clone: Cloning into 'data/tmp/repos/216094242.git'...
done.
Downloading nofilter.mp4 (2.06 MB)
Error downloading object: nofilter.mp4 (8a870a2f4efbc72e3686c2936b24c5c6f7ebd9475e2b076bd583086e71a345cf)
```
## Description

I wanted to test the master version of Gitea in order to check the new features including LFS.
I added a new repo in Gitea, pushed a mp4 file which I did set for LFS. The file was properly pushed and stored using LFS. 

Then I branched the "master" branch into a "dev". I push a "test.html" file into the "dev" branch. Then in Gitea I created a pull request. Gitea said there were no conflict and that the branch can be merged automatically. But when merging, I got a 500 error (see log above). It seems related to the LFS. 

Dunno if I did something wrong, but seems to be a bug to me. 
Thanks

### PR DESCRIPTION
**Pull request by zeripath**
This PR Fixes #732.

It first disables the standard git-lfs filters including the missing process, (filter.lfs.process, filter.lfs.clean, filter.lfs.smudge, filter.lfs.required.) 

Then just before merging it walks the merging history ensuring that all files in the history to be merged, that are <1k, and match LFS pointer files - actually representing lfs objects in the content store are then added to the base repositories lfs objects.

~~This PR attempts to Fix #732  (Yes this bug is that old) whereby trying to merge a pull request containing LFS objects fails. This is substantially better than simply ignoring the missed filter.lfs.process which is an alternative fix as that technique likely leads to the loss of lfs objects on forked repo deletion.~~

~~The current implementation just routes the requests to the internal url for the gitea server - however this may not work if Gitea is running over a unix pipe and therefore likely requires more thought.~~

~~It does however provide a fix.~~

### CODE REVIEW

File: cmd/serv.go [hunk 1]
```diff
@@ -282,32 +280,11 @@ func runServ(c *cli.Context) error {
...
-			"nbf":  now.Unix(),
-		}
-		if user != nil {
-			claims["user"] = user.ID
-		}
-		token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
-
-		// Sign and get the complete encoded token as a string using the secret
-		tokenString, err := token.SignedString(setting.LFS.JWTSecretBytes)
+		tokenAuthentication, err := models.GenerateLFSAuthenticationToken(user, repo, lfsVerb)
```
Comment (zeripath) [inline cmd/serv.go]:
```suggestion
		repo.OwnerName = username
		tokenAuthentication, err := models.GenerateLFSAuthenticationToken(user, repo, lfsVerb)
```

File: cmd/serv.go [hunk 2]
```diff
@@ -282,32 +280,12 @@ func runServ(c *cli.Context) error {
...
-		}
-		if user != nil {
-			claims["user"] = user.ID
-		}
-		token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
-
-		// Sign and get the complete encoded token as a string using the secret
-		tokenString, err := token.SignedString(setting.LFS.JWTSecretBytes)
+		repo.OwnerName = username
+		tokenAuthentication, err := models.GenerateLFSAuthenticationToken(user, repo, lfsVerb)
```
Comment (lunny) [inline cmd/serv.go]: I think we should move `GenerateLFSAuthenticationToken` out of `models` but a sub package on `modules` maybe `generate` or `tokens`.

Comment (lunny) [inline cmd/serv.go]: Move these codes to `modules/generate`, `modules/lfs` or `modules/tokens` is better.

File: modules/merge/merge.go [hunk 3]
```diff
@@ -0,0 +1,480 @@
...
+	"io/ioutil"
+	"os"
+	"path"
+	"path/filepath"
+	"strconv"
+	"strings"
+	"sync"
+
+	"code.gitea.io/gitea/modules/lfs"
+
```
Comment (lunny) [inline modules/merge/merge.go]: blank line is uncessary.

File: cmd/serv.go (hunk 2 above)
Comment (zeripath) [reply cmd/serv.go]: I've reverted those changes - they'll conflict with #6993 and they're not needed anyway

File: modules/merge/merge.go (hunk 3 above)
Comment (zeripath) [reply modules/merge/merge.go]: done

File: modules/merge/merge.go [hunk 4]
```diff
@@ -0,0 +1,479 @@
...
+					catFileBatchReader.CloseWithError(err)
+					break
+				}
+				pointerBuf = pointerBuf[:size]
+				// now we need to check if the pointerBuf is an LFS pointer
+				pointer := lfs.IsPointerFile(&pointerBuf)
+				if pointer == nil {
+					continue
+				}
+				pointer.RepositoryID = pr.BaseRepoID
```
Comment (zeripath) [inline modules/merge/merge.go]: One thing I'm not doing here is checking that the LFS object is present in the head repo. This only checks if the LFS object is present in the store.

I could add this check if wanted.

**Comment by zeripath** [comment]
I've expanded git_test to include showing that on merging a fork the lfs objects remain available.

**Comment by zeripath** [comment]
I've also expanded the git_test to delete the repository before checking if the lfs objects are available in the merged repository.

File: modules/merge/merge.go (hunk 4 above)
Comment (zeripath) [reply modules/merge/merge.go]: I've added this check.

File: modules/merge/lfs.go [hunk 5]
```diff
@@ -0,0 +1,226 @@
...
+		_ = shasToBatchReader.CloseWithError(fmt.Errorf("git rev-list [%s]: %v - %s", tmpBasePath, err, errbuf.String()))
+	}
+}
+
+func readCatFileBatch(catFileBatchReader *io.PipeReader, wg *sync.WaitGroup, pr *models.PullRequest) {
+	defer wg.Done()
+	defer catFileBatchReader.Close()
+
+	bufferedReader := bufio.NewReader(catFileBatchReader)
+	buf := make([]byte, 1025)
```
Comment (lunny) [inline modules/merge/lfs.go]: Why not 1024? :(

File: modules/merge/lfs.go [hunk 6]
```diff
@@ -0,0 +1,226 @@
+// Copyright 2019 The Gitea Authors.
```
Comment (lunny) [inline modules/merge/lfs.go]: How about use `modules/pull` but not `modules/merge` so that we could move more pull related codes to this package.

File: modules/merge/lfs.go (hunk 5 above)
Comment (zeripath) [reply modules/merge/lfs.go]: That was a C-ism that's crept in - a string is always 1 byte longer than you think. I'll change it. 

```suggestion
	buf := make([]byte, 1024)
```

Comment (zeripath) [reply modules/merge/lfs.go]: Actually no, it does need to be there. It's because git cat-file will include a trailing newline which we need to read and discard.

Comment (zeripath) [reply modules/merge/lfs.go]:
```suggestion
	buf := make([]byte, 1025)
```

File: modules/merge/lfs.go (hunk 6 above)
Comment (zeripath) [reply modules/merge/lfs.go]: Well we could just rename this when that's done but if you prefer I can do that now.

A few of the pipelines used in the lfs code are reusable, e.g. in #7199 - so may be some of those should be moved to git (or migrated to go-git code over time.)

**Review by sapk — APPROVED** [review]
I didn't tested this but tests seems to cover the cases. Trusted LGTM.

File: modules/pull/lfs.go [hunk 7]
```diff
@@ -0,0 +1,226 @@
...
+		if has {
+			return err
+		}
+	default:
+	}
+	return nil
+}
+
+func doRevListObjects(revListWriter *io.PipeWriter, wg *sync.WaitGroup, tmpBasePath, headSHA, baseSHA string, errChan chan<- error) {
+	defer wg.Done()
```
Comment (lunny) [inline modules/pull/lfs.go:73]: How about
```go
defer func() {
  wg.Done()
  revListWriter.Close()
}()
```

**Comment by lunny** [comment]
Otherwise LGTM

File: modules/pull/lfs.go (hunk 7 above)
Comment (zeripath) [reply modules/pull/lfs.go:73]: Hmm AFAIU defers run in spite of panics. If wg.Done() panics then revListWriter will not close if we do this suggestion.

Comment (zeripath) [reply modules/pull/lfs.go:73]: (not that that particularly matters as the panic will be unrecovered in the goroutine and thus bring down gitea)
