### PR TITLE
fix: duplicate startup warnings in admin panel

### LINKED ISSUE #36630: Duplicate startup warnings in admin panel
## Description

`StartupProblems` warnings (from `deprecatedSetting` and other `LogStartupProblem` calls) appear twice in the admin panel at `/-/admin/self_check` and other places.

Image

## Cause

`LoadCommonSettings()` is called twice during web server startup:

1. Early init via `cmd/main.go:79` → `InitWorkPathAndCommonConfig` → `LoadCommonSettings()`
2. Web server startup via `cmd/web.go:167` → `LoadCommonSettings()`

The second call re-initializes the config provider first (`InitCfgProvider`), but the `StartupProblems` slice in `modules/setting/config_provider.go` is never cleared between loads, so every warning gets appended twice.

## How to reproduce

1. Add a deprecated setting to `app.ini`, e.g. `[oauth2]` → `ENABLE = true` (deprecated in favor of `ENABLED`)
2. Start Gitea
3. Go to Site Administration → the warnings section shows each warning duplicated

### PR DESCRIPTION
**Pull request by nllptrx**
Fixes #36630

## Problem

`StartupProblems` warnings (from `deprecatedSetting` and other `LogStartupProblem` calls) appear twice in the admin panel at `/-/admin` and `/-/admin/self_check`.

`LoadCommonSettings()` is called twice during web server startup:
1. Early init via `cmd/main.go` → `InitWorkPathAndCommonConfig` → `LoadCommonSettings()`
2. Web server startup via `cmd/web.go` → `serveInstalled` → `LoadCommonSettings()`

The second call re-initializes the config provider first (`InitCfgProvider`), but `StartupProblems` and `configuredPaths` are never cleared between loads, so every warning gets appended twice.

## Fix

Clear `StartupProblems` and `configuredPaths` at the start of `LoadCommonSettings()` so only the final load's warnings are retained.

This approach was chosen over clearing in `InitCfgProvider` because:
- Warnings are produced during settings load, not provider init
- Some callers set `CfgProvider` directly without calling `InitCfgProvider`
- It avoids coupling correctness to a specific call ordering

## Screenshots

**Result** (single warning as expected):
Screenshot From 2026-02-16 01-27-01

## testing

[x] Added `TestLoadCommonSettingsClearsStartupProblems` — verifies no duplicate messages after consecutive loads
[x] Added `TestLoadCommonSettingsClearsConfiguredPaths` — verifies path overlap map is identical after consecutive loads
[x] All existing `modules/setting` tests pass
[x] Manually verified in admin panel with deprecated `[oauth2].ENABLE` setting

### CODE REVIEW

File: modules/setting/setting.go [hunk 1]
```diff
@@ -101,6 +101,8 @@ func MustInstalled() {
 }
 
 func LoadCommonSettings() {
+	StartupProblems = StartupProblems[:0]
+	clear(configuredPaths)
```
Comment (silverwind) [inline modules/setting/setting.go]: This needs a comment.

**Comment by silverwind** [comment]
*Comment written by Claude (AI assistant)*

I reviewed this PR. The analysis of the double-call problem is correct:

1. `cmd/main.go` → `InitWorkPathAndCommonConfig` → `LoadCommonSettings()` (first call)
2. `cmd/web.go` → `serveInstalled` → `InitCfgProvider` + `LoadCommonSettings()` (second call)

`StartupProblems` and `configuredPaths` accumulate across both calls, causing duplicates.

The fix is minimal and placed correctly. Clearing at the start of `LoadCommonSettings` rather than in `InitCfgProvider` is the right call, since `LogStartupProblem` callers outside `LoadCommonSettings` (e.g. `services/webtheme/webtheme.go`) run later during web startup and their warnings won't be lost.

Two minor notes:

1. Using `StartupProblems[:0]` (reslice) instead of `nil` is fine — it reuses the underlying array on the next `append`, though for a startup-only slice the difference is negligible.

2. For `configuredPaths`, the `clear` is mainly about cleanliness. Without it, re-adding the same `(path, name)` pairs from the second load wouldn't trigger false overlap warnings (since `checkOverlappedPath` checks `targetName != name`), but it could mask a real overlap if a path's logical owner changed between loads. Clearing makes the final state deterministic regardless.

LGTM

File: modules/setting/setting.go [hunk 2]
```diff
@@ -101,6 +101,8 @@ func MustInstalled() {
 }
 
 func LoadCommonSettings() {
+	StartupProblems = StartupProblems[:0]
```
Comment (wxiaoguang) [inline modules/setting/setting.go]:
```suggestion
	// FIXME: the config is loaded twice during startup, maybe it is caused by the changed behavior of the cli framework, or some abuses from our code.
	// 1. cmd/main.go -> InitWorkPathAndCommonConfig -> LoadCommonSettings()
	// 2. cmd/web.go -> serveInstalled -> LoadCommonSettings()
	// Either clarify the config loading order, or migrate to a dependency-injection framework
	StartupProblems = StartupProblems[:0]
```

File: modules/setting/setting.go (hunk 1 above)
Comment (silverwind) [reply modules/setting/setting.go]: See https://github.com/go-gitea/gitea/pull/36641#discussion_r2810398175.

**Review by silverwind — APPROVED** [review]

**Comment by wxiaoguang** [comment]
I think I can spend more time on this to have a better fix (avoid duplicate calls)

I worry about the side effects of these duplicate calls, and I guess it is a problem caused by my code (introducing InitWorkPathAndCommonConfig to fix other problems)

----

Will take a look when I get some time later. Thank you all.

**Comment by silverwind** [comment]
Yeah a root cause fix would be ideal, this is just a workaround.

**Comment by wxiaoguang** [comment]
The duplicate LoadCommonSettings call is caused by Refactor to use urfave/cli/v2 (#25959) &  Refactor path & config system #25330 

I think we need to remove the LoadCommonSettings in serveInstalled. Will try

**Review by wxiaoguang — APPROVED** [review]

**Review by silverwind — APPROVED** [review]
