### PR TITLE
Offer rsa-sha2-512 and rsa-sha2-256 algorithms in internal SSH

### LINKED ISSUE #17175: key exhange negotiation failed though client and server share some protocols
### Gitea Version

1.15.3

### Git Version

2.33.0

### Operating System

CentOS 7

### How are you running Gitea?

After a openssh client upgrade, push to gitea

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

using built-in SSH server with below config:
```ini
[server]
SSH_SERVER_CIPHERS      = aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128
SSH_SERVER_KEY_EXCHANGES = curve25519-sha256 diffie-hellman-group1-sha1 diffie-hellman-group14-sha1 ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 curve25519-sha256@libssh.org ssh-rsa
```

both client and server have common algorithm, but report `no common algorithm for key exchange`
```txt
2021/09/29 10:46:19 modules/ssh/ssh.go:259:sshConnectionFailed() [W] Failed connection from 10.118.13.125:50358 with error: ssh: no common algorithm for key exchange; 
client offered: [curve25519-sha256 curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group-exchange-sha256 diffie-hellman-group16-sha512 diffie-hellman-group18-sha512 diffie-hellman-group14-sha256 ext-info-c], 
server offered: [curve25519-sha256 diffie-hellman-group1-sha1 diffie-hellman-group14-sha1 ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 curve25519-sha256@libssh.org]
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by zeripath**
There is a subtle bug in the SSH library x/crypto/ssh which makes the incorrect
assumption that the public key type is the same as the signature algorithm type.

This means that only ssh-rsa signatures are offered by default.

This PR adds a workaround around this problem.

Fix #17175

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by 6543** [comment]
Is that bug reported upstream too?

File: modules/ssh/ssh.go [hunk 1]
```diff
@@ -316,10 +316,66 @@ func Listen(host string, port int, ciphers []string, keyExchanges []string, macs
...
+					algorithm: gossh.SigAlgoRSASHA2512,
+				},
+				&wrapSigner{
+					Signer:    signer,
+					algorithm: gossh.SigAlgoRSASHA2256,
+				},
+			)
+			srv.HostSigners = append(front,
+				srv.HostSigners[i:]...,
+			)
```
Comment (wxiaoguang) [inline modules/ssh/ssh.go]: srv.HostSigners is changed here, is it still correct to continue use `i` to iterate?

Comment (zeripath) [reply modules/ssh/ssh.go]: So because of the way `SetOption(ssh.HostKeyFile(...))` works there can actually only be one `"ssh-rsa"` key thus this actually right but I'll change it to be clearer.

**Comment by zeripath** [comment]
> error log: https://hastebin.nl/CViInAB

This works on CI, running tests locally and in simple testing here. Was this on your testing?

**Review by wxiaoguang — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]
