### PR TITLE
Fix `GetCommitBranchStart` bug

### LINKED ISSUE #33265: A protected branch cannot be created from a normal branch when the protection rule includes specific file protections.
### Description

I've encountered a non-critical but illogical issue that manifests as unexpected behavior. I have a rule for the customer/ prefix that protects the core folder (details are in the screenshots). When I try to create a branch with the customer/ prefix from the master branch (which has no protections), I receive an error. The error is shown in the screenshots, and the root cause can be seen in the server logs. It looks like this:
`2025/01/14 13:54:42 .../hook_pre_receive.go:235:preReceiveBranch() [E] Unable to check file protection for commits from 0000000000000000000000000000000000000000 to 6ca0e381b177e3577f62ec9a03df8a00acb0b165 in <Repository 2:compname/reponame>: cannot find the start commit of 6ca0e381b177e3577f62ec9a03df8a00acb0b165`
`
2025/01/14 13:54:42 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/internal/hook/pre-receive/compname/reponame for 127.0.0.1:0, 500 Internal Server Error in 52.7ms @ private/hook_pre_receive.go:105(private.HookPreReceive)`

### Gitea Version

1.22.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

изображение
изображение
изображение

### Git Version

2.42.0.windows.2

### Operating System

Windows 11

### How are you running Gitea?

Use exe for win from official gitea site

### Database

PostgreSQL

### LINKED ISSUE #33370: "Protected file patterns" in Branch protections can be bypassed
### Description

I want to use "Protected file patterns" to prevent normal developers with write access to the repo from creating any commits under `~/.gitea/**` so they won't be able to create or change workflows. Like mentioned under #25423 I'm using the pattern `.gitea/**/*.*;.github/**/*.*` for this, which seems to work fine. When testing the protected file patterns logic I've found a way so a normal user can bypass it and can still change protected files.

**Steps to reproduce:**
1. Create new repository
2. Add file `hello` with dummy content and commit to main
3. Go to repository settings -> Branches and add new Branch protection rule
4. Define the following Branch protection configuration:

- Protected Branch Name Pattern: `*`
- Protected file patterns (separated using semicolon ';'): `hello`
- Enable push
- Other settings should be with default configuration

5. Save Branch protection rule
6. Go to the code in the `main` branch and edit the `hello` file
7. Commit directly to the `main` branch is not possible because of the branch protection -> that's correct
8. Now select "Create a new branch for this commit and start a pull request" at the bottom and "Commit Changes"
9. A new branch was created with a change to `hello`, therefore bypassing the branch protection rule

**Expected behavior:**
I would have expected that step 8 would fail because of the branch protection I'm not allowed to edit the `hello` file on any branch, even on new branches. But it created the commit without any error.

The same behavior can also be reproduced with the Git CLI when pushing a new branch with a new name to Gitea. I would have expected for the branch protection rule with file patterns to reject this new branch.

### Gitea Version

1.23.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Downloaded version, but it can also be reproduced with https://demo.gitea.com/

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by Zettat123**
Fix #33265
Fix #33370

This PR also fixes some bugs in `TestGitGeneral`.

### CODE REVIEW

File: modules/git/repo_commit.go [hunk 1]
```diff
@@ -533,19 +533,16 @@ func (repo *Repository) GetCommitBranchStart(env []string, branch, endCommitID s
...
-	var startCommitID string
 	for _, commitID := range parts {
 		branches, err := repo.getBranches(env, string(commitID), 2)
 		if err != nil {
 			return "", err
 		}
 		for _, b := range branches {
 			if b != branch {
-				return startCommitID, nil
+				return string(commitID), nil
```
Comment (wxiaoguang) [inline modules/git/repo_commit.go:546]: I am unable to understand what `GetCommitBranchStart` is doing here ....

The old code seems to "return the last found one", the new code seems to "return the first found one"?

Comment (Zettat123) [reply modules/git/repo_commit.go:546]: > I am unable to understand what `GetCommitBranchStart` is doing here ....

According to #31778, `GetCommitBranchStart` is used to find the divergence commit of a newly created branch. 

> The old code seems to "return the last found one", the new code seems to "return the first found one"?

The old code returns "the first commit after the divergence point", but I think here we should return "the divergence point". Because "the first commit after the divergence point" may not exist. For example, it does not exist when we create a new branch without any changes.

Comment (wxiaoguang) [reply modules/git/repo_commit.go:546]: Could there be some comments (with some examples)?

Comment (Zettat123) [reply modules/git/repo_commit.go:546]: Sure. I'll try to add some comments and test cases.

File: tests/integration/git_general_test.go [hunk 2]
```diff
@@ -466,7 +497,7 @@ func doProtectBranch(ctx APITestContext, branch, userToWhitelistPush, userToWhit
 		// Check if master branch has been locked successfully
 		flashCookie := ctx.Session.GetCookie(gitea_context.CookieNameFlash)
 		assert.NotNil(t, flashCookie)
-		assert.EqualValues(t, "success%3DBranch%2Bprotection%2Bfor%2Brule%2B%2522"+url.QueryEscape(branch)+"%2522%2Bhas%2Bbeen%2Bupdated.", flashCookie.Value)
+		assert.EqualValues(t, "success%3DBranch%2Bprotection%2Bfor%2Brule%2B%2522"+url.QueryEscape(url.QueryEscape(branch))+"%2522%2Bhas%2Bbeen%2Bupdated.", flashCookie.Value)
```
Comment (Zettat123) [inline tests/integration/git_general_test.go]: I have to escape `branch` twice here, otherwise the test will fail. The reason may be that we escaped the cookie value twice:

https://github.com/go-gitea/gitea/blob/7582eb0419cda6dbd6b4bc1326a7e8d1533ecb6b/services/context/context.go#L184

https://github.com/go-gitea/gitea/blob/7582eb0419cda6dbd6b4bc1326a7e8d1533ecb6b/modules/web/middleware/cookie.go#L44

File: tests/integration/git_general_test.go [hunk 3]
```diff
@@ -336,7 +366,7 @@ func doBranchProtectPRMerge(baseCtx *APITestContext, dstPath string) func(t *tes
 
 		// Protect branch without any whitelisting
 		t.Run("ProtectBranchNoWhitelist", func(t *testing.T) {
-			doProtectBranch(ctx, "protected", "", "", "")
+			doProtectBranch(ctx, "protected", "", "", "", "")
```
Comment (Zettat123) [inline tests/integration/git_general_test.go]: Maybe I found some other problems. Will the branch protection rule be created? Should this be `doProtectBranch(ctx, "protected", "", "", "", "")(t)` ?

Comment (lunny) [reply tests/integration/git_general_test.go]: I can confirm they are bugs. Maybe you can fix them in the same PR.

Comment (Zettat123) [reply tests/integration/git_general_test.go]: Fixed in 693a225af7002bb0ca7964f43ef199ba519e9006

File: tests/integration/git_general_test.go (hunk 2 above)
Comment (lunny) [reply tests/integration/git_general_test.go]: So that's another bug? Can you create an issue for that.

Comment (Zettat123) [reply tests/integration/git_general_test.go]: I created an issue for this. See #33372

Comment (wxiaoguang) [reply tests/integration/git_general_test.go]: Actually, I think you need this:  Refactor context flash msg #33375

File: modules/git/repo_commit.go [hunk 4]
```diff
@@ -533,19 +534,18 @@ func (repo *Repository) GetCommitBranchStart(env []string, branch, endCommitID s
...
 
-	var startCommitID string
+	// check the commits one by one until we find a commit contained by another branch
+	// and we think this commit is the divergence point
 	for _, commitID := range parts {
 		branches, err := repo.getBranches(env, string(commitID), 2)
 		if err != nil {
 			return "", err
 		}
 		for _, b := range branches {
```
Comment (lunny) [inline modules/git/repo_commit.go:544]: Maybe we can use len(branches) >1 here

**Review by lunny — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]
