### PR TITLE
Fix markup init after issue comment editing

### LINKED ISSUE #35533: Mermaid diagrams get stuck on loading after an edit
### Description

Bug: When you add a Mermaid diagram while editing an issue, it gets stuck on a loading spinner after you save.

### Gitea Version

f09bea7af13bd00d07a34252468389d15de39a8d

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Steps to Reproduce:

1. Create a new issue.
2. Edit the issue and add a Mermaid block (e.g., graph TD; A-->B;).
3. Save the change.

Result: The diagram never loads. It should render correctly.

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #35533

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

File: web_src/js/features/repo-issue-edit.ts [hunk 1]
```diff
@@ -47,30 +47,32 @@ async function tryOnEditContent(e: DOMEvent<MouseEvent>) {
...
-        showErrorToast(data.errorMessage);
+      if (!response.ok) {
+        showErrorToast(data?.errorMessage ?? window.config.i18n.error_occurred);
         return;
       }
+
       reinitializeAreYouSure(editContentZone.querySelector('form')); // the form is no longer dirty
       editContentZone.setAttribute('data-content-version', data.contentVersion);
-      if (!data.content) {
-        renderContent.innerHTML = document.querySelector('#no-content').innerHTML;
```
Comment (wxiaoguang) [inline web_src/js/features/repo-issue-edit.ts:57]: Backend always responds correct "data.content" (see `UpdateCommentContent`)

So `no-content` is not needed anymore.

**Review by lunny — APPROVED** [review]
