### PR TITLE
Fix forked repositories missed tags

### LINKED ISSUE #18715: Tags and Releases missing after fork
### Gitea Version

1.17.0+dev-145-g165ab17a0 

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Verified with gitea 1.16.1 running as docker and with try.gitea.io

### Database

_No response_

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Description

When forking a repository with Tags and Releases they are not shown under Tags or Releases. But at least the Tags can be selected in the code view. See Screenshot. Can be seen here: https://try.gitea.io/Monty/testing-fork/tags

When mirroring the same repository it is working: https://try.gitea.io/Monty/testing-mirror/tags

### Screenshots

image

### PR DESCRIPTION
**Pull request by lunny**
Fix #18715

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
I'm not sure if this really should be allowed to fail

File: services/repository/fork.go [hunk 1]
```diff
@@ -143,7 +143,17 @@ func ForkRepository(doer, owner *user_model.User, opts ForkRepoOptions) (_ *repo
 		log.Error("Failed to update size for repository: %v", err)
 	}
 	if err := repo_model.CopyLanguageStat(opts.BaseRepo, repo); err != nil {
-		log.Error("Copy language stat from oldRepo failed")
+		log.Error("Copy language stat from oldRepo failed: %v", err)
+	}
+
+	gitRepo, err := git.OpenRepository(repo.RepoPath())
```
Comment (6543) [inline services/repository/fork.go]: open with context

**Review by 6543 — APPROVED** [review]

**Comment by lunny** [comment]
> I'm not sure if this really should be allowed to fail

I have tried this, it will change more code than my predict. So I will keep this PR as it. I will open another PR to do that.
