### PR TITLE
Fix LDAP sync when Username Attribute is empty

### LINKED ISSUE #21072: LDAP sync not working if Username Attribute not specified
### Description

When LDAP Authentication configured only with required fields, sync_external_users not creating accounts.
Enable user synchronization option is checked.

When trying to login with user from connected LDAP, new user is created with username taken from uid probably.
On the next sync this user is marked as inactive.

It either [documentation](https://docs.gitea.io/en-us/authentication/#ldap-via-binddn) problem or a bug.

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Using compose file

```yaml
---
version: "2"

services:
  db:
    image: bitnami/postgresql:latest
    user: 1001
    environment:
      - POSTGRESQL_USER=gitea
      - POSTGRESQL_PASSWORD=gitea
      - POSTGRESQL_DATABASE=gitea
    networks:
      - gitea-network

  gitea:
    image: gitea/gitea:1.17.1-rootless
    user: 1000:1000
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    volumes:
      - ./gitea-config:/etc/gitea
      - ./gitea-data:/var/lib/gitea
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - gitea-network

  ldap1:
    image: glauth/glauth
    user: 1000
    volumes:
      - ./ldap-config.cfg:/app/config/config.cfg
    networks:
      - gitea-network
```

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by Zettat123**
Fix #21072

image

Username Attribute is not a required item when creating an authentication source. If Username Attribute is empty, the username value of LDAP user cannot be read, so all users from LDAP will be marked as inactive by mistake when synchronizing external users.

This PR improves the sync logic, if username is empty, the email address will be used to find user.

### CODE REVIEW

File: tests/integration/auth_ldap_test.go [hunk 1]
```diff
@@ -268,6 +268,30 @@ func TestLDAPUserSync(t *testing.T) {
...
+	req := NewRequestWithValues(t, "POST", "/admin/auths/new", payload)
+	session.MakeRequest(t, req, http.StatusSeeOther)
+
+	for _, u := range gitLDAPUsers {
+		req := NewRequest(t, "GET", "/admin/users?q="+u.UserName)
+		resp := session.MakeRequest(t, req, http.StatusOK)
+
+		htmlDoc := NewHTMLParser(t, resp.Body)
+
+		tr := htmlDoc.doc.Find("table.table tbody tr")
```
Comment (silverwind) [inline tests/integration/auth_ldap_test.go:291]: Is a better selector possible? Maybe by adding a unique class to that table and then selecting as `.users-table tr`?

Comment (Zettat123) [reply tests/integration/auth_ldap_test.go:291]: Hmm I agree that `.users-table tr` is a better selector. But this PR is for an LDAP issue, I think maybe it would be better to send another PR to improve the selector?

Comment (silverwind) [reply tests/integration/auth_ldap_test.go:291]: Well, I don't strictly require this here I guess.

File: tests/integration/auth_ldap_test.go [hunk 2]
```diff
@@ -268,6 +268,49 @@ func TestLDAPUserSync(t *testing.T) {
...
+		assert.True(t, tr.Length() == 0)
+	}
+
+	for _, u := range gitLDAPUsers {
```
Comment (lunny) [inline tests/integration/auth_ldap_test.go:295]: How many users in this test LDAP server? Could we have an assert for the user count?

Comment (Zettat123) [reply tests/integration/auth_ldap_test.go:295]: 5 users. Add the assert of user count in c8e6607d54013999a3de3ac46686f331e44382a8

**Review by lunny — APPROVED** [review]

File: services/auth/source/ldap/source_sync.go [hunk 3]
```diff
@@ -41,9 +39,15 @@ func (source *Source) Sync(ctx context.Context, updateExisting bool) error {
...
-		return users[i].LowerName < users[j].LowerName
-	})
+	usernameUsers := make(map[string]*user_model.User, len(users))
+	mailUsers := make(map[string]*user_model.User, len(users))
+	existingUsers := make(map[int64]struct{})
+
+	for i := range users {
+		u := users[i]
+		usernameUsers[u.LowerName] = u
+		mailUsers[u.Email] = u
```
Comment (wxiaoguang) [inline services/auth/source/ldap/source_sync.go]: Are the `Email` and `Mail` case-sensitive or case-insensitive?

File: services/auth/source/ldap/source_sync.go [hunk 4]
```diff
@@ -41,9 +39,15 @@ func (source *Source) Sync(ctx context.Context, updateExisting bool) error {
...
 
-	sort.Slice(users, func(i, j int) bool {
-		return users[i].LowerName < users[j].LowerName
-	})
+	usernameUsers := make(map[string]*user_model.User, len(users))
+	mailUsers := make(map[string]*user_model.User, len(users))
+	existingUsers := make(map[int64]struct{})
+
+	for i := range users {
+		u := users[i]
```
Comment (wxiaoguang) [inline services/auth/source/ldap/source_sync.go]:
```suggestion
	for _, u := range users {
```

I guess Golang likes this syntax (and below) (well, not a must)

File: services/auth/source/ldap/source_sync.go [hunk 5]
```diff
@@ -203,19 +204,18 @@ func (source *Source) Sync(ctx context.Context, updateExisting bool) error {
...
 	// Deactivate users not present in LDAP
 	if updateExisting {
-		existPos := 0
-		for i, usr := range users {
-			for existPos < len(existingUsers) && i > existingUsers[existPos] {
-				existPos++
+		for i := range users {
+			usr := users[i]
+			if _, ok := existingUsers[usr.ID]; ok {
+				continue
```
Comment (wxiaoguang) [inline services/auth/source/ldap/source_sync.go]: The name of `existingUsers` seems a little misleading (existing in database or existing in LDAP?), I read many times to know what it means.

It doesn't mean existing in database nor existing in LDAP, it means "the user can be considered as active in Gitea's database, because it has proper username or email"

I think it needs some comments and maybe a new name is better (eg: "keepActiveUsers")

Or maybe there could be a slice for the "usersToDeactive":

```go
	if usr == nil {
		usersToDeactive = append(usersToDeactive, u)
	}
...
	if updateExisting {
		for _, usr := range usersToDeactive {
			usr.IsActive = false
			err = user_model.UpdateUserCols(ctx, usr, "is_active")
		}
	}
```

File: services/auth/source/ldap/source_sync.go (hunk 3 above)
Comment (Zettat123) [reply services/auth/source/ldap/source_sync.go]: The `Mail` from LDAP might contain uppercase letters so I think we should convert them to lowercase before comparing.
Done in 003ea013cc019eed323473f604f8da4050f44442

File: services/auth/source/ldap/source_sync.go (hunk 5 above)
Comment (Zettat123) [reply services/auth/source/ldap/source_sync.go]: `existingUsers` has been renamed to `keepActiveUsers`

File: services/auth/source/ldap/source_sync.go (hunk 4 above)
Comment (Zettat123) [reply services/auth/source/ldap/source_sync.go]: fixed in e50f6d0c3880937ae5ff4745872402740e73724c and 99ee376ec49f92e239c4aed491443ba2e613c6ab

**Review by silverwind — APPROVED** [review]
