### PR TITLE
Fix code owners will not be mentioned when a pull request comes from a forked repository

### LINKED ISSUE #30277: Gitea does not apply CODEOWNERS for PRs from forks
### Description

If you create a pull request from a fork Gitea won't apply the CODEOWNERS. They only work for PRs from origin to origin.

### Gitea Version

1.21.10

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

```yaml
version: '3'

services:
  gitea:
    image: gitea/gitea
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE=false
    restart: always
    networks:
      - gitea
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  gitea:

volumes:
  gitea-data:
  postgres-data:
```

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix #30277
Caused by #29783

### CODE REVIEW

File: services/issue/pull.go [hunk 1]
```diff
@@ -51,14 +51,14 @@ func PullRequestCodeOwnersReview(ctx context.Context, issue *issues_model.Issue,
...
-		return nil, nil
-	}
-
 	if err := pr.LoadBaseRepo(ctx); err != nil {
 		return nil, err
 	}
 
+	if pr.BaseRepo.IsFork {
+		return nil, nil
+	}
```
Comment (delvh) [inline services/issue/pull.go:60]: That sounds equally wrong:
If we have base repo `A`, fork `B`, and fork `C` of `B`, then PRs from `C` to `B` don't notify code reviewers?
I'd expect one of two things here:
Either we say that the fork does not touch the codeowners file in which case we don't want to trigger notifications, or it modifies it to its likings in which case we do want notifications.
Sounds a bit like the only way to fix this is by adding a setting that is only available for forks, namely whether CODEOWNERS should be honored.
The default value should probably be `false`

Comment (delvh) [reply services/issue/pull.go:60]: For now, it probably suffices if we add this comment ↑ as a TODO above these lines

Comment (lunny) [reply services/issue/pull.go:60]: Because codowner should only for base repository's pull requests. So yes, if you send pull requests from C -> B or from B -> B, the code owners will not triggered.

The files will always be read from base repository.

Comment (wolfogre) [reply services/issue/pull.go:60]: I don't think we need to do anything more for forked repositories except ensure that CODEOWNERS doesn't take effect in them.

If users fork a repo to submit PRs to upstream, they don't care about CODEOWNERS in the fork.

If users fork a repo to start a new fire with new CODEOWNERS, I don't think they will really fork it, they will clone, rename, and create a new repo.

**Review by wolfogre — APPROVED** [review]

File: tests/integration/pull_review_test.go [hunk 2]
```diff
@@ -161,10 +161,18 @@ func TestPullView_CodeOwner(t *testing.T) {
 			assert.NoError(t, err)
 
 			session := loginUser(t, "user5")
-			testPullCreate(t, session, "user5", "test_codeowner", true, forkedRepo.DefaultBranch, "codeowner-basebranch-forked", "Test Pull Request2")
+
+			// create a pull request on the forked repository, code reviewers should not be mentioned
+			testPullCreateDirectly(t, session, "user5", "test_codeowner", forkedRepo.DefaultBranch, "", "", "codeowner-basebranch-forked", "Test Pull Request2")
```
Comment (yp05327) [inline tests/integration/pull_review_test.go]: title can be `Test Pull Request Fork`, as we already have `Test Pull Request2` in L136
Also, use `forkedRepo.OwnerName` and `forkedRepo.Name` can be more readable.

**Review by yp05327 — APPROVED** [review]
