### PR TITLE
fix: auto-expand and auto-scroll for actions logs (#35570)

### LINKED ISSUE #35570: Actions logs auto-scroll/auto-expand not working
### Description

It doesn't seem like the auto-scroll/auto-expand feature of the actions logs page is working as intended, even with those options checked.

If I refresh the page while it is running it will expand just one section and leave the others collapsed. Otherwise it all stays closed.

The first time it needs to auto-scroll it will but will not thereafter.

### Gitea Version

1.25.0-rc1

### Can you reproduce the bug on the Gitea demo site?

No (no actions runners set up)

### Log Gist

No browser console logs.

### Screenshots

This is if I do nothing after starting the workflow:

Image

This is if I expand the "Set up job" section. Note the position of the scrollbar.

Image

### Git Version

2.39.5

### Operating System

Debian 12

### How are you running Gitea?

Binary download running as a systemd service.

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by ita004**
### **Description:**

Implements reliable auto-expand and auto-scroll behavior for the Actions logs view.

* Expands running or unfinished steps automatically.
* Smoothly scrolls to the latest log line during execution.
* Controlled via existing “Always auto-scroll” and “Expand running steps” options.

Fixes #35570.

### CODE REVIEW

File: web_src/js/components/RepoActionView.vue [hunk 1]
```diff
@@ -185,11 +186,72 @@ export default defineComponent({
...
     this.hashChangeListener();
     window.addEventListener('hashchange', this.hashChangeListener);
+
+    // === Auto Expand + Auto Scroll Fix (for Issue #35570) ===
+    // Ensure Vue has updated DOM for steps after initial load
+    await nextTick();
+
+    // Set up observer on the steps container (safer and more efficient than document.body)
+    const stepsContainer = (this.$refs.steps as HTMLElement);
+    if (stepsContainer && typeof MutationObserver !== 'undefined') {
```
Comment (silverwind) [inline web_src/js/components/RepoActionView.vue]:
```suggestion
    if (stepsContainer && 'MutationObserver' in window) {
```

matches other `MutationObserver` usages.

**Comment by silverwind** [comment]
Hmm is there no other way than `MutationObserver`? Isn't the class change that it's observing triggered by our JS?

**Comment by ita004** [comment]
> Hmm is there no other way than `MutationObserver`? Isn't the class change that it's observing triggered by our JS?

thanks for the suggestion...have removed the MutationObserver entirely, the auto-expand behavior is now handled directly within loadJob() based on state changes...simplifying the logic and keeping it consistent with the rest of the component’s approach...

File: web_src/js/components/RepoActionView.vue [hunk 2]
```diff
@@ -360,6 +360,19 @@ export default defineComponent({
...
         }
 
+        // Auto-expand running steps if option is enabled (fix for Issue #35570)
+        for (let i = 0; i < this.currentJob.steps.length; i++) {
+          const step = this.currentJob.steps[i];
+          const state = this.currentJobStepsStates[i];
+          if (
+            this.optionAlwaysExpandRunning &&
+            step.status === 'running' &&
+            !state.expanded
```
Comment (wxiaoguang) [inline web_src/js/components/RepoActionView.vue]: It will cause problems if a step has been manually collapsed. Then the step will always be expanded again which will annoy end users.

Will make some improvements.

**Comment by wxiaoguang** [comment]
Made some improvements, and you can test the behavior by `http://localhost:3000/devtest/repo-action-view/`

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
Unfortunately, this PR causes the automatic loading of the actions log to stop working.

**Comment by wxiaoguang** [comment]
> Unfortunately, this PR causes the automatic loading of the actions log to stop working.

How to reproduce?

**Comment by ita004** [comment]
> Unfortunately, this PR causes the automatic loading of the actions log to stop working.

it looks like the MutationObserver or auto-expand hook is interfering with the log streaming/polling lifecycle...??

**Comment by wxiaoguang** [comment]
> > Unfortunately, this PR causes the automatic loading of the actions log to stop working.
> 
> it looks like the MutationObserver or auto-expand hook is interfering with the log streaming/polling lifecycle...??

There is no MutationObserver or auto-expand hook. The changed logic :

* https://github.com/go-gitea/gitea/pull/35583/files#diff-c3422631a14edbe1e508c4b22f0c718db318be08a6e889427802f9b6165d88d6R382-R386
    * added the "else" to auto-expand more cases

* https://github.com/go-gitea/gitea/pull/35583/files#diff-c3422631a14edbe1e508c4b22f0c718db318be08a6e889427802f9b6165d88d6R410-R413
    * relax the scroll check

Other changes seem trivial.

**Comment by lunny** [comment]
> > Unfortunately, this PR causes the automatic loading of the actions log to stop working.
> 
> How to reproduce?

Pushing a commit which can trigger any action task and stay in the page of the action logs. Before 0a0baeb, the logs will be loaded automatically. After this commit, it will not load logs.

**Comment by wxiaoguang** [comment]
> > > Unfortunately, this PR causes the automatic loading of the actions log to stop working.
> > 
> > 
> > How to reproduce?
> 
> Pushing a commit which can trigger any action task and stay in the page of the action logs. Before [0a0baeb](https://github.com/go-gitea/gitea/commit/0a0baeb3b020bb4ca89af205cc9660ef3585fc37), the logs will be loaded automatically. After this commit, it will not load logs.

Screenshot? Console error?

**Comment by wxiaoguang** [comment]
> > > Unfortunately, this PR causes the automatic loading of the actions log to stop working.
> > 
> > 
> > How to reproduce?
> 
> Pushing a commit which can trigger any action task and stay in the page of the action logs. Before [0a0baeb](https://github.com/go-gitea/gitea/commit/0a0baeb3b020bb4ca89af205cc9660ef3585fc37), the logs will be loaded automatically. After this commit, it will not load logs.

If you only see the problem for "new tasks" by "staying on the empty page". Maybe it is related to `elStepsContainer`: if there is no step, then the container is undefined.

Please confirm, or provide more details.

**Comment by wxiaoguang** [comment]
Try by guess:  Always create Actions logs stepsContainer #35654

**Comment by lunny** [comment]
> > > > Unfortunately, this PR causes the automatic loading of the actions log to stop working.
> > > 
> > > 
> > > How to reproduce?
> > 
> > 
> > Pushing a commit which can trigger any action task and stay in the page of the action logs. Before [0a0baeb](https://github.com/go-gitea/gitea/commit/0a0baeb3b020bb4ca89af205cc9660ef3585fc37), the logs will be loaded automatically. After this commit, it will not load logs.
> 
> Screenshot? Console error?

console error.
image
