### PR TITLE
Fix paging of file commit logs

### LINKED ISSUE #8716: The pagination result of commit history is incorrect
- Gitea version (or commit ref): 1.10.0 / e3875ac
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://gitea.com/gitea/gitea_mirror/commits/branch/master/models/action.go?page=1
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A
## Description
Duplicate commits appear on each page
## Screenshots
Page1:

Page5:

### PR DESCRIPTION
**Pull request by zeripath**
Unfortunately `git log revision ... --skip=x -- path` skips the number of commits from the revision's history
not the number of commits relating to the path.

This PR changes the function to have a reader that reads and skips the
necessary number of commits by hand instead.

Fix #8716

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: modules/git/repo_commit.go [hunk 1]
```diff
@@ -232,8 +234,42 @@ func (repo *Repository) FileCommitsCount(revision, file string) (int64, error) {
...
+			if err != nil {
+				if err == io.ErrUnexpectedEOF {
+					break
+				}
+				_ = stdoutReader.CloseWithError(err)
+				return nil, err
+			}
+			skip--
+		}
+	}
```
Comment (6543) [inline modules/git/repo_commit.go]:
```suggestion
	if skip > 0 {
		_, err := io.CopyN(ioutil.Discard, stdoutReader, int64(skip*41))
		if err != nil {
			if err == io.EOF {
				return list.New(), nil
			}
			_ = stdoutReader.CloseWithError(err)
			return nil, err
		}
	}
```

**Review by 6543 — APPROVED** [review]
works :rocket:

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
please send backport
