### PR TITLE
Extend comment treepath length

### LINKED ISSUE #33716: Creating comment on a file with filename+path longer than 256 chars leads to 500 internal server error
### Description

We have some files which including path and file names are having more than 256 chars in length. After trying to create comment on such files we receive 500 internal server error:

```
500 Internal Server Error

An error occurred:

CreateCodeComment, pq: value too long for type character varying(255)

Gitea Version: 1.23.1
```

Is this soft or hard limit of gitea? Can it be adjusted to allow more characters?
On our postgresql we see that there's character limit including the comment table:

```
SELECT table_name, column_name, character_maximum_length
FROM information_schema.columns
WHERE table_schema = 'public'
AND character_maximum_length = 255;

---------------------------+-----------------------+--------------------------
        table_name         |      column_name      | character_maximum_length
---------------------------+-----------------------+--------------------------
...
 comment                   | old_title             |                      255
 comment                   | new_title             |                      255
 comment                   | old_ref               |                      255
 comment                   | new_ref               |                      255
 comment                   | tree_path             |                      255
```

Is tree_path parameter responsible for this issue? so comment cannot be created when the tree_path exceeds 255 characters?
Is this parameter adjustable or it can negatively impact the overall gitea functionality?
And if there are allowed files with longer filepath+filename length why commenting them leads to error? Shouldn't be this limit adjustable according to allowed length of filepath+filename?

PS: Issue cannot be reproduced on gitea demo site as the site is down.

### Gitea Version

1.23.1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

Image

### Git Version

v2.34.1 

### Operating System

Ubuntu 22.04.3 LTS

### How are you running Gitea?

We use one of your downloads for gitea binary (v1.23.1) and run it on our servers.
It's being run as systemd service

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by lunny**
Extend the maximum length of comment.treepath from 255 to 4000 characters.

All databases supported by Gitea allow VARCHAR fields of 4000, so compatibility is ensured. Git itself does not impose a strict limit on path length. On Windows, the `core.longpaths` setting has already been enabled to handle long file paths.

Fix #33716

### CODE REVIEW

File: models/issues/comment.go [hunk 1]
```diff
@@ -279,8 +279,8 @@ type Comment struct {
 	DependentIssue   *Issue `xorm:"-"`
 
 	CommitID        int64
-	Line            int64 // - previous line / + proposed line
-	TreePath        string
+	Line            int64         // - previous line / + proposed line
+	TreePath        string        `xorm:"VARCHAR(1024)"`
```
Comment (wxiaoguang) [inline models/issues/comment.go]: Would you like to do some research about:

* What's the max length of a git path
* What's the max limit of VARCHAR

?

Comment (lunny) [reply models/issues/comment.go]: https://github.com/go-gitea/gitea/pull/35389#issue-3369631561

File: models/migrations/migrations.go [hunk 2]
```diff
@@ -393,6 +393,7 @@ func prepareMigrationTasks() []*migration {
 
 		// Gitea 1.24.0 ends at database version 321
 		newMigration(321, "Use LONGTEXT for some columns and fix review_state.updated_files column", v1_25.UseLongTextInSomeColumnsAndFixBugs),
+		newMigration(322, "Extend comment treepath length to 1024", v1_25.ExtendCommentTreePathLength),
```
Comment (wxiaoguang) [inline models/migrations/migrations.go]:
```suggestion
		newMigration(322, "Extend comment tree_path length limit", v1_25.ExtendCommentTreePathLength),
```

File: models/migrations/v1_25/v322.go [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+	"xorm.io/xorm/schemas"
+)
+
+func ExtendCommentTreePathLength(x *xorm.Engine) error {
+	return base.ModifyColumn(x, "comment", &schemas.Column{
+		Name: "tree_path",
+		SQLType: schemas.SQLType{
+			Name: "VARCHAR",
+		},
+		Length:         4096,
```
Comment (wxiaoguang) [inline models/migrations/v1_25/v322.go]:
```suggestion
		Length:         4000,
```

File: models/issues/comment.go [hunk 4]
```diff
@@ -279,8 +279,8 @@ type Comment struct {
 	DependentIssue   *Issue `xorm:"-"`
 
 	CommitID        int64
-	Line            int64 // - previous line / + proposed line
-	TreePath        string
+	Line            int64         // - previous line / + proposed line
+	TreePath        string        `xorm:"VARCHAR(4096)"`
```
Comment (wxiaoguang) [inline models/issues/comment.go]:
```suggestion
	TreePath        string        `xorm:"VARCHAR(4096)"` // SQLServer only supports up to 4000
```

File: models/issues/comment.go [hunk 5]
```diff
@@ -279,8 +279,8 @@ type Comment struct {
 	DependentIssue   *Issue `xorm:"-"`
 
 	CommitID        int64
-	Line            int64 // - previous line / + proposed line
-	TreePath        string
+	Line            int64         // - previous line / + proposed line
+	TreePath        string        `xorm:"VARCHAR(4096)"` // SQLServer only supports up to 4000
```
Comment (wxiaoguang) [inline models/issues/comment.go]:
```suggestion
	TreePath        string        `xorm:"VARCHAR(4000)"` // SQLServer only supports up to 4000
```

**Review by silverwind — APPROVED** [review]

**Review by hiifong — APPROVED** [review]
