### PR TITLE
Fix milestone num_issues

### LINKED ISSUE #8190: Wrong count of issues in milestones
Gitea ver : 8b54b58 on gitea.com

Just noticed that milestone count and graph showing wrong open issues. This mostly happens when change ms of issues.

ms

cc @lunny

### PR DESCRIPTION
**Pull request by lunny**
Should fix #8190

### CODE REVIEW

File: models/issue_milestone.go [hunk 1]
```diff
@@ -311,71 +311,57 @@ func ChangeMilestoneStatus(m *Milestone, isClosed bool) (err error) {
...
 			return err
 		}
-
-		m.NumIssues--
-		if issue.IsClosed {
-			m.NumClosedIssues--
-		}
-
-		if err = updateMilestone(e, m); err != nil {
+		if err := updateMilestoneClosedNum(e, oldMilestoneID); err != nil {
```
Comment (guillep2k) [inline models/issue_milestone.go]: It looks like this will execute always, whether the issue closed status has changed or not.

File: models/issue_milestone.go [hunk 2]
```diff
@@ -311,71 +311,57 @@ func ChangeMilestoneStatus(m *Milestone, isClosed bool) (err error) {
...
 			return err
 		}
-
-		m.NumIssues++
-		if issue.IsClosed {
-			m.NumClosedIssues++
-		}
-
-		if err = updateMilestone(e, m); err != nil {
+		if err := updateMilestoneClosedNum(e, issue.MilestoneID); err != nil {
```
Comment (guillep2k) [inline models/issue_milestone.go]: Same here. If the issue is not closed, I think this function should not be called.

File: models/issue_milestone.go (hunk 1 above)
Comment (lunny) [reply models/issue_milestone.go]: No. The function `changeMilestoneAssign` will only be invoked when issues/pulls status changed.

File: models/issue_milestone.go (hunk 2 above)
Comment (lunny) [reply models/issue_milestone.go]: As above.

File: models/issue_milestone.go (hunk 1 above)
Comment (guillep2k) [reply models/issue_milestone.go]: Isn't `changeMilestoneAssign()` used to move the target milestone of the issue? (e.g. 1.10.0 --> 1.11.0).
I've just set a breakpoint on the function and set a new milestone for one issue. The function was definitely called, and the issue never changed its `IsClosed` status.

Comment (lunny) [reply models/issue_milestone.go]: see line 336, this will be invoked only `if oldMilestoneID > 0 {`

**Comment by lunny** [comment]
Forgot update `completeness`.

File: models/issue_milestone.go (hunk 1 above)
Comment (guillep2k) [reply models/issue_milestone.go]: `oldMilestoneID > 0` != `isClosed`
I'm probably misunderstanding something but what I mean is:
* Milestone `1.10.0` has `ID`: 4; milestone `1.11.0` has `ID`: 5.
* Create issue `#123`; assign to milestone `1.10.0` (issue.MilestoneID=4).
    * `1.10.0` ==> num_issues = 1, num_closed_issues = 0
    * `1.11.0` ==> num_issues = 0, num_closed_issues = 0
* Edit issue `#123`; change milestone from `1.10.0` to `1.11.0`.

Now `changeMilestoneAssign()` is called with issue.MilestoneID=5, oldMilestoneID = 4, and issue.IsClosed = false. We expect:

* `1.10.0` ==> num_issues = 0, num_closed_issues = 0
* `1.11.0` ==> num_issues = 1, num_closed_issues = 0

In no case `num_closed_issues` should be updated, but `oldMilestoneID > 0` and `updateMilestoneClosedNum()` is called.

**Comment by lunny** [comment]
@guillep2k You are right. Done.

File: models/issue_milestone.go (hunk 2 above)
Comment (lunny) [reply models/issue_milestone.go]: This one is different from previous one. This function is `changeStatus` which will be invoked when issue is closed or reopened.

File: models/issue_milestone.go [hunk 3]
```diff
@@ -311,71 +311,61 @@ func ChangeMilestoneStatus(m *Milestone, isClosed bool) (err error) {
...
-
-	if issue.IsClosed {
-		m.NumOpenIssues--
-		m.NumClosedIssues++
-	} else {
-		m.NumOpenIssues++
-		m.NumClosedIssues--
-	}
+func updateMilestoneTotalNum(e Engine, milestoneID int64) (err error) {
+	_, err = e.Exec("UPDATE `milestone` SET num_issues=(SELECT count(*) FROM issue WHERE milestone_id=?), completeness=if(num_issues>0,100*num_closed_issues/num_issues, 0) WHERE id=?",
```
Comment (guillep2k) [inline models/issue_milestone.go]: I'm afraid `completeness` will lag behind one issue. It may be engine dependent, but i think that `num_issues` on the right is evaluated before `num_issues` on the left is updated. `completeness` is not currently checked in any tests, AFAIK.

Comment (guillep2k) [reply models/issue_milestone.go]: To solve the division by 0 without using `if()`, you could use:
```
UPDATE milestone SET num_issues=(SELECT count(*) FROM issue WHERE milestone_id=?),
completeness = 100*num_closed_issues/(num_issues+1-sign(num_issues)) WHERE id=?;
```

Comment (guillep2k) [reply models/issue_milestone.go]: However it does lag one value behind:
```
; First, a milestone with wrong value in num_issues:
giteatest=> select id, name, num_issues, num_closed_issues, completeness
    from milestone where id = 1;
 id |      name       | num_issues | num_closed_issues | completeness
----+-----------------+------------+-------------------+--------------
  1 | First milestone |          0 |                 1 |           50
(1 row)

; Run the UPDATE for the first time
giteatest=> UPDATE milestone SET num_issues=(SELECT count(*) FROM issue WHERE milestone_id=1),
    completeness = 100*num_closed_issues/(num_issues+1-sign(num_issues)) WHERE id=1;
UPDATE 1

; The UPDATE corrected the value for num_issues, but completeness was calculated using
; the previous value in num_issues
giteatest=> select id, name, num_issues, num_closed_issues, completeness
    from milestone where id = 1;
 id |      name       | num_issues | num_closed_issues | completeness
----+-----------------+------------+-------------------+--------------
  1 | First milestone |          2 |                 1 |          100
(1 row)

; Run the same UPDATE a second time.
giteatest=> UPDATE milestone SET num_issues=(SELECT count(*) FROM issue WHERE milestone_id=1),
    completeness = 100*num_closed_issues/(num_issues+1-sign(num_issues)) WHERE id=1;
UPDATE 1

; Now completeness is calculated correctly
; because num_issues already had the right value.
giteatest=> select id, name, num_issues, num_closed_issues, completeness
    from milestone where id = 1;
 id |      name       | num_issues | num_closed_issues | completeness
----+-----------------+------------+-------------------+--------------
  1 | First milestone |          2 |                 1 |           50
(1 row)
```

Comment (guillep2k) [reply models/issue_milestone.go]: I think your best bet is to use an UPDATE JOIN. The following works correctly in every case:

```
UPDATE milestone
SET num_issues=c.issues, num_closed_issues=c.closed_issues,
    completeness = 100*c.closed_issues/(c.issues+1-sign(c.issues))
FROM (SELECT count(*) as issues,
      SUM(CASE is_closed WHEN true THEN 1 ELSE 0 END) as closed_issues
      FROM issue WHERE milestone_id = ?) as c
WHERE id = ?;
```

**Comment by techknowlogick** [comment]
CI Fail

File: models/issue_milestone.go (hunk 3 above)
Comment (lunny) [reply models/issue_milestone.go]: @guillep2k But it seems not all databases support the SQL well.

Comment (guillep2k) [reply models/issue_milestone.go]: Yeah, I see that sqlite3 can't handle that. 😞

**Comment by lunny** [comment]
It seems sqlite didn't support `sign` function.
```
--- FAIL: TestUpdateIssuesCommit (0.01s)
    action_test.go:277: 
        	Error Trace:	action_test.go:277
        	Error:      	Received unexpected error:
        	            	no such function: sign
        	Test:       	TestUpdateIssuesCommit
```

**Comment by guillep2k** [comment]
> 
> 
> It seems sqlite didn't support `sign` function.
> 
> ```
> --- FAIL: TestUpdateIssuesCommit (0.01s)
>     action_test.go:277: 
>         	Error Trace:	action_test.go:277
>         	Error:      	Received unexpected error:
>         	            	no such function: sign
>         	Test:       	TestUpdateIssuesCommit
> ```

😞 There are alternatives for each engine, but I couldn't find one that works in all of them.

**Comment by guillep2k** [comment]
In sqlite there is `min(num_issues,1)`, but that won't work with mssql.

File: models/issue_milestone.go [hunk 4]
```diff
@@ -311,71 +311,74 @@ func ChangeMilestoneStatus(m *Milestone, isClosed bool) (err error) {
...
+	if _, err = e.Exec("UPDATE `milestone` SET num_closed_issues=(SELECT count(*) FROM issue WHERE milestone_id=? AND is_closed=?) WHERE id=?",
+		milestoneID,
+		true,
+		milestoneID,
+	); err != nil {
+		return
 	}
 
-	return updateMilestone(e, m)
+	_, err = e.Exec("UPDATE `milestone` SET completeness=100*num_closed_issues/(num_issues+1-(CASE WHEN num_issues > 0 THEN 1 ELSE 0 END)) WHERE id=?",
```
Comment (guillep2k) [inline models/issue_milestone.go]:
```suggestion
	_, err = e.Exec("UPDATE `milestone` SET completeness=100*num_closed_issues/(CASE WHEN num_issues > 0 THEN num_issues ELSE 1 END) WHERE id=?",
```
More clear, perhaps?

**Review by guillep2k — COMMENTED** [review]
Just for clarity. Otherwise LGTM.

File: models/issue_milestone.go (hunk 4 above)
Comment (lunny) [reply models/issue_milestone.go]: Good catch. Done.

**Review by guillep2k — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
@lunny please send backport :)

**Comment by 6543** [comment]
@techknowlogick i can create it too?
I dont like to steel @lunny's work but i like to see 1.9.4 released ...

**Comment by techknowlogick** [comment]
@6543 sure. If you cherrypick the commit that was merged then @lunny will remain author (worst case a maintainer can rewrite git history of PR before merge)

**Comment by 6543** [comment]
@lunny lable backport done?
