### PR TITLE
Fix wrong display of recently pushed notification

### LINKED ISSUE #30611: Proposal: cancel the reminder of this merge request on the page
### Feature Description

WechatIMG1486
想取消页面上的这个合并请求的提醒。请问在哪里设置。看了所有的设置项都没有找到。因为这个提醒即使合并的也不会即使更新。
en:
I want to cancel the reminder of this merge request on the page. Can you tell me where to set it up? I looked at all the settings and couldn't find them. Because even if this reminder is merged, it will not be updated.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by yp05327**
There's a bug in #25715: 
If user pushed a commit into another repo with same branch name, the no-related repo will display the recently pushed notification incorrectly.
It is simple to fix this, we should match the repo id in the sql query.

image
The latest commit is 2 weeks ago.
image

The notification comes from another repo with same branch name:
image

After:
In forked repo:
image
New PR Link will redirect to the original repo:
image
In the original repo:
image
New PR Link:
image

In the same repo:
image
New PR Link:
image

08/15 Update:
Follow #26257, added permission check and logic fix mentioned in https://github.com/go-gitea/gitea/pull/26257#discussion_r1294085203

2024/04/25 Update:
Fix #30611

### CODE REVIEW

**Comment by lunny** [comment]
duplicated with #25795

**Comment by yp05327** [comment]
Have no enough time to test this PR, I will test it later.

**Review by lunny — APPROVED** [review]

File: models/git/branch.go [hunk 1]
```diff
@@ -391,7 +391,7 @@ func FindRecentlyPushedNewBranches(ctx context.Context, repoID, userID int64) (B
 			"issue.is_closed":           false,
 		})
 	err := db.GetEngine(ctx).
-		Where("pusher_id=? AND is_deleted=?", userID, false).
+		Where("repo_id=? AND pusher_id=? AND is_deleted=?", repoID, userID, false).
```
Comment (delvh) [inline models/git/branch.go]: The problem I see with this is the following:
Now, you won't be able to see this message in forks.
I've thought about the logic in the previous PR and thought it seems sensible.
While I can also see your problem, the question is now which of the two is better?
Or is there a third approach to still include forks, i.e. additionally storing a `ForkedFromID` or something like that?

Comment (lunny) [reply models/git/branch.go]: I think it's difficult to get all forked repositories. Maybe only the first level forked?

Comment (delvh) [reply models/git/branch.go]: I meant the other way round as it is a `one-to-n` relation: Each fork only has a single parent, so we can check for `repoID = fork or parent`.

**Comment by yp05327** [comment]
#25795 not looks good to me.
Instead, I used latest commit id, then you can also avoid display notification from both no-change branch in forked repo or the original repo.

**Comment by yp05327** [comment]
We can add a test for this new feature later. 
Maybe not in this PR, it is not easy to do this, as we need to make many changes in db and git data.

**Comment by yp05327** [comment]
This PR will not fix merged PR, as it will be fixed in #25810

File: models/git/branch.go [hunk 2]
```diff
@@ -382,20 +393,34 @@ func RenameBranch(ctx context.Context, repo *repo_model.Repository, from, to str
...
-	err := db.GetEngine(ctx).
-		Where("pusher_id=? AND is_deleted=?", userID, false).
-		And("name <> ?", excludeBranchName).
+		Where(builder.And(
+			builder.Eq{"issue.is_closed": false},
+			builder.In("pull_request.head_repo_id", repoCond),
+		))
+	err = db.GetEngine(ctx).
+		Where("id != ? AND commit_id != ? AND pusher_id = ? AND is_deleted = ?", baseBranch.ID, baseBranch.CommitID, doer.ID, false).
 		And("updated_unix >= ?", time.Now().Add(-time.Hour*6).Unix()).
```
Comment (lunny) [inline models/git/branch.go]: How about moving this condition as the first condition, and repo_id as the second condition

Comment (yp05327) [reply models/git/branch.go]: Updated the code here: use builder to generate the sql query instead.

**Comment by yp05327** [comment]
There's a problem if we do not use branch id to link the head branch and the pull request.
If we merged a PR, deleted the branch(ID:1) of that PR and created a new branch(ID:2) with the same name, we will never get the new PR notification, because when we search existing PR, the new created branch(ID:2) will be linked to the merged PR, and it will be excepted.

File: templates/repo/code/recently_pushed_new_branches.tmpl [hunk 3]
```diff
@@ -1,10 +1,22 @@
...
+		{{end}}
+		{{if not (eq .Repo.ID $.Repository.ID)}}
+			{{$branchName = (print .Repo.FullName ":" .Name)}}
+		{{end}}
+	{{end}}
 	<div class="ui positive message gt-df gt-ac">
 		<div class="gt-f1">
 			{{$timeSince := TimeSince .UpdatedUnix.AsTime $.locale}}
-			{{$.locale.Tr "repo.pulls.recently_pushed_new_branches" (PathEscapeSegments .Name) $timeSince | Safe}}
+			{{$.locale.Tr "repo.pulls.recently_pushed_new_branches" (PathEscapeSegments $branchName) $timeSince | Safe}}
```
Comment (puni9869) [inline templates/repo/code/recently_pushed_new_branches.tmpl]:
```
{{$.locale.Tr "repo.pulls.recently_pushed_new_branches" (PathEscapeSegments $branchName) $timeSince | Safe}}
```			
`PathEscapeSegments $branchname` This will create the problem when `branchname` contains `#` . like `branchname#123`. Is is due to `PathEscapeSegments`.

Double encoding of html Escape is going on.

There was an issue raised 
Screenshot 1:
https://user-images.githubusercontent.com/23124682/252675332-4f8da1bf-40f6-4442-bf39-a261bd7289fa.png

Screenshot 2:
https://user-images.githubusercontent.com/23124682/252675084-e3bc020c-1cb8-4801-87fe-dd79de9bcd02.png

### Issue link: -
https://github.com/go-gitea/gitea/issues/25830

@yp05327  FYI.

Comment (yp05327) [reply templates/repo/code/recently_pushed_new_branches.tmpl]: Not only here, for example: #25864
Maybe we should check all of them?

Comment (yp05327) [reply templates/repo/code/recently_pushed_new_branches.tmpl]: When I try to test this, I notice that we have more problems:
https://try.gitea.io/yp05327/testrepo/src/branch/main
If you select branch `test#11`, the url will be 
https://try.gitea.io/yp05327/testrepo/src/branch/test#11
but in the list it is `test`
image
Maybe we need a summary. 🤔

Comment (yp05327) [reply templates/repo/code/recently_pushed_new_branches.tmpl]: @puni9869 
I created a new issue to discuss branch name problems: #25865
~It seems that it is a global problem, so there's no plan to fix it in this PR now.~
Avoid forgetting fix this, I will fix it in this PR.

Comment (puni9869) [reply templates/repo/code/recently_pushed_new_branches.tmpl]: > When I try to test this, I notice that we have more problems: https://try.gitea.io/yp05327/testrepo/src/branch/main If you select branch `test#11`, the url will be https://try.gitea.io/yp05327/testrepo/src/branch/test#11 but in the list it is `test` image Maybe we need a summary. 🤔


Thanks yp05327  for the quick response
Here is the url of `test#11`.See its encoded  `test%2311`.

https://try.gitea.io/yp05327/testrepo/src/branch/test%2311

PS: I have checked be visiting `branches` tab 
image

That was the problem I was pointing in my comments.

`test` --> when you visite `https://try.gitea.io/yp05327/testrepo/src/branch/test#11` ie`test#11` it will redirect to  `test` branch
image
The `#` in the `test#11` will be treated as `hash routing`.

`test#11` ---> when you visite `https://try.gitea.io/yp05327/testrepo/src/branch/test%2311` ie `test%2311` you will land to  `test#11`

Comment (puni9869) [reply templates/repo/code/recently_pushed_new_branches.tmpl]: I appreciate your feedback and Opening a new issue on specific to branch name.

**Comment by silverwind** [comment]
Any tests possible?

**Comment by yp05327** [comment]
> Any tests possible?

I think an unit test is possible.

**Comment by yp05327** [comment]
I'm coding the test, and notice that maybe we need to check the repo access permission here, but not sure about this now.
Maybe user can get new branches notification from no accessible repo, as the `repoCond` does not look good.
So I change the PR status to draft now.

**Comment by yp05327** [comment]
Ready for review.

File: templates/repo/code/recently_pushed_new_branches.tmpl [hunk 4]
```diff
@@ -1,10 +1,22 @@
...
+	{{$branchName := .Name}}
+	{{if .Repo}}
+		{{$pullRepo = .Repo}}
+		{{if and $.Repository.IsFork}}
+			{{$baseRepo = $.Repository.BaseRepo}}
+		{{end}}
+		{{if not (eq .Repo.ID $.Repository.ID)}}
+			{{$branchName = (print .Repo.FullName ":" .Name)}}
+		{{end}}
+	{{end}}
```
Comment (silverwind) [inline templates/repo/code/recently_pushed_new_branches.tmpl]: Hmm, it almost seems to me that this logic would be better in go code. Also I don't really like `$.Repository` vs. `.Repo`. What's the difference?

Comment (yp05327) [reply templates/repo/code/recently_pushed_new_branches.tmpl]: `$.Repository` is the repo you access. `.Repo` is the repo which has a recently pushed branch.
If the repo you access has a recently pushed branch, we will only display the branch name, or we should display the repo name and the branch name:
image

ps: Maybe we can do this in backend not in template. 🤔

Comment (yp05327) [reply templates/repo/code/recently_pushed_new_branches.tmpl]: Have rewritten the code in https://github.com/go-gitea/gitea/pull/25812/commits/d7cb37c8bae723a7fd3687107bd9d6a17eb485fb

**Review by silverwind — APPROVED** [review]

**Comment by yp05327** [comment]
Found a new problem:
If user A fork a repo which have a recently commit pushed by user B, user A will see the notification immediately, 
as `branch.pusher_id` will be exchanged to user A 's id during, but actually it is committed by user B.

**Comment by lunny** [comment]
> Found a new problem: If user A fork a repo which have a recently commit pushed by user B, user A will see the notification immediately, as `branch.pusher` will be exchanged to user A, but actually it is committed by user B.
> 
> @lunny So what is the definition of `branch.pusher`?

Pusher is a user which have registered in this Gitea instance which is different from committer. Git Committer maybe not a user of this instance. i.e. I pushed git kernel to my Gitea instance. I'm the pusher, but I haven't committed any commit to this repository.

**Comment by yp05327** [comment]
> Pusher is a user which have registered in this Gitea instance which is different from committer. Git Committer maybe not a user of this instance. i.e. I pushed git kernel to my Gitea instance. I'm the pusher, but I haven't committed any commit to this repository.

I see. I tried this in GitHub, and got the same result. So this is not a problem any more. 😄 
But GitHub will only fork main branch by default, then user will not see the notification by default.

**Comment by silverwind** [comment]
Is it ready?

**Comment by yp05327** [comment]
> Is it ready?

Yes.

**Comment by wxiaoguang** [comment]
The question in my mind is: could the existing test fixtures be reused for testing?

I am not a fan of adding a lot of new fixtures for each new feature, otherwise, years later, there would be hundreds or thousands of git repositories for testing? Then would any one can tell their usage or is is possible to maintain them?

File: tests/integration/tests/integration/gitea-integration-sqlite/gitea.db-journal
Comment (wxiaoguang) [inline tests/integration/tests/integration/gitea-integration-sqlite/gitea.db-journal:1]: What's this file?

**Review by wxiaoguang — DISMISSED** [review]
Need to re-think about the added files

File: tests/integration/tests/integration/gitea-integration-sqlite/gitea.db-journal
Comment (yp05327) [reply tests/integration/tests/integration/gitea-integration-sqlite/gitea.db-journal:1]: Removed

**Comment by wxiaoguang** [comment]
> But I found that for a complex test, reusing them will break lots of tests and become a hard work.

How does it break? Each test uses the original fixtures, everything is reset.

**Comment by yp05327** [comment]
For example:
There's a repo A which seems that can be reused in your new test. And you decided to reuse it.
You finished your new test, and it worked well. So you pushed the codes, but got lots of CI failures.
Then you checked logs, and noticed that repo A can not be reused in your new test as there are several tests you didn't notice at the beginning are using repo A and your changes will cause conflicts in the end. For example, you can not change something related to repo A as the existing test A will check them, but you have to because you need these changes in your new test.
Then you rewrite the codes and try to reuse repo B.
But after taking several hours to finish your work, you notice that repo B can also not be reused for the same reason.
Then this will bring you into a loop of deciding which one to reuse, finishing your codes, and resolving the conflicts.

File: templates/repo/code/recently_pushed_new_branches.tmpl [hunk 5]
```diff
@@ -2,9 +2,9 @@
 	<div class="ui positive message gt-df gt-ac">
 		<div class="gt-f1">
 			{{$timeSince := TimeSince .CommitTime.AsTime $.locale}}
-			{{$.locale.Tr "repo.pulls.recently_pushed_new_branches" (Escape .Name) $timeSince | Safe}}
+			{{$.locale.Tr "repo.pulls.recently_pushed_new_branches" .BranchName $timeSince | Safe}}
```
Comment (wxiaoguang) [inline templates/repo/code/recently_pushed_new_branches.tmpl]: XSS

**Comment by wxiaoguang** [comment]
CI failure seems related

```
    api_org_test.go:94: 
        	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/api_org_test.go:94
        	            				/home/runner/work/gitea/gitea/tests/integration/git_helper_for_declarative_test.go:87
        	            				/home/runner/work/gitea/gitea/tests/integration/api_org_test.go:28
        	Error:      	"[%!s(*structs.User=&{1 user1 user1 User One user1@example.com https://secure.gravatar.com/avatar/111d68d06e2d317b5a59c2c6c5bad808?d=identicon en-US true {0 63828797734 <nil>} {0 62135596800 <nil>} false true false    public 0 0 0}) %!s(*structs.User=&{12 user12 user12 User 12 user12@example.com https://secure.gravatar.com/avatar/ef1debc1364806281c42eeedfdeb943b?d=identicon  false {0 62135596800 <nil>} {0 62135596800 <nil>} false true false    public 0 0 0})]" should have 1 item(s), but has 2
        	Test:       	TestAPIOrgCreate
```

**Comment by yp05327** [comment]
> CI failure seems related
> 
> ```
>     api_org_test.go:94: 
>         	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/api_org_test.go:94
>         	            				/home/runner/work/gitea/gitea/tests/integration/git_helper_for_declarative_test.go:87
>         	            				/home/runner/work/gitea/gitea/tests/integration/api_org_test.go:28
>         	Error:      	"[%!s(*structs.User=&{1 user1 user1 User One user1@example.com https://secure.gravatar.com/avatar/111d68d06e2d317b5a59c2c6c5bad808?d=identicon en-US true {0 63828797734 <nil>} {0 62135596800 <nil>} false true false    public 0 0 0}) %!s(*structs.User=&{12 user12 user12 User 12 user12@example.com https://secure.gravatar.com/avatar/ef1debc1364806281c42eeedfdeb943b?d=identicon  false {0 62135596800 <nil>} {0 62135596800 <nil>} false true false    public 0 0 0})]" should have 1 item(s), but has 2
>         	Test:       	TestAPIOrgCreate
> ```

Yes, but have no idea now why it only fails in pgsql. 🤔

**Comment by yp05327** [comment]
No CI failure now.

**Comment by yp05327** [comment]
As this PR has changed a lot, I think it should be reviewed again.

File: models/git/branch.go [hunk 6]
```diff
@@ -139,6 +141,16 @@ func (b *Branch) LoadPusher(ctx context.Context) (err error) {
 	return err
 }
 
+func (b *Branch) LoadRepo(ctx context.Context) (err error) {
+	if b.Repo == nil && b.RepoID > 0 {
+		b.Repo, err = repo_model.GetRepositoryByID(ctx, b.RepoID)
+		if repo_model.IsErrRepoNotExist(err) {
```
Comment (lunny) [inline models/git/branch.go]: Why ignore this error? I think a branch should always have related branch.

Comment (yp05327) [reply models/git/branch.go]: Done in https://github.com/go-gitea/gitea/pull/25812/commits/7fa0362d3637537d7c6fbc1064af0a0c2acc6b54

File: models/git/branch.go [hunk 7]
```diff
@@ -381,24 +391,100 @@ func RenameBranch(ctx context.Context, repo *repo_model.Repository, from, to str
...
+	prBranchIds := builder.Select("branch.id").From("branch").
+		InnerJoin("pull_request", "branch.name = pull_request.head_branch AND branch.repo_id = pull_request.head_repo_id").
+		Where(builder.And(
+			builder.Eq{"pull_request.base_repo_id": opts.BaseRepo.ID},
+			builder.Eq{"pull_request.base_branch": opts.BaseRepo.DefaultBranch},
+			builder.In("pull_request.head_repo_id", repoIDs),
+		))
+
+	if opts.CommitAfterUnix == 0 {
+		opts.CommitAfterUnix = time.Now().Add(-time.Hour * 6).Unix()
```
Comment (silverwind) [inline models/git/branch.go]:
```suggestion
		opts.CommitAfterUnix = time.Now().Add(-time.Hour * 2).Unix()
```

Match GitHub, maybe make it configurable.

File: models/git/branch.go [hunk 8]
```diff
@@ -381,24 +391,100 @@ func RenameBranch(ctx context.Context, repo *repo_model.Repository, from, to str
...
-// except the indicate branch
-func FindRecentlyPushedNewBranches(ctx context.Context, repoID, userID int64, excludeBranchName string) (BranchList, error) {
-	branches := make(BranchList, 0, 2)
-	subQuery := builder.Select("head_branch").From("pull_request").
-		InnerJoin("issue", "issue.id = pull_request.issue_id").
-		Where(builder.Eq{
-			"pull_request.head_repo_id": repoID,
-			"issue.is_closed":           false,
+// opts.Actor should not be nil
+// if opts.CommitAfterUnix is 0, we will find the branches committed in recently 6 hours
```
Comment (silverwind) [inline models/git/branch.go]:
```suggestion
// if opts.CommitAfterUnix is 0, we will find the branches that were committed to in the last 2 hours
```

File: models/git/branch.go [hunk 9]
```diff
@@ -381,24 +391,100 @@ func RenameBranch(ctx context.Context, repo *repo_model.Repository, from, to str
...
+	CommitAfterUnix int64
+}
+
+type RecentlyPushedNewBranch struct {
+	BranchName       string
+	BranchCompareURL string
+	CommitTime       timeutil.TimeStamp
+}
+
 // FindRecentlyPushedNewBranches return at most 2 new branches pushed by the user in 6 hours which has no opened PRs created
```
Comment (silverwind) [inline models/git/branch.go]:
```suggestion
// FindRecentlyPushedNewBranches return at most 2 new branches pushed by the user in 2 hours which has no opened PRs created
```

**Comment by yp05327** [comment]
Forgot this one. Need to fix the conflicts first. 😕 
image

**Comment by yp05327** [comment]
conflicts and test errors are all resolved.

File: models/git/branch.go [hunk 10]
```diff
@@ -139,6 +141,14 @@ func (b *Branch) LoadPusher(ctx context.Context) (err error) {
 	return err
 }
 
+func (b *Branch) LoadRepo(ctx context.Context) (err error) {
+	if b.Repo != nil && b.RepoID == 0 {
```
Comment (lunny) [inline models/git/branch.go]:
```suggestion
	if b.Repo != nil || b.RepoID == 0 {
```

**Comment by yp05327** [comment]
Fixing conflicts is too terrible.
Can someone help me to review this PR. 😭

**Comment by lunny** [comment]
Please resolve the conflicts.

File: models/git/branch.go [hunk 11]
```diff
@@ -381,24 +392,100 @@ func RenameBranch(ctx context.Context, repo *repo_model.Repository, from, to str
...
+	BranchCompareURL  string
+	CommitTime        timeutil.TimeStamp
+}
+
+// FindRecentlyPushedNewBranches return at most 2 new branches pushed by the user in 2 hours which has no opened PRs created
+// opts.Actor should not be nil
+// if opts.CommitAfterUnix is 0, we will find the branches that were committed to in the last 2 hours
+// if opts.ListOptions is not set, we will only display top 2 latest branch
+func FindRecentlyPushedNewBranches(ctx context.Context, opts *FindRecentlyPushedNewBranchesOptions) ([]*RecentlyPushedNewBranch, error) {
+	// find all related repo ids
```
Comment (lunny) [inline models/git/branch.go:436]: Why do we need to search for all repos?

Comment (yp05327) [reply models/git/branch.go:436]: For displaying notification in origin repo when I pushed commits in fork.
And it only search all `related` repos, not `all` repos.

Comment (yp05327) [reply models/git/branch.go:436]: Something like this:
image

by the way, I also prefer displaying this in PR list page as what GH does.

File: models/git/branch_list.go [hunk 12]
```diff
@@ -63,30 +64,83 @@ func (branches BranchList) LoadPusher(ctx context.Context) error {
 	return nil
 }
 
+func (branches BranchList) LoadRepo(ctx context.Context) error {
+	ids := container.Set[int64]{}
```
Comment (lunny) [inline models/git/branch_list.go]: Now we can should use `container.FilterSlice` to get repoIDs

File: models/git/branch_list.go [hunk 13]
```diff
@@ -63,30 +64,83 @@ func (branches BranchList) LoadPusher(ctx context.Context) error {
...
+	for _, branch := range branches {
+		if branch.RepoID > 0 {
```
Comment (lunny) [inline models/git/branch_list.go]:
```suggestion
		if branch.RepoID > 0 && branch.Repo == nil {
```

File: models/git/branch_list.go (hunk 12 above)
Comment (yp05327) [reply models/git/branch_list.go]: Done.

File: models/git/branch_list.go (hunk 13 above)
Comment (yp05327) [reply models/git/branch_list.go]: we should also add this check in the below, or we will get bug here.
Done.

File: models/git/branch.go [hunk 14]
```diff
@@ -381,24 +392,100 @@ func RenameBranch(ctx context.Context, repo *repo_model.Repository, from, to str
...
+		Actor:      opts.Actor,
+		Private:    true,
+		AllPublic:  false, // Include also all public repositories of users and public organisations
+		AllLimited: false, // Include also all public repositories of limited organisations
+		Fork:       optional.Some(true),
+		ForkFrom:   opts.BaseRepo.ID,
+		Archived:   optional.Some(false),
+	}
+	repoCond := repo_model.SearchRepositoryCondition(&repoOpts).And(repo_model.AccessibleRepositoryCondition(opts.Actor, unit.TypeCode))
+	if opts.Repo == opts.BaseRepo {
```
Comment (lunny) [inline models/git/branch.go]: Compare the IDs but not pointers?

Comment (yp05327) [reply models/git/branch.go]: Done

**Comment by yp05327** [comment]
image
image
😕

**Comment by yp05327** [comment]
Which one is correct?

**Comment by wxiaoguang** [comment]
It looks strange to me .... why so many test fixtures are changed?

* If some fixtures must be changed, I think something could be "appended", while keep the old IDs unchanged.
* If no fixture must be changed, then revert these unnecessary changes? Some data could be inserted dynamically when testing.

**Comment by yp05327** [comment]
It seems that there's a bug, if user create a branch and pushed a commit, then he/she lose the write permission, the notification will also be there.

File: models/git/branch.go [hunk 15]
```diff
@@ -400,24 +411,105 @@ func RenameBranch(ctx context.Context, repo *repo_model.Repository, from, to str
...
+	repoOpts := repo_model.SearchRepoOptions{
+		Actor:      opts.Actor,
+		Private:    true,
+		AllPublic:  false, // Include also all public repositories of users and public organisations
+		AllLimited: false, // Include also all public repositories of limited organisations
+		Fork:       optional.Some(true),
+		ForkFrom:   opts.BaseRepo.ID,
+		Archived:   optional.Some(false),
+	}
+	repoCond := repo_model.SearchRepositoryCondition(&repoOpts).And(repo_model.AccessibleRepositoryCondition(opts.Actor, unit.TypeCode))
```
Comment (yp05327) [inline models/git/branch.go]: We need convert `AccessibleRepositoryCondition` into `WritableRepositoryCondition` here.
Do we already have one?

File: routers/web/repo/view.go [hunk 16]
```diff
@@ -1045,7 +1045,7 @@ func renderHomeCode(ctx *context.Context) {
 
 		if !opts.Repo.IsMirror && !opts.BaseRepo.IsMirror &&
 			opts.BaseRepo.UnitEnabled(ctx, unit_model.TypePullRequests) &&
-			baseRepoPerm.CanRead(unit_model.TypePullRequests) {
+			baseRepoPerm.CanWrite(unit_model.TypePullRequests) {
```
Comment (wxiaoguang) [inline routers/web/repo/view.go]: IIRC "read" means "create", "write" means "delete/modify"

File: models/fixtures/access.yml [hunk 17]
```diff
@@ -1,173 +1,185 @@
...
 -
-  id: 2
+  id: 3
   user_id: 2
   repo_id: 5
   mode: 4
 
 -
-  id: 3
+  id: 4
```
Comment (wxiaoguang) [inline models/fixtures/access.yml]: Still a lot of unnecessary changes.

Comment (yp05327) [reply models/fixtures/access.yml]: WIP

File: routers/web/repo/view.go (hunk 16 above)
Comment (yp05327) [reply routers/web/repo/view.go]: I tested it:
- user A create a public repo
- user B access this repo, the pull request button is disabled.
- add user B as a contributor with write permission
- the pull request button is enabled.
- convert the permission to read
- the pull request button is disabled.

It seems that this has been changed.

Comment (yp05327) [reply routers/web/repo/view.go]: sorry, that is because user B has no branch to create PR

File: models/fixtures/access.yml (hunk 17 above)
Comment (yp05327) [reply models/fixtures/access.yml]: https://github.com/go-gitea/gitea/pull/25812/commits/9fb523c6892bfb0f5a67a1470070452b4d8e76e1

File: models/git/branch.go (hunk 15 above)
Comment (yp05327) [reply models/git/branch.go]: The problem seems not too bad.
Maybe we can allow user to create a PR on the branch they created even they have no write permission to the branch now. So we can allow display the notification.

But for the normal creating PR page, no matter who created the branch, anyone with read permission of code and PR unit, can create a PR, which seems not good.

**Comment by yp05327** [comment]
@wxiaoguang 
Tests has been fixed.
We allow displaying notifications if the branch is created by doer, no matter doer really has the permission to create PR.
It will be checked when creating PR.

**Comment by wxiaoguang** [comment]
Still unrelated changes?

image

**Comment by yp05327** [comment]
user13 is added as a collaborator to repo10, so access table changed.

**Comment by wxiaoguang** [comment]
> user13 is added as a collaborator to repo10, so access table changed.

Why not just "append" one, and keep the old "id" as-is?

**Comment by yp05327** [comment]
> > user13 is added as a collaborator to repo10, so access table changed.
> 
> Why not just "append" one, and keep the old "id" as-is?

@wxiaoguang 
Done in b1346d561c12890e89b985d4146d61a7d3164ce9

**Comment by yp05327** [comment]
So strange. I only saw 126 lines in compare_test.go, but the CI failed in L143.
But after I updated the branch, I saw it. 😕

**Comment by wxiaoguang** [comment]
Still unrelated changes? 🤔 


image

File: models/git/branch_list.go [hunk 18]
```diff
@@ -59,30 +60,74 @@ func (branches BranchList) LoadPusher(ctx context.Context) error {
...
+	if opts.PusherID > 0 {
+		cond = cond.And(builder.Eq{"branch.pusher_id": opts.PusherID})
 	}
+
 	if opts.IsDeletedBranch.Has() {
-		cond = cond.And(builder.Eq{"is_deleted": opts.IsDeletedBranch.Value()})
+		cond = cond.And(builder.Eq{"branch.is_deleted": opts.IsDeletedBranch.Value()})
 	}
 	if opts.Keyword != "" {
 		cond = cond.And(builder.Like{"name", opts.Keyword})
```
Comment (wxiaoguang) [inline models/git/branch_list.go]: `branch.` is added to the line above. Does it also need `branch.` here?

(Is it used by a JOIN query?)

File: models/git/branch_list.go [hunk 19]
```diff
@@ -59,30 +60,74 @@ func (branches BranchList) LoadPusher(ctx context.Context) error {
...
+	return nil
+}
+
 type FindBranchOptions struct {
 	db.ListOptions
 	RepoID             int64
+	RepoCond           builder.Cond
 	ExcludeBranchNames []string
+	CommitCond         builder.Cond
+	PusherID           int64
```
Comment (wxiaoguang) [inline models/git/branch_list.go]: It doesn't seem good to continue bloating the `FindXxxOptions`. They are used for general querying purpose. Mixing too many options together would cause unclear behaviors and make it difficult to maintain.

Now since you have a clear requirement to query some "recently pushed branches", I think it needs a brand new function to do such query.

File: models/git/branch_list.go (hunk 18 above)
Comment (yp05327) [reply models/git/branch_list.go]: These are unnecessary codes.
Done in 484b3344f84f380777bcce5c007d602595434926

File: models/git/branch_list.go (hunk 19 above)
Comment (yp05327) [reply models/git/branch_list.go]: Done in 484b3344f84f380777bcce5c007d602595434926

File: models/git/branch_list.go [hunk 20]
```diff
@@ -59,10 +60,29 @@ func (branches BranchList) LoadPusher(ctx context.Context) error {
...
+		branch.Repo = reposMap[branch.RepoID]
+	}
+	return nil
+}
+
 type FindBranchOptions struct {
 	db.ListOptions
 	RepoID             int64
 	ExcludeBranchNames []string
+	PusherID           int64
```
Comment (wxiaoguang) [inline models/git/branch_list.go]:
```suggestion
```

It seems that this `PusherID` is not really used? Let's try to remove to see whether CI fails.

**Review by wxiaoguang — APPROVED** [review]
