### PR TITLE
Ignore useless error message "broken pipe"

### LINKED ISSUE #30792: tcp: write: broken pipe: [E] Render failed: failed to render template + [E] plainTextInternal (status=500)
### Description

In the log it show the following:

2024/04/30 23:21:27 .../context_response.go:87:HTML() [E] Render failed: failed to render template: home, error: write tcp 127.0.0.1:3000->127.0.0.1:50284: write: broken pipe
2024/04/30 23:21:27 .../context_response.go:89:HTML() [E] plainTextInternal (status=500): write bytes failed: write tcp 127.0.0.1:3000->127.0.0.1:50284: write: broken pipe

Installed via docker compose on Synology NAS.

### Gitea Version

gitea-1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

log

### Git Version

_No response_

### Operating System

Synology DSM

### How are you running Gitea?

Docker Container

### Database

None

### Additional remarks
I already did this setting: Administration -> Konfiguration -> Einstellungen -> Gravatar deaktivieren

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #30792

### CODE REVIEW

File: routers/api/packages/maven/maven.go [hunk 1]
```diff
@@ -140,9 +140,7 @@ func serveMavenMetadata(ctx *context.Context, params parameters) {
 	ctx.Resp.Header().Set("Content-Length", strconv.Itoa(len(xmlMetadataWithHeader)))
 	ctx.Resp.Header().Set("Content-Type", contentTypeXML)
 
-	if _, err := ctx.Resp.Write(xmlMetadataWithHeader); err != nil {
-		log.Error("write bytes failed: %v", err)
-	}
+	_, _ = ctx.Resp.Write(xmlMetadataWithHeader)
```
Comment (delvh) [inline routers/api/packages/maven/maven.go:143]: Is there no other way to detect this apart from ignoring errors completely?

File: services/context/base.go [hunk 2]
```diff
@@ -234,9 +234,7 @@ func (b *Base) plainTextInternal(skip, status int, bs []byte) {
 	b.Resp.Header().Set("Content-Type", "text/plain;charset=utf-8")
 	b.Resp.Header().Set("X-Content-Type-Options", "nosniff")
 	b.Resp.WriteHeader(status)
-	if _, err := b.Resp.Write(bs); err != nil {
-		log.ErrorWithSkip(skip, "plainTextInternal (status=%d): write bytes failed: %v", status, err)
-	}
+	_, _ = b.Resp.Write(bs)
```
Comment (delvh) [inline services/context/base.go:237]: See above

**Review by delvh — APPROVED** [review]

File: services/context/context_response.go [hunk 3]
```diff
@@ -13,6 +13,7 @@ import (
 	"path"
 	"strconv"
 	"strings"
+	"syscall"
```
Comment (silverwind) [inline services/context/context_response.go:16]: Will this work on Windows? My impression is that the syscall package is unix only.

Comment (wxiaoguang) [reply services/context/context_response.go:16]: It is a common package.

Windows also have similar concept "syscall"

image

File: routers/api/packages/maven/maven.go (hunk 1 above)
Comment (wxiaoguang) [reply routers/api/packages/maven/maven.go:143]: The question is: why do you want to do so? What would you like to do when the "Write" fails .......... I do not see any useful case to handle such error.

File: services/context/context_response.go (hunk 3 above)
Comment (silverwind) [reply services/context/context_response.go:16]: Yeah looks like there is some form of [stub module](https://go.dev/src/syscall/syscall_windows.go) for windows syscall. I don't think it could emit EPIPE there but at least it will compile.

**Review by silverwind — APPROVED** [review]

File: routers/api/packages/maven/maven.go (hunk 1 above)
Comment (wxiaoguang) [reply routers/api/packages/maven/maven.go:143]: I think we can merge it as-is, if there would be any real requirement to see the "errors", we can improve it then
