### PR TITLE
Fix all rounded borders, change affected tab menus to pills

### LINKED ISSUE #30673: UI border-radius inconsistent problems
- [x] Repository Activity
image

- [x] Repository Actions Secrets
image

- [x] Repository Actions Variables
image

- [x] File editor
image

- [x] File editor preview
image

- [x] User profile
image

- [x] Admin -> Identity & Access -> User Emails
image

- [x] Admin -> Code Assets -> Repositories
image

- [x] Admin -> Integrations -> Webhook
image

- [x] Admin -> Actions -> Variables
image

- [x] Admin -> System Notices
image

- [x] Org setting -> Webhooks
image

- [x] Org setting -> Labels
image

- [x] Org Setting -> Blocked Users
image

- [x] Org Setting -> Actions -> Secrets
image

- [x] Org Setting -> Actions -> Variables
image

- [x] Org -> Teams -> Members/Repositories setting for a Team
image

- [x] New migration
image

- [x] notification -> subscriptions
image

- [x] User settings -> Blocked users
image

- [x] User settings -> Actions -> Secrets
image

- [x] User settings -> Actions -> Variables
image

- [x] User setttings -> Webhooks
image

### PR DESCRIPTION
**Pull request by silverwind**
Fixes https://github.com/go-gitea/gitea/issues/30673, all 23 issues. Notes:

- Tab bar menus had to change to pills because of unsolvable issue with the border-radius as tab bar renders a overlapping border onto the box below. And I think pills look better.
- Added padding to code editor empty preview message
- Hide monaco's built-in blue focus border, we don't need it and it never showed before either.
- Label add menu is simplified, removing the nested segment.

Screenshot 2024-04-25 at 22 26 19
Screenshot 2024-04-25 at 22 28 00
Screenshot 2024-04-25 at 22 36 53
Screenshot 2024-04-25 at 22 56 09
Screenshot 2024-04-25 at 22 57 12

### CODE REVIEW

File: routers/web/repo/editor.go [hunk 1]
```diff
@@ -420,7 +420,7 @@ func DiffPreviewPost(ctx *context.Context) {
 	}
 
 	if diff.NumFiles == 0 {
-		ctx.PlainText(http.StatusOK, ctx.Locale.TrString("repo.editor.no_changes_to_show"))
+		ctx.PlainText(http.StatusOK, `<div class="tw-p-6">` + ctx.Locale.TrString("repo.editor.no_changes_to_show") + `</div>`)
```
Comment (silverwind) [inline routers/web/repo/editor.go]: This does return `content-type: text/plain;charset=utf-8` but still works, fwiw. `ctx.HTML` is unsuitable as I can not pass a string to it.

Comment (silverwind) [reply routers/web/repo/editor.go]: https://github.com/go-gitea/gitea/pull/30707/commits/7e401494155bc3a5fd78d66158f1ee62de13c8ed adds `ctx.HTMLString`, if you have better ideas, please shoot. Could also just inline the three calls here.

File: routers/web/repo/editor.go [hunk 2]
```diff
@@ -420,7 +420,7 @@ func DiffPreviewPost(ctx *context.Context) {
 	}
 
 	if diff.NumFiles == 0 {
-		ctx.PlainText(http.StatusOK, ctx.Locale.TrString("repo.editor.no_changes_to_show"))
+		ctx.HTMLString(http.StatusOK, `<div class="tw-p-6">`+ctx.Locale.TrString("repo.editor.no_changes_to_show")+`</div>`)
```
Comment (lunny) [inline routers/web/repo/editor.go]: Maybe it's unrelated changes?

Comment (silverwind) [reply routers/web/repo/editor.go]: See https://github.com/go-gitea/gitea/pull/30707#discussion_r1580125936

**Comment by lunny** [comment]
editor tabs are broken

image

**Comment by lunny** [comment]
If there is no extra branches except main branch.

image

**Comment by lunny** [comment]
If there is no tags

image

**Comment by lunny** [comment]
admin panel -> repositories
image

**Comment by silverwind** [comment]
> editor tabs are broken
> image

That's intentional, read comment.

**Comment by lunny** [comment]
admin panel -> system notices
image

**Comment by silverwind** [comment]
> If there is no extra branches except main branch.
> image

These double border issues are unrelated and are because of missing empty content state, related to https://github.com/go-gitea/gitea/issues/29810, but I can have a look of the fix is easy.

**Comment by silverwind** [comment]
> admin panel -> system notices image

Cannot reproduce:

image

File: routers/web/repo/editor.go (hunk 1 above)
Comment (silverwind) [reply routers/web/repo/editor.go]: @wxiaoguang any suggestions on how to avoid adding this `HTMLString` function?

**Comment by silverwind** [comment]
> admin panel -> repositories image

Also does not reproduce:

image

**Comment by silverwind** [comment]
> If there is no tags
> image

Fixed by not rendering anything. This is consistent with release list.

image

File: routers/web/repo/editor.go (hunk 1 above)
Comment (wxiaoguang) [reply routers/web/repo/editor.go]: No need to do so. Just use `{{if eq NumFiles 0}} ... {{end}}` in the template, and do not return early.

Comment (silverwind) [reply routers/web/repo/editor.go]: Ah, I see.

Comment (silverwind) [reply routers/web/repo/editor.go]: Fixed in https://github.com/go-gitea/gitea/pull/30707/commits/73937a520403a721b39f83ad5bb5bc49776372e4.

File: routers/web/repo/editor.go [hunk 3]
```diff
@@ -420,10 +420,10 @@ func DiffPreviewPost(ctx *context.Context) {
 	}
 
 	if diff.NumFiles == 0 {
-		ctx.HTMLString(http.StatusOK, `<div class="tw-p-6">`+ctx.Locale.TrString("repo.editor.no_changes_to_show")+`</div>`)
-		return
+		ctx.Data["File"] = nil
+	} else {
+		ctx.Data["File"] = diff.Files[0]
```
Comment (wxiaoguang) [inline routers/web/repo/editor.go:423]:
```
if diff.NumFiles != 0 {
    ctx.Data["File"] = diff.Files[0]
}
```

Comment (silverwind) [reply routers/web/repo/editor.go:423]: Is it safe from out-of-bounds access?

Comment (silverwind) [reply routers/web/repo/editor.go:423]: Ah yes, template accessing `nil` should be fine.

Comment (wxiaoguang) [reply routers/web/repo/editor.go:423]: Where is the ` out-of-bounds `? The logic is the same as before.

Comment (silverwind) [reply routers/web/repo/editor.go:423]: It's fine, I misread. Fixed in https://github.com/go-gitea/gitea/pull/30707/commits/33d4ed973f7c5d9883b6b75daf200bfb8a947500.

**Review by lunny — APPROVED** [review]

**Comment by silverwind** [comment]
Fix added for modal actions:

image

**Comment by silverwind** [comment]
Diff boxes fixes as well in https://github.com/go-gitea/gitea/pull/30707/commits/02be08f23388061fe674cccb9b1ce03b0f77ce4a. Top and bottom and while sticky/scrolled:

Screenshot 2024-04-26 at 22 28 01
Screenshot 2024-04-26 at 22 32 29

**Comment by silverwind** [comment]
Commit box for unsigned commits fixed:

Screenshot 2024-04-26 at 22 39 43

File: web_src/css/base.css [hunk 4]
```diff
@@ -435,6 +435,10 @@ a.label,
   box-shadow: 1px 1px 0 0 var(--color-secondary);
 }
 
+.ui.modal .actions {
+  border-radius: 0 0 var(--border-radius) var(--border-radius);
+}
```
Comment (wxiaoguang) [inline web_src/css/base.css]: There is `modal.css` and there are more accurate selectors for `actions`.

File: templates/repo/editor/edit.tmpl [hunk 5]
```diff
@@ -26,25 +26,25 @@
...
 						data-previewable-extensions="{{.PreviewableExtensions}}"
 						data-line-wrap-extensions="{{.LineWrapExtensions}}">{{.FileContent}}</textarea>
 					<div class="editor-loading is-loading"></div>
 				</div>
-				<div class="ui bottom attached tab segment markup" data-tab="preview">
+				<div class="ui tab segment markup tw-rounded" data-tab="preview">
 					{{ctx.Locale.Tr "loading"}}
 				</div>
-				<div class="ui bottom attached tab segment diff edit-diff" data-tab="diff">
+				<div class="ui tab segment diff edit-diff tw-text-center" data-tab="diff">
```
Comment (wxiaoguang) [inline templates/repo/editor/edit.tmpl]: `tw-text-center` doesn't seem right. Do you have a screenshot for it?

File: templates/shared/user/profile_big_avatar.tmpl [hunk 6]
```diff
@@ -1,4 +1,4 @@
-<div id="profile-avatar-card" class="ui card">
+<div id="profile-avatar-card" class="ui card tw-rounded">
```
Comment (wxiaoguang) [inline templates/shared/user/profile_big_avatar.tmpl]: I have seen not only one `ui card tw-rounded`. 

Should it write border styles into the `.ui.card` selectors?

File: templates/user/notification/notification_subscriptions.tmpl [hunk 7]
```diff
@@ -1,15 +1,15 @@
...
+		<div class="ui compact small menu small-menu-items">
 			<a href="{{AppSubUrl}}/notifications/subscriptions" class="{{if eq .Status 1}}active {{end}}item">
 				{{ctx.Locale.Tr "notification.subscriptions"}}
 			</a>
 			<a href="{{AppSubUrl}}/notifications/watching" class="{{if eq .Status 2}}active {{end}}item">
 				{{ctx.Locale.Tr "notification.watching"}}
 			</a>
 		</div>
-		<div class="ui bottom attached active tab segment">
+		<div class="ui top attached active tab segment">
```
Comment (wxiaoguang) [inline templates/user/notification/notification_subscriptions.tmpl]: https://fomantic-ui.com/modules/tab.html

`tab` should be used with `tabular menu`, but there is no `tabular menu` now?

File: web_src/css/base.css (hunk 4 above)
Comment (silverwind) [reply web_src/css/base.css]: I made this intentionally inprecise because the original fomantic selector does not match all variants seen on the devtest page.

File: templates/repo/editor/edit.tmpl (hunk 5 above)
Comment (silverwind) [reply templates/repo/editor/edit.tmpl]: It's for this text, but I guess I can move this one element down.

image

File: templates/shared/user/profile_big_avatar.tmpl (hunk 6 above)
Comment (silverwind) [reply templates/shared/user/profile_big_avatar.tmpl]: Hmm yes, I think we could.

File: templates/user/notification/notification_subscriptions.tmpl (hunk 7 above)
Comment (silverwind) [reply templates/user/notification/notification_subscriptions.tmpl]: Likely some JS is still bound to the `tab` class, but I can check if I can remove there as well.

File: templates/repo/editor/edit.tmpl (hunk 5 above)
Comment (wxiaoguang) [reply templates/repo/editor/edit.tmpl]: Yup, I think the "text center" could be put here

https://github.com/go-gitea/gitea/pull/30707/files/2cdda417cedd53ee168ce0071fc49b89827f3059#diff-00d13d738c9cbc506b77666d160bdffaad21a34187ad9e240eeec31d546db039R14-R16

File: web_src/css/base.css (hunk 4 above)
Comment (wxiaoguang) [reply web_src/css/base.css]: I will take a try, and make devtest page cover all cases.

Comment (wxiaoguang) [reply web_src/css/base.css]: It should be like this. The details were written in the modal's comments.

image


image

Comment (silverwind) [reply web_src/css/base.css]: Looks good.

File: templates/repo/editor/edit.tmpl (hunk 5 above)
Comment (silverwind) [reply templates/repo/editor/edit.tmpl]: Fixed in https://github.com/go-gitea/gitea/pull/30707/commits/f18ad0efa9728c97a3fcddc96e2f246175731390.

File: templates/shared/user/profile_big_avatar.tmpl (hunk 6 above)
Comment (silverwind) [reply templates/shared/user/profile_big_avatar.tmpl]: Fixed in https://github.com/go-gitea/gitea/pull/30707/commits/2bd28a7f73ebac4f56af5d65ef6bca8e10ad2029.

File: templates/user/notification/notification_subscriptions.tmpl (hunk 7 above)
Comment (silverwind) [reply templates/user/notification/notification_subscriptions.tmpl]: This case is fixed in https://github.com/go-gitea/gitea/pull/30707/commits/3de13aa93fe676b8ff4a509bf1d0d0fc1b86ceee but there are more.

Comment (silverwind) [reply templates/user/notification/notification_subscriptions.tmpl]: Damn this htmx crap in the editor is hard to debug.

Comment (silverwind) [reply templates/user/notification/notification_subscriptions.tmpl]: I'm not going ahead with the `tab` class removal, it's required for the tab-click-to-content-change mechanism to work.

We can do it once we remove the fomantic `tab` module.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/30707/commits/7c31f748493c7a97373f11268a70a10bc472bc61 contains a few refactors for the editor and also fixes the styling of the patch editor.

File: web_src/js/features/repo-editor.js [hunk 8]
```diff
@@ -7,9 +7,9 @@ import {attachRefIssueContextPopup} from './contextpopup.js';
 import {POST} from '../modules/fetch.js';
 
 function initEditPreviewTab($form) {
-  const $tabMenu = $form.find('.tabular.menu');
+  const $tabMenu = $form.find('.repo-editor-menu');
   $tabMenu.find('.item').tab();
-  const $previewTab = $tabMenu.find(`.item[data-tab="${$tabMenu.data('preview')}"]`);
+  const $previewTab = $tabMenu.find('a[data-tab="preview"]');
```
Comment (delvh) [inline web_src/js/features/repo-editor.js:12]: Why require it to be a link?
```suggestion
  const $previewTab = $tabMenu.find('[data-tab="preview"]');
```

**Review by delvh — APPROVED** [review]

File: web_src/js/features/repo-editor.js (hunk 8 above)
Comment (silverwind) [reply web_src/js/features/repo-editor.js:12]: Because the `data-tab` attribute is used for both the link to the tab and the tab content element itself, so we can not query on data attribute alone. Doing this change would most likely break the tabs.

**Comment by silverwind** [comment]
Would backport as enhancement.

**Comment by wxiaoguang** [comment]
The new UI looks a little strange.

IMO these "tab buttons" should attach to the main content. GitHub also attaches these 2 parts together by backgrounds.

image


image

**Comment by silverwind** [comment]
Yes, we should add a header to the editor to hold these buttons.
