### PR TITLE
Use configurable remote name for git commands

### LINKED ISSUE #19403: Change default remote name
### Feature Description

When a new repository is created using the web interface, instructions are given to push a new or existing repository from the command line.

```
git remote add origin <server>/<repo>.git
git push -u origin main
```

This is great, but I often find myself wanting to push repositories for which `origin` is already defined.

```
error: remote origin already exists.
```

Perhaps it would be benificial to be able to change the default remote name, either on repository, user or global level, so these conflicts are unlikely to exists. Just like [default branch names](https://docs.gitea.io/en-us/config-cheat-sheet/#repository-repository) can be set. The obvious result in the web interface would be the following.

```
git remote add <default_remote_name> <server>/<repo>.git
git push -u <default_remote_name> main
```

This is one of those *really* minor issues that would enhance the user experience in my opinion. Apologies if this feature has been requested or exists, but I couldn't find it anywhere. I'd gladly implement this feature, by the way. :)

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by ilya-nurullin**
Closes #19403, and makes it possible to use any remote name in code snippets for an empty repository and pull request.
This change is very helpful to me, because I always use different name for my gitea remote.

Uses setting config module to store the value. Default is `origin` for backward compatibility.

### Screenshots
<details>
<summary>Empty repo</summary>
image
</details>

<details>
<summary>Pull Request</summary>
image
</details>

<details>
<summary>Settings page</summary>
image
</details>

### CODE REVIEW

**Comment by hiifong** [comment]
This remote should be an optional configuration item with a default value of origin.

**Comment by lunny** [comment]
Maybe it should be a per repository setting but not a global one.

**Comment by ilya-nurullin** [comment]
> Maybe it should be a per repository setting but not a global one.

I think we can get started with a global one, and then if needed, make it more precise. 
At least, the global one works well for me, and I don't need more granular settings here.

**Comment by lunny** [comment]
Even if you intend to add a global configuration, please store it in the database rather than in app.ini.

**Comment by ilya-nurullin** [comment]
> Even if you intend to add a global configuration, please store it in the database rather than in app.ini.

Done!

File: routers/web/admin/config.go [hunk 1]
```diff
@@ -206,6 +206,20 @@ func ChangeConfig(ctx *context.Context) {
 		}
 		return "false", nil
 	}
+
+	marshalStringWithDefault := func(def string) func(v string) (string, error) {
+		return func(v string) (string, error) {
+			if strings.TrimSpace(v) == "" {
+				v = def
+			}
+			b, err := json.Marshal(v)
```
Comment (lunny) [inline routers/web/admin/config.go]: Why is it necessary to use JSON format to store a string?

Comment (ilya-nurullin) [reply routers/web/admin/config.go]: This is the default behavior of the config module: when it reads values from db, it unmarshals them from JSON.
- https://github.com/go-gitea/gitea/blob/2e8a4a09d55b0ca2b3333e1388fff16d402814ff/modules/setting/config/value.go#L68
- https://github.com/go-gitea/gitea/blob/2e8a4a09d55b0ca2b3333e1388fff16d402814ff/modules/setting/config/value.go#L29-L37

**Comment by lunny** [comment]
Does the title “Repository Snippets” in the configuration accurately reflect its purpose? It might be more appropriate under the Pull Request Settings section.

**Comment by ilya-nurullin** [comment]
> Does the title “Repository Snippets” in the configuration accurately reflect its purpose? It might be more appropriate under the Pull Request Settings section.

This setting affects two pages at once:
1. Empty repo page - I believe this is the most frequent use case for the setting
2. Pull Request page - you can do a merge using the button on the page, so snippets are hidden by default

Therefore, I would choose a more general name. I am open to any suggestions.

**Review by lunny — APPROVED** [review]

**Review by hiifong — APPROVED** [review]

File: services/context/repo.go [hunk 2]
```diff
@@ -542,6 +542,7 @@ func RepoAssignment(ctx *Context) {
 	ctx.Data["CanWriteIssues"] = ctx.Repo.CanWrite(unit_model.TypeIssues)
 	ctx.Data["CanWritePulls"] = ctx.Repo.CanWrite(unit_model.TypePullRequests)
 	ctx.Data["CanWriteActions"] = ctx.Repo.CanWrite(unit_model.TypeActions)
+	ctx.Data["SnippetRemoteName"] = setting.Config().Repository.SnippetRemoteName.Value(ctx)
```
Comment (wxiaoguang) [inline services/context/repo.go]: Here and above: we can remove this `SnippetRemoteName` from template data, and get its value directly from the templates that need it.

File: templates/admin/config_settings.tmpl [hunk 3]
```diff
@@ -39,4 +39,19 @@
...
 </div>
+
+<h4 class="ui top attached header">
+	{{ctx.Locale.Tr "admin.config.repository_snippets"}}
+</h4>
+<div class="ui attached segment">
+	<form class="ui form form-fetch-action" method="post" action="{{AppSubUrl}}/-/admin/config?key={{.SystemConfig.Repository.SnippetRemoteName.DynKey}}">
+		<div class="field" data-field-patched="true">
+			<label for="remote_name">{{ctx.Locale.Tr "admin.config.repository_snippets.remote_name"}}</label>
+			<input id="remote_name" name="value" value="{{.SystemConfig.Repository.SnippetRemoteName.Value ctx}}" maxlength="100" dir="auto" placeholder="{{.SystemConfig.Repository.SnippetRemoteName.Def}}">
```
Comment (wxiaoguang) [inline templates/admin/config_settings.tmpl]: I don't think the `Def` here is useful.

The value is always filled by `Value` when a user opens this page.

So I think we should remove the `Def` function.

File: modules/setting/config.go [hunk 4]
```diff
@@ -49,6 +49,7 @@ func DefaultOpenWithEditorApps() OpenWithEditorAppsType {
 
 type RepositoryStruct struct {
 	OpenWithEditorApps *config.Value[OpenWithEditorAppsType]
+	SnippetRemoteName  *config.Value[string]
```
Comment (wxiaoguang) [inline modules/setting/config.go]: Is `Snippet` a proper name?

IMO it is not a "snippet", it is for "git guide for users"

File: options/locale/locale_en-US.ini [hunk 5]
```diff
@@ -3419,6 +3419,9 @@ config.disable_gravatar = Disable Gravatar
 config.enable_federated_avatar = Enable Federated Avatars
 config.open_with_editor_app_help = The "Open with" editors for the clone menu. If left empty, the default will be used. Expand to see the default.
 
+config.repository_snippets = Repository Snippets
```
Comment (wxiaoguang) [inline options/locale/locale_en-US.ini]: It's also an unclear name ....

`Repository Snippets` reads like "some parts of the repository", and  GitLab users have been familiar with its Code Snippets https://docs.gitlab.com/user/snippets/

File: modules/setting/config.go (hunk 4 above)
Comment (ilya-nurullin) [reply modules/setting/config.go]: What name would you use here? Can it be just `RemoteName`?

File: services/context/repo.go (hunk 2 above)
Comment (ilya-nurullin) [reply services/context/repo.go]: Since it is used in several places in the template, I think it makes sense to extract it into a variable, which is what I did.

File: templates/admin/config_settings.tmpl (hunk 3 above)
Comment (ilya-nurullin) [reply templates/admin/config_settings.tmpl]: The main reason for `Def` is being able to get the default value when user removes value on settings page. 
It is used here: https://github.com/go-gitea/gitea/pull/35172/files#diff-b3b66aef8cc83304cd5cfc661233e6c1c1be656fbd6cd1e09b114348f224ff32R251

In current architecture `func (value *Value[T]) Value(ctx context.Context) (v T)` function uses a default value only if it is not present in the database. So `null` in db, `nil` in go values are valid ones, and therefore the default value won't be used, and as a result there won't be any remote name on the page in snippets.

File: options/locale/locale_en-US.ini (hunk 5 above)
Comment (ilya-nurullin) [reply options/locale/locale_en-US.ini]: Can you suggest a better name?

Comment (wxiaoguang) [reply options/locale/locale_en-US.ini]: Sorry I am not a native speaker ....

**Comment by ilya-nurullin** [comment]
Added new config section `setting.Config().Template` - the setting works with templates and not with repo itself.

I think `Empty Repo Page` makes more sense on settings page:
image

**Comment by wxiaoguang** [comment]
> I think `Empty Repo Page` makes more sense on settings page:

But it is also for "templates/repo/issue/view_content/pull_merge_instruction.tmpl", it is a guide for end users to checkout the repo into their local clone. So I think `it is for "git guide for users"`, but no idea how to express in English.

File: templates/admin/config_settings.tmpl (hunk 3 above)
Comment (wxiaoguang) [reply templates/admin/config_settings.tmpl]: > [](https://github.com/go-gitea/gitea/pull/35172/files#diff-b3b66aef8cc83304cd5cfc661233e6c1c1be656fbd6cd1e09b114348f224ff32R251)
> 
> In current architecture `func (value *Value[T]) Value(ctx context.Context) (v T)` function uses a default value only if it is not present in the database. So `null` in db, `nil` in go values are valid ones, and therefore the default value won't be used, and as a result there won't be any remote name on the page in snippets.

But if the case `null in db` happens, the "Value" itself is already wrong at many places. What would you expect to see in the "git clone command" for this case?

IMO we should fix such edge from root cause, but not add a `Def` method.

**Comment by ilya-nurullin** [comment]
Okay, 
1. I've removed `val.Def()`
2. changed `parse` function to return a default value if it is `null` in db
3. changed translation to `Git Guide`

image

File: services/context/repo.go (hunk 2 above)
Comment (lunny) [reply services/context/repo.go]: You can use `$.SystemConfig` directly if there is no special requirements.
```go
  ctx.Data["SystemConfig"] = setting.Config()
```

**Review by hiifong — APPROVED** [review]
