### PR TITLE
Fix milestone API state parameter unhandled

### LINKED ISSUE #10047: [Bug] [API] cant close milestone
as title 
tested with: gitea version 1.12.0-dev

### PR DESCRIPTION
**Pull request by lunny**
Fix #10047

### CODE REVIEW

File: models/issue_milestone.go [hunk 1]
```diff
@@ -291,12 +291,33 @@ func updateMilestone(e Engine, m *Milestone) error {
...
+func UpdateMilestone(m *Milestone, oldIsClosed bool) error {
+	sess := x.NewSession()
+	defer sess.Close()
+	if err := sess.Begin(); err != nil {
+		return err
+	}
+
+	if m.IsClosed && !oldIsClosed {
+		m.ClosedDateUnix = timeutil.TimeStampNow()
+	}
```
Comment (zeripath) [inline models/issue_milestone.go:303]: Do we need to be able to handle reopen?

Comment (lunny) [reply models/issue_milestone.go:303]: When reopen, we could just update `is_closed` to `false` and don't change `closed_date_unix` like gitea did before.

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Please send backports
