### PR TITLE
Lock goth/gothic and Re-attempt OAuth2 registration on login if registration failed at startup

### LINKED ISSUE #16096: External login source becomes disabled every now and then
- Gitea version (or commit ref): 1.14.2 (Docker image)
- Git version: (Whatever's included in the Docker image, does not seem to be relevant)
- Operating system: Linux (Docker)
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:

Did not find any mention in log, but this was running at production without debugging logs turned on. Can turn them on for a while if desired.

## Description

For some reason, `is_activated` is sometimes reset to `0` for our primary `login_source`. Although I cannot rule out external causes completely (i.e. some weird issue with MySQL replication) my suspicion is that Gitea makes this change (e.g. when the login source is temporarily unavailable?). 

## Screenshots

This is what `login_source` looks like after the source was deactivated (the first two sources are deliberately disabled, the 'bouncer' login source is the one that becomes disabled every now and then):

image

### PR DESCRIPTION
**Pull request by zeripath**
This PR has two parts:

* Add locking to goth and gothic calls with a RWMutex

The goth and gothic calls are currently unlocked and thus are a cause of multiple potential races

* Reattempt OAuth2 registration on login if registration failed

If OAuth2 registration fails at startup we currently disable the login_source however an alternative approach could be to reattempt registration on login attempt.
    
Fix #16096

### CODE REVIEW

**Comment by zeripath** [comment]
backporting the locking to 1.15 is quite easy but... backporting the re-attempt registration will involve changing the signature of oauth2.Auth to add in all of the arguments necessary to call RegisterProvider.

File: services/auth/source/oauth2/init.go [hunk 1]
```diff
@@ -71,12 +81,7 @@ func initOAuth2LoginSources() error {
 		}
 		err := oauth2Source.RegisterSource()
 		if err != nil {
-			log.Critical("Unable to register source: %s due to Error: %v. This source will be disabled.", source.Name, err)
-			source.IsActive = false
-			if err = models.UpdateSource(source); err != nil {
-				log.Critical("Unable to update source %s to disable it. Error: %v", err)
-				return err
-			}
+			log.Critical("Unable to register source: %s due to Error: %v.", source.Name, err)
```
Comment (lunny) [inline services/auth/source/oauth2/init.go:84]: These codes added here to allow Gitea start up when some auth sources take down temporarily.

Comment (zeripath) [reply services/auth/source/oauth2/init.go:84]: Yes. 

The proposed changes in the Auth and Callback handlers allow us to stop auto disabling and reattempt to register at login time if registration failed at startup. 

(But you've reminded me I need to recheck GetProviders once we have the hard lock to prevent double registration.)

If that "second" attempt at registration fails again then the user will be presented with a 500 page - but it genuinely is an internal server error at that point - although I fully expect that there will be complaints about that too.

(Hopefully such complaints would actually come with logs so we could at least attempt to present a nicer error page.)

Comment (zeripath) [reply services/auth/source/oauth2/init.go:84]: > (But you've reminded me I need to recheck GetProviders once we have the hard lock to prevent double registration.)

Actually we're ok from the double register PoV but the issue is that RegisterSource could be somewhat slow so users may double/triple attempt to login. Will have a think.

Comment (zeripath) [reply services/auth/source/oauth2/init.go:84]: Hmm... looking at routers/web/user/auth.go:582 and the changes made by #14116 resetting is actually already handled.

So I'll let #14116 handle the re-registration attempt.

**Review by lafriks — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
make lgtm work
