### PR TITLE
Fix markdown preview $$ support

### LINKED ISSUE #31481: $$ Math Markup inside tables is not supported
### Description

Github supports both single `$` and double `$$` for math blocks inside table cells, and Gitea documents `ENABLE_MATH` to support both as well. But it appears that `$$` is only supported *outside* tables, and the `pytablewriter` python module generates `$$` markup for color markup in tables.

| x     | y    |
| ------------- | ------------- |
| $2^4$ | $$2^4$$  |

See https://demo.gitea.com/microtherion/Markup/issues/1 for a demonstration.

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.45.1

### Operating System

Linux

### How are you running Gitea?

Using official docker image.

### Database

SQLite

### PR DESCRIPTION
**Pull request by charles7668**
close #31481

currently `$$A + B$$ test` will ignore text after $$ block

test text
圖片

before fix
圖片

after fix
圖片

github display
圖片

### CODE REVIEW

**Comment by wxiaoguang** [comment]
I guess we shouldn't introduce too much copy&pasted code ........

**Comment by charles7668** [comment]
> I guess we shouldn't introduce too much copy&pasted code ........我想我们不应该引入太多的复制粘贴代码........

Removed some duplicate code.

File: modules/markup/markdown/math/block_parser.go [hunk 1]
```diff
@@ -53,6 +53,12 @@ func (b *blockParser) Open(parent ast.Node, reader text.Reader, pc parser.Contex
 	}
 	idx := bytes.Index(line[pos+2:], endBytes)
 	if idx >= 0 {
+		// for case $$ ... $$ any other text
+		for i := pos + idx + 4; i < len(line); i++ {
+			if line[i] != ' ' && line[i] != '\n' {
+				return nil, parser.NoChildren
+			}
+		}
```
Comment (wxiaoguang) [inline modules/markup/markdown/math/block_parser.go:61]: What happens to `$$ a $$ xxxxxxxxx $$ b $$`?

File: modules/markup/markdown/math/inline_renderer.go [hunk 2]
```diff
@@ -21,7 +21,11 @@ func NewInlineRenderer() renderer.NodeRenderer {
 
 func (r *InlineRenderer) renderInline(w util.BufWriter, source []byte, n ast.Node, entering bool) (ast.WalkStatus, error) {
 	if entering {
-		_, _ = w.WriteString(`<code class="language-math is-loading">`)
+		if _, ok := n.(*InlineBlock); ok {
+			_, _ = w.WriteString(`<pre class="code-block is-loading"><code class="chroma language-math display">`)
+		} else {
+			_, _ = w.WriteString(`<code class="language-math is-loading">`)
```
Comment (wxiaoguang) [inline modules/markup/markdown/math/inline_renderer.go]: It could be `<code class="language-math is-loading {{some-extra-class-for-inline-or-not}}">`

File: modules/markup/markdown/math/block_parser.go (hunk 1 above)
Comment (charles7668) [reply modules/markup/markdown/math/block_parser.go:61]: > What happens to `$$ a $$ xxxxxxxxx $$ b $$`?

In the current version, any text after a $$ block will be ignored because it is rendered as a block. So, I check the character after the second $$; if any text exists, it will not be rendered as a block.

In the current version, only `a` will be displayed ,  `xxxxxxx` and `b` will disappear.
After the fix,  `a`  , `xxxxxxx`, and `b` will all be displayed.
圖片

File: modules/markup/markdown/math/inline_renderer.go (hunk 2 above)
Comment (charles7668) [reply modules/markup/markdown/math/inline_renderer.go]: > It could be `<code class="language-math is-loading {{some-extra-class-for-inline-or-not}}">`

`is-loading` is not a common `code` attribute in this case, and the class order can't be changed. If we need to change the order, we might need to update the rule in sanitizer_default.go.

Comment (wxiaoguang) [reply modules/markup/markdown/math/inline_renderer.go]: My intuition is that single `<code>` is good enough and more maintainable/consistent, while I won't block the two tags.

**Review by wxiaoguang — APPROVED** [review]

File: modules/markup/markdown/math/inline_renderer.go (hunk 2 above)
Comment (silverwind) [reply modules/markup/markdown/math/inline_renderer.go]: I think the only reason for two tags is semantical correctness.

Comment (charles7668) [reply modules/markup/markdown/math/inline_renderer.go]: I used two tags to keep the same style as the block render for the `$$` block, but one `code` tag also works.

I have updated it to the one `code` tag version.

**Review by lafriks — APPROVED** [review]
