### PR TITLE
Fix run command race

### LINKED ISSUE #1453: Data race detected
- Gitea version (or commit ref):
Gitea 1.1.0

- Git version:
git version 2.7.4

- Operating system:
Ubuntu 16.04.2 LTS

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
Apr  6 09:41:19 DIR-101 gitea[14276]: ==================
Apr  6 09:41:19 DIR-101 gitea[14276]: WARNING: DATA RACE
Apr  6 09:41:19 DIR-101 gitea[14276]: Write at 0x00c421eea368 by goroutine 136:
Apr  6 09:41:19 DIR-101 gitea[14276]:   os/exec.(*Cmd).Wait()
Apr  6 09:41:19 DIR-101 gitea[14276]:       /home/mura/tools/go/src/os/exec/exec.go:439 +0x15d
Apr  6 09:41:19 DIR-101 gitea[14276]:   code.gitea.io/gitea/vendor/code.gitea.io/git.(*Command).RunInDirTimeoutPipeline.func1()
Apr  6 09:41:19 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/code.gitea.io/git/command.go:71 +0x38
Apr  6 09:41:19 DIR-101 gitea[14276]: Previous read at 0x00c421eea368 by goroutine 148:
Apr  6 09:41:19 DIR-101 gitea[14276]:   code.gitea.io/gitea/vendor/code.gitea.io/git.(*Command).RunInDirTimeoutPipeline()
Apr  6 09:41:19 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/code.gitea.io/git/command.go:77 +0x3fe
Apr  6 09:41:19 DIR-101 gitea[14276]:   code.gitea.io/gitea/vendor/code.gitea.io/git.(*Command).RunInDirTimeout()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/code.gitea.io/git/command.go:96 +0xd1
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/vendor/code.gitea.io/git.Fsck()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/code.gitea.io/git/git.go:78 +0x103
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/models.GitFsck.func1()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/models/repo.go:1943 +0xe4
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/vendor/github.com/go-xorm/xorm.(*Session).Iterate()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/go-xorm/xorm/session_iterate.go:35 +0x1a1
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/models.GitFsck()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/models/repo.go:1951 +0x1fe
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/vendor/github.com/gogits/cron.FuncJob.Run()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/gogits/cron/cron.go:92 +0x34
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/vendor/github.com/gogits/cron.(*Cron).runWithRecovery()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/gogits/cron/cron.go:152 +0x68
Apr  6 09:41:20 DIR-101 gitea[14276]: Goroutine 136 (running) created at:
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/vendor/code.gitea.io/git.(*Command).RunInDirTimeoutPipeline()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/code.gitea.io/git/command.go:72 +0x25c
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/vendor/code.gitea.io/git.(*Command).RunInDirTimeout()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/code.gitea.io/git/command.go:96 +0xd1
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/vendor/code.gitea.io/git.Fsck()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/code.gitea.io/git/git.go:78 +0x103
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/models.GitFsck.func1()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/models/repo.go:1943 +0xe4
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/vendor/github.com/go-xorm/xorm.(*Session).Iterate()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/go-xorm/xorm/session_iterate.go:35 +0x1a1
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/models.GitFsck()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/models/repo.go:1951 +0x1fe
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/vendor/github.com/gogits/cron.FuncJob.Run()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/gogits/cron/cron.go:92 +0x34
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/vendor/github.com/gogits/cron.(*Cron).runWithRecovery()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/gogits/cron/cron.go:152 +0x68
Apr  6 09:41:20 DIR-101 gitea[14276]: Goroutine 148 (running) created at:
Apr  6 09:41:20 DIR-101 gitea[14276]:   code.gitea.io/gitea/vendor/github.com/gogits/cron.(*Cron).run()
Apr  6 09:41:20 DIR-101 gitea[14276]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/gogits/cron/cron.go:185 +0x661
Apr  6 09:41:20 DIR-101 gitea[14276]: ==================
```

### PR DESCRIPTION
**Pull request by typeless**
Use exec.CommandContext to simplify timeout handling, and fixing the data races which can be identified by the added tests when -race enabled.

Related to #1453

### CODE REVIEW

**Comment by typeless** [comment]
I'm afraid that the stdin is redirected to /dev/null within drone :(
I would have to think about other approach.

File: modules/process/manager.go [hunk 1]
```diff
@@ -6,13 +6,12 @@ package process
 
 import (
 	"bytes"
+	"context"
```
Comment (bkcsoft) [inline modules/process/manager.go:9]: This is only availably in 1.7+, we still need to support 1.6

**Review by bkcsoft — CHANGES_REQUESTED** [review]

File: modules/process/manager.go (hunk 1 above)
Comment (lunny) [reply modules/process/manager.go:9]: Why we need to support 1.6?

Comment (bkcsoft) [reply modules/process/manager.go:9]: Because some developers (@strk for example) still run 1.6. Latest version in Ubuntu 16.04 LTS is 1.6 as well http://packages.ubuntu.com/xenial/golang-go

Comment (appleboy) [reply modules/process/manager.go:9]: https://github.com/go-gitea/gitea/pull/1349 discussed before.

Comment (bkcsoft) [reply modules/process/manager.go:9]: Still not liking it 😂

Comment (typeless) [reply modules/process/manager.go:9]: We can vendor the package but the reason is less compelling since it doesn't affect end-users. Otherwise we can postpone the PR until Ubuntu catching up with the latest.

By the way, what keeps you (@bkcsoft @strk) using Ubuntu's Go rather than the official one? I'm curious if there's anything I could help.

Comment (bkcsoft) [reply modules/process/manager.go:9]: Next LTS is [18.04](https://www.ubuntu.com/info/release-end-of-life), which should include 1.7+. IMO we should wait for that until droping support for 1.6

Comment (strk) [reply modules/process/manager.go:9]: Personally I've upgraded already, so don't think about me. Just think about random possible contributor staying safe in her latest debian/ubuntu/fedora stable system. We want to reduce the barriers of entry for any contributor.

We should also have Drone test all Go versions we want to support. For comparison Gogs is Travis-tested against Go versions from 1.5 to master.

Comment (typeless) [reply modules/process/manager.go:9]: I don't agree that strictly supporting old toolchains would reward the project's developers and users that much, if any. Just speaking for my own opinion though. ❤️

**Comment by strk** [comment]
It's not about reward but entry barrier.

Developers are a scarce resource, and even many of
the documented maintainers are being increasily inactive.
For these reasons I think we should lower the barrier as much
as possible. From low dependencies to documented procedures and
codebase, to easy to use testing frameworks...

**Comment by lunny** [comment]
We could drop Go v1.6 support on Gitea v1.3, so I moved this to v1.3

**Comment by sapk** [comment]
Go v1.6 is already drop in git module so dropped in gitea. https://github.com/go-gitea/git/blob/master/command.go#L9

**Comment by lunny** [comment]
So that we only need to add an implicated declare on some README or other document.

**Comment by lafriks** [comment]
@bkcsoft need your approval

File: modules/process/manager.go (hunk 1 above)
Comment (bkcsoft) [reply modules/process/manager.go:9]: 18.10 is released and have Go 1.8 so no need for this change.

**Review by bkcsoft — APPROVED** [review]

File: modules/process/manager.go [hunk 2]
```diff
@@ -111,30 +113,15 @@ func (pm *Manager) ExecDirEnv(timeout time.Duration, dir, desc string, env []str
...
-	case err = <-done:
-	}
-
+	err := cmd.Wait()
 	pm.Remove(pid)
 
-	if err != nil {
-		out := fmt.Errorf("exec(%d:%s) failed: %v stdout: %v stderr: %v", pid, desc, err, stdOut, stdErr)
-		return stdOut.String(), stdErr.String(), out
+	if err == nil {
```
Comment (bkcsoft) [inline modules/process/manager.go]: I'd change the error-handling to a more go-esque way
```go
if err != nil {
  err = fmt.Errorf(...) // NOTE: include the original error as well as the `ctx.Err()`...
}

return stdOut.String(), stdErr.String(), err
```

**Review by bkcsoft — CHANGES_REQUESTED** [review]

File: modules/process/manager.go [hunk 3]
```diff
@@ -101,7 +100,10 @@ func (pm *Manager) ExecDirEnv(timeout time.Duration, dir, desc string, env []str
 	stdOut := new(bytes.Buffer)
 	stdErr := new(bytes.Buffer)
 
-	cmd := exec.Command(cmdName, args...)
+	ctx, cancel := context.WithTimeout(context.Background(), timeout)
```
Comment (bkcsoft) [inline modules/process/manager.go:103]: What happens if the `timeout` is negative? (Since the functions docs says to use `-1 for DefaultTimeout` (which we don't seems to honour... )

Comment (lunny) [reply modules/process/manager.go:103]: @bkcsoft The first line on this function has checked that. if timeout == -1 timout = 60 *time.Second

File: modules/process/manager.go (hunk 2 above)
Comment (lunny) [reply modules/process/manager.go]: @typeless maybe you could change this.

**Comment by lunny** [comment]
LGTM except @bkcsoft 's second comment I agree with.

File: modules/process/manager.go (hunk 2 above)
Comment (typeless) [reply modules/process/manager.go]: Done.

File: modules/process/manager.go (hunk 3 above)
Comment (typeless) [reply modules/process/manager.go:103]: Do you want 
```
if timeout < 0 {
    timeout = 60 * time.Second
}
``` 
?

**Review by bkcsoft — APPROVED** [review]

**Comment by bkcsoft** [comment]
LGTM

**Comment by typeless** [comment]
The following error doesn't seem to be caused by the pull request.
```
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Operation timed out
128s
```

**Comment by lafriks** [comment]
Yes it's just random drone failure

**Comment by lunny** [comment]
@lafriks that's a network error not caused by this PR. I will test it twice again then I will move it to v1.3.0 and merge it.
