### PR TITLE
Fix network error when open/close organization/individual projects and redirect to project page

### LINKED ISSUE #30901: Network Error when opening a closed project
### Description

Hi,

I have a closed project that I want to open - however when I click on the ```Open``` button I get a ```Network Error``` message as seen in the screenshot and the project does not open. When I look at the error logs from the browser console I see:

```
error when doRequest SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

Any ideas why this could be the case?

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

networkerror

### Git Version

_No response_

### Operating System

Linux

### How are you running Gitea?

Using one of the downloads

### Database

None

### PR DESCRIPTION
**Pull request by yp05327**
Follow #27734
Fix #30901 

image

Updated:
Redirect to project page instead of project list page.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: routers/web/org/projects.go [hunk 1]
```diff
@@ -195,22 +195,27 @@ func NewProjectPost(ctx *context.Context) {
...
 	}
 	id := ctx.ParamsInt64(":id")
 
 	if err := project_model.ChangeProjectStatusByRepoIDAndID(ctx, 0, id, toClose); err != nil {
-		ctx.NotFoundOrServerError("ChangeProjectStatusByRepoIDAndID", project_model.IsErrProjectNotExist, err)
+		if project_model.IsErrProjectNotExist(err) {
+			ctx.NotFound("", err)
+		} else {
+			ctx.ServerError("ChangeProjectStatusByRepoIDAndID", err)
+		}
```
Comment (delvh) [inline routers/web/org/projects.go]: ?

Comment (yp05327) [reply routers/web/org/projects.go]: Ah, my bad

**Review by lunny — APPROVED** [review]

**Review by silverwind — APPROVED** [review]
