### PR TITLE
Reload issue when sending webhook to make num comments is right.

### LINKED ISSUE #35229: Webhook value comments contains wrong comment count
### Description

Hello,
when I add or delete an issue comment via the web interface the webhook action "comment created/deleted" reports the old value in the `comments` field.

### Gitea Version

1.24.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

I don't know

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix #35229

### CODE REVIEW

File: services/issue/comments.go [hunk 1]
```diff
@@ -80,6 +80,12 @@ func CreateIssueComment(ctx context.Context, doer *user_model.User, repo *repo_m
 		return nil, err
 	}
 
+	// reaload issue to ensure it has the latest data, especially the number of comments
```
Comment (kemzeb) [inline services/issue/comments.go]: nit: reaload -> reload

File: services/webhook/notifier.go [hunk 2]
```diff
@@ -481,6 +481,7 @@ func (m *webhookNotifier) DeleteComment(ctx context.Context, doer *user_model.Us
 		log.Error("LoadPoster: %v", err)
 		return
 	}
+	comment.Issue = nil // reload issue to ensure it has the latest data, especially the number of comments
 	if err = comment.LoadIssue(ctx); err != nil {
```
Comment (kemzeb) [inline services/webhook/notifier.go:485]: note: I pondered if it would be better to reload the comment count in `issue_service.DeleteComment()` before passing it to the notify service. But since the only other notifier that I can see who implements `DeleteComment()` (i.e. [actions](https://github.com/go-gitea/gitea/blob/main/services/actions/notifier.go)) reloads the issue I believe this is fine

Comment (kemzeb) [reply services/webhook/notifier.go:485]: I just realized that the actions [notifier](https://github.com/go-gitea/gitea/blob/c4c1a4bd18a6b38aa7ae3f3763258a728fbe1806/services/actions/notifier.go#L281) does not set it's old issue to `nil`, which would mean `comment.LoadIssue()` would just use the old issue object. Based on this and looking at other areas of the codebase, I believe this may also return an old comment count.

I will approve since this is out-of-scope of the issue, but you are more than welcome to resolve if my analysis is correct

**Review by kemzeb — APPROVED** [review]

File: services/webhook/notifier.go (hunk 2 above)
Comment (lunny) [reply services/webhook/notifier.go:485]: I think you are right. aef2e2f491 will fix the same problem in the actions notifier

**Review by kemzeb — APPROVED** [review]

**Review by hiifong — APPROVED** [review]
