### PR TITLE
Redesign Scoped Access Tokens

### LINKED ISSUE #24501: [Proposal] Redesign Scoped Personal Access Tokens (PATs) / Fine Grained Personal Access Tokens
### Feature Description

There are a number of issues with scoped access tokens currently, ranging from UI/UX to implementation. 

The gitea implementation of scoped PATs was clearly based off of GitHub's original implementation, which inherits some issues:
 - GH's token scopes never really made sense and have since [been depricated](https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/)
   - You couldn't give separate read vs write permissions to repos
   - They were always ambiguous as to what the scopes gave access to

Additionally, our implementation had to map the odd GH scopes to our API routes, which further complicates the implementation, and leaves `reqToken` calls sprinkled around the code (which introduces bugs now and will be difficult to maintain going forward). 

Consider that we already have a nice hierarchy of scopes introduced by the API - imo, there is no reason to remap these to arbitrary GH scopes. I propose the following high-level scopes:
 - `activitypub`
 - `admin` (hidden if user is not a site admin)
 - `misc`
 - `notification`
 - `organization`
 - `package`
 - `issue`
 - `repository`
 - `user`

The for each of the above we have an option for:
 - `read`
 - `write`
 - `delete`

We also add an option at the top for:
 - only public repositories / orgs

This will be significantly easier for users to understand and for us to document and maintain, and it more closely matches the direction GitHub is moving.

While we're here, some further improvements:
 - By default in the UI, scopes are collapsed, meaning that if a user just creates a PAT without expanding the hidden scopes, they won't have access to anything (or will it? it's unclear what "no scopes" implies).
   - Solution: if no scopes literally gives access to nothing, the "create" button should be disabled if no scopes are selected.
   - if no scopes gives access to something, we should have a "scope" that explains what that access is, and is always checked.
   - edit: apparently default is `all`, but the shows Scopes: `(empty)' and not `all`
 - Tooltips & documentation embedded in the scoped access tokens UI
 - In GH, if you selected a higher level scope (eg. "repo") it would automatically check the lower level scopes (eg. `repo:status` and `public_repo`), however, it does not for us. So what happens if I select `repo` ("Full control over all repositories."), but not "repo:status")? 
   - Solution: selecting a higher level scope should select all of the lower level scopes
 - User shouldn't be able to select scopes they themselves do not have access to. It's confusing and misleading. We should disable those options.
 - Allow to set a expiry on tokens
 - Allow to scope to repo

### Screenshots
eg.
image

### LINKED ISSUE #24799: [BUG] [nightly] Personal Access Tokens don't work
### Description

On the nightly build of gitea 1e1e8b5d43a36aa788ce0973fa57ac6df648cbd0, Generating Tokens no longer has `scope` option. As a result, the generated tokens are useless, and are not able to clone private repositories, etc.

### Gitea Version

1e1e8b5d43a36aa788ce0973fa57ac6df648cbd0 (commit SHA)

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://paste.evanferrao.win/raw/lh22z6t

### Screenshots

I'm uploading a screen recording instead of a screenshot. It helps to understand way faster.

[Gitea Token Scope missing.webm](https://github.com/go-gitea/gitea/assets/130160624/173b64c5-cdef-4303-8410-84fbe4aa01f3)

### Git Version

2.40.1, Wire Protocol Version 2 Enabled

### Operating System

ZorinOS 16 based on ubuntu 20.04 LTS

### How are you running Gitea?

I'm running gitea using docker-compose. I've attached it below.

```
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:nightly
    container_name: gitea
    restart: always
    environment:
      - GITEA__log__MODE="console"
      - GITEA__log__ROUTER="console"
      - GITEA__log__LEVEL="debug"
      - GITEA__log__STACKTRACE_LEVEL="debug"
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /home/git/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:2222:22"
```

### Database

SQLite

### PR DESCRIPTION
**Pull request by jackHay22**
## Changes
- Adds the following high level access scopes, each with `read` and `write` levels:
    - `activitypub`
    - `admin` (hidden if user is not a site admin)
    - `misc`
    - `notification`
    - `organization`
    - `package`
    - `issue`
    - `repository`
    - `user`
- Adds new middleware function `tokenRequiresScopes()` in addition to `reqToken()`
  -  `tokenRequiresScopes()` is used for each high-level api section
     - _if_ a scoped token is present, checks that the required scope is included based on the section and HTTP method
  - `reqToken()` is used for individual routes
    - checks that required authentication is present (but does not check scope levels as this will already have been handled by `tokenRequiresScopes()`
- Adds migration to convert old scoped access tokens to the new set of scopes
- Updates the user interface for scope selection

### User interface example
Screen Shot 2023-05-31 at 1 56 55 PM
Screen Shot 2023-05-31 at 1 56 43 PM

## tokenRequiresScopes  Design Decision
- `tokenRequiresScopes()` was added to more reliably cover api routes. For an incoming request, this function uses the given scope category (say `AccessTokenScopeCategoryOrganization`) and the HTTP method (say `DELETE`) and verifies that any scoped tokens in use include `delete:organization`.
- `reqToken()` is used to enforce auth for individual routes that require it. If a scoped token is not present for a request, `tokenRequiresScopes()` will not return an error

## TODO
- [x] Alphabetize scope categories
- [x] Change 'public repos only' to a radio button (private vs public). Also expand this to organizations
- [X] Disable token creation if no scopes selected. Alternatively, show warning
- [x] `reqToken()` is missing from many `POST/DELETE` routes in the api. `tokenRequiresScopes()` only checks that a given token has the correct scope,  `reqToken()` must be used to check that a token (or some other auth) is present.
   -  _This should be addressed in this PR_
- [x] The migration should be reviewed very carefully in order to minimize access changes to existing user tokens. 
   - _This should be addressed in this PR_
- [x] Link to api to swagger documentation, clarify what read/write/delete levels correspond to
- [x] Review cases where more than one scope is needed as this directly deviates from the api definition. 
   - _This should be addressed in this PR_
   - For example: 
   ```go
	m.Group("/users/{username}/orgs", func() {
		m.Get("", reqToken(), org.ListUserOrgs)
		m.Get("/{org}/permissions", reqToken(), org.GetUserOrgsPermissions)
	}, tokenRequiresScopes(auth_model.AccessTokenScopeCategoryUser, auth_model.AccessTokenScopeCategoryOrganization), context_service.UserAssignmentAPI())
   ```

## Future improvements
- [ ] Add required scopes to swagger documentation
- [ ] Redesign `reqToken()` to be opt-out rather than opt-in
- [ ] Subdivide scopes like `repository`
- [ ] Once a token is created, if it has no scopes, we should display text instead of an empty bullet point
- [ ] If the 'public repos only' option is selected, should read categories be selected by default

Closes #24501
Closes #24799

## Why is this PR marked as `breaking`?

~~This PR is not breaking, all existing tokens are converted to the new equivalent.
However, users might want to regenerate their tokens now as the scopes have drastically changed which can have security implications.~~

As we've discovered in the meantime, there is already an API route that allows generating new tokens and setting their scopes (https://gitea.com/api/swagger#/user/userCreateToken).
Previously working API calls with the old scopes do not work anymore as the corresponding scopes no longer exist.

### CODE REVIEW

File: web_src/js/components/ScopedAccessTokenSelector.vue [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+        <div class="ui checkbox">
+          <input ref="write" v-model="writeSelected" :disabled="categorySelected" class="enable-system" type="checkbox" name="scope" :value="'write:' + category" @change="onIndividualInput">
+          <label>write:{{ category }}</label>
+        </div>
+      </div>
+      <div class="field">
+        <div class="ui checkbox">
+          <input ref="delete" v-model="deleteSelected" :disabled="categorySelected" class="enable-system" type="checkbox" name="scope" :value="'delete:' + category" @change="onIndividualInput">
+          <label>delete:{{ category }}</label>
+        </div>
```
Comment (wxiaoguang) [inline web_src/js/components/ScopedAccessTokenSelector.vue]: `ui checkbox` only works for Fomantic UI checkbox in templates.

For Vue, it doesn't work well. I think it could be simple `<label><input></label>` here

Comment (jackHay22) [reply web_src/js/components/ScopedAccessTokenSelector.vue]: It looks like we'll lose some of the styling that way: 
Screen Shot 2023-05-17 at 10 09 24 AM

Comment (wxiaoguang) [reply web_src/js/components/ScopedAccessTokenSelector.vue]: No worry, there are already some PRs doing so:

* #23596

It won't be a problem.

File: models/migrations/v1_20/v257.go [hunk 2]
```diff
@@ -0,0 +1,143 @@
...
+	OldAccessTokenScopeAdminApplication OldAccessTokenScope = "admin:application"
+	OldAccessTokenScopeWriteApplication OldAccessTokenScope = "write:application"
+	OldAccessTokenScopeReadApplication  OldAccessTokenScope = "read:application"
+
+	OldAccessTokenScopeSudo OldAccessTokenScope = "sudo"
+)
+
+var accessTokenScopeMap = map[OldAccessTokenScope][]auth_model.AccessTokenScope{
+	OldAccessTokenScopeAll:              {auth_model.AccessTokenScopeAll},
+	OldAccessTokenScopeRepo:             {auth_model.AccessTokenScopeDeleteRepository},
```
Comment (delvh) [inline models/migrations/v1_20/v257.go]: As far as I know, we shouldn't depend on external types for migrations in case they are changed later on.
Instead, hardcode the corresponding replacements

File: web_src/js/components/ScopedAccessTokenSelector.vue (hunk 1 above)
Comment (silverwind) [reply web_src/js/components/ScopedAccessTokenSelector.vue]: That PR was only for the issue list, not globally which is still TODO.

File: modules/context/permission.go [hunk 3]
```diff
@@ -111,28 +111,36 @@ func RequireRepoReaderOr(unitTypes ...unit.Type) func(ctx *Context) {
...
 			return
 		}
-		if !scopeMatched && !repo.IsPrivate {
-			scopeMatched, err = scope.HasScope(auth_model.AccessTokenScopePublicRepo)
-			if err != nil {
-				ctx.ServerError("HasScope", err)
-				return
-			}
+
+		if publicOnly && repo.IsPrivate {
```
Comment (delvh) [inline modules/context/permission.go:133]: How are limited repos stored?

File: web_src/js/components/ScopedAccessTokenSelector.vue (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/components/ScopedAccessTokenSelector.vue]: It really needs some framework level support now.

Otherwise, `ui checkbox` in Vue would make the label part can't toggle the checkbox, which is very annoying for users.

Comment (silverwind) [reply web_src/js/components/ScopedAccessTokenSelector.vue]: > Otherwise, ui checkbox in Vue would make the label part can't toggle the checkbox, which is very annoying for users.

Is nesting checkbox inside label not an option? How about a `for` attribute?

Comment (wxiaoguang) [reply web_src/js/components/ScopedAccessTokenSelector.vue]: > Is nesting checkbox inside label not an option?

IMO "nesting checkbox inside label" is the proper way.

> How about a for attribute?

1. It would conflict a lot
2. It just introduces unnecessary IDs and makes code hard to read or maintain.

Comment (wxiaoguang) [reply web_src/js/components/ScopedAccessTokenSelector.vue]: In history , there were commits like this:

https://github.com/go-gitea/gitea/compare/583d5738b53673743672d8b8860f73d1ba9f50fb..2f2450f316f13ee6085be9da1cb2a16d28e4e5ad

(this commit reverts unnecessary changes in #22593 

Manually adding ID/FOR attributes, I have strong objection for doing so because it's unmaintainable.

So a new PR replaces it: https://github.com/go-gitea/gitea/pull/22599 


----

If there is no special requirement,  it's better to use `<label><input checkbox></label>` as much as possible.

Comment (silverwind) [reply web_src/js/components/ScopedAccessTokenSelector.vue]: Yes, nesting is better if possible. If not, we could autogenerate via something similar to react [`useId`](https://react.dev/reference/react/useId) in the Vue case.

File: routers/api/v1/api.go [hunk 4]
```diff
@@ -236,44 +236,79 @@ func reqPackageAccess(accessMode perm.AccessMode) func(ctx *context.APIContext)
...
-			return
-		}
-
 		// If OAuth2 token is present
 		if _, ok := ctx.Data["ApiTokenScope"]; ctx.Data["IsApiToken"] == true && ok {
 			// no scope required
-			if requiredScope == "" {
+			if len(requiredScopeCategories) == 0 {
 				return
 			}
```
Comment (delvh) [inline routers/api/v1/api.go]: Actually, I think this check can be moved  to be the first instruction of this method.

File: routers/api/v1/api.go [hunk 5]
```diff
@@ -236,44 +236,79 @@ func reqPackageAccess(accessMode perm.AccessMode) func(ctx *context.APIContext)
...
+// if a token is not being used, reqToken will enforce other sign in methods
+func tokenRequiresScopes(requiredScopeCategories ...auth_model.AccessTokenScopeCategory) func(ctx *context.APIContext) {
 	return func(ctx *context.APIContext) {
-		// If actions token is present
-		if true == ctx.Data["IsActionsToken"] {
-			return
-		}
-
 		// If OAuth2 token is present
 		if _, ok := ctx.Data["ApiTokenScope"]; ctx.Data["IsApiToken"] == true && ok {
```
Comment (delvh) [inline routers/api/v1/api.go]: Instead of keeping everything this intended, what about short circuiting when it isn't present?
So, what I mean is
```go
if _, ok := ctx.Data["ApiTokenScope"]; ctx.Data["IsApiToken"] != true || !ok {
  return
}
```

File: routers/api/v1/api.go [hunk 6]
```diff
@@ -236,44 +236,79 @@ func reqPackageAccess(accessMode perm.AccessMode) func(ctx *context.APIContext)
...
 			// no scope required
-			if requiredScope == "" {
+			if len(requiredScopeCategories) == 0 {
 				return
 			}
 
-			// check scope
+			// get the scope from the request
 			scope := ctx.Data["ApiTokenScope"].(auth_model.AccessTokenScope)
```
Comment (delvh) [inline routers/api/v1/api.go]: By the way, can't we combine this check in the same one above?
```go
if scope, ok := ctx.Data["ApiTokenScope"].(auth_model.AccessTokenScope)
```
That way, we don't check twice, and we "only" get a security problem instead of an unusable instance if the returned value is not an access token scope for some reason.

**Review by kdumontnu — CHANGES_REQUESTED** [review]
This is a huge improvement! 💯 for the updated tests with only the access they require.

Do you add any tests that assert no access when out of scope?

I think the Public Repos Only checkbox needs to be restyled as well
image

I think we need to do something about having none of the scopes selected by default and scopes collapsed by default. 
image
- Is a token with no scopes useful at all? Just trying to understand if this is an actual use-case
- We should at least update the UI so that a token with no scopes says _None_ instead of blank after the token is created.
- I don't think toggling the scopes on by default on the page makes sense, because it eats up all of the vertical real-estate (for example if you were only interested in the sections below).
- Some options:
  - A warning if the token has no scopes set, either in the UI or a modal
  - The current behavior of default to "all" (this seems like a bad default)
  - A ui that shows which scopes the token has in real-time in a list (similar to the list shown after the token is created). One issue here is that the UI redrawing when checking/unchecking sounds annoying.

"Applications using a token have full access to your account." - this should be updated

"Public repos Only" should be "Public repositories and organizations only" 
  - should read settings be checked by default (and disabled if that is checked?
 
We should define read, write, and delete.

We should also explicitly define where the scopes are coming from (with a link to the API)

Maybe consider GitHub's fine-grained access tokens summary or other UI dropdowns.

A warning or block user from creating a token with no scopes?

Add section (badge/label?) in swagger for each route that says what required scope is.

@jtran any thoughts here?

**Comment by jtran** [comment]
The whole point of the scopes is to deny access when a token doesn't have permission.  I'm afraid that when people add new routes in the future, it will be error prone to accidentally copy the access of other routes and use the wrong one.  It would be nice if we could test that we accurately deny access by looping over each route, something like this in pseduocode:

```
for each route {
    create token with all scopes except the one required for this route
    request the route
    assert that the response is permission denied
}
```

**Comment by jtran** [comment]
For the UI, a few things to simplify it from the user's perspective, partly inspired by GitHub's redesigned UI for fine-grained access tokens, which is pretty good, in my opinion.

- Rename "scopes" to "permissions".  (In the UI only.)
- Most scopes control _what_ can be done, but the "public repos only" checkbox controls _where_ it can be done.  We should pull out "Public repos only" to be above the selection of scopes, not part of it.  GitHub has a radio option to choose between "Public Repositories (read-only)" and "All repositories".  I think this is much clearer and less confusing to new users.  Again, this is all in the UI only.  I'm not suggesting any internal changes.

**Comment by jackHay22** [comment]
>     * Most scopes control _what_ can be done, but the "public repos only" checkbox controls _where_ it can be done.  We should pull out "Public repos only" to be above the selection of scopes, not part of it.  GitHub has a radio option to choose between "Public Repositories (read-only)" and "All repositories".  I think this is much clearer and less confusing to new users.  Again, this is all in the UI only.  I'm not suggesting any internal changes.

How does this look? 
Screen Shot 2023-05-18 at 3 41 34 PM

File: models/migrations/v1_20/v257.go [hunk 7]
```diff
@@ -0,0 +1,143 @@
...
+	for _, token := range tokens {
+		allNewScopesMap := make(map[auth_model.AccessTokenScope]bool)
+		for _, oldScope := range strings.Split(token.Scope, ",") {
+			if newScopes, exists := accessTokenScopeMap[OldAccessTokenScope(oldScope)]; exists {
+				for _, newScope := range newScopes {
+					allNewScopesMap[newScope] = true
+				}
+			} else {
+				return fmt.Errorf("old access token scope %s does not exist", oldScope)
+			}
```
Comment (delvh) [inline models/migrations/v1_20/v257.go]: The migration should be a no-op when the token has been converted already.
There is a non-null chance that migrations are re-executed.
The problematic thing is rather checking if it is a valid new scope.
I'm not entirely sure how to handle invalid scopes… simply keep them perhaps?
An error is certainly not the correct answer here as that means if something is messed up for any repo, the whole migration fails.

File: routers/api/v1/api.go [hunk 8]
```diff
@@ -236,44 +236,79 @@ func reqPackageAccess(accessMode perm.AccessMode) func(ctx *context.APIContext)
...
+			publicOnly, err := scope.PublicOnly()
 			if err != nil {
-				ctx.Error(http.StatusForbidden, "reqToken", "parsing token failed: "+err.Error())
+				ctx.Error(http.StatusForbidden, "tokenRequiresScope", "parsing public resource scope failed: "+err.Error())
 				return
 			}
-			if allow {
+
+			if publicOnly && auth_model.ContainsCategory(requiredScopeCategories, auth_model.AccessTokenScopeCategoryRepository) &&
+				ctx.Repo.Repository != nil && ctx.Repo.Repository.IsPrivate {
```
Comment (delvh) [inline routers/api/v1/api.go]: limited repos when the doer is signed in?

File: routers/api/v1/api.go [hunk 9]
```diff
@@ -236,44 +236,79 @@ func reqPackageAccess(accessMode perm.AccessMode) func(ctx *context.APIContext)
...
 
-			// if requires 'repo' scope, but only has 'public_repo' scope, allow it only if the repo is public
-			if requiredScope == auth_model.AccessTokenScopeRepo {
-				if allowPublicRepo, err := scope.HasScope(auth_model.AccessTokenScopePublicRepo); err == nil && allowPublicRepo {
-					if ctx.Repo.Repository != nil && !ctx.Repo.Repository.IsPrivate {
-						return
-					}
-				}
+			if publicOnly && auth_model.ContainsCategory(requiredScopeCategories, auth_model.AccessTokenScopeCategoryOrganization) &&
+				ctx.Org.Organization != nil && ctx.Org.Organization.Visibility != api.VisibleTypePublic {
```
Comment (delvh) [inline routers/api/v1/api.go]: limited orgs when the doer is signed in?

File: models/auth/token_scope.go [hunk 10]
```diff
@@ -6,175 +6,259 @@ package auth
...
+// AccessTokenScope represents the scope for an access token.
+type AccessTokenScope string
 
-	AccessTokenScopeAdminRepoHook AccessTokenScope = "admin:repo_hook"
-	AccessTokenScopeWriteRepoHook AccessTokenScope = "write:repo_hook"
-	AccessTokenScopeReadRepoHook  AccessTokenScope = "read:repo_hook"
+// for all categories, delete implies write, write implies read
+const (
+	AccessTokenScopeAll        AccessTokenScope = "all"
+	AccessTokenScopePublicOnly AccessTokenScope = "public" // limited to public orgs/repos
```
Comment (delvh) [inline models/auth/token_scope.go]: Should we perhaps call it `public-only`?
I think that prevents some confusion…

File: models/auth/token_scope.go [hunk 11]
```diff
@@ -6,175 +6,259 @@ package auth
...
+		AccessTokenScopeCategoryPackage:      AccessTokenScopeDeletePackage,
+		AccessTokenScopeCategoryIssue:        AccessTokenScopeDeleteIssue,
+		AccessTokenScopeCategoryRepository:   AccessTokenScopeDeleteRepository,
+		AccessTokenScopeCategoryUser:         AccessTokenScopeDeleteUser,
+	},
+}
+
+// GetRequiredScopes gets the specific scopes for a given level and categories
+func GetRequiredScopes(level AccessTokenScopeLevel, scopeCategories ...AccessTokenScopeCategory) []AccessTokenScope {
+	scopes := make([]AccessTokenScope, 0)
```
Comment (delvh) [inline models/auth/token_scope.go]:
```suggestion
	scopes := make([]AccessTokenScope, 0, len(scopeCategories))
```

File: routers/api/v1/api.go (hunk 6 above)
Comment (wxiaoguang) [reply routers/api/v1/api.go]: It should be a struct field in APIContext, or a sub struct field like APIContext.APIToken.TokenScope

(including the `_, ok := ctx.Data["ApiTokenScope"]; ctx.Data["IsApiToken"] != true || !ok` above and other similar fields)

**Comment by delvh** [comment]
Is this PR still maintained?
It is blocking 1.20.0-rc0, and that is supposed to be released at the end of the week…

**Comment by kdumontnu** [comment]
> Is this PR still maintained? It is blocking 1.20.0-rc0, and that is supposed to be released at the end of the week…

Yes, we're working on the suggested changes over the next day or two. Thanks for the review.

File: modules/context/permission.go (hunk 3 above)
Comment (jtran) [reply modules/context/permission.go:133]: I believe limited visibility is only for organizations, not repos.

Comment (delvh) [reply modules/context/permission.go:133]: Let's hope so.
Limited repos/ orgs are one of the things I have no idea how they work internally.

File: models/auth/token_scope_test.go [hunk 12]
```diff
@@ -53,25 +44,32 @@ func TestAccessTokenScope_Normalize(t *testing.T) {
...
+		{"delete:package", "all", false, nil},
+		{"public-only", "read:issue", false, nil},
+	}
+
+	for _, scope := range []string{"activitypub", "admin", "misc", "notification", "organization", "package", "issue", "repository", "user"} {
+		tests = append(tests,
+			scopeTestHasScope{AccessTokenScope(fmt.Sprintf("read:%s", scope)), AccessTokenScope(fmt.Sprintf("read:%s", scope)), true, nil},
+			scopeTestHasScope{AccessTokenScope(fmt.Sprintf("write:%s", scope)), AccessTokenScope(fmt.Sprintf("write:%s", scope)), true, nil},
+			scopeTestHasScope{AccessTokenScope(fmt.Sprintf("delete:%s", scope)), AccessTokenScope(fmt.Sprintf("delete:%s", scope)), true, nil},
+			scopeTestHasScope{AccessTokenScope(fmt.Sprintf("write:%s", scope)), AccessTokenScope(fmt.Sprintf("read:%s", scope)), true, nil},
```
Comment (delvh) [inline models/auth/token_scope_test.go]:
```suggestion
			scopeTestHasScope{AccessTokenScope(fmt.Sprintf("write:%s", scope)), AccessTokenScope(fmt.Sprintf("read:%s", scope)), true, nil},
			scopeTestHasScope{AccessTokenScope(fmt.Sprintf("delete:%s", scope)), AccessTokenScope(fmt.Sprintf("read:%s", scope)), true, nil},
```

File: web_src/js/components/ScopedAccessTokenSelector.vue [hunk 13]
```diff
@@ -0,0 +1,156 @@
...
+      if (this.$refs.delete.checked) {
+        this.readSelected = true;
+        this.writeSelected = true;
+        this.categorySelected = true;
+      }
+      if (this.$refs.write.checked) {
+        this.readSelected = true;
+      }
+    },
+  }
```
Comment (delvh) [inline web_src/js/components/ScopedAccessTokenSelector.vue]: I've noticed a slight disconnect between the behaviors which I think we should fix:
When you click on a top level checkbox, all sub-checkboxes are checked.
By clicking on the checkbox again, all sub-checkboxes are deselected.
Okay, so far so good.

However, if you click on the `delete` checkbox, all sub-checkboxes get disabled, so you have to navigate to the top-level checkbox to disable the scopes again.
It would probably better to always enable the `delete` checkbox so that you can immediately undo an accidental click.

Furthermore, if you click on the `write` checkbox, you enable the `read` checkbox as well.
But if you deselect `write` again,  `read` is still selected.
It would probably be better to be consistent, and deselect the `read` checkbox in this case as well.

These behavior changes don't block the PR for now, but should be fixed in subsequent PRs.

File: templates/user/settings/applications.tmpl [hunk 14]
```diff
@@ -40,222 +48,43 @@
...
+						<input class="enable-system" type="radio" name="scope" value="{{$.AccessTokenScopePublicOnly}}" style="margin: 4px 5px 0 0">
+						{{.locale.Tr "settings.permissions_public_only"}}
+					</label>
+					<label style="cursor: pointer">
+						<input class="enable-system" type="radio" name="scope" value="" style="margin: 4px 5px 0 0" checked>
+						{{.locale.Tr "settings.permissions_access_all"}}
+					</label>
+				</div>
+				<details class="ui optional field">
 					<summary class="gt-p-2">
```
Comment (delvh) [inline templates/user/settings/applications.tmpl]: Based on my own instinct, I rather recommend something like
```suggestion
					<summary class="gt-pb-4 gt-pl-2">
```

File: templates/user/settings/applications.tmpl [hunk 15]
```diff
@@ -40,222 +48,43 @@
...
-					<div class="field">
-						<div class="ui checkbox">
-							<input class="enable-system" type="checkbox" name="scope" value="sudo">
-							<label>sudo</label>
-						</div>
-					</div>
+					<scoped-access-token-category category="activitypub"></scoped-access-token-category>
+					{{if .IsAdmin}}
+						<scoped-access-token-category category="admin"></scoped-access-token-category>
+					{{end}}
```
Comment (delvh) [inline templates/user/settings/applications.tmpl:78]: Hmm… We should probably also check when persisting the scopes that a non-admin didn't maliciously add an admin scope for themselves.
Having an admin scope on a token might give a false sense of security for developers.
(I don't know if this is currently done already but I guess not).

File: templates/user/settings/applications.tmpl [hunk 16]
```diff
@@ -40,222 +48,43 @@
...
+					<!-- issue is intentionally omitted. -->
+					<scoped-access-token-category category="misc"></scoped-access-token-category>
+					<scoped-access-token-category category="notification"></scoped-access-token-category>
+					<scoped-access-token-category category="organization"></scoped-access-token-category>
+					<scoped-access-token-category category="package"></scoped-access-token-category>
+					<scoped-access-token-category category="repository"></scoped-access-token-category>
+					<scoped-access-token-category category="user"></scoped-access-token-category>
 				</details>
-				<button class="ui green button">
+				<div id="scoped-access-warning" class="ui warning message center" style="display: none">
```
Comment (delvh) [inline templates/user/settings/applications.tmpl]: Use `gt-hidden` instead.

File: templates/user/settings/applications.tmpl [hunk 17]
```diff
@@ -40,222 +48,43 @@
...
 				</div>
-				<!--Temporarily disable-->
-				<details class="gt-hidden ui optional field">
+				<div class="field">
+					<label>{{.locale.Tr "settings.repo_and_org_access"}}</label>
+					<label style="cursor: pointer">
+						<input class="enable-system" type="radio" name="scope" value="{{$.AccessTokenScopePublicOnly}}" style="margin: 4px 5px 0 0">
+						{{.locale.Tr "settings.permissions_public_only"}}
+					</label>
+					<label style="cursor: pointer">
```
Comment (delvh) [inline templates/user/settings/applications.tmpl]: Please do not use inline styles.
Use or define a helper class instead.
I think there is already a helper for that.

File: web_src/js/components/ScopedAccessTokenSelector.vue [hunk 18]
```diff
@@ -0,0 +1,156 @@
...
+  document.getElementById('scoped-access-submit')?.addEventListener('click', (e) => {
+    e.preventDefault();
+    // check that at least one scope has been selected
+    for (const el of document.getElementsByClassName('scoped-access-token-input')) {
+      if (el.checked) {
+        document.getElementById('scoped-access-form').submit();
+      }
+    }
+    // no scopes selected, show validation error
+    document.getElementById('scoped-access-warning').style.display = 'block';
```
Comment (silverwind) [inline web_src/js/components/ScopedAccessTokenSelector.vue]: use `showElem` from `web_src/js/utils/dom.js` instead

Comment (kdumontnu) [reply web_src/js/components/ScopedAccessTokenSelector.vue]: Should be all set 👍

Comment (silverwind) [reply web_src/js/components/ScopedAccessTokenSelector.vue]: Thanks.

File: templates/user/settings/applications.tmpl (hunk 17 above)
Comment (silverwind) [reply templates/user/settings/applications.tmpl]: was resolved

File: templates/user/settings/applications.tmpl (hunk 16 above)
Comment (silverwind) [reply templates/user/settings/applications.tmpl]: was resolved

**Comment by silverwind** [comment]
Resolve all fixed comments please so we have a overview.

**Comment by kdumontnu** [comment]
> Resolve all fixed comments please so we have a overview.

OP is out until Tuesday, so jtran and I are not able to resolve comments or edit the PR description.

In short, @jtran has addressed all of the outstanding TODO items & feedback comments except @delvh questions about checkboxes, which we can push.
> ## TODO
> * [x]  Alphabetize scope categories
> * [x]  Change 'public repos only' to a radio button (private vs public). Also expand this to organizations
>   
>   * [ ]  If public selected, which read categories should we select by default?

Currently, read scope must be selected to GET public repo routes with a token. It seems the most consistent with other behavior. However, we can also check "read" by default when "Public" is selected.

> * [x]  Disable token creation if no scopes selected. Alternatively, show warning
> * [ ]  `reqToken()` is missing from many `POST/DELETE` routes in the api. `tokenRequiresScopes()` only checks that a given token has the correct scope,  `reqToken()` must be used to check that a token (or some other auth) is present.
>   
>   * _This should be addressed in this PR_

This does not seem to be a regression from this PR, thus shouldn't block it. 

> * [x]  The migration should be reviewed very carefully in order to minimize access changes to existing user tokens.
>   
>   * _This should be addressed in this PR_
> * [ ]  Link to api to swagger documentation, clarify what read/write/delete levels correspond to

WIP

> * [x]  Add tests to check that scope omission results in a 4xx response
>   
>   * _This should be addressed in this PR_
> * [ ]  Review cases where more than one scope is needed as this directly deviates from the api definition.
>   
>   * _This should be addressed in this PR_
>   * For example:
>   
>   ```go
>    m.Group("/users/{username}/orgs", func() {
>    	m.Get("", reqToken(), org.ListUserOrgs)
>    	m.Get("/{org}/permissions", reqToken(), org.GetUserOrgsPermissions)
>    }, tokenRequiresScopes(auth_model.AccessTokenScopeCategoryUser, auth_model.AccessTokenScopeCategoryOrganization), context_service.UserAssignmentAPI())
>   ```


## Proposed blocking items:
- [ ] Update [Gitea documentation](https://docs.gitea.com/development/oauth2-provider) (I'll do this)
- [ ] Add some notes and a link to documentation in scopes (WIP)
- [ ] I'm not thrilled that the issues route exists in the API, but not token scopes. This is presumably because in `api.go` the issues route is nested under repos. However, it creates a US discrepancy between API & scoped tokens.

**Comment by jtran** [comment]
To clarify this:

> I'm not thrilled that the issues route exists in the API, but not token scopes. This is presumably because in `api.go` the issues route is nested under repos. However, it creates a US discrepancy between API & scoped tokens.

The code doesn't use the issues scope anywhere.  You need the repository scope to access issues.  "Issues" was removed from the create token UI to prevent confusion until that's changed.

**Comment by silverwind** [comment]
> In short, @jtran has addressed all of the outstanding TODO items & feedback comments except @delvh questions about checkboxes, which we can push.

Okay, I've marked all except that checkbox topic as resolved.

**Comment by kdumontnu** [comment]
> To clarify this:
> 
> > I'm not thrilled that the issues route exists in the API, but not token scopes. This is presumably because in `api.go` the issues route is nested under repos. However, it creates a US discrepancy between API & scoped tokens.
> 
> The code doesn't use the issues scope anywhere. You need the repository scope to access issues. "Issues" was removed from the create token UI to prevent confusion until that's changed.

👍 I split `issues` up into its own route and reenabled it in the UI

**Comment by kdumontnu** [comment]
PR should be all set now. Going forward, I think we should update the swagger documentation to include the required token scopes for each route and label those basic auth only (like the user/token routes). Adding explicit documentation there would be helpful. 

There's an option to add security + scopes in swagger, but they aren't rendered in the UI. I dug into making  a plugin for swagger UI, (and there is an [example here](https://github.com/swagger-api/swagger-ui/issues/5062#issuecomment-747972244)), but I think someone more familiar with React/swagger would need to take that on.

**Comment by silverwind** [comment]
> PR should be all set now. Going forward, I think we should update the swagger documentation to include the required token scopes for each route and label those basic auth only (like the user/token routes). Adding explicit documentation there would be helpful.

One can put `security` onto each route, does that help?

https://swagger.io/docs/specification/2-0/authentication/

image

**Comment by kdumontnu** [comment]
> > PR should be all set now. Going forward, I think we should update the swagger documentation to include the required token scopes for each route and label those basic auth only (like the user/token routes). Adding explicit documentation there would be helpful.
> 
> One can put `security` onto each route, does that help?
> 
> https://swagger.io/docs/specification/2-0/authentication/
> 
> image

Yeah, that's something I'd like to follow up on later. Unfortunately, the UI doesn't seem to render it anywhere.

**Comment by silverwind** [comment]
If it's in the produced spec file, it should be good enough initially.

File: options/locale/locale_en-US.ini [hunk 19]
```diff
@@ -803,8 +802,13 @@ access_token_deletion_cancel_action = Cancel
 access_token_deletion_confirm_action = Delete
 access_token_deletion_desc = Deleting a token will revoke access to your account for applications using it. This cannot be undone. Continue?
 delete_token_success = The token has been deleted. Applications using it no longer have access to your account.
-select_scopes = Select scopes
-scopes_list = Scopes:
+repo_and_org_access = Repository and Organization Access
+permissions_public_only = Public only
+permissions_access_all = All (public, private, and limited)
+select_permissions = Select permissions
+scoped_token_desc = Selected token scopes limit authentication only to the corresponding <a href="/api/swagger" target="_blank">API</a> routes. See <a href="https://docs.gitea.com/development/oauth2-provider#scopes" target="_blank">documentation</a> for more information.
```
Comment (silverwind) [inline options/locale/locale_en-US.ini]: Move the `<a>` attributes out of translation please. You can use something like this:

```ini
scoped_token_desc = Selected token scopes limit authentication only to the corresponding <a %s>API</a> routes. See <a %s>documentation</a> for more information.
```

```handlebars
{{$.locale.Tr "setting.scoped_token_desc" (printf `href="/api/swagger" target="_blank"`) (printf `ref="https://docs.gitea.com/development/oauth2-provider#scopes" target="_blank"`) | Str2html}}
```

File: docs/content/doc/development/oauth2-provider.en-us.md [hunk 20]
```diff
@@ -44,42 +44,53 @@ To use the Authorization Code Grant as a third party application it is required
...
+| &nbsp;&nbsp;&nbsp; **write:misc** | Grants read/write access to miscellaneous operations, such as markup utility operations. |
+| &nbsp;&nbsp;&nbsp; **delete:misc** | Grants read/write/delete access to miscellaneous operations. Currently the same as `write:misc`. |
+| **notification** | `notification/*` API routes: user notification operations. |
+| &nbsp;&nbsp;&nbsp; **read:notification** | Grants read access to user notifications, such as which notifications users are subscribed to and read new notifications. |
+| &nbsp;&nbsp;&nbsp; **write:notification** | Grants read/write access to user notifications, such as marking notifications as read. |
+| &nbsp;&nbsp;&nbsp; **delete:notification** | Grants read/write/delete access to user notifications. Currently the same as `write:notification`. |
+| **organization** | `orgs/*` and `teams/*` API routes: Organization and team managment operations. |
+| &nbsp;&nbsp;&nbsp; **read:organization** | Grants read access to org and team status, such as listing all orgs a user has visibility to, teams, and team memebers. |
```
Comment (delvh) [inline docs/content/doc/development/oauth2-provider.en-us.md]:
```suggestion
| **organization** | `orgs/*` and `teams/*` API routes: Organization and team management operations. |
| &nbsp;&nbsp;&nbsp; **read:organization** | Grants read access to org and team status, such as listing all orgs a user has visibility to, teams, and team members. |
```

File: docs/content/doc/development/oauth2-provider.en-us.md [hunk 21]
```diff
@@ -44,42 +44,53 @@ To use the Authorization Code Grant as a third party application it is required
...
+| &nbsp;&nbsp;&nbsp; **write:organization** | Grants read/write access to org and team status, such as creating and updating teams and updating org settings. |
+| &nbsp;&nbsp;&nbsp; **delete:organization** | Grants read/write/delete access to org and team status, such as deleting teams and orgs. |
+| **package** | `/packages/*` API routes: Packages operations |
+| &nbsp;&nbsp;&nbsp; **read:package** | Grants read access to package operations, such as reading and downloading available packages. |
+| &nbsp;&nbsp;&nbsp; **write:package** | Grants read/write access to package operations. Currently the same as `read:package`. |
+| &nbsp;&nbsp;&nbsp; **delete:package** | Grants read/write/delete access to package operations, such as deleting packages. |
+| **repository** | `/repos/*` API routes except `/repos/issues/*`: Repository file, pull-request, and release operations. |
```
Comment (delvh) [inline docs/content/doc/development/oauth2-provider.en-us.md]: I have a slight feeling that this is precisely the category we should split up into distinct categories as those are again **completely** different subcategories - typically, you either want the whole package, or you only want to interact with 2-3 parts of the API, i.e. pulling all issues and PRs, perhaps writing back to them or creating a new release.
At best, you don't want to touch file states or even releases.

File: web_src/js/components/ScopedAccessTokenSelector.vue [hunk 22]
```diff
@@ -0,0 +1,158 @@
...
+    <div class="field gt-pl-2">
+      <label class="checkbox-label">
+        <input
+          ref="category"
+          v-model="categorySelected"
+          class="scope-checkbox scoped-access-token-input"
+          type="checkbox"
+          name="scope"
+          :value="'delete:' + category"
+          @change="onCategoryInput"
```
Comment (delvh) [inline web_src/js/components/ScopedAccessTokenSelector.vue]: Hmm… Interesting.
I just tested it, and surprisingly it works with <kbd>Space</kbd>.
However, it doesn't work if you set it manually from the console.
As I've had to learn myself, it is probably better to use
```suggestion
          @input="onCategoryInput"
```

File: web_src/js/components/ScopedAccessTokenSelector.vue [hunk 23]
```diff
@@ -0,0 +1,158 @@
...
+        <label class="checkbox-label">
+          <input
+            ref="read"
+            v-model="readSelected"
+            :disabled="categorySelected || writeSelected"
+            class="scope-checkbox scoped-access-token-input"
+            type="checkbox"
+            name="scope"
+            :value="'read:' + category"
+            @change="onIndividualInput"
```
Comment (delvh) [inline web_src/js/components/ScopedAccessTokenSelector.vue]:
```suggestion
            @input="onIndividualInput"
```

File: web_src/js/components/ScopedAccessTokenSelector.vue [hunk 24]
```diff
@@ -0,0 +1,158 @@
...
+        <label class="checkbox-label">
+          <input
+            ref="write"
+            v-model="writeSelected"
+            :disabled="categorySelected"
+            class="scope-checkbox scoped-access-token-input"
+            type="checkbox"
+            name="scope"
+            :value="'write:' + category"
+            @change="onIndividualInput"
```
Comment (delvh) [inline web_src/js/components/ScopedAccessTokenSelector.vue]:
```suggestion
            @input="onIndividualInput"
```

File: web_src/js/components/ScopedAccessTokenSelector.vue [hunk 25]
```diff
@@ -0,0 +1,158 @@
...
+        <label class="checkbox-label">
+          <input
+            ref="delete"
+            v-model="deleteSelected"
+            :disabled="categorySelected"
+            class="scope-checkbox scoped-access-token-input"
+            type="checkbox"
+            name="scope"
+            :value="'delete:' + category"
+            @change="onIndividualInput"
```
Comment (delvh) [inline web_src/js/components/ScopedAccessTokenSelector.vue]:
```suggestion
            @input="onIndividualInput"
```

File: routers/api/v1/api.go [hunk 26]
```diff
@@ -236,44 +236,87 @@ func reqPackageAccess(accessMode perm.AccessMode) func(ctx *context.APIContext)
...
+func tokenRequiresScopes(requiredScopeCategories ...auth_model.AccessTokenScopeCategory) func(ctx *context.APIContext) {
+	return func(ctx *context.APIContext) {
+		// no scope required
+		if len(requiredScopeCategories) == 0 {
+			return
+		}
+
+		// Need OAuth2 token to be present.
+		scope, scopeExists := ctx.Data["ApiTokenScope"].(auth_model.AccessTokenScope)
+		if ctx.Data["IsApiToken"] != true || !scopeExists {
```
Comment (delvh) [inline routers/api/v1/api.go:250]: I still agree with @wxiaoguang that we should not query the token like that, but in order to get the PR merged, I'll allow it for now.

Comment (wxiaoguang) [reply routers/api/v1/api.go:250]: Agree, no block from my side. Since the code is covered by tests, it could be refactored later, to make this PR more focused.

**Comment by jackHay22** [comment]
> There are TODO's left for `reqToken()`. I'll have to check with @jackHay22 on this, because I just don't understand the purpose of that function. My understanding is that this isn't something we're regressing on or introducing this this PR, but rather something we wanted to address while we're here - I'll have to confirm. If anyone else has experience with this please feel free to chip in.

Basically, we need to review the places where `reqToken()` is used or missing. This is the function that verifies that a token is actually present (the required scopes are checked separately). For example, the top level `user` group below checks that any tokens have the `user` scope, but we need to use `reqToken` to confirm that a scoped token is actually present (or some other form of token auth). 
```go
m.Group("/user", func() {
        ...
	m.Combo("/emails").
		Get(user.ListEmails). // Note: this route won't require a token
		Post(bind(api.CreateEmailOption{}), user.AddEmail). // TODO reqToken?
		Delete(bind(api.DeleteEmailOption{}), user.DeleteEmail) // TODO reqToken?
```
I don't think I am familiar enough with the API permissions to decide whether `reqToken()` is needed on a per-route basis but it seems as though all requests other than `GET` should use `reqToken()` (with the exception of some public routes).

**Review by yardenshoham — COMMENTED** [review]
I think you need to add the migration in `models/migrates/migrations.go`

**Comment by kdumontnu** [comment]
@sapk since I saw you recently forked the http-swagger repo, maybe you're interested in this? 😉 😄 https://github.com/go-gitea/gitea/pull/24767#issuecomment-1567452600

**Comment by jackHay22** [comment]
Okay, I think this PR is in good shape. We've identified a few follow-on features that we'd like to include in the future (unless people feel strongly about them being included in this PR).

- Rename and rework `reqToken()`
  - Ideally tokens would be opt-out rather than opt-in. Routes should be marked as _not_ needing token authentication rather than vice-versa
- Add scopes to swagger auth documentation
  - Could this be automated in some way
- Further subdivide certain categories
  - Ex. repository scopes

**Review by kdumontnu — APPROVED** [review]
👍

**Review by yardenshoham — COMMENTED** [review]
Please don't update by rebase. Update by merge once review starts

File: public/serviceworker.js [hunk 27]
```diff
@@ -0,0 +1,6 @@
+/******/ (function() { // webpackBootstrap
+/******/ 	"use strict";
+/******/ 	
+/******/ 	
+/******/ })()
+;
```
Comment (delvh) [inline public/serviceworker.js]: ?

File: models/migrations/v1_20/v259_test.go [hunk 28]
```diff
@@ -0,0 +1,110 @@
...
+			createNewTokenScope(newScope...),
+		})
+	}
+
+	x, deferable := base.PrepareTestEnv(t, 0, new(AccessToken))
+	if x == nil || t.Failed() {
+		defer deferable()
+		return
+	}
+	defer deferable()
```
Comment (delvh) [inline models/migrations/v1_20/v259_test.go]:
```suggestion
	defer deferable()
	if x == nil || t.Failed() {
		return
	}
```

Comment (delvh) [reply models/migrations/v1_20/v259_test.go]: Additionally, shouldn't that be 
```suggestion
	defer deferable()
	if x == nil || t.Failed() {
		t.Skip()
		return
	}
```
instead?

File: options/locale/locale_en-US.ini [hunk 29]
```diff
@@ -807,8 +806,13 @@ access_token_deletion_cancel_action = Cancel
 access_token_deletion_confirm_action = Delete
 access_token_deletion_desc = Deleting a token will revoke access to your account for applications using it. This cannot be undone. Continue?
 delete_token_success = The token has been deleted. Applications using it no longer have access to your account.
-select_scopes = Select scopes
-scopes_list = Scopes:
+repo_and_org_access = Repository and Organization Access
+permissions_public_only = Public only
+permissions_access_all = All (public, private, and limited)
+select_permissions = Select permissions
+scoped_token_desc = Selected token scopes limit authentication only to the corresponding <a %s>API</a> routes. See <a %s>documentation</a> for more information.
```
Comment (delvh) [inline options/locale/locale_en-US.ini]:
```suggestion
scoped_token_desc = Selected token scopes limit authentication only to the corresponding <a %s>API</a> routes. Read the <a %s>documentation</a> for more information.
```

File: public/serviceworker.js (hunk 27 above)
Comment (silverwind) [reply public/serviceworker.js]: The file was removed from gitignore, so they may have had a old build artifact from it.

**Review by delvh — APPROVED** [review]
I think we can remove the `breaking` label, right?

According to my tests, everything seems to work as intended :tada:

File: docs/content/doc/development/oauth2-provider.en-us.md [hunk 30]
```diff
@@ -44,42 +44,53 @@ To use the Authorization Code Grant as a third party application it is required
...
-| &nbsp;&nbsp;&nbsp; **read:package** | Grants read access to packages |
-| &nbsp;&nbsp;&nbsp; **delete:package** | Grants delete access to packages |
-| **admin:gpg_key** | Grants full access for managing GPG keys |
-| &nbsp;&nbsp;&nbsp; **write:gpg_key** | Grants read/write access to GPG keys |
-| &nbsp;&nbsp;&nbsp; **read:gpg_key** | Grants read-only access to GPG keys |
-| **admin:application** | Grants full access to manage applications |
-| &nbsp;&nbsp;&nbsp; **write:application** | Grants read/write access for managing applications |
-| &nbsp;&nbsp;&nbsp; **read:application** | Grants read access for managing applications |
-| **sudo** | Allows to perform actions as the site admin. |
+| **(no scope)** | Not supported. A scope is required even for public repositories. |
```
Comment (lunny) [inline docs/content/doc/development/oauth2-provider.en-us.md]: Wow, this is a big break for old Gitea instances?

Comment (delvh) [reply docs/content/doc/development/oauth2-provider.en-us.md]: No, all unscoped tokens were already converted to tokens with scope `all` in the original scoped tokens PR #20908.
Have a look at `models/migrations/v1_19/v239.go`:
https://github.com/go-gitea/gitea/blob/c5ede35124c8d5280219c24049bb0ad7da9f02ed/models/migrations/v1_19/v239.go#L10-L22

**Comment by lunny** [comment]
@harryzcy could you help to review this PR?

File: web_src/js/components/ScopedAccessTokenSelector.vue [hunk 31]
```diff
@@ -0,0 +1,158 @@
...
+          >
+          delete:{{ category }}
+        </label>
+      </div>
+    </div>
+  </div>
+</template>
+
+<script>
+
```
Comment (silverwind) [inline web_src/js/components/ScopedAccessTokenSelector.vue]:
```suggestion
```

File: web_src/js/components/ScopedAccessTokenSelector.vue [hunk 32]
```diff
@@ -0,0 +1,157 @@
...
+    deleteSelected: false,
+  }),
+
+  methods: {
+    /**
+     * When entire category is toggled
+     * @param {Event} event
+     */
+    onCategoryInput(event) {
+      event.preventDefault();
```
Comment (silverwind) [inline web_src/js/components/ScopedAccessTokenSelector.vue]:
```suggestion
    onCategoryInput(e) {
      e.preventDefault();
```

File: web_src/js/components/ScopedAccessTokenSelector.vue [hunk 33]
```diff
@@ -0,0 +1,157 @@
...
+      this.writeSelected = this.$refs.category.checked;
+      this.readSelected = this.$refs.category.checked;
+    },
+
+    /**
+     * When an individual level of category is toggled
+     * @param {Event} event
+     */
+    onIndividualInput(event) {
+      event.preventDefault();
```
Comment (silverwind) [inline web_src/js/components/ScopedAccessTokenSelector.vue]:
```suggestion
    onIndividualInput(e) {
      e.preventDefault();
```

File: models/auth/token_scope.go [hunk 34]
```diff
@@ -269,7 +382,7 @@ func (bitmap AccessTokenScopeBitmap) ToScope() AccessTokenScope {
 	scope := AccessTokenScope(strings.Join(scopes, ","))
 	scope = AccessTokenScope(strings.ReplaceAll(
 		string(scope),
-		"repo,admin:org,admin:public_key,admin:org_hook,admin:user_hook,notification,user,delete_repo,package,admin:gpg_key,admin:application",
+		"delete:activitypub,delete:admin,delete:misc,delete:notification,delete:organization,delete:package,delete:issue,delete:repository,delete:user",
```
Comment (wxiaoguang) [inline models/auth/token_scope.go]: `strings.ReplaceAll(scope, "every is delete", "all")` :

Why "delete" scope means "all"? I guess there is an assumption that "delete" also means "write"+"read", but it is not  a strong assumption.

File: models/migrations/v1_20/v259.go [hunk 35]
```diff
@@ -0,0 +1,387 @@
...
+			scopes = append(scopes, string(singleScope))
+		}
+	}
+
+	scope := AccessTokenScope(strings.Join(scopes, ","))
+	scope = AccessTokenScope(strings.ReplaceAll(
+		string(scope),
+		"delete:activitypub,delete:admin,delete:misc,delete:notification,delete:organization,delete:package,delete:issue,delete:repository,delete:user",
+		"all",
+	))
```
Comment (wxiaoguang) [inline models/migrations/v1_20/v259.go:183]: Could the `accessTokenScopeBitmap` be put in the `modules` package (instead of the `models` package) ?

Then the code could be shared by this migration package, no need to duplicate.

File: models/migrations/v1_20/v259.go [hunk 36]
```diff
@@ -0,0 +1,387 @@
...
+	OldAccessTokenScopeAdminOrg:         {AccessTokenScopeDeleteOrganization},
+	OldAccessTokenScopeWriteOrg:         {AccessTokenScopeWriteOrganization},
+	OldAccessTokenScopeReadOrg:          {AccessTokenScopeReadOrganization},
+	OldAccessTokenScopeAdminPublicKey:   {AccessTokenScopeDeleteUser},
+	OldAccessTokenScopeWritePublicKey:   {AccessTokenScopeWriteUser},
+	OldAccessTokenScopeReadPublicKey:    {AccessTokenScopeReadUser},
+	OldAccessTokenScopeAdminRepoHook:    {AccessTokenScopeDeleteRepository},
+	OldAccessTokenScopeWriteRepoHook:    {AccessTokenScopeWriteRepository},
+	OldAccessTokenScopeReadRepoHook:     {AccessTokenScopeReadRepository},
+	OldAccessTokenScopeAdminOrgHook:     {AccessTokenScopeWriteOrganization},
```
Comment (wxiaoguang) [inline models/migrations/v1_20/v259.go:297]: Above: `OldAccessTokenScopeAdminRepoHook:    {AccessTokenScopeDeleteRepository}`: old admin -> new delete

Here: `OldAccessTokenScopeAdminOrgHook:     {AccessTokenScopeWriteOrganization},`: old admin -> new write ?


----

I still think the new "delete" is not a right scope name.

File: docs/content/doc/development/oauth2-provider.en-us.md [hunk 37]
```diff
@@ -44,42 +44,53 @@ To use the Authorization Code Grant as a third party application it is required
 
 ## Scopes
 
-Gitea supports the following scopes for tokens:
+Gitea supports scoped access tokens, which allow users the ability to restrict tokens to operate only on selected url routes. Scopes are grouped by high-level API routes, and further refined to the following:
+
+- `read`: `GET` routes
+- `write`: `POST`, `PUT`, and `PATCH` routes (in addition to `GET`)
+- `delete`: `DELETE` routes (in addition to `POST`, `PUT`, `PATCH` and `GET`)
```
Comment (wxiaoguang) [inline docs/content/doc/development/oauth2-provider.en-us.md]: I guess something like "full" or "manage" is a better name than "delete".

----

For example: IMO "transfer a repo" is "full manage", but not "write" or "delete".

File: docs/content/doc/development/oauth2-provider.en-us.md [hunk 38]
```diff
@@ -44,42 +44,53 @@ To use the Authorization Code Grant as a third party application it is required
...
+
+Gitea token scopes are as follows:
```
Comment (wxiaoguang) [inline docs/content/doc/development/oauth2-provider.en-us.md:52]: The "public only" is not mentioned here but appears in code, I still have difficulty to understand what is "public only" or what it affects .....

File: routers/api/v1/api.go [hunk 39]
```diff
@@ -713,37 +756,43 @@ func Routes(ctx gocontext.Context) *web.Route {
...
-			m.Get("/api", settings.GetGeneralAPISettings)
-			m.Get("/attachment", settings.GetGeneralAttachmentSettings)
-			m.Get("/repository", settings.GetGeneralRepoSettings)
-		})
 
-		// Notifications (requires 'notification' scope)
+		// Misc (requires 'misc' scope)
+		m.Group("", func() {
+			m.Get("/version", misc.Version)
+			m.Get("/signing-key.gpg", misc.SigningKey)
```
Comment (wxiaoguang) [inline routers/api/v1/api.go:763]: The comment "Misc (requires 'misc' scope)" doesn't seem right.

If I understand correctly, `/version` could always be accessed without a token (it doesn't really require the misc scope token).

But .... if it is accessed by a token without "misc" scope, then it becomes inaccessible? It really looks strange.

File: routers/api/v1/api.go [hunk 40]
```diff
@@ -781,59 +830,61 @@ func Routes(ctx gocontext.Context) *web.Route {
...
 
 			m.Get("/followers", user.ListMyFollowers)
 			m.Group("/following", func() {
 				m.Get("", user.ListMyFollowing)
 				m.Group("/{username}", func() {
 					m.Get("", user.CheckMyFollowing)
-					m.Put("", reqToken(auth_model.AccessTokenScopeUserFollow), user.Follow)      // requires 'user:follow' scope
-					m.Delete("", reqToken(auth_model.AccessTokenScopeUserFollow), user.Unfollow) // requires 'user:follow' scope
+					m.Put("", user.Follow)
+					m.Delete("", user.Unfollow)
```
Comment (wxiaoguang) [inline routers/api/v1/api.go:851]: I guess this "DELETE" operation should be treated as "write" permission as "user.Follow"?

**Review by wxiaoguang — COMMENTED** [review]
Assuming "DELETE" is a separate "delete" scope doesn't look good to me.

In some cases, the "DELETE" method should be treated as "write" scope permission IMO.

**Comment by delvh** [comment]
I don't understand your problem with the `DELETE` scope.
This PR is specifically based on the following assumption:
`delete implies write implies read` which you can immediately understand from the UI to select scopes.
I think it is even documented that these implications exist.
Please, try out this branch and then tell me if you still have questions about this scope.

**Comment by wxiaoguang** [comment]
> I don't understand your problem with the `DELETE` scope.
> This PR is specifically based on the following assumption:
> `delete implies write implies read` which you can immediately understand from the UI to select scopes.
> I think it is even documented that these implications exist.
> Please, try out this branch and then tell me if you still have questions about this scope.

My opinion is that the assumption is not good enough. Because many route handlers were not strictly designed with HTTP methods. And "delete" itself doesn't seem to be a meaningful scope in daily usage.


----

> - `write`: `POST`, `PUT`, and `PATCH` routes (in addition to `GET`)
> - `delete`: `DELETE` routes (in addition to `POST`, `PUT`, `PATCH` and `GET`)

I do not think this assumption could work well for all cases.

1. Some POST/PATCH could also be destructive (eg: transfer repo, or clean some data)
2. Some DELETE is not destructive (eg: the "unfollow" example above)

Using "delete" scope for "DELETE" method would cause misunderstanding and abuses.

The "scope" could be designed with a more general approach: "read" for read-only, "write" for change its content, "full/manage" for management (including destructive) operations.

**Comment by delvh** [comment]
> The "scope" could be designed with a more general approach: "read" for read-only, "write" for change its content, "full/manage" for management (including destructive) operations.
ps: well known cloud service providers like AWS, they also use "Read/Write/Full" for their permission management, it has been proven that such design is good for daily usage.

Yes, that's how it works already.
I don't care if call it `Full` or `Delete` as it still does the same thing.
But we can probably rename it to `Full` to prevent confusion.

**Comment by wxiaoguang** [comment]
IMO it's not as simple as "renaming it".

I think it needs to clarify how to handle these 2 cases above 

> 1. Some POST/PATCH could also be destructive (eg: transfer repo, or clean some data)
> 2. Some DELETE is not destructive (eg: the "unfollow" example above)

If there is no clear solution, there would be 3rd "breaking" "redesign" PR for the token scope system.

**Comment by jackHay22** [comment]
> IMO it's not as simple as "renaming it".
> 
> I think it needs to clarify how to handle these 2 cases above
> 
> > 1. Some POST/PATCH could also be destructive (eg: transfer repo, or clean some data)
> > 2. Some DELETE is not destructive (eg: the "unfollow" example above)
> 
> If there is no clear solution, there would be 3rd "breaking" "redesign" PR for the token scope system.

This is a good point. It seems like we need a way of disambiguating `write` with `delete`. 

This PR attempts to simplify the assignment of scopes to routes by mapping scope levels to HTTP methods and scope categories to route groups. I see this as being a more maintainable approach than an individual scope to route assignment. However, this has an obvious drawback; HTTP methods may not accurately reflect the actual operation of a route (as described above). 

I propose that we remove `delete` altogether. In most cases, I think that write access implies the ability to delete. I think that the distinction between `read` and `write` is far more useful than `write` versus `delete`. 

I think our best approach with this PR is to create a minimal set of scopes (it will almost certainly be easier to add new scopes than to remove them). In the future, more granular scopes can be made by dividing up the existing scopes (which will be much easier to migrate). I think this will give the user more meaningful control over API access than distinguishing between write and delete. If there is a case where `write` access is seen as being too permissive, it is probably better to introduce a new category rather than a new access level.

File: tests/integration/api_token_test.go [hunk 41]
```diff
@@ -4,24 +4,537 @@
...
+
+// runTestCase Helper function to run a single test case.
+func runTestCase(t *testing.T, testCase *requiredScopeTestCase, user *user_model.User) {
+	t.Run(testCase.Name(), func(t *testing.T) {
+		defer tests.PrintCurrentTest(t)()
+
+		// Create a token with all scopes NOT required by the endpoint.
+		var unauthorizedScopes []auth_model.AccessTokenScope
+		for _, category := range auth_model.AllAccessTokenScopeCategories {
+			// For permissions, Delete > Write > Read > NoAccess.  So we need to
```
Comment (jtran) [inline tests/integration/api_token_test.go]: Can you update this comment also?  Thanks.

**Review by delvh — APPROVED** [review]

**Review by kdumontnu — APPROVED** [review]
👍

File: routers/api/v1/api.go (hunk 39 above)
Comment (richmahn) [reply routers/api/v1/api.go:763]: Yes, this needs to be addressed.

Comment (richmahn) [reply routers/api/v1/api.go:763]: https://github.com/go-gitea/gitea/issues/26035
