### PR TITLE
Fix various legacy problems

### LINKED ISSUE #35800: Markdown rendering broken when markup starts with horizontal line
### Description

When you start issue/comment text from the horizontal line (`---`), the markdown render partially fails. Especially this affects lists of linked issues/PRs. Bug demonstrated at: https://demo.gitea.com/didim99/test/issues/3

To render correctly you need to add at least one blank line to the start of the text.

Not works:
```md
------

Related:
* #1

This not works
```

Works:
```md

------

Related:
* #1

This works
```

### Gitea Version

1.26.0+dev-91-g39c08ce4c1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Image

Image

### Git Version

Not matters

### Operating System

Not matters

### How are you running Gitea?

Using demo.gitea.com

### Database

None

### LINKED ISSUE #35866: Cannot find description of the format of the project description text
### Description

While the format of the PR comments is documented I cannot find documentation of the format of project description text. Using same formatting as PR comments does not work. eg. images are not displayed.

### Gitea Version

1.24.6

### Can you reproduce the bug on the Gitea demo site?

[Yes](https://demo.gitea.com/hramrach/testrepo)

### Log Gist

_No response_

### Screenshots

GFM example
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/25423296/163456776-7f95b81a-f1ed-45f7-b7ab-8fa810d529fa.png">
  <source media="(prefers-color-scheme: light)" srcset="https://user-images.githubusercontent.com/25423296/163456779-a8556205-d0a5-45e2-ac17-42d089e3c3f8.png">
  Shows an illustrated sun in light mode and a moon with stars in dark mode.
</picture>

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

It's some distro service, no idea. 

### Database

None

### LINKED ISSUE #36243: Cannot create release from tag page
### Description

1. Create a tag (e.g. `v1`)
2. Open tag page (Releases -> N tags -> v1)
3. Click `New release`
4. Fill out fields and click Save Draft or Publish release

Expected result: release should be published or saved as draft
Actual result: error: `Target branch does not exist.`

But if you're open just new release (from releases page, not tags) and fill `v1` as tag name manually all works fine.

### Gitea Version

1.25.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Image

### Git Version

2.27.0

### Operating System

_No response_

### How are you running Gitea?

Selfhosted. Binary from official builds.

### Database

MySQL/MariaDB

### LINKED ISSUE #36439: Users logs in as existing organization
### Description

I have a user that every time he logs in to gitea he is not "himself" but an organization he created. Attached you find some screenshots. Login provider is OIDC with EntraID (MS Azure). 

Please advice me on what more information I can provide you to drill down on this!

### Gitea Version

1.25.4

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

Image
Image

### Git Version

_No response_

### Operating System

RHEL 9

### How are you running Gitea?

Docker deployed with ansible

### Database

PostgreSQL

### LINKED ISSUE #37089: Repository migration/mirroring hangs due to unoptimized milestone SQL query (Missing Parentheses)
### Description

When mirroring or migrating a repository in a Gitea instance with many repositories (1000+ repos, and each has plenty of metadata), the Gitea UI frequently times out after several minutes with a Failed to fetch error. The background worker eventually completes the migration after a very very long time, but the frontend connection is lost. If you keep watching the migration status, it shows as stuck on "Migrating Topics".

After digging into the PostgreSQL and Gitea logs, I discovered this is caused by a potentially malformed SQL query triggered during the final Finish() cleanup phase of the migration.

XORM is generating a query with missing parentheses around an OR condition. Because AND takes precedence over OR in SQL, the repo_id filter is only applied to half of the query. This forces PostgreSQL to perform a massive, instance-wide nested loop scan across all milestones and issues on the server, rather than isolating the query to the single repository being migrated.

The Buggy SQL Query Captured from the Gitea logs (modules/migrations/gitea_uploader.go:973:(*GiteaLocalUploader).Finish()):

```sql
SELECT "milestone".id 
FROM "milestone" 
WHERE "milestone".num_closed_issues!=(SELECT COUNT(*) FROM "issue" WHERE "issue".milestone_id="milestone".id AND "issue".is_closed=$1) 
OR "milestone".num_issues!=(SELECT COUNT(*) FROM "issue" WHERE "issue".milestone_id="milestone".id) 
AND "milestone".repo_id = $2
```
Because there are no parentheses wrapping the OR statements, the database interprets the logic as:
`WHERE Condition A OR (Condition B AND repo_id = $2)`
Instead of the intended:
`WHERE (Condition A OR Condition B) AND repo_id = $2`

**Proof of Concept & Workaround (Database Proxy)**
To prove this missing syntax was the sole cause of the UI timeouts and extremely long mirror time, I first tested the query directly in the PG database. Without fix, it took 6500 seconds to finish. With the fix (adding parentheses), the query took 0.015 seconds.

I then deployed a Gallium Data database proxy between Gitea and PostgreSQL.

I used a real-time intercept rule that caught this exact wire packet and injected the missing parentheses before passing it to PostgreSQL:

```javascript
let sql = context.packet.query;

const badQuery = 'SELECT "milestone".id FROM "milestone" WHERE "milestone".num_closed_issues!=(SELECT COUNT(*) FROM "issue" WHERE "issue".milestone_id="milestone".id AND "issue".is_closed=$1) OR "milestone".num_issues!=(SELECT COUNT(*) FROM "issue" WHERE "issue".milestone_id="milestone".id) AND "milestone".repo_id = $2';

const fixedQuery = 'SELECT "milestone".id FROM "milestone" WHERE ("milestone".num_closed_issues!=(SELECT COUNT(*) FROM "issue" WHERE "issue".milestone_id="milestone".id AND "issue".is_closed=$1) OR "milestone".num_issues!=(SELECT COUNT(*) FROM "issue" WHERE "issue".milestone_id="milestone".id)) AND "milestone".repo_id = $2';

if (sql === badQuery) {
    context.packet.query = fixedQuery;
    log.info("--- GITEA BUG INTERCEPTED AND FIXED IN REAL TIME ---");
}
```
And with this my mirroring process now is an instant for a small repo, which used to take me hours before I introduced this proxy.

**Proposed Fix**
The ORM builder constructing this specific milestone cleanup query needs to explicitly wrap the OR conditions in a parenthesis builder block before appending the AND repo_id = ? condition.

### Gitea Version

1.25.5

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.43.0

### Operating System

Ubuntu 24.04, Docker 28.5.2

### How are you running Gitea?

Official docker image

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by wxiaoguang**
1.  Fix #36439
    * Since nobody cares #36208
2. Fix #37089
3. Fix incorrect layout of admin auth oidc page
4. Fix #35866
    * add picture srcset support
5. Fix #35800
6. Fix #36243

### CODE REVIEW

File: routers/web/auth/auth.go [hunk 1]
```diff
@@ -633,16 +633,15 @@ func createUserInContext(ctx *context.Context, tpl templates.TplName, form any,
 			case setting.OAuth2AccountLinkingAuto:
 				var user *user_model.User
 				user = &user_model.User{Name: u.Name}
-				hasUser, err := user_model.GetUser(ctx, user)
+				hasUser, err := user_model.GetIndividualUser(ctx, user)
 				if !hasUser || err != nil {
 					user = &user_model.User{Email: u.Email}
-					hasUser, err = user_model.GetUser(ctx, user)
+					hasUser, err = user_model.GetIndividualUser(ctx, user)
```
Comment (lunny) [inline routers/web/auth/auth.go:639]: It seems we need to confirm the `u.Email` is not empty. `GetIndividualUser` is still dangerous if every field is empty.

Comment (wxiaoguang) [reply routers/web/auth/auth.go:639]: Not in this PR's scope. All callers need to be refactored in the future.

**Comment by wxiaoguang** [comment]
UI fix

Old:

<details>

image

</details>

New:

<details>

image

</details>

**Review by lunny — APPROVED** [review]

**Review by bircni — APPROVED** [review]

File: modules/markup/markdown/markdown_test.go [hunk 2]
```diff
@@ -471,14 +471,26 @@ foo: bar
 </details><ul>
 <li class="task-list-item"><input type="checkbox" disabled="" data-source-position="19"/>task 1</li>
 </ul>
+`,
+		},
+		// we have our own frontmatter parser, don't need to use github.com/yuin/goldmark-meta
```
Comment (bircni) [inline modules/markup/markdown/markdown_test.go:479]: Is that comment really necessary?

Comment (wxiaoguang) [reply modules/markup/markdown/markdown_test.go:479]: Just good to have, in case someone would introduce "github.com/yuin/goldmark-meta" again in the future.

**Comment by wxiaoguang** [comment]
All done, large enough (why so many bugs .... 🤣 )

New changes all either have tests or enough comments. And I have manually tested

**Comment by bircni** [comment]
Good to go!
