### PR TITLE
Restart zero worker if there is still work to do (#18658)

### LINKED ISSUE #18607: cron.update_mirrors broken in Gitea 1.16.0
### Gitea Version

1.16.0

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.3

### How are you running Gitea?

Precompiled gitea-1.16.0-linux-amd64

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

I'm hosting a lot of mirrors on my Gitea instance. Some days ago I updated to 1.16.0.

image

I see -> it started at 04:00 AM, but ...

Last run with Gitea 1.15.x:

image

cron.update_mirrors needed with Gitea 1.15.x ~3h to update all mirrors. The cron runs fridays at 04:00 AM. And today was the first run.

I saw in gitea that the cron runs -> run count was 1. But the monitoring data shows no activity (RAM usage, CPU usage, Disk usage) between 04:00 and 07:00 AM.

Than I started (4-6x times) the cron in Gitea admin web console. It runs for some seconds. and I saw some activity.

But there is no date for the last run of the cron

image

After the 4-6 runs the sorting by last update time isn't showing any changes

image

All the projects with Feb 04 date are created today. But I can't see the updated mirrors when I change the sort order.

Why cron.update_mirrors is not updating all my mirrors? I can't see any errors in the Gitea logs.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by zeripath**
Backport #18658

It is possible for the zero worker to timeout before all the work is finished.
This may mean that work may take a long time to complete because a worker will only
be induced on repushing.

Also ensure that requested count is reset after pulls and push mirror sync requests and add some more trace logging to the queue push.

Fix #18607

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: modules/queue/workerpool.go [hunk 1]
```diff
@@ -277,6 +291,22 @@ func (p *WorkerPool) addWorkers(ctx context.Context, cancel context.CancelFunc,
 				p.cond.Broadcast()
 				cancel()
 			}
+
+			select {
+			case <-p.baseCtx.Done():
+				// Don't warn if the baseCtx is shutdown
+			default:
+				if p.hasNoWorkerScaling() {
```
Comment (Gusted) [inline modules/queue/workerpool.go:299]: Why does this differ from the other PR?

Comment (zeripath) [reply modules/queue/workerpool.go:299]: because of the lack of the pause function in 1.16.

**Review by Gusted — APPROVED** [review]

File: modules/queue/workerpool.go [hunk 2]
```diff
@@ -277,6 +291,22 @@ func (p *WorkerPool) addWorkers(ctx context.Context, cancel context.CancelFunc,
...
+					log.Warn(
+						"Queue: %d is configured to be non-scaling and has no workers - this configuration is likely incorrect.\n"+
+							"The queue will be paused to prevent data-loss with the assumption that you will add workers and unpause as required.", p.qid)
```
Comment (zeripath) [inline modules/queue/workerpool.go]:
```suggestion
						"Queue: %d is configured to be non-scaling and has no workers - this configuration is likely incorrect.", p.qid)
```

File: modules/queue/workerpool.go (hunk 1 above)
Comment (zeripath) [reply modules/queue/workerpool.go:299]: I'm gonna send another pr against main simplifying the logic here as we can just test the baseCtx.Done() once and there's no point trying to boost if the queue is non-scaling.

**Review by lafriks — APPROVED** [review]
