### PR TITLE
Fix bug when migrate from API

### LINKED ISSUE #8607: Error 500 after migrating github repository via api
- Gitea version (or commit ref):  
1.11.0+dev-56-g28f60bb5c built with GNU Make 4.2.1, go1.13.3 : bindata, sqlite, sqlite_unlock_notify
- Git version:  N/A
- Operating system:   docker on ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

I am attempting to migrate github repositories to gitea.  Each migration appears to work, but the repository is inaccessible in the GUI (display an Error 500 page).

```
$data='{
  "auth_username": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "clone_addr": "https://github.com/user/repository",
  "private": true,
  "mirror": true,
  "uid": 3,
  "repo_name": "repository",
  "auth_password": "",
  "description": ""
}'

$ curl -kvs -H 'Content-Type: application/json' -XPOST -d "$data" -H 'Authorization: token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' 'http://gitea:3000/api/v1/repos/migrate

{
  "id": 19,
  "owner": {
    "id": 3,
    "login": "myuser",
    "full_name": "",
    "email": "",
    "avatar_url": "https://gitea.local/user/avatar/myuser/-1",
    "language": "",
    "is_admin": false,
    "last_login": "1970-01-01T00:00:00Z",
    "created": "2019-05-28T01:59:28Z",
    "username": "myuser"
  },
  "name": "repository",
  "full_name": "myuser/repository",
  "description": "Common Place to put documentation about VISION",
  "empty": false,
  "private": true,
  "fork": false,
  "parent": null,
  "mirror": true,
  "size": 1063,
  "html_url": "https://gitea.local/myuser/repository",
  "ssh_url": "git@gitea.local:myuser/repository.git",
  "clone_url": "https://gitea.local/myuser/repository.git",
  "original_url": "",
  "website": "",
  "stars_count": 0,
  "forks_count": 0,
  "watchers_count": 1,
  "open_issues_count": 0,
  "default_branch": "master",
  "archived": false,
  "created_at": "2019-10-21T04:17:17Z",
  "updated_at": "2019-10-21T04:17:21Z",
  "permissions": {
    "admin": true,
    "push": true,
    "pull": true
  },
  "has_issues": true,
  "internal_tracker": {
    "enable_time_tracker": true,
    "allow_only_contributors_to_track_time": true,
    "enable_issue_dependencies": true
  },
  "has_wiki": true,
  "has_pull_requests": true,
  "ignore_whitespace_conflicts": false,
  "allow_merge_commits": true,
  "allow_rebase": true,
  "allow_rebase_explicit": true,
  "allow_squash_merge": true,
  "avatar_url": ""
}
```

At this point the repository exists, but returns Error 500 when you attempt to browse to it.

I discovered after a while that the following command;

```
sqlite gitea.db 'update repository set status=0'
```

would immediately unlock all the repositories, and I could browse and interact with them.

These are NOT large repositories, most between 1 and 25 megabytes.

Am I doing something wrong? Not waiting long enough? Or is something broken?

Thanks
Dave

### PR DESCRIPTION
**Pull request by lunny**
Fix #8607

### CODE REVIEW

**Review by guillep2k — COMMENTED** [review]
So I guess there's no point in having a background task for this. Any chances of the HTTP connection to break while migrating a large repository?

**Comment by lunny** [comment]
@guillep2k in fact, every http request will be running on a goroutine. If the handler function has been invoked and http connection break. The goroutine will still be running.

**Review by guillep2k — COMMENTED** [review]
> 
> 
> @guillep2k in fact, every http request will be running on a goroutine. If the handler function has been invoked and http connection break. The goroutine will still be running.

@lunny Yes, I guess so, but an API is meant to be called from a program, which means automation. What would be the correct procedure to check whether the migration succeeded or failed using the API?

Anyway, that seems to be out of the scope of this PR, so LGTM.

**Comment by guillep2k** [comment]
Tests fail as the text of the error message changed. 😑

**Comment by lunny** [comment]
The client could call the API on a gorutine/thread and if it succeed that's OK. If it's failed and it's a network problem, he can check if the repository exist via some API(which API is best?). If it's failed with a returned http status code. That means the migration failed.

I haven't moved this migration API to a background job because we need more work(i.e. task APIs) to let people could check if the migration task is done/success/failed. But this could be a PR in future.

**Review by guillep2k — COMMENTED** [review]
@lunny Please resolve conflicts.

**Review by guillep2k — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

File: routers/api/v1/repo/repo.go [hunk 1]
```diff
@@ -425,15 +427,55 @@ func Migrate(ctx *context.APIContext, form auth.MigrateRepoForm) {
...
+	}()
+
+	_, err = migrations.MigrateRepository(ctx.User, ctxUser.Name, opts)
+	if err == nil {
 		log.Trace("Repository migrated: %s/%s", ctxUser.Name, form.RepoName)
 		ctx.JSON(201, repo.APIFormat(models.AccessModeAdmin))
 		return
 	}
 
+	handleMigrateError(ctx, remoteAddr, err)
```
Comment (lafriks) [inline routers/api/v1/repo/repo.go]: This would be better instead:
```go
	if _, err = migrations.MigrateRepository(ctx.User, ctxUser.Name, opts); err != nil {
		handleMigrateError(ctx, remoteAddr, err)
		return
	}
	log.Trace("Repository migrated: %s/%s", ctxUser.Name, form.RepoName)
	ctx.JSON(201, repo.APIFormat(models.AccessModeAdmin))
```

File: routers/api/v1/repo/repo.go [hunk 2]
```diff
@@ -442,7 +484,7 @@ func Migrate(ctx *context.APIContext, form auth.MigrateRepoForm) {
 	case migrations.IsTwoFactorAuthError(err):
 		ctx.Error(422, "", "Remote visit required two factors authentication.")
 	case models.IsErrReachLimitOfRepo(err):
-		ctx.Error(422, "", fmt.Sprintf("You have already reached your limit of %d repositories.", ctxUser.MaxCreationLimit()))
+		ctx.Error(422, "", fmt.Sprintf("You have already reached your limit of %d repositories.", ctx.User.MaxCreationLimit()))
```
Comment (lafriks) [inline routers/api/v1/repo/repo.go]: why this change? `ctxUser` could be organization imho and than this would be organization limit not users

**Review by lafriks — CHANGES_REQUESTED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by techknowlogick** [comment]
@lunny please send backport

**Comment by davidlt** [comment]
Are there any plans to have this in 1.10.2 ?

**Comment by 6543** [comment]
@lunny @davidlt backport created
