### PR TITLE
Fix access check for org-level project

### LINKED ISSUE #25934: If repo.projects unit is disabled, it's still shown in user profile page
### Description

I'm using the DISABLE_REPO_UNITS to disable the projects unit. In most places, the project links are removed but in the user profile, the link still exists.

image

Clicking on that, leads to a 404 page

### Screenshots

image

### Gitea Version

1.20

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Docker on Debian

### Browser Version

Chrome 114

### PR DESCRIPTION
**Pull request by Zettat123**
Fix #25934

Add `ignoreGlobal` parameter to `reqUnitAccess` and only check global disabled units when `ignoreGlobal` is true. So the org-level projects and user-level projects won't be affected by global disabled `repo.projects` unit.

### CODE REVIEW

File: tests/integration/org_project_test.go [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+
+import (
+	"net/http"
+	"testing"
+
+	unit_model "code.gitea.io/gitea/models/unit"
+	"code.gitea.io/gitea/tests"
+)
+
+func TestOrgProjectAccess(t *testing.T) {
```
Comment (puni9869) [inline tests/integration/org_project_test.go:14]: 💯 
Thanks for the unit test. Much appreciated.

**Review by lunny — APPROVED** [review]

**Review by puni9869 — APPROVED** [review]
