### PR TITLE
Do not show 500 error when default branch doesn't exist

### LINKED ISSUE #34090: 500 Internal Server Error @ http://192.168.128.136:3000/username/repository/activity
### Description

500 Internal Server Error
An error occurred:

GetActivityStats, FillFromGit: Failed to get GetCodeActivityStats for repository.
Error: exit status 128
Stderr: fatal: ambiguous argument 'main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

### Gitea Version

Gitea Version: 1.23.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker-compose.yaml

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #34090

### CODE REVIEW

**Comment by wxiaoguang** [comment]
image

**Review by hiifong — APPROVED** [review]

File: routers/web/repo/activity.go [hunk 1]
```diff
@@ -52,6 +53,12 @@ func Activity(ctx *context.Context) {
 	ctx.Data["DateUntil"] = timeUntil
 	ctx.Data["PeriodText"] = ctx.Tr("repo.activity.period." + ctx.Data["Period"].(string))
 
+	branchExist, _ := git.IsBranchExist(ctx, ctx.Repo.Repository.ID, ctx.Repo.Repository.DefaultBranch)
```
Comment (lunny) [inline routers/web/repo/activity.go]: Since this page include code, issues and other information. Maybe just consider not return 404 but use `ctx.Repo.CanRead(unit.TypeCode) && branchExist` as the parameter.

Comment (wxiaoguang) [reply routers/web/repo/activity.go]: https://github.com/go-gitea/gitea/pull/34096/commits/7c5d7af5daf4f50a44010b0e8b7b9002a2f7a6b1

**Review by lunny — APPROVED** [review]
