### PR TITLE
GitLab reviews may not have the updated_at field set

### LINKED ISSUE #18434: Gitlab mirgration: invalid memory address or nil pointer
### Gitea Version

1.17.0+dev-47-g8038610a4

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

```yml
services:
        gitea-database:
          image: postgres:12.6-alpine
          restart: always
          environment:
            POSTGRES_USER: gitea
            POSTGRES_PASSWORD: "{{ gitea_database_password }}"
            POSTGRES_DB: gitea
            PGDATA: /var/lib/postgresql/data/pgdata
          volumes:
            - /var/lib/postgresql/gitea/pgdata:/var/lib/postgresql/data/pgdata

        gitea:
          image: gitea/gitea:{{ gitea_version }}
          restart: always
          ports:
            - "3022:22"
          volumes:
            - /opt/gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
          depends_on:
            - gitea-database
          environment:
            USER_UID: 1000
            USER_GID: 1000
            GITEA__database__DB_TYPE: postgres
            GITEA__database__HOST: gitea-database:5432
            GITEA__database__NAME: gitea
            GITEA__database__USER: gitea
            GITEA__database__PASSWD: "{{ gitea_database_password }}"
          networks:
            - default
            - web-proxy
```

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/anbraten/17a91226dbca85be5dae8a9541da4523

### Description

Getting an error while gitea tries to migrate pull-requests from Gitlab:

```
PANIC during runMigrateTask[3] by DoerID[4] to RepoID[3] for OwnerID[5]: runtime error: invalid memory address or nil pointer dereference
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by realaravinth**
> On behalf of [Loïc Dachary](https://lab.forgefriends.org/dachary)

Fallback to created_at if that the case and to time.Now() if it is
also missing.

Fixes: #18434

---
[source](https://lab.forgefriends.org/forgefriends/forgefriends/-/merge_requests/37)

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

File: services/migrations/gitlab.go [hunk 1]
```diff
@@ -640,13 +640,22 @@ func (g *GitlabDownloader) GetReviews(context base.IssueContext) ([]*base.Review
...
 
+	var createdAt time.Time
+	if approvals.UpdatedAt != nil {
+		createdAt = *approvals.UpdatedAt
+	} else if approvals.CreatedAt != nil {
+		createdAt = *approvals.CreatedAt
+	} else {
+		createdAt = time.Now()
+	}
+
```
Comment (wxiaoguang) [inline services/migrations/gitlab.go:651]: Why did the migrator use `approval.UpdatedAt` for `review.CreatedAt`?

It seems more reasonable to use `review.CreatedAt = approvals.CreatedAt ? approvals.CreatedAt : zero` ....

(Although both are fine to me, I just want to make it clear why the logic looks like this ....)

File: services/migrations/main_test.go [hunk 2]
```diff
@@ -28,6 +30,11 @@ func assertTimeEqual(t *testing.T, expected, actual time.Time) {
 	assert.Equal(t, expected.UTC(), actual.UTC())
 }
 
+func assertTimeEqualEpsilon(t *testing.T, expected, actual time.Time) {
+	d := expected.UTC().Sub(actual.UTC()).Seconds()
```
Comment (wxiaoguang) [inline services/migrations/main_test.go]:
```suggestion
	d := expected.Sub(actual).Seconds()
```


`Time.UTC()` only changes the timezone, `Time.Seconds()` is correct and enough.

**Review by wxiaoguang — COMMENTED** [review]
Generally L-G-T-M

File: services/migrations/main_test.go (hunk 2 above)
Comment (6543) [reply services/migrations/main_test.go]: I would just convert to unix timestamp and compare against - that way you have the second diff if needed + the exact time in log if it fails

Comment (6543) [reply services/migrations/main_test.go]: something like assert.Equal(t, expected.Unix(), actual.Unix(), "time differs") ...

File: services/migrations/gitlab.go (hunk 1 above)
Comment (6543) [reply services/migrations/gitlab.go:651]: I'm als for first check if CreatedAt != nil and fall back to UpdatedAt next. if we need Update too - we should add it to the base.Review - but that's nothing for a bugfix

**Review by 6543 — CHANGES_REQUESTED** [review]
as per comments

File: services/migrations/main_test.go (hunk 2 above)
Comment (wxiaoguang) [reply services/migrations/main_test.go]: @6543 

> something like assert.Equal(t, expected.Unix(), actual.Unix(), "time differs") ...

It's impossible without a mocked time provider. The `expected = time.Now()` is not the same as the `createdAt = time.Now()` inside `services/migrations/gitlab.go`

Comment (wxiaoguang) [reply services/migrations/main_test.go]: Aha, there is a `assert.WithinDuration()`, it's very handy. We do not need to re-invent the wheel `assertTimeEqualEpsilon`

Comment (6543) [reply services/migrations/main_test.go]: oh that's a new function! got added unoticed to me

File: services/migrations/gitlab.go (hunk 1 above)
Comment (6543) [reply services/migrations/gitlab.go:651]: @realaravinth

Comment (realaravinth) [reply services/migrations/gitlab.go:651]: > Why did the migrator use `approval.UpdatedAt` for `review.CreatedAt`?
> 
> It seems more reasonable to use `review.CreatedAt = approvals.CreatedAt ? approvals.CreatedAt : zero` ....
> 
> (Although both are fine to me, I just want to make it clear why the logic looks like this ....)


I agree that it would make more sense to use `approval.CreatedAt` and I cannot speak to the motives of the original implementor. I preserved this logic to not introduce a semantic change in the bugfix, however small. That being said, if you think this should be added to this patch, I'd be happy to do it.

---

[source](https://lab.fedeproxy.eu/forgefriends/forgefriends/-/merge_requests/37#note_915)

File: services/migrations/main_test.go (hunk 2 above)
Comment (realaravinth) [reply services/migrations/main_test.go]: Good find! I completely missed the `assert.WithinDuration` method. It is used in other other place in the Gitea tests with a delta of 10 seconds and I reused this. It should be plenty even for slow machines.

---
[source](https://lab.fedeproxy.eu/forgefriends/forgefriends/-/merge_requests/37#note_915)

File: services/migrations/gitlab.go (hunk 1 above)
Comment (wxiaoguang) [reply services/migrations/gitlab.go:651]: Since we all think that `approval.CreatedAt` is more reasonable, then we can have it now (we are making things better!).

It's hard to say whether the legacy code is correct or not 😂

File: services/migrations/gitlab.go [hunk 3]
```diff
@@ -640,13 +640,22 @@ func (g *GitlabDownloader) GetReviews(context base.IssueContext) ([]*base.Review
 		return nil, err
 	}
 
+	var createdAt time.Time
+	if approvals.UpdatedAt != nil {
+		createdAt = *approvals.UpdatedAt
+	} else if approvals.CreatedAt != nil {
+		createdAt = *approvals.CreatedAt
```
Comment (6543) [inline services/migrations/gitlab.go]:
```suggestion
	if approvals.CreatedAt != nil {
		createdAt = *approvals.CreatedAt
	} else if approvals.UpdatedAt != nil {
		createdAt = *approvals.UpdatedAt
```

**Review by 6543 — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Comment by 6543** [comment]
please send a backport :)
