### PR TITLE
Fix to use only needed columns from tables to get repository git paths

### LINKED ISSUE #3864: [E] Failed to initialize ORM engine: migrate: do migrate: pq: column "is_fsck_enabled" does not exist
This happens during migration. 

- Gitea version (or commit ref): v1.4.0
- Git version:
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
Compiled from source then try to execute the binary. That when this happens
gitea@slave:~$ ./gitea web
2018/04/30 02:44:08 [T] AppPath: /home/gitea/gitea
2018/04/30 02:44:08 [T] AppWorkPath: /home/gitea
2018/04/30 02:44:08 [T] Custom path: /home/gitea/custom
2018/04/30 02:44:08 [T] Log path: /home/gitea/log
gitea@slave:~$ tail -10 log/gitea.log
2018/04/30 02:30:52 [I] Migration: adds comment to an action
2018/04/30 02:30:53 [I] Migration: regenerate git hooks
2018/04/30 02:30:53 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: pq: column "is_fsck_enabled" does not exist
2018/04/30 02:44:08 [I] Log Mode: File(Info)
2018/04/30 02:44:08 [I] XORM Log Mode: File(Info)
2018/04/30 02:44:08 [I] Cache Service Enabled
2018/04/30 02:44:08 [I] Session Service Enabled
2018/04/30 02:44:08 [I] Mail Service Enabled
2018/04/30 02:44:08 [I] Migration: regenerate git hooks
2018/04/30 02:44:08 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: pq: column "is_fsck_enabled" does not exist
gitea@slave:~$

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #3864

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

File: models/repo.go [hunk 1]
```diff
@@ -479,6 +488,41 @@ func (repo *Repository) mustOwner(e Engine) *User {
 	return repo.Owner
 }
 
+func (repo *Repository) getOwnerName(e Engine) error {
+	if repo.OwnerName != "" {
```
Comment (bkcsoft) [inline models/repo.go]: `len(repo.OwnerName) > 0`

File: models/repo.go [hunk 2]
```diff
@@ -479,6 +488,41 @@ func (repo *Repository) mustOwner(e Engine) *User {
...
+
+// GetOwnerName returns the repository owner name
+func (repo *Repository) GetOwnerName() error {
+	return repo.getOwnerName(x)
+}
+
+func (repo *Repository) mustOwnerName(e Engine) string {
+	if err := repo.getOwnerName(e); err != nil {
+		log.Error(4, "Error loading repository owner name: %v", err)
+		return "error"
```
Comment (bkcsoft) [inline models/repo.go:520]: So `error` is now a reserved username/organization name? Then it should be added to said list :slightly_smiling_face:

File: models/repo.go [hunk 3]
```diff
@@ -479,6 +488,41 @@ func (repo *Repository) mustOwner(e Engine) *User {
...
+		return nil
+	}
+
+	if repo.Owner != nil {
+		repo.OwnerName = repo.Owner.Name
+		return nil
+	}
+
+	u := new(User)
+	has, err := e.ID(repo.OwnerID).Cols("name").Get(u)
```
Comment (bkcsoft) [inline models/repo.go:502]: Other than a slight increase in memory usage, I don't see any point in only loading the name. The database still has to find and fetch the entire row :thinking: I would change this to just `mustOwner()`

Comment (lafriks) [reply models/repo.go:502]: That's needed because it is used in migrations and can be that struct has more fields than database has so there will be error in select that database does not contain such column

File: models/repo.go (hunk 2 above)
Comment (lafriks) [reply models/repo.go:520]: It already returns owner name `error` in `mustOwner`, I just keep previous behaviour, this should be fixed in other PR

**Review by bkcsoft — APPROVED** [review]

File: models/repo.go [hunk 4]
```diff
@@ -479,6 +488,41 @@ func (repo *Repository) mustOwner(e Engine) *User {
...
```
Comment (lunny) [inline models/repo.go:502]:
```
has, err := e.Table("repository").Select("owner_name").Where("id=?", repo.OwnerID).Get(&repo.OwnerName)
```

Comment (lafriks) [reply models/repo.go:502]: @lunny do you want me to submit PR to change this to master first?

Comment (lafriks) [reply models/repo.go:502]: Do you mean something like:
```
has, err := e.Table("user").Select("name").Where("id=?", repo.OwnerID).Get(&repo.OwnerName)
```

Comment (lunny) [reply models/repo.go:502]: @lafriks the currently code is OK. I only want to say there is another way to do that.

Comment (lafriks) [reply models/repo.go:502]: ok, thanks, I will keep in mind that
