### PR TITLE
Fix and enhance comment editor monospace toggle

### LINKED ISSUE #36175: Monospace font settings broken in comment/issue editor
### Description

When you open a comment editor via "Edit" menu first time after page load, the font will be proportional regardless of font setting in upper right corner, but text on button says "disable monospace font". It seems to setting is properly stored in browser between reloads but not applied in editor and you need to double click button to enable monospace font again.

### Gitea Version

1.25.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

Not matters

### Operating System

Not matters

### How are you running Gitea?

Using demo.gitea.com, self-hosted

### Database

None

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/36175

1. Correctly apply setting on textareas spawned by comment edit
3. When changing the setting, apply it to all textareas on the current page

### CODE REVIEW

**Comment by silverwind** [comment]
I think this could be expanded to also apply the setting in other open tabs by leveraging the `storage` event:

https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event

I guess a small storage helper module is needed to abstract this out of the file and be useful for all localStorage-backed variables.

**Comment by silverwind** [comment]
I've added the bare minimum to get the setting working across tabs too. There's probably an opportunity to abstract into some `localStorage` module suitable for more similar localStorage-backed settings, but I'm not totally certain how to design it.

**Comment by silverwind** [comment]
`web_src/js/modules/storage.ts` is now contains minimal `localStorage` wrapper functions and I've used them everywhere where we previously used `localStorage` directly (except inline scripts, but that's another topic to be solved via web components). This is in preparation so that these settings can be synced to the server in the future.

**Review by lunny — APPROVED** [review]

File: web_src/js/modules/storage.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
+/** Get a setting from localStorage */
+export function getLocalStorageSetting(key: string) {
+  return localStorage?.getItem(key);
+}
+
+/** Set a setting in localStorage */
+export function setLocalStorageSetting(key: string, value: string) {
+  return localStorage?.setItem(key, value);
+}
```
Comment (wxiaoguang) [inline web_src/js/modules/storage.ts]: How do these two wrapper functions help?

Why not just write `localStorage.getItem()`?

File: web_src/js/features/comp/ComboMarkdownEditor.ts [hunk 2]
```diff
@@ -47,6 +48,21 @@ export function validateTextareaNonEmpty(textarea: HTMLTextAreaElement) {
   return true;
 }
 
+/** Returns whether the user currently has the monospace font setting enabled */
+function isMonospaceEnabled() {
+  return getLocalStorageSetting('markdown-editor-monospace') === 'true';
+}
+
+/** Apply font to the provided or all textareas on the page and optionally save on localStorage */
+function applyMonospace(enabled: boolean, {textarea, save}: {textarea?: HTMLTextAreaElement, save?: boolean}) {
```
Comment (wxiaoguang) [inline web_src/js/features/comp/ComboMarkdownEditor.ts]: It should be a method of `ComboMarkdownEditor`

And to change others, `getComboMarkdownEditor` and call their instance's method.

File: web_src/js/modules/storage.ts (hunk 1 above)
Comment (silverwind) [reply web_src/js/modules/storage.ts]: The wrappers are in preparation to synchronize these settings with the server, e.g. the current settings would be rendered into `<head>` and it would trigger a POST when a setting changes. For non-logged-in users, localStorage will be continued to be used. So to support both cases, these wrappers are needed.

Maybe the functions should have a better name like `getUserSetting`.

File: web_src/js/features/comp/ComboMarkdownEditor.ts (hunk 2 above)
Comment (silverwind) [reply web_src/js/features/comp/ComboMarkdownEditor.ts]: Might be possible if there's a way to get references to all current `ComboMarkdownEditor` on the page.

File: web_src/js/modules/storage.ts (hunk 1 above)
Comment (silverwind) [reply web_src/js/modules/storage.ts]: Thought this `addLocalStorageChangeListener` could not be implemented with server-backed storage without a websocket, I suppose. Maybe I should remove it.

File: web_src/js/features/comp/ComboMarkdownEditor.ts (hunk 2 above)
Comment (wxiaoguang) [reply web_src/js/features/comp/ComboMarkdownEditor.ts]: Use `getComboMarkdownEditor` for the related elements to get all current ComboMarkdownEditor instances

**Comment by wxiaoguang** [comment]
To make code maintainable: https://github.com/go-gitea/gitea/pull/36181/commits/b32c75f74d2536828fe56c4baca04b50560a59f1

**Comment by silverwind** [comment]
Instead of all these `get<Type>` functions, we could [let TypeScript handle it for us](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAyhzAJYDsDmBnKBeKBvAUFFAIYBcU6wATiqgDSFQBG5yArgLZMRUMC++fAGMA9skoV4SNOnJwEtTDgJEyUAEQBGdQyIsom-oIBmbZEKRioqePOmoAPABUoEAB7AIyACaYA1hAgIsawUooAfAAUASDkTgCUeIxU8GxUyJIKMgDaMQC6ANz4AsJiEsTY1rZhaJHqxOrxpeLAzJU2wHa0dUyNQA). `a` is `string` and `b` is `number`, it works like magic.

**Comment by wxiaoguang** [comment]
> Instead of all these `get<Type>` functions, we could [let TypeScript handle it for us](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAyhzAJYDsDmBnKBeKBvAUFFAIYBcU6wATiqgDSFQBG5yArgLZMRUMC++fAGMA9skoV4SNOnJwEtTDgJEyUAEQBGdQyIsom-oIBmbZEKRioqePOmoAPABUoEAB7AIyACaYA1hAgIsawUooAfAAUASDkTgCUeIxU8GxUyJIKMgDaMQC6ANz4AsJiEsTY1rZhaJHqxOrxpeLAzJU2wHa0dUyNQA). `a` is `string` and `b` is `number`, it works like magic.

It doesn't work. Or, you can make changes as your proposal.

**Comment by wxiaoguang** [comment]
> `a` is `string` and `b` is `number`, it works like magic.

It won't work like magic because our code needs to handle string parsing (not simply use the local storage value as-is).

I believe the current design is good enough, easy to use and error-proof. So I think we can get it merged.

**Review by wxiaoguang — APPROVED** [review]

**Comment by silverwind** [comment]
Hmm fine, I still think Typescript could be leveraged and that functions like `GetString` have no right to exist in a sound type system.

**Comment by silverwind** [comment]
Assuming we will sync to server later, I would not name it `localUserSettings` but `userSettings`.

File: web_src/js/modules/user-settings.ts [hunk 3]
```diff
@@ -0,0 +1,66 @@
+const itemKeyPrefix = 'glus:'; // gitea-local-user-settings
+
+function handleLocalStorageError(e: any) {
+  // in the future, maybe we need to handle quota exceeded errors differently
+  console.error('Error using local storage for user settings', e);
+}
+
+function getLocalStorageUserSetting(settingKey: string): string | null {
+  const legacyKey = settingKey;
+  const itemKey = `${itemKeyPrefix}${settingKey}`; // to avoid conflict with other localStorage items, use prefix
```
Comment (silverwind) [inline web_src/js/modules/user-settings.ts]: What conflict? A `get` operation can not have a conflict. Just use the existing keys which also avoids resetting the user's existing settings.

Comment (silverwind) [reply web_src/js/modules/user-settings.ts]: I see the code below does a migration, but I'm not sure a prefix is even neccessary, except maybe for key collisions with 3rd-party JS.

File: web_src/js/modules/user-settings.ts [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+  setString: (key: string, value: string) => {
+    setLocalStorageUserSetting(key, value);
+  },
+  getBoolean: (key: string, def: boolean = false): boolean => {
+    return localUserSettings.getString(key, String(def)) === 'true';
+  },
+  setBoolean: (key: string, value: boolean) => {
+    localUserSettings.setString(key, String(value));
+  },
+  getJsonObject: (key: string, def: any = null): any => {
```
Comment (silverwind) [inline web_src/js/modules/user-settings.ts]:
```ts
getJsonObject: <T = Record<string, any>>(key: string, def: T = null): T => {
```

And call like

```ts
localUserSettings.getJsonObject<LocaleStorageOptions>('actions-view-options', defaultViewOptions);
```

**Comment by wxiaoguang** [comment]
> Assuming we will sync to server later, I would not name it `localUserSettings` but `userSettings`.

I believe no at the moment. Because when that time reaches, the design will be quite different.

And since there is TypeScript type checking, it is easier to rewrite in the future.

**Comment by silverwind** [comment]
> > Assuming we will sync to server later, I would not name it `localUserSettings` but `userSettings`.
> 
> I believe no at the moment. Because when that time reaches, the design will be quite different.
> 
> And since there is TypeScript type checking, it is easier to rewrite in the future.

I guess it's actually ok because these settings are always kept local currently, so we can later rename the var to fit.

File: web_src/js/modules/user-settings.ts (hunk 3 above)
Comment (wxiaoguang) [reply web_src/js/modules/user-settings.ts]: Some people deploy Gitea under a subpath, which will cause potential conflicts.

So using prefix is always good.

And in case in the future Gitea will use local storage for other purposes, the keys for user settings do need a prefix

File: web_src/js/globals.d.ts [hunk 5]
```diff
@@ -77,6 +77,7 @@ interface Window {
     push: (e: ErrorEvent & PromiseRejectionEvent) => void | number,
   },
   codeEditors: any[], // export editor for customization
+  localUserSettings: typeof import('./modules/user-settings.ts').localUserSettings,
```
Comment (silverwind) [inline web_src/js/globals.d.ts:80]: This does not yet exist, right? Would add it when it actually does.

File: web_src/js/modules/user-settings.ts (hunk 4 above)
Comment (wxiaoguang) [reply web_src/js/modules/user-settings.ts]: Can you help to make this change? Thank you

File: web_src/js/globals.d.ts (hunk 5 above)
Comment (wxiaoguang) [reply web_src/js/globals.d.ts:80]: Don't understand.

"What" doesn't exist?

File: web_src/js/modules/user-settings.ts (hunk 3 above)
Comment (silverwind) [reply web_src/js/modules/user-settings.ts]: OK, but maybe prefix with `gitea:`? At least then we are not bound to this variable naming. And people inspecting localStorage will immediately know what those vars are.

Comment (wxiaoguang) [reply web_src/js/modules/user-settings.ts]: > OK, but maybe prefix with `gitea:`?

And in case in the future Gitea will use local storage for other purposes, the keys for user settings do need a prefix.

Comment (wxiaoguang) [reply web_src/js/modules/user-settings.ts]: > At least then we are not bound to this variable naming. And people inspecting localStorage will immediately know what those vars are.

Or you can use something like "gitea-user-setting:", but I think it is unnecessarily long.

File: web_src/js/modules/user-settings.ts (hunk 4 above)
Comment (silverwind) [reply web_src/js/modules/user-settings.ts]: Done in https://github.com/go-gitea/gitea/pull/36181/commits/2e7528924d663bb3e704d510ffd8d2a027cd0633.

File: web_src/js/globals.d.ts (hunk 5 above)
Comment (silverwind) [reply web_src/js/globals.d.ts:80]: Oh I see you are using a global? What's the use case for using a global? Why not share via imports?

File: web_src/js/modules/user-settings.ts [hunk 6]
```diff
@@ -51,7 +51,7 @@ export const localUserSettings = {
   setBoolean: (key: string, value: boolean) => {
     localUserSettings.setString(key, String(value));
   },
-  getJsonObject: (key: string, def: any = null): any => {
+  getJsonObject: <T extends Record<string, any> | null>(key: string, def: T = (null as T)): T => {
```
Comment (wxiaoguang) [inline web_src/js/modules/user-settings.ts]: It seem not strict.

`getJsonObject` declares that it only returns non-null T, but it can return null.

File: web_src/js/globals.d.ts (hunk 5 above)
Comment (silverwind) [reply web_src/js/globals.d.ts:80]: Ah, I see it's because of template JS, that's ok.

File: web_src/js/modules/user-settings.ts (hunk 3 above)
Comment (silverwind) [reply web_src/js/modules/user-settings.ts]: > And in case in the future Gitea will use local storage for other purposes, the keys for user settings do need a prefix.

I'm sure another prefix can be found then. `glus` is obscure, we need to change it.

Comment (silverwind) [reply web_src/js/modules/user-settings.ts]: maybe `gitea:settings:` or something. does not have to be overly precise.

File: web_src/js/modules/user-settings.ts (hunk 6 above)
Comment (silverwind) [reply web_src/js/modules/user-settings.ts]: `T extends Record<string, any> | null` includes `null`, should be fine. 

BTW I had to put this `(null as T)`, not sure how to get rid of the TS error otherwise.

File: web_src/js/modules/user-settings.ts (hunk 3 above)
Comment (wxiaoguang) [reply web_src/js/modules/user-settings.ts]: Done, and added comments

**Comment by silverwind** [comment]
lgtm
