### PR TITLE
fix incorrect role labels for migrated issues and comments

### LINKED ISSUE #22797: Migrated github issues incorrectly labeling all users as owner
### Description

All users in all issues are incorrectly labeled as "owner" for a project migrated from github. For example, see:

migrated: [tuxracer/react-canvas#169](https://gitea.com/tuxracer/react-canvas/issues/169)

source: https://github.com/Flipboard/react-canvas/issues/169

### Gitea Version

1.19.0+dev-403-gb6b8feb3d

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

**Gitea:**

Screenshot 2023-02-06 at 18 21 19

**Github:**

Screenshot 2023-02-06 at 18 21 38

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

gitea.com

### Database

None

### PR DESCRIPTION
**Pull request by Zettat123**
Fix #22797.

## Reason
If a comment was migrated from other platforms, this comment may have an original author and its poster is always not the original author. When the `roleDescriptor` func get the poster's role descriptor for a comment, it does not check if the comment has an original author. So the migrated comments' original authors might be marked as incorrect roles.

### CODE REVIEW

**Comment by lunny** [comment]
CI failure is related, otherwise LGTM.

File: models/issues/issue.go [hunk 1]
```diff
@@ -2403,3 +2403,8 @@ func DeleteOrphanedIssues(ctx context.Context) error {
 	}
 	return nil
 }
+
+// HasOriginalAuthor returns if an issue was migrated and has an original author.
+func (c *Issue) HasOriginalAuthor() bool {
```
Comment (zeripath) [inline models/issues/issue.go]:
```suggestion
func (issue *Issue) HasOriginalAuthor() bool {
```

File: models/issues/issue.go [hunk 2]
```diff
@@ -2403,3 +2403,8 @@ func DeleteOrphanedIssues(ctx context.Context) error {
 	}
 	return nil
 }
+
+// HasOriginalAuthor returns if an issue was migrated and has an original author.
+func (issue *Issue) HasOriginalAuthor() bool {
+	return c.OriginalAuthor != "" && c.OriginalAuthorID != 0
```
Comment (zeripath) [inline models/issues/issue.go]:
```suggestion
	return issue.OriginalAuthor != "" && issue.OriginalAuthorID != 0
```

**Review by zeripath — APPROVED** [review]

**Comment by techknowlogick** [comment]
ping lg-tm bot
