### PR TITLE
Make migrations SKIP_TLS_VERIFY apply to git too

### LINKED ISSUE #18998: SKIP_TLS_VERIFY not working for self-signed mirror
### Gitea Version

1.16.3

### Git Version

2.27.0

### Operating System

Rocky Linux 8.5

### How are you running Gitea?

Locally installed with systemd services.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

Cannot bypass self-signed cert validation for mirroring configuration, unless we import the target self-signed CA certificate into system path /etc/pki/ca-trust/source/anchors/my-ca.crt to make it work.

## Not working ##
```
[migrations]
SKIP_TLS_VERIFY = true
```

```
2022/03/04 10:08:43 ...ces/mirror/mirror.go:40:doMirrorSync() [I] [SQL] UPDATE `push_mirror` SET `repo_id` = ?, `remote_name` = ?, `interval` = ?, `last_update` = ?, `last_error` = ? WHERE `id`=? [400 remote_mirror_vL2BA04IvF 4h0m0s 1646388523 fatal: unable to access 'https://git.masked-dev.local/user1/common-library/': SSL certificate problem: self signed certificate in certificate chain
         3] - 9.847194ms
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by zeripath**
Make SKIP_TLS_VERIFY apply to git data migrations too

Fix #18998

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: modules/repository/repo.go [hunk 1]
```diff
@@ -72,9 +72,10 @@ func MigrateRepositoryGitData(ctx context.Context, u *user_model.User,
 	}
 
 	if err = git.Clone(ctx, opts.CloneAddr, repoPath, git.CloneRepoOptions{
-		Mirror:  true,
-		Quiet:   true,
-		Timeout: migrateTimeout,
+		Mirror:        true,
+		Quiet:         true,
+		Timeout:       migrateTimeout,
+		SkipTLSVerify: setting.Migrations.SkipTLSVerify,
```
Comment (Gusted) [inline modules/repository/repo.go:78]: Is the only instance that will need to have this option passed?

Comment (zeripath) [reply modules/repository/repo.go:78]: Done.

**Review by Gusted — APPROVED** [review]

**Comment by zeripath** [comment]
make lgtm work
