### PR TITLE
Drop is_bare IDX only when it exists for MySQL and MariaDB

### LINKED ISSUE #6718: Migration failure 1.7.6->1.8.0: No such index: IDX_user_"idx_user_IDX_user_is_active"
- Gitea version (or commit ref): 1.7.6
- Git version: ---
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
2019/04/23 11:48:27 [...itea/routers/init.go:82 GlobalInit()] [E] ORM engine initialization failed: migrate: do migrate: no such index: IDX_user_"idx_user_IDX_user_is_active"
2019/04/23 11:48:27 [I] Log Mode: File(Info)
2019/04/23 11:48:27 [I] XORM Log Mode: File(Info)
2019/04/23 11:48:27 [I] Cache Service Enabled
2019/04/23 11:48:27 [I] Session Service Enabled
2019/04/23 11:48:27 [I] Mail Service Enabled
2019/04/23 11:48:27 [I] Notify Mail Service Enabled
2019/04/23 11:48:27 [I] Beginning ORM engine initialization.
2019/04/23 11:48:27 [I] ORM engine initialization attempt #1/10...
2019/04/23 11:48:27 [I] Migration: add theme to users
2019/04/23 11:48:27 [I] Backing off for 3 seconds
2019/04/23 11:48:30 [I] ORM engine initialization attempt #2/10...
2019/04/23 11:48:30 [I] Migration: add theme to users
2019/04/23 11:48:30 [I] Backing off for 3 seconds
2019/04/23 11:48:33 [I] ORM engine initialization attempt #3/10...
2019/04/23 11:48:33 [I] Migration: add theme to users
2019/04/23 11:48:33 [I] Backing off for 3 seconds
...
```
## Description
I made sure every version from 1.7.0 up to 1.7.6 was working.
As soon as I upgrade from 1.7.6 to 1.8.0 I get the above error.

Indexes do exist and there's also one for `idx_user_IDX_user_is_active`
```sh
$ sqlite3 gitea.db .indexes | grep user_is_active
idx_user_IDX_user_is_active
```

### PR DESCRIPTION
**Pull request by adelowo**
Fixes https://github.com/go-gitea/gitea/issues/6718#issuecomment-486119583

### CODE REVIEW

File: models/migrations/v78.go [hunk 1]
```diff
@@ -34,8 +34,17 @@ func renameRepoIsBareToIsEmpty(x *xorm.Engine) error {
 	} else if models.DbCfg.Type == core.MSSQL {
 		_, err = sess.Exec("DROP INDEX IF EXISTS IDX_repository_is_bare ON repository")
 	} else {
-		_, err = sess.Exec("DROP INDEX IDX_repository_is_bare ON repository")
+
+		indexes, err := sess.QueryString(`SHOW INDEX FROM repository WHERE KEY_NAME = 'IDX_repository_is_bare'`)
```
Comment (lafriks) [inline models/migrations/v78.go:37]: I don't think this will work for sqlite

**Review by lafriks — CHANGES_REQUESTED** [review]

File: models/migrations/v78.go (hunk 1 above)
Comment (adelowo) [reply models/migrations/v78.go:37]: Take a look at https://github.com/go-gitea/gitea/pull/6736/commits/9715cac7b6fe2cf57dbd4b084db12d82284bed71

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by lafriks** [comment]
please backport to release/v1.8
