### PR TITLE
Bypass Firefox (iOS) bug

### LINKED ISSUE #20240: Javascript error on mobile Firefox (iOS)
### Description

When browsing on Firefox iOS, I get the following error: 

`JavaScript error: Script error. ( @ 0:0). Open browser console to see more details.` 

I can reproduce it on the demo site. 

Does not occur when browsing with Safari on iOS or DuckDuckGo browser on iOS. And does not occur on desktop. 

### Screenshots

9895B54E-F0BB-457C-8CD8-88AB4E65A9E2
3010AB31-D6D6-4C6C-95B1-0405AFA9D9E3

### Gitea Version

1.17.0+rc1 (docker version)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

iOS 

### Browser Version

Firefox Daylight 101.1 (10346)

### PR DESCRIPTION
**Pull request by wxiaoguang**
Close #20240

* https://github.com/go-gitea/gitea/issues/20240

At the moment, Firefox (iOS) (10x) has an engine bug. See https://github.com/go-gitea/gitea/issues/20240
If a script inserts a newly created (and content changed) element into DOM, there will be a nonsense error event reporting: Script error: line 0, col 0.

This PR ignores such nonsense error event.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
Is FirefoxIOs aware of this bug?

I guess we should just handle this bug though - so LGTM.

**Comment by wxiaoguang** [comment]
I have submitted an issue `https://github.com/mozilla-mobile/firefox-ios/issues/11191` , not sure when they can get it fixed.

File: web_src/js/bootstrap.js [hunk 1]
```diff
@@ -20,6 +20,11 @@ export function showGlobalErrorMessage(msg) {
  * @param {ErrorEvent} e
  */
 function processWindowErrorEvent(e) {
+  if (!e.error && e.lineno === 0 && e.colno === 0 && e.filename === '' && window.navigator.userAgent.includes('FxiOS/')) {
```
Comment (delvh) [inline web_src/js/bootstrap.js:23]: Isn't the last condition unnecessary?
It feels less like a workaround without the last condition...
```suggestion
  if (!e.error && e.lineno === 0 && e.colno === 0 && e.filename === '') {
```

**Review by delvh — APPROVED** [review]

File: web_src/js/bootstrap.js (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/bootstrap.js:23]: But only Firefox(iOS) has this bug. `'FxiOS/'` means Firefox(iOS)

Comment (wxiaoguang) [reply web_src/js/bootstrap.js:23]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#firefox_for_ios

[Firefox for iOS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#firefox_for_ios)

Firefox for iOS uses the default Mobile Safari UA string, with an additional FxiOS/<version> token on iPod and iPhone

Comment (delvh) [reply web_src/js/bootstrap.js:23]: At the moment.
But if Firefox already manages to produce such an obscure bug, why shouldn't the others be able to do that as well?

Comment (delvh) [reply web_src/js/bootstrap.js:23]: I'm fine with both approaches, hence I already approved, but I still wanted to point that out.

Comment (wxiaoguang) [reply web_src/js/bootstrap.js:23]: I do not think it could be a general bug for modern browsers. This bug is highly likely to be caused by some incorrect DOM layout handling. The last similar bug in my mind is as old as back to Internet Explorer 6 (20 years ago) ......

**Comment by zeripath** [comment]
Please send backport
