### PR TITLE
Fix commit status cache which missed target_url

### LINKED ISSUE #30421: commit status link in dashboard is broken
### Description

https://github.com/go-gitea/gitea/pull/30223#issuecomment-2046655940

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

build

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix #30421

### CODE REVIEW

File: services/repository/commitstatus/commitstatus.go [hunk 1]
```diff
@@ -26,12 +27,33 @@ func getCacheKey(repoID int64, brancheName string) string {
...
+		}
+	}
+	return nil
 }
 
-func deleteCommitStatusCache(ctx context.Context, repoID int64, branchName string) error {
+func updateCommitStatusCache(repoID int64, branchName string, state api.CommitStatusState, targetURL string) error {
+	c := cache.GetCache()
+	bs, _ := json.Marshal(commitStatusCacheValue{
+		State:     string(state),
```
Comment (yp05327) [inline services/repository/commitstatus/commitstatus.go]: state.String() ?

File: services/repository/commitstatus/commitstatus.go [hunk 2]
```diff
@@ -98,12 +120,12 @@ func CreateCommitStatus(ctx context.Context, repo *repo_model.Repository, creato
...
 	for i, repo := range repos {
-		status, ok := c.Get(getCacheKey(repo.ID, repo.DefaultBranch)).(string)
-		if ok && status != "" {
-			results[i] = &git_model.CommitStatus{State: api.CommitStatusState(status)}
+		if cv := getCommitStatusCache(repo.ID, repo.DefaultBranch); cv != nil {
+			results[i] = &git_model.CommitStatus{
+				State:     api.CommitStatusState(cv.State),
+				TargetURL: cv.TargetURL,
+			}
 		}
```
Comment (yp05327) [inline services/repository/commitstatus/commitstatus.go:137]: log when get commit status cache failed?

**Comment by yp05327** [comment]
We only uses State and TargetURL now, so it is ok. 
But if we want to use this cache with other fields, we should be careful about it.
So why not add other fields together?

**Comment by lunny** [comment]
> We only uses State and TargetURL now, so it is ok. But if we want to use this cache with other fields, we should be careful about it. So why not add other fields together?

You don't know which fields will be used. Maybe that field hasn't been implemented in the current version.

File: services/repository/commitstatus/commitstatus.go (hunk 2 above)
Comment (lunny) [reply services/repository/commitstatus/commitstatus.go:137]: Fixed.

**Review by yp05327 — APPROVED** [review]

File: services/repository/commitstatus/commitstatus.go [hunk 3]
```diff
@@ -26,12 +27,41 @@ func getCacheKey(repoID int64, brancheName string) string {
 	return fmt.Sprintf("commit_status:%x", hashBytes)
 }
 
-func updateCommitStatusCache(ctx context.Context, repoID int64, branchName string, status api.CommitStatusState) error {
+type commitStatusCacheValue struct {
+	State     string
+	TargetURL string
```
Comment (wolfogre) [inline services/repository/commitstatus/commitstatus.go]:
```suggestion
	State     string `json:"state"`
	TargetURL string `json:"target_url"`
```

File: services/repository/commitstatus/commitstatus.go [hunk 4]
```diff
@@ -26,12 +27,41 @@ func getCacheKey(repoID int64, brancheName string) string {
...
+	statusStr, ok := c.Get(getCacheKey(repoID, branchName)).(string)
+	if ok && statusStr != "" {
+		var cv commitStatusCacheValue
+		err := json.Unmarshal([]byte(statusStr), &cv)
+		if err == nil && cv.State != "" {
+			return &cv
+		}
+		if err != nil {
+			log.Warn("getCommitStatusCache: json.Unmarshal failed: %v", err)
+		}
```
Comment (wolfogre) [inline services/repository/commitstatus/commitstatus.go:46]: ~~Be compatible with the old `string(status)` data?~~

Hmm, maybe it's fine to ignore them since they are just cache.

**Review by wolfogre — APPROVED** [review]

File: services/repository/commitstatus/commitstatus.go [hunk 5]
```diff
@@ -26,12 +27,41 @@ func getCacheKey(repoID int64, brancheName string) string {
...
+	State     string `json:"state"`
+	TargetURL string `json:"target_url"`
+}
+
+func getCommitStatusCache(repoID int64, branchName string) *commitStatusCacheValue {
+	c := cache.GetCache()
+	statusStr, ok := c.Get(getCacheKey(repoID, branchName)).(string)
+	if ok && statusStr != "" {
+		var cv commitStatusCacheValue
+		err := json.Unmarshal([]byte(statusStr), &cv)
```
Comment (wxiaoguang) [inline services/repository/commitstatus/commitstatus.go:40]: That's a mess .... why not wait for #30417 first? Could you help to resolve the conflicts with #30417 ?

Comment (lunny) [reply services/repository/commitstatus/commitstatus.go:40]: Because this PR will be backport but that will not. I will contribute to #30417 and resolve the conflicts.

Comment (wxiaoguang) [reply services/repository/commitstatus/commitstatus.go:40]: #30417 also must be backported because it fixes various cache bugs.


image

Comment (wxiaoguang) [reply services/repository/commitstatus/commitstatus.go:40]: The original description explained why it is necessary and how the bugs are fixed, but the content was edited.

image

Comment (lunny) [reply services/repository/commitstatus/commitstatus.go:40]: This PR also needs to be backpor to v1.21.
