### PR TITLE
Fix date rendering by adding `<gitea-absolute-date>`

### LINKED ISSUE #29034: MIlestones with 2/29 due date display as 2/28
### Description

As simple as it sounds. Create a milestone with due date 2/29/2024, and it will display as 2/28/2024.

image

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.40.1

### Operating System

Gentoo

### How are you running Gitea?

Gentoo gitea package

### Database

SQLite

### PR DESCRIPTION
**Pull request by silverwind**
Alternative to: https://github.com/go-gitea/gitea/pull/29698
Fixes: https://github.com/go-gitea/gitea/issues/29034

image

It also fixes a secondary issue that we were showing timestamp tooltips over date, which makes no sense, so these are now gone as well:

image

### CODE REVIEW

**Comment by silverwind** [comment]
This is using the current naming scheme, not the one from https://github.com/go-gitea/gitea/pull/29400. Likely in that PR or separately, I will do the rename.

File: web_src/js/webcomponents/GiteaLocaleDate.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
+window.customElements.define('gitea-locale-date', class extends HTMLElement {
```
Comment (yardenshoham) [inline web_src/js/webcomponents/GiteaLocaleDate.js]: why not extend `<relative-time>`?

Comment (silverwind) [reply web_src/js/webcomponents/GiteaLocaleDate.js]: We aren't replacing https://github.com/github/relative-time-element, we are just adding another custom element to render absolute dates in locale format.

**Review by yardenshoham — APPROVED** [review]

**Comment by yardenshoham** [comment]
Backport?

**Comment by denyskon** [comment]
We can try....

**Comment by silverwind** [comment]
> Backport?

Yeah, would be good.

File: web_src/js/webcomponents/GiteaLocaleDate.js (hunk 1 above)
Comment (silverwind) [reply web_src/js/webcomponents/GiteaLocaleDate.js]: Oh, and to answer specifically: `<relative-time>` is not meant to be passed dates, only datetimes. So it's currently unsuitable for the date rendering and I'm not sure whether upstream would accept a `date` parameter as it would increase internal complexity of the component a lot.

File: web_src/js/webcomponents/GiteaLocaleDate.js [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+  update = () => {
+    const year = this.getAttribute('year') ?? '';
+    const month = this.getAttribute('month') ?? '';
+    const weekday = this.getAttribute('weekday') ?? '';
+    const day = this.getAttribute('day') ?? '';
+    const lang = this.closest('[lang]')?.getAttribute('lang') ||
+      this.ownerDocument.documentElement.getAttribute('lang') ||
+      '';
+
+    // only extract the `yyyy-mm-dd` part
```
Comment (silverwind) [inline web_src/js/webcomponents/GiteaLocaleDate.js]:
```suggestion
    // only extract the `yyyy-mm-dd` part. When converting to Date, the date will be in UTC and when rendered
    // as locale date, will have a offset towards UTC added. We should eventually use `Temporal.PlainDate` here
    // to avoid needing to remove this offset: https://tc39.es/proposal-temporal/docs/plaindate.html
```

**Review by denyskon — APPROVED** [review]

**Comment by silverwind** [comment]
Let's see if it backports automatically 😆.

**Comment by yardenshoham** [comment]
It broke my timezone (UTC+2) if I set March 29
bug

**Comment by silverwind** [comment]
Hmm, will need to debug this.

**Comment by silverwind** [comment]
@yardenshoham try https://github.com/go-gitea/gitea/pull/29804
