### PR TITLE
Fix go get

### LINKED ISSUE #14756: Go get broken because parameters cannot be retrieved from chi middleware
A report said that `go get` will not work on master. I found that because chi don't support that. 
ref. https://github.com/go-chi/chi/issues/468

### PR DESCRIPTION
**Pull request by lunny**
Fix broken go get, Fix #14756

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Review by zeripath — CHANGES_REQUESTED** [review]
blocking as per @techknowlogick

File: routers/routes/web.go [hunk 1]
```diff
@@ -216,6 +219,67 @@ func WebRoutes() *web.Route {
...
+<html>
+	<body>
+		invalid import path
+	</body>
+</html>
+`))
+		ctx.Status(400)
+		return
+	}
+	branchName := "master"
```
Comment (techknowlogick) [inline routers/routes/web.go]: Instead of master here, could you use Default branch from settings?

**Comment by lunny** [comment]
@techknowlogick @zeripath Done.

**Review by 6543 — APPROVED** [review]

**Review by zeripath — APPROVED** [review]
