### PR TITLE
Fix clean tmp dir

### LINKED ISSUE #31792: Gitea keeps on filling /tmp with indexes
### Description

We are running Gitea (`1.22.1`) on OpenBSD (`7.5-current` on `amd64`). For some reason, Gitea keeps writing index files to `/tmp`, despite having configured different paths in the Gitea config. Since this partition is 3GB, it fills up rather quickly.

What causes this behaviour? Is there a configuration option that we are missing? If it possible to have Gitea use a custom path for these temporary indexes?

Our config:

```
APP_NAME = Code
RUN_USER = _gitea
RUN_MODE = prod
WORK_PATH = /usr/local/share/gitea

[server]
PROTOCOL = http
DOMAIN = [domain]
ROOT_URL = https://[domain]
HTTP_ADDR = 127.0.0.1
HTTP_PORT = 3000
START_SSH_SERVER = true
BUILTIN_SSH_SERVER_USER = git
SSH_PORT = 2222
SSH_LISTEN_PORT = %(SSH_PORT)s
SSH_SERVER_CIPHERS = chacha20-poly1305@openssh.com,aes256-ctr,aes256-gcm@openssh.com
SSH_SERVER_KEY_EXCHANGES = curve25519-sha256
SSH_SERVER_MACS = hmac-sha2-256-etm@openssh.com
SSH_SERVER_HOST_KEYS = /var/gitea/.ssh/gitea.ed
;, /var/gitea/.ssh/gitea.rsa
APP_DATA_PATH = /var/gitea/data
PPROF_DATA_PATH = /var/gitea/data/tmp/pprof
LFS_JWT_SECRET = [secret]
SSH_DOMAIN = [domain]
DISABLE_SSH = false
LFS_START_SERVER = true
OFFLINE_MODE = true

[database]
DB_TYPE = postgres
LOG_SQL = false
HOST = 127.0.0.1:5432
NAME = gitea
USER = gitea
PASSWD = [secret]
SCHEMA = 
SSL_MODE = disable
CHARSET = utf8

[security]
INSTALL_LOCK = true
SECRET_KEY = 
INTERNAL_TOKEN = [secret]
PASSWORD_HASH_ALGO = pbkdf2

[ssh.minimum_key_sizes]
ED25519 = 256
ECDSA = -1
RSA = 4096
DSA = -1

[camo]

[oauth2]
ENABLE = true
JWT_SIGNING_PRIVATE_KEY_FILE = /var/gitea/jwt/private.pem
JWT_SECRET = [secret]

[log]
ROOT_PATH = /var/log/gitea
MODE = file
LEVEL = Fatal

[git]

[service]
DISABLE_REGISTRATION = false
REQUIRE_SIGNIN_VIEW = false
DISABLE_USERS_PAGE = true
DEFAULT_KEEP_EMAIL_PRIVATE = true
DEFAULT_ALLOW_CREATE_ORGANIZATION = false
DEFAULT_USER_VISIBILITY = private
DEFAULT_ORG_VISIBILITY = private
ROOT = /var/gitea/gitea-repositories
SCRIPT_TYPE = sh
DEFAULT_PRIVATE = private
PREFERRED_LICENSES = BSD-2-Clause,ISC
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL = false
ALLOW_ONLY_EXTERNAL_REGISTRATION = false
ENABLE_CAPTCHA = false
DEFAULT_ENABLE_TIMETRACKING = true
NO_REPLY_ADDRESS = noreply.[domain]

[repository.local]
LOCAL_COPY_PATH = /var/gitea/tmp/local-repo

[repository.upload]
TEMP_PATH = /var/gitea/data/tmp/uploads
FILE_MAX_SIZE = 2048

[cache]
ADAPTER = redis
HOST = redis://127.0.0.1:6379/1?pool_size=100&idle_timeout=180s

[ui]
SHOW_USER_EMAIL = false
DEFAULT_THEME = gitea-dark
THEMES = gitea-dark
ED25519 = 256
ECDSA = 256
RSA = 2047
DSA = -1

[indexer]
ISSUE_INDEXER_TYPE = db
ISSUE_INDEXER_PATH = /var/gitea/indexers/issues.bleve
STARTUP_TIMEOUT = 30s
REPO_INDEXER_ENABLED = false
REPO_INDEXER_PATH = /var/gitea/indexers/repos.bleve
;ISSUE_INDEXER_QUEUE_DIR = /var/gitea/indexers/issues.queue
;REPO_INDEXER_PATH = /var/gitea/indexers/repos.bleve

[admin]
DISABLE_REGULAR_ORG_CREATION = true
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false

[queue]
TYPE = redis
CONN_STR = redis://127.0.0.1:6379/0
MAX_WORKERS = 4
DATADIR = /var/gitea/queue

[storage]
STORAGE_TYPE = local

[mailer]
ENABLED = true
PROTOCOL = smtp+starttls
SMTP_ADDR = [smtp-server]
SMTP_PORT = 587
FROM = [sender]
SEND_AS_PLAIN_TEXT = true
USER = [user]
PASSWD = [secret]

[session]
PROVIDER = db
COOKIE_SECURE = true

[picture]
AVATAR_UPLOAD_PATH = /var/gitea/data/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /var/gitea/data/repo-avatars
DISABLE_GRAVATAR = true
ENABLE_FEDERATED_AVATAR = false

[attachment]
MAX_SIZE = 2048
PATH = /var/gitea/data/attachments

[time]
FORMAT = RFC1123Z

[other]
SHOW_FOOTER_VERSION = false
SHOW_FOOTER_TEMPLATE_LOAD_TIME = false
CHUNKED_UPLOAD_PATH = /var/gitea/data/tmp/package-upload

[repository]
ROOT = /var/code/repos

[lfs]
PATH = /var/code/lfs

[repository.pull-request]
DEFAULT_MERGE_STYLE = merge

[repository.signing]
DEFAULT_TRUST_MODEL = committer

[git.timeout]
DEFAULT = 720
MIGRATE = 30000
MIRROR = 72000
CLONE = 30000
PULL = 30000
GC = 60
```

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

We are using the OpenBSD package

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by lunny**
Try to fix #31792 

Credit to @jeroenlaylo
Copied from https://github.com/go-gitea/gitea/issues/31792#issuecomment-2311920520

### CODE REVIEW

**Review by a1012112796 — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

File: modules/git/repo_index.go [hunk 1]
```diff
@@ -63,9 +63,16 @@ func (repo *Repository) ReadTreeToTemporaryIndex(treeish string) (filename, tmpD
...
+	// Defer the cancel function to ensure cleanup in case of an error
+	defer func() {
+		if err != nil {
+			cancel()
+		}
+	}()
+
 	err = repo.ReadTreeToIndex(treeish, filename)
 	if err != nil {
-		defer cancel()
```
Comment (wxiaoguang) [inline modules/git/repo_index.go:68]: What's the difference?

Before: `if err != nil`, then in defer: `cancel`

After: `if err != nil`, then in defer: `if err != nil { cacnel }`.

File: modules/git/repo_index.go [hunk 2]
```diff
@@ -63,9 +63,16 @@ func (repo *Repository) ReadTreeToTemporaryIndex(treeish string) (filename, tmpD
 			log.Error("failed to remove tmp index file: %v", err)
 		}
 	}
+
+	// Defer the cancel function to ensure cleanup in case of an error
+	defer func() {
+		if err != nil {
+			cancel()
+		}
+	}()
```
Comment (wxiaoguang) [inline modules/git/repo_index.go:60]: It should be moved to the beginning of the `ReadTreeToTemporaryIndex`, to avoid the overridden (local err) `err := ...` in the future

Comment (lunny) [reply modules/git/repo_index.go:60]: 812f8bb8c4fadeae0027c9ea3b1cf481b9cbc9e0

File: modules/git/repo_index.go [hunk 3]
```diff
@@ -51,6 +51,13 @@ func (repo *Repository) readTreeToIndex(id ObjectID, indexFilename ...string) er
 
 // ReadTreeToTemporaryIndex reads a treeish to a temporary index file
 func (repo *Repository) ReadTreeToTemporaryIndex(treeish string) (filename, tmpDir string, cancel context.CancelFunc, err error) {
+	defer func() {
+		// if error happens and there is a cancel function, do the clean up
+		if err != nil && cancel != nil {
+			cancel()
```
Comment (wxiaoguang) [inline modules/git/repo_index.go:57]:
```suggestion
			cancel()
			cancel = nil
```

File: modules/git/repo_index.go [hunk 4]
```diff
@@ -65,7 +73,6 @@ func (repo *Repository) ReadTreeToTemporaryIndex(treeish string) (filename, tmpD
 	}
 	err = repo.ReadTreeToIndex(treeish, filename)
 	if err != nil {
-		defer cancel()
 		return "", "", func() {}, err
```
Comment (wxiaoguang) [inline modules/git/repo_index.go]:
```suggestion
		return "", "", cancel, err
```

File: modules/git/repo_index.go [hunk 5]
```diff
@@ -51,6 +51,14 @@ func (repo *Repository) readTreeToIndex(id ObjectID, indexFilename ...string) er
...
+		// if error happens and there is a cancel function, do the clean up
+		if err != nil && cancel != nil {
+			cancel()
+			cancel = nil
+		}
+	}()
+
 	tmpDir, err = os.MkdirTemp("", "index")
 	if err != nil {
 		return filename, tmpDir, cancel, err
```
Comment (wxiaoguang) [inline modules/git/repo_index.go]:
```suggestion
		return "", "", cancel, err
```

**Comment by wxiaoguang** [comment]
Reset my changes (the code looks pretty messy) ...  will think about it

**Review by wxiaoguang — DISMISSED** [review]
Some more details: it is still about the "variable overriding". For example, I think the initial commits like d3b98337353abcae14d81512fdcd5c0e32d1b49f won't work, because when doing `return "", "", func() {}, err
`, it makes `tmpDir=""`, then the `cancel` in defer will be skipped.

**Review by 6543 — APPROVED** [review]

**Review by lafriks — APPROVED** [review]
