### PR TITLE
Fix deadline on update issue or PR via API

### LINKED ISSUE #8179: Due date not saving when set via API
- Gitea version (or commit ref): 1.10.0+dev-288-g7a8e299c7 
- Git version: 2.11.0
- Operating system: Devuan Ascii (Debian Stretch)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When using API to set a due date the timeline shows it has been set, but the due date comes back null.

```
curl -X PATCH "https://xxx/api/v1/repos/jhodges/test/issues/11" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{ \"due_date\": \"2019-09-14T15:46:01.026Z\" }"

{"id":1116, ... "due_date":null, ...}
```
~~The same API call works just fine on try.gitea.io so it must be something local.  Any ideas?~~ edit: not true

## Screenshots

You can see the timeline showing my attempts to add a date, yet still it is not shown in the due date field on the right bar.

2019-09-14-165952_1099x235_scrot

### PR DESCRIPTION
**Pull request by davidsvantesson**
Fix #8179.

### CODE REVIEW

File: routers/api/v1/repo/issue.go [hunk 1]
```diff
@@ -337,13 +337,13 @@ func EditIssue(ctx *context.APIContext, form api.EditIssueOption) {
 
 	// Update the deadline
 	var deadlineUnix timeutil.TimeStamp
-	if form.Deadline != nil && !form.Deadline.IsZero() && ctx.Repo.CanWrite(models.UnitTypeIssues) {
+	if form.Deadline != nil && ctx.Repo.CanWrite(models.UnitTypeIssues) {
 		deadlineUnix = timeutil.TimeStamp(form.Deadline.Unix())
```
Comment (guillep2k) [inline routers/api/v1/repo/issue.go]:
```suggestion
		deadlineUnix := timeutil.TimeStamp(form.Deadline.Unix())
```
(And remove declaration above)

File: routers/api/v1/repo/pull.go [hunk 2]
```diff
@@ -393,13 +393,13 @@ func EditPullRequest(ctx *context.APIContext, form api.EditPullRequestOption) {
 
 	// Update Deadline
 	var deadlineUnix timeutil.TimeStamp
-	if form.Deadline != nil && !form.Deadline.IsZero() {
+	if form.Deadline != nil {
 		deadlineUnix = timeutil.TimeStamp(form.Deadline.Unix())
```
Comment (guillep2k) [inline routers/api/v1/repo/pull.go]:
```suggestion
		deadlineUnix := timeutil.TimeStamp(form.Deadline.Unix())
```

**Review by guillep2k — APPROVED** [review]

**Comment by davidsvantesson** [comment]
Should this be backported to both v1.10 and v1.9? There was some changes after v1.9 so I can't just cherry-pick, but no problem to do similar fix.

**Comment by lunny** [comment]
@davidsvantesson I think yes. But so that you can't remove the deadline any more?

**Comment by davidsvantesson** [comment]
I have submitted all PRs for this issue now, slight difference:
master & 1.10: The deadline can be removed (if set but is zero)
1.9: The deadline can't be removed, to not change behavior. 

Make comment in respective PR if you think it should be different.

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by bobemoe** [comment]
1.11.0+dev-104-ge3875ace9

Confirmed working:
* Setting due date via `PATCH ​/repos​/{owner}​/{repo}​/issues​/{index}` now works.
* Editing title or body without due date via `PATCH ​/repos​/{owner}​/{repo}​/issues​/{index}` now works without triggering erroneous "due date removed" timeline comment.

Having trouble with:
* I can't remove the due date by setting it to "", "0", 0, null, "null", nill, "nill", false, "false" or "0000-00-00".  I just get various "cannot parse time" errors. Interestingly setting to value `null` (without the quotes) does not produce an error, but it does not remove the due date.

**Comment by davidsvantesson** [comment]
@bobemoe I though I tested that but apparently not after my fix. I will look at it tonight.
