### PR TITLE
Fix incorrect `/tokens` api

### LINKED ISSUE #32078: Incomplete API `POST` reponse for `scopes` in `/api/v1/users/<user>/tokens`
### Description

When creating a token via the API and supplying scopes, eg...
```sh
curl -k -H "Content-Type: application/json" -d '{"name":"test2", "scopes":["write:package", "read:notification"]}' -u user:pass https://gitea.domain.com/api/v1/users/Vlad/tokens
```
the response for `scopes` is always `null`, eg.
```json
{"id":13,"name":"test2","sha1":"6xxxxxxxxxxxxxx87c","token_last_eight":"bd4e087c","scopes":null}
```
even though the permissions are actually there:
```sh
curl -k -H "Content-Type: application/json" -u user:pass https://gitea.domain.com/api/v1/users/Vlad/tokens
```
```json
[{"id":13,"name":"test2","sha1":"","token_last_eight":"bd4e087c","scopes":["read:notification","write:package"]}]
```
This issue was found when updating the documentation in pull request https://gitea.com/gitea/docs/pulls/72

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Ubuntu server, installed via binaries downloaded from this repo

### Database

None

### PR DESCRIPTION
**Pull request by KN4CK3R**
Fixes #32078

- Add missing scopes output.
- Disallow empty scope.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Review by wolfogre — APPROVED** [review]

File: tests/integration/api_token_test.go [hunk 1]
```diff
@@ -563,8 +555,7 @@ func createAPIAccessTokenWithoutCleanUp(t *testing.T, tokenName string, user *us
 	return newAccessToken
 }
 
-// createAPIAccessTokenWithoutCleanUp Delete an API access token and assert that
-// deletion succeeded.
+// Delete an API access token and assert that deletion succeeded.
```
Comment (lafriks) [inline tests/integration/api_token_test.go]: Go function comment should start with function name

Comment (lunny) [inline tests/integration/api_token_test.go]:
```suggestion
// deleteAPIAccessToken deletes an API access token and assert that deletion succeeded.
```
