### PR TITLE
Fix archive error when rename repo or user

### LINKED ISSUE #16390: Repo Archive path invalid after rename
After a repository rename the old archive path gets unaccessable which prevents deleting old archives.
Reason is the repository name in the filepath:
`fmt.Sprintf("%s/%s/%s.%s", repo.FullName(), archiver.CommitID[:2], archiver.CommitID, archiver.Type.String())`

/cc @lunny

### PR DESCRIPTION
**Pull request by lunny**
Fix #16390

#14723 introduced two bugs, one is to delete all archivers may failed, another is after rename repo or user, visit archivers may failed.

This PR will fix them. But it's a break change. After applying the patch, please run `Delete all repositories' archives` to remove all old files which may become garbages.

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

File: models/repo_archiver.go [hunk 1]
```diff
@@ -57,7 +57,7 @@ func (archiver *RepoArchiver) RelativePath() (string, error) {
 		return "", err
 	}
 
-	return fmt.Sprintf("%s/%s/%s.%s", repo.FullName(), archiver.CommitID[:2], archiver.CommitID, archiver.Type.String()), nil
+	return fmt.Sprintf("%d/%s/%s.%s", repo.ID, archiver.CommitID[:2], archiver.CommitID, archiver.Type.String()), nil
```
Comment (zeripath) [inline models/repo_archiver.go]: ~~Why this change?~~ -- ah I understand.

You don't need to load the repo anymore and can just use the archiver.RepoID unless you really want to check if the repo is still extant.

**Review by noerw — APPROVED** [review]
