### PR TITLE
Fix CSV diff for added/deleted files

### LINKED ISSUE #21184: CSV diff: unable to load file from base commit
### Description

Creating a new CSV file as part of a pull request doesn't display the files content in the PRs `Files changed` tab:

https://try.gitea.io/otbutz99/test/pulls/1/files

The file is valid and renders just fine if viewed directly:

https://try.gitea.io/otbutz99/test/src/commit/988460b06f64270788a9f30ed02947e4ab1e6f5a/SampleCSVFile_11kb.csv

The CSV diff works fine for me if the content of the CSV is just changed in the PR:

https://try.gitea.io/otbutz99/test/pulls/2/files

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Release binary via systemd

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by KN4CK3R**
Fixes #21184
Regression of #19552

Instead of using `GetBlobByPath` I use the already existing instances.

We need more information from #19530 if that error is still present.

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]
looks good, and the comment is clear.

**Review by lafriks — APPROVED** [review]

File: routers/web/repo/compare.go [hunk 1]
```diff
@@ -138,28 +138,28 @@ func setCsvCompareContext(ctx *context.Context) {
...
-			return CsvDiffResult{nil, err.Error()}
-		}
 		if err != nil {
-			log.Error("CreateCsvDiff error whilst creating headReader from file %s in commit %s in %s: %v", diffFile.Name, headCommit.ID.String(), ctx.Repo.Repository.Name, err)
-			return CsvDiffResult{nil, "unable to load file from head commit"}
+			if err == errTooLarge {
+				return CsvDiffResult{nil, err.Error()}
+			}
+			log.Error("error whilst creating csv.Reader from file %s in head commit %s in %s: %v", diffFile.Name, headBlob.ID.String(), ctx.Repo.Repository.Name, err)
+			return CsvDiffResult{nil, "unable to load file"}
```
Comment (delvh) [inline routers/web/repo/compare.go:162]: I think it might be beneficial to extract this block into one common function taking
`ctx context.Context, relativePath string, blob *git.blob, commitType string`,
and then calling it once with
`ctx, diffFile.OldName, baseBlob, "base"`
and once with
`ctx, diffFile.Name, headBlob, "head"`

Comment (wxiaoguang) [reply routers/web/repo/compare.go:162]: As a bug fix, I think current approach is also clear and readable.

**Comment by wxiaoguang** [comment]
Backport for 1.17: 
* #21193
