### PR TITLE
Use native go method to get current user rather than environment variable

### LINKED ISSUE #1640: `CurrentUsername` is not always reliable
- Gitea version (or commit ref): 1.1.0
- Git version: 2.1.4
- Operating system: Bananian (based on Debian Jessie)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
This is an issue [existing with Gogs as well](https://github.com/gogits/gogs/issues/3948) (but not considered an issue by Unknwon):

When starting *Gitea* via e.g. `init.d` using `start-stop-daemon` (defining the correct user/group), I get the following error:

    [...s/setting/setting.go:801 NewContext()] [E] Expect user 'git' but current user is: root

Took me a while to figure (and only the linked Gogs issue brought me on the right path): the environment variable `$USER` still points to `root`, though `id -un` as well as `whoami` indicate the script is running under the correct user (i.e. `git:git`). I've worked around that using a shell script, prefixing the `gitea web` command by a line stating `USER=$(id -un)` – but shouldn't Gitea figure that itself? Some other users might give up before figuring :)

And while on it: is there a way to tell Gitea it should run in "daemon mode" instead of "in foreground" – other than using `&`?

### PR DESCRIPTION
**Pull request by SagePtr**
Fixes #1640, #4894

Native "os/user" go package has good function to retrieve current user, rather than relying on USER environment variable.

If getting current user doesn't work on target OS (for example, not yet implemented for it) - it falls back to old implementation with environment variables.

Unit test also changed, old one won't work because USER environment variable spoofing doesn't work anymore (unless os/user is not implemented for OS under which tests are run), now it just compares CurrentUser() with `whoami` command output (skipped on Windows where whoami behaves different way).

For Windows OS with "domain\username" format, only second part (username) is returned to match previous behavior and trim unnecessary prefix.

### CODE REVIEW

**Review by adelowo — APPROVED** [review]

**Comment by lafriks** [comment]
Blocked until 1.6.0-rc1 is released

File: modules/user/user_test.go [hunk 1]
```diff
@@ -2,21 +2,40 @@ package user
...
-	if user != "foobar" {
-		t.Errorf("expected foobar as user, got: %s", user)
+	if len(user) <= 0 {
+		t.Errorf("expected non-empty user, got: %s", user)
 	}
-
-	os.Setenv("USER", "gitea")
+	// Windows whoami is weird, so just skip remaining tests
+	if runtime.GOOS == "windows" {
+		return
```
Comment (sapk) [inline modules/user/user_test.go]: Please use t.Skip in place of return with some explaination like the comment two line before.

**Review by sapk — CHANGES_REQUESTED** [review]
Looks good just need a little change.

**Review by lafriks — APPROVED** [review]

**Review by sapk — APPROVED** [review]
