### PR TITLE
Handle insecure and ports in go get

### LINKED ISSUE #6985: Not able to go get a repository with non-80 port
- Gitea version (or commit ref): 1.8.1
- Git version: 2.17.1
- Operating system: Xubuntu 19.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
According to the [gogs issue tracker](https://github.com/gogs/gogs/issues/5305) this issue has been fixed there, but apparently it is still present in gitea.

In my case gitea is running on port 13000 and trying to **go get** my golang package:
```shell
go get -v 192.168.1.66:13000/my_user_name/my_golang_repo
```
but got the following error:

unrecognized import path "192.168.1.66:13000/my_user_name/my_golang_repo" (parse https://192.168.1.66:13000/my_user_name/my_golang_repo?go-get=1: no go-import meta tags (meta tag 192.168.1.66/my_user_name/my_golang_repo did not match import path 192.168.1.66:13000/my_user_name/my_golang_repo))

### PR DESCRIPTION
**Pull request by zeripath**
If a gitea running on non-standard port is listed as the location for a go mod file, go will fail to get it as the port is not listed and for HTTP the --insecure flag is not set. This PR applies these changes.

Fixes #6985 

Also fixes a similar unreported bug in url.IsExternalURL on non-standard ports.

### CODE REVIEW

File: modules/context/repo.go [hunk 1]
```diff
@@ -188,7 +188,11 @@ func RetrieveBaseRepo(ctx *Context, repo *models.Repository) {
 
 // ComposeGoGetImport returns go-get-import meta content.
 func ComposeGoGetImport(owner, repo string) string {
-	return path.Join(setting.Domain, setting.AppSubURL, url.PathEscape(owner), url.PathEscape(repo))
+	host := setting.Domain
+	if (setting.Protocol == setting.HTTP && setting.HTTPPort != "80") || (setting.Protocol == setting.HTTPS && setting.HTTPPort != "443") {
```
Comment (lafriks) [inline modules/context/repo.go]: If Gitea is running behind reverse proxy this will be incorrect imho

**Review by lafriks — CHANGES_REQUESTED** [review]

File: modules/context/repo.go (hunk 1 above)
Comment (zeripath) [reply modules/context/repo.go]: So you think we should just use url.Parse(setting.AppURL) and grab it from there? (And similarly below?)

Comment (zeripath) [reply modules/context/repo.go]: No I knew I'd checked this:

https://github.com/go-gitea/gitea/blob/355ab0c62c1d58200d68e30d112db398ea00297a/modules/setting/setting.go#L583-L592

This will be updated with the correct host from the AppURL

File: modules/context/context.go [hunk 2]
```diff
@@ -257,6 +257,11 @@ func Contexter() macaron.Handler {
 				branchName = repo.DefaultBranch
 			}
 			prefix := setting.AppURL + path.Join(url.PathEscape(ownerName), url.PathEscape(repoName), "src", "branch", util.PathEscapeSegments(branchName))
+
+			insecure := ""
+			if setting.Protocol == setting.HTTP {
```
Comment (lunny) [inline modules/context/context.go]: As @lafriks said, gitea maybe behind a proxy.

**Review by lunny — CHANGES_REQUESTED** [review]

File: modules/context/repo.go (hunk 1 above)
Comment (zeripath) [reply modules/context/repo.go]: OK, I think setting.Protocol can't necessary be trusted to be updated - therefore I've switched to parsing the AppURL.

**Review by lunny — APPROVED** [review]

File: modules/context/context.go (hunk 2 above)
Comment (zeripath) [reply modules/context/context.go]: OK, Although setting.Domain is updated with the correct host, I think setting.Protocol can't necessary be trusted to be updated - therefore I've switched to parsing the AppURL.

File: modules/util/url.go [hunk 3]
```diff
@@ -52,7 +52,11 @@ func IsExternalURL(rawURL string) bool {
 	if err != nil {
 		return true
 	}
-	if len(parsed.Host) != 0 && strings.Replace(parsed.Host, "www.", "", 1) != strings.Replace(setting.Domain, "www.", "", 1) {
+	host := setting.Domain
```
Comment (lafriks) [inline modules/util/url.go]: Shouldn't this also use parsed root url?

Comment (zeripath) [reply modules/util/url.go]: Yeah. Sorry I was making these changes based on your comments. I'll pop another one up.

Comment (zeripath) [reply modules/util/url.go]:
```suggestion
	appURL, _ := url.Parse(setting.AppURL)
```

File: modules/util/url.go [hunk 4]
```diff
@@ -52,7 +52,11 @@ func IsExternalURL(rawURL string) bool {
...
+	if (setting.Protocol == setting.HTTP && setting.HTTPPort != "80") || (setting.Protocol == setting.HTTPS && setting.HTTPPort != "443") {
```
Comment (zeripath) [inline modules/util/url.go]:
```suggestion
```

File: modules/util/url.go [hunk 5]
```diff
@@ -52,7 +52,11 @@ func IsExternalURL(rawURL string) bool {
...
+		host += ":" + setting.HTTPPort
```
Comment (zeripath) [inline modules/util/url.go]:
```suggestion
```

File: modules/util/url.go [hunk 6]
```diff
@@ -52,7 +52,11 @@ func IsExternalURL(rawURL string) bool {
...
+	}
```
Comment (zeripath) [inline modules/util/url.go]:
```suggestion
```

File: modules/util/url.go [hunk 7]
```diff
@@ -52,7 +52,11 @@ func IsExternalURL(rawURL string) bool {
...
+	if len(parsed.Host) != 0 && strings.Replace(parsed.Host, "www.", "", 1) != strings.Replace(host, "www.", "", 1) {
```
Comment (zeripath) [inline modules/util/url.go]:
```suggestion
	if len(parsed.Host) != 0 && strings.Replace(parsed.Host, "www.", "", 1) != strings.Replace(appURL.Host, "www.", "", 1) {
```

**Review by lafriks — APPROVED** [review]
