### PR TITLE
Fix WebAuthn error checking

### LINKED ISSUE #36216: WebAuthn failure on HTTP instance with a custom domain (again)
### Description

I updated gitea for windows from 1.25.2 to 1.25.3. It works fine, but I see a big ugly error message at the login screen, see screenshot. The error is the same as in this issue:
https://github.com/go-gitea/gitea/issues/33615

Gitea is running in my "windows server" (it is only a headless windows 10) under myserver:3001. The error goes away when I access it using localhost:3001

I have no login for the Gitea demo site, so I can't reproduce it on this demo site.

As far as I know I am not using passkey or WebAuthn.

My use case involves accessing Gitea remotely through WireGuard VPN, which connects me to my home network. Once connected, I access Gitea by using myserver:3001 (from my Android). Using localhost is not an option in my case since the entire purpose is to be able to access Gitea from any device, after establishing a VPN connection to my home network.

Config:
[server]
SSH_DOMAIN = localhost
PROTOCOL = http
DOMAIN = myserver
HTTP_PORT = 3001
APP_DATA_PATH = D:\myuser\Einstellungen\Gitea\data
DISABLE_SSH = true
LFS_START_SERVER = true
LFS_JWT_SECRET = some-text
OFFLINE_MODE = true
LANDING_PAGE = login

### Gitea Version

1.25.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

-

### Screenshots

Image

### Git Version

2.52.0

### Operating System

Windows 10

### How are you running Gitea?

D:\path\to\Gitea\gitea.exe --config D:\myuser\Einstellungen\Gitea\custom\conf\app.ini

### Database

SQLite

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/36216

Now `detectWebAuthnSupport` returns the error type and lets the caller decide whether they call `webAuthnError` and show the error. It no longer shows the error during page load when the user has not even interacted with the feature.

The bug affects all users on HTTP, so I think a quick fix release for this might be good.

### CODE REVIEW

**Comment by silverwind** [comment]
I have tested and passkey login still works. Errors also display as expected when I do not provide a passkey.

File: web_src/js/features/user-auth-webauthn.ts [hunk 1]
```diff
@@ -194,25 +195,26 @@ function webAuthnError(errorType: string, message:string = '') {
   showElem('#webauthn-error');
 }
 
-function detectWebAuthnSupport() {
+/** Returns the error type or the empty string when there was no error. */
```
Comment (delvh) [inline web_src/js/features/user-auth-webauthn.ts]:
```suggestion
/**
  * Returns the error type or the empty string when there was no error.
  * The return value is one of the possible values for the `data-webauthn-error-msg` attribute on the webauthn error message element 
  */
```

**Review by delvh — APPROVED** [review]

File: web_src/js/features/user-auth-webauthn.ts (hunk 1 above)
Comment (silverwind) [reply web_src/js/features/user-auth-webauthn.ts]: Seems a bit over the top because there are other places that use these error strings. I think we can make the code self-documenting by adding a `ErrorType` type and documenting it there.

Comment (silverwind) [reply web_src/js/features/user-auth-webauthn.ts]: Better fix in https://github.com/go-gitea/gitea/pull/36219/commits/67a5b9238737cad7969e59ae001d9d4d306e376e with a union type.

**Review by lafriks — APPROVED** [review]
