### PR TITLE
Check user/org repo limit instead of doer

### LINKED ISSUE #30011: UI preventing org repo creation as well if user org limit is reached
## Scenario
- On our instance we have `MAX_CREATION_LIMIT = 0` to prevent random new users from spamming our instance
- There is an org which has a few members, which is being used for a collaborative project. These members should only be able to create repos inside this org, but not under their user account.
- Users have been put into a team `Dev` which has `Create repositories` enabled

## Problem
- On the repo create page, the submit button `Create Repository` is disabled in case `CanCreateRepo == false`: https://github.com/go-gitea/gitea/blob/5c91d7920f4aff08768e274269e211e926aa3d36/templates/repo/create.tmpl#L212
- `CanCreateRepo` checks whether the user already has too many personal repos: https://github.com/go-gitea/gitea/blob/5c91d7920f4aff08768e274269e211e926aa3d36/models/user/user.go#L240-L251
- But the submit button will be disabled for all available repo owners; **Personal and also Orgs!**
- This means the **UI will not allow users to create org repos** even though they have the `Create repositories` permission in their org!
- EDIT: This problem also affects repos which are created from migrations (this however is a backend issue!)

## Solutions
- This is only a UI bug, the backend validation works as expected (I have tested this by removing the previously mentioned disable check from the template to force the button to be always enabled)
- The `CanCreateRepo` value should only influence creation of a personal repo
- Repo limit of the org is only checked after the form is submitted, this would be a good quick-fix for this issue (removing the disabled button check and the error banner from the template)
- For a long term solution we could hide the personal user account in the owners list the same way orgs are hidden when their limit is reached. This would make the disabled submit button and the banner completely obsolete, as the user is forced to select an owner that is allowed to have more repos created

Note that I was not able to reproduce the issue on the demo instance, because there is no repo count limit and also it seems like you can't create orgs there..

## Screenshots
Trying to create a new repo `testrepo45` under `testorg` organization, note the banner telling me there is a limit:
Screenshot from 2024-03-22 23-19-41

Submit button is disabled:
Screenshot from 2024-03-22 23-19-29

Repo create works anyway when enabling the submit button by hand:
Screenshot from 2024-03-22 23-19-56

## Gitea Version
v1.21.9

### PR DESCRIPTION
**Pull request by DrMaxNix**
This PR tries to finally fix the bug mentioned in #30011 and #15504, where the user repo limit is checked when creating a repo in an organization.

Fix #30011

---

Please verify that this change makes sense, I don't know a lot about the gitea codebase, so I cannot overlook the security implications that this change will have for other parts of the code.

### CODE REVIEW

File: models/repo/update.go [hunk 1]
```diff
@@ -113,7 +113,7 @@ func (err ErrRepoFilesAlreadyExist) Unwrap() error {
 
 // CheckCreateRepository check if could created a repository
 func CheckCreateRepository(ctx context.Context, doer, u *user_model.User, name string, overwriteOrAdopt bool) error {
-	if !doer.CanCreateRepo() {
+	if !u.CanCreateRepo() {
```
Comment (TheFox0x7) [inline models/repo/update.go]:
```suggestion
	if !doer.IsAdmin && !u.CanCreateRepo() {
```
Admin is exempt from the limit checks.

**Review by TheFox0x7 — COMMENTED** [review]
Change looks reasonable to me, though I'm also not an expert.

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
I think we need a complete fix like this: https://github.com/go-gitea/gitea/pull/34147/commits/8b48d863364d41f74c51b6035adbdaec51252673

Use `CanCreateRepoIn` , it should be clearer than before and won't be abused.

**Comment by wxiaoguang** [comment]
And let's add some tests: https://github.com/go-gitea/gitea/pull/34147/commits/c654ade60e718018806ef68fa136f2a61208404c

File: models/user/user.go [hunk 2]
```diff
@@ -247,19 +247,19 @@ func (u *User) MaxCreationLimit() int {
 	return u.MaxRepoCreation
 }
 
-// CanCreateRepo returns if user login can create a repository
-// NOTE: functions calling this assume a failure due to repository count limit; if new checks are added, those functions should be revised
-func (u *User) CanCreateRepo() bool {
+// CanCreateRepoIn checks whether the doer(u) can create a repository in the owner
+func (u *User) CanCreateRepoIn(owner *User) bool {
```
Comment (wxiaoguang) [inline models/user/user.go:252]:
```suggestion
// NOTE: functions calling this assume a failure due to repository count limit; it ONLY checks the repo number LIMIT, if new checks are added, those functions should be revised
func (u *User) CanCreateRepoIn(owner *User) bool {
```

File: models/user/user.go [hunk 3]
```diff
@@ -272,13 +273,11 @@ func (u *User) CanEditGitHook() bool {
 	return !setting.DisableGitHooks && (u.IsAdmin || u.AllowGitHook)
 }
 
-// CanForkRepo returns if user login can fork a repository
-// It checks especially that the user can create repos, and potentially more
-func (u *User) CanForkRepo() bool {
+func (u *User) CanForkRepoIn(owner *User) bool {
```
Comment (wxiaoguang) [inline models/user/user.go:277]:
```suggestion
// CanForkRepoIn ONLY checks repository count limit
func (u *User) CanForkRepoIn(owner *User) bool {
```

**Review by lunny — APPROVED** [review]

File: services/repository/create.go [hunk 4]
```diff
@@ -267,6 +267,7 @@ func CreateRepositoryDirectly(ctx context.Context, doer, u *user_model.User, opt
 		}
 	}()
 
+
```
Comment (wxiaoguang) [inline services/repository/create.go]:
```suggestion
```

File: services/repository/adopt.go [hunk 5]
```diff
@@ -103,9 +103,7 @@ func AdoptRepository(ctx context.Context, doer, u *user_model.User, opts CreateR
 	if err = repo_model.UpdateRepositoryCols(ctx, repo, "status"); err != nil {
 		return nil, fmt.Errorf("UpdateRepositoryCols: %w", err)
 	}
-
-	notify_service.AdoptRepository(ctx, doer, u, repo)
-
+	notify_service.AdoptRepository(ctx, doer, owner, repo)
```
Comment (wxiaoguang) [inline services/repository/adopt.go:107]:
```suggestion

	notify_service.AdoptRepository(ctx, doer, owner, repo)

```

**Review by wxiaoguang — COMMENTED** [review]
fix merge conflict
