### PR TITLE
Fix topics deleted via API not being deleted in org page

### LINKED ISSUE #24820: [Bug] WebUI: Topics get removed from org repo, but not from organization view
### Description

There seems to be a bug with repo topics in organizations.

I make api calls to add and remove a topic, in our case the pacman repo target.
This all works fine for the repo, but the organization doesn't notice the changes. 
It only does if I manually do a "done" edit of the repo's topics in the UI.

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

[](https://postimg.cc/zyYhkZC8)

[](https://postimg.cc/N5m9FJWV)

### Git Version

2.40.1

### Operating System

artix linux

### How are you running Gitea?

Gitea runs as server instance on bare metal server.
We build the gitea package with a package pipeline, essentially arch linux package minus systemd.

### Database

MySQL

### PR DESCRIPTION
**Pull request by yardenshoham**
The topics are saved in the repo_topic table with a repoID key. They are also saved directly in the repository table.

Before this PR, only `AddTopic` and `SaveTopics` made sure the `topics` field in the repository field was synced with the repo_topic table.

This PR makes sure `GenerateTopics` and `DeleteTopic` also sync the `topics` in the repository table.

`RemoveTopicsFromRepo` doesn't need to sync the data as it is only used to delete a repository.

- Fixes #24820

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]
good catch

File: models/repo/topic.go [hunk 1]
```diff
@@ -370,5 +357,23 @@ func GenerateTopics(ctx context.Context, templateRepo, generateRepo *Repository)
 			return err
 		}
 	}
+
+	return syncTopicsInRepository(db.GetEngine(ctx), generateRepo.ID)
+}
+
+// syncTopicsInRepository makes sure topics in the topics table are copied into the topics field of the repository
+func syncTopicsInRepository(sess db.Engine, repoID int64) error {
```
Comment (lunny) [inline models/repo/topic.go:365]: How about using ctx as the first parameter?

Comment (yardenshoham) [reply models/repo/topic.go:365]: In some places it's a part of a transaction and some places not

**Review by delvh — APPROVED** [review]
