### PR TITLE
Fix various bugs

### LINKED ISSUE #35768: Panic during startup
(Just record, haven't got time to look into it)

```
2025/10/29 13:57:19 .../actions/notifier_helper.go:165:notify() [W] Ref of event "workflow_run" is empty, will fall back to the default branch
2025/10/29 13:57:19 .../queue/workerqueue.go:250:NewWorkerPoolQueueWithContext.1.1() [E] Recovered from panic in queue "mail" handler: runtime error: index out of range [0] with length 0
/Users/xiaoguang/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.3.darwin-arm64/src/runtime/panic.go:115 (0x10450f48f)
	goPanicIndex: panic(boundsError{x: int64(x), signed: true, y: y, code: boundsIndex})
/Users/xiaoguang/work/gitea/services/mailer/sender/sender.go:33 (0x1069e9b9b)
	send: if err := sender.Send(froms[0].Address, to, m); err != nil {
/Users/xiaoguang/work/gitea/services/mailer/mailer.go:52 (0x106a020e7)
	NewContext.func1: if err := sender_service.Send(sender, msg); err != nil {
/Users/xiaoguang/work/gitea/modules/queue/workerqueue.go:254 (0x1066b3ed3)
	NewWorkerPoolQueueWithContext[...].func1: return w.origHandler(t...)
/Users/xiaoguang/work/gitea/modules/queue/workergroup.go:103 (0x1066b2643)
	(*WorkerPoolQueue[...]).doWorkerHandle: unhandled := q.safeHandler(batch...)
/Users/xiaoguang/work/gitea/modules/queue/workergroup.go:179 (0x1066b1fe7)
	(*WorkerPoolQueue[...]).doStartNewWorker.func1: q.doWorkerHandle(batch)
/Users/xiaoguang/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.3.darwin-arm64/src/sync/waitgroup.go:239 (0x104561e4f)
	(*WaitGroup).Go.func1: f()
/Users/xiaoguang/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.3.darwin-arm64/src/runtime/asm_arm64.s:1268 (0x10454eed3)
	goexit: MOVD	R0, R0	// NOP
```

### LINKED ISSUE #36051: Wrong extra index url for pypi
Hi!
I guess `--extra-index-url` here:
https://github.com/go-gitea/gitea/blob/a36951aef6361c0ca55cd778fe8811a7dbb4a226/templates/package/content/pypi.tmpl#L7
suppose to be `https://pypi.org/simple` instead of `https://pypi.org/`

### LINKED ISSUE #36064: NPM Package Registry 500 Internal Server Error
### Description

Some troubles with `license` processing...

Get package from registry.npmjs.org:
```
wget https://registry.npmjs.org/dev-null/-/dev-null-0.1.1.tgz
```

a) Publish package above to demo.gitea.com:
```
$ npm publish dev-null-0.1.1.tgz
npm notice
npm notice 📦  dev-null@0.1.1
npm notice Tarball Contents
npm notice 97B .npmignore
npm notice 48B .travis.yml
npm notice 1.1kB LICENSE
npm notice 773B README.md
npm notice 187B examples/devnull.js
npm notice 137B examples/no-devnull.js
npm notice 486B index.js
npm notice 984B package.json
npm notice 486B test/fixtures/number-readable.js
npm notice 687B test/index.js
npm notice Tarball Details
npm notice name: dev-null
npm notice version: 0.1.1
npm notice filename: dev-null-0.1.1.tgz
npm notice package size: 2.4 kB
npm notice unpacked size: 5.0 kB
npm notice shasum: 5a205ce3c2b2ef77b6238d6ba179eb74c6a0e818
npm notice integrity: sha512-nMNZG0zfMgmdv[...]M9kM6RlawPxEQ==
npm notice total files: 10
npm notice
npm notice Publishing to https://demo.gitea.com/api/packages/podsvirov/npm/ with tag latest and default access
npm error code E500
npm error 500 Internal Server Error - PUT https://demo.gitea.com/api/packages/podsvirov/npm/dev-null - internal server error
npm error A complete log of this run can be found in: ~\AppData\Local\npm-cache\_logs\2025-12-01T20_09_36_052Z-debug-0.log
```

b) Publish package above to self-hosted gitea instance:
```
$ npm publish dev-null-0.1.1.tgz
npm notice
npm notice 📦  dev-null@0.1.1
npm notice Tarball Contents
npm notice 97B .npmignore
npm notice 48B .travis.yml
npm notice 1.1kB LICENSE
npm notice 773B README.md
npm notice 187B examples/devnull.js
npm notice 137B examples/no-devnull.js
npm notice 486B index.js
npm notice 984B package.json
npm notice 486B test/fixtures/number-readable.js
npm notice 687B test/index.js
npm notice Tarball Details
npm notice name: dev-null
npm notice version: 0.1.1
npm notice filename: dev-null-0.1.1.tgz
npm notice package size: 2.4 kB
npm notice unpacked size: 5.0 kB
npm notice shasum: 5a205ce3c2b2ef77b6238d6ba179eb74c6a0e818
npm notice integrity: sha512-nMNZG0zfMgmdv[...]M9kM6RlawPxEQ==
npm notice total files: 10
npm notice
npm notice Publishing to https://<my.url>/api/packages/podsvirov/npm/ with tag latest and default access
npm error code E500
npm error 500 Internal Server Error - PUT https://<my.url>/api/packages/podsvirov/npm/dev-null - npm.packageUpload.PackageMetadata: Versions: npm.PackageMetadataVersion.License: ReadString: expects " or n, but found {, error found in #10 byte of ...|license":{"type":"MI|..., bigger context ...|z@gmx.de","url":"http://thlorenz.com"},"license":{"type":"MIT","url":"https://github.com/thlorenz/de|...
npm error A complete log of this run can be found in: ~\AppData\Local\npm-cache\_logs\2025-12-01T19_43_18_249Z-debug-0.log
```

### Gitea Version

1.25.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.52.0

### Operating System

Ubuntu

### How are you running Gitea?

It's being run from docker

### Database

SQLite

### PR DESCRIPTION
**Pull request by wxiaoguang**
* Fix #35768
* Fix #36064
* Fix #36051
* Fix cherry-pick panic
* Make `filePathSanitize` do path cleaning, to avoid potential abuses or low-level mistakes (although the existing code is right).

### CODE REVIEW

File: modules/packages/npm/creator.go [hunk 1]
```diff
@@ -62,7 +62,28 @@ type PackageMetadata struct {
 	Author         User                               `json:"author"`
 	ReadmeFilename string                             `json:"readmeFilename,omitempty"`
 	Users          map[string]bool                    `json:"users,omitempty"`
-	License        string                             `json:"license,omitempty"`
+	License        License                            `json:"license,omitempty"`
+}
+
+type License string
+
+func (l *License) UnmarshalJSON(data []byte) error {
```
Comment (delvh) [inline modules/packages/npm/creator.go:70]: Could there be leading whitespace?

**Review by delvh — APPROVED** [review]

File: modules/packages/npm/creator.go (hunk 1 above)
Comment (wxiaoguang) [reply modules/packages/npm/creator.go:70]: Nope, see other simliar code.

**Review by lunny — APPROVED** [review]

File: services/mailer/sender/sender.go [hunk 2]
```diff
@@ -16,23 +14,17 @@ type Sender interface {
...
-			return err
-		}
 
-		// TODO: implement sending from multiple addresses
-		if err := sender.Send(froms[0].Address, to, m); err != nil {
-			return err
-		}
+	// TODO: implement sending from multiple addresses
+	if len(froms) == 0 {
+		return errors.New("no FROM specified")
```
Comment (wxiaoguang) [inline services/mailer/sender/sender.go:28]:
```suggestion
		// FIXME: no idea why sometimes the "froms" can be empty, need to figure out the root problem
		return errors.New("no FROM specified")
```

File: modules/packages/npm/creator.go [hunk 3]
```diff
@@ -62,7 +62,28 @@ type PackageMetadata struct {
...
+		if err := json.Unmarshal(data, &value); err != nil {
+			return err
+		}
+		*l = License(value)
+	case '{':
+		var values map[string]any
+		if err := json.Unmarshal(data, &values); err != nil {
+			return err
+		}
+		value := values["type"].(string)
```
Comment (wxiaoguang) [inline modules/packages/npm/creator.go]:
```suggestion
		value, _ := values["type"].(string)
```

File: services/mailer/sender/sender.go [hunk 4]
```diff
@@ -16,23 +14,18 @@ type Sender interface {
...
-		}
 
-		// TODO: implement sending from multiple addresses
-		if err := sender.Send(froms[0].Address, to, m); err != nil {
-			return err
-		}
+	// TODO: implement sending from multiple addresses
+	if len(froms) == 0 {
+		// FIXME: no idea why sometimes the "froms" can be empty, need to figure out the root problem
+		return errors.New("no FROM specified")
```
Comment (lunny) [inline services/mailer/sender/sender.go:28]: It would be helpful to log additional trace information about the message content or type so we can identify which kinds of emails trigger this error.

Comment (wxiaoguang) [reply services/mailer/sender/sender.go:28]: Already

image
