### PR TITLE
Fix bug when sort repos on org home page login with non-admin

### LINKED ISSUE #6511: organization repository sort order
- Gitea version (or commit ref): 1.7.2, 28fcbf3 
- Git version:
- Operating system: rhel
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The sort order of organization repositories doesn't work for logged in users.

## Reproduce
- create organization
- add mutliple repos to organization
- go to organization overview
- change sort order, for example switch between alphabetical and revers alphabetical
- log out
- change sort order

https://try.gitea.io/order_issue?sort=reversealphabetically
https://try.gitea.io/order_issue?sort=alphabetically

notice different URLs but same order of repositories

alphabetical
reverse alphabetical

### PR DESCRIPTION
**Pull request by lunny**
Will fix #6511 with integration tests

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

File: integrations/org_test.go [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+
+	"github.com/stretchr/testify/assert"
+)
+
+func TestOrgRepos(t *testing.T) {
+	prepareTestEnv(t)
+
+	var (
+		users = []string{"user1", "user2"}
+		kases = map[string][]string{
```
Comment (mrsdizzie) [inline integrations/org_test.go]:
```suggestion
		cases = map[string][]string{
```

File: integrations/org_test.go [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+			"alphabetically":        {"repo21", "repo3", "repo5"},
+			"reversealphabetically": {"repo5", "repo3", "repo21"},
+		}
+	)
+
+	for _, user := range users {
+		t.Run(user, func(t *testing.T) {
+			session := loginUser(t, user)
+			for sortBy, repos := range kases {
```
Comment (mrsdizzie) [inline integrations/org_test.go]:
```suggestion
			for sortBy, repos := range cases {
```

**Review by mrsdizzie — CHANGES_REQUESTED** [review]

**Comment by lunny** [comment]
@mrsdizzie done.

**Review by mrsdizzie — APPROVED** [review]
