### PR TITLE
Fix shutdown waitgroup panic

### LINKED ISSUE #35468: Ctrl +C shudown Gitea caused WaitGroup panic
### Description

Ctrl +C shutdown Gitea caused panic

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

local development env

### Database

None

### LINKED ISSUE #35551: [no logger writer]: Queue "repo-archive" stops running
### Description

When shutdown Gitea, the log displayed `no logger writer`.

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

local dev

### Database

None

### LINKED ISSUE #35559: Ctrl+C result in panic
### Description

```log
^C2025/09/30 21:10:08 .../graceful/manager_unix.go:141:(*Manager).handleSignals() [W] PID 64524. Received SIGINT. Shutting down...
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "repo_stats_update" is shutting down
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "repo_license_updater" is shutting down
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-43: Queue: repo_stats_update
2025/09/30 21:10:08 .../graceful/manager_unix.go:154:(*Manager).handleSignals() [W] PID: 64524. Background context for manager closed - context canceled - Shutting down...
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "push_update" is shutting down
2025/09/30 21:10:08 modules/graceful/server.go:156:(*Server).Serve() [D] Waiting for connections to finish... (PID: 64524)
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-35: Queue: repo_license_updater
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-36: Queue: push_update
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "webhook_sender" is shutting down
2025/09/30 21:10:08 .../queue/workergroup.go:191:(*WorkerPoolQueue).doStartNewWorker.1() [D] Queue "push_update" stops idle worker
2025/09/30 21:10:08 .../graceful/server_hooks.go:46:(*Server).doShutdown() [I] PID: 64524 Listener ([::]:3000) closed.
2025/09/30 21:10:08 .../queue/workergroup.go:191:(*WorkerPoolQueue).doStartNewWorker.1() [D] Queue "repo_license_updater" stops idle worker
2025/09/30 21:10:08 .../graceful/server_hooks.go:63:(*Server).doHammer() [W] Forcefully shutting down parent
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "push_update" stops running
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "repo_license_updater" stops running
2025/09/30 21:10:08 .../graceful/server_hooks.go:57:(*Server).doHammer.1() [E] WaitGroup at 0: Error: sync: negative WaitGroup counter
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "pr_patch_checker" is shutting down
2025/09/30 21:10:08 .../src/runtime/panic.go:783:gopanic() [D] Serve() returning... (PID: 64524)
2025/09/30 21:10:08 .../queue/workergroup.go:191:(*WorkerPoolQueue).doStartNewWorker.1() [D] Queue "repo_stats_update" stops idle worker
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-47: Queue: pr_patch_checker
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-7: Graceful: HandleSignals
2025/09/30 21:10:08 .../queue/workergroup.go:191:(*WorkerPoolQueue).doStartNewWorker.1() [D] Queue "webhook_sender" stops idle worker
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a8-21: Web: Gitea Server
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "repo_stats_update" stops running
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "actions_ready_job" is shutting down
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-44: Queue: mirror
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "notification-service" is shutting down
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-50: Service: EventSource
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a8: Queue: actions_ready_job
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-48: Queue: pr_auto_merge
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-31: Queue: notification-service
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "actions_ready_job" stops running
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "task" is shutting down
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-49: Queue: task
2025/09/30 21:10:08 .../queue/workergroup.go:191:(*WorkerPoolQueue).doStartNewWorker.1() [D] Queue "notification-service" stops idle worker
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "notification-service" stops running
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-41: Queue: code_indexer
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "task" stops running
2025/09/30 21:10:08 .../queue/workergroup.go:191:(*WorkerPoolQueue).doStartNewWorker.1() [D] Queue "code_indexer" stops idle worker
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "repo-archive" is shutting down
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-32: Queue: repo-archive
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "repo-archive" stops running
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "code_indexer" is shutting down
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "code_indexer" stops running
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-45: Queue: webhook_sender
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-30: Queue: mail
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-34: Queue: tag_sync
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "branch_sync" is shutting down
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-39: Queue: issue_indexer
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-37: Queue: branch_sync
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "branch_sync" stops running
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a8-2: Service: Cron
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "issue_indexer" is shutting down
2025/09/30 21:10:08 .../queue/workergroup.go:191:(*WorkerPoolQueue).doStartNewWorker.1() [D] Queue "mail" stops idle worker
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "mirror" is shutting down
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "mail" is shutting down
2025/09/30 21:10:08 .../queue/workergroup.go:191:(*WorkerPoolQueue).doStartNewWorker.1() [D] Queue "pr_patch_checker" stops idle worker
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "pr_auto_merge" is shutting down
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "pr_patch_checker" stops running
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "webhook_sender" stops running
2025/09/30 21:10:08 .../queue/workergroup.go:345:(*WorkerPoolQueue).doRun() [D] Queue "tag_sync" is shutting down
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a8-17: Asset Local FileSystem Watcher
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-24: Asset Local FileSystem Watcher
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a7-29: Asset Local FileSystem Watcher
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca6a8-18: Service: SlowQueryDetector
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "issue_indexer" stops running
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "mail" stops running
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "pr_auto_merge" stops running
2025/09/30 21:10:08 .../queue/workergroup.go:346:(*WorkerPoolQueue).doRun() [D] Queue "tag_sync" stops running
2025/09/30 21:10:08 HTTPRequest [T] router: completed GET /user/events for [::1]:54218, 200 OK in 459552.0ms @ events/events.go:18(events.Events)
2025/09/30 21:10:08 modules/process/manager.go:226:(*Manager).remove() [T] Done 68dca7d4-39: HTTP: GET /user/events
2025/09/30 21:10:08 modules/graceful/server.go:275:(*wrappedConn).Close.1() [W] Panic during connection close! sync: negative WaitGroup counter. Likely there has been a deadlocked request which has been released by forced shutdown.
2025/09/30 21:10:08 cmd/web.go:251:runWeb.1() [F] PANIC: sync: WaitGroup is reused before previous Wait has returned
/Users/xxxx/sdk/go1.25.1/src/sync/waitgroup.go:208 (0x100e04dcb)
	(*WaitGroup).Wait: panic("sync: WaitGroup is reused before previous Wait has returned")
/Users/xxxx/data/Projects/gitea/gitea/modules/graceful/server.go:157 (0x1016eea4b)
	(*Server).Serve: srv.wg.Wait()
/Users/xxxx/data/Projects/gitea/gitea/modules/graceful/server.go:95 (0x1016ee52f)
	(*Server).ListenAndServe: return srv.Serve(serve)
/Users/xxxx/data/Projects/gitea/gitea/modules/graceful/server_http.go:29 (0x1016ef93b)
	HTTPListenAndServe: return server.ListenAndServe(lHandler, useProxyProtocol)
/Users/xxxx/data/Projects/gitea/gitea/cmd/web_graceful.go:18 (0x1030c293f)
	runHTTP: return graceful.HTTPListenAndServe(network, listenAddr, name, m, useProxyProtocol)
/Users/xxxx/data/Projects/gitea/gitea/cmd/web.go:344 (0x1030c290c)
	listen: err = runHTTP("tcp", listenAddr, "Web", m, setting.UseProxyProtocol)
/Users/xxxx/data/Projects/gitea/gitea/cmd/web.go:231 (0x1030c1da7)
	serveInstalled: err := listen(webRoutes, true)
/Users/xxxx/data/Projects/gitea/gitea/cmd/web.go:286 (0x1030c215f)
	runWeb: return serveInstalled(cmd)
/Users/xxxx/go/pkg/mod/github.com/urfave/cli/v3@v3.4.1/command_run.go:344 (0x101dea91f)
	(*Command).run: if err := cmd.Action(ctx, cmd); err != nil {
/Users/xxxx/go/pkg/mod/github.com/urfave/cli/v3@v3.4.1/command_run.go:278 (0x101dea377)
	(*Command).run: ctx, err = subCmd.run(ctx, cmd.Args().Slice())
/Users/xxxx/go/pkg/mod/github.com/urfave/cli/v3@v3.4.1/command_run.go:94 (0x1030bb247)
	(*Command).Run: _, deferErr = cmd.run(ctx, osArgs)
/Users/xxxx/data/Projects/gitea/gitea/cmd/main.go:154 (0x1030bb228)
	RunMainApp: err := app.Run(ctx, args)
/Users/xxxx/data/Projects/gitea/gitea/main.go:46 (0x1030f6c57)
	main: _ = cmd.RunMainApp(app, os.Args...) // all errors should have been handled by the RunMainApp
/Users/xxxx/sdk/go1.25.1/src/runtime/proc.go:285 (0x100dba7e7)
	main: fn()
/Users/xxxx/sdk/go1.25.1/src/runtime/asm_arm64.s:1268 (0x100df8ca3)
	goexit: MOVD	R0, R0	// NOP
```

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

local env

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
This PR fixes a panic issue in the WaitGroup that occurs when Gitea is shut down using Ctrl+C.
It ensures that all active connection pointers in the server are properly tracked and forcibly closed when the hammer shutdown is invoked.
The process remains graceful — the normal shutdown sequence runs before the hammer is triggered, and existing connections are given a timeout period to complete gracefully.

This PR also fixes `no logger writer` problem. Now the log close will only be invoked when the command exit.

- Fixes #35468
- Fixes #35551
- Fixes #35559
- Replace #35578

### CODE REVIEW

**Comment by wxiaoguang** [comment]
1. `Fixes #35648` seems to be a wrong reference, 35648 is for OAuth2
2. I don't think it's right to keep doing "// Check for shutdown signal during startup", the "shutdown" can occur exactly after your check, then the check doesn't really help anything.
3. ~~For the connections, if you decided to use "connections map", what does `wl.server.wg.Add(1)` do? Does it still make sense?~~
    * `wg.Wait` is used for waiting for the open connections, so it is still useful (BUT not right)
    * Maybe the Add-After-Wait data-race still exists (much more rare than before, better than before): doShutdown -> setState(stateShuttingDown) -> new conn comes -> listener.Close() -> wg.Wait() -> new conn wg.Add()

**Comment by lunny** [comment]
> 1. `Fixes #35648` seems to be a wrong reference, 35648 is for OAuth2
> 2. I don't think it's right to keep doing "// Check for shutdown signal during startup", the "shutdown" can occur exactly after your check, then the check doesn't really help anything.
> 3. ~For the connections, if you decided to use "connections map", what does `wl.server.wg.Add(1)` do? Does it still make sense?~
>    
>    * `wg.Wait` is used for waiting for the open connections, so it is still useful
>    * Maybe the Add-After-Wait data-race still exists (much more rare than before, better than before): doShutdown -> setState(stateShuttingDown) -> new conn comes -> listener.Close() -> wg.Wait() -> new conn wg.Add()

- 1 is a typo that it should be #35468 
- The checking could check the situation ctrl+c before web listening. I can try to reduce them.
- Once listener closed, there should be no new connection coming.

File: modules/graceful/server.go [hunk 1]
```diff
@@ -178,6 +181,21 @@ func (srv *Server) setState(st state) {
...
+	srv.connectionsLock.Lock()
+	connections := make([]*wrappedConn, 0, len(srv.connections))
+	for conn := range srv.connections {
+		connections = append(connections, conn)
+	}
+	srv.connectionsLock.Unlock()
+
+	// Close all connections outside the lock to avoid deadlock
+	for _, conn := range connections {
+		_ = conn.Conn.Close() // Force close the underlying connection
```
Comment (wxiaoguang) [inline modules/graceful/server.go]: Not right, you can't close "underlying", you must close the conn itself.

File: main.go [hunk 2]
```diff
@@ -44,7 +44,6 @@ func main() {
 	}
 	app := cmd.NewMainApp(cmd.AppVersion{Version: Version, Extra: formatBuiltWith()})
 	_ = cmd.RunMainApp(app, os.Args...) // all errors should have been handled by the RunMainApp
-	log.GetManager().Close()
```
Comment (wxiaoguang) [inline main.go:47]: I don't think it is right. Are you sure `cli.OsExiter` is always called?

**Comment by wxiaoguang** [comment]
> The checking could check the situation ctrl+c before web listening. I can try to reduce them.

You can reproduce doesn't mean the fix is right. 


> Once listener closed, there should be no new connection coming.

I am showing the "DATA-RACE". "listener.Close" and "Accept" are in different threads.

Anyway, talk is cheap, I showed you my code.

**Comment by wxiaoguang** [comment]
> This PR also fixes `no logger writer` problem. Now the log close will only be invoked when the command exit.
> Fixes [no logger writer]: Queue "repo-archive" stops running #35551

Your change is also wrong. I have told you the root problem and it is not easy to fix. https://github.com/go-gitea/gitea/issues/35551#issuecomment-3356896897

**Review by Zettat123 — APPROVED** [review]

File: modules/graceful/server.go [hunk 3]
```diff
@@ -178,63 +179,87 @@ func (srv *Server) setState(st state) {
...
+
+// closeAllConnections forcefully closes all active connections
+func (srv *Server) closeAllConnections() {
+	srv.lock.Lock()
+	if srv.connCounter > 0 {
+		log.Warn("After graceful shutdown period, %d connections are still active. Forcefully close.", srv.connCounter)
+		srv.connCounter = 0 // OS will close all the connections after the process exits, so we just assume there is no active connection now
+	}
+	srv.lock.Unlock()
+	srv.connEmptyCond.Broadcast()
```
Comment (yp05327) [inline modules/graceful/server.go:221]: I’m not familiar with the sync functions, so this is just a question.
Should `Broadcast` be called before `Unlock`?
In the code above, `Broadcast` is always called before `Unlock`.
I asked AI about it, and it said it isn’t safe, so I left this comment.

Comment (wxiaoguang) [reply modules/graceful/server.go:221]: Maybe AI didn't read the Golang doc: https://pkg.go.dev/sync#Cond.Broadcast

Comment (lunny) [reply modules/graceful/server.go:221]: I think @yp05327 means it’s inconsistent because, on line 209, the `Broadcast` function is called before the lock is released.

**Review by yp05327 — APPROVED** [review]

File: modules/graceful/server.go (hunk 3 above)
Comment (wxiaoguang) [reply modules/graceful/server.go:221]: > >  I asked AI about it, and it said it isn’t safe, so I left this comment.
>
> I think @yp05327 means it’s inconsistent because ....

He means `it isn’t safe`, not `inconsistent`

Does "not safe" mean "inconsistent" in your mind?
