### PR TITLE
Fix issue overview for teams

### LINKED ISSUE #19636: Issue totals are wrong when filtering by team
### Description

The issue totals for "Assigned to you", "Created by you" and "Mentioning you" are incorrect in the statistics when filtering on team, when the current filter is "In your repositories".

image

When selecting another filter, they are correct:

image

I recently upgraded from 1.16.4 to 1.16.7, and I believe it may be a regression in #18916.

### Gitea Version

1.16.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

_No response_

### PR DESCRIPTION
**Pull request by Gusted**
- Don't use hacky solution to limit to the correct RepoID's, instead use current code to handle these limits. The existing code is more correct than the hacky solution.
- Resolves #19636

### CODE REVIEW

File: models/issue.go [hunk 1]
```diff
@@ -1348,22 +1348,50 @@ func (opts *IssuesOptions) setupSessionNoLimit(sess *xorm.Session) {
...
-			cond = cond.And(teamUnitsRepoCond(repoIDstr, userID, org.ID, team.ID, unitType)) // special team member repos
+			// If the current user is a admin, it doesn't necesarly mean
+			// it has joined the team, but we still should return all repo's
+			// of that team.
+			isAdmin, err := org.IsOwnedBy(userID)
+			if err != nil {
+				return nil, err
+			}
+			if isAdmin {
+				cond = cond.And(builder.In(repoIDstr,
```
Comment (Gusted) [inline models/issue.go]: I personally don't like if this cause needs to be extracted as I feel this could easily be misused(this doesn't have the check if the user is in the team)

File: models/issue.go [hunk 2]
```diff
@@ -1348,22 +1348,50 @@ func (opts *IssuesOptions) setupSessionNoLimit(sess *xorm.Session) {
...
 	if isPull {
 		unitType = unit.TypePullRequests
 	}
 	if org != nil {
 		if team != nil {
-			cond = cond.And(teamUnitsRepoCond(repoIDstr, userID, org.ID, team.ID, unitType)) // special team member repos
+			// If the current user is a admin, it doesn't necesarly mean
+			// it has joined the team, but we still should return all repo's
+			// of that team.
+			isAdmin, err := org.IsOwnedBy(userID)
```
Comment (lunny) [inline models/issue.go]: This will begin a new db connection that I don't know whether it will affect outside of the function.

Comment (Gusted) [reply models/issue.go]: I dont see another way of checking if this person is a admin of the organization. They should "act" as they are member of the team.

Comment (Gusted) [reply models/issue.go]: Should we inline the SQL that is used by this function?

Comment (6543) [reply models/issue.go]: Yes

Comment (6543) [reply models/issue.go]: Deadlocks are real ;)

**Comment by zeripath** [comment]
There's quite a few IN SELECTs in there and whilst the SQL is correct I'm wondering if we might want to use a few JOINS instead of chains of IN SELECTs - however perhaps we should consider that for another PR.

**Comment by Gusted** [comment]
> There's quite a few IN SELECTs in there and whilst the SQL is correct I'm wondering if we might want to use a few JOINS instead of chains of IN SELECTs - however perhaps we should consider that for another PR.

Feel free to do it. This is a plain copy-paste of the SQL that is otherwise used by the function(`IsOwnedBy`). I already found it a mystery that it worked first-try.

**Comment by lunny** [comment]
> There's quite a few IN SELECTs in there and whilst the SQL is correct I'm wondering if we might want to use a few JOINS instead of chains of IN SELECTs - however perhaps we should consider that for another PR.

A subquery maybe faster than join in modern databases.

**Comment by lunny** [comment]
Could we have a test which could reproduce #19636 ? So that we can avoid repeat the problem.

**Comment by Gusted** [comment]
Added it: https://github.com/go-gitea/gitea/pull/19652/commits/50e61afdc3eb0c2ccc6ccb7955320cb1c78a4f52 

Quite annoying to debug the SQL statements to only realize that rows on the test database is set to `NULL` which conflicts with a real-world-data database.

**Review by wxiaoguang — APPROVED** [review]
Seems good. If I understand correctly, the major change between this one and the code before the last PR is : `Check if the user is in the owner team of the organisation.`, and fixes the bug caused by `opts.RepoCond = models.SearchRepositoryCondition(repoOpts)`

**Comment by Gusted** [comment]
> the major change between this one and the code before the last PR is : `Check if the user is in the owner team of the organisation.`,

Yes, this caused my previous PR to be incorrect, as I thought this was already implemented so I adjusted the code until it had that result(but was actually incorrect).



> and fixes the bug caused by `opts.RepoCond = models.SearchRepositoryCondition(repoOpts)`

Yup, by using the already supported TeamID option.

**Review by lunny — APPROVED** [review]
