### PR TITLE
Lock goth/gothic and Re-attempt OAuth2 registration on login if registration failed at startup (#16564)

### LINKED ISSUE #16096: External login source becomes disabled every now and then
- Gitea version (or commit ref): 1.14.2 (Docker image)
- Git version: (Whatever's included in the Docker image, does not seem to be relevant)
- Operating system: Linux (Docker)
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:

Did not find any mention in log, but this was running at production without debugging logs turned on. Can turn them on for a while if desired.

## Description

For some reason, `is_activated` is sometimes reset to `0` for our primary `login_source`. Although I cannot rule out external causes completely (i.e. some weird issue with MySQL replication) my suspicion is that Gitea makes this change (e.g. when the login source is temporarily unavailable?). 

## Screenshots

This is what `login_source` looks like after the source was deactivated (the first two sources are deliberately disabled, the 'bouncer' login source is the one that becomes disabled every now and then):

image

### PR DESCRIPTION
**Pull request by zeripath**
Backport #16564

This PR has two parts:

* Add locking to goth and gothic calls with a RWMutex

The goth and gothic calls are currently unlocked and thus are a cause of multiple potential races

* Reattempt OAuth2 registration on login if registration failed

If OAuth2 registration fails at startup we currently disable the login_source however an alternative approach could be to reattempt registration on login attempt.
    
Fix #16096

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

File: modules/auth/oauth2/oauth2.go [hunk 1]
```diff
@@ -108,6 +120,9 @@ func RegisterProvider(providerName, providerType, clientID, clientSecret, openID
 	provider, err := createProvider(providerName, providerType, clientID, clientSecret, openIDConnectAutoDiscoveryURL, customURLMapping)
 
 	if err == nil && provider != nil {
+		gothRWMutex.Lock()
```
Comment (lunny) [inline modules/auth/oauth2/oauth2.go:123]: RLock()?

**Review by lunny — APPROVED** [review]

**Comment by zeripath** [comment]
make lgtm work
