### PR TITLE
update git vendor to fix wrong release commit id and add migrations

### LINKED ISSUE #5585: Wrong commit Id after creating a release on existing tag
- Gitea version (or commit ref): a06ae0b
- Git version: don't know (try.gitea.io)
- Operating system: Linux
- Database (use `[x]`): don't know (try.gitea.io)
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

I have created a mirror repository from Github. When I go the the panel "Releases", all tags are show with the right commit Id. But when I create a release on an existing tag, the commit Id is not the same and not match any commit Id of the repository.

**Gitea mirror:** https://try.gitea.io/zero-x-baadf00d/play-ebean-httpquery
**Origin:** https://github.com/0xbaadf00d/play-ebean-httpquery/tags

## Screenshots
image

### PR DESCRIPTION
**Pull request by lunny**
Should fix #5585

### CODE REVIEW

File: models/migrations/v81.go [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+		repoCache    = make(map[int64]*models.Repository)
+	)
+
+	if err = sess.Begin(); err != nil {
+		return err
+	}
+
+	for start := 0; ; start += batchSize {
+		releases := make([]*Release, 0, batchSize)
+		if err = sess.Limit(batchSize, start).Where("is_tag=?", false).Find(&releases); err != nil {
```
Comment (lafriks) [inline models/migrations/v81.go]: You should add order by id otherwise you can get inconsistent results

**Review by lafriks — CHANGES_REQUESTED** [review]

File: models/migrations/v81.go (hunk 1 above)
Comment (techknowlogick) [inline models/migrations/v81.go]:
```suggestion
		if err = sess.Limit(batchSize, start).Where("is_tag=?", false).Desc("id").Find(&releases); err != nil {
```

Comment (lunny) [reply models/migrations/v81.go]: done.

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]
