### PR TITLE
Fix bug webhook milestone is not right.

### LINKED ISSUE #34400: Webhook milestoned contains old milestone
### Description

Hello, when I receive the webhook action `milestoned` when changing an issue milestone, the `issue.milestone` field is still set to the last milestone (except there wasn't a milestone set before, then it's the correct one). It looks a little bit like the fixed #32887 issue.

### Gitea Version

1.23.7

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

I don't know

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix #34400

### CODE REVIEW

File: routers/web/repo/issue.go [hunk 1]
```diff
@@ -418,6 +418,16 @@ func UpdateIssueMilestone(ctx *context.Context) {
 			continue
 		}
 		issue.MilestoneID = milestoneID
+		if milestoneID > 0 {
+			var err error
+			issue.Milestone, err = issues_model.GetMilestoneByRepoID(ctx, ctx.Repo.Repository.ID, milestoneID)
+			if err != nil {
+				ctx.ServerError("GetMileStoneByID", err)
```
Comment (silverwind) [inline routers/web/repo/issue.go]:
```suggestion
				ctx.ServerError("GetMilestoneByRepoID", err)
```

**Review by silverwind — APPROVED** [review]

**Review by Zettat123 — APPROVED** [review]
