### PR TITLE
Fix artifact v4 upload above 8MB

### LINKED ISSUE #31354: Large Actions artifacts (> ~8MB) will fail checksum when merging their chunks
ref: https://forum.gitea.com/t/large-actions-artifacts-8mb-will-fail-checksum-when-merging-their-chunks/9291

I'm using a self-hosted Gitea 1.22.0, with the patched version of `upload-artifact@v4` (https://github.com/ChristopherHX/gitea-upload-artifact@v4), and am trying to upload a ~1.8GB artifact.

From the Actions step:
```
Uploaded bytes 1851809172
Finished uploading artifact content to blob storage!
SHA256 hash of uploaded artifact zip is 5445b7ac4b993cbc01f349b0ec90b8ebceee564cff62ce9a529fdb9ce1326886
Finalizing artifact upload
::error::Failed to FinalizeArtifact: Unexpected token 'E', "Error merge chunks%0A" is not valid JSON
```
When looking at the Gitea server logs, this matches up to this error message:

`...artifactsv4.go:363:finalizeArtifact() [E] Error merge chunks: update artifact error checksum is invalid`

I did some tests, and it looks like any artifacts that are bigger than roughly 8MB will fail to be merged when finalizing the upload.

### PR DESCRIPTION
**Pull request by ChristopherHX**
Multiple chunks are uploaded with type "block" without using "appendBlock" and eventually out of order for bigger uploads.
8MB seems to be the chunk size

This change parses the blockList uploaded after all blocks to get the final artifact size and order them correctly before calculating the sha256 checksum over all blocks

Fixes #31354

### CODE REVIEW

File: routers/api/actions/artifactsv4.go [hunk 1]
```diff
@@ -295,33 +303,57 @@ func (r *artifactV4Routes) uploadArtifact(ctx *ArtifactContext) {
...
+				log.Error("Error UpdateArtifactByID: %v", err)
+				ctx.Error(http.StatusInternalServerError, "Error UpdateArtifactByID")
+				return
+			}
+		} else {
+			_, err := r.fs.Save(fmt.Sprintf("tmp%d/block-%d-%d-%s", task.Job.RunID, task.Job.RunID, ctx.Req.ContentLength, blockid), ctx.Req.Body, -1)
+			if err != nil {
+				log.Error("Error runner api getting task: task is not running")
+				ctx.Error(http.StatusInternalServerError, "Error runner api getting task: task is not running")
+				return
```
Comment (ChristopherHX) [inline routers/api/actions/artifactsv4.go]: If we have a blockid, delay ordering chunks to the end and use it's blockid to form the name

I notice that this might be a security issue, because an attacker could control the filesystem name, but what alternatives do we have?
Santizing is probably the way to go here

File: routers/api/actions/artifactsv4.go [hunk 2]
```diff
@@ -295,33 +303,57 @@ func (r *artifactV4Routes) uploadArtifact(ctx *ArtifactContext) {
...
+			}
 		}
-
-		_, err = appendUploadChunk(r.fs, ctx, artifact, artifact.FileSize, ctx.Req.ContentLength, artifact.RunID)
+		ctx.JSON(http.StatusCreated, "appended")
+	case "blocklist":
+		_, err := r.fs.Save(fmt.Sprintf("tmp%d/%d-blocklist", task.Job.RunID, task.Job.RunID), ctx.Req.Body, -1)
```
Comment (ChristopherHX) [inline routers/api/actions/artifactsv4.go]: Now we got the final block order by blockid in xml, save it for the merge step

File: routers/api/actions/artifactsv4.go [hunk 3]
```diff
@@ -340,18 +372,49 @@ func (r *artifactV4Routes) finalizeArtifact(ctx *ArtifactContext) {
...
+			log.Error("Error merge chunks: %v", err)
+			ctx.Error(http.StatusInternalServerError, "Error merge chunks")
+			return
+		}
+		chunks, ok = chunkMap[artifact.ID]
+		if !ok {
+			log.Error("Error merge chunks")
+			ctx.Error(http.StatusInternalServerError, "Error merge chunks")
+			return
+		}
```
Comment (ChristopherHX) [inline routers/api/actions/artifactsv4.go]: My tests don't upload a blockmap yet, fallback try old broken mode

File: routers/api/actions/artifacts_chunks.go [hunk 4]
```diff
@@ -123,6 +123,49 @@ func listChunksByRunID(st storage.ObjectStorage, runID int64) (map[int64][]*chun
 	return chunksMap, nil
 }
 
+func listChunksByRunIDV4(st storage.ObjectStorage, runID int64, artifactID int64, blist *BlockList) ([]*chunkFileItem, error) {
```
Comment (ChristopherHX) [inline routers/api/actions/artifacts_chunks.go]: Syntetise a chunk list with the correct start/end and artifact entries, based on the xml Blocklist

**Review by ChristopherHX — COMMENTED** [review]
I think the issue is fixed like that, but we need to look at the security of storing a blockid in blob storage or find alternatives
```
Uploaded bytes 746586112
Uploaded bytes 754974720
Uploaded bytes 763363328
Uploaded bytes 771751936
Uploaded bytes 780140544
Uploaded bytes 788529152
Uploaded bytes 796917760
Uploaded bytes 805306368
Uploaded bytes 807753807
Finished uploading artifact content to blob storage!
SHA256 hash of uploaded artifact zip is 6feeaf6b88049a4c6ced1240ed3911afaa819229cd082999be5c81eff09c33f1
Finalizing artifact upload
Artifact artifact.zip successfully finalized. Artifact ID 22
Artifact artifact has been successfully uploaded! Final size is 807753807 bytes. Artifact ID is 22
Artifact download URL: http://localhost:3000/test/artifact-upload-big/actions/runs/39/artifacts/22
```

File: routers/api/actions/artifactsv4.go (hunk 1 above)
Comment (ChristopherHX) [reply routers/api/actions/artifactsv4.go]: I switched to base64url encoding of the blockid that doesn't allow to traverse the filesystem or do other bad things

File: routers/api/actions/artifacts_chunks.go [hunk 5]
```diff
@@ -123,6 +123,54 @@ func listChunksByRunID(st storage.ObjectStorage, runID int64) (map[int64][]*chun
...
 
+func listChunksByRunIDV4(st storage.ObjectStorage, runID, artifactID int64, blist *BlockList) ([]*chunkFileItem, error) {
+	storageDir := fmt.Sprintf("tmpv4%d", runID)
+	var chunks []*chunkFileItem
+	chunkMap := map[string]*chunkFileItem{}
+	dummy := &chunkFileItem{}
+	for _, name := range blist.Latest {
+		chunkMap[name] = dummy
+	}
+	if err := st.IterateObjects(storageDir, func(fpath string, obj storage.Object) error {
```
Comment (lunny) [inline routers/api/actions/artifacts_chunks.go:134]: This operation may take much time.

Comment (ChristopherHX) [reply routers/api/actions/artifacts_chunks.go:134]: Would iterating over BlockList and call stat for every block be better?

In this case I need to remove the size from the name, to make the name deterministic.

The following call to mergeChunksForArtifact is really really slow https://github.com/go-gitea/gitea/pull/31664/files/5a2a3958bb2185057ac9762d32b98a765cc1b849#diff-08f14348237183e6db3e10b54ea2bb47cce48b41cc0a3e54983bda4d9cdfd2f4R429

mergeChunksForArtifact does read all blocks and copies them to a single new object together with calculating sha256

**EDIT**
Assuming constant chunk size can reduce to two stat calls one per chunk (first and last chunk/block), but at the cost of some undefined behavior.

**Comment by VAllens** [comment]
I also encountered the same problem.
When can this PR be merged?
Has there been any progress?

**Comment by silverwind** [comment]
> look at the security of storing a blockid in blob storage

Isn't the storage considered "private" anyways?

**Comment by silverwind** [comment]
Ah I see where you are getting at. Yes, cross-repo contamination should be avoided.

**Comment by silverwind** [comment]
Is a test easily possible here? Might be valuable.

**Review by techknowlogick — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by VAllens** [comment]
goooooooooooooooooood !!!
