### PR TITLE
Fix branch/tag notifications in mirror sync

### LINKED ISSUE #13810: Webhook not delivered for tag creation on mirror repo
- Gitea version (or commit ref): `1.13.0`
- Git version: `2.26.2`
- Operating system: linux (using `gitea/gitea:1.13.0` from dockerhub)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No

Web hook: https://try.gitea.io/dbowring/gitea-tag-issue-test/settings/hooks/434
Not that an event was devlivered for the push, but not for the tag.

- Log gist:

```
gitea 2020/12/03 08:03:18 ...n/webhook/webhook.go:697:NotifyCreateRef() [E] GetRefCommitID[v0.0.6[]: object does not exist [id: v0.0.6, rel_path: ] 
```

## Description

If you have a webhook on a mirror repository, events will not be produced when tags are created on the remote repository.

### PR DESCRIPTION
**Pull request by manuelluis**
Fix: https://github.com/go-gitea/gitea/issues/13810

### CODE REVIEW

File: services/mirror/mirror.go [hunk 1]
```diff
@@ -438,6 +443,21 @@ func syncMirror(repoID string) {
 
 		// Create reference
 		if result.oldCommitID == gitShortEmptySha {
+			if tp == git.TagPrefix {
```
Comment (lunny) [inline services/mirror/mirror.go:446]: It seems line 442 has done this?

Comment (manuelluis) [reply services/mirror/mirror.go:446]: `SplitRefName` returns `refs/tags/` or `refs/heads/`, `NotifyCreateRef` uses `tag` and `branch` , for example: 
https://github.com/go-gitea/gitea/blob/d8c2c6cd59f3d38fcad9925fede4045c17975182/services/repository/push.go#L281-L290

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]
