### PR TITLE
Fix tracked time issues

### LINKED ISSUE #11313: DELETE time tracking fail with 500 error
- Gitea version (or commit ref): 1.11.4
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/api/v1/repos/camdarley/api-test/issues/1/times/769
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hi,
I seems that a DELETE request to https://try.gitea.io/api/v1/repos/camdarley/api-test/issues/1/times/769 leads to a 500 error with this trace:

`runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:199 (0x44c4db)
/usr/local/go/src/runtime/signal_unix.go:394 (0x44c318)
/go/src/code.gitea.io/gitea/models/issue_tracked_time.go:282 (0xee64b0)
/go/src/code.gitea.io/gitea/routers/api/v1/repo/issue_tracked_time.go:302 (0x1725f60)
...`

GET https://try.gitea.io/api/v1/repos/camdarley/api-test/issues/1/times list a time entry with ID 769, but when I send a DELETE to https://try.gitea.io/api/v1/repos/camdarley/api-test/issues/1/times/769 it fails with above error.

I tested first on my own Gitea instance, which is 1.11.4 with same issue.

### PR DESCRIPTION
**Pull request by 6543**
as title

close #11313
fix hidden 500 issue
enable tests 😆

### CODE REVIEW

File: models/issue_tracked_time.go [hunk 1]
```diff
@@ -299,13 +303,11 @@ func deleteTime(e Engine, t *TrackedTime) error {
...
-	time := &TrackedTime{
-		ID: id,
-	}
-	has, err := x.Get(time)
+	time := new(TrackedTime)
+	has, err := x.ID(id).Get(time)
 	if err != nil {
 		return nil, err
-	} else if !has {
+	} else if !has || time.Deleted {
```
Comment (lunny) [inline models/issue_tracked_time.go]: Maybe it's not a good idea to add this on this function.

Comment (6543) [reply models/issue_tracked_time.go]: changed @lunny

File: integrations/api_issue_tracked_time_test.go [hunk 2]
```diff
@@ -72,17 +72,17 @@ func TestAPIDeleteTrackedTime(t *testing.T) {
...
 	session.MakeRequest(t, req, http.StatusNoContent)
 	//Delete non existing time
-	session.MakeRequest(t, req, http.StatusInternalServerError) */
+	session.MakeRequest(t, req, http.StatusNotFound)
 
 	//Reset time of user 2 on issue 2
 	trackedSeconds, err := models.GetTrackedSeconds(models.FindTrackedTimesOptions{IssueID: 2, UserID: 2})
 	assert.NoError(t, err)
-	assert.Equal(t, int64(3662), trackedSeconds)
+	assert.Equal(t, int64(3661), trackedSeconds)
```
Comment (guillep2k) [inline integrations/api_issue_tracked_time_test.go:85]: Is this value sensitive to CPU load or something like that?

File: models/issue_tracked_time.go [hunk 3]
```diff
@@ -299,10 +303,8 @@ func deleteTime(e Engine, t *TrackedTime) error {
 
 // GetTrackedTimeByID returns raw TrackedTime without loading attributes by id
 func GetTrackedTimeByID(id int64) (*TrackedTime, error) {
-	time := &TrackedTime{
-		ID: id,
-	}
-	has, err := x.Get(time)
+	time := new(TrackedTime)
+	has, err := x.ID(id).Get(time)
```
Comment (guillep2k) [inline models/issue_tracked_time.go:307]: This is OK, but I wonder if there's some specific reason for the change, or it's just for tidiness.

Comment (lunny) [reply models/issue_tracked_time.go:307]: This will always generate `WHERE id =?`, but if `id == 0`, FindByExample will not generate any query conditions. So I will give this a ❤️

**Review by lunny — APPROVED** [review]

File: integrations/api_issue_tracked_time_test.go (hunk 2 above)
Comment (6543) [reply integrations/api_issue_tracked_time_test.go:85]: @guillep2k traked time **ID: 3** is just 1second:

https://github.com/go-gitea/gitea/blob/b9df5da1f4862d3ed58d528258ea56671791d60d/models/fixtures/tracked_time.yml#L17-L23

**Review by adelowo — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]
