### PR TITLE
Fix task list checkbox toggle to work with YAML front matter

### LINKED ISSUE #25160: Toggling checkbox in task list corrupts markdown when there's YAML front matter
### Description

Steps to reproduce:

1. Go to New Issue page
2. Fill in a title, and for content, fill in both YAML front matter and a task list, such as the below:
  ```
  ---
  foo: bar
  ---
  - [ ] checkbox
  ```
3. Click "Create Issue"
4. Once the issue is created, a checkbox is rendered.  Click the checkbox to make it checked.
5. Reload the page

I expected the checkbox to be checked and all other text including front matter to be the same as was originally entered.

Instead, a seemingly random character in the middle of the front matter or other markdown text content, depending on character positions, is replaced by an `x` character.  Unchecking will replace the character with a space character.  The problem has also been observed in pull request descriptions.

Demo: https://try.gitea.io/shravya/testing/issues/1

### Gitea Version

1.20.0+rc0-12-g63a429581

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Screenshot 2023-06-08 at 8 05 33 PM

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Using try.gitea.io.

### Database

None

### PR DESCRIPTION
**Pull request by jtran**
Fixes #25160.

`data-source-position` of checkboxes in a task list was incorrect whenever there was YAML front matter.  This would result in issue content or PR descriptions getting corrupted with random `x` or space characters when a user checked or unchecked a task.

### CODE REVIEW

**Review by kdumontnu — APPROVED** [review]
💯

File: modules/markup/markdown/markdown_test.go [hunk 1]
```diff
@@ -520,3 +520,40 @@ func TestMathBlock(t *testing.T) {
...
+		expected string
+	}{
+		{
+			// data-source-position should take into account YAML frontmatter.
+			`---
+foo: bar
+---
+- [ ] task 1`,
+			`<details><summary><i class="icon table"></i></summary><table>
+<thead>
```
Comment (wxiaoguang) [inline modules/markup/markdown/markdown_test.go:536]: Maybe there could be a `include_toc: false` in the meta section, to disable the `<details><summary>` part, then the output could be much simpler and clearer.

File: modules/markup/markdown/goldmark.go [hunk 2]
```diff
@@ -457,12 +462,7 @@ func (r *HTMLRenderer) renderTaskCheckBoxListItem(w util.BufWriter, source []byt
 		} else {
 			_, _ = w.WriteString("<li>")
 		}
-		_, _ = w.WriteString(`<input type="checkbox" disabled=""`)
-		segments := node.FirstChild().Lines()
-		if segments.Len() > 0 {
-			segment := segments.At(0)
-			_, _ = w.WriteString(fmt.Sprintf(` data-source-position="%d"`, segment.Start))
-		}
+		_, _ = w.WriteString(fmt.Sprintf(`<input type="checkbox" disabled="" data-source-position="%d"`, n.SourcePosition))
```
Comment (wxiaoguang) [inline modules/markup/markdown/goldmark.go]: `fmt.Fprint(w, ...)`?

**Comment by wxiaoguang** [comment]
Could there be a check when updating the context with `x`? Check whether there is `[` and `]` around it, then it could avoid corrupting.

File: modules/markup/markdown/goldmark.go (hunk 2 above)
Comment (kdumontnu) [reply modules/markup/markdown/goldmark.go]: Seems out of scope for this PR. There are lots of writes using the same method here. 

I think it's best to minimize the changes for this bugfix, since it will need to be backported.

**Comment by kdumontnu** [comment]
> Could there be a check when updating the content with `x`? Check whether there is `[` and `]` around it, then it could avoid corrupting.

Like a runtime assertion?

**Comment by wxiaoguang** [comment]
> > Could there be a check when updating the content with `x`? Check whether there is `[` and `]` around it, then it could avoid corrupting.
> 
> Like a runtime assertion?

Somewhat. It's not a must for this PR, but I can see a case for it (corruption):

1. user opens page 1 
2. user opens page 2
3. user clicks edit the comment on page 1 and save
4. user click checkbox on page 2 (now, the content is still old on page 2)
5. without the check, the `x` would corrupt the content

File: modules/markup/markdown/renderconfig.go [hunk 3]
```diff
@@ -20,6 +20,9 @@ type RenderConfig struct {
 	TOC      string // "false": hide,  "side"/empty: in sidebar,  "main"/"true": in main view
 	Lang     string
 	yamlNode *yaml.Node
+
+	// Used internally.  Cannot be controlled by frontmatter.
+	MetaLength int
```
Comment (wxiaoguang) [inline modules/markup/markdown/renderconfig.go]: It seems that this field is only used in the `markdown` package, maybe it can be private to avoid being exposed.

**Review by wxiaoguang — APPROVED** [review]
Overall LGTM

File: modules/markup/markdown/markdown_test.go (hunk 1 above)
Comment (jtran) [reply modules/markup/markdown/markdown_test.go:536]: You mean add `include_toc: false` to the YAML?  I can't get this to affect the details/summary.

Comment (wxiaoguang) [reply modules/markup/markdown/markdown_test.go:536]: Never mind. IIRC the render should work that way. But it is not a must. 😄 maybe there are some other tricks behind it.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Waiting whether we want to adress https://github.com/go-gitea/gitea/pull/25184#issuecomment-1587732485 here or not.

**Comment by jackHay22** [comment]
> Somewhat. It's not a must for this PR, but I can see a case for it (corruption):
> 
>     1. user opens page 1
> 
>     2. user opens page 2
> 
>     3. user clicks edit the comment on page 1 and save
> 
>     4. user click checkbox on page 2 (now, the content is still old on page 2)
> 
>     5. without the check, the `x` would corrupt the content

I don't think this scenario is possible. The operation in number 4 will completely overwrite the changes in number 3. Checking the box publishes all of the stale content, not just the new checkmark so it will still be correct relative to the content being published.

**Comment by jtran** [comment]
> > > Could there be a check when updating the content with `x`? Check whether there is `[` and `]` around it, then it could avoid corrupting.
> > 
> > 
> > Like a runtime assertion?
> 
> Somewhat. It's not a must for this PR, but I can see a case for it (corruption):
> 
>     1. user opens page 1
> 
>     2. user opens page 2
> 
>     3. user clicks edit the comment on page 1 and save
> 
>     4. user click checkbox on page 2 (now, the content is still old on page 2)
> 
>     5. without the check, the `x` would corrupt the content

Unless something has changed since this comment https://github.com/go-gitea/gitea/issues/24253#issuecomment-1517646488, I don't think we currently handle multi-window editing or re-syncing after the page loads.

However, I did make an update to prevent markdown corruption if there's ever another bug.  If it can't see bracket characters before and after and either a space or `x` character where it's changing, it will prevent the toggling from happening.

**Comment by wxiaoguang** [comment]
> Waiting whether we want to adress [#25184 (comment)](https://github.com/go-gitea/gitea/pull/25184#issuecomment-1587732485) here or not.

No need to wait my comment since I have approved, that's just a nit/question from my opinion.
