### PR TITLE
Rework file highlight rendering and fix yaml copy-paste

### LINKED ISSUE #19331: Copy/Paste ommitting newlines (again)
STR:

1. Open https://try.gitea.io/silverwind/symlink-test/src/branch/master/.drone.yml
2. Select the first 5 lines of code
3. Copy the code to clipboard
4. Paste it somewhere
5. Observe that empty line 4 is not copied

I recall https://github.com/go-gitea/gitea/commit/a6168fa25d0a7dfee689e1bce940557fff70d392, which ought to have fixed this but it must have regressed recently and 1.16 is also affected. I do not see a literal newline in the HTML on these empty lines anymore while there should be one.

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/19331

Followup to #19798. Remove both the `.line` and `.cl` classes from Chroma's HTML which made the old conditional work again. This fixed Copy of YAML files for me while also reducing the amount of rendered HTML nodes.

This retains the `.w` class which is for whitespace and which may be useful for themes to style.

### CODE REVIEW

File: modules/highlight/highlight.go [hunk 1]
```diff
@@ -196,18 +196,25 @@ func File(numLines int, fileName, language string, code []byte) []string {
...
 		content := string(v)
+
+		// remove useless wrapper nodes that are always present
+		content = strings.Replace(content, "<span class=\"line\"><span class=\"cl\">", "", 1)
+		content = strings.TrimPrefix(content, `</span></span>`)
+
+		// if there's no final newline, closing tags will be on last line
+		if !finalNewLine && i == numLines-1 {
+			content = strings.TrimSuffix(content, `</span></span>`)
+		}
```
Comment (wxiaoguang) [inline modules/highlight/highlight.go]: These two trimmings of `</span></span>` seems to be fragile. Maybe these tags could be removed more accurately

Comment (silverwind) [reply modules/highlight/highlight.go]: I guess only with an XML parser it could be made cleaner, but also likely much slower. Or maybe Chroma has an option to emit less wrapper tags, I did not investigate yet.

Comment (Gusted) [reply modules/highlight/highlight.go]: > I guess only with an XML parser it could be made cleaner

FYI: https://pkg.go.dev/golang.org/x/net/html

Comment (wxiaoguang) [reply modules/highlight/highlight.go]: I have looked at the Chroma code, it seems impossible to get rid of the line wrapper tags (two `span`s)  at the moment.

Since the outputted HTML is strict, I think it can be processed accurately by a simple `<tag>` match and a stack, because no necessary to handle various edge cases (attribute escaping, broken tags, etc)

Actually, the question in my mind is that why the Replace+TrimPrefix+TrimSuffix should be used. When reading the code, I can not guess the correctness for it. Even a `TrimPrefix("<span ...")` + `TrimSuffix("</span>")` is more readable and can be more stable.

Comment (silverwind) [reply modules/highlight/highlight.go]: The final TrimSuffix is to prevent unbalanced HTML from being emitted, which I think the previous code did. Browsers generally ignore unmatched closing tags, that's probably why it was never noticed, but now the test code tests for it too.

What could maybe be done is instead of splitting and iterating these "lines", regexp replacement across those whole string could be applied. It might even be a bit faster overall.

Ultimately, I consider the lack of newline characters on empty line a Chroma bug.

Comment (wxiaoguang) [reply modules/highlight/highlight.go]: Can we have a clear definition for Gitea about how to handle new lines?

For GitHub:

* https://github.com/wxiaoguang/playground/blob/main/eol-no.py : no new line, 1 lines (1 sloc) 13 Bytes
* https://github.com/wxiaoguang/playground/blob/main/eol-newline.py : one new line,  1 lines (1 sloc) 14 Bytes 
* https://github.com/wxiaoguang/playground/blob/main/eol-newline2.py : two new lines,  2 lines (1 sloc) 15 Bytes , but still only one line is displayed on UI

The copying of all of these GitHub files on UI will result in only one line without new line.

----

So, what's the expected behavior of Gitea for these cases?

* How many lines should be reported to users?
* How many lines should be displayed on the UI?
* What's the copied content?

Comment (silverwind) [reply modules/highlight/highlight.go]: Final newline is a different topic, this PR deals with empty lines in the middle of code which is currently bugged for copy on at least YAML files.

Generally, I'd say do not show or copy final newline(s), because when I copy these into my editor (sublime), I end up having to delete the extra newlines after the paste action, so I think it's pointless to even copy with them (and to a further extend display it, but https://github.com/go-gitea/gitea/pull/18076 is about that).

And to answer:

> How many lines should be reported to users?

Number of lines including all trailing newlines

> How many lines should be displayed on the UI?

After https://github.com/go-gitea/gitea/pull/18076, depends on setting of ui.HIDE_FINAL_NEWLINE.

> What's the copied content?

The same that is displayed.

Comment (wxiaoguang) [reply modules/highlight/highlight.go]: I am asking for the definition because I have some ideas to rewrite the highlight code, to make everything clear, instead of patching the buggy code again and again.

I would propose a PR for it, including the new line problem and the empty line problem.

**Comment by wxiaoguang** [comment]
I proposed a PR https://github.com/silverwind/gitea/pull/2 .

Major changes:
* the tags are processed accurately
* read the buffer directly instead of splitting it, performance improvement.
* EOL should be handled correctly
* complete (and more simple) tests

After this PR, the highlighted result can be processed easily without hacky methods.

**Comment by wxiaoguang** [comment]
I have a feeling that the fix should also be included in 1.17 release, otherwise the lost empty line problem is too annoying for users.

**Comment by silverwind** [comment]
merged that, pr. Need to rebase and test this.

**Review by wxiaoguang — APPROVED** [review]

**Comment by silverwind** [comment]
Tested this successfully, copy paste of empty lines in YAML still works.

Regarding final newline, it seems to behave similar to https://github.com/go-gitea/gitea/pull/18076 now, which I'm personally happy with. The option from that PR could still be added separately later.

File: routers/web/repo/view.go [hunk 2]
```diff
@@ -556,8 +546,14 @@ func renderFile(ctx *context.Context, entry *git.TreeEntry, treeLink, rawLink st
 			)
 		} else {
 			buf, _ := io.ReadAll(rd)
-			lineNums := linesBytesCount(buf)
-			ctx.Data["NumLines"] = strconv.Itoa(lineNums)
+
+			// empty: 0 line; "a": one line; "a\n": two lines; "a\nb": two lines;
```
Comment (KN4CK3R) [inline routers/web/repo/view.go]:
```suggestion
			// empty: 0 lines; "a": one line; "a\n": two lines; "a\nb": two lines;
```

**Comment by silverwind** [comment]
Squashed and added a better title.

**Comment by silverwind** [comment]
@zeripath would you mind a review? This PR started out as a bugfix for copy/paste, but then was rewritten by @wxiaoguang. I think it's a nice simplification of the output HTML of rendered files, it also removes wrapper elements introduced by chroma, the same as we did in https://github.com/go-gitea/gitea/pull/19958, resulting in less HTML sent the the browser, and in turn faster rendering.

**Comment by zeripath** [comment]
Hmm... I have a feeling that we're going about this the wrong way.

What's the purpose of all of this?

>  Remove both the .line and .cl classes from Chroma's HTML which made the old conditional work again

OK. Where and why do they appear? 

* The chroma HTML formatter adds them for each line during its `Format`
* https://github.com/alecthomas/chroma/blob/96fe58e6b13d6bf3e2da0bb88b37f70be2dd9bef/formatters/html/html.go#L279

Let's examine that code:

```go
	fmt.Fprintf(w, f.preWrapper.Start(true, f.styleAttr(css, chroma.PreWrapper)))

	highlightIndex = 0
	for index, tokens := range lines {
		// 1-based line number.
		line := f.baseLineNumber + index
		highlight, next := f.shouldHighlight(highlightIndex, line)
		if next {
			highlightIndex++
		}

		if !(f.preventSurroundingPre || f.inlineCode) {
			// Start of Line
			fmt.Fprint(w, `<span`)

			if highlight {
				// Line + LineHighlight
				if f.Classes {
					fmt.Fprintf(w, ` class="%s %s"`, f.class(chroma.Line), f.class(chroma.LineHighlight))
				} else {
					fmt.Fprintf(w, ` style="%s %s"`, css[chroma.Line], css[chroma.LineHighlight])
				}
				fmt.Fprint(w, `>`)
			} else {
				fmt.Fprintf(w, "%s>", f.styleAttr(css, chroma.Line))
			}

			// Line number
			if f.lineNumbers && !wrapInTable {
				fmt.Fprintf(w, "<span%s%s>%s</span>", f.styleAttr(css, chroma.LineNumbers), f.lineIDAttribute(line), f.lineTitleWithLinkIfNeeded(lineDigits, line))
			}

			fmt.Fprintf(w, `<span%s>`, f.styleAttr(css, chroma.CodeLine))
		}

		for _, token := range tokens {
			html := html.EscapeString(token.String())
			attr := f.styleAttr(css, token.Type)
			if attr != "" {
				html = fmt.Sprintf("<span%s>%s</span>", attr, html)
			}
			fmt.Fprint(w, html)
		}

		if !(f.preventSurroundingPre || f.inlineCode) {
			fmt.Fprint(w, `</span>`) // End of CodeLine

			fmt.Fprint(w, `</span>`) // End of Line
		}
	}
	fmt.Fprintf(w, f.preWrapper.End(true))
```

* Interestingly this differs from the code we currently have in Gitea because of: https://github.com/alecthomas/chroma/commit/d18e8a46f25ce0eb40f276410ab6cb3f2def9b7e

### 1. Upgrade Chroma to at least version 2.2.0

Chroma has added an option to  prevent these spans from being created in the first place.


### Can we fix this without upgrading Chroma?

However assuming that we can't upgrade Chroma... Perhaps we can do things differently... Lets just look at this loop a bit more clearly.

```go
	for index, tokens := range lines {
		// 1-based line number.
		...

		// Start of Line
		fmt.Fprint(w, `<span`)
		if highlight {
			...
		} else {
			fmt.Fprintf(w, "%s>", f.styleAttr(css, chroma.Line))
		}

		// Line number
		...

		fmt.Fprintf(w, `<span%s>`, f.styleAttr(css, chroma.CodeLine))

		for _, token := range tokens {
			html := html.EscapeString(token.String())
			attr := f.styleAttr(css, token.Type)
			if attr != "" {
				html = fmt.Sprintf("<span%s>%s</span>", attr, html)
			}
			fmt.Fprint(w, html)
		}

		fmt.Fprint(w, `</span>`) // End of CodeLine

		fmt.Fprint(w, `</span>`) // End of Line
	}
```

### 2. Lex and Format lines individually then remove the common prefix and suffix

There is no need to send the whole excerpt to the lexer and formatter in one go.

So long as you keep hold of the lexer state you can lexer and feed each line to the formatter individually.

Looking at the formatter code it should be clear that every line will start with `<span class="line"><span class"cl">` and end with `</span></span>`

Therefore if we feed lines in to the lexer and formatter one at a time we will always be able to just return the inner subset of the string.

### 3. Split lines using the suffix-prefix

Even if we don't want to do that - there is still no need to parse the html output from chroma. You can simply remove the initial `<span class="line"><span class"cl">` and terminal `</span></span>` and just `` strings.Split(formatted, `</span></span><span class="line"><span class"cl">`) ``  to get the highlighted lines.

**Comment by zeripath** [comment]
I guess I also don't understand what the `&#10;` is supposed to be doing.

**Comment by silverwind** [comment]
> Chroma has added an option to prevent these spans from being created in the first place.

Right, it's then obvious that we should upgrade first and set that Chroma option to remove the span wrappers. Ideally we may then get away without modifying HTML, but I have my doubts about it because of this empty line copying issue.

Maybe we should start a fresh PR. I'm not sure I have the bandwidth to do so in the next days, so if @wxiaoguang wants to take a stab, please go ahead. It will probably also require a update in the diff code after the Chroma upgrade.

**Comment by wxiaoguang** [comment]
> Hmm... I have a feeling that we're going about this the wrong way.
> Interestingly this differs from the code we currently have in Gitea because of: https://github.com/alecthomas/chroma/commit/d18e8a46f25ce0eb40f276410ab6cb3f2def9b7e

At that time, it was the right way. 

> Looking at the formatter code it should be clear that every line will start with <span class="line"><span class"cl"> and end with </span></span>

Replacing these tags without a parser are fragile, it's not right. About ```strings.Split(formatted, `</span></span><span class="line"><span class"cl">`)```, you can read the old code like https://github.com/go-gitea/gitea/commit/948190ed3d611b8e9dc83cc5857c0d0f0ecd66a0 , if you think that was right, I have nothing to argue, while I insist that was not.

> I guess I also don't understand what the &#10; is supposed to be doing.

That' in comment, to make the test clear: `make it clear to do tests: "&#10;" is the real newline for rendering, '\n' is ignorable/trim-able and could be ignored`. You can take the old tests if you like.

> Maybe we should start a fresh PR. I'm not sure I have the bandwidth to do so in the next days, so if wxiaoguang wants to take a stab, please go ahead. It will probably also require a update in the diff code after the Chroma upgrade.

Sorry but I have no time either, feel free to close this one and open a new one.

**Comment by wxiaoguang** [comment]
@zeripath 

Now, in https://github.com/go-gitea/gitea/pull/19967/commits/49f62a4d7145e14e5277e5c7d03995fe05a8c171 , there is no tag parser, just use Split+Trim as your wish.

**Comment by zeripath** [comment]
I'm bowing out from reviewing this PR. I've said my piece regarding this. 

I do not believe that the tag parser is necessary. I've explained that instead we should just use our knowledge of the output that comes from the formatter as I proposed in my PR.

I am deeply disturbed by the proposal to use the magic code `&#10;` too. I do not understand why it is necessary.

I will not review further.

**Comment by silverwind** [comment]
> I am deeply disturbed by the proposal to use the magic code &#10; too. I do not understand why it is necessary.

I was also against this. It seems just weird to abuse this token for our purposes when browsers can render literal newlines just fine.

**Comment by wxiaoguang** [comment]
OK, since many people do not like the HTML entity, then https://github.com/go-gitea/gitea/pull/19967/commits/025e3d9aa2f8fd4e61e31210eb868db27c3bb334 removed it.

But I do not know how to rewrite the tests to satisfy everyone. Please edit the tests directly, I am fine with any approach.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
.

**Comment by silverwind** [comment]
Seems to complicated to backport, even with https://github.com/go-gitea/gitea/commit/3310dd1d197495fbfa2d7ee490e19e6d08e1d30f applied I get merge conflicts, let's skip this.

**Comment by wxiaoguang** [comment]
There should be no hard dependency between these 2 PRs.

Maybe, for backport, could a simple and quick fix be fine? Maybe zeripath's approach can be backported without conflict, it doesn't change too much.

**Comment by wxiaoguang** [comment]
I tried to make a backport with zeripath's approach.

* https://github.com/go-gitea/gitea/pull/20612

**Comment by wxiaoguang** [comment]
> *
> 
> * If users want to hide the last empty line or show a block emoji (🚫) for no-newline when rendering, the new code is easier to do so in the future.

->  Show a no-EOL mark for the last line when viewing a file #27391
