### PR TITLE
Stop logging EOFs and exit(1)s in ssh handler (#20476)

### LINKED ISSUE #20473: Continuous SSH "Session Failed To Exit" Spam In Log
### Description

Every minute I get the following in my logs. Is this an issue that needs to be looked into? I am using the internal Gitea SSH server.

```
2022/07/25 07:10:20 modules/ssh/ssh.go:145:sessionHandler() SSH: Wait: exit status 1
2022/07/25 07:10:20 modules/ssh/ssh.go:149:sessionHandler() Session failed to exit. EOF
2022/07/25 07:11:20 modules/ssh/ssh.go:145:sessionHandler() SSH: Wait: exit status 1
2022/07/25 07:11:20 modules/ssh/ssh.go:149:sessionHandler() Session failed to exit. EOF
2022/07/25 07:12:20 modules/ssh/ssh.go:145:sessionHandler() SSH: Wait: exit status 1
2022/07/25 07:12:20 modules/ssh/ssh.go:149:sessionHandler() Session failed to exit. EOF
2022/07/25 07:13:20 modules/ssh/ssh.go:145:sessionHandler() SSH: Wait: exit status 1
2022/07/25 07:13:20 modules/ssh/ssh.go:149:sessionHandler() Session failed to exit. EOF
2022/07/25 07:14:20 modules/ssh/ssh.go:145:sessionHandler() SSH: Wait: exit status 1
2022/07/25 07:14:20 modules/ssh/ssh.go:149:sessionHandler() Session failed to exit. EOF
```

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.37.1

### Operating System

Windows 10

### How are you running Gitea?

From the latest Windows x64 binary directly from the Gitea downloads.

### Database

_No response_

### PR DESCRIPTION
**Pull request by zeripath**
Backport #20476

The code in modules/ssh/ssh.go:sessionHandler() currently cause an error to be
logged if `gitea serv` exits with a exit(1). This logging is useless because the
accompanying stderr is not provided and in any case the exit(1) is most likely due
to permissions errors.

Further it then causes the EOF to be logged - even though this is not helpful.

This PR simply checks the errors returned and stops logging them.

In the case of misconfigurations causing `gitea serv` to fail with exit(1)
the current logging is not helpful at determining this and users should simply
review the message passed over the ssh connection.

Fix #20473

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by jolheiser — APPROVED** [review]

File: modules/ssh/ssh.go [hunk 1]
```diff
@@ -142,10 +143,14 @@ func sessionHandler(session ssh.Session) {
...
-		log.Error("SSH: Wait: %v", err)
+		// Cannot use errors.Is here because ExitError doesn't implement Is
+		// Thus errors.Is will do equality test NOT type comparison
+		if _, ok := err.(*exec.ExitError); !ok {
+			log.Error("SSH: Wait: %v", err)
+		}
 	}
 
-	if err := session.Exit(getExitStatusFromError(err)); err != nil {
+	if err := session.Exit(getExitStatusFromError(err)); err != nil && !errors.Is(err, io.EOF) {
```
Comment (Gusted) [inline modules/ssh/ssh.go:153]: Is using error.Is correct here? https://github.com/golang/go/issues/39155 suggests that io.EOF never should be wrapped(and currently standard library shouldn't do that)

Comment (zeripath) [reply modules/ssh/ssh.go:153]: Just because io.EOF shouldn't be wrapped does not mean that it cannot be wrapped and errors.Is will still work on it.

We don't care about io.EOF. we don't care about errors that accidentally wrap io.EOF.

Therefore we should ignore them.

Therefore errors.Is is correct

**Review by Gusted — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:
