### PR TITLE
Return 400 but not 500 when request archive with wrong format

### LINKED ISSUE #17689: Internal Server Error when attempting to download archive via API
### Gitea Version

1.15.6

### Git Version

2.30.2

### Operating System

Raspberry Pi OS + Docker

### How are you running Gitea?

Running official docker image (tag: `1.15-linux-arm64`, id: `d7e5e9d96a5d269120a579a887efeae1589afb8d92ba4c03fe61264548e9af7f`) on an up-to-date version of Raspberry Pi OS (based on Debian bullseye).

TLS is handled by a Caddy reverse-proxy.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/jotoho/e4813169969a9d0a669cd86169de14e8

### Description

I was attempting to learn how to use the API to download the files in a private repository and attempted using it with a public repo first to avoid needing to provide a token.

Unfortunately when I tried to access the archive for `master` via `/api/swagger` or curl, my server threw back a "500 Internal Server Error" message.

* Original repository: https://gitea.jotoho.de/jotoho/waituntil
* Reproduction repository (mirror): https://try.gitea.io/jotoho/waituntil

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by lunny**
Fix #17689

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

File: integrations/api_repo_archive_test.go [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+	link, _ = url.Parse(fmt.Sprintf("/api/v1/repos/%s/%s/archive/master.bundle", user2.Name, repo.Name))
+	link.RawQuery = url.Values{"token": {token}}.Encode()
+	resp = MakeRequest(t, NewRequest(t, "GET", link.String()), http.StatusOK)
+	bs, err = io.ReadAll(resp.Body)
+	assert.NoError(t, err)
+	assert.EqualValues(t, 382, len(bs))
+
+	link, _ = url.Parse(fmt.Sprintf("/api/v1/repos/%s/%s/archive/master", user2.Name, repo.Name))
+	link.RawQuery = url.Values{"token": {token}}.Encode()
+	MakeRequest(t, NewRequest(t, "GET", link.String()), 400)
```
Comment (KN4CK3R) [inline integrations/api_repo_archive_test.go]:
```suggestion
	MakeRequest(t, NewRequest(t, "GET", link.String()), http.StatusBadRequest)
```

File: services/archiver/archiver_test.go [hunk 2]
```diff
@@ -132,3 +126,8 @@ func TestArchive_Basic(t *testing.T) {
 	assert.NotEqual(t, zipReq.GetArchiveName(), tgzReq.GetArchiveName())
 	assert.NotEqual(t, zipReq.GetArchiveName(), secondReq.GetArchiveName())
 }
+
+func TestErrUnknowArchiveFormat(t *testing.T) {
```
Comment (jotoho) [inline services/archiver/archiver_test.go]: `TestErrUnknowArchiveFormat` is supposed to be `TestErrUnknownArchiveFormat`, I presume.

**Review by jotoho — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
make lgtm work
