### PR TITLE
Fix encoding for Matrix Webhooks

### LINKED ISSUE #36012: matrix webhook encodes ! and # rendreing the links unusable by matrix
### Description

I am trying to set up a webhook to matrix, i tryed host, roomid and bearer token with a curl script, and they work.

When trying the webhook, i see that the leading ! of the room id is converted to %21and the matrix server returns me a  401 for the test.... 
i don't sse how i can enforce the non conversion of ! and # in the matrix webhook?

### Gitea Version

1.25

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.43

### Operating System

docker

### How are you running Gitea?

official docker image: image: gitea/gitea:1.25

### Database

None

### PR DESCRIPTION
**Pull request by bircni**
`url.PathEscape` unnecessarily encodes ! to %21, causing Matrix homeservers to reject the request with 401. Replace %21 back to ! after escaping.

Fixes #36012

### CODE REVIEW

**Comment by wxiaoguang** [comment]
There are different standards: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#description

Only `!` is special here?

> The characters on the second line are characters that may be part of the URI syntax, and are only escaped by encodeURIComponent(). Both encodeURI() and encodeURIComponent() do not encode the characters -.!~*'(), known as "unreserved marks", which do not have a reserved purpose but are allowed in a URI "as is". (See RFC2396)

**Comment by wxiaoguang** [comment]
btw: is it possible to find some "matrix official documents" for this encoding?

**Comment by bircni** [comment]
Good point — `:` also needs to be preserved since Matrix room IDs are of the form `!localpart:server` and `url.PathEscape` encodes `:` as `%3A` too. Updated to restore both.

For documentation: the Matrix spec defines room IDs at https://spec.matrix.org/latest/appendices/#room-ids. The underlying reason both characters are safe to leave unencoded is RFC 3986 §3.3 — `!` is a sub-delimiter and `:` is explicitly listed as a valid `pchar`, so neither requires percent-encoding in a path segment.

Attribution: Nicolas (bircni) with claude-sonnet-4-6

**Comment by bircni** [comment]
Maybe also interesting: https://spec.matrix.org/latest/appendices/#matrix-uri-scheme

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Wait, `%3A` can be kept:

Matrix does a mess for the encoding .......

image

**Comment by TheFox0x7** [comment]
Those are matrix.to links. It might not be the same as direct ones. And for the comment maybe stick to `!opaque_id:domain` naming?

File: routers/web/repo/setting/webhook.go [hunk 1]
```diff
@@ -454,8 +454,10 @@ func matrixHookParams(ctx *context.Context) webhookParams {
 	form := web.GetForm(ctx).(*forms.NewMatrixHookForm)
 
 	return webhookParams{
-		Type:        webhook_module.MATRIX,
-		URL:         fmt.Sprintf("%s/_matrix/client/r0/rooms/%s/send/m.room.message", form.HomeserverURL, url.PathEscape(form.RoomID)),
+		Type: webhook_module.MATRIX,
+		// See https://spec.matrix.org/latest/appendices/#room-ids
```
Comment (wxiaoguang) [inline routers/web/repo/setting/webhook.go]:
```suggestion
		// See https://spec.matrix.org/latest/appendices/#room-ids
		// Demo links: https://spec.matrix.org/latest/appendices/#matrixto-navigation
		// It seems that only `!` needs to be kept
```

**Comment by bircni** [comment]
thanks @wxiaoguang - I was too fast xD

**Comment by wxiaoguang** [comment]
> Those are matrix.to links. It might not be the same as direct ones. And for the comment maybe stick to `!opaque_id:domain` naming?

I am not sure, maybe need to find some real matrix users to try.

**Comment by TheFox0x7** [comment]
> > Those are matrix.to links. It might not be the same as direct ones. And for the comment maybe stick to `!opaque_id:domain` naming?
> 
> I am not sure, maybe need to find some real matrix users to try.

well it's less broken than before and if it is still broken someone will complain.

**Review by TheFox0x7 — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Maybe it needs to migrate to the latest API, and the encoding problem might should have been fixed.

https://spec.matrix.org/v1.18/client-server-api/#sending-events-to-a-room

**Comment by bircni** [comment]
> Maybe it needs to migrate to the latest API, and the encoding problem might should have been fixed.
> 
> https://spec.matrix.org/v1.18/client-server-api/#sending-events-to-a-room

Yes looks like our implementation is kinda old - but this should be solved in another issue and by someone who has matrix knowledge

**Comment by wxiaoguang** [comment]
r0 API is like this, indeed, `:` should be also be kept .....


image

**Comment by bircni** [comment]
> r0 API is like this, indeed, `:` should be also be kept .....

Thats why I was confused when you said we don't need lol

**Comment by wxiaoguang** [comment]
OK, latest API .....

image

**Comment by bircni** [comment]
this is so confusing the deeper you dive

**Comment by wxiaoguang** [comment]
> > r0 API is like this, indeed, `:` should be also be kept .....
> 
> Thats why I was confused when you said we don't need lol

Well, just beucase their API design is a mess .... there is no reason to reject encoded characters like `!` in real world .....
