### PR TITLE
Fix API Bug (fail on empty assignees)

### LINKED ISSUE #8872: [Bug] [API] CreateIssue not ignore empty assignees
afected version: 1.11-dev
not afected: 1.9.x; 1.10.0

If json include `"assignees": [ "" ],` responce is `422`:
```json
{
  "message": "Assignee does not exist: [name: user does not exist [uid: 0, name: , keyid: 0]]",
  "url": "https://gitea.com/api/swagger"
}
```
What sould happen: ignore assignees

### PR DESCRIPTION
**Pull request by 6543**
* [x] fix #8872 CreateIssue not ignore empty assignees
* [x] refactor MakeIDsFromAPIAssigneesToAdd
* [x] add tests

### CODE REVIEW

**Review by guillep2k — COMMENTED** [review]
This just should work, but the function seems now overly complicated. Do you think you can simplify it a little? You could use `util.ExistsInSlice()`, so you can also filter out any duplicates that `multipleAssignees` may have.

**Comment by 6543** [comment]
@guillep2k done

File: models/issue_assignees.go [hunk 1]
```diff
@@ -171,25 +172,31 @@ func toggleUserAssignee(e *xorm.Session, issue *Issue, assigneeID int64) (remove
...
 	// Keeping the old assigning method for compatibility reasons
-	if oneAssignee != "" {
+	if !util.ExistsInSlice(oneAssignee, multipleAssignees) {
+		requestAssignees = append(requestAssignees, oneAssignee)
+	}
 
-		// Prevent double adding assignees
-		var isDouble bool
+	//Prevent empty assignerees
+	if util.ExistsInSlice("", multipleAssignees) {
```
Comment (guillep2k) [inline models/issue_assignees.go]: My bad! `ExistsInSlice` requires an ordered slice; `IsStringInSlice` performs a linear search.
```suggestion
	if util.IsStringInSlice("", multipleAssignees) {
```

**Review by guillep2k — COMMENTED** [review]
I think you could just check if multipleAssignees is exactly [""], which is the bug you're trying to fix. And add oneAssignee if != "" and not already in the array. So, no loop needed. Also, if I recall correctly, GetUserIDsByNames() already checks for empty input, so there should be no need to check it here too.

File: models/issue_assignees.go [hunk 2]
```diff
@@ -171,25 +172,20 @@ func toggleUserAssignee(e *xorm.Session, issue *Issue, assigneeID int64) (remove
...
-		}
+	if oneAssignee != "" && !util.IsStringInSlice(oneAssignee, multipleAssignees) {
+		requestAssignees = append(requestAssignees, oneAssignee)
+	}
 
-		if !isDouble {
-			multipleAssignees = append(multipleAssignees, oneAssignee)
-		}
+	//Prevent empty assignees
+	if multipleAssignees[0] != "" {
```
Comment (guillep2k) [inline models/issue_assignees.go]:
```suggestion
	if len(multipleAssignees) > 0 && multipleAssignees[0] != "" {
```

**Review by guillep2k — APPROVED** [review]

File: models/issue_assignees.go [hunk 3]
```diff
@@ -5,6 +5,7 @@
 package models
 
 import (
+	"code.gitea.io/gitea/modules/util"
```
Comment (lunny) [inline models/issue_assignees.go]: wrong import order

**Review by lunny — CHANGES_REQUESTED** [review]

File: models/issue_assignees.go (hunk 3 above)
Comment (6543) [reply models/issue_assignees.go]: @lunny done

**Comment by lunny** [comment]
How about add a test for function `MakeIDsFromAPIAssigneesToAdd`?

**Comment by 6543** [comment]
@lunny tests are added

**Review by lunny — APPROVED** [review]

**Comment by 6543** [comment]
@lunny I'm ready to merge if you are ..
