### PR TITLE
Fix Matrix and MSTeams nil dereference

### LINKED ISSUE #28088: `nil` dereference in webhooks
Unfortunately this PR broke Gitea for us as the call to `p.Repository` inside `func (m *MatrixPayload) Package(p *api.PackagePayload) (api.Payloader, error)` (`services/webhook/matrix.go:239`) results in a nil pointer dereference. Looks like `p.Repository` is not set when triggered from `UploadManifest`. Stack trace (Gitea 1.21):

```
/source/services/webhook/matrix.go:215 (0x23cf774)
/source/services/webhook/payloader.go:58 (0x23dae5d)
/source/services/webhook/matrix.go:239 (0x23cfac4)
/source/services/webhook/webhook.go:198 (0x23dfc6b)
/source/services/webhook/webhook.go:261 (0x23e0435)
/source/services/webhook/notifier.go:882 (0x23da6d0)
/source/services/webhook/notifier.go:863 (0x23da495)
/source/services/notify/notify.go:353 (0x2306326)
/source/routers/api/packages/container/manifest.go:309 (0x23062da)
/source/routers/api/packages/container/manifest.go:184 (0x2305364)
/source/routers/api/packages/container/manifest.go:191 (0x230483c)
/source/routers/api/packages/container/manifest.go:75 (0x2304724)
/source/routers/api/packages/container/container.go:546 (0x2301bec)
```

_Originally posted by @niklaskorz in https://github.com/go-gitea/gitea/issues/27839#issuecomment-1814149873_

### LINKED ISSUE #28094: "PANIC: runtime error" when pushing container to Gitea container registry
### Description

Hi there,

Upon pushing a container to Gitea (even something as simple as a `hello-world` container), I'm getting the attached kernel panic. I'm not able to replicate it on try.gitea.io, but I can reliably reproduce it on my Gitea instance.

Error
```
2023/11/16 22:42:51 ...eb/routing/logger.go:47:func1() [T] router: started   PUT /v2/<user>/<repo>/manifests/db5e586 for 10.233.81.22:48164
2023/11/16 22:42:51 ...eb/routing/logger.go:78:func1() [W] router: failed    PUT /v2/<user>/<repo>/manifests/db5e586 for 10.233.81.22:48164, panic in 521.6ms @ container/container.go:516(container.UploadManifest), err=runtime error: invalid memory address or nil pointer dereference
2023/11/16 22:42:51 ...s/process/manager.go:231:remove() [T] Done 65569aeb-31: PUT: /v2/<user>/<repo>/manifests/db5e586
2023/11/16 22:42:51 ...rs/common/errpage.go:26:RenderPanicErrorPage() [E] PANIC: runtime error: invalid memory address or nil pointer dereference
```

Example Dockerfile:
```yaml
FROM viaductoss/ksops:v4.2.5 as ksops-builder
FROM quay.io/argoproj/argocd:v2.9.0
USER root
ARG PKG_NAME=ksops
COPY --from=ksops-builder /usr/local/bin/kustomize /usr/local/bin/kustomize
COPY --from=ksops-builder /usr/local/bin/ksops /usr/local/bin/ksops
USER argocd
```

Upon pushing the container, I get the following response:
```
...
e3ba1babc8bc: Layer already exists
74c0af6e0227: Layer already exists
received unexpected HTTP status: 500 Internal Server Error
```

I've deployed the Gitea Helm Chart, and there are no memory limitations, I'm using Redis, Elasticsearch, and Postgres. It was previously functional in `1.20.5`. I've executed Gitea doctor:
```
gitea -c /data/gitea/conf/app.ini doctor check --fix --all
```
to no avail unfortunately. Please let me know if I can provide any additional information that might help. 

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/perfectra1n/5b24f3c44dd77d3585036a474bb65b15

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Linux

### How are you running Gitea?

I've deployed the Gitea Helm Chart, and there are no memory limitations, I'm using Redis, Elasticsearch, and Postgres. I have the following values:

```yaml
        image:
          repository: gitea/gitea
          # Overrides the image tag whose default is the chart appVersion.
          tag: 1.21.0
          pullPolicy: Always
          rootless: true
        deployment:
          annotations:
            reloader.stakater.com/auto: "true"
        strategy:
          type: Recreate
        clusterDomain: newcluster.local
        podSecurityContext:
          fsGroupChangePolicy: "OnRootMismatch"
        containerSecurityContext:
          capabilities:
            add: ["SYS_CHROOT"]
        redis-cluster:
          enabled: false
        postgresql:
          enabled: false
        postgresql-ha:
          enabled: false
        persistence:
          enabled: true
          mount: true
          create: false
          claimName: "gitea-data"
        gitea:
          additionalConfigSources:
            - secret: 
                secretName: gitea-config-secret
          admin:
            existingSecret: gitea-admin-secret
          config:
            APP_NAME: Gitea
            indexer:
              ISSUE_INDEXER_TYPE: elasticsearch
            
              REPO_INDEXER_ENABLED: true
              REPO_INDEXER_TYPE: elasticsearch
              REPO_INDEXER_REPO_TYPES: sources,mirrors,templates
              MAX_FILE_SIZE: 52428800
            repository:
              ENABLE_PUSH_CREATE_USER: true
              ENABLE_PUSH_CREATE_ORG: true
              DEFAULT_BRANCH: master
              DEFAULT_PRIVATE: true
            repository.upload:
              FILE_MAX_SIZE: 102400
              MAX_FILES: 300
            server:
              DISABLE_SSH: true
              DOMAIN: gitea.domain.com
              ROOT_URL: https://gitea.domain.com
              ENABLE_GZIP: true
              LFS_START_SERVER: true
            database:
              DB_TYPE: postgres
              HOST: main-cluster-rw.databases.svc.newcluster.local
            session:
              PROVIDER: db
            ui:
              THEMES: gitea,arc-green,github-dark,codeberg,anamecool
              DEFAULT_THEME: arc-green
            attachment:
              MAX_SIZE: 102400
              MAX_FILES: 300
            git.timeout:
              GC: 500
            actions:
              ENABLED: true
            service:
              REGISTER_EMAIL_CONFIRM: false
              REGISTER_MANUAL_CONFIRM: true
              DISABLE_REGISTRATION: false
              REQUIRE_SIGNIN_VIEW: true
              ENABLE_NOTIFY_MAIL: true
              ALLOW_ONLY_EXTERNAL_REGISTRATION: false
              ENABLE_CAPTCHA: false
              DEFAULT_KEEP_EMAIL_PRIVATE: true
              DEFAULT_ALLOW_CREATE_ORGANIZATION: true
              DEFAULT_ENABLE_TIMETRACKING: true
              NO_REPLY_ADDRESS: "thing@gmail.com"
            cache:
              ENABLED: true
              ADAPTER: redis
              HOST: redis://:gitea@gitea-redis.gitea.svc.newcluster.local:6379/0?pool_size=100&idle_timeout=180s&
            queue:
              TYPE: redis
              CONN_STR: redis://:gitea@gitea-redis.gitea.svc.newcluster.local:6379/0?pool_size=100&idle_timeout=180s&
            cron:
              ENABLED: true
            cron.update_mirrors:
              SCHEDULE: 0 */12 * * *
            security:
              LOGIN_REMEMBER_DAYS: 180
            log:
              LEVEL: Debug
            mailer:
              ENABLED: true
          metrics:
            enabled: true
```

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by KN4CK3R**
Fixes #28088 
Fixes #28094

Added missing tests.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

File: services/webhook/matrix.go [hunk 1]
```diff
@@ -212,7 +212,7 @@ func (m *MatrixPayload) Repository(p *api.RepositoryPayload) (api.Payloader, err
 
 func (m *MatrixPayload) Package(p *api.PackagePayload) (api.Payloader, error) {
 	senderLink := MatrixLinkFormatter(setting.AppURL+p.Sender.UserName, p.Sender.UserName)
-	repoLink := MatrixLinkFormatter(p.Repository.HTMLURL, p.Repository.FullName)
+	repoLink := MatrixLinkFormatter(p.Package.HTMLURL, p.Package.Name)
```
Comment (yp05327) [inline services/webhook/matrix.go]:
```suggestion
	packageLink := MatrixLinkFormatter(p.Package.HTMLURL, p.Package.Name)
```
maybe the variable name should also be changed.


ps: `p.Repository` is always `nil`, as `api.PackagePayload` comes from here:
https://github.com/go-gitea/gitea/blob/fce1d5d7dce6a16429d0fe043555eac2c083ae7b/services/webhook/notifier.go#L882-L886
And as the comment mentioned here, `Repository` can be `nil` when user upload/delete a package to an organization. So we should not use `p.Repository` here.
https://github.com/go-gitea/gitea/blob/fce1d5d7dce6a16429d0fe043555eac2c083ae7b/services/actions/notifier_helper.go#L310-L315
