### PR TITLE
Use UTC as default timezone when schedule Actions cron tasks

### LINKED ISSUE #31657: Actions workflow schedule to support UTC
### Feature Description

It is my understanding that [Github Actions schedule objects are all interpreted as UTC](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule). After configuring some cron workflows and setting them to run at 9AM, I have noticed that they run at 9AM local time and not 9AM UTC. I am unsure if this was an intended effect or could be viewed as a bug.

I see the following as paths forward:
* Document that workflow schedules are configured to local time
* Change workflow schedules to instead be based on UTC
* Add a configuration value to allow cron to be interpreted as either local or UTC, default to use local to retain current behaviors and add documentation to clarify

For posterity here is my observed behavior:
Given a workflow defined to run as
```
on:
  schedule:
    - cron: "0 9 * * *"
```

I see job ran ~25 minutes ago at roughly that amount of time past 9AM local
image

### Screenshots

image

### PR DESCRIPTION
**Pull request by wolfogre**
Fix #31657.

According to the [doc](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onschedule) of GitHub Actions, The timezone for cron should be UTC, not the local timezone. And Gitea Actions doesn't have any reasons to change this, so I think it's a bug.

However, Gitea Actions has extended the syntax, as it supports descriptors like `@weekly` and `@every 5m`, and supports specifying the timezone like `TZ=UTC 0 10 * * *`. So we can make it use UTC only when the timezone is not specified, to be compatible with GitHub Actions, and also respect the user's specified.

It does break the feature because the times to run tasks would be changed, and it may confuse users. So I don't think we should backport this.

## ⚠️ BREAKING ⚠️

If the server's local time zone is not UTC, a scheduled task would run at a different time after upgrading Gitea to this version.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: models/actions/schedule_spec.go [hunk 1]
```diff
@@ -32,8 +34,29 @@ type ActionScheduleSpec struct {
...
 func (s *ActionScheduleSpec) Parse() (cron.Schedule, error) {
-	return cronParser.Parse(s.Spec)
+	parser := cron.NewParser(cron.Minute | cron.Hour | cron.Dom | cron.Month | cron.Dow | cron.Descriptor)
+	schedule, err := parser.Parse(s.Spec)
+	if err != nil {
+		return nil, err
+	}
+
+	// If the spec has specified a timezone, use it
+	if strings.HasPrefix(s.Spec, "TZ=") || strings.HasPrefix(s.Spec, "CRON_TZ=") {
```
Comment (delvh) [inline models/actions/schedule_spec.go:47]: How do we handle leading whitespace?

**Review by delvh — APPROVED** [review]

File: models/actions/schedule_spec.go (hunk 1 above)
Comment (wolfogre) [reply models/actions/schedule_spec.go:47]: It's not "we", it's how "robfig/cron" handle this.

https://github.com/robfig/cron/blob/bc59245fe10efaed9d51b56900192527ed733435/parser.go#L95

If we want to handle leading whitespace, it could be done before storing it into the database.
