### PR TITLE
Fix RocketChat webhook

### LINKED ISSUE #9899: Web hooks not successful: Invalid href value provided.
- Gitea version (or commit ref): ad1b6d4
- Git version: 1.12.0+dev-130
- Operating system: Docker (Ubuntu 18.04 LTS host)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
All webhooks have begin to fail with the following response:
##### Headers
```
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Origin: *
Cache-Control: no-store
Connection: keep-alive
Content-Type: application/json
Date: Mon, 20 Jan 2020 18:00:59 GMT
Pragma: no-cache
Server: nginx/1.17.5
Strict-Transport-Security: max-age=31536000
Vary: Accept-Encoding
X-Instance-Id: kywEfEQGjr4NXbNts
X-Ratelimit-Limit: 50
X-Ratelimit-Remaining: 49
X-Ratelimit-Reset: 1579543319854
X-Xss-Protection: 1
```
##### Body
```
{"success":false,"error":"Invalid href value provided"}
```
The webhook URL has *not* changed, and it was working properly before.

## Screenshots
image
image

### PR DESCRIPTION
**Pull request by jolheiser**
Resolves #9899

~~I'm fairly certain this should fix rocket chat webhooks for push actions.~~  
~~I do not have a rocket chat instance to confirm on, however, so this PR should probably not be accepted until someone can confirm.~~  

Turns out rocket chat has a free cloud trial, so I can confirm it works.
I also just removed attachments altogether for repo create/delete event, as it was always blank. :man_shrugging: 

(Repo event) With blank attachment
Screenshot from 2020-01-20 23-43-13

(Repo event) Without
Screenshot from 2020-01-20 23-43-19

(Push event) Rocket Chat
Screenshot from 2020-01-20 23-44-38

(Repo events and push event) Slack
Screenshot from 2020-01-20 23-40-48

### CODE REVIEW

File: modules/webhook/slack.go [hunk 1]
```diff
@@ -233,6 +233,8 @@ func getSlackPushPayload(p *api.PushPayload, slack *SlackMeta) (*SlackPayload, e
 		IconURL:  slack.IconURL,
 		Attachments: []SlackAttachment{{
 			Color: slack.Color,
+			Title: p.Repo.HTMLURL,
```
Comment (guillep2k) [inline modules/webhook/slack.go]: An URL for a title? I expected some plain text (https://api.slack.com/reference/messaging/attachments).

Comment (jolheiser) [reply modules/webhook/slack.go]: Do you have a suggestion for that text? Other payloads have issue titles or some such, but I didn't know of a good one for this, unless I just re-use `x new commits pushed` or something.

**Comment by lunny** [comment]
@bkraul could you confirm that this fixed #9899 ?

File: modules/webhook/slack.go (hunk 1 above)
Comment (jolheiser) [reply modules/webhook/slack.go]: The repository payload seems to do something similar.

```go
func getSlackRepositoryPayload(p *api.RepositoryPayload, slack *SlackMeta) (*SlackPayload, error) {
	senderLink := SlackLinkFormatter(setting.AppURL+p.Sender.UserName, p.Sender.UserName)
	repoLink := SlackLinkFormatter(p.Repository.HTMLURL, p.Repository.FullName)
	var text, title, attachmentText string

	switch p.Action {
	case api.HookRepoCreated:
		text = fmt.Sprintf("[%s] Repository created by %s", repoLink, senderLink)
		title = p.Repository.HTMLURL
	case api.HookRepoDeleted:
		text = fmt.Sprintf("[%s] Repository deleted by %s", repoLink, senderLink)
	}

	return &SlackPayload{
		Channel:  slack.Channel,
		Text:     text,
		Username: slack.Username,
		IconURL:  slack.IconURL,
		Attachments: []SlackAttachment{{
			Color:     slack.Color,
			Title:     title,
			TitleLink: title,
			Text:      attachmentText,
		}},
	}, nil
}
```

**Comment by jolheiser** [comment]
Turns out rocket chat has a free cloud trial, so I can confirm it works.
I also just removed attachments altogether for repo create/delete event, as it was always blank. :man_shrugging: 

(Repo event) With blank attachment
Screenshot from 2020-01-20 23-43-13

(Repo event) Without
Screenshot from 2020-01-20 23-43-19

(Push event) Rocket Chat
Screenshot from 2020-01-20 23-44-38


(Repo events and push event) Slack
Screenshot from 2020-01-20 23-40-48

**Comment by guillep2k** [comment]
If this bug was caused by #9378, perhaps we should consider backporting this fix into 1.10.4, as that PR was backported to 1.10.2.

File: modules/webhook/slack.go (hunk 1 above)
Comment (guillep2k) [reply modules/webhook/slack.go]: No idea, but if the attachment links to the repo itself (which is weird, maybe?), perhaps the repo name should be used?

I'm under the impression that it should better to remove the property from the payload when empty rather than sending improper data. 🤔

Comment (jolheiser) [reply modules/webhook/slack.go]: I'd agree with not sending anything, but that seems to be what caused the bug for whatever reason.

It could be repo name, but even that is sort of dupe data. Better than a URL, though? 😅

Comment (guillep2k) [reply modules/webhook/slack.go]: I'm not a webhook user; not even a Slack user, so please take my opinion with a grain of salt. From what I [read](https://api.slack.com/reference/messaging/attachments) from the [docs](https://api.slack.com/messaging/composing/layouts#when-to-use-attachments), I think we're using the attachment section to produce a "Read more" action. It looks like it should not have a link at all, and if any title, it should be.... "More details" or something like that (but it would be redundant because I bet Slack already gives you the "Read more").

Comment (jolheiser) [reply modules/webhook/slack.go]: Bars on my screenshots above, "see more" works in RC but possibly not Slack, since RC allows you to hide it but Slack appears to show all of it no matter what

Comment (jolheiser) [reply modules/webhook/slack.go]: But I am also not a Slack or RC user, I just have some workspaces for testing webhooks lately.

Comment (guillep2k) [reply modules/webhook/slack.go]: https://api.slack.com/messaging/composing/layouts#when-to-use-attachments

>
> Any content displayed within attachments may be wrapped, truncated, or hidden behind a "show more" style option by Slack clients. 

So I guess it depends on the client.

File: modules/webhook/slack.go [hunk 2]
```diff
@@ -289,12 +291,11 @@ func getSlackPullRequestApprovalPayload(p *api.PullRequestPayload, slack *SlackM
 func getSlackRepositoryPayload(p *api.RepositoryPayload, slack *SlackMeta) (*SlackPayload, error) {
 	senderLink := SlackLinkFormatter(setting.AppURL+p.Sender.UserName, p.Sender.UserName)
 	repoLink := SlackLinkFormatter(p.Repository.HTMLURL, p.Repository.FullName)
-	var text, title, attachmentText string
+	var text string
 
 	switch p.Action {
 	case api.HookRepoCreated:
 		text = fmt.Sprintf("[%s] Repository created by %s", repoLink, senderLink)
-		title = p.Repository.HTMLURL
```
Comment (zeripath) [inline modules/webhook/slack.go:297]: Is this right?

**Review by zeripath — APPROVED** [review]
One query, but otherwise lgtm.

**Comment by bkraul** [comment]
> 
> 
> @bkraul could you confirm that this fixed #9899 ?

Will do once this is merged and built on to docker image. Thanks for the quick response, guys!

File: modules/webhook/slack.go (hunk 2 above)
Comment (jolheiser) [reply modules/webhook/slack.go:297]: @zeripath Yeah, if you look at the images all this used to do was add an attachment with no actual content, just a title with the repo URL (which is already part of `repoLink`)   
It also broke the hook for delete events because title was only ever given a value here.

File: modules/webhook/slack.go (hunk 1 above)
Comment (jolheiser) [reply modules/webhook/slack.go]: For the record I am not against changing this, I just really can't think of a good title.  
An empty title would break the webhook (at least for RC, not sure about Slack or mattermost)

Comment (bkraul) [reply modules/webhook/slack.go]: Why not open it up as an option with a default? Maybe more trouble than it's worth?

Comment (jolheiser) [reply modules/webhook/slack.go]: Since it only applies to this payload, I don't know that it would be worth it.  
Other payloads have something meaningful for this title.

**Review by 6543 — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

File: modules/webhook/slack.go (hunk 1 above)
Comment (guillep2k) [reply modules/webhook/slack.go]: What about "details"? The problem is of course l10n....
Anyway, I'm not in the least against leaving it like this if nobody complains. 😄

Comment (jolheiser) [reply modules/webhook/slack.go]: Agreed. Maybe it can be updated in future PR.

**Comment by sapk** [comment]
@jolheiser  Please, can you send backport ?

**Comment by bkraul** [comment]
This works like a charm on latest docker build! Thank you!
