### PR TITLE
Fix compare dropdown for branches without common history

### LINKED ISSUE #37469: Compare dropdown fails when selecting branch with no common merge-base (unrelated histories)
### Description

Selecting a branch in the compare dropdown can fail with a server error if the currently selected base branch has no common merge base with the selected branch.

The failure happens already during dropdown selection, not only when opening the compare view.

## Steps to Reproduce

1. Have two branches with **no common history** (e.g. `main` and a branch based on another root like `poc/...`)
2. Open the compare view (`/compare`)
3. Keep `base = main`
4. Try to select the unrelated branch via the dropdown (e.g. `feature/...`)

## Actual Behavior

The selection fails and Gitea logs:
`GetCompareInfo: MergeBase: get merge-base of <commit> and <commit> failed: exit status 1`
The Ui shows an error 500

## Expected Behavior

- Selecting a branch in the dropdown should **not fail**, even if the current base branch is incompatible
- Gitea should either:
  - allow selection first and only validate afterwards, or
  - show a proper message like:  
    _"Branches have no common history / no merge base"_  
    instead of failing during selection

## Additional Context

- Opening the compare view directly with a valid base branch (one that shares history) works fine
- The issue only occurs when the dropdown triggers a compare against an incompatible base branch

### Gitea Version

1.26

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by bircni**
## Summary

- handle compare requests where base and head refs have no common merge base without returning 500
- keep the compare branch selectors usable and show a clear warning message
- add regression coverage for unrelated-history compare selection and merge-base error detection
- refactor legacy code, remove dead code and fix incorrect logic

Fixes #37469

### CODE REVIEW

File: modules/gitrepo/merge.go [hunk 1]
```diff
@@ -5,17 +5,44 @@ package gitrepo
...
 	"code.gitea.io/gitea/modules/git/gitcmd"
 )
 
+type ErrNoMergeBase struct {
+	BaseCommitID string
+	HeadCommitID string
+	Err          error
+}
+
+func IsErrNoMergeBase(err error) bool {
```
Comment (wxiaoguang) [inline modules/gitrepo/merge.go]: Please use modern Go error system, don't add `IsXxx` functions.

File: modules/gitrepo/merge.go [hunk 2]
```diff
@@ -5,17 +5,44 @@ package gitrepo
...
+func (err ErrNoMergeBase) Unwrap() error {
+	return err.Err
+}
+
 // MergeBase checks and returns merge base of two commits.
 func MergeBase(ctx context.Context, repo Repository, baseCommitID, headCommitID string) (string, error) {
 	mergeBase, _, err := RunCmdString(ctx, repo, gitcmd.NewCommand("merge-base").
 		AddDashesAndList(baseCommitID, headCommitID))
 	if err != nil {
+		if gitcmd.IsErrorExitCode(err, 1) {
```
Comment (wxiaoguang) [inline modules/gitrepo/merge.go]: There must be a clear git message for this case.

Different failures can all cause exit code 1

Comment (bircni) [reply modules/gitrepo/merge.go]: there is none, I tested and it returned only 1 silently :-(

File: templates/repo/diff/compare.tmpl [hunk 3]
```diff
@@ -168,7 +168,11 @@
 		</div>
 
 		{{$showDiffBox := and .CommitCount (not .IsNothingToCompare)}}
-		{{if and .IsSigned .PageIsComparePull}}
+		{{if .NoMergeBase}}
+			<div class="ui warning message">
+				{{ctx.Locale.Tr "repo.pulls.no_common_history"}}
+			</div>
+		{{else if and .IsSigned .PageIsComparePull}}
```
Comment (wxiaoguang) [inline templates/repo/diff/compare.tmpl]: There are already a lot of "nothing" errors. 

They should be managed and reused together

Image

File: routers/web/repo/compare.go [hunk 4]
```diff
@@ -413,6 +413,12 @@ func ParseCompareInfo(ctx *context.Context) *git_service.CompareInfo {
 
 	compareInfo, err := git_service.GetCompareInfo(ctx, baseRepo, headRepo, headGitRepo, baseRef, headRef, compareReq.DirectComparison(), fileOnly)
 	if err != nil {
+		if gitrepo.IsErrNoMergeBase(err) {
+			ctx.Data["NoMergeBase"] = true
+			ctx.Data["BeforeCommitID"] = compareInfo.BaseCommitID
+			ctx.Data["AfterCommitID"] = compareInfo.HeadCommitID
+			return &compareInfo
+		}
```
Comment (wxiaoguang) [inline routers/web/repo/compare.go]: If no merge base, do BeforeCommitID and AfterCommitID still make sense?

File: routers/web/repo/compare.go [hunk 5]
```diff
@@ -473,6 +479,12 @@ func PrepareCompareDiff(
 	ctx.Data["TitleQuery"] = newPrFormTitle
 	ctx.Data["BodyQuery"] = newPrFormBody
 
+	if ctx.Data["NoMergeBase"] == true {
```
Comment (wxiaoguang) [inline routers/web/repo/compare.go]: No .....

I have spent a lot of time on refactoring the fragile templates: Refactor pull request view (1) ... (4) ....


If we keep writing such code, there will be  Refactor pull request view (100) ... (1000) .... (10000) .... endless

File: modules/gitrepo/merge.go (hunk 2 above)
Comment (wxiaoguang) [reply modules/gitrepo/merge.go]: "stderr" doesn't contain anything either?

File: templates/repo/diff/compare.tmpl (hunk 3 above)
Comment (wxiaoguang) [reply templates/repo/diff/compare.tmpl]: To keep template logic simple and clear, it can use a Flash.Error message for this case.

No need to change template logic too much. The template itself needs to be refactored in the future, just like the PR view page ......

File: modules/gitrepo/merge.go (hunk 2 above)
Comment (bircni) [reply modules/gitrepo/merge.go]: Nope i saw nothing

File: templates/repo/diff/compare.tmpl [hunk 6]
```diff
@@ -210,7 +211,7 @@
 				</div>
 			{{end}}
 		{{else}}{{/* not singed-in or not for pull-request */}}
-			{{if not .CommitCount}}
+			{{if and (not .CommitCount) (not .HideCompareNothingMessage)}}
```
Comment (wxiaoguang) [inline templates/repo/diff/compare.tmpl]: Since our template is very fragile, if there is no necessity, I think we can leave most things as is.

For example: there is indeed nothing to compare if two branches are unrelated, so I think we don't need to change the `if` logic.

What do you think?

File: routers/web/repo/compare.go [hunk 7]
```diff
@@ -645,6 +662,11 @@ func CompareDiff(ctx *context.Context) {
 	}
 	ctx.Data["HeadTags"] = headTags
 
+	if ctx.Data["NoMergeBase"] == true {
+		ctx.HTML(http.StatusOK, tplCompare)
+		return
+	}
+
```
Comment (wxiaoguang) [inline routers/web/repo/compare.go]: It's more fragile to serve a template out of the router's direct handler.

The callers just are not able to know whether the necessary data is well prepared for the template.

I mean: don't use `ctx.Data["NoMergeBase"] == true` to pass backend variables.

File: templates/repo/diff/compare.tmpl (hunk 6 above)
Comment (bircni) [reply templates/repo/diff/compare.tmpl]: yep just rereviewed - same point

**Comment by wxiaoguang** [comment]
Took a deep look, I found that the legacy code is not quite right.

For example: after GetHeadOwnerAndRepo gets introduced, `	has := headRepo != nil` and related logic doesn't make sense anymore.

Will take a deeper look and maybe fix the legacy problems together.

**Comment by bircni** [comment]
> Took a deep look, I found that the legacy code is not quite right.
> 
> For example: after GetHeadOwnerAndRepo gets introduced, ` has := headRepo != nil` and related logic doesn't make sense anymore.
> 
> Will take a deeper look and maybe fix the legacy problems together.

Thank you !!!

**Comment by wxiaoguang** [comment]
Much more changes than I thought (more problems in legacy code than it looks ....). I think it's worth to do the deep clean up changes.

So I guess no need to backport it (the problem has been there for many years, and it doesn't really block daily work, just bad user experience).

File: routers/web/repo/compare.go [hunk 8]
```diff
@@ -313,42 +285,10 @@ func ParseCompareInfo(ctx *context.Context) *git_service.CompareInfo {
 		}
 	}
 
-	has := headRepo != nil
```
Comment (wxiaoguang) [inline routers/web/repo/compare.go:316]: To reviewers: since long time ago, headRepo can never be nil here.

File: routers/web/repo/pull.go [hunk 9]
```diff
@@ -1281,23 +1281,19 @@ func PullsNewRedirect(ctx *context.Context) {
 // CompareAndPullRequestPost response for creating pull request
 func CompareAndPullRequestPost(ctx *context.Context) {
 	form := web.GetForm(ctx).(*forms.CreateIssueForm)
-	ctx.Data["Title"] = ctx.Tr("repo.pulls.compare_changes")
-	ctx.Data["PageIsComparePull"] = true
-	ctx.Data["IsDiffCompare"] = true
-	ctx.Data["PullRequestWorkInProgressPrefixes"] = setting.Repository.PullRequest.WorkInProgressPrefixes
-	ctx.Data["IsAttachmentEnabled"] = setting.Attachment.Enabled
-	upload.AddUploadContext(ctx, "comment")
-	ctx.Data["HasIssuesOrPullsWritePermission"] = ctx.Repo.Permission.CanWrite(unit.TypePullRequests)
```
Comment (wxiaoguang) [inline routers/web/repo/pull.go:1290]: To reviewers: frontend already uses "form-fetch-action". Backend code can be simplified, only respond JSON

**Comment by bircni** [comment]
@wxiaoguang would really Like to backport as this bothered us very much today and will still do in the next few weeks/months

**Comment by wxiaoguang** [comment]
OK, maybe you can use the early commits as backport.

**Review by wxiaoguang — APPROVED** [review]

**Comment by silverwind** [comment]
Small error-message fixup added in https://github.com/go-gitea/gitea/pull/37470/changes/109fef5dcf43e984584e3e8e728e1e12c3bd9057.

**Review by silverwind — APPROVED** [review]

**Comment by wxiaoguang** [comment]
-> Refactor compare diff/pull page (1) #37481
