### PR TITLE
Multiple Queue improvements: LevelDB Wait on empty, shutdown empty shadow level queue, reduce goroutines etc

### LINKED ISSUE #15542: High Idle CPU usage (fresh install)
- Gitea version (or commit ref): 1.14.1 (rootless)
- Git version: 2.30.2
- Operating system: Debian 10, amd64, Intel Celeron N4100 (quad-core 1.1 GHz, up to 2.4 GHz)
- Docker: Docker 19.03.13, Compose: 1.27.4
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

I have a high idle CPU usage with my upgraded gitea server, so I tried a fresh deployment and have the same issue. 
After a fresh install (even 1 hour after) the CPU% usage is about 5% of my system. One user, no repository. 
In my testing VM (also Debian 10, 1 CPU thread only) the idle CPU% usage is about 0,1% (with the exact same docker-compose.yml and configuration). 
This happens with 14.1 root or rootless version. (haven't tried others)

I know 5% is not that high, but should it really be that much with a fresh install and while idle?

According to htop the CPU is used by /usr/local/bin/gitea -c /etc/gitea/app.ini web. I've set the logging to debug but there's no logs when being idle. 

Any help is appreciated :)

## Screenshots

gitea1
gitea2

### LINKED ISSUE #15776: queue: Flaky test TestLevelQueue
Can reproduce this locally somewhat rarely. [CI failure example](https://drone.gitea.io/go-gitea/gitea/39472/2/12):

```bash
$ while true; do go test -count=1 -run TestLevelQueue ./modules/queue; done
ok    code.gitea.io/gitea/modules/queue 0.457s
ok    code.gitea.io/gitea/modules/queue 0.452s
ok    code.gitea.io/gitea/modules/queue 0.445s
2021/05/07 19:46:40 ...les/queue/manager.go:134:Add() [T] Queue Manager registered: queue-1 (QID: 1)
2021/05/07 19:46:40 ...ue/queue_bytefifo.go:96:Run() [D] level:  Starting
2021/05/07 19:46:40 ...ue/queue_bytefifo.go:104:Run() [T] level:  Waiting til closed
2021/05/07 19:46:40 ...ue/queue_bytefifo.go:147:readToChan() [T] level : Task found: &queue.testData{TestString:"A", TestInt:1}
2021/05/07 19:46:40 .../queue/workerpool.go:251:commonRegisterWorkers() [T] WorkerPool: 1 (for queue-1) adding 1 workers with group id: 1
2021/05/07 19:46:40 .../queue/workerpool.go:93:zeroBoost() [W] WorkerPool: 1 (for queue-1) has zero workers - adding 5 temporary workers for 5m0s
2021/05/07 19:46:40 ...ue/queue_bytefifo.go:147:readToChan() [T] level : Task found: &queue.testData{TestString:"B", TestInt:2}
2021/05/07 19:46:40 .../queue/workerpool.go:420:doWork() [T] Handling: 1 data, [0xc00065edf8]
2021/05/07 19:46:40 .../queue/workerpool.go:420:doWork() [T] Handling: 1 data, [0xc00000ed98]
2021/05/07 19:46:40 ...ue/queue_bytefifo.go:156:Shutdown() [T] level:  Shutting down
2021/05/07 19:46:40 ...ue/queue_bytefifo.go:164:Shutdown() [D] level:  Shutdown
2021/05/07 19:46:40 ...ue/queue_bytefifo.go:106:Run() [T] level:  Waiting til done
2021/05/07 19:46:40 .../queue/workerpool.go:396:doWork() [T] Worker shutting down
2021/05/07 19:46:40 .../queue/workerpool.go:396:doWork() [T] Worker shutting down
2021/05/07 19:46:40 .../queue/workerpool.go:396:doWork() [T] Worker shutting down
2021/05/07 19:46:40 .../queue/workerpool.go:396:doWork() [T] Worker shutting down
2021/05/07 19:46:40 .../queue/workerpool.go:396:doWork() [T] Worker shutting down
2021/05/07 19:46:40 .../queue/workerpool.go:396:doWork() [T] Worker shutting down
2021/05/07 19:46:40 ...ue/queue_bytefifo.go:109:Run() [T] level:  Waiting til cleaned
2021/05/07 19:46:40 .../queue/workerpool.go:309:CleanUp() [T] WorkerPool: 1 CleanUp
2021/05/07 19:46:40 .../queue/workerpool.go:321:CleanUp() [T] WorkerPool: 1 CleanUp Done
2021/05/07 19:46:40 ...ue/queue_bytefifo.go:174:Terminate() [T] level:  Terminating
2021/05/07 19:46:40 ...ue/queue_bytefifo.go:156:Shutdown() [T] level:  Shutting down
2021/05/07 19:46:40 ...ue/queue_bytefifo.go:164:Shutdown() [D] level:  Shutdown
2021/05/07 19:46:40 ...ue/queue_bytefifo.go:186:Terminate() [D] level:  Closing with 2 tasks left in queue
2021/05/07 19:46:40 ...ue/queue_bytefifo.go:191:Terminate() [D] level:  Terminated
2021/05/07 19:46:41 ...les/queue/manager.go:134:Add() [T] Queue Manager registered: queue-2 (QID: 2)
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:96:Run() [D] level:  Starting
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:104:Run() [T] level:  Waiting til closed
2021/05/07 19:46:41 .../queue/workerpool.go:251:commonRegisterWorkers() [T] WorkerPool: 2 (for queue-2) adding 1 workers with group id: 1
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:147:readToChan() [T] level : Task found: &queue.testData{TestString:"A", TestInt:1}
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:147:readToChan() [T] level : Task found: &queue.testData{TestString:"B", TestInt:2}
2021/05/07 19:46:41 .../queue/workerpool.go:412:doWork() [T] Handling: 2 data, [0xc000d085d0 0xc000d08708]
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:156:Shutdown() [T] level:  Shutting down
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:164:Shutdown() [D] level:  Shutdown
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:156:Shutdown() [T] level:  Shutting down
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:164:Shutdown() [D] level:  Shutdown
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:174:Terminate() [T] level:  Terminating
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:156:Shutdown() [T] level:  Shutting down
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:106:Run() [T] level:  Waiting til done
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:164:Shutdown() [D] level:  Shutdown
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:174:Terminate() [T] level:  Terminating
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:156:Shutdown() [T] level:  Shutting down
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:164:Shutdown() [D] level:  Shutdown
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:186:Terminate() [D] level:  Closing with 0 tasks left in queue
2021/05/07 19:46:41 ...ue/queue_bytefifo.go:191:Terminate() [D] level:  Terminated
--- FAIL: TestLevelQueue (0.70s)
    queue_disk_test.go:21:
          Error Trace:  queue_disk_test.go:21
                              workerpool.go:421
                              workerpool.go:276
                              asm_amd64.s:1371
          Error:        Should be true
          Test:         TestLevelQueue
    queue_disk_test.go:21:
          Error Trace:  queue_disk_test.go:21
                              workerpool.go:421
                              workerpool.go:276
                              asm_amd64.s:1371
          Error:        Should be true
          Test:         TestLevelQueue
    queue_disk_test.go:73:
          Error Trace:  queue_disk_test.go:73
          Error:        Not equal:
                        expected: "A"
                        actual  : "B"

                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1 +1 @@
                        -A
                        +B
          Test:         TestLevelQueue
    queue_disk_test.go:74:
          Error Trace:  queue_disk_test.go:74
          Error:        Not equal:
                        expected: 1
                        actual  : 2
          Test:         TestLevelQueue
    queue_disk_test.go:77:
          Error Trace:  queue_disk_test.go:77
          Error:        Not equal:
                        expected: "B"
                        actual  : "A"

                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1 +1 @@
                        -B
                        +A
          Test:         TestLevelQueue
    queue_disk_test.go:78:
          Error Trace:  queue_disk_test.go:78
          Error:        Not equal:
                        expected: 2
                        actual  : 1
          Test:         TestLevelQueue
FAIL
FAIL  code.gitea.io/gitea/modules/queue 0.781s
FAIL
ok    code.gitea.io/gitea/modules/queue 0.444s
ok    code.gitea.io/gitea/modules/queue 0.485s
ok    code.gitea.io/gitea/modules/queue 0.450s
ok    code.gitea.io/gitea/modules/queue 0.449s
ok    code.gitea.io/gitea/modules/queue 0.448s
ok    code.gitea.io/gitea/modules/queue 0.445s
ok    code.gitea.io/gitea/modules/queue 0.445s
ok    code.gitea.io/gitea/modules/queue 0.442s
ok    code.gitea.io/gitea/modules/queue 0.449s
```

### PR DESCRIPTION
**Pull request by zeripath**
* LevelDB queues should wait on empty instead of polling.
* The shadow levelDB queue can be shutdown if/when the level db is empty in persistable-channel queue
* ByteFIFOQueue readToChan doesn't need a separate goroutine
* Change the cancel function on AddWorkers to remove the PID from the queue without additional goroutine
* Simplify the zero boost workers to also self-tidy-up without additional goroutine.
* Within Graceful Manager coalesce the shutdownfns etc into a list of functions that get run at shutdown rather then have them run at goroutines blocked on selects.
* Remove the context lock in the RunWithShutdownFns calls as these can just be part of the AtShutdown call as necessary
* Make ChannelQueues and ChannelUniqueQueues Flush as shutdown
* UniquePersistableChannelQueues don't have individual workers so don't show them as having this.

Related #15542
Partial Fixes #15542 

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
Ref: #15542

**Comment by silverwind** [comment]
Contains fix for https://github.com/go-gitea/gitea/issues/15776.

**Review by silverwind — APPROVED** [review]

File: modules/graceful/manager.go [hunk 1]
```diff
@@ -314,25 +329,20 @@ func (g *Manager) InformCleanup() {
...
-	select {
-	case <-g.Done():
-		return ErrTerminate
-	default:
-		return nil
-	}
+	return g.done.Err()
 }
 
 // Value allows the manager to be viewed as a context.Context done at Terminate, it has no values
```
Comment (6543) [inline modules/graceful/manager.go]: .. it has no values

still the case?

Comment (zeripath) [reply modules/graceful/manager.go]: not necessarily. Have updated the comment. Sorry about that.

File: modules/queue/bytefifo.go [hunk 2]
```diff
@@ -4,14 +4,16 @@
 
 package queue
 
+import "context"
+
 // ByteFIFO defines a FIFO that takes a byte array
 type ByteFIFO interface {
 	// Len returns the length of the fifo
-	Len() int64
+	Len(ctx context.Context) int64
```
Comment (lunny) [inline modules/queue/bytefifo.go:12]: Since these operations are very quick, I don't think a `context.Context` is necessary, Only those functions which will has a loop or will spend many time should use a `context.Context`. And also, the interface is ugly.

File: modules/queue/queue_channel.go [hunk 3]
```diff
@@ -75,6 +81,39 @@ func (q *ChannelQueue) Push(data Data) error {
 	return nil
 }
 
+// Shutdown processing from this queue
+func (q *ChannelQueue) Shutdown() {
+	log.Trace("ChannelQueue: %s Shutting down", q.name)
+	select {
```
Comment (lunny) [inline modules/queue/queue_channel.go:88]: invoke `q.shudownCancel()` before waiting for the `q.shutdownCtx.Done`. And we could have a timeout wait on the same select and return directly if timeout

File: modules/queue/bytefifo.go (hunk 2 above)
Comment (zeripath) [reply modules/queue/bytefifo.go:12]: Redis V8 has ctx for this.

File: modules/queue/queue_channel.go (hunk 3 above)
Comment (zeripath) [reply modules/queue/queue_channel.go:88]: If you do that multiple calls to shutdown will invoke flushers. If you have this select block you only create a terminate ctx flusher on the first shutdown.

File: modules/queue/bytefifo.go (hunk 2 above)
Comment (zeripath) [reply modules/queue/bytefifo.go:12]: https://github.com/go-redis/redis/blob/f7ac48d4d5490cbf0d166b9f42dba9e62483b77e/commands.go#L180

Comment (6543) [reply modules/queue/bytefifo.go:12]: yes can remember this ... :X

File: modules/queue/queue_channel.go (hunk 3 above)
Comment (zeripath) [reply modules/queue/queue_channel.go:88]: Ah I think you've misunderstood what shutdownCancel is - it's the CancelFunc for the shutdownCtx. I've renamed things to make them a little clearer.

File: modules/queue/bytefifo.go (hunk 2 above)
Comment (zeripath) [reply modules/queue/bytefifo.go:12]: This explicit passing in of the correct context also fixes an issue with Tasks left in the queue always being reported as -1

**Comment by 6543** [comment]
@zeripath would be nice if you have time to resolve this conflict :)

**Comment by zeripath** [comment]
just on it @6543

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
🚀
