### PR TITLE
User facing messages for AGit errors

### LINKED ISSUE #32965: Better end user visibility for failures in agit PRs
### Feature Description

The error messages in agit PRs aren't very visible to the end user. I think that adding an error label for fails would make them pop out more (if one has color enabled). See screenshots for full options.

I encountered this while trying to [submit an agit PR to docs](https://gitea.com/gitea/docs/issues/127), which uncovered a missing UserMsg, which would've been helpful:
https://github.com/go-gitea/gitea/blob/7553ae1a57a2d017b8bb1024ad95b6918716ddb2/routers/private/hook_proc_receive.go#L31-L34
and I've glanced over it before, so I think having a color before it would be helpful.

Similarly an instruction for setting up branch tracking would be a good improvement - no idea how to set it up though.

### Screenshots

image
Possible options:
image

### PR DESCRIPTION
**Pull request by TheFox0x7**
Adds user facing messages to errors when submitting agit pull request
Tries to highlight the returned error more and fixes agit suggestion to create PR on first submission.

Closes: https://github.com/go-gitea/gitea/issues/32965

### CODE REVIEW

File: cmd/hook.go [hunk 1]
```diff
@@ -705,7 +705,8 @@ Gitea or set your environment appropriately.`, "")
 
 	if err == nil {
 		for _, res := range resp.Results {
-			hookPrintResult(res.ShouldShowMessage, res.IsCreatePR, res.HeadBranch, res.URL)
+			// AGit always creates a pull request so there is no point in prompting user to create one
+			hookPrintResult(res.ShouldShowMessage, false, res.HeadBranch, res.URL)
```
Comment (lunny) [inline cmd/hook.go]: But the backend may return true or false, why should we ignore the returned value? Maybe we should change the router level.

Comment (TheFox0x7) [reply cmd/hook.go]: I think I've moved it in a more fitting spot now.

File: routers/private/hook_proc_receive.go [hunk 2]
```diff
@@ -27,6 +30,14 @@ func HookProcReceive(ctx *gitea_context.PrivateContext) {
 	if err != nil {
 		if repo_model.IsErrUserDoesNotHaveAccessToRepo(err) {
 			ctx.Error(http.StatusBadRequest, "UserDoesNotHaveAccessToRepo", err.Error())
+		} else if errors.Is(err, issues_model.ErrMustCollaborator) {
+			ctx.JSON(http.StatusUnauthorized, private.Response{
+				Err: err.Error(), UserMsg: string(ctx.Tr("repo.pulls.new.must_collaborator")),
```
Comment (hiifong) [inline routers/private/hook_proc_receive.go]: Currently, gitea's echo does not seem to use i18n

Comment (TheFox0x7) [reply routers/private/hook_proc_receive.go]: True, I could hardcode that string as a solution. It doesn't feel more correct though.

File: routers/private/hook_proc_receive.go [hunk 3]
```diff
@@ -27,6 +30,14 @@ func HookProcReceive(ctx *gitea_context.PrivateContext) {
 	if err != nil {
 		if repo_model.IsErrUserDoesNotHaveAccessToRepo(err) {
 			ctx.Error(http.StatusBadRequest, "UserDoesNotHaveAccessToRepo", err.Error())
```
Comment (TheFox0x7) [inline routers/private/hook_proc_receive.go]: I don't know how to actually trigger this if-branch but when I tried this style of returning error in any of the below cases it errored out with `Internal Server Error Decoding Failed`. So I'm assuming it might be an error.
Am I correct or am I missing something?

Comment (wxiaoguang) [reply routers/private/hook_proc_receive.go]: I think you are right. IIRC the permission check should have already been done before this handler?

(and maybe we could remove this `if` check, just let `else` handle all other cases, it's also fine to keep it as-is)

File: routers/private/hook_proc_receive.go (hunk 2 above)
Comment (wxiaoguang) [reply routers/private/hook_proc_receive.go]: I also think hard-coding the response message is better. At least it is consistency with existing code.

If we'd like to introduce i18n support, it needs more work.

----

Actually, using `ctx.Tr` could cause some edge cases here since it doesn't have correct i18n context: some users might have set non-English language as the default language (yes, Gitea supports that: Remove legacy unmaintained packages, refactor to support change default locale (#19308))

Comment (TheFox0x7) [reply routers/private/hook_proc_receive.go]: Fair, I forgot about that default might not be English. I guess supporting that would require passing, different locale to git first and that's out of scope here.
I'll hardcode it then.

File: routers/private/hook_proc_receive.go (hunk 3 above)
Comment (TheFox0x7) [reply routers/private/hook_proc_receive.go]: `issue_service.AddAssigneeIfNotAssigned` can return it if user can't be assigned and it's called by `pull_service.NewPullRequest`, which is called from `agit.ProcReceive`.
So it is possible but that's function is called only if there are assignees in opts, which agit doesn't set so it should never get called.

> (and maybe we could remove this if check, just let else handle all other cases, it's also fine to keep it as-is)

I'm not sure what you're thinking of here

Comment (wxiaoguang) [reply routers/private/hook_proc_receive.go]: Either is fine. If it is unclear, I think we could leave a comment and keep it as-is.

File: routers/private/hook_proc_receive.go [hunk 4]
```diff
@@ -25,8 +27,14 @@ func HookProcReceive(ctx *gitea_context.PrivateContext) {
...
+		if errors.Is(err, issues_model.ErrMustCollaborator) {
+			ctx.JSON(http.StatusUnauthorized, private.Response{
+				Err: err.Error(), UserMsg: "You must be a collaborator to create pull request.",
+			})
+		} else if errors.Is(err, user_model.ErrBlockedUser) {
+			ctx.JSON(http.StatusUnauthorized, private.Response{
+				Err: err.Error(), UserMsg: "Cannot create pull request because you are blocked by the repository owner.",
+			})
 		} else {
 			log.Error(err.Error())
```
Comment (wxiaoguang) [inline routers/private/hook_proc_receive.go]:
```suggestion
			log.Error("agit.ProcReceive failed: %v", err)
```

File: cmd/serv.go [hunk 5]
```diff
@@ -104,7 +104,9 @@ func fail(ctx context.Context, userMessage, logMsgFmt string, args ...any) error
 	// There appears to be a chance to cause a zombie process and failure to read the Exit status
 	// if nothing is outputted on stdout.
 	_, _ = fmt.Fprintln(os.Stdout, "")
-	_, _ = fmt.Fprintln(os.Stderr, "Gitea:", userMessage)
+	_, _ = fmt.Fprintln(os.Stderr, "error:")
+	_, _ = fmt.Fprintln(os.Stderr, "error:", userMessage)
+	_, _ = fmt.Fprintln(os.Stderr, "error:")
```
Comment (wxiaoguang) [inline cmd/serv.go:110]: Just a question: why it needs 2 empty lines around the message?

Comment (TheFox0x7) [reply cmd/serv.go:110]: It doesn't. I figured it would better and get more attention if it's separated from the git error. It's purely stylistic to give the error some breathing room.
image

I'm not stuck on this

Comment (wxiaoguang) [reply cmd/serv.go:110]:
```suggestion
	// add extra empty lines to separate our message from other git errors to get more attention
	_, _ = fmt.Fprintln(os.Stderr, "error:")
	_, _ = fmt.Fprintln(os.Stderr, "error:", userMessage)
	_, _ = fmt.Fprintln(os.Stderr, "error:")
```

**Review by wxiaoguang — APPROVED** [review]

**Review by hiifong — APPROVED** [review]

**Review by lunny — APPROVED** [review]
I will remove the `IsCreatePR` in the future PRs.
