### PR TITLE
Fix localization texts that contain semicolon

### LINKED ISSUE #2887: Some translation values in crowding containing semicolon are wrong in crowdin
If localization text contains `;` it's treated as comment in crowdin as per ini file format. Currently used parser does not support escaping it (`\;`). That's way currently generated values when translated are wrong in other language ini files.

Related issue in go-ini library
https://github.com/go-ini/ini/issues/129

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #2887

### CODE REVIEW

**Comment by lafriks** [comment]
Currently crowdin has folowing for these keys for translation:
attels

And completly wrong html generated for localized ini files:
```
issues.add_label_at=` pievienoja <div class="ui label" style="color: %s" ; background-color: %s">%s</div> label %s`
```

**Comment by ethantkoenig** [comment]
Would it make more sense to just update the `i18n.Tr` helper to always do unescaping?

**Comment by lafriks** [comment]
@ethantkoenig it's not under our control

File: modules/templates/helper.go [hunk 1]
```diff
@@ -159,6 +159,9 @@ func NewFuncMap() []template.FuncMap {
 			return setting.DisableGitHooks
 		},
 		"TrN": TrN,
+		"UnescapeBS": func(str string) string {
```
Comment (bkcsoft) [inline modules/templates/helper.go]: "BS"? I agree, but maybe we can name it better? 😂

Comment (lafriks) [reply modules/templates/helper.go]: BackSlash :) any suggestions for better name? :)

**Comment by lunny** [comment]
LGTM

File: modules/templates/helper.go (hunk 1 above)
Comment (ethantkoenig) [reply modules/templates/helper.go]: UnescapeLocale? It also took me a few minutes to figure out what BS stood for

Comment (bkcsoft) [reply modules/templates/helper.go]: I thought it actually stood for bullshit 😂 I agree with @ethantkoenig that it should be `UnescapeLocale` 🙂

**Comment by bkcsoft** [comment]
One alternative is to wrap the `i18n.Tr` command and start using that instead.

File: modules/templates/helper.go (hunk 1 above)
Comment (lafriks) [reply modules/templates/helper.go]: It can stand for that also :) It can be also temporary fix if unknwon fixes that in go-ini library to support such escape as it is per ini file format. That is why I did not want it to be so intrusive

**Comment by lafriks** [comment]
@ethantkoenig @bkcsoft fixed to better name

As for replacing `i18n.Tr` function I would not do that currently as there is still chance that go-ini at some point could be fixed and there would be no need for that

**Comment by ethantkoenig** [comment]
Okay, I still think adding a wrapper around `i18n.Tr` is worth doing at some point, but perhaps outside the scope

**Comment by ethantkoenig** [comment]
@lafriks If this is just a temporary hack until `go-ini` is fixed, could we add a `TODO` to eventually remove this?

**Comment by lafriks** [comment]
@ethantkoenig done

**Comment by ethantkoenig** [comment]
LGTM
