### PR TITLE
Discard unread data of `git cat-file`

### LINKED ISSUE #29101: Invalid output in `batch_reader.go`
`strconv.ParseInt: parsing "number": invalid syntax`

Steps to reproduce:
1. Create a repository with actions enabled
2. Create a file `/.gitea/workflows` with the content `not a number`
3. Create a file `/.github/workflows` with the content `not a number`
4. Open the page `/<owner>/<repo>/actions`
5. If no error is shown, refresh the page multiple times until an error occurs

The reason is this code
https://github.com/go-gitea/gitea/blob/ce9978bfd4e035ed065b02b28e02905674320b6a/modules/actions/workflows.go#L47-L50

which fails in line 179
https://github.com/go-gitea/gitea/blob/ce9978bfd4e035ed065b02b28e02905674320b6a/modules/git/batch_reader.go#L152-L181

If the error occurs the code tries to parse `not a number` as output of the batch reader. A normal output looks like `8b2bfd3a117fcb7ae93f93616cb2f7a9706c513a tree 104`. I don't know how the content of a file can be present here. And even worse is that it does not fail every time. If I create only one `workflows` file it does not fail but that may just be a timing issue.

### Git Version

2.43.0, non-gogit

### PR DESCRIPTION
**Pull request by KN4CK3R**
Fixes #29101
Related #29298

Discard all read data to prevent misinterpreting existing data. Some discard calls were missing in error cases.

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

File: modules/git/blob_nogogit.go [hunk 1]
```diff
@@ -104,25 +103,6 @@ func (b *blobReader) Read(p []byte) (n int, err error) {
...
-		}
-	}
-	if b.n == 0 {
-		_, err := b.rd.Discard(1)
-		b.n--
-		return err
-	}
-	return nil
+
+	return DiscardFull(b.rd, b.n+1)
```
Comment (KN4CK3R) [inline modules/git/blob_nogogit.go:107]: Note: Changed behaviour here. Old code just double called `b.cancel` but new code may error. But the go spec defines double closes as undefined behaviour, so it should be fine.

**Comment by KN4CK3R** [comment]
Reason why the code sometimes works and sometimes not is in #29298.

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]
