### PR TITLE
Prevent NPE on partial match of compare URL and allow short SHA1 compare URLs (#18472)

### LINKED ISSUE #18471: Gitea 1.16.0 crash when click on repo link
### Gitea Version

1.16.0

### Git Version

2.30.2

### Operating System

docker in ubuntu focal

### How are you running Gitea?

I run gitea and drone with docker-compose.
image: gitea/gitea:latest

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/hypernics/12552cd6b64454fd9d5bedbe61571b91

### Description

After upgrading to 1.16.0 with docker-compose, when I click on a repo link some of them crash the gitea server.
It worked with 1.15.x
I just clicked all of my project repo links and as I see all my Laravel project crash the server, python and javascript projects are working.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Gusted**
Backport #18472

- Prevent NPE panic when the full compare url regex isn't matched
- Allow the usage of a shorter sha1 being used.

Fix #18471

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

File: modules/markup/html.go [hunk 1]
```diff
@@ -944,6 +944,13 @@ func comparePatternProcessor(ctx *RenderContext, node *html.Node) {
 			return
 		}
 
+		// Ensure that every group (m[0]...m[7]) has a match
+		for i := 0; i < 8; i++ {
```
Comment (zeripath) [inline modules/markup/html.go:948]: This is unfortunately incorrect on partial matches too.

`len(m)` needs to be checked to ensure that it is at least 8
