### PR TITLE
Fix mime-type detection for HTTP server

### LINKED ISSUE #18347: serviceworker.js failed to register (on windows)
### Gitea Version

1.16.0-rc1

### Git Version

git version 2.34.1.windows.1

### Operating System

Windows 10 21H1 (build 19043.1466)

### How are you running Gitea?

Downloaded gitea-1.16.0-rc1-gogit-windows-4.0-amd64.exe from the github releases page.  
stopped windows service
Copied over top to replace existing gitea.exe
restarted windows service

### Database

MSSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

In edge & chrome, the serviceworker.js fails to install with an error logged to the console.

DOMException: Failed to register a ServiceWorker for scope ('http://localhost:3000/assets/') with script ('http://localhost:3000/assets/serviceworker.js'): The script has an unsupported MIME type ('text/plain').

First appeared when i installed version 1.15.10

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by wxiaoguang**
As the title, all information is in the comment.

Closes #18347

* https://github.com/go-gitea/gitea/issues/18347

```
// detectWellKnownMimeType will return the mime-type for a well-known file ext name
// The purpose of this function is to bypass the unstable behavior of Golang's mime.TypeByExtension
// mime.TypeByExtension would use OS's mime-type config to overwrite the well-known types (see its document).
// If the user's OS has incorrect mime-type config, it would make Gitea can not respond a correct Content-Type to browsers.
// For example, if Gitea returns `text/plain` for a `.js` file, the browser couldn't run the JS due to security reasons.
// detectWellKnownMimeType makes the Content-Type for well-known files stable.
```

### CODE REVIEW

**Review by zeripath — APPROVED** [review]
Lgtm Although I wonder if we should be using an external package for this.

**Comment by wxiaoguang** [comment]
>  if we should be using an external package for this.

IMO, this feature is very trivial, not worthy to introduce a new mime package. And usually we do not need to update the mime types frequently.

**Review by Gusted — APPROVED** [review]

File: modules/public/mime_types.go [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+	".mjs":  "text/javascript; charset=utf-8",
+	".pdf":  "application/pdf",
+	".png":  "image/png",
+	".svg":  "image/svg+xml",
+	".wasm": "application/wasm",
+	".webp": "image/webp",
+	".xml":  "text/xml; charset=utf-8",
+
+	// well, there are some types missing from the builtin list
+	".txt": "text/plain; charset=utf-8",
```
Comment (Gusted) [inline modules/public/mime_types.go:29]: Hmm, thought: 

Isn't it risky to set charset utf-8 here? It could UTF-16 or alike...

Comment (wxiaoguang) [reply modules/public/mime_types.go:29]: No problem here. Our mime types are only used inside `modules/public` package, which only serves files in `/assets/`, they are either from Gitea source code or custom files in `GITEA_CUSTOM/public`, they can be guaranteed to be `utf-8` encoding.
