### PR TITLE
Fix 500 error viewing pull request when fork has pull requests disabled

### LINKED ISSUE #20826: Migration issue: PRs broken after upgrade to 1.17.0
### Description

After upgrading from 1.12.6 to 1.17.0, I'm running into an issue where any mergable PRs result in server error 500s. Merged PRs and WIP PRs display normally.

Relevant log lines:

```
2022/08/17 10:58:16 ...vices/pull/update.go:109:IsUserAllowedToUpdate() [E] [62fcc9c8] pr.BaseRepo.GetUnit(unit.TypePullRequests): Unit type does not exist: TypePullRequests
2022/08/17 10:58:16 ...ers/web/repo/pull.go:509:PrepareViewPullInfo() [E] [62fcc9c8] IsUserAllowedToUpdate: Unit type does not exist: TypePullRequests
```

I followed to recommended upgrade procedure (and also removed any custom templates we had in use previously). The upgrade seems to have gone OK otherwise. `gitea doctor` also doesn't show anything wrong.

If possible, a "quick fix" as a workaround for this error would be appreciated as we're currently unable to perform any merges in gitea which is a showstopper.

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.37.1

### Operating System

CentOS Linux 7.9.2009

### How are you running Gitea?

From binary downloaded from gitea.io

### Database

MySQL

### PR DESCRIPTION
**Pull request by brechtvl**
Swallow error just like in #20839, for the case where there is no protected branch.

Fixes #20826 for me, though I can't tell if this now covers all cases.

### CODE REVIEW

File: services/pull/update.go [hunk 1]
```diff
@@ -117,6 +117,9 @@ func IsUserAllowedToUpdate(ctx context.Context, pull *issues_model.PullRequest,
 			return false, false, err
 		}
 		prUnit, err := pr.BaseRepo.GetUnit(ctx, unit.TypePullRequests)
+		if repo_model.IsErrUnitTypeNotExist(err) {
+			return false, false, nil
+		}
 		if err != nil {
```
Comment (jolheiser) [inline services/pull/update.go]: Can this be moved inside the `err != nil` block?

**Review by jolheiser — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by jolheiser** [comment]
@brechtvl It may be beneficial if you select the "allow edits by maintainers" checkbox, as we will have to update the PR branch with `main` prior to merging (for all your PRs). 
This just lets us do it instead of having to bug you for it after each merge. 🙂

**Comment by brechtvl** [comment]
I don't see that checkbox, it seems because of a GitHub limitation regarding organizations? https://github.com/community/community/discussions/5634

I rebased this PR on main now, and I guess for future PRs I can use my personal account.

**Comment by jolheiser** [comment]
Ah thanks, my bad for not checking it came from the org. 😅
