### PR TITLE
Add force_merge to merge request and fix checking mergable

### LINKED ISSUE #23000: Admin Merge broken on 1.18.4
### Description

I have a branch with a Branch Protection (at least 1 approval and a check that has to run)

image

The UI tells me I still can merge it anyway since i'm Admin. But when I try to merge it 

The error message
> This pull request is not ready to be merged, check review status and status checks.
Appears 

Could also reproduce on try.gitea.io with `[Powered by Gitea](https://gitea.io/) Version: 1.19.0+dev-521-g2b3f12f6f Page: 99ms Template: 11ms`

Steps To Reproduce
- Be admin in repository
- Setup branch protection for any branch, require 1 approval
- Create a pull request pointing at the protected branch
- Try to merge without having 1 approval (with the red admin merge button)

### Gitea Version

1.18.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Irrelevant

### Database

None

### PR DESCRIPTION
**Pull request by wolfogre**
Fix #23000.

The bug was introduced in #22633, and it seems that it has been noticed: https://github.com/go-gitea/gitea/pull/22633#discussion_r1095395359 .

However, #22633 did nothing wrong, the logic should be "check if they is admin only when `force` is true".

So we should provide the `ForceMerge` when merging from UI.

After this, an admin can also send a normal merge request with `ForceMerge` false. So it fixes a potential bug: if the admin doesn't want to do a force merge, they just see the green "Merge" button and click it. At the same time, the status of the PR changed, and it shouldn't be merged now, so the admin could send an unexpected force merge.

In addition, I updated `ForceMerge *bool` to `ForceMerge bool`, I don't see the reason to use a pointer.

And fixed the logic of CheckPullMergable to handle auto merge and force merge correctly.

### CODE REVIEW

File: services/forms/repo_form.go [hunk 1]
```diff
@@ -604,7 +604,7 @@ type MergePullRequestForm struct {
 	MergeMessageField      string
 	MergeCommitID          string // only used for manually-merged
 	HeadCommitID           string `json:"head_commit_id,omitempty"`
-	ForceMerge             *bool  `json:"force_merge,omitempty"`
+	ForceMerge             bool   `json:"force_merge,omitempty"`
```
Comment (lunny) [inline services/forms/repo_form.go:607]: But then it's a break change?

Comment (wolfogre) [reply services/forms/repo_form.go:607]: I don't think so, the default value `false` has the same effect as `nil` when there's no `force_merge` in API requests or form requests. So it breaks nothing.

File: web_src/js/components/PullRequestMergeForm.vue [hunk 2]
```diff
@@ -167,6 +169,7 @@ export default {
       this.deleteBranchAfterMerge = this.mergeForm.defaultDeleteBranchAfterMerge;
       this.mergeTitleFieldValue = this.mergeStyleDetail.mergeTitleFieldText;
       this.mergeMessageFieldValue = this.mergeStyleDetail.mergeMessageFieldText;
+      this.forceMerge = this.mergeForm.canMergeNow && !this.mergeForm.allOverridableChecksOk;
```
Comment (wxiaoguang) [inline web_src/js/components/PullRequestMergeForm.vue]: IIRC canMergeNow and allOverridableChecksOk are all constant values in this component.

So the `forceMerge` assigning could be put in `created`, or just make it as a `computed` value.

----

ps: why `toggleActionForm` needs to assign other values: because other values could be changed by users, so `toggleActionForm` must reset them to default.

**Review by lunny — APPROVED** [review]

**Review by Zettat123 — APPROVED** [review]
