### PR TITLE
Make repo migration cancelable and fix various bugs

### LINKED ISSUE #12845: Migration: add Cancel button
currently you you have to go to `<gitea-url>/<owner>/<migrating-repo>/settings` and use the "Delete Repo" button, to cancel migration

A cancel Button would be nice

### LINKED ISSUE #24601: [Summary] Migration progress problems
This issue only lists some issues in my mind, feel free to correct it / edit it.

At the moment, Gitea's migration feature has some problems:

1. The migration is not cancel-able (related to #12845 IMO it might be able to be done by other approaches, eg: read some status from database, not blocked by the cluster)
2. If a migration is in progress and Gitea process stops, the repo seems stuck in a unrecoverable state (not sure whether it is still a problem in latest release)
3. The migration may have some errors, users have to read Gitea's server logs to see what happens
4. Some big repositories need long time, which exceed the default timeout and the migration fails without UI feedback.

### PR DESCRIPTION
**Pull request by wxiaoguang**
Replace #12917

Close #24601
Close #12845

image

image

image

image

### CODE REVIEW

File: services/migrations/gitea_uploader.go [hunk 1]
```diff
@@ -923,9 +923,8 @@ func (g *GiteaLocalUploader) CreateReviews(reviews ...*base.Review) error {
 func (g *GiteaLocalUploader) Rollback() error {
 	if g.repo != nil && g.repo.ID > 0 {
 		g.gitRepo.Close()
-		if err := models.DeleteRepository(g.doer, g.repo.OwnerID, g.repo.ID); err != nil {
-			return err
-		}
+
```
Comment (lunny) [inline services/migrations/gitea_uploader.go:926]: When and how the repository could be deleted?

Comment (wxiaoguang) [reply services/migrations/gitea_uploader.go:926]: "running" -> can be canceled.

"failed" -> can be deleted, if you visit that repo again.

File: templates/repo/migrate/migrating.tmpl [hunk 2]
```diff
@@ -32,10 +32,14 @@
...
 								<p id="repo_migrating_failed_error"></p>
 							</div>
-							{{if and .Failed .Permission.IsAdmin}}
+							{{if .Permission.IsAdmin}}
 								<div class="ui divider"></div>
 								<div class="item">
+									{{if .Failed}}
 									<button class="ui basic red show-modal button" data-modal="#delete-repo-modal">{{.locale.Tr "repo.settings.delete"}}</button>
+									{{else}}
+									<button class="ui basic red show-modal button" data-modal="#cancel-repo-modal">{{.locale.Tr "cancel"}}</button>
```
Comment (lunny) [inline templates/repo/migrate/migrating.tmpl:41]: So he need to cancel first and then delete?

Comment (wxiaoguang) [reply templates/repo/migrate/migrating.tmpl:41]: No if you visit the page again. I do not want to make the page too complex.

File: services/migrations/gitea_uploader.go (hunk 1 above)
Comment (wxiaoguang) [reply services/migrations/gitea_uploader.go:926]: "running" -> can be canceled.

"failed" -> can be deleted.

**Review by lunny — APPROVED** [review]

File: options/locale/locale_en-US.ini [hunk 3]
```diff
@@ -1055,6 +1055,8 @@ migrate.migrating_labels = Migrating Labels
 migrate.migrating_releases = Migrating Releases
 migrate.migrating_issues = Migrating Issues
 migrate.migrating_pulls = Migrating Pull Requests
+migrate.cancel_migrating_title = Cancel Migrating
```
Comment (yardenshoham) [inline options/locale/locale_en-US.ini]:
```suggestion
migrate.cancel_migrating_title = Cancel Migration
```

Comment (wxiaoguang) [reply options/locale/locale_en-US.ini]: I think `Migrating` is better, because it means "cancel this operation (migrating)"

`Migration` could also be fine, I am more or less netural.

File: options/locale/locale_en-US.ini [hunk 4]
```diff
@@ -1038,7 +1038,7 @@ migrated_from_fake = Migrated From %[1]s
 migrate.migrate = Migrate From %s
 migrate.migrating = Migrating from <b>%s</b> ...
 migrate.migrating_failed = Migrating from <b>%s</b> failed.
-migrate.migrating_failed.error = Error: %s
+migrate.migrating_failed.error = Failed to migrate: %s
```
Comment (yardenshoham) [inline options/locale/locale_en-US.ini:1041]: Is there a way to tell crowdin they should translate if the key wasn't changed?

Comment (wxiaoguang) [reply options/locale/locale_en-US.ini:1041]: Crowdin always does so (changed content also triggers re-translation)

File: options/locale/locale_en-US.ini (hunk 3 above)
Comment (yardenshoham) [reply options/locale/locale_en-US.ini]: I'm not a native English speaker but `Migration` sounded better to me

File: web_src/js/features/repo-migrate.js [hunk 5]
```diff
@@ -1,51 +1,55 @@
...
+    } finally {
+      if (doNextRefresh) {
+        setTimeout(syncTaskStatus, 2000);
       }
-    });
-  }
+    }
+  };
+
+  const _ = syncTaskStatus();
```
Comment (yardenshoham) [inline web_src/js/features/repo-migrate.js]: Why `const _`?
```suggestion
  syncTaskStatus();
```

Comment (wxiaoguang) [reply web_src/js/features/repo-migrate.js]: Nope, that's a "async" promise. silverwind also thinks it's good to declare that we do not wait for that promise explicitly.

https://docs.gitea.io/en-us/contributing/guidelines-frontend/#async-functions

File: routers/web/repo/migrate.go [hunk 6]
```diff
@@ -257,3 +258,19 @@ func setMigrationContextData(ctx *context.Context, serviceType structs.GitServic
...
 }
+
+func MigrateCancelPost(ctx *context.Context) {
+	migratingTask, err := admin_model.GetMigratingTask(ctx.Repo.Repository.ID)
+	if err != nil {
+		ctx.ServerError("GetMigratingTask", err)
+		return
+	}
+	if migratingTask.Status == structs.TaskStatusRunning {
+		taskUpdate := &admin_model.Task{ID: migratingTask.ID, Status: structs.TaskStatusFailed, Message: "canceled"}
```
Comment (yardenshoham) [inline routers/web/repo/migrate.go:270]: Localize `canceled`?

Comment (wxiaoguang) [reply routers/web/repo/migrate.go:270]: Almost all error messages here are returned by `err.Error()`, none of them is localized, so I think it's good to behave like them, no need to translate.

Comment (yardenshoham) [reply routers/web/repo/migrate.go:270]: This one is different because it's shown in the UI, no?

Comment (wxiaoguang) [reply routers/web/repo/migrate.go:270]: All  of them will be shown on the UI.

This one is special because it doesn't come from `err.Error()`

Comment (wxiaoguang) [reply routers/web/repo/migrate.go:270]: To make it come from `error`: `Message: errors.New("canceled").Error()`  😁

Comment (wxiaoguang) [reply routers/web/repo/migrate.go:270]: These errors are not translatable.


image

image

File: routers/web/repo/migrate.go [hunk 7]
```diff
@@ -257,3 +258,19 @@ func setMigrationContextData(ctx *context.Context, serviceType structs.GitServic
 	ctx.Data["Services"] = append([]structs.GitServiceType{structs.PlainGitService}, structs.SupportedFullGitService...)
 	ctx.Data["service"] = serviceType
 }
+
+func MigrateCancelPost(ctx *context.Context) {
+	migratingTask, err := admin_model.GetMigratingTask(ctx.Repo.Repository.ID)
+	if err != nil {
```
Comment (delvh) [inline routers/web/repo/migrate.go:264]: `if errors.Is(err, util.ErrNotExist) {…} else if err != nil {`?

Comment (wxiaoguang) [reply routers/web/repo/migrate.go:264]: ~~No difference, this handler is only for the special JS. JS only accepts 200, and retries for others.~~

Oops, not JS. But I think it could do nothing here, 404/500 is still the same for end users.

Comment (delvh) [reply routers/web/repo/migrate.go:264]: Given that I've already seen PRs doing nothing else than handling a `404` not as a `500`, I'd disagree.

Comment (wxiaoguang) [reply routers/web/repo/migrate.go:264]: No 404 or 500 any more, just redirect. 8f38e57ac5ce7761e3f52b5f1f6e238b8f29d76b

File: web_src/js/features/repo-migrate.js (hunk 5 above)
Comment (silverwind) [reply web_src/js/features/repo-migrate.js]: I'd question that recommendation now. I think it'd be better to just add a comment `// no await` to indicate that a returned promise was intentionally not awaited.

Comment (silverwind) [inline web_src/js/features/repo-migrate.js]:
```suggestion
  syncTaskStatus(); // no await
```

Comment (silverwind) [reply web_src/js/features/repo-migrate.js]: Feel free to update the linked document to this in this PR.

Comment (wxiaoguang) [reply web_src/js/features/repo-migrate.js]: Feel free to edit.

Comment (silverwind) [reply web_src/js/features/repo-migrate.js]: Will put a PR for this.

Comment (silverwind) [reply web_src/js/features/repo-migrate.js]: https://github.com/go-gitea/gitea/pull/24640

File: web_src/js/features/repo-migrate.js [hunk 8]
```diff
@@ -1,51 +1,55 @@
...
+    } finally {
+      if (doNextRefresh) {
+        setTimeout(syncTaskStatus, 2000);
       }
-    });
-  }
+    }
+  };
+
+  syncTaskStatus(); // no await
```
Comment (silverwind) [inline web_src/js/features/repo-migrate.js:54]: Could also use a IIFE in this case:

```js
(async function syncTaskStatus() {
  let doNextRefresh = true;
  try {
    doNextRefresh = await refresh();
  } finally {
    if (doNextRefresh) {
      setTimeout(syncTaskStatus, 2000);
    }
  }
})()
```

Comment (wxiaoguang) [reply web_src/js/features/repo-migrate.js:54]: It's not clearer than before.

**Review by silverwind — APPROVED** [review]
