### PR TITLE
Retry SSH key verification with additional CRLF if it failed

### LINKED ISSUE #21527: Command for verifying SSH key doesn't work under Windows
### Description

When verifying an SSH key, the Gitea settings page gives a command that (after adjusting for the correct key path) does not work in Windows, because the output produced by the command is different than on other OSes such as Linux

The same command given the same exact private key and token will produce 2 different outputs, depending on whether the command is run under PowerShell on Windows, or the terminal on Linux (in my case, via WSL). Included are screenshots showing the same command producing two different outputs, then the public key file being echoed to show that it is the same. When pasting the given signature into Gitea (including the 'BEGIN' and 'END' parts of the output), the output from Linux will be accepted, but the output from Windows will be rejected.

I'm not sure what command would work natively in Windows, but the UI should be adjusted to show either 1 command that does work for all operating systems, or multiple commands for each operating system.

Also a QOL fix i'd like to see, instead of `/path_to_your_pubkey` in the command, it should use the path where the public key is stored at by default, such as `~\.ssh\id_rsa.pub` on powershell and linux. Where you currently always have to modify the command, this would allow not having to modify the command in the majority of cases.

### Gitea Version

1.17.3 on docker installs, 1.18.0+dev-602-g6a0330979 on demo site

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

The problematic command in question:
image

Running the given command (with token replaced with "sample" for demonstration purposes) with adjusted path under PowerShell, then cat-ing the public key:
image

Running the given command (with token replaced with "sample" for demonstration purposes) with adjusted path under WSL, then cat-ing the public key:
image

Error given when pasting from Windows:
image

Success message when pasting from Linux:
image

### Git Version

_No response_

### Operating System

Windows 10 21H2 & 21H1

### How are you running Gitea?

This was tested via a Docker and Docker-Compose based install, as well as the try.gitea.io demo site

### Database

_No response_

### PR DESCRIPTION
**Pull request by nekrondev**
Windows-based shells will add a CRLF when piping the token into ssh-keygen command resulting in
verification error. This resolves #21527.

### CODE REVIEW

File: models/asymkey/ssh_key_verify.go [hunk 1]
```diff
@@ -30,7 +30,9 @@ func VerifySSHKey(ctx context.Context, ownerID int64, fingerprint, token, signat
 		return "", ErrKeyNotExist{}
 	}
 
-	if err := sshsig.Verify(bytes.NewBuffer([]byte(token)), []byte(signature), []byte(key.Content), "gitea"); err != nil {
+	// edge case for Windows based shells that will add CR LF if piped to ssh-keygen command
```
Comment (techknowlogick) [inline models/asymkey/ssh_key_verify.go]: Thanks for this PR. Could you instead check for the line-endings instead of validating twice?

Comment (nekrondev) [reply models/asymkey/ssh_key_verify.go]: Hi @techknowlogick I think this isn't possible. The token value processed by the method was generated by GT and signed remotely by the user (`echo -n "token" | ssh-keygen ...`). Now the user pipes the token + CRLFed input string to `ssh-keygen` and submits the signature output back to GT for verification. To check if the token was CRLFed on the users site we need to process the token twice: one none-CRLF version of the token and one with CRLF and check if both signature verifications fail with an error.

Comment (techknowlogick) [reply models/asymkey/ssh_key_verify.go]: Ah ok, thanks for that clarification. That makes complete sense :)

Comment (wxiaoguang) [reply models/asymkey/ssh_key_verify.go]: Oudated.

<details>

Still the question:

1. Why it's not possible? Could you do something like `if setting.IsWindows { use "\r\n" } else { for posix }`?
2. What if the user input already has the "\r\n"? Does it need to trim/strip some spaces ahead?
3. ps: I have difficulty to understand the meaning of "GT" in your comment, did you mean "Gitea"?

</details>

Comment (wxiaoguang) [reply models/asymkey/ssh_key_verify.go]: Hmm, I think I can understand the problem now.

File: models/asymkey/ssh_key_verify.go [hunk 2]
```diff
@@ -30,7 +30,9 @@ func VerifySSHKey(ctx context.Context, ownerID int64, fingerprint, token, signat
...
+	errcrlf := sshsig.Verify(bytes.NewBuffer([]byte(token+"\r\n")), []byte(signature), []byte(key.Content), "gitea")
+	if err := sshsig.Verify(bytes.NewBuffer([]byte(token)), []byte(signature), []byte(key.Content), "gitea"); err != nil && errcrlf != nil {
```
Comment (wxiaoguang) [inline models/asymkey/ssh_key_verify.go]: Maybe it could be like this:

1. Only try to verify for the original message
2. If it fails to verify the original message, then try to verify "windows style", then clean the error on success.

Then it doesn't need duplicate `sshsig.Verify` for POSIX users.

```suggestion
	err := sshsig.Verify(bytes.NewBuffer([]byte(token)), []byte(signature), []byte(key.Content), "gitea")
	if err != nil {
		// edge case for Windows based shells that will add CR LF if piped to ssh-keygen command
		if sshsig.Verify(bytes.NewBuffer([]byte(token+"\r\n")), []byte(signature), []byte(key.Content), "gitea") == nil {
			err = nil
		}
	}
	if err != nil {
```

Comment (nekrondev) [reply models/asymkey/ssh_key_verify.go]: Thanks for your suggestion @wxiaoguang I applied your commit into the PR. It clearly makes sense to reduce the verification call and attempt it only if the plain (un-CRLFed) token fails.

Another solution that comes to my mind would be the following code:

```go
	if err := sshsig.Verify(bytes.NewBuffer([]byte(token)), []byte(signature), []byte(key.Content), "gitea"); err != nil &&
		sshsig.Verify(bytes.NewBuffer([]byte(token+"\r\n")), []byte(signature), []byte(key.Content), "gitea") != nil {
		log.Error("Unable to validate token signature. Error: %v", err)
		return "", ErrSSHInvalidTokenSignature{
			Fingerprint: key.Fingerprint,
		}
	}
```

This would reduce the additional block for the second if statement.

What do you think?

Comment (wxiaoguang) [reply models/asymkey/ssh_key_verify.go]: Personally I do not like making code too compact, it's difficult to read or maintain.

**Review by delvh — APPROVED** [review]

**Comment by KN4CK3R** [comment]
Are we sure we want this workaround in Gitea? The error is produced outside of Gitea just because a tool behaves not as intended.

**Comment by nekrondev** [comment]
> Are we sure we want this workaround in Gitea? The error is produced outside of Gitea just because a tool behaves not as intended.

Yes that's right, it's an Windows Powershell issue that's pending since so many years. However a lot of Windows-based users will run into this issue if they try to verify their key and wonder what's wrong. You can see it at #21527 how many folks struggle with this. Until this issue gets fixed by Powershell the workaround even if GT is not the source of trouble should be implemented but YMMV and it's up for discussion here.

**Comment by lunny** [comment]
Since the upstream issue existed for about 5 years. Maybe the workaround is valuable.

**Comment by nekrondev** [comment]
> Since the upstream issue existed for about 5 years. Maybe the workaround is valuable. Add a comment and ref to upstream issue link is prefered.

Hi @lunny  I added a comment referencing the Powershell issue.

**Comment by wxiaoguang** [comment]
I can vote my approval if the code is not that compact. I really dislike the long `if` statements which contains complex function calls.

**Comment by nekrondev** [comment]
> I can vote my approval if the code is not that compact. I really dislike the long `if` statements which contain complex expressions and function calls. [#28392 (comment)](https://github.com/go-gitea/gitea/pull/28392#discussion_r1420201444)

@wxiaoguang I changed the coding to be more explicit making it easier to read and understand.

File: models/asymkey/ssh_key_verify.go [hunk 3]
```diff
@@ -30,13 +30,18 @@ func VerifySSHKey(ctx context.Context, ownerID int64, fingerprint, token, signat
...
-		return "", ErrSSHInvalidTokenSignature{
-			Fingerprint: key.Fingerprint,
+	err = sshsig.Verify(bytes.NewBuffer([]byte(token)), []byte(signature), []byte(key.Content), "gitea")
+	if err != nil {
+		// edge case for Windows based shells that will add CR LF if piped to ssh-keygen command
+		// see https://github.com/PowerShell/PowerShell/issues/5974
+		if sshsig.Verify(bytes.NewBuffer([]byte(token+"\r\n")), []byte(signature), []byte(key.Content), "gitea") == nil {
+			err = nil
+		}
+		if err != nil {
```
Comment (wxiaoguang) [inline models/asymkey/ssh_key_verify.go]:
```suggestion
		if sshsig.Verify(bytes.NewBuffer([]byte(token+"\r\n")), []byte(signature), []byte(key.Content), "gitea") != nil {
```

**Review by wxiaoguang — APPROVED** [review]
