### PR TITLE
Stream repo zip/tar.gz/bundle achives by default

### LINKED ISSUE #29942: Stream repo zip/tar.gz/bundle achives by default
### Feature Description

A common problem that users report is their disk running out of space because of all the repo archive "caches". I propose a new option `repository.STREAM_ARCHIVES` which by default would be enabled and which will directly stream the compressed bytestream to the client, which will:

1. Improve initial download performance as the POST+GET negotiation on UI goes away and it will be pure GET.
2. Reduce performance on subsequent downloads, because there is no cache anymore, but busy instances with enough disk space can opt into cache by disabling the option.
3. Eliminate any worries regard the disk running out of space.
4. Prevent the client from showing download progress because `content-length` will not be communicated to the client for streamed downloads.

### LINKED ISSUE #30443: External storage (s3) archive job fails silently (api/website)
### Description

If the s3 storage endpoint is set to a domain which doesn't resolve for whatever reason, the archive download on the user's side silently fails.
While the job throws some errors in the console, the api response only reflects if the archive job is completed and doesn't include a scenario if the job failed, which means it stays as false even after the job failed and isn't being worked on anymore.
`HTTP POST https://git.example.com/tachiyomi/tachiyomi/archive/v0.15.3.zip`
res: `{"complete":false}`
The website/frontend then continues to request the status of the job again and again until the user gets bored and closes the tab.

tldr; archive job fail is not handled by website or api (silent fail)
The 1. api response should include a scenario where the job failed and 2. the frontend should show an error if it did and 3. stop making requests.

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/TristanWasTaken/369af8ffdcd7d2e93c507f5fe2c85602

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Docker

### How are you running Gitea?

docker `gitea/gitea:1.21.3`
docker `minio/minio`
both run in the same bridge network, though gitea has to contact storage.*example.com* because you can only set one hostname which has to be the public hostname when `SERVE_DIRECT` is used

### Database

None

### LINKED ISSUE #34003: Gitea server keeps filling up with bundle/zip archives
### Description

Hi, I am the maintainer of [git.nixmagic.com](https://git.nixmagic.com). After using Gitea on it since 2020-06-04, I recently started experiencing storage issues on both `gitea-1.23.5-linux-amd64` and `gitea-1.22.1-linux-amd64` (both upstream binary releases). This may have been present before too, but unlikely. Currently its instance is on a 64GB storage quota (applied after this incident consumed a whole ZFS pool instead), which it exceeded in less than 48 hours from 13GB base. This was temporarily resolved by executing the command below.

Directory: `~/data/repo-archives`
User: `git`
Command: `for file in $(find . | grep -E 'zip|bundle'); do rm $file; done`

This leads me to believe that zip and bundle archives are being generated at an unreasonable pace. In other issues and related documentation, I found that such files are generated on-demand by users of the instance. However, my edge nodes that terminate TLS for this node do not confirm this being an active attack. They don't seem to have much traffic at all. That leads me to believe that this is an internal issue. For the time being, I'll apply a cron job to periodically flush these files as mentioned there. But that's a band-aid, not a solution. Both generating and eliminating these files consumes unneccesary CPU and IO resources.

If you're willing to take a look into the source code to narrow this down, much appreciated. Similarly, I'll keep track of this issue to offer any information I can from my instance. Thank you!

As a side note, is it possible to downgrade Gitea? I tried to replace my symlink from 1.23.5 to 1.22.1, but this caused the associated service to fail. Both files are/were executable, but I don't remember why exactly it failed. I can start this service both in systemd and manually, so troubleshooting here is possible. However, it does incur service downtime that I'd prefer to avoid unless necessary.

If need be, I can clone this entire instance into a local replica. This replica would have a filesystem-level one-to-one copy on account of ZFS, but would not necessarily be tethered to the production instance and its reverse proxy. The replica will require network and other such client-side changes. This may be useful to determine whether this issue is truly local at the application level. If determined useful, I will make such replica and document it accordingly.

Tracking on snapshot `ssd/lxc/ct/gitea@2025-03-25_GitHub`, created / completed on 02:02 CET.

### Gitea Version

1.23.5

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

[nixmagic.com/pub/2025-03-24_Gitea](https://nixmagic.com/pub/2025-03-24_Gitea) - I'll publish logs here as needed. So far I'm thinking of e1.nixmagic.com and e2.nixmagic.com's NGINX logs for git.nixmagic.com. Those should offer an overview into the Internet's requests towards this Gitea instance. Internally, the only user is yours truly. But infected hosts may exist. Logs from Gitea itself may provide equally useful, if not more so. Please let me know.

### Screenshots

_No response_

### Git Version

2.39.5

### Operating System

Debian 12 amd64

### How are you running Gitea?

My deployment of Gitea is from upstream binary release, for amd64 target architecture. This is on a Debian 12 stable system, running within LXC. The storage system is ZFS, which is how the quota has been applied from the host system.

### Database

None

### PR DESCRIPTION
**Pull request by ChristopherHX**
Initial implementation of linked proposal.

* Closes #29942
* Fix #34003
* Fix #30443

### CODE REVIEW

**Comment by ChristopherHX** [comment]
> Improve initial download performance as the POST+GET negotiation on UI goes away and it will be pure GET.

Here I kept the POST+GET negotiation, where the POST does nothing when enabled

**Comment by silverwind** [comment]
> Here I kept the POST+GET negotiation, where the POST does nothing when enabled

Will check later, I think it should be possible to turn into a GET. Benefit is that these downloads will be curl-able.

**Comment by ChristopherHX** [comment]
They are curl-able for some amount of time already, just not via html inspect. I believe in 2021 this didn't work in gitea.

e.g. `curl -L https://gitea.com/gitea/act_runner/archive/main.zip` just like on github.com

We would get a cleaner html page if we remove the POST as long this setting on.

**Comment by silverwind** [comment]
I wonder if we even need the setting at all. Are there any benefits to non-streaming downloads?

The only one I can think of is reduced CPU usage for instances that receive a lot of downloads, but it's rather niche I think, especially because if a repo is pushed to often, that cache will invalidate every push.

**Comment by ChristopherHX** [comment]
> Are there any benefits to non-streaming downloads?

I would not require any setting, but I also do not host gitea productively anywhere. Let's hear others opinions, given I assume  this would be more a change for a future release like 1.26.0.

If we decide to removing the repo-archive cache, then we also no longer need the repo-archive settings. I assume this way of doing this has been inherited from Gogs.

**Comment by silverwind** [comment]
I guess non-streaming does have a benefit for archived or otherwise rarely pushed-to repos. FWIW, Github does only implement streaming and I think this is also the only mode that can work on big instances without consuming copious amounts of disk space (think crawlers crawling archive links for all commit hashes).

**Comment by silverwind** [comment]
I pushed the UI change which will omit the POST when streaming is enabled. The archive links work natively without JS when streaming is enabled.

**Review by silverwind — APPROVED** [review]

**Review by hiifong — APPROVED** [review]

File: routers/web/repo/repo.go [hunk 1]
```diff
@@ -377,6 +377,28 @@ func Download(ctx *context.Context) {
...
+		ctx.Resp.Header().Add("Link", fmt.Sprintf(`<%s/archive/%s.%s?rev=%s>; rel="immutable"`,
+			ctx.Repo.Repository.APIURL(),
+			aReq.CommitID,
+			aReq.Type.String(),
+			aReq.CommitID,
+		))
+
+		ctx.SetServeHeaders(&context.ServeHeaderOptions{
+			Filename: downloadName,
+		})
```
Comment (wxiaoguang) [inline routers/web/repo/repo.go]: This code block seems duplicate

File: services/repository/archiver/archiver.go [hunk 2]
```diff
@@ -138,6 +138,42 @@ func (aReq *ArchiveRequest) Await(ctx context.Context) (*repo_model.RepoArchiver
 	}
 }
 
+// Stream satisfies the ArchiveRequest being passed in.  Processing
+// will occur directly in this routine.
+func (aReq *ArchiveRequest) Stream(ctx context.Context, w io.Writer) error {
+	ctx, _, finished := process.GetManager().AddContext(ctx, fmt.Sprintf("ArchiveRequest[%d]: %s", aReq.RepoID, aReq.GetArchiveName()))
+	defer finished()
```
Comment (wxiaoguang) [inline services/repository/archiver/archiver.go]: I don't think it needs to use process manager it. It is already in a HTTP request context.

File: services/repository/archiver/archiver.go [hunk 3]
```diff
@@ -138,6 +138,42 @@ func (aReq *ArchiveRequest) Await(ctx context.Context) (*repo_model.RepoArchiver
...
+	repo, err := repo_model.GetRepositoryByID(ctx, aReq.RepoID)
+	if err != nil {
+		return fmt.Errorf("archiver.LoadRepo failed: %w", err)
+	}
+
+	gitRepo, err := gitrepo.OpenRepository(ctx, repo)
+	if err != nil {
+		return err
+	}
+	defer gitRepo.Close()
```
Comment (wxiaoguang) [inline services/repository/archiver/archiver.go]: I think you can just pass the git repo into this function from its caller.

File: web_src/js/features/repo-common.ts [hunk 4]
```diff
@@ -32,7 +32,10 @@ async function onDownloadArchive(e: DOMEvent<MouseEvent>) {
 }
 
 export function initRepoArchiveLinks() {
-  queryElems(document, 'a.archive-link[href]', (el) => el.addEventListener('click', onDownloadArchive));
+  // when archive streaming is enabled, the links will work natively without JS
+  if (!window.config.streamArchives) {
+    queryElems(document, 'a.archive-link[href]', (el) => el.addEventListener('click', onDownloadArchive));
+  }
```
Comment (wxiaoguang) [inline web_src/js/features/repo-common.ts]: It's too hacky and fragile, there will be bugs in the future if somebody touches the code.

Comment (silverwind) [reply web_src/js/features/repo-common.ts]: So what do you suggest? We could alternatively just remove non-streaming mode entirely which would make all the JS and probably a good chunk of Go code deletable (my preference).

Comment (wxiaoguang) [reply web_src/js/features/repo-common.ts]: Why you need this JS? "GET" request can always start the downloading. So you can just make POST check return immediately for streaming?

Comment (silverwind) [reply web_src/js/features/repo-common.ts]: It's still a unneccesary round-trip to the server. It's better to not tamper with these links if we don't need to.

Comment (silverwind) [reply web_src/js/features/repo-common.ts]: BTW I think we could eliminate the POST (and the JS) in both cases if we just delay the GET response in non-streaming mode.

Comment (wxiaoguang) [reply web_src/js/features/repo-common.ts]: Although it is "unnecessary", the old logic is still clear and nothing worse or wrong.

If you add more fragile code to eliminate the "unnecessary" code, I think the "fragile code" is more unnecessary.

Comment (silverwind) [reply web_src/js/features/repo-common.ts]: I don't share such concerns but lets eliminate the POST entirely then, then there is no JS at all and "no code" is not "fragile".

File: services/repository/archiver/archiver.go (hunk 2 above)
Comment (ChristopherHX) [reply services/repository/archiver/archiver.go]: removed in https://github.com/go-gitea/gitea/pull/35487/commits/d447b7cabf394d42c98e82a257ba8fe6dc3d0e14

File: services/repository/archiver/archiver.go (hunk 3 above)
Comment (ChristopherHX) [reply services/repository/archiver/archiver.go]: added gitRepo as parameter in https://github.com/go-gitea/gitea/commit/d447b7cabf394d42c98e82a257ba8fe6dc3d0e14

File: routers/web/repo/repo.go (hunk 1 above)
Comment (ChristopherHX) [reply routers/web/repo/repo.go]: I pulled this code out of conditionals, now we have similar duplicates as in the default branch
```
		// Add nix format link header so tarballs lock correctly:
		// https://github.com/nixos/nix/blob/56763ff918eb308db23080e560ed2ea3e00c80a7/doc/manual/src/protocols/tarball-fetcher.md
		ctx.Resp.Header().Add("Link", fmt.Sprintf(`<%s/archive/%s.%s?rev=%s>; rel="immutable"`,
			ctx.Repo.Repository.APIURL(),
			aReq.CommitID,
			aReq.Type.String(),
			aReq.CommitID,
		))
```

I am not sure yet in which package we should place a shared method that adds this header..

I have yet to think about deduping this, maybe pass download name to the download function and pull this variable out of the if
```
downloadName := ctx.Repo.Repository.Name + "-" + aReq.GetArchiveName()
		ctx.SetServeHeaders(&context.ServeHeaderOptions{
			Filename: downloadName,
		})
```

**EDIT** dedupped downloadName now in https://github.com/go-gitea/gitea/pull/35487/commits/9f485821cffdc74f3a7d5434a7f1b038c2895a19

If we pass the filename, why not the whole download name.

**Review by ChristopherHX — COMMENTED** [review]
After simplifing Archiverequest.Stream, I decided to call this as well when caching the repository but use the pipe as destination

File: web_src/js/features/repo-common.ts (hunk 4 above)
Comment (wxiaoguang) [reply web_src/js/features/repo-common.ts]: There can be a complete plan for how to improve the design.

My suggestion is:

1. Introduce the "stream" option in backend, but don't expose it in configuration document. Keep other parts as simple as possible (and don't introduce too many JS changes)
2. Wait for some time and collect user feedbacks.

I can foresee that the result will be one of them:

* Nobody complains, "stream" works well for all users.
    * Then we can completely remove the POST, and remove JS code
* A few users complain, they insist to use the "repo archive", then we need to:
    * Tell them there is still an option
    * Add document for the "stream" option
    * Add comments about why repo archive is really needed
    * Add tests for legacy repo archive mode, including making frontend stable

Comment (silverwind) [reply web_src/js/features/repo-common.ts]: I don't see that justified in any way. End users won't care, only server admins will, because their disk fills up with useless caches when bots crawl their instances. Streaming is superior in all ways, there is no downside.

Comment (wxiaoguang) [reply web_src/js/features/repo-common.ts]: Yes, streaming is good.

If nobody complains, that's good.

If you promise to answer the user's questions "why I can't use repo archive" and help to revert the code if some users report their use cases and have to use repo archive (just in case, IDK), then I also agree to remove the repo archive in one PR.

Comment (silverwind) [reply web_src/js/features/repo-common.ts]: I think we can go with this way of keeping non-streaming an option in case anyone relies on it, but the only real use case I see is "archive" style gitea instances where git content never changes, where the cache is always "hot". Any instance that receives git content changes will be better of with streaming.

Comment (wxiaoguang) [reply web_src/js/features/repo-common.ts]: > I wonder if we even need the setting at all. Are there any benefits to non-streaming downloads?

I was talking about this idea https://github.com/go-gitea/gitea/pull/35487#issuecomment-3289947061 , and my plan can make us get the best result IMO.

Comment (silverwind) [reply web_src/js/features/repo-common.ts]: You mean we revert the JS change and make the POST return immediately when streaming? And what exactly decides whether to stream or not if there is no config option?

Comment (wxiaoguang) [reply web_src/js/features/repo-common.ts]: What are the problems we'd like to resolve?

* We'd like to use streaming for repo downloading
* We don't know whether there are users heavily using archive downloading

What are the results we'd like to see?

* Either we only support streaming downloading
* Or support streaming and archive downloading at the same time, controlled by an option
    * Then we need more tests to cover these 2 behaviors, otherwise one might break since the default option won't make the bugs occur in development.


How to achieve the result? Two steps:

1. This PR, introduce the streaming option, only use it in backend, but don't expose it in document.
    * Then we have a few months to collect user feedbacks
    * This PR can be as simple as possible, don't need to introduce too many unnecessary changes like JS (keep the old POST as-is), because final PR will make us have a clear result.
2. Final PR
    * (Highly likely) we don't need the archive downloading method any more, completely remove the code and data (backend, frontend, storage, config option, document, etc)
    * (Have to ...) some users still need the archive downloading method
        * We need to refactor the JS code, make the download event handler depend on its class or data attribute (eg `data-wait-for-complete`). But not use a global and fragile `if` check.
        * Add enough tests to test the different rendering results of different streaming config option, and test the download code.

Comment (wxiaoguang) [reply web_src/js/features/repo-common.ts]: Any objection?

Comment (ChristopherHX) [reply web_src/js/features/repo-common.ts]: For me would be your plan ok as well.

_On the other hand the current js change makes the file download start sightly faster without right click menu and stops showing me http 400 codes shortly after restarts (invalid csrf tokens? auto fixes itself with later page refresh, GET is not protected)_

Comment (wxiaoguang) [reply web_src/js/features/repo-common.ts]: I will make some changes according to my plan. I think eventually we will get rid of the repo archive and remove a lot of code.


----

> the current js change ....

I would prefer not going with current JS. It couples a lot of modules (source files) together, a single "true/false" value is passed everywhere, which is not ideal. We should avoid such fragile "global variable".

And eventually, we will remove all the legacy JS

----

> showing me http 400 codes shortly after restarts (invalid csrf tokens? 

IIRC CSRF token is preserved between restarts, can you reproduce the CSRF token problem by other forms? For example: a comment form?

**Comment by wxiaoguang** [comment]
Made some changes, and I merged the legacy copy-pasted code (since long time ago ...) into one `ServeRepoArchive`, then no duplicate `download`/`prepare`/`Add(link)`

Now `+110 −156` , less code, better result.

There are tests covering "repo archive download", so as long as tests pass, I think it is good enough.

File: web_src/js/features/repo-common.ts (hunk 4 above)
Comment (silverwind) [reply web_src/js/features/repo-common.ts]: Go ahead and revert the JS if you like. I still hope we eventually can change all use cases to GET only, but the POST+GET isn't bothering me too much I guess.

Edit: I see you did already.

**Review by silverwind — APPROVED** [review]

File: web_src/js/features/repo-common.ts (hunk 4 above)
Comment (wxiaoguang) [reply web_src/js/features/repo-common.ts]: Thank you all. Let's keep the unnecessary "POST" for a short time, then completely remove it in next release 🎉

**Review by wxiaoguang — APPROVED** [review]
