### PR TITLE
Fix ldap loginname

### LINKED ISSUE #18547: Unable to login using e-mail (LDAP)
### Gitea Version

1.16.0

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Using gitea binary downloaded from dl.gitea.io.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

When trying to log in using my e-mail, I get an error "Identifiant ou mot de passe invalide." (username or password invalid).
When using username, it works as expected.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by johanvdw**
This PR extends: https://github.com/go-gitea/gitea/pull/18769

to fix https://github.com/go-gitea/gitea/issues/18547

The stored LoginName was not used for existing accounts. 

I'm no gitea expert, so the fix may not be optimal. I'll try to figure out if we can add this in a unit test tomorrow, any guidance would be useful.

For clarity, this has been tested and solves the issue that it is no longer possible to login when a different loginname is stored.

### CODE REVIEW

File: services/auth/source/ldap/source_authenticate.go [hunk 1]
```diff
@@ -20,6 +20,9 @@ import (
 // Authenticate queries if login/password is valid against the LDAP directory pool,
 // and create a local user if success when enabled.
 func (source *Source) Authenticate(user *user_model.User, userName, password string) (*user_model.User, error) {
+	if user != nil {
```
Comment (lunny) [inline services/auth/source/ldap/source_authenticate.go:24]: I think userName should not be empty? It should be come from inputbox.

Comment (johanvdw) [reply services/auth/source/ldap/source_authenticate.go:24]: But the username may be different from the loginname that must be used with ldap. It could also be an email address. 

In ldap you want to search for the login name only (this was at least what was working up to version 1.15.9).

Comment (lunny) [reply services/auth/source/ldap/source_authenticate.go:24]: So that should be changed in the progress of LDAP users sync but not when authenticating. When sync a user, we need to know should we use login name as identify or use email?

Comment (johanvdw) [reply services/auth/source/ldap/source_authenticate.go:24]: I still think this is the appropriate place - when you login using your gitea username or email address, validation must be done using the loginname that was stored for the account. 

I improved wording a bit in a new commit.

Comment (lunny) [reply services/auth/source/ldap/source_authenticate.go:24]: OK. Let's clarify. If `user` is nil, that means there is no user found in Gitea's table, `userName` is input by login user, it could be a name or an email address. So if `user` is nil, and `userName` is email. This function will return failure.

Of course, this resolved the problem when `user` is not nil and `userName` is email. I think we can merge it at first.

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]
