### PR TITLE
Fix corrupted external render content

### LINKED ISSUE #35944: External render failed when content is binary
### Description

Hello . After upgrading to version 1.25.* pandoc stopped working, it returns an error 500.

I tried the command as in the manual.
500 Internal Server Error
An error occurred:

Render, docx render run command pandoc [--from docx --to html --self-contained --template /home/git/gitea/custom/html/basic.html] failed: exit status 63
Stderr: [WARNING] Deprecated: --self-contained. use --embed-resources --standalone
couldn't unpack docx container: not enough bytes

So it is with the recommended updated parameter.
500 Internal Server Error

An error occurred:

Render, docx render run command pandoc [--from docx --to html --embed-resources --template /home/git/gitea/custom/html/basic.html] failed: exit status 63
Stderr: couldn't unpack docx container: not enough bytes

I tried it on different machines, the result is the same

### Gitea Version

1.25.1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

git version 2.47.3

### Operating System

SMP Debian 4.19.249-2 (2022-06-30) and SMP PREEMPT_DYNAMIC Debian 6.12.48-1 (2025-09-20)

### How are you running Gitea?

I use your releases. I use systemd and gitea-1.25.1-linux-amd64.

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #35944

### CODE REVIEW

**Comment by wxiaoguang** [comment]
image

File: routers/web/repo/view_file.go [hunk 1]
```diff
@@ -92,8 +92,6 @@ func handleFileViewRenderMarkup(ctx *context.Context, filename string, sniffedTy
 		ctx.ServerError("Render", err)
 		return true
 	}
-	// to prevent iframe from loading third-party url
-	ctx.Resp.Header().Add("Content-Security-Policy", "frame-src 'self'")
```
Comment (wxiaoguang) [inline routers/web/repo/view_file.go:96]: This was introduced by "Allow render HTML with css/js external links (#19017)" by mistake, it doesn't help anything, the renders should have done the sanitation or set necessary headers.

Comment (delvh) [reply routers/web/repo/view_file.go:96]: Wouldn't it make sense to keep regardless?
It doesn't impact performance and is an extra safety net in case everything else fails

Comment (wxiaoguang) [reply routers/web/repo/view_file.go:96]: * For non-iframe mode: it breaks STATIC_URL_PREFIX and also affects the render's output.
* For iframe mode: it only breaks STATIC_URL_PREFIX and doesn't provide any safety.

I really don't see any reason to keep it.

**Review by delvh — APPROVED** [review]

**Review by lunny — APPROVED** [review]
