### PR TITLE
Perform Newest sort type correctly when sorting issues

### LINKED ISSUE #30642: Sort type Newest for isues/pull request is not working
### Description

The sort Newest is sorting the same as "Recently updated".

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

image

### Git Version

1.21.11

### Operating System

Linux

### How are you running Gitea?

Building gitea by myself
OS: Ubuntu 22.04 LTS
gitea is running with systemd

### Database

MSSQL

### PR DESCRIPTION
**Pull request by kemzeb**
Should resolve #30642.

---
Before this commit, we were treating an empty `?sort=` query parameter as the correct sorting type (which is to sort issues in descending order by their created UNIX time). But when we perform `sort=latest`, we did not include this as a type so we would sort by the most recently updated when reaching the `default` switch statement block.

This commit fixes this by considering the empty string, "latest", and just any other string that is not mentioned in the switch statement as sorting by newest.

### CODE REVIEW

File: modules/indexer/issues/dboptions.go [hunk 1]
```diff
@@ -87,8 +85,10 @@ func ToSearchOptions(keyword string, opts *issues_model.IssuesOptions) *SearchOp
 	case "priority", "priorityrepo", "project-column-sorting":
 		// Unsupported sort type for search
 		searchOpt.SortBy = SortByUpdatedDesc
+	case "latest":
+		fallthrough
 	default:
-		searchOpt.SortBy = SortByUpdatedDesc
+		searchOpt.SortBy = SortByCreatedDesc
```
Comment (kemzeb) [inline modules/indexer/issues/dboptions.go]: Is it alright to change the default block here? My reasoning for changing this was because only invalid sort types would resort in executing the default block (as expected) and users/web handlers should be passing correct sort type anyways. Alternatively I could just add a `case: "" || "latest"` instead of changing this block.

**Comment by yp05327** [comment]
I think the default sort order should be updated time.
The problem is that we do not have a sort for created time
so maybe we can convert `newest` to `recently created` in the sort list, and then let `recently update` to be the default sort order

**Comment by kemzeb** [comment]
Thanks for the review @yp05327!

> I think the default sort order should be updated time.

Gotcha, I didn't have any other reason for changing this other than it was convenient and of the thought that users/the web client should be passing sort types that we support.

> The problem is that we do not have a sort for created time (in UI)

I'm a tad confused by this. I'm sure there is something I'm missing here, but when reading this [line](https://github.com/go-gitea/gitea/blob/8924d9b2efd52132876fcd106c625a2a2db7a295/routers/web/repo/issue.go#L348) from a function that the affected route handler uses and from looking at this template file [here](https://github.com/go-gitea/gitea/blob/8924d9b2efd52132876fcd106c625a2a2db7a295/templates/shared/issuelist.tmpl#L3), to me it looks like we do since we just snatch the sorted list and pass it on to the template engine for it to use. 

> so maybe we can convert newest to recently created in the sort list, and then let recently update to be the default sort order

Just to make sure I understand this, do you mean I should update the switch statement I changed? Something like:
```go
switch opts.SortType {
case "", "latest":
  searchOpt.SortBy = SortByCreatedDesc
. . .
case "recentupdate":
  fallthrough
default:
  searchOpt.SortBy = SortByUpdatedDesc
}
```

File: modules/indexer/issues/dboptions.go [hunk 2]
```diff
@@ -87,8 +85,10 @@ func ToSearchOptions(keyword string, opts *issues_model.IssuesOptions) *SearchOp
 	case "priority", "priorityrepo", "project-column-sorting":
 		// Unsupported sort type for search
 		searchOpt.SortBy = SortByUpdatedDesc
```
Comment (yp05327) [inline modules/indexer/issues/dboptions.go]: Sorry, I misunderstood, plz ignore my comment above.
Your fix is right, it think it is better to fix it here.
Unsupported sort type should be same to default?

**Review by yp05327 — APPROVED** [review]

**Review by lunny — APPROVED** [review]

File: modules/indexer/issues/dboptions.go (hunk 1 above)
Comment (wxiaoguang) [reply modules/indexer/issues/dboptions.go]: I am not sure whether it is right to change the "default" behavior.

I think the old behavior should be kept as-is if it is not clear.

**Comment by wxiaoguang** [comment]
Wait for https://github.com/go-gitea/gitea/pull/30644/files#r1575681276

File: modules/indexer/issues/dboptions.go (hunk 2 above)
Comment (kemzeb) [reply modules/indexer/issues/dboptions.go]: No worries!

Another review was made and it was determined that we shouldn't change the default block. However, I did replace the only line of this case block with a `fallthrough` since it's the same as the `default` block.

File: modules/indexer/issues/dboptions.go (hunk 1 above)
Comment (kemzeb) [reply modules/indexer/issues/dboptions.go]: Gotcha, I made the necessary changes and decided to change the second-to-last case statement to just use a `fallthrough` since it's right above the `default` block and they both do the same thing.

**Review by wxiaoguang — APPROVED** [review]

File: modules/indexer/issues/dboptions.go (hunk 2 above)
Comment (yp05327) [reply modules/indexer/issues/dboptions.go]: The latest version LGTM.
