### PR TITLE
Set self-adjusting deadline for connection writing

### LINKED ISSUE #16055: Unexpected connection loss when cloning via https with slow bandwidth
- Gitea version (or commit ref): lastest 1.14 and latest main
- Git version: 2.29
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No

## Description

When cloning a repository with slow bandwidth over https, gitea seems to timeout.
We noticed that because F-Droid fails to checkout repositories from codeberg.org, there is also a issue on Codeberg here: https://codeberg.org/Codeberg/Community/issues/461.

This seems to affect try.gitea.io also. Timeouts seem to happen after a few minutes, but not always after the same time. We tried to increase git.timeout values on our test instance also, also accessed port 3000 directly without reverse proxy, without any effect.
```
$ sudo wondershaper enp0s31f6 4000 4000 # somehow values do not really matter, anything between 500-4000 had the same effect
$ time git clone https://try.gitea.io/ashi/Gadgetbridge
Klone nach 'Gadgetbridge' ...
remote: Enumerating objects: 92096, done.
remote: Counting objects: 100% (92096/92096), done.
remote: Compressing objects: 100% (22562/22562), done.
error: 5767 Bytes des Bodys werden noch erwartet | 12.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: zu frühes Dateiende
fatal: fetch-pack: ungültige index-pack Ausgabe

real    1m31,925s
user    0m0,005s
sys     0m0,025s

```

### PR DESCRIPTION
**Pull request by zeripath**
In #16055 it appears that the simple 5s deadline doesn't work for large
file writes. Now we can't - or at least shouldn't just set no deadline
as go will happily let these connections block indefinitely. However,
what seems reasonable is to set some minimum rate we expect for writing.

This PR suggests the following algorithm:

* Every write has a minimum timeout of 5s (adjustable at compile time.)
* If there has been a previous write - then consider its previous
deadline, add half of the minimum timeout + 2s per kb about to written.
* If that new deadline is after the minimum timeout use that.

Fix #16055

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: modules/graceful/server.go [hunk 1]
```diff
@@ -31,6 +31,9 @@ var (
 // PerWriteWriteTimeout timeout for writes
 const PerWriteWriteTimeout = 5 * time.Second
```
Comment (fnetX) [inline modules/graceful/server.go]: I think this does not sufficiently address the problem yet.

This code is not always executed a few times within the timeout frame, downloading with 50KB/s has for example 18 seconds between runs of the function on my end.

So I'd say there is need for a more elegant solution, or at least a higher default timeout.

Comment (fnetX) [reply modules/graceful/server.go]: very exactly btw, confirmed this is the interval for a few minutes now ... thought it would be somewhat random at first.

File: modules/graceful/server.go [hunk 2]
```diff
@@ -249,13 +252,26 @@ func (wl *wrappedListener) File() (*os.File, error) {
...
 }
 
 func (w wrappedConn) Write(p []byte) (n int, err error) {
 	if PerWriteWriteTimeout > 0 {
-		_ = w.Conn.SetWriteDeadline(time.Now().Add(PerWriteWriteTimeout))
+		minTimeout := PerWriteWriteTimeout/2 + time.Duration(len(p)/1024)*PerWriteWriteTimeoutKbRate
+		minDeadline := time.Now().Add(minTimeout)
+
+		if minTimeout < PerWriteWriteTimeout {
+			minDeadline := time.Now().Add(PerWriteWriteTimeout)
```
Comment (zeripath) [inline modules/graceful/server.go]:
```suggestion
			minDeadline = time.Now().Add(PerWriteWriteTimeout)
```

File: modules/graceful/server.go (hunk 1 above)
Comment (zeripath) [reply modules/graceful/server.go]: I mean this is more elegant as it takes account of previous writes through the previous deadline and the next write. 

The next step is accounting for how much is written directly and double counting for it. 

The other option is tuning those constants - I would guess that setting the first to 30s and maybe doubling the other would work.

File: modules/graceful/server.go [hunk 3]
```diff
@@ -249,13 +252,26 @@ func (wl *wrappedListener) File() (*os.File, error) {
...
 	if PerWriteWriteTimeout > 0 {
-		_ = w.Conn.SetWriteDeadline(time.Now().Add(PerWriteWriteTimeout))
+		minTimeout := PerWriteWriteTimeout/2 + time.Duration(len(p)/1024)*PerWriteWriteTimeoutKbRate
+		minDeadline := time.Now().Add(minTimeout)
+
+		if minTimeout < PerWriteWriteTimeout {
+			minDeadline = time.Now().Add(PerWriteWriteTimeout)
+		}
+
+		minDeadline := time.Now().Add(minTimeout)
```
Comment (zeripath) [inline modules/graceful/server.go]:
```suggestion
```

**Comment by zeripath** [comment]
It would also help if it actually compiled!

File: modules/graceful/server.go (hunk 1 above)
Comment (fnetX) [reply modules/graceful/server.go]: Yeah, my main issue is that the low values will never work if the function is not called before the deadline kicks in. It sounds cool if we could make sure it's called at least after a moment to calculate the deadline accordingly. On the other hand, I don't see a way to make sure it gets called if the connection stalls immediately (thinking of attacks or something) and the default timeout window is set very high.

I'll try to test if I can get some numbers about the situation, esp. connections that are x slow can still transfer y large files etc ...

Comment (fnetX) [reply modules/graceful/server.go]: Okay, it looks like the situation improved drastically.
Downloading 100MB over 10KB/s fails with `2021-06-05 01:47:11 (10.0 KB/s) - Connection closed at byte 2621440. Giving up.` (Gitea timeout after `1m6.50294821s`)
but otherwise, this looks quote good, 100MB with 50KB/s worked fine, too.

Comment (zeripath) [reply modules/graceful/server.go]: Ok. So if we up the baseline delay to 30s and adjust the formula to remove the halving we should be in business I guess.

Comment (zeripath) [reply modules/graceful/server.go]: Ok I've adjusted things. 

Every write gets at least 30s. (pWWT)

Every kB written gets at least 2s. (pWWkBRate)

So either you get the previous deadline + the new perKbRate or 30s plus the new perKbRate.

Choose a minimum perKbTime that you will tolerate - the current is set probably too low. I would guess 10s per kB is the worst we should tolerate. 

I'll make these settings at the app.ini level.

**Review by 6543 — APPROVED** [review]
fix it

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Please send backport
