### PR TITLE
Fix various problems around projects board view

### LINKED ISSUE #30701: Wrong `project_board_id` for newly created issue
### Description

image

If I create an issue and add it to a project, its `project_board_id` is 0, but it should not be.

Instead, `project_board_id` should either be the value of the default board or board with lowest `sorting`

### Gitea Version

1.21.11+9-g0e20ccfe32

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
# The problem
The previous implementation will start multiple POST requests from the frontend when moving a column and another bug is moving the default column will never be remembered in fact.

# What's changed

- [x] This PR will allow the default column to move to a non-first position
- [x] And it also uses one request instead of multiple requests when moving the columns
- [x] Use a star instead of a pin as the icon for setting the default column action
- [x] Inserted new column will be append to the end
- [x] Fix #30701 the newly added issue will be append to the end of the default column
- [x] Fix when deleting a column, all issues in it will be displayed from UI but database records exist.
- [x] Add a limitation for columns in a project to 20. So the sorting will not be overflow because it's int8.

### CODE REVIEW

File: web_src/js/features/repo-projects.js [hunk 1]
```diff
@@ -63,17 +62,20 @@ async function initRepoProjectSortable() {
...
+          sorting: i,
+        })),
+      };
+
+      try {
+        await POST(`${mainBoard.getAttribute('data-url')}`, {
+          data: columnSorting,
+        });
+      } catch (error) {
+        console.error(error);
```
Comment (silverwind) [inline web_src/js/features/repo-projects.js:78]: Is color remembered now in backend after this POST?

File: web_src/js/features/repo-projects.js [hunk 2]
```diff
@@ -63,17 +62,20 @@ async function initRepoProjectSortable() {
...
+
+      const columnSorting = {
+        columns: Array.from(boardColumns, (column, i) => ({
+          columnID: parseInt(column.getAttribute('data-id')),
+          sorting: i,
+        })),
+      };
+
+      try {
+        await POST(`${mainBoard.getAttribute('data-url')}`, {
```
Comment (silverwind) [inline web_src/js/features/repo-projects.js]:
```suggestion
        await POST(mainBoard.getAttribute('data-url'), {
```

`getAttribute` returns string, except when attribute is not there it will be `null`, but it makes no sense to POST to `null` and it's better to let it throw then.

File: web_src/js/features/repo-projects.js (hunk 1 above)
Comment (lunny) [reply web_src/js/features/repo-projects.js:78]: I think the edit operation will not invoke this function. It now only is used to move the columns.

Comment (silverwind) [reply web_src/js/features/repo-projects.js:78]: Yeah if color persists after move operations, then it's good. I always thought it to be unnecessary to send color for the move operation.

Comment (lunny) [reply web_src/js/features/repo-projects.js:78]: Yes, this PR fixed that problem.

File: templates/projects/view.tmpl [hunk 3]
```diff
@@ -90,7 +90,7 @@
 										data-modal-default-project-column-header="{{ctx.Locale.Tr "repo.projects.column.set_default"}}"
 										data-modal-default-project-column-content="{{ctx.Locale.Tr "repo.projects.column.set_default_desc"}}"
 										data-url="{{$.Link}}/{{.ID}}/default">
-										{{svg "octicon-pin"}}
+										{{svg "octicon-star"}}
```
Comment (silverwind) [inline templates/projects/view.tmpl:93]: Not sure about this change, but if it stay, it needs a bit margin/gap.

File: templates/projects/view.tmpl [hunk 4]
```diff
@@ -64,15 +64,15 @@
...
+	<div class="board {{if .CanWriteProjects}}sortable{{end}}"{{if .CanWriteProjects}} data-url="{{$.Link}}/move"{{end}}>
 		{{range .Columns}}
 			<div class="ui segment project-column"{{if .Color}} style="background: {{.Color}} !important; color: {{ContrastColor .Color}} !important"{{end}} data-id="{{.ID}}" data-sorting="{{.Sorting}}" data-url="{{$.Link}}/{{.ID}}">
 				<div class="project-column-header{{if $canWriteProject}} tw-cursor-grab{{end}}">
 					<div class="ui large label project-column-title tw-py-1">
 						<div class="ui small circular grey label project-column-issue-count">
 							{{.NumIssues ctx}}
 						</div>
-						<span class="project-column-title-label">{{.Title}}</span>
+						<span class="project-column-title-label">{{.Title}}{{if .Default}}{{svg "octicon-star"}}{{end}}</span>
```
Comment (silverwind) [inline templates/projects/view.tmpl:75]: Not sure about this change to star icon, but if it stay, it needs a bit margin/gap.

Comment (silverwind) [inline templates/projects/view.tmpl]:
```suggestion
						<span class="project-column-title-label">{{.Title}}{{if .Default}}{{svg "octicon-star" 16 "tw-ml-2"}}{{end}}</span>
```

**Comment by silverwind** [comment]
Not sure I like this pin to star change, star icon does seem a bit out of place here.

**Comment by lunny** [comment]
> Not sure I like this pin to star change, star icon does seem a bit out of place here.

But it's not suitable to use `pin` to indicate it's a default column especially now default column can also be moved from the first position.

**Comment by silverwind** [comment]
Should users even have to care about "default column"? Imho we should remove that concept entirely.

**Comment by lunny** [comment]
> Should users even have to care about "default column"? Seems like useless visual distraction to render that icon.
> 
> Imho we should remove that concept entirely. What's the purpose a default column anyways?

Yes, I agree to remove the default column concept but not this PR. The default column exist absent feature of #30617

**Comment by silverwind** [comment]
> > Should users even have to care about "default column"? Seems like useless visual distraction to render that icon.
> > Imho we should remove that concept entirely. What's the purpose a default column anyways?
> 
> Yes, I agree to remove the default column concept but not this PR. The default column because of the absent feature #30617

Maybe then  remove the unrelated change with the icon?

**Comment by lunny** [comment]
> > > Should users even have to care about "default column"? Seems like useless visual distraction to render that icon.
> > > Imho we should remove that concept entirely. What's the purpose a default column anyways?
> > 
> > 
> > Yes, I agree to remove the default column concept but not this PR. The default column because of the absent feature #30617
> 
> Maybe then remove the unrelated change with the icon?

I'd say it's related. Before this PR, a default column will always be in the first position of a project board view. So that a `pin` icon is acceptable. But now, `default column` could be moved to any position, it's not `pin`, so a `star` maybe better?

**Comment by silverwind** [comment]
At least we need to find a better icon than star, star has a very specific meaning in gitea that should not be abused elsewhere.

File: models/project/issue.go [hunk 5]
```diff
@@ -17,7 +17,7 @@ type ProjectIssue struct { //revive:disable-line:exported
 	IssueID   int64 `xorm:"INDEX"`
 	ProjectID int64 `xorm:"INDEX"`
 
-	// If 0, then it has not been added to a specific board in the project
+	// If this should not be zero from 1.22. If it's zero, it will not be displayed on UI and maybe result in errors.
```
Comment (wxiaoguang) [inline models/project/issue.go]:
```suggestion
	// ProjectBoardID should not be zero since 1.22. If it's zero, the issue will not be displayed on UI and it might result in errors.
```

File: routers/web/org/projects.go [hunk 6]
```diff
@@ -678,3 +693,66 @@ func MoveIssues(ctx *context.Context) {
 
 	ctx.JSONOK()
 }
+
+// MoveColumns moves or keeps columns in a project and sorts them inside that project
+func MoveColumns(ctx *context.Context) {
+	if ctx.Doer == nil {
```
Comment (wxiaoguang) [inline routers/web/org/projects.go]: Why it needs this check? I do not think it could happen

File: routers/web/org/projects.go [hunk 7]
```diff
@@ -678,3 +693,66 @@ func MoveIssues(ctx *context.Context) {
...
+		Columns []struct {
+			ColumnID int64 `json:"columnID"`
+			Sorting  int64 `json:"sorting"`
+		} `json:"columns"`
+	}
+
+	form := &movedColumnsForm{}
+	if err = json.NewDecoder(ctx.Req.Body).Decode(&form); err != nil {
+		ctx.ServerError("DecodeMovedColumnsForm", err)
+	}
```
Comment (wxiaoguang) [inline routers/web/org/projects.go]: no return?

File: routers/web/repo/projects.go [hunk 8]
```diff
@@ -666,3 +681,70 @@ func MoveIssues(ctx *context.Context) {
 
 	ctx.JSONOK()
 }
+
+// MoveColumns moves or keeps columns in a project and sorts them inside that project
+func MoveColumns(ctx *context.Context) {
```
Comment (wxiaoguang) [inline routers/web/repo/projects.go]: I just saw the same function above? Why duplicate

File: routers/web/repo/pull.go [hunk 9]
```diff
@@ -1331,10 +1332,20 @@ func CompareAndPullRequestPost(ctx *context.Context) {
 
 	if projectID > 0 {
 		if !ctx.Repo.CanWrite(unit.TypeProjects) {
-			ctx.Error(http.StatusBadRequest, "user hasn't the permission to write to projects")
+			log.Error("user hasn't the permission to write to projects")
```
Comment (wxiaoguang) [inline routers/web/repo/pull.go]: Why not respond?

**Comment by silverwind** [comment]
Maybe https://primer.github.io/octicons/home-16 for default column.

File: routers/web/repo/pull.go (hunk 9 above)
Comment (lunny) [reply routers/web/repo/pull.go]: d300bfd

File: routers/web/repo/projects.go (hunk 8 above)
Comment (lunny) [reply routers/web/repo/projects.go]: d300bfd

File: routers/web/org/projects.go (hunk 7 above)
Comment (lunny) [reply routers/web/org/projects.go]: d300bfd

File: routers/web/org/projects.go (hunk 6 above)
Comment (lunny) [reply routers/web/org/projects.go]: d300bfd

File: models/project/board.go [hunk 10]
```diff
@@ -316,3 +329,12 @@ func UpdateBoardSorting(ctx context.Context, bs BoardList) error {
 		return nil
 	})
 }
+
+func GetColumnsByIDs(ctx context.Context, columnsIDs []int64) (BoardList, error) {
```
Comment (delvh) [inline models/project/board.go]: I recommend passing a `projectID int64`, and then using `And(project_id = projectID)` to prevent any unintended access.

File: models/project/issue.go [hunk 11]
```diff
@@ -102,7 +102,37 @@ func MoveIssuesOnProjectBoard(ctx context.Context, board *Board, sortedIssueIDs
 	})
 }
 
-func (b *Board) removeIssues(ctx context.Context) error {
-	_, err := db.GetEngine(ctx).Exec("UPDATE `project_issue` SET project_board_id = 0 WHERE project_board_id = ? ", b.ID)
+func (b *Board) moveIssuesToAnotherColumn(ctx context.Context, columnID int64) error {
+	if b.ID == columnID {
```
Comment (delvh) [inline models/project/issue.go]: also, `if b.ProjectID != getBoard(columnID).ProjectID return errNoAccess` or something like that

File: models/project/issue.go [hunk 12]
```diff
@@ -102,7 +102,37 @@ func MoveIssuesOnProjectBoard(ctx context.Context, board *Board, sortedIssueIDs
...
+
+// MoveColumnsOnProject moves or keeps issues in a column and sorts them inside that column
+func MoveColumnsOnProject(ctx context.Context, project *Project, sortedColumnIDs map[int64]int64) error {
+	return db.WithTx(ctx, func(ctx context.Context) error {
+		sess := db.GetEngine(ctx)
+
+		columnIDs := make([]int64, 0, len(sortedColumnIDs))
+		for _, columnID := range sortedColumnIDs {
+			columnIDs = append(columnIDs, columnID)
+		}
```
Comment (delvh) [inline models/project/issue.go]: Isn't there a `map.Values` method by now?

File: models/project/issue.go [hunk 13]
```diff
@@ -102,7 +102,37 @@ func MoveIssuesOnProjectBoard(ctx context.Context, board *Board, sortedIssueIDs
...
+		count, err := sess.Table(new(Board)).Where("project_id=?", project.ID).In("id", columnIDs).Count()
+		if err != nil {
+			return err
+		}
+		if int(count) != len(sortedColumnIDs) {
+			return fmt.Errorf("all issues have to be added to a project first")
```
Comment (delvh) [inline models/project/issue.go]: Error message is wrong when issues across multiple projects have been queried

File: routers/web/shared/project/column.go [hunk 14]
```diff
@@ -0,0 +1,74 @@
...
+		ctx.ServerError("DecodeMovedColumnsForm", err)
+		return
+	}
+
+	columnIDs := make([]int64, 0, len(form.Columns))
+	sortedColumnIDs := make(map[int64]int64)
+	for _, column := range form.Columns {
+		columnIDs = append(columnIDs, column.ColumnID)
+		sortedColumnIDs[column.Sorting] = column.ColumnID
+	}
```
Comment (delvh) [inline routers/web/shared/project/column.go]: There's a check for `len(columnIDs) != len(sortedColumnIDs)` missing here, for when two issues should get the same sorting

Comment (delvh) [inline routers/web/shared/project/column.go]: There's a check for `len(columnIDs) != len(sortedColumnIDs)` missing here, for when two issues should get the same sorting

Comment (lunny) [reply routers/web/shared/project/column.go]: f280c9b

Comment (lunny) [reply routers/web/shared/project/column.go]: f280c9b

File: models/project/issue.go (hunk 13 above)
Comment (lunny) [reply models/project/issue.go]: f280c9b

File: models/project/issue.go (hunk 12 above)
Comment (lunny) [reply models/project/issue.go]: f280c9b Which one did you mean? Looks like golang has a exp package but it cannot be allowed to import to Gitea. I have to write one myself.

File: models/project/issue.go (hunk 11 above)
Comment (lunny) [reply models/project/issue.go]: f280c9b

File: models/project/board.go (hunk 10 above)
Comment (lunny) [reply models/project/board.go]: f280c9b

File: models/project/board.go [hunk 15]
```diff
@@ -330,11 +330,13 @@ func UpdateBoardSorting(ctx context.Context, bs BoardList) error {
 	})
 }
 
-func GetColumnsByIDs(ctx context.Context, columnsIDs []int64) (BoardList, error) {
+func GetColumnsByIDs(ctx context.Context, projectID int64, columnsIDs []int64) (BoardList, error) {
 	columns := make([]*Board, 0, 5)
-	if err := db.GetEngine(ctx).In("id", columnsIDs).OrderBy("sorting").Find(&columns); err != nil {
+	if err := db.GetEngine(ctx).
+		Where("project_id =?", projectID).
```
Comment (delvh) [inline models/project/board.go:336]:
```suggestion
		Where("project_id = ?", projectID).
```

File: modules/container/map.go [hunk 16]
```diff
@@ -0,0 +1,14 @@
+// Copyright 2024 The Gitea Authors. All rights reserved.
+// SPDX-License-Identifier: MIT
+
+package container
+
+// MapValues returns a slice of all values in a map.
+// TODO: remove this after Golang std lib has similar function but not golang.org/x/exp
+func MapValues[K comparable, V any](m map[K]V) []V {
```
Comment (delvh) [inline modules/container/map.go]: Either remove this one or
```go
modules/util/slice.go
58:func ValuesOfMap[K comparable, V any](m map[K]V) []V {
```

File: models/project/issue.go [hunk 17]
```diff
@@ -102,34 +104,38 @@ func MoveIssuesOnProjectBoard(ctx context.Context, board *Board, sortedIssueIDs
...
-	_, err := db.GetEngine(ctx).Exec("UPDATE `project_issue` SET project_board_id = ? WHERE project_board_id = ? ", columnID, b.ID)
+	if b.ProjectID != newColumn.ProjectID {
+		return fmt.Errorf("columns have to be in the same project")
+	}
+	_, err := db.GetEngine(ctx).Exec("UPDATE `project_issue` SET project_board_id = ? WHERE project_board_id = ? ", newColumn.ID, b.ID)
 	return err
 }
 
-// MoveColumnsOnProject moves or keeps issues in a column and sorts them inside that column
+// MoveColumnsOnProject moves or keeps column in a project and sorts them inside that column
```
Comment (delvh) [inline models/project/issue.go]: The second part no longer makes sense

**Comment by yp05327** [comment]
This PR mixing `column` and `board`, I would suggest merging #30170 first

File: models/project/issue.go (hunk 17 above)
Comment (lunny) [reply models/project/issue.go]: 833ec563792b2fa883dbd147df19bb09bef61277

File: modules/container/map.go (hunk 16 above)
Comment (lunny) [reply modules/container/map.go]: 833ec563792b2fa883dbd147df19bb09bef61277

File: models/project/board.go [hunk 18]
```diff
@@ -156,6 +156,15 @@ func NewBoard(ctx context.Context, board *Board) error {
...
 	}
 
+	var maxSorting int8
+	if _, err := db.GetEngine(ctx).Select("Max(sorting)").Table("project_board").
+		Where("project_id=?", board.ProjectID).Get(&maxSorting); err != nil {
+		return err
+	}
+	if maxSorting > 0 {
+		board.Sorting = maxSorting + 1
+	}
```
Comment (yp05327) [inline models/project/board.go]: 1. It seems that we need a migration. 
For the existing project with only one default board, max sorting will always be 0.
2. sorting is int8, and will always +1, how to handle the overflow?

File: routers/web/repo/projects.go [hunk 19]
```diff
@@ -383,16 +383,41 @@ func UpdateIssueProject(ctx *context.Context) {
...
+		ctx.ServerError("LoadProjects", err)
+		return
+	}
 
 	projectID := ctx.FormInt64("id")
+	var dstColumnID int64
+	if projectID > 0 {
+		dstProject, err := project_model.GetProjectByID(ctx, projectID)
+		if err != nil {
+			ctx.ServerError("GetProjectByID", err)
```
Comment (yp05327) [inline routers/web/repo/projects.go]: A similar problem to #30580.
~~Didn't look into it, but tested if return `ServerError`, you will see nothing in frontend.~~

Updated:
https://github.com/go-gitea/gitea/pull/29776/files#diff-d39a63ccfd5f0fe703f74ce48a3624ba59a856317b0d236d7eae87dfcf6c1c20R351
image
After check the code, I can see this error log in console after enable preserve log (it seems that it is disabled by default, so user will see nothing as it will be refreshed after window.location.reload())

I'm confusing which one should be used, JSON error or server error or both of them are ok when the 200 response type is JSON

Comment (yp05327) [reply routers/web/repo/projects.go:396]: https://github.com/go-gitea/gitea/pull/29722/files#diff-4f89ee029f289a1c40cf85fa40b0a10046a93d5fe1dac8d158e98bebd2e6e49eR83
the response will not be handled, so no matter what error occurred user will not see any error message if the operation is failed.

File: models/project/board.go (hunk 18 above)
Comment (lunny) [reply models/project/board.go]: This is columns number on a project, I don't think they should have too much columns. I think maybe we could have a max_number of columns for that but no migrations.

File: routers/web/repo/projects.go [hunk 20]
```diff
@@ -383,16 +383,41 @@ func UpdateIssueProject(ctx *context.Context) {
 		ctx.ServerError("LoadProjects", err)
 		return
 	}
+	if _, err := issues.LoadRepositories(ctx); err != nil {
+		ctx.ServerError("LoadProjects", err)
```
Comment (yp05327) [inline routers/web/repo/projects.go:388]:
```suggestion
		ctx.ServerError("LoadRepositories", err)
```

File: routers/web/repo/projects.go (hunk 19 above)
Comment (lunny) [reply routers/web/repo/projects.go]: 81d455fa6cd22994ee99eb819f13e2b10fc2e874

File: routers/web/repo/projects.go (hunk 20 above)
Comment (lunny) [reply routers/web/repo/projects.go:388]: 81d455fa6cd22994ee99eb819f13e2b10fc2e874

File: services/context/context.go [hunk 21]
```diff
@@ -267,3 +268,14 @@ func (ctx *Context) JSONError(msg any) {
...
+
+func (ctx *Context) JSONServerError(msg string, err error) {
+	errorMessage := msg
+	if err != nil {
+		log.Log(1, log.ERROR, "%s: %v", msg, err)
+		if ctx.Doer != nil && ctx.Doer.IsAdmin {
+			errorMessage = fmt.Sprintf("%s: %v", errorMessage, err)
+		}
+	}
+	ctx.JSON(http.StatusBadRequest, map[string]any{"errorMessage": errorMessage, "renderFormat": "text"})
```
Comment (yp05327) [inline services/context/context.go]: convert into `JSONError`?

File: models/project/board.go (hunk 18 above)
Comment (yp05327) [reply models/project/board.go]: max_number is necessary I think, at least adding a check when create new column

Comment (lunny) [reply models/project/board.go]: 03562c7ff70c9d51e5140b1f38eb6c62ad40663b

File: services/context/context.go (hunk 21 above)
Comment (lunny) [reply services/context/context.go]: 24c2c13c418e501fdcd82e6b74b5d2c5a33b68d4

File: services/context/context.go [hunk 22]
```diff
@@ -267,3 +268,14 @@ func (ctx *Context) JSONError(msg any) {
 		panic(fmt.Sprintf("unsupported type: %T", msg))
 	}
 }
+
+func (ctx *Context) JSONServerError(msg string, err error) {
```
Comment (wxiaoguang) [inline services/context/context.go]: Do not do so. Are you sure about what you are doing or it really works?

Comment (yp05327) [reply services/context/context.go]: Do you have ideas about handling internal server error if the response should be JSON in backend?

I think it is a bit strange to return bad request status when internal error occurred.
And in frontend, no matter what happened it will always reload the page so it will not show anything.
image

File: routers/web/repo/projects.go (hunk 19 above)
Comment (yp05327) [reply routers/web/repo/projects.go]: I think we can ignore this issue in this PR, and fix it later, as this needs discussion.

File: services/context/context.go (hunk 22 above)
Comment (wxiaoguang) [reply services/context/context.go]: The idea is: design some framework mechanisms carefully and rewrite.

Comment (yp05327) [reply services/context/context.go]: I have left a comment above:
https://github.com/go-gitea/gitea/pull/30696#discussion_r1586974696

I think we can ignore this issue in this PR, and do it later as you suggested.

Comment (lunny) [reply services/context/context.go]: Or I can revert the changes around the returned 500 and leave it for other PRs since it's not tight with this PR.

**Comment by yp05327** [comment]
image

**Comment by lunny** [comment]
> image maybe can be done in #29311

Yes, this PR will focus on fixing bug.

File: services/context/context.go (hunk 22 above)
Comment (lunny) [reply services/context/context.go]: e9f58eb5f9ed664e3156692467918c6b1ca6093d reverted

File: models/project/issue.go [hunk 23]
```diff
@@ -102,7 +104,41 @@ func MoveIssuesOnProjectBoard(ctx context.Context, board *Board, sortedIssueIDs
...
+		if err != nil {
+			return err
+		}
+		if len(movedColumns) != len(sortedColumnIDs) {
+			return errors.New("some columns do not exist")
+		}
+
+		for _, column := range movedColumns {
+			if column.ProjectID != project.ID {
+				return errors.New("some column's projectID is not equal to project's ID")
```
Comment (yp05327) [inline models/project/issue.go]: instead of `some`. print `column.ID`, `column.ProjectID` and `project.ID`?
same to L128

File: routers/web/shared/project/column.go [hunk 24]
```diff
@@ -0,0 +1,53 @@
...
+		return
+	}
+	if project.RepoID > 0 && project.RepoID != ctx.Repo.Repository.ID {
+		ctx.NotFound("InvalidRepoID", nil)
+		return
+	}
+
+	type movedColumnsForm struct {
+		Columns []struct {
+			ColumnID int64 `json:"columnID"`
```
Comment (yp05327) [inline routers/web/shared/project/column.go:26]:
```suggestion
			ColumnID int64 `json:"column_id"`
```

File: routers/web/shared/project/column.go [hunk 25]
```diff
@@ -0,0 +1,53 @@
...
+		return
+	}
+
+	sortedColumnIDs := make(map[int64]int64)
+	for _, column := range form.Columns {
+		sortedColumnIDs[column.Sorting] = column.ColumnID
+	}
+
+	if err = project_model.MoveColumnsOnProject(ctx, project, sortedColumnIDs); err != nil {
+		ctx.NotFoundOrServerError("MoveColumnsOnProject", issues_model.IsErrIssueNotExist, err)
```
Comment (yp05327) [inline routers/web/shared/project/column.go]: Where does `issues_model.IsErrIssueNotExist` come from? 🤔

File: templates/projects/view.tmpl [hunk 26]
```diff
@@ -64,7 +64,7 @@
 </div>
 
 <div id="project-board">
-	<div class="board {{if .CanWriteProjects}}sortable{{end}}">
+	<div class="board {{if .CanWriteProjects}}sortable{{end}}"{{if .CanWriteProjects}} data-url="{{$.Link}}/move"{{end}}>
```
Comment (yp05327) [inline templates/projects/view.tmpl:67]: `{{if .CanWriteProjects}}` twice?

File: web_src/js/features/repo-projects.js [hunk 27]
```diff
@@ -63,17 +62,20 @@ async function initRepoProjectSortable() {
...
+        columns: Array.from(boardColumns, (column, i) => ({
+          columnID: parseInt(column.getAttribute('data-id')),
+          sorting: i,
+        })),
+      };
+
+      try {
+        await POST(mainBoard.getAttribute('data-url'), {
+          data: columnSorting,
+        });
```
Comment (yp05327) [inline web_src/js/features/repo-projects.js:76]: Do we need raise exception when response is not 200?

File: routers/web/shared/project/column.go (hunk 24 above)
Comment (lunny) [reply routers/web/shared/project/column.go:26]: Why? The frontend also used `columnID`.

File: templates/projects/view.tmpl (hunk 26 above)
Comment (lunny) [reply templates/projects/view.tmpl:67]: The first one to add a new class, the second one to add a new attribute. I don't think mixing them is a good idea for readability.

File: web_src/js/features/repo-projects.js (hunk 27 above)
Comment (lunny) [reply web_src/js/features/repo-projects.js:76]: I don't think so. Following all other similar functions.

File: models/project/issue.go (hunk 23 above)
Comment (lunny) [reply models/project/issue.go]: 699c9e618764134fa318606be9449edfc2ec9724

File: routers/web/shared/project/column.go (hunk 25 above)
Comment (lunny) [reply routers/web/shared/project/column.go]: 699c9e618764134fa318606be9449edfc2ec9724

**Comment by wxiaoguang** [comment]
Any test for the new code?

**Comment by lunny** [comment]
> Any test for the new code?

Tests added.

File: models/issues/issue_project.go [hunk 28]
```diff
@@ -90,22 +90,16 @@ func LoadIssuesFromBoardList(ctx context.Context, bs project_model.BoardList) (m
...
-	}
-	defer committer.Close()
-
-	if err := addUpdateIssueProject(ctx, issue, doer, newProjectID); err != nil {
-		return err
-	}
-
-	return committer.Commit()
+// ChangeProjectAssign changes the project associated with an issue, if newProjectID is 0, the issue is removed from the project
+func ChangeProjectAssign(ctx context.Context, issue *Issue, doer *user_model.User, newProjectID, newColumnID int64) error {
```
Comment (wxiaoguang) [inline models/issues/issue_project.go]: ChangeProjectAssign is exactly addUpdateIssueProject? Why it needs this wrapper

File: models/project/issue.go [hunk 29]
```diff
@@ -102,7 +102,13 @@ func MoveIssuesOnProjectBoard(ctx context.Context, board *Board, sortedIssueIDs
...
-func (b *Board) removeIssues(ctx context.Context) error {
-	_, err := db.GetEngine(ctx).Exec("UPDATE `project_issue` SET project_board_id = 0 WHERE project_board_id = ? ", b.ID)
+func (b *Board) moveIssuesToAnotherColumn(ctx context.Context, newColumn *Board) error {
+	if b.ID == newColumn.ID {
+		return nil
+	}
+	if b.ProjectID != newColumn.ProjectID {
+		return fmt.Errorf("columns have to be in the same project")
+	}
+	_, err := db.GetEngine(ctx).Exec("UPDATE `project_issue` SET project_board_id = ? WHERE project_board_id = ? ", newColumn.ID, b.ID)
```
Comment (wxiaoguang) [inline models/project/issue.go]: Why the issue's sorting is kept as old value?

File: routers/web/shared/project/column.go [hunk 30]
```diff
@@ -0,0 +1,52 @@
...
+)
+
+// MoveColumns moves or keeps columns in a project and sorts them inside that project
+func MoveColumns(ctx *context.Context) {
+	project, err := project_model.GetProjectByID(ctx, ctx.ParamsInt64(":id"))
+	if err != nil {
+		ctx.NotFoundOrServerError("GetProjectByID", project_model.IsErrProjectNotExist, err)
+		return
+	}
+	if project.OwnerID > 0 && project.OwnerID != ctx.ContextUser.ID {
```
Comment (wxiaoguang) [inline routers/web/shared/project/column.go]: Why not check "can write project"?

Comment (lunny) [reply routers/web/shared/project/column.go]: The write project permission has been checked on the `routers` definition functions.

File: models/project/issue.go (hunk 29 above)
Comment (lunny) [reply models/project/issue.go]: cf9ef10

File: models/issues/issue_project.go (hunk 28 above)
Comment (lunny) [reply models/issues/issue_project.go]: cf9ef105101fbc13f1e971b45036a6a46edf5b19
functions renamed.

File: routers/web/shared/project/column.go (hunk 30 above)
Comment (wxiaoguang) [reply routers/web/shared/project/column.go]: What does it do here?

File: models/issues/issue_project.go [hunk 31]
```diff
@@ -90,16 +90,16 @@ func LoadIssuesFromBoardList(ctx context.Context, bs project_model.BoardList) (m
 	return issuesMap, nil
 }
 
-// ChangeProjectAssign changes the project associated with an issue, if newProjectID is 0, the issue is removed from the project
-func ChangeProjectAssign(ctx context.Context, issue *Issue, doer *user_model.User, newProjectID, newColumnID int64) error {
+// IssueAssignOrRemoveProject changes the project associated with an issue, if newProjectID is 0, the issue is removed from the project
+func IssueAssignOrRemoveProject(ctx context.Context, issue *Issue, doer *user_model.User, newProjectID, newColumnID int64) error {
```
Comment (wxiaoguang) [inline models/issues/issue_project.go:95]: Again, why it needs this wrapper? Database transaction could be virtually nested by XORM.

Comment (lunny) [reply models/issues/issue_project.go:95]: It's just derived from old code. To reduce the changes to make review easier, so I haven't merge them as one function. If you think it's better, I can do it in this PR. Otherwise, I can do it in another PR.

File: routers/web/shared/project/column.go (hunk 30 above)
Comment (lunny) [reply routers/web/shared/project/column.go]: The write project permission check will only check the current login user has write permission to the repository's project unit. However it will not check whether the project belongs to this repository or this organization. This checks will avoid the request like `/<owner>/<repo>/projects/<non-current-repo-project-id>`

File: models/issues/issue_project.go (hunk 31 above)
Comment (lunny) [reply models/issues/issue_project.go:95]: f7f36ddbaaf0619ce0d47bbb2d75763d56ca4a0c

File: routers/web/shared/project/column.go (hunk 30 above)
Comment (wxiaoguang) [reply routers/web/shared/project/column.go]: Then it still needs to introduce a general function `can write to project {id}`? It seems that it is not the only call.

Comment (lunny) [reply routers/web/shared/project/column.go]: But all of them are only 1 line, I don't think that's related to the bug fixes. Maybe other PRs.

Comment (wxiaoguang) [reply routers/web/shared/project/column.go]: I do not see "1 line" is a reason. All other "can read" or "can write" are also all just 1 line.

----

Now, it is indeed 1 line, but they are all copied & pasted and there is no test. You could have 9 places right, but if one place goes wrong, then there is a security problem.

**Comment by wxiaoguang** [comment]
Rewritten and simplified.

**Comment by lunny** [comment]
> This PR mixing `column` and `board`, I would suggest merging #30170 first

Since this is a bug fix and will be backported to v1.22. So I think it's better to merge this one and then that one.

File: models/project/board.go [hunk 32]
```diff
@@ -150,12 +163,27 @@ func createBoardsForProjectsType(ctx context.Context, project *Project) error {
 	return db.Insert(ctx, boards)
 }
 
+// maxProjectColumns max columns allowed in a project, this should not bigger than 127
+// because sorting is int8 in database
+const maxProjectColumns = 20
```
Comment (yp05327) [inline models/project/board.go:168]: This should have a description in docs I think.

Comment (lunny) [reply models/project/board.go:168]: I think you are right but currently, there is no documentation for projects. This could be added after project documentation is added.

**Review by silverwind — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]
