### PR TITLE
Fix review request notification email links when external issue tracker is enabled

### LINKED ISSUE #13720: Review request email notification links to external issue tracker
- Gitea version (or commit ref): 1.12.6
- Operating system: docker
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No

## Description

If an external issue tracker is configured, the PR link in the "review request" notification email points to the external issue tracker instead of the gitea pull request.

## Screenshots

Without an external issue tracker configured:
image
=> It links to /issues/ instead of /pulls/. This works though (I guess gitea redirects to the pull request if issue does not exist).

With an external issue tracker configured:
image
=> It links to the external issue tracker instead of the pull request.

Note that the "View it on Gitea link" below it DOES work.

### PR DESCRIPTION
**Pull request by jpraet**
Fixes #13720 

Use !%d issue notation instead of #%d in review request notification when external issue tracker is enabled.

Or would it be preferrable to just always use the !%d notation here?
I noticed in other places like the default squash commit messages the choice between ! and # is also done based on whether external issue tracker is enabled. So I did it here as well.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by mrsdizzie** [comment]
I think this could be fixed to pass the fact that we know it is a PR in the metas so we aren't sending users the weird ! workaround (since we know it is a PR already and that is just for the case when a user is typing and we can't possibly know if they mean an issue or PR by just a number).

File: modules/notification/mail/mail.go [hunk 1]
```diff
@@ -104,7 +104,12 @@ func (m *mailNotifier) NotifyIssueChangeAssignee(doer *models.User, issue *model
 
 func (m *mailNotifier) NotifyPullReviewRequest(doer *models.User, issue *models.Issue, reviewer *models.User, isRequest bool, comment *models.Comment) {
 	if isRequest && doer.ID != reviewer.ID && reviewer.EmailNotifications() == models.EmailNotificationsEnabled {
-		ct := fmt.Sprintf("Requested to review #%d.", issue.Index)
+		var ct string
+		if issue.Repo.UnitEnabled(models.UnitTypeExternalTracker) {
+			ct = fmt.Sprintf("Requested to review !%d.", issue.Index)
```
Comment (mrsdizzie) [inline modules/notification/mail/mail.go]:
```suggestion
			ct := fmt.Sprintf("Requested to review %s.", issue.HTMLURL())
```
This should end up with the correct result since issue.HTMLURL() will have the full URL to the pull and then when it is rendered it will be converted to the expected ```#2``` type format with the link pointing at the correct place (as a shorter option then trying to keep track of it is a pull through metas)

Comment (zeripath) [reply modules/notification/mail/mail.go]: cunning plan

**Review by lafriks — APPROVED** [review]
