### PR TITLE
Fix wrong review requested number

### LINKED ISSUE #18808: Member of Two Teams Shows Up Twice on Review Request
### Gitea Version

1.16

### Git Version

2.24.1

### Operating System

RHEL 7

### How are you running Gitea?

I was able to reproduce this on try.gitea.io. [https://try.gitea.io/developers/foobar/pulls/1](https://try.gitea.io/developers/foobar/pulls/1)

We download the binary (linux-amd64) from the releases page and install in /usr/bin.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Description

Create two teams with at least one user on both teams. Create a pull request and add both teams as reviewers. Login as the user on both teams and go to your "Review Requested ". The PR will appear twice in the list.

### Screenshots

image

### PR DESCRIPTION
**Pull request by nanguanlin6**
Fix the wrong review requested number mentioned by #18808 .
Fix #18808 
Before:
ksnip_20230829-140750
After:
ksnip_20230829-141817

### CODE REVIEW

**Review by yp05327 — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Review by CaiCandong — APPROVED** [review]

**Comment by yp05327** [comment]
image

File: models/issues/issue_search.go [hunk 1]
```diff
@@ -480,7 +480,7 @@ func IssueIDs(ctx context.Context, opts *IssuesOptions, otherConds ...builder.Co
 	applySorts(sess, opts.SortType, opts.PriorityRepoID)
```
Comment (yp05327) [inline models/issues/issue_search.go]:
```suggestion
```
As a simple fix method, we only care about issue ids here, so no need to add sort options.
It seems that using both `orderby` and `distinct` will cause sql error.

ps: only tested in mysql8, not sure this will fix all ci fails.

Comment (yp05327) [reply models/issues/issue_search.go]: But maybe in some cases, we need a sorted issue ids list? Not sure about this.

Comment (nanguanlin6) [reply models/issues/issue_search.go]: Thanks for your advice! I also agree that removing `applySorts` will solve the problem, but manually removing the duplicate key looks safer. I doubt if the function `Issues()` will have the same problem as duplicate records too and we just haven't discovered the case yet.

**Comment by lng2020** [comment]
@techknowlogick Hi, can you remove the reviewed/wait-merge tag for me? There are still bugs in this code. Thank you in advance!

File: models/issues/issue_search.go [hunk 2]
```diff
@@ -358,12 +358,9 @@ func applyMentionedCondition(sess *xorm.Session, mentionedID int64) *xorm.Sessio
 }
 
 func applyReviewRequestedCondition(sess *xorm.Session, reviewRequestedID int64) *xorm.Session {
-	return sess.Join("INNER", []string{"review", "r"}, "issue.id = r.issue_id").
-		And("issue.poster_id <> ?", reviewRequestedID).
-		And("r.type = ?", ReviewTypeRequest).
-		And("r.reviewer_id = ? and r.id in (select max(id) from review where issue_id = r.issue_id and reviewer_id = r.reviewer_id and type in (?, ?, ?))"+
-			" or r.reviewer_team_id in (select team_id from team_user where uid = ?)",
-			reviewRequestedID, ReviewTypeApprove, ReviewTypeReject, ReviewTypeRequest, reviewRequestedID)
+	return sess.Where("EXISTS (SELECT 1 FROM review r WHERE r.issue_id = issue.id AND r.type in (?, ?, ?) AND issue.poster_id <> ? "+
```
Comment (CaiCandong) [inline models/issues/issue_search.go]: Please use xorm.Builder to generate SQL 
https://gitea.com/xorm/builder

**Comment by lng2020** [comment]
current SQL query
```sql
SELECT issue.id
FROM issue
... // other condition
JOIN review ON review.issue_id = issue.id
JOIN team_user ON team_user.team_id = review.reviewer_team_id AND team_user.uid = <user_id>
WHERE review.`type` IN ('type1', 'type2', 'type3')
AND (r.reviewer_id = <user_id> OR tu.team_id IS NOT NULL)
AND issue.poster_id <> <user_id>
GROUP BY i.id
... // other limit or order
```

**Review by CaiCandong — APPROVED** [review]

**Comment by techknowlogick** [comment]
Is it okay to add "wait-merge" label back again?

**Comment by lng2020** [comment]
> Is it okay to add "wait-merge" label back again?

I believe so
