### PR TITLE
Hide target selector if tag exists when creating new release

### LINKED ISSUE #22649: Release targeting wrong branch after deleting another release with the same tag but different branch
### Description

Steps to reproduce:

1. In a repository with at least 2 branches one with some changes (in this example: main branch, test branch) create a release 1.0.0@test (**1.0.0** tag name, **test** branch).
2. Delete the created release.
3. Create a new release with the same tag but in the correct branch 1.0.0@main

Expected behaviour:
 &nbsp;&nbsp;&nbsp;&nbsp;The last release and tag should show the changes/commits made on the branch main.
Observed behaviour:
&nbsp;&nbsp;&nbsp;&nbsp;The release show the changes made on the test branch even when the release says is targeting the main branch and shows negative commits like this:
image

More Info:
 [the main branch has a empty readme file](https://try.gitea.io/krone/TestRelease/src/branch/main/README.md)
[ the test branch has 2 commits changing the readme file](https://try.gitea.io/krone/TestRelease/src/branch/test/README.md)
[the tag 1.0.0 show the file with the changes made on test branch](https://try.gitea.io/krone/TestRelease/src/tag/1.0.0)
if a click on the "-2 commits" the "Compare commits" screen shows no changes.
image

### Gitea Version

1.18.3 and 1.19.0 (gitea demo)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Debian Linux and Try.gitea.io

### How are you running Gitea?

The issue can be replicated both on my docker installation of giteo and in https://try.gitea.io/

### Database

None

### PR DESCRIPTION
**Pull request by Zettat123**
Close #22649.

|status|screenshot|
|-|-|
|empty tag name||
|new tag||
|existing tag||

### CODE REVIEW

File: web_src/js/features/tag-name-editor.js [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+  if (!el) return;
+
+  const existingTags = JSON.parse(el.getAttribute('data-existing-tags'));
+  if (!Array.isArray(existingTags)) return;
+
+  const defaultTagHelperText = el.getAttribute('data-tag-helper');
+  const newTagHelperText = el.getAttribute('data-tag-helper-new');
+  const existingTagHelperText = el.getAttribute('data-tag-helper-existing');
+
+  $('#tag-name').on('keyup', (e) => {
```
Comment (wxiaoguang) [inline web_src/js/features/tag-name-editor.js]: https://docs.gitea.io/en-us/guidelines-frontend/#framework-usage

It's better to avoid mixing jQuery and Vanilla JS together which reduces the maintainability.

Vanilla JS seems enough?

File: web_src/js/features/tag-name-editor.js [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+    const value = e.target.value;
+    if (existingTags.includes(value)) {
+      // If the tag already exists, hide the target branch selector.
+      hideElem($('#tag-target-selector'));
+      $('#tag-helper').text(existingTagHelperText);
+    } else {
+      showElem($('#tag-target-selector'));
+      if (typeof value === 'string' && value.length > 0) {
```
Comment (wxiaoguang) [inline web_src/js/features/tag-name-editor.js]: `if (value)` seems enough?

```suggestion
      if (value) {
```

File: web_src/js/features/tag-name-editor.js (hunk 1 above)
Comment (Zettat123) [reply web_src/js/features/tag-name-editor.js]: Thanks for your reviewing. I've removed jQuery and only use Vanilla JS.

File: web_src/js/features/tag-name-editor.js (hunk 2 above)
Comment (Zettat123) [reply web_src/js/features/tag-name-editor.js]: Yes, you're right. I have fixed it.

**Review by lunny — APPROVED** [review]

File: templates/repo/release/new.tmpl [hunk 3]
```diff
@@ -20,22 +20,27 @@
...
-								{{.locale.Tr "repo.release.target"}} :
-								<strong id="repo-branch-current">{{.Repository.DefaultBranch}}</strong>
-							</div>
-							{{svg "octicon-triangle-down" 14 "dropdown icon"}}
-							<div class="menu">
-								{{range .Branches}}
-									<div class="item" data-value="{{.}}">{{.}}</div>
-								{{end}}
+						<input id="tag-name-editor" type="hidden" data-existing-tags={{Json .Tags}} data-tag-helper={{.locale.Tr "repo.release.tag_helper"}} data-tag-helper-new={{.locale.Tr "repo.release.tag_helper_new"}} data-tag-helper-existing={{.locale.Tr "repo.release.tag_helper_existing"}} />
+						<span id="tag-target-selector">
```
Comment (wxiaoguang) [inline templates/repo/release/new.tmpl]: Usually `div` (below) is not suitable to be put inside a `span`. So this element could be a `div`

File: web_src/js/index.js [hunk 4]
```diff
@@ -198,4 +199,6 @@ $(document).ready(() => {
   initUserAuthWebAuthnRegister();
   initUserSettings();
   initViewedCheckboxListenerFor();
+
+  initTagNameEditor();
```
Comment (wxiaoguang) [inline web_src/js/index.js]: IMO we do not need to make more global `init` calls.

The `tag-name-editor` only appears on the `repository new release` page.

So the exiting `initRepoReleaseEditor` could be refactored to something like:

```js
export function initRepoReleaseNew() {
    const $repoReleaseNew = $('.repository.new.release');
    if (!$repoReleaseNew.length) return;

    // init tag name editor
    // init content editor
}
```

File: templates/repo/release/new.tmpl (hunk 3 above)
Comment (Zettat123) [reply templates/repo/release/new.tmpl]: Yes, I replaced `span` with `div`.

File: web_src/js/index.js (hunk 4 above)
Comment (Zettat123) [reply web_src/js/index.js]: Good idea. I refactored the `initRepoReleaseEditor` according to your comment.

File: templates/repo/release/new.tmpl [hunk 5]
```diff
@@ -20,22 +20,27 @@
...
+								<div class="menu">
+									{{range .Branches}}
+										<div class="item" data-value="{{.}}">{{.}}</div>
+									{{end}}
+								</div>
 							</div>
 						</div>
-						<span class="help">{{.locale.Tr "repo.release.tag_helper"}}</span>
+						<div>
+							<span id="tag-helper" class="help">{{.locale.Tr "repo.release.tag_helper"}}</span>
```
Comment (silverwind) [inline templates/repo/release/new.tmpl]:
```suggestion
							<span id="tag-helper" class="help gt-mt-2">{{.locale.Tr "repo.release.tag_helper"}}</span>
```

Add a bit margin.

Comment (Zettat123) [reply templates/repo/release/new.tmpl]: Added margin. Please review again, thanks!

Comment (silverwind) [reply templates/repo/release/new.tmpl]: Looks good

**Review by silverwind — APPROVED** [review]

**Comment by jolheiser** [comment]
🎺 🤖
