### PR TITLE
Fix scheduled action panic with null event payload

### LINKED ISSUE #37447: Actions withScheduleInEventPayload PANIC
### Description

```
2026/04/27 08:41:47 services/cron/tasks.go:106:(*Task).RunWithUser.1.1() [E] PANIC whilst running task: start_schedule_tasks Value: assignment to entry in nil map
/usr/local/go/src/internal/runtime/maps/runtime_faststr.go:265 (0x419f0c)
/go/src/code.gitea.io/gitea/services/actions/schedule_tasks.go:145 (0x1f836be)
/go/src/code.gitea.io/gitea/services/actions/schedule_tasks.go:105 (0x1f83384)
/go/src/code.gitea.io/gitea/services/actions/schedule_tasks.go:71 (0x1f82edd)
/go/src/code.gitea.io/gitea/services/actions/schedule_tasks.go:23 (0x2b6e99c)
/go/src/code.gitea.io/gitea/services/cron/tasks_actions.go:64 (0x2b6e99d)
/go/src/code.gitea.io/gitea/services/cron/tasks.go:124 (0x2b6b362)
/go/src/code.gitea.io/gitea/modules/graceful/manager.go:88 (0xe7b6d8)
/go/src/code.gitea.io/gitea/services/cron/tasks.go:101 (0x2b6afcb)
/go/src/code.gitea.io/gitea/services/cron/tasks.go:70 (0x2b6f78c)
/usr/local/go/src/reflect/value.go:586 (0x51e245)
/usr/local/go/src/reflect/value.go:369 (0x51d0f8)
/go/pkg/mod/github.com/go-co-op/gocron/v2@v2.19.1/util.go:28 (0x2b574e4)
/go/pkg/mod/github.com/go-co-op/gocron/v2@v2.19.1/executor.go:478 (0x2b4df24)
/go/pkg/mod/github.com/go-co-op/gocron/v2@v2.19.1/executor.go:249 (0x2b4c1bb)
/usr/local/go/src/runtime/asm_amd64.s:1771 (0x49af20)
```

I get this error since 1.26.1? I didn't notice it before could be there for longer.

Cheers

### Gitea Version

1.26.1

### Operating System

RHEL 9

### How are you running Gitea?

Docker

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by cyphercodes**
This fixes the scheduled action panic when an event payload is JSON `null` by initializing the payload map before adding `schedule`. It also adds regression coverage for the null-payload case.

Fixes #37447.

Testing:
- `go test -tags 'sqlite sqlite_unlock_notify' ./services/actions -run '^TestWithScheduleInEventPayload$' -count=1`
  - Local note: this agent ran the command as root with a temporary `GITEA_TEST_CONF=custom/conf/app-test-root.ini` file that only set `I_AM_BEING_UNSAFE_RUNNING_AS_ROOT = true`.

Authorship: cyphercodes; AI assistance disclosed: Hermes Agent (GPT-5.5).

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: services/actions/schedule_tasks.go [hunk 1]
```diff
@@ -141,6 +141,9 @@ func withScheduleInEventPayload(eventPayload, schedule string) string {
 		log.Error("withScheduleInEventPayload: unmarshal: %v", err)
 		return eventPayload
 	}
```
Comment (wxiaoguang) [inline services/actions/schedule_tasks.go]: I think It should treat eventPayload=="" as empty map and update the tests

Or, it needs some comment about why "eventPayload" can be empty string, why it can happen, what it means.

Comment (bircni) [reply services/actions/schedule_tasks.go]: fxied

Comment (bircni) [reply services/actions/schedule_tasks.go]: Ok cool i cannot push

**Comment by cyphercodes** [comment]
Rechecked wxiaoguang's inline feedback against current HEAD `fd2ab90dfc1c67b73846550816b38793af4b24c7`. The current diff already treats `eventPayload == ""` as an empty payload/map and includes the regression test for that case, so I did not push another commit.

Local verification:
- Created temporary root-test config `custom/conf/hermes-root-test.ini` with `I_AM_BEING_UNSAFE_RUNNING_AS_ROOT = true`, then ran `GITEA_TEST_CONF=custom/conf/hermes-root-test.ini PATH=/root/sdk/go1.26.2/bin:$PATH go test -tags 'sqlite sqlite_unlock_notify' -run '^TestWithScheduleInEventPayload$' ./services/actions/` ✅
- `PATH=/root/sdk/go1.26.2/bin:$PATH gofmt -l services/actions/schedule_tasks.go services/actions/schedule_tasks_test.go` ✅ (no output)
- `git diff --check upstream/main...HEAD` ✅

Authored-by: Hermes Agent (GPT-5.5)

**Comment by bircni** [comment]
> Rechecked wxiaoguang's inline feedback against current HEAD `fd2ab90dfc1c67b73846550816b38793af4b24c7`. The current diff already treats `eventPayload == ""` as an empty payload/map and includes the regression test for that case, so I did not push another commit.

Yes as I did it 👀

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Test failure is unrelated
