### PR TITLE
Restore user autoregistration with email addresses

### LINKED ISSUE #19256: SMTP Auto Registration Broken after v1.15.11
### Description

If I add an SMTP auth source to an install of Gitea v1.15.11, I can register new accounts by logging in against that source.

If I do the same in Gitea v1.16.5, new accounts will not register, and I get a `Username or password is incorrect.` error. This is true whether I use a fresh install, or if I migrate the above instance to v1.16.

Even though I can't register a new account, if I add the user manually I can then login with SMTP auth. This implies the SMTP connection is set up correctly.

I am doing all this as part of an evaluation exercise, so these are all fresh, clean Gitea installs.

I get the following in the logs:

> 2022/03/29 09:10:19 Completed GET /user/login?redirect_to=%2f 200 OK in 10.7847ms
> 2022/03/29 09:10:19 Started GET /assets/img/logo.svg for 127.0.0.1:54610
> 2022/03/29 09:10:19 Completed GET /assets/img/logo.svg 200 OK in 949.5µs
> 2022/03/29 09:10:32 Started POST /user/login for 127.0.0.1:54612
> 2022/03/29 09:10:32 ...ers/web/auth/auth.go:200:SignInPost() [I] Failed authentication attempt for <my-email@domain.com> from 127.0.0.1:54612: Email address does not exist [email: <my-email@domain.com>]
> 2022/03/29 09:10:32 Completed POST /user/login 200 OK in 5.5843ms

My research suggests that this relates to issue https://github.com/go-gitea/gitea/pull/16612, where the SMTP was overhauled between the two versions.

---

# Reproduction:
## v1.15.11 working
- Create a new instance of Gitea v1.15.11 running locally
- Change the DB type to SQLite and approve the initial setup
- Create an admin account and log in
- Add an authentication source, SMTP, "LOGIN", Enable TLS Encryption
- Log out, then try to log in with a valid account on the SMTP server
- - This will succeed

## v.1.16.5 not working
- Create a new instance of Gitea v1.16.5 running locally
- Change the DB type to SQLite and approve the initial setup
- Create an admin account and log in
- Add an authentication source, SMTP, "LOGIN"
- Log out, then try to log in with a valid account on the SMTP server
- - This will fail
- Log back in as an admin, and add that SMTP account as a new user
- Log out,and attempt to log in the SMTP account again
- - This will succeed

### Gitea Version

v1.16.5

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Self hosted on both WSL Ubuntu 20 and Windows 11. Not running in a package.

### Database

SQLite

### PR DESCRIPTION
**Pull request by zeripath**
Unfortunately #18789 disabled autoregistration using email addresses as they would
be shortcut to email address does not exist.

This PR attempts to restore autoregistration by allowing an unknown email address
to percolate through to the autoregistration path of UserSignin.

Fix #19256

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: services/auth/signin.go [hunk 1]
```diff
@@ -23,19 +23,23 @@ import (
...
+		isEmail = true
 		emailAddress := user_model.EmailAddress{LowerEmail: strings.ToLower(strings.TrimSpace(username))}
 		// check same email
-		has, err := db.GetEngine(db.DefaultContext).Where("is_activated=?", true).Get(&emailAddress)
+		has, err := db.GetEngine(db.DefaultContext).Get(&emailAddress)
 		if err != nil {
 			return nil, nil, err
 		}
-		if !has {
+		if !emailAddress.IsActivated {
```
Comment (lunny) [inline services/auth/signin.go]: `emailAddress.IsActivated` hides following `has`.

**Comment by wxiaoguang** [comment]
That's a lot of changes, I think if there is a chance, we should define the logic clearly and write some tests .....

File: services/auth/signin.go (hunk 1 above)
Comment (zeripath) [reply services/auth/signin.go]: oh yeah!

**Comment by zeripath** [comment]
> That's a lot of changes

Hide whitespace and you'll see the change it's not actually that much.

But yes we do need some tests here. I think the fundamental issue is that we need to be able to mock up the authenticators but I think we can do that reasonably now.

**Review by Gusted — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Comment by lunny** [comment]
Please send backport
