### PR TITLE
Ensure that rebase conflicts are handled in updates

### LINKED ISSUE #16922: 500 server error when trying to update a PR that contains conflicts with `rebase`
- Gitea version (or commit ref):1.16.0+dev-192-g268b2d0c9
- Git version:2.30.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
- Logs:
```
.../api/v1/repo/pull.go:1140:UpdatePullRequest() [E] pull_service.Update: Rebase Error: exit status 1: Whilst Rebasing: <commit hash>
        Rebasing (1/1)\01503derror: could not apply <commit hash>... change README.md
        Resolve all conflicts manually, mark them as resolved with
        "git add/rm <conflicted_files>", then run "git rebase --continue".
        You can instead skip this commit: run "git rebase --skip".
        To abort and get back to the state before "git rebase", run "git rebase --abort".
        Could not apply 5a5fa47... change README.md

        Auto-merging README.md
        CONFLICT (content): Merge conflict in README.md
Completed POST /api/v1/repos/qwerty287/tests/pulls/1/update?style=rebase 500 Internal Server Error in 258.618144ms
```

## Description
If I try to update a PR with conflicts via `rebase` (using the API), I get a 500 error. If I use the default merge option, I get a 409 Conflict error, which is better. It would be nice if it could return a 409 error if the PR contains conflicts.

### PR DESCRIPTION
**Pull request by zeripath**
PR #16125 did not update the error handlers to handle conflict errors relating
to rebases. This PR adds them.

Fix #16922

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: routers/api/v1/repo/pull.go [hunk 1]
```diff
@@ -1136,6 +1136,8 @@ func UpdatePullRequest(ctx *context.APIContext) {
 		if models.IsErrMergeConflicts(err) {
 			ctx.Error(http.StatusConflict, "Update", "merge failed because of conflict")
 			return
+		} else if models.IsErrRebaseConflicts(err) {
+			ctx.Error(http.StatusConflict, "Update", "rebase failed because of conflict")
```
Comment (lunny) [inline routers/api/v1/repo/pull.go:1140]: Missed return

Comment (zeripath) [reply routers/api/v1/repo/pull.go:1140]:
```suggestion
			ctx.Error(http.StatusConflict, "Update", "rebase failed because of conflict")
			return
```

**Review by a1012112796 — APPROVED** [review]

**Review by lafriks — APPROVED** [review]
