### PR TITLE
fix(api): handle missing base branch in PR commits API

### LINKED ISSUE #36366: PR commits API returns with internal server error if the base branch is missing
### Description

Wanted to fetch PR commits from `/repos/{owner}/{repo}/pulls/{index}/commits`, but if the base (target) branch missing, it returns with HTTP 500.

The corresponding log:
```
2026/01/14 14:48:17 routers/api/v1/repo/pull.go:1469:GetPullRequestCommits() [E] InternalServerError: exit status 128: Stderr: fatal: bad revision 'release-1.3.0...refs/pull/1/head'
2026/01/14 14:48:17 HTTPRequest [I] router: completed GET /api/v1/repos/TestGroup/test-repo/pulls/1/commits?page=1&limit=100&verification=false&files=false for 10.42.3.51:38594, 500 Internal Server Error in 73.3ms @ repo/pull.go:1395(repo.GetPullRequestCommits)
```

The UI shows the PR related commits as expected.

### Gitea Version

1.24.7

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Running inside Kubernetes as a very basic deployment.
Used image is `gitea/gitea:1.24.7-rootless`

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by Mohit25022005**
fix(api): handle missing base branch in PR commits API

Closes #36366

Previously, the PR commits API returned a 500 Internal Server Error
when the base branch was missing due to an unhandled git "bad revision" error.

This change:
- Checks for base branch existence before performing git operations
- Returns 404 when the base branch does not exist
- Prevents git errors from surfacing as 500 responses

This improves API robustness and aligns behavior with expected error handling.

Tested locally by:
- Creating a pull request
- Deleting the base branch
- Verifying that the API returns 404 instead of 500

### CODE REVIEW

File: routers/api/v1/repo/pull.go [hunk 1]
```diff
@@ -1427,12 +1427,26 @@ func GetPullRequestCommits(ctx *context.APIContext) {
...
 	} else {
+		branchExist, err := git_model.IsBranchExist(ctx, pr.BaseRepo.ID, pr.BaseBranch)
+		if err != nil {
+			ctx.APIErrorInternal(err)
+			return
+		}
+		if !branchExist {
+			ctx.APIError(http.StatusNotFound, fmt.Errorf("base branch '%s' does not exist", pr.BaseBranch))
+			return
+		}
```
Comment (wxiaoguang) [inline routers/api/v1/repo/pull.go]: I don't think you need this extra check.

The returned error of `GetCompareInfo` should be enough.

Comment (Mohit25022005) [reply routers/api/v1/repo/pull.go]: Thanks for the feedback

You're right, the additional branch existence check is unnecessary since GetCompareInfo already handles this case.

I have removed the extra check and now rely on handling the "bad revision" error to return a proper 404 response.

**Comment by Mohit25022005** [comment]
Thanks! This looks cleaner and aligns better with existing patterns. Appreciate the fix.

**Review by wxiaoguang — APPROVED** [review]

**Review by bircni — APPROVED** [review]

**Comment by bircni** [comment]
@wxiaoguang can you merge?
I'd like to merge all possible backports so we can finally release
