### PR TITLE
Stop logging CheckPath returns error: context canceled

### LINKED ISSUE #20709: CheckPath returns error: context canceled
### Description

I see often (just one day)

```
$ grep "CheckPath returns error: context canceled" log/gitea.log | wc -l
126389
```
this in my gitea.log

```
2022/08/07 08:07:59 ...it/repo_attribute.go:195:func1() [E] [62ef5536-21] CheckPath returns error: context canceled
        /source/modules/git/repo_attribute.go:195 (0xc7da47)
        /source/modules/git/repo_attribute.go:201 (0xc7d67d)
        /source/modules/git/repo_language_stats_nogogit.go:89 (0xc94e6c)
        /source/modules/indexer/stats/db.go:64 (0x1b3e6a4)
        /source/modules/indexer/stats/queue.go:23 (0x1b3f34e)
        /source/modules/queue/unique_queue_disk_channel.go:60 (0x16c36a1)
        /source/modules/queue/unique_queue_channel.go:79 (0x16c0b4a)
        /source/modules/queue/workerpool.go:564 (0x16caeee)
        /source/modules/queue/workerpool.go:312 (0x16c96e4)
        /usr/local/go/src/runtime/asm_amd64.s:1571 (0x4700e0)
```

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.4

### How are you running Gitea?

Downloaded gitea-1.17.0-linux-amd64

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by zeripath**
We should only log CheckPath errors if they are not simply due to context cancellation - and we should add a little more context to the error message.

Fix #20709

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: modules/git/repo_attribute.go [hunk 1]
```diff
@@ -191,8 +191,8 @@ func (c *CheckAttributeReader) Run() error {
 // CheckPath check attr for given path
 func (c *CheckAttributeReader) CheckPath(path string) (rs map[string]string, err error) {
 	defer func() {
-		if err != nil {
-			log.Error("CheckPath returns error: %v", err)
+		if err != nil && err != c.ctx.Err() {
+			log.Error("Unexpected error when checking path %s in %s returns error: %v", path, c.Repo.Path, err)
```
Comment (delvh) [inline modules/git/repo_attribute.go]:
```suggestion
			log.Error("Unexpected error when checking path %s in %s. Error: %v", path, c.Repo.Path, err)
```

File: services/gitdiff/gitdiff.go [hunk 2]
```diff
@@ -1178,8 +1178,6 @@ func GetDiff(gitRepo *git.Repository, opts *DiffOptions, files ...string) (*Diff
 				} else if language, has := attrs["gitlab-language"]; has && language != "unspecified" && language != "" {
 					diffFile.Language = language
 				}
-			} else {
-				log.Error("Unexpected error: %v", err)
```
Comment (delvh) [inline services/gitdiff/gitdiff.go:1182]: > We should only log CheckPath errors if they are not simply due to context cancellation

Are you and I interpreting this sentence differently?
Why did you completely remove this branch then?

Comment (zeripath) [reply services/gitdiff/gitdiff.go:1182]: The error will already be logged by the defer logger

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
Does it conflict with https://github.com/go-gitea/gitea/pull/20823?

**Comment by zeripath** [comment]
@silverwind I guess it is orthogonal to #20823

**Comment by zeripath** [comment]
Peeps this PR would remove a lot of confusing log messages. It would be good to get it merged

**Review by Gusted — APPROVED** [review]
