### PR TITLE
Ignore trivial errors when updating push data

### LINKED ISSUE #23213: Push update failed when git tag reference to a blob
### Description

When I push [git source code repository](https://github.com/git/git) to gitea, I found gitea server log turn out error:

```
[E] pushUpdate failed: gitRepo.GetCommit(3a1c74404d544d20c0d1f0b9c072b471a20b04c0) in cool/git2[4]: object does not exist [id: 7214aea37915ee2c4f6369eb9dea520aec7d855b, rel_path: ]
```

So I check and find out that this object is a special tag which reference to a blob:

```
git cat-file -p 3a1c74404d544d20c0d1f0b9c072b471a20b04c0
object 7214aea37915ee2c4f6369eb9dea520aec7d855b
type blob
tag junio-gpg-pub
tagger Junio C Hamano <gitster@pobox.com> 1416525135 -0800

GPG key to sign git.git archive

This blob contains the GPG public key I use to sign git.git archive.

To use it to verify tags I signed, do:

  $ git-cat-file blob junio-gpg-pub | gpg --import

to import it into your keyring, and then

  $ git-tag -v $tag_to_be_verified

The fingerprint information for the key is as follows:

$ gpg --fingerprint -k 96AFE6CB\!
pub   4096R/713660A7 2011-10-01
      Key fingerprint = 96E0 7AF2 5771 9559 80DA  D100 20D0 4E5A
      7136 60A7
uid                  Junio C Hamano <gitster@pobox.com>
uid                  Junio C Hamano <junio@pobox.com>
uid                  Junio C Hamano <jch@google.com>
sub   4096R/833262C4 2011-10-01
sub   4096R/96AFE6CB 2011-10-03 [expires: 2015-09-21]
sub   4096R/B3F7CAC9 2014-09-20 [expires: 2017-09-19]
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAABAgAGBQJUbnV7AAoJELC16IaWr+bLvjYP+wSOG8rp1y77ExHDJQj7HBLm
9PVQIb70tkiBxAGUpVNNbaoJQBuMAgFdT4Baj8CIo2jdzDeeqbjtcdy/XsHZ3IMl
7VRm9cI8Veh5nPc9U3z6XYTMmDhxxSsnCONQECYYFEJ5QGhnwkpOUTDYPRmnghWu
4JSDyWX0RLNXVPZkoP/zwVbv74Exx1Gz24p6fPlc4iETrKNHzzSM07CPKlAmXRHT
Ozh/NXfiE3OZSFDUNKkzHQJHtyFEPpVw/aUIyObvOcSYy6ZxQ+56U9h24D1mW8kY
w8BPdhzQ5d9nB/zpX83/cqsv6IXsK62ls8Qj51MfNM902D0pghVBInjR2xekWx+b
AO5VMaRiC+hgHvyzAM2nXuDfTUssd9ryYIx/plfw0gcKZ41S3HzHTiXYqRqd4O4I
lkFlWL11no7od+T9T2nap5wfdLliQpMxxZFLsqH67LzAvHxg/NjtIMXDxUfo++tV
qBR153FxcJX8AOcQo3zY7WotbmgS+8JPron3XvjXNOlz9HAxR2+orxhEC3pTVfeC
/aEZzs+ub9pV6ZQzVdfHzRZbtiN4Zw2ycW+EoXvlUCwNy72efaBRpKjQl4zJHKfD
LAwljdrenm8X6RjBKd/vPyTPSHx1AtSoXqseVw8Ly+qqoXnhsh2N0Xe2Ozx3D0lk
PtscHvD+diDMRLbLgK/k
=Sxgg
-----END PGP SIGNATURE-----

```

This made me realize that gitea may not consider the ref references to other blobs/trees at all. Since the error occurs in the post-receive-hook, this error may cause some notifications to be lost.

A simple workaround might be to skip this specially referenced webhook, this at least won't let us lose the webhook for common references.

But a more complete approach may be to modify the content of the notification, make it compatible with this special reference.

### Gitea Version

3e426bba78dbdd3e1369dd929de4ef7186f3d630

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

image

### Git Version

2.34.1

### Operating System

archlinux

### How are you running Gitea?

command-line

### Database

MySQL

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #23213

This block is only used for sending notifications, and it is executed after the git repo has been successfully pushed. So we could safely ignore the error.

By the way, remove another useless warning: `unknown whitespace behavior: %q, default to 'show-all'`. That parameter is provided by the end user, no need to warn that.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Diff with ignoring spaces: https://github.com/go-gitea/gitea/pull/33864/files?diff=unified&w=1

**Review by delvh — APPROVED** [review]

**Comment by wxiaoguang** [comment]
By the way, remove another useless warning: `unknown whitespace behavior: %q, default to 'show-all'`. That parameter is provided by the end user, no need to warn that.

File: services/repository/push.go [hunk 1]
```diff
@@ -133,23 +134,26 @@ func pushUpdates(optsList []*repo_module.PushUpdateOptions) error {
 			} else { // is new tag
 				newCommit, err := gitRepo.GetCommit(opts.NewCommitID)
 				if err != nil {
-					return fmt.Errorf("gitRepo.GetCommit(%s) in %s/%s[%d]: %w", opts.NewCommitID, repo.OwnerName, repo.Name, repo.ID, err)
+					// in case there is dirty data, for example, the "github.com/git/git" repository has tags points to non-existing commits
+					if !errors.Is(err, util.ErrNotExist) {
+						log.Error("Unable to get tag commit: gitRepo.GetCommit(%s) in %s/%s[%d]: %v", opts.NewCommitID, repo.OwnerName, repo.Name, repo.ID, err)
+					}
```
Comment (adlternative) [inline services/repository/push.go]: Firstly, in this context, git/git does not refer to a tag pointing to a non-existent commit, but rather to a blob. Additionally, why not log all error conditions here?

Comment (adlternative) [inline services/repository/push.go:140]: Firstly, in this context, git/git does not refer to a tag pointing to a non-existent commit, but rather to a blob. Additionally, why not log all error conditions here?

Comment (wxiaoguang) [reply services/repository/push.go]: 1. The "tag" could point to anything. It just happened to point to a blob, and in this case `GetCommit` considers it as the commit doesn't exist (it is right). I do not see a bad case for this approach.
2. Why log all errors?

Comment (adlternative) [reply services/repository/push.go]: 1. Alright, I think your explanation makes sense.
2. Do we not need to record errors: there is a tag pointing to a non-existent commit?

Comment (wxiaoguang) [reply services/repository/push.go]: > Do we not need to record errors: there is a tag pointing to a non-existent commit?

Suppose the error is recorded, then what it would help in real world? Would end user be able to see that error message, or site admin would really regularly check the error message, or site admin could take any action to that error message?

**Review by lunny — APPROVED** [review]

File: services/repository/push.go [hunk 2]
```diff
@@ -133,23 +134,26 @@ func pushUpdates(optsList []*repo_module.PushUpdateOptions) error {
 			} else { // is new tag
 				newCommit, err := gitRepo.GetCommit(opts.NewCommitID)
 				if err != nil {
-					return fmt.Errorf("gitRepo.GetCommit(%s) in %s/%s[%d]: %w", opts.NewCommitID, repo.OwnerName, repo.Name, repo.ID, err)
+					// in case there is dirty data, for example, the "github.com/git/git" repository has tags points to non-existing commits
```
Comment (wxiaoguang) [inline services/repository/push.go]:
```suggestion
					// in case there is dirty data, for example, the "github.com/git/git" repository has tags pointing to non-existing commits
```

File: services/repository/push.go (hunk 1 above)
Comment (adlternative) [reply services/repository/push.go]: I think this is generally intended for Gitea administrators. This kind of error message can inform the administrators that a push webhook may be missing here.
