### PR TITLE
Fix bug in getting merged pull request by commit

### LINKED ISSUE #32027: API shows unexpected PR for a commit
### Description

The API endpoint `GET /repos/{owner}/{repo}/commits/{sha}/pull` returns a pull request in more cases than I would expect:
I created the example repo https://demo.gitea.com/betanummeric/pr-test1 as an example:
```
* 2e0af5a76e4e02ff9ee4d52949d25fd229683754  (HEAD -> yetanother, origin/yetanother)
| * a8a7c696d7de8abd600798966caa4a47a6c420ca  (origin/other, other)
| * 827ed730869e32856e56da7be2a294dbf89a1b93  (origin/mergeme, mergeme)
|/  
* bd0050a443969356bf847bed330aa34a53be00cf  (origin/main, main)
```
I created a PR from branch `mergeme` to `main`: https://demo.gitea.com/betanummeric/pr-test1/pulls/1

The API returns that PR for every commit hash of the repo. I would have expected this to return the PR only for commit `827ed730869e32856e56da7be2a294dbf89a1b93`, because only that will be applied to the target branch in the PR.

I'm using this endpoint to determine if a push event relates to some PR. I work around by checking if the PR head matches the head of the push event.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

tested with gitea 1.22.1 and https://demo.gitea.com/ at 1.23.0+dev-464-g19af534462

### Database

None

### PR DESCRIPTION
**Pull request by Zettat123**
Fix #32027

---

This is actually a bug. But I'm worried that some users are already using this API to get unmerged PRs, and fixing it might be a breaking change.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
Maybe we can say it's just a documentation problem. The implementation hasn't been changed. So I marked it as backportable.

File: routers/api/v1/repo/commits.go [hunk 1]
```diff
@@ -325,11 +325,11 @@ func DownloadCommitDiffOrPatch(ctx *context.APIContext) {
 	}
 }
 
-// GetCommitPullRequest returns the pull request of the commit
+// GetCommitPullRequest returns the merged pull request of the commit
 func GetCommitPullRequest(ctx *context.APIContext) {
 	// swagger:operation GET /repos/{owner}/{repo}/commits/{sha}/pull repository repoGetCommitPullRequest
```
Comment (lunny) [inline routers/api/v1/repo/commits.go:330]:
```suggestion
	// swagger:operation GET /repos/{owner}/{repo}/commits/{ref}/pull repository repoGetCommitPullRequest
```

Comment (Zettat123) [reply routers/api/v1/repo/commits.go:330]: Fixed by 1b68fb944c46d5d2730040724940c379f2b5e378

**Review by wolfogre — APPROVED** [review]

File: routers/api/v1/repo/commits.go [hunk 2]
```diff
@@ -325,11 +325,11 @@ func DownloadCommitDiffOrPatch(ctx *context.APIContext) {
 	}
 }
 
-// GetCommitPullRequest returns the pull request of the commit
+// GetCommitPullRequest returns the merged pull request of the commit
 func GetCommitPullRequest(ctx *context.APIContext) {
```
Comment (wxiaoguang) [inline routers/api/v1/repo/commits.go:329]: It is at the wrong place, because other handlers all support branch/tag (ResolveRefOrSha), but this one doesn't

File: routers/api/v1/repo/commits.go [hunk 3]
```diff
@@ -354,7 +354,7 @@ func GetCommitPullRequest(ctx *context.APIContext) {
 	//   "404":
 	//     "$ref": "#/responses/notFound"
 
-	pr, err := issues_model.GetPullRequestByMergedCommit(ctx, ctx.Repo.Repository.ID, ctx.PathParam(":sha"))
+	pr, err := issues_model.GetPullRequestByMergedCommit(ctx, ctx.Repo.Repository.ID, ctx.PathParam("ref"))
```
Comment (wxiaoguang) [inline routers/api/v1/repo/commits.go]: `ref` is not a right name. `ref` means branch, tag or commit

But here, it only accepts commit id.

File: routers/api/v1/repo/commits.go (hunk 2 above)
Comment (lunny) [reply routers/api/v1/repo/commits.go:329]: Maybe that should be another PR.

Comment (Zettat123) [reply routers/api/v1/repo/commits.go:329]: I moved the handler to `/{sha}`, see fd35dc9e5cbf47eef0494661aef07a929ad4092f
