### PR TITLE
Fix missing unlock in uniquequeue

### LINKED ISSUE #9667: 1.11.rc1 - Stuck on checking merge conflicts
- Gitea version (or commit ref): 1.11.rc1
- Git version:
- Operating system: ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I didn't know where to post this one, but I did update my gitea to 1.11-rc1 and since then my PRs get stucked in "Checking for merge conflicts, try again in a few moments" after merging in the main branch. I did roll back to 1.10.2 and it seems to work well on that one.

### LINKED ISSUE #9759: View PR in UI always returns 500
- Gitea version (or commit ref):
- Git version: 1.11.0-rc1
- Operating system: Ubuntu 18.04.3
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
```
2020/01/14 05:32:33 routers/repo/pull.go:320:PrepareMergedViewPullInfo() [E] GetCompareInfo: exit status 128 - fatal: ambiguous argument 'a6bb53d9d3ae1d78dd55fdd202aec98c62836485...refs/pull/14/head': unknown revision or path not in the working tree.
        Use '--' to separate paths from revisions, like this:
        'git <command> [<revision>...] -- [<file>...]'
```

```
2020/01/14 05:35:18 routers/repo/pull.go:383:PrepareViewPullInfo() [E] GetRefCommitID(refs/pull/84/head): reference not found
```

## Description
After upgrading from 1.10.2 we can't open any pull-request. Gitea  returns always a 500. The first error appears when opening a merged pull-request. The second error appears when opening a open pull-request. I can't figure out how to reproduce this situation.

## Screenshot
image

### PR DESCRIPTION
**Pull request by zeripath**
Fixes a missing unlock in uniquequeue that will cause a deadlock.

Fix #9667
Likely Fixes #9759

### CODE REVIEW

File: modules/sync/unique_queue.go [hunk 1]
```diff
@@ -82,6 +82,7 @@ func (q *UniqueQueue) AddFunc(id interface{}, fn func()) {
 	idStr := com.ToStr(id)
 	q.table.lock.Lock()
 	if _, ok := q.table.pool[idStr]; ok {
+		q.table.lock.Unlock()
```
Comment (davidsvantesson) [inline modules/sync/unique_queue.go:85]: Can use defer instead?

Comment (zeripath) [reply modules/sync/unique_queue.go:85]: nope you want to unlock before you push to the channel.

**Review by davidsvantesson — APPROVED** [review]

File: modules/sync/unique_queue.go (hunk 1 above)
Comment (zeripath) [reply modules/sync/unique_queue.go:85]: the only issue is if you panic in fn() then you might not get unlocked...

Comment (zeripath) [reply modules/sync/unique_queue.go:85]: really not sure what you can do to protect against that.

Comment (zeripath) [reply modules/sync/unique_queue.go:85]: I suppose this would cope:

```go
func (q *UniqueQueue) AddFunc(id interface{}, fn func()) {
	idStr := com.ToStr(id)
	q.table.lock.Lock()
	locked := true
	defer func() {
		if locked {
			q.table.lock.Unlock()
		}
	}()
	if _, ok := q.table.pool[idStr]; ok {
		return
	}
	q.table.pool[idStr] = struct{}{}
	if fn != nil {
		fn()
	}
	locked = false
	q.table.lock.Unlock()
	select {
	case <-q.closed:
		return
	case q.queue <- idStr:
		return
	}
}
```

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
Please send back port to v1.11
