### PR TITLE
Shadow the password on cache and session config on admin panel

### LINKED ISSUE #7147: SessionProvider MySQL credentials are shown in the admin GUI as plaintext
- Gitea version (or commit ref): 1.8.1
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Greetings!
I'm using Gitea 1.8.1 with MySQL 5.7. And if I'm using MySQL for session storing purposes, I can see the credentials in GUI as plaintext. 

**Steps to reproduce**

1. Select MySQL like a sessions storage in the config file:
```
[session]
PROVIDER        = mysql
PROVIDER_CONFIG = someclient:somepassword@tcp(srv-mysql:3306)/someclient
```
2. Reload Gitea
3. Login in into Gitea with admin credentials
4. Follow this way: Site Administration ⇒ Configuration ⇒ Session Configuration ⇒ Provider Config

### PR DESCRIPTION
**Pull request by lunny**
will fix #7147

### CODE REVIEW

**Review by sapk — APPROVED** [review]

File: routers/admin/admin.go [hunk 1]
```diff
@@ -202,6 +202,17 @@ func SendTestMail(ctx *context.Context) {
 	ctx.Redirect(setting.AppSubURL + "/admin/config")
 }
 
+func shadowPassword(cfgItem string) string {
+	fields := strings.Split(cfgItem, ",")
```
Comment (mrsdizzie) [inline routers/admin/admin.go]: I think there need to be more than one check, since the config strings can be different for MySQL and redis. This seems to fix for redis, but not MySQL. In the example from  #7147, the session provider connection string is:
```
someclient:somepassword@tcp(srv-mysql:3306)/someclient
```
This format uses DSN, so the password is optional: https://github.com/go-sql-driver/mysql

Maybe it you can also pass in the adapter/provider to shadowPassword and then know if it is Redis/MySQL and check based on that.

**Review by mrsdizzie — CHANGES_REQUESTED** [review]

File: routers/admin/admin.go (hunk 1 above)
Comment (lunny) [reply routers/admin/admin.go]: OK. Will fix that.

**Comment by lunny** [comment]
@mrsdizzie done with test.

**Review by mrsdizzie — APPROVED** [review]
