### PR TITLE
Fix rendered wiki page link

### LINKED ISSUE #31395: Regression - 1.22 wiki links which contain dots point to "raw" media and only return plain text
### Description

**Steps to reproduce**

1. Create a wiki page with a hyphen `-` or a dot `.` in the name
2. Link to that page from another wiki page

**Result**

Clicking on the link will only return a plain text representation of the linked wiki page's content.

**Expected Result**

The whole wiki page html should be returned

**Additional info**

This was working in gitea 1.21.8.

The auto-generated URLs for the wiki pages with a hyphen end in `.-` and the ones for wiki pages with a `.` contain the dot.

I assume that [this change](https://github.com/go-gitea/gitea/pull/30273) caused the problem.

**Example project with wiki**

https://demo.gitea.com/reimer-atb/test/wiki/Home

**Example markdown with links that do not work**

```
Welcome to the Wiki.

- [Test](Test) => works
- [Test with spaces](Test-with-spaces) => works
- [Test-with-hyphen](Test-with-hyphen.-) => does **not** work
- [Test+with+spaces+2024-06-17.-](Test+with+spaces+2024-06-17.-) => does **not** work
- [2024-06-17](2024-06-17.-) => does **not** work
- [17-06-2024](17-06-2024.-) => does **not** work
- [17.06.2024](17.06.2024) => does **not** work
- [06/17/2024](06%2F17%2F2024) => works
- [17/06/2024](17%2F06%2F2024) => works
```

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Tested on demo.gitea.com and on a private gitea 1.22.0 instance (no idea how that is run because it is provided by someone else).

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #31395

### CODE REVIEW

File: modules/markup/markdown/markdown_test.go [hunk 1]
```diff
@@ -635,7 +635,7 @@ mail@domain.com
 <a href="https://example.com/file.bin" rel="nofollow">https://example.com/file.bin</a><br/>
 <a href="/file.bin" rel="nofollow">local link</a><br/>
 <a href="https://example.com" rel="nofollow">remote link</a><br/>
-<a href="/src/file.bin" rel="nofollow">local link</a><br/>
+<a href="/file.bin" rel="nofollow">local link</a><br/>
```
Comment (wxiaoguang) [inline modules/markup/markdown/markdown_test.go:638]: For reviewers: the old test is not right. It should be the same as line above (L636). And there are many similar cases, they are all fixed.

**Review by silverwind — APPROVED** [review]

**Review by lunny — APPROVED** [review]
