### PR TITLE
Fix: unstable sort skips/duplicates issues across pages

### LINKED ISSUE #13395: Missing/Duplicate issue when sorting by nearest due date
- Gitea version (or commit ref): 1.12.5
- Git version: 2.25.1
- Operating system: Ubuntu Server 20.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Haven't tried
- Log gist: N/A

## Description

When sorting by nearest due date, some issues are duplicated and some cannot be found when going through pages. In my case the first page contains issue 108 and 118, and the second page still contains them but in a different order mixed with other issues. The overall issue count remains the same, but since some are duplicated some can't be found. This can be reproduced both at the per user issues page and the repository issues page.

One thing to note is that they all have the same due date and are all past due by less than a day.

## Screenshots

Page 1:
image
Page 2:
image

### PR DESCRIPTION
**Pull request by DuckDuckWhale**
When viewing issues in sorted order, some issues are duplicated across pages and some are missing. This is caused by the lack of tie-breakers in database queries, making pagination inconsistent.

Fixes #13395.

### CODE REVIEW

File: models/issue.go [hunk 1]
```diff
@@ -1193,37 +1193,41 @@ type IssuesOptions struct {
...
 			OrderBy("CASE " +
 				"WHEN milestone.deadline_unix IS NULL THEN issue.deadline_unix " +
 				"WHEN milestone.deadline_unix < issue.deadline_unix OR issue.deadline_unix = 0 THEN milestone.deadline_unix " +
-				"ELSE issue.deadline_unix END DESC")
+				"ELSE issue.deadline_unix END DESC").
+			Desc("issue.id")
 	case "priorityrepo":
-		sess.OrderBy("CASE WHEN issue.repo_id = " + strconv.FormatInt(priorityRepoID, 10) + " THEN 1 ELSE 2 END, issue.created_unix DESC")
+		sess.OrderBy("CASE WHEN issue.repo_id = " + strconv.FormatInt(priorityRepoID, 10) +
+			" THEN 1 ELSE 2 END, issue.created_unix DESC").
```
Comment (wxiaoguang) [inline models/issue.go]:
```suggestion
		sess.OrderBy("CASE " + 
			"WHEN issue.repo_id = " + strconv.FormatInt(priorityRepoID, 10) + " THEN 1 " +
			"ELSE 2 END").
		Desc("issue.created_unix").
```

Could this style be more similar as other CASE-WHEN-ELSE?

Generally LGTM.

Comment (DuckDuckWhale) [reply models/issue.go]: Does the new style look good?

File: models/issue.go [hunk 2]
```diff
@@ -1193,37 +1193,43 @@ type IssuesOptions struct {
...
+		sess.Desc("issue.updated_unix").Desc("issue.id")
 	case "leastupdate":
-		sess.Asc("issue.updated_unix")
+		sess.Asc("issue.updated_unix").Asc("issue.id")
 	case "mostcomment":
-		sess.Desc("issue.num_comments")
+		sess.Desc("issue.num_comments").Desc("issue.id")
 	case "leastcomment":
-		sess.Asc("issue.num_comments")
+		sess.Asc("issue.num_comments").Desc("issue.id")
```
Comment (KN4CK3R) [inline models/issue.go]:
```suggestion
		sess.Asc("issue.num_comments").Asc("issue.id")
```

File: models/issue.go [hunk 3]
```diff
@@ -1193,37 +1193,43 @@ type IssuesOptions struct {
...
 	case "nearduedate":
 		// 253370764800 is 01/01/9999 @ 12:00am (UTC)
 		sess.Join("LEFT", "milestone", "issue.milestone_id = milestone.id").
 			OrderBy("CASE " +
 				"WHEN issue.deadline_unix = 0 AND (milestone.deadline_unix = 0 OR milestone.deadline_unix IS NULL) THEN 253370764800 " +
 				"WHEN milestone.deadline_unix = 0 OR milestone.deadline_unix IS NULL THEN issue.deadline_unix " +
 				"WHEN milestone.deadline_unix < issue.deadline_unix OR issue.deadline_unix = 0 THEN milestone.deadline_unix " +
-				"ELSE issue.deadline_unix END ASC")
+				"ELSE issue.deadline_unix END ASC").
+			Desc("issue.id")
```
Comment (KN4CK3R) [inline models/issue.go:1216]:
```suggestion
			Asc("issue.id")
```

File: models/issue.go [hunk 4]
```diff
@@ -1193,37 +1193,43 @@ type IssuesOptions struct {
...
 				"WHEN milestone.deadline_unix IS NULL THEN issue.deadline_unix " +
 				"WHEN milestone.deadline_unix < issue.deadline_unix OR issue.deadline_unix = 0 THEN milestone.deadline_unix " +
-				"ELSE issue.deadline_unix END DESC")
+				"ELSE issue.deadline_unix END DESC").
+			Desc("issue.id")
 	case "priorityrepo":
-		sess.OrderBy("CASE WHEN issue.repo_id = " + strconv.FormatInt(priorityRepoID, 10) + " THEN 1 ELSE 2 END, issue.created_unix DESC")
+		sess.OrderBy("CASE " +
+			"WHEN issue.repo_id = " + strconv.FormatInt(priorityRepoID, 10) + " THEN 1 " +
+			"ELSE 2 END").
```
Comment (KN4CK3R) [inline models/issue.go]:
```suggestion
			"ELSE 2 END DESC").
```

File: models/issue.go [hunk 5]
```diff
@@ -1193,37 +1193,43 @@ type IssuesOptions struct {
...
+			Desc("issue.created_unix").
+			Desc("issue.id")
 	case "project-column-sorting":
-		sess.Asc("project_issue.sorting")
+		sess.Asc("project_issue.sorting").Desc("issue.id")
```
Comment (KN4CK3R) [inline models/issue.go]:
```suggestion
		sess.Asc("project_issue.sorting").Asc("issue.id")
```

File: models/issue.go (hunk 2 above)
Comment (DuckDuckWhale) [reply models/issue.go]: The rationale here is that when sorting by the number of comments the order of creation do not matter, so in both cases fallback to default, i.e. descending order, i.e. newest first.

File: models/issue.go (hunk 3 above)
Comment (DuckDuckWhale) [reply models/issue.go:1216]: The rationale here is that when sorting by deadline the order of creation do not matter, so in both cases fallback to default, i.e. descending order, i.e. newest first.

File: models/issue.go (hunk 2 above)
Comment (KN4CK3R) [reply models/issue.go]: Shouldn't it be `sess.Asc("issue.num_comments").Desc("issue.created_unix").Desc("issue.id")` in that case?

File: models/issue.go (hunk 4 above)
Comment (DuckDuckWhale) [reply models/issue.go]: If I understand the original query correctly, shouldn't this default to ascend? I don't know how to test though because I don't know how to sort by `priorityrepo`.

File: models/issue.go (hunk 5 above)
Comment (DuckDuckWhale) [reply models/issue.go]: I'm not sure how project issue sorting works. What's the reasoning here?

File: models/issue.go (hunk 4 above)
Comment (KN4CK3R) [reply models/issue.go]: Sorry, I was wrong. The old value was `ASC` for that value.

File: models/issue.go (hunk 3 above)
Comment (KN4CK3R) [reply models/issue.go:1216]: See the other one, default would be `.Desc("issue.created_unix").Desc("issue.id")`

File: models/issue.go (hunk 4 above)
Comment (DuckDuckWhale) [reply models/issue.go]: Made explicit in newest commit.

File: models/issue.go (hunk 2 above)
Comment (DuckDuckWhale) [reply models/issue.go]: Make sense. Addressed in newest commit.

**Review by wxiaoguang — APPROVED** [review]

**Comment by DuckDuckWhale** [comment]
@lafriks can you also review this PR?

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Looks good from my side

**Review by wxiaoguang — APPROVED** [review]
Also LGTM. I think we can merge this, and if there is anything need to change, then we propose a new PR.
