### PR TITLE
Fixes #7023 - API Org Visibility

### LINKED ISSUE #7023: Set organisation visibility from API
- Gitea version (or commit ref): 799f5e0
- Git version: 2.20.1
- Operating system: gitea/gitea:1.8 (docker)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

It is currently not possible to set the visibilty of an organisation from API calls (especially /orgs). The visibility option is not documented in swagger; I tried sending a "visibility" field with "private", but it did not work.

```
curl -X POST "http://<gitea>/api/v1/orgs?access_token=<my_token>" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"username\": \"newOrg\",\"visibility\": \"private\"}"
```

### PR DESCRIPTION
**Pull request by richmahn**
Fixes #7023 

Makes sure we are handling visibility when creating and editing orgs as strings. Can be "public", "limited" or "private". Isn't required so if visibility isn't set (empty string) when creating it will be public and when editing it will remain the same.

Update: Did a little clean up of swagger comments and properties for repo Create and Update file endpoints as well since didn't know that comments could be put in the struct and seen by clicking "Model" on the swagger page until recently.

### CODE REVIEW

File: routers/api/v1/org/org.go [hunk 1]
```diff
@@ -75,6 +75,7 @@ func Create(ctx *context.APIContext, form api.CreateOrgOption) {
 	// parameters:
 	// - name: organization
 	//   in: body
+	//   description: "'visibility' can be \"public\", \"limited\" or \"private\""
```
Comment (zeripath) [inline routers/api/v1/org/org.go]: You should use enum to provide the valid values

File: modules/structs/org.go [hunk 2]
```diff
@@ -6,25 +6,25 @@ package structs
...
-	Location    string      `json:"location"`
-	Visibility  VisibleType `json:"visibility"`
+	ID          int64  `json:"id"`
+	UserName    string `json:"username"`
+	FullName    string `json:"full_name"`
+	AvatarURL   string `json:"avatar_url"`
+	Description string `json:"description"`
+	Website     string `json:"website"`
+	Location    string `json:"location"`
+	Visibility  string `json:"visibility"`
```
Comment (lunny) [inline modules/structs/org.go:16]: Is this a break change?

File: modules/structs/org_type.go [hunk 3]
```diff
@@ -40,6 +40,16 @@ func (vt VisibleType) IsPrivate() bool {
 	return vt == VisibleTypePrivate
 }
 
+// VisibilityMode provides the mode string of the visibility type (public, limited, private)
+func (vt VisibleType) VisibilityMode() string {
```
Comment (lunny) [inline modules/structs/org_type.go]: I think `Name` or `String` is a better name for the function.

**Review by lunny — CHANGES_REQUESTED** [review]

File: modules/structs/org.go (hunk 2 above)
Comment (techknowlogick) [reply modules/structs/org.go:16]: No, because Visibility field is not in stable release.

File: routers/api/v1/org/org.go (hunk 1 above)
Comment (zeripath) [reply routers/api/v1/org/org.go]: E.g. https://github.com/go-gitea/gitea/blob/c385dcc26b0da7fc1c245a1da316551cb6585ad3/routers/api/v1/repo/pull.go#L48

Comment (zeripath) [reply routers/api/v1/org/org.go]:
```suggestion
	//   enum: [public, limited, private]
	//   description: "'visibility' can be \"public\", \"limited\" or \"private\""
```

File: modules/structs/org_type.go (hunk 3 above)
Comment (richmahn) [reply modules/structs/org_type.go]: Actually first had it as String before. Will go back to using that.

File: routers/api/v1/org/org.go (hunk 1 above)
Comment (richmahn) [reply routers/api/v1/org/org.go]: Looks like you can only do this in a query, not the body.

File: routers/api/v1/convert/convert.go [hunk 4]
```diff
@@ -213,6 +213,7 @@ func ToOrganization(org *models.User) *api.Organization {
 		Description: org.Description,
 		Website:     org.Website,
 		Location:    org.Location,
+		Visibility:  org.Visibility.VisibilityString(),
```
Comment (lafriks) [inline routers/api/v1/convert/convert.go]:
```suggestion
		Visibility:  org.Visibility.String(),
```

File: modules/structs/org_type.go [hunk 5]
```diff
@@ -40,6 +40,16 @@ func (vt VisibleType) IsPrivate() bool {
 	return vt == VisibleTypePrivate
 }
 
+// VisibilityString provides the mode string of the visibility type (public, limited, private)
+func (vt VisibleType) VisibilityString() string {
```
Comment (lafriks) [inline modules/structs/org_type.go]: Why not just use `String` that would implemented `fmt.Stringer` interface?
```suggestion
func (vt VisibleType) String() string {
```

File: modules/structs/org_type.go [hunk 6]
```diff
@@ -40,6 +40,16 @@ func (vt VisibleType) IsPrivate() bool {
 	return vt == VisibleTypePrivate
 }
 
+// VisibilityString provides the mode string of the visibility type (public, limited, private)
```
Comment (lafriks) [inline modules/structs/org_type.go:43]:
```suggestion
// String provides the mode string of the visibility type (public, limited, private)
```

**Review by lafriks — CHANGES_REQUESTED** [review]

File: modules/structs/org_type.go (hunk 3 above)
Comment (richmahn) [reply modules/structs/org_type.go]: Done

File: modules/structs/org.go (hunk 2 above)
Comment (richmahn) [reply modules/structs/org.go:16]: Yeah, this was never actually used as it couldn't be set before this PR.

File: routers/api/v1/convert/convert.go (hunk 4 above)
Comment (richmahn) [reply routers/api/v1/convert/convert.go]: Ah, ok, just String. Got it.

File: modules/structs/org.go (hunk 2 above)
Comment (adelowo) [reply modules/structs/org.go:16]: I think this will be better if it keeps the type or was it changed because of the validation process?

File: routers/api/v1/org/org.go (hunk 1 above)
Comment (zeripath) [reply routers/api/v1/org/org.go]: Sorry I misread the swagger here - I didn't realise this was referring to a CreateOrgOption. The enum needs to be in struct.

Here's a patch: (I'd have opened a PR to your PR but I don't have access to it.)

```patch
diff --git a/modules/structs/org.go b/modules/structs/org.go
index aa76b9120..a99197ffc 100644
--- a/modules/structs/org.go
+++ b/modules/structs/org.go
@@ -24,7 +24,8 @@ type CreateOrgOption struct {
        Description string `json:"description"`
        Website     string `json:"website"`
        Location    string `json:"location"`
-       Visibility  string `json:"visibility" binding:"In(,visible,limited,private)"`
+       // enum: public,limited,private
+       Visibility string `json:"visibility" binding:"In(,visible,limited,private)"`
 }
 
 // EditOrgOption options for editing an organization
@@ -33,5 +34,6 @@ type EditOrgOption struct {
        Description string `json:"description"`
        Website     string `json:"website"`
        Location    string `json:"location"`
-       Visibility  string `json:"visibility" binding:"In(,visible,limited,private)"`
+       // enum: public,limited,private
+       Visibility string `json:"visibility" binding:"In(,visible,limited,private)"`
 }
diff --git a/templates/swagger/v1_json.tmpl b/templates/swagger/v1_json.tmpl
index 846ddec79..e7a7e6c3a 100644
--- a/templates/swagger/v1_json.tmpl
+++ b/templates/swagger/v1_json.tmpl
@@ -7144,6 +7144,11 @@
         },
         "visibility": {
           "type": "string",
+          "enum": [
+            "public",
+            "limited",
+            "private"
+          ],
           "x-go-name": "Visibility"
         },
         "website": {
@@ -7658,6 +7663,11 @@
         },
         "visibility": {
           "type": "string",
+          "enum": [
+            "public",
+            "limited",
+            "private"
+          ],
           "x-go-name": "Visibility"
         },
         "website": {
```

Or pull from https://github.com/zeripath/gitea/tree/fix-7023-api-org-visibility

Comment (richmahn) [reply routers/api/v1/org/org.go]: Ok. Merged in. Thanks!

File: templates/swagger/v1_json.tmpl [hunk 7]
```diff
@@ -550,6 +552,7 @@
             "required": true
           },
           {
+            "description": "'visibility' can be \"public\", \"limited\" or \"private\"",
```
Comment (zeripath) [inline templates/swagger/v1_json.tmpl]: Description should be set in the referenced schema
```suggestion
```

File: templates/swagger/v1_json.tmpl [hunk 8]
```diff
@@ -459,6 +460,7 @@
         "operationId": "orgCreate",
         "parameters": [
           {
+            "description": "'visibility' can be \"public\", \"limited\" or \"private\"",
```
Comment (zeripath) [inline templates/swagger/v1_json.tmpl]: As below, the description should describe the body in total and should be in the referenced schema

```suggestion
```

**Review by zeripath — APPROVED** [review]
Last two nits from me. The description field should describe the body in total but in any case I think it has to be in the referenced schema when there is a reference like that. (I could be wrong - if you want to keep a description just check what other bits do.)

File: modules/structs/org.go (hunk 2 above)
Comment (lunny) [reply modules/structs/org.go:16]: But `go-sdk` will reference this package.

**Review by lunny — CHANGES_REQUESTED** [review]

File: modules/structs/org.go (hunk 2 above)
Comment (zeripath) [reply modules/structs/org.go:16]: Yes but it will never have used this and won't have an endpoint for it.

File: templates/swagger/v1_json.tmpl (hunk 7 above)
Comment (richmahn) [reply templates/swagger/v1_json.tmpl]: Yeah, I model this off of other body descriptions as I never could figure out how to do it in the struct the body points to. Of course I modeled it after my own work on other end points, like https://try.gitea.io/api/swagger#/repository/repoCreateFile. It is meant to be able to describe other fields as needed, but I put the one in that I was adding to make it clear. If I click "Model" in that example, it doesn't explain anything.

Comment (richmahn) [reply templates/swagger/v1_json.tmpl]: Actually now see that my comments in my other PR for Repo edit that comments in the scheme show up in swagger! (I didn't know about clicking on "Model" before). I should have done that this way for the link I also gave above. Going to fix that for both structs.

Comment (richmahn) [reply templates/swagger/v1_json.tmpl]: Ok, all the swagger comments I have been incorrectly making are now moved their structs as seems best to do in the latest commit. Had to put an extra Note: in the struct header comment of CreateFileOption and UpdateFileOption about author and committer as it doesn't seem to get the comments for those fields since it points to another struct.

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]
