### PR TITLE
Revert the minimal golang version requirement from 1.17 to 1.16 and add a warning in Makefile

### LINKED ISSUE #19187: Recent Gitea 1.16 (stable) breaks build on Fedora 35 because the go.mod was changed to require Go1.17
### Description

I can no longer build the stable branch 1.16 on my Fedora 35 system.

go mod tidy fails, see below.

```
+ make 'TAGS=bindata sqlite sqlite_unlock_notify pam' 'LDFLAGS=-X "code.gitea.io/gitea/modules/setting.AppWorkPath=/var/lib/gitea" -X "code.gitea.io/gitea/modules/setting.CustomPath=/var/lib/gitea/custom" -X "code.gitea.io/gitea/modules/setting.PIDFile=/run/gitea/gitea.pid" -X "code.gitea.io/gitea/modules/setting.CustomConf=/etc/gitea/app.ini"' vendor build
go mod tidy && go mod vendor
go mod tidy: go.mod file indicates go 1.17, but maximum supported version is 1.16
make: *** [Makefile:374: vendor] Error 1
```

IMHO The stable branch should not break existing working setups.

### Gitea Version

1.16

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

f9ea4ab69ae397be4791c2e2ebf59f6cd9e5a6f8

### Operating System

Fedora 35 x64

### How are you running Gitea?

not relevant

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by lunny**
Fix #19187

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

File: Makefile [hunk 1]
```diff
@@ -203,10 +203,13 @@ help:
...
 	$(eval MIN_GO_VERSION := $(shell printf "%03d%03d%03d" $(shell echo '$(MIN_GO_VERSION_STR)' | tr '.' ' ')))
-	$(eval GO_VERSION := $(shell printf "%03d%03d%03d" $(shell $(GO) version | grep -Eo '[0-9]+\.[0-9.]+' | tr '.' ' ');))
+	$(eval GO_VERSION_STR := $(shell $(GO) version | grep -Eo '[0-9]+\.[0-9.]+'))
+	$(eval GO_VERSION := $(shell printf "%03d%03d%03d" $(shell echo '$(GO_VERSION_STR)' | tr '.' ' ')))
 	@if [ "$(GO_VERSION)" -lt "$(MIN_GO_VERSION)" ]; then \
-		echo "Gitea requires Go $(MIN_GO_VERSION_STR) or greater to build. You can get it at https://go.dev/dl/"; \
+		echo "Gitea requires Go $(MIN_GO_VERSION_STR) or greater to build, but get $(GO_VERSION). You can get it at https://go.dev/dl/"; \
 		exit 1; \
+	else \
+		echo "WARNNING: Please ensure Go $(GO_VERSION_STR) is still maintaining to avoid possible security problems. You can check it at https://go.dev/dl/"; \
```
Comment (jolheiser) [inline Makefile]:
```suggestion
		echo "WARNING: Please ensure Go $(GO_VERSION_STR) is still maintained to avoid possible security problems. You can check it at https://go.dev/dl/"; \
```

File: Makefile [hunk 2]
```diff
@@ -203,10 +203,13 @@ help:
 go-check:
 	$(eval MIN_GO_VERSION_STR := $(shell grep -Eo '^go\s+[0-9]+\.[0-9.]+' go.mod | cut -d' ' -f2))
 	$(eval MIN_GO_VERSION := $(shell printf "%03d%03d%03d" $(shell echo '$(MIN_GO_VERSION_STR)' | tr '.' ' ')))
-	$(eval GO_VERSION := $(shell printf "%03d%03d%03d" $(shell $(GO) version | grep -Eo '[0-9]+\.[0-9.]+' | tr '.' ' ');))
+	$(eval GO_VERSION_STR := $(shell $(GO) version | grep -Eo '[0-9]+\.[0-9.]+'))
+	$(eval GO_VERSION := $(shell printf "%03d%03d%03d" $(shell echo '$(GO_VERSION_STR)' | tr '.' ' ')))
 	@if [ "$(GO_VERSION)" -lt "$(MIN_GO_VERSION)" ]; then \
-		echo "Gitea requires Go $(MIN_GO_VERSION_STR) or greater to build. You can get it at https://go.dev/dl/"; \
+		echo "Gitea requires Go $(MIN_GO_VERSION_STR) or greater to build, but get $(GO_VERSION). You can get it at https://go.dev/dl/"; \
```
Comment (jolheiser) [inline Makefile]:
```suggestion
		echo "Gitea requires Go $(MIN_GO_VERSION_STR) or greater to build, but $(GO_VERSION) was found. You can get an updated version at https://go.dev/dl/"; \
```

**Review by jolheiser — APPROVED** [review]
LGTM after phrasing nits.

File: Makefile [hunk 3]
```diff
@@ -203,10 +203,13 @@ help:
...
 	$(eval MIN_GO_VERSION := $(shell printf "%03d%03d%03d" $(shell echo '$(MIN_GO_VERSION_STR)' | tr '.' ' ')))
-	$(eval GO_VERSION := $(shell printf "%03d%03d%03d" $(shell $(GO) version | grep -Eo '[0-9]+\.[0-9.]+' | tr '.' ' ');))
+	$(eval GO_VERSION_STR := $(shell $(GO) version | grep -Eo '[0-9]+\.[0-9.]+'))
+	$(eval GO_VERSION := $(shell printf "%03d%03d%03d" $(shell echo '$(GO_VERSION_STR)' | tr '.' ' ')))
 	@if [ "$(GO_VERSION)" -lt "$(MIN_GO_VERSION)" ]; then \
-		echo "Gitea requires Go $(MIN_GO_VERSION_STR) or greater to build. You can get it at https://go.dev/dl/"; \
+		echo "Gitea requires Go $(MIN_GO_VERSION_STR) or greater to build, but $(GO_VERSION) was found. You can get an updated version at https://go.dev/dl/"; \
 		exit 1; \
+	else \
+		echo "WARNING: Please ensure Go $(GO_VERSION_STR) is still maintained to avoid possible security problems. You can check it at https://go.dev/dl/"; \
```
Comment (wxiaoguang) [inline Makefile:212]: Isn't it very strange for a user who uses Go1.18 see this WARNING?

Comment (lunny) [reply Makefile:212]: Currently yes, but when Golang go to 1.2x, it will not.

**Comment by techknowlogick** [comment]
This actually won't build in 1.16 as this PR is now, due this file https://github.com/go-gitea/gitea/commit/f9ea4ab69ae397be4791c2e2ebf59f6cd9e5a6f8#diff-93c289a98a6bd37986878061f982fad85e37b47dff818559e021216f9319a2a8 I will push changes to this branch to resolve before merging.

**Review by techknowlogick — DISMISSED** [review]
temporarily blocking

File: modules/util/net.go [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+// Use of this source code is governed by a MIT-style
+// license that can be found in the LICENSE file.
+
+package util
+
+import (
+	"net"
+)
+
+// IsIPPrivate for net.IP.IsPrivate. TODO: replace with `ip.IsPrivate()` if min go version is bumped to 1.17
```
Comment (Gusted) [inline modules/util/net.go]: 1.16.x branch won't be bumped to go version 1.17

```suggestion
// IsIPPrivate for net.IP.IsPrivate.
```

File: Makefile (hunk 3 above)
Comment (Gusted) [reply Makefile:212]: I think if we leave this, we can expect other issues with why this warning is appearing for users that are using the latest go version. We don't want to let them think that they are using a outdated go version when they are not.

Comment (lunny) [reply Makefile:212]: But we will never know it except we check Golang's website in the Makefile.

**Review by 6543 — COMMENTED** [review]
lgtm
