### PR TITLE
Add rebase push display wrong comments bug

### LINKED ISSUE #35518: Pull Request Timeline is Wrong When Force Pushing
### Description

When having an open PR with commits already added and showing up in the "timeline", I'd expect a force push to be shown correctly in the timeline with some link to the diff of the force push.

To reproduce: 

- added two commits to a branch
- opened a PR
- drop the last commit
- do a force push
- check the timeline on the PR

This was working in earlier versions of gitea.

Reproduced on Gitea Demo Site [1]

[1] https://demo.gitea.com/smartEBL/test/pulls/1

### Gitea Version

1.24.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

What I get:
Image

What I got earlier / what I would expect:
Image

### Git Version

2.49.1

### Operating System

Ubuntu 22.04

### How are you running Gitea?

Gitea runs in a docker container using the official gitea docker image.

### Database

SQLite

### PR DESCRIPTION
**Pull request by lunny**
Fix #35518

### CODE REVIEW

**Comment by silverwind** [comment]
Will this erase commits that were force-pushed over from the history? This is a very old bug that I noticed once, and I would appreciate if these commits were erased from history, just like on GitHub.

**Comment by lunny** [comment]
> Will this erase commits that were force-pushed over from the history? This is a very old bug that I noticed once, and I would appreciate if these commits were erased from history, just like on GitHub.

This will fix a bug caused by my previous PR which forgot set IsForceBranch as true. That means this will restore the features before my previous PR and the old push comments will not be deleted.

Are you sure Github will delete the old push comments?
P.S. Changing target branch will delete all the old push comments.

**Comment by silverwind** [comment]
Yes they do. Say for example I push up commits 1,2,3 to a PR and I `git rebase -i origin/master` and squash commits 2 and 3 and force-push that, they will be erased from the commit history on GitHub, but not in Gitea. [Example PR](https://github.com/silverwind/symlink-test/pull/19).

Before:

Screenshot 2025-10-02 at 06 37 09

After:

Screenshot 2025-10-02 at 06 37 41

**Review by silverwind — APPROVED** [review]

File: routers/web/repo/pull.go [hunk 1]
```diff
@@ -1583,7 +1583,10 @@ func UpdatePullRequestTarget(ctx *context.Context) {
 	}
 
 	if err := pull_service.ChangeTargetBranch(ctx, pr, ctx.Doer, targetBranch); err != nil {
-		if issues_model.IsErrPullRequestAlreadyExists(err) {
+		switch {
+		case git_model.IsErrBranchNotExist(err):
+			ctx.HTTPError(http.StatusBadRequest)
```
Comment (wxiaoguang) [inline routers/web/repo/pull.go]: Why other `case` blocks use "ctx.JSON", but here you use "ctx.HTTPError"?

File: tests/integration/pull_comment_test.go [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+		doGitCreateBranch(dstPath, "dev")(t)
+		content, err := os.ReadFile(dstPath + "/README.md")
+		assert.NoError(t, err)
+		assert.Equal(t, "Hello, World (Edited Conflicted)\n", string(content))
+
+		err = os.WriteFile(dstPath+"/README.md", []byte("Hello, World (Edited Conflict Resolved)\n"), 0o644)
+		assert.NoError(t, err)
+		_, _, err = gitcmd.NewCommand().AddArguments("add", "--all").RunStdString(t.Context(), &gitcmd.RunOpts{Dir: dstPath})
+		assert.NoError(t, err)
+		doGitCommit(dstPath, "Resolve conflict")(t)
```
Comment (wxiaoguang) [inline tests/integration/pull_comment_test.go]: There is already `doGitAddSomeCommits`?

File: tests/integration/pull_comment_test.go [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+		u.Path = "/user1/repo1.git"
+		u.User = url.UserPassword("user1", userPassword)
+		doGitAddRemote(dstPath, "fork", u)(t)
+		// non force push will fail
+		_, _, err = gitcmd.NewCommand().AddArguments("push", "fork", "dev:master").RunStdString(t.Context(), &gitcmd.RunOpts{Dir: dstPath})
+		assert.Error(t, err)
+		_, _, err = gitcmd.NewCommand().AddArguments("push", "--force", "fork", "dev:master").RunStdString(t.Context(), &gitcmd.RunOpts{Dir: dstPath})
+		assert.NoError(t, err)
+
+		time.Sleep(time.Second) // wait for pull request conflict checking
```
Comment (wxiaoguang) [inline tests/integration/pull_comment_test.go]: `require.Eventually`

File: tests/integration/pull_comment_test.go [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+		assert.Equal(t, "user1/repo1", prIssue.PullRequest.HeadRepo.FullName())
+
+		// do retarget
+		req := NewRequestWithValues(t, "POST", fmt.Sprintf("/user2/repo1/pull/%d/target_branch", prIssue.PullRequest.Index), map[string]string{
+			"_csrf":         GetUserCSRFToken(t, session2),
+			"target_branch": "dev",
+		})
+		session2.MakeRequest(t, req, http.StatusOK)
+
+		time.Sleep(time.Second) // wait for pull request conflict checking
```
Comment (wxiaoguang) [inline tests/integration/pull_comment_test.go]: `require.Eventually`

File: tests/integration/pull_comment_test.go (hunk 2 above)
Comment (lunny) [reply tests/integration/pull_comment_test.go]: That function can not be used here because we need to make a conflict line.

Comment (wxiaoguang) [reply tests/integration/pull_comment_test.go]: I do not see why it should duplicate the code by copy&paste

https://github.com/go-gitea/gitea/pull/35560/commits/2bea40d41517d2dd84fc0cd61a57349d162d7a40

File: routers/web/repo/pull.go (hunk 1 above)
Comment (lunny) [reply routers/web/repo/pull.go]: 9b148f2589

**Review by hiifong — APPROVED** [review]

**Comment by badhezi** [comment]
@lunny 
I think the `TestPullComment` test might be flaky, I had it fail and pass on the same code (without changes related to it)
Failed: https://github.com/go-gitea/gitea/actions/runs/18338982161/job/52229590592
Passed: https://github.com/go-gitea/gitea/actions/runs/18343618920/job/52244747162

Appears to be from nil pointer on:
`testPullCommentRebase` > `LoadCommentPushCommits` > `RepositoryFromContextOrOpen`
https://github.com/go-gitea/gitea/blob/03fce8f3d0cf3c180f06470257dc09a6c09ec5b0/services/issue/comments.go#L174

**Comment by lunny** [comment]
> @lunny I think the `TestPullComment` test might be flaky, I had it fail and pass on the same code (without changes related to it) Failed: https://github.com/go-gitea/gitea/actions/runs/18338982161/job/52229590592 Passed: https://github.com/go-gitea/gitea/actions/runs/18343618920/job/52244747162
> 
> Appears to be from nil pointer on: `testPullCommentRebase` > `LoadCommentPushCommits` > `RepositoryFromContextOrOpen`
> 
> https://github.com/go-gitea/gitea/blob/03fce8f3d0cf3c180f06470257dc09a6c09ec5b0/services/issue/comments.go#L174

I have sent #35647 to try to fix it.
