### PR TITLE
Prevent NPE on partial match of compare URL and allow short SHA1 compare URLs

### LINKED ISSUE #18471: Gitea 1.16.0 crash when click on repo link
### Gitea Version

1.16.0

### Git Version

2.30.2

### Operating System

docker in ubuntu focal

### How are you running Gitea?

I run gitea and drone with docker-compose.
image: gitea/gitea:latest

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/hypernics/12552cd6b64454fd9d5bedbe61571b91

### Description

After upgrading to 1.16.0 with docker-compose, when I click on a repo link some of them crash the gitea server.
It worked with 1.15.x
I just clicked all of my project repo links and as I see all my Laravel project crash the server, python and javascript projects are working.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Gusted**
- Prevent NPE panic when the full compare url regex isn't matched
- Allow the usage of a shorter sha1 being used.

Fix #18471

### CODE REVIEW

File: modules/markup/html.go [hunk 1]
```diff
@@ -946,6 +946,13 @@ func comparePatternProcessor(ctx *RenderContext, node *html.Node) {
 			return
 		}
 
+		// Check m[0...7] to not be be -1
```
Comment (zeripath) [inline modules/markup/html.go]:
```suggestion
		// Ensure that every group (m[0]...m[7]) has a match
```

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
Regression #17924

**Comment by zeripath** [comment]
Oh actually @Gusted it would be good to add a test case for something where there would only be a partial match

**Review by techknowlogick — APPROVED** [review]
