### PR TITLE
Fix invalid repo urls after change username

### LINKED ISSUE #10141: Invalid repo urls after change username
- Gitea version (or commit ref): 1.12.0+dev-239-g391e0638c
- Git version: 2.25.0
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/testNewUsername)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
After change username, user repo urls wouldn't updated.

## Screenshots
issue1

### PR DESCRIPTION
**Pull request by shadowspore**
Fix #10141

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by sapk — APPROVED** [review]

**Comment by sapk** [comment]
No need to backport to 1.11 since it was introduced in #9717

**Comment by zeripath** [comment]
Hmm... So this functionality should really be folded in to https://github.com/go-gitea/gitea/blob/77431599f6708b87019a7e929d02fe8d1b95a8e7/models/user.go#L1073. There's a race here that could break things.

**Comment by lunny** [comment]
But if rename folder succeed but database changed failed? That will break the repository.

**Comment by mavenbline** [comment]
> But if rename folder succeed but database changed failed? That will break the repository.
If database request failed, we can rename folder back.
But what if folder name rollback failed? :o
Will this be cause for panic?

**Comment by lunny** [comment]
The orgnization update needs a rewritten.

File: models/user.go [hunk 1]
```diff
@@ -1050,7 +1050,17 @@ func ChangeUserName(u *User, newUserName string) (err error) {
 		return fmt.Errorf("Rename user directory: %v", err)
 	}
 
-	return nil
+	sess := x.NewSession()
```
Comment (lafriks) [inline models/user.go:1048]: It would be better to move L1053-L1061 before directory rename to minimize possiblity of having one thing done and other failing

**Review by lafriks — CHANGES_REQUESTED** [review]

**Review by lafriks — APPROVED** [review]
