### PR TITLE
Fix failure on creating pull request with assignees (#4419)

### LINKED ISSUE #4419: Error 500 creating PR with assignees
- Gitea version (or commit ref): bbf9abde4937285c77154129ae9934b22b4ea7a6
- Git version: 2.7.4
- Operating system:  Ubuntu 16.04.4 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When I try to create pull request with one or more assignees I get 500 error. Error doesn't show up if nobody is assigned. I'm able to add assignees only for already existing pull requests. 

Log error:

```
2018/07/10 15:41:42 [...routers/repo/pull.go:836 CompareAndPullRequestPost()] [E] NewPullRequest: newIssue: loadPullRequest: pull request does not exist [id: 0, issue_id: 24, head_repo_id: 0, base_repo_id: 0, head_branch: , base_branch: ]
```

### PR DESCRIPTION
**Pull request by SagePtr**
Fixes #4419

If pull request is in the middle of creation, it's impossible to call 'pull_request' webhook with action 'assign' in changeAssignee function. Now it's just skipped.

I don't know if this extra webhooks should be called after pull request is created, because 'pull_request' webhook with action 'opened' is called anyway and it already contains assignees section. For now additional assign webhooks are just skipped.

### CODE REVIEW

**Comment by webjoel** [comment]
Waiting...

File: models/issue_assignees.go [hunk 1]
```diff
@@ -162,6 +162,10 @@ func (issue *Issue) changeAssignee(sess *xorm.Session, doer *User, assigneeID in
 	mode, _ := accessLevel(sess, doer.ID, issue.Repo)
 	if issue.IsPull {
 		if err = issue.loadPullRequest(sess); err != nil {
+			// If pull request is not yet created - don't fail here, skip webhooks
+			if IsErrPullRequestNotExist(err) {
```
Comment (lunny) [inline models/issue_assignees.go]: If it's creation not modification and `if IsErrPullRequestNotExist(err)` then return nil, other will return err

**Review by lunny — CHANGES_REQUESTED** [review]

File: models/issue_assignees.go (hunk 1 above)
Comment (SagePtr) [reply models/issue_assignees.go]: Added fourth argument to function which determines whenever assignee is added in the middle of creation or not. Also this made ```if IsErrPullRequestNotExist(err)``` check not necessary - no reason to even try to load pull request if it's in creation.

**Review by lunny — APPROVED** [review]

**Review by Bwko — APPROVED** [review]
