### PR TITLE
redirect .wiki/* ui link to /wiki

### LINKED ISSUE #18590: [Bug Report] Wiki as submodule
# Introduction

When adding the wiki of a repo to the repo itself as a submodule, you will get a 404 error in the web UI when clicking on the submodule. This occurs due to the fact that the wiki is no real repo.

# Example

Here are two example repositories. One on codeberg and one on try.gitea

- https://try.gitea.io/schorsch/test-wiki-submodule
- https://codeberg.org/moenavigator/moenavigatorengine (the `./doc` folder)

# Proposal

The wiki has the exact same name as the original repo but with the suffix `.wiki`. When accessing `https://gitea-instace.example/user/repo.wiki` just redirect to `https://gitea-instance.example/user/repo/wiki`

# Credits

The bug was discovered by the codeberg user [ncc1988](https://codeberg.org/ncc1988). They also suggested the workaround. For further information have a look at the issue on codeberg: https://codeberg.org/Codeberg/Community/issues/217

### PR DESCRIPTION
**Pull request by a1012112796**
fix #18590

### CODE REVIEW

**Review by Gusted — APPROVED** [review]

File: modules/context/repo.go [hunk 1]
```diff
@@ -440,6 +440,12 @@ func RepoAssignment(ctx *Context) (cancel context.CancelFunc) {
 	ctx.Repo.Owner = owner
 	ctx.Data["Username"] = ctx.Repo.Owner.Name
 
+	// redirect link to wiki
+	if strings.HasSuffix(repoName, ".wiki") {
+		ctx.Redirect(strings.Replace(ctx.Req.RequestURI, ".wiki", "/wiki", 1))
```
Comment (silverwind) [inline modules/context/repo.go]: This would break on `https://foo.wiki/user/repo.wiki?query=foo.wiki`. Would at least include the repo name in the replacement, or properly parse the URL apart and join it again after replacement on the path.

**Review by silverwind — APPROVED** [review]

File: modules/context/repo.go [hunk 2]
```diff
@@ -440,6 +440,25 @@ func RepoAssignment(ctx *Context) (cancel context.CancelFunc) {
...
+			if parts[i] == repoName {
+				parts[i] = strings.Replace(parts[i], ".wiki", "/wiki", 1)
+				break
+			}
+		}
+		
+		redirectLink := ""
+		for _, part := range parts {
+			redirectLink += part + "/"
+		}
```
Comment (wxiaoguang) [inline modules/context/repo.go]: https://pkg.go.dev/net/http#Request  `RequestURI is the unmodified request-target of the Request-Line`

Bugs:

case 1: `/path?foo=bar` => `/path?foo=bar/`
case 2: `/path/` => `/path//`

And the code above should not split RequestURI directly IMO.

**Review by wxiaoguang — CHANGES_REQUESTED** [review]

**Comment by zeripath** [comment]
@wxiaoguang @a1012112796  I've changed the redirect code to more closely match https://github.com/go-gitea/gitea/blob/3f280f89e7471a6dcdaefccc64a8d39188970e63/modules/context/context.go#L125-L143 

This now works on suburl mounted giteas too.

File: modules/context/repo.go [hunk 3]
```diff
@@ -441,6 +441,26 @@ func RepoAssignment(ctx *Context) (cancel context.CancelFunc) {
 	ctx.Repo.Owner = owner
 	ctx.Data["Username"] = ctx.Repo.Owner.Name
 
+	// redirect link to wiki
+	if strings.HasSuffix(repoName, ".wiki") {
+		// ctx.Req.URL.Path does not have the preceding appSubURL - any redirect must have this added
+		// Now we happen to know that all of our paths are: /:username/:reponame/whatever_else
+		originalRepoName := ctx.Params(":reponame")
+		redirectRepoName := strings.TrimSuffix(repoName, ".wiki")
+		redirectRepoName = redirectRepoName + originalRepoName[len(redirectRepoName)+5:]
```
Comment (zeripath) [inline modules/context/repo.go]:
```suggestion
		redirectRepoName += originalRepoName[len(redirectRepoName)+5:]
```

**Review by wxiaoguang — APPROVED** [review]
It seems correct.

I have a small question that could we just use `redirectPath := url.PathEscape(userName)+"/"+url.PathEscape(mainRepoName)+"/wiki" + what_ever`? Then we do not need the replace.

Maybe like this?

```go
	// redirect link to from "/org/repo.wiki" to "/org/repo/wiki"
	if strings.HasSuffix(repoName, ".wiki") {
		// ctx.Req.URL.Path does not have the preceding appSubURL - any redirect must have this added
		// Now we happen to know that all of our paths are: /:username/:reponame/whatever_else
		pathFields := strings.SplitN(ctx.Req.URL.EscapedPath(), "/", 4)
		redirectUri := "/" + pathFields[1] + "/" + strings.TrimSuffix(pathFields[2], ".wiki") + "/wiki"
		if len(pathFields) == 4 {
			redirectUri += "/" + pathFields[3]
		}
		if ctx.Req.URL.RawQuery != "" {
			redirectUri += "?" + ctx.Req.URL.RawQuery
		}
		ctx.Redirect(path.Join(setting.AppSubURL, redirectUri))
		return
	}
```

**Comment by zeripath** [comment]
So I initially considered that but decided that it would be better to keep the same code style as the RedirectToUser.

**Comment by wxiaoguang** [comment]
Either is fine to me, already approved. (while personally I would choose a straight way if it's better than the old method)

**Comment by zeripath** [comment]
make lgtm work

**Comment by wxiaoguang** [comment]
Maybe it's worthy to introduce a function `RedirectToOrgRepo(org, repo, extra, query)` to replace `RedirectToUser` and this code.
