### PR TITLE
Stop logging EOFs and exit(1)s in ssh handler

### LINKED ISSUE #20473: Continuous SSH "Session Failed To Exit" Spam In Log
### Description

Every minute I get the following in my logs. Is this an issue that needs to be looked into? I am using the internal Gitea SSH server.

```
2022/07/25 07:10:20 modules/ssh/ssh.go:145:sessionHandler() SSH: Wait: exit status 1
2022/07/25 07:10:20 modules/ssh/ssh.go:149:sessionHandler() Session failed to exit. EOF
2022/07/25 07:11:20 modules/ssh/ssh.go:145:sessionHandler() SSH: Wait: exit status 1
2022/07/25 07:11:20 modules/ssh/ssh.go:149:sessionHandler() Session failed to exit. EOF
2022/07/25 07:12:20 modules/ssh/ssh.go:145:sessionHandler() SSH: Wait: exit status 1
2022/07/25 07:12:20 modules/ssh/ssh.go:149:sessionHandler() Session failed to exit. EOF
2022/07/25 07:13:20 modules/ssh/ssh.go:145:sessionHandler() SSH: Wait: exit status 1
2022/07/25 07:13:20 modules/ssh/ssh.go:149:sessionHandler() Session failed to exit. EOF
2022/07/25 07:14:20 modules/ssh/ssh.go:145:sessionHandler() SSH: Wait: exit status 1
2022/07/25 07:14:20 modules/ssh/ssh.go:149:sessionHandler() Session failed to exit. EOF
```

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.37.1

### Operating System

Windows 10

### How are you running Gitea?

From the latest Windows x64 binary directly from the Gitea downloads.

### Database

_No response_

### PR DESCRIPTION
**Pull request by zeripath**
The code in modules/ssh/ssh.go:sessionHandler() currently cause an error to be
logged if `gitea serv` exits with a exit(1). This logging is useless because the
accompanying stderr is not provided and in any case the exit(1) is most likely due
to permissions errors.

Further it then causes the EOF to be logged - even though this is not helpful.

This PR simply checks the errors returned and stops logging them.

In the case of misconfigurations causing `gitea serv` to fail with exit(1)
the current logging is not helpful at determining this and users should simply
review the message passed over the ssh connection.

Fix #20473

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by a1012112796 — APPROVED** [review]

File: modules/ssh/ssh.go [hunk 1]
```diff
@@ -142,10 +143,12 @@ func sessionHandler(session ssh.Session) {
 	// Wait for the command to exit and log any errors we get
 	err = cmd.Wait()
 	if err != nil {
-		log.Error("SSH: Wait: %v", err)
+		if _, ok := err.(*exec.ExitError); !ok {
```
Comment (silverwind) [inline modules/ssh/ssh.go:148]: What does this `err.(*exec.ExitError)` do? Check if the command has non-zero exit code?

Comment (zeripath) [reply modules/ssh/ssh.go:148]: If `gitea serv` exits with a non-zero exit code - an `*exec.ExitError` will be returned by `cmd.Wait()`.

The contents of this error will be simply the exit code without any further context.

That is because the actual error that occurred will have been emitted on the stderr pipe and sent to the downstream user.

Now... 

There are many ways in which `gitea serv` could exit with a non-zero exit code as part of normal behaviour. Thus logging this error is pointless - especially as we can get no context for it.

However, `cmd.Wait()` can return with other errors, and we should log those. Therefore check the error and if it's not an `*exec.ExitError` log it - otherwise drop it.

Comment (silverwind) [reply modules/ssh/ssh.go:148]: Ok. Would `errors.Is(err, exec.ExitError)` work in this case, or is that an oddity of the `exec` API that one has to type assert like that?

Comment (zeripath) [reply modules/ssh/ssh.go:148]: No. It would not work. `errors.Is` does an equality comparison on the target *NOT* a type comparison. If the target error implements `interface{ Is(error) bool }` and that did the correct type comparison we could use it but `exec.ExitError` does not do this.

<details><summary> 

Definition of `errors.Is(err, target error) bool`

</summary>

```go
func Is(err, target error) bool {
	if target == nil {
		return err == target
	}

	isComparable := reflectlite.TypeOf(target).Comparable()
	for {
		if isComparable && err == target {
			return true
		}
		if x, ok := err.(interface{ Is(error) bool }); ok && x.Is(target) {
			return true
		}
		// TODO: consider supporting target.Is(err). This would allow
		// user-definable predicates, but also may allow for coping with sloppy
		// APIs, thereby making it easier to get away with them.
		if err = Unwrap(err); err == nil {
			return false
		}
	}
}
```

</details>


<details><summary> 

Defintion of `type ExitError struct { ... }` 

</summary>

```go
// An ExitError reports an unsuccessful exit by a command.
type ExitError struct {
	*os.ProcessState

	// Stderr holds a subset of the standard error output from the
	// Cmd.Output method if standard error was not otherwise being
	// collected.
	//
	// If the error output is long, Stderr may contain only a prefix
	// and suffix of the output, with the middle replaced with
	// text about the number of omitted bytes.
	//
	// Stderr is provided for debugging, for inclusion in error messages.
	// Users with other needs should redirect Cmd.Stderr as needed.
	Stderr []byte
}

func (e *ExitError) Error() string {
	return e.ProcessState.String()
}
```

and `*os.ProcessState` does not have an `Is(error) bool` function either.

</details>

Comment (zeripath) [reply modules/ssh/ssh.go:148]: It's a failure of the std library and the `errors.Is` function. All of these errors should be implementing `Is` and advertising in a clear and reasonable way what it means for an error to be `Is(...)` another error.

A present `errors.Is` is a massive gotcha.

Comment (silverwind) [reply modules/ssh/ssh.go:148]: Yeah, error handling in golang stdlib is a huge mess, the error classes are not even named consistently, and what I'm really missing from other languages are exceptions, but I guess golang will never get them as they are already too invested in the error return values at this point.

**Review by silverwind — APPROVED** [review]

File: modules/ssh/ssh.go (hunk 1 above)
Comment (delvh) [reply modules/ssh/ssh.go:148]: If this question already popped up during the review, I guess we can expect it to pop up more often.
What about a comment?

**Review by delvh — APPROVED** [review]

File: modules/ssh/ssh.go (hunk 1 above)
Comment (zeripath) [reply modules/ssh/ssh.go:148]:
```suggestion
		// Cannot use errors.Is here because ExitError doesn't implement Is
		// Thus errors.Is will do equality test NOT type comparison 
		if _, ok := err.(*exec.ExitError); !ok {
```

The problem is if we start adding comments like this we're going to need to add them everywhere we do error type checks.
