### PR TITLE
Test cache during init

### LINKED ISSUE #17380: Check if cache works correctly during init
Users may meet problem if the cache doesn't work. If we can check the cache during init, we can report this failure to users as early as possible.

```
2021/10/21 03:44:46 Started GET /repo/demo for x.x.x.x:yyyy
...
2021/10/21 03:44:46 ...ules/context/repo.go:849:func1() [E] GetCommitsCount: memcache: connect timeout to z.z.z.z:1234
...
2021/10/21 03:44:46 Completed GET /repo/demo 500 Internal Server Error in 255.614891ms
```

_Originally posted by @tardich in https://github.com/go-gitea/gitea/issues/17369#issuecomment-948232414_

### PR DESCRIPTION
**Pull request by wxiaoguang**
Some users set wrong options for cache. Such mistake can not be easily found before the cache is accessed.

Now we check if the cache works during init, the error can be reported as early as possible (just like incorrect database config would fail the init)

Close or relate:
* https://github.com/go-gitea/gitea/issues/17380
* https://github.com/go-gitea/gitea/issues/17369  (two problems in the issue: one is caused incorrect memcached config, antoher is caused by ld.so.preload)

### CODE REVIEW

File: modules/cache/cache.go [hunk 1]
```diff
@@ -35,6 +35,18 @@ func NewContext() error {
 		if conn, err = newCache(setting.CacheService.Cache); err != nil {
 			return err
 		}
+		const testKey = "__gitea_cache_test"
+		const testVal = "test-value"
+		if err = conn.Put(testKey, testVal, 10); err != nil {
+			return err
+		}
+		val := conn.Get(testKey)
+		if valStr, ok := val.(string); !ok || valStr != testVal {
```
Comment (zeripath) [inline modules/cache/cache.go:45]: Hmm... I'm not sure that all caches promise this.

Imagine a shared cache sitting behind a cluster of Giteas.

Our new Gitea starts up and puts this in to the cache. 

The cache is already full and this is not a commonly seen entry.
This cache has a hidden unreported queue where it keeps track of keys and only evicts if a key has been seen twice therefore this put doesn't cause an eviction. So it's not cached. 

So the Get fails here even though the cache is working correctly.

Similarly there could be a race between a busy cache evicting the item and it being read back.

Potentially better to just leave this at the put or ensuring that the get doesn't panic.

Comment (wxiaoguang) [reply modules/cache/cache.go:45]: I will change the error to a warning.

File: modules/cache/cache.go [hunk 2]
```diff
@@ -35,6 +36,20 @@ func NewContext() error {
...
+			// If the cache is full, the Get may not read the expected value stored by Put.
+			// Since we have checked that Put can success, so we just show a warning here, do not return an error to panic.
+			log.Warn("cache (adapter:%s, config:%s) doesn't seem to work correctly, set test value '%v' but get '%v'",
```
Comment (singuliere) [inline modules/cache/cache.go:48]: The **Get** method in [file](https://gitea.com/go-chi/cache/src/branch/master/file.go#L87-L98), [memcache](https://gitea.com/go-chi/cache/src/branch/master/memcache/memcache.go#L47-L53), [redis](https://gitea.com/go-chi/cache/src/branch/master/redis/redis.go#L63-L69), [mysql](https://gitea.com/go-chi/cache/src/branch/master/mysql/mysql.go#L84-L96), [postgres](https://gitea.com/go-chi/cache/src/branch/master/postgres/postgres.go#L84-L96) either returns the value or **nil**. It will return **nil** if the key is not found in the cache or if there is an error (including a connection error) and there is no way to distinguish between the two.

As @zeripath pointed out, returning **nil** does not mean there is a malfunction and issuing a warning could be misleading to the system administrator. If their cache is very busy, they may see this warning intermittently even though all is working as expected.

Maybe it is best to not test with **Get** at all? Or to issue a log.Info message declaring that the cache has been verified to work when it returns the expected value and remain silent when the return value is nil?

Comment (wxiaoguang) [reply modules/cache/cache.go:48]: If the cache is busy, if the value just written in can not be read, I believe the cache doesn't work correctly (the cache system can not provide expected cache function, then it is malfunction)

In such case, the sys admin should tune the cache system ASAP, otherwise, the cache doesn't help at all (if the sys admin are sure that the cache is full and won't help, then they should disable the cache for Gitea)

Comment (singuliere) [reply modules/cache/cache.go:48]: In that case it may be worth explaining more precisely. As a system administrator I would not know what to make of the fact that storing **test-value** returns **nil**. Maybe something like **" adding key=%s value=%s in the cache worked but getting the value of key=%s immediately afterwards failed. It is likely because the cache is too busy or not working properly.", testKey, testVal, testKey** ?

Comment (wxiaoguang) [reply modules/cache/cache.go:48]: In my mind the log should only show the problem, but not guess the reasons for sys admins. Incorrect guess would mislead users. A sys admin should be experienced and know how to check the caches. If the sys admins don't know how to check the cache, then they can ignore this warning, Gitea could still work.

Comment (singuliere) [reply modules/cache/cache.go:48]: > In my mind the log should only show the problem, but not guess the reasons for sys admins.

Fair enough.

>  ...then they can ignore this warning, Gitea could still work.

The error message does not say that though: how can the sysadmin know they can ignore the warning?

Comment (wxiaoguang) [reply modules/cache/cache.go:48]: Well, it's just a warning, not a error, a warning usually means that it's not that serious .... and Gitea continues running.

Comment (singuliere) [reply modules/cache/cache.go:48]: I'm sorry, it looks like I've wasted your time trying to improve the readability of this error/warning message.

Comment (wxiaoguang) [reply modules/cache/cache.go:48]: Oh you are welcome, I think the suggestions are good. Open discussion is always good.

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by wxiaoguang** [comment]
trigger bot
