### PR TITLE
Fixes #7152 - Allow create/update/delete message to be empty, use default message

### LINKED ISSUE #7152: Can't create file via API
- Gitea version (or commit ref): 1.8.2
- Git version: 
- Operating system: linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

always: Error: Unprocessable Entity

## Screenshots

s

s1

### PR DESCRIPTION
**Pull request by richmahn**
Fixed #7152 - the swagger comment for the "message" field for the API request for Create/Update/Delete says to be optional, but failed if not supplied. Now, like the web interface, uses a default message ("Add `file.txt`", "Update `file.txt`" and "Delete `file.txt" respectively) like the web edit/delete interface does.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Comment by lunny** [comment]
The message could be saved on locale file so that users could define it themselves.

**Comment by richmahn** [comment]
@lunny Don't quite understand what you are saying. It uses the locale text like the web interface does.

File: integrations/api_repo_file_create_test.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ func getCreateFileOptions() api.CreateFileOptions {
 		FileOptions: api.FileOptions{
 			BranchName:    "master",
 			NewBranchName: "master",
-			Message:       "Creates new/file.txt",
+			Message:       "Making this new file new/file.txt",
```
Comment (lunny) [inline integrations/api_repo_file_create_test.go:31]: ~@richmahn I mean we can use a translated message here. This will not block this PR.~

```
Message: ctx.Tr("my language message")
```

Comment (richmahn) [reply integrations/api_repo_file_create_test.go:31]: Why worry about translating a message in the integration test?

Comment (richmahn) [reply integrations/api_repo_file_create_test.go:31]: Unless you were just showing that as an example, but with GitHub there is no translation done with commit messages. But right, not the issue addressed by this PR, as it is just giving the default editor.repo.add, editor.repo.update, editor.repo.delete messages if message is empty.

Comment (zeripath) [reply integrations/api_repo_file_create_test.go:31]: I agree with @richmahn I don't think we should be trying to translate messages in the integration tests.

Comment (lunny) [reply integrations/api_repo_file_create_test.go:31]: @richmahn  Oh. it's a test file. Ignore my words above.

**Review by lunny — APPROVED** [review]

File: integrations/api_repo_file_create_test.go (hunk 1 above)
Comment (richmahn) [reply integrations/api_repo_file_create_test.go:31]: I think a message should never be translated, but as the user intended. Only when it is auto-generated should it be translated. There may be a problem to as what if for some reason they actually wanted to write something like "template" or "home" which would get translated to "Template" or "Home" from our locale_en-US.ini file... while not a big change, it would boggle them why the message is getting uppercased.
