### PR TITLE
fix #36463: preserve sort order of exclusive labels from template repo

### LINKED ISSUE #36463: Exclusive issue label sort order not preserved when using a template repository
### Description

When creating a repository with issue labels based off a template repository, the sort order of none of the exclusive labels is preserved.

This is reproducible at https://demo.gitea.com/.

### Steps to reproduce

1. Create a template repository
2. Create one or more issue label which is exclusive and has an explicit sort order (e.g., `exclusive/alpha` with sort order 1, and `exclusive/bravo` with sort order 2)
3. Create a _new_ repository based off the template choosing to copy issue labels
4. View the list of issue labels available in that newly created repository

#### Expected behavior

The exclusive labels available in the template repository exist in the new repository, are exclusive, and have the same sort order.

With the example names listed above, `exclusive/alpha` still has sort order 1, and `exclusive/bravo` still has sort order 2.

#### Observed behavior

The exclusive labels available in the template repository exist in the new repository, and are exclusive, but _do not_ have any sort order (i.e., the sort order was lost).

Hence, `exclusive/alpha` becomes an exclusive label with _no_ sort order (sort order 0), and `exclusive/bravo` also becomes an exclusive label with _no_ sort order.

### Gitea Version

1.25.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Image

Image

### Git Version

2.49.1

### Operating System

Ubuntu Server 24.04 LTS

### How are you running Gitea?

ARM Docker container running on a RasPI 5. But the issue is also reproducible on https://demo.gitea.com/.

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by cyx25**
### Description
When creating a new repository and copying issue labels from a template, the explicit sort order of exclusive labels was previously being lost (resetting to 0). This fix ensures that the original sort order for exclusive labels (e.g., 1, 2) is properly copied and retained in the newly created repository.

Fixes #36463

### Changes

- Modified template.go to explicitly copy the ExclusiveOrder field during the label generation process.
- Updated integration test TestGenerateRepository to allow IssueLabels option and verify that labels in the generated repository match the template's labels, by inserting template labels dynamically into the database.

### CODE REVIEW

File: tests/integration/repo_test.go [hunk 1]
```diff
@@ -559,3 +561,47 @@ func TestGenerateRepository(t *testing.T) {
 	assert.NoError(t, err)
 	assert.False(t, exist)
 }
+
+func TestGenerateRepositoryPreservesLabels(t *testing.T) {
```
Comment (wxiaoguang) [inline tests/integration/repo_test.go]: The labels can be dynamically inserted into database, and use the existing `func TestGenerateRepository(t *testing.T)` to test.


It doesn't need to introduce more fixtures or tests to slow down the whole CI/testing time.

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]
