### PR TITLE
Ensure git tag tests and others create test repos in tmpdir

### LINKED ISSUE #18077: CI unrelated failures
During unit-test:

```
+ make unit-test-coverage test-check
Running unit-test-coverage -race -tags 'sqlite sqlite_unlock_notify'...
?   	code.gitea.io/gitea	[no test files]
ok  	code.gitea.io/gitea/build/codeformat	0.189s	coverage: 71.8% of statements
ok  	code.gitea.io/gitea/cmd	0.793s	coverage: 8.6% of statements
?   	code.gitea.io/gitea/contrib/environment-to-ini	[no test files]
......
?   	code.gitea.io/gitea/services/task	[no test files]
ok  	code.gitea.io/gitea/services/user	6.467s	coverage: 30.7% of statements
ok  	code.gitea.io/gitea/services/webhook	4.276s	coverage: 62.0% of statements
ok  	code.gitea.io/gitea/services/wiki	13.117s	coverage: 65.5% of statements

==>Ok

Running test-check...
make test-backend has changed files in the source tree:
?? mssql-log/
?? mysql-log/
?? mysql8-log/
You should change the tests to create these files in a temporary directory.
Do not simply add these files to .gitignore
make: *** [Makefile:368: test-check] Error 1
```

### LINKED ISSUE #18444: Random unit test failure in TestRepository_GetAnnotatedTag
### Gitea Version

1.15.x/1.16.x/main

### Git Version

On CI

### Operating System

Linux

### How are you running Gitea?

In the CI

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Description

```
TestRepository_GetAnnotatedTag (0.24s)
    repo_tag_test.go:90: 
        	Error Trace:	repo_tag_test.go:90
        	Error:      	Received unexpected error:
        	            	exit status 128 - fatal: destination path 'tests/repos/repo1_TestRepository_GetTag' already exists and is not an empty directory.
```

This test and the rest of the tests in this file should be changed to clone into random temporary directories:

https://github.com/go-gitea/gitea/blob/726715fcfb73751452adbf5cf594908b3954b080/modules/git/repo_tag_test.go#L86-L91

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by zeripath**
There are a few places where tests appear to reuse testing repos which
causes random CI failures.

This PR simply changes these tests to ensure that cloning always happens
into new temporary directories.

Also ensure that integration tests go to repo_test_dir too.

Fix #18444
Fix #18077

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]
LGTM. IIRC, most `assert.Xxx` return `bool`

```
if err != nil {
	assert.NotNil(t, aTag)
	return
}
```

could be written as:

```
if !assert.NotNil(t, aTag) {
	return
}
```

File: modules/git/repo_compare_test.go [hunk 1]
```diff
@@ -37,17 +53,25 @@ func TestReadPatch(t *testing.T) {
...
+
 	// This patch is an empty one (sometimes it's a 404)
 	noCommit, err := repo.ReadPatchCommit(1)
 	assert.Error(t, err)
+
 	// This patch is legit and should return a commit
 	oldCommit, err := repo.ReadPatchCommit(2)
-	assert.NoError(t, err)
+	if err != nil {
+		assert.NoError(t, err)
```
Comment (6543) [inline modules/git/repo_compare_test.go:72]:
```diff
-	if err != nil {
-		assert.NoError(t, err)
+	if !assert.NoError(t, err) {
```

would have done it too ...
