### PR TITLE
fix(upgrade.sh): use HTTPS for GPG key import and restore SELinux context after upgrade

### LINKED ISSUE #36928: contrib/upgrade.sh: GPG key import fails when HKP port 11371 is blocked by firewall
## Description

`contrib/upgrade.sh` imports the Gitea signing key using the GPG keyserver protocol:

```bash
gpg --keyserver keys.openpgp.org --recv 7C9E68152594688862D62AF62D9AE806EC1592E2
```

This uses HKP port **11371**, which is blocked on many firewalls and cloud/corporate networks, causing:

```
gpg: keyserver receive failed: Connection timed out
```

The upgrade aborts because `set -euo pipefail` treats the non-zero exit as fatal.

## Steps to reproduce

1. Run `contrib/upgrade.sh` on a machine where outbound port 11371 is firewalled
2. GPG key import fails with `Connection timed out`
3. Upgrade aborts before replacing the binary

## Expected behaviour

The script should import the key successfully regardless of firewall rules on port 11371.

## Proposed fix

Use the `keys.openpgp.org` **HTTPS REST API** (port 443) instead of HKP, with keyservers as fallback:

```bash
curl -fsSL --connect-timeout 10 \
  "https://keys.openpgp.org/vks/v1/by-fingerprint/7C9E68152594688862D62AF62D9AE806EC1592E2" \
  | gpg --import \
  || gpg --keyserver keyserver.ubuntu.com --recv 7C9E68152594688862D62AF62D9AE806EC1592E2 \
  || gpg --keyserver keys.openpgp.org --recv 7C9E68152594688862D62AF62D9AE806EC1592E2
```

Verified working — same server, same key, served over port 443 instead of 11371.

## Environment

- Gitea version: 1.24.3 → 1.25.5
- OS: Linux (Fedora)
- Network: outbound port 11371 blocked by firewall

### LINKED ISSUE #36929: contrib/upgrade.sh: Gitea fails to start after upgrade on SELinux systems (exit code 203/EXEC)
## Description

After a successful upgrade on RHEL/Fedora (SELinux enforcing) systems, Gitea fails to start with systemd exit code `203/EXEC`:

```
gitea.service: Failed with result 'exit-code'.
Process: ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini (code=exited, status=203/EXEC)
```

## Root cause

The script moves the new binary from `$giteahome` (e.g. `/var/lib/gitea/`) to `/usr/local/bin/gitea`:

```bash
mv -f "$binname" "$giteabin"
```

`mv` preserves the SELinux security context from the source directory, so the binary ends up with the wrong label for an executable under `/usr/local/bin/`. Systemd then refuses to execute it.

Running `sudo restorecon -v /usr/local/bin/gitea` immediately fixes it.

## Proposed fix

Add a `restorecon` call after the `mv`, guarded so it is a no-op on non-SELinux systems:

```bash
cp -f "$giteabin" "$giteabin.bak" && mv -f "$binname" "$giteabin"
# Restore SELinux context if applicable (e.g. RHEL/Fedora)
command -v restorecon &>/dev/null && restorecon -v "$giteabin" || true
```

## Environment

- Gitea version: 1.24.3 → 1.25.5
- OS: Fedora with SELinux enforcing
- systemd exit code: `203/EXEC`

### PR DESCRIPTION
**Pull request by xijiang**
## Summary

Two bug fixes for `contrib/upgrade.sh` found during a real-world upgrade from 1.24.3 to 1.25.5 on Fedora.

---

### Fix 1: GPG key import fails when HKP port 11371 is blocked (closes #36928)

**Before:**
```bash
gpg --keyserver keys.openpgp.org --recv 7C9E68152594688862D62AF62D9AE806EC1592E2
```
This uses HKP port **11371**, which is blocked by many firewalls. The upgrade aborts with:
```
gpg: keyserver receive failed: Connection timed out
```

**After:**
```bash
curl -fsSL --connect-timeout 10 \
  "https://keys.openpgp.org/vks/v1/by-fingerprint/7C9E68152594688862D62AF62D9AE806EC1592E2" \
  | gpg --import \
  || gpg --keyserver keyserver.ubuntu.com --recv 7C9E68152594688862D62AF62D9AE806EC1592E2 \
  || gpg --keyserver keys.openpgp.org --recv 7C9E68152594688862D62AF62D9AE806EC1592E2
```
Same `keys.openpgp.org` server, same key — but fetched over **HTTPS port 443** which is universally accessible. Keyservers remain as fallbacks.

---

### Fix 2: Gitea fails to start after upgrade on SELinux systems (closes #36929)

**Problem:** After `mv`-ing the binary from `$giteahome` to `/usr/local/bin/gitea`, the file retains the SELinux context of the source directory. Systemd refuses to execute it, exiting with `status=203/EXEC`.

**Fix:** Add a `restorecon` call guarded by `command -v` so it is a no-op on non-SELinux systems:
```bash
command -v restorecon &>/dev/null && restorecon -v "$giteabin" || true
```
Verified: `restorecon -v /usr/local/bin/gitea` immediately restored service on the affected machine.

### CODE REVIEW

File: contrib/upgrade.sh [hunk 1]
```diff
@@ -108,7 +108,9 @@ curl --connect-timeout 10 --silent --show-error --fail --location -O "$binurl{,.
 sha256sum -c "${binname}.xz.sha256"
 if [[ -z "${ignore_gpg:-}" ]]; then
   require gpg
-  gpg --keyserver keys.openpgp.org --recv 7C9E68152594688862D62AF62D9AE806EC1592E2
+  curl -fsSL --connect-timeout 10 "https://keys.openpgp.org/vks/v1/by-fingerprint/7C9E68152594688862D62AF62D9AE806EC1592E2" | gpg --import \
```
Comment (wxiaoguang) [inline contrib/upgrade.sh:112]:
```suggestion
  # try to use curl first, it uses standard tcp 443 port and works better behind strict firewall rules
  curl -fsSL --connect-timeout 10 "https://keys.openpgp.org/vks/v1/by-fingerprint/7C9E68152594688862D62AF62D9AE806EC1592E2" | gpg --import \
```

File: contrib/upgrade.sh [hunk 2]
```diff
@@ -108,7 +108,10 @@ curl --connect-timeout 10 --silent --show-error --fail --location -O "$binurl{,.
 sha256sum -c "${binname}.xz.sha256"
 if [[ -z "${ignore_gpg:-}" ]]; then
   require gpg
-  gpg --keyserver keys.openpgp.org --recv 7C9E68152594688862D62AF62D9AE806EC1592E2
+  # try to use curl first, it uses standard tcp 443 port and works better behind strict firewall rules
+  curl -fsSL --connect-timeout 10 "https://keys.openpgp.org/vks/v1/by-fingerprint/7C9E68152594688862D62AF62D9AE806EC1592E2" | gpg --import \
+    || gpg --keyserver keyserver.ubuntu.com --recv 7C9E68152594688862D62AF62D9AE806EC1592E2 \
```
Comment (wxiaoguang) [inline contrib/upgrade.sh]:
```suggestion
```

**Review by wxiaoguang — APPROVED** [review]

**Review by TheFox0x7 — APPROVED** [review]
