### PR TITLE
Fix bug when the linked account was disactived and list the linked accounts

### LINKED ISSUE #28667: accountlinks.tmpl: nil pointer evaluating oauth2.Provider.IconHTML
#### Description and suspected cause
It is possible to get a `nil` pointer for `$providerData` in [accountlinks.tmpl](https://github.com/go-gitea/gitea/blob/f8a1bad883aa4697b4001f74e2074898d7162aef/templates/user/settings/security/accountlinks.tmpl#L30). This then results in an error like:
```
An error occurred:

Render failed, failed to render template: user/settings/security/security, error: template error: builtin(bindata):user/settings/security/accountlinks:32:20 : executing "user/settings/security/accountlinks" at <$providerData.IconHTML>: nil pointer evaluating oauth2.Provider.IconHTML
----------------------------------------------------------------------
					{{$providerData.IconHTML 20}}
					               ^
----------------------------------------------------------------------
```

I haven't exactly figured out how to replicate this yet, but will investigate it myself. Just created the issue to keep track of my investigation into this.

Probably something to do with an error that is ignored [here](https://github.com/go-gitea/gitea/blob/da58bb85fa4ff8a37f843d09452b4244b18f93ce/routers/web/user/setting/security/security.go#L91)

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_
Relevant logs are in description (they're short).

### Screenshots

image

### Git Version

2.40.1

### Operating System

gitea/gitea Docker image on virtual Debian 12 host.

### How are you running Gitea?

Unmodified [gitea/gitea Docker image](https://hub.docker.com/r/gitea/gitea/) running on a virtual Debian 12 host with a mariadb 10 database.

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by lunny**
The bug has been fixed on v1.22 but not backport to v1.21.
This original PR have many refactors so I don't think it's necessary to backport all of them.

Fix #28667

### CODE REVIEW

File: models/auth/oauth2.go [hunk 1]
```diff
@@ -626,10 +626,14 @@ func (err ErrOAuthApplicationNotFound) Unwrap() error {
 	return util.ErrNotExist
 }
 
-// GetActiveOAuth2ProviderSources returns all actived LoginOAuth2 sources
-func GetActiveOAuth2ProviderSources() ([]*Source, error) {
+// GetOAuth2ProviderSources returns all actived LoginOAuth2 sources
+func GetOAuth2ProviderSources(isActive bool) ([]*Source, error) {
```
Comment (wxiaoguang) [inline models/auth/oauth2.go]: It should be called as `onlyActive` ?

Comment (lunny) [reply models/auth/oauth2.go]: Fixed in b56459ca5f3d3c4d2980dc1d5443b8382ea21400

**Review by lafriks — APPROVED** [review]

**Review by 6543 — APPROVED** [review]
