### PR TITLE
Check if label template exist first

### LINKED ISSUE #14327: API: create repo with invalid label set hangs gitea
- Gitea version (or commit ref): 1.14.0+dev-454-g19ae6439b 
- Git version: 2.29.2
- Operating system: fedora linux
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (probably, at least on gitea.com, see https://gitea.com/gitea/gitea.com/issues/21
  - [ ] No
- Log gist: https://pastebin.com/eXZc273c

## Description
Using the API to create a repo with a non-existent label-set makes gitea hang, and leaves a partially initialized repo.

On gitea.com the repo is partially created, and an empty error message is returned.
Testing locally with 9659808172b0d33a79eca44e37cabaf33fbf1b8b, Gitea hangs indefinitely instead of finishing the request.

Following requests give `repository files already exist`.

To reproduce:
```
tea repo create --name foo --labels asdfasdf404
```

ref: https://gitea.com/gitea/gitea.com/issues/21

### PR DESCRIPTION
**Pull request by 6543**
fix #14327

and other possible db-deadlocks with SQLite

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: models/repo.go [hunk 1]
```diff
@@ -1512,60 +1512,82 @@ func UpdateRepositoryUnits(repo *Repository, units []RepoUnit, deleteUnitTypes [
...
+	defer sess.Close()
+	if err := sess.Begin(); err != nil {
+		return err
+	}
+
+	if err := deleteRepository(sess, doer, uid, repoID); err != nil {
+		return err
+	}
+
+	if err := sess.Commit(); err != nil {
```
Comment (lunny) [inline models/repo.go]: if failed, we should not rewrie public keys.

**Comment by 6543** [comment]
ok this resolve the DB deadlock for sqlite without the check, but I'll leave the check in since if it will fail anyway why not check it before touching DB at all ...

File: models/repo.go [hunk 2]
```diff
@@ -1605,92 +1618,79 @@ func DeleteRepository(doer *User, uid, repoID int64) error {
...
-				return fmt.Errorf("Commit: %v SSH Keys: %v", err, err2)
-			}
-		}
-		return fmt.Errorf("Commit: %v", err)
-	}
-
-	sess.Close()
-
 	// We should always delete the files after the database transaction succeed. If
 	// we delete the file but the database rollback, the repository will be borken.
```
Comment (zeripath) [inline models/repo.go]: Have you accounted for this?

Comment (6543) [reply models/repo.go]: now this will be a bigger refactor ... I think I'll backport the check and use this pull to refactor it

**Review by zeripath — APPROVED** [review]
