### PR TITLE
Fix gpg key deletion

### LINKED ISSUE #14531: PGP keys aren't deleted when user is deleted
- Gitea version (or commit ref): Tested on both 1.13.1 and gfcfbab99f
- Git version: 2.17.1
- Operating system: Debian 10

Gitea is from downloads, and is running as a systemd service.
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (repro link N/A)
  - [ ] No
- Log gist: https://gist.github.com/aveao/481fa4aacbb7377ce202fcff780f5dd1

### Current behavior

When a user deletes their account, their pgp key(s) in `pgp_key_import` table isn't deleted. As such, when the user registers again with the same email and tries to add the PGP key, it causes a unique constraint violation, and gitea throws a 500.

### Expected behavior

- Bugfix: When a user deletes their account, their PGP key(s) in `pgp_key_import` should be deleted too.
- Nice to have in addition to bugfix: Trying to add non-unique PGP keys should probably display a better error page.

## Screenshots

500 error

### PR DESCRIPTION
**Pull request by anton-khimich**
Fixes #14531.

Per #14531, deleting a user account will delete the user's GPG keys
from the `gpg_key` table but not from `gpg_key_import`, which causes
an error when creating an account with the same email and attempting
to re-add the same key. This commit deletes all entries from
`gpg_key_import` that match any GPG key IDs belonging to the user.

Note: Deleting the user's keys from `gpg_key_import` this way seems pretty convoluted,
but I don't see an obvious alternative except for maybe modifying `GPGKeyImport` to
have an `OwnerID` field as in `GPGKey`.

### CODE REVIEW

File: models/user.go [hunk 1]
```diff
@@ -1208,6 +1208,16 @@ func deleteUser(e Engine, u *User) error {
 	// ***** END: PublicKey *****
 
 	// ***** START: GPGPublicKey *****
+	keys, err := ListGPGKeys(u.ID, ListOptions{})
```
Comment (6543) [inline models/user.go]: need `listGPGKeys(e Engine, ...)` version

Comment (anton-khimich) [reply models/user.go]: To clarify, is that the `listGPGKeys` defined [here?](https://github.com/go-gitea/gitea/blob/master/routers/api/v1/user/gpg_key.go#L18-L31)

Comment (6543) [reply models/user.go]: I'll send you the diff to apply :)

Comment (6543) [reply models/user.go:1211]:
```diff
diff --git a/models/gpg_key.go b/models/gpg_key.go
index b944fdcbf..6e5347bac 100644
--- a/models/gpg_key.go
+++ b/models/gpg_key.go
@@ -65,7 +65,11 @@ func (key *GPGKey) AfterLoad(session *xorm.Session) {
 
 // ListGPGKeys returns a list of public keys belongs to given user.
 func ListGPGKeys(uid int64, listOptions ListOptions) ([]*GPGKey, error) {
-       sess := x.Where("owner_id=? AND primary_key_id=''", uid)
+       return listGPGKeys(x, uid, listOptions)
+}
+
+func listGPGKeys(e Engine, uid int64, listOptions ListOptions) ([]*GPGKey, error) {
+       sess := e.Where("owner_id=? AND primary_key_id=''", uid)
        if listOptions.Page != 0 {
                sess = listOptions.setSessionPagination(sess)
        }
diff --git a/models/user.go b/models/user.go
index 642d9d56a..495fed1ff 100644
--- a/models/user.go
+++ b/models/user.go
@@ -1208,7 +1208,7 @@ func deleteUser(e Engine, u *User) error {
        // ***** END: PublicKey *****
 
        // ***** START: GPGPublicKey *****
-       keys, err := ListGPGKeys(u.ID, ListOptions{})
+       keys, err := listGPGKeys(e, u.ID, ListOptions{})
        if err != nil {
                return fmt.Errorf("ListGPGKeys: %v", err)
        }
```

Comment (6543) [reply models/user.go]:
```diff
diff --git a/models/gpg_key.go b/models/gpg_key.go
index b944fdcbf..3e8ddd962 100644
--- a/models/gpg_key.go
+++ b/models/gpg_key.go
@@ -65,7 +65,11 @@ func (key *GPGKey) AfterLoad(session *xorm.Session) {
 
 // ListGPGKeys returns a list of public keys belongs to given user.
 func ListGPGKeys(uid int64, listOptions ListOptions) ([]*GPGKey, error) {
-       sess := x.Where("owner_id=? AND primary_key_id=''", uid)
+       return listGPGKeys(x, uid, listOptions)
+}
+
+func listGPGKeys(e Engine, uid int64, listOptions ListOptions) ([]*GPGKey, error) {
+       sess := e.Table(&GPGKey{}).Where("owner_id=? AND primary_key_id=''", uid)
        if listOptions.Page != 0 {
                sess = listOptions.setSessionPagination(sess)
        }
diff --git a/models/user.go b/models/user.go
index 642d9d56a..495fed1ff 100644
--- a/models/user.go
+++ b/models/user.go
@@ -1208,7 +1208,7 @@ func deleteUser(e Engine, u *User) error {
        // ***** END: PublicKey *****
 
        // ***** START: GPGPublicKey *****
-       keys, err := ListGPGKeys(u.ID, ListOptions{})
+       keys, err := listGPGKeys(e, u.ID, ListOptions{})
        if err != nil {
                return fmt.Errorf("ListGPGKeys: %v", err)
        }
```

**Review by 6543 — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
We also needs a doctor command to correct history wrong data.

**Comment by lunny** [comment]
Please send backport to v1.13
