### PR TITLE
Make composer registry support tar.gz and tar.bz2 and fix bugs

### LINKED ISSUE #35957: Please add support for tar / tar.gz / tar.bz2 archives in Composer package registry
### Feature Description

Hello,

First, a big thank you to all the maintainers working on Gitea.
It's really a great tool.

While working with Composer packages and Gitea's package registry, I noticed that Gitea only allows ZIP archives to be uploaded. [[1]]
Meanwhle, Composer supports other archive formats (tar, tar.gz & tar.bz2) in additional to zip archives. [[2]]
Indeed, trying to upload anything other than a zip archive into Gitea fails:
```sh
$ curl --netrc --upload-file /tmp/build.tar.gz https://gitea.dev/api/packages/fpoirotte/composer
{"errors":[{"status":500,"message":"zip: not a valid zip file"}]}
```

Since tar.gz and tar.bz2 archives usually offer much better compression than the zip format, it could help save disk space if these were supported too.

Would it be possible to add support for these formats? (and since both formats are built around the tar format, add support for raw tar archives as well in the process)

Cheers,
François

[1]: https://docs.gitea.com/usage/packages/composer#publish-a-package
[2]: https://getcomposer.org/doc/03-cli.md#archive

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #35957

### CODE REVIEW

File: modules/packages/composer/metadata.go [hunk 1]
```diff
@@ -44,7 +51,7 @@ type Metadata struct {
 	Description string            `json:"description,omitempty"`
 	Readme      string            `json:"readme,omitempty"`
 	Keywords    []string          `json:"keywords,omitempty"`
-	Comments    Comments          `json:"_comments,omitempty"`
+	Comments    Comments          `json:"_comment,omitempty"`
```
Comment (wxiaoguang) [inline modules/packages/composer/metadata.go:54]: Here is a bug. It should be `_comment`

https://getcomposer.org/doc/04-schema.md#-comment

File: modules/packages/composer/metadata.go [hunk 2]
```diff
@@ -111,39 +118,121 @@ type Author struct {
...
+}
+
+func readPackageFileZip(r ReadSeekAt, filename string, limit int) ([]byte, error) {
+	archive, err := zip.NewReader(r, r.Size())
 	if err != nil {
 		return nil, err
 	}
 
 	for _, file := range archive.File {
-		if strings.Count(file.Name, "/") > 1 {
```
Comment (wxiaoguang) [inline modules/packages/composer/metadata.go:122]: Here seems a bug, only the "composer.json" in the root should be used?

File: modules/packages/composer/metadata.go [hunk 3]
```diff
@@ -168,17 +257,23 @@ func ParseComposerFile(archive *zip.Reader, pathPrefix string, r io.Reader) (*Pa
...
-		cj.Readme = string(buf)
-		_ = f.Close()
-	} else {
+	dataReadmeMd, _ := readPackageFile(pkgExt, r, cj.Readme, 10*1024)
+
+	// FIXME: legacy problem, the "Readme" field is abused, it should always be the path to the readme file
+	if len(dataReadmeMd) == 0 {
 		cj.Readme = ""
+	} else {
+		cj.Readme = string(dataReadmeMd)
```
Comment (wxiaoguang) [inline modules/packages/composer/metadata.go:269]: Abused field, but impossible to get an easy fix in this PR

File: routers/api/packages/composer/composer.go [hunk 4]
```diff
@@ -235,7 +233,7 @@ func UploadPackage(ctx *context.Context) {
 		},
 		&packages_service.PackageFileCreationInfo{
 			PackageFileInfo: packages_service.PackageFileInfo{
-				Filename: strings.ToLower(fmt.Sprintf("%s.%s.zip", strings.ReplaceAll(cp.Name, "/", "-"), cp.Version)),
```
Comment (wxiaoguang) [inline routers/api/packages/composer/composer.go:238]: Old code generated a name like `gitea-package..zip` if the "version" is empty (update: old code guarantees that the "version" can't be empty, so new code also follows the behavior)

**Comment by wxiaoguang** [comment]
Also see many bugs, some get fixed, some don't.

Also cc @KN4CK3R

**Review by lunny — APPROVED** [review]

**Review by silverwind — APPROVED** [review]
