### PR TITLE
Fix count for commit graph last page

### LINKED ISSUE #8798: [Bug] Commit Graph: pagination sometimes drop last
repo wich has this problem: https://gitea.com/gitnex/GitNex/graph

"Last" go to https://gitea.com/gitnex/GitNex/graph?page=3
but in realety it is https://gitea.com/gitnex/GitNex/graph?page=4

so affected versions are: current, 1.10?

### PR DESCRIPTION
**Pull request by ghost**
Fixes #8798

### CODE REVIEW

File: modules/git/commit.go [hunk 1]
```diff
@@ -248,6 +248,22 @@ func CommitChanges(repoPath string, opts CommitChangesOptions) error {
 	return err
 }
 
+func allCommitsCount(repoPath string) (int64, error) {
+	cmd := NewCommand("rev-list", "--all", "--count")
+
+	stdout, err := cmd.RunInDir(repoPath)
```
Comment (lafriks) [inline modules/git/commit.go]: no need for `cmd` variable if used only once
```suggestion
	stdout, err := NewCommand("rev-list", "--all", "--count").RunInDir(repoPath)
```

**Review by lafriks — CHANGES_REQUESTED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by jaqra** [comment]
@lafriks  this is not part of 1.10. added in 1.11

File: modules/git/commit.go [hunk 2]
```diff
@@ -248,6 +248,20 @@ func CommitChanges(repoPath string, opts CommitChangesOptions) error {
...
+	if err != nil {
+		return 0, err
+	}
+
+	return strconv.ParseInt(strings.TrimSpace(stdout), 10, 64)
+}
+
+// AllCommitsCount returns count of all commits in repository
+func AllCommitsCount(repoPath string) (int64, error) {
+	return allCommitsCount(repoPath)
```
Comment (zeripath) [inline modules/git/commit.go]: Why the indirection here? I could see it being reasonable to add a function on git.Repository that basically just calls a non-localised repo only function but this seems unnecessary.

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
Thanks!
