### PR TITLE
[Vendor] Fix Version Compare Lib

### LINKED ISSUE #12731: Gitea fails with non-release git version number (2.28.0.618.gf4bc123cb7)
- Gitea version (or commit ref): [`1.13.0+dev-545-g913ac9cac`](https://github.com/go-gitea/gitea/commit/913ac9cacda864b6f0bcb6225c499bdbd8e9f90d)
- Git version: `2.28.0.618.gf4bc123cb7`
- Operating system: `Arch Linux` || `Fedora 33 (beta)`
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Not relevant
- Log gist:
```log
~/utils/gitea on branch master via ⬢ v14.7.0 via 🐹 v1.15 on 🐳 v19.03.11 took 3m 52s
➜  ./gitea
2020/09/05 20:24:58 cmd/web.go:108:runWeb() [I] Starting Gitea on PID: 1435904
2020/09/05 20:24:58 ...s/setting/setting.go:540:NewContext() [W] Custom config '.../gitea/custom/conf/app.ini' not found, ignore this if you're running first time
2020/09/05 20:24:58 ...dules/setting/git.go:68:newGit() [F] Failed to initialize Git settings%!(EXTRA *log.ColoredValue=Git version missing: Malformed version: 2.28.0.618.gf4bc123cb7)
```

## Description

Recently there has been a change in checking of `git` version used introduced by [bc11caff94896c8c3f9a5c970a77470ed9beb83a](https://github.com/go-gitea/gitea/commit/bc11caff94896c8c3f9a5c970a77470ed9beb83a).
It causes issues for non-release `git` builds with versions such as `2.28.0.618.gf4bc123cb7` and makes Gitea fail to run (start).
Build process yields no errors at all, though.

### PR DESCRIPTION
**Pull request by 6543**
close #12731

test: https://play.golang.org/p/WgUmgbn1uN7

### CODE REVIEW

**Comment by 6543** [comment]
upstream pull: https://github.com/hashicorp/go-version/pull/77

File: modules/git/git.go [hunk 1]
```diff
@@ -15,7 +15,7 @@ import (
 
 	"code.gitea.io/gitea/modules/process"
 
-	"github.com/hashicorp/go-version"
+	"github.com/6543/go-version"
```
Comment (techknowlogick) [inline modules/git/git.go]: Instead of updating all of these references, could you instead add a replace call to the go.mod so that when (if?) the PR is accepted upstream then we could just remove the replace

Comment (6543) [reply modules/git/git.go]: @techknowlogick as in Discord ...

I get errors like `replace github.com/hashicorp/go-version: version "1.2.1" invalid: unknown revision 1.2.1`
If you have more luck I'm happy if you could push your solution :/

**Review by zeripath — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

File: vendor/modules.txt [hunk 2]
```diff
@@ -965,3 +965,4 @@ xorm.io/xorm/log
 xorm.io/xorm/names
 xorm.io/xorm/schemas
 xorm.io/xorm/tags
+# github.com/hashicorp/go-version => github.com/6543/go-version v1.2.2
```
Comment (6543) [inline vendor/modules.txt]:
```suggestion
# github.com/hashicorp/go-version => github.com/6543/go-version v1.2.3
```

File: vendor/modules.txt [hunk 3]
```diff
@@ -423,7 +423,7 @@ github.com/hashicorp/go-cleanhttp
 # github.com/hashicorp/go-retryablehttp v0.6.6
 ## explicit
 github.com/hashicorp/go-retryablehttp
-# github.com/hashicorp/go-version v1.2.1
+# github.com/hashicorp/go-version v0.0.0-00010101000000-000000000000 => github.com/6543/go-version v1.2.2
```
Comment (6543) [inline vendor/modules.txt]:
```suggestion
# github.com/hashicorp/go-version v0.0.0-00010101000000-000000000000 => github.com/6543/go-version v1.2.3
```

File: go.mod [hunk 4]
```diff
@@ -117,3 +117,5 @@ require (
 	xorm.io/builder v0.3.7
 	xorm.io/xorm v1.0.4
 )
+
+replace github.com/hashicorp/go-version => github.com/6543/go-version v1.2.2
```
Comment (6543) [inline go.mod]:
```suggestion
replace github.com/hashicorp/go-version => github.com/6543/go-version v1.2.3
```

**Comment by 6543** [comment]
@techknowlogick thanks

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
cheers fellows 🚀
