### PR TITLE
Fix remove org user failure on mssql

### LINKED ISSUE #34448: Deleting a User that belongs to an org with 0 repositories may result in database error in mssql
### Description

`user_service.DeleteUser(t.Context(), user, true)` fails on mssql for userid 2 in testdata

Due to NumRepos being 0 for one org this user belongs to.
https://github.com/go-gitea/gitea/blob/7a097138deeb0289c1d52c942eb1b1dfe20d1cda/services/org/user.go#L67-L68

Not a problem on any other database

### Gitea Version

1.24-rc0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

1.39.5

### Operating System

macOS

### How are you running Gitea?

in test environment
```go

// Test that the ephemeral runner is deleted when a user is deleted
func testEphemeralActionsRunnerDeletionByUser(t *testing.T) {
	defer tests.PrepareTestEnv(t)()

	_, err := actions_model.GetRunnerByID(t.Context(), 34350)
	assert.NoError(t, err)

	task := unittest.AssertExistsAndLoadBean(t, &actions_model.ActionTask{ID: 52})
	assert.Equal(t, actions_model.StatusRunning, task.Status)

	user := unittest.AssertExistsAndLoadBean(t, &user_model.User{ID: 2})

	err = user_service.DeleteUser(t.Context(), user, true)
	assert.NoError(t, err)

	_, err = actions_model.GetRunnerByID(t.Context(), 34350)
	assert.ErrorIs(t, err, util.ErrNotExist)
}
```

### Database

MSSQL

### PR DESCRIPTION
**Pull request by ChristopherHX**
* mssql does not support fetching 0 repositories
  * remove paging by NumRepos that might be 0
* extend admin api test to purge user 2

Fixes #34448

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: services/org/user.go [hunk 1]
```diff
@@ -64,10 +64,15 @@ func RemoveOrgUser(ctx context.Context, org *organization.Organization, user *us
 	if err != nil {
 		return fmt.Errorf("AccessibleReposEnv: %w", err)
 	}
-	repoIDs, err := env.RepoIDs(ctx, 1, org.NumRepos)
-	if err != nil {
-		return fmt.Errorf("GetUserRepositories [%d]: %w", user.ID, err)
+	var repoIDs []int64
+	// mssql does not support fetching 0 repositories
+	if org.NumRepos > 0 {
+		repoIDs, err = env.RepoIDs(ctx, 1, org.NumRepos)
```
Comment (wxiaoguang) [inline services/org/user.go]: I don't think the fix is right. What if `NumRepos` is out-of-sync? Such problems happened a lot.

The root problem is not related to `org.NumRepos`, the real problem is that `RepoIDs` should have a correct behavior

Comment (wxiaoguang) [reply services/org/user.go]: See https://github.com/go-gitea/gitea/pull/34449/commits/1c32f8cffe582933aa0db3edee94aebb7f898b9a

**Review by wxiaoguang — APPROVED** [review]
Vote my approval ahead, feel free to improve my changes.

File: services/org/user.go (hunk 1 above)
Comment (ChristopherHX) [reply services/org/user.go]: I guess you are right this works for me, found this by accident while trying to fix my user deletion test cases
