### PR TITLE
Fix orphaned objects deletion bug

### LINKED ISSUE #15668: [Bug] [Doctor] db consistency fix function not working
doctor **check-db-consistency** task use `models.DeleteOrphanedObjects()` witch does not work

ref: https://github.com/go-gitea/gitea/pull/15658#issuecomment-829474478

tested with `mariadb Ver 15.1`

gitea v1.13.7, v1.14.1 & master have same issue:

v13: `Error: Unsupported type`
v14&master: ` - [C] Error: %!v(MISSING) whilst deleting orphaned objects`

### PR DESCRIPTION
**Pull request by lunny**
close  #15668

### CODE REVIEW

**Review by KN4CK3R — APPROVED** [review]

File: models/consistency_test.go [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+
+import (
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+)
+
+func TestDeleteOrphanedObjects(t *testing.T) {
+	assert.NoError(t, PrepareTestDatabase())
+
```
Comment (zeripath) [inline models/consistency_test.go:15]: This test should add some orphaned objects.

Comment (6543) [reply models/consistency_test.go:15]: Yes just add an pull emtry with repo&issue id = 10000 and we should catch it

Comment (lunny) [reply models/consistency_test.go:15]: Since all tests shared the only one fixture directory, I don't think we should change the fixture to an inconsistent state. And also I cannot find any function to create an empty pull request into database.

Comment (6543) [reply models/consistency_test.go:15]: Well we have to exec custom sql. Simple "INSERT INTO x () VALUES(1000,1000);" so i do testing manualy too

**Comment by 6543** [comment]
@lunny 
```diff
diff --git a/models/consistency_test.go b/models/consistency_test.go
index d42906d9c..0a91d9f3d 100644
--- a/models/consistency_test.go
+++ b/models/consistency_test.go
@@ -13,6 +13,20 @@ import (
 func TestDeleteOrphanedObjects(t *testing.T) {
        assert.NoError(t, PrepareTestDatabase())
 
-       err := DeleteOrphanedObjects("pull_request", "issue", "pull_request.issue_id=issue.id")
+       countBefore, err := x.Count(&PullRequest{})
        assert.NoError(t, err)
+
+       _, err = x.Insert(&PullRequest{IssueID: 1000}, &PullRequest{IssueID: 1001}, &PullRequest{IssueID: 1003})
+       assert.NoError(t, err)
+
+       orphaned, err := CountOrphanedObjects("pull_request", "issue", "pull_request.issue_id=issue.id")
+       assert.NoError(t, err)
+       assert.EqualValues(t, 3, orphaned)
+
+       err = DeleteOrphanedObjects("pull_request", "issue", "pull_request.issue_id=issue.id")
+       assert.NoError(t, err)
+
+       countAfter, err := x.Count(&PullRequest{})
+       assert.NoError(t, err)
+       assert.EqualValues(t, countBefore, countAfter)
 }
```

can i push this patch?

**Review by 6543 — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:

**Comment by 6543** [comment]
Backports:
 * #15682 <- in case someone like to run doctor before migrating
 * #15683
