### PR TITLE
Git LFS lock api

### LINKED ISSUE #2725: Git LFS File Locking API
- Gitea version (or commit ref): 1.2.0
- Git version: 2.11.0
- Operating system: Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: -

## Description

Hi, 

The [Git LFS File Locking API](https://github.com/git-lfs/git-lfs/blob/master/docs/api/locking.md) is currently not implemented in Gitea:

```
$ git lfs lock foo.bin
Lock failed: Repository or object not found: http://git.example.com/test/test.git/info/lfs/locks
Check that it exists and that you have proper access to it
```

I wonder if there is a plan to support it or even if someone is interested by it?

### PR DESCRIPTION
**Pull request by sapk**
Resolve #2725

### CODE REVIEW

**Comment by sapk** [comment]
It is ready for review.

File: models/lfs_lock.go [hunk 1]
```diff
@@ -0,0 +1,173 @@
+// Copyright 2014 The Gogs Authors. All rights reserved.
```
Comment (lunny) [inline models/lfs_lock.go]: ... 2017 The Gitea ... ?

File: models/lfs_lock.go [hunk 2]
```diff
@@ -0,0 +1,173 @@
...
+// Use of this source code is governed by a MIT-style
+// license that can be found in the LICENSE file.
+
+package models
+
+import (
+	api "code.gitea.io/sdk/gitea"
```
Comment (lunny) [inline models/lfs_lock.go]: wrong order

File: models/lfs_lock.go [hunk 3]
```diff
@@ -0,0 +1,173 @@
...
+	"fmt"
+	"strconv"
+	"time"
+)
+
+// LFSLock represents a git lfs lfock of repository.
```
Comment (lunny) [inline models/lfs_lock.go]: lfock -> lock

File: models/lfs_lock.go [hunk 4]
```diff
@@ -0,0 +1,173 @@
...
+type LFSLock struct {
+	ID          int64       `xorm:"pk autoincr"`
+	RepoID      int64       `xorm:"INDEX"`
+	Repo        *Repository `xorm:"-"`
+	OwnerID     int64       `xorm:"INDEX"`
+	Owner       *User       `xorm:"-"`
+	Path        string
+	Created     time.Time `xorm:"-"`
+	CreatedUnix int64     `xorm:"INDEX"`
```
Comment (lunny) [inline models/lfs_lock.go]: Use `created` is enough, then line 28 -> 30 and line 36 could be removed.

File: models/lfs_lock.go [hunk 5]
```diff
@@ -0,0 +1,173 @@
...
+		LockedAt: l.Created,
+		Owner: &api.LFSLockOwner{
+			Name: l.Owner.DisplayName(),
+		},
+	}
+}
+
+// IsLFSLockExist returns true if lock with given path already exists.
+func IsLFSLockExist(repoID int64, path string) (bool, error) {
+	return x.Get(&LFSLock{RepoID: repoID, Path: path}) //TODO Define if path should needed to be lower for windows compat ?
```
Comment (lunny) [inline models/lfs_lock.go]: maybe store a lower column?

File: models/lfs_lock.go [hunk 6]
```diff
@@ -0,0 +1,173 @@
...
+func CreateLFSLock(lock *LFSLock) (*LFSLock, error) {
+	err := CheckLFSAccessForRepo(lock.Owner, lock.RepoID, "create")
+	if err != nil {
+		return nil, err
+	}
+	isExist, err := IsLFSLockExist(lock.RepoID, lock.Path)
+	if err != nil {
+		return nil, err
+	} else if isExist {
+		l, err := GetLFSLock(lock.RepoID, lock.Path)
```
Comment (lunny) [inline models/lfs_lock.go]: `IsLFSLockExist` has been invoked on `GetLFSLock`.

File: models/lfs_lock.go [hunk 7]
```diff
@@ -0,0 +1,173 @@
...
+	} else if !has {
+		return nil, ErrLFSLockNotExist{id, 0, ""}
+	}
+	return lock, nil
+}
+
+// GetLFSLockByRepoID returns a list of locks of repository.
+func GetLFSLockByRepoID(repoID int64) (locks []*LFSLock, err error) {
+	err = x.Where("repo_id = ?", repoID).Find(&locks)
+	return locks, err
```
Comment (lunny) [inline models/lfs_lock.go]: `return`

**Review by lunny — CHANGES_REQUESTED** [review]

File: modules/lfs/locks.go [hunk 8]
```diff
@@ -0,0 +1,232 @@
+package lfs
```
Comment (sapk) [inline modules/lfs/locks.go]: Note to myself missing header.

File: models/lfs_lock.go (hunk 6 above)
Comment (sapk) [reply models/lfs_lock.go]: @lunny To be sure, I would better use directly GetLFSLock and check if `!IsErrLFSLockNotExist(err)` ?

File: models/lfs_lock.go (hunk 4 above)
Comment (sapk) [reply models/lfs_lock.go]: I base myself on other models like : https://github.com/go-gitea/gitea/blob/a8717e5e3ace4dd226547faae9c3a44616bbf6f0/models/issue_stopwatch.go#L24
After review more of those, I might be needed adding `xorm:"INDEX created"` on created like : 
https://github.com/go-gitea/gitea/blob/aa962deec037375a7cfae3b96094becdfe48e778/models/token.go#L23
After adding that, does I need ? https://github.com/go-gitea/gitea/blob/aa962deec037375a7cfae3b96094becdfe48e778/models/token.go#L32
I will totally follow you on xorm since you will know more about it and maybe (in another PR) we should clean other models with such pattern.

**Comment by sapk** [comment]
Rebase and implemented all fixes

File: models/lfs_lock.go [hunk 9]
```diff
@@ -0,0 +1,141 @@
...
+	api "code.gitea.io/sdk/gitea"
+)
+
+// LFSLock represents a git lfs lock of repository.
+type LFSLock struct {
+	ID      int64 `xorm:"pk autoincr"`
+	RepoID  int64 `xorm:"INDEX"`
+	Owner   *User `xorm:"-"`
+	OwnerID int64 `xorm:"INDEX"`
+	Path    string
```
Comment (lunny) [inline models/lfs_lock.go]: Path with `varchar(255)` if not xorm tag here. Is that enough length?

**Review by lunny — APPROVED** [review]

File: models/lfs_lock.go (hunk 9 above)
Comment (sapk) [reply models/lfs_lock.go]: Good catch. I switch to TEXT and add a corresponding test

Comment (lunny) [reply models/lfs_lock.go]: Maybe `xorm:"varchar(1024)"` or `xorm:"varchar(2048)"` is enough.

File: models/lfs_lock.go [hunk 10]
```diff
@@ -0,0 +1,141 @@
...
+	api "code.gitea.io/sdk/gitea"
+)
+
+// LFSLock represents a git lfs lock of repository.
+type LFSLock struct {
+	ID      int64     `xorm:"pk autoincr"`
+	RepoID  int64     `xorm:"INDEX"`
+	Owner   *User     `xorm:"-"`
+	OwnerID int64     `xorm:"INDEX"`
+	Path    string    `xorm:"TEXT"`
```
Comment (lunny) [inline models/lfs_lock.go]: And maybe `Path` should be unique with `RepoID` ?

Comment (sapk) [reply models/lfs_lock.go]: Yes and that make me think that I should also use filepath.Clean before adding a entry.

Comment (sapk) [reply models/lfs_lock.go]: Done + add not null constraint

Comment (sapk) [reply models/lfs_lock.go]: Revert back the uniqueness since mysql need a fixed size to index uniquess on field and path is a TEXT field. Uniqueness is preserve by code.

Comment (lunny) [reply models/lfs_lock.go]: `Path` could be `xorm:"varchar(1024)"`.

Comment (sapk) [reply models/lfs_lock.go]: after looking at it linux limits path length to 4096

**Comment by lunny** [comment]
LGTM

**Comment by lafriks** [comment]
@sapk please resolve vendor conflict

**Comment by sapk** [comment]
@lafriks done

**Comment by lafriks** [comment]
LGTM
