### PR TITLE
Fix an error while adding a dependency via UI.

### LINKED ISSUE #5783: Cannot add issue/pull dependencies
Reproducible at https://try.gitea.io (currently dbb4aee).

## Description

1. Create a repository.
2. Create two issues for your repository.
3. Open one issue and pick the other in the Dependencies select. Click the green plus.
4. The site reloads and there are still no dependencies.

### PR DESCRIPTION
**Pull request by HarshitOnGitHub**
We were not checking if the `Repo` attribute is loaded or not before using it.

image

Fixes: #5783.

### CODE REVIEW

File: models/issue_comment.go [hunk 1]
```diff
@@ -749,6 +749,9 @@ func createIssueDependencyComment(e *xorm.Session, doer *User, issue *Issue, dep
 	if !add {
 		cType = CommentTypeRemoveDependency
 	}
+	if err = issue.LoadRepo(); err != nil {
```
Comment (zeripath) [inline models/issue_comment.go]: You must load the repo from with the provided session `e`

**Review by zeripath — CHANGES_REQUESTED** [review]

File: models/issue_comment.go (hunk 1 above)
Comment (zeripath) [reply models/issue_comment.go]: To be more explicit, when there is an open transaction you **MUST** use the provided `*xorm.Session` to do database lookups.

This line should read:

```go
     if err = issue.loadRepo(e); err != nil {
```

If you don't do this you will cause deadlocks.

**Review by zeripath — APPROVED** [review]

**Review by kolaente — APPROVED** [review]

File: models/issue_comment.go (hunk 1 above)
Comment (zeripath) [reply models/issue_comment.go]: No problems. It was caught. That's the point of the review system. I've added bugs myself - see the debacle about the last migration. (Although I've more than suffered trying to create migration tests as my penance.)

Thanks for updating the tests too. I think they're due a rationalisation - we probably need to make the integration tests more story like - create repos, fix issues, upload stuff etc. At present they're more of a hodgepodge of almost unit tests which take too long to complete.

**Comment by HarshitOnGitHub** [comment]
@lunny Done.

**Comment by adelowo** [comment]
@zeripath Can you add `backport/done` label
