### PR TITLE
Merge setting.InitXXX into one function with options

### LINKED ISSUE #12082: embedded subcommand not working in Linux
- Gitea version (or commit ref): 1.12.1 (till latest)

## Description

The embedded subcommand does not work list or extract any files. 

## Screenshots

```
bash-5.0# gitea -v
Gitea version 1.12.1 built with GNU Make 4.2.1, go1.14.4 : bindata, sqlite, sqlite_unlock_notify
bash-5.0# gitea embedded list '**'
bash-5.0#
```

## Reason

Gitea `embedded` can not run with mismatched Linux user in an installed config, there will be no output at all.

## Workaround

Run gitea with the correct Linux user (as in the `app.ini`), using `su` or `sudo`

### PR DESCRIPTION
**Pull request by lunny**
This PR will merge 3 Init functions on setting packages as 1 and introduce an options struct.

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Comment by wxiaoguang** [comment]
It doesn't fully fix #12082

The root problem of #12082 is: the buggy logger system. If the "console" is removed incorrectly, other fatal errors will still make users see nothing.

File: modules/setting/setting.go [hunk 1]
```diff
@@ -136,7 +136,7 @@ func forcePathSeparator(path string) {
 // This check is ignored under Windows since SSH remote login is not the main
 // method to login on Windows.
 func IsRunUserMatchCurrentUser(runUser string) (string, bool) {
-	if IsWindows || SSH.StartBuiltinServer {
+	if IsWindows || SSH.StartBuiltinServer || ignoreCheckRunUser {
```
Comment (wxiaoguang) [inline modules/setting/setting.go]: I do not think it is right to add this check here.

Instead, the callers should decide whether to call "IsRunUserMatchCurrentUser"

**Comment by lunny** [comment]
Yes, I'm thinking that every sub-command should have its own log context. Except for `ssh`/`hooks` related subcommands and the `web` subcommand, other sub commands should not log info into files, just output console is enough.

**Review by KN4CK3R — COMMENTED** [review]
`setting.LoadCommonSettings()` gets called multiple times now because it gets called in `Init` already.

**Comment by lunny** [comment]
> `setting.LoadCommonSettings()` gets called multiple times now because it gets called in `Init` already.

I don't think so.

**Comment by lunny** [comment]
> 

But you remind me, looks like it's unnecessary to have a second invoke to `LoadCommonSettingsFrom`.

**Comment by KN4CK3R** [comment]
[055b9ec](https://github.com/go-gitea/gitea/pull/24389/commits/055b9ec7bdf53c0e7e8a4dc60531319638ef4b73) was exactly what I talked about. 😏

File: modules/setting/config_provider.go [hunk 2]
```diff
@@ -66,41 +65,49 @@ func newConfigProviderFromData(configContent string) (ConfigProvider, error) {
...
-	if extraConfig != "" {
-		if err := cfg.Append([]byte(extraConfig)); err != nil {
+	if opts.ExtraConfig != "" {
+		if err := cfg.Append([]byte(opts.ExtraConfig)); err != nil {
 			return nil, fmt.Errorf("unable to append more config: %v", err)
 		}
 	}
 
 	cfg.NameMapper = ini.SnackCase
+	ignoreCheckRunUser = opts.IgnoreCheckRunUser
```
Comment (wxiaoguang) [inline modules/setting/config_provider.go]: It seems still fragile. I would suggest do not do so.

Refactor the logger system instead of patching it.

Comment (lunny) [reply modules/setting/config_provider.go]: Done.

**Review by wxiaoguang — APPROVED** [review]
