### PR TITLE
Fix package webhook

### LINKED ISSUE #23742: Empty notice on Matrix
### Description

Pushing packages causes a notification to be sent via Matrix (as it should), but the notification is empty. Here's the output from devtools:

```json
{
  "type": "m.room.message",
  "sender": "@gitea:domain.tld",
  "content": {
    "body": "",
    "msgtype": "m.notice",
    "format": "",
    "formatted_body": ""
  },
  "event_id": "$16799077162395uSyzy:domain.tld",
  "origin_server_ts": 1679907716675,
  "unsigned": {
    "age": 113167
  },
  "room_id": "!AlQEYiOnameiBnPOIj:domain.tld"
}
```

Other notifications (PR, Issues, ...) work fine.

### Gitea Version

1.18.5

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by lunny**
Fix #23742

### CODE REVIEW

File: services/convert/package.go [hunk 1]
```diff
@@ -35,6 +38,7 @@ func ToPackage(ctx context.Context, pd *packages.PackageDescriptor, doer *user_m
 		Name:       pd.Package.Name,
 		Version:    pd.Version.Version,
 		CreatedAt:  pd.Version.CreatedUnix.AsTime(),
+		HTMLURL:    fmt.Sprintf("%s%s/-/packages/%s/%s", setting.AppURL, pd.Owner.LoginName, string(pd.Package.Type), url.PathEscape(pd.Version.Version)),
```
Comment (KN4CK3R) [inline services/convert/package.go]:
```suggestion
		HTMLURL:    pd.FullWebLink(),
```

**Review by KN4CK3R — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by niklaskorz** [comment]
Unfortunately this PR broke Gitea for us as the call to `p.Repository` inside `func (m *MatrixPayload) Package(p *api.PackagePayload) (api.Payloader, error)` (`services/webhook/matrix.go:239`) results in a nil pointer dereference. Looks like `p.Repository` is not set when triggered from `UploadManifest`. Stack trace (Gitea 1.21):

```
/source/services/webhook/matrix.go:215 (0x23cf774)
/source/services/webhook/payloader.go:58 (0x23dae5d)
/source/services/webhook/matrix.go:239 (0x23cfac4)
/source/services/webhook/webhook.go:198 (0x23dfc6b)
/source/services/webhook/webhook.go:261 (0x23e0435)
/source/services/webhook/notifier.go:882 (0x23da6d0)
/source/services/webhook/notifier.go:863 (0x23da495)
/source/services/notify/notify.go:353 (0x2306326)
/source/routers/api/packages/container/manifest.go:309 (0x23062da)
/source/routers/api/packages/container/manifest.go:184 (0x2305364)
/source/routers/api/packages/container/manifest.go:191 (0x230483c)
/source/routers/api/packages/container/manifest.go:75 (0x2304724)
/source/routers/api/packages/container/container.go:546 (0x2301bec)
```

**Comment by KN4CK3R** [comment]
Thank you for the info. Same error was in the MS Teams webhook.
https://github.com/go-gitea/gitea/pull/28089
