### PR TITLE
Fix CSV render error

### LINKED ISSUE #17378: Editing CSV after 2048 chars results in "Can't render this file because it has a wrong number of fields" error
### Gitea Version

35b918f574464eeca89fcf0d5f3a07a58a4b5a38

### Git Version

v1.17.2

### Operating System

MacOS ARM1

### How are you running Gitea?

Gitea developer, so running a build of the main branch on my local system.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Description

If you have a CSV file with more than 2048 characters (bytes), and then edit a line past 2048 characters (bytes), you get this error (line is based on whatever line the 2048th character falls on):

```
Can't render this file because it has a wrong number of fields in line 30.
```

Screenshot:

image

URL: https://try.gitea.io/richmahn/test/commit/ce02bb6107c8d7ba1b8a8d30335658a84e4c9c50

Yet the regular diff view shows no columns were changed, and both the [parent commit](https://try.gitea.io/richmahn/test/src/commit/44d026d24ff571be9de86a90015dae07e02dbc29/names.csv) and [new commit](https://try.gitea.io/richmahn/test/src/commit/ce02bb6107c8d7ba1b8a8d30335658a84e4c9c50/names.csv) render as CSV tables:

image

Actually, when you even create a CSV file with more than 2048 characters, the diff of the new file even gives you this error, because the code is only rendering/diffing the first 2048 bytes, and thus if the 2048th byte mark cuts off other fields in that row, that row, 30 in this case, is seen as having the wrong number of columns. See: https://try.gitea.io/richmahn/test/commit/44d026d24ff571be9de86a90015dae07e02dbc29 (both diff and CSV table)

### Screenshots

image

image

### PR DESCRIPTION
**Pull request by KN4CK3R**
closed #17378 

Both errors from #17378 were caused by  #15175.

Problem 1 (error with added file):
`ToUTF8WithFallbackReader` creates a `MultiReader` from a `byte[2048]` and the remaining reader. `CreateReaderAndGuessDelimiter` tries to read 10000 bytes from this reader but only gets 2048 because that's the first reader in the `MultiReader`. Then the `if size < 1e4` thinks the input is at EOF and just returns that.

Problem 2 (error with changed file):
The blob reader gets defer closed. That was fine because the old version reads the whole file into memory. Now with the streaming version the close needs to defer after the method.

### CODE REVIEW

File: modules/csv/csv.go [hunk 1]
```diff
@@ -27,35 +27,27 @@ func CreateReader(input io.Reader, delimiter rune) *stdcsv.Reader {
 }
 
 // CreateReaderAndGuessDelimiter tries to guess the field delimiter from the content and creates a csv.Reader.
+// Reads at most 10k bytes.
 func CreateReaderAndGuessDelimiter(rd io.Reader) (*stdcsv.Reader, error) {
-	var data = make([]byte, 1e4)
-	size, err := rd.Read(data)
+	var buf = make([]byte, 1e4)
+	n, err := rd.Read(buf)
```
Comment (zeripath) [inline modules/csv/csv.go]: Are you trying to fill that buffer if you at all can? There's no guarantee even if the size is 16Mb that the buffer will contain more than one byte. You need to use `ReadAtLeast` or `ReadFull`.

Comment (KN4CK3R) [reply modules/csv/csv.go]: Will add this in a follow up PR because that needs to be fixed in more places like LFS pointer detection.

**Review by 6543 — APPROVED** [review]

**Review by richmahn — APPROVED** [review]

File: modules/csv/csv.go [hunk 2]
```diff
@@ -27,32 +27,24 @@ func CreateReader(input io.Reader, delimiter rune) *stdcsv.Reader {
...
-		newInput = bytes.NewReader(data[:size])
-	} else {
-		newInput = io.MultiReader(bytes.NewReader(data), rd)
-	}
-
-	return CreateReader(newInput, delimiter), nil
+	return CreateReader(
+		io.MultiReader(bytes.NewReader(buf[:n]), rd),
+		guessDelimiter(buf[:n]),
+	), nil
```
Comment (6543) [inline modules/csv/csv.go]:
```suggestion
	return CreateReader(
		io.MultiReader(bytes.NewReader(data[:n]), rd),
		guessDelimiter(data[:n]),
	), nil
```

**Review by 6543 — APPROVED** [review]

File: modules/csv/csv.go [hunk 3]
```diff
@@ -27,32 +27,24 @@ func CreateReader(input io.Reader, delimiter rune) *stdcsv.Reader {
...
-		newInput = bytes.NewReader(data[:size])
-	} else {
-		newInput = io.MultiReader(bytes.NewReader(data), rd)
-	}
-
-	return CreateReader(newInput, delimiter), nil
+	return CreateReader(
+		io.MultiReader(bytes.NewReader(data[:n]), rd),
+		guessDelimiter(data[:n]),
+	), nil
```
Comment (6543) [inline modules/csv/csv.go]:
```suggestion
	return CreateReader(
		io.MultiReader(bytes.NewReader(data[:size]), rd),
		guessDelimiter(data[:size]),
	), nil
```

**Review by 6543 — APPROVED** [review]
2nd
