### PR TITLE
Fix TestSearchRepo by waiting till indexing is done

### LINKED ISSUE #6977: TestSearchRepos is broken
- Gitea version (or commit ref):1.9.0+dev-262-g96b412bb8

## Description

`TAGS="bindata sqlite sqlite_unlock_notify" make build test-sqlite\#TestSearchRepo` fails

### PR DESCRIPTION
**Pull request by zeripath**
Fixes #6977 by force waiting till the repository has finished updating the index.

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

File: integrations/repo_search_test.go [hunk 1]
```diff
@@ -27,6 +31,23 @@ func resultFilenames(t testing.TB, doc *HTMLDoc) []string {
...
+	repo, err := models.GetRepositoryByOwnerAndName("user2", "repo1")
+	assert.NoError(t, err)
+
+	models.UpdateRepoIndexer(repo)
+
+	log.Printf("Waiting for indexing\n")
+
+	i := 0
+	for {
+		if repo.IndexerStatus != nil && len(repo.IndexerStatus.CommitSha) != 0 && i <= 60 {
```
Comment (mrsdizzie) [inline integrations/repo_search_test.go]: What happens if this takes more than 60 seconds? wouldn't it get stuck in an infinite loop?

Comment (zeripath) [reply integrations/repo_search_test.go]:
```suggestion
		if (repo.IndexerStatus != nil && len(repo.IndexerStatus.CommitSha) != 0) || i > 60 {
```

Oh dear what was wrong with me!

Comment (zeripath) [reply integrations/repo_search_test.go]: Go test would have timed out with a failure but still...

File: integrations/repo_search_test.go [hunk 2]
```diff
@@ -27,6 +31,23 @@ func resultFilenames(t testing.TB, doc *HTMLDoc) []string {
...
 
+	repo, err := models.GetRepositoryByOwnerAndName("user2", "repo1")
+	assert.NoError(t, err)
+
+	models.UpdateRepoIndexer(repo)
+
+	log.Printf("Waiting for indexing\n")
+
+	i := 0
+	for {
```
Comment (mrsdizzie) [inline integrations/repo_search_test.go]:
```suggestion
	for i < 60 {
	if (repo.IndexerStatus != nil && len(repo.IndexerStatus.CommitSha) != 0) {
```
Might be a bit more readable, but thats just a small nit.

File: integrations/repo_search_test.go [hunk 3]
```diff
@@ -27,6 +31,23 @@ func resultFilenames(t testing.TB, doc *HTMLDoc) []string {
...
+		if (repo.IndexerStatus != nil && len(repo.IndexerStatus.CommitSha) != 0) || i > 60 {
+			break
+		}
+		time.Sleep(1 * time.Second)
+		i++
+	}
+	log.Printf("Indexing took: %d s\n", i)
```
Comment (mrsdizzie) [inline integrations/repo_search_test.go]: What happens if the indexing didn't finish after 60 seconds? Should this check to see if it finished and fail with a message if not?

Comment (zeripath) [reply integrations/repo_search_test.go]: I'm not sure that's much we can really infer much about indexing - the API is very minimal - if anything inferring that the indexing has finished by checking IndexerStatus,CommitSha is non-zero is probably assuming too much. Yes it appears to work and looking at the source code that appears the only way to check but I don't think we can say much more than that.

If after 60s the IndexerStatus.CommitSha hasn't been set then maybe the "API" of indexer has changed? At present this test would just check and hopefully pass - probably taking too long to do so. If however, you enforce that the IndexerStatus has to be set then we're now forcing an API - one which I would not design this way. I guess it depends on how much you want to enforce an API on UpdateRepoIndexer.

Comment (mrsdizzie) [reply integrations/repo_search_test.go]: Sure, that all makes sense and I wouldn't want to make any big changes or block this fix -- just to avoid confusion by saying it has finished if really we just hit the time limit. Maybe just:

```
if i < 60 {
log.Printf("Indexing took: %d s\n", i)
}  else {
log.Printf("Waited the limit: %d s for indexing, continuing\n", i)
}
```
Which keeps the current assumptions from the loop but specifies if we think it finished vs it reached the time limit (since reaching the time limit is probably the only thing we would know for sure here)

**Review by mrsdizzie — APPROVED** [review]
