### PR TITLE
Fix migrate storage bug

### LINKED ISSUE #28728: Error migrating repo-avatars to minio
### Description

I am testing the process of moving from local storage to AWS S3.  I did this on a test machine:

```sh
for DATATYPE in attachments lfs avatars repo-avatars repo-archive packages actions_log actions_artifacts; do
    echo DATATYPE=$DATATYPE;
    gitea migrate-storage \
        --type=$DATATYPE \
        --minio-base-path=$DATATYPE \
        --storage=minio \
        --minio-endpoint=s3.us-east-1.amazonaws.com \
        --minio-access-key-id=xxxx \
        --minio-secret-access-key=yyyy \
        --minio-bucket=my-gitea \
        --minio-location=us-east-1 \
        --minio-use-ssl=true
done
```

This mostly worked.  I am ignoring the "unsupported storage" errors for things that do not support minio... that's fair.

The problem is `repo-avatars`.  Normal avatars migrated fine (and so did attachments and lfs), but repo-avatars gave me this error:

```
2024/01/08 09:03:35 ...les/storage/minio.go:86:NewMinioStorage() [I] Creating Minio storage at s3.us-east-1.amazonaws.com:my-gitea with base path repo-avatars
Command error: Put "https://my-gitea.s3.dualstack.us-east-1.amazonaws.com/repo-avatars": read /data/gitea/repo-avatars: is a directory
```

Yes, it's a directory, but that shouldn't be a problem.  Right?

Config:

```toml
[picture]
ENABLE_FEDERATED_AVATAR = false
AVATAR_UPLOAD_PATH            = /data/gitea/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars
```

The error message refers to the current storage path on the local disk, so here's what those folders look like:
```
gitea:/$ ls -ld /data/gitea/avatars /data/gitea/repo-avatars
drwxr-xr-x    3 git      git           4096 Nov 28 22:49 /data/gitea/avatars
drwxr-xr-x    3 git      git           4096 Apr 28  2023 /data/gitea/repo-avatars
```

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/Infinoid/7bd96c126ad1245b013940de6fac118d

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

using official docker image with tag `1.21`

### Database

SQLite

### PR DESCRIPTION
**Pull request by lunny**
Fix #28728

### CODE REVIEW

File: cmd/migrate_storage.go [hunk 1]
```diff
@@ -110,13 +110,19 @@ func migrateLFS(ctx context.Context, dstStorage storage.ObjectStorage) error {
...
+			return nil
+		}
 		_, err := storage.Copy(dstStorage, user.CustomAvatarRelativePath(), storage.Avatars, user.CustomAvatarRelativePath())
 		return err
 	})
 }
 
 func migrateRepoAvatars(ctx context.Context, dstStorage storage.ObjectStorage) error {
 	return db.Iterate(ctx, nil, func(ctx context.Context, repo *repo_model.Repository) error {
+		if repo.CustomAvatarRelativePath() == "" {
```
Comment (delvh) [inline cmd/migrate_storage.go:123]: If we add it here for `repo`, don't we also need it for any other of these other `migrate-` functions?

Comment (lunny) [reply cmd/migrate_storage.go:123]: Other functions will iterate the table the value should not be null of empty. But for user and repo, avatar is optional.

**Review by delvh — APPROVED** [review]

**Review by denyskon — APPROVED** [review]
