### PR TITLE
Fix git commit committer parsing and add some tests

### LINKED ISSUE #34882: Avatars not visible in commit view when no-reply address is configured to the real domain
### Description

This is basically the same problem as being reported by https://github.com/go-gitea/gitea/issues/33595

There are two observations:

- The icons (custom ones) are not correctly displayed - nearly all of them show the "default" one. This happens in the commit view in the "Code" tab of a repo, as well as in the commit view of any Pull request.
- The link behind the commit author is broken and will lead to a 404 page.

In our setup we use ldap for authentication. The gitea usernames are `lastname`, while the email addresses are `firstname.lastname@company.bla`.
The link created for a user will be `http://gitea:3000/firstname lastname` - which does not exist. Instead it should be `http://gitea:3000/lastname`.

In some cases this link creation works - if the user misconfigured his git email address to `lastname@company.bla` instead of `firstname.lastname@company.bla`.

### Gitea Version

1.24.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

Image

### Git Version

2.49.0

### Operating System

Ubuntu 22.04

### How are you running Gitea?

Gitea 1.24.2 via docker compose with SQLite database

### Database

SQLite

### LINKED ISSUE #34991: Commit list author rendering regression in v1.24+
### Description

In 1.24.2 and on main branch, I notice two bugs in the commit list author rendering. In the latest commit rendering, everything works as expected.

1. Author is not associated to local user via commit e-mail address despite e-mail address matching
2. The author link renders invalid hrefs which leads to the 404 page:

```html
<a class="muted author-wrapper" href="/Firstname%20Lastname">Firstname Lastname</a>
```

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

no

### How are you running Gitea?

natively

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by lunny**
* Fix #34991
* Fix #34882

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Need to double check another similar change:

image

**Comment by lunny** [comment]
> #34991

I can confirm the `.User` haven't been override from `ParseCommitsWithSignature`. This function will assign a new variable to `Verification` but not `UserCommit`.

**Comment by wxiaoguang** [comment]
> > #34991
> 
> I can confirm the `.User` haven't been override from `ParseCommitsWithSignature`. This function will assign a new variable to `Verification` but not `UserCommit`.

But why it needs a "fake" commiter user?

**Comment by lunny** [comment]
> > > #34991
> > 
> > 
> > I can confirm the `.User` haven't been override from `ParseCommitsWithSignature`. This function will assign a new variable to `Verification` but not `UserCommit`.
> 
> But why it needs a "fake" commiter user?

The field `UserCommit` should be renamed to `AuthorCommit` and the fake user in `ParseCommitsWithSignature` is the committer. The avatar on the UI is author and the committer will be displayed with the git hash if it's signed.

**Comment by wxiaoguang** [comment]
I know the old names are unclear.

My question is: does the old code prepare that "fake" gitea user? why your new code make a "fake" gitea user?

**Comment by lunny** [comment]
> I know the old names are unclear.
> 
> My question is: does the old code prepare that "fake" gitea user? why your new code make a "fake" gitea user?

#33528 doesn't introduce that fake user in signature committer function. It just extracted the fake user logic from `ParseCommitWithSignature`.
image

**Review by wxiaoguang — COMMENTED** [review]
Done from my side

File: services/asymkey/commit.go [hunk 1]
```diff
@@ -24,47 +24,43 @@ import (
...
-			}
+	committer, err := user_model.GetUserByEmail(ctx, c.Committer.Email)
+	if err != nil && !user_model.IsErrUserNotExist(err) {
+		log.Error("GetUserByEmail: %v", err)
+		return &asymkey_model.CommitVerification{
+			Verified: false,
+			Reason:   "gpg.error.no_committer_account", // this error is not right, but such error should seldom happen
 		}
 	}
-
```
Comment (lafriks) [inline services/asymkey/commit.go:49]: For readability it's better to have an empty line before return

Comment (wxiaoguang) [reply services/asymkey/commit.go:49]: If you open it in IDE, the new code's readability is pretty good

Image

**Comment by silverwind** [comment]
I tested this branch, it seems to fully both issues from https://github.com/go-gitea/gitea/issues/34991. We should definitely backport this to 1.24.

File: models/asymkey/gpg_key_commit_verification.go [hunk 2]
```diff
@@ -15,34 +15,15 @@ import (
...
-// \     \___(  <_> )  Y Y  \  Y Y  \  ||  |
-//  \______  /\____/|__|_|  /__|_|  /__||__|
-//         \/             \/      \/
-// ____   ____           .__  _____.__               __  .__
-// \   \ /   /___________|__|/ ____\__| ____ _____ _/  |_|__| ____   ____
-//  \   Y   // __ \_  __ \  \   __\|  |/ ___\\__  \\   __\  |/  _ \ /    \
-//   \     /\  ___/|  | \/  ||  |  |  \  \___ / __ \|  | |  (  <_> )   |  \
-//    \___/  \___  >__|  |__||__|  |__|\___  >____  /__| |__|\____/|___|  /
-//               \/                        \/     \/                    \/
-
```
Comment (silverwind) [inline models/asymkey/gpg_key_commit_verification.go:36]: Maybe we should remove all ascii art in a separate PR later to avoid this noise.

**Review by silverwind — APPROVED** [review]
LGMT from functional perspective.

**Comment by wxiaoguang** [comment]
> I tested this branch, it seems to fully both issues from #34991. We should definitely backport this to 1.24.

I still think it's too risky to backport.

And since the fix is quite large, I would suggest either use a quick patch for 1.24 (only check ID!=0), or just don't backport.

I guess end users could bear it, not a serious bug in most cases, just a 404 page. We can release 1.25 soon if we'd like to land more fixes, actually 1.25 contains many important fixes including the container bug, which can't be backported to 1.24

----

If most people agree to backport, I won't block.

**Comment by silverwind** [comment]
The more serious issue is the missing email-to-user association (for which I have no steps to reproduce, but it happens everywhere in my instance), which seems to be fixed by this PR as well. Maybe we can just backport that part?

**Comment by wxiaoguang** [comment]
> The more serious issue is the missing email-to-user association (for which I have no steps to reproduce, but it happens everywhere in my instance)

Have you check your "noreply address"? That fix is simple, just `models/user/user.go`: https://github.com/go-gitea/gitea/pull/35007/commits/53146a8ca7092c98dda2cfad4b18c3d6479c837a#diff-dacacda4403790aa4e9b4473c62b3af81b9c0a05d795dd31bd936866e26cfb13

**Comment by silverwind** [comment]
> > The more serious issue is the missing email-to-user association (for which I have no steps to reproduce, but it happens everywhere in my instance)
> 
> Have you check your "noreply address"? That fix is simple, just `models/user/user.go`: [53146a8#diff-dacacda4403790aa4e9b4473c62b3af81b9c0a05d795dd31bd936866e26cfb13](https://github.com/go-gitea/gitea/commit/53146a8ca7092c98dda2cfad4b18c3d6479c837a#diff-dacacda4403790aa4e9b4473c62b3af81b9c0a05d795dd31bd936866e26cfb13)

Hmm no that can't be it. My NoReplyAddress resolves to like `noreply.git.foo.com` but my email address from the commit is on a different TLD entirely, like `user@bar.com`. My user currently has multiple email addresses configured, maybe that is part of the problem.

File: models/user/user.go [hunk 3]
```diff
@@ -1195,12 +1189,14 @@ func GetUsersByEmails(ctx context.Context, emails []string) (*EmailUserMap, erro
...
 	needCheckUserNames := make(container.Set[string])
+	noReplyAddressSuffix := "@" + strings.ToLower(setting.Service.NoReplyAddress)
 	for _, email := range emails {
-		if strings.HasSuffix(email, "@"+setting.Service.NoReplyAddress) {
-			username := strings.TrimSuffix(email, "@"+setting.Service.NoReplyAddress)
-			needCheckUserNames.Add(strings.ToLower(username))
+		emailLower := strings.ToLower(email)
+		if noReplyUserNameLower, ok := strings.CutSuffix(emailLower, noReplyAddressSuffix); ok {
+			needCheckUserNames.Add(noReplyUserNameLower)
+			needCheckEmails.Add(emailLower)
```
Comment (lunny) [inline models/user/user.go:1197]: Why the logic changed?

Comment (wxiaoguang) [reply models/user/user.go:1197]: image

Comment (wxiaoguang) [reply models/user/user.go:1197]: image

File: services/asymkey/commit.go (hunk 1 above)
Comment (lafriks) [reply services/asymkey/commit.go:49]: I'm not blocking, just an opinion

**Review by hiifong — APPROVED** [review]

**Comment by silverwind** [comment]
> > > The more serious issue is the missing email-to-user association (for which I have no steps to reproduce, but it happens everywhere in my instance)
> > 
> > 
> > Have you check your "noreply address"? That fix is simple, just `models/user/user.go`: [53146a8#diff-dacacda4403790aa4e9b4473c62b3af81b9c0a05d795dd31bd936866e26cfb13](https://github.com/go-gitea/gitea/commit/53146a8ca7092c98dda2cfad4b18c3d6479c837a#diff-dacacda4403790aa4e9b4473c62b3af81b9c0a05d795dd31bd936866e26cfb13)
> 
> Hmm no that can't be it. My NoReplyAddress resolves to like `noreply.git.foo.com` but my email address from the commit is on a different TLD entirely, like `user@bar.com`. My user currently has multiple email addresses configured, maybe that is part of the problem.

Actually I found the issue. In configuration I had `service.NO_REPLY_ADDRESS=bar.com` which is incorrect and should have been `noreply.bar.com`. Changing it to that value fixed the committer association.

**Comment by wxiaoguang** [comment]
> > > > The more serious issue is the missing email-to-user association (for which I have no steps to reproduce, but it happens everywhere in my instance)
> > > 
> > > 
> > > Have you check your "noreply address"? That fix is simple, just `models/user/user.go`: [53146a8#diff-dacacda4403790aa4e9b4473c62b3af81b9c0a05d795dd31bd936866e26cfb13](https://github.com/go-gitea/gitea/commit/53146a8ca7092c98dda2cfad4b18c3d6479c837a#diff-dacacda4403790aa4e9b4473c62b3af81b9c0a05d795dd31bd936866e26cfb13)
> > 
> > 
> > Hmm no that can't be it. My NoReplyAddress resolves to like `noreply.git.foo.com` but my email address from the commit is on a different TLD entirely, like `user@bar.com`. My user currently has multiple email addresses configured, maybe that is part of the problem.
> 
> Actually I found the issue. In configuration I had `service.NO_REPLY_ADDRESS=bar.com` which is incorrect and should have been `noreply.bar.com`. Changing it to that value fixed the committer association.

Yep, this is my fourth time to fix the regressions from #33528, so I am pretty sure it is the cause.

I think I also know why your "noreply address" is incorrect, I guess in old days, Gitea used the DOMAIN as noreply address, then it caused problem, then the behavior was changed (a prefix as added). BUT, in old Gitea, Gitea also had another wrong behavior: it wrote garbage config options into the config file (I also fixed that), so very old users might be affected by incorrect config options.

**Comment by silverwind** [comment]
Yeah it's possible that the incorrect value came from that incorrect config rewrite. In any case, I'm glad we figured it out.

**Comment by silverwind** [comment]
@wxiaoguang is this good to merge from your side?

**Comment by wxiaoguang** [comment]
The code written by me surely looks good to me. So I asked other maintainers to review.
