### PR TITLE
fix: generate IDs for HTML headings without id attribute

### LINKED ISSUE #27383: wrong permalink to html heading in markdown file
### Description

in a markdown file, put the html heading

```
<h1>Heading without ID</h1>
```

then gitea blob API will generate the wrong permalink `#` for that heading.
github blob API would generate the permalink `#heading-without-id`

if the html heading has an id
gitea blob API renders the correct permalink `#heading-with-id` 

```
<h1 id="heading-with-id">Heading with ID</h1>
```

compare:

- https://github.com/milahu/gitea-html-in-markdown-render-bug
- https://codeberg.org/milahu/gitea-html-in-markdown-render-bug

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

im using some gitea instances, i dont know how they are running gitea...

### Database

None

### PR DESCRIPTION
**Pull request by bimakw**
## Summary

This PR fixes #27383 where HTML headings like `<h1>Title</h1>` in markdown files would have empty permalink anchors (showing just `#` in the URL).

**Before:**
- `<h1>Heading without ID</h1>` → permalink shows `#` (empty)

**After:**
- `<h1>Heading without ID</h1>` → permalink shows `#heading-without-id`

## Problem

When users write HTML headings in markdown without an `id` attribute, the frontend's `anchors.ts` generates permalink links using `heading.id`. If the heading has no `id`, the link becomes just `#`, which is not useful.

GitHub handles this by auto-generating IDs for HTML headings based on their text content, matching the behavior of Markdown headings.

## Solution

Modified `processNodeAttrID` in `modules/markup/html_node.go` to:
1. Detect heading tags (h1-h6) without an `id` attribute
2. Extract the text content from the heading (including nested elements)
3. Generate an ID using the same `CleanValue` function used for Markdown headings
4. Apply the `user-content-` prefix as expected by the frontend

This ensures consistent behavior between:
- Markdown headings: `## Title` → `id="user-content-title"`
- HTML headings: `<h1>Title</h1>` → `id="user-content-title"`

## Testing

Added test cases in `modules/markup/html_node_test.go` covering:
- HTML headings without id (h1, h2, h3)
- HTML headings with existing id (should preserve and prefix)
- HTML headings with user-content prefix (should not double prefix)
- Headings with special characters
- Headings with nested elements (bold, italic)
- Non-heading elements (should not get id)

All existing tests continue to pass.

Fixes #27383

### CODE REVIEW

File: modules/markup/html_node_test.go [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+		{
+			name:     "non-heading element should not get id",
+			input:    `<p>Just a paragraph</p>`,
+			expected: `<p>Just a paragraph</p>`,
+		},
+		{
+			name:     "div should not get id",
+			input:    `<div>A div element</div>`,
+			expected: `<div>A div element</div>`,
+		},
```
Comment (wxiaoguang) [inline modules/markup/html_node_test.go]: These tests can be removed, I think we don't need to test them, these tags appear a lot in other tests

File: modules/markup/html_node_test.go [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+		t.Run(tc.name, func(t *testing.T) {
+			var result strings.Builder
+			err := PostProcessDefault(NewTestRenderContext(), strings.NewReader(tc.input), &result)
+			assert.NoError(t, err)
+			assert.Equal(t, tc.expected, strings.TrimSpace(result.String()))
+		})
+	}
+}
+
+func TestIsHeadingTag(t *testing.T) {
```
Comment (wxiaoguang) [inline modules/markup/html_node_test.go]: This test can also be removed.

**Review by wxiaoguang — APPROVED** [review]

**Comment by silverwind** [comment]
One difference from GitHub's implementation is that this `id` generation is [not performed in issue comments](https://github.com/silverwind/symlink-test/issues/17#issuecomment-3687840923), but is performed on Gitea.

I think the reason for this is because in issue comments you have multiple markdown documents on one page, so the generated IDs may not be unique any more. So ideally we should disable this generation mechanism on pages where there can be more than one markdown document.

**Comment by bimakw** [comment]
good point! baru sadar juga kalo di issue comments bisa duplicate ID karena multiple markdown docs di satu page. mau saya tambahin logic buat skip generation di context issue comments? atau prefer bikin follow-up PR aja?

**Comment by wxiaoguang** [comment]
See this

image

**Comment by bimakw** [comment]
@wxiaoguang got it, jadi perlu skip ID generation untuk issue comments ya. mau saya fix di PR ini atau prefer follow-up PR terpisah?

**Comment by wxiaoguang** [comment]
Please speak in English

**Comment by bimakw** [comment]
@wxiaoguang got it, I need to skip ID generation for issue comments. Should I fix it in this PR or would you prefer a separate follow-up PR?

**Comment by wxiaoguang** [comment]
It should be an easy fix in this PR, see https://github.com/go-gitea/gitea/pull/36233#issuecomment-3688963883

**Comment by bimakw** [comment]
@wxiaoguang Fixed. Now skipping heading ID generation for issue comments (when markupAllowShortIssuePattern is true). Added tests to verify the behavior.

**Comment by wxiaoguang** [comment]
Please don't use `markupAllowShortIssuePattern`, it is an abuse.

You need a clearly defined option to control the new behavior. (no need to add a configurable option, you can hard-code it for wiki and file)

**Comment by bimakw** [comment]
Thanks for the feedback! I've refactored the implementation to use a dedicated `EnableHeadingIDGeneration` option instead of abusing `markupAllowShortIssuePattern`.

Changes:
- Added `EnableHeadingIDGeneration` field to `RenderOptions`
- Added `WithEnableHeadingIDGeneration()` builder method to `RenderContext`
- Enabled it explicitly in `repo_file.go` and `repo_wiki.go`
- Updated tests to use the new explicit option

This makes the option clearly defined and hard-coded for file and wiki pages as requested.

**Comment by wxiaoguang** [comment]
@go-gitea/maintainers

**Review by delvh — APPROVED** [review]
