### PR TITLE
Branch protection: Possibility to not use whitelist but allow anyone with write access

### LINKED ISSUE #5731: about git push -f
Wishing to increase the authority to control compulsory push restrictions

### LINKED ISSUE #8208: push commits after upgrade from 1.8.3 to 1.9.3 errors happen
- Gitea version (or commit ref): 1.9.3
- Git version: 2.7
- Operating system: ubuntu 16
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
some error happen when  push commits after upgrad from 1.8.3 to 1.9.3.

$ git push
Counting objects: 3, done.
Writing objects: 100% (3/3), 228 bytes | 228.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: Gitea: Internal error
remote: retrieve protected branches information failed: invalid character '<' looking for beginning of value
To https://abc.com/abc/test_123.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://abc.com/abc/test_123.git'

### LINKED ISSUE #8288: Allow Collaborators with Write Access to Give Approving PR Reviews
- Gitea version (or commit ref): 1.9.0
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
(not relevant)

## Description
Currently in Gitea, merging PRs against protected branch with required reviews can only be allowed with enough approving reviews from whitelisted reviewers. However, on GitHub, approving reviews can be given from users with write (or admin) access to the repo. If this feature will be implemented to Gitea, whitelisted reviewers list should contain additional users that can give approving reviews.

The caveat is, when a collaborator with write, admin, or owner access submit `request change` review, the PR cannot be merged until the same collaborator submits another approving reviews.

Thus, the wording for `Review Required` message should be (when no approvals yet):
```
This Pull Request doesn't have approvals yet. 0 of 1 approvals granted from reviewers with write access and whitelisted reviewers.
```
## Screenshots

`Review Required` message on a PR in Gitea:
image

On GitHub:
image

### PR DESCRIPTION
**Pull request by davidsvantesson**
fixes #8288. Related to #5731 (does not solve exactly what poster wants)

Gives three options for pushing to protected branch:
 - disabled
 - anyone with write access
 - only whitelisted

For approvals a new checkbox is added to enable whitelist. Otherwise anyone with write access is considered as a valid approval.

# Screenshot

image

### CODE REVIEW

File: models/migrations/v109.go [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+// license that can be found in the LICENSE file.
+
+package migrations
+
+import (
+	"xorm.io/xorm"
+)
+
+// BranchProtectionAddEnableWhitelist migrates can push vs whitelist push and enabling of approvals whitelist
+func BranchProtectionAddEnableWhitelist(x *xorm.Engine) error {
```
Comment (6543) [inline models/migrations/v109.go]:
```suggestion
func addBranchProtectionAddEnableWhitelist(x *xorm.Engine) error {
```

File: models/migrations/migrations.go [hunk 2]
```diff
@@ -272,6 +272,8 @@ var migrations = []Migration{
 	NewMigration("Add template options to repository", addTemplateToRepo),
 	// v108 -> v109
 	NewMigration("Add comment_id on table notification", addCommentIDOnNotification),
+	// v109 -> v110
+	NewMigration("update branch protection whitelist enable", BranchProtectionAddEnableWhitelist),
```
Comment (6543) [inline models/migrations/migrations.go]:
```suggestion
	NewMigration("update branch protection whitelist enable", addBranchProtectionAddEnableWhitelist),
```

File: models/migrations/v109.go (hunk 1 above)
Comment (6543) [reply models/migrations/v109.go]: or some other better name .. but it should start with add

**Comment by guillep2k** [comment]
Sorry if I didn't get this correctly; the original issue was kind of unclear, but what I understood is that the OP asked for something like...?:

- [ ] Allow forced pushs (-f)

This PR seems very useful nonetheless.

**Comment by davidsvantesson** [comment]
Reading the issue again (and also the comment that was in Chinese), I see I misunderstood what the original poster wanted. I though the problem was that you wanted to easily disable only force pushing for everyone but allowing pushing (without having to enter a whitelist), and maybe also that it shall be enforced for all branches (which can be solved by wildcard protected branches). 
So yes, enabling force pushing for some users is not solved by this PR.

File: models/migrations/v109.go (hunk 1 above)
Comment (davidsvantesson) [reply models/migrations/v109.go]: I tried to give it a slightly better name.

**Comment by 6543** [comment]
:eyes:

**Review by 6543 — APPROVED** [review]

**Comment by lunny** [comment]
Please resolve conflicts.

**Comment by 6543** [comment]
Migration number has changed  +1

File: models/branches.go [hunk 3]
```diff
@@ -26,11 +26,11 @@ const (
...
-	ID                        int64  `xorm:"pk autoincr"`
-	RepoID                    int64  `xorm:"UNIQUE(s)"`
-	BranchName                string `xorm:"UNIQUE(s)"`
-	CanPush                   bool   `xorm:"NOT NULL DEFAULT false"`
-	EnableWhitelist           bool
+	ID                        int64              `xorm:"pk autoincr"`
+	RepoID                    int64              `xorm:"UNIQUE(s)"`
+	BranchName                string             `xorm:"UNIQUE(s)"`
+	CanPush                   bool               `xorm:"NOT NULL DEFAULT false"`
+	EnableWhitelist           bool               `xorm:"NOT NULL DEFAULT false"`
```
Comment (guillep2k) [inline models/branches.go]: Bools always default to false, but why this column needs NOT NULL now? The `Sync2()` function will not update the column in a migration, AFAIK (didn't in my database).

File: models/branches.go [hunk 4]
```diff
@@ -111,12 +127,28 @@ func (protectBranch *ProtectedBranch) GetGrantedApprovalsCount(pr *PullRequest)
...
+		return 0
+	}
+
 	approvals := int64(0)
 	userIDs := make([]int64, 0)
 	for _, review := range reviews {
 		if review.Type != ReviewTypeApprove {
 			continue
 		}
+		if !protectBranch.EnableApprovalsWhitelist {
```
Comment (guillep2k) [inline models/branches.go]: IMHO approvals should "remember" if the users were whitelisted at the moment they approved and this value should not be recalculated. Two reasons for this:

* This is not "list friendly"; it's very difficult to optimize as we want to have the PR list showing the number of approvals. If possible, we should resolve the list with a simple join/select.
* If rules change, history should not be rewritten. Non-counting approvals should remain non-counting and vice-versa.

File: models/migrations/v110.go [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+
+import (
+	"xorm.io/xorm"
+)
+
+func addBranchProtectionCanPushAndEnableWhitelist(x *xorm.Engine) error {
+
+	type ProtectedBranch struct {
+		CanPush                  bool  `xorm:"NOT NULL DEFAULT false"`
+		EnableWhitelist          bool  `xorm:"NOT NULL DEFAULT false"`
```
Comment (guillep2k) [inline models/migrations/v110.go]: This will not have any effect, I believe.

File: routers/private/hook.go [hunk 6]
```diff
@@ -98,7 +98,7 @@ func HookPreReceive(ctx *macaron.Context) {
 
 		canPush := false
 		if isDeployKey {
-			canPush = protectBranch.WhitelistDeployKeys
+			canPush = protectBranch.CanPush && (!protectBranch.EnableWhitelist || protectBranch.WhitelistDeployKeys)
```
Comment (guillep2k) [inline routers/private/hook.go:101]: Previously the fact that people were listed in the whitelist wasn't an impediment to push using the deploy key. If I get this correctly, now deploy keys can't be used if there is a whitelist?

File: routers/repo/setting_protected_branch.go [hunk 7]
```diff
@@ -216,6 +226,7 @@ func SettingsProtectedBranchPost(ctx *context.Context, f auth.ProtectBranchForm)
 		protectBranch.WhitelistDeployKeys = f.WhitelistDeployKeys
 
 		protectBranch.RequiredApprovals = f.RequiredApprovals
+		protectBranch.EnableApprovalsWhitelist = f.EnableApprovalsWhitelist
```
Comment (guillep2k) [inline routers/repo/setting_protected_branch.go:238]: Maybe if `EnableApprovalsWhitelist` or `EnableWhitelist` change to false the existing whitelist should be blanked? It may be a feature, but it can also look like a bug. 😁

File: models/branches.go (hunk 3 above)
Comment (lafriks) [reply models/branches.go]: Not null is needed so not to have null values in database

Comment (guillep2k) [reply models/branches.go]: > 
> 
> Not null is needed so not to have null values in database

@lafriks I know, but this column was always nullable and worked fine. If we suddenly need to make it not null, we need to create some kind of special migration (`ALTER TABLE`) because xorm's `Sync2()` won't touch the column if it already exists. I've tested that locally.

Comment (davidsvantesson) [reply models/branches.go]: I just found it strange only this variable didn't have any xorm directive (NOT NULL), I don' think it will make any difference? Should I remove it again or try to add something to the migration?

File: models/branches.go (hunk 4 above)
Comment (davidsvantesson) [reply models/branches.go]: Your argumentation makes sense, but that would require quite large code change (need new database columns). I think it should be a different PR.

File: routers/private/hook.go (hunk 6 above)
Comment (davidsvantesson) [reply routers/private/hook.go:101]: My intention is that deploy keys can push if:
- Form is set to _Enable Push_. This corresponds to CanPush=True and EnableWhitelist=False
- Form is set to _Whitelist Restricted Push_ and _Whitelist deploy keys..._ is ticked. This corresponds to CanPush=True, EnableWhitelist=True and WhitelistDeployKeys=True

File: routers/repo/setting_protected_branch.go (hunk 7 above)
Comment (davidsvantesson) [reply routers/repo/setting_protected_branch.go:238]: I like the current "feature" but doesn't have a strong opinion. If we change shouldn't all dependent settings be cleared? So e.g. CanPush=false will clear/false all values regarding pushing, RequiredApprovals=0 will clear/false all values regarding approving?

File: models/branches.go (hunk 3 above)
Comment (guillep2k) [reply models/branches.go]: > 
> 
> I just found it strange only this variable didn't have any xorm directive (NOT NULL), I don' think it will make any difference? Should I remove it again or try to add something to the migration?

In all formality, it should be `NOT NULL` (which requires `DEFAULT false`). But it was working so far, so.... The thing is I'm not sure what xorm does behind the curtains (it needs to be checked for each engine). In plain SQL, the following needs to be considered:

* Some databases support bool values; some don't, so tinyint or similar is used instead.
* Some databases resolve `WHERE null = false` as true, some don't.
* Some databases resolve `WHERE null <> true` as true, some don't.

So the question goes beyond this PR. I think that problems may show up if the column is used for filtering (i.e. in a `WHERE` clause). Otherwise it will be no problem. I just wanted to make you aware that this change may not give the expected results.

File: routers/private/hook.go (hunk 6 above)
Comment (guillep2k) [reply routers/private/hook.go:101]: I don't use deploy keys so I'm not familiar with its use case, but this will be a breaking change then, I believe?

File: routers/repo/setting_protected_branch.go (hunk 7 above)
Comment (guillep2k) [reply routers/repo/setting_protected_branch.go:238]: > 
> 
> I like the current "feature" but doesn't have a strong opinion. If we change shouldn't all dependent settings be cleared? So e.g. CanPush=false will clear/false all values regarding pushing, RequiredApprovals=0 will clear/false all values regarding approving?

I don't have a strong opinion either, but what you've said makes sense.

File: models/branches.go (hunk 4 above)
Comment (guillep2k) [reply models/branches.go]: I don't think it's that big of a change. I think you only need a new "Verified bool"  column to the review table and move this check to the code that inserts the review. One day that "verified" column can reflect a 2FA, for example.

File: routers/private/hook.go (hunk 6 above)
Comment (davidsvantesson) [reply routers/private/hook.go:101]: Neither do I use deploy keys, but I don't think the behavior will change with this PR. I have added the term `CanPush` as requirement for any pushing (migration step handles that). `protectBranch.WhitelistDeployKeys` is the existing condition for deploy key pushing. The new condition is that deploy keys can still push if whitelist is not used (option **Enable Push**), i.e. `!protectBranch.EnableWhitelist`.

Comment (davidsvantesson) [reply routers/private/hook.go:101]: Potentially if `protectBranch.EnableWhitelist` is false and `protectedBranch.WhitelistDeployKeys` is true it would be a change of behavior. But that would only be possible because we don't clear existing flags and I don't think that is correct behavior.

File: models/branches.go (hunk 4 above)
Comment (davidsvantesson) [reply models/branches.go]: Can it be called `OfficialReviewer  (bool)`? 
You mean there will be an option to only accept 2FA users as reviewers?

File: routers/repo/setting_protected_branch.go (hunk 7 above)
Comment (davidsvantesson) [reply routers/repo/setting_protected_branch.go:238]: I think it makes sense to clear the settings when disabled, so I changed it. However for RequiredApprovals=0 I didn't clear the approval settings, for two reasons: 
- You might want to block at requested changes (as discussed in other issue) even if you don't require approvals.
- Sometimes I find it convenient to temporary set the number of approvals to zero 😊 .

File: models/branches.go (hunk 4 above)
Comment (guillep2k) [reply models/branches.go]: Yes, it can be called OfficialReviewer, although that would lock the meaning. What I mean is that what today is a bool (verified/not verified) tomorrow can be an enum (not verified/verified/verified+signed, etc.). But whatever we may want in the future can be solved with a migration no problem, so feel free to choose whatever you feel that fits best. 👍

File: routers/private/hook.go (hunk 6 above)
Comment (guillep2k) [reply routers/private/hook.go:101]: Sorry, I see now what you mean. 👍

File: models/migrations/v110.go [hunk 8]
```diff
@@ -17,16 +20,74 @@ func addBranchProtectionCanPushAndEnableWhitelist(x *xorm.Engine) error {
...
+	if _, err := sess.Exec("UPDATE `protected_branch` SET `enable_approvals_whitelist` = ? WHERE `required_approvals` > ?", true, 0); err != nil {
 		return err
 	}
-	_, err := x.Exec("UPDATE `protected_branch` SET `enable_approvals_whitelist` = ? WHERE `required_approvals` > ?", true, 0)
-	return err
+
+	// Find latest review of each user in each pull request, and set official field if appropriate
+	reviews := []*models.Review{}
+	if x.Dialect().DBType() == core.MSSQL {
+		if err := x.SQL(`SELECT *, max(review.updated_unix) as review_updated_unix FROM review WHERE (review.type = ? OR review.type = ?)
```
Comment (guillep2k) [inline models/migrations/v110.go]: IMHO this query won't do what you want from it, and it will choke from the sheer number of records. Since Gitea uses sequential ID numbers, you can try this:
```
select * from review where id in (
    select max(id) from review group by issue_id, reviewer_id
    where issue_id > ? and issue_id <= ? and type in (?, ?)
)
```

You will have exactly one review (the last one) per reviewer per issue.

But you'll have to paginate the PR IDs to avoid loading too many records at once.

Comment (guillep2k) [reply models/migrations/v110.go]: You may have to use:
```
select * from review where id in (
    select max(id), issue_id, reviewer_id from review group by issue_id, reviewer_id
    where issue_id > ? and issue_id <= ? and type in (?, ?)
)
```
for syntactical reasons but I'm not sure. Anyway, it's equivalent.

File: models/migrations/v110.go [hunk 9]
```diff
@@ -43,36 +42,25 @@ func addBranchProtectionCanPushAndEnableWhitelist(x *xorm.Engine) error {
...
 	// Find latest review of each user in each pull request, and set official field if appropriate
 	reviews := []*models.Review{}
-	if x.Dialect().DBType() == core.MSSQL {
-		if err := x.SQL(`SELECT *, max(review.updated_unix) as review_updated_unix FROM review WHERE (review.type = ? OR review.type = ?)
-GROUP BY review.id, review.issue_id, review.reviewer_id, review.type, ) as review
-ORDER BY review_updated_unix DESC`,
-			models.ReviewTypeApprove, models.ReviewTypeReject).
+	var page int64
+	for page = 0; page <= totalPages; page++ {
+		if err := sess.Sql("SELECT * FROM review WHERE id IN (SELECT max(id) as id FROM review WHERE issue_id > ? AND issue_id <= ? AND type in (?, ?) GROUP BY issue_id, reviewer_id)",
```
Comment (lunny) [inline models/migrations/v110.go]: Please use `sess.SQL`.

File: models/branches.go (hunk 3 above)
Comment (davidsvantesson) [reply models/branches.go]: I think ALTER TABLE will not be possible for sqlite (https://stackoverflow.com/questions/29583396/modify-sqlite-table-column-not-null-to-null)

Thus it would require to create a new column and replace with the old one. Currently I don't think this is an issue, but if new features are implemented where this is not considered it can result in bugs. So is it better to leave it without the NOT NULL to not mislead?

Comment (guillep2k) [reply models/branches.go]: > 
]> 
> So is it better to leave it without the NOT NULL to not mislead?

I think that's preferrable, yes.

File: models/migrations/v110.go [hunk 10]
```diff
@@ -43,30 +44,37 @@ func addBranchProtectionCanPushAndEnableWhitelist(x *xorm.Engine) error {
...
 			page*pageSize, (page+1)*pageSize, models.ReviewTypeApprove, models.ReviewTypeReject).
 			Find(&reviews); err != nil {
 			return err
 		}
 
 		for _, review := range reviews {
 			if err := review.LoadAttributes(); err != nil {
-				return err
+				// Error might occur if user or issue doesn't exist, ignore it.
+				continue
```
Comment (guillep2k) [inline models/migrations/v110.go]: Good catch. I like resilience. 😄

File: models/migrations/v110.go [hunk 11]
```diff
@@ -0,0 +1,89 @@
...
+
+	if _, err := sess.Exec("UPDATE `protected_branch` SET `can_push` = `enable_whitelist`"); err != nil {
+		return err
+	}
+	if _, err := sess.Exec("UPDATE `protected_branch` SET `enable_approvals_whitelist` = ? WHERE `required_approvals` > ?", true, 0); err != nil {
+		return err
+	}
+
+	var pageSize int64 = 20
+	qresult, err := sess.QueryInterface("SELECT max(id) as max_id FROM pull_request")
```
Comment (guillep2k) [inline models/migrations/v110.go]: Try:
```
	var max_id int64
	if _, err = sess.Select("max(id) as `max_id`").Table("pull_request").Get(&max_id); err != nil {
		return err
	}
```

File: models/migrations/v110.go (hunk 10 above)
Comment (davidsvantesson) [reply models/migrations/v110.go]: Actually test cases failed

File: models/review.go [hunk 12]
```diff
@@ -345,9 +345,9 @@ func GetReviewersByPullID(pullID int64) (issueReviewers []*PullReviewersWithType
 	irs := []*PullReviewersWithType{}
 	if x.Dialect().DBType() == core.MSSQL {
 		err = x.SQL(`SELECT [user].*, review.type, review.official, review.review_updated_unix FROM
-(SELECT review.id, review.type, review.reviewer_id, max(review.updated_unix) as review_updated_unix
+(SELECT review.id, review.type, review.reviewer_id, review.official, max(review.updated_unix) as review_updated_unix
```
Comment (guillep2k) [inline models/review.go]: This line I don't understand. If you have `review.id` in the row, all lines are already unique (unless there were multiple users with the same id which should never happen). A `MAX(updated_unix)` will be the same as `updated_unix` without the Group By. 🤔

What is it that you are trying to accomplish? Bring up the latest review? The query from the migration should achieve that.

File: models/migrations/v110.go (hunk 11 above)
Comment (davidsvantesson) [reply models/migrations/v110.go]: The current query seem to work, although your suggestion maybe looks a bit simpler.

File: models/review.go (hunk 12 above)
Comment (davidsvantesson) [reply models/review.go]: The function shall return the latest review of each reviewer (not necessary official reviewers). I see that I actually don't use the change in this function, probably rewrote something. I think later on the information on which reviews are "official" should be shown on the pull request page.

The `max(review.updated_unix) as review_updated_unix` is used to sort the list and ensure the group by gets the latest review. However it might have been enough to get the `max(id)` instead, I don't see how reviews from same reviewer could change order.

Comment (guillep2k) [reply models/review.go]: > 
> 
> The function shall return the latest review of each reviewer (not necessary official reviewers). I see that I actually don't use the change in this function, probably rewrote something. I think later on the information on which reviews are "official" should be shown on the pull request page.
> 
> The `max(review.updated_unix) as review_updated_unix` is used to sort the list and ensure the group by gets the latest review. However it might have been enough to get the `max(id)` instead, I don't see how reviews from same reviewer could change order.

This kind of query will not work. If you have two different `review.type` (e.g. comment + approval) from the same user, you'll get two rows because Group By will see them as different values. To get the latest record you need to do a select in select like the one used in the migration:

```golang
if err := sess.SQL("SELECT * FROM review WHERE id IN (SELECT max(id) as id FROM review WHERE issue_id = ? AND type in (?, ?) GROUP BY issue_id, reviewer_id)",
			issueID, models.ReviewTypeApprove, models.ReviewTypeReject).
			Find(&reviews); err != nil {
			return err
		}
```

Of course the example above requires some adaptation to get the JOIN and the columns you're expecting.

Comment (davidsvantesson) [reply models/review.go]: It is actually solved further down in the function (I don't say it is a good solution 😄)

```
	// We need to group our results by the fields we want, otherwise some databases will fail (only_full_group_by).
	// But becaus we're doing this, we need to manually filter out multiple reviews of different types by the
	// same person because we only want to show the newest review grouped by user. Thats why we're using a map here.
```

Comment (davidsvantesson) [reply models/review.go]: Your query might work... although it doesn't work to just remove some of the group by fields for pgsql and mysql (due to some _only_full_group_by_ setting).

Comment (davidsvantesson) [reply models/review.go]: So I didn't want to touch this function more than needed (and actually I can revert the changes I done). But the only thing I added was the `Official` field to the results, and hence added in SQL where necessary. The multiple rows is handled by the code later already. 

I think maybe this function tries to do too much in SQL which makes it a bit complex.

Comment (guillep2k) [reply models/review.go]: To exemplify this, let me give you one example. Suppose you have this in the `review` table:

| review ID  | user_id     | review_type         | review_date         |
|------------|-------------|---------------------|--------------|
| 1          | 1           | comment             | Jan 1        |
| 2          | 2           | request-changes     | Jan 2        |
| 3          | 1           | comment             | Jan 3        |
| 4          | 3           | comment             | Jan 4        |
| 5          | 2           | approval            | Jan 5        |

If you do:

```SQL
select max(review_id), user_id, review_type, max(review_date)
from review
group by user_id, review_type;
```

This is what you will get:

| review ID  | user_id     | review_type         | review_date         |
|------------|-------------|---------------------|--------------|
| 2          | 2           | request-changes     | Jan 2        |
| 3          | 1           | comment             | Jan 3        |
| 4          | 3           | comment             | Jan 4        |
| 5          | 2           | approval            | Jan 5        |

As you see, the two reviews from user `#1` were consolidated in one row, as the fields `user_id` and `review_type` are the same for all records; user `#3` is not a problem, but the two reviews from user `#2` show up as different rows.

That's why the only way to get this SQL right is with a sub-query:

```SQL
select max(id), user_id from review group by user_id;
```

Will give you:

| review ID  | user_id     |
|------------|-------------|
| 3          | 1           |
| 4          | 3           |
| 5          | 2           |

So, these are the records that you're looking for:

```SQL
select review_id, user_id, review_type, review_date
from `review`
where review_id in (
        select max(id), user_id from `review` as `review_inner` group by user_id
    )
```

returns:

| review ID  | user_id     | review_type         | date         |
|------------|-------------|---------------------|--------------|
| 3          | 1           | comment             | Jan 3        |
| 4          | 3           | comment             | Jan 4        |
| 5          | 2           | approval            | Jan 5        |

which is what you want. With this method you can perform joins too:

```SQL
select review_id, user_id, review_type, review_date, `user`.*
from `review`
INNER JOIN `user` ON `user`.`id` = `review`.`user_id`
where review_id in (
        select max(id), user_id from `review` as `review_inner` group by user_id
    )
```

There's probably a nice way to write all of this with a couple of xorm directives (e.g. I think you can write the subquery in builder and use it in the `In()` operator, but I'm not sure), so I think it will be just quicker to do it with `sess.SQL()` like you did in migrations.

Comment (davidsvantesson) [reply models/review.go]: Very long informative response 😄. 
I just wanted to point out that the existing code actually works, although not very efficient or elegant. I will see if I can rewrite the SQL query in a better way.

Comment (guillep2k) [reply models/review.go]: Oh, sorry! I didn't realize that the code wasn't yours. It's my tendency of checking the right column more thoroughly than the left one. 😋

If you just don't feel like doing that change just let me know, because that's the only thing I was waiting for to give my 👍.

File: models/review.go [hunk 13]
```diff
@@ -308,46 +331,25 @@ func SubmitReview(doer *User, issue *Issue, reviewType ReviewType, content strin
...
-	// But becaus we're doing this, we need to manually filter out multiple reviews of different types by the
-	// same person because we only want to show the newest review grouped by user. Thats why we're using a map here.
-	issueReviewers = []*PullReviewersWithType{}
-	usersInArray := make(map[int64]bool)
-	for _, ir := range irs {
-		if !usersInArray[ir.ID] {
-			issueReviewers = append(issueReviewers, ir)
-			usersInArray[ir.ID] = true
+	for _, review := range reviews {
+		if err := review.loadReviewer(sess); err != nil {
```
Comment (davidsvantesson) [inline models/review.go:362]: Need to handle case when user has been deleted

Comment (guillep2k) [reply models/review.go:362]: There's a "ghost" user for these cases if you need it.

File: models/review.go (hunk 12 above)
Comment (davidsvantesson) [reply models/review.go]: I rewrote the code and think it is easier to understand now although there will be a few more sql queries, but normally there will not be that many reviews for a PR.

**Comment by davidsvantesson** [comment]
So finally I think this PR is ready....

File: models/review.go [hunk 14]
```diff
@@ -283,10 +298,18 @@ func SubmitReview(doer *User, issue *Issue, reviewType ReviewType, content strin
 			return nil, nil, ContentEmptyErr{}
 		}
 
+		// Official status of review updated at every submit in case settings changed
+		official, err := isOfficialReviewer(sess, issue, doer)
```
Comment (guillep2k) [inline models/review.go]: `Review.Official` is not being set when the review is created above in line 284 (e.g. direct approval without commenting code).

File: models/review.go [hunk 15]
```diff
@@ -255,6 +265,11 @@ func SubmitReview(doer *User, issue *Issue, reviewType ReviewType, content strin
 		return nil, nil, err
 	}
 
+	// Only reviewers latest review shall count as "official", so existing reviews needs to be cleared
+	if _, err := sess.Exec("UPDATE `review` SET official=? WHERE issue_id=? AND reviewer_id=?", false, issue.ID, doer.ID); err != nil {
```
[the remark this answers is not in the document]
Comment (davidsvantesson) [reply models/review.go]: I didn't consider this, you are right only approving/rejecting review shall count for the official attribute. I think l have fixed that now.

It is correct that clearing old "official" reviews is not needed to get the latest reviews of each reviewer. That query still returns reviews from each reviewer, even those that are not official (i.e in the "approval whitelist"). However the reason you wanted this was to efficiently calculate number of approvals, and if you loook at `GetGrantedApprovalsCount` it sums it up directly. So therefore it is necessary to clear old approvals. Also I think it can be handy if we implement _block at "Changes requested"_, we can easily do a direct SQL query to see if there are any official review with status Rejected/Changes requested.

File: models/review.go (hunk 14 above)
Comment (davidsvantesson) [reply models/review.go]: It was done in `createReview`, but the updated code shall be more clear. An approved or rejected review always go to function `SubmitReview`, and the update of official attribute is handled there now.

**Review by guillep2k — APPROVED** [review]
Thanks for all the good work!
