### PR TITLE
Fix issue comment number

### LINKED ISSUE #22419: Source code line's comments are not taken into account on Pull Requests page
### Description

On the Gitea demo site, source code line's comments are not taken into account on `Pull Requests` page. So, they are not added to the count of the MR's comments count.

### Gitea Version

1.19.0+dev-291

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

I visit it via a browser.

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix #22419

Only comments with types `CommentTypeComment` and `CommentTypeReview` will be counted as conversations of the pull request. `CommentTypeReview` was missed in the previous implementation.

### CODE REVIEW

**Comment by silverwind** [comment]
How much work would it be to add a migration that fixes the counts on existing issues? Would probably be a long-running migration on big instances, right?

**Comment by lunny** [comment]
> How much work would it be to add a migration that fixes the counts on existing issues? Would probably be a long-running migration on big instances, right?

Yes, so I don't think the migration is necessary. The number will be corrected when next comment created/updated.

> Also, not sure if such a migration would be backportable at all as it would likely skip migration numbers (a design flaw in the migration system).

**Comment by silverwind** [comment]
Yeah it's not really a requirement from me, more like a "nice to have" but likely too complicated with the migration backport to really be justified.

**Comment by silverwind** [comment]
Willing to approve this without migration once you fix the tests :)

File: models/issues/comment.go [hunk 1]
```diff
@@ -1266,6 +1266,26 @@ func (c *Comment) HasOriginalAuthor() bool {
 	return c.OriginalAuthor != "" && c.OriginalAuthorID != 0
 }
 
+func CountCommentsBuilder(issueID int64) *builder.Builder {
+	return builder.Select("count(*)").From("comment").Where(builder.Eq{
+		"issue_id": issueID,
+	}.And(builder.Or(
```
Comment (yp05327) [inline models/issues/comment.go]: Can this be converted into `In`?

File: models/repo.go [hunk 2]
```diff
@@ -109,7 +109,7 @@ func userStatsCorrectNumRepos(ctx context.Context, id int64) error {
 }
 
 func repoStatsCorrectIssueNumComments(ctx context.Context, id int64) error {
-	return StatsCorrectSQL(ctx, "UPDATE `issue` SET num_comments=(SELECT COUNT(*) FROM `comment` WHERE issue_id=? AND type=0) WHERE id=?", id)
+	return StatsCorrectSQL(ctx, "UPDATE `issue` SET num_comments=(SELECT COUNT(*) FROM `comment` WHERE issue_id=? AND (type=0 or type=22)) WHERE id=?", id)
```
Comment (yp05327) [inline models/repo.go]: > type=0 or type=22

use variable instead of number?

File: models/issues/comment.go (hunk 1 above)
Comment (lunny) [reply models/issues/comment.go]: Fixed

File: models/repo.go (hunk 2 above)
Comment (lunny) [reply models/repo.go]: Fixed

File: models/repo.go [hunk 3]
```diff
@@ -198,7 +200,8 @@ func CheckRepoStats(ctx context.Context) error {
 		},
 		// Issue.NumComments
 		{
-			statsQuery("SELECT `issue`.id FROM `issue` WHERE `issue`.num_comments!=(SELECT COUNT(*) FROM `comment` WHERE issue_id=`issue`.id AND type=0)"),
+			statsQuery(fmt.Sprintf("SELECT `issue`.id FROM `issue` WHERE `issue`.num_comments!=(SELECT COUNT(*) FROM `comment` WHERE issue_id=`issue`.id AND (type=%d OR type=%d))",
+				issues_model.CommentTypeComment, issues_model.CommentTypeReview)),
```
Comment (wxiaoguang) [inline models/repo.go]: image

Comment (lunny) [reply models/repo.go]: fcfb518a321bfd56f190cb001916a955603bec87

File: models/repo.go [hunk 4]
```diff
@@ -198,7 +200,8 @@ func CheckRepoStats(ctx context.Context) error {
 		},
 		// Issue.NumComments
 		{
-			statsQuery("SELECT `issue`.id FROM `issue` WHERE `issue`.num_comments!=(SELECT COUNT(*) FROM `comment` WHERE issue_id=`issue`.id AND type=0)"),
+			statsQuery(fmt.Sprintf("SELECT `issue`.id FROM `issue` WHERE `issue`.num_comments!=(SELECT COUNT(*) FROM `comment` WHERE issue_id=`issue`.id AND (type=%d OR type=%d))",
+				issues_model.ConversationCountedCommentType()...)),
```
Comment (wxiaoguang) [inline models/repo.go]: ```func statsQuery(args ...any)```

File: models/issues/comment.go [hunk 5]
```diff
@@ -197,6 +197,19 @@ func (t CommentType) HasMailReplySupport() bool {
...
+func (t CommentType) CountedAsConversation() bool {
+	for _, ct := range ConversationCountedCommentType() {
+		if t == ct {
+			return true
+		}
+	}
+	return false
+}
+
+func ConversationCountedCommentType() []any {
```
Comment (wxiaoguang) [inline models/issues/comment.go]: ```any``` ?

Comment (lunny) [reply models/issues/comment.go]: It can be used directly in format functions but `[]CommentType` cannot.

File: models/repo.go (hunk 4 above)
Comment (lunny) [reply models/repo.go]: Yes, if it's `statsQuery(string, ...any)`, then I can remove the format. But since it's `statsQuery(...any)`. It's also not perfect to create a temporary slice.

Comment (wxiaoguang) [reply models/repo.go]: But we should never used `ExecSQL(Sprintf(...))` (in case SQL-injection), we should always use statement arguments, right?

Comment (lunny) [reply models/repo.go]: ee4bf009eb

File: models/issues/comment.go (hunk 5 above)
Comment (lunny) [reply models/issues/comment.go]: 17d8a24801dfd5af8cec6efcdb3c78050155203f

Comment (wxiaoguang) [reply models/issues/comment.go]: Why not use `statsQuery( ... builder....In("type", ConversationCountedCommentType) ... )`?

File: models/repo.go [hunk 6]
```diff
@@ -24,7 +25,7 @@ func Init(ctx context.Context) error {
 }
 
 type repoChecker struct {
-	querySQL   func(ctx context.Context) ([]map[string][]byte, error)
+	querySQL   func(ctx context.Context) ([]int64, error)
```
Comment (wxiaoguang) [inline models/repo.go:29]: The old design `[]map[string]` seems more flexible, why change it?

Comment (lunny) [reply models/repo.go:29]: Every SQL is assumed using `select id` for this checker. If we want that flexibility, many places need to be changed. So I don't think it's necessary to keep the flexible if there is no whole design.

File: models/issues/comment.go [hunk 7]
```diff
@@ -197,6 +197,21 @@ func (t CommentType) HasMailReplySupport() bool {
...
+	for _, ct := range ConversationCountedCommentType() {
+		if t == ct {
+			return true
+		}
+	}
+	return false
+}
+
+// ConversationCountedCommentType returns the comment types that are counted as a conversation
+// The returned types are []any rather than []CommentType to allow for easy use as xorm args
```
Comment (wxiaoguang) [inline models/issues/comment.go]:
```suggestion
```

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
CI failure is related

File: models/repo.go [hunk 8]
```diff
@@ -106,7 +109,14 @@ func userStatsCorrectNumRepos(ctx context.Context, id int64) error {
...
 func repoStatsCorrectIssueNumComments(ctx context.Context, id int64) error {
-	return StatsCorrectSQL(ctx, "UPDATE `issue` SET num_comments=(SELECT COUNT(*) FROM `comment` WHERE issue_id=? AND type=0) WHERE id=?", id)
+	return StatsCorrectSQL(ctx,
+		builder.Update(builder.Eq{
+			"num_comments": builder.Select("COUNT(*)").From("`comment`").Where(
+				builder.Eq{"issue_id": id}.And(
+					builder.In("type", issues_model.ConversationCountedCommentType()),
+				)),
+		}).From("`issue`").Where(builder.Eq{"id": id}),
+	)
```
Comment (wxiaoguang) [inline models/repo.go]: 2 separate SQL could be clearer. And fix the CI failure.

```
numComments := query()
update(num_comments = numComments)
```

Comment (lunny) [reply models/repo.go]: d867475

**Review by lafriks — APPROVED** [review]
