### PR TITLE
Avoid issue info panic

### LINKED ISSUE #29624: 500 error while upgrade from 1.6.x to 1.21.7 (Render failed, failed to render template: user/dashboard/dashboard, error: template error: builtin(bindata):user/dashboard/feeds:107:19)
### Description

After upgrading from 1.6.x to 1.21.7, this error appears on my Index page

```
Render failed, failed to render template: user/dashboard/dashboard, error: template error: builtin(bindata):user/dashboard/feeds:107:19 : executing "user/dashboard/feeds" at <index .GetIssueInfos 1>: error calling index: reflect: slice index out of range
----------------------------------------------------------------------
					{{$comment := index .GetIssueInfos 1}}
					              ^
```

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

Screenshot_20240306_153025

### Git Version

2.40.1

### Operating System

Docker with unraid 6.12.4

### How are you running Gitea?

Docker with unraid 6.12.4

### Database

SQLite

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #29624

### CODE REVIEW

File: models/activities/action.go [hunk 1]
```diff
@@ -393,10 +393,13 @@ func (a *Action) GetCreate() time.Time {
...
 
-// GetIssueInfos returns a list of issues associated with
-// the action.
+// GetIssueInfos returns a list of associated information with the action.
 func (a *Action) GetIssueInfos() []string {
-	return strings.SplitN(a.Content, "|", 3)
+	ret := strings.SplitN(a.Content, "|", 3)
+	for len(ret) < 3 {
+		ret = append(ret, "")
+	}
```
Comment (KN4CK3R) [inline models/activities/action.go:402]: Do we know in 2 years why that is needed? The whole delimiter concept is fragile because the values are not just numbers but user provided text which can contain the delimiter:
https://github.com/go-gitea/gitea/blob/a2b0fb1a64b0794b808a013089758a49f56d8915/services/feed/action.go#L232
https://github.com/go-gitea/gitea/blob/a2b0fb1a64b0794b808a013089758a49f56d8915/services/feed/action.go#L278
https://github.com/go-gitea/gitea/blob/a2b0fb1a64b0794b808a013089758a49f56d8915/services/feed/action.go#L310
That field should be json or a struct which can be json serialized by xorm. Here for example it contains json text:
https://github.com/go-gitea/gitea/blob/a2b0fb1a64b0794b808a013089758a49f56d8915/services/feed/action.go#L344

File: models/activities/action.go [hunk 2]
```diff
@@ -393,10 +393,10 @@ func (a *Action) GetCreate() time.Time {
 	return a.CreatedUnix.AsTime()
 }
 
-// GetIssueInfos returns a list of issues associated with
-// the action.
+// GetIssueInfos returns a list of associated information with the action.
 func (a *Action) GetIssueInfos() []string {
-	return strings.SplitN(a.Content, "|", 3)
+	// make sure it always returns 3 elements, because there are some access to the a[1] and a[2] without checking the length
+	return strings.SplitN(a.Content+"||", "|", 3)
```
Comment (KN4CK3R) [inline models/activities/action.go]: Thanks for the comment but that's wrong now:
```go
fmt.Printf("%#v", strings.SplitN("1|2|3"+"||", "|", 3))
// []string{"1", "2", "3||"}
```

File: models/activities/action.go (hunk 1 above)
Comment (wxiaoguang) [reply models/activities/action.go:402]: I totally agree with you, but this patch is done intentionally.

1. The fragile `|` is as old 2014-07 (8dd07c0d Unknwon on 2014-07-26 at 12:24)
    * At that time, only `SplitN(2)`, it is generally safe.
    * #12674 made it worse: `SplitN(3)`  ....
3. This patch fixes the panic, and is easy to backport

File: models/activities/action.go (hunk 2 above)
Comment (wxiaoguang) [reply models/activities/action.go]: Already reverted with a new comment

File: models/activities/action.go (hunk 1 above)
Comment (a1012112796) [reply models/activities/action.go:402]: I'd like don't show the comment which not have enough data.

Comment (wxiaoguang) [reply models/activities/action.go:402]: > I'd like don't show the comment which not have enough data.

Then it needs a lot of new `{{if}}` blocks in the templates. I don't think it's worth to make it that complex.

**Comment by wxiaoguang** [comment]
I know there might be some different opinions about this "fix", IMO, it is good enough:

1. It doesn't make anything worse, the proper fix could be proposed in the future.
2. It fixes the panic for end users
3. It is easy to backport

**Review by delvh — APPROVED** [review]

**Review by lunny — APPROVED** [review]
