### PR TITLE
Make `gitea serv` respect git binary home

### LINKED ISSUE #23137: `gitea serv` doesn't respect git's binary path in config(app.ini):
### Description

`gitea serv` doesn't respect git's binary path in config(app.ini):

https://github.com/go-gitea/gitea/blob/10cdcb9ea8077098921d72720f9f36fcfd950452/cmd/serv.go#L293-L304

If a user has different git versions, this code might execute an incorrect git.

### PR DESCRIPTION
**Pull request by wxiaoguang**
Close #23137

The old code is too old (8-9 years ago)

Let's try to execute the git commands from git bin home directly.

The verb has been checked above, it could only be:
* git-upload-pack
* git-upload-archive
* git-receive-pack
* git-lfs-authenticate

### CODE REVIEW

**Review by wolfogre — APPROVED** [review]

File: cmd/serv.go [hunk 1]
```diff
@@ -290,17 +291,21 @@ func runServ(c *cli.Context) error {
...
-		verb = strings.Replace(verb, "-", " ", 1)
-	}
-
 	var gitcmd *exec.Cmd
-	verbs := strings.Split(verb, " ")
-	if len(verbs) == 2 {
-		gitcmd = exec.CommandContext(ctx, verbs[0], verbs[1], repoPath)
-	} else {
-		gitcmd = exec.CommandContext(ctx, verb, repoPath)
+	gitBinPath := filepath.Dir(git.GitExecutable) // e.g. /usr/bin
```
Comment (lunny) [inline cmd/serv.go:295]: `git.GitExecutable` maybe a relative path. e.g. just `git`.

Comment (wxiaoguang) [reply cmd/serv.go:295]: No, it can't (after the InitSimple or InitFull)

<details>

image


image

</details>

Comment (wxiaoguang) [reply cmd/serv.go:295]: And the good thing is, even if the `git.GitExecutable` is not an absolute path (well, that's impossible), then the `os.Stat` check would fail, then the logic would fallback to `exec.CommandContext(ctx, git.GitExecutable, verbFields[1]` (aka: `git upload-pack ...`), everything is still good.

**Review by lunny — APPROVED** [review]

**Comment by jolheiser** [comment]
🎺 🤖

**Comment by wolfogre** [comment]
> I was unable to create a backport for 1.18, please send one manually. 🍵

Maybe there are some bugs of GiteaBot, it has already created a backport for 1.18: https://github.com/go-gitea/gitea/pull/23196
