### PR TITLE
Fix updating user visibility

### LINKED ISSUE #35030: Cannot Set User Visibility to Public via API
### Description

/admin/users/{username}
Update user visibility. Supports changing to private or limited, but does not support changing visibility to public.
When attempting to set public, the API still returns HTTP 200 without an error, but the parameter is not successfully updated.

### Gitea Version

1.24.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

gitea installed using the helm package

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix #35030

### CODE REVIEW

File: routers/api/v1/admin/user.go [hunk 1]
```diff
@@ -234,13 +234,15 @@ func EditUser(ctx *context.APIContext) {
 	}
 
 	opts := &user_service.UpdateOptions{
-		FullName:                optional.FromPtr(form.FullName),
-		Website:                 optional.FromPtr(form.Website),
-		Location:                optional.FromPtr(form.Location),
-		Description:             optional.FromPtr(form.Description),
-		IsActive:                optional.FromPtr(form.Active),
-		IsAdmin:                 user_service.UpdateOptionFieldFromPtr(form.Admin),
-		Visibility:              optional.FromNonDefault(api.VisibilityModes[form.Visibility]),
```
Comment (wxiaoguang) [inline routers/api/v1/admin/user.go:243]: ~~It should simply use `FromPtr` and make `form.Visibility` to be a pointer~~

OK, it needs other designs

File: modules/optional/option.go [hunk 2]
```diff
@@ -28,12 +28,18 @@ func FromPtr[T any](v *T) Option[T] {
 	return Some(*v)
 }
 
-func FromNonDefault[T comparable](v T) Option[T] {
-	var zero T
-	if v == zero {
+func FromNonDefaultFunc[T comparable](f T, isZero func(T) bool) Option[T] {
```
Comment (wxiaoguang) [inline modules/optional/option.go]: Are you really sure what you are doing is right?

Comment (wxiaoguang) [reply modules/optional/option.go]: It needs a `FromMapLookup(map, key)`

Comment (lunny) [reply modules/optional/option.go]: What's the problem? I don't understand what did you mean.

Comment (wxiaoguang) [reply modules/optional/option.go]: No need to understand

**Review by wxiaoguang — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Review by lafriks — APPROVED** [review]
