### PR TITLE
Fix locale init

### LINKED ISSUE #14577: InitLocales() [F] Failed to set messages to en-US: Lang already exists
- Gitea version (or commit ref): https://github.com/go-gitea/gitea/commit/014313134f72ebb2ca57eb2e5cd42726231f8fff, https://github.com/go-gitea/gitea/commit/4457d0e8d9b09e7577242a8bc005ef9d43be4e8c
- Git version: 2.29.2
- Operating system: Ubuntu in Gitpod
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite3
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Unable (present during a deployment)
- Log gist: https://gist.githubusercontent.com/Kreyren/e4dcd14f49c2b7f2cbfe3a196625371d/raw/a87e9d6326c0205c1b2c6df273d528522c9f96c2/gistfile1.txt

## Steps to reproduce
1. Clone gitea and change tag on version 2.13.2
2. `docker build -t kreyren -f Dockerfile.rootless .`
3. `docker run -it -p 3000:3000 kreyren`
4. Open `localhost:3000` and press `Install Gitea`
5. Expect mentioned failure

## Screenshots

image

### PR DESCRIPTION
**Pull request by jolheiser**
Fixes #14577 

Locales were being init twice on new installs, which caused a failure.

### CODE REVIEW

**Review by 6543 — COMMENTED** [review]
.

**Review by 6543 — APPROVED** [review]

File: modules/translation/translation.go [hunk 1]
```diff
@@ -57,8 +59,13 @@ func InitLocales() {
...
 	for i := range setting.Names {
 		key := "locale_" + setting.Langs[i] + ".ini"
-		if err := i18n.SetMessageWithDesc(setting.Langs[i], setting.Names[i], localFiles[key]); err != nil {
-			log.Fatal("Failed to set messages to %s: %v", setting.Langs[i], err)
+		if err = i18n.SetMessageWithDesc(setting.Langs[i], setting.Names[i], localFiles[key]); err != nil {
+			if errors.Is(err, i18n.ErrLangAlreadyExist) {
+				// just log if lang is already loaded since we can not reload it
+				log.Warn("Can not load language '%s' since already loaded", setting.Langs[i])
+			} else {
+				log.Fatal("Failed to set messages to %s: %v", setting.Langs[i], err)
```
Comment (zeripath) [inline modules/translation/translation.go]: Make this:

```suggestion
				log.Error("Failed to set messages to %s: %v", setting.Langs[i], err)
```

Killing a server and causing a docker loop for a problem with a possibly unused or not found locale file is just nasty.

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
just to ref ... this https://github.com/unknwon/i18n/pull/9 will make flush before init able ...
