### PR TITLE
Fix state desync in ComboMarkdownEditor

### LINKED ISSUE #24253: Markdown tasklist does not preserve checkbox state on "Edit"
### Description

Steps to reproduce:

1. Create issue comment with `- [ ]`.
2. Click Edit
3. Click Cancel
4. Click the checkbox
5. Click Edit

Checkbox is incorrectly unchecked in markdown source:

image

Screenshot 2023-04-21 at 12 42 53

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### PR DESCRIPTION
**Pull request by silverwind**
Fixes https://github.com/go-gitea/gitea/issues/24253

When a tasklist checkbox is clicked, the tasklist code [updates `.raw-content` with latest server data](https://github.com/go-gitea/gitea/blob/7a8fe9eb370c6f3f5ec6eae2e1ebba5ac77b1f25/web_src/js/markup/tasklist.ts#L73) in the DOM after POSTing.

Then when "Edit" is clicked the ComboMarkdownEditor is shown with a stale value from the previous edit session.

The fix makes it always read from `.raw-content`, no server syncronization necessary because the value in `.raw-content` is the latest from the server.

### CODE REVIEW

File: web_src/js/features/repo-issue-edit.ts [hunk 1]
```diff
@@ -98,10 +98,7 @@ async function tryOnEditContent(e: Event) {
     form.addEventListener('submit', saveAndRefresh);
   }
 
-  // FIXME: ideally here should reload content and attachment list from backend for existing editor, to avoid losing data
```
Comment (wxiaoguang) [inline web_src/js/features/repo-issue-edit.ts:101]: Is this FIXME fixed?

**Review by lafriks — APPROVED** [review]

**Review by lunny — APPROVED** [review]
