### PR TITLE
Fix org team assignee/reviewer lookups for team member permissions

### LINKED ISSUE #34871: Cannot add an organization owner as a Pull Request reviewer
### Description

When creating a new pull request I cannot add an owner of the organization as a reviewer. 
I can add other members from different teams or collaborators but not an owner.

This seems to be an issue with this particular Organization, since I can add them as reviewers in others, but organization and team configurations are the same.

Is there a setting I'm missing?
I hope my explanation was clear, thank you very much in advance

### Gitea Version

1.24.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

We used the `gitea-1.24.2-darwin-10.12-amd64` binary

### Database

None

### PR DESCRIPTION
**Pull request by pisarz77**
Fix team members missing from assignee list when `team_unit.access_mode` is 0 but the doer is owner.

Fix  #34871

1. Use `GetTeamUserIDsWithAccessToAnyRepoUnit` for repo assignee list
2. Load assignee list for project issues directly
3. Use `GetTeamUserIDsWithAccessToAnyRepoUnit` for repo reviewer list

### CODE REVIEW

**Comment by wxiaoguang** [comment]
The proper fix should use `GetUserIDsWithUnitAccess` or `GetTeamUserIDsWithAccessToAnyRepoUnit`

**Comment by pisarz77** [comment]
Updated per review: dropped the migration entirely and refactored `GetRepoAssignees` to use `organization.GetTeamUserIDsWithAccessToAnyRepoUnit`, which also matches teams via `team.authorize` so Owner-team members come through even when `team_unit.access_mode` is stale.

Two calls preserve the previous condition (write to any unit + read on PullRequests). Existing `TestRepoAssignees` passes locally. Force-pushed to the branch.

**Comment by pisarz77** [comment]
Used `GetTeamUserIDsWithAccessToAnyRepoUnit` directly. `GetUserIDsWithUnitAccess` isn't reachable from `models/repo` without creating an import cycle (`models/perm/access` already imports `models/repo`), so the function is effectively re-implemented in place: read the `access` table once, then delegate the team-member lookup to the helper for both the "write on any repo unit" and "read on PullRequests" cases.

Happy to move `GetRepoAssignees` into `models/perm/access` (or another package that can import `access`) and collapse to two `GetUserIDsWithUnitAccess` calls instead if you'd prefer that shape — that touches ~12 callers across `routers/` and `models/`. Let me know which direction you want.

**Comment by wxiaoguang** [comment]
Are you sure `GetRepoAssignees` is not right? It already calls `GetTeamUserIDsWithAccessToAnyRepoUnit`, the SQL already uses `team.authorize`

The SQL you showed ``Join("INNER", "team_unit", "`team_unit`.team_id = `team_user`.team_id").`` doesn't belong to `GetRepoAssignees` either.

image

**Comment by pisarz77** [comment]
Good catch — the same raw `team_user × team_unit` JOIN existed in `GetOrgAssignees` (org-level assignee picker, e.g. org Kanban project boards) and `services/pull.GetReviewers` (PR reviewer picker). Extended the PR to cover all three call sites:

- `GetRepoAssignees` (per-repo) → `GetTeamUserIDsWithAccessToAnyRepoUnit`
- `GetReviewers` (per-repo, PR) → same helper
- `GetOrgAssignees` (org-wide) → new sibling helper `GetTeamUserIDsWithAccessToAnyRepoUnitInOrg` (same OR logic, no per-repo filter)

Also picked up a pre-existing guard in `GetOrgAssignees` that skipped the final user lookup when the direct-access list was empty but the team-based list wasn't.

`TestRepoAssignees`, `TestRepoGetReviewers`, `TestRepoGetReviewerTeams` all pass locally. No schema changes.

**Comment by wxiaoguang** [comment]
The changed `GetOrgAssignees` and newly added `GetTeamUserIDsWithAccessToAnyRepoUnitInOrg` actually is not right.

```
// GetOrgAssignees returns all users that have write access and can be assigned to issues
// of the any repository in the organization.
func GetOrgAssignees(ctx context.Context, orgID int64) (_ []*user_model.User, err error) {
```

What if user-a has no access to repo-1? Actually the design here is totally a mess and no clear fix:

* org-level project can contain any issue from any repo
* some users have access to repo-1 , but not repo-2, while some users can be on the contrary.

**Comment by wxiaoguang** [comment]
To make things simple, it can simpliy list all org members for the "project assignee list"

```
assigneeUsers, err := org_model.GetOrgAssignees(ctx, project.OwnerID) -> change it to list all members
```

**Comment by wxiaoguang** [comment]
OK, even simpler, since you already have all issues for all project columns, so you should already be able to know all assignees here.

**Review by wxiaoguang — APPROVED** [review]

**Comment by silverwind** [comment]
Some cleanups and a test in https://github.com/go-gitea/gitea/pull/37365/changes/b7ccc56d47ab518a0b36184c8212e5327612c29b.

**Review by silverwind — APPROVED** [review]

**Review by lunny — APPROVED** [review]

File: models/repo/user_repo.go [hunk 1]
```diff
@@ -114,15 +115,9 @@ func GetRepoAssignees(ctx context.Context, repo *Repository) (_ []*user_model.Us
...
-		additionalUserIDs := make([]int64, 0, 10)
-		if err = e.Table("team_user").
-			Join("INNER", "team_repo", "`team_repo`.team_id = `team_user`.team_id").
-			Join("INNER", "team_unit", "`team_unit`.team_id = `team_user`.team_id").
-			Where("`team_repo`.repo_id = ? AND (`team_unit`.access_mode >= ? OR (`team_unit`.access_mode = ? AND `team_unit`.`type` = ?))",
-				repo.ID, perm.AccessModeWrite, perm.AccessModeRead, unit.TypePullRequests).
-			Distinct("`team_user`.uid").
-			Select("`team_user`.uid").
-			Find(&additionalUserIDs); err != nil {
+		// Helper also matches via team.authorize, so owner/admin team members are included even when their team_unit.access_mode is 0.
```
Comment (wxiaoguang) [inline models/repo/user_repo.go]:
```suggestion
```

File: services/pull/reviewer.go [hunk 2]
```diff
@@ -40,15 +40,9 @@ func GetReviewers(ctx context.Context, repo *repo_model.Repository, doerID, post
...
-		additionalUserIDs := make([]int64, 0, 10)
-		if err := e.Table("team_user").
-			Join("INNER", "team_repo", "`team_repo`.team_id = `team_user`.team_id").
-			Join("INNER", "team_unit", "`team_unit`.team_id = `team_user`.team_id").
-			Where("`team_repo`.repo_id = ? AND (`team_unit`.access_mode >= ? AND `team_unit`.`type` = ?)",
-				repo.ID, perm.AccessModeRead, unit.TypePullRequests).
-			Distinct("`team_user`.uid").
-			Select("`team_user`.uid").
-			Find(&additionalUserIDs); err != nil {
+		// Helper also matches via team.authorize, so owner/admin team members are included even when their team_unit.access_mode is 0.
```
Comment (wxiaoguang) [inline services/pull/reviewer.go]:
```suggestion
```
