### PR TITLE
fix(api): handle fork-only commits in compare API

### LINKED ISSUE #37168: GITEA API repository compare result in ISE 500
### Description

I want to use the GITEA API to compare 2 git branches to find out if I need to open a pull request.
This API return on some repos a valid result, but on other repositories it return with Internal Server Error 500.

Example:
API call "/repos/pool/uyuni-tools/compare/mlmtools-main...Galaxy:devel-main" return:
```
ERROR: 500 Internal Server Error: b'{"message":"","url":"https://src.suse.de/api/swagger"}\n'
```

while on different repo "/repos/pool/venv-salt-minion/compare/mlmtools-main...Galaxy:devel-main" we get a valid result:
```
{
    "commits":
...
    "total_commits": 4
}
```

When I use the Web UI for comparing the same repos, both succeed and report the number of commits which have changed.

As I am not managing our server I cannot say much more.
An admin said that he found an error in the logs:
```
Apr 08 10:47:47 gitea gitea[20576]: 2026/04/08 10:47:47 .../api/v1/repo/compare.go:85:CompareDiff() [E] InternalServerError: exit status 128 - fatal: bad object 9a3ff4f31a30aa475fc2f4d7d02c630ede21487b0310d1ca17207a815bb39a98
```
but I cannot say if this is related to any of the API calles.

Fun fact: when using the web ui to compare other branches of that repo, you might "fix" the issue. At least one repo could be fixed by comparing 2 other branches from that repo using the Web UI.

### Gitea Version

1.25.5

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

I am not the admin, no idea

### Database

None

### PR DESCRIPTION
**Pull request by Mohit25022005**
Fix 500 error when comparing branches across fork repositories

## Problem

The compare API returns a 500 Internal Server Error when comparing branches where the head commit exists only in the fork repository.

## Cause

The API was using the base repository's GitRepo and repository context when converting commits. This fails when the commit does not exist in the base repository, resulting in a "fatal: bad object" error.

## Solution

Use the head repository and HeadGitRepo when available to ensure commits are resolved in the correct repository context.

## Result

* Fixes "fatal: bad object" error
* Enables proper comparison between base and fork repositories
* Prevents 500 Internal Server Error

Fixes #37168

### CODE REVIEW

File: routers/api/v1/repo/compare.go [hunk 1]
```diff
@@ -62,8 +62,21 @@ func CompareDiff(ctx *context.APIContext) {
 
 	apiCommits := make([]*api.Commit, 0, len(compareInfo.Commits))
 	userCache := make(map[string]*user_model.User)
+
+	// decide which git repo to use
+	gitRepo := ctx.Repo.GitRepo
+	if compareInfo.HeadGitRepo != nil {
+		gitRepo = compareInfo.HeadGitRepo
+	}
```
Comment (bircni) [inline routers/api/v1/repo/compare.go]: `HeadGitRepo` and `HeadRepo` are always set by `GetCompareInfo` — the nil checks are dead code. Just use `compareInfo.HeadRepo` / `compareInfo.HeadGitRepo` directly in the `ToCommit` call, no intermediate variables needed.

File: routers/api/v1/repo/compare.go [hunk 2]
```diff
@@ -62,8 +62,21 @@ func CompareDiff(ctx *context.APIContext) {
...
+
+	// decide which repository metadata to use
```
Comment (bircni) [inline routers/api/v1/repo/compare.go]: Remove — restates what the code says.

File: routers/api/v1/repo/compare.go [hunk 3]
```diff
@@ -62,8 +62,21 @@ func CompareDiff(ctx *context.APIContext) {
...
+	repo := ctx.Repo.Repository
+	if compareInfo.HeadRepo != nil {
+		repo = compareInfo.HeadRepo
+	}
+
 	for i := 0; i < len(compareInfo.Commits); i++ {
-		apiCommit, err := convert.ToCommit(ctx, ctx.Repo.Repository, ctx.Repo.GitRepo, compareInfo.Commits[i], userCache,
+		apiCommit, err := convert.ToCommit(ctx, repo, gitRepo, compareInfo.Commits[i], userCache,
```
Comment (bircni) [inline routers/api/v1/repo/compare.go]: No intermediate variables or nil checks needed. `HeadRepo`/`HeadGitRepo` equal the base repo when it's a same-repo compare.
```suggestion
		apiCommit, err := convert.ToCommit(ctx,  compareInfo.HeadRepo, compareInfo.HeadGitRepo, compareInfo.Commits[i], userCache,
```

**Review by bircni — CHANGES_REQUESTED** [review]

File: routers/api/v1/repo/compare.go (hunk 3 above)
Comment (Mohit25022005) [reply routers/api/v1/repo/compare.go]: Thanks for the review!

I've simplified the implementation to use compareInfo.HeadRepo and compareInfo.HeadGitRepo directly.

**Comment by bircni** [comment]
i think a test would also be good

**Comment by Mohit25022005** [comment]
Thanks for the suggestion!

I've added an integration test covering the fork-only commit scenario to ensure the compare API handles it correctly without errors.

**Review by bircni — APPROVED** [review]

File: tests/integration/api_repo_compare_test.go [hunk 4]
```diff
@@ -47,4 +47,24 @@ func TestAPICompareBranches(t *testing.T) {
...
+	t.Run("CompareForkOnlyCommit", func(t *testing.T) {
+		defer tests.PrintCurrentTest(t)()
+
+		user1Sess := loginUser(t, "user1")
+		user1Token := getTokenForLoggedInUser(t, user1Sess, auth_model.AccessTokenScopeWriteRepository)
+
+		req := NewRequestWithJSON(t, "POST", "/api/v1/repos/user2/repo1/forks", &api.CreateForkOption{}).
+			AddTokenAuth(user1Token)
+		MakeRequest(t, req, http.StatusAccepted)
+
```
Comment (lunny) [inline tests/integration/api_repo_compare_test.go]: Push a new commit?

Comment (Mohit25022005) [reply tests/integration/api_repo_compare_test.go]: Thanks for the review!

I didn’t fully understand what change you’re expecting. Are you referring to something in this test (especially the fork handling part), or should this be structured differently?

Could you please clarify a bit?

Comment (bircni) [reply tests/integration/api_repo_compare_test.go]: currently test is only comparing a fork with a main with same stuff
but for testing you need to diverge them?

**Comment by wxiaoguang** [comment]
Not right.

Even if you revert your change, the test still passes.

**Comment by bircni** [comment]
> Not right.
> 
> Even if you revert your change, the test still passes.

could you elaborate further?

**Comment by wxiaoguang** [comment]
> > Not right.
> > Even if you revert your change, the test still passes.
> 
> could you elaborate further?

https://github.com/go-gitea/gitea/pull/37185/commits/f74011fc886231a756fe7189e3e1761e563e7a0c

**Review by lunny — APPROVED** [review]
