### PR TITLE
Restore PAM user autocreation functionality

### LINKED ISSUE #15702: pam.d authentication fails
- Gitea version (or commit ref): 1.15.0+dev-206-gae6d7860b
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:

## Description

Authentication via pam.d krb5 module fails with error

`...dels/login_source.go:831:UserSignIn() [W] Failed to login 'USERID' via 'systemusers': e-mail invalid [email: USERID]`

### PR DESCRIPTION
**Pull request by zeripath**
PAM autoregistration of users currently fails due to email invalidity.
This PR adds a new setting to PAM to allow an email domain to be set
or just sets the email to the noreply address and if that fails falls
back to uuid@localhost

Fix #15702

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: models/login_source.go [hunk 1]
```diff
@@ -696,15 +698,26 @@ func LoginViaPAM(user *User, login, password string, sourceID int64, cfg *PAMCon
...
+	email := pamLogin
 	idx := strings.Index(pamLogin, "@")
 	if idx > -1 {
 		username = pamLogin[:idx]
 	}
+	if ValidateEmail(email) != nil {
+		if cfg.EmailDomain != "" {
+			email = fmt.Sprintf("%s@%s", pamLogin, cfg.EmailDomain)
+		} else {
+			email = fmt.Sprintf("%s@%s", pamLogin, setting.Service.NoReplyAddress)
```
Comment (KN4CK3R) [inline models/login_source.go]: Is `pamLogin` a good choice for the email? Line 699 states it can contain `@`. `username` contains the stripped name, so maybe `{username}@...` is better?

**Review by KN4CK3R — APPROVED** [review]

**Review by noerw — APPROVED** [review]

**Comment by zeripath** [comment]
Make lgtm work
