### PR TITLE
Transaction-aware retry create issue to cope with duplicate keys

### LINKED ISSUE #7887: models/issue.go NewIssue() could fail due to duplicate key
The current code for `models/issue.go` roughly does:

```
func getMaxIndexOfIssue(e Engine, repoID int64) (int64, error) {
    var (
        maxIndex int64
        has      bool
        err      error
    )

    has, err = e.SQL("SELECT COALESCE((SELECT MAX(`index`) FROM issue WHERE repo_id = ?),0)", repoID).Get(&maxIndex)

   [...]

    return maxIndex, nil
}

func newIssue(e *xorm.Session, doer *User, opts NewIssueOptions) (err error) {
	opts.Issue.Title = strings.TrimSpace(opts.Issue.Title)

	maxIndex, err := getMaxIndexOfIssue(e, opts.Issue.RepoID)
	if err != nil {
		return err
	}
	opts.Issue.Index = maxIndex + 1

   [...]

	if _, err = e.Insert(opts.Issue); err != nil {
		return err
	}

   [...]
}
```

It's possible that under heavy loads (e.g. a small server) two sessions may attempt to use the same index number to create issues; one of the two will fail due to a race condition:

1. User **A** submits the form creating an issue for repo abc.
2. User **B** submits the form creating another issue for repo abc.
3. At `issue.go`, in the context of user **A**'s request, `getMaxIndexOfIssue()` returns `99`. It will be used at step *5*.
4. At `issue.go`, in the context of user **B**'s request, `getMaxIndexOfIssue()` also returns `99`. because at the moment that's the latest issue for the repo. It will be used at step *6*.
5. At `issue.go`, in the context of user **A**'s request, `newIssue()` inserts **A**'s issue with `Index: 100`.
6. At `issue.go`, in the context of user **B**'s request, `newIssue()` attempts to insert **B**'s issue with `Index: 100` and fails with `duplicate key error`, because `100` was used at step *5*.

This will of course depend on the database locking model.

I think the best way to handle this is to use a mutex, thus covering most scenarios.

### PR DESCRIPTION
**Pull request by guillep2k**
This PR is a new approach to fix #7887 in replace of #7898, bacause that solution caused other problems (#8302) and it didn't really work.

This time, the whole transaction for the issue creation is retried in case of error (not just the INSERT statement), but _only_ if the error occurs precisely while attempting the INSERT.

Sorry about the tongue-twister description.

It's using INSERT ... WHERE again, now that #8301 was solved.

### CODE REVIEW

**Comment by guillep2k** [comment]
The effect of this PR is easier to follow by looking just at the last commit:
https://github.com/go-gitea/gitea/pull/8307/commits/c786930c12ea83f7706f56c94794f4eed07f143b
(previous commits only revert the old PR)

**Comment by guillep2k** [comment]
Closes #8301 
Closes #8302

**Comment by guillep2k** [comment]
I'll update this to use INSERT ... WHERE again, now that it's corrected.

**Comment by guillep2k** [comment]
Ready for review.

File: models/issue.go [hunk 1]
```diff
@@ -1225,7 +1232,12 @@ func NewIssue(repo *Repository, issue *Issue, labelIDs []int64, assigneeIDs []in
 	}
 	sess.Close()
 
-	if err = NotifyWatchers(&Action{
+	return nil
+}
+
+// newIssuePostInsert performs issue creation operations that need to be separate transactions
+func newIssuePostInsert(issue *Issue, repo *Repository) error {
```
Comment (lunny) [inline models/issue.go]: I think we should move the events handle codes out of models at first. That's my PR #8217 did.

Comment (guillep2k) [reply models/issue.go]: OK; would you like to make this PR dependent of #8217 ?

Comment (lunny) [reply models/issue.go]: @guillep2k I think maybe you could review #8217 at first. 😅

Comment (guillep2k) [reply models/issue.go]: @lunny  Done

File: models/issue.go [hunk 2]
```diff
@@ -1201,6 +1190,22 @@ func newIssue(e *xorm.Session, doer *User, opts NewIssueOptions) (err error) {
 
 // NewIssue creates new issue with labels for repository.
 func NewIssue(repo *Repository, issue *Issue, labelIDs []int64, assigneeIDs []int64, uuids []string) (err error) {
+	// Retry several times in case INSERT fails due to duplicate key for (repo_id, index); see #7887
+	i := 0
+	for {
+		if err = newIssueAttempt(repo, issue, labelIDs, assigneeIDs, uuids); !IsErrNewIssueInsert(err) {
+			// Usually err == nil
+			return err
+		}
```
Comment (lunny) [inline models/issue.go:1201]: if err == nil {
  return
}

**Review by lunny — CHANGES_REQUESTED** [review]

File: models/pull.go [hunk 3]
```diff
@@ -657,6 +657,22 @@ func (pr *PullRequest) testPatch(e Engine) (err error) {
...
 // NewPullRequest creates new pull request with labels for repository.
 func NewPullRequest(repo *Repository, pull *Issue, labelIDs []int64, uuids []string, pr *PullRequest, patch []byte, assigneeIDs []int64) (err error) {
+	// Retry several times in case INSERT fails due to duplicate key for (repo_id, index); see #7887
+	i := 0
+	for {
+		if err = newPullRequestAttempt(repo, pull, labelIDs, uuids, pr, patch, assigneeIDs); !IsErrNewIssueInsert(err) {
+			// Usually err == nil
+			return err
+		}
+		if i++; i == issueMaxDupIndexAttempts {
```
Comment (lunny) [inline models/pull.go:669]: As above.

**Review by lunny — CHANGES_REQUESTED** [review]

File: models/issue.go (hunk 2 above)
Comment (guillep2k) [reply models/issue.go:1201]: @lunny have you noticed that the condition is `!IsErrNewIssueInsert(err)`? If you want me to open it it multiple lines, it will then be:
```
if err = newIssueAttempt(repo, issue, labelIDs, assigneeIDs, uuids); err == nil {
	return nil
}
if !IsErrNewIssueInsert(err) {
	return err
}
```
I just thought it was shorter. Should I change it anyway?

Comment (lunny) [reply models/issue.go:1201]: @guillep2k I think the new one is correct but the old one is not correct even it was shorter.

Comment (guillep2k) [reply models/issue.go:1201]: @lunny  OK, done.

File: models/issue.go [hunk 4]
```diff
@@ -1104,21 +1104,10 @@ func newIssue(e *xorm.Session, doer *User, opts NewIssueOptions) (err error) {
...
-		}
-
-		dupIndexAttempts--
-		if dupIndexAttempts <= 0 {
-			return err
-		}
+	if _, err := e.SetExpr("`index`", "coalesce(MAX(`index`),0)+1").
+		Where("repo_id=?", opts.Issue.RepoID).
+		Insert(opts.Issue); err != nil {
+		return err
```
Comment (sapk) [inline models/issue.go]: Shouldn't err be wrap around ErrNewIssueInsert ?
```suggestion
		return ErrNewIssueInsert{err}
```

Comment (guillep2k) [reply models/issue.go]: Oh, man! Gross oversight on my part. Sorry. That's what happens when you move code around without using git.
Give me a minute; I'll check this properly (I need to artificially produce an error for that).

Comment (guillep2k) [reply models/issue.go]: @sapk fixed, checked and tested. I've used a trigger to produce the fail artificially:
```
CREATE OR REPLACE FUNCTION make_insert_fail()
  RETURNS trigger AS 
$BODY$
DECLARE
    is_longer_than_max_length BOOLEAN;
BEGIN
    RAISE EXCEPTION 'Error produced by BEFORE INSERT TRIGGER insert_fail.' USING ERRCODE='20808';
END
$BODY$
  LANGUAGE 'plpgsql' SECURITY INVOKER
;

CREATE TRIGGER insert_fail BEFORE INSERT ON issue
FOR EACH ROW EXECUTE PROCEDURE make_insert_fail();
```

Then, when attempting to create an issue, I've got in the log:
```
2019/10/01 13:25:47 models/issue.go:1205:NewIssue() [E] NewIssue: error attempting to insert the new issue; will retry. Original error: pq: Error produced by BEFORE INSERT TRIGGER insert_fail.
2019/10/01 13:25:47 models/issue.go:1205:NewIssue() [E] NewIssue: error attempting to insert the new issue; will retry. Original error: pq: Error produced by BEFORE INSERT TRIGGER insert_fail.
2019/10/01 13:25:47 ...outers/repo/issue.go:580:NewIssuePost() [E] NewIssue: NewIssue: too many errors attempting to insert the new issue. Last error was: pq: Error produced by BEFORE INSERT TRIGGER insert_fail.
```

For a pull request:
```
2019/10/01 13:29:07 models/pull.go:672:NewPullRequest() [E] NewPullRequest: error attempting to insert the new issue; will retry. Original error: pq: Error produced by BEFORE INSERT TRIGGER insert_fail.
2019/10/01 13:29:07 models/pull.go:672:NewPullRequest() [E] NewPullRequest: error attempting to insert the new issue; will retry. Original error: pq: Error produced by BEFORE INSERT TRIGGER insert_fail.
2019/10/01 13:29:07 routers/repo/pull.go:796:CompareAndPullRequestPost() [E] NewPullRequest: NewPullRequest: too many errors attempting to insert the new issue. Last error was: pq: Error produced by BEFORE INSERT TRIGGER insert_fail.
```

On the screen:

image

**Everything worked correctly** when I disabled the trigger:

```
alter table issue disable trigger insert_fail;
```

**Review by sapk — APPROVED** [review]

**Review by lunny — APPROVED** [review]
