### PR TITLE
api: fix multiple bugs with statuses endpoints

### LINKED ISSUE #7784: API call (commits/{ref}/statuses) dont work
- Gitea version (or commit ref): 1.9.0 Stable
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.2 LTS (GNU/Linux 4.18.0-21-generic x86_64)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

curl -X GET "https://try.gitea.io/api/v1/repos/gitea/gitea/commits/master/statuses" -H "accept: application/json"

## Description
if i make an API call with "/repos/{owner}/{repo}/commits/{ref}/statuses" i get only an empty output back.

## Screenshots
Screenshot_107
Screenshot_106
Screenshot_105

### PR DESCRIPTION
**Pull request by sapk**
Fix #7784 and more.

### CODE REVIEW

File: routers/api/v1/repo/status.go [hunk 1]
```diff
@@ -155,9 +152,39 @@ func GetCommitStatusesByRef(ctx *context.APIContext) {
...
+	}
+
+	for _, reftype := range []string{"heads", "tags"} { //Search branches and tags
+		refSHA, lastMethodName, err := searchRefCommitByType(ctx, reftype, filter)
+		if err != nil {
+			ctx.Error(500, lastMethodName, err)
+			return
+		}
+		if refSHA != "" {
+			getCommitStatuses(ctx, refSHA)
```
Comment (lafriks) [inline routers/api/v1/repo/status.go]: imho this would be better so that there is only one place where `getCommitStatuses` is called
```suggestion
			filter = refSHA
			break
```

**Review by lafriks — CHANGES_REQUESTED** [review]

File: routers/api/v1/repo/status.go [hunk 2]
```diff
@@ -155,9 +152,39 @@ func GetCommitStatusesByRef(ctx *context.APIContext) {
...
+func searchRefCommitByType(ctx *context.APIContext, refType, filter string) (string, string, error) {
+	refs, lastMethodName, err := getGitRefs(ctx, refType+"/"+filter) //Search by type
+	if err != nil {
+		return "", lastMethodName, err
+	}
+	if len(refs) > 0 {
+		return refs[0].Object.String(), "", nil //Return found SHA
+	}
+	return "", "", nil
+}
```
Comment (lafriks) [inline routers/api/v1/repo/status.go:187]: nit
```suggestion
}

```

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work

**Comment by lunny** [comment]
@sapk Please send back port
