### PR TITLE
Fix bug because of duplicated join

### LINKED ISSUE #14448: [Bug] 500 error when searching issues with type=your_repository
- Gitea version (or commit ref): 1.14.0+dev-604-gbc05ddc0e
- Git version: 
- Operating system: Windows
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io: 
  - [X] Yes https://try.gitea.io/issues?type=your_repositories&repos=%5B%5D&sort=&state=open&q=test
  - [ ] No
- Log gist:
https://gist.github.com/kdumontnu/36b418034d7546da09eaed066450627e

## Description

When searching issues from my user page (i.e. title-bar -> Issues -> Search, searching anything returns a 500 error for me. I've tested this locally and on the try.gitea server. 

When I run locally with debug logging I get the following additional output:
`GetRepoIDsForIssuesOptions: pq: table name "repository" specified more than once`
From the logs attached, it appears this is returned from `routers/user/home.go:453:buildIssueOverview()`

## Screenshots

image

### PR DESCRIPTION
**Pull request by lunny**
Fix #14448

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

File: models/issue.go [hunk 1]
```diff
@@ -1210,7 +1210,7 @@ func (opts *IssuesOptions) setupSession(sess *xorm.Session) {
 	}
 
 	if opts.IsArchived != util.OptionalBoolNone {
-		sess.Join("INNER", "repository", "issue.repo_id = repository.id").And(builder.Eq{"repository.is_archived": opts.IsArchived.IsTrue()})
```
Comment (techknowlogick) [inline models/issue.go:1213]: CI fail as `repository` for `repository.is_archived` is not yet defined (due to it being defined in the join). This conditional needs to be below where the join is set

File: models/issue.go [hunk 2]
```diff
@@ -1210,7 +1210,8 @@ func (opts *IssuesOptions) setupSession(sess *xorm.Session) {
...
+		sess.Join("INNER", "repository", "`issue`.repo_id = `repository`.id").
```
Comment (jpraet) [inline models/issue.go]: When the method is called with opts.IsArchived = util.OptionalBoolNone, won't the absence of the join cause a problem in GetRepoIDsForIssuesOptions()?

Comment (lunny) [reply models/issue.go]: Fixed

**Review by lafriks — APPROVED** [review]
