### PR TITLE
Make actions URL in commit status webhooks absolute

### LINKED ISSUE #33603: Discord "Commit Status" Webhooks Are Broken
### Description

Gitea's commit status webhooks are malformed and thus rejected by Discord. This is because it only provides a relative URL (like `/minecraft-pi-reborn/runtime/actions/runs/7/jobs/1`) instead of a full URL (like `https://gitea.thebrokenrail.com/minecraft-pi-reborn/runtime/actions/runs/7/jobs/1`). The issue seems to be caused by [this line](https://github.com/go-gitea/gitea/blob/1ba7cbbfd6bb758b5c3796dfe46fa688dc20b5d1/services/webhook/matrix.go#L248).

### Gitea Version

1.23.3

### Can you reproduce the bug on the Gitea demo site?

Probably. But I do not have the time to set up an additional Gitea Actions runner just to test a webhook.

### Log Gist

_No response_

### Screenshots

After manually modifying the request, it worked:

Image

BTW this should probably just use the short commit hash.

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Using the official Gitea Docker image.

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Gitea Actions generated target url doesn't contain host and port. So we need to include them for external webhook visiting.

Fix #33603

### CODE REVIEW

**Review by yp05327 — APPROVED** [review]

**Review by delvh — APPROVED** [review]

File: services/webhook/notifier.go [hunk 1]
```diff
@@ -871,14 +872,22 @@ func (m *webhookNotifier) CreateCommitStatus(ctx context.Context, repo *repo_mod
 		return
 	}
 
+	// as a webhook url, target should be an absolute url. But for internal actions target url
+	// the target url is a url path with no host and port to make it easy to be visited
+	// from multiple hosts. So we need to convert it to an absolute url here.
+	target := status.TargetURL
+	if strings.HasPrefix(target, "/") {
+		target = setting.AppURL + strings.TrimPrefix(target, "/")
+	}
```
Comment (wxiaoguang) [inline services/webhook/notifier.go]: It could simply use `MakeAbsoluteURL`, then no need to use these tricks.

And the `TargetURL` should already have the "subpath" prefix (`TargetURL:   fmt.Sprintf("%s/jobs/%d", run.Link(), index),`), using `AppURL+target` causes duplicate subpath.

image

Comment (lunny) [reply services/webhook/notifier.go]: 8f80089a3c
