### PR TITLE
Fix sending mail with a non-latin display name. #2102

### LINKED ISSUE #2102: Cannot send mail after merge when Username contains UTF8 character
- Gitea version (or commit ref): 1.1.2
- Git version: git version 2.13.0.windows.1
- Operating system: Windows Server 2016 Standard
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant (cannot view logs)
- Log gist:
2017/07/03 12:14:19 [...les/mailer/mailer.go:244 processMailQueue()] [E] Failed to send emails [username@mycompany.com]: Subject: [Project] description (#16), issue comment - gomail: could not send email 1: gomail: invalid address "=?UTF-8?q?\"P=C3=A9ter\"_<git@mycompany.com>?=": mail: expected single address, got "?="

## Description
After merging a commit in one of our repositories, I saw this in the log, which says it was unable to deliver the notification. 

> P=C3=A9ter

 Should be 

> Péter

 which is used as the Full name for that user (acquired through Active Directory), so I think the latin/utf8 character 

> é

causes the mentioned error.

### PR DESCRIPTION
**Pull request by rems4e**
Signed-off-by: Rémi Saurel <contact@remi-saurel.com>

This pull request fixes #2102, where display name of email addresses containing non-latin characters cannot be used in the From: field when creating/updating issues (resulting in no email sent at all).

The fix is simple, it uses `Message.SetAddressHeader`, instead of `Message.SetHeader` with a custom-formatted `DisplayName <email@address>` from address.

### CODE REVIEW

File: modules/mailer/mailer.go [hunk 1]
```diff
@@ -58,7 +58,7 @@ func NewMessageFrom(to []string, from, subject, body string) *Message {
 
 // NewMessage creates new mail message object with default From header.
 func NewMessage(to []string, subject, body string) *Message {
-	return NewMessageFrom(to, setting.MailService.From, subject, body)
+	return NewMessageFrom(to, setting.MailService.From, "", subject, body)
```
Comment (lafriks) [inline modules/mailer/mailer.go]: But as stated in https://github.com/go-gitea/gitea/blob/master/conf/app.ini#L312 From can be in format `"Sender" <sender@domain.ext>` so it should be parsed somehow and passed in both arguments

**Review by lafriks — CHANGES_REQUESTED** [review]

**Comment by rems4e** [comment]
@lafriks OK, I overlooked this part. But parsing must also be done here too:

https://github.com/go-gitea/gitea/pull/2559/files#diff-91afb18937651f768645eff6cf5779a8R169

and keeping only the address part.

I will look into this.


**EDIT** Nevermind, the place I pointed uses `setting.MailService.FromEmail`.

**Comment by lafriks** [comment]
@rems4e it actually already parses it here:
https://github.com/go-gitea/gitea/blob/master/modules/setting/setting.go#L1344

so probably new type field needs to be added `FromDisplayName` and assigned in same place where `FromEmail` is set and than it can be reused in your code

**Comment by rems4e** [comment]
@lafriks Yes, see my edit above, it was my mistake and I managed to follow the track too ^^

**Comment by rems4e** [comment]
This time it should be cleaner.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
LGTM

**Comment by ethantkoenig** [comment]
LGTM

**Comment by ptman** [comment]
Any chance of getting this backported to 1.2.x?

**Comment by lunny** [comment]
seems it's not difficult.
