### PR TITLE
Fix the protected branch panic issue

### LINKED ISSUE #3326: Protected branches causes 500 Internal Server Error
When browsing a repository while not logged in with a protected branch, a '500 Internal Server Error' is thrown when selecting 'branches'

- Gitea version (or commit ref): 1.3.0 & 1.3.2
- Git version: 2.7.4
- Operating system: Linux (Ubuntu 16.04)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/indyspike/test_repo/branches/
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

### PR DESCRIPTION
**Pull request by xwjdsh**
Fixes #3326

### CODE REVIEW

File: routers/repo/branch.go [hunk 1]
```diff
@@ -148,10 +148,13 @@ func loadBranches(ctx *context.Context) []*Branch {
 			return nil
 		}
 
-		isProtected, err := ctx.Repo.Repository.IsProtectedBranch(rawBranches[i].Name, ctx.User)
-		if err != nil {
-			ctx.ServerError("IsProtectedBranch", err)
-			return nil
+		var isProtected bool
```
Comment (lunny) [inline routers/repo/branch.go]: isProtected maybe default `true`?

**Review by lunny — CHANGES_REQUESTED** [review]

File: routers/repo/branch.go (hunk 1 above)
Comment (sapk) [reply routers/repo/branch.go]: I think it would be better to add a check before https://github.com/go-gitea/gitea/blob/19bf4ddf800dd405bddbafee7574ff4df07ed275/models/branches.go#L167 
If we are here and user is nil -> return true, nil

Comment (sapk) [reply routers/repo/branch.go]: This will fix this for any use case of IsProtectedBranch

Comment (xwjdsh) [reply routers/repo/branch.go]: Yes, I thought so once, but the bad thing is the IsProtectedBranch function will be invoked multi-times redundantly.

Comment (sapk) [reply routers/repo/branch.go]: So simply do at start of func as it would be the same.
```
if doer  == nil {
  return true, nil
}
```

**Review by lunny — APPROVED** [review]

File: routers/repo/branch.go (hunk 1 above)
Comment (xwjdsh) [reply routers/repo/branch.go]: OK, I updated, thanks.

**Review by appleboy — APPROVED** [review]

**Review by sapk — APPROVED** [review]

**Comment by lafriks** [comment]
I think this should be backported to `release/v1.4` branch
