### PR TITLE
Imrove scroll behavior to hash issuecomment(scroll position, auto expand if file is folded, and on refreshing)

### LINKED ISSUE #23466: PR comment link on viewed files not scrolling
### Description

When reviewing a file it is very common for the reviewer to mark these files as "viewed" 
When you now get a link to a comment in a file you already viewed you can't properly open that link because the anchor tag is missing.

Steps to reproduce:
1. Make a PR
2. Add a comment
3. Copy link of the comment (via the 3 dots menu)
4. Mark the file as viewed
5. Open the link

You will land at the top of the PR instead of at the comment.

My example:

https://try.gitea.io/gempir/gempbot/pulls/1/files#issuecomment-163257

First time you will land on the comment 
> Some comment on a file that is already marked as "viewed" for the user opening the link Previous Next

When you now mark that file as viewed you will not land on that comment anymore when you are opening the link above.
(See first screenshot)

Also minor nitpick: The Anchor lands directly on the text of the comment, not a little above, so it's very "cramped". (See second screenshot)

### Gitea Version

1.20.0+dev-163-gd56bb7420

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

https://try.gitea.io/

### Database

None

### PR DESCRIPTION
**Pull request by HesterG**
Close #23466
Right now on pull request "files Changed" tab, if a file is viewed, when the comments' links are visited, the comment will not be shown as the file is folded after viewed. This PR is to improve the behavior, to make the comment seen even the related file is folded, like on github.

And right now scroll position will be remembered and hence it won’t scroll to hashed comment after refreshing, this PR also adjust the scroll position remembering behavior: When there is hash comment in url, do not remember the scroll position.

Before:

https://user-images.githubusercontent.com/17645053/225512079-6cf79581-9346-44cf-95d6-06919642e6a8.mov

After:

https://user-images.githubusercontent.com/17645053/225523753-3f6728f2-977b-4ed0-a65c-63dcef2ace80.mov

Update - long comment's behavior after using `scrollTop ` (Comment div scroll to the position which is 30px below the diff header, or 30px below top on conversation tab):

https://user-images.githubusercontent.com/17645053/225614460-0602c1a6-229c-41f4-84d2-334e78251486.mov

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by yp05327** [comment]
When non-login users access, it is still a bit strange. Is it possible to fix it in this PR?
width 600:
image
width 1500:
image
But after refresh, it becomes correct:
image

Ah, login user with viewed comment also have this issue:
width 600:
image
width 1500:
image
(Refresh dones't work)

**Comment by HesterG** [comment]
> When non-login users access, it is still a bit strange. Is it possible to fix it in this PR? width 600: image width 1500: image But after refresh, it becomes correct: image
> 
> Ah, login user with viewed comment also have this issue: width 600: image width 1500: image (Refresh dones't work)

I am not sure what is the specific issue, can you specify?

**Comment by yp05327** [comment]
It will be out of alignment with some special the window width.

> Also minor nitpick: The Anchor lands directly on the text of the comment, not a little above, so it's very "cramped". (See second screenshot)
image

**Comment by HesterG** [comment]
> It will be out of alignment with some special window width.
> 
> > Also minor nitpick: The Anchor lands directly on the text of the comment, not a little above, so it's very "cramped". (See second screenshot)
> > image

I cannot reproduce this after applying this PR. In these lines:
```
commentDiv[0].scrollIntoView({
  behavior: 'auto',
  block: 'center',
  inline: 'center'
});
```
The comment div will be scrolled to the middle of the screen.

**Comment by HesterG** [comment]
> It will be out of alignment with some special window width.
> 
> > Also minor nitpick: The Anchor lands directly on the text of the comment, not a little above, so it's very "cramped". (See second screenshot)
> > image

I cannot reproduce this after applying this PR. The comment div will be in the middle of the screen because of these lines:
```js
commentDiv[0].scrollIntoView({
  behavior: 'auto',
  block: 'center',
  inline: 'center'
});
```

**Comment by yp05327** [comment]
You need to create a comment with multiple lines, and ensure they are long enough to be outside of the window.
image

**Comment by yp05327** [comment]
Maybe this is the real problem.
If we use `center`, when the height of window is short, it will show the middle part of this comment.
`Width` is not related, `Height` is related.
image

**Comment by HesterG** [comment]
> Maybe this is the real problem. If we use `center`, when the height of window is short, it will show the middle part of this comment. `Width` is not related, `Height` is related. image

I see. I changed the scroll to middle because the header part of the page has various height. So it might be complicated to have it scrolled exactly to the top of the comment div. Header part example:
截屏2023-03-16 16 00 22

And if we leave it as it was(`commentDiv[0].scrollIntoView({})` with no options), the div will go beneath the header
截屏2023-03-16 16 01 13

So middle might work better in most cases.

**Comment by yp05327** [comment]
In Github it seems that it works well, maybe we can fix it better as maybe it is a good example.
 (just a suggestion, not blocking, I'm sorry I know little about ui, I can't give code suggestions.)

https://github.com/yp05327/test/pull/4/files#r1138279659

**Comment by HesterG** [comment]
> In Github it seems that it works well, maybe we can fix it better? As it is a good example. (just a suggestion, not blocking, I'm sorry I know little about ui, I can't give code suggestions.)
> 
> https://github.com/yp05327/test/pull/4/files#r1138279659

It's alright, i think this can be improved. Just added a commit to use `scrolltop` instead. Feel free to try

**Comment by yp05327** [comment]
It looks awesome now.👍

**Comment by wxiaoguang** [comment]
Since this is a rewriting of old code, I guess it's better either using jQuery or use Vanilla JS ....

Now the code looks a little strange, different approaches are mixed together ....

```js
ancestorDiffBox[0]?.querySelector?.('.diff-file-header');
$('.diff-detail-box')[0].offsetHeight + diffHeader.offsetHeight;
```

File: web_src/js/features/repo-issue.js [hunk 1]
```diff
@@ -437,17 +438,33 @@ export async function handleReply($el) {
...
         $(`#show-outdated-${id}`).addClass('gt-hidden');
         $(`#code-comments-${id}`).removeClass('gt-hidden');
         $(`#code-preview-${id}`).removeClass('gt-hidden');
         $(`#hide-outdated-${id}`).removeClass('gt-hidden');
-        commentDiv[0].scrollIntoView();
+        // if the comment box is folded, expand it
+        if (ancestorDiffBox.attr('data-folded') && ancestorDiffBox.attr('data-folded') === 'true') {
+          setFileFolding(ancestorDiffBox[0], ancestorDiffBox.find('.fold-file')[0], false);
+        }
+        $('html, body').scrollTop(commentDiv.offset().top - offset);
```
Comment (wxiaoguang) [inline web_src/js/features/repo-issue.js]: Why two selectors? The `scrollTop` should be invoked on a clear target IMO.

ps: I just thought it's a good chance to rewrite all the legacy jQuery code to Vanilla JS 😂

Comment (HesterG) [reply web_src/js/features/repo-issue.js]: https://stackoverflow.com/questions/12222485/why-to-use-html-body-for-scrolltop-instead-of-just-html

For the two selectors, I saw this. I think it might be a good idea as we are also using vue, and it sometimes feels strange to have jquery at the same time. But I think I still lack an overall view to the product to comment on this right now..

Comment (wxiaoguang) [reply web_src/js/features/repo-issue.js]: But that's too old, 10 years ago ... I do not think Gitea supports so old browsers. What's the modern and proper approach, by MDN?

Comment (silverwind) [reply web_src/js/features/repo-issue.js]: I think `html` aka `document.documentElement` is sufficient, tested on try.gitea.io:

image

So if you want to scroll the page in JS to a certain offset:
```js
document.documentElement.scrollTop = value
```
Thought I generally recommend `Element.scrollIntoView()` instead of scrolling to calculated offsets, if that is an option here, but I think it isn't. Or even better, let browser-native anchor scrolling take effect.

Comment (HesterG) [reply web_src/js/features/repo-issue.js]: Yep `scrollIntoView` cannot set offset value, added a commit to use `window.scrollto`

Comment (silverwind) [reply web_src/js/features/repo-issue.js]: Sounds good as well.

**Review by silverwind — APPROVED** [review]

**Comment by gempir** [comment]
Maybe I'm missing something, but did this introduce an extra top offset that's incorrect on the sticky header?

image

Screenshot made on 46addc1f938abefd346a7a74d815f6c4faaa6818

**Comment by silverwind** [comment]
I can reproduce as well. Sorry we missed that.

**Comment by silverwind** [comment]
I see the issue, the sticky header offset needs to be changes whether the row has 1 or 2 lines. I don't think the regression is from this PR but it's actually from https://github.com/go-gitea/gitea/pull/23271. I'm preparing a fix.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/23549 will fix it.
