### PR TITLE
UI: Fix issue update race condition

### LINKED ISSUE #6191: Unable to set labels on issues
Reproduced on https://try.gitea.io/silverwind/symlink-test/issues/1, but should affect any issue. 

1. Create new issue without any labels
2. Try to set a 'bug' label by clicking it in the dropdown and closing the dropdown by clicking outside
3. Page initially shows the label, but then reloads and label is gone

Maybe related to https://github.com/go-gitea/gitea/pull/5980 @jolheiser.

### PR DESCRIPTION
**Pull request by silverwind**
https://github.com/go-gitea/gitea/pull/5980 introduced a race condition where `location.reload` would in some browers fire before the async ajax request in `updateIssuesMeta` to update a issue label was completed. Fixed this by letting `updateIssuesMeta` return a Promise and only executing the reload after all requests have finished.

Also introduced a shared `reload` function.

Fixes: https://github.com/go-gitea/gitea/issues/6191

### CODE REVIEW

File: public/js/index.js [hunk 1]
```diff
@@ -479,8 +487,7 @@ function initCommentForm() {
                     "clear",
                     $listMenu.data('issue-id'),
                     ""
-                );
-                $listMenu.data('action', 'update'); // Update to reload the page when we updated items
+                ).then(reload);
```
Comment (silverwind) [inline public/js/index.js:490]: This was the only way to make it reliably show the correct status entry on the issue. Without it I was unable to assign a issue in Firefox (clearing did work, though).

**Comment by zeripath** [comment]
Hmm... Do we have a Promise library already installed for IE?

**Comment by silverwind** [comment]
> Hmm... Do we have a Promise library already installed for IE?

Yes, we do have a Promise polyfill, but it was so far only loaded when heatmap was enabled. Just fixed that so it is always loaded.

**Comment by silverwind** [comment]
Replaced [es6-promise](https://github.com/stefanpenner/es6-promise) with [promise-polyfill](https://github.com/taylorhakes/promise-polyfill). Not sure if the former does automatically polyfill `window.Promise`, but the latter one [surely does](https://github.com/taylorhakes/promise-polyfill#cdn-polyfill-use). Testing IE now.

**Comment by silverwind** [comment]
IE11 fixed and working, it actually choked on ES6 trailing commas, took me a while to realize.

**Review by zeripath — APPROVED** [review]

File: public/js/index.js [hunk 2]
```diff
@@ -216,17 +216,19 @@ function initBranchSelector() {
...
+        $.ajax({
+            type: "POST",
+            url: url,
+            data: {
+                "_csrf": csrf,
+                "action": action,
+                "issue_ids": issueIds,
+                "id": elementId
+            },
+            success: resolve,
```
Comment (lafriks) [inline public/js/index.js]: Unneeded trailing cona

Comment (silverwind) [reply public/js/index.js]: fixed, thanks

**Review by jolheiser — APPROVED** [review]
Tested with Chrome, Firefox, and IE11 using @sapk checkout PR contrib, worked on all browsers.
