### PR TITLE
Keep download count on Container tag overwrite

### LINKED ISSUE #20722: docker registry delete download counts on push
if you push a docker image to same existing tag, download counts are erased.

to reproduce:
1. push a docker image with tag `:latest`
2. delete image local and download image -> download count shows 1
3. push a new image with tag `:latest`
4. download count is 0 again

gitea version: v1.17.0 - main

### PR DESCRIPTION
**Pull request by KN4CK3R**
fixes #20722

### CODE REVIEW

File: routers/api/packages/container/manifest.go [hunk 1]
```diff
@@ -312,6 +312,8 @@ func createPackageAndVersion(ctx context.Context, mci *manifestCreationInfo, met
 				return nil, err
 			}
 
+			_pv.DownloadCount = pv.DownloadCount
```
Comment (6543) [inline routers/api/packages/container/manifest.go:316]:
```suggestion
			// keep download count on overwrite
			_pv.DownloadCount = pv.DownloadCount
```

**Review by 6543 — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
please send backport

**Comment by lunny** [comment]
@KN4CK3R Please send backport to v1.17
