### PR TITLE
Fix bug create/edit wiki pages when code master branch protected

### LINKED ISSUE #7561: Branch protection affects wiki write permission
- Gitea version (or commit ref): 1.9.0+rc2-2-g91e24a3a1
- Git version: 2.22.0
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

```
2019/07/22 07:48:31 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT `id`, `repo_id`, `branch_name`, `can_push`, `enable_whitelist`, `whitelist_user_i_ds`, `whitelist_team_i_ds`, `enable_merge_whitelist`, `merge_whitelist_user_i_ds`, `merge_whitelist_team_i_ds`, `approvals_whitelist_user_i_ds`, `approvals_whitelist_team_i_ds`, `required_approvals`, `created_unix`, `updated_unix` FROM `protected_branch` WHERE `repo_id`=? AND `branch_name`=? LIMIT 1 []interface {}{20, "master"}
2019/07/22 07:48:31 ...ters/private/hook.go:107:HookPreReceive() [W] Forbidden: User 23 cannot push to protected branch: master in 824713418768:Integrations/pvf
2019/07/22 07:48:31 models/wiki.go:222:updateWikiPage() [E] exit status 1 - remote: Gitea: protected branch master can not be pushed to
        To /data/git/repositories/integrations/pvf.wiki.git
         ! [remote rejected] 7bd77abfa7580be79b51fa4490fafefc697440d0 -> master (pre-receive hook declined)
        error: failed to push some refs to '/data/git/repositories/integrations/pvf.wiki.git'

2019/07/22 07:48:31 routers/repo/wiki.go:425:EditWikiPost() [E] EditWikiPage: Push: exit status 1 - remote: Gitea: protected branch master can not be pushed to
        To /data/git/repositories/integrations/pvf.wiki.git
         ! [remote rejected] 7bd77abfa7580be79b51fa4490fafefc697440d0 -> master (pre-receive hook declined)
        error: failed to push some refs to '/data/git/repositories/integrations/pvf.wiki.git'
```
## Description
Got error 500 when you try to modify an existing pag einto Wiki or to create a new one.
The problem occurs only if on the default branch (usually "master") has active protection and the user attempting to modify the wiki page does not have permission to push/merge on master.
If the user permissions are modified to allow him to push on master, then he is able to modify/create wiki pages.

### PR DESCRIPTION
**Pull request by lunny**
Will fix #7561

### CODE REVIEW

**Review by zeripath — COMMENTED** [review]
It might be better to change the signature of FullPushingEnvironment etc to pass in a bool for wiki instead.

File: models/helper_environment.go [hunk 1]
```diff
@@ -12,13 +12,13 @@ import (
 
 // PushingEnvironment returns an os environment to allow hooks to work on push
 func PushingEnvironment(doer *User, repo *Repository) []string {
-	return FullPushingEnvironment(doer, doer, repo, 0)
+	return FullPushingEnvironment(doer, doer, repo.MustOwnerName(), repo.Name, repo.ID, 0)
```
Comment (zeripath) [inline models/helper_environment.go]:
```suggestion
	return FullPushingEnvironment(doer, doer, repo, false, 0)
```

File: models/helper_environment.go [hunk 2]
```diff
@@ -12,13 +12,13 @@ import (
...
 }
 
 // FullPushingEnvironment returns an os environment to allow hooks to work on push
-func FullPushingEnvironment(author, committer *User, repo *Repository, prID int64) []string {
+func FullPushingEnvironment(author, committer *User, ownerName, repoName string, repoID, prID int64) []string {
```
Comment (zeripath) [inline models/helper_environment.go]:
```suggestion
func FullPushingEnvironment(author, committer *User, repo *Repository, wiki bool, prID int64) []string {
```

File: models/helper_environment.go [hunk 3]
```diff
@@ -12,13 +12,13 @@ import (
...
 	isWiki := "false"
-	if strings.HasSuffix(repo.Name, ".wiki") {
+	if strings.HasSuffix(repoName, ".wiki") {
```
Comment (zeripath) [inline models/helper_environment.go:21]:
```suggestion
	if wiki {
```

File: models/wiki.go [hunk 4]
```diff
@@ -217,7 +217,14 @@ func (repo *Repository) updateWikiPage(doer *User, oldWikiName, newWikiName, con
 	if err := git.Push(basePath, git.PushOptions{
 		Remote: "origin",
 		Branch: fmt.Sprintf("%s:%s%s", commitHash.String(), git.BranchPrefix, "master"),
-		Env:    PushingEnvironment(doer, repo),
+		Env: FullPushingEnvironment(
+			doer,
+			doer,
+			repo.MustOwnerName(),
```
Comment (zeripath) [inline models/wiki.go]:
```suggestion
			repo,
```

File: models/helper_environment.go [hunk 5]
```diff
@@ -32,12 +32,12 @@ func FullPushingEnvironment(author, committer *User, repo *Repository, prID int6
 		"GIT_AUTHOR_EMAIL="+authorSig.Email,
 		"GIT_COMMITTER_NAME="+committerSig.Name,
 		"GIT_COMMITTER_EMAIL="+committerSig.Email,
-		EnvRepoName+"="+repo.Name,
-		EnvRepoUsername+"="+repo.MustOwnerName(),
+		EnvRepoName+"="+repoName,
```
Comment (zeripath) [inline models/helper_environment.go:35]:
```suggestion
		EnvRepoName+"="+repo.Name,
```

File: models/helper_environment.go [hunk 6]
```diff
@@ -32,12 +32,12 @@ func FullPushingEnvironment(author, committer *User, repo *Repository, prID int6
...
+		EnvRepoUsername+"="+ownerName,
```
Comment (zeripath) [inline models/helper_environment.go]:
```suggestion
		EnvRepoUsername+"="+repo.MustOwnerName(),
```

File: models/helper_environment.go [hunk 7]
```diff
@@ -32,12 +32,12 @@ func FullPushingEnvironment(author, committer *User, repo *Repository, prID int6
...
 		EnvRepoIsWiki+"="+isWiki,
 		EnvPusherName+"="+committer.Name,
 		EnvPusherID+"="+fmt.Sprintf("%d", committer.ID),
-		ProtectedBranchRepoID+"="+fmt.Sprintf("%d", repo.ID),
+		ProtectedBranchRepoID+"="+fmt.Sprintf("%d", repoID),
```
Comment (zeripath) [inline models/helper_environment.go]:
```suggestion
		ProtectedBranchRepoID+"="+fmt.Sprintf("%d", repo.ID),
```

File: models/wiki.go [hunk 8]
```diff
@@ -217,7 +217,14 @@ func (repo *Repository) updateWikiPage(doer *User, oldWikiName, newWikiName, con
...
+			repo.Name+".wiki",
```
Comment (zeripath) [inline models/wiki.go:224]:
```suggestion
			true,
```

File: models/wiki.go [hunk 9]
```diff
@@ -217,7 +217,14 @@ func (repo *Repository) updateWikiPage(doer *User, oldWikiName, newWikiName, con
...
+			repo.ID,
```
Comment (zeripath) [inline models/wiki.go]:
```suggestion
```

File: modules/pull/merge.go [hunk 10]
```diff
@@ -240,7 +240,14 @@ func Merge(pr *models.PullRequest, doer *models.User, baseGitRepo *git.Repositor
 		headUser = doer
 	}
 
-	env := models.FullPushingEnvironment(headUser, doer, pr.BaseRepo, pr.ID)
+	env := models.FullPushingEnvironment(
+		headUser,
+		doer,
+		pr.BaseRepo.MustOwnerName(),
```
Comment (zeripath) [inline modules/pull/merge.go]:
```suggestion
		pr.BaseRepo,
```

File: modules/pull/merge.go [hunk 11]
```diff
@@ -240,7 +240,14 @@ func Merge(pr *models.PullRequest, doer *models.User, baseGitRepo *git.Repositor
...
+		pr.BaseRepo.Name,
```
Comment (zeripath) [inline modules/pull/merge.go:247]:
```suggestion
		false,
```

File: modules/pull/merge.go [hunk 12]
```diff
@@ -240,7 +240,14 @@ func Merge(pr *models.PullRequest, doer *models.User, baseGitRepo *git.Repositor
...
+		pr.BaseRepo.ID,
```
Comment (zeripath) [inline modules/pull/merge.go]:
```suggestion
```

**Review by zeripath — COMMENTED** [review]
Like this:

File: models/helper_environment.go (hunk 1 above)
Comment (lunny) [reply models/helper_environment.go]: This will not work. we need `repoName` which is different from `repo.Name`. When it's a wiki, `repo.Name` will return `my_repo`, but `repoName` should be `my_repo.wiki`.

**Comment by lunny** [comment]
@zeripath thanks for your review, but I don't think your review will work. I have pushed a new version, please review again.

**Review by zeripath — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Comment by zeripath** [comment]
@lunny please send backport
