### PR TITLE
Server-side syntax highlighting for all code

### LINKED ISSUE #3682: JavaScript syntax highlighting breaks
The title should be concise enough. Tested against `1324d62 `.

screen shot 2018-03-16 at 22 48 41

The comment highlighting continues until EOF.

### LINKED ISSUE #3872: Markdown: Syntax highlighting fails with escaped double quotes
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/yooooo/test/src/branch/master/burn)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

With shell scripts syntax highlighting fails when encountering an escaped double quote (`\"`) causing following code to be incorrectly highlighted. This is very distracting and instead of making the code easier to read, the syntax highlighting makes it harder to read. Please see the try.gitea.io example link for a test case.

## Screenshots

test

### LINKED ISSUE #7728: Syntax highlight in diff and edit preview broken
The highlighting code currently assumes a `pre > code` structure to work but this is not given for diff and edit previews. Given that `pre > code` is problematic in regards to introducing extra whitespace for text selection, I think we should introduce a new exclusive HTML class for syntax highlighting and use that everywhere.

### LINKED ISSUE #7729: Server-side syntax highlighting
Syntax highlighing is currently performed client-side which has a few drawbacks:

- We need to ship a 700kB library to the client which hurts performance
- There is a flash of unhighlighted code on every page load
- Language detection of highlight.js does not work based on filenames but on the code itself, giving a lot of false highlights (we could probably fix by mapping more file extensions, thought).

It may be worth investigating integrating https://github.com/alecthomas/chroma as server-side highlight. It supports language detection based on filename out of the box.

### LINKED ISSUE #10157: Syntx highlighting not working properly for PERL
I notice that many of my scripts in PERL have problems with the syntax highlighting, usually where there's regex involved, e.g.

Screenshot-20200205172429-744x441

### LINKED ISSUE #11825: Code blocks in Wiki are rendered with arbitrary syntax highlighting instead of none
- Gitea version (or commit ref): 1.11.5
- Can you reproduce the bug at https://try.gitea.io: 
  - [X] Yes: https://try.gitea.io/qwertfisch/markdown-test/wiki/Code-blocks
  - [ ] No
  - [ ] Not relevant

## Description

When adding a code block on a page in the built-in wiki, but with no language given for syntax highlighting, this block will be rendered using an arbitrarily chosen highlighting. Code blocks without selected syntax I will set like this:

~~~
```
This is simple text rendered with fixed-width font,
but no syntax highlighting.
```
~~~

Even if the text inside the block would contain keywords for *some* languages, I do not expect them to be highlighted or rendered other than as fixed-width font. In fact when given no language for the code block, I expect the language to be *None*.

### Actual result
When selecting the preview window, or after storing the page, a second later a seemingly arbitrarily chosen syntax highlighting is applied to the block. On the [example page](https://try.gitea.io/qwertfisch/markdown-test/wiki/Code-blocks) I added some keywords (for some languages), and the two blocks are rendered as Cal and Vim, respectively. It seems the highlighting is selected automatically given the content of the block.

### Workaround
I can enclose the block with `<pre>` / `</pre>` instead of Markdown. Is there otherwise a possibility to have a non-syntaxed code block with Markdown syntax?
**Edit:** `<pre>` does not set the content to a fixed-width font, so this is unfortunately no solution.

Is this a bug for Gitea? Or should I file a bug on the Markdown interpreter used (goldmark?).

### PR DESCRIPTION
**Pull request by mrsdizzie**
This PR does a few things:

* Remove all traces of highlight.js
* Use [chroma ](https://github.com/alecthomas/chroma) library to provide fast syntax highlighting directly on the server
* Provide syntax highlighting for diffs + code comments
* Re-style code view and unified/split diffs views to try and look a bit more 'modern'
* Add custom syntax highlighting styling for regular theme and convert previous arc-green highlighting best I could

Fixes #7729
Fixes #10157
Fixes #11825
Fixes #7728
Fixes #3872
Fixes #3682

And perhaps gets closer to #9553

Suggestions welcome for styling

New Diff:

Screen Shot 2020-06-24 at 4 13 12 PM
Screen Shot 2020-06-24 at 7 31 29 PM
Screen Shot 2020-06-24 at 7 46 21 PM
Screen Shot 2020-06-24 at 7 43 10 PM

Screen Shot 2020-06-26 at 12 26 37 PM

### CODE REVIEW

File: modules/markup/sanitizer.go [hunk 1]
```diff
@@ -65,8 +65,8 @@ func ReplaceSanitizer() {
 	// Allow classes for emojis
 	sanitizer.policy.AllowAttrs("class").Matching(regexp.MustCompile(`emoji`)).OnElements("img")
 
-	// Allow icons, checkboxes and emojis on span
-	sanitizer.policy.AllowAttrs("class").Matching(regexp.MustCompile(`^((icon(\s+[\p{L}\p{N}_-]+)+)|(ui checkbox)|(ui checked checkbox)|(emoji))$`)).OnElements("span")
+	// Allow icons, checkboxes, emojis, and chroma syntax on span
+	sanitizer.policy.AllowAttrs("class").Matching(regexp.MustCompile(`^((icon(\s+[\p{L}\p{N}_-]+)+)|(ui checkbox)|(ui checked checkbox)|(emoji))$|^((c|g|i|k|m|n|o|s|u|v|w)[a-z0-9]{0,2})$`)).OnElements("span")
```
Comment (lafriks) [inline modules/markup/sanitizer.go]: What this regexp is meant to do?

Comment (mrsdizzie) [reply modules/markup/sanitizer.go]: It is for the classes used for highlighting (see chroma.less in this PR for the classes) All Markdown is run through sanitizer so we need to allow these for the Chroma markdown plugin generated code to work.

So if in markdown you wrote
```

```go
t.Fatal(err)
``
```
It would highlight it by producing this:

```<span class="nx">t</span>
<span class="p">.</span>
<span class="nf">Fatal</span>
<span class="p">(</span>
<span class="nx">err</span>
<span class="p">)</span>
```


Similar to what it is like on Github (they used to use Pigments which this is based on but I think use something else now). 

I know these regex are getting a bit out of hand when we keep adding new things but wasn't sure if there was a better option. They don't seem to stack either from what I can tell so everything needs to be inside one big one ; (

**Comment by silverwind** [comment]
I think you still need to run `npm uninstall highlight.js` and commit the results.

File: modules/markup/sanitizer.go (hunk 1 above)
Comment (lafriks) [reply modules/markup/sanitizer.go]: Maybe we could just use such:
```suggestion
	sanitizer.policy.AllowAttrs("class").Matching(regexp.MustCompile(`^((icon(\s+[\p{L}\p{N}_-]+)+)|(ui checkbox)|(ui checked checkbox)|(emoji))$|^([a-z][a-z0-9]{0,2})$`)).OnElements("span")
```

Comment (mrsdizzie) [reply modules/markup/sanitizer.go]: sure, done

**Comment by mrsdizzie** [comment]
> I think you still need to run `npm uninstall highlight.js` and commit the results.

Thanks! fixed

**Comment by silverwind** [comment]
Oh, and `npm uninstall domino` as well and remove [this line](https://github.com/go-gitea/gitea/blob/4b66d9ad980aa9d84f4496cee67bcef0b82d643c/webpack.config.js#L63).

**Comment by mrsdizzie** [comment]
> Oh, and `npm uninstall domino` as well and remove [this line](https://github.com/go-gitea/gitea/blob/4b66d9ad980aa9d84f4496cee67bcef0b82d643c/webpack.config.js#L63).

fixed

File: web_src/less/themes/theme-arc-green.less [hunk 2]
```diff
@@ -1,69 +1,390 @@
...
 }
+/* CommentPreprocFile */
+
+.chroma .cpf {
+    color: #7f7f7f;
+}
+/* GenericDeleted */
+
+.chroma .gd {
+    color: #000000;
```
Comment (silverwind) [inline web_src/less/themes/theme-arc-green.less]:
```suggestion
    color: #9e9e9e;
```

File: web_src/less/themes/theme-arc-green.less [hunk 3]
```diff
@@ -1,69 +1,390 @@
...
+    background-color: #ffdddd;
+}
+/* GenericEmph */
+
+.chroma .ge {
+    color: #000000;
```
Comment (silverwind) [inline web_src/less/themes/theme-arc-green.less]:
```suggestion
    color: #9e9e9e;
```

File: web_src/less/themes/theme-arc-green.less [hunk 4]
```diff
@@ -1,69 +1,390 @@
...
+}
+/* GenericHeading */
+
+.chroma .gh {
+    color: #999999;
+}
+/* GenericInserted */
+
+.chroma .gi {
+    color: #000000;
```
Comment (silverwind) [inline web_src/less/themes/theme-arc-green.less]:
```suggestion
    color: #9e9e9e;
```

File: web_src/less/themes/theme-arc-green.less [hunk 5]
```diff
@@ -1,69 +1,390 @@
...
+}
+/* NameOther */
+
+.chroma .nx {
+    color: #9daccc;
+}
+/* NameTag */
+
+.chroma .nt {
+    color: #000080;
```
Comment (silverwind) [inline web_src/less/themes/theme-arc-green.less]:
```suggestion
    color: #88f;
```

File: web_src/less/themes/theme-arc-green.less [hunk 6]
```diff
@@ -1,69 +1,390 @@
...
+}
+/* NameFunction */
+
+.chroma .nf {
+    color: #986c88;
+}
+/* NameLabel */
+
+.chroma .nl {
+    color: #990000;
```
Comment (silverwind) [inline web_src/less/themes/theme-arc-green.less]:
```suggestion
    color: #f88;
```

File: web_src/less/themes/theme-arc-green.less [hunk 7]
```diff
@@ -1,69 +1,390 @@
...
+}
+/* NameEntity */
+
+.chroma .ni {
+    color: #800080;
+}
+/* NameException */
+
+.chroma .ne {
+    color: #990000;
```
Comment (silverwind) [inline web_src/less/themes/theme-arc-green.less]:
```suggestion
    color: #f88;
```

File: web_src/less/themes/theme-arc-green.less [hunk 8]
```diff
@@ -1,69 +1,390 @@
...
+}
+/* NameDecorator */
+
+.chroma .nd {
+    color: #3c5d5d;
+}
+/* NameEntity */
+
+.chroma .ni {
+    color: #800080;
```
Comment (silverwind) [inline web_src/less/themes/theme-arc-green.less]:
```suggestion
    color: #f8f;
```

File: web_src/less/themes/theme-arc-green.less [hunk 9]
```diff
@@ -1,69 +1,390 @@
...
+}
+/* NameClass */
+
+.chroma .nc {
+    color: #445588;
+}
+/* NameConstant */
+
+.chroma .no {
+    color: #008080;
```
Comment (silverwind) [inline web_src/less/themes/theme-arc-green.less]:
```suggestion
    color: #8ff;
```

File: web_src/less/themes/theme-arc-green.less [hunk 10]
```diff
@@ -1,69 +1,390 @@
...
+.chroma .kt {
+    color: #9daccc;
+    font-weight: bold;
 }
+/* NameAttribute */
 
-.hljs-string {
-    color: #6a8759;
+.chroma .na {
+    color: #008080;
```
Comment (silverwind) [inline web_src/less/themes/theme-arc-green.less]:
```suggestion
    color: #8ff;
```

File: web_src/less/themes/theme-arc-green.less [hunk 11]
```diff
@@ -1,69 +1,390 @@
...
+/* GenericStrong */
+
+.chroma .gs {
+    color: #a8a8a2;
+    font-weight: bold;
+}
+/* GenericSubheading */
+
+.chroma .gu {
+    color: #aaaaaa;
```
Comment (silverwind) [inline web_src/less/themes/theme-arc-green.less]:
```suggestion
    color: #888;
```

**Comment by silverwind** [comment]
Those suggestions above fix some of colors that are definitely too dark in `arc-green` for sufficient contrast. Are there any themes for Chroma we could maybe use as a baseline?

File: templates/repo/diff/blob_excerpt.tmpl [hunk 12]
```diff
@@ -13,18 +13,19 @@
...
+    <td class="blob-excerpt lines-code lines-code-old halfwidth"><span class="mono wrap">{{if $line.LeftIdx}}{{$.section.GetComputedInlineDiffFor $line}}{{end}}</span></td>
     <td class="lines-num lines-num-new" data-line-num="{{if $line.RightIdx}}{{$line.RightIdx}}{{end}}"><span rel="{{if $line.RightIdx}}diff-{{Sha1 $.fileName}}R{{$line.RightIdx}}{{end}}"></span></td>
     <td class="blob-excerpt lines-type-marker lines-type-marker-new">{{if $line.RightIdx}}<span class="mono" data-type-marker=""></span>{{end}}</td>
-    <td class="blob-excerpt lines-code lines-code-new halfwidth"><span class="mono wrap{{if $.highlightClass}} language-{{$.highlightClass}}{{else}} nohighlight{{end}}">{{if $line.RightIdx}}{{$.section.GetComputedInlineDiffFor $line}}{{end}}</span></td>
+    <td class="blob-excerpt lines-code lines-code-new halfwidth"><span class="mono wrap">{{if $line.RightIdx}}{{$.section.GetComputedInlineDiffFor $line}}{{end}}</span></td>
     {{end}}
   </tr>
   {{end}}
 {{else}}
+<p>what the fuck</p>
```
Comment (silverwind) [inline templates/repo/diff/blob_excerpt.tmpl]: leftover debug?

**Comment by silverwind** [comment]
This looks to work quite nice. I wonder if we need a mechanism to stop highlighting big files if they take too long, either based on processing time or line count. I think GitHub just stops highlighting around line 20k in a single file.

File: templates/repo/diff/blob_excerpt.tmpl (hunk 12 above)
Comment (mrsdizzie) [reply templates/repo/diff/blob_excerpt.tmpl]: lol yes

**Comment by mrsdizzie** [comment]
@silverwind I tried a few but they looked weird on dark green as-is so I tried to just copy the values that were present before. I  don't use/enjoy dark themes so I'm certainly not the best judge probably (I think he current one is difficult to look at too).

If you want to try and test how some look on dark green, I think the quickest way would be to set this to false so it uses inline styles for the moment:

 https://github.com/go-gitea/gitea/blob/1bb78a013d55767d80d732bbd9ea752b8f1d2416/modules/highlight/highlight.go#L85

and then you can try different themes here (where it says styles.GitHub now).

 https://github.com/go-gitea/gitea/blob/1bb78a013d55767d80d732bbd9ea752b8f1d2416/modules/highlight/highlight.go#L116

Heres a list

 https://github.com/alecthomas/chroma/tree/master/styles

I'll commit the changes above as well

File: templates/repo/diff/blob_excerpt.tmpl (hunk 12 above)
Comment (mrsdizzie) [inline templates/repo/diff/blob_excerpt.tmpl]:
```suggestion

```

**Comment by silverwind** [comment]
Will check the themes later. I'm thinking we could probably use these colors, at least as the baseline:

Light: https://github.com/alecthomas/chroma/blob/master/styles/github.go
Dark: https://github.com/alecthomas/chroma/blob/master/styles/solarized-dark.go

**Comment by mrsdizzie** [comment]
I used the Github one as a baseline for light but I think it is either too old or was just bad because it looks nothing like Github does (as you can tell I still tried my best to just copy what Github does in all of the light sections).

I'll add file size limit to rendering later too -- I thought we already had a limit for this but it is just the general UI display limit which is 8MB so that isn't helpful here.

**Comment by silverwind** [comment]
GitHub at one time used pygments so I assume that theme is based on it. They're now the Prettylights highlighter (closed source), but I found this which may be of use:

https://github.com/primer/github-syntax-theme-generator

File: routers/repo/blame.go [hunk 13]
```diff
@@ -236,11 +232,11 @@ func renderBlame(ctx *context.Context, blameParts []git.BlamePart, commitNames m
 				lineNumbers.WriteString(fmt.Sprintf(`<span id="L%d" data-line-number="%d"></span>`, i, i))
 			}
 
-			//Code line
-			line = gotemplate.HTMLEscapeString(line)
 			if i != len(lines)-1 {
 				line += "\n"
 			}
+			fileName := fmt.Sprintf("%v", ctx.Data["FileName"])
```
Comment (lafriks) [inline routers/repo/blame.go:238]: Why %v is needed here?

File: web_src/less/_repository.less [hunk 14]
```diff
@@ -1723,14 +1715,20 @@
...
-                background-color: #ffe0e0 !important;
+                background-color: #ffeef0 !important;
                 border-color: #f1c0c0 !important;
             }
 
             &.add-code td {
-                background-color: #d6fcd6 !important;
-                border-color: #c1e9c1 !important;
+                background-color: #e6ffed;
+                /* border-color: #c1e9c1 !important; */
```
Comment (lafriks) [inline web_src/less/_repository.less]:
```suggestion
```

**Comment by silverwind** [comment]
Noticed we don't need the `worker-loader` either now, so you can `npm uninstall worker-loader`, then remove these lines:

https://github.com/go-gitea/gitea/blob/b918609acc11d2deb1dd2182597c7cbb3624dbdb/webpack.config.js#L116-L129

And finally remove the first entry here:

https://github.com/go-gitea/gitea/blob/master/.eslintrc#L31

File: routers/repo/blame.go (hunk 13 above)
Comment (mrsdizzie) [reply routers/repo/blame.go:238]: Did this to avoid
```
 cannot use ctx.Context.Data["FileName"] (type interface {}) as type string in argument to highlight.File: need type assertion
```
There is probably a better way I just didn't know and used this

**Comment by mrsdizzie** [comment]
@silverwind limited size to 25kb and made those js changes thanks

File: modules/highlight/highlight.go [hunk 15]
```diff
@@ -39,6 +39,10 @@ func NewContext() {
 // Code returns a HTML version of code string with chroma syntax highlighting classes
 func Code(fileName, code string) string {
 	NewContext()
+	// don't highlight over 25kb
+	if len(code) > 25000 {
```
Comment (lafriks) [inline modules/highlight/highlight.go]: This value should be moved to constant variable

Comment (silverwind) [reply modules/highlight/highlight.go]: Maybe make a config option?

Comment (lafriks) [reply modules/highlight/highlight.go]: Option can be also added in other PR, for this PR it would be fine also with constant

Comment (mrsdizzie) [reply modules/highlight/highlight.go]: Updated thanks!

**Review by lafriks — APPROVED** [review]

**Comment by mrsdizzie** [comment]
@silverwind made a few tweaks to light theme based on the link you gave above -- think it is pretty good for now. Pygments doesn't have quite the level of detail that pretty lights does in some areas but is pretty close.

Also raised the threshold for highlighting to 1MB based on https://help.github.com/en/github/creating-cloning-and-archiving-repositories/limits-for-viewing-content-and-diffs-in-a-repository

**Comment by silverwind** [comment]
Will likely need to undo to `worker-loader` removal (part of https://github.com/go-gitea/gitea/pull/12047/commits/901ce59785e65bd21c83d189cb3d111d7e3254d2) because https://github.com/go-gitea/gitea/pull/12095 will depend on it.

**Comment by mrsdizzie** [comment]
> Will likely need to undo to `worker-loader` removal (part of [901ce59](https://github.com/go-gitea/gitea/commit/901ce59785e65bd21c83d189cb3d111d7e3254d2)) because #12095 will depend on it.

Do I need to do any special commands to properly add it back to npm, or just add the line back to package.json and run make frontend?

**Comment by silverwind** [comment]
Run `npm install worker-loader` and add back the two removed sections in `webpack.config.js` and `.eslintrc`. `npm install` will take care of `package-lock.json`.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Syntax looks good on light and dark. I have not encountered some of the more exotic identifiers in the files I was looking at but we should be good with those brighter color on arc-green.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
:rocket:

**Comment by mrsdizzie** [comment]
Thanks all : )
