### PR TITLE
Fix avatar upload error handling

### LINKED ISSUE #35884: First login via LDAP fails if there is no avatar
### Description

When a LDAP user that Gitea does not yet know tries to log in for the first time and does not have an avatar (and the auth source has the Avatar Attribute set), it fails, and the second attempt succeeds.

The log contains the following lines:
```
2025/11/06 13:28:00 services/auth/signin.go:119:UserSignIn() [W] Failed to login 'git-test' via 'FreeIPA': image.DecodeConfig: image: unknown format
2025/11/06 13:28:00 routers/web/auth/auth.go:222:SignInPost() [W] Failed authentication attempt for git-test from <redacted>: user does not exist [uid: 0, name: git-test]
```

Subsequent login attempts succeed.

### Gitea Version

1.24.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Downloaded the official release

### Database

SQLite

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #35884

### CODE REVIEW

**Review by Zettat123 — APPROVED** [review]

**Review by lunny — APPROVED** [review]

File: services/auth/source/ldap/source_authenticate.go [hunk 1]
```diff
@@ -105,9 +105,7 @@ func (source *Source) Authenticate(ctx context.Context, user *user_model.User, u
 			}
 		}
 		if source.AttributeAvatar != "" {
-			if err := user_service.UploadAvatar(ctx, user, sr.Avatar); err != nil {
-				return user, err
-			}
+			_ = user_service.UploadAvatar(ctx, user, sr.Avatar)
```
Comment (delvh) [inline services/auth/source/ldap/source_authenticate.go:108]: Should we log the error?

**Review by delvh — APPROVED** [review]

File: services/auth/source/ldap/source_authenticate.go (hunk 1 above)
Comment (wxiaoguang) [reply services/auth/source/ldap/source_authenticate.go:108]: Didn't see the necessity:

image
