### PR TITLE
Fix activity feed

### LINKED ISSUE #1730: Activity Feed is not updated after username-change
- Gitea version (or commit ref): 91417e9 
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) -> Screenshot
  - [ ] No
  - [ ] Not relevant

## Description

After changing the Username the Activity Feed goes empty (removes all entries of the user that changed the username).
When creating a organisation with the old username, it appears as if the organisation did the things the user originally did. Also, the URL to the repo remains the old and now invalid one.

## Screenshots

grafik

grafik

### PR DESCRIPTION
**Pull request by ethantkoenig**
Preserve actions after user/repo name change. Fixes #1730.

Essentially removes the `act_user_name`, `repo_user_name`, and `repo_name` columns from the `action` table (which can become stale when a user/repo changes name). There's really no point in having the `act_user_name` column, since you have the load the user for the avatar link anyways.

__NOTE__: I'm having some trouble getting the migration to work; if anyone knows how to drop columns with xorm, please help me out.

### CODE REVIEW

File: models/migrations/v34.go [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+	RepoUserName string `xorm:"-"`
+	RepoName     string `xorm:"-"`
+}
+
+// TableName will be invoked by XORM to customize the table name
+func (*ActionV34) TableName() string {
+	return "action"
+}
+
+func removeActionColumns(x *xorm.Engine) (err error) {
```
Comment (lunny) [inline models/migrations/v34.go]: But this will not remove the column currently.

**Comment by lunny** [comment]
This will also drop #1744

File: models/migrations/v34.go (hunk 1 above)
Comment (ethantkoenig) [reply models/migrations/v34.go]: I know, I made a note of it in the PR description. How does one remove columns with xorm?

**Comment by sapk** [comment]
It will be more easy/clean to remove :
```
 	ActUserID    int64  `xorm:"INDEX"` // Action user id.
	ActUserName  string // Action user name.
 	ActAvatar    string `xorm:"-"`
 	RepoID       int64  `xorm:"INDEX"`
	RepoUserName string
	RepoName     string
```
and simply use `ActUser *User` et `Repo *Repository` and let xorm make the linking.

File: models/migrations/v34.go (hunk 1 above)
Comment (sapk) [reply models/migrations/v34.go]: Not the best at xorm but you could still [execute sql](http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-08/#) and [pass a ALTER TABLE command](https://www.w3schools.com/sql/sql_alter.asp)

**Comment by ethantkoenig** [comment]
@sapk Updated the migration, and took your suggestion about the fields for the `Action` struct

**Comment by ethantkoenig** [comment]
Build timed out :cry:

**Comment by sapk** [comment]
You could easely restart the build by doing a git commit --amend and pushing (with -f) the new commit ;-). 
We should add an issue for this problem that were seing more and more with the addition of test.

**Comment by ethantkoenig** [comment]
Rebased onto master to retrigger build

File: models/action_test.go [hunk 2]
```diff
@@ -4,30 +4,9 @@ import (
 	"strings"
 	"testing"
 
-	"code.gitea.io/gitea/modules/setting"
-
 	"github.com/stretchr/testify/assert"
 )
 
-func TestAction_GetRepoPath(t *testing.T) {
```
Comment (lunny) [inline models/action_test.go]: How about add some new tests?

**Comment by lunny** [comment]
LGTM

**Comment by lafriks** [comment]
LGTM
