### PR TITLE
Make issue meta dropdown support Enter, confirm before reloading

### LINKED ISSUE #20727: [1.17.0] Search label and assignee fields pressing enter has no effect
### Description

Clicking a label in an existing issue or typing a keyword in the assignee field and pressing Enter does not select search results

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

systemd

### Database

PostgreSQL

### LINKED ISSUE #22607: Writing tag and clicking enter not working
### Description

Hi, 
When i'm inside an issue and i want to modify a tag i have a bug when typing the tagname and clicking enter. 
It just do a reload and not apply my tag

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

https://user-images.githubusercontent.com/60541446/214807733-0289f189-c7d7-4f22-99b3-582342622543.mov

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Gitea is build and host on a local server

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
As the title. Label/assignee share the same code.

* Close #22607
* Close #20727

Also:

* partially fix for #21742, now the comment reaction and menu work with keyboard.
* partially fix for #17705, in most cases the comment won't be lost.
* partially fix for #21539
* partially fix for #20347
* partially fix for #7329

### The `Enter` support

Before, if user presses Enter, the dropdown just disappears and nothing happens or the window reloads.

After, Enter can be used to select/deselect labels, and press Esc to hide the dropdown to update the labels (still no way to cancel .... maybe you can do a Cmd+R or F5 to refresh the window to discard the changes .....)

This is only a quick patch, the UX is still not perfect, but it's much better than before.

### The `confirm` before reloading

And more fixes for the `reload` problem, the new behaviors:

* If nothing changes (just show/hide the dropdown), then the page won't be reloaded.
* If there are draft comments, show a confirm dialog before reloading, to avoid losing comments.

That's the best effect can be done at the moment, unless completely refactor these dropdown related code.

Screenshot of the confirm dialog:

<details>

image

</details>

### CODE REVIEW

File: web_src/js/features/repo-legacy.js [hunk 1]
```diff
@@ -86,11 +86,12 @@ export function initRepoCommentForm() {
     let hasUpdateAction = $listMenu.data('action') === 'update';
     const items = {};
 
-    $(`.${selector}`).dropdown('setting', 'onHide', () => {
-      hasUpdateAction = $listMenu.data('action') === 'update'; // Update the var
-      if (hasUpdateAction) {
-        // TODO: Add batch functionality and make this 1 network request.
-        (async function() {
+    $(`.${selector}`).dropdown({
+      'action': 'nothing', // do not hide the menu if user presses Enter
```
Comment (brechtvl) [inline web_src/js/features/repo-legacy.js:110]:
```suggestion
      'action': 'nothing', // do not hide the menu if user presses Enter
      fullTextSearch: 'exact',
```

Comment (brechtvl) [reply web_src/js/features/repo-legacy.js:110]: This is needed to make search work well, without it a label `color/green` is not found by searching for `green`.

It's because this code from `web_src/js/features/common-global.js` no longer applies.
```
  $uiDropdowns.filter(':not(.custom)').dropdown({
    fullTextSearch: 'exact'
  });
```

**Comment by wxiaoguang** [comment]
And more fixes for the `reload` problem, the new behaviors:
* If nothing changes (just show/hide the dropdown), then the page won't be reloaded.
* If there are draft comments, show a confirm dialog before reloading, to avoid losing comments.

I think this PR is ready for review.

File: web_src/js/features/repo-legacy.js [hunk 2]
```diff
@@ -29,6 +29,24 @@ import {hideElem, showElem} from '../utils/dom.js';
...
 const {csrfToken} = window.config;
 
+// if there are draft comments (more than 20 chars), confirm before reloading, to avoid losing comments
+function reloadConfirmDraftComment() {
+  const commentTextareas = [
+    document.querySelector('.edit-content-zone:not(.gt-hidden) textarea'),
+    document.querySelector('.edit_area'),
+  ];
+  for (const textarea of commentTextareas) {
+    if (textarea && textarea.value.trim().length > 20) {
```
Comment (lunny) [inline web_src/js/features/repo-legacy.js:41]: Why it's 20 not other number?

Comment (wxiaoguang) [reply web_src/js/features/repo-legacy.js:41]: Just a magic number.

I think most users won't feel sad if they lose a comment with 10 or 20 chars

But if they have typed 50 chars and the comment is lost, they will be very unhappy.

Comment (wxiaoguang) [reply web_src/js/features/repo-legacy.js:41]: Added more comments in https://github.com/go-gitea/gitea/pull/23014/commits/afef2c4ea9fedca0d35db8ee1aa4c1f0a8b54419

**Review by lunny — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Comment by lunny** [comment]
Please send backport

File: web_src/js/features/repo-legacy.js [hunk 3]
```diff
@@ -29,6 +29,26 @@ import {hideElem, showElem} from '../utils/dom.js';
...
+    // But if they have typed more (like 50) chars and the comment is lost, they will be very unhappy.
+    if (textarea && textarea.value.trim().length > 20) {
+      textarea.parentElement.scrollIntoView();
+      if (!window.confirm('Page will be reloaded, but there are draft comments. Continuing to reload will discard the comments. Continue?')) {
+        return;
+      }
+      break;
+    }
+  }
+  window.location.reload();
```
Comment (silverwind) [inline web_src/js/features/repo-legacy.js:49]: I'm of the opinion that it's better to just save unsubmitted data into `sessionStorage` or `localStorage` and subsequently restore it on page load, but hooking [onbeforeunload](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) would also have been an improvement over this method because it works even when the user presses F5 for example.

Comment (wxiaoguang) [reply web_src/js/features/repo-legacy.js:49]: I also proposed so (draft) as one approach.

* https://github.com/go-gitea/gitea/issues/17705#issuecomment-1165105062

Comment (wxiaoguang) [reply web_src/js/features/repo-legacy.js:49]: > but hooking [onbeforeunload](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) would also have been an improvement over

Before SimpleMDE/EasyMDE, there is a global `$.areYourSure` confirm (using onbeforeunload) for comment textarea. Everything was just "fine".

However, `$.areYourSure` doesn't work well with SimpleMDE/EasyMDE editor, so the situation became what you see now.

Comment (silverwind) [reply web_src/js/features/repo-legacy.js:49]: I think we should remove this [`jquery-are-you-sure`](https://github.com/codedance/jquery.AreYouSure) module and implement it on our own to be more flexible. It also has a [license issue](https://github.com/codedance/jquery.AreYouSure/pull/147).

Ideally I would this to also not use `window.confirm`, but a actual styled confirmation dialog (maybe not fomantic).
