### PR TITLE
Send email on Workflow Run Success/Failure

### LINKED ISSUE #23725: Actions - send Email on Success/Failure
### Feature Description

On GitHub, I get emails every time a run succeeds or fails:

image

In Gitea, even though emails are set up (and working), I'm not getting any emails when a job runs (whether successful or failed).

Would it be possible to be able to set that up?

If that could be a setting in the YAML file, even better!

Thank you very much!

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by ghost**
Closes #23725 

/claim #23725

### CODE REVIEW

**Comment by ghost** [comment]
Note: For code reusability, there's a refactor/renaming in `mail.go`, `mail_issue_common.go` and `mail_test.go` in c8b64c76, ed7b2bc

File: services/mailer/mail_issue_common.go [hunk 1]
```diff
@@ -302,35 +303,20 @@ func generateMessageIDForIssue(issue *issues_model.Issue, comment *issues_model.
...
-		"X-GitLab-Project-Path":       repo.FullName(),
-		"X-GitLab-Issue-IID":          strconv.FormatInt(ctx.Issue.Index, 10),
-	}
+	issueID := strconv.FormatInt(ctx.Issue.Index, 10)
+	headers := generateMetadataHeaders(repo)
+
+	maps.Copy(headers, generateSenderRecipientHeaders(ctx.Doer, recipient))
+	maps.Copy(headers, generateReasonHeaders(reason))
+
+	headers["X-Gitea-Recipient-Address"] = recipient.Email
```
Comment (lunny) [inline services/mailer/mail_issue_common.go]: Why not move this line to the function `generateSenderRecipientHeaders`?

File: services/mailer/mail_issue_common.go [hunk 2]
```diff
@@ -302,35 +303,20 @@ func generateMessageIDForIssue(issue *issues_model.Issue, comment *issues_model.
...
+	headers["X-Gitea-Issue-ID"] = issueID
+	headers["X-Gitea-Issue-Link"] = ctx.Issue.HTMLURL()
+	headers["X-GitHub-Recipient-Address"] = recipient.Email
```
Comment (lunny) [inline services/mailer/mail_issue_common.go]: The same as above.

**Comment by lunny** [comment]
replace #33601

File: services/mailer/mail_workflow_run.go [hunk 3]
```diff
@@ -0,0 +1,176 @@
...
+			}
+			sendActionsWorkflowRunStatusEmail(ctx, repo, run, sender, recipients)
+			return
+		} else if sender.EmailNotificationsPreference != user_model.EmailNotificationsOnMention &&
+			sender.EmailNotificationsPreference != user_model.EmailNotificationsDisabled {
+			recipients = append(recipients, sender)
+		}
+	}
+
+	watchers, err := repo_model.GetRepoWatchers(ctx, repo.ID, db.ListOptionsAll)
```
Comment (wxiaoguang) [inline services/mailer/mail_workflow_run.go]: We need a clear definition about "who should receive the emails"

I don't think the "watchers" should receive, for example: on GitHub, I watched some repositories that I have interests, but it doesn't mean that I should receive their notifications.

**Comment by wxiaoguang** [comment]
> replace #33601

Why replace? That one comes first, should we usually respect the first comer (unless the author wasn't active or there are some design problems)?

----

Update: https://github.com/go-gitea/gitea/pull/33601#issuecomment-3047206505

**Comment by wxiaoguang** [comment]
<details>

<summary>outdated</summary>

And by reading the history discussions:

* https://github.com/go-gitea/gitea/pull/33601#issuecomment-2692410578

I think the concern is not addressed? ~~should we send the email on "workflow job" level, or "workflow run" level?~~ (I am not certain about the details, just FYI)

</details>

----

It looks right, the concerns in "Actions - send Email on Success/Failure #33601" should all be addressed. 🙏

File: templates/mail/notify/workflow_run.tmpl [hunk 4]
```diff
@@ -0,0 +1,90 @@
+<!DOCTYPE html>
```
Comment (wxiaoguang) [inline templates/mail/notify/workflow_run.tmpl:1]: Hmm, I think we can try to introduce a "email template review" function in devtest (in the future), then we can preview the email templates. 🤔

File: services/mailer/mail_workflow_run.go [hunk 5]
```diff
@@ -0,0 +1,176 @@
...
+			si := jobs[i].Status
+			sj := jobs[j].Status
+			if si.IsSuccess() {
+				si = 99
+			}
+			if sj.IsSuccess() {
+				sj = 99
+			}
+			return si < sj
+		})
```
Comment (wxiaoguang) [inline services/mailer/mail_workflow_run.go]: Curious, why we need this sort?

File: services/mailer/mail.go [hunk 6]
```diff
@@ -171,3 +171,39 @@ func fromDisplayName(u *user_model.User) string {
 	}
 	return u.GetCompleteName()
 }
+
+func generateMetadataHeaders(repo *repo_model.Repository) map[string]string {
+	return map[string]string{
+		// https://datatracker.ietf.org/doc/html/rfc2919
+		"List-ID": fmt.Sprintf("%s <%s.%s.%s>", repo.FullName(), repo.Name, repo.OwnerName, setting.Domain),
```
Comment (wxiaoguang) [inline services/mailer/mail.go:181]: I can see similar code from other part.

But I guess we could try to merge the duplicate code

Comment (wxiaoguang) [reply services/mailer/mail.go:181]: Oops, the code has been de-duplicated. Sorry for the misreading.

File: services/mailer/mail_workflow_run.go [hunk 7]
```diff
@@ -0,0 +1,176 @@
...
+		subject += " succeeded"
+	}
+	subject = fmt.Sprintf("%s: %s (%s)", subject, run.WorkflowID, base.ShortSha(run.CommitSHA))
+	displayName := fromDisplayName(sender)
+	messageID := generateMessageIDForActionsWorkflowRunStatusEmail(repo, run)
+	metadataHeaders := generateMetadataHeaders(repo)
+
+	jobs, err := actions_model.GetRunJobsByRunID(ctx, run.ID)
+	if err != nil {
+		log.Error("GetRunJobsByRunID: %v", err)
```
Comment (wxiaoguang) [inline services/mailer/mail_workflow_run.go:53]: If error occurs, then "jobs" is nil, then we should "return" here?

File: services/mailer/mail_workflow_run.go [hunk 8]
```diff
@@ -0,0 +1,176 @@
...
+			"Subject":       subject,
+			"Repo":          repo,
+			"Run":           run,
+			"RunStatusText": runStatusText,
+			"Jobs":          convertedJobs,
+			"locale":        locale,
+			"Language":      locale.Language(),
+		}); err != nil {
+			log.Error("ExecuteTemplate [%s]: %v", tplWorkflowRun, err)
+		}
```
Comment (wxiaoguang) [inline services/mailer/mail_workflow_run.go]: If "ExecuteTemplate" fails, it should skip the "NewMessageFrom(...mailBody.String()," below?

File: services/mailer/mail_workflow_run.go (hunk 5 above)
Comment (ghost) [reply services/mailer/mail_workflow_run.go]: It's intentional, to prioritize unsuccessful jobs in email body.

File: services/mailer/mail_issue_common.go (hunk 1 above)
Comment (ghost) [reply services/mailer/mail_issue_common.go]: Simply because I don't see any "X-GitHub-Recipient-Address" in actions email source.

Note, all the refactoring is in another branch.

File: templates/mail/notify/workflow_run.tmpl (hunk 4 above)
Comment (wxiaoguang) [reply templates/mail/notify/workflow_run.tmpl:1]: Refactor mail template and support preview #34990 

I think we can use this "mail preview" to help to fine tune mail templates.

(If there is any conflict, I will help to resolve)

File: services/mailer/mail_workflow_run.go (hunk 5 above)
Comment (wxiaoguang) [reply services/mailer/mail_workflow_run.go]: I think we can avoid the magic number by this:


```
if si == sj || si.IsSuccess() {
    return false
}
return si < sj
```

File: services/mailer/mail_workflow_run.go (hunk 8 above)
Comment (ghost) [reply services/mailer/mail_workflow_run.go]: Apparently there are such inconsistencies in `mail_issue_common.go`

Comment (wxiaoguang) [reply services/mailer/mail_workflow_run.go]: Hmm yes, many bad smells in old code. These problems could be fixed later.

File: templates/mail/notify/workflow_run.tmpl [hunk 9]
```diff
@@ -0,0 +1,90 @@
...
+<html>
+<head>
+	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
+	<meta name="format-detection" content="telephone=no,date=no,address=no,email=no,url=no">
+	<title>{{.Subject}}</title>
+	<style>
```
Comment (wxiaoguang) [inline templates/mail/notify/workflow_run.tmpl]: Although the styles look beautiful, but I think we can't use them (well, AI thinks)


Image

Comment (ghost) [reply templates/mail/notify/workflow_run.tmpl]: :shrug:

Comment (wxiaoguang) [reply templates/mail/notify/workflow_run.tmpl]: Legacy code. And that style is quite simple, even it doesn't work, the rendered content still looks fine.

Comment (ghost) [reply templates/mail/notify/workflow_run.tmpl]: How about embedding style into tags? e.g. `<div style="...">`

Comment (wxiaoguang) [reply templates/mail/notify/workflow_run.tmpl]: Yup, I think it is the only working approach 🤔 

(Maybe Refactor mail template and support preview #34990 can help to work on the mail templates.)

File: services/mailer/mail_workflow_run.go (hunk 3 above)
Comment (ghost) [reply services/mailer/mail_workflow_run.go]: Fair enough. I look around but could not find a solid answer, end up asking AI. Send to watchers that are on "And Your Own Notifications"?

File: templates/mail/notify/workflow_run.tmpl (hunk 9 above)
Comment (wxiaoguang) [reply templates/mail/notify/workflow_run.tmpl]: Or maybe we can keep this approach. And we can write a helper function to embed these styles to inline (in the future)

**Comment by ghost** [comment]
<del>linting is failing because of d41aee8. The linter thinks the bool func (`sort.SliceStable`) ends `sendActionsWorkflowRunStatusEmail`</del>

File: services/mailer/mail_workflow_run.go (hunk 3 above)
Comment (wxiaoguang) [reply services/mailer/mail_workflow_run.go]: IMO:

* PR poster
* PR reviewers (maybe)
* Workflow doer

**Comment by wxiaoguang** [comment]
> linting is failing because of [d41aee8](https://github.com/go-gitea/gitea/commit/d41aee8fa3594a546dc6500cad0281c1a15bc57e). The linter thinks the bool func (`sort.SliceStable`) ends `sendActionsWorkflowRunStatusEmail`

No, it's not related to `SliceStable`

It means this:

```
if {
   return
} else { // fail
   other
}
```

It should be:

```
if {
   return
} 
other
```

File: services/mailer/mail_workflow_run.go (hunk 3 above)
Comment (ChristopherHX) [reply services/mailer/mail_workflow_run.go]: _Yes I am writing about an feature opt out, this would affect me on Gitea.com_. My local installation cannot deliver E-Mails.
I am a fan of this global user setting of GitHub Actions (https://github.com/settings/notifications)
Screenshot_20250708-105348

Other than that only notify on failure is there as well

Screenshot_20250708-110915
Screenshot_20250708-110416


If I am not mistaken, this would start sending me E-Mails as long I do not opt out anything else.

_Reasoning: On GitHub Actions I have multiple daily failures that are not worth a mail._

I read scheduled workflows on GitHub Actions are sent to the last doer changed the cron setting, idk what exactly happens here.
Otherwise I also read this is full of randomness for this trigger

Comment (ghost) [reply services/mailer/mail_workflow_run.go]: Since Gitea currently has no fine-grained control over notification, adding the setting requires a database schema migration.

Comment (ghost) [reply services/mailer/mail_workflow_run.go]: @ChristopherHX I'm going to add something for the opt out setting and waiting for #35008

**Comment by Naxdy** [comment]
GitLab is capable of notifying you when you've "fixed" a pipeline, i.e. if a particular workflow succeeded that previously failed on the same branch.

I think it would make sense to implement that if possible (outside of `EmailNotificationsAndYourOwn`), as opposed to simply notifying on _any_ workflow success.

**Comment by ghost** [comment]
@Naxdy Currently, Gitea just mixes all job attempts in a single run, not as GitHub explicitly stating re-run attempts creating a new run ID. Not possible without extra work. Is it actually desired? Personally not adding that here in this PR. afaik GitHub has no notifying successful retries after failure, unless enable successful run notification.

**Comment by Naxdy** [comment]
Thanks for the explanation. And yeah, as of right now, only GitLab has this feature. Perhaps I'll take a crack at it after your PR is merged :thinking:

**Comment by ghost** [comment]
@wxiaoguang @ChristopherHX @Naxdy

**Comment by lunny** [comment]
Is the new table `NotificationSettings` necessary? Could we reuse `UserSetting` table?

**Comment by ghost** [comment]
@lunny The use of `UserSetting` table is not clear imv. Looks like it has quite limited use.

**Comment by wxiaoguang** [comment]
I also think it should reuse the existing setting system, instead of introducing a new system.

And the existing system is indeed not clear, it needs refactoring and improvements.

**Comment by ghost** [comment]
@lunny @wxiaoguang 
- 540c3f00 32ad9ba8 07602a09
- fed3ade2

**Comment by jonnytest1** [comment]
> Thanks for the explanation. And yeah, as of right now, only GitLab has this feature. Perhaps I'll take a crack at it after your PR is merged 🤔

probably just add a "previousRunFailed" property to the event then it should be easy to make conditions for it based on user configuration

File: services/mailer/mail_workflow_run.go [hunk 10]
```diff
@@ -0,0 +1,170 @@
...
+	if setting.MailService == nil {
+		return
+	}
+	if run.Status.IsSkipped() {
+		return
+	}
+
+	recipients := make([]*user_model.User, 0)
+
+	if !sender.IsGiteaActions() && !sender.IsGhost() && sender.IsMailable() {
```
Comment (lunny) [inline services/mailer/mail_workflow_run.go:150]: Why checking sender's preference rather than receivers?

Comment (ghost) [reply services/mailer/mail_workflow_run.go:150]: @lunny Currently in the code the sender is the receiver. Only the sender goes receiver list.
https://github.com/go-gitea/gitea/pull/34982#discussion_r2191349778
https://github.com/go-gitea/gitea/pull/34982#discussion_r2191915412

**Comment by ghost** [comment]
Any further review please?

**Comment by lunny** [comment]
> Any further review please?

I will complete my review by Monday.

File: services/mailer/mail_workflow_run.go [hunk 11]
```diff
@@ -0,0 +1,170 @@
...
+				recipients = append(recipients, sender)
+			}
+			sendActionsWorkflowRunStatusEmail(ctx, repo, run, sender, recipients)
+			return
+		} else if notifyPref != user_model.EmailNotificationGiteaActionsDisabled {
+			recipients = append(recipients, sender)
+		}
+	}
+
+	sendActionsWorkflowRunStatusEmail(ctx, repo, run, sender, recipients)
```
Comment (ChristopherHX) [inline services/mailer/mail_workflow_run.go]: Something not important: I would skip calling this method if len(recipients) == 0, because this method does some preprocessing not needed when sending no email.

_Another note_
the following code fragment seem to duplicate, line 169 and may cause bugs if we would decide to change who will get an email (update recipients creation) 
```go
			sendActionsWorkflowRunStatusEmail(ctx, repo, run, sender, recipients)
			return
```

**Review by ChristopherHX — APPROVED** [review]
Works great on my end

_unrelated: only configureing gitea for me with enabled mails, could be better documented that the email service needs to be enabled additionally to the mailer itself_

File: services/mailer/mail_workflow_run.go (hunk 11 above)
Comment (ghost) [reply services/mailer/mail_workflow_run.go]: The Notifications setting page will not be available without EnableNotifyMail. 
Initially I do prepare a list of recipients. Right now just send to the trigger, without updating func arguments once again.

File: services/mailer/mail_workflow_run.go [hunk 12]
```diff
@@ -0,0 +1,172 @@
...
+		}
+		if run.Status.IsSuccess() {
+			if notifyPref == user_model.EmailNotificationGiteaActionsAll {
+				recipients = append(recipients, sender)
+			}
+			sendActionsWorkflowRunStatusEmail(ctx, repo, run, sender, recipients)
+			return
+		} else if notifyPref != user_model.EmailNotificationGiteaActionsDisabled {
+			recipients = append(recipients, sender)
+		}
```
Comment (ChristopherHX) [inline services/mailer/mail_workflow_run.go]: _Functionally this works right now, this are optional change request comments at very high level_

 > Initially I do prepare a list of recipients. Right now just send to the trigger, without updating func arguments once again

Yes I read the code like: you prepare recipients then call sendActionsWorkflowRunStatusEmail

However now we have multiple places where this function calls an exists without doing anything else.
```go
sendActionsWorkflowRunStatusEmail(ctx, repo, run, sender, recipients)
```
So this one still calls this code if the workflow succeeded, even if the user only gets notified on failure.

> without updating func arguments once again

Doesn't line 159-162 update the arguments "updating func arguments once again"?
```go
			if notifyPref == user_model.EmailNotificationGiteaActionsAll {
				recipients = append(recipients, sender)
			}
```

Idk, maybe a linter complained due to an nested if inside an if... then the following refactoring would resolve this:
```suggestion
		if notifyPref == user_model.EmailNotificationGiteaActionsAll || !run.Status.IsSuccess() && notifyPref != user_model.EmailNotificationGiteaActionsDisabled {
			recipients = append(recipients, sender)
		}
```

File: services/mailer/mail_workflow_run.go (hunk 11 above)
Comment (ChristopherHX) [reply services/mailer/mail_workflow_run.go]: > The Notifications setting page will not be available without EnableNotifyMail.

Yes, but this docs page left me in unknown: <https://docs.gitea.com/administration/email-setup>

_I never set up the mailer in Gitea before, ref https://gitea.com/gitea/docs/pulls/246_

File: services/mailer/mail_workflow_run.go (hunk 12 above)
Comment (ghost) [reply services/mailer/mail_workflow_run.go]: Ah, I mean currently no need to touch function definition again :sweat_smile: 
The linter isn't complaining. All checks pass.
Line 159-162. It's intentional. As success notify is redundant and not necessary in most cases, when run is success, nest in and check if recipient wants it or not.

File: routers/web/user/setting/notifications.go [hunk 13]
```diff
@@ -29,6 +30,19 @@ func Notifications(ctx *context.Context) {
...
 	ctx.Data["EmailNotificationsPreference"] = ctx.Doer.EmailNotificationsPreference
 
+	fineGrainedPreference, err := user_model.GetSettings(ctx, ctx.Doer.ID, []string{
+		user_model.SettingsEmailNotificationGiteaActions,
+	})
+	if err != nil {
+		ctx.ServerError("GetUserNotificationSettings", err)
+		return
+	}
+	actionsNotify := fineGrainedPreference[user_model.SettingsEmailNotificationGiteaActions].SettingValue
```
Comment (wxiaoguang) [inline routers/web/user/setting/notifications.go]: It will panic if the setting key doesn't exist.

The user setting system really needs a complete refactor

File: services/mailer/mail_workflow_run.go [hunk 14]
```diff
@@ -0,0 +1,166 @@
...
+				msg.SetHeader(k, v)
+			}
+			msg.SetHeader("Message-ID", messageID)
+			msgs = append(msgs, msg)
+		}
+		SendAsync(msgs...)
+	}
+}
+
+func SendActionsWorkflowRunStatusEmail(ctx context.Context, sender *user_model.User, repo *repo_model.Repository, run *actions_model.ActionRun) {
```
Comment (wxiaoguang) [inline services/mailer/mail_workflow_run.go]: Why there are two `SendActionsWorkflowRunStatusEmail` `sendActionsWorkflowRunStatusEmail` for different purposes ...

Is it possible to make them have different names?

File: routers/web/user/setting/notifications.go (hunk 13 above)
Comment (ghost) [reply routers/web/user/setting/notifications.go]: There's just one setting key for now. I just use GetUserSetting as a workaround.

**Review by lunny — APPROVED** [review]

File: models/user/email_notification_test.go [hunk 15]
```diff
@@ -0,0 +1,34 @@
...
+import (
+	"testing"
+
+	"code.gitea.io/gitea/models/db"
+	"code.gitea.io/gitea/models/unittest"
+
+	"github.com/stretchr/testify/assert"
+)
+
+func TestNotificationSettings(t *testing.T) {
```
Comment (wxiaoguang) [inline models/user/email_notification_test.go]: I think we should remove this test. It only tests the functions from the user setting module: `SetUserSetting` / `GetSetting`

**Comment by ghost** [comment]
:man_facepalming:

File: services/mailer/mail_workflow_run.go [hunk 16]
```diff
@@ -0,0 +1,166 @@
...
+		}
+		var mailBody bytes.Buffer
+		if err := LoadedTemplates().BodyTemplates.ExecuteTemplate(&mailBody, tplWorkflowRun, map[string]any{
+			"Subject":       subject,
+			"Repo":          repo,
+			"Run":           run,
+			"RunStatusText": runStatusText,
+			"Jobs":          convertedJobs,
+			"locale":        locale,
+			"Language":      locale.Language(),
```
Comment (wxiaoguang) [inline services/mailer/mail_workflow_run.go]: Why it needs to fill "Language" to template data?

**Comment by wxiaoguang** [comment]
> 🤦‍♂️ 

You can first understand what they do and what they affect before copying them.

**Review by wxiaoguang — APPROVED** [review]

**Comment by ghost** [comment]
> > 🤦‍♂️ 
> 
> You can first understand what they do and what they affect before copying them.

I haven't seen anywhere crappy so I would like to hear your thoughts. 
I refer a lot from elsewhere in the whole code base, and I see it potentially reusable/re-applicable if it's been there.
Other than that I'm fine.
Related #28145

**Comment by wxiaoguang** [comment]
> I haven't seen anywhere crappy so I would like to hear your thoughts.
> I refer a lot from elsewhere in the whole code base, and I see it potentially reusable/re-applicable if it's been there.
> Other than that I'm fine.
> Related #28145

* `_blank` already means `noopener`
* `<meta name="referrer" content="no-referrer">` already means `noreferrer`

**Comment by wxiaoguang** [comment]
> I refer a lot from elsewhere in the whole code base, and I see it potentially reusable/re-applicable if it's been there.

Actually we should never trust existing code, there are bugs and bad-smells. If you just copy-paste existing code, then there will be more bugs and bad-smells.

**Comment by wxiaoguang** [comment]
Will explain more "bad smells" in old code that I have made changes to:

1. It shouldn't duplicate `log.Error` when using `ServerError` which already logs the err
1. It shouldn't show 500 error page when the user input is invalid.
1. It shouldn't set `selected active` for a dropdown item, `selected` and `active` have different meanings
1. It shouldn't duplicate `{{if eq ...}}selected{{end}}` when using dropdown, the input value is the selected one and the framework already handles it
1. It shouldn't duplicate `rel="noopener noreferer"`, it only makes the translation more difficult (the affect has been explained above)

-----

Actually I can tolerate the nits in code (not serious bugs) if the PR was reviewed and merged by others, or I missed some of them. While if I am reviewing or writing code, I will always do my best to avoid the bad smells.

**Review by hiifong — APPROVED** [review]

**Comment by ankurk91** [comment]
@lunny 
this will land in 1.25?😬 please

**Comment by wxiaoguang** [comment]
Yes, it is in 1.25, great thanks to @NorthRealm and reviewers 🎉 

You can use it by the nightly build:

* https://dl.gitea.com/gitea/main-nightly/
* https://hub.docker.com/r/gitea/gitea/tags?name=nightly

**Comment by ghnp5** [comment]
Thank you so much for this!! 🥳🎉🧡

**Comment by ghost** [comment]
@NorthRealm 
How do I activate this feature? I have set up the mailer and the mailer seems to work. When clicking the Test button in the settings, the email is sent successfully. However, if a Action run fails, I do not get any emails.

**Comment by ghost** [comment]
@inxcts `[service] ENABLE_NOTIFY_MAIL=true`

**Comment by ghost** [comment]
> @inxcts `[service] ENABLE_NOTIFY_MAIL=true`

I also set this variable to true and restarted Gitea. When an action run fails, I still do net any emails. I still something is still missing.

**Comment by ghost** [comment]
@inxcts I'm pretty sure that's the key. Manually tested on local instance (localhost) and it's working as intended. Do you have a valid email address in your account? Is your mailbox provider putting gitea emails into spam folder?

**Comment by ghost** [comment]
@NorthRealm 

> @inxcts I'm pretty sure that's the key. Manually tested on local instance (localhost) and it's working as intended. Do you have a valid email address in your account? Is your mailbox provider putting gitea emails into spam folder?

The spam folder is empty. In the mailer section of the app.ini, I have put an email address that is not in use by any Gitea user, it is just used as the email account that Gitea should use. In the "FROM" variable, I have put the email address from my main account.

When navigating to the settings page, the mailer seems to work. When typing an email address and clicking the Test button, the email is sent to my account (the same that should be used for the actions).

**Comment by ghost** [comment]
@inxcts Enable Gitea trace log and see if anything like `New e-mail sending request []: Run failed`(failed/cancelled/succeeded) appears. If yes, then I don't see any issue on Gitea. If no, it probably means:
- Event is not triggered (not likely)
- Trigger user not eligible to receive emails.
- Trigger user has disabled action emails. (In current implementation it's independent from the existing email notification preference setting.)
- Trigger user is not you.
- Anywhere else that I have not noticed.

```
[mailer]
ENABLED = true
SMTP_ADDR = mailbox.host
SMTP_PORT = 465
PROTOCOL = smtps
FROM = noreply@email.domain
USER = noreply@email.domain
PASSWD = 
```
The above is my (dummy) mailer config. You usually don't "put the email address from your main account."

**Comment by ghost** [comment]
@NorthRealm 

When I commit something and the action fails, I now get the email. The problem seems to be that the job is scheduled.

`name: Nightly
on:
  schedule:
    - cron: "0 0 * * *"`

Is it possible to receive emails here or run the job with my user?

**Comment by ghost** [comment]
@inxcts I am not familiar with how Gitea determines trigger user. I looked at code base and did not find anywhere clear that logs an existing user as trigger user for a scheduled task. You get the email probably because of push trigger and you become the trigger user.
Prior in #23725 people had other workarounds.
To "run the job with your user", maybe trigger the run manually or with API?

**Comment by lunny** [comment]
@inxcts Please notice this feature will be released in v1.25

**Comment by ghost** [comment]
> @inxcts Please notice this feature will be released in v1.25

@lunny I know that this is a 1.25 feature, I am running the latest dev build.

@NorthRealm I think for scheduled builds, the repository owner should receive the emails(just like GitHub does), otherwise no one really knows that actions fail.

**Comment by PhantomPhoton** [comment]
FWIW, I'm in agreement with inxcts. I'm more interested in receiving notifications for scheduled actions when they fail vs push actions, as with push actions, I'm actively doing something and know to check. Having to check the results manually every morning is a chore I wish to avoid. Just my two cents.

That said, I really appreciate the work and feature and am very thankful for the project.

**Comment by ChristopherHX** [comment]
> I think for scheduled builds, the repository owner should receive the emails(just like GitHub does)

My experience is different. The user who has changed the schedule trigger yaml most recently  is the trigger of the run and email recipient on GitHub Actions, here is Gitea Actions the trigger and has no real user as target.

In very rare cases this is the repository owner for multi user projects.

---

There were discussions on how bad GitHubs behavior is, so it might make sense to actually use the repository owner for all non deliverable workflow failure notifications.

Some people might prefer, a repo setting to send all schedule failures to a custom user/team members / receive other event failures of other users as well.

---

Emoji Vote
- 😀 The user who last changed the schedule workflow trigger yaml = trigger + email target, just like GitHub
- 🚀 Use the owner for workflow emails without recipient, **but orgs cannot receive emails, then the org owners need to looked up**
- 👀 Repository setting to specify target audience of workflow email notifications

**Comment by ghnp5** [comment]
Thanks!! I suggest repository setting for email address, and if it's not set, default to "last changed".
