### PR TITLE
Fix admin queue page title and fix CI failures

### LINKED ISSUE #26408: Broken template in title of queues page
### Description

When visiting the queue overview on the Site Admin dashboard, the page title displays `Queue: %s`, presumably because visiting a detail page displays `Queue: [name-of-the-queue]`.

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

From the downloaded binaries, using systemd.

### Database

MySQL

### PR DESCRIPTION
**Pull request by wxiaoguang**
* Fix #26408
* Bypass the data race issue in "ssh" package
* Test eventsource failure

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Review by KN4CK3R — APPROVED** [review]

**Comment by silverwind** [comment]
Test failure likely unrelated - Data race in `TestGit/SSH`.

**Comment by wxiaoguang** [comment]
> Test failure likely unrelated - Data race in `TestGit/SSH`.

Already a PR:  Fix data race by using atomic value https://github.com/gliderlabs/ssh/pull/211

**Comment by silverwind** [comment]
Ah, nice, I opened https://github.com/go-gitea/gitea/issues/26411 to track it.

**Comment by wxiaoguang** [comment]
Use a trick to bypass the upstream data race bug. d682e1032de83fec81f520d3f224ba9c6fff3a0c

Let's see whether it works.

**Comment by wxiaoguang** [comment]
The patch works, CI passes

File: modules/ssh/ssh.go [hunk 1]
```diff
@@ -164,6 +165,9 @@ func sessionHandler(session ssh.Session) {
 }
 
 func publicKeyHandler(ctx ssh.Context, key ssh.PublicKey) bool {
+	// FIXME: the "ssh.Context" is not thread-safe, so db operations should use the immutable parent "Context"
+	parentCtx := reflect.ValueOf(ctx).Elem().FieldByName("Context").Interface().(context.Context)
```
Comment (silverwind) [inline modules/ssh/ssh.go:170]:
```suggestion
  // TODO: Remove after https://github.com/gliderlabs/ssh/pull/211
	parentCtx := reflect.ValueOf(ctx).Elem().FieldByName("Context").Interface().(context.Context)
```

**Comment by silverwind** [comment]
Giving this a bit more time for other reviewers, but ultimately we should land it soon to eliminate the intermittent CI failures related to the race.

**Comment by silverwind** [comment]
I guess it's better to land now to unblock other PRs.

**Comment by silverwind** [comment]
I suspect the race has something to do with go1.21 which already runs on the ci because we specify `go-version: ">=1.20"`. Might wanna lock that down.

**Comment by wxiaoguang** [comment]
A new failure, I think it's related to speed up TestEventSourceManagerRun #26262 : `EventSourceUpdateTime = time.Second`

```
--- FAIL: TestEventSourceManagerRun (31.56s)
    eventsource_test.go:83: 
        	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/eventsource_test.go:83
        	Error:      	Condition never satisfied
        	Test:       	TestEventSourceManagerRun
```
