### PR TITLE
Notify the user when the file path contains leading or trailing spaces and fix the error message for invalid file names.

### LINKED ISSUE #31478: Consider sanitizing filenames for whitespaces when creating a file from web interface
### Description

When creating a filename using the website you may accidentally add whitespace to the filename which can lead to unexpected events, attempting to clone a repo which contains a file that has a trailing whitespace on Windows leads to this error:

```
git clone https://demo.gitea.com/future/test-filename.git
Cloning into 'test-filename'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), done.
error: invalid path 'there-is-a-whitespace '
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

This leads me to open this discussion to see if it's worth asking the gitea devs to perform whitespace removal (trim) at both the end and start of the filename string so this can be prevented automatically.

### Gitea Version

1.23.0+dev-273-ga4899ffa24

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

test2
test1

### Git Version

demo.gitea.com

### Operating System

demo.gitea.com

### How are you running Gitea?

demo.gitea.com

### Database

None

### PR DESCRIPTION
**Pull request by charles7668**
close #31478

### CODE REVIEW

**Review by silverwind — APPROVED** [review]
Seems ok. Personally I would have tried to do it in frontend, but this is also fine and probably simpler than frontend stuff.

File: routers/web/repo/editor.go [hunk 1]
```diff
@@ -392,6 +392,14 @@ func EditFilePost(ctx *context.Context) {
 // NewFilePost response for creating file
 func NewFilePost(ctx *context.Context) {
 	form := web.GetForm(ctx).(*forms.EditRepoFileForm)
+
+	// trim leading and trailing spaces from the tree path
+	treePath := strings.Split(form.TreePath, "/")
+	for i, v := range treePath {
+		treePath[i] = strings.TrimSpace(v)
+	}
+	form.TreePath = strings.Join(treePath, "/")
```
Comment (wxiaoguang) [inline routers/web/repo/editor.go]: Hmm, the path could be something like `/ / / /`, just press Space Slash Space Slash on the editor page 🤣 

Then the tree path becomes "////", which doesn't seem good.

Comment (silverwind) [reply routers/web/repo/editor.go]: Another thing to consider is when editing a existing file with leading or trailing space in any tree path segment, previously, it could be saved, now it can't.

So maybe this mechanism needs to be restricted to file creations only.

Comment (silverwind) [reply routers/web/repo/editor.go]: Ah, we are already in `NewFilePost`, so above remark is invalid.

Comment (silverwind) [reply routers/web/repo/editor.go]: > Then the tree path becomes "////", which doesn't seem good.

I assume the backend would reject that? Seems like right behaviour to me.

Comment (wxiaoguang) [reply routers/web/repo/editor.go]: There are more edge cases: for example, what happens to `foo/ .. /bar`? Will it be rejected or become `foo/../bar` then become `bar`?

Comment (wxiaoguang) [reply routers/web/repo/editor.go]: Actually I think we could just warn the users on the UI, instead of doing too much for "replacing"

The more we do, the more edge cases come.

Comment (silverwind) [reply routers/web/repo/editor.go]: > There are more edge cases: for example, what happens to `foo/ .. /bar`? Will it be rejected or become `foo/../bar` then become `bar`?

Same as entering `..` before and I hope we don't follow this reference in backend.

Not sure about warning, for me it seems clear-cut that a user would never want leading/trailing whitespace in the file or folder names and if they really do, they ought to use a git client.

Comment (charles7668) [reply routers/web/repo/editor.go]: > Hmm, the path could be something like `/ / / /`, just press Space Slash Space Slash on the editor page 🤣
> 
> Then the tree path becomes "////", which doesn't seem good.

In this case, there is prevention by the front-end, we can't just type '/' in the path without any other character.

> There are more edge cases: for example, what happens to `foo/ .. /bar`? Will it be rejected or become `foo/../bar` then become `bar`?

In the current latest version, if the path is ' .. ' with leading or trailing spaces, it will cause some incorrect behavior because '..' with leading and trailing spaces is not allowed in the system.

For example, the test case 't1/ ../t2/test-1' will not be created, and the system will just respond with the same string.

Typing '..' might seem weird, but I believe that people who type '..' do it with meaningful intent (maybe the path is just copied from another location).

I also tried '../../../../test'. Paths outside the repository will be prevented by the current latest version.

Comment (charles7668) [reply routers/web/repo/editor.go]: Preventing this on the front-end is a good solution, but currently, we can't see spaces in the UI.

This is the current UI display, but every t-n I have added some leading or trailing space, which is not being shown.
image

To prevent this on the front-end, we have two choices:

1. Change the display to show spaces. This will let people see what they have typed and display a warning.
2. Just show a warning (I think this is not ideal because people can't see the full typed path in the current UI).

Comment (wxiaoguang) [reply routers/web/repo/editor.go]: Tested with GitHub, I think GitHub also uses my suggestion: do not do too much for end users, only warn them.

Comment (wxiaoguang) [reply routers/web/repo/editor.go]: GitHub has another good behavior: if `../` is inputted, then it changes the path to parent, not sure whether it is implemented in Gitea's UI.

Comment (charles7668) [reply routers/web/repo/editor.go]: > Tested with GitHub, I think GitHub also uses my suggestion: do not do too much for end users, only warn them.

On GitHub, it shows a warning but does not take any action for users. This is my test: 't2  /  t3   /   t4  /test' 
圖片
圖片

This problem is the same as #31478.

I'm not sure if we need to follow this behavior or not.

Comment (silverwind) [reply routers/web/repo/editor.go]: Given that GitHub has this warning, then I agree, we should implement it too.

Comment (delvh) [reply routers/web/repo/editor.go]: Both approaches sound good to me.
Both get an LGTM from me.

**Review by delvh — APPROVED** [review]

File: routers/web/repo/editor.go (hunk 1 above)
Comment (charles7668) [reply routers/web/repo/editor.go]: firefox_XPWa8Ls4eU


I added some warnings for users similar to GitHub. 
However, I have kept backend processing for spaces. 
On GitHub, it only removes spaces from filenames, not from parent directories. Since Gitea can run on different operating systems, leading or trailing spaces may cause some problems. Therefore, I have retained space processing.

**Comment by delvh** [comment]
@silverwind could you review again?

**Comment by wxiaoguang** [comment]
1. IMO trimming spaces in backend is not right (well, just my personal option, not a blocker if most people like this behavior)
2. Coding style: `showElem` vs `.style.display = ...`
3. There are still bugs, for example:
    * `input` something like `foo/../bar` causes incorrect result.
    * `document.querySelector('.ui.warning.message.flash-message.flash-warning')` may query other "flash message" incorrectly but not the "space-related" one.

**Comment by charles7668** [comment]
> 1. IMO trimming spaces in backend is not right (well, just my personal option, not a blocker if most people like this behavior)
> 
>     2. Coding style: `showElem` vs `.style.display = ...`
> 
>     3. There are still bugs, for example:
>        
>        * `input` something like `foo/../bar` causes incorrect result.

How can this bug be reproduced? I tried it but couldn't reproduce it.
firefox_V5c0V4tfCL


>        * `document.querySelector('.ui.warning.message.flash-message.flash-warning')` may query other "flash message" incorrectly but not the "space-related" one.
>        * the concern in https://github.com/go-gitea/gitea/pull/31507/files#r1657163784 is still not resolved, I do not think making `/ / / /` to `////` is right for backend path handling.

I will fix the other bug.

**Comment by wxiaoguang** [comment]
> How can this bug be reproduced? I tried it but couldn't reproduce it.

Paste `foo/../bar`

**Comment by charles7668** [comment]
Fixed bugs

Regarding the backend problem, I think we might need more information.

Actually, I tested Gitea on both Windows and Linux servers by creating a `  test  /  test2  /test` file.

On the Linux server, this file can be created successfully.

On the Windows server, it returns the following page and fails to create the file:

圖片

In my opinion, for consistency, we need to maintain the same behavior across different OS servers.

**Comment by wxiaoguang** [comment]
> On the Linux server, this file can be created successfully.
> On the Windows server, it returns the following page and fails to create the file:
> In my opinion, for consistency, we need to maintain the same behavior across different OS servers.


That's impossible, naturally Windows and Linux are different, eg: `the?file.txt`, `the*file.txt`, `the<file.txt`, `con`, `com1` .........

**Comment by wxiaoguang** [comment]
> > On the Linux server, this file can be created successfully.
> > On the Windows server, it returns the following page and fails to create the file:
> > In my opinion, for consistency, we need to maintain the same behavior across different OS servers.
> 
> That's impossible, naturally Windows and Linux are different, eg: `the?file.txt`, `the*file.txt`, `the<file.txt`, `con`, `com1` .........

Personally I would suggest never to run Gitea server on Windows

**Comment by diamante0018** [comment]
Any update on this ? 🙏

**Comment by lunny** [comment]
> As an alternative to trimming spaces, I fixed the error message when the file can't be created.
> 
> 圖片

Could you also change the title and resolve the conflicts?

**Comment by charles7668** [comment]
> > As an alternative to trimming spaces, I fixed the error message when the file can't be created.
> > 圖片
> 
> Could you also change the title and resolve the conflicts?

Updated and CI error seems not related

**Comment by lunny** [comment]
It looks like I can still create a file name with trailing whitespace.
图片

**Comment by charles7668** [comment]
> It looks like I can still create a file name with trailing whitespace. 图片

Based on this comment, I have changed the approach to not prevent users from creating spaces in the file name. Instead, a warning message will be shown if there are trailing or leading spaces, and an error message will be displayed if the file cannot be created on the server OS.

I think whether or not to process spaces in the backend can be proposed for discussion.

> > On the Linux server, this file can be created successfully.
> > On the Windows server, it returns the following page and fails to create the file:
> > In my opinion, for consistency, we need to maintain the same behavior across different OS servers.
> 
> That's impossible, naturally Windows and Linux are different, eg: `the?file.txt`, `the*file.txt`, `the<file.txt`, `con`, `com1` .........

**Comment by lunny** [comment]
> > It looks like I can still create a file name with trailing whitespace. 图片
> 
> Based on this comment, I have changed the approach to not prevent users from creating spaces in the file name. Instead, a warning message will be shown if there are trailing or leading spaces, and an error message will be displayed if the file cannot be created on the server OS.
> 
> I think whether or not to process spaces in the backend can be proposed for discussion.
> 
> Leading or trailing spaces are allowed on a Linux server, but if using a Windows server, it will show an error message.
> 
> > > On the Linux server, this file can be created successfully.
> > > On the Windows server, it returns the following page and fails to create the file:
> > > In my opinion, for consistency, we need to maintain the same behavior across different OS servers.
> > 
> > 
> > That's impossible, naturally Windows and Linux are different, eg: `the?file.txt`, `the*file.txt`, `the<file.txt`, `con`, `com1` .........

Yes. But no warning or error was displayed.

**Comment by charles7668** [comment]
> > > It looks like I can still create a file name with trailing whitespace. 图片
> > 
> > 
> > Based on this comment, I have changed the approach to not prevent users from creating spaces in the file name. Instead, a warning message will be shown if there are trailing or leading spaces, and an error message will be displayed if the file cannot be created on the server OS.
> > I think whether or not to process spaces in the backend can be proposed for discussion.
> > Leading or trailing spaces are allowed on a Linux server, but if using a Windows server, it will show an error message.
> > > > On the Linux server, this file can be created successfully.
> > > > On the Windows server, it returns the following page and fails to create the file:
> > > > In my opinion, for consistency, we need to maintain the same behavior across different OS servers.
> > > 
> > > 
> > > That's impossible, naturally Windows and Linux are different, eg: `the?file.txt`, `the*file.txt`, `the<file.txt`, `con`, `com1` .........
> 
> Yes. But no warning or error was displayed.

I referred to GitHub's behavior, which only checks when typing '/'. I have now fixed it to check after every typing.

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
I think this can be kept v1.23 only.
