### PR TITLE
Fix Quote Reply button on review diff

### LINKED ISSUE #13762: Quote reply on code review comment does not work
- Gitea version (or commit ref): 1.12.6
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No

## Description

When doing "Quote Reply" on a code review comment, the quoted text from the comment is not added in the reply form.

## Screenshots

image

The quoted text is missing:

image

However, the "Preview" tab DOES show the comment.

image

### PR DESCRIPTION
**Pull request by jpraet**
Fixes #13762

This fixes the "Quote Reply" button on the code review diff page.

I also noticed the focusing of the text area wasn't working for the "Quote Reply" as well as "Edit". Something else is stealing the focus. I tried to work around that with `event.stopPropagation()` at first, but that caused other issues. Once I wrapped the focus code in a `setTimeout(..., 0)` it started working. Might not be the cleanest solution?

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by silverwind** [comment]
> Something else is stealing the focus

Is there a `autofocus` element on the page? Also, you can try logging `document.activeElement` in the browser console to find the current focused element.

File: web_src/js/index.js [hunk 1]
```diff
@@ -901,25 +901,23 @@ async function initRepository() {
...
+      }
+      if ($simplemde !== null) {
+        if ($simplemde.value() !== '') {
+          $simplemde.value(`${$simplemde.value()}\n\n${content}`);
         } else {
-          autoSimpleMDE.value(`${content}`);
+          $simplemde.value(`${content}`);
         }
       }
+      setTimeout(() => {
```
Comment (silverwind) [inline web_src/js/index.js]: Note that `setTimeout` can be pretty slow to fire because it has low scheduling priority. I recommend using `requestAnimationFrame` where possible, or better yet, avoid these both altogether.

Comment (jpraet) [reply web_src/js/index.js]: Ok, I changed it to `requestAnimationFrame`. Without the setTimeout/requestAnimationFrame, the focus goes to the body element (checked with `document.activeElement`). I think it has something to do with the dropdown menu closing, but can't really afford to spend more time investigating that.

Comment (silverwind) [reply web_src/js/index.js]: Focus going to body usually means something is calling `.blur()` and I think it's probably coming from fomantic so we probably can't avoid it.

https://github.com/fomantic/Fomantic-UI/blob/develop/src/definitions/modules/dropdown.js

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@jpraet would be nice if you send a backport

**Comment by 6543** [comment]
-> #13898
