### PR TITLE
Fix unnecessary comment when moving issue on the same project column

### LINKED ISSUE #33482: Dragging items between and within columns in project boards
### Description

Our triagers reported the following user experience issues with Project boards after updating to Gitea 1.23.1:

- Project boards are now displayed as a table where the height matches the tallest column. Previously, they were constrained to fit within the browser view, with individual scrollbars for each column. This change makes dragging items between columns—especially from the bottom of one column to the top of another—more difficult.

- (resolved) ~~Moving an item laterally within a project board column appears to trigger an event, when it should likely just update its column placement.~~

<details>

<summary> (screenshot for 2, resolved)</summary>

Image

<details>

### Gitea Version

1.23.1 built with GNU Make 4.4.1, go1.23.5 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### PR DESCRIPTION
**Pull request by lunny**
Fix #33482

### CODE REVIEW

**Review by a1012112796 — APPROVED** [review]

**Review by hiifong — APPROVED** [review]

File: models/issues/issue_project.go [hunk 1]
```diff
@@ -38,13 +38,15 @@ func (issue *Issue) projectID(ctx context.Context) int64 {
...
-func (issue *Issue) ProjectColumnID(ctx context.Context) int64 {
+func (issue *Issue) ProjectColumnID(ctx context.Context) (int64, error) {
 	var ip project_model.ProjectIssue
 	has, err := db.GetEngine(ctx).Where("issue_id=?", issue.ID).Get(&ip)
-	if err != nil || !has {
-		return 0
+	if err != nil {
+		return 0, err
+	} else if !has {
+		return 0, nil
```
Comment (wxiaoguang) [inline models/issues/issue_project.go:47]: ~~IIRC the old code is done intentionally to make Gitea could self-heal if an column doesn't exist.~~

Hmm, new code could be right.

**Review by wxiaoguang — APPROVED** [review]
