### PR TITLE
Fix PR diff review form submit

### LINKED ISSUE #31622: PR Review Add Comment increments counter in Review button but CTRL+Enter shortcut doesn't
### Description

When reviewing a PR, adding a comment via the Add Comment button will increment the counter presented in the Review button in the top right corner.

When adding a comment and using the CTRL+Enter shortcut, the comment is added correctly, but the counter is not incremented.

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

We're running a docker container on a Linux VPC

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #31622.

There is a longstanding bug in #19612, it doesn't handle submit event correctly

This PR also rewrites some jQuery code

image

### CODE REVIEW

File: web_src/js/utils/dom.ts [hunk 1]
```diff
@@ -340,3 +347,11 @@ export function querySingleVisibleElem<T extends HTMLElement>(parent: Element, s
   if (candidates.length > 1) throw new Error(`Expected exactly one visible element matching selector "${selector}", but found ${candidates.length}`);
   return candidates.length ? candidates[0] as T : null;
 }
+
+export function addElemsEventListener<T extends HTMLElement>(parent: Node, type: string, selector: string, listener: (elem: T, e: Event) => void | Promise<any>, options?: boolean | AddEventListenerOptions) {
```
Comment (wxiaoguang) [inline web_src/js/utils/dom.ts]: To reviewers: this function helps migrating jQuery `$(document).on('click', selector, function() { this.xxx } )` to new code.

jQuery's `this` is `closest(selector)`, it is not `e.target`, nor `e.currentTarget`.

File: web_src/js/features/repo-diff.ts [hunk 2]
```diff
@@ -7,30 +7,19 @@ import {validateTextareaNonEmpty} from './comp/ComboMarkdownEditor.ts';
...
 import {initImageDiff} from './imagediff.ts';
 import {showErrorToast} from '../modules/toast.ts';
-import {submitEventSubmitter, queryElemSiblings, hideElem, showElem, animateOnce} from '../utils/dom.ts';
+import {
+  submitEventSubmitter,
+  queryElemSiblings,
+  hideElem,
+  showElem,
+  animateOnce,
+  addElemsEventListener, createElementFromHTML,
```
Comment (silverwind) [inline web_src/js/features/repo-diff.ts]:
```suggestion
  addElemsEventListener,
  createElementFromHTML,
```

**Review by yardenshoham — APPROVED** [review]

File: web_src/js/features/repo-diff.ts [hunk 3]
```diff
@@ -47,19 +36,15 @@ function initRepoDiffFileViewToggle() {
 }
 
 function initRepoDiffConversationForm() {
-  $(document).on('submit', '.conversation-holder form', async (e) => {
+  addElemsEventListener<HTMLFormElement>(document, 'submit', '.conversation-holder form', async (form, e) => {
     e.preventDefault();
+    const textArea = form.querySelector('textarea');
```
Comment (silverwind) [inline web_src/js/features/repo-diff.ts]:
```suggestion
    const textArea = form.querySelector<HTMLTextAreaElement>('textarea');
```

File: web_src/js/utils/dom.ts [hunk 4]
```diff
@@ -302,8 +302,15 @@ export function replaceTextareaSelection(textarea: HTMLTextAreaElement, text: st
 
 // Warning: Do not enter any unsanitized variables here
 export function createElementFromHTML(htmlString: string): HTMLElement {
```
Comment (silverwind) [inline web_src/js/utils/dom.ts]:
```suggestion
export function createElementFromHTML<T = HTMLElement>(htmlString: string): T {
```

and change the return types to `T`. This will allow the user to call the function with `createElementFromHTML<HTMLDivElement>('<div></div>')` for example.

File: web_src/js/utils/dom.ts [hunk 5]
```diff
@@ -302,8 +302,15 @@ export function replaceTextareaSelection(textarea: HTMLTextAreaElement, text: st
...
+  htmlString = htmlString.trim();
+  // some tags like "tr" are special, it must use a correct parent container to create
+  if (htmlString.startsWith('<tr')) {
```
Comment (silverwind) [inline web_src/js/utils/dom.ts:307]:
```suggestion
  if (htmlString.toLowerCase().startsWith('<tr')) {
```

File: web_src/js/utils/dom.ts (hunk 4 above)
Comment (wxiaoguang) [reply web_src/js/utils/dom.ts]: But we never use the `HTMLDivElement` type in code. The default `HTMLElement` is good enough

File: web_src/js/utils/dom.ts (hunk 1 above)
Comment (silverwind) [reply web_src/js/utils/dom.ts]: maybe call it `addDelegatedEventListener`?

File: web_src/js/utils/dom.ts (hunk 5 above)
Comment (wxiaoguang) [reply web_src/js/utils/dom.ts:307]: I do not think we should accept such dirty HTML tag in code.

`createElementFromHTML` is only used internally, not for uncontrolled contents.

File: web_src/js/utils/dom.ts (hunk 4 above)
Comment (silverwind) [reply web_src/js/utils/dom.ts]: But it might be useful in the future being able to specificy exact return type so one can avoid having to use `as`.

File: web_src/js/utils/dom.ts (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/utils/dom.ts]: done

**Review by silverwind — APPROVED** [review]

File: web_src/js/utils/dom.ts (hunk 4 above)
Comment (wxiaoguang) [reply web_src/js/utils/dom.ts]: `createElementFromHTML<T extends HTMLElement>` should be enough

File: web_src/js/utils/dom.ts [hunk 6]
```diff
@@ -301,10 +301,17 @@ export function replaceTextareaSelection(textarea: HTMLTextAreaElement, text: st
 }
 
 // Warning: Do not enter any unsanitized variables here
-export function createElementFromHTML(htmlString: string): HTMLElement {
+export function createElementFromHTML<T extends HTMLElement>(htmlString: string): T {
```
Comment (silverwind) [inline web_src/js/utils/dom.ts:304]: With `extends`, the type parameter becomes required, right? I would prefer it to be optional.

Does `T extends HTMLElement = HTMLElement` work?

Comment (wxiaoguang) [reply web_src/js/utils/dom.ts:304]: `T extends HTMLElement` implies `HTMLElement` by default, if I understand correctly.

image

File: web_src/js/utils/dom.ts (hunk 4 above)
Comment (silverwind) [reply web_src/js/utils/dom.ts]: Maybe, but see below.

File: web_src/js/utils/dom.ts (hunk 6 above)
Comment (silverwind) [reply web_src/js/utils/dom.ts:304]: If there is no `tsc` error at the call site, it should be fine, please check `npx tsc`.

Comment (wxiaoguang) [reply web_src/js/utils/dom.ts:304]: `npx tsc | grep dom.test.ts` find nothing

Comment (silverwind) [reply web_src/js/utils/dom.ts:304]: Ok then. I wasn't aware the `extends` also implies a default, but as per your screenshot, it seems to work.
