### PR TITLE
Fix EasyMDE toolbar

### LINKED ISSUE #24486: EasyMDE toolbar is broken
Related to https://github.com/go-gitea/gitea/pull/24471

I think we should keep EasyMDE, or at least find an alternative. Because when writing Wiki page, it is useful.

image

### PR DESCRIPTION
**Pull request by silverwind**
Fixes https://github.com/go-gitea/gitea/issues/24486

The "clean block" button is gone because I could not find a matching octicon. Order of buttons is roughly equal to textarea.

Screenshot 2023-05-02 at 21 10 00

### CODE REVIEW

File: web_src/js/features/comp/ComboMarkdownEditor.js [hunk 1]
```diff
@@ -204,11 +203,87 @@ class ComboMarkdownEditor {
...
+  prepareEasyMDEToolbarActions(EasyMDE) {
     this.easyMDEToolbarDefault = [
-      'bold', 'italic', 'strikethrough', '|', 'heading-1', 'heading-2', 'heading-3', 'heading-bigger', 'heading-smaller', '|',
-      'code', 'quote', '|', 'gitea-checkbox-empty', 'gitea-checkbox-checked', '|',
-      'unordered-list', 'ordered-list', '|', 'link', 'image', 'table', 'horizontal-rule', '|', 'clean-block', '|',
+      {
+        name: 'heading',
+        action: EasyMDE.toggleHeading3,
+        icon: svg('octicon-heading'),
+        title: 'Heading',
```
Comment (wxiaoguang) [inline web_src/js/features/comp/ComboMarkdownEditor.js]: Could we find some h1-h3 icons for the editor? I guess it might be useful.

Comment (silverwind) [reply web_src/js/features/comp/ComboMarkdownEditor.js]: Sorry, but I'm not motivated right now for that. If we do it, we could extend both editors with it, but I see that as a task for later.

File: web_src/js/features/comp/ComboMarkdownEditor.js [hunk 2]
```diff
@@ -204,11 +203,87 @@ class ComboMarkdownEditor {
     });
   }
 
-  prepareEasyMDEToolbarActions() {
+  prepareEasyMDEToolbarActions(EasyMDE) {
     this.easyMDEToolbarDefault = [
```
Comment (wxiaoguang) [inline web_src/js/features/comp/ComboMarkdownEditor.js:208]: this is only the "default". "repo-wiki.js" also has its own toolbar.

Comment (silverwind) [reply web_src/js/features/comp/ComboMarkdownEditor.js:208]: Hmm yes, wiki still broken

image

File: web_src/js/features/comp/ComboMarkdownEditor.js (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/features/comp/ComboMarkdownEditor.js:212]: Leave the wiki editor toolbar broken?

Comment (wxiaoguang) [reply web_src/js/features/comp/ComboMarkdownEditor.js:212]: I guess it could keep the string name, and replace them with Gitea's definition.

File: web_src/js/features/comp/ComboMarkdownEditor.js (hunk 2 above)
Comment (wxiaoguang) [reply web_src/js/features/comp/ComboMarkdownEditor.js:208]: I guess it could keep the string name, and replace them with Gitea's definition (just like gitea-switch-to-textarea or gitea-checkbox-checked, easyMDEToolbarActions)


( Oops, sorry for wrong comment 😭 )

File: web_src/js/features/comp/ComboMarkdownEditor.js (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/features/comp/ComboMarkdownEditor.js]: Good news is that we do not need any new icon (not a must, just to share)

```
.editor-toolbar button.heading-1::after {
    content: "1";
}
.editor-toolbar button::after {
    font-family: Arial,Helvetica Neue,Helvetica,sans-serif;
    font-size: 65%;
    vertical-align: text-bottom;
    position: relative;
    top: 2px;
}
```

File: web_src/js/features/comp/ComboMarkdownEditor.js (hunk 2 above)
Comment (silverwind) [reply web_src/js/features/comp/ComboMarkdownEditor.js:208]: Wiki fixed, idk why preview icon does not show:

Screenshot 2023-05-02 at 20 10 13

File: web_src/js/features/comp/ComboMarkdownEditor.js (hunk 1 above)
Comment (silverwind) [reply web_src/js/features/comp/ComboMarkdownEditor.js]: Fixed:

image

File: web_src/js/features/comp/ComboMarkdownEditor.js (hunk 2 above)
Comment (silverwind) [reply web_src/js/features/comp/ComboMarkdownEditor.js:208]: Preview icon only shows in fullscreen:

image

File: web_src/js/features/repo-wiki.js [hunk 3]
```diff
@@ -53,13 +53,7 @@ async function initRepoWikiFormEditor() {
...
     easyMDEOptions: {
       previewRender: (_content, previewTarget) => previewTarget.innerHTML, // disable builtin preview render
-      toolbar: ['bold', 'italic', 'strikethrough', '|',
-        'heading-1', 'heading-2', 'heading-3', 'heading-bigger', 'heading-smaller', '|',
-        'gitea-code-inline', 'code', 'quote', '|', 'gitea-checkbox-empty', 'gitea-checkbox-checked', '|',
-        'unordered-list', 'ordered-list', '|',
-        'link', 'image', 'table', 'horizontal-rule', '|',
-        'clean-block', 'preview', 'fullscreen', 'side-by-side', '|', 'gitea-switch-to-textarea'
-      ],
+      isWiki: true,
```
Comment (wxiaoguang) [inline web_src/js/features/repo-wiki.js]: Could we not use this `isWiki`?

We can just make all buttons as an object map, let callers choose which buttons they need.

Otherwise , the `isWiki` creates a strange dependency between the component and it's callers.

Comment (silverwind) [reply web_src/js/features/repo-wiki.js]: Caller needs access to `EasyMDE` object to define button actions, so no, not easily.

Comment (wxiaoguang) [reply web_src/js/features/repo-wiki.js]: From a framework view, the wiki uses editor, tells the editor which buttons it needs, while the editor shouldn't share wiki's knowledge.

Comment (silverwind) [reply web_src/js/features/repo-wiki.js]: Feel free to edit, but from my point of view, current version is sufficient.

Comment (wxiaoguang) [reply web_src/js/features/repo-wiki.js]: > Caller needs access to EasyMDE object to define button actions, so no, not easily.

I have done so, that's how the `gitea-...` buttons work.

>  Feel free to edit, but from my point of view, current version is sufficient.

I have no writer permission.

Comment (silverwind) [reply web_src/js/features/repo-wiki.js]: > > Caller needs access to EasyMDE object to define button actions, so no, not easily.
> 
> I have done so, that's how the `gitea-...` buttons work.
> 
> > Feel free to edit, but from my point of view, current version is sufficient.
> 
> I have no writer permission.

Now you have, I guess you could somehow map it from string during initialization, yes. Just remember `clean-block`, `heading-bigger`, `heading-smaller` are gone so far.

Comment (wxiaoguang) [reply web_src/js/features/repo-wiki.js]: I will try. And I guess it's better to move the EasyMDE action code into a separate file, to keep our editor JS simple, and make the future removal of EasyMDE easier. 

I will try, just a while.

Comment (silverwind) [reply web_src/js/features/repo-wiki.js]: The `isWiki` addition also added a bug `can't access property "isWiki", this.options.easyMDEOptions is undefined` in the non-wiki init, but I guess you can fix that as well 😆

Comment (wxiaoguang) [reply web_src/js/features/repo-wiki.js]: Done in 9e9a4e7a59b9d070b0a48ead38ead9f940c6fca0

**Review by wxiaoguang — APPROVED** [review]

File: web_src/js/features/repo-wiki.js (hunk 3 above)
Comment (silverwind) [reply web_src/js/features/repo-wiki.js]: Works, thanks.

**Review by yardenshoham — APPROVED** [review]
