### PR TITLE
Fix overdue marking of closed issues and milestones

### LINKED ISSUE #14536: [Bug] Don't mark due date in merged/ closed PRs as overdue
- Gitea version (or commit ref): 1.14.0+dev-646-g6064bfa3c
- Can you reproduce the bug at https://try.gitea.io:
  - [Yes](https://try.gitea.io/delvh/kanban-test/pulls?q=&type=all&sort=&state=closed&labels=&milestone=0&assignee=0)

## Description
Currently when a PR has a due date and gets merged or closed, it will, after the due date has expired, get displayed as overdue, even if it was merged on time. This always gets confusing when looking at closed PRs.
The question is: Is it really needed to display the due date when a PR has been closed (independent from if it was closed or merged)?
I'd argue that leaving it out for any closed/ merged PR would suffice to solve the problem, as there is no real value in leaving it in.
Another possible approach would be to display the due date in a PR merged on time normally, and otherwise overdue. This approach however is most likely more complex to implement.
I'm fine with both.
...

## Screenshots
image

### PR DESCRIPTION
**Pull request by zeripath**
Closed milestones and issues should only be marked overdue if they were
closed after their deadline.

Fix: #14536

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

File: models/issue.go [hunk 1]
```diff
@@ -97,6 +97,9 @@ func (issue *Issue) loadTotalTimes(e Engine) (err error) {
 
 // IsOverdue checks if the issue is overdue
 func (issue *Issue) IsOverdue() bool {
+	if issue.IsClosed {
```
Comment (6543) [inline models/issue.go:100]: If you close an issue before deadline it will be marked overdue

shouldn't we just return false if IsClosed?

Comment (delvh) [reply models/issue.go:100]: I think I mentioned that in the issue:
Basically there are two possible options for closed issues/PRs -
a) we simply hide it/ show it as not overdue
b) we differentiate between whether it has been closed on time or not.
Both are in my opinion valid. The currently suggested approach is b)

What I am asking myself is:
Is that function also getting called when rendering the PR conversation page where the due date gets displayed?
Because if that is the case then I would say we should stick to the currently suggested behavior, because that is the one place where it certainly should always get displayed correctly

Comment (zeripath) [reply models/issue.go:100]: @6543 how are you getting if you close an issue before its deadline it will be marked overdue for this test? 

`issue.ClosedUnix >= issue.DeadlineUnix
`

Comment (zeripath) [reply models/issue.go:100]: There is a question of what happens if you reopen and then reclose an issue. That would make the issue overdue

Comment (6543) [reply models/issue.go:100]: ah sure ... missed that one

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:
