### PR TITLE
Fix assigned issues dashboard

### LINKED ISSUE #503: Issues: Assigned to me
This is a much needed feature, to easily keep an overview over issues assigned to yourself. A PR was made on Gogs here https://github.com/gogits/gogs/pull/3560

### PR DESCRIPTION
**Pull request by lunny**
fix #503

### CODE REVIEW

**Comment by lunny** [comment]
@jeppech could you try to confirm this?

**Comment by jeppech** [comment]
@lunny This works perfectly, thank you!
nj4xk4

File: models/issue.go [hunk 1]
```diff
@@ -1298,29 +1321,39 @@ func GetUserIssueStats(repoID, uid int64, repoIDs []int64, filterMode int, isPul
...
 
-	stats.CreateCount, _ = countSession(false, isPull, repoID, repoIDs).
+	stats.CreateCount, _ = countSession(false, isPull, repoID, nil).
 		And("poster_id = ?", uid).
-		Count(&Issue{})
+		Count(new(Issue))
 
-	openCountSession := countSession(false, isPull, repoID, repoIDs)
-	closedCountSession := countSession(true, isPull, repoID, repoIDs)
+	stats.YourRepositoriesCount, _ = countSession(false, isPull, repoID, repoIDs).
```
Comment (ethantkoenig) [inline models/issue.go:1332]: I don't like this. We're essentially assuming that the repositories in `repoIDs` are exactly the set of repositories that *some* user owns. Moreover, this will return the wrong count if `repoID > 0`.

Comment (ethantkoenig) [reply models/issue.go:1332]: It would be nice if we could change the interface of `GetUserIssueStats` so that we don't need to make these sort of implicit assumptions.

**Review by ethantkoenig — CHANGES_REQUESTED** [review]

File: models/issue.go (hunk 1 above)
Comment (lunny) [reply models/issue.go:1332]: I cherry-pick from gogits/Gogs#3560 and resolved the conflicts. I think we can improve this in further PRs.

Comment (ethantkoenig) [reply models/issue.go:1332]: Ok fine

**Review by ethantkoenig — APPROVED** [review]

**Comment by ethantkoenig** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Comment by Lourens-Rich** [comment]
Update to https://github.com/go-gitea/gitea/commit/43c94d0a6cd8daf01125df3bf895f1beb1bcd664 give me that: `template: user/dashboard/issues:10:44: executing "user/dashboard/issues" at <.IssueStats.YourRepo...>: YourRepositoriesCount is not a field of struct type interface {}`

**Comment by lunny** [comment]
Have you recompile Gitea?

**Comment by Lourens-Rich** [comment]
Ops. First time when a forgot this, sorry.
