### PR TITLE
Fix markdown meta parsing

### LINKED ISSUE #12815: Issue template format should be more forgiving
The recently merged #11450 contains a potential flaw. 

## The problem

Using the example I added to the docs
```yaml
-----
name: "Template Name"
about: "This template is for testing!"
title: "[TEST] "
labels:
  - bug
  - "help needed"
-----
This is the template!
```
will not actually work.

This is because the `ExtractMetadata` func actually tries to parse everything within the separators, _including_ the separators themselves. As a matter of fact if you look closely at the above block, syntax highlighting reveals the issue with the `-` separators.

While YAML does allow a similar format for "blocks", those _must_ be three hyphens, which means currently issue templates expect a specific number of hyphens to work.

## The solution

The `ExtractMetadata` func should only parse between the lines, e.g.
```yaml
name: "Template Name"
about: "This template is for testing!"
title: "[TEST] "
labels:
  - bug
  - "help needed"
```

This would allow users to use any amount of hyphens (as long as it's two or more so that lists aren't confused as separators)

### PR DESCRIPTION
**Pull request by jolheiser**
Fixes #12815 

This code should now exclude the separator lines themselves, so as long as there are two or more hyphens it will work as a separator and also YAML won't choke.

Included a minimal test case.

### CODE REVIEW

File: modules/markup/markdown/meta.go [hunk 1]
```diff
@@ -25,15 +25,16 @@ func isYAMLSeparator(line string) bool {
 // and returns the frontmatter metadata separated from the markdown content
 func ExtractMetadata(contents string, out interface{}) (string, error) {
```
Comment (zeripath) [inline modules/markup/markdown/meta.go:26]: AFAIU The yaml front matter must be the first thing in the file.

Therefore line[0] must be a line SEP and there must be another SEP later on
Then yaml starts at line[1] and continues until there is a SEP.

Thus this should be: check line 0, if SEP, find next SEP line and take lines [1:SEPline] to give to yaml. And the content is lines[SEPline+1:]

No need to keep two seps around.

Comment (jolheiser) [reply modules/markup/markdown/meta.go:26]: I suppose so. I guess the only difference is this would allow someone to have a blank line as the first line.  
Not sure why/when that would happen, but it could.

Do you want me to require the first sep being line 1? ~~Line 0 if you think in slices~~

Comment (zeripath) [reply modules/markup/markdown/meta.go:26]: Dunno - have you seen a spec for yaml front matter? How does yuin meta handle this?

Comment (jolheiser) [reply modules/markup/markdown/meta.go:26]: It looks like it does enforce the first line being a separator. I can change it.

Comment (jolheiser) [reply modules/markup/markdown/meta.go:26]: Well, it now enforces a first separator. 
The bad news is the func is longer now. 

It occurred to me that `idx+1` is probably not a great idea in a slice of unknown length, e.g. a template with no body.

So now it checks for remaining lines before setting the body. This way someone could make an issue template with only frontmatter if they wanted.

Comment (zeripath) [reply modules/markup/markdown/meta.go:26]: Go is very kind.

```go
a := "0123456789"
fmt.Println(a[9:], a[10:])
```
https://play.golang.org/p/1s393Y2bknc

Doesn't panic.

`a[10]` and `a[11:]` do panic, but a slice starting at `len(a)` doesn't.

File: modules/markup/markdown/meta.go [hunk 2]
```diff
@@ -25,20 +25,25 @@ func isYAMLSeparator(line string) bool {
...
+			if !isYAMLSeparator(line) {
+				return "", errors.New("frontmatter must start with a separator line")
+			}
+			continue
 		}
 		if isYAMLSeparator(line) {
-			seps++
-			continue
+			front = lines[1:idx]
+			if len(lines) >= idx+1 {
```
Comment (zeripath) [inline modules/markup/markdown/meta.go]: This will always be true.

idx will always be less than len(lines).

File: modules/markup/markdown/meta.go (hunk 1 above)
Comment (jolheiser) [reply modules/markup/markdown/meta.go:26]: I see. Okay, I've changed it back to the one-line then. Tests for an empty body still passed :+1:

**Review by zeripath — APPROVED** [review]

File: modules/markup/markdown/meta.go [hunk 3]
```diff
@@ -25,20 +25,22 @@ func isYAMLSeparator(line string) bool {
 // and returns the frontmatter metadata separated from the markdown content
 func ExtractMetadata(contents string, out interface{}) (string, error) {
 	var front, body []string
-	var seps int
 	lines := strings.Split(contents, "\n")
 	for idx, line := range lines {
```
Comment (lunny) [inline modules/markup/markdown/meta.go:29]: It's better to use `Scanner`.
```go
scanner := bufio.NewScanner(strings.NewReader(contents))
var idx = 0 
for scanner.Scan() {
    line := scanner.Text()
    ...
    idx++
}
```

Comment (jolheiser) [reply modules/markup/markdown/meta.go:29]: What's the advantage in this case?
We still need to scan the whole file so we can return body, and we've already checked file size prior to calling this func.

**Review by mrsdizzie — APPROVED** [review]

File: modules/markup/markdown/meta.go (hunk 3 above)
Comment (lunny) [reply modules/markup/markdown/meta.go:29]: Less CPU and memory usage. But since it should be a small file, it's not necessary.
