### PR TITLE
Fix content holes in Actions task logs file

### LINKED ISSUE #25451: `scan: bufio.Scanner: token too long` when clicking actions sections
### Description

1. Open https://gitea.com/gitea/gitea-docusaurus/actions/runs/133/jobs/0
2. Click any section in the run
3. Nothing happens, stays stuck loading forever and logs an error in the console

Error should be made visible in UI, either inline at the loader or with a [toast](https://github.com/go-gitea/gitea/pull/25449).

Screenshot 2023-06-22 at 21 10 02

### Gitea Version

1.20.0+dev-999-g8d7893e81

### PR DESCRIPTION
**Pull request by wolfogre**
Fix #25451.

Bugfixes:
- When stopping the zombie or endless tasks, set `LogInStorage` to true after transferring the file to storage. It was missing, it could write to a nonexistent file in DBFS because `LogInStorage` was false.
- Always update `ActionTask.Updated` when there's a new state reported by the runner, even if there's no change. This is to avoid the task being judged as a zombie task.

Enhancement:
- Support `Stat()` for DBFS file.
- `WriteLogs` refuses to write if it could result in content holes.

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

File: models/dbfs/dbfile.go [hunk 1]
```diff
@@ -193,10 +195,26 @@ func (f *file) Close() error {
 	return nil
 }
 
+func (f *file) Stat() (os.FileInfo, error) {
+	if f.metaID == 0 {
+		return nil, os.ErrInvalid
```
Comment (wxiaoguang) [inline models/dbfs/dbfile.go:200]: ~~Other code returns `os.ErrNotExist` for this case~~

Comment (wxiaoguang) [reply models/dbfs/dbfile.go:200]: Hmm ... not consistent. This check should never be true because Open would never return a "file" with ID=0.

So I think it's fine
