### PR TITLE
Fix mermaid flowchart margin issue

### LINKED ISSUE #27435: Text is not visible on Mermaid flowchart shapes with markdown string labels
### Description

When I use the [markdown string](https://mermaid.js.org/syntax/flowchart.html#markdown-strings) feature to format mermaid flowchart labels, the label position is off by a few pixels, so that most of the text is hidden.

Example:
https://try.gitea.io/terius/MermaidTest/src/branch/main/README.md
```
flowchart LR
TEST{{"`**Rendering problem**`"}}
```
gitea-mermaid

I guess this is due to mermaid uses ``<p>`` tag for markdown labels and gitea renders mermaid inside an ``<iframe>``. Seems like chrome adds some default margin to ``<p>``-tags inside iframes.

There is an ``iframeCss`` const in [mermaid.js](https://github.com/go-gitea/gitea/blob/main/web_src/js/markup/mermaid.js#L9). Adding a style to set margin to 0 for the iframe might fix the issue?
```css
p {margin: 0}
```

### Gitea Version

1.22.0+dev-101-g112f37c54

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Tested with try.gitea.io

### Database

None

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/27435
Related: https://github.com/mermaid-js/mermaid/issues/4907

image

### CODE REVIEW

File: web_src/js/markup/mermaid.js [hunk 1]
```diff
@@ -4,9 +4,11 @@ import {displayError} from './common.js';
 
 const {mermaidMaxSourceCharacters} = window.config;
 
+// margin removal is for https://github.com/mermaid-js/mermaid/issues/4907
 const iframeCss = `:root {color-scheme: normal}
 body {margin: 0; padding: 0; overflow: hidden}
-#mermaid {display: block; margin: 0 auto}`;
+#mermaid {display: block; margin: 0 auto}
+blockquote, dd, dl, figure, h1, h2, h3, h4, h5, h6, hr, p, pre {margin: 0}`;
```
Comment (zeripath) [inline web_src/js/markup/mermaid.js:11]: Shouldn't this be

`#mermaid blockquote ,#mermaid dd, #mermaid dl, #mermaid figure, #mermaid h1, #mermaid h2, #mermaid h3, #mermaid h4, #mermaid h5, #mermaid h6, #mermaid hr, #mermaid p, #mermaid pre { margin: 0}`

Comment (silverwind) [reply web_src/js/markup/mermaid.js:11]: This CSS is already contained in an iframe, so there is no risk of the rules affecting the outside page. Adding these would likely introduce more issues because of CSS specificity. The [mermaid demo](https://mermaid.live) has the exact same rules, too.

**Review by delvh — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

File: web_src/js/markup/mermaid.js (hunk 1 above)
Comment (zeripath) [reply web_src/js/markup/mermaid.js:11]: ah sorry I missed that!
