### PR TITLE
Fix Go 1.13 private repository go get issue

### LINKED ISSUE #8095: Gitea returns import path for organization
- Gitea version (or commit ref): 1.9.2
- Git version: 2.22.0
- Operating system: Manjaro 18.0.4
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

To quote:

> In module mode in Go 1.13, the go command checks all possible module paths in parallel for the requested package.

Gitea returns a non-valid Git fetch URL for e.g. `https://try.gitea.io/test`, as seen in the example below. This makes it impossible to use Go modules pulling dependencies from a private Gitea instance, because Go 1.13 expects no clone URL if it is not a valid repository path (see GitLab behavior). This issue is related to golang/go#34075. See that issue for more information.

```
$ curl https://try.gitea.io/test/?go-get=1  
<!doctype html>
<html>
        <head>
                <meta name="go-import" content="try.gitea.io/test git https://try.gitea.io/test/.git">
                <meta name="go-source" content="try.gitea.io/test _ https://try.gitea.io/test/src/branch/master{/dir} https://try.gitea.io/test/src/branch/master{/dir}/{file}#L{line}">
        </head>
        <body>
                go get try.gitea.io/test
        </body>
</html>
```

But test is an organization and this information should not be added, as it makes it impossible to retrieve dependencies using go get in Go 1.13.

### PR DESCRIPTION
**Pull request by rutgerbrf**
Fixes #8095.

### CODE REVIEW

File: modules/context/context.go [hunk 1]
```diff
@@ -249,6 +249,17 @@ func Contexter() macaron.Handler {
 		if ctx.Query("go-get") == "1" {
 			ownerName := c.Params(":username")
 			repoName := c.Params(":reponame")
+			if ownerName == "" || repoName == "" {
+				_, _ = c.Write([]byte(`<!doctype html>
```
Comment (lunny) [inline modules/context/context.go:255]: if returned error, you should give a 500 I think.

File: modules/context/repo.go [hunk 2]
```diff
@@ -202,6 +202,9 @@ func ComposeGoGetImport(owner, repo string) string {
 func EarlyResponseForGoGetMeta(ctx *Context) {
 	username := ctx.Params(":username")
 	reponame := ctx.Params(":reponame")
+	if username == "" || reponame == "" {
+		ctx.PlainText(404, []byte("invalid repository path"))
```
Comment (lunny) [inline modules/context/repo.go]: return

**Review by lunny — CHANGES_REQUESTED** [review]

File: modules/context/context.go (hunk 1 above)
Comment (sapk) [reply modules/context/context.go:255]: Why not see the problem the other way and simply ignore go-get params instead of erroring ?
```
if ctx.Query("go-get") == "1" && ownerName != "" && repoName != "" {

}
```

Comment (sapk) [reply modules/context/context.go:255]: This could be break down in two `if` obviously.
```
if ctx.Query("go-get") == "1" 
  ownerName := c.Params(":username")
  repoName := c.Params(":reponame")
  if ownerName != "" && repoName != "" {
	... Do go-get work
  }
}
```

File: modules/context/repo.go [hunk 3]
```diff
@@ -202,6 +202,9 @@ func ComposeGoGetImport(owner, repo string) string {
 func EarlyResponseForGoGetMeta(ctx *Context) {
```
Comment (sapk) [inline modules/context/repo.go:202]: Same here we can check previously to calling this method and maybe pass `username` and `reponame` as args since they are already extracted and cleaned from context before calling:
https://github.com/go-gitea/gitea/blob/85202d4784758573f80f93dbbda97a444e7ece99/routers/repo/http.go#L58

File: modules/context/context.go (hunk 1 above)
Comment (lunny) [reply modules/context/context.go:255]: But else we still need return 404 but not continue the other work.

Comment (lunny) [reply modules/context/context.go:255]: Once `ctx.Query("go-get") == "1" `, it should return anyway here.

File: modules/context/repo.go (hunk 3 above)
Comment (rutgerbrf) [reply modules/context/repo.go:202]: Would it not be preferable to add this for `username` as well in case only `.git` is appended to the Gitea instance URL?

Comment (rutgerbrf) [reply modules/context/repo.go:202]: I guess not because it seems possible to have the suffix `.git` in a username or organization name.

File: modules/context/context.go (hunk 1 above)
Comment (rutgerbrf) [reply modules/context/context.go:255]: I think a 400 should be returned because in this case the client has not provided adequate information for the server to provide an import URL from the its request.

Comment (rutgerbrf) [reply modules/context/context.go:255]: https://github.com/go-gitea/gitea/blob/85202d4784758573f80f93dbbda97a444e7ece99/routers/repo/http.go#L58 I suppose this should also be applied in this case.

Comment (rutgerbrf) [reply modules/context/context.go:255]: Or perhaps in `trimmedRepoName`, such that this is not interfered with:
https://github.com/go-gitea/gitea/blob/bb609caceee95abfabfbb27bc2683339fe551fbf/modules/context/context.go#L258

Comment (sapk) [reply modules/context/context.go:255]: Why we should return an error ? For exemple github doesn't trigger an error on an profile if you use go-get param. Futhermore triggering an error from a supervision point could be misleading. I will not block as it need a quick fix.

**Review by lunny — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]

**Review by techknowlogick — DISMISSED** [review]
This should be sent to master branch first. I'm going to mark this as blocked so we don't merge this prematurely.

**Comment by lunny** [comment]
@rutgerbrf please send a PR to master at first.

**Comment by lunny** [comment]
Since #8112 merged, I have removed the blocked label. @techknowlogick

**Comment by lafriks** [comment]
@techknowlogick it is been merged to master please approve
