### PR TITLE
Inherit submodules from template repository content

### LINKED ISSUE #10316: When using templates, submodules do not get "inherited"
- Gitea version (or commit ref): 1.11.1
- Git version: 2.23.1
- Operating system: NixOS
- Database: shouldn't matter, if so, please write
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (POC can be found [here](https://try.gitea.io/hanemile))
  - [ ] No
  - [ ] Not relevant

## Description

So I tried out the new template feature and found out, that when using templates, submodules do not get "inherited".

### Reproduction

1. Create a repo **A** that should be used as a template
1. Mark the repo **A** as a template in the repos settings
1. Create a repo **B** using the repo **A** as a submodule: `git submodule add <repo A>`
1. Create a repo **C** using **B** as a template. My result is that **C** does not contains the submodule **A**.

### LINKED ISSUE #32970: Submodules in Templates Aren't Added to Generated Repositories
### Description

If you create a template repository containing a submodule, any repositories created from that template do not have the submodule added to it. Specifically, while the ".gitmodules" file is added to the created repository, the submodule object for the folder does not. This means that calls to `git submodule init` or similar will not work.

My expectation would be that the created repository from the template would contain either a copy of the submodule within it, or a newly generated submodule object. This would allow the cloning developer to use `git clone --recurse-submodules` to fully create the repository in one go.

I have created an example repository on the Gitea demo site here: https://demo.gitea.com/Vingenuity/submodule-templated-repository demonstrating this issue.

NOTE: This is a different issue from https://github.com/go-gitea/gitea/issues/10316, which is about templates of templates.

### Gitea Version

1.22.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Unraid

### How are you running Gitea?

I am running the official gitea Docker container via Unraid.

### Database

None

### PR DESCRIPTION
**Pull request by sschroe**
This PR addresses issue #10316 and makes submodules available in repositories created from templates.
Submodules are now inherited when creating a new repository from a template with "Git Content" checked, 

Unlike the initial suggestion provided by @davidsvantesson in the original issue i decided not to use `git submodule status` initially because its output can look like this:
```
 0dff7e5493898954537202c0c975f7b1c55d0845 lib (no%_()delay)1 (heads/master)
```
Submodule names can contain all sorts of special characters and the `(heads/master)` part is not always present in the output which makes reliably parsing the name out of this quite a pain if not impossible. I replaced this step with `git config -f .gitmodules --list --name-only` which will give:
```
submodule.lib (no%_()delay)1.path
submodule.lib (no%_()delay)1.url
```
This is far easier to parse and provides the necessary submodule name. `git submodule status lib (no%_()delay)1` is then used as second step to get the commit hash which is now easily parsed as well as there is only a single line of output.

These steps happen in the `getSubmodules` function and are the largest part of the change. This function does not throw any errors but will just skip broken submodules so that a template with a malformed .gitmodules file can still be used.

To re add the submodules i use `git update-index --add --cacheinfo 160000 0dff7e5493898954537202c0c975f7b1c55d0845 lib (no%_()delay)1` instead of the regular `git submodule add ...`. Updating the index directly skips cloning the submodule which is far faster and entirely avoids the problem of users adding excessively large submodules to possibly DoS attack the Gitea server. It also avoids the issue where a submodule repository might not be accessible by the Gitea server due to authentication/permissions or other reasons such as absolute local file paths being used.

### CODE REVIEW

File: modules/repository/generate.go [hunk 1]
```diff
@@ -182,6 +250,15 @@ func generateRepoCommit(repo, templateRepo, generateRepo *models.Repository, tmp
 		return fmt.Errorf("git remote add: %v", err)
 	}
 
+	// Reapply the submodules by updating the index
```
Comment (6543) [inline modules/repository/generate.go]: we may wana move this into the `modules/git` package ... and we should also utilize if exist open pipes to git comans

as @zeripath converted a lot of them to improve speed ...

File: modules/repository/generate.go [hunk 2]
```diff
@@ -97,6 +102,66 @@ func checkGiteaTemplate(tmpDir string) (*models.GiteaTemplate, error) {
 	return gt, nil
 }
 
+func getSubmodules(repoDir string) []submodule {
```
Comment (6543) [inline modules/repository/generate.go]: move this into the `modules/git` package

Comment (sschroe) [reply modules/repository/generate.go]: Moved it and added a basic unittest. The extra test repository clutters the PR up a good bit, is there a better way to add those?

**Comment by 6543** [comment]
@sschroe If you dont force-push and not swash, it's simpler to review and see made changes ...

... wills will be squash-merged if accepted anyways

File: modules/git/submodule.go [hunk 3]
```diff
@@ -122,3 +127,63 @@ func (sf *SubModuleFile) RefURL(urlPrefix, repoFullName, sshDomain string) strin
...
+			!strings.HasSuffix(line, ".url") {
+
+			continue
+		}
+
+		name := line[len("submodule.") : len(line)-len(".url")]
+		name = strings.TrimSpace(name)
+
+		if len(name) == 0 {
+			log("Submodule skipped because it has no name")
```
Comment (6543) [inline modules/git/submodule.go]: from "code.gitea.io/gitea/modules/log"

`log.Info(...)`

File: modules/git/submodule.go [hunk 4]
```diff
@@ -122,3 +127,63 @@ func (sf *SubModuleFile) RefURL(urlPrefix, repoFullName, sshDomain string) strin
...
+			continue
+		}
+
+		commit, err := NewCommand("submodule", "status", name).
+			RunInDir(repoPath)
+
+		// If no commit was found for the module skip it
+		if err != nil {
+			log("Submodule %s skipped because it has no commit", name)
```
Comment (6543) [inline modules/git/submodule.go]: log.Info

File: modules/git/submodule.go [hunk 5]
```diff
@@ -122,3 +127,63 @@ func (sf *SubModuleFile) RefURL(urlPrefix, repoFullName, sshDomain string) strin
...
+		}
+
+		if len(commit) > 0 {
+			commit = commit[1:]
+		}
+
+		fields := strings.Fields(commit)
+
+		if len(fields) == 0 {
+			log("Submodule %s skipped because it has no valid commit", name)
```
Comment (6543) [inline modules/git/submodule.go]: log.Info

File: modules/git/submodule.go [hunk 6]
```diff
@@ -122,3 +127,63 @@ func (sf *SubModuleFile) RefURL(urlPrefix, repoFullName, sshDomain string) strin
...
+			continue
+		}
+
+		commit = fields[0]
+
+		if len(commit) != 40 {
+			log("Submodule %s skipped due to malformed commit hash", name)
```
Comment (6543) [inline modules/git/submodule.go]: log.Info

File: modules/repository/generate.go (hunk 2 above)
Comment (6543) [reply modules/repository/generate.go]: no this is just fine :+1:

**Comment by 6543** [comment]
@sschroe avter #16243 got merged you dont need to rename import :)

File: modules/repository/generate.go (hunk 1 above)
Comment (sschroe) [reply modules/repository/generate.go]: By utilizing pipes do you mean using `RunInDirPipeline` instead of `RunInDir` for the command or is there more to it?

**Comment by sschroe** [comment]
@6543 all changes should be implemented so far. Just for the pipelines i need a little more info, is it enough to change the command to use `RunInDirPipeline` or is there more to that?

**Comment by 6543** [comment]
https://github.com/go-gitea/gitea/blob/main/modules/git/repo_ref_nogogit.go#L16 is a nice example

**Review by 6543 — APPROVED** [review]

File: modules/git/submodule.go [hunk 7]
```diff
@@ -120,3 +131,90 @@ func (sf *SubModuleFile) RefURL(urlPrefix, repoFullName, sshDomain string) strin
...
+func GetSubmoduleCommits(ctx context.Context, repoPath string) []SubModuleCommit {
+	stdoutReader, stdoutWriter := io.Pipe()
+	defer func() {
+		_ = stdoutReader.Close()
+		_ = stdoutWriter.Close()
+	}()
+
+	go func() {
+		stderrBuilder := &strings.Builder{}
+		err := NewCommand(ctx, "config", "-f", ".gitmodules", "--list", "--name-only").RunInDirPipeline(repoPath, stdoutWriter, stderrBuilder)
```
Comment (6543) [inline modules/git/submodule.go]: see #18693 to refactor this line :)

**Comment by sschroe** [comment]
Any other input or changes needed here to proceed?

**Review by 6543 — APPROVED** [review]

**Comment by CakePost** [comment]
I see this issue was closed but it still appears to be present on the latest gitea release. Is this being tracked somewhere else or was there some reason that this was closed that I'm missing?

**Comment by 6543** [comment]
@techknowlogick what was the reason for closing it?

**Comment by techknowlogick** [comment]
@6543 I don't recall. Please feel free to reopen

**Comment by 6543** [comment]
Ok will do so (and try to resolve conflichts ... next week :) )

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> Ok will do so ~(and try to resolve conflichts ... next week :) )~

Maybe we could get it in Jan 1 2025

**Review by lunny — APPROVED** [review]
