### PR TITLE
Prevent NPE in CSV diff rendering when column removed

### LINKED ISSUE #16837: 500 on CSV diff: runtime error: index out of range
- Gitea version (or commit ref): latest 1.15, https://github.com/go-gitea/gitea/commit/0c7927fe48b29769dd5da2d585ecde54dcbb4f4d
- Git version: 2.33.0
- Operating system: Ubuntu 20.04

When viewing a certain CSV diff, I see a 500 and this error in the log:

````
2021/08/27 13:14:14 ...s/context/context.go:195:HTML() [E] Render failed: template: repo/diff/csv_diff:3:15: executing "repo/diff/csv_diff" at <call .root.CreateCsvDiff .file .root.BaseCommit .root.HeadCommit>: error calling call: runtime error: index out of range [-1]
````

I can't share the particular CSV content but will try to fabricate a file that reproduces that error.

### PR DESCRIPTION
**Pull request by richmahn**
Fixes #16837 if a column is deleted.

We were clobbering the columns that were added by looping through the aline (base) and then when bline (head) was looped through, it clobbered what was in the "cells" array that is show in the diff, and then left a nil cell because nothing was shifted.

This fix properly shifts the cells, and properly puts the b cell either at its location or after, according to what the aline placed in the cells.

This includes test, adding a new test function since adding/removing cells works best with three columns, not two, which results in 4 columns of the resulting cells because it has a deleted column and an added column. If you try this locally, you can try those cases and others, such as adding a column.

There was no need to do anything special for the rows when `aline == 0 || bline == 0` so that was removed. This allows the same code to be used for removed or added lines, with the bcell text always being the RightCell, acell text being the LeftCell.

I still added the patch @zeripath gave at https://github.com/go-gitea/gitea/issues/16837#issuecomment-913007382 so that just in case for some reason a cell is nil (which shouldn't happen now) it doesn't throw a 500 error, so the user can at least view the raw diff.

Also fixes in the [view.go](https://github.com/go-gitea/gitea/pull/17018/files#diff-43a7f4747c7ba8bff888c9be11affaafd595fd55d27f3333840eb19df9fad393L521) file how if a CSV file is empty (either created empty or if you edit it and remove all contents) it throws a huge 500 error when you then save it (when you view the file). Since we allow creating, saving and pushing empty files, we shouldn't throw an error on an empty CSV file, but just show its empty contents. This doesn't happen if it is a Markdown file or other type of file that is empty.
EDIT: Now handled in the markup/csv renderer code

### CODE REVIEW

File: services/gitdiff/csv.go [hunk 1]
```diff
@@ -161,31 +161,6 @@ func createCsvDiff(diffFile *DiffFile, baseReader *csv.Reader, headReader *csv.R
 	createDiffRow := func(aline int, bline int) (*TableDiffRow, error) {
 		cells := make([]*TableDiffCell, columns)
 
-		if aline == 0 || bline == 0 {
```
Comment (richmahn) [inline services/gitdiff/csv.go:164]: As mentioned in the PR comment, this is not needed as the code below for all rows works

**Comment by richmahn** [comment]
I see integration isn't passing, and I also found this case causes and index out of bounds error. Will fix.

BASE:
```
col1,col2,col3
a,b,c
```

HEAD:
```
col3,col4,col5
c,d,e
```

**Comment by richmahn** [comment]
@silverwind @zeripath Ok, if you could play with this reworking of all things CSV Diff locally (try to break with all sorts of CSV diffs) and review, appreciate it!

File: routers/web/repo/view.go [hunk 2]
```diff
@@ -518,7 +518,7 @@ func renderFile(ctx *context.Context, entry *git.TreeEntry, treeLink, rawLink st
 				Metas:     ctx.Repo.Repository.ComposeDocumentMetas(),
 				GitRepo:   ctx.Repo.GitRepo,
 			}, rd, &result)
-			if err != nil {
+			if err != nil && err != io.EOF {
```
Comment (KN4CK3R) [inline routers/web/repo/view.go]: This may be wrong for other renderers. You could check in the csv renderer for `io.EOF` and treat it as no error.

Comment (richmahn) [reply routers/web/repo/view.go]: Yeah, I was thinking of looking at that a bit deeper, but if all it reads for any renderer is an EOF marker should we really throw a big 500 error rather than show an empty file that they can deal with?

Comment (zeripath) [reply routers/web/repo/view.go]: I don't think a renderer should be returning io.EOF at all.

Comment (richmahn) [reply routers/web/repo/view.go]: Ok, will just make sure the CSV renderer isn't doing that. I do think we should make sure all Renders don't do that, but will let that be a separate issue

Comment (richmahn) [reply routers/web/repo/view.go]: Ok, I have changed to just making sure the two places that the CSV Render reads the file to just return nil if it encounters only an EOF marker.

**Comment by richmahn** [comment]
DO NOT MERGE yet..... now I find that if the file is empty initially, viewing the commit returns a 500 again. Have to check that case.

**Comment by richmahn** [comment]
Ok, fixed initial commit with EOF 500 error.

File: modules/markup/csv/csv.go [hunk 3]
```diff
@@ -88,7 +88,7 @@ func (Renderer) Render(ctx *markup.RenderContext, input io.Reader, output io.Wri
 
 	// FIXME: don't read all to memory
 	rawBytes, err := ioutil.ReadAll(input)
-	if err != nil {
+	if err != nil && err != io.EOF {
```
Comment (zeripath) [inline modules/markup/csv/csv.go]: ioutil cannot return io.EOF

File: modules/markup/csv/csv.go [hunk 4]
```diff
@@ -104,7 +104,7 @@ func (Renderer) Render(ctx *markup.RenderContext, input io.Reader, output io.Wri
 	}
 
 	rd, err := csv.CreateReaderAndGuessDelimiter(bytes.NewReader(rawBytes))
-	if err != nil {
+	if err != nil && err != io.EOF {
```
Comment (zeripath) [inline modules/markup/csv/csv.go]: I would worry that in this case the rd would be nil and we'd get an NPE below.

File: modules/csv/csv.go [hunk 5]
```diff
@@ -30,7 +30,7 @@ func CreateReader(input io.Reader, delimiter rune) *stdcsv.Reader {
 func CreateReaderAndGuessDelimiter(rd io.Reader) (*stdcsv.Reader, error) {
 	var data = make([]byte, 1e4)
 	size, err := rd.Read(data)
-	if err != nil {
+	if err != nil && err != io.EOF {
```
Comment (zeripath) [inline modules/csv/csv.go]: So if we get an NPE we fall down to line 37 where we guess a delimiter on an empty []byte and create a reader on the empty input?

Comment (richmahn) [reply modules/csv/csv.go]: It actually goes through just fine, but I'll do some testing.

File: modules/markup/csv/csv.go (hunk 4 above)
Comment (richmahn) [reply modules/markup/csv/csv.go]: That's actually why I also have to not return err if the err is io.EOF and let it do the CreateReader. The data is an empty byte array so it just defaults to comma as the delimiter.

File: modules/csv/csv.go (hunk 5 above)
Comment (richmahn) [reply modules/csv/csv.go]: Yes, actually, that's what we want. I guess I could do that if the error is io.EOF but I noticed that the data is just an empty byte array and then it just returns comma as the delimiter. It still needs a Reader to show the file on the view page.

File: modules/markup/csv/csv.go (hunk 4 above)
Comment (richmahn) [reply modules/markup/csv/csv.go]: Ok, changed it...does that seem better?

File: modules/csv/csv.go (hunk 5 above)
Comment (richmahn) [reply modules/csv/csv.go]: See my changes to the Create & Guess function

File: services/gitdiff/csv.go [hunk 6]
```diff
@@ -199,25 +181,82 @@ func createCsvDiff(diffFile *DiffFile, baseReader *csv.Reader, headReader *csv.R
 		}
 
 		for i := 0; i < len(a2b); i++ {
-			acell, _ := getCell(arow, i)
-			if a2b[i] == unmappedColumn {
-				cells[i] = &TableDiffCell{LeftCell: acell, Type: TableDiffCellDel}
+			var aCell string
+			aIsUndefined := false
```
Comment (zeripath) [inline services/gitdiff/csv.go]: Probably better to set aIsUndefined := true and then only set it to false at line 193

File: services/gitdiff/csv.go [hunk 7]
```diff
@@ -199,25 +181,82 @@ func createCsvDiff(diffFile *DiffFile, baseReader *csv.Reader, headReader *csv.R
...
+			}
 
-				celltype := TableDiffCellChanged
-				if acell == bcell {
-					celltype = TableDiffCellEqual
+			if a2b[i] == unmappedColumn {
+				cells[i] = &TableDiffCell{LeftCell: aCell, Type: TableDiffCellDel}
+			} else {
+				var bCell string
+				bIsUndefined := false
```
Comment (zeripath) [inline services/gitdiff/csv.go]: Similarly flip this to true and set it false if you get something

File: services/gitdiff/csv.go [hunk 8]
```diff
@@ -199,25 +181,82 @@ func createCsvDiff(diffFile *DiffFile, baseReader *csv.Reader, headReader *csv.R
...
+				cells[i] = &TableDiffCell{LeftCell: aCell, RightCell: bCell, Type: cellType}
 			}
 		}
+		cellsIndex := 0
 		for i := 0; i < len(b2a); i++ {
 			if b2a[i] == unmappedColumn {
-				bcell, _ := getCell(brow, i)
-				cells[i] = &TableDiffCell{LeftCell: bcell, Type: TableDiffCellAdd}
+				var bCell string
+				bIsUndefined := false
```
Comment (zeripath) [inline services/gitdiff/csv.go]: Similarly flip this to true and set it false if you get something

File: services/gitdiff/csv.go [hunk 9]
```diff
@@ -199,25 +181,82 @@ func createCsvDiff(diffFile *DiffFile, baseReader *csv.Reader, headReader *csv.R
 		}
 
 		for i := 0; i < len(a2b); i++ {
```
Comment (zeripath) [inline services/gitdiff/csv.go]: This could do with some comments to explain what it's doing and why we're iterating over both sides.

File: modules/markup/csv/csv.go (hunk 4 above)
Comment (zeripath) [reply modules/markup/csv/csv.go]: yeah better!

File: services/gitdiff/csv.go (hunk 9 above)
Comment (richmahn) [reply services/gitdiff/csv.go]: Yeah, it does need some commenting....especially when I shift the cells array with copy(). Actually wish the first person to write this commented...I really had to think with this one.

Comment (zeripath) [reply services/gitdiff/csv.go]: yeah

**Comment by richmahn** [comment]
Just a note, still working on this, have made great progress in making sure it is done right. Even adding in it noting when a column has been moved so that is brought to the attention of the person reviewing the PR.

**Comment by richmahn** [comment]
Finally got a chance to work on this after dealing with COVID and lots of other work. Hope this gets looked at. Please feel free to ask question but hopefully the comments make sense. Takes a bit of work to nicely show a CSV diff. As already stated, now also shows moved columns but accounts for column additions and deletions (that is, if columns before a column were added or deleted, it doesn't flag the existing column as moved).

Example diff:

image

@zeripath @silverwind @KN4CK3R

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]
