### PR TITLE
Fix API not persisting pull request unit config when has_pull_requests is not set

### LINKED ISSUE #36466: "default_delete_branch_after_merge"cannot be updated via API
### Description

Updating a repository's `default_delete_branch_after_merge` property via the PATCH API endpoint does not persist the change, even though the API returns a 200 OK status.

**Reproduction Steps:**

1. Identify a repository (e.g., hnrx/test).
2. Send a PATCH request to /api/v1/repos/hnrx/test with the following payload:
   {  "default_delete_branch_after_merge": true }
3. The response is HTTP 200 OK and includes the full repository JSON object.
4. Observe that in the response JSON, "default_delete_branch_after_merge" is still false.
5. Check the Web UI settings for the repository; the option remains disabled.

**Additional Context:**

- Other properties (like name or description) can be successfully updated using the same PATCH call.
- The issue persists regardless of whether ALLOW_KEEP_PULL_REQUEST_HEAD_BRANCH is explicitly set in the app.ini or not.
- Testing via the built-in Swagger UI produces the same incorrect behavior.
- **Manual update via Web UI works:** Setting the "Delete branch after merge" option manually in the repository settings via the web interface works perfectly and persists as expected. The issue is strictly limited to the API PATCH method.

**Expected behavior:** The property should be updated to true in the database and reflected in the API response and Web UI.

### Gitea Version

1.25.4

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

official docker container

### Database

SQLite

### PR DESCRIPTION
**Pull request by silverwind**
The `PATCH /api/v1/repos/{owner}/{repo}` endpoint silently ignores pull
request config fields (like `default_delete_branch_after_merge`,
`allow_squash_merge`, etc.) unless `has_pull_requests: true` is also
included in the request body. This is because the entire PR unit config
block was gated behind `if opts.HasPullRequests != nil`.

This PR restructures the logic so that PR config options are applied
whenever the pull request unit already exists on the repo, without
requiring `has_pull_requests` to be explicitly set. A new unit is only
created when `has_pull_requests: true` is explicitly sent.

Fixes https://github.com/go-gitea/gitea/issues/36466

### CODE REVIEW

File: routers/api/v1/repo/repo.go [hunk 1]
```diff
@@ -884,77 +884,51 @@ func updateRepoUnits(ctx *context.APIContext, opts api.EditRepoOption) error {
...
-			if opts.DefaultMergeStyle != nil {
-				config.DefaultMergeStyle = repo_model.MergeStyle(*opts.DefaultMergeStyle)
-			}
-			if opts.DefaultAllowMaintainerEdit != nil {
-				config.DefaultAllowMaintainerEdit = *opts.DefaultAllowMaintainerEdit
+				units = append(units, repo_model.RepoUnit{
+					RepoID: repo.ID,
+					Type:   unit_model.TypePullRequests,
+					Config: config,
+				})
```
[the remark this answers is not in the document]
Comment (silverwind) [reply routers/api/v1/repo/repo.go:923]: *Written by @silverwind using Claude Code.*

Good catch. Added `EditRepoOption.HasPullRequestOptions()` method and the block now only triggers when `HasPullRequests` is explicitly set or at least one PR config field is non-nil.

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
AI only knows copying-pasting code.

It will cause inconsistency and even bugs in the future.

https://github.com/go-gitea/gitea/blob/427954ba6ed3a553f75eb1d01fb2f4597e3eda1c/services/repository/create.go#L385-L394

**Comment by wxiaoguang** [comment]
And you always blindly use AI, you know nothing about the code base and don't know what is the right thing to do. For example: Change default "allow edits from maintainers" to true #36709 , it is also related.

If you ever have some basic sense, you should know that the "default unit settings" should be handled in the same way.

File: modules/structs/repo.go [hunk 2]
```diff
@@ -230,6 +230,14 @@ type EditRepoOption struct {
 	EnablePrune *bool `json:"enable_prune,omitempty"`
 }
 
+// HasPullRequestOptions returns true if any pull request unit config options are set.
+func (o EditRepoOption) HasPullRequestOptions() bool {
+	return o.IgnoreWhitespaceConflicts != nil || o.AllowMerge != nil || o.AllowRebase != nil ||
+		o.AllowRebaseMerge != nil || o.AllowSquash != nil || o.AllowFastForwardOnly != nil ||
+		o.AllowManualMerge != nil || o.AutodetectManualMerge != nil || o.AllowRebaseUpdate != nil ||
+		o.DefaultDeleteBranchAfterMerge != nil || o.DefaultMergeStyle != nil || o.DefaultAllowMaintainerEdit != nil
+}
```
Comment (wxiaoguang) [inline modules/structs/repo.go]: There can be different approach to make it better. AI chose the most fragile approach.

Comment (silverwind) [reply modules/structs/repo.go]: I tried a few options to avoid this but the other option resulted in even more complex code.

**Comment by silverwind** [comment]
The code might be bad but it's proven to work so it can't be completely wrong. I think the reason why AI can't produce good code is that the code base ist just too convoluted. In other code bases I have AI produce beautiful code.

**Comment by wxiaoguang** [comment]
Because the rubberstamp approvals only make the code base more and more messy.

Although I do refactoring works, it never catches the new messy code growing faster and faster.

Actually I should leave the messy code to other maintainers, and save my time to play games.

**Comment by wxiaoguang** [comment]
By the way, `DefaultAllowMaintainerEdit=true` by default is there.


CI failure is caused by the changed default value:

<details>

image

</details>

Fixed.

**Review by wxiaoguang — APPROVED** [review]

**Comment by silverwind** [comment]
So I understand that new repos will now have `DefaultAllowMaintainerEdit=true` while existing ones remain at their stored setting? I can live with that personally.

**Comment by lunny** [comment]
> So I understand that new repos will now have `DefaultAllowMaintainerEdit=true` while existing ones remain at their stored setting? I can live with that personally.

Yes. The pull request content needs to be updated.

**Comment by silverwind** [comment]
> > So I understand that new repos will now have `DefaultAllowMaintainerEdit=true` while existing ones remain at their stored setting? I can live with that personally.
> 
> Yes. The pull request content needs to be updated.

Pull request? I thought it's a per-repo setting, set only during repo creation or when manually updated in the repo settings.

**Comment by lunny** [comment]
> > > So I understand that new repos will now have `DefaultAllowMaintainerEdit=true` while existing ones remain at their stored setting? I can live with that personally.
> > 
> > 
> > Yes. The pull request content needs to be updated.
> 
> Pull request? I thought it's a per-repo setting, set only during repo creation or when manually updated in the repo settings.

I mean since more codes changed since you first post this pull request, the content of this pull request should be updated before merging.

**Comment by silverwind** [comment]
Ah, you meant the description. Yeah I will do that via AI to summarize this PR's content.

**Comment by silverwind** [comment]
description updated, merging.
