### PR TITLE
Prevent NPE on invalid diff

### LINKED ISSUE #17193: Nil Pointer 500 in compare view
### Gitea Info
version: main (3bbdce2)
git: v33.0
os: linux

# Gist
```
PANIC: runtime error: invalid memory address or nil pointer dereference
/usr/lib/go/src/runtime/panic.go:221 (0x44da46)
	panicmem: panic(memoryError)
/usr/lib/go/src/runtime/signal_unix.go:735 (0x44da16)
	sigpanic: panicmem()
/home/maddl/git/own/gitea/routers/web/repo/compare.go:638 (0x1ba4378)
	CompareDiff.func1: if ci.HeadGitRepo != nil {
/home/maddl/git/own/gitea/routers/web/repo/compare.go:643 (0x1ba42cc)
	CompareDiff: return
/home/maddl/git/own/gitea/modules/web/route.go:74 (0x1b53cc4)
	Wrap.func1: t(ctx)
/usr/lib/go/src/net/http/server.go:2046 (0x76190e)
	HandlerFunc.ServeHTTP: f(w, r)
/home/maddl/git/own/gitea/vendor/github.com/go-chi/chi/mux.go:436 (0x138cb58)
	(*Mux).routeHTTP: h.ServeHTTP(w, r)
/usr/lib/go/src/net/http/server.go:2046 (0x76190e)
	HandlerFunc.ServeHTTP: f(w, r)
/home/maddl/git/own/gitea/modules/web/route.go:113 (0x1b544a5)
	Middle.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
/usr/lib/go/src/net/http/server.go:2046 (0x76190e)
	HandlerFunc.ServeHTTP: f(w, r)
/home/maddl/git/own/gitea/modules/web/route.go:113 (0x1b544a5)
	Middle.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
/usr/lib/go/src/net/http/server.go:2046 (0x76190e)
	HandlerFunc.ServeHTTP: f(w, r)
/home/maddl/git/own/gitea/modules/web/route.go:113 (0x1b544a5)
	Middle.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
/usr/lib/go/src/net/http/server.go:2046 (0x76190e)
	HandlerFunc.ServeHTTP: f(w, r)
/home/maddl/git/own/gitea/vendor/github.com/go-chi/chi/middleware/get_head.go:37 (0x1b71304)
	GetHead.func1: next.ServeHTTP(w, r)
/usr/lib/go/src/net/http/server.go:2046 (0x76190e)
	HandlerFunc.ServeHTTP: f(w, r)
/home/maddl/git/own/gitea/modules/web/route.go:113 (0x1b544a5)
	Middle.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
/usr/lib/go/src/net/http/server.go:2046 (0x76190e)
	HandlerFunc.ServeHTTP: f(w, r)
/home/maddl/git/own/gitea/modules/context/context.go:747 (0x139dedb)
	Contexter.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
/usr/lib/go/src/net/http/server.go:2046 (0x76190e)
	HandlerFunc.ServeHTTP: f(w, r)
/home/maddl/git/own/gitea/vendor/github.com/go-chi/chi/mux.go:70 (0x138a9ad)
	(*Mux).ServeHTTP: mx.handler.ServeHTTP(w, r)
/home/maddl/git/own/gitea/vendor/github.com/go-chi/chi/mux.go:311 (0x138c35b)
```

### Description

should return 404

### PR DESCRIPTION
**Pull request by zeripath**
If ParseCompareInfo returns a nil compare info the defer function needs to ensure
that it does not attempt to close the HeadGitRepo.

Fix #17193
Regression #16635 

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

File: integrations/compare_test.go [hunk 1]
```diff
@@ -21,4 +22,8 @@ func TestCompareTag(t *testing.T) {
 	selection := htmlDoc.doc.Find(".choose.branch .filter.dropdown")
 	// A dropdown for both base and head.
 	assert.Lenf(t, selection.Nodes, 2, "The template has changed")
+
+	req = NewRequest(t, "GET", "/user2/repo1/compare/invalid")
+	resp = session.MakeRequest(t, req, http.StatusOK)
```
Comment (6543) [inline integrations/compare_test.go]:
```suggestion
	resp = session.MakeRequest(t, req, http.StatusNotFound)
```

**Review by 6543 — APPROVED** [review]

**Review by 6543 — APPROVED** [review]
lgtm bot?

**Review by KN4CK3R — APPROVED** [review]

**Comment by KN4CK3R** [comment]
lgtm likes me 🙂
