### PR TITLE
Fix #31185 try fix lfs download from bitbucket failed

### LINKED ISSUE #31185: git lfs mirror download request maybe shouldn't carry `Accept`
### Description

My situation is as follows: I use Gitea to mirror a repository on Bitbucket. Then, I found that the content stored using LFS (Large File Storage) was not correctly synchronized. So, I opened the trace logs to check. The batch operation was normal, but when it came to the download operation, the first server directly returned a 500 error, and no response body was returned. Therefore, I tried to understand what was happening from the source code and found that the request header for the download operation would additionally include an Accept field. When I removed it, the download worked properly...

Followed by the official [doc](https://github.com/git-lfs/git-lfs/blob/main/docs/api/basic-transfers.md), it seems there is no need to download with `Accept` header, maybe we can remove it from download?

I don't have the permission to the bitbucket server, so I don't know what happend in the bitbucket background.

### Gitea Version

v1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

linux

### How are you running Gitea?

run from docker

### Database

None

### PR DESCRIPTION
**Pull request by Zoupers**
Fix #31185

### CODE REVIEW

**Comment by Zoupers** [comment]
Maybe I should try if combined `Accept` header like `application/vnd.git-lfs+json;q=0.9, */*;q=0.8` could solve it, since the later one should be more universal.

File: modules/lfs/transferadapter.go [hunk 1]
```diff
@@ -37,6 +37,8 @@ func (a *BasicTransferAdapter) Download(ctx context.Context, l *Link) (io.ReadCl
 	if err != nil {
 		return nil, err
 	}
+	req.Header.Del("Accept")
```
Comment (silverwind) [inline modules/lfs/transferadapter.go]: Instead of deleting, can you find the place where the header is originally set and investigate why it sets it in first place?

Comment (Zoupers) [reply modules/lfs/transferadapter.go]: Cool, I will try to understand more about the purpose behind it.

**Comment by Zoupers** [comment]
I have try the new `Accept` header, it works.

File: modules/lfs/shared.go [hunk 2]
```diff
@@ -10,6 +10,8 @@ import (
 const (
 	// MediaType contains the media type for LFS server requests
 	MediaType = "application/vnd.git-lfs+json"
+	// Some LFS server might offer content with other types, so open with */*
```
Comment (delvh) [inline modules/lfs/shared.go]:
```suggestion
	// Some LFS servers offer content with other types, so fallback to '*/*' if application/vnd.git-lfs+json cannot be served
```

File: modules/lfs/transferadapter_test.go [hunk 3]
```diff
@@ -24,9 +24,12 @@ func TestBasicTransferAdapterName(t *testing.T) {
 
 func TestBasicTransferAdapter(t *testing.T) {
 	p := Pointer{Oid: "b5a2c96250612366ea272ffac6d9744aaf4b45aacd96aa7cfcb931ee3b558259", Size: 5}
+	downloadTestFlag := false
```
Comment (delvh) [inline modules/lfs/transferadapter_test.go]: `download := false`

Comment (Zoupers) [reply modules/lfs/transferadapter_test.go]: ok

Comment (Zoupers) [reply modules/lfs/transferadapter_test.go]: wait, I forgot that it should check since the accept header is still add now

**Review by delvh — APPROVED** [review]

**Review by silverwind — APPROVED** [review]
