### PR TITLE
Graceful Queues:  Issue Indexing and Tasks

### LINKED ISSUE #9004: Can't use Redis through UNIX socket for the task scheduler
- Gitea version (or commit ref): v1.10.0
- Git version: v2.20.1
- Operating system: Debian Buster
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

## Description

Hey back the team, second issue of the evening.
It looks like we cannot make the `task` scheduler use Redis over an UNIX socket, as for the `cache` storage or the `session` provider.

```config
[task]
QUEUE_TYPE     = redis
QUEUE_CONN_STR = network=unix addrs=/var/run/redis/redis-server.sock password=$PASSWORD db=$N pool_size=$X idle_timeout=$T
```

The service hard-fails at startup with :

`routers/init.go:107:GlobalInit() [F] Failed to initialize task scheduler: dial tcp [::1]:6379: connect: connection refused`

So this issue got multiple purposes :

1. Should we be able to achieve this ?
2. Why connection strings are not parsed _consistently_ across different configuration entries ?
    * `addr` becomes `addrs`
    * Token separator is sometimes `,` and some other times ` `
    * Some options as `network`, `pool_size` or `idle_timeout` are _de facto_ not interpreted (still according to the [parser sources of the `task` scheduler](https://github.com/go-gitea/gitea/blob/f2a3abc683ad4b2177b7c7c6160a2c0b4316120a/modules/task/queue_redis.go#L37))
3. **kind/proposal** : `cache`, `session`, `task` and issue `indexer` connection strings **should** be configured the same way.

Bye again 👋

### PR DESCRIPTION
**Pull request by zeripath**
This PR is a breakout from #8874. 

* modules/queue introduces a generic queue infrastructure with pooled workers, a monitoring page and a generic setting format (This fixes #9004)
* As a first stage proof of concept we migrate the issues indexer to this format - keeping previous 
config working but allowing it to be overrided and added to in the new queue settings format
* As a more standard example Tasks are migrated to the new queue format.

### CODE REVIEW

**Comment by lunny** [comment]
I would like to move this to 1.12 since 1.11 has freezed when you send the PR.

File: modules/queue/queue_test.go [hunk 1]
```diff
@@ -0,0 +1,42 @@
+// Copyright 2019 The Gitea Authors. All rights reserved.
+// Use of this source code is governed by a MIT-style
+// license that can be found in the LICENSE file.
+
+package queue
+
```
Comment (6543) [inline modules/queue/queue_test.go:6]: import format ?

**Review by 6543 — COMMENTED** [review]
.

**Review by 6543 — CHANGES_REQUESTED** [review]
smal format nit

File: modules/queue/queue_test.go (hunk 1 above)
Comment (zeripath) [reply modules/queue/queue_test.go:6]: done

**Comment by zeripath** [comment]
@6543 I can't see what the "." and "small format nit" are referring to.

**Comment by zeripath** [comment]
@lunny I think we do need to put this one in - it's the final step of gracefulising most of the components. It's been part of graceful-2 for months now.

**Review by 6543 — APPROVED** [review]

File: integrations/issue_test.go [hunk 2]
```diff
@@ -87,7 +89,12 @@ func TestViewIssuesKeyword(t *testing.T) {
 	defer prepareTestEnv(t)()
 
 	repo := models.AssertExistsAndLoadBean(t, &models.Repository{ID: 1}).(*models.Repository)
-
+	issue := models.AssertExistsAndLoadBean(t, &models.Issue{
+		RepoID: repo.ID,
+		Index:  1,
+	}).(*models.Issue)
+	issues.UpdateIssueIndexer(issue)
+	time.Sleep(time.Second * 1)
```
Comment (guillep2k) [inline integrations/issue_test.go:97]: Mmm.... isn't this value too arbritrary? If it's intended to give the indexer some time to process the request, the value might be insufficient when the load is too heavy on the system. Perhaps we'll need some kind of flush mechanism in the future.

File: modules/indexer/issues/indexer.go [hunk 3]
```diff
@@ -75,98 +79,97 @@ func (h *indexerHolder) get() Indexer {
...
+		go graceful.GetManager().RunWithShutdownFns(issueIndexerQueue.Run)
 
+		// Populate the index
 		if populate {
 			if syncReindex {
-				populateIssueIndexer()
+				graceful.GetManager().RunWithShutdownContext(populateIssueIndexer)
 			} else {
-				go populateIssueIndexer()
+				go graceful.GetManager().RunWithShutdownContext(populateIssueIndexer)
```
Comment (guillep2k) [inline modules/indexer/issues/indexer.go:181]: Perhaps with these new queues + graceful we don't need the blocking option anymore?

File: integrations/issue_test.go (hunk 2 above)
Comment (zeripath) [reply integrations/issue_test.go:97]: So this is only a test but you're right.

Yeah we definitely need a flush for tests - or some other way of indicating that the job is done. That could be with a handler that writes to a test channel etc.

File: modules/indexer/issues/indexer.go (hunk 3 above)
Comment (zeripath) [reply modules/indexer/issues/indexer.go:181]: I'll have a look

File: integrations/issue_test.go (hunk 2 above)
Comment (zeripath) [reply integrations/issue_test.go:97]: However they interface doesn't really give us that option so hence the wait. 

The indexer in this case has just been started and so a second is not too unreasonable.

File: modules/queue/manager.go [hunk 4]
```diff
@@ -0,0 +1,216 @@
...
+// PoolWorkersList implements the sort.Interface
+type PoolWorkersList []*PoolWorkers
+
+func init() {
+	_ = GetManager()
+}
+
+// GetManager returns a Manager and initializes one as singleton if there's none yet
+func GetManager() *Manager {
+	if manager == nil {
```
Comment (guillep2k) [inline modules/queue/manager.go:77]: `once.Do()`? Otherwise a race condition might occur.

File: modules/queue/manager.go [hunk 5]
```diff
@@ -0,0 +1,216 @@
...
+	sort.Sort(DescriptionList(descs))
+	return descs
+}
+
+// Workers returns the poolworkers
+func (q *Description) Workers() []*PoolWorkers {
+	q.mutex.Lock()
+	workers := make([]*PoolWorkers, 0, len(q.PoolWorkers))
+	for _, worker := range q.PoolWorkers {
+		workers = append(workers, worker)
```
Comment (guillep2k) [inline modules/queue/manager.go:147]: Doesn't golang have something like...?:
```suggestion
		workers = append(workers, ...q.PoolWorkers)
```

File: modules/queue/manager.go [hunk 6]
```diff
@@ -0,0 +1,216 @@
...
+
+// Descriptions returns the queue descriptions
+func (m *Manager) Descriptions() []*Description {
+	m.mutex.Lock()
+	descs := make([]*Description, 0, len(m.Queues))
+	for _, desc := range m.Queues {
+		descs = append(descs, desc)
+	}
+	m.mutex.Unlock()
+	sort.Sort(DescriptionList(descs))
```
Comment (guillep2k) [inline modules/queue/manager.go]: Is sort always required?

File: modules/queue/queue.go [hunk 7]
```diff
@@ -0,0 +1,133 @@
...
+		i++
+	}
+	return types
+}
+
+// RegisteredTypesAsString provides the list of requested types of queues
+func RegisteredTypesAsString() []string {
+	types := make([]string, len(queuesMap))
+	i := 0
+	for key := range queuesMap {
```
Comment (guillep2k) [inline modules/queue/queue.go:119]:
```suggestion
	for i, key := range queuesMap {
```
I think you can do this and skip `i := 0` and `i++`.

File: modules/queue/manager.go (hunk 4 above)
Comment (zeripath) [reply modules/queue/manager.go:77]: It's created at init so there's no race.

File: modules/queue/manager.go (hunk 6 above)
Comment (zeripath) [reply modules/queue/manager.go]: The results of iterating through a map are random

File: modules/queue/manager.go (hunk 5 above)
Comment (zeripath) [reply modules/queue/manager.go:147]: `q.PoolWorkers` is a map - they don't have that.

File: modules/queue/queue.go (hunk 7 above)
Comment (zeripath) [reply modules/queue/queue.go:119]: It's a map, `i` would then refer to the keys of the map not the ordinal position and `key` would then be the value of the map.

File: modules/indexer/issues/indexer.go (hunk 3 above)
Comment (zeripath) [reply modules/indexer/issues/indexer.go:181]: The sync option is required for tests.

File: integrations/issue_test.go (hunk 2 above)
Comment (zeripath) [reply integrations/issue_test.go:97]: If we want this to work properly we need to add a blevetest option - whereby you can add watchers to the various methods of the indexer with registerable callbacks à la https://github.com/go-gitea/gitea/blob/c6e1111934aa6350dff04882ca4fe02bba2d61d0/integrations/notification_helper_test.go

I think there is a problem with the way gitea is structured in general - it's not really possible to mock up things properly. It's the reason why our integration tests are fundamentally racy even if we manage to bodge a pass on the race test.

**Comment by 6543** [comment]
resolfe confilct

**Comment by zeripath** [comment]
Thanks lunny.

**Comment by 6543** [comment]
@zeripath I think your rebase messed up :( + conflicting files

**Comment by zeripath** [comment]
No idea how I did that! Two seconds... I think I'll have to force push.

File: modules/queue/manager.go [hunk 8]
```diff
@@ -0,0 +1,266 @@
...
+	if !ok {
+		return
+	}
+	pw.Cancel()
+}
+
+// RemoveWorkers deletes pooled workers with pid
+func (q *Description) RemoveWorkers(pid int64) {
+	q.mutex.Lock()
+	delete(q.PoolWorkers, pid)
```
Comment (guillep2k) [inline modules/queue/manager.go:185]: Perhaps this should enforce cancellation just in case?

File: modules/queue/manager.go [hunk 9]
```diff
@@ -0,0 +1,266 @@
...
+// MaxNumberOfWorkers returns the maximum number of workers for the pool
+func (q *Description) MaxNumberOfWorkers() int {
+	if q.Pool != nil {
+		return q.Pool.MaxNumberOfWorkers()
+	}
+	return 0
+}
+
+// BoostWorkers returns the number of workers for a boost
+func (q *Description) BoostWorkers() int {
```
Comment (guillep2k) [inline modules/queue/manager.go]: Why are workers added in batches that need to be removed in block? Seems like a linked list should work better and be more granular; unless of course workers are needed in blocks specifically.

File: modules/queue/queue_channel.go [hunk 10]
```diff
@@ -0,0 +1,106 @@
...
+	})
+	atTerminate(context.Background(), func() {
+		log.Warn("ChannelQueue: %s is not terminatable!", c.name)
+	})
+	go func() {
+		_ = c.pool.AddWorkers(c.workers, 0)
+	}()
+}
+
+// Push will push the indexer data to queue
```
Comment (guillep2k) [inline modules/queue/queue_channel.go]:
```suggestion
// Push will push data into the queue
```

File: modules/queue/queue_disk.go [hunk 11]
```diff
@@ -0,0 +1,207 @@
...
+	pool       *WorkerPool
+	queue      *levelqueue.Queue
+	closed     chan struct{}
+	terminated chan struct{}
+	exemplar   interface{}
+	workers    int
+	name       string
+}
+
+// NewLevelQueue creates a ledis local queue
```
Comment (guillep2k) [inline modules/queue/queue_disk.go:48]:
```suggestion
// NewLevelQueue creates a disk library queue
```

File: modules/queue/queue_disk.go [hunk 12]
```diff
@@ -0,0 +1,207 @@
...
+			}
+			if err != nil {
+				log.Error("LevelQueue: %s Failed to unmarshal with error: %v", l.name, err)
+				time.Sleep(time.Millisecond * 100)
+				continue
+			}
+
+			log.Trace("LevelQueue %s: Task found: %#v", l.name, data)
+			l.pool.Push(data)
+			time.Sleep(time.Millisecond * 10)
```
Comment (guillep2k) [inline modules/queue/queue_disk.go]: This caps the pool performance innecessarily, IMHO. A sleep is performed when there's no more data to process, which is OK, but the worker should process as fast as possible when there is (unless there's risk of contention?).

File: modules/queue/queue_disk.go [hunk 13]
```diff
@@ -0,0 +1,207 @@
...
+
+// Terminate this queue and close the queue
+func (l *LevelQueue) Terminate() {
+	log.Trace("LevelQueue: %s Terminating", l.name)
+	l.Shutdown()
+	select {
+	case <-l.terminated:
+	default:
+		close(l.terminated)
+		if err := l.queue.Close(); err != nil && err.Error() != "leveldb: closed" {
```
Comment (guillep2k) [inline modules/queue/queue_disk.go:199]: Problem here is we will not know if the error description changes in a future library update.

File: modules/queue/queue_disk_channel.go [hunk 14]
```diff
@@ -0,0 +1,186 @@
...
+		BlockTimeout: config.BlockTimeout,
+		BoostTimeout: config.BoostTimeout,
+		BoostWorkers: config.BoostWorkers,
+		Name:         config.Name + "-channel",
+	}, exemplar)
+	if err != nil {
+		return nil, err
+	}
+
+	// the level backend only needs temporary workrers to catch up with the previously dropped work
```
Comment (guillep2k) [inline modules/queue/queue_disk_channel.go]:
```suggestion
	// the level backend only needs temporary workers to catch up with the previously dropped work
```

**Review by guillep2k — COMMENTED** [review]
Still a lot of files to go, sorry for taking so long.

File: modules/setting/queue.go [hunk 15]
```diff
@@ -0,0 +1,214 @@
...
+import (
+	"encoding/json"
+	"fmt"
+	"path"
+	"strconv"
+	"strings"
+	"time"
+
+	"code.gitea.io/gitea/modules/log"
+	"code.gitea.io/gitea/modules/queue"
```
Comment (lunny) [inline modules/setting/queue.go]: I don't think package setting should depend on module queue.

**Review by lunny — CHANGES_REQUESTED** [review]

File: modules/indexer/issues/indexer.go [hunk 16]
```diff
@@ -68,107 +81,115 @@ func (h *indexerHolder) set(indexer Indexer) {
...
 func InitIssueIndexer(syncReindex bool) {
 	waitChannel := make(chan time.Duration)
+
+	// Create the Queue
+	switch setting.Indexer.IssueType {
+	case "bleve":
+		handler := func(data ...queue.Data) {
+			indexer := holder.get()
+			if indexer == nil {
+				log.Error("Unable to get indexer!")
```
[the remark this answers is not in the document]
Comment (zeripath) [reply modules/indexer/issues/indexer.go]: We get the filename and line number in our logs but ok

File: modules/queue/manager.go (hunk 9 above)
Comment (zeripath) [reply modules/queue/manager.go]: You would need a context and channel for every worker which is quite inefficient

File: modules/queue/queue_disk.go (hunk 11 above)
Comment (zeripath) [reply modules/queue/queue_disk.go:48]: So in this case I think the underlying implementation detail is important - the fact that this is a ledis queue shows that it's not clusterable and can't be read by more than one process at a time. If we move to a different disk implementation we can change it

File: modules/queue/queue_disk.go (hunk 12 above)
Comment (zeripath) [reply modules/queue/queue_disk.go]: It's copied from the original - (in fact I reduced the time.) Happy to remove the wait if preferred though.

Comment (zeripath) [reply modules/queue/queue_disk.go]:
```suggestion
```

File: modules/queue/queue_disk.go (hunk 13 above)
Comment (zeripath) [reply modules/queue/queue_disk.go:199]: Don't really have a choice - it's either that or pass it up and log it unnecessarily
 
We'll just have to be aware of it.

File: modules/setting/queue.go (hunk 15 above)
Comment (zeripath) [reply modules/setting/queue.go]: Ok, it's a shame because queue is otherwise quite well contained depending only on log and could be broken out. I guess so long as the dependency on setting is well contained it could gain it. 

The other option is to stick the setting dependency in service but that means models can't create queues - which I think would be limiting at present.

File: modules/indexer/issues/indexer.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (guillep2k) [reply modules/indexer/issues/indexer.go]: For us Gitea maintainers it's only-half useful (as line numbers are tied to specific versions). For people not familiar with Gitea's code or golang, the function name can help a bit more, IMHO.

File: modules/queue/queue_disk.go (hunk 11 above)
Comment (guillep2k) [reply modules/queue/queue_disk.go:48]: _"ledis queue"_? OMG, I thought it was a typo! 🤣

File: modules/queue/queue_redis.go [hunk 17]
```diff
@@ -0,0 +1,222 @@
...
+			maxNumberOfWorkers: config.MaxWorkers,
+		},
+		queueName: config.QueueName,
+		exemplar:  exemplar,
+		closed:    make(chan struct{}),
+		workers:   config.Workers,
+		name:      config.Name,
+	}
+	if len(dbs) == 0 {
+		return nil, errors.New("no redis host found")
```
Comment (guillep2k) [inline modules/queue/queue_redis.go]:
```suggestion
		return nil, errors.New("no redis host specified")
```
"not found" sounds to me like the host could not be contacted.

File: modules/queue/queue_redis.go [hunk 18]
```diff
@@ -0,0 +1,222 @@
...
+			Addr:     strings.TrimSpace(dbs[0]), // use default Addr
+			Password: config.Password,           // no password set
+			DB:       config.DBIndex,            // use default DB
+		})
+	} else {
+		queue.client = redis.NewClusterClient(&redis.ClusterOptions{
+			Addrs: dbs,
+		})
+	}
+	if err := queue.client.Ping().Err(); err != nil {
```
Comment (guillep2k) [inline modules/queue/queue_redis.go:107]: Is it OK to fail if any host of the cluster fails? Or for clusters Ping() is successful as long as any host is alive?

File: modules/queue/queue_redis.go [hunk 19]
```diff
@@ -0,0 +1,222 @@
...
+
+func (r *RedisQueue) readToChan() {
+	for {
+		select {
+		case <-r.closed:
+			// tell the pool to shutdown
+			r.pool.cancel()
+			return
+		default:
+			bs, err := r.client.LPop(r.queueName).Bytes()
```
Comment (guillep2k) [inline modules/queue/queue_redis.go:146]: Won't this lock until `LPop` returns? It seems to me that the lock should be handled at the same level as `<-r.closed`; otherwise `<-r.closed` won't be checked until after anything is read from the client.

File: modules/queue/queue_redis.go [hunk 20]
```diff
@@ -0,0 +1,222 @@
...
+			}
+			if err != nil {
+				log.Error("RedisQueue: %s Error on Unmarshal: %v", r.name, err)
+				time.Sleep(time.Millisecond * 100)
+				continue
+			}
+
+			log.Trace("RedisQueue: %s Task found: %#v", r.name, data)
+			r.pool.Push(data)
+			time.Sleep(time.Millisecond * 10)
```
Comment (guillep2k) [inline modules/queue/queue_redis.go]:
```suggestion
```

File: modules/queue/queue_redis.go [hunk 21]
```diff
@@ -0,0 +1,222 @@
...
+	return r.client.RPush(r.queueName, bs).Err()
+}
+
+// Shutdown processing from this queue
+func (r *RedisQueue) Shutdown() {
+	log.Trace("Shutdown: %s", r.name)
+	select {
+	case <-r.closed:
+	default:
+		close(r.closed)
```
Comment (guillep2k) [inline modules/queue/queue_redis.go:205]: Is it possible that two goroutines will attempt to call `Shutdown()` at the same time? If that's the case, there's a slight chance that `close()` can be called twice if both threads pass `<-r.closed` at the same time.

File: modules/queue/manager.go [hunk 22]
```diff
@@ -0,0 +1,266 @@
...
+// Manager is a queue manager
+type Manager struct {
+	mutex sync.Mutex
+
+	counter int64
+	Queues  map[int64]*Description
+}
+
+// Description represents a working queue inheriting from Gitea.
+type Description struct {
```
[the remark this answers is not in the document]
Comment (zeripath) [reply modules/queue/manager.go]: Done

File: modules/setting/queue.go (hunk 15 above)
Comment (guillep2k) [reply modules/setting/queue.go]: Are the dependencies needed because of the config data types? Perhaps there could be a `queue_config` package that holds only the structs (like the `structs` package). I think `settings` could safely depend on that package as it will not chain any additional weird dependencies.

File: modules/queue/manager.go (hunk 8 above)
Comment (zeripath) [reply modules/queue/manager.go:185]: done

File: modules/queue/queue_wrapped.go [hunk 23]
```diff
@@ -0,0 +1,196 @@
...
+	}
+
+	q.internal.Run(atShutdown, atTerminate)
+	log.Trace("WrappedQueue: %s Done", q.name)
+}
+
+// Shutdown this queue and stop processing
+func (q *WrappedQueue) Shutdown() {
+	log.Trace("WrappedQueue: %s Shutdown", q.name)
+	q.lock.Lock()
```
Comment (guillep2k) [inline modules/queue/queue_wrapped.go:181]: `Shutdown` can't execute while `setInternal` has a hold on the lock.

File: modules/queue/queue_wrapped.go [hunk 24]
```diff
@@ -0,0 +1,196 @@
...
+	}
+	if shutdownable, ok := q.internal.(Shutdownable); ok {
+		shutdownable.Shutdown()
+	}
+}
+
+// Terminate this queue and close the queue
+func (q *WrappedQueue) Terminate() {
+	log.Trace("WrappedQueue: %s Terminating", q.name)
+	q.lock.Lock()
```
Comment (guillep2k) [inline modules/queue/queue_wrapped.go:194]: Same problem as with `Shutdown`

File: modules/queue/workerpool.go [hunk 25]
```diff
@@ -0,0 +1,322 @@
...
+	if p.blockTimeout > 0 && p.boostTimeout > 0 && (p.numberOfWorkers <= p.maxNumberOfWorkers || p.maxNumberOfWorkers < 0) {
+		p.lock.Unlock()
+		p.pushBoost(data)
+	} else {
+		p.lock.Unlock()
+		p.dataChan <- data
+	}
+}
+
+func (p *WorkerPool) pushBoost(data Data) {
```
Comment (guillep2k) [inline modules/queue/workerpool.go:44]: As a side note, I'd say that running many things in parallel is usually for the worse unless the underlying system in inherently parallelizable. To give a crude example, adding parallel db indexers in a SQLite database will consume more memory and increase shutdown delays rather than insert at a faster rate.

File: modules/queue/workerpool.go [hunk 26]
```diff
@@ -0,0 +1,322 @@
...
+	p.lock.Lock()
+	defer p.lock.Unlock()
+	return p.numberOfWorkers
+}
+
+// MaxNumberOfWorkers returns the maximum number of workers automatically added to the pool
+func (p *WorkerPool) MaxNumberOfWorkers() int {
+	p.lock.Lock()
+	defer p.lock.Unlock()
+	return p.maxNumberOfWorkers
```
Comment (guillep2k) [inline modules/queue/workerpool.go:117]: I think `atomic.LoadInt64(&p.maxNumberOfWorkers` is preferrable, so no Lock/Unlock are needed.

File: modules/setting/queue.go (hunk 15 above)
Comment (zeripath) [reply modules/setting/queue.go]: Done

File: modules/queue/workerpool.go [hunk 27]
```diff
@@ -0,0 +1,322 @@
...
+		p.numberOfWorkers++
+		p.lock.Unlock()
+		go func() {
+			p.doWork(ctx)
+
+			p.lock.Lock()
+			p.numberOfWorkers--
+			if p.numberOfWorkers <= 0 {
+				// numberOfWorkers can't go negative but...
+				p.numberOfWorkers = 0
```
Comment (guillep2k) [inline modules/queue/workerpool.go:210]: A `log.Warn` seems in order.

File: modules/queue/workerpool.go [hunk 28]
```diff
@@ -0,0 +1,322 @@
...
+func (p *WorkerPool) Wait() {
+	p.lock.Lock()
+	defer p.lock.Unlock()
+	if p.cond == nil {
+		p.cond = sync.NewCond(&p.lock)
+	}
+	if p.numberOfWorkers <= 0 {
+		return
+	}
+	p.cond.Wait()
```
Comment (guillep2k) [inline modules/queue/workerpool.go:228]: Is it OK to `Wait()` while holding `p.lock`?

File: modules/setting/queue.go [hunk 29]
```diff
@@ -0,0 +1,214 @@
...
+		default:
+			log.Fatal("Unsupported indexer queue type: %v",
+				Indexer.IssueQueueType)
+		}
+	}
+	if _, ok := issueIndexerSectionMap["LENGTH"]; !ok {
+		section.Key("LENGTH").SetValue(fmt.Sprintf("%d", Indexer.UpdateQueueLength))
+	}
+	if _, ok := issueIndexerSectionMap["BATCH_LENGTH"]; !ok {
+		section.Key("BATCH_LENGTH").SetValue(fmt.Sprintf("%d", Indexer.IssueQueueBatchNumber))
```
Comment (guillep2k) [inline modules/setting/queue.go:126]: What will the pusher do if the queue is full? Will it block, will it drop requests? (e.g. in the initial indexer population, a repo migration, etc).

**Review by guillep2k — COMMENTED** [review]
Still more to go... 😅

File: options/locale/locale_en-US.ini [hunk 30]
```diff
@@ -2022,6 +2022,54 @@ monitor.execute_time = Execution Time
...
+monitor.queue.settings.timeout = Boost Timeout
+monitor.queue.settings.timeout.placeholder = Currently %[1]v
+monitor.queue.settings.timeout.error = Timeout must be a golang duration eg. 5m or be 0
+monitor.queue.settings.numberworkers = Boost Number of Workers
+monitor.queue.settings.numberworkers.placeholder = Currently %[1]d
+monitor.queue.settings.numberworkers.error = Number of Workers to add must be greater than or equal to zero
+monitor.queue.settings.maxnumberworkers = Max Number of workers
+monitor.queue.settings.maxnumberworkers.placeholder = Currently %[1]d
+monitor.queue.settings.maxnumberworkers.error = Max number of workers must be a number
+monitor.queue.settings.submit = Change Settings
```
Comment (guillep2k) [inline options/locale/locale_en-US.ini]:
```suggestion
monitor.queue.settings.submit = Update Settings
```

File: options/locale/locale_en-US.ini [hunk 31]
```diff
@@ -2022,6 +2022,54 @@ monitor.execute_time = Execution Time
...
+
+monitor.queue.pool.none = This queue does not have a Pool
+monitor.queue.pool.added = Worker Group Added
+monitor.queue.pool.max_changed = Maximum number of workers changed
+monitor.queue.pool.workers.title = Active Worker Groups
+monitor.queue.pool.workers.none = No worker groups.
+monitor.queue.pool.cancel = Shutdown Worker Group
+monitor.queue.pool.cancelling = Worker Group shutting down
+monitor.queue.pool.cancel_notices = Shutdown this group of %s workers?
+monitor.queue.pool.cancel_desc = Leaving a queue without any worker groups may cause requests may block indefinitely.
```
Comment (guillep2k) [inline options/locale/locale_en-US.ini]:
```suggestion
monitor.queue.pool.cancel_desc = Leaving a queue without any worker groups may cause requests to block indefinitely.
```

File: modules/setting/task.go [hunk 32]
```diff
@@ -4,22 +4,15 @@
...
 func newTaskService() {
-	sec := Cfg.Section("task")
-	Task.QueueType = sec.Key("QUEUE_TYPE").MustString(ChannelQueueType)
-	Task.QueueLength = sec.Key("QUEUE_LENGTH").MustInt(1000)
-	Task.QueueConnStr = sec.Key("QUEUE_CONN_STR").MustString("addrs=127.0.0.1:6379 db=0")
+	taskSec := Cfg.Section("task")
+	queueTaskSec := Cfg.Section("queue.task")
+	switch taskSec.Key("QUEUE_TYPE").MustString(ChannelQueueType) {
+	case ChannelQueueType:
+		queueTaskSec.Key("TYPE").MustString("persistable-channel")
```
Comment (guillep2k) [inline modules/setting/task.go:12]: Where do these values go?

File: routers/admin/admin.go [hunk 33]
```diff
@@ -366,3 +370,126 @@ func MonitorCancel(ctx *context.Context) {
...
+		ctx.Flash.Error(ctx.Tr("admin.monitor.queue.pool.none"))
+		ctx.Redirect(setting.AppSubURL + fmt.Sprintf("/admin/monitor/queue/%d", qid))
+		return
+	}
+	mq.AddWorkers(number, timeout)
+	ctx.Flash.Success(ctx.Tr("admin.monitor.queue.pool.added"))
+	ctx.Redirect(setting.AppSubURL + fmt.Sprintf("/admin/monitor/queue/%d", qid))
+}
+
+// SetQueueSettings sets the maximum number of workers for this queue
```
Comment (guillep2k) [inline routers/admin/admin.go]:
```suggestion
// SetQueueSettings sets the maximum number of workers and other values for a queue
```

**Review by guillep2k — COMMENTED** [review]
Last batch! :dizzy_face:

**Comment by lunny** [comment]
@zeripath I would like move this to v1.12 since we need more time to review.

File: modules/setting/queue.go (hunk 15 above)
Comment (zeripath) [reply modules/setting/queue.go]: There's always this problem with configuration - you don't want configuration to end up depending on everything however, correct configuration depends on the specifics of the modules it's configuring.

In this case the original code would check against the list of valid queue types at configuration time and would do some nice bridging between the ini configuration of our current setting format and the more POJO like config I'd written for the queue interface.

I think we're quite limited by our current architecture for setting up Gitea - I'd suggest a more DI approach but that's a massive PR.

File: modules/queue/queue_redis.go (hunk 18 above)
Comment (zeripath) [reply modules/queue/queue_redis.go:107]: I don't know - I just copied this code from the original here:

https://github.com/go-gitea/gitea/blob/171b3598778a1ecd0a921c71ed6755bfef68f7f0/modules/indexer/issues/queue_redis.go#L80

The redis command is documented here:

https://redis.io/commands/ping

and the clustering is here: 

https://redis.io/topics/cluster-spec

As I just copied this code from other code in Gitea I have assumed it's correct.

@lunny can you answer @guillep2k's question here?

File: modules/queue/queue_redis.go (hunk 19 above)
Comment (zeripath) [reply modules/queue/queue_redis.go:146]: So it depends on what you mean by blocking... 

* Redis LPop doesn't block at the Redis end - so once you've sent the message and redis has received it, it will send back redis.Nil.

* If you mean the queue blocking whilst this is going on well... It's difficult because LPop is not a channel so you can't do:
 
```go
case <- r.closed():
...
case <- LPop():
...
```

Looking at the code for go-redis (the current v6 line) - although it has functions `WithContext(...)` and `Context()` these aren't being used anywhere... They're a bit more plugged in in the v7 beta - so although I can add the WithContext() formulation to the code it won't be helpful - and even using the v7 beta doesn't seem to use the context for the TLS code. (I'm also a bit concerned that there's no clear way to just create a RedisClient with a context from the start but looking at that code the uncloned previous client doesn't seem to need to be closed.)

The default Timeout for read and write are 3 seconds - which I suppose are ok.

The only way of cancelling I can see is to create a purpose built dialer. I guess that's what we have to do if we really want this cancellable but then upgrading to v7 when it comes out will be a bit more difficult.

Comment (zeripath) [reply modules/queue/queue_redis.go:146]: OK so in order to have the context be in this connection section we would need to rewrite the line:

```go
	} else if len(dbs) == 1 {
		queue.client = redis.NewClient(&redis.Options{
			Network:  config.Network,
			Addr:     strings.TrimSpace(dbs[0]), // use default Addr
			Password: config.Password,           // no password set
			DB:       config.DBIndex,            // use default DB
		})
```

To:

```go
		addr := strings.TrimSpace(dbs[0])
		var dialer func() (net.Conn, error)
		if config.TLS {
			dialer = func() (net.Conn, error) {
				netDialer := &net.Dialer{
					Timeout:   5 * time.Second,
					KeepAlive: 5 * time.Minute,
				}
				return netDialer.DialContext(ctx, config.Network, addr)
			}
		} else {
			host := addr
			host, _, err := net.SplitHostPort(addr)
			if err != nil {
				log.Warn("Unable to split %s as a host port: Error: %v", addr)
				host = addr
			}
			tlsConfig := &tls.Config{ServerName: host}
			dialer = func() (net.Conn, error) {
				netDialer := &net.Dialer{
					Timeout:   5 * time.Second,
					KeepAlive: 5 * time.Minute,
				}
				errChan := make(chan error, 2)
				time.AfterFunc(netDialer.Timeout, func() {
					errChan <- fmt.Errorf("tls: DialWithDialer timed out")
				})
				conn, err := netDialer.DialContext(ctx, config.Network, addr)
				if err != nil {
					return nil, err
				}
				tlsConn := tls.Client(conn, tlsConfig)
				go func() {
					errChan <- tlsConn.Handshake()
				}()
				select {
				case err = <-errChan:
					if err != nil {
						conn.Close()
						return nil, err
					}
				case <-ctx.Done():
					tlsConn.Close()
					conn.Close()
					return nil, ctx.Err()
				}

				return tlsConn, nil
			}
		}
		queue.client = redis.NewClient(&redis.Options{
			Network:  config.Network,
			Addr:     addr,
			Password: config.Password,
			DB:       config.DBIndex,
			Dialer:   dialer,
		})
```

Comment (zeripath) [reply modules/queue/queue_redis.go:146]: And something similar for the cluster client...

File: modules/queue/queue_redis.go (hunk 21 above)
Comment (zeripath) [reply modules/queue/queue_redis.go:205]: I'll add a mutex to both this and the ledis disk queue.

File: modules/queue/queue_wrapped.go [hunk 34]
```diff
@@ -0,0 +1,196 @@
...
+			return fmt.Errorf("Unable to assign data: %v to same type as exemplar: %v in %s", data, q.exemplar, q.name)
+		}
+	}
+	q.channel <- data
+	return nil
+}
+
+// Run starts to run the queue and attempts to create the internal queue
+func (q *WrappedQueue) Run(atShutdown, atTerminate func(context.Context, func())) {
+	q.lock.Lock()
```
[the remark this answers is not in the document]
Comment (zeripath) [reply modules/queue/queue_wrapped.go:157]: I don't think there's any particular difference either way but I've moved the unlocking out of setInternal.

Done.

File: modules/queue/queue_wrapped.go (hunk 23 above)
Comment (zeripath) [reply modules/queue/queue_wrapped.go:181]: That's why it adds it's own shutdown handler that causes setInternal to exit

File: modules/queue/queue_wrapped.go (hunk 24 above)
Comment (zeripath) [reply modules/queue/queue_wrapped.go:194]: That's why it adds it's own shutdown handler that causes setInternal to exit

File: modules/queue/workerpool.go (hunk 25 above)
Comment (zeripath) [reply modules/queue/workerpool.go:44]: That's why I've done so much work to make this configurable!!

File: modules/queue/workerpool.go (hunk 26 above)
Comment (zeripath) [reply modules/queue/workerpool.go:117]: Then we'd have to change the storing of maxNumberOfWorkers to atomic.StoreInt64 and any other use of maxNumberOfWorkers to Load as appropriate whereas we can simply lock. (4 other places.)

It's just adding complexity.

File: modules/queue/workerpool.go (hunk 27 above)
Comment (zeripath) [reply modules/queue/workerpool.go:210]: done.

File: modules/queue/workerpool.go (hunk 28 above)
Comment (zeripath) [reply modules/queue/workerpool.go:228]: Yes. In fact you must:

https://golang.org/pkg/sync/#Cond.Wait

Wait atomically unlocks c.L and suspends execution of the calling goroutine. After later resuming execution, Wait locks c.L before returning. Unlike in other systems, Wait cannot return unless awoken by Broadcast or Signal.

Technically this should be the even more confusing:

```go
// Wait for WorkerPool to finish
func (p *WorkerPool) Wait() {
	p.lock.Lock()
	defer p.lock.Unlock()
	if p.cond == nil {
		p.cond = sync.NewCond(&p.lock)
	}
	for {
		if p.numberOfWorkers <= 0 {
			return
		}
		p.cond.Wait()	
	}
}
```

However, no code uses it in such a way that the number of workers could increase between the lock unlocking and being relocked - the wait happens after the pool is closed.

If you want I can add that loop though.

File: modules/setting/queue.go (hunk 29 above)
Comment (zeripath) [reply modules/setting/queue.go:126]: You should be commenting on the Length setting - Batch_length is about the size of the array sent to the handler of the queue.

However, if the queue contains LENGTH elements it blocks - hence the pool worker boost ability.

File: modules/setting/task.go (hunk 32 above)
Comment (zeripath) [reply modules/setting/task.go:12]: This is here to support the old task configuration and maps onto the queue configuration.

If the user configures a queue.task section then those values will override these task configuration sections.

File: modules/queue/queue_redis.go (hunk 17 above)
Comment (zeripath) [reply modules/queue/queue_redis.go]: Done

File: modules/queue/queue_redis.go (hunk 19 above)
Comment (guillep2k) [reply modules/queue/queue_redis.go:146]: Otherwise the shutdown time will be increased in up to three seconds. Perhaps we can shorten the wait to 1 sec? (is it configurable?)

File: modules/queue/queue_wrapped.go (hunk 34 above)
[the remark this answers is not in the document]
Comment (guillep2k) [reply modules/queue/queue_wrapped.go:157]: I think that having lock and unlock in the same function is easier for analysis and for refactoring.

File: modules/setting/queue.go (hunk 29 above)
Comment (guillep2k) [reply modules/setting/queue.go:126]: I ask because IMHO I think it _should_ block. Let's take indexing as example. In the initial index population, if there are too many files to process, the indexing will not get faster by adding workers (i.e. boost): I/O will be at peak demand, memory consumption will skyrocket, the whole system will slow down... even start swapping out... However, if the queue blocks (which is a natural thing to do for a queue), it will make the data provider (repository loop) to wait until some of the work has been cleared out. On the other hand, if releasing the provider as quick as possible is critical, it's preferrable to let the queue grow indefinitely and have only the right amount of workers.

File: modules/queue/queue_redis.go (hunk 19 above)
Comment (zeripath) [reply modules/queue/queue_redis.go:146]: it could be configurable as go-redis provides the option.

File: docs/content/doc/advanced/config-cheat-sheet.en-us.md [hunk 35]
```diff
@@ -234,13 +235,23 @@ relation to port exhaustion.
...
-## Queue (`queue`)
+## Queue (`queue` and `queue.*`)
 
 - `TYPE`: **persistable-channel**: General queue type, currently support: `persistable-channel`, `channel`, `level`, `redis`, `dummy`
-- `DATADIR`: **queues/**: Base DataDir for storing persistent and level queues.
+- `DATADIR`: **queues/**: Base DataDir for storing persistent and level queues. `DATADIR` for inidividual queues can be set in `queue.name` sections but will default to `DATADIR/`**`name`**.
 - `LENGTH`: **20**: Maximal queue size before channel queues block
 - `BATCH_LENGTH`: **20**: Batch data before passing to the handler
 - `CONN_STR`: **addrs=127.0.0.1:6379 db=0**: Connection string for the redis queue type.
+- `QUEUE_NAME`: **""**: The suffix for default redis queue name. Individual queues will default to **`name`**`QUEUE_NAME` but can be overriden in the specific `queue.name` section.
```
Comment (guillep2k) [inline docs/content/doc/advanced/config-cheat-sheet.en-us.md]: Is it `_queue` as in `app.ini.sample` or `""` like it says here?

File: modules/setting/queue.go (hunk 29 above)
Comment (zeripath) [reply modules/setting/queue.go:126]: OK, so it is dependent on the underlying queue type where it blocks.

In the case of the level and redis queues the caller will not block - it's going to block at the reader from the db and it is there that handles the boost functionality.

In the case of the channel queues it will block at caller level. Persistent Channel queues are basically Channel queues except on initialisation when they read from the disk or at shutdown when they write to the disk.

Whether you get a boost or not is dependent on the pool settings but by default you shouldn't end up with more than 10 workers on any particular queue - with a boost of 5 workers if you block for a 1s and a further boost of 4 if you block for 2s after blocking for 1s.

File: docs/content/doc/advanced/config-cheat-sheet.en-us.md (hunk 35 above)
Comment (zeripath) [reply docs/content/doc/advanced/config-cheat-sheet.en-us.md]:
```suggestion
- `QUEUE_NAME`: **_queue**: The suffix for default redis queue name. Individual queues will default to **`name`**`QUEUE_NAME` but can be overriden in the specific `queue.name` section.
```

Comment (zeripath) [reply docs/content/doc/advanced/config-cheat-sheet.en-us.md]: Sorry about that. I literally changed my mind straight after writing that section.

**Review by guillep2k — APPROVED** [review]

**Comment by guillep2k** [comment]
That's a lot of work. Thank you!!!

**Comment by lafriks** [comment]
@lunny need your review

File: modules/setting/queue.go (hunk 15 above)
Comment (techknowlogick) [reply modules/setting/queue.go]: I think it is ok for settings to rely on queue because queue only relies on log (settings also relies on log), so circular dependency is not possible right now. I agree that DI should be done in future, but out of scope of this PR.

**Review by techknowlogick — APPROVED** [review]

File: modules/indexer/issues/indexer_test.go [hunk 36]
```diff
@@ -14,6 +14,7 @@ import (
 
 	"code.gitea.io/gitea/models"
 	"code.gitea.io/gitea/modules/setting"
+	"gopkg.in/ini.v1"
```
Comment (lunny) [inline modules/indexer/issues/indexer_test.go:18]: blank line.

File: modules/queue/manager.go [hunk 37]
```diff
@@ -0,0 +1,270 @@
...
+	"time"
+
+	"code.gitea.io/gitea/modules/log"
+)
+
+var manager *Manager
+
+// Manager is a queue manager
+type Manager struct {
+	mutex sync.Mutex
```
Comment (lunny) [inline modules/queue/manager.go:23]: How about use `sync.Map`?

**Comment by lunny** [comment]
Need a blank line on these two tables.

图片

**Comment by lunny** [comment]
Why we have two task queues?

图片

**Comment by lunny** [comment]
How about format the timeout as `1s`?

```
 Initial Configuration

{
  "DataDir": "xxxxxxxxx",
  "QueueLength": 20,
  "BatchLength": 20,
  "Workers": 1,
  "MaxWorkers": 10,
  "BlockTimeout": 1000000000,
  "BoostTimeout": 300000000000,
  "BoostWorkers": 5,
  "Name": "issue_indexer"
}
```

File: modules/queue/queue_disk.go (hunk 11 above)
Comment (lunny) [reply modules/queue/queue_disk.go:48]: This should be my typo on previous PR. It should be `leveldb based`.

File: modules/indexer/issues/indexer_test.go (hunk 36 above)
Comment (zeripath) [reply modules/indexer/issues/indexer_test.go:18]:
```suggestion

	"gopkg.in/ini.v1"
```

File: modules/queue/manager.go (hunk 37 above)
Comment (zeripath) [reply modules/queue/manager.go:23]: The key is a counter - you would need to lock in any case to increment the counter so sync.Map gains you nothing but the loss of static typing.

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/pull/9363#issuecomment-570986944

This is a fomantic problem take a look at the admin settings page and everywhere else that uses the same html structure.

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/pull/9363#issuecomment-570987107

The default queue is a persistable-channel so you have a level queue that exists to read from the level db that was persisted at previous shutdown - it should be empty - and a channel queue that Gitea is using. 

At terminate the both queue's workers are stopped and the remaining contents of the channel queue is diverted to the level queue before the level queue is closed.

On startup you get both queues again, only this time there should be some contents in the level queue so its worker will work its way through the queue until that is empty at which point it will have nothing more to do. The channel queue will be active in the meantime.

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/pull/9363#issuecomment-570987461

Hmm... That section comes from:

```
<pre>{{.Queue.Configuration | JsonPrettyPrint}}
```

in templates/admin/queue.tmpl

So to render the timeouts correctly we'd need to degenericise that and specifically render each config type. It's possible but a lot of work to get right and keep right ... We don't do that for session providers, or other places that use jsonprettyprint.

**Comment by lunny** [comment]
`QUEUE_NAME` on `[queue.task]` seems not be displayed correctly on monitoring UI.

**Comment by zeripath** [comment]
QUEUE_NAME is the redis queue name. I can change that to make it clearer of required.

**Review by lunny — APPROVED** [review]
