### PR TITLE
Fix package list performance

### LINKED ISSUE #28255: Performance issue when viewing all packages of an organisation
### Description

In addition to #25953 there is atleast on more very slow scenario for a very lot of packages when viewing all packages of an organisation. The total time was about 4m.

I discovered atleast two very slow queries:
```sql
exec sp_executesql N'SELECT * FROM [package_version] LEFT JOIN [package_version] [pv2] ON (package_version.package_id = pv2.package_id AND (package_version.created_unix < pv2.created_unix OR (package_version.created_unix = pv2.created_unix AND package_version.id < pv2.id))) AND pv2.is_internal=@p1 INNER JOIN [package] ON package.id = package_version.package_id WHERE package_version.is_internal=@p2 AND package.owner_id=@p3 AND (pv2.id IS NULL) ORDER BY [package_version].[created_unix] DESC OFFSET 0 ROWS FETCH NEXT 20 ROWS ONLY',N'@p1 bit,@p2 bit,@p3 bigint',@p1=0,@p2=0,@p3=2
```

and

```sql
exec sp_executesql N'SELECT count(*) FROM [package_version] LEFT JOIN [package_version] [pv2] ON (package_version.package_id = pv2.package_id AND (package_version.created_unix < pv2.created_unix OR (package_version.created_unix = pv2.created_unix AND package_version.id < pv2.id))) AND pv2.is_internal=@p1 INNER JOIN [package] ON package.id = package_version.package_id WHERE package_version.is_internal=@p2 AND package.owner_id=@p3 AND (pv2.id IS NULL)',N'@p1 bit,@p2 bit,@p3 bigint',@p1=0,@p2=0,@p3=2
```

The first one run 2m46s and the second one 1m20s.
There might be more slow queries.

I'm happy to help and execute queries for test if necessary

### Gitea Version

Gitea version 1.21.1 built with GNU Make 4.3, go1.21.4 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

git version 2.39.1.windows.1

### Operating System

Windows Server 2016 - Version 1607 (Build 14393.6452)

### How are you running Gitea?

- Using `gitea-1.21.1-windows-4.0-amd64.exe` from your download page
- Registered as a Windows service with the following command line: `D:\gitea\gitea.exe web --config D:\gitea\custom\conf\app.ini`

### Database

MSSQL

### PR DESCRIPTION
**Pull request by KN4CK3R**
Fixes #28255

The new query uses the id field to sort by "newer". This must not be correct (usually it is) but it's faster (see #28255).
If someone has a better idea, please propose changes.

### CODE REVIEW

File: models/packages/package_version.go [hunk 1]
```diff
@@ -304,19 +305,18 @@ func SearchVersions(ctx context.Context, opts *PackageSearchOptions) ([]*Package
...
+		From("package_version").
+		InnerJoin("package", "package.id = package_version.package_id").
+		Where(opts.ToConds()).
+		GroupBy("package_version.package_id")
 
 	sess := db.GetEngine(ctx).
+		Select("package_version.*").
 		Table("package_version").
-		Join("LEFT", "package_version pv2", joinCond).
 		Join("INNER", "package", "package.id = package_version.package_id").
```
Comment (lunny) [inline models/packages/package_version.go:318]: Looks like this line could be removed.

**Review by lunny — APPROVED** [review]
per https://github.com/go-gitea/gitea/pull/30520/files#r1568415629 , otherwise LGTM

File: models/packages/package_version.go (hunk 1 above)
Comment (KN4CK3R) [reply models/packages/package_version.go:318]: It's needed by `configureOrderBy` because you could sort by `package.name`.

**Review by silverwind — APPROVED** [review]
