### PR TITLE
Fix CODEOWNERS review request attribution using comment metadata

### LINKED ISSUE #36333: When reviewers are automatically added via CODEOWNERS rules, it is presented as an action by the PR author
### Description

When the `.gitea/CODEOWNERS` file indicates a user should be added as reviewer to a PR, this reviewer is added automatically. This addition is marked as a personal action by the PR author:

> `${PR_OWNER}` requested review from `${CODE_OWNER}` 18 hours ago

This even happens when the `CODEOWNERS` file did not exist when the PR was created; in that case, the reviewer is added when a new commit is pushed to the PR. And it happens even when the PR author previously removed that particular user from the reviewers list.

This behaviour means that I, as PR author, have no control over this. The code owner is always added to the reviewers list. If that's how Gitea works, that's a bit clumsy, but fine.

I do have **a moral issue with the fact that this is presented in the Gitea history as my personal action**. This is wrong, and the reason I write this bug report. Especially because, as I described above, I have no control over this.

A solution would simply be to change the node that is added to the PR:

> System requested review from `${CODE_OWNER}` by CODEOWNERS ruleset

That way I also understand where this comes from, and that I didn't just mis-click something. And other people understand that I didn't choose to add this user to the reviewers list, but that it was an automated action.

Example in production: https://projects.blender.org/blender/blender/pulls/152416

I can't test on demo.gitea.com because I'm getting a '500 Internal Server Error' when I try to log in.

### Gitea Version

1.25.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Self-built, self-hosted.

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by bimakw**
## Problem

When CODEOWNERS automatically assigns reviewers to a pull request, the timeline incorrectly shows the PR author as the one who requested the review (e.g., "PR_AUTHOR requested review from CODE_OWNER"). This is misleading since the action was triggered automatically by CODEOWNERS rules, not by the PR author.

Fixes #36333

## Solution

Store CODEOWNERS attribution in comment metadata instead of changing the doer user:
- Add `SpecialDoerName` field to `CommentMetaData` struct (value: `"CODEOWNERS"` for CODEOWNERS-triggered requests)
- Pass `isCodeOwners=true` to `AddReviewRequest` and `AddTeamReviewRequest` functions
- Template can check this metadata to show appropriate attribution message

This approach:
- Keeps the actual doer (PR author) intact for permission/audit purposes
- Allows UI to display "CODEOWNERS requested review" when metadata is present
- More general design that can support other special doer names in the future

## Changes

- `models/issues/comment.go`: Add `SpecialDoerName` field to `CommentMetaData` and `CreateCommentOptions`
- `models/issues/review.go`: Update `AddReviewRequest` and `AddTeamReviewRequest` to set metadata when `isCodeOwners=true`
- `models/issues/review_test.go`: Add test case for metadata verification

## Testing

- [x] `go build` passes
- [x] `go test` passes for `TestAddReviewRequest`

### CODE REVIEW

**Comment by wxiaoguang** [comment]
It is an abuse of "Ghost" user. "Ghost" user means that there was a user, but it has been deleted.

**Comment by bimakw** [comment]
Makes sense. Was thinking of adding something like CodeOwnersUser (similar to ActionsUser), would that work?

**Comment by wxiaoguang** [comment]
> Makes sense. Was thinking of adding something like CodeOwnersUser (similar to ActionsUser), would that work?

I believe it needs a general "gitea system account" at the moment (https://github.com/go-gitea/gitea/pull/30205#discussion_r2562129164)

Keeping adding new "system accounts" causes problems for end users who might already have users with the same names (https://github.com/go-gitea/gitea/pull/30205#discussion_r2652363891)

But other maintainers might not agree with me.

**Comment by bimakw** [comment]
Thanks for the feedback @wxiaoguang. I understand the concern about Ghost user semantics - you're right that Ghost user represents deleted accounts, not system automation.

Regarding the general system account approach, I looked at the discussion in #30205. As @lunny [pointed out](https://github.com/go-gitea/gitea/pull/30205#discussion_r2562129164), system bot accounts with `[bot]` prefix and no profile page are visually distinct from regular users, so name collision shouldn't be an issue in practice.

I'd like to propose following the exact same pattern as `ActionsUser`:

```go
const (
    CodeOwnersUserID    int64 = -3
    CodeOwnersUserName        = "gitea-codeowners"
    CodeOwnersUserEmail       = "codeowners@gitea.io"
)

func NewCodeOwnersUser() *User {
    return &User{
        ID:               CodeOwnersUserID,
        Name:             CodeOwnersUserName,
        LowerName:        CodeOwnersUserName,
        IsActive:         true,
        FullName:         "Gitea CODEOWNERS",
        Email:            CodeOwnersUserEmail,
        KeepEmailPrivate: true,
        LoginName:        CodeOwnersUserName,
        Type:             UserTypeBot,
        Visibility:       structs.VisibleTypePublic,
    }
}
```

Plus add `"gitea-codeowners"` to `reservedUsernames`.

This approach is:
- Consistent with existing patterns (`ActionsUser`)
- Semantically correct (CODEOWNERS attribution, not Actions)
- Minimal in scope

Would this approach work, or would you prefer to wait for the broader general system account discussion to conclude first?

**Comment by wxiaoguang** [comment]
> so name collision shouldn't be an issue in practice.

It doesn't answer the question: what if the user's Gitea instance already has a user named `gitea-codeowners`

----

I am against for "keeping adding a lot of reserved usernames", the more you add, the more potential conflicts will be.

**Comment by wxiaoguang** [comment]
> As @lunny [pointed out](https://github.com/go-gitea/gitea/pull/30205#discussion_r2562129164), system bot accounts with `[bot]` prefix and no profile page are visually distinct from regular users, so name collision shouldn't be an issue in practice.

He doesn't answer the question either. As long as you added a new reserved username, there will be conflict. No matter `[bot]` prefix is added or not.

In practice, GitHub's "dependabot" occupies that name too.

**Comment by lunny** [comment]
> > As @lunny [pointed out](https://github.com/go-gitea/gitea/pull/30205#discussion_r2562129164), system bot accounts with `[bot]` prefix and no profile page are visually distinct from regular users, so name collision shouldn't be an issue in practice.
> 
> He doesn't answer the question either. As long as you added a new reserved username, there will be conflict. No matter `[bot]` prefix is added or not.
> 
> In practice, GitHub's "dependabot" occupies that name too.

In GitHub’s implementation, https://github.com/dependabot is an organization, while the dependabot[bot] account is a separate entity that represents the GitHub App. These two are distinct and do not conflict with each other.

**Comment by wxiaoguang** [comment]
> > 
> 
> In GitHub’s implementation, https://github.com/dependabot is an organization, while the dependabot[bot] account is a separate entity that represents the GitHub App. These two are distinct and do not conflict with each other.

Because `dependabot[bot]` works for `dependabot[org]`, literally they are the same thing for the same purpose.

But your design: it only introduces conflicts:

* User has its `project-workflows` user or org.
* Gitea has its `project-workflows` reserved bot name.

They are different things, and it only makes the system more messy when you introduce more potential conflicting names.

**Comment by wxiaoguang** [comment]
Again: OK, that's your choice to keep introducing fragile designs and confusing end users. If you believe it's right, I won't block.

You can use your power to push and merge.

**Comment by lunny** [comment]
> > > 
> > 
> > 
> > In GitHub’s implementation, [@dependabot](https://github.com/dependabot) is an organization, while the dependabot[bot] account is a separate entity that represents the GitHub App. These two are distinct and do not conflict with each other.
> 
> Because `dependabot[bot]` works for `dependabot[org]`, literally they are the same thing for the same purpose.
> 
> But your design: it only introduces conflicts:
> 
> * User has its `project-workflows` user or org.
> * Gitea has its `project-workflows` reserved bot name.
> 
> They are different things, and it only makes the system more messy when you introduce more potential conflicting names.

In GitHub’s implementation, the `dependabot[bot]` account is automatically created when the app is installed and it seems all APP instances created by the same APP share the same name. It is completely unrelated to the `dependabot` organization.

The `dependabot` organization is optional—users may choose to create it or not—and there is no functional relationship between the two beyond the similarity in their names.

I’m simply pointing out how GitHub has implemented this.

**Comment by wxiaoguang** [comment]
> I’m simply pointing out how GitHub has implemented this.

What if a user would like to search the PRs created by the real "dependabot" user? And how to search the PRs created by "dependabot" bot?

GitHub never uses "dependabot" as the "user name"

**Comment by lunny** [comment]
> > I’m simply pointing out how GitHub has implemented this.
> 
> What if a user would like to search the PRs created by the real "dependabot" user? And how to search the PRs created by "dependabot" bot?
> 
> GitHub never uses "dependabot" as the "user name"

Github never use `dependabot` as a `user name` because `dependabot` was registered as an organization. If another APP's name was registered as a user name, there will be a confusing. There will be `xxx [bot]` and `xxx` at the same time and they are unrelated.

I guess there are two tables in Github's implementation, one is `user`, another is `apps`. All names in the `apps` have a label `[bot]` and names from `user` will not. And both kinds of users could be listed in the pull request authors list or other necessary places.

**Comment by wxiaoguang** [comment]
> I guess there are two tables in Github's implementation ...

Please propose a complete and feasible design in Gitea, that's what I am always asking for.

And show how to search PRs for real "dependabot" user, search PRs for bot "dependabot" app.

**Comment by bimakw** [comment]
Replaced GhostUser with dedicated CodeOwnersUser following the same pattern as ActionsUser:

- ID: `-3`
- Name: `gitea-codeowners`
- Type: `UserTypeBot`

This addresses the concern that "Ghost user means deleted user" while maintaining proper semantic attribution for CODEOWNERS-triggered review requests.

Changes:
- Added `CodeOwnersUser` constants and functions in `models/user/user_system.go`
- Added to `reservedUsernames` and `systemUserNewFuncs`
- Updated `services/issue/pull.go` to use `NewCodeOwnersUser()`
- Updated template to check `IsCodeOwners()` instead of `IsGhost()`
- Updated tests

**Comment by bimakw** [comment]
@lunny Ready for review when you have time.

**Comment by lunny** [comment]
I don’t think we need a system bot user here. It’s only used for comments and doesn’t involve any permission design. The comment itself can simply be adjusted to something like:
xxx was requested to review due to changes in xxx file.

File: models/issues/review.go [hunk 1]
```diff
@@ -876,6 +876,130 @@ func RemoveTeamReviewRequest(ctx context.Context, issue *Issue, reviewer *organi
...
+		}
+
+		comment.Review = review
+		return comment, nil
+	})
+}
+
+// AddCodeOwnersTeamReviewRequest adds a team review request from CODEOWNERS rules.
+// It works like AddTeamReviewRequest but marks the comment as CODEOWNERS-triggered.
+func AddCodeOwnersTeamReviewRequest(ctx context.Context, issue *Issue, reviewer *organization.Team, doer *user_model.User) (*Comment, error) {
```
Comment (lunny) [inline models/issues/review.go]: Could you please add a test for this newly added function?

File: models/issues/review.go [hunk 2]
```diff
@@ -876,6 +876,130 @@ func RemoveTeamReviewRequest(ctx context.Context, issue *Issue, reviewer *organi
 	})
 }
 
+// AddCodeOwnersReviewRequest adds a review request from CODEOWNERS rules.
+// It works like AddReviewRequest but marks the comment as CODEOWNERS-triggered.
+func AddCodeOwnersReviewRequest(ctx context.Context, issue *Issue, reviewer, doer *user_model.User) (*Comment, error) {
```
Comment (wxiaoguang) [inline models/issues/review.go]: It is a copy of "AddReviewRequest"? Why not add an option to AddReviewRequest and reuse the existing logic ......

File: models/issues/comment.go [hunk 3]
```diff
@@ -773,11 +774,12 @@ func CreateComment(ctx context.Context, opts *CreateCommentOptions) (_ *Comment,
...
-		if opts.ProjectColumnTitle != "" {
+		if opts.ProjectColumnTitle != "" || opts.IsCodeOwnersReviewRequest {
 			commentMetaData = &CommentMetaData{
-				ProjectColumnID:    opts.ProjectColumnID,
-				ProjectColumnTitle: opts.ProjectColumnTitle,
-				ProjectTitle:       opts.ProjectTitle,
+				ProjectColumnID:           opts.ProjectColumnID,
+				ProjectColumnTitle:        opts.ProjectColumnTitle,
+				ProjectTitle:              opts.ProjectTitle,
+				IsCodeOwnersReviewRequest: opts.IsCodeOwnersReviewRequest,
```
Comment (wxiaoguang) [inline models/issues/comment.go]: Ideally:

```
if opts.ProjectColumnTitle != "" {
    commentMetaData = &CommentMetaData{ project fields }
}
if opts.IsCodeOwnersReviewRequest {
    commentMetaData = &CommentMetaData{ code owners review fields }
}
```

**Review by lunny — APPROVED** [review]

File: models/issues/review_test.go [hunk 4]
```diff
@@ -321,14 +322,178 @@ func TestAddReviewRequest(t *testing.T) {
...
 	pull.HasMerged = true
 	assert.NoError(t, pull.UpdateCols(t.Context(), "has_merged"))
 	issue.IsClosed = false
-	_, err = issues_model.AddReviewRequest(t.Context(), issue, reviewer, &user_model.User{})
+	_, err = issues_model.AddReviewRequest(t.Context(), issue, reviewer, &user_model.User{}, false)
 	assert.Error(t, err)
 	assert.True(t, issues_model.IsErrReviewRequestOnClosedPR(err))
 }
+
+func TestAddReviewRequest_WithCodeOwners(t *testing.T) {
```
Comment (wxiaoguang) [inline models/issues/review_test.go]: These hundreds lines of tests were added for the copied & pasted `AddCodeOwnersReviewRequest` function

Now, the existing `AddReviewRequest` is reused, only one line is added, I think all the new tests should be removed. Only need to add a new case for `AddReviewRequest(..., true)` into the existing tests.

File: models/issues/comment.go [hunk 5]
```diff
@@ -235,9 +235,10 @@ func (r RoleInRepo) LocaleHelper(lang translation.Locale) string {
 
 // CommentMetaData stores metadata for a comment, these data will not be changed once inserted into database
 type CommentMetaData struct {
-	ProjectColumnID    int64  `json:"project_column_id,omitempty"`
-	ProjectColumnTitle string `json:"project_column_title,omitempty"`
-	ProjectTitle       string `json:"project_title,omitempty"`
+	ProjectColumnID           int64  `json:"project_column_id,omitempty"`
+	ProjectColumnTitle        string `json:"project_column_title,omitempty"`
+	ProjectTitle              string `json:"project_title,omitempty"`
+	IsCodeOwnersReviewRequest bool   `json:"is_code_owners_review_request,omitempty"`
```
Comment (wxiaoguang) [inline models/issues/comment.go]: Is it worth to make it more general for future usages?

I can foresee that there would be similar requirements, so a general field like `SpecialDoerName` seems better, it can be `SpecialDoerName = "CODEOWNERS"` at the moment for this case, and can be reused in the future for other operations.

**Comment by wxiaoguang** [comment]
By the way, PR title & description also need to update.

File: templates/repo/issue/view_content/comments.tmpl [hunk 6]
```diff
@@ -514,32 +514,48 @@
...
-					{{if (gt .AssigneeID 0)}}
-						{{if .RemovedAssignee}}
-							{{if eq .PosterID .AssigneeID}}
-								{{ctx.Locale.Tr "repo.issues.review.remove_review_request_self" $createdStr}}
-							{{else}}
-								{{ctx.Locale.Tr "repo.issues.review.remove_review_request" .Assignee.GetDisplayName $createdStr}}
-							{{end}}
+				{{if and .CommentMetaData .CommentMetaData.IsCodeOwnersReviewRequest}}
+					{{/* CODEOWNERS-triggered review request - show different message */}}
+					<span class="badge tw-bg-transparent">{{svg "octicon-file-code" 16}}</span>
```
Comment (wxiaoguang) [inline templates/repo/issue/view_content/comments.tmpl]: This line is not right. Have you tested the layout and UI?

**Comment by wxiaoguang** [comment]
Made some changes in https://github.com/go-gitea/gitea/pull/36348/commits/decccdf3ff7ba4ccfb79300f6e9dcb229eb2db12

Key points:

1. Fix the UI, and use the same layout/syntax as user's review request, for consistency
2. The template code is fragile, so move the complex logic to Go
3. Clean up or improve "author" related code (by the way)

Screenshots:

<details>

image

----

image

</details>

**Comment by wxiaoguang** [comment]
Oh no, please don't force push. https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md#maintaining-open-prs

I made many necessary changes, please revert to my commits

**Review by wxiaoguang — APPROVED** [review]

File: models/issues/comment.go [hunk 7]
```diff
@@ -764,6 +771,37 @@ func (c *Comment) CodeCommentLink(ctx context.Context) string {
...
+	}
+	if c.CommentMetaData.SpecialDoerName == SpecialDoerNameCodeOwners {
+		return locale.Tr("repo.issues.review.codeowners_rules")
+	}
+	return htmlutil.HTMLFormat("%s", c.CommentMetaData.SpecialDoerName)
+}
+
+func (c *Comment) TimelineRequestedReviewTr(locale translation.Locale, createdStr template.HTML) template.HTML {
+	if c.AssigneeID > 0 {
+		// it guarantees LoadAssigneeUserAndTeam has been called, and c.Assignee is Ghost user but not nil
```
Comment (wxiaoguang) [inline models/issues/comment.go]:
```suggestion
		// it guarantees LoadAssigneeUserAndTeam has been called, and c.Assignee is Ghost user but not nil if the user doesn't exist
```
