### PR TITLE
Trigger sync webhooks on UI commit

### LINKED ISSUE #2295: Committing using web UI does not trigger webhook action "synchronized"
- Gitea version (or commit ref): be29d5f 
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

The webhook action "synchronized" does not get triggered when changes to the PR-branch are made using the web UI.

Steps to reproduce:
1. Setup webhook to be triggered for every event on a repository
2. Fork this repository
3. Make changes to the fork and commit to a new branch using the web UI
4. Create a Pull Request in the original repository (webhook gets triggered correctly)
5. Make another change to the new branch in the forked repository **using the web UI**: **A webhook event "synchronized" is expected to be triggered but it is not triggered.**
6. Checkout the fork/pr-branch, make changes locally and push them back to origin: A webhook event "synchronized" is correctly being triggered

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fixes #2295.

Ensure that `AddTestPullRequestTask(..)` called during a UI commit. For normally-pushed commits, `AddTestPullRequestTask(..)` is called by the `post-receive` webhook, but the webhook does not run* for UI commits.

(*It technically runs, but immediately quits because `$SSH_ORIGINAL_COMMAND` is not set)

### CODE REVIEW

File: routers/private/push_update.go [hunk 1]
```diff
@@ -51,10 +43,5 @@ func PushUpdate(ctx *macaron.Context) {
 		}
 		return
 	}
-
-	log.Trace("TriggerTask '%s/%s' by %s", repo.Name, branch, pusher.Name)
-
-	go models.HookQueue.Add(repo.ID)
```
Comment (ethantkoenig) [inline routers/private/push_update.go:57]: This line is actually removed (as opposed to simply being moved to `models/update.go`), since the repo ID is already added to `HookQueue` by `CommitRepoAction(..)`

**Comment by lunny** [comment]
In fact, there are still many places to call `CommitRepoAction` for example `DeleteRepoFile` where maybe also need to be replaced by `PushUpdate`?

**Comment by ethantkoenig** [comment]
@lunny Good point, I've updated `DeleteRepoFile(..)` and `UploadRepoFiles(..)`

**Comment by lunny** [comment]
LGTM

**Comment by strk** [comment]
LGTM
