### PR TITLE
Remove legacy git code (ver < 2.0), fine tune markup tests

### LINKED ISSUE #19874: Fix all unit tests without git.Init after #19732 merged, clean code for git < 2.0 after #19577
At the moment, PR #19732 doesn't ensure all unit tests call git.Init correctly.

```go
// at the moment, we just use a temp HomeDir to prevent from conflicting with user's git config
// in future, the git module should be initialized first before use.
HomeDir = filepath.Join(os.TempDir(), "/gitea-temp-home")
log.Warn("Git's HomeDir is empty, the git module is not initialized correctly, using a temp HomeDir (%s) temporarily", HomeDir) 
```

This issue is here to remind that these unit tests should be fixed after #19732 gets merged.

And one more thing, since Gitea 1.17 has dropped Git<2.0 (#19577), some code might be cleaned, too.

### LINKED ISSUE #19964: GPG Commit Signatures by Gitea not working anymore in dev builds
### Description

Latest builds showing earlier merged signed commits as `No known key found for this signature in database`.
New merged commits are unsigned.
New initialized repositories are created unsigned with `SIGNING_KEY    = default` and not created at all with error 500 when specifying KEYID instead of default and adding SIGNING_NAME, SIGNING_EMAIL as per docs.

> 2022/06/13 20:54:23 ...s/repository/init.go:349:initRepoCommit() [E] Failed to commit: [commit --author='Ilya Pavlov <piv@devmem.ru>' -m Initial commit -SB0292765]: Stdout: 
	Error: exit status 128 - error: gpg failed to sign the data
	fatal: failed to write commit object
	 - error: gpg failed to sign the data
	fatal: failed to write commit object
2022/06/13 20:54:23 ...ers/web/repo/repo.go:195:handleCreateError() [E] CreatePost: initRepository: initRepoCommit: git commit: exit status 128 - error: gpg failed to sign the data
	fatal: failed to write commit object
	 - error: gpg failed to sign the data
	fatal: failed to write commit object

Server GPG key without expiry date not changed in last two years, git or gitea relevant config parameters either.

```bash
git config --global user.signingkey B0292765
git config --global commit.gpgsign true
```

```ini
[repository.signing]
SIGNING_KEY    = default
INITIAL_COMMIT = always
CRUD_ACTIONS   = pubkey, twofa, parentsigned
WIKI           = never
MERGES         = pubkey, twofa, basesigned, commitssigned
```

When i create manual test commits inside container they are signed.

### Gitea Version

1.17.0+dev-709-gff82a1831

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker image gitea/gitea:dev

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by wxiaoguang**
Follows #19732 #19577
* #19732
* #19577

Close #19874
* #19874

Major changes:
1. Remove legacy code for git < 2.0
2. Fix a bug in runHookPostReceive, now `setup(including git.Init)` is called before `git.NewCommand`
3. Introduce strict mode for `git.InitXxx`
    * strict mode means that if the `git.InitXxx` isn't called, then the calls to `git.NewCommand` will result in error. 
    * this mechanism will guarantee that there will be no mistake in the future. 
4. Fix the unit test code for `markup` module
5. Add more comments for `git.InitXxx`
6. Update document for commit signing, using Gitea's internal git config

Files changed: [Diff with whitespace-ignored](https://github.com/go-gitea/gitea/pull/19930/files?diff=unified&w=1)

### CODE REVIEW

File: modules/git/repo_language_stats_gogit.go [hunk 1]
```diff
@@ -45,7 +45,7 @@ func (repo *Repository) GetLanguageStats(commitID string) (map[string]int64, err
 
 	var checker *CheckAttributeReader
 
-	if CheckGitVersionAtLeast("1.7.8") == nil {
```
Comment (delvh) [inline modules/git/repo_language_stats_gogit.go:48]: Why is the parenthesis still here?

File: modules/git/repo_language_stats_nogogit.go [hunk 2]
```diff
@@ -65,7 +65,7 @@ func (repo *Repository) GetLanguageStats(commitID string) (map[string]int64, err
 
 	var checker *CheckAttributeReader
 
-	if CheckGitVersionAtLeast("1.7.8") == nil {
```
Comment (delvh) [inline modules/git/repo_language_stats_nogogit.go:68]: Why is the parenthesis still here?

File: modules/git/repo_tree.go [hunk 3]
```diff
@@ -45,11 +45,11 @@ func (repo *Repository) CommitTree(author, committer *Signature, tree *Tree, opt
...
 
-	if CheckGitVersionAtLeast("1.7.9") == nil && (opts.KeyID != "" || opts.AlwaysSign) {
+	if opts.KeyID != "" || opts.AlwaysSign {
 		cmd.AddArguments(fmt.Sprintf("-S%s", opts.KeyID))
 	}
 
-	if CheckGitVersionAtLeast("2.0.0") == nil && opts.NoGPGSign {
+	if opts.NoGPGSign {
 		cmd.AddArguments("--no-gpg-sign")
 	}
```
Comment (delvh) [inline modules/git/repo_tree.go:54]: By the way, isn't this logic wrong?
Shouldn't it be `if opts.NoGPGSign { ... } else if opts.KeyID != "" || opts.AlwaysSign { ... }`?

File: services/gitdiff/gitdiff.go [hunk 4]
```diff
@@ -1418,7 +1418,7 @@ func GetDiff(gitRepo *git.Repository, opts *DiffOptions, files ...string) (*Diff
 
 	var checker *git.CheckAttributeReader
 
-	if git.CheckGitVersionAtLeast("1.7.8") == nil {
+	{
```
Comment (delvh) [inline services/gitdiff/gitdiff.go]: Why is the parenthesis still here?

File: modules/git/repo_language_stats_gogit.go (hunk 1 above)
Comment (wxiaoguang) [reply modules/git/repo_language_stats_gogit.go:48]: To limit the variable scopes.

ps: this PR is still WIP, too early to be reviewd.

Comment (delvh) [reply modules/git/repo_language_stats_gogit.go:48]: What's the purpose of a WIP PR then?

File: modules/git/repo_tree.go (hunk 3 above)
Comment (wxiaoguang) [reply modules/git/repo_tree.go:54]: I always prefer to keep the old logic as much as possible when refactoring.

File: modules/git/repo_language_stats_gogit.go (hunk 1 above)
Comment (wxiaoguang) [reply modules/git/repo_language_stats_gogit.go:48]: For me, to do run the full tests.

And you see, GitHub says:

image


Only after the button is clicked, then it's ready for review.

Comment (wxiaoguang) [reply modules/git/repo_language_stats_gogit.go:48]: (ps: I mean `draft` status, too)

Comment (delvh) [reply modules/git/repo_language_stats_gogit.go:48]: Ah, okay. Yeah, that's slightly different from my definition:
For me, a WIP PR is a PR you can already comment on, but where you have to be prepared that it will still (drastically) change.

Comment (wxiaoguang) [reply modules/git/repo_language_stats_gogit.go:48]: Let's wait for more time.

Indeed, the situation of refactoring the git module is more complex than I thought. IMO at the moment it's impossible to achieve the ideal status with a few PRs. We still have to move on.

**Comment by wxiaoguang** [comment]
This PR has done what it could do. There is still a remaining problem.

To avoid blocking 1.17 release, the remaining problem is recorded in a new issue #19938
* #19938

**Comment by zeripath** [comment]
Hmm... This PR is not fixing legacy git code - rather it appears to be removing it.

If so - please re-title.  Perhaps:

Remove support for Git <2.0

**Comment by zeripath** [comment]
Hmm... I remember somewhere you commented about CheckLFSVersion causing problems.

I wonder if It could just be folded into the Init function?

File: modules/git/git.go [hunk 5]
```diff
@@ -24,9 +24,6 @@ import (
 
 var (
 	// GitVersionRequired is the minimum Git version required
-	// At the moment, all code for git 1.x are not changed, if some users want to test with old git client
-	// or bypass the check, they still have a chance to edit this variable manually.
-	// If everything works fine, the code for git 1.x could be removed in a separate PR before 1.17 frozen.
 	GitVersionRequired = "2.0.0"
```
Comment (zeripath) [inline modules/git/git.go]: This may need to become a const

File: modules/git/repo_language_stats_gogit.go [hunk 6]
```diff
@@ -45,7 +45,8 @@ func (repo *Repository) GetLanguageStats(commitID string) (map[string]int64, err
...
+	// this code block is refactored from old code "if (git version ...)", keep the block to limit the variable scope
+	{
```
Comment (zeripath) [inline modules/git/repo_language_stats_gogit.go]: I think it might be reasonable to refactor this into a function:

```go
func (repo *Repository) CheckAttributesFor(commitID string) (checker *CheckAttributeReader, deferrable func())
```

Happy to do that refactor if you want.

Comment (wxiaoguang) [reply modules/git/repo_language_stats_gogit.go:49]: > Hmm... I remember somewhere you commented about CheckLFSVersion causing problems.
> 
> I wonder if It could just be folded into the Init function?

I have tried but got no success at the moment. Since 1.17 is going to be released, I think the big refactoring could be postponed to next milestone, otherwise there will be a lot of code changed, which may affect the 1.17 milestone.

> I think it might be reasonable to refactor this into a function: CheckAttributesFor

Agree it should be refactored. I was thinking about postponing it to next milestone (reason as above). How do you think? I am fine to either plan.

**Comment by wxiaoguang** [comment]
> Hmm... I remember somewhere you commented about CheckLFSVersion causing problems.
> 
> I wonder if It could just be folded into the Init function?

I have tried but got no success at the moment. Since 1.17 is going to be released, I think the big refactoring could be postponed to next milestone, otherwise there will be a lot of code changed, which may affect the 1.17 milestone.

> I think it might be reasonable to refactor this into a function: CheckAttributesFor

Agree it should be refactored. I was thinking about postponing it to next milestone (reason as above). How do you think? I am fine to either plan.

**Comment by wxiaoguang** [comment]
The remaining problem has been fixed. https://github.com/go-gitea/gitea/issues/19938#issuecomment-1152942934

**Review by delvh — APPROVED** [review]

**Comment by zeripath** [comment]
https://github.com/wxiaoguang/gitea/pull/6

**Comment by wxiaoguang** [comment]
> [wxiaoguang#6](https://github.com/wxiaoguang/gitea/pull/6)

Merged, thank you very much.

**Comment by delvh** [comment]
@silverwind https://github.com/go-gitea/gitea/pull/19577/files

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work.
