### PR TITLE
Fix oauth2 session gob register

### LINKED ISSUE #36016: panic - LinkAccountData
### Description

Hey!

Thanks for the project.
I am not sure how to reproduce the bug.
The site was showing me 500 error, then ssh-ed in server and found following `panic` logs.
The panic was gone when I cleared my session/cookie data and logged in again. It's all working now again.

```
gitea  | 2025/11/24 11:12:50 modules/graceful/server.go:50:NewServer() [I] Starting new Web server: tcp:0.0.0.0:3000 on PID: 16
gitea  | 2025/11/24 11:12:58 HTTPRequest [W] router: failed    GET / for <redacted_ip>:0, panic in 1.2ms @ session@v0.0.0-20240316035857-16768d98ec96/session.go:243(session.Sessioner), err=session(start): gob: name not registered for interface: "code.gitea.io/gitea/routers/web/auth.LinkAccountData"
gitea  | 2025/11/24 11:12:58 routers/common/errpage.go:25:RenderPanicErrorPage() [E] PANIC: session(start): gob: name not registered for interface: "code.gitea.io/gitea/routers/web/auth.LinkAccountData"
gitea  | /usr/local/go/src/runtime/panic.go:783 (0x4860b1)
gitea  | /go/src/code.gitea.io/gitea/modules/web/routing/logger_manager.go:116 (0x1826344)
gitea  | /usr/local/go/src/runtime/panic.go:783 (0x4860b1)
gitea  | /go/pkg/mod/gitea.com/go-chi/session@v0.0.0-20240316035857-16768d98ec96/session.go:247 (0x17cf733)
gitea  | /usr/local/go/src/net/http/server.go:2322 (0x9645e8)
gitea  | /go/src/code.gitea.io/gitea/modules/web/handler.go:125 (0x182ff15)
gitea  | /usr/local/go/src/net/http/server.go:2322 (0x9645e8)
gitea  | /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.3/mux.go:73 (0x182784e)
gitea  | /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.3/mux.go:321 (0x18291ba)
gitea  | /usr/local/go/src/net/http/server.go:2322 (0x9645e8)
gitea  | /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.3/mux.go:477 (0x1829dbb)
gitea  | /usr/local/go/src/net/http/server.go:2322 (0x9645e8)
gitea  | /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.3/mux.go:73 (0x182784e)
gitea  | /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.3/mux.go:321 (0x18291ba)
gitea  | /usr/local/go/src/net/http/server.go:2322 (0x9645e8)
gitea  | /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.3/mux.go:477 (0x1829dbb)
gitea  | /usr/local/go/src/net/http/server.go:2322 (0x9645e8)
gitea  | /go/src/code.gitea.io/gitea/modules/web/routing/logger_manager.go:122 (0x18261ce)
gitea  | /usr/local/go/src/net/http/server.go:2322 (0x9645e8)
gitea  | /go/src/code.gitea.io/gitea/modules/web/handler.go:125 (0x182ff15)
gitea  | /usr/local/go/src/net/http/server.go:2322 (0x9645e8)
gitea  | /go/pkg/mod/github.com/chi-middleware/proxy@v1.1.1/middleware.go:37 (0x29689af)
gitea  | /usr/local/go/src/net/http/server.go:2322 (0x9645e8)
gitea  | /go/src/code.gitea.io/gitea/modules/web/handler.go:125 (0x182ff15)
gitea  | /usr/local/go/src/net/http/server.go:2322 (0x9645e8)
gitea  | /go/src/code.gitea.io/gitea/routers/common/middleware.go:78 (0x296b194)
gitea  | /usr/local/go/src/net/http/server.go:2322 (0x9645e8)
gitea  | /go/src/code.gitea.io/gitea/modules/web/handler.go:125 (0x182ff15)
gitea  | /usr/local/go/src/net/http/server.go:2322 (0x9645e8)
gitea  | /go/src/code.gitea.io/gitea/routers/common/middleware.go:93 (0x296ad2f)
gitea  | /usr/local/go/src/net/http/server.go:2322 (0x9645e8)
gitea  | /go/src/code.gitea.io/gitea/modules/web/handler.go:125 (0x182ff15)
gitea  | /usr/local/go/src/net/http/server.go:2322 (0x9645e8)
gitea  | /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.3/mux.go:90 (0x182780d)
gitea  | /go/src/code.gitea.io/gitea/modules/web/router.go:243 (0x1831bc2)
gitea  | /go/src/code.gitea.io/gitea/modules/web/router.go:181 (0x18315e6)
gitea  | /usr/local/go/src/net/http/server.go:3340 (0x984e4d)
gitea  | /usr/local/go/src/net/http/server.go:2109 (0x9626e4)
gitea  | /usr/local/go/src/runtime/asm_amd64.s:1693 (0x48ea20)
```

### Gitea Version

1.25.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Ubuntu Server

### How are you running Gitea?

Docker (compose)

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by wxiaoguang**
`gob.Register` must be called before Sessioner

Fix #36016

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Upstream fix: https://gitea.com/go-chi/session/pulls/11

**Review by lunny — APPROVED** [review]

File: routers/common/middleware.go [hunk 1]
```diff
@@ -120,8 +125,7 @@ func Sessioner() (func(next http.Handler) http.Handler, error) {
 		Domain:         setting.SessionConfig.Domain,
 	})
 	if err != nil {
-		return nil, fmt.Errorf("failed to create session middleware: %w", err)
```
Comment (delvh) [inline routers/common/middleware.go:123]: I'm not sure if the old or the new version of this error message is better.
I think I prefer the old one.

**Review by delvh — APPROVED** [review]

File: routers/common/middleware.go (hunk 1 above)
Comment (wxiaoguang) [reply routers/common/middleware.go:123]: This is the **old one**:

image
