### PR TITLE
Fix bug clone wiki

### LINKED ISSUE #15494: It is impossible to clone wiki repo
- Gitea version: 1.14.0
- Git version: 2.30.0
- Operating system: Ubuntu 18.04.3 LTS
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No

## Description

It is impossible to clone wiki repo any more. 

".wiki.git" suffix is not working.

For example try to clone https://try.gitea.io/pvnhome/test.wiki.git (user: pvnhome, pwd: qwerty):

```
git clone https://try.gitea.io/pvnhome/test.wiki.git
```

### PR DESCRIPTION
**Pull request by lunny**
Fix #15494

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

File: routers/repo/http.go [hunk 1]
```diff
@@ -314,6 +316,11 @@ func httpBase(ctx *context.Context) (h *serviceHandler) {
 			return
 		}
 
+		if isWiki { // you cannot send wiki operation before create the repository
+			ctx.HandleText(http.StatusForbidden, "Repository not found")
```
Comment (lafriks) [inline routers/repo/http.go]: It should be not found:
```suggestion
			ctx.HandleText(http.StatusNotFound, "Repository not found")
```

**Review by lafriks — CHANGES_REQUESTED** [review]

**Review by 6543 — APPROVED** [review]

**Review by lafriks — APPROVED** [review]
