### PR TITLE
Fixing the issue when status check per rule matches multiple actions

### LINKED ISSUE #29628: Gitea fails to complete all checks with more than 1 pattern in "Enable status check"
### Description

Hello.
I have a branch, which is protected with setting "Enable status check" and Build server, which is sending statuses of build in Gitea.
When I set **only one** pattern in a field, all checks are considered successful.
When I set **multiply** patterns in a filed, I got an error "Some required checks are missing" 
You can see it on screenshots.

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

Multiply pattern

sc1

PR checks failed

sc2

Single patterns

sc3

PR checks successful

sc4

### Git Version

latest

### Operating System

linux

### How are you running Gitea?

self-hosted

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by charles7668**
Close #29628
rule
```
Test / Build*
Test / Build *
Test / Build 2*
Test / Build 1*
```
image
rule2
```
Test / Build*
Test / Build 1*
```
image

rule3
```
Test / Build*
Test / Build 1*
NotExist*
```
image

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Related to:

* #29143

I guess the `if matchedCount != len(requiredContexts)` was written intentionally?  @MarkusAmshove would you like to take a look? 🙏

**Comment by wxiaoguang** [comment]
Maybe, the logic needs to rewrite, and add some tests:

Suppose there are some rules:

```
*success*
*complete*
```

----

If the results are:

```
required Task1 success
required Task2 complete
required Task3 success & complete
other Task4
```

Then, the check should pass.

----

If the results are:

```
required Task1 success
required Task2 complete
required Task3 fail
other Task4
```

Then, the check should fail.

**Comment by wxiaoguang** [comment]
I proposed some examples in https://github.com/go-gitea/gitea/pull/29631#issuecomment-1980759915.

I think the correct logic should be:

1. All "required" are matched
2. All "rules" are used

**Comment by wxiaoguang** [comment]
Sorry I think I misunderstood something. Ignore my comments ....

ps: It would be helpful to add some tests to clarify the behavior.

**Comment by MarkusAmshove** [comment]
> Related to:
> 
> 
> 
> * #29143
> 
> 
> 
> I guess the `if matchedCount != len(requiredContexts)` was written intentionally?  @MarkusAmshove would you like to take a look? 🙏

The problem I fixed with that condition was that the function was returning success even if a required check hasn't run at all (e.g. no status check was submitted that matches a required pattern).
I guess I didn't think of a `*` pattern that catches multiple checks (so required 1, but matched 5).
The condition should still be correct, but it should test if matched is less than required, not unequal.
That should catch both cases

**Comment by MarkusAmshove** [comment]
Yeah I think I didn't communicate that well.

The deleted `if` in this PR is an early exit, so I was talking about the `pending` condition.

To put it the other way around:
If there is a required context that matches no available status that is successful, then the function should return `pending`.

Currently it is also returning `pending` if a context matches multiple checks and that is obviously a bug.

**Comment by charles7668** [comment]
Hmm... I think perhaps one rule matching at least one action is correct.

In GitHub, it seems like one rule matches just one action.

But if Gitea allows wildcard characters, then it seems to allow one rule to match multiple actions.

In this case, we can't simply compare the rule count and the matched action count.

just like this [case](https://github.com/go-gitea/gitea/pull/29631#issuecomment-1980857197)

**Comment by MarkusAmshove** [comment]
I've taken the time to write some tests, which I should have done beforehand, and also changed the `!=` to `<` to see if my assumption was correct.

Have a look at this commit (feel free to grab the tests into this PR): https://github.com/MarkusAmshove/gitea/commit/adc885be28dac08627b0ddddb2930b78c5a0f0fe
the only test failing is `TestMergeRequiredContextsCommitStatus_MissingContextWithPattern`
But I also can't guarantee that I'm not missing some cases :)

**Comment by charles7668** [comment]
> I've taken the time to write some tests, which I should have done beforehand, and also changed the `!=` to `<` to see if my assumption was correct.
> 
> Have a look at this commit (feel free to grab the tests into this PR): [MarkusAmshove@adc885b](https://github.com/MarkusAmshove/gitea/commit/adc885be28dac08627b0ddddb2930b78c5a0f0fe) the only test failing is `TestMergeRequiredContextsCommitStatus_MissingContextWithPattern` But I also can't guarantee that I'm not missing some cases :)

I'm just curious about this case. I think it should pass because when allowing wildcard characters, sometimes intersections are possible.

image

**Comment by MarkusAmshove** [comment]
None of the contexts have a wildcard character, did you mean to add a * somewhere?

**Comment by charles7668** [comment]
> None of the contexts have a wildcard character, did you mean to add a * somewhere?

Like this, just simulating when multiple rules match the same action.

```go
	givenStatuses := createStatuses(
		createSuccess("Build 1"),
		createSuccess("Build 2"),
		createSuccess("Build 2t"),
	)

	requiredContexts := createRequiredContexts(
		"Build 1*",
		"Build 2*",
		"Build*",
		"Build *",
	)
```

**Comment by MarkusAmshove** [comment]
Yes, that should result in success :-)

Maybe it's easier to change the logic to check each required context if it matches a check and if one doesn't, return pending. That way we don't have to count how many match

**Review by lunny — APPROVED** [review]

File: services/pull/commit_status.go [hunk 1]
```diff
@@ -35,26 +35,30 @@ func MergeRequiredContextsCommitStatus(commitStatuses []*git_model.CommitStatus,
...
 
+			// If required rule not match any action, then it is pending
+			if targetStatus == "" {
+				if structs.CommitStatusPending.NoBetterThan(returnedStatus) {
+					returnedStatus = structs.CommitStatusPending
+				}
+				break
+			}
+
 			if targetStatus != "" && targetStatus.NoBetterThan(returnedStatus) {
```
Comment (Zettat123) [inline services/pull/commit_status.go]:
```suggestion
			if targetStatus.NoBetterThan(returnedStatus) {
```

**Review by Zettat123 — APPROVED** [review]
