### PR TITLE
fix: Actor is required to get user repositories

### LINKED ISSUE #20442: Panic when admin tries to delete a user with `purge=true`
### Description

As an admin, when you try to delete a user with `purge=true`, it panics. This is done using the API, so the url would be something like `https://localhost:3000/api/v1/admin/users/foo?purge=true`.

### Gitea Version

c0f5111fea0b742a60113e1bda81bf39607d6ca8

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/dhruvmanila/9c8a2c45dd31247dd993cfbfa3db2922

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

macOS

### How are you running Gitea?

Running locally using `make watch` command on the command-line.

Steps to reproduce:
1. Create an admin user
2. Create 2 non-admin user
3. Using [`httpie`](https://httpie.io/), run `http :3000/api/v1/admin/users/{username}?purge=false --auth username:password` for the first user and then use `purge=true` for the second user

When purge is true, it panics.

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by dhruvmanila**
fixes: #20442

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

File: models/repo/repo_list.go [hunk 1]
```diff
@@ -695,7 +695,9 @@ func GetUserRepositories(opts *SearchRepoOptions) (RepositoryList, int64, error)
 	}
 
 	cond := builder.NewCond()
-	cond = cond.And(builder.Eq{"owner_id": opts.Actor.ID})
+	if opts.Actor != nil {
+		cond = cond.And(builder.Eq{"owner_id": opts.Actor.ID})
+	}
```
Comment (wxiaoguang) [inline models/repo/repo_list.go]: I am not sure whether we should do this.

This function is named as `GetUserRepositories: returns a list of repositories of given user.`

If this `cond` is removed, then it will list all user's repositories.

**Review by silverwind — CHANGES_REQUESTED** [review]
redacting review for now.

File: models/repo/repo_list.go (hunk 1 above)
Comment (6543) [reply models/repo/repo_list.go]: if actor == nil we have an other issue!!!

Comment (wxiaoguang) [reply models/repo/repo_list.go]: Yup, so the problem should be resolved fundamentally, instead of patching and changing this behavior.

**Comment by 6543** [comment]
what we could do to not have a panic but an error:

check for actor == nil and if so return an error.New("Actor is needed but not given")

**Comment by dhruvmanila** [comment]
So, the panic was thrown because instead of passing in the user model directly through the `Actor` field, it's passing the id through the `OwnerId` field: 

https://github.com/go-gitea/gitea/blob/7690de56f7bdcc5065af2c9478e8572d318a84f3/services/user/user.go#L71-L78

As per the reviews, I think 2 changes need to be done:
1. Pass in the user model directly through the `Actor` option
2. Return an error if `Actor` is not given (as suggested by @6543)

File: services/user/user.go [hunk 2]
```diff
@@ -74,7 +74,7 @@ func DeleteUser(ctx context.Context, u *user_model.User, purge bool) error {
 					Page:     1,
 				},
 				Private: true,
-				OwnerID: u.ID,
+				Actor:   u,
```
Comment (6543) [inline services/user/user.go:78]:
```suggestion
				OwnerID: u.ID,
				Actor:   u,
```

Comment (6543) [reply services/user/user.go:78]: I know OwnerID is not needed in this case ... but as this "option struct schema" nomaly works it's more future prove that way ...

**Review by 6543 — APPROVED** [review]

**Review by zeripath — APPROVED** [review]
I have a feeling we should change repo_model.GetUserRepositories to use OwnerID and not Actor to list the UserRepositories. However, this does fix the bug.

I apologise for merging the PR with this bug - it is due to a mismerge.

**Comment by zeripath** [comment]
I've added a test case too

**Comment by zeripath** [comment]
Doesn't need backporting as far as I'm aware as purging hasn't been backported

**Comment by 6543** [comment]
:rocket:
