### PR TITLE
fix label of --id in admin delete user

### LINKED ISSUE #13995: gitea admin user delete --help gives misleading documentation
This is the current --help output for `gitea admin user delete`:
```
NAME:
   Gitea admin user delete - Delete specific user

USAGE:
   Gitea admin user delete [command options] [arguments...]

OPTIONS:
   --id value                     ID of authentication source (default: 0)
   --custom-path value, -C value  Custom path file path (default: "/home/git/custom")
   --config value, -c value       Custom configuration file path (default: "/home/git/custom/conf/app.ini")
   --version, -v                  print the version
   --work-path value, -w value    Set the gitea working path (default: "/home/git")
```

BUT the `--id` switch does NOT specify an authentication source. Instead it is used as the _user_ identifier (not easy to figure out, btw).  I'd think it's a bug in implementation rather than documentation, and that the implmeentation is missing a `--username` switch to reference users by username instead of id

### PR DESCRIPTION
**Pull request by zeripath**
This pr fixes the label descriptor of `gitea admin delete user`
but also adds a `--username` and `--email` option.

Fix #13995

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: cmd/admin.go [hunk 1]
```diff
@@ -463,15 +469,21 @@ func runListUsers(c *cli.Context) error {
...
 	}
 
-	user, err := models.GetUserByID(c.Int64("id"))
+	var err error
+	var user *models.User
+	if c.IsSet("id") {
+		user, err = models.GetUserByID(c.Int64("id"))
+	} else {
+		user, err = models.GetUserByName(c.String("username"))
+	}
```
Comment (a1012112796) [inline cmd/admin.go:496]: suggest add ``user-email`` support.

Comment (zeripath) [reply cmd/admin.go:496]: OK.

**Review by techknowlogick — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by techknowlogick** [comment]
🚀
