### PR TITLE
Fix broken spans in diffs

### LINKED ISSUE #14231: Display issue in commit diff
- Gitea version (or commit ref): try.gitea.io or codeberg.org
- Operating system: Debian GNU/Linux 10 (Buster)
- Yes, @6543  could reproduce the bug at https://try.gitea.io/6543/vturn_server/commit/8d672a398f22ea465edd42a6d9de7cd2e88c7ab5

## Description
First reported on https://codeberg.org/Codeberg/Community/issues/374

> I found a display issue in this commit diff view: https://codeberg.org/eventbike/vturn_server/commit/8d672a398f22ea465edd42a6d9de7cd2e88c7ab5 (main.v, line 27)
> 
> Displayed line: 
> ```		run(dban class="o">)```
> Actual file content: 
> ```		run(db)```
> 
> HTML code at this is point:
> ```
> <td class="lines-code lines-code-new halfwidth add-code"><span class="mono wrap">
> <span class="n">run</span><span class="added-code"><span class="o">(
> </span><span class="n">d</span>b</span>
> <sp<span class="added-code">an class="o</sp<span></span>"&gt;)</td>
> ```

## Screenshots
image

Thank you a lot.

### PR DESCRIPTION
**Pull request by zeripath**
Gitea runs diff on highlighted code fragment for each line in order to provide
code highlight diffs. Unfortunately this diff algorithm is not aware that span tags
and entities are atomic and cannot be split.

The current fixup code makes some attempt to fix these broken tags however, it cannot
handle situations where a tag is split over multiple blocks.

This PR provides a more algorithmic fixup mechanism whereby spans and entities are
completely coalesced into their respective blocks.

This may result in a incompletely reduced diff but - it will definitely prevent the
broken entities and spans that are currently possible.

As a result of this fixup several inconsistencies were discovered in our testcases
and these were also fixed.

Fix #14231 

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: services/gitdiff/gitdiff_test.go [hunk 1]
```diff
@@ -61,22 +62,22 @@ func TestDiffToHTML(t *testing.T) {
 		{Type: dmp.DiffEqual, Text: "</span><span class=\"p\">)</span>"},
 	}, DiffLineDel))
 
-	assertEqual(t, "<span class=\"nx\">r</span><span class=\"p\">.</span><span class=\"nf\">WrapperRenderer</span><span class=\"p\">(</span><span class=\"nx\">w</span><span class=\"p\">,</span> <span class=\"removed-code\"><span class=\"nx\">language</span></span><span class=\"removed-code\"><span class=\"p\">,</span> <span class=\"kc\">true</span><span class=\"p\">,</span> <span class=\"nx\">attrs</span></span><span class=\"p\">,</span> <span class=\"kc\">false</span><span class=\"p\">)</span>", diffToHTML("", []dmp.Diff{
+	assertEqual(t, "<span class=\"nx\">r</span><span class=\"p\">.</span><span class=\"nf\">WrapperRenderer</span><span class=\"p\">(</span><span class=\"nx\">w</span><span class=\"p\">,</span> <span class=\"removed-code\"><span class=\"nx\">language</span><span class=\"p\">,</span> <span class=\"kc\">true</span><span class=\"p\">,</span> <span class=\"nx\">attrs</span></span><span class=\"p\">,</span> <span class=\"kc\">false</span><span class=\"p\">)</span>", diffToHTML("", []dmp.Diff{
```
Comment (zeripath) [inline services/gitdiff/gitdiff_test.go:65]: This removes an unnecessary close and reopen of a removed-code span

File: services/gitdiff/gitdiff_test.go [hunk 2]
```diff
@@ -61,22 +62,22 @@ func TestDiffToHTML(t *testing.T) {
...
 		{Type: dmp.DiffDelete, Text: "language</span><span "},
 		{Type: dmp.DiffEqual, Text: "c"},
 		{Type: dmp.DiffDelete, Text: "lass=\"p\">,</span> <span class=\"kc\">true</span><span class=\"p\">,</span> <span class=\"nx\">attrs"},
 		{Type: dmp.DiffEqual, Text: "</span><span class=\"p\">,</span> <span class=\"kc\">false</span><span class=\"p\">)</span>"},
 	}, DiffLineDel))
 
-	assertEqual(t, "<span class=\"added-code\">language</span></span><span class=\"added-code\"><span class=\"p\">,</span> <span class=\"kc\">true</span><span class=\"p\">,</span> <span class=\"nx\">attrs</span></span><span class=\"p\">,</span> <span class=\"kc\">false</span><span class=\"p\">)</span>", diffToHTML("", []dmp.Diff{
+	assertEqual(t, "<span class=\"added-code\">language</span><span class=\"p\">,</span> <span class=\"kc\">true</span><span class=\"p\">,</span> <span class=\"nx\">attrs</span></span><span class=\"p\">,</span> <span class=\"kc\">false</span><span class=\"p\">)</span>", diffToHTML("", []dmp.Diff{
```
Comment (zeripath) [inline services/gitdiff/gitdiff_test.go:73]: This removes an unnecessary close and reopen of a added-code span

File: services/gitdiff/gitdiff_test.go [hunk 3]
```diff
@@ -61,22 +62,22 @@ func TestDiffToHTML(t *testing.T) {
...
 		{Type: dmp.DiffInsert, Text: "lass=\"p\">,</span> <span class=\"kc\">true</span><span class=\"p\">,</span> <span class=\"nx\">attrs"},
 		{Type: dmp.DiffEqual, Text: "</span><span class=\"p\">,</span> <span class=\"kc\">false</span><span class=\"p\">)</span>"},
 	}, DiffLineAdd))
 
-	assertEqual(t, "<span class=\"k\">print</span><span class=\"added-code\"></span><span class=\"added-code\"><span class=\"p\">(</span></span><span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">// </span><span class=\"s2\">&#34;</span><span class=\"p\">,</span> <span class=\"n\">sys</span><span class=\"o\">.</span><span class=\"n\">argv</span><span class=\"added-code\"><span class=\"p\">)</span></span>", diffToHTML("", []dmp.Diff{
+	assertEqual(t, "<span class=\"k\">print</span><span class=\"added-code\"><span class=\"p\">(</span></span><span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">// </span><span class=\"s2\">&#34;</span><span class=\"p\">,</span> <span class=\"n\">sys</span><span class=\"o\">.</span><span class=\"n\">argv</span><span class=\"added-code\"><span class=\"p\">)</span></span>", diffToHTML("", []dmp.Diff{
```
Comment (zeripath) [inline services/gitdiff/gitdiff_test.go:80]: This removes an unnecessary close and reopen of a removed-code span

File: services/gitdiff/gitdiff_test.go [hunk 4]
```diff
@@ -85,14 +86,14 @@ func TestDiffToHTML(t *testing.T) {
 		{Type: dmp.DiffInsert, Text: "<span class=\"p\">)</span>"},
 	}, DiffLineAdd))
 
-	assertEqual(t, "sh <span class=\"added-code\">&#39;useradd -u $(stat -c &#34;%u&#34; .gitignore) jenkins</span>&#39;", diffToHTML("", []dmp.Diff{
+	assertEqual(t, "sh <span class=\"added-code\">&#39;useradd -u $(stat -c &#34;%u&#34; .gitignore) jenkins&#39;</span>", diffToHTML("", []dmp.Diff{
```
Comment (zeripath) [inline services/gitdiff/gitdiff_test.go:89]: If you look at the provided diff array and what was previously listed as expected you'll see that we actually expected something incorrect!

File: services/gitdiff/gitdiff_test.go [hunk 5]
```diff
@@ -85,14 +86,14 @@ func TestDiffToHTML(t *testing.T) {
...
 		{Type: dmp.DiffEqual, Text: "sh &#3"},
 		{Type: dmp.DiffDelete, Text: "4;useradd -u 111 jenkins&#34"},
 		{Type: dmp.DiffInsert, Text: "9;useradd -u $(stat -c &#34;%u&#34; .gitignore) jenkins&#39"},
 		{Type: dmp.DiffEqual, Text: ";"},
 	}, DiffLineAdd))
 
-	assertEqual(t, "<span class=\"x\">							&lt;h<span class=\"added-code\">4 class=</span><span class=\"added-code\">&#34;release-list-title df ac&#34;</span>&gt;</span>", diffToHTML("", []dmp.Diff{
+	assertEqual(t, "<span class=\"x\">							&lt;h<span class=\"added-code\">4 class=&#34;release-list-title df ac&#34;</span>&gt;</span>", diffToHTML("", []dmp.Diff{
```
Comment (zeripath) [inline services/gitdiff/gitdiff_test.go:96]: This removes an unnecessary close and reopen of a addded-code span

File: services/gitdiff/gitdiff_test.go [hunk 6]
```diff
@@ -462,3 +463,14 @@ func TestGetDiffRangeWithWhitespaceBehavior(t *testing.T) {
...
+func TestDiffToHTML_14231(t *testing.T) {
+	setting.Cfg = ini.Empty()
+	diffRecord := diffMatchPatch.DiffMain(highlight.Code("main.v", "		run()\n"), highlight.Code("main.v", "		run(db)\n"), true)
+	diffRecord = diffMatchPatch.DiffCleanupEfficiency(diffRecord)
+
+	expected := `		<span class="n">run</span><span class="added-code"><span class="o">(</span><span class="n">db</span></span><span class="o">)</span>`
+	output := diffToHTML("main.v", diffRecord, DiffLineAdd)
+
+	assertEqual(t, expected, output)
+}
```
Comment (zeripath) [inline services/gitdiff/gitdiff_test.go:476]: here we add a test case specific for the issue that this PR fixes.

**Review by khmarbaise — APPROVED** [review]

**Review by 6543 — APPROVED** [review]
unless we want to rewrite whole diff code ... this is the way to go :rocket:

**Comment by 6543** [comment]
:rocket:
