### PR TITLE
Alert error message if open dependencies are included in the issues that try to batch close

### LINKED ISSUE #24185: Fail to bulk close issues via datatable
### Description

image

When you try to bulk close issues from the datatable and if there is a precondition error, there is no error shown in the frontend which is quite confusing, unless you open the dev tools and look at the above shown error.

Also, I marked the dependency to be closed as well, which means with bulk closing, there is no dependency check, where the list should check if all dependent issues are also marked for closure, close them first and then close the issue that's being blocked. 

If check is hard, a workaround to show an error message will do fine for now.

Another thing that would be nice is to have a column of dependency issues. So, the user knows which ones might be causing the problem.

### Gitea Version

1.19.1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

On a internal linux server.

### Database

None

### PR DESCRIPTION
**Pull request by sillyguodong**
fix #24185 

https://user-images.githubusercontent.com/33891828/234231450-28e2668c-b31f-4e51-a8d3-9e3ead4f201e.mov

### CODE REVIEW

File: web_src/js/features/repo-issue-list.js [hunk 1]
```diff
@@ -55,6 +55,8 @@ function initRepoIssueListCheckboxes() {
       elementId
     ).then(() => {
       window.location.reload();
+    }).catch((reason) => {
+      alert(reason.responseJSON.error)
```
Comment (silverwind) [inline web_src/js/features/repo-issue-list.js]:
```suggestion
      window.alert(reason.responseJSON.error);
```

File: options/locale/locale_en-US.ini [hunk 2]
```diff
@@ -1540,6 +1540,7 @@ issues.dependency.issue_closing_blockedby = Closing this issue is blocked by the
 issues.dependency.issue_close_blocks = This issue blocks closing of the following issues
 issues.dependency.pr_close_blocks = This pull request blocks closing of the following issues
 issues.dependency.issue_close_blocked = You need to close all issues blocking this issue before you can close it.
+issues.dependency.issue_batch_close_blocked = `Cannot batch close issues that you choose, because issue (#%[1]d) still has open dependencies`
```
Comment (silverwind) [inline options/locale/locale_en-US.ini]: What's the point of the backticks?

File: web_src/js/features/repo-issue-list.js (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/features/repo-issue-list.js]: Off-topic (somewhat related): I think we need some general "toast" or "popup" or "banner" for error display.

I also need to show error message if the comment editor has something wrong. Fomantic UI has "toast" module, but I guess we don't want to use it?

GitHub could show friendly error messages:

image

Comment (silverwind) [reply web_src/js/features/repo-issue-list.js]: For toasts, maybe https://www.npmjs.com/package/toastify-js.

Comment (silverwind) [reply web_src/js/features/repo-issue-list.js]: OTOH, it does not allow SVG close icon without hacks:

https://github.com/apvarun/toastify-js/issues/23

**Review by silverwind — APPROVED** [review]

File: options/locale/locale_en-US.ini [hunk 3]
```diff
@@ -1540,6 +1540,7 @@ issues.dependency.issue_closing_blockedby = Closing this issue is blocked by the
 issues.dependency.issue_close_blocks = This issue blocks closing of the following issues
 issues.dependency.pr_close_blocks = This pull request blocks closing of the following issues
 issues.dependency.issue_close_blocked = You need to close all issues blocking this issue before you can close it.
+issues.dependency.issue_batch_close_blocked = Cannot batch close issues that you choose, because issue (#%[1]d) still has open dependencies
```
Comment (wxiaoguang) [inline options/locale/locale_en-US.ini]: Actually, we can't do so, it breaks the crowdin, the part after `#` will be treated as comment.

And it seems that the parentheses are not necessary.


```suggestion
issues.dependency.issue_batch_close_blocked = "Cannot batch close issues that you choose, because issue #%d still has open dependencies"
```


ps: the backticks were also not right, see my comments: https://github.com/go-gitea/gitea/blob/4d5c803f8b71ccf3182d89584196783e2338e365/modules/translation/i18n/i18n_test.go#L118-L130

Comment (silverwind) [reply options/locale/locale_en-US.ini]: Is it because of ini format?

Comment (wxiaoguang) [reply options/locale/locale_en-US.ini]: > Is it because of ini format?

Yes, the `#` needs to be quoted (at the moment, only double-quote does the work)

Comment (silverwind) [reply options/locale/locale_en-US.ini]: Okay, maybe we should just refactor to always quote all values for consistency when there is no drawback. Values that contain `"` might be one. What about backtick quote everywhere?

Comment (wxiaoguang) [reply options/locale/locale_en-US.ini]: But there is another case: ` key = there is quote "hello" inside `, or  ` key = "there is quote \"hello\" inside" `

I think people may like the first style.

IMO we need our ini package to parse and lint, and that is the first step for  [Proposal] Use ICU message for i18n & l10n #23863

**Review by wxiaoguang — APPROVED** [review]

File: options/locale/locale_en-US.ini (hunk 3 above)
Comment (wxiaoguang) [reply options/locale/locale_en-US.ini]: > What about backtick quote everywhere?

The backtick could only be parsed by the old ini package, it's not supported by Crowdin, that's why many translations are broken (some backticks are missing, then Gitea can't parse them correctly)

Comment (silverwind) [reply options/locale/locale_en-US.ini]: Hmm, could we for example convert to YAML? Or does Crowdin not support it?

Comment (wxiaoguang) [reply options/locale/locale_en-US.ini]: I am not crowdin admin, and I am not sure whether it would cause whole re-translating.

File: web_src/js/features/repo-issue-list.js (hunk 1 above)
Comment (silverwind) [reply web_src/js/features/repo-issue-list.js]: See https://github.com/go-gitea/gitea/issues/24353
