### PR TITLE
Ensure that git daemon export ok is created for mirrors

### LINKED ISSUE #17241: Mirror repo: no such file or directory <path>/git-daemon-export-ok
### Gitea Version

1.15.3

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.3

### How are you running Gitea?

I'm running official build: gitea-1.15.3-linux-amd64

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

When I start a new mirror I see every time this

```
2021/10/06 20:26:58 models/repo.go:1159:CreateRepository() [E] Failed to create /var/lib/gitea/repositories/m66b/xprivacylua.git/git-daemon-export-ok: open /var/lib/gitea/repositories/m66b/xprivacylua.git/git-daemon-export-ok: no such file or directory
        /source/models/repo.go:1159 (0x143dc90)
        /source/modules/repository/create.go:58 (0x1583304)
        /source/models/context.go:53 (0x139cd04)
        /source/modules/repository/create.go:57 (0x156d349)
        /source/modules/task/task.go:107 (0x202a73a)
        /source/modules/task/task.go:61 (0x202a177)
        /source/routers/web/repo/migrate.go:235 (0x20cb3b7)
        /source/modules/web/route.go:64 (0x202f83b)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/vendor/github.com/go-chi/chi/mux.go:436 (0x16f49ea)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/modules/web/route.go:103 (0x202ff16)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/modules/web/route.go:103 (0x202ff16)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/modules/web/route.go:103 (0x202ff16)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/vendor/github.com/go-chi/chi/middleware/get_head.go:37 (0x20531a1)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/modules/web/route.go:103 (0x202ff16)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/modules/context/context.go:776 (0x17156e9)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/vendor/github.com/go-chi/chi/mux.go:70 (0x16f254a)
        /source/vendor/github.com/go-chi/chi/mux.go:311 (0x16f893b)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/vendor/github.com/go-chi/chi/mux.go:436 (0x16f49ea)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/routers/web/base.go:186 (0x2265b50)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/vendor/gitea.com/go-chi/session/session.go:256 (0x14ff88e)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/modules/public/public.go:42 (0x167640e)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/vendor/github.com/go-chi/chi/mux.go:70 (0x16f254a)
        /source/vendor/github.com/go-chi/chi/mux.go:311 (0x16f893b)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/vendor/github.com/go-chi/chi/mux.go:436 (0x16f49ea)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/routers/common/middleware.go:72 (0x2057c7d)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/routers/common/logger.go:23 (0x2056ebb)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/vendor/github.com/go-chi/chi/middleware/strip.go:30 (0x2053aa7)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/vendor/github.com/chi-middleware/proxy/middleware.go:37 (0x204f10e)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/routers/common/middleware.go:25 (0x20577bc)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /source/vendor/github.com/go-chi/chi/mux.go:87 (0x16f22d0)
        /source/modules/web/route.go:318 (0x202ed73)
        /source/vendor/github.com/gorilla/context/context.go:141 (0x120bbb3)
        /usr/local/go/src/net/http/server.go:2049 (0x7bd183)
        /usr/local/go/src/net/http/server.go:2867 (0x7c0742)
        /usr/local/go/src/net/http/server.go:1932 (0x7bbc6c)
        /usr/local/go/src/runtime/asm_amd64.s:1371 (0x47aa40)
```

stacktrace in the gitea.log.

```
$ zgrep git-daemon-export-ok gitea.log* | wc -l
712
```

The mirror process is working.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by zeripath**
There is an issue with #16508 where it appears that create repo requires that the
repo does not exist. This causes #17241 where an error is reported because of this.

This PR fixes this and also runs update-server-info for mirrors and generated repos.

Fix #17241

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by noerw — COMMENTED** [review]
LGTM, though the tests show a change in status codes from 201 to 200, though I can't see why the diff would make that happen.. 🤔

File: models/repo.go [hunk 1]
```diff
@@ -1169,6 +1159,31 @@ func CreateRepository(ctx context.Context, doer, u *User, repo *Repository, over
 	return nil
 }
 
+// CheckDaemonExportOK creates/removes git-daemon-export-ok for git-daemon...
+func (repo *Repository) CheckDaemonExportOK() error {
+	// Create/Remove git-daemon-export-ok for git-daemon...
+	daemonExportFile := path.Join(repo.RepoPath(), `git-daemon-export-ok`)
+	isExist, err := util.IsExist(daemonExportFile)
+	isPublic := !repo.IsPrivate && repo.Owner.Visibility == api.VisibleTypePublic
+	if err != nil {
```
Comment (lafriks) [inline models/repo.go:1173]: small readability nit - it would be more readable if this check would be right after where err is returned (before isPublic)

Comment (zeripath) [reply models/repo.go:1173]: done

**Comment by zeripath** [comment]
> LGTM, though the tests show a change in status codes from 201 to 200, though I can't see why the diff would make that happen.. thinking

Yeah I don't get how this could be related at all. I've been assuming it's a temporary issue but I'll see if it's still ongoing.

File: modules/repository/repo.go [hunk 2]
```diff
@@ -96,6 +96,25 @@ func MigrateRepositoryGitData(ctx context.Context, u *models.User, repo *models.
 		}
 	}
 
+	if repo.OwnerID == u.ID {
+		repo.Owner = u
+	}
+
+	if err = repo.GetOwner(); err != nil {
```
Comment (noerw) [inline modules/repository/repo.go]: wouldn't be cleaner to do this inside `CheckDaemonExportOK()` right?

Comment (zeripath) [reply modules/repository/repo.go]: That makes CheckDaemonExportOK a db dependent function.

Comment (zeripath) [reply modules/repository/repo.go]: We'd need something like: 

```patch
diff --git a/models/db/context.go b/models/db/context.go
index 0037bb198..62b77bc72 100644
--- a/models/db/context.go
+++ b/models/db/context.go
@@ -31,6 +31,14 @@ type Context struct {
 	e Engine
 }
 
+// WithEngine returns a db.Context from a context.Context and db.Engine
+func WithEngine(ctx context.Context, e Engine) *Context {
+	return &Context{
+		Context: ctx,
+		e:       e,
+	}
+}
+
 // Engine returns db engine
 func (ctx *Context) Engine() Engine {
 	return ctx.e
diff --git a/models/repo.go b/models/repo.go
index 2eba0855d..25b1e6520 100644
--- a/models/repo.go
+++ b/models/repo.go
@@ -1160,7 +1160,12 @@ func CreateRepository(ctx context.Context, doer, u *User, repo *Repository, over
 }
 
 // CheckDaemonExportOK creates/removes git-daemon-export-ok for git-daemon...
-func (repo *Repository) CheckDaemonExportOK() error {
+func (repo *Repository) CheckDaemonExportOK(ctx context.Context) error {
+	e := db.GetEngine(ctx)
+	if err := repo.getOwner(e); err != nil {
+		return err
+	}
+
 	// Create/Remove git-daemon-export-ok for git-daemon...
 	daemonExportFile := path.Join(repo.RepoPath(), `git-daemon-export-ok`)
 
@@ -1335,7 +1340,7 @@ func updateRepository(e db.Engine, repo *Repository, visibilityChanged bool) (er
 		}
 
 		// Create/Remove git-daemon-export-ok for git-daemon...
-		if err := repo.CheckDaemonExportOK(); err != nil {
+		if err := repo.CheckDaemonExportOK(db.WithEngine(db.DefaultContext, e)); err != nil {
 			return err
 		}
 
diff --git a/modules/repository/adopt.go b/modules/repository/adopt.go
index 07b8d17bc..21477ab7d 100644
--- a/modules/repository/adopt.go
+++ b/modules/repository/adopt.go
@@ -68,7 +68,7 @@ func AdoptRepository(doer, u *models.User, opts models.CreateRepoOptions) (*mode
 		if err := adoptRepository(ctx, repoPath, doer, repo, opts); err != nil {
 			return fmt.Errorf("createDelegateHooks: %v", err)
 		}
-		if err := repo.CheckDaemonExportOK(); err != nil {
+		if err := repo.CheckDaemonExportOK(ctx); err != nil {
 			return fmt.Errorf("checkDaemonExportOK: %v", err)
 		}
 
diff --git a/modules/repository/create.go b/modules/repository/create.go
index 4c1851255..64d92eeb2 100644
--- a/modules/repository/create.go
+++ b/modules/repository/create.go
@@ -105,11 +105,11 @@ func CreateRepository(doer, u *models.User, opts models.CreateRepoOptions) (*mod
 			}
 		}
 
-		if err := repo.CheckDaemonExportOK(); err != nil {
+		if err := repo.CheckDaemonExportOK(ctx); err != nil {
 			return fmt.Errorf("checkDaemonExportOK: %v", err)
 		}
 
-		if stdout, err := git.NewCommand("update-server-info").
+		if stdout, err := git.NewCommandContext(ctx, "update-server-info").
 			SetDescription(fmt.Sprintf("CreateRepository(git update-server-info): %s", repoPath)).
 			RunInDir(repoPath); err != nil {
 			log.Error("CreateRepository(git update-server-info) in %v: Stdout: %s\nError: %v", repo, stdout, err)
diff --git a/modules/repository/fork.go b/modules/repository/fork.go
index 6bd0ea3f8..df1dccc59 100644
--- a/modules/repository/fork.go
+++ b/modules/repository/fork.go
@@ -97,7 +97,7 @@ func ForkRepository(doer, owner *models.User, opts models.ForkRepoOptions) (_ *m
 		needsRollback = true
 
 		repoPath := models.RepoPath(owner.Name, repo.Name)
-		if stdout, err := git.NewCommand(
+		if stdout, err := git.NewCommandContext(ctx,
 			"clone", "--bare", oldRepoPath, repoPath).
 			SetDescription(fmt.Sprintf("ForkRepository(git clone): %s to %s", opts.BaseRepo.FullName(), repo.FullName())).
 			RunInDirTimeout(10*time.Minute, ""); err != nil {
@@ -105,11 +105,11 @@ func ForkRepository(doer, owner *models.User, opts models.ForkRepoOptions) (_ *m
 			return fmt.Errorf("git clone: %v", err)
 		}
 
-		if err := repo.CheckDaemonExportOK(); err != nil {
+		if err := repo.CheckDaemonExportOK(ctx); err != nil {
 			return fmt.Errorf("checkDaemonExportOK: %v", err)
 		}
 
-		if stdout, err := git.NewCommand("update-server-info").
+		if stdout, err := git.NewCommandContext(ctx, "update-server-info").
 			SetDescription(fmt.Sprintf("ForkRepository(git update-server-info): %s", repo.FullName())).
 			RunInDir(repoPath); err != nil {
 			log.Error("Fork Repository (git update-server-info) failed for %v:\nStdout: %s\nError: %v", repo, stdout, err)
diff --git a/modules/repository/generate.go b/modules/repository/generate.go
index 47bc70734..f6b76b14a 100644
--- a/modules/repository/generate.go
+++ b/modules/repository/generate.go
@@ -275,11 +275,11 @@ func GenerateRepository(ctx context.Context, doer, owner *models.User, templateR
 		return generateRepo, err
 	}
 
-	if err = generateRepo.CheckDaemonExportOK(); err != nil {
+	if err = generateRepo.CheckDaemonExportOK(ctx); err != nil {
 		return generateRepo, fmt.Errorf("checkDaemonExportOK: %v", err)
 	}
 
-	if stdout, err := git.NewCommand("update-server-info").
+	if stdout, err := git.NewCommandContext(ctx, "update-server-info").
 		SetDescription(fmt.Sprintf("GenerateRepository(git update-server-info): %s", repoPath)).
 		RunInDir(repoPath); err != nil {
 		log.Error("GenerateRepository(git update-server-info) in %v: Stdout: %s\nError: %v", generateRepo, stdout, err)
diff --git a/modules/repository/repo.go b/modules/repository/repo.go
index 6eafe9763..05306218d 100644
--- a/modules/repository/repo.go
+++ b/modules/repository/repo.go
@@ -100,15 +100,11 @@ func MigrateRepositoryGitData(ctx context.Context, u *models.User, repo *models.
 		repo.Owner = u
 	}
 
-	if err = repo.GetOwner(); err != nil {
-		return repo, fmt.Errorf("unable to get owner[%d] for repo [%d]. Error: %v", repo.OwnerID, repo.ID, err)
-	}
-
-	if err = repo.CheckDaemonExportOK(); err != nil {
+	if err = repo.CheckDaemonExportOK(ctx); err != nil {
 		return repo, fmt.Errorf("checkDaemonExportOK: %v", err)
 	}
 
-	if stdout, err := git.NewCommand("update-server-info").
+	if stdout, err := git.NewCommandContext(ctx, "update-server-info").
 		SetDescription(fmt.Sprintf("MigrateRepositoryGitData(git update-server-info): %s", repoPath)).
 		RunInDir(repoPath); err != nil {
 		log.Error("MigrateRepositoryGitData(git update-server-info) in %v: Stdout: %s\nError: %v", repo, stdout, err)
```

Comment (noerw) [reply modules/repository/repo.go]: ah, good point. not an easy tradeoff

**Review by noerw — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
I realy do like how `CheckDaemonExportOK(ctx context.Context)` is implemented!

I think that's a nice idear to dynamicaly have one func who can be used within or outside a session
