### PR TITLE
Fixed race condition when deleting documents by repoId in ElasticSearch

### LINKED ISSUE #32184: Race condition when running ES delete_by_query
### Description

When running the unit test associated with code search (file modules/indexer/code/indexer_test.go), I ran into the issue in the screenshot below.

image

As explained [here](https://discuss.elastic.co/t/elasticsearch-delete-by-query-409-version-conflict/174150), this is due to a racing condition where ES uses an outdated index while looking for the documents to delete. The safe approach is to ask ES to refresh the index before.

I wrote a PR that changes the behavior when trying to delete the documents of a repo. If the deletion results in a conflict, Gitea will refresh the index and retry.

P.S. ES is running inside a docker container spun by the command below:

```
docker run --rm --memory="4g" -p 127.0.0.1:9200:9200 -p 127.0.0.1:9300:9300 -e "discovery.type=single-node" -v "$(pwd)/data/elasticsearch:/usr/share/elasticsearch/data" docker.elastic.co/elasticsearch/elasticsearch:7.16.3
```

### Gitea Version

0b1b4030e66b1312fc9c0270f128bcf368f14178

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

I ran into this issue while running the tests inside VSCode

### Database

None

### PR DESCRIPTION
**Pull request by bsofiato**
Resolves #32184

### CODE REVIEW

File: modules/indexer/code/elasticsearch/elasticsearch.go [hunk 1]
```diff
@@ -197,11 +198,37 @@ func (b *Indexer) Index(ctx context.Context, repo *repo_model.Repository, sha st
...
+
+	return nil
+}
+
+// Delete entries by repoId
+func (b *Indexer) doDelete(ctx context.Context, repoID int64) error {
 	_, err := b.inner.Client.DeleteByQuery(b.inner.VersionedIndexName()).
 		Query(elastic.NewTermsQuery("repo_id", repoID)).
 		Do(ctx)
+
```
Comment (lunny) [inline modules/indexer/code/elasticsearch/elasticsearch.go]: unnecessary change.

**Review by lunny — APPROVED** [review]

**Review by denyskon — APPROVED** [review]

File: modules/indexer/code/elasticsearch/elasticsearch.go (hunk 1 above)
Comment (techknowlogick) [reply modules/indexer/code/elasticsearch/elasticsearch.go]:
```suggestion
```
