### PR TITLE
Fix the wrong push commits in the pull request when force push

### LINKED ISSUE #36905: Incorrect commit count in timeline after force-push
### Description

Related to https://github.com/go-gitea/gitea/pull/36653. Steps should be these, untested:

- Create 1 commit, push
- Create 2nd commit, push
- Amend 2nd commit, force-push
- UI should show the 2 commits that exist on the branch but only shows 1, the count in header is correct already.

Image

### Gitea Version

1.25.5

### PR DESCRIPTION
**Pull request by lunny**
Fix #36905

The changes focus on force-push PR timeline handling and commit range calculation:
- Reworked pull-request push comment creation to use a new `gitrepo.GetCommitIDsBetweenReverse` helper, with special handling for force pushes (merge-base based range, tolerate missing/invalid old commits, and keep force-push timeline entries).
- Added `Comment.GetPushActionContent` to parse push comment payloads and used it to delete only non-force-push push comments during force pushes.
- Removed the old `Repository.CommitsBetweenNotBase` helper from `modules/git/repo_commit.go` in favor of the new commit ID range helper.
- Added tests for `GetCommitIDsBetweenReverse` (normal range, `notRef` filtering, fallback branch usage) and expanded pull comment tests to cover force-push edge cases.

image

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Don't make it depends on "db"

Don't use `func TestMain(m *testing.M) { unittest.MainTest(m) }`


Why the simple git operation should depend on db?

**Comment by silverwind** [comment]
In essence the fix should be pretty simple: The commit timeline (and tab count) should always show the actual commits present in the branch, ordered into the timeline with their authoring date. Force-push can rewrite the entire commit timeline, so must invalidate all commits in the timeline.

Could just make it completely git-based and skip storing in the DB entirely, but do whatever perform better, but a DB cache does bring the invalidation complexity.

**Review by silverwind — COMMENTED** [review]
Review by Claude on behalf of @silverwind

File: services/git/compare.go [hunk 1]
```diff
@@ -42,6 +42,38 @@ func (ci *CompareInfo) DirectComparison() bool {
 	return ci.CompareSeparator == ".."
 }
 
+// GetCompareCommitIDsWithMergeBase get commit IDs from repo in between oldCommitID and newCommitID
+// Commit on baseBranch will skip
+func GetCompareCommitIDsWithMergeBase(ctx context.Context, repo *repo_model.Repository, oldCommitID, newCommitID string) (commitIDs []string, err error) {
+	gitRepo, closer, err := gitrepo.RepositoryFromContextOrOpen(ctx, repo)
```
Comment (silverwind) [inline services/git/compare.go]: The parameter is named `oldCommitID` but the caller passes `pr.BaseBranch` (a branch name). The function works because `gitrepo.MergeBase` resolves refs, but the name is misleading — consider renaming to `baseRef` or `baseBranch`.

File: services/git/compare.go [hunk 2]
```diff
@@ -42,6 +42,38 @@ func (ci *CompareInfo) DirectComparison() bool {
...
+	if err != nil {
+		return nil, err
+	}
+	defer closer.Close()
+
+	newCommit, err := gitRepo.GetCommit(newCommitID)
+	if err != nil {
```
Comment (silverwind) [inline services/git/compare.go]: `newCommit` is fetched via `GetCommit` but only `newCommit.ID.String()` is used, which is just `newCommitID` again. This call could be removed and `newCommitID` used directly in `ShowPrettyFormatLogToList` — the subsequent calls will fail anyway if the commit doesn't exist.

**Review by silverwind — COMMENTED** [review]
Review by Claude on behalf of @silverwind

File: models/issues/comment.go [hunk 3]
```diff
@@ -343,6 +345,17 @@ type PushActionContent struct {
...
 
+func (c *Comment) GetPushActionContent(ctx context.Context) (*PushActionContent, error) {
+	if c.Type != CommentTypePullRequestPush {
+		return nil, errors.New("not a pull request push comment")
+	}
+	var data PushActionContent
+	if err := json.Unmarshal([]byte(c.Content), &data); err != nil {
+		return nil, err
+	}
+	return &data, nil
```
[the remark this answers is not in the document]
Comment (lunny) [reply models/issues/comment.go]: 1e0efd2f86

**Review by Zettat123 — APPROVED** [review]

**Comment by bircni** [comment]
Am I allowed to approve? If so I would

**Comment by lunny** [comment]
> Am I allowed to approve? If so I would

Yes, you’re welcome to review any PRs that interest you.

File: modules/gitrepo/compare.go [hunk 4]
```diff
@@ -42,3 +42,22 @@ func GetDivergingCommits(ctx context.Context, repo Repository, baseBranch, targe
...
+// GetCommitIDsBetween returns the commit IDs between startRef and endRef, if notRef is not empty,
+// it will exclude commits reachable from notRef.
+func GetCommitIDsBetween(ctx context.Context, repo Repository, startRef, endRef, notRef string) ([]string, error) {
+	baseCmd := gitcmd.NewCommand("rev-list", "--reverse")
+	if notRef != "" {
+		baseCmd.AddOptionValues("--not", notRef)
+	}
+	stdout, _, err := RunCmdString(ctx, repo, baseCmd.AddDynamicArguments(startRef+".."+endRef))
+	if err != nil && strings.Contains(err.Error(), "no merge base") {
+		stdout, _, err = RunCmdString(ctx, repo, baseCmd.AddDynamicArguments(startRef, endRef))
```
Comment (bircni) [inline modules/gitrepo/compare.go]: If I understand that correct...
First call — MUTATES baseCmd, appending "startRef..endRef" to its args in line 53
The fallback mutates the already-mutated baseCmd again if the command failed
resulting in: `baseCmd.args` being `["rev-list", "--reverse", "startRef..endRef", "startRef", "endRef"]`

**Review by bircni — CHANGES_REQUESTED** [review]

File: modules/gitrepo/compare.go (hunk 4 above)
Comment (lunny) [reply modules/gitrepo/compare.go]: da4811dd75

Comment (bircni) [reply modules/gitrepo/compare.go]: Somehow i cannot resolve it but yes thats good!

**Review by bircni — APPROVED** [review]

File: modules/gitrepo/compare.go [hunk 5]
```diff
@@ -42,3 +42,26 @@ func GetDivergingCommits(ctx context.Context, repo Repository, baseBranch, targe
...
+	genBaseCmd := func() *gitcmd.Command {
+		baseCmd := gitcmd.NewCommand("rev-list", "--reverse")
+		if notRef != "" {
+			baseCmd.AddOptionValues("--not", notRef)
+		}
+		return baseCmd
+	}
+
+	stdout, _, err := RunCmdString(ctx, repo, genBaseCmd().AddDynamicArguments(startRef+".."+endRef))
+	if err != nil && strings.Contains(err.Error(), "no merge base") {
```
Comment (wxiaoguang) [inline modules/gitrepo/compare.go]: https://github.com/go-gitea/gitea/blob/main/modules/git/gitcmd/error.go

image

image

Comment (lunny) [reply modules/gitrepo/compare.go]: 45694fb489

File: modules/gitrepo/compare.go [hunk 6]
```diff
@@ -42,3 +42,26 @@ func GetDivergingCommits(ctx context.Context, repo Repository, baseBranch, targe
...
+	genBaseCmd := func() *gitcmd.Command {
+		baseCmd := gitcmd.NewCommand("rev-list", "--reverse")
+		if notRef != "" {
+			baseCmd.AddOptionValues("--not", notRef)
+		}
+		return baseCmd
+	}
+
+	stdout, _, err := RunCmdString(ctx, repo, genBaseCmd().AddDynamicArguments(startRef+".."+endRef))
+	if err != nil && strings.Contains(err.Stderr(), "no merge base") {
```
Comment (wxiaoguang) [inline modules/gitrepo/compare.go:60]:
```suggestion
	// example git error message: fatal: origin/main...HEAD: no merge base
	if err != nil && strings.Contains(err.Stderr(), "no merge base") {
```

File: modules/gitrepo/compare_test.go [hunk 7]
```diff
@@ -40,3 +40,59 @@ func TestRepoGetDivergingCommits(t *testing.T) {
...
+
+	commitIDs, err := GetCommitIDsBetween(t.Context(), repo,
+		"8d92fc957a4d7cfd98bc375f0b7bb189a0d6c9f2",
+		"ce064814f4a0d337b333e646ece456cd39fab612",
+		notRef,
+	)
+
+	assert.NoError(t, err)
+	// Ensure that the commit specified by notRef is not present in the result.
+	assert.NotContains(t, commitIDs, notRef)
```
Comment (wxiaoguang) [inline modules/gitrepo/compare_test.go]: The test is not right. It can always succeed even if the repo changes or commit ID range changes.

You need to first check when no "notRef", the commit ID exsits, then use "notRef", then it doesn't exist.

File: modules/gitrepo/compare_test.go [hunk 8]
```diff
@@ -40,3 +40,59 @@ func TestRepoGetDivergingCommits(t *testing.T) {
...
+
+	// Call GetCommitIDsBetween using branch names instead of raw commit IDs.
+	// This exercises an alternative call pattern which is intended to cover
+	// the fallback handling in the underlying implementation when computing
+	// the commit range.
+	commitIDs, err := GetCommitIDsBetween(t.Context(), repo,
+		"master",
+		"branch2",
+		"",
+	)
```
Comment (wxiaoguang) [inline modules/gitrepo/compare_test.go]: I don't see it fails and fallbacks.

Do you really know what you are doing, or have you really tested your code?


image

File: services/pull/comment.go [hunk 9]
```diff
@@ -62,31 +28,64 @@ func CreatePushPullComment(ctx context.Context, pusher *user_model.User, pr *iss
...
+			data.CommitIDs, err = gitrepo.GetCommitIDsBetween(ctx, pr.BaseRepo, mergeBase, newCommitID, notRef)
+			if err != nil {
+				// For force-push events, failures resolving the base ref/head commit or computing
+				// the merge-base should not prevent deleting stale push comments or creating the
+				// force-push timeline entry.
+				log.Error("GetCommitIDsBetween %q..%q (not %q) failed: %v", mergeBase, newCommitID, notRef, err)
+			}
+		}
+	} else {
+		data.CommitIDs, err = gitrepo.GetCommitIDsBetween(ctx, pr.BaseRepo, oldCommitID, newCommitID, pr.BaseBranch)
```
Comment (wxiaoguang) [inline services/pull/comment.go]: Is it a proper name? How can reader know that the result is "reversed"? Everyone would assume that the result is in default order.

**Review by wxiaoguang — DISMISSED** [review]
Tests don't seem right

File: services/pull/comment.go (hunk 9 above)
Comment (lunny) [reply services/pull/comment.go]: 9f5bfae054

File: modules/gitrepo/compare_test.go (hunk 8 above)
Comment (lunny) [reply modules/gitrepo/compare_test.go]: 9f5bfae054

File: modules/gitrepo/compare_test.go (hunk 7 above)
Comment (lunny) [reply modules/gitrepo/compare_test.go]: 9f5bfae054

**Comment by lunny** [comment]
> Tests don't seem right

9f5bfae054

**Comment by wxiaoguang** [comment]
> > Tests don't seem right
> 
> [9f5bfae](https://github.com/go-gitea/gitea/commit/9f5bfae054024639305ca1f8427d97482d14a114)

Well, your AI just removes the test coverage that it is unable to handle and tells you that "Hey, I have fixed".

TBH, I don't need to care about whether the tests have good coverage. So, it's up to you.

image

File: modules/git/repo_commit.go [hunk 10]
```diff
@@ -362,39 +362,6 @@ func (repo *Repository) CommitsBetweenLimit(last, before *Commit, limit, skip in
...
-			RunStdBytes(repo.Ctx)
-	} else {
-		stdout, _, err = gitcmd.NewCommand("rev-list").
-			AddDynamicArguments(before.ID.String()+".."+last.ID.String()).
-			AddOptionValues("--not", baseBranch).
-			WithDir(repo.Path).
-			RunStdBytes(repo.Ctx)
-		if err != nil && strings.Contains(err.Error(), "no merge base") {
-			// future versions of git >= 2.28 are likely to return an error if before and last have become unrelated.
-			// previously it would return the results of git rev-list before last so let's try that...
```
Comment (wxiaoguang) [inline modules/git/repo_commit.go:384]: Is it a useful comment which is removed by your AI?

And why there are so many duplicate comments?

> Git 2.28 no longer permits diff with ... on unrelated branches (#12364)


image

Comment (lunny) [reply modules/git/repo_commit.go:384]: 6f07441

**Review by wxiaoguang — DISMISSED** [review]
(test "request change" for "Fix #36525: dismiss prior approval on review re-request #36938")

**Comment by silverwind** [comment]
@lunny can you describe high-level how it works now? Does it always represent the commits like they are on branch, exactly?

**Comment by lunny** [comment]
> @lunny can you describe high-level how it works now? Does it always represent the commits like they are on branch, exactly?

For a non-force-push:

- We only need to create commit comments for commits in oldcommit..newcommit.

For a force-push:
	
1.	Delete all previously added non-force-push commit comments.
2.	Add commit comments for commits in basebranch..newcommit.
3.	Add a new force-push commit comment.

This matches GitHub’s behavior. In other words, the number of non-force-push commit comments should always match the number of commits shown in the PR Commits tab.

**Comment by silverwind** [comment]
Ok, seems good. And the timestamp of these commits in the timeline will be the author timestamp of the commits, right? E.g. not the time of force-push. That's how GitHub does it, so for example one can force-push old commits and they appear correctly ordered in the timeline with other comments and such.

**Comment by lunny** [comment]
> Ok, seems good. And the timestamp of these commits in the timeline will be the author timestamp of the commits, right? E.g. not the time of force-push. That's how GitHub does it, so for example one can force-push old commits and they appear correctly ordered in the timeline with other comments and such.

Not yet. I’ll check the timestamps. Should the commit date be used as the comment’s insertion time?

**Comment by wxiaoguang** [comment]
No, I don't think it should do more with "commit time" in this PR.

For example:

doer push commit with commit time 2020. (on 2024-01-01)
doer push commit with commit time  2019. (on 2024-01-02)
doer push commit with commit time  2021. (on 2024-01-03)


The display order in UI should be 3 comments (not commits):

doer force pushed on 2024-01-01
doer force pushed on 2024-01-02
doer force pushed on 2024-01-03

**Comment by silverwind** [comment]
1. Commits and force-push are separate timeline entries. I think on GitHub only the last force-push event shows, e.g. it deletes all previous ones.
2. On GitHub it's definitely possible to "back-date" a commit, for example:

- commit (day1)
- comment (day3)

If I push a commit authored on day2, it will appear before day3 comment, so only author date matters, not push date. So in summary:

- Commits in timeline is a strict representation of git content with commit author dates.
- Force-push is a separate timeline-entry and only the last shows.

**Comment by silverwind** [comment]
Also one interesting tidbit about is that GitHub apparently uses commit vs. author date in different contexts. For the timeline it seems to use commit date, if Google AI can be trusted, that is:

image

**Comment by wxiaoguang** [comment]
There is no sense to blindly follow GitHub or AI.

The only questions you need to answer are: whether the design is right, whether it shows useful information to end users, whether it causes surprises to end users.

**Comment by lunny** [comment]
I think both can be accepted. Let me clarify the different between the PR and Github's implementation.

Github's timeline.

- Commit1 comment committed day1 but force pushed day 3
- User comment posted day2
- Force Push hint comment pushed day 3

Meanwhile, the timeline in this PR

- User comment posted day2
- Commit1 comment committed day1 but force pushed day 3
- Force Push hint comment pushed day 3

Github use commit dates for the commit comment and this PR use push dates for the commit comment.

If only part of commits are rewritten, it seems Github's implementation sounds more reasonable. Not all previous commit comments should be deleted.

**Comment by silverwind** [comment]
> If only part of commits are rewritten, it seems Github's implementation sounds more reasonable. Not all previous commit comments should be deleted.

Imho, on every force-push, recalculate the whole set of commit messages in the timeline using the commit dates. That way they will still be ordered correctly in the timeline if for example only some of the commits were actually rewritten.

I won't block on this time ordering topic because it's mostly cosmetic. The important part is that all commits on the branch are visible in the timeline, at all times.

**Comment by lunny** [comment]
> > If only part of commits are rewritten, it seems Github's implementation sounds more reasonable. Not all previous commit comments should be deleted.
> 
> Imho, on every force-push, recalculate the whole set of commit messages in the timeline using the commit dates. That way they will still be ordered correctly in the timeline if for example only some of the commits were actually rewritten.
> 
> I won't block on this time ordering topic because it's mostly cosmetic. The important part is that all commits on the branch are visible in the timeline, at all times.

It's ready to review again. I adjust the deletion of previous commit comments so that the old commit comments will be kept if it will be included in the new commits list. I think it should be the same behavior as Github now.

File: services/pull/comment.go [hunk 11]
```diff
@@ -62,31 +30,91 @@ func CreatePushPullComment(ctx context.Context, pusher *user_model.User, pr *iss
...
-	if err != nil {
-		// For force-push events, a missing/unreachable old commit should not prevent
-		// deleting stale push comments or creating the force-push timeline entry.
-		if !isForcePush {
+	commitIDMaps := make(container.Set[string])
+	if isForcePush {
+		// if it's a force push, we need to get the whole pull request commits
+		mergeBase, err := gitrepo.MergeBase(ctx, pr.BaseRepo, pr.BaseBranch, newCommitID)
+		if err != nil {
+			// For force-push events, failures resolving the base ref/head commit or computing the merge-base should not prevent deleting stale push comments or creating the force-push timeline entry.
```
Comment (silverwind) [inline services/pull/comment.go]: This uses `GetCommitIDsBetweenReversed(oldCommitID, newCommitID)` which is just `rev-list --reverse old..new`. The old code used `CommitsBetweenNotBase` with `--not baseBranch` to exclude base branch commits. Without that exclusion, if the head branch rebases onto new base commits, those base commits will incorrectly appear in push timeline entries.

This is a regression from both old Gitea behavior and GitHub behavior.

**Review by silverwind — COMMENTED** [review]
### Detailed review comparing against GitHub behavior

**Core idea**: Preserving push comment history on force-push instead of deleting everything is sound and aligns better with GitHub. However there are several concerns:

#### 1. Non-force-push path lost `--not baseBranch` filtering (regression)

The old code used `CommitsBetweenNotBase` which ran `git rev-list old..new --not baseBranch`. The new `GetCommitIDsBetweenReversed` runs `git rev-list --reverse old..new` without `--not baseBranch`. If the head branch merges or rebases onto new base branch commits, those base commits will incorrectly appear in the "pushed N commits" timeline entry. This is a regression from both old Gitea behavior and GitHub behavior (GitHub also excludes base-only commits from push events).

#### 2. Behavioral divergence from GitHub on force-push

GitHub's force-push behavior:
- **Never modifies or deletes old push comments** — they stay as historical artifacts (old commit links may 404 after GC, which is acceptable)
- Adds a single "force-pushed from `abc` to `def`" timeline event
- Does NOT create a new regular push comment alongside the force-push event

This PR's behavior:
- Filters/updates old non-force-push comments (removes commits no longer in the branch)
- Preserves old force-push comments
- Creates a NEW regular push comment with commits not covered by old comments
- Creates a NEW force-push comment

The complexity of filtering old comments to remove stale commit IDs and redistribute them is significantly more complex than GitHub's simple approach. More surface area for bugs and edge cases (e.g., what if JSON parsing fails mid-loop leaving partial state?).

**A simpler approach matching GitHub**: on force-push, just keep all old push comments untouched and add the force-push timeline event. Old commit links may become dead, which is acceptable (GitHub does this too).

#### 3. `GetCommitIDsBetweenReversed` "no merge base" fallback is questionable

The fallback runs `rev-list --reverse startRef endRef` (space-separated). With space separation, `rev-list` lists ALL commits reachable from EITHER ref (union), which could return the entire repository history. The old code had the same fallback but applied `--not baseBranch` to limit results. This version has no such protection.

#### 4. Tests don't cover the interesting cases

- `base-branch-only`: Old comments have empty commit lists, so filtering is trivially "delete all". Doesn't test partial filtering.
- `head-vs-base-branch`: Doesn't assert which specific commits end up in which comments.
- `force-push-ignores-missing-old-commit`: Second force-push uses the same head commit — doesn't test what happens when commits actually change.
- No test covers old push comments with real commit IDs that partially overlap with the new commit set (the core scenario this PR is trying to fix).

#### 5. `CommitsBetweenNotBase` removal is premature

The function is removed but its `--not baseBranch` semantics are needed. The replacement doesn't provide equivalent filtering.

File: services/pull/comment.go [hunk 12]
```diff
@@ -62,31 +30,91 @@ func CreatePushPullComment(ctx context.Context, pusher *user_model.User, pr *iss
...
+				log.Error("GetCommitIDsBetween %q..%q failed: %v", mergeBase, newCommitID, err)
+			}
+			for _, commitID := range data.CommitIDs {
+				commitIDMaps.Add(commitID)
+			}
+		}
+	} else {
+		data.CommitIDs, err = gitrepo.GetCommitIDsBetweenReversed(ctx, pr.BaseRepo, oldCommitID, newCommitID)
+		if err != nil {
 			return nil, err
```
Comment (silverwind) [inline services/pull/comment.go]: The error handling here uses `log.Error` + `continue` for `GetPushActionContent`, `json.Marshal`, and DB update failures. If any of these fail mid-loop, `data.CommitIDs` will be partially reduced and some old comments may be updated while others are not, leaving inconsistent state. Consider failing the entire transaction instead.

File: services/pull/comment.go [hunk 13]
```diff
@@ -62,31 +30,91 @@ func CreatePushPullComment(ctx context.Context, pusher *user_model.User, pr *iss
...
+			// For force-push events, failures resolving the base ref/head commit or computing the merge-base should not prevent deleting stale push comments or creating the force-push timeline entry.
+			log.Error("MergeBase %q and %q failed: %v", pr.BaseBranch, newCommitID, err)
+		} else {
+			data.CommitIDs, err = gitrepo.GetCommitIDsBetweenReversed(ctx, pr.BaseRepo, mergeBase, newCommitID)
+			if err != nil {
+				// For force-push events, failures resolving the base ref/head commit or computing
+				// the merge-base should not prevent deleting stale push comments or creating the
+				// force-push timeline entry.
+				log.Error("GetCommitIDsBetween %q..%q failed: %v", mergeBase, newCommitID, err)
+			}
```
Comment (silverwind) [inline services/pull/comment.go]: This entire filtering approach (removing stale commits from old comments, redistributing them) is significantly more complex than what GitHub does. GitHub simply preserves old push comments unchanged on force-push — old commit links may become dead (404), which is acceptable. A simpler approach would match GitHub more closely and have less surface area for bugs.

File: modules/gitrepo/compare.go [hunk 14]
```diff
@@ -42,3 +42,20 @@ func GetDivergingCommits(ctx context.Context, repo Repository, baseBranch, targe
 	}
 	return &DivergeObject{Ahead: ahead, Behind: behind}, nil
 }
+
+// GetCommitIDsBetweenReversed returns the commit IDs between two commits in reverse order(from old to new)
+func GetCommitIDsBetweenReversed(ctx context.Context, repo Repository, startRef, endRef string) ([]string, error) {
+	stdout, _, err := RunCmdString(ctx, repo, gitcmd.NewCommand("rev-list", "--reverse").AddDynamicArguments(startRef+".."+endRef))
+	// example git error message: fatal: origin/main...HEAD: no merge base
+	if err != nil && strings.Contains(err.Stderr(), "no merge base") {
+		// future versions of git >= 2.28 are likely to return an error if before and last have become unrelated.
```
Comment (silverwind) [inline modules/gitrepo/compare.go:61]: The "no merge base" fallback runs `rev-list --reverse startRef endRef` (space-separated), which lists ALL commits reachable from EITHER ref. This could return the entire repository history. The old `CommitsBetweenNotBase` had the same fallback pattern but applied `--not baseBranch` to limit results.

**Comment by silverwind** [comment]
I don't think this is ready yet as per above review.

**Comment by wxiaoguang** [comment]
> I don't think this is ready yet as per above review.

If nothing worse than before, and it won't block future improvements, then it could be fine.


https://github.com/go-gitea/gitea/pull/36914#discussion_r2979897310 `--not` this one seems related.

**Comment by wxiaoguang** [comment]
> > I don't think this is ready yet as per above review.
> 
> If nothing worse than before, and it won't block future improvements, then it could be fine.
> 
> [#36914 (comment)](https://github.com/go-gitea/gitea/pull/36914#discussion_r2979897310) `--not` this one seems related.

The old approach (before https://github.com/go-gitea/gitea/pull/36914/commits/cf69efa1a778b95149e22695e0a2bb93f9ee66df) is overall good enough.

The more changes just made this PR messy and worse, no test to cover the new complex logic, due to the code can't be written correctly (why I shouldn't question whether there is ability to write code correctly?)

**Comment by silverwind** [comment]
Up to @lunny if he wants to merge as-is. I'm not blocking it, but we see it's still not as clean as it could be.

**Comment by lunny** [comment]
> > > I don't think this is ready yet as per above review.
> > 
> > 
> > If nothing worse than before, and it won't block future improvements, then it could be fine.
> > [#36914 (comment)](https://github.com/go-gitea/gitea/pull/36914#discussion_r2979897310) `--not` this one seems related.
> 
> The old approach (before [cf69efa](https://github.com/go-gitea/gitea/commit/cf69efa1a778b95149e22695e0a2bb93f9ee66df)) is overall good enough.
> 
> The more changes just made this PR messy and worse, no test to cover the new complex logic, due to the code can't be written correctly (why I shouldn't question whether there is ability to write code correctly?)

Before cf69efa, the change would delete all existing commit comments and recreate them, even when some commits remained unchanged. The new logic preserves commit comments for commits that were not rewritten by the force-push, and only recreates comments for commits that actually changed. I think this better matches GitHub’s behavior, and the timeline should also look more correct.

**Comment by wxiaoguang** [comment]
> > > > I don't think this is ready yet as per above review.
> > > 
> > > 
> > > If nothing worse than before, and it won't block future improvements, then it could be fine.
> > > [#36914 (comment)](https://github.com/go-gitea/gitea/pull/36914#discussion_r2979897310) `--not` this one seems related.
> > 
> > 
> > The old approach (before [cf69efa](https://github.com/go-gitea/gitea/commit/cf69efa1a778b95149e22695e0a2bb93f9ee66df)) is overall good enough.
> > The more changes just made this PR messy and worse, no test to cover the new complex logic, due to the code can't be written correctly (why I shouldn't question whether there is ability to write code correctly?)
> 
> Before [cf69efa](https://github.com/go-gitea/gitea/commit/cf69efa1a778b95149e22695e0a2bb93f9ee66df), the change would delete all existing commit comments and recreate them, even when some commits remained unchanged. The new logic preserves commit comments for commits that were not rewritten by the force-push, and only recreates comments for commits that actually changed. I think this better matches GitHub’s behavior, and the timeline should also look more correct.

I don't mean the purpose is not right. I mean : The more changes just made this PR messy and worse, no test to cover the new complex logic

**Comment by wxiaoguang** [comment]
You should be able to know how to write correct tests for the functions like `prepareOldCommitCommentsToDelete` after https://github.com/go-gitea/gitea/pull/36914/commits/16e1d63a1f996476df9d99659e73f7f4f9437652

File: modules/gitrepo/compare.go (hunk 14 above)
Comment (wxiaoguang) [reply modules/gitrepo/compare.go:61]: `--not baseBranch` doesn't really help to limit results, because these two refs can share no base.

I added "limit" argument to limit the count.

In real world, listing 1000 commits in a push is already large enough, nobody can really read that many commit IDs.

File: services/pull/pull.go [hunk 15]
```diff
@@ -343,7 +343,7 @@ func ChangeTargetBranch(ctx context.Context, pr *issues_model.PullRequest, doer
 			return err
 		}
 
-		_, _, err = CreatePushPullComment(ctx, doer, pr, git.BranchPrefix+pr.BaseBranch, pr.GetGitHeadRefName(), false)
+		_, _, err = CreatePushPullComment(ctx, doer, pr, git.BranchPrefix+pr.BaseBranch, pr.GetGitHeadRefName(), false, false)
```
Comment (wxiaoguang) [inline services/pull/pull.go]: Can you avoid such "false, false" trick? Readers don't know what does "false" mean.

Comment (lunny) [reply services/pull/pull.go]: 21e833079f

File: services/pull/comment.go [hunk 16]
```diff
@@ -99,19 +99,24 @@ func cleanUpOldCommitCommentsForNewForcePush(ctx context.Context, pr *issues_mod
 	return err
 }
 
+type CreatePushPullCommentOptions struct {
+	IsForcePush bool
+	IsSync      bool // IsSync indicates whether it's a sync push, that means most
```
Comment (wxiaoguang) [inline services/pull/comment.go]: What is a "sync push" indeed? What does it mean if they both are false?

Does the definition conflict with:

```
IsSync      bool // True means it's a pull request synchronization, false means it's triggered for pull request merging or updating
```

?

----

`that means most`: "what" means most? most "what"?

----

`agit.go`: `IsSync:      false`, so agit  "false means it's triggered for pull request merging or updating"?

**Comment by wxiaoguang** [comment]
Unclear concept, dirty design, noodle-like code, noodle-like logic.

File: services/pull/comment.go (hunk 16 above)
Comment (lunny) [reply services/pull/comment.go]: This is wrong and removed.

**Comment by lunny** [comment]
@wxiaoguang @silverwind This is ready again.

**Comment by wxiaoguang** [comment]
I have spent enough time. I will leave the honor to other maintainers.

**Review by bircni — COMMENTED** [review]
👀

**Comment by bircni** [comment]
wtf whats wrong with GitHub - I did not approve it I just left a comment that's not an approval

**Comment by bircni** [comment]
1. `GetPushActionContent` always returns `nil` error despite the signature — callers get a silent zero-value struct on malformed content; either propagate the unmarshal error or drop it from the signature entirely
2. `prepareOldCommitCommentsToDelete` mutates `newData.CommitIDs` as a hidden side effect — the name only hints at returning IDs to delete, this will confuse future readers; rename or make the mutation explicit
3. `GetLastCommitIDsBetweenReverse` — "Last" and "Reverse" are both confusing here; "Last" refers to the `-n limit` cap silently dropping old commits, "Reverse" is just the output ordering; `GetCommitIDsBetween` would be clearer
4. `cleanUpOldCommitCommentsForNewForcePush` logs errors internally and doesn't return them, so `db.WithTx2` can't roll back on partial failures — the cleanup can leave comments in an inconsistent state if the content update succeeds but the delete fails
5. Passing the zero SHA (`EmptyObjectID`) as `oldRef` goes through `gitRepo.GetRefCommitID` which may not handle it gracefully — the force-push-with-missing-old-commit test case asserts `require.NotNil(t, comment)` but if `GetRefCommitID` errors on zero SHA the whole function returns early with `created=false`; this path needs an explicit guard
6. The commit deduplication logic (stripping already-accounted-for commits from `newData`) has no test — a subtest where an old comment shares some but not all commits with the new push would cover the core `prepareOldCommitCommentsToDelete` logic
7. Typo in `GetLastCommitIDsBetweenReverse`: `"--not should be kep as the last parameter"` → `kept`; also the `"future versions of git >= 2.28"` comment is stale copy-paste, 2.28 shipped in 2020

_Written by Claude Code_

**Comment by lunny** [comment]
> 1. `GetPushActionContent` always returns `nil` error despite the signature — callers get a silent zero-value struct on malformed content; either propagate the unmarshal error or drop it from the signature entirely

We can do nothing if unmarshal failed.

> 2. `prepareOldCommitCommentsToDelete` mutates `newData.CommitIDs` as a hidden side effect — the name only hints at returning IDs to delete, this will confuse future readers; rename or make the mutation explicit

Renamed at [628d769](https://github.com/go-gitea/gitea/pull/36914/commits/628d7690f39fc6b185c98157dca55ef312fe67f8)

> 3. `GetLastCommitIDsBetweenReverse` — "Last" and "Reverse" are both confusing here; "Last" refers to the `-n limit` cap silently dropping old commits, "Reverse" is just the output ordering; `GetCommitIDsBetween` would be clearer

Renamed at [94345ee](https://github.com/go-gitea/gitea/pull/36914/commits/94345ee4286b3db47a7078d284355e2b550a6187)

> 4. `cleanUpOldCommitCommentsForNewForcePush` logs errors internally and doesn't return them, so `db.WithTx2` can't roll back on partial failures — the cleanup can leave comments in an inconsistent state if the content update succeeds but the delete fails

We don't need to roll back here.

> 5. Passing the zero SHA (`EmptyObjectID`) as `oldRef` goes through `gitRepo.GetRefCommitID` which may not handle it gracefully — the force-push-with-missing-old-commit test case asserts `require.NotNil(t, comment)` but if `GetRefCommitID` errors on zero SHA the whole function returns early with `created=false`; this path needs an explicit guard

[d3286f7](https://github.com/go-gitea/gitea/pull/36914/commits/d3286f7732618f75d0879f781c6ce68374b41af0)

> 6. The commit deduplication logic (stripping already-accounted-for commits from `newData`) has no test — a subtest where an old comment shares some but not all commits with the new push would cover the core `prepareOldCommitCommentsToDelete` logic
> 7. Typo in `GetLastCommitIDsBetweenReverse`: `"--not should be kep as the last parameter"` → `kept`; also the `"future versions of git >= 2.28"` comment is stale copy-paste, 2.28 shipped in 2020
> 

Fixed.


> _Written by Claude Code_

**Comment by silverwind** [comment]
## Review update (considering [previous review](https://github.com/go-gitea/gitea/pull/36914#pullrequestreview-3997273644))

### What's been addressed

1. **`--not baseBranch` regression** — Fixed. The non-force-push path now passes `pr.BaseBranch` as `notRef`, correctly excluding base branch commits from push timeline entries.

2. **`CommitsBetweenNotBase` removal** — Addressed. The `notRef` parameter in `GetCommitIDsBetweenReverse` replicates the `--not baseBranch` semantics.

3. **"No merge base" fallback unbounded output** — Partially addressed. The `limit` parameter caps output at 1000. The fallback semantics (listing commits reachable from EITHER ref) are still wrong in principle, but the limit prevents catastrophic behavior.

4. **`genCmd` mutation bug** — Fixed. `genCmd` now creates a new command each call instead of mutating a shared one.

### What's still outstanding

**The reconciliation approach is still overly complex.** `reconcileOldCommitCommentsForForcePush` modifies old comments in-place (removing commit IDs, deleting empty ones, deduplicating against the new commit set). GitHub simply preserves old push comments unchanged on force-push — old commit links may 404, which is acceptable. The current approach:
- Mutates `newData.CommitIDs` as a side effect, making data flow hard to trace
- Updates individual old comments inside the transaction, with errors only logged (not returned)
- Has more surface area for edge-case bugs (malformed JSON, partial failures)

**Tests still don't cover the reconciliation logic.** All test cases create old comments with empty `PushActionContent{}` (no commit IDs). The reconciliation code's interesting paths — where old comments have real commit IDs that partially overlap with the new force-push commits — are never exercised.

### New concerns

**`GetPushActionContent` silently ignores unmarshal errors.** `_ = json.Unmarshal(...)` returns an empty `PushActionContent` on malformed JSON (no error). During reconciliation, that empty content causes the comment to be deleted (no surviving commit IDs). This could silently destroy valid comments with corrupted content. Either propagate the error or don't return `nil` error when unmarshal fails.

**`cleanUpOldCommitCommentsForNewForcePush` errors are swallowed inside the transaction.** If cleanup partially fails, the transaction continues creating new comments on top of inconsistent state. This should either fail the transaction or the individual updates inside `reconcileOldCommitCommentsForForcePush` should also be resilient.

**Multiple `json.Marshal` errors silently ignored.** `dataJSON, _ := json.Marshal(data)` appears in 3 places.

**Comment by wxiaoguang** [comment]
> GetPushActionContent silently ignores unmarshal errors. _ = json.Unmarshal(...) returns an empty PushActionContent on malformed JSON (no error).

Tolerate corrupted database values, otherwise `json.Unmarshal` should never fail.

> **Multiple `json.Marshal` errors silently ignored.** `dataJSON, _ := json.Marshal(data)` appears in 3 places.

json.Marshal never fails in these cases.

**Comment by wxiaoguang** [comment]
> **`cleanUpOldCommitCommentsForNewForcePush` errors are swallowed inside the transaction.**

It is also a right decision.


------

@silverwind Can you please show your thoughts, instead of just copying AI slop?

You should have your judgement, don't let AI slop waste everyone's time or mislead others.

https://github.com/go-gitea/gitea/pull/37040#issuecomment-4163524408

image

**Comment by wxiaoguang** [comment]
https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md#ai-contribution-policy

> Do not use AI to reply to questions about your issue or pull request. The questions are for you, not an AI model.

I believe it also applies to the reviews & questions: if you are reviewing or questioning, the reviews and questions are from you, not an AI model.

**Comment by silverwind** [comment]
@lunny will you address https://github.com/go-gitea/gitea/pull/36914#issuecomment-4161304410?

> @silverwind Can you please show your thoughts, instead of just copying AI slop?

My requirement is:

- Exact representenation of commits on the branch (likely addressed)
- One force-push message per force-push, no "reconcilation" and no mutation (not addressed)

**Comment by lunny** [comment]
> @lunny will you address [#36914 (comment)](https://github.com/go-gitea/gitea/pull/36914#issuecomment-4161304410)?
> 
> > @silverwind Can you please show your thoughts, instead of just copying AI slop?
> 
> My requirement is:
> 
> * Exact representenation of commits on the branch (likely addressed)
> * One force-push message per force-push, no "reconcilation" and no mutation (not addressed)

I don't understand your second requirement? I think the current behavior matched what Github did.

**Review by silverwind — APPROVED** [review]
I guess it is an improvement, but should be iterated upon later.

**Comment by silverwind** [comment]
Don't have time or motivation to dig deeper now, so I trust it is correct.

**Comment by bircni** [comment]
I don't feel good with this 
@wxiaoguang what it's your opinion?
@Zettat123 as there were more changes could you also have a look at it again?

**Comment by wxiaoguang** [comment]
I have done enough. My patience is limited.

* https://github.com/go-gitea/gitea/pull/36914#issuecomment-4147724668
* https://github.com/go-gitea/gitea/pull/36914#issuecomment-4149866944
* https://github.com/go-gitea/gitea/pull/36914#issuecomment-4151486233
* https://github.com/go-gitea/gitea/pull/36914#issuecomment-4158317785
* https://github.com/go-gitea/gitea/pull/36914#discussion_r3006886483

**Comment by lunny** [comment]
I think we can merge this now. I could fix it if there is any bug.

**Review by bircni — COMMENTED** [review]
👍
