### PR TITLE
Create doctor command to fix repo_units broken by dumps from 1.14.3-1.14.6 (#17136)

### LINKED ISSUE #16961: Unable to access repos after going from 1.15.0 => 1.15.2
- Gitea version (or commit ref): 1.15.2
- Git version: 2.33.0
- Operating system: Ubuntu 20.04.2 using systemd and Gitea downloaded from the github releases page (amd64 build)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ x] No
- Log gist:
`2021/09/05 09:58:23 ...ules/context/repo.go:343:repoAssignment() [E] GetUserRepoPermission: skipObjectDecoder: expect object or null, error found in #0 byte of ...|&\003d{\003d}\003d|..., bigger context ...|&\003d{\003d}\003d|...
2021/09/05 09:54:32 ...ters/private/serv.go:293:ServCommand() [E] Unable to get permissions for 3:REMOVED with key 8 in 2:ORG/myrepo Error: skipObjectDecoder: expect object or null, error found in #0 byte of ...|&\003d{\003d}\003d|..., bigger context ...|&\003d{\003d}\003d|...
2021/09/05 09:54:33 modules/ssh/ssh.go:140:sessionHandler() [E] SSH: Wait: exit status 1
`

## Description
When logging in, I am able to see all commits on the dashboard to repos I have access to, but the right side repos card is empty and missing all repos that I have access to. When selecting to view a repo, I get a 500 error with the error above logged. Rolling back to 1.15.0 and everything returns to normal.

SSH access also fails with errors as well as shown above.

### LINKED ISSUE #17297: 500 error on organization page: error calling DescriptionHTML
### Gitea Version

1.15.3

### Operating System

Linux (NixOS)

### Browser Version

Firefox 92.0

### Can you reproduce the bug on the Gitea demo site?

No

### Description

A user on my `gitea` instance reported that whenever they hit the "org" page for one organization they get a 500 error. I'm able to reproduce this. The error only occurs on 1 organization - all other organizations are viewable without any errors.

I imagine a `select` statement in one of the tables in the associated database could provide more relevant information, but I'm not sure which table(s) to `select` from.

Any help would be greatly appreciated.

Thank you.

### Screenshots

Screenshot_20211012_224441
Screenshot_20211012_224409

### PR DESCRIPTION
**Pull request by zeripath**
Backport #17136

There was a serious issue with the `gitea dump` command in 1.14.3-1.14.6 which led to corruption of the `config` field of the `repo_unit` table. 

This PR adds a doctor command to attempt to fix the broken repo_units. Users affected by #16961 should run:

```
gitea doctor --fix --run fix-broken-repo-units
```

Fix #16961
Fix #17297

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

File: modules/doctor/fix16961_test.go [hunk 1]
```diff
@@ -0,0 +1,271 @@
+// Copyright 2020 The Gitea Authors. All rights reserved.
```
Comment (techknowlogick) [inline modules/doctor/fix16961_test.go]:
```suggestion
// Copyright 2021 The Gitea Authors. All rights reserved.
```

File: modules/doctor/fix16961.go [hunk 2]
```diff
@@ -0,0 +1,317 @@
+// Copyright 2020 The Gitea Authors. All rights reserved.
```
Comment (techknowlogick) [inline modules/doctor/fix16961.go]:
```suggestion
// Copyright 2021 The Gitea Authors. All rights reserved.
```

**Review by techknowlogick — APPROVED** [review]

**Comment by zeripath** [comment]
make lgtm work
