### PR TITLE
Fix download buttons on branches page

### LINKED ISSUE #30143: `JavaScript promise rejection: dropdownBtn is null`
When downloading a branch from `/<repo>/branches`

grafik

### PR DESCRIPTION
**Pull request by silverwind**
Fixes https://github.com/go-gitea/gitea/issues/30143, regression from https://github.com/go-gitea/gitea/pull/29920.

We have `.button` on the repo page, but on the branch page it's a `.btn`. Eventually we should find a solution to have a single button class but until then this solution should be acceptable.

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

File: web_src/js/features/repo-common.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ import {hideElem, showElem} from '../utils/dom.js';
 import {POST} from '../modules/fetch.js';
 
 async function getArchive($target, url, first) {
-  const dropdownBtn = $target[0].closest('.ui.dropdown.button');
+  const dropdownBtn = $target[0].closest('.ui.dropdown.button') ?? $target[0].closest('.ui.dropdown.btn');
```
Comment (wxiaoguang) [inline web_src/js/features/repo-common.js:6]: Why not just use `.ui.dropdown` .....

Comment (silverwind) [reply web_src/js/features/repo-common.js:6]: Right, could have.
