### PR TITLE
Fix global packages enabled avaiable

### LINKED ISSUE #19275: Disabling the package registry does not work
### Description

Disabling the package registry as per https://docs.gitea.io/en-us/config-cheat-sheet/#packages-packages does not seem to work, the package pages are still available in the repos and the user pages.

To be clear I have this in my `app.ini`:
```
[packages]
ENABLED = false
```

### Gitea Version

43332a4

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.34.1

### Operating System

Debian 11

### How are you running Gitea?

Docker

### Database

SQLite

### PR DESCRIPTION
**Pull request by lunny**
Fix #19275

### CODE REVIEW

File: routers/api/packages/api.go [hunk 1]
```diff
@@ -81,15 +81,17 @@ func Routes() *web.Route {
...
 						r.Post("/upload_urls", reqPackageAccess(perm.AccessModeWrite), conan.RecipeUploadURLs)
 						r.Get("/download_urls", conan.RecipeDownloadURLs)
-						r.Group("/packages", func() {
-							r.Post("/delete", reqPackageAccess(perm.AccessModeWrite), conan.DeletePackageV1)
-							r.Group("/{package_reference}", func() {
-								r.Get("", conan.PackageSnapshot)
-								r.Get("/digest", conan.PackageDownloadURLs)
-								r.Post("/upload_urls", reqPackageAccess(perm.AccessModeWrite), conan.PackageUploadURLs)
-								r.Get("/download_urls", conan.PackageDownloadURLs)
+						if setting.Packages.Enabled {
```
Comment (delvh) [inline routers/api/packages/api.go]: I am absolutely not a friend of offering **API** routes conditionally.
Because then, an app like `GitNex` has no option but to "try-catch" whether a given route is supported for an unknown server.
I think a better alternative would be to make the corresponding functions no-ops in that case, i.e. by simply returning the status `501 - Not Implemented`.

File: routers/api/packages/api.go [hunk 2]
```diff
@@ -127,26 +129,28 @@ func Routes() *web.Route {
 										r.Put("", reqPackageAccess(perm.AccessModeWrite), conan.UploadRecipeFile)
 									})
 								})
-								r.Group("/packages", func() {
-									r.Delete("", reqPackageAccess(perm.AccessModeWrite), conan.DeletePackageV2)
-									r.Group("/{package_reference}", func() {
+								if setting.Packages.Enabled {
```
Comment (delvh) [inline routers/api/packages/api.go]: See above

File: routers/web/web.go [hunk 3]
```diff
@@ -472,10 +472,12 @@ func RegisterRoutes(m *web.Route) {
 			m.Post("/delete", admin.DeleteRepo)
 		})
 
-		m.Group("/packages", func() {
-			m.Get("", admin.Packages)
-			m.Post("/delete", admin.DeletePackageVersion)
-		})
+		if setting.Packages.Enabled {
```
Comment (delvh) [inline routers/web/web.go:476]: Here it is fine as these routes are only called internally, and hence we can ensure using them correctly.

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
I just noticed: We should update the swagger docs for this return value-

File: routers/api/packages/api.go [hunk 4]
```diff
@@ -28,6 +28,11 @@ import (
 
 func reqPackageAccess(accessMode perm.AccessMode) func(ctx *context.Context) {
 	return func(ctx *context.Context) {
+		if !setting.Packages.Enabled {
```
Comment (KN4CK3R) [inline routers/api/packages/api.go]: This gets never called because the routes are still disabled in `init.go`:

```go
	if setting.Packages.Enabled {
		r.Mount("/api/packages", packages_router.Routes())
		r.Mount("/v2", packages_router.ContainerRoutes())
	}
```

File: routers/api/packages/api.go (hunk 1 above)
Comment (KN4CK3R) [reply routers/api/packages/api.go]: I'm uncertain what is a good approach. We already use conditional routes

https://github.com/go-gitea/gitea/blob/9c349a4277926bfd3ff0360301765ad7abd9f10b/routers/api/v1/api.go#L632-L636

https://github.com/go-gitea/gitea/blob/9c349a4277926bfd3ff0360301765ad7abd9f10b/routers/api/v1/api.go#L638-L640

https://github.com/go-gitea/gitea/blob/9c349a4277926bfd3ff0360301765ad7abd9f10b/routers/api/v1/api.go#L669-L671

And all the `mustXXX` methods return a 404 which cannot be distinguished from real not found paths.
https://github.com/go-gitea/gitea/blob/9c349a4277926bfd3ff0360301765ad7abd9f10b/routers/api/v1/api.go#L475

File: routers/api/packages/api.go (hunk 4 above)
Comment (lunny) [reply routers/api/packages/api.go]: reverted the change.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
.

**Comment by BlackOrca** [comment]
My problem is i cannot activate the packages functionality.
Is a workaround to activate the packages while this fix comes to a new Release?

**Comment by 6543** [comment]
@BlackOrca It's not released - if you use docker you have to use the `dev` tag ...
