### PR TITLE
Fix duplicate Reviewed-by trailers

### LINKED ISSUE #24795: Duplicate Reviewed-by lines in default merge message
### Description

When using the merge commit strategy for a pull request it is possible for unofficial approvers to be duplicated in the commit message trailers. 

The requirements to trigger this scenario:

1) app.ini
[repository.pull-request]
DEFAULT_MERGE_MESSAGE_OFFICIAL_APPROVERS_ONLY = false

2) No custom MERGE_TEMPLATE *or* a custom pull.tmpl that always appends the default merge message.

For example if the unofficial reviewer `User A` casts two approval votes, the generated merge message looks like this
```
Commit Title

Reviewed-by: User A <user.a@example.com>
Reviewed-by: User A <user.a@example.com>
```

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

image

### Git Version

2.40.1

### Operating System

Ubuntu 23.04

### How are you running Gitea?

Built from source on v1.19.3, also verified on tip of main, and running locally from command line.
```
TAGS="bindata sqlite sqlite_unlock_notify" make build
```

### Database

SQLite

### PR DESCRIPTION
**Pull request by corytodd**
Enable deduplication of unofficial reviews. When pull requests are configured to include all approvers, not just official ones, in the default merge messages it was possible to generate duplicated Reviewed-by lines for a single person. Add an option to find only distinct reviews for a given query. 

fixes #24795

### CODE REVIEW

File: models/issues/review.go [hunk 1]
```diff
@@ -248,9 +249,14 @@ func FindReviews(ctx context.Context, opts FindReviewOptions) ([]*Review, error)
...
 		sess = db.SetSessionPagination(sess, &opts)
 	}
+	distinct := ""
+	if opts.Distinct {
+		distinct = "reviewer_id"
+	}
 	return reviews, sess.
 		Asc("created_unix").
 		Asc("id").
+		Distinct(distinct).
```
Comment (lunny) [inline models/issues/review.go]: Not every database support the SQL syntax?

Comment (corytodd) [reply models/issues/review.go]: Okay, I didn't know this. So using an empty string for `Distinct` is the issue? How about this then:

```
if opts.Distinct {
	return reviews, sess.
		Asc("created_unix").
		Asc("id").
		Distinct("reviewer_id").
		Find(&reviews)
else {
	return reviews, sess.
		Asc("created_unix").
		Asc("id").
		Find(&reviews)
}
```

Comment (corytodd) [reply models/issues/review.go]: Oh I see there is a test harness for this. I'll work on a test and resubmit.

**Comment by silverwind** [comment]
A test would be nice here.

**Comment by silverwind** [comment]
Is it ready?

**Comment by corytodd** [comment]
Yes, was waiting for the tests to pass before I removed the draft state thanks for the reminder!

**Comment by corytodd** [comment]
The merge conflict has been resolved so this is ready again.

**Review by lunny — APPROVED** [review]

File: models/issues/review.go [hunk 2]
```diff
@@ -269,6 +270,12 @@ func FindReviews(ctx context.Context, opts FindReviewOptions) ([]*Review, error)
 	if opts.Page > 0 {
 		sess = db.SetSessionPagination(sess, &opts)
 	}
+	if opts.LatestOnly {
+		sess.In("id", builder.
+			Select("max ( id ) ").
+			From("review").
+			GroupBy("reviewer_id"))
```
Comment (wxiaoguang) [inline models/issues/review.go]: No more "where" condition for this query?

For a instance with 100,000 reviews, this "IN" query will group these 100,000 reviews for each FindReviews call?

Comment (lunny) [reply models/issues/review.go]: issue_id condition is necessary.

Comment (corytodd) [reply models/issues/review.go]: Done. I wasn't sure about this one since IssueID will not always be provided. I think re-using the outer condition on where on the subquery should be okay?

**Comment by corytodd** [comment]
Fixed more conflicts.

File: models/issues/review.go [hunk 3]
```diff
@@ -243,6 +243,7 @@ type FindReviewOptions struct {
 	IssueID      int64
 	ReviewerID   int64
 	OfficialOnly bool
+	LatestOnly   bool // Latest per-reviewer
```
Comment (wxiaoguang) [inline models/issues/review.go]: After reading the code again, I think it's better to add a `FindLatestReviews` , instead of adding `LatestOnly` to FindReviewOptions.

The reason is, the newly added `LatestOnly` is not respected by `toCond`, but `FindReviewOptions` is shared by `FindReviewOptions` and `CountReviewOptions`. So, if LatestOnly=true, FindReviewOptions and CountReviewOptions behave differently, it would cause bugs or confuse developers in the future.

----

If we introduce a `FindLatestReviews`, then everything is clear.

Comment (corytodd) [reply models/issues/review.go]: That's a very good point, thanks for the feedback. I've made the requested revisions.

**Review by wxiaoguang — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Should we backport this?
