### PR TITLE
Fix the logic of finding the latest pull review commit ID

### LINKED ISSUE #31423: "Show changes since your last review" button should still show even if a review was requested from me again
### Description

A PR "Files Changed" tab's "Filter by commit" button's "Show changes since your last review" sub button should still show even if a review was requested from me again after my review. Note that the previous review was not dismissed.

My guess is that the logic only looks at the top of the review stack of a person, and when a request is on top it just skips the part where it works out the difference.

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No, because I need 2 account for that, but I'll do that when I have time.

### Log Gist

_No response_

#### Before a new review was requested of me
20240619_18h04m14s_grim
20240619_18h04m04s_grim

#### After a new review was requested of me
20240619_18h07m48s_grim
20240619_18h07m55s_grim

### Git Version

_No response_

### Operating System

Ubuntu 22.04

### How are you running Gitea?

self-hosted docker image

### Database

None

### PR DESCRIPTION
**Pull request by Zettat123**
Fix #31423

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: models/issues/review_list.go [hunk 1]
```diff
@@ -107,8 +107,12 @@ func (opts *FindReviewOptions) toCond() builder.Cond {
 	if opts.ReviewerID > 0 {
 		cond = cond.And(builder.Eq{"reviewer_id": opts.ReviewerID})
 	}
-	if opts.Type != ReviewTypeUnknown {
-		cond = cond.And(builder.Eq{"type": opts.Type})
+	if len(opts.Types) > 0 {
+		typeConds := make([]builder.Cond, 0, len(opts.Types))
+		for _, reviewType := range opts.Types {
+			typeConds = append(typeConds, builder.Eq{"type": reviewType})
```
Comment (sillyguodong) [inline models/issues/review_list.go]: use `builder.In`?

Comment (Zettat123) [reply models/issues/review_list.go]: a34862aadf1d2cb1b71a4daeb0c71bb50853f7db

**Review by yp05327 — APPROVED** [review]
