### PR TITLE
Various wiki bug fixes

### LINKED ISSUE #2869: Using / in Wiki Title break the wiki
In [This Wiki Url For example](https://try.gitea.io/testrepo/testrepo/wiki/GET%3A-%2Fhello%2F%3Aanother%2F%3Aanother) it just show the Raw Markdown instead of the markdown with Gitea Layout.

### LINKED ISSUE #2965: Wiki ignores case of page names, but allows creating different pages with same case-insensitive names.
- Gitea version (or commit ref): master
- Can you reproduce the bug at https://try.gitea.io: 
  - [x] Yes (https://try.gitea.io/ethantkoenig/sandbox/wiki/home, see screenshot below)
  - [ ] No
  - [ ] Not relevant

The repo wikis ignore case, but allow you to create two pages whose name differ only in case. In the provided example, there are two pages, "Home" and "home". If the user tries to view the contents of the "home" page, the file contents of the "Home" page are displayed.

image

## Possible Solutions

Either we can keep the wiki case-insensitive, and disallow pages whose names differ only in case (this is what Github does), or we can make the wiki case-sensitive (my preference, to more closely match filesystems)

### PR DESCRIPTION
**Pull request by ethantkoenig**
This PR does the following:
* Updates macaron
* Fixes #2869
* Fixes #2965
* Fixes a bug where trying to create a wiki page with a reserved name would result in a "This page already exists" error being shown to the user. This error message is misleading, because pages with reserved names *cannot* exist. Instead, display a "This page name is reserved" error.
* Adds more unit tests to `models/wiki_test.go`, addressing existing TODOs

### CODE REVIEW

File: models/unit_tests.go [hunk 1]
```diff
@@ -32,7 +32,6 @@ func CreateTestEngine(fixturesDir string) error {
 	if err = x.StoreEngine("InnoDB").Sync2(tables...); err != nil {
 		return err
 	}
-	x.ShowSQL(true)
```
Comment (techknowlogick) [inline models/unit_tests.go]: This change is from your other PR #2995 and unrelated to this PR. It is unlikely to create merge conflicts, but perhaps it should be removed just in case.

File: models/twofactor.go [hunk 2]
```diff
@@ -61,7 +61,7 @@ func (t *TwoFactor) getEncryptionKey() []byte {
 
 // SetSecret sets the 2FA secret.
 func (t *TwoFactor) SetSecret(secret string) error {
-	secretBytes, err := com.AESEncrypt(t.getEncryptionKey(), []byte(secret))
```
Comment (techknowlogick) [inline models/twofactor.go:64]: The changes to 2FA are unrelated to this PR, could they be pulled out an resubmitted under a diff PR?

Comment (ethantkoenig) [reply models/twofactor.go:64]: They are necessary, because of the macaron update.

Comment (techknowlogick) [reply models/twofactor.go:64]: Thanks for the clarification :)

File: models/unit_tests.go (hunk 1 above)
Comment (ethantkoenig) [reply models/unit_tests.go]: done

File: modules/templates/helper.go [hunk 3]
```diff
@@ -25,6 +25,7 @@ import (
 	"golang.org/x/net/html/charset"
 	"golang.org/x/text/transform"
 	"gopkg.in/editorconfig/editorconfig-core-go.v1"
+	"net/url"
```
Comment (lunny) [inline modules/templates/helper.go]: wrong import order

File: templates/repo/wiki/view.tmpl [hunk 4]
```diff
@@ -85,7 +85,7 @@
 			{{end}}
 		</div>
 		{{if .footerPresent}}
-		<div class="ui grey segment">
+		<div class="ui segment">
```
Comment (lunny) [inline templates/repo/wiki/view.tmpl:88]: why remove`grey`?

**Review by lunny — CHANGES_REQUESTED** [review]

File: templates/repo/wiki/view.tmpl (hunk 4 above)
Comment (ethantkoenig) [reply templates/repo/wiki/view.tmpl:88]: Because the footer was the only one with a grey line on the top; neither the main wiki page nor the sidebar had one, so I removed it for consistency.

File: modules/templates/helper.go (hunk 3 above)
Comment (ethantkoenig) [reply modules/templates/helper.go]: done

**Comment by lafriks** [comment]
Tests seem to fail

File: routers/routes/routes.go [hunk 5]
```diff
@@ -608,7 +608,6 @@ func RegisterRoutes(m *macaron.Macaron) {
 
 		m.Group("/wiki", func() {
 			m.Get("/raw/*", repo.WikiRaw)
-			m.Get("/*", repo.WikiRaw)
```
Comment (lafriks) [inline routers/routes/routes.go:611]: Why this route is removed?

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
LGTM

File: routers/routes/routes.go (hunk 5 above)
Comment (ethantkoenig) [reply routers/routes/routes.go:611]: It cannot be reached (aside from a few corner cases), since the `/:page` route takes precedence.

**Comment by lafriks** [comment]
LGTM
