### PR TITLE
Fix heatmap activity

### LINKED ISSUE #6087: Heatmap: Actions are shown on the previous day
- Gitea version (or commit ref): dfad569 1.7.1 (docker image)
- Git version: 2.18.1
- Operating system: Alpine Linux 3.8 (docker image)
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (screenshots below)
  - [ ] No
  - [ ] Not relevant
- Log gist: none

## Description

Heatmap actions are shown on the previous day for actions in an EST (and beyond?) timezone.

#### Steps to reproduce:
- Have your system time be in EST
- Register and login to https://try.gitea.io
- Create a repository and make a commit
- View the heatmap and compare the date of the 2 actions that should be there

## Screenshots

Here is a screenshot from my own gitea instance, the heatmap should show actions from Monday to Friday, instead they are shifted back one day.
image

From try.gitea.io, here is a combined screenshot to show the commit time and the heatmap action time:
image

### PR DESCRIPTION
**Pull request by siddweiker**
### Fixes #6087
Heatmap actions are not timezone aware

- user_heatmap.go model now returns contributions rounded down to 15 minute intervals instead of day
- heatmap.js now will convert the epoch time to the users local time and summarize it to the day

This will balance the amount of data sent and processing time. 15 minute intervals are used as that is the smallest difference in possible time zones.

One outstanding question I have is whether we need to modify the documentation for the swagger API call to note that contributions are rounded to 15 min intervals?

### Testing
For testing I wrote a [script](https://github.com/siddweiker/gitea-generate-heatmap) to create 4 commits per hour for a whole day (96 total). Here is a screenshot before the fix:
image
Heatmap with the fix:
image
And here is a snippet of the entries to show that they should be all on the 27th:
image

### CODE REVIEW

File: web_src/js/features/heatmap.js [hunk 1]
```diff
@@ -7,8 +7,15 @@ export default async function initHeatmap() {
...
+    const heatmap = {};
+    JSON.parse(el.dataset.heatmapData).forEach(({contributions, timestamp}) => {
+      // Convert to user timezone and sum contributions by date
+      const dateStr = new Date(timestamp * 1000).toDateString();
+      heatmap[dateStr] = (heatmap[dateStr] || 0) + contributions;
+    });
+
+    const values = Object.keys(heatmap).map((v) => {
+      return {date: new Date(v), count: heatmap[v]};
     });
```
Comment (silverwind) [inline web_src/js/features/heatmap.js:19]: Why iterate twice?

Comment (siddweiker) [reply web_src/js/features/heatmap.js:19]: The user-heatmap data is made up of timestamps (at 15-minute intervals) to contributions, ActivityHeatmap.vue accepts daily contributions.

The first loop converts the timestamps to the users timezone aware date string (stripping time) and sums the contributions.
The second loop converts it back to a date object with the proper format (list of objects).

(Disclosure: I am not very experienced with JS, so if there is a more elegant way to do this, please let me know.)

Comment (silverwind) [reply web_src/js/features/heatmap.js:19]: Pretty sure it can be all done in one iteration (e.g. in the previous `map` callback). The only reason to loop twice through the data would be to deduplicate it, but I think that is not necessary.

Comment (silverwind) [reply web_src/js/features/heatmap.js:19]: Try this:

```js
const values = JSON.parse(el.dataset.heatmapData).map(({contributions, timestamp}) => {
  // Convert to user timezone and sum contributions by date
  return {
    date: new Date(timestamp * 1000),
    count: (heatmap[dateStr] || 0) + contributions
  }
});

Comment (silverwind) [reply web_src/js/features/heatmap.js:19]: Note, time will probably be in incorrect timezone, we'd need a helper function to convert to current timezone, like this (untested):

```js
function timestampToLocalDate(timestamp) {
  const offset = (new Date()).getTimezoneOffset() * -60000;
  return new Date(timestamp + offset);
};
```

If that works, put it in `web_src/js/utils.js` and import it in this file.

Comment (siddweiker) [reply web_src/js/features/heatmap.js:19]: I tried it and it does not work because ActivityMap.vue will not do any summation, it will only pick one entry per day. You have to de-duplicate it as you've mentioned.

Comment (silverwind) [reply web_src/js/features/heatmap.js:19]: Yes, graph expects absolute per-day values. I will test my suggestion above later.

Comment (siddweiker) [reply web_src/js/features/heatmap.js:19]: The timezone has been correct in my testing. new Date() in JavaScript will return a date with the local browsers timezone automatically. I have also tested it with changing my timezone using a browser extension.

File: models/user_heatmap.go [hunk 2]
```diff
@@ -32,17 +32,14 @@ func getUserHeatmapData(user *User, team *Team, doer *User) ([]*UserHeatmapData,
 		return hdata, nil
 	}
 
-	var groupBy string
-	groupByName := "timestamp" // We need this extra case because mssql doesn't allow grouping by alias
+	// Group by 15 minute intervals which will allow the client to accurately shift the timestamp to their timezone.
+	// The interval is based on the fact that there are timezones such as UTC +5:30 and UTC +12:45.
+	var groupBy = "created_unix / 900 * 900"
+	var groupByName = "timestamp" // We need this extra case because mssql doesn't allow grouping by alias
```
Comment (kins-dev) [inline models/user_heatmap.go]: I'd be careful here as the comment no longer matches the code.
MySQL requires using DIV instead of / for integer division in the group by statement,  That's fine, but what happened to not supporting grouping via an alias as the comment suggests?

FYI:
This looks like a general SQL implementation issue <https://stackoverflow.com/a/3841804>

It may be more robust to set the `groupByName` to `created_unix  / 900` or `created_unix DIV 900` and then set `groupBy` to be `groupByName + " * 900"`.  It would simplify the code.

Comment (siddweiker) [reply models/user_heatmap.go]: The comment does match the code, it matches what it [used to be](https://github.com/go-gitea/gitea/blob/167b0f46ef946fad3ca13976c3b87598f505e2ea/models/user_heatmap.go#L36). M**y**SQL supports group by alias, M**S**SQL does not.

Comment (kins-dev) [reply models/user_heatmap.go]: Sorry that's my fault.  Apparently I need to move to a bigger text size.
That said, adding a comment on why mysql is special here, before that case would be good.

And I would be concerned with MSSQL possibly doing something stupid like actually dividing by 900 then multiplying by 900 when it could group after doing the divide.

Comment (siddweiker) [reply models/user_heatmap.go]: I did fix the variable declaration to be consistent with the rest of the code base.
Here is a SQL fiddle that demonstrates that it should be fine for MSSQL: http://sqlfiddle.com/#!18/9eecb/117255

File: web_src/js/features/heatmap.js (hunk 1 above)
Comment (kins-dev) [reply web_src/js/features/heatmap.js:19]: @silverwind  no, do not try to correct for the timezone.
Unix time, which is stored in the database is based on UTC.
When you call `new Date( int milliseconds )`  the parameter is defined as the ECMA epoch which is also UTC based.
- <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#parameters>
- <https://tc39.es/ecma262/#sec-date-objects>

Here's the trick, when the code calls `toDateString()` it is the responsibility of the javascript engine to provide the time using the local system timezone.

- <https://tc39.es/ecma262/#sec-date.prototype.todatestring>

This means it will show the correct information for the user in their timezone.  If I compare what it looks like for me with someone on the other side of the world using the same server, yes the heatmap will look different.  I think that's OK since it is easy to explain.

This is a user heatmap of user contribution and a user is likely to be looking the page from their computer mapped to their local timezone .  It is also clear when you hover over a box what frame of reference is being used, and I think this is far more intuitive.

Comment (silverwind) [reply web_src/js/features/heatmap.js:19]: Thanks for clearing that up. I wasn't aware of this built-in timezone conversion of the various `Date()` `.toString` methods.

I think we also need to clean up the click mechanism which (wrongly) converts from UTC to local offset, while we should actually send/receive only UTC from/to the server:

https://github.com/go-gitea/gitea/blob/c680eb2cc74823f017f5ad5a4c9e8094cde311f4/web_src/js/components/ActivityHeatmap.vue#L58-L59

File: models/user_heatmap.go [hunk 3]
```diff
@@ -32,17 +32,14 @@ func getUserHeatmapData(user *User, team *Team, doer *User) ([]*UserHeatmapData,
...
-		groupBy = "strftime('%s', strftime('%Y-%m-%d', created_unix, 'unixepoch'))"
 	case setting.Database.UseMySQL:
-		groupBy = "UNIX_TIMESTAMP(DATE(FROM_UNIXTIME(created_unix)))"
-	case setting.Database.UsePostgreSQL:
-		groupBy = "extract(epoch from date_trunc('day', to_timestamp(created_unix)))"
+		groupBy = "created_unix DIV 900 * 900"
 	case setting.Database.UseMSSQL:
-		groupBy = "datediff(SECOND, '19700101', dateadd(DAY, 0, datediff(day, 0, dateadd(s, created_unix, '19700101'))))"
 		groupByName = groupBy
 	}
```
Comment (silverwind) [inline models/user_heatmap.go:44]: Can we somehow cover this with tests? I'm not an expert on SQL dialects but this seems like a risky change unless properly tested (our CI does test all SQL dialects). Maybe [xorm](https://gitea.com/xorm/xorm) could be used?

Comment (siddweiker) [reply models/user_heatmap.go:44]: I have updated and added tests to user_heatmap_test.go and models/fixtures/action.yml.
This should test that the timestamps are properly rounded down to 15 minute intervals and also that two timestamps in the same 15-min interval will be grouped together (contributions=2). I'm not familiar with how the CI tests work, but I see `TestUserHeatmap` in the test-mssql step passed successfully.

File: web_src/js/features/heatmap.js (hunk 1 above)
Comment (siddweiker) [reply web_src/js/features/heatmap.js:19]: I can't explain how, but in my testing clicking the days on the heatmap to filter the actions works as intended for me in EST.
Here are some screenshots:

image
image

Comment (kins-dev) [reply web_src/js/features/heatmap.js:19]: I think that's because when you create a new date from a string rather than a millisecond epoch, again the date object is responsible for converting that from local time to utc which is what the date object stores.  I'd have to double check to be 100% sure but that's what I remember.

File: models/user_heatmap.go (hunk 3 above)
Comment (siddweiker) [reply models/user_heatmap.go:44]: Hey @silverwind let me know if my answers make sense.

**Comment by lafriks** [comment]
Just a wild idea, wouldn't it be better to pass users timezone to backend to do correct calculations based on that?

**Comment by kins-dev** [comment]
> Just a wild idea, wouldn't it be better to pass users timezone to backend to do correct calculations based on that?

Why?  What problem are you trying to solve by that and does it make sense?

For example let's say the server is in London.  My team (Organization Foo) is in California, and there's a team (Organization Bar) in India.

For me, when I look at the Foo or Bar dashboard, I expect to see commits based on my frame of reference.  There is an easy, simple, reliable way to get this behavior that does not require adding a new setting to the backend or even adding to the load on the backend.  My browser which is typically in my frame of reference does it all.

I think if you're doing any timezone conversion on the server here, you're doing something wrong.  Store things in UTC, present them in UTC, let the javascript engine do what it is designed to do.  (Yes you have to chop it up and then let javascript reassemble things, but frankly that's required so the engine can properly do the conversion and dump into buckets. That is required because the heatmap library doesn't accept more than one entry per 24 hour period.)

**Comment by lafriks** [comment]
One thing is that API still requires returning counts per day, other thing is that timezone conversation can be easily done on unixtime just adding or removing specific count of seconds from UTC time and than just grouping as it was done before.

**Comment by siddweiker** [comment]
> One thing is that API still requires returning counts per day

Where is it required to be counts per day?

**Comment by kins-dev** [comment]
> One thing is that API still requires returning counts per day, other thing is that timezone conversation can be easily done on unixtime just adding or removing specific count of seconds from UTC time and than just grouping as it was done before.

https://try.gitea.io/api/swagger#/user/userGetHeatmapData

The model's description is:
`UserHeatmapData represents the data needed to create a heatmap`

Am I missing something here?  If I use this API I need to handle a generic timestamp object, not a date object. 

Also if you believe timezone handling is easy, well you should read up some on it:
https://stackoverflow.com/questions/2532729/daylight-saving-time-and-time-zone-best-practices

One of the major bullets is do not confuse time offsets with time zones.  They are two different things and there are very specific rules around each.

The advice is to keep servers in UTC and "If using JavaScript, use [moment.js](http://momentjs.com/) with the [moment-timezone](http://momentjs.com/timezone/) extension."  This is true if your are supporting older browsers that do not handle ECMAScript 6 as earlier versions do not support daylight savings time in an expected way:
<https://stackoverflow.com/a/16951442>

So let's look at browser support: <https://caniuse.com/?search=es6>

Based on global usage, 94+% of users won't run into the date/time problem if you just depend on ECMA.  For the rest, there may be a case if they happen to be in the US and their in a location with day light savings that the values may be off by an hour for 1-2 weeks.  Now you have to ask is it worth bringing in and maintaining another library for this?  It seems like overkill.

But please, **please** do not try to do this as "just adding or removing specific count of seconds from UTC time"

Instead if you insist on making this harder (and frankly this issue has sat open for 2+ years because it looks like the Gitea team is making thngs harder than they need to be) use the [go timezone library](https://golang.org/pkg/time/tzdata/) and don't roll this yourself.  You will make things worse.

**Comment by siddweiker** [comment]
Any updates on getting this PR reviewed?

**Comment by zeripath** [comment]
Hi @Siddweiker I didn't realise how small this PR is.

OK, I think it would generally be better for the client to request the data in the correct timezone but I can see how that would be difficult. 

Given how small this PR then I think it's a worthy stopgap.

**Review by zeripath — APPROVED** [review]
Please fix conflicts.

This is not ultimately the correct solution but it's a good workaround

**Comment by siddweiker** [comment]
> 
> 
> Please fix conflicts.
> 
> This is not ultimately the correct solution but it's a good workaround

@zeripath Conflicts fixed. I also agree with your statement.

**Review by noerw — APPROVED** [review]
