### PR TITLE
Fix the wrong derive path

### LINKED ISSUE #26264: Found a way to break all repositories inside a gitea instance
### Description

The task "Delete all repositories' archives (ZIP, TAR.GZ, etc..)" corrupts all git repositories.
One of the deleted files are the HEAD files at the root of one repository.
I send the screenshot of the error message of the ui

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

It is running from the official docker image

### Database

MySQL

### PR DESCRIPTION
**Pull request by lunny**
This PR will fix #26264, caused by #23911.

The package configuration derive is totally wrong when storage type is local in that PR.

This PR fixed the inherit logic when storage type is local with some unit tests.

The breakage is if storage type is `local`, the end derive section will derive it but not just use it directly. i.e.

```ini
[storage]
STORAGE_TYPE = local
PATH = /data
```
Then the attachments storage directory will be `/data/attachments` but not `/data`, the behavior is different from before.

### CODE REVIEW

**Review by wxiaoguang — DISMISSED** [review]
It is breaking but it have to be backported to fix the bug.

File: modules/setting/storage_test.go [hunk 1]
```diff
@@ -101,26 +102,26 @@ STORAGE_TYPE = local
 
 	assert.NoError(t, loadPackagesFrom(cfg))
 	assert.EqualValues(t, "local", Packages.Storage.Type)
-	assert.EqualValues(t, "packages/", Packages.Storage.Path)
+	assert.EqualValues(t, filepath.Join(AppWorkPath, "packages"), Packages.Storage.Path)
```
Comment (wxiaoguang) [inline modules/setting/storage_test.go]: It should base on AppDataPath

**Review by wolfogre — APPROVED** [review]

File: modules/setting/storage.go [hunk 2]
```diff
@@ -158,10 +158,26 @@ func getStorage(rootCfg ConfigProvider, name, typ string, sec ConfigSection) (*S
...
+		}
+
+		if extraConfigSec == nil {
+			storage.Path = filepath.Join(targetPath, name)
+		} else {
+			storage.Path = ConfigSectionKeyString(extraConfigSec, "PATH", filepath.Join(targetPath, name))
+		}
+
 		if !filepath.IsAbs(storage.Path) {
 			storage.Path = filepath.Join(AppWorkPath, storage.Path)
```
Comment (wxiaoguang) [inline modules/setting/storage.go]: ~~It should report an error (not abs path). This should be an impossible case in real production.~~

Update: at least, the "relative path" should base on AppDataPath, and it needs a test, eg:

```
[storage]
PATH = relative-path
```

Comment (lunny) [reply modules/setting/storage.go]: `ConfigSectionKeyString(extraConfigSec, "PATH",filepath.Join(targetPath, name)` may return an relative path?

Comment (wxiaoguang) [reply modules/setting/storage.go]: The question is "why".

For consistent, the "targetPath" itself should be absolute first.

File: modules/setting/storage_test.go [hunk 3]
```diff
@@ -190,6 +190,39 @@ PATH = /data/gitea
 	assert.EqualValues(t, "/data/gitea/repo-avatars", RepoAvatar.Storage.Path)
 }
 
+func Test_getStorageInheritStorageTypeLocalRelativePath(t *testing.T) {
+	iniStr := `
+[storage]
+STORAGE_TYPE = local
+PATH = storages
+`
+	cfg, err := NewConfigProviderFromData(iniStr)
```
Comment (wxiaoguang) [inline modules/setting/storage_test.go]:
```suggestion
`
	AppDataPath = "/tmp/data"
	cfg, err := NewConfigProviderFromData(iniStr)
```

File: modules/setting/storage.go [hunk 4]
```diff
@@ -153,31 +153,44 @@ func getStorage(rootCfg ConfigProvider, name, typ string, sec ConfigSection) (*S
...
+		} else if !filepath.IsAbs(targetPath) {
+			targetPath = filepath.Join(AppDataPath, targetPath)
+		}
+
+		if extraConfigSec == nil {
+			storage.Path = filepath.Join(targetPath, name)
+		} else {
+			storage.Path = ConfigSectionKeyString(extraConfigSec, "PATH", filepath.Join(targetPath, name))
+			if !filepath.IsAbs(storage.Path) {
+				storage.Path = filepath.Join(AppDataPath, storage.Path)
```
Comment (wxiaoguang) [inline modules/setting/storage.go]: Here it should base on targetPath but not AppDataPath, and it also needs a test ....

Comment (lunny) [reply modules/setting/storage.go]: Here `extraConfigSec != nil`, that means we will use the override configuration. I have added 2 tests for this.

File: modules/setting/storage.go (hunk 2 above)
Comment (lunny) [reply modules/setting/storage.go]: Changed to `AppDataPath`

File: modules/setting/storage.go (hunk 4 above)
Comment (wxiaoguang) [reply modules/setting/storage.go]: But some tests are not right.

image

Comment (lunny) [reply modules/setting/storage.go]: Tests PASS

Comment (wxiaoguang) [reply modules/setting/storage.go]: "tests pass" doesn't mean the test code is right. Why here the path is a relative path? I don't think it's right.

Comment (lunny) [reply modules/setting/storage.go]: I have added a line `AppDataPath = "/tmp/data"` to make it not a relative path. At non-test env, `AppDataPath` can be guaranteed as absolute path but it's not in the test env.

File: modules/setting/storage_test.go [hunk 5]
```diff
@@ -90,3 +91,161 @@ STORAGE_TYPE = minio
...
+	testLocalStoragePath(t, "/appdata", `
+[storage]
+STORAGE_TYPE = local
+PATH = /data/gitea
+
+[repo-archive]
+PATH = the-archives-dir
+`, []testLocalStoragePathCase{
+		{loadPackagesFrom, &Packages.Storage, "/data/gitea/packages"},
+		{loadRepoArchiveFrom, &RepoArchive.Storage, "/appdata/the-archives-dir"},
```
Comment (wxiaoguang) [inline modules/setting/storage_test.go]: I still consider this behavior is inconsistent.

See the test above: 

* when `[storage].PATH` is empty, it uses AppDataPath, then all storages use paths like `[storage].PATH/name` (which equals to `AppDataPath/name`)
* when `[storage].PATH = /data/gitea`, all storages use use paths like `/data/gitea/name`
* **then**,  when `[storage].PATH = /data/gitea` and a storage has its own relative path, the path for intuition is  `/data/gitea/{relative-path}` but not `AppDataPath/{relative-path}`

Comment (lunny) [reply modules/setting/storage_test.go]: What's the result do you expected? `/data/gitea/the-archives-dir` or `/appdata/the-archives-dir`?

Comment (wxiaoguang) [reply modules/setting/storage_test.go]: >  **then**,  when `[storage].PATH = /data/gitea` and a storage has its own relative path, the path for intuition is  `/data/gitea/{relative-path}`

`/data/gitea/the-archives-dir`

Comment (lunny) [reply modules/setting/storage_test.go]: > > **then**,  when `[storage].PATH = /data/gitea` and a storage has its own relative path, the path for intuition is  `/data/gitea/{relative-path}`
> 
> `/data/gitea/the-archives-dir`

I have the opposite expectation as you. Since the override section's `PATH` have override the parent section's PATH. They should have no relation except there is no override.

Comment (lunny) [reply modules/setting/storage_test.go]: Done.

**Review by wxiaoguang — APPROVED** [review]
Can't fully understand the logic for targetSec/targetSecIsStoragename/extraConfigSec/targetPath/fallbackPath, but the bug needs to be fixed so vote the approval.

**Comment by silverwind** [comment]
"Breaking" section is missing

**Comment by lunny** [comment]
> "Breaking" section is missing

Added.
