### PR TITLE
Fix file name could not be searched if the file was not a text file when using the Bleve indexer

### LINKED ISSUE #33828: Explore/search only searches "code files", not file types like PDF, PNG, etc.
### Description

Hi all, regarding: https://github.com/go-gitea/gitea/pull/32210. I'm on Gitea 1.23.5, and have indexing configured identical to the docs: https://docs.gitea.com/administration/repo-indexer

Searching is performed under https://GITEADOMAIN/explore/code, Exact search type. Have tried FILENAME.pdf, **pdf, **.pdf, etc. Note this is an issue with other file types that are not binaries. I can take any non-standard file and get zero results.

As a counter point, if I search `README.md` all the top results are readme files.

I'm trying to search site-wide in the Explore tab for filenames, but haven't limited luck. Something like `Dockerfile` seems to work fine, but if I put in an exact filename of a PDF, for example, I get zero results for both fuzzy and exact match. Does that PR only apply to "known code" files? Any format that isn't recognized (i.e. `pdf`) never returns results.

Perhaps I'm using Gitea in an "alternative" fashion, but I do have a handful of repos of non-code files (both binary and human-readable), and short of using Go to File from within the actual repo, I can't search for the files.

### Gitea Version

1.23.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

1.23.5

### Operating System

_No response_

### How are you running Gitea?

Self-hosted, internal. I'm the sole user and admin.

### Database

SQLite

### PR DESCRIPTION
**Pull request by charles7668**
Close #33828

### CODE REVIEW

File: modules/indexer/code/bleve/bleve.go [hunk 1]
```diff
@@ -191,7 +191,7 @@ func (b *Indexer) addUpdate(ctx context.Context, batchWriter git.WriteCloserErro
 		return err
 	} else if !typesniffer.DetectContentType(fileContents).IsText() {
 		// FIXME: UTF-16 files will probably fail here
-		return nil
+		fileContents = make([]byte, 0)
```
Comment (wxiaoguang) [inline modules/indexer/code/bleve/bleve.go]:
```suggestion
		// Even if the file is not recognized as a "text file", we could still put its name into the indexers to make the filename become searchable, while leave the content to empty.
		fileContents = nil
```

Does `fileContents = nil` work? In most cases, Golang should treat nil as empty byte slice equally.

**Review by wxiaoguang — APPROVED** [review]

**Review by delvh — APPROVED** [review]
