### PR TITLE
Increase the size of the webauthn_credential credential_id field

### LINKED ISSUE #18727: Migration from 1.15 to 1.16 fails on webauthn table
### Gitea Version

1.16.1

### Git Version

 2.30.2

### Operating System

Debian 11

### How are you running Gitea?

Self-compiled from https://codeberg.org/Codeberg/gitea/src/branch/codeberg-1.16

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

When doing a test migration for coderberg.org to 1.16 in an isolated vm, the migration fails with

```
022/02/11 13:34:47 ...ations/migrations.go:465:Migrate() [I] Migration[207]: Add webauthn table and migrate u2f data to webauthn
2022/02/11 13:34:47 routers/common/db.go:33:InitDBEngine() [E] ORM engine initialization attempt #1/10 failed. Error: migrate: migration[207]: Add webauthn table and migrate u2f data to webauthn failed: Error 1406: Data too long for column 'credential_id' at row 1
```
The credential_id is a varchar(255) column.
Relaxing the sql mode would probably work but truncate the data, probably leading to u2f failing for affected users

(Might be related to #18477)

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by zeripath**
Unfortunately credentialIDs in u2f are 255 bytes long which with base32 encoding
becomes 408 bytes. The default size of a xorm string field is only a VARCHAR(255)

This problem is not apparent on SQLite because strings get mapped to TEXT there.

Fix #18727

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
I don't know if we should remigrate the U2F keys or not.

**Review by 6543 — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by fnetX** [comment]
> remigrate the U2F

What do you mean? Is the original U2F data still present (like redo the migration) or do you mean doing a fix for first-time migrations?

If the first is possible, this might fix some broken keys. Maybe check that the key wasn't removed in the meantime if this is possible?

**Comment by zeripath** [comment]
the original table is still there - because I worried that this might happen.

So we would remigrate the data - but - actually users might have removed those old keys already.

**Comment by fnetX** [comment]
> actually users might have removed those old keys already.

That's what I meant by 

> Maybe check that the key wasn't removed in the meantime

But it should be possible to check the webauthn table for fields that are using the maximum length and then try to remigrate that data, right?

**Comment by lunny** [comment]
> Details

Ah. Checking the records of the webauthn and u2f and decide if the migration is necessary.

**Comment by lunny** [comment]
make L-G-T-M work.

File: models/migrations/v209.go [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+				continue
+			}
+			remigratedCredID := base32.HexEncoding.EncodeToString(parsed.KeyHandle)
+			if cred.CredentialID == remigratedCredID || (!strings.HasPrefix(remigratedCredID, cred.CredentialID) && cred.CredentialID != "") {
+				continue
+			}
+
+			cred.CredentialID = remigratedCredID
+
+			_, err = x.Update(cred)
```
Comment (lunny) [inline models/migrations/v209.go]: This is wrong. We need `x.ID(id).Update(cred)`.

**Review by lunny — DISMISSED** [review]

File: models/migrations/v209.go (hunk 1 above)
Comment (zeripath) [reply models/migrations/v209.go]:
```suggestion
			_, err = x.ID(cred.ID).Update(cred)
```

File: models/migrations/v209.go [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+
+package migrations
+
+import (
+	"encoding/base32"
+	"fmt"
+	"strings"
+
+	"code.gitea.io/gitea/modules/timeutil"
+	"github.com/tstranex/u2f"
```
Comment (lunny) [inline models/migrations/v209.go:14]: blank line.

File: models/migrations/v209.go [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+	}
+
+	// This column has an index on it. I could write all of the code to attempt to change the index OR
+	// I could just use recreate table.
+	sess := x.NewSession()
+	if err := sess.Begin(); err != nil {
+		_ = sess.Close()
+		return err
+	}
+	if err := recreateTable(sess, new(webauthnCredential)); err != nil {
```
Comment (lunny) [inline models/migrations/v209.go]: Why not just modify the column for non-sqlite database?

File: models/migrations/v209.go (hunk 2 above)
Comment (zeripath) [reply models/migrations/v209.go:14]:
```suggestion

	"github.com/tstranex/u2f"
```

File: models/migrations/v209.go (hunk 3 above)
Comment (zeripath) [reply models/migrations/v209.go]:
```go
	// This column has an index on it. I could write all of the code to attempt to change the index OR
	// I could just use recreate table.
```

Comment (zeripath) [reply models/migrations/v209.go]: Honestly it's a nightmare handling all of the hoops which the various databases would require one to jump through to handle the index.

Certainly MSSQL won't allow you adjust a column that has a contraint on it already - that would need to be dropped first but I'm not sure about when you're allowed to readd the constraint. 

Then MYSQL - which I think will allow you to change the column if it's empty - but if it contains data I have a feeling it would need to drop the constraint. Then IIRC if I would try to readd the constraint that won't work.

I think Postgres is fine simply because of cascade.

**Comment by zeripath** [comment]
OK I've written a test and this appears to be working as intended - so I think we can merge.

File: models/migrations/v209.go [hunk 4]
```diff
@@ -0,0 +1,136 @@
...
+		return err
+	}
+
+	switch x.Dialect().URI().DBType {
+	case schemas.MYSQL:
+		_, err := x.Exec("ALTER TABLE webauthn_credential MODIFY COLUMN credential_id VARCHAR(410)")
+		if err != nil {
+			return err
+		}
+	case schemas.ORACLE:
```
Comment (lunny) [inline models/migrations/v209.go:45]: Wow, Gitea hasn't support `ORACLE` yet.
