### PR TITLE
Fix bug when issue disabled, pull request number in the commit message cannot be redirected

### LINKED ISSUE #35419: Redirect between Issue/PR Number not working if one of both is disabled in Repo Settings
### Description
Normally, if `#17` is a Pull Request and you enter `.../issues/17` as the url, you will be redirected to `.../pulls/17`. This, however, does not happen if the issues tab is disabled in the repo settings and produces a "404 Not Found" when visiting `.../issues/17`. The effect of this is not only that mistyped urls won't be fixed for you, but (and this is much more of a problem) gitea relies on this mechanism internally. When referencing an issue/PR number in a commit message (eg. `foo bar baz (fix #17)`), gitea will add an anchor to this number on the website, which will always be of the form `/{user}/{repo}/issues/{number}`, even if the number referenced by the commit message is in fact a PR.

Steps to reproduce:
1. Visit this repo: https://git.tjdev.de/tjdev/dns-watch-2022
2. See the commit message `🩹 get reference list working (#17)`
3. Click on the green `#17`
4. Note how you get a 404 page
5. Now click on the _Pull Requests_ tab
6. See how there actually is a PR with number `#17`
7. Now if I would enable the issues tab for this repo, step 3 would actually take you to the correct PR page

### Gitea Version
1.24.5

### PR DESCRIPTION
**Pull request by lunny**
Fix #35419

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

File: tests/integration/issue_test.go [hunk 1]
```diff
@@ -487,6 +490,36 @@ func TestIssueRedirect(t *testing.T) {
...
+	assert.True(t, exist)
+	assert.NotNil(t, repoUnit)
+
+	_, err = db.DeleteByID[repo_model.RepoUnit](t.Context(), repoUnit.ID)
+	assert.NoError(t, err)
+
+	defer func() {
+		repoUnit.ID = 0
+		assert.NoError(t, db.Insert(t.Context(), repoUnit))
+	}()
```
Comment (wxiaoguang) [inline tests/integration/issue_test.go]: Database is reset between tests.

File: tests/integration/issue_test.go [hunk 2]
```diff
@@ -487,6 +490,36 @@ func TestIssueRedirect(t *testing.T) {
 	req = NewRequest(t, "GET", path.Join("org26", "repo_external_tracker_alpha", "issues", "1"))
 	resp = session.MakeRequest(t, req, http.StatusSeeOther)
 	assert.Equal(t, "/"+path.Join("org26", "repo_external_tracker_alpha", "pulls", "1"), test.RedirectURL(resp))
+
+	// test to check that the PR redirection works if the issue unit is disabled
+	// repo1 is a normal repository with issue unit enabled, visit issue 2(which is a pull request)
+	// will redirect to pulls
+	req = NewRequest(t, "GET", path.Join("user2", "repo1", "issues", "2"))
+	resp = session.MakeRequest(t, req, http.StatusSeeOther)
+	assert.Equal(t, "/"+path.Join("user2", "repo1", "pulls", "2"), test.RedirectURL(resp))
```
Comment (wxiaoguang) [inline tests/integration/issue_test.go]: Why not just simply write  `"/user2/repo1/pulls/2`? Does the "path.Join" look more modern?

File: tests/integration/issue_test.go [hunk 3]
```diff
@@ -487,6 +490,36 @@ func TestIssueRedirect(t *testing.T) {
...
+
+	// disable issue unit
+	repoUnit, exist, err := db.Get[repo_model.RepoUnit](t.Context(), builder.Eq{
+		"repo_id": 1,
+		"type":    unit.TypeIssues,
+	})
```
Comment (wxiaoguang) [inline tests/integration/issue_test.go]: Why `unittest.AssertExistsAndLoadBean` doesn't work?

Comment (lunny) [reply tests/integration/issue_test.go]: 1f0e11b225

File: tests/integration/issue_test.go (hunk 2 above)
Comment (lunny) [reply tests/integration/issue_test.go]: 1f0e11b225

File: tests/integration/issue_test.go (hunk 1 above)
Comment (lunny) [reply tests/integration/issue_test.go]: 1f0e11b225

File: tests/integration/issue_test.go [hunk 4]
```diff
@@ -474,19 +476,42 @@ func TestIssueRedirect(t *testing.T) {
...
+
+	// even if the issue unit is disabled, visiting an issue which is a pull request
+	// will still redirect to pull request
+	req = NewRequest(t, "GET", "/user2/repo1/issues/2")
+	resp = session.MakeRequest(t, req, http.StatusSeeOther)
+	assert.Equal(t, "/user2/repo1/pulls/2", test.RedirectURL(resp))
+
+	// cleanup, re-enable issue unit
+	repoUnit.ID = 0
+	assert.NoError(t, db.Insert(t.Context(), repoUnit))
```
Comment (wxiaoguang) [inline tests/integration/issue_test.go]: Why you need to do this?


Image

Comment (lunny) [reply tests/integration/issue_test.go]: beb7e50f80

**Review by hiifong — APPROVED** [review]
