### PR TITLE
Fix sort order for organization home and user profile page

### LINKED ISSUE #31916: Orga: sort projects by size isn't working
### Description

Go to orga with some projects. Sort by size (small, big) isn't working. Instead "shortly updated" is selected.

image

It it's not implementen than remove or hide the both options.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.46.0

### Operating System

Ubuntu 22.04.4 LTS x86_64

### How are you running Gitea?

gitea-1.22.1-linux-amd64

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by yp05327**
Fix #31916

In #30876, `sortOrder` has been changed into a map, but it is only implemented in explore.
~~But it seems that size sort order has no effect from long long ago,~~ not directly caused by the PR above.

I think it is still caused by #29231.
In #29231, it merged the sort orders from `templates/explore/repo_search.tmpl` and `templates/admin/repo/search.tmpl`.
In `templates/admin/repo/search.tmpl`, it contains size sort orders, but not in `templates/explore/repo_search.tmpl`, which is used in non-admin pages.
So `order by size` is added from #29231, but the handler was not added.
~~So maybe we should manually backport this fix to 1.22.~~
Backport: #31922

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: routers/web/org/home.go [hunk 1]
```diff
@@ -48,32 +48,20 @@ func Home(ctx *context.Context) {
...
+		sortOrder = setting.UI.ExploreDefaultSort
+	}
+
+	if order, ok := repo_model.OrderByFlatMap[sortOrder]; ok {
+		orderBy = order
+	} else {
+		sortOrder = "recentupdate"
 		orderBy = db.SearchOrderByRecentUpdated
 	}
+	ctx.Data["SortType"] = sortOrder
```
Comment (wxiaoguang) [inline routers/web/org/home.go]: I think it could be as simple as:

```suggestion
	sortOrder := ctx.FormString("sort")
	if _, ok := repo_model.OrderByFlatMap[sortOrder]; !ok {
		sortOrder = setting.UI.ExploreDefaultSort // TODO: add new default sort order for org home?
	}
	ctx.Data["SortType"] = sortOrder
	orderBy = repo_model.OrderByFlatMap[sortOrder]
```

And everything should work well.

Comment (yp05327) [reply routers/web/org/home.go]: It seems good, but is it ok to remove `strings.ToLower`?

Comment (wxiaoguang) [reply routers/web/org/home.go]: Why it needs `strings.ToLower`?

Comment (yp05327) [reply routers/web/org/home.go]: It comes from https://github.com/go-gitea/gitea/pull/30876/files#diff-2223ddaf610a594e44153435be6477904e56dbfca54317b35e7ada231a9ab7faR61

Comment (wxiaoguang) [reply routers/web/org/home.go]: How could it be right?

Comment (yp05327) [reply routers/web/org/home.go]: Maybe user will input the URL manually? Then we can adjust the value which maybe wrong.
I think there are no big differences, so I also added it here.

@6543 
Why did you add `strings.ToLower` in #30876. 🤔

Comment (6543) [reply routers/web/org/home.go]: because it's  also used in the api witch where we do not control the sort paramerter, so to make the api option more resiliant it is used.

here as we should control the var via our own frontend, it is not nessesary, through you could argue input sanitazation never hurts (if not to resource intensive...)

Comment (6543) [reply routers/web/org/home.go]: @yp05327 https://github.com/go-gitea/gitea/pull/31951 well looking twice i noticed that it was on the wrong place ...

File: routers/web/user/profile.go [hunk 2]
```diff
@@ -110,32 +110,19 @@ func prepareUserProfileTabData(ctx *context.Context, showPrivate bool, profileDb
...
+		sortOrder = setting.UI.ExploreDefaultSort
+	}
+
+	if order, ok := repo_model.OrderByFlatMap[sortOrder]; ok {
+		orderBy = order
+	} else {
+		sortOrder = "recentupdate"
 		orderBy = db.SearchOrderByRecentUpdated
 	}
+	ctx.Data["SortType"] = sortOrder
```
Comment (6543) [inline routers/web/user/profile.go]:
```suggestion
	sortOrder := ctx.FormString("sort")
	if _, ok := repo_model.OrderByFlatMap[sortOrder]; !ok {
		sortOrder = setting.UI.ExploreDefaultSort // TODO: add new default sort order for org home?
	}
	ctx.Data["SortType"] = sortOrder
	orderBy = repo_model.OrderByFlatMap[sortOrder]
```

**Review by 6543 — APPROVED** [review]

File: routers/web/user/profile.go (hunk 2 above)
Comment (wxiaoguang) [reply routers/web/user/profile.go]: The comment is wrong.

It is for "user profile", not "org home"

Comment (6543) [reply routers/web/user/profile.go]: c0db47bf9b6eb59d822ad21b7dd8b1d6acd8ad8e
