### PR TITLE
If rendering has failed due to a net.OpError stop rendering

### LINKED ISSUE #18629: Error: invalid memory address or nil pointer dereference
### Gitea Version

1.16-rc1

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Compiled from source.

### Database

_No response_

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

A single case was caught:

```
2022/02/05 21:20:50 ...s/context/context.go:377:JSON() [E] Render JSON failed: write tcp giteahostip:3000->clientip:52624: write: connection reset by peer
2022/02/05 21:20:50 ...common/middleware.go:70:1() [E] PANIC: runtime error: invalid memory address or nil pointer dereference
    /usr/lib/go-1.17/src/runtime/panic.go:221 (0x44dc66)
    /usr/lib/go-1.17/src/runtime/signal_unix.go:735 (0x44dc36)
    /src/somepath/gitea-build/modules/context/context.go:201 (0x14d2083)
    /src/somepath/gitea-build/modules/context/context.go:273 (0x14d2ae9)
    /src/somepath/gitea-build/modules/context/context.go:261 (0x14d479b)
    /src/somepath/gitea-build/modules/context/context.go:377 (0x14d477f)
    /src/somepath/gitea-build/routers/api/v1/repo/repo.go:239 (0x1daf584)
    /src/somepath/gitea-build/modules/web/route.go:80 (0x1cb0f66)
    /usr/lib/go-1.17/src/net/http/server.go:2047 (0x77ba4e)
    /pkg/mod/github.com/go-chi/chi/v5@v5.0.4/mux.go:442 (0x14c6a15)
    /usr/lib/go-1.17/src/net/http/server.go:2047 (0x77ba4e)
    /src/somepath/gitea-build/modules/web/route.go:144 (0x1cb1a4d)
    /usr/lib/go-1.17/src/net/http/server.go:2047 (0x77ba4e)
    /src/somepath/gitea-build/modules/web/route.go:144 (0x1cb1a4d)
    /usr/lib/go-1.17/src/net/http/server.go:2047 (0x77ba4e)
    /src/somepath/gitea-build/modules/context/api.go:307 (0x14ced5a)
    /usr/lib/go-1.17/src/net/http/server.go:2047 (0x77ba4e)
    /src/somepath/gitea-build/routers/api/v1/api.go:1107 (0x1de2a33)
    /usr/lib/go-1.17/src/net/http/server.go:2047 (0x77ba4e)
    /pkg/mod/gitea.com/go-chi/session@v0.0.0-20211218221615-e3605d8b28b8/session.go:257 (0x12cbf3d)
    /usr/lib/go-1.17/src/net/http/server.go:2047 (0x77ba4e)
    /pkg/mod/github.com/go-chi/chi/v5@v5.0.4/mux.go:71 (0x14c484c)
    /pkg/mod/github.com/go-chi/chi/v5@v5.0.4/mux.go:314 (0x14c61fb)
    /usr/lib/go-1.17/src/net/http/server.go:2047 (0x77ba4e)
    /pkg/mod/github.com/go-chi/chi/v5@v5.0.4/mux.go:442 (0x14c6a15)
    /usr/lib/go-1.17/src/net/http/server.go:2047 (0x77ba4e)
    /src/somepath/gitea-build/routers/common/middleware.go:78 (0x1ce80e1)
    /usr/lib/go-1.17/src/net/http/server.go:2047 (0x77ba4e)
    /pkg/mod/github.com/go-chi/chi/v5@v5.0.4/middleware/strip.go:30 (0x1ce2bb8)
    /usr/lib/go-1.17/src/net/http/server.go:2047 (0x77ba4e)
    /pkg/mod/github.com/chi-middleware/proxy@v1.1.1/middleware.go:37 (0x1cdf476)
    /usr/lib/go-1.17/src/net/http/server.go:2047 (0x77ba4e)
    /src/somepath/gitea-build/routers/common/middleware.go:31 (0x1ce7f39)
    /usr/lib/go-1.17/src/net/http/server.go:2047 (0x77ba4e)
    /pkg/mod/github.com/go-chi/chi/v5@v5.0.4/mux.go:88 (0x14c4801)
    /src/somepath/gitea-build/modules/web/route.go:328 (0x1cb42ed)
    /usr/lib/go-1.17/src/net/http/server.go:2879 (0x77efba)
    /usr/lib/go-1.17/src/net/http/server.go:1930 (0x77ab27)
    /usr/lib/go-1.17/src/runtime/asm_amd64.s:1581 (0x46ad60)
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by zeripath**
When a net.OpError occurs during rendering the underlying connection is essentially
dead and therefore attempting to render further data will only cause further errors.

Therefore in serverErrorInternal detect if the passed in error is an OpError and
if so do not attempt any further rendering.

Fix #18629

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: modules/context/context.go [hunk 1]
```diff
@@ -265,6 +267,12 @@ func (ctx *Context) ServerError(logMsg string, logErr error) {
 func (ctx *Context) serverErrorInternal(logMsg string, logErr error) {
 	if logErr != nil {
 		log.ErrorWithSkip(2, "%s: %v", logMsg, logErr)
+		if errors.Is(logErr, &net.OpError{}) {
```
Comment (6543) [inline modules/context/context.go:270]:
```suggestion
		if errors.Is(logErr, net.OpError) {
```
shouldn't work this too ?

Comment (zeripath) [reply modules/context/context.go:270]: That won't compile. 

`net.OpError` is a `type` not an `error`, (`net.OpError` doesn't implement `error` either, `*net.OpError` would be the type that implements the `error` interface but is again a `type` not an `error`.)

**Review by 6543 — APPROVED** [review]

File: modules/context/context.go (hunk 1 above)
Comment (Gusted) [reply modules/context/context.go:270]: For what's worth: go internally also use this error as a pointer: https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/internal/poll/error_test.go#L38 Approving.

**Review by Gusted — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:
