### PR TITLE
When the title in the issue has a value, set the text cursor at the end of the text.

### LINKED ISSUE #25055: Place text cursor in title field in template based issue after specified default value
### Description

When adding a default value for the title in an issue template, the text cursor is set to the beginning of title's input instead of the end.

```
name: 🐞 Bug Report
about: File a bug report
title: "[Bug] "
labels:
- Type/Bug
```

### Screenshots

Current:
image

Preferred:
image

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

_No response_

### Browser Version

firefox

### PR DESCRIPTION
**Pull request by HEREYUA**
Fix:  [#25055](https://github.com/go-gitea/gitea/issues/25055)

Before

image

After

image

ps:I've noticed that we are gradually replacing jQuery, so I didn't use jQuery here.

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: web_src/js/features/repo-issue.js [hunk 1]
```diff
@@ -331,6 +331,14 @@ export function initRepoIssueReferenceRepositorySearch() {
     });
 }
 
+export function initRepoIssueTitleFocus() {
+  const issueTtitle = document.getElementById('issue_title');
+  if (issueTtitle) {
+    issueTtitle.focus();
+    issueTtitle.setSelectionRange(issueTtitle.value.length, issueTtitle.value.length);
+  }
```
Comment (silverwind) [inline web_src/js/features/repo-issue.js]:
```suggestion
  const issueTitle = document.getElementById('issue_title');
  if (issueTitle) {
    issueTitle.focus();
    issueTitle.setSelectionRange(issueTitle.value.length, issueTitle.value.length);
  }
```

File: templates/repo/issue/new_form.tmpl [hunk 2]
```diff
@@ -9,7 +9,7 @@
 				{{ctx.AvatarUtils.Avatar .SignedUser 40}}
 				<div class="ui segment content tw-my-0">
 					<div class="field">
-						<input name="title" id="issue_title" placeholder="{{ctx.Locale.Tr "repo.milestones.title"}}" value="{{if .TitleQuery}}{{.TitleQuery}}{{else if .IssueTemplateTitle}}{{.IssueTemplateTitle}}{{else}}{{.title}}{{end}}" autofocus required maxlength="255" autocomplete="off">
+						<input name="title" id="issue_title" placeholder="{{ctx.Locale.Tr "repo.milestones.title"}}" value="{{if .TitleQuery}}{{.TitleQuery}}{{else if .IssueTemplateTitle}}{{.IssueTemplateTitle}}{{else}}{{.title}}{{end}}"  required maxlength="255" autocomplete="off">
```
Comment (silverwind) [inline templates/repo/issue/new_form.tmpl]:
```suggestion
						<input name="title" id="issue_title" placeholder="{{ctx.Locale.Tr "repo.milestones.title"}}" value="{{if .TitleQuery}}{{.TitleQuery}}{{else if .IssueTemplateTitle}}{{.IssueTemplateTitle}}{{else}}{{.title}}{{end}}" required maxlength="255" autocomplete="off">
```

Comment (HEREYUA) [reply templates/repo/issue/new_form.tmpl]: updated

File: web_src/js/features/repo-issue.js (hunk 1 above)
Comment (HEREYUA) [reply web_src/js/features/repo-issue.js]: updated

File: web_src/js/features/repo-issue.js [hunk 3]
```diff
@@ -331,6 +331,14 @@ export function initRepoIssueReferenceRepositorySearch() {
     });
 }
 
+export function initRepoIssueTitleFocus() {
+  const issueTitle = document.getElementById('issue_title');
```
Comment (wxiaoguang) [inline web_src/js/features/repo-issue.js]: Instead of hard-coding `issue_title` here, I would suggest to introduce a general CSS selector:

```
<input type="js-auto-focus-end ...">
```

File: templates/repo/issue/new_form.tmpl [hunk 4]
```diff
@@ -9,7 +9,7 @@
 				{{ctx.AvatarUtils.Avatar .SignedUser 40}}
 				<div class="ui segment content tw-my-0">
 					<div class="field">
-						<input name="title" id="issue_title" placeholder="{{ctx.Locale.Tr "repo.milestones.title"}}" value="{{if .TitleQuery}}{{.TitleQuery}}{{else if .IssueTemplateTitle}}{{.IssueTemplateTitle}}{{else}}{{.title}}{{end}}" autofocus required maxlength="255" autocomplete="off">
+						<input name="title" id="issue_title" placeholder="{{ctx.Locale.Tr "repo.milestones.title"}}" value="{{if .TitleQuery}}{{.TitleQuery}}{{else if .IssueTemplateTitle}}{{.IssueTemplateTitle}}{{else}}{{.title}}{{end}}" required maxlength="255" autocomplete="off">
```
Comment (wxiaoguang) [inline templates/repo/issue/new_form.tmpl]:
```suggestion
						<input name="title" id="issue_title" class="js-autofocus-end" placeholder="{{ctx.Locale.Tr "repo.milestones.title"}}" value="{{if .TitleQuery}}{{.TitleQuery}}{{else if .IssueTemplateTitle}}{{.IssueTemplateTitle}}{{else}}{{.title}}{{end}}" required maxlength="255" autocomplete="off">
```

File: web_src/js/features/repo-issue.js [hunk 5]
```diff
@@ -331,6 +331,14 @@ export function initRepoIssueReferenceRepositorySearch() {
...
+  if (issueTitle) {
+    issueTitle.focus();
+    issueTitle.setSelectionRange(issueTitle.value.length, issueTitle.value.length);
+  }
```
Comment (wxiaoguang) [inline web_src/js/features/repo-issue.js]:
```suggestion
  for (el of document.querySelectorAll("js-autofocus-end")) {
    el.focus(); // expects only one such element on one page. If there are many, then the last one gets the focus.
    el.setSelectionRange(issueTitle.value.length, issueTitle.value.length);
  }
```

**Review by wxiaoguang — COMMENTED** [review]
By using `js-auto-focus-end`, it works for more cases, and no need to hard depend the input id.

File: web_src/js/features/repo-issue.js (hunk 3 above)
Comment (silverwind) [reply web_src/js/features/repo-issue.js]: I wonder if we could keep the DOM `autofocus` property, detect when it runs and then just set the cursor to the right position when a class like `js-autofocus-end` is present. That should in theory also work for content appended to DOM via JS, unlike a `querySelector`-based solution which wouldn't.

**Comment by silverwind** [comment]
Call it `js-autofocus-end`. There is no `-` in the [HTML prop](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus).

File: web_src/js/features/repo-issue.js (hunk 3 above)
Comment (silverwind) [reply web_src/js/features/repo-issue.js]: Not sure if it's possible to detect autofocus in JS. One could install a `focus` event listener on `document.body` but the problem will be telling apart a autofocus from a regular user interaction.

Comment (silverwind) [reply web_src/js/features/repo-issue.js]: Yeah no I think trying to detect autofocus is a hopeless effort. Would suggest to follow @wxiaoguang and add this simple class that will manually focus the first matching element on page load.

Comment (HEREYUA) [reply web_src/js/features/repo-issue.js]: Updated

**Review by wxiaoguang — APPROVED** [review]
