### PR TITLE
Fix commit sha1 URL rendering in markdown

### LINKED ISSUE #1667: Issues: Commit hash not parsed
Commit hashes in issue comments, are not parsed correctly, when the hash is in the same line as some other text.

An example of this can be seen here https://try.gitea.io/jeppech/test/issues/3

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #1667

### CODE REVIEW

File: modules/markdown/markdown_test.go [hunk 1]
```diff
@@ -296,6 +296,7 @@ func TestRender_Commits(t *testing.T) {
 	test(sha, `<p><a href="`+commit+`" rel="nofollow">b6dd6210ea</a></p>`)
 	test(commit, `<p><a href="`+commit+`" rel="nofollow">b6dd6210ea</a></p>`)
 	test(tree, `<p><a href="`+src+`" rel="nofollow">b6dd6210ea/src</a></p>`)
+	test("commit "+sha, `<p>commit <a href="`+commit+`" rel="nofollow">b6dd6210ea</a></p>`)
```
Comment (sapk) [inline modules/markdown/markdown_test.go:299]: I won't ask for this PR but it would be better if the short sha is not hardcoded but derived from sha in test result (in the future ^^).

File: modules/markdown/markdown.go [hunk 2]
```diff
@@ -542,7 +542,7 @@ func RenderCrossReferenceIssueIndexPattern(rawBytes []byte, urlPrefix string, me
 func renderSha1CurrentPattern(rawBytes []byte, urlPrefix string) []byte {
 	ms := Sha1CurrentPattern.FindAllSubmatch(rawBytes, -1)
 	for _, m := range ms {
-		all := m[0]
+		all := m[1]
```
Comment (sapk) [inline modules/markdown/markdown.go]: I think we should not call it `all` now that it right fully catch only the commitId/sha1.

**Comment by sapk** [comment]
I have made two comments that are non blocking just improvement. Otherwise LGTM.

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lafriks** [comment]
Changed variable name as requested :)
