### PR TITLE
Normalize guessed languages for code highlighting

### LINKED ISSUE #22443: FSharp highlighting incorrect
### Description

FSharp syntax highlighting is on two different servers (Codeberg and private Gitea instance) rendered incorrectly. 

The Chroma playground renderes it beautifully. 

### Screenshots

grafik
grafik

### Gitea Version

Current

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

_No response_

### Browser Version

Firefox 108.0.2

### PR DESCRIPTION
**Pull request by mrtz-j**
For when Enry correctly recognised the language, but returns the language name in a way that isn't recognized by chroma.

This resolves the issue that previously required the addition of a `.gitattributes` file containing the line `*.fs linguist-language=FSharp`.

Resolves https://github.com/go-gitea/gitea/issues/22443

### CODE REVIEW

File: modules/highlight/highlight.go [hunk 1]
```diff
@@ -195,6 +201,9 @@ func File(fileName, language string, code []byte) ([]template.HTML, string, erro
 
 	if lexer == nil {
 		guessLanguage := analyze.GetCodeLanguage(fileName, code)
+		if normalizedGuessLanguage, ok := normalizeEnryToChroma[guessLanguage]; ok {
+			guessLanguage = normalizedGuessLanguage
+		}
```
Comment (wxiaoguang) [inline modules/highlight/highlight.go]: ~~It seems that the logic should be in `analyze.GetCodeLanguage`, and test that function.~~

A function like `GetCodeLanguageForChroma` or `GetCodeLanguageForHighlighting` should be better.

Comment (mrtz-j) [reply modules/highlight/highlight.go]: I agree, I'll move the logic to `analyze` and add `analyze.GetCodeLanguageForChroma`.

**Comment by wxiaoguang** [comment]
Hmm, the problem is more complicated than it looks

The diff highlighting also depends on the "programming language"


So, the complete fix could be like this: add a helper function like `toChromaLanguage`, make `highlight.Code` and `highlight.File` call it.

File: modules/highlight/highlight.go [hunk 2]
```diff
@@ -88,6 +88,20 @@ func UnsafeSplitHighlightedLines(code template.HTML) (ret [][]byte) {
 	}
 }
 
+// For when Enry recognises the language,
+// but doesn't use the names that Chroma expects.
+var normalizeEnryToChroma = map[string]string{
```
Comment (delvh) [inline modules/highlight/highlight.go]: `enryToChroma`?

**Review by delvh — APPROVED** [review]

File: modules/highlight/highlight.go (hunk 2 above)
Comment (mrtz-j) [reply modules/highlight/highlight.go]: Sounds good to me.

**Comment by mrtz-j** [comment]
> Hmm, the problem is more complicated than it looks
> 
> The diff highlighting also depends on the "programming language"
> 
> So, the complete fix could be like this: add a helper function like `toChromaLanguage`, make `highlight.Code` and `highlight.File` call it.

Created the helper for both `highlight.File` and `highlight.Code` and update the tests to make them pass.

**Comment by wxiaoguang** [comment]
Will take a look. I just found a lot of legacy problems, will fix together.

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Done from my side, does the change look good to you?

**Comment by mrtz-j** [comment]
> Done from my side, does the change look good to you?
Yes, it looks good to me :)
