### PR TITLE
Fix bug when creating pull request

### LINKED ISSUE #20906: reloading the pull request creation page creates duplicate pull requests
### Description

See https://gitea.com/gitea/go-sdk/pulls: there are two identical pull requests: 

* https://gitea.com/gitea/go-sdk/pulls/598
* https://gitea.com/gitea/go-sdk/pulls/597

image

It happened while trying to submit a pull request while the gitea.com gateway was timeout (504 Gateway Time-out). Multiple requests were sent (reloading the URL creating the pull request with POST at https://gitea.com/gitea/go-sdk/compare/master...earl-warren/go-sdk:wip-issue-delete).

The final attempt showed a page explaining the pull request already exists:

image

But despite this safeguard two of the attempts raced against each other and created a duplicate. There is a race condition *somewhere*. An integration test trying to repeat these conditions would eventually run into this problem.

### Gitea Version

dev

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

a

### Screenshots

a

### Git Version

a

### Operating System

a

### How are you running Gitea?

a

### Database

_No response_

### LINKED ISSUE #35912: Unable to get commit comparasion data via API when Pull Request feature is disabled
### Description

The API endpoint `/repos/{owner}/{repo}/compare/{basehead}` fails to return commit comparison data (in the same branch) when the "Pull Requests" feature is disabled for a repository. The request returns an error: `{"errors":null,"message":"Can't read pulls or can't read UnitTypeCode","url":"https://xxx.com/api/swagger"}`.

However, commit comparison through the web interface continues to work normally.

Test it with this command:
```bash
curl -X 'GET' 'https://demo.gitea.com/api/v1/repos/dangjinghao/test-diff/compare/5b20aef62d...main' -H 'accept: application/json'
```
web: <https://demo.gitea.com/dangjinghao/test-diff/compare/5b20aef62d...main>

### Gitea Version

v1.25.1 and 1c8c565(latest commit)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

SQLite

### LINKED ISSUE #36116: unable to create a pull request from fork's fork
### Description

- when I create org1/repo
- and I create org2
- and I fork org1/repo to org2/repo
- and I create org3
- and I fork org2/repo to org3/repo (I tried with a different name first, but it doesn't matter)

Then creating a pull request using API from org3/repo to org1/repo fails with `{"message":"GetBaseRepo","url":"https://gitea.com/api/swagger","errors":null}`

WebUI seems to be working fine.

### Gitea Version

1.25.0~dev-623-ga4ccbc9291

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

https://demo.gitea.com/

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Extract from #36105 

Fix #36116
Fix #35912
Fix #20906

### CODE REVIEW

File: routers/common/compare.go [hunk 1]
```diff
@@ -20,3 +22,54 @@ type CompareInfo struct {
...
+			}
+			curRepo = curRepo.BaseRepo
+		}
+		return curRepo, nil
+	}
+
+	return findHeadRepoFromRootBase(ctx, baseRepo, headUserID, maxForkTraverseLevel)
+}
+
+func findHeadRepoFromRootBase(ctx context.Context, baseRepo *repo_model.Repository, headUserID int64, traverseLevel int) (*repo_model.Repository, error) {
```
Comment (Zettat123) [inline routers/common/compare.go:48]: If most fork repos were forked form the root base repo, will BFS be better?

**Review by Zettat123 — APPROVED** [review]

File: routers/common/compare.go (hunk 1 above)
Comment (lunny) [reply routers/common/compare.go:48]: If we are lucky, in most cases a forked repository will be compared against its immediate parent repository.

**Review by silverwind — APPROVED** [review]
