### PR TITLE
Fix an issue where changing an organization’s visibility caused problems when users had forked its repositories.

### LINKED ISSUE #37317: Unable to change organisation visibility with forks in user areas
### Description

Steps to produce
 
1) Create an organisation
2) Create a repository
3) Create a fork of that repository into a user’s account
3) Attempt to change the visibility of the organisation
 
What is expected
 
The organisation visibility should change
 
What actually happens
 
A popup saying ‘An error occurred’. In the debug log, it says the following:
 
ChangeOrganizationVisibility: updateOrgRepoForVisibilityChanged: updateRepoForVisibilityChanged[{fork-owner}/{fork-name}]: recalculateTeamAccesses: owner is not an organization: {fork-owner-id}
 
Suggested fix
 
The ‘updateOrgRepoForVisibilityChanged’ call in ‘/services/org/org.go’ (line 105) at the end of the function loops over the forked repositories and calls ‘updateOrgRepoForVisibilityChanged’ on each forked repository. If your forked repository is not in an organisation, then the error will appear. The reason for this is because that method calls ‘access_model.RecalculateTeamAccesses(…)’ and this throws an error if the repository is not owned be an organisation.
 
I would suggest that line 107 in ‘/services/org/org.go’ changes from ‘if err := access_model.RecalculateTeamAccesses(ctx, repo, 0); err != nil {‘ to the following:
 
if err := access_model.RecalculateAccesses(ctx, repo); err != nil {
 
This is because this method checks if the repository is owned by an organisation, and if it does, then it calls the ‘RecalculateTeamAccesses’ function anyway.

Not tested on demo server because it is overloaded.

### Gitea Version

1.25.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

N/a

### Screenshots

_No response_

### Git Version

2.43.7

### Operating System

Red hat

### How are you running Gitea?

Download from your website

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by lunny**
A quick fix #37317

---

The current behavior for forks when an organization or repository is changed to private differs from GitHub.

On GitHub, when a parent repository becomes private, the fork relationship is removed, which keeps the behavior simple and avoids visibility conflicts.

I think we need a similar solution to handle cases where the parent repository becomes private while a fork remains public and the fork relationship is still preserved.

### CODE REVIEW

**Comment by silverwind** [comment]
A couple of observations from a review pass, all non-blocking:

1. Stale error wrap: after switching from `RecalculateTeamAccesses` to `RecalculateAccesses`, the wrap string `"recalculateTeamAccesses: %w"` in `updateRepoForVisibilityChanged` is now misleading in logs.

2. Latent behavior surfaced by this fix (probably out of scope for the backport, but worth a follow-up): the recursion still runs the `makePrivate` block on user-owned forks when the org goes private — marking their `activities_model.Action` rows `is_private=true` and clearing their stars — even though the fork itself remains public. As the PR description notes, the proper fix is GitHub-style fork-relationship removal; flagging so it's not lost.

3. The new test asserts the visibility change succeeds but doesn't verify the resulting access-table state on the user-owned fork. Could be worth an extra assertion so a regression in the fork branch doesn't silently pass.

---
Review written with the help of Claude Opus 4.7.

**Review by silverwind — APPROVED** [review]

File: services/org/org.go [hunk 1]
```diff
@@ -102,9 +102,13 @@ func DeleteOrganization(ctx context.Context, org *org_model.Organization, purge
...
-func updateOrgRepoForVisibilityChanged(ctx context.Context, repo *repo_model.Repository, makePrivate bool) error {
+func updateRepoForVisibilityChanged(ctx context.Context, repo *repo_model.Repository, makePrivate bool) error {
+	if err := repo.LoadOwner(ctx); err != nil {
+		return fmt.Errorf("loadOwner: %w", err)
+	}
+
 	// Organization repository need to recalculate access table when visibility is changed.
-	if err := access_model.RecalculateTeamAccesses(ctx, repo, 0); err != nil {
+	if err := access_model.RecalculateAccesses(ctx, repo); err != nil {
 		return fmt.Errorf("recalculateTeamAccesses: %w", err)
```
Comment (silverwind) [inline services/org/org.go]:
```suggestion
		return fmt.Errorf("recalculateAccesses: %w", err)
```

**Review by Zettat123 — APPROVED** [review]
