### PR TITLE
Set Setpgid on child git processes

### LINKED ISSUE #19077: Defunct git processes when running Gitea as PID 1 on docker
### Gitea Version

1.15.7

### Git Version

2.34.1

### Operating System

OpenSuse Leap 15.3 (Docker) 

### How are you running Gitea?

I used an rpm built using the repo at https://build.opensuse.org/package/show/devel:tools:scm/gitea and installed with zypper.
I'm running in a docker container based on OpenSuse Leap 15.3, base os also OpenSuse Leap 15.3

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

I have zombie processes whose start time coincides with log entries such as below:
Upon updating my github login credentials, the zombie processes seem to no longer occur.
#13987 is documented as being fixed by #14006 in the 1.14.0 milestone, so I'm reporting this as a possible regression. I'm sorry I haven't been able to upgrade to the latest version to check if the issue still exists. If you need any additional information, please let me know.

```
2022/03/14 15:22:27 ...irror/mirror_pull.go:176:runSync() [E] Failed to update mirror repository &{21 2 Towa <nil> purchasevisualization PurchaseVisualization 購入品管理  2 https://:xxxxxx@github.com/Towa-Japan/PurchaseVisualization.git main 4 0 1 0 0 0 0 0 0 0 0 0 0 0 0 false false false true <nil> [] 0 map[] map[] [] <nil> false 0 <nil> false 0 <nil> 103641 <nil> <nil> false false [] default  1610340108 1647238881}:
        Stdout: Fetching origin

        Stderr: remote: Repository not found.
        fatal: Authentication failed for 'https://github.com/Towa-Japan/PurchaseVisualization.git/'
        error: Could not fetch origin

        Err: exit status 1
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by zeripath**
When Gitea is running as PID 1 git will occassionally orphan child processes leading
to (defunct) processes. This PR simply sets Setpgid to true on these child processes
meaning that these defunct processes will also be correctly reaped.

Fix #19077

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by delvh — APPROVED** [review]
Unfortunately don't have a windows machine to test.

**Review by singuliere — APPROVED** [review]

File: modules/git/command_windows.go [hunk 1]
```diff
@@ -0,0 +1,11 @@
+// Copyright 2016 The Gitea Authors. All rights reserved.
+// Use of this source code is governed by a MIT-style
+// license that can be found in the LICENSE file.
+
+//go:build windows
```
Comment (singuliere) [inline modules/git/command_windows.go]:
```suggestion
//go:build windows

import (
	"os/exec"
)
```

**Review by singuliere — APPROVED** [review]

File: modules/git/command_windows.go [hunk 2]
```diff
@@ -0,0 +1,15 @@
+// Copyright 2016 The Gitea Authors. All rights reserved.
```
Comment (techknowlogick) [inline modules/git/command_windows.go]:
```suggestion
// Copyright 2022 The Gitea Authors. All rights reserved.
```

File: modules/git/command_unix.go [hunk 3]
```diff
@@ -0,0 +1,16 @@
+// Copyright 2016 The Gitea Authors. All rights reserved.
```
Comment (techknowlogick) [inline modules/git/command_unix.go]:
```suggestion
// Copyright 2022 The Gitea Authors. All rights reserved.
```

File: modules/git/command_windows.go [hunk 4]
```diff
@@ -0,0 +1,15 @@
+// Copyright 2022 The Gitea Authors. All rights reserved.
+// Use of this source code is governed by a MIT-style
+// license that can be found in the LICENSE file.
+
+//go:build windows
+
```
Comment (zeripath) [inline modules/git/command_windows.go]:
```suggestion

package git

```

File: modules/git/command_windows.go [hunk 5]
```diff
@@ -0,0 +1,15 @@
...
+import (
+	"os/exec"
+)
+
+package git
```
Comment (zeripath) [inline modules/git/command_windows.go]:
```suggestion
```

**Comment by wxiaoguang** [comment]
Looks good to me while I think there could be a comment in code to remember the reason why it is needed.

And I am not sure whether there could be a case that: Gitea -> SubProcessA -> SubProcessB , then although SubProcessA is killed (and there is no defunct due to Setpgid), SubProcessB is still running for a long time (still somewhat resource leaking?).

**Comment by singuliere** [comment]
> Looks good to me while I think there could be a comment in code to remember the reason why it is needed.
> 
> And I am not sure whether there could be a case that: Gitea -> SubProcessA -> SubProcessB , then although SubProcessA is killed (and there is no defunct due to Setpgid), SubProcessB is still running for a long time (still somewhat resource leaking?).

You misunderstand the purpose of Setpgid, let me explain:

> although SubProcessA is killed (and there is no defunct due to Setpgid)...

SubProcessA is not defunct/zombie because Gitea waits for it, not because of Setpgid

> SubProcessB is still running for a long time...

the purpose of Setpgid is to make sure SubProcessB is also killed when SubProcessA is killed. For a more detailed explanation and a reproducer, please see https://hostea.org/blog/zombies/.

**Comment by wxiaoguang** [comment]
> > Looks good to me while I think there could be a comment in code to remember the reason why it is needed.
> > And I am not sure whether there could be a case that: Gitea -> SubProcessA -> SubProcessB , then although SubProcessA is killed (and there is no defunct due to Setpgid), SubProcessB is still running for a long time (still somewhat resource leaking?).
> 
> You misunderstand the purpose of Setpgid, let me explain:
> 
> > although SubProcessA is killed (and there is no defunct due to Setpgid)...
> 
> SubProcessA is not defunct/zombie because Gitea waits for it, not because of Setpgid
> 
> > SubProcessB is still running for a long time...
> 
> the purpose of Setpgid is to make sure SubProcessB is also killed when SubProcessA is killed. For a more detailed explanation and a reproducer, please see https://hostea.org/blog/zombies/.

I didn't misunderstand and I know how zombie/defunct works & occurs.

I mean: when Gitea wants to kill SubProcessA, it's better to do a group kill, and try to make the SubProcessA do `waitpid` correctly for SubProcessB, then no `setpgid` is needed and it might be more clear. And there is no long-running SubProcessB anymore. It's my feeling but I am not sure whether it's easy to make the the `kill` correct. `waitpid` is always the proper answer for defunct processes.

**Comment by wxiaoguang** [comment]
```go
func main() {
	c := exec.Command("/bin/bash", "-c", `echo "sleep 100000" | bash`)
	c.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	fmt.Printf("run err = %v", c.Run())
}
```

```
go run test-setpgid.go
pstree
 |      \-+- 86853 user test-setpgid
 |       \-+= 86855 user /bin/bash -c echo "sleep 100000" | bash
 |         \-+- 86857 user bash
 |           \--- 86858 user sleep 100000

kill 86855

pstree
 |-+- 86857 xiaoguang bash
 | \--- 86858 xiaoguang sleep 100000
```

**Comment by singuliere** [comment]
```
kill -9 -- -86855
```
Would have worked as intended.

**Comment by singuliere** [comment]
```
package main

import (
	"fmt"
	"os/exec"
	"syscall"
	"time"
)

func main() {
	c := exec.Command("/bin/bash", "-c", `echo "sleep 100000" | bash`)
	c.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	c.Start()
	fmt.Println("running err = ", c.Process.Pid)
	time.Sleep(5 * time.Second)
	syscall.Kill(-c.Process.Pid, syscall.SIGKILL)
	fmt.Println("run err = ", c.Wait())
}
```

**Comment by wxiaoguang** [comment]
Then, does Gitea use your `syscall.Kill` in `modules/git/command.go` or `modules/process/manager_exec.go`? Or Gitea just simply uses contexts with deadlines?

**Comment by zeripath** [comment]
This PR is not designed to kill children - but to simply allow for them to be reaped. 

We need to check that this does stop the (defunct) processes from occuring.

**Comment by wxiaoguang** [comment]
> This PR is not designed to kill children - but to simply allow for them to be reaped.
> We need to check that this does stop the (defunct) processes from occuring.

I know, my comment was about `SubProcessB is still running for a long time (still somewhat resource leaking?)`, but singuliere has misunderstanding about how setpgid/kill/waitpid work. So I just made some examples for him. It's not a blocker from my side while I think the purpose/context of this PR could be clarified by comments.

And my comment was `Looks good to me while I think there could be a comment in code to remember the reason why it is needed`, I think there could be some detailed comments for the `setpgid` to make future developers know why it is here and what problem it resolves, and make new developers know how setpgid works.

File: modules/process/manager_unix.go [hunk 6]
```diff
@@ -0,0 +1,17 @@
...
+package process
+
+import (
+	"os/exec"
+	"syscall"
+)
+
+// SetSysProcAttribute sets the common SysProcAttrs for commands
+func SetSysProcAttribute(cmd *exec.Cmd) {
+	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
```
Comment (wxiaoguang) [inline modules/process/manager_unix.go:17]:
```suggestion
	// When Gitea runs SubProcessA -> SubProcessB and SubProcessA gets killed by context timeout, use setpgid to make sure the sub processes can be reaped instead of leaving defunct(zombie) processes.
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
```

(correct me if its wrong or inaccurate)

**Comment by singuliere** [comment]
> ... but singuliere has misunderstanding about how setpgid/kill/waitpid work. So I just made some examples for him.

This is not true: everything I wrote on the topic of setpgid/kill/waitpid is perfectly accurate.

**Comment by wxiaoguang** [comment]
> > ... but singuliere has misunderstanding about how setpgid/kill/waitpid work. So I just made some examples for him.
> 
> This is not true: everything I wrote on the topic of setpgid/kill/waitpid is perfectly accurate.

Maybe you can think more about your comment: `the purpose of Setpgid is to make sure SubProcessB is also killed when SubProcessA is killed`: does Gitea use your `syscall.Kill` in `modules/git/command.go` or `modules/process/manager_exec.go`? Or Gitea just simply uses contexts with deadlines? How does your perfectly accurate understanding answer the `SubProcessB long-running` problem?

**Comment by zeripath** [comment]
I think @singuliere was meaning about `kill -PID` vs `kill PID`. It's my fault for not being clearer in the opening comment on the PR. 

I guess we should move on. I'm not sure that we want to necessarily always kill children of processes - there will be a lot of cases where we would want that but I would bet that there are many cases where that would not be ideal. 

So ... I'm glad that putting it in a process group only means it gets inherited by Gitea and reaped in a PID1 situation - but that it also allows one to do a `kill -PID` to get rid of Gitea and all of its children.

**Comment by singuliere** [comment]
> > > ... but singuliere has misunderstanding about how setpgid/kill/waitpid work. So I just made some examples for him.
> > 
> > 
> > This is not true: everything I wrote on the topic of setpgid/kill/waitpid is perfectly accurate.
> 
> Maybe you can think more about your comment: `the purpose of Setpgid is to make sure SubProcessB is also killed when SubProcessA is killed`: does Gitea use your `syscall.Kill` in `modules/git/command.go` or `modules/process/manager_exec.go`? Or Gitea just simply uses contexts with deadlines? How does your perfectly accurate understanding answer the `SubProcessB long-running` problem?

I do not understand why you insist so much to prove me wrong when I'm not. I contributed valuable expertise to this conversation and I have more to say. But each of my comment is met with rejection from you, a few times without any justification or logic. This creates a hostile environment where I feel unappreciated. I ran out of patience and will move on.

**Comment by wxiaoguang** [comment]
Of course I agree to move on. In my first time I have said "look good to me", and the question is clear enough.

I have been very patience (with demo code) to tell you the background and fact, and because you started the `misunderstood` topic first.

**Comment by singuliere** [comment]
This is going too far.

> Have I ever rejected your comment in the first 2 replies?

Yes, you did, in the message below, which I received as a GitHub notification.

And it appears you deleted that message from GitHub afterwards, but not before GitHub broadcasted it to all people subscribed to this issue. You have to be very careful when you try to rewrite history and claim that you did not write what you wrote.

---

> >  @singuliere 
> >
> >     You misunderstand the purpose of Setpgid, let me explain:
> > 
> >         although SubProcessA is killed (and there is no defunct due to Setpgid)...
> > 
> > 
> >     SubProcessA is not defunct/zombie because Gitea waits for it, not because of Setpgid
> > 
> >         SubProcessB is still running for a long time...
> > 
> > 
> >     the purpose of Setpgid is to make sure SubProcessB is also killed when SubProcessA is killed. For a more detailed explanation and a reproducer, please see https://hostea.org/blog/zombies/.
> > 
>
> @wxiaoguang 
>
> I didn't misunderstand and I know how zombie/defunct works & occurs.
> 
> I mean: when Gitea wants to kill SubProcessA, it's better to do a group kill, and try to make the SubProcessA do `waitpid` correctly for SubProcessB, then no `setpgid` is needed and it might be more clear. And there is no long-running SubProcessB anymore. It's my feeling but I am not sure whether it's easy to make the the `kill` correct. `waitpid` is always the proper answer for defunct processes.

**Comment by zeripath** [comment]
Please stop both of you.
