### PR TITLE
Fix push-create SSH bugs

### LINKED ISSUE #10142: Create repo on push allows invalid names with slashes
- Gitea version (or commit ref): 1.11.0+rc2-17-g0129e76ef
- Git version: 2.20.1
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No ("Push to create is not enabled for users." and "Push to create is not enabled for organizations.")
  - [ ] Not relevant
- Log gist:

## Description
With `ENABLE_PUSH_CREATE_USER`, all of this works fine from the command line:
```bash
git init test
cd test
echo hi > README.md
git add README.md
git commit -m 'Initial commit'
git remote add origin git@git.example.com:jim/foo/bar/test.git
git push --set-upstream origin master     # this works
git pull     # this works
cd ..
git clone git@git.example.com:jim/foo/bar/test.git test2     # this works
```
And things look OK at first glance in the UI...

image

or 

image

**But** clicking on the repo pops up a browser auth prompt:

image

followed by a page saying just "invalid credentials".

I don't even know how to delete this repo now.  Related to #9175 I assume.

### LINKED ISSUE #10143: Cloning creates empty repositories
- Gitea version (or commit ref): 1.11.0+rc2-17-g0129e76ef
- Git version: 2.20.1
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No ("Push to create is not enabled for users." and "Push to create is not enabled for organizations.")
  - [ ] Not relevant
- Log gist:

## Description
With `ENABLE_PUSH_CREATE_USER`, it's not just pushing -- even cloning a nonexistent repository will create it:
```bash
$ git clone git@git.example.com:jim/did-not-exist
Cloning into 'did-not-exist'...
warning: You appear to have cloned an empty repository.
```
image

That ends up being really inconvenient, because a typo means you're creating empty repositories instead of getting a useful error.

It seems like this was maybe the subject of #9797?  But as far as I can tell that patch should already be included in the build I'm running.

### PR DESCRIPTION
**Pull request by jolheiser**
Fix #10142
Fix #10143

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Review by sapk — APPROVED** [review]

File: cmd/serv.go [hunk 1]
```diff
@@ -72,6 +73,7 @@ var (
 		"git-receive-pack":   models.AccessModeWrite,
 		lfsAuthenticateVerb:  models.AccessModeNone,
 	}
+	alphaDashDotPattern = regexp.MustCompile(`[^\w-\.]`)
```
Comment (sapk) [inline cmd/serv.go:76]: It feel that this should belong somewhere in models package or in modules/validation/.
But that a more global problem that input validation are scattered across gitea code.

**Comment by sapk** [comment]
@jolheiser please send backport

File: cmd/serv.go (hunk 1 above)
Comment (jolheiser) [reply cmd/serv.go:76]: I agree, when writing this I felt like it would be nice to have a central validation method, but when I looked this validation is actually in Macaron code and we use a binding for it.  
I think there's one other place that uses this pattern, but I forget what for off the top of my head.
