### PR TITLE
Make a.add-code-comment click handler an event handler

### LINKED ISSUE #17736: Cannot add code comment on file loaded with "Show More"
### Gitea Version

1.16.0+dev-564-gf380bc8a5

### Git Version

2.34.0

### Operating System

Windows

### How are you running Gitea?

Built myself

### Database

_No response_

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

Adding code comments to files loaded with "Show More" does not seem to be working.
Clicking the "+"  button does nothing. There are no errors in the browser console or gitea logs.

Cannot reproduce on try.gitea.io yet, because "Show More" doesn't work there (#17731).

### Screenshots

image

### PR DESCRIPTION
**Pull request by zeripath**
Instead of directly attaching the add-code-comment on click handler to
the a.add-code-comment elements - make this an event handler on the
document instead.

Fix #17736

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by jpraet — APPROVED** [review]
Validated.

There's one more related thing: when you click a direct link to such a comment (e.g. http://localhost:3000/jpraet/test/pulls/33/files#issuecomment-451) that was added on a file loaded with "Show More", that doesn't work because only the first x files are loaded.

**Review by lunny — APPROVED** [review]

File: web_src/js/features/repo-issue.js [hunk 1]
```diff
@@ -480,7 +480,7 @@ export function initRepoPullRequestReview() {
     $(this).closest('.menu').toggle('visible');
   });
 
-  $('a.add-code-comment').on('click', async function (e) {
+  $(document).on('click', 'a.add-code-comment', async function (e) {
```
Comment (delvh) [inline web_src/js/features/repo-issue.js:483]: Maybe we should add a comment here detailing why it is better to use a document listener here than a local listener, i.e.
```javascript
// We listen on the document instead of locally as files can be lazy-loaded at a later time
// and the listener would need to be added there as well
```
Otherwise, this issue might reoccur somewhen.
