### PR TITLE
Handle the error of a missing blob object fix #19530

### LINKED ISSUE #19530: PR Error 500 on CreateCsvDiff when trying to merge some branches: invalid memory address
### Description

Hello
We have a huge repo (800 branches, 6Gb lfs files, 12k commits, with branch protection) that we have migrated from Gitlab 2 weeks ago, on a Self hosted Gitea 1.16.5 with Pgsql

Since 2 days, some users encounters a 500 error when trying to create a pull request, there are some branches that generates this error 
I tested this on the 1.16.5 & 1.16.6 instances I have. We have not many other repo to test otherwise

**If we recreate the same branch with another name, the PR works as intended.**

short version log :

`2022/04/27 14:44:11 ...rs/web/repo/issue.go:751:setTemplateIfExists() [D] could not extract metadata fdev .gitea/pull_request_template.md [mainrepo/dev]: frontmatter must start with a separator line`

`2022/04/27 14:44:11 ...s/context/context.go:204:HTML() [D] Template: repo/diff/compare`

`2022/04/27 14:44:12 ...s/context/context.go:214:HTML() [E] Render failed: template: repo/diff/csv_diff:3:15: executing "repo/diff/csv_diff" at <call .root.CreateCsvDiff .file .root.BaseCommit .root.HeadCommit>: error calling call: runtime error: invalid memory address or nil pointer dereference`

`2022/04/27 14:44:12 ...s/context/context.go:204:HTML() [D] Template: status/500`

`2022/04/27 14:44:12 Completed GET /mainrepo/dev/compare/release/master...release/calibration 500 Internal Server Error in 1.331171119s`

### Gitea Version

1.16.5 / 1.16.6 / latest dev on master

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://try.gitea.io/99rgosse/issues/issues/1

### Screenshots

image

### Git Version

2.30.3

### Operating System

Docker Gitea with Ubuntu

### How are you running Gitea?

Docker official Gitea v.16.6
Caching enabled : 
```
[cache]
  | ENABLED  = true
  | ADAPTER  = memory
  | INTERVAL = 120
  | ITEM_TTL = 24h
  |  
  | [cache.last_commit]
  | ENABLED       = true
  | ITEM_TTL      = 8760h
  | COMMITS_COUNT = 7000
```

I tried :
- Removing the caching
- Removing the template generating errors

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by 99rgosse**
Following bug #19530 
this is a small hack to avoid a 500 Error when PR on blob objects missing : the error was not handled if it was other than a CSV Too large.

For context there is a missing blob on my repository that render a 500 Error when trying to Pull Request between two branches. Restoring the CSV File avoid the Error.

I have the feeling that has somehow something to do with https://github.com/go-gitea/gitea/blob/main/modules/git/tree_blob_nogogit.go
but I am not enough proficient with git cat-file to ensure the handle of objects.

### CODE REVIEW

File: routers/web/repo/compare.go [hunk 1]
```diff
@@ -150,6 +150,9 @@ func setCsvCompareContext(ctx *context.Context) {
 		if err == errTooLarge {
 			return CsvDiffResult{nil, err.Error()}
 		}
+		if err != nil {
+			return CsvDiffResult{nil, err.Error()}
```
Comment (wxiaoguang) [inline routers/web/repo/compare.go]: At the moment, the Error is rendered into page directly, I am not sure whether there is any guarantee that the general error doesn't contain sensitive information (eg: server path).

Ideally, at the moment, I think the log could be:

```
if err != nil {
  log.Error("....", err)
  return CsvDiffResult{nil, errors.New("csv diff error")}
}
```

Comment (99rgosse) [reply routers/web/repo/compare.go]: You're totally right, I just checked for my use case and I did not think of this...

File: routers/web/repo/compare.go [hunk 2]
```diff
@@ -150,6 +150,9 @@ func setCsvCompareContext(ctx *context.Context) {
 		if err == errTooLarge {
 			return CsvDiffResult{nil, err.Error()}
 		}
+		if err != nil {
+			return CsvDiffResult{nil, "csv diff error"}
```
Comment (wxiaoguang) [inline routers/web/repo/compare.go]:
```suggestion
		if err != nil {
			log.Error("CreateCsvDiff error: %v", err)
			return CsvDiffResult{nil, "csv diff error"}
```

**Review by wxiaoguang — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

File: routers/web/repo/compare.go [hunk 3]
```diff
@@ -150,6 +150,10 @@ func setCsvCompareContext(ctx *context.Context) {
 		if err == errTooLarge {
 			return CsvDiffResult{nil, err.Error()}
 		}
+		if err != nil {
+			log.Error("CreateCsvDiff error: %v", err)
```
Comment (zeripath) [inline routers/web/repo/compare.go]: It would be helpful to add more context here:

```go
			log.Error("CreateCsvDiff error whilst creating reader from file %s in commit %s in %s: %v", diffFile.Name, headCommit.ID().String, REPONAME, err)
```

**Review by zeripath — DISMISSED** [review]
the error message is lacking in sufficient detail to investigate the problem further. Please add more context.

**Comment by wxiaoguang** [comment]
Oh, one more thing, the returned `err` in `baseReader, baseBlobCloser, err` should also be check. This PR only checks the `err` in `headReader, headBlobCloser, err`.

**Review by lunny — APPROVED** [review]

File: routers/web/repo/compare.go (hunk 3 above)
Comment (6543) [inline routers/web/repo/compare.go]:
```suggestion
			log.Error("CreateCsvDiff error whilst creating reader from file %s in commit %s in %s: %v", diffFile.Name, headCommit.ID().String, REPONAME, err)
```

**Comment by wxiaoguang** [comment]
@zeripath I edited on this PR directly, now it should be nearly perfect.

**Comment by lunny** [comment]
@zeripath Need your approval.

**Review by 6543 — APPROVED** [review]

**Comment by wxiaoguang** [comment]
@99rgosse it seems that what we did in this PR is incorrect, the CreateCsvDiff is intended to handle nil head or nil base commit.

I have tried on my side without this PR's change (remove these err checks), then for added or deleted CSV files, the code works well. But this PR's change makes the diff for added/deleted CSV files report errors (see #21184).

So the question is, what's the root case of the 500 error on your side?

**Comment by 99rgosse** [comment]
> So the question is, what's the root case of the 500 error on your side?
The root case of the error 500 is from a missing CSV file 

Now that I see in the new PR that the "nil" blob could be handled, it should work as intended.

In any case, it's now fixed from our side ! thank you
