### PR TITLE
Ensure that relative paths in edit preview work

### LINKED ISSUE #10131: Relative links broken in preview mode
- Gitea version (or commit ref): 1.11.0+rc2-8-g4b11f967b
- Git version: 2.25.0
- Operating system: Debian Sid/Unstable
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/testuser78944/test-markdown/src/branch/master/a/doc.md)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When editing Markdown, links to other files in the repo are relative to the location of the file. However, when previewing changes, the rendered preview seem to render links from the repository root.

In the linked example, the link works as expected and links to https://try.gitea.io/testuser78944/test-markdown/src/branch/master/a/b/other.md. But try to edit the file and enable the preview mode: the link will be to https://try.gitea.io/testuser78944/test-markdown/src/branch/master/b/other.md instead (the `a/` part for the relative link is stripped).

## Screenshots

image

### PR DESCRIPTION
**Pull request by zeripath**
Fix #10131

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

File: web_src/js/index.js [hunk 1]
```diff
@@ -64,10 +64,16 @@ function initEditPreviewTab($form) {
     previewFileModes = $previewTab.data('preview-file-modes').split(',');
     $previewTab.on('click', function () {
       const $this = $(this);
+      let context = $this.data('context') + "/"
+      let treePathEl = $form.find('input#tree_path')
+      if (treePathEl) {
+        let val = treePathEl.val()
+        context += val.substring(0, val.lastIndexOf("/"))
```
Comment (silverwind) [inline web_src/js/index.js]: Maybe move the slash trimming outside the `if` block so it's always trimmed.

**Comment by silverwind** [comment]
Needs som linter fixes (semicolons, `const`).

File: web_src/js/index.js [hunk 2]
```diff
@@ -64,10 +64,16 @@ function initEditPreviewTab($form) {
...
+      }
       $.post($this.data('url'), {
         _csrf: csrf,
         mode: 'gfm',
-        context: $this.data('context'),
+        context: context,
```
Comment (silverwind) [inline web_src/js/index.js]:
```suggestion
        context,
```

**Comment by zeripath** [comment]
So that linter has actually done the impossible: it's made dealing with js even more bloody annoying.

File: web_src/js/index.js [hunk 3]
```diff
@@ -64,10 +64,16 @@ function initEditPreviewTab($form) {
     previewFileModes = $previewTab.data('preview-file-modes').split(',');
     $previewTab.on('click', function () {
       const $this = $(this);
+      let context = $this.data('context') + "/";
```
Comment (zeripath) [inline web_src/js/index.js]:
```suggestion
      let context = `{$this.data('context')}/`;
```

File: web_src/js/index.js [hunk 4]
```diff
@@ -64,10 +64,16 @@ function initEditPreviewTab($form) {
...
+      let treePathEl = $form.find('input#tree_path');
+      if (treePathEl) {
+        context += treePathEl.val();
+      }
+      context = context.substring(0, context.lastIndexOf("/"));
```
Comment (zeripath) [inline web_src/js/index.js]:
```suggestion
      context = context.substring(0, context.lastIndexOf('/'));
```

**Comment by silverwind** [comment]
@zeripath you should try an editor plugin for eslint, it's very fast.

File: web_src/js/index.js [hunk 5]
```diff
@@ -64,10 +64,16 @@ function initEditPreviewTab($form) {
     previewFileModes = $previewTab.data('preview-file-modes').split(',');
     $previewTab.on('click', function () {
       const $this = $(this);
+      let context = `{$this.data('context')}/`;
+      const treePathEl = $form.find('input#tree_path');
+      if (treePathEl) {
```
Comment (lafriks) [inline web_src/js/index.js]: Wouldn't this be safer?
```suggestion
      if (treePathEl.length > 0) {
```

**Review by silverwind — APPROVED** [review]

**Review by lafriks — APPROVED** [review]
