### PR TITLE
Fix issue title rendering and refactor legacy function names

### LINKED ISSUE #32700: Issue number no longer clickable in pr title
### Description

image

### Gitea Version

1.23.0+dev-739-g576e31ae3b

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #32700, regression of recent markup refactoring

And by the way, clarify many legacy problems:

1. Some "RenderXxx" functions do not really "render", they only call "post processors"
2. Merge "RenderEmoji | RenderCodeBlock", they are all for "simple issue title"

### CODE REVIEW

File: modules/templates/util_render.go [hunk 1]
```diff
@@ -114,6 +114,13 @@ func (ut *RenderUtils) RenderIssueTitle(text string, metas map[string]string) te
 	return template.HTML(renderedText)
 }
 
+// RenderIssueSimpleTitle only renders with emoji and inline code block
+func (ut *RenderUtils) RenderIssueSimpleTitle(text string) template.HTML {
+	ret := ut.RenderEmoji(text)
+	ret = renderCodeBlock(ret)
+	return ret
+}
```
Comment (silverwind) [inline modules/templates/util_render.go:122]: This could almost be used to render commit titles as well. I guess the only difference is that commit titles also render issue links.

Comment (wxiaoguang) [reply modules/templates/util_render.go:122]: No, commit subject has its own "render"

----

`PostProcessCommitMessageSubject`

**Review by lunny — APPROVED** [review]

**Review by silverwind — APPROVED** [review]
