### PR TITLE
Fix repo init README EOL

### LINKED ISSUE #27120: When creating the initial README.md from the project creation page, the text lines have CRLF line endings when the client is Windows, but Gitea is running in Linux
### Description

When creating the project description README.md file, the resulting file in the git has CRLF line endings on the part the is copied from the project description, when checking out in Linux the file is still using CRLF endings since no autoconversion is used.

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

when looking at the resulting file checked out on Linux, it looks like this:

image

### Git Version

2.30.2

### Operating System

ubuntu  22.04.2 LTS

### How are you running Gitea?

GITEA_WORK_DIR=$PWD/data/ ./gitea web -c $PWD/etc/app.ini -p 3003

### Database

sqlite

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #27120

By the way, refactor ReserveLineBreakForTextarea to NormalizeStringEOL

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: modules/util/util.go [hunk 1]
```diff
@@ -281,11 +281,13 @@ func EnumValue[T comparable](val EnumConst[T]) (ret T, valid bool) {
...
 	// It's a standard behavior of HTML.
-	// But we want to store them as \n like what GitHub does.
-	// And users are unlikely to really need to keep the \r.
+	// But in most cases, we only want "\n" for EOL
+	// * Text files: use "\n" by default because "\r\n" sometimes doesn't work in POSIX
+	// * Actions values: store them as "\n" like what GitHub does.
+	// And users are unlikely to really need the "\r".
 	// Other than this, we should respect the original content, even leading or trailing spaces.
-	return strings.ReplaceAll(input, "\r\n", "\n")
+	return UnsafeBytesToString(NormalizeEOL(UnsafeStringToBytes(input)))
```
Comment (silverwind) [inline modules/util/util.go:292]: Maybe small comment why "Unsafe" is safe?

Comment (wxiaoguang) [reply modules/util/util.go:292]: Underlying buffer is fully controlled by us

Comment (silverwind) [reply modules/util/util.go:292]: Ok, I wonder if codeql will still flag it 😆

**Review by silverwind — APPROVED** [review]
