### PR TITLE
Fix discord webhook 400 status code when description limit is exceeded

### LINKED ISSUE #34027: Discord Webhook Error 400
### Description

After updating Gitea my Discord notifications no longer work. I did not change any configuration in Gitea or on Discord. I am able to send a curl test message to my webhook. Sending a test message to my webhook gives the following response:

Error 400

Headers:
```
Alt-Svc: h3=":443"; ma=86400
Cf-Cache-Status: DYNAMIC
Cf-Ray: 925921e2cbde29f4-ORD
Connection: keep-alive
Content-Length: 17
Content-Security-Policy: frame-ancestors 'none'; default-src https://o64374.ingest.sentry.io; report-to csp-sentry; report-uri https://o64374.ingest.sentry.io/api/5441894/security/?sentry_key=8fbbce30bf5244ec9429546beef21870&sentry_environment=stable
Content-Type: application/json
Date: Mon, 24 Mar 2025 21:06:26 GMT
Nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=gv0YKk7DZRkzLUeOeIIe3DjLqo96N0rsQfe4HnAkZSz8HNyPhcArpL1IaW0D5WmklGjL84m8CW9i7iO1KsYn09pp1zP5St6ckyP%2BdZEHc%2FGG51Codu%2FkTQTcCsBk"}],"group":"cf-nel","max_age":604800}
Reporting-Endpoints: csp-sentry="https://o64374.ingest.sentry.io/api/5441894/security/?sentry_key=8fbbce30bf5244ec9429546beef21870&sentry_environment=stable"
Server: cloudflare
Set-Cookie: __dcfduid=d9524f7808f311f082f06270192b2772; Expires=Sat, 23-Mar-2030 21:06:26 GMT; Max-Age=157680000; Secure; HttpOnly; Path=/; SameSite=Lax,__sdcfduid=d9524f7808f311f082f06270192b2772f32aae96089add0fd9912b677ae84ac499c730e6dedb0e58c75c39d5a9e0c551; Expires=Sat, 23-Mar-2030 21:06:26 GMT; Max-Age=157680000; Secure; HttpOnly; Path=/; SameSite=Lax,__cfruid=e1415af9c0b0b3005bfc12025dbb9c5c3c2961eb-1742850386; path=/; domain=.discord.com; HttpOnly; Secure; SameSite=None,_cfuvid=t7_yGkV4LQLMJiX4rKOzBaoFyCSRCsOz_gWkGQ0xl2k-1742850386495-0.0.1.1-604800000; path=/; domain=.discord.com; HttpOnly; Secure; SameSite=None
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Via: 1.1 google
X-Content-Type-Options: nosniff
X-Ratelimit-Bucket: 3d2712a9e4fe17cc9d3fed4a8e672e5f
X-Ratelimit-Limit: 5
X-Ratelimit-Remaining: 4
X-Ratelimit-Reset: 1742850387
X-Ratelimit-Reset-After: 1
```

Body:

```
{"embeds": ["0"]}
```

I tried deleting the webhook in Gitea and recreating it but now when I click "Test Delivery" nothing happens and there is nothing in "Recent Deliveries". 

Edit: On further investigation it appears to be broken when changing the trigger from Push Events to Custom Events. My only marked Custom Event is "Release".

### Gitea Version

1.23.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker

### Database

None

### PR DESCRIPTION
**Pull request by Mopcho**
Fixes [#34027](https://github.com/go-gitea/gitea/issues/34027)

Discord does not allow for description bigger than 2048 bytes. If the description is bigger than that it will throw 400 and the event won't appear in discord. To fix that, in the createPayload method we now slice the description to ensure it doesn’t exceed the limit.

### CODE REVIEW

File: services/webhook/discord.go [hunk 1]
```diff
@@ -307,6 +309,9 @@ func parseHookPullRequestEventType(event webhook_module.HookEventType) (string,
 }
 
 func (d discordConvertor) createPayload(s *api.User, title, text, url string, color int) DiscordPayload {
+	if len(text) > discordDescriptionBytesLimit {
+		text = text[:discordDescriptionBytesLimit]
```
Comment (wxiaoguang) [inline services/webhook/discord.go]: It will break UTF8, there are some util functions: `util.TruncateRunes`

Comment (Mopcho) [reply services/webhook/discord.go]: Yep, I will change that up in a bit. I'm just trying to figure out how their limits work. The [documentation](https://discord.com/developers/docs/resources/message#embed-object-embed-limits) says the limit is: 4096 characters for the description, 6000 characters for the sum of all characters from all fields. However I can't seem to understand how they count them. When testing manually I found this: 

I can post 4096 "A", but I can't post 4097 "A"
I can post 2490  "🔷" , but I can't post 2491 "🔷"
I can't post 2489  "🔷" + 1 "A"

Doesn't seem to be bytes either as I can post 2490 🔷 and that is 9,960 bytes. Trying to figure this out currently.

Comment (wxiaoguang) [reply services/webhook/discord.go]: Maybe we don't need to make it too complex, for example: just truncate at 2000 characters and leave a comment there?

Comment (Mopcho) [reply services/webhook/discord.go]: Yeah, you're right. I truncate it now at 2000.

File: services/webhook/discord.go [hunk 2]
```diff
@@ -101,6 +101,8 @@ var (
 	redColor         = color("ff3232")
 )
 
+const discordDescriptionCharactersLimit = 2000
```
Comment (wxiaoguang) [inline services/webhook/discord.go:109]:
```suggestion
// https://discord.com/developers/docs/resources/message#embed-object-embed-limits
// Discord has some limits in place for the embeds.
// According to some tests, there is no consistent limit for different character sets.
// For example: 4096 ASCII letters are allowed, but only 2490 emoji characters are allowed.
// To keep it simple, we currently truncate at 2000.
const discordDescriptionCharactersLimit = 2000
```

Comment (Mopcho) [reply services/webhook/discord.go:109]: Added it

**Review by wxiaoguang — APPROVED** [review]

File: services/webhook/discord.go [hunk 3]
```diff
@@ -101,6 +101,13 @@ var (
 	redColor         = color("ff3232")
 )
 
+// https://discord.com/developers/docs/resources/message#embed-object-embed-limits
+// Discord has some limits in place for the embeds.
+// According to some tests, there is no consistent limit for different characet sets.
```
Comment (wxiaoguang) [inline services/webhook/discord.go]: Sorry I made a typo, will fix

```suggestion
// According to some tests, there is no consistent limit for different character sets.
```

**Review by lunny — APPROVED** [review]
