### PR TITLE
Run `detectWebAuthnSupport` only on sign-in page

### LINKED ISSUE #31675: All pages show error `JavaScript promise rejection: Cannot set properties of null (setting 'textContent').`
### Description

image

## How to reproduce

1. Start Gitea **WITHOUT** a [Secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), like `http://192.168.85.1:3000/`
   - No `https`.
   - No `127.0.0.1`, `localhost`, `*.localhost` 
2. Visit the sign-in page, and you will see a right warning about WebAuthn:
image

3. And visit any other pages (even the home page), you will see:
image
image

## Possible causes

It seems introduced by
- #31504

1. After `#31504`, every page will run `detectWebAuthnSupport`
image

2. And it emits error `insecure`
image

3. But it's not sign-in page, it cannot get `#webauthn-error-msg`, so it shows a strange error.
image

### Gitea Version

main (ad91a59c18)

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Command line.

### Database

None

### PR DESCRIPTION
**Pull request by wolfogre**
Fix #31675, regression of #31504.

### CODE REVIEW

**Review by KN4CK3R — APPROVED** [review]

File: web_src/js/features/user-auth-webauthn.ts [hunk 1]
```diff
@@ -5,6 +5,10 @@ import {GET, POST} from '../modules/fetch.ts';
 const {appSubUrl} = window.config;
 
 export async function initUserAuthWebAuthn() {
+  if (!document.querySelector('.user.signin')) {
```
Comment (wxiaoguang) [inline web_src/js/features/user-auth-webauthn.ts:8]: This check is not right because `link_account` also uses `signin_inner`

But I guess some logic has been broken for a while.

Comment (silverwind) [reply web_src/js/features/user-auth-webauthn.ts:8]: We should probably add a `data-page="user-signin"` attribute to `<body>` at some point to clearly indicate the which page we are on instead of relying on these flimsy selectors.

**Review by techknowlogick — APPROVED** [review]
+1 to the suggestion that we should add a page attribute rather than relying on the selectors. I think that this PR is a way to reduce the scope of the bug significantly while we do that refactor.

**Comment by silverwind** [comment]
Yes, that was just a suggestion for the future. But if the webauthn code runs in the `link_account` that would be a outstanding issue, thought not a blocker I guess.

File: web_src/js/features/user-auth-webauthn.ts (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/features/user-auth-webauthn.ts:8]: Are you serious? I am talking the logic bug.

**Comment by wxiaoguang** [comment]
Are you serious about the logic?

I am talking about the BUG, not about it should refactor or not.


image

**Comment by wxiaoguang** [comment]
> But if the webauthn code incorrectly runs on the `link_account` page that would be a outstanding issue, thought not a blocker I guess.

It is NOT "incorrectly runs on the `link_account` page". I have explained above: `signin_inner` is also used by `link_account` to "sign in".

**Comment by wolfogre** [comment]
> > But if the webauthn code incorrectly runs on the `link_account` page that would be a outstanding issue, thought not a blocker I guess.
> 
> It is NOT "incorrectly runs on the `link_account` page". I have explained above: `signin_inner` is also used by `link_account` to "sign in".

@wxiaoguang I think I got your point, the selector is wrong, what about #31691

File: web_src/js/features/user-auth-webauthn.ts (hunk 1 above)
Comment (silverwind) [reply web_src/js/features/user-auth-webauthn.ts:8]: I guess next time put a negative review, because otherwise, every PR runs danger of being merged too hastily.

And yes, my remark was just some idea for the future, but apparently @techknowlogick had read it incorrectly.
