### PR TITLE
Ensure topics added using the API are added to the repository

### LINKED ISSUE #12426: Topics added using API don't display on explore page
- Gitea version: 1.12.3
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 (xenial) LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
If you use the `/repos/{owner}/{repo}/topics/{topic}` API route to add a topic to a repository it will not be displayed on the explore page, but will show up properly on the repository page.

## Steps to reproduce
1. Go to the API route on your Gitea installation (`/api/swagger`)
2. Click the Authorize button and provide some form of authentication (if the repository is private)
3. Expand the "Add a topic to a repository" section (under the "Repository" heading)
4. Click the "Try it out" button, fill in the fields, and click "Execute"
5. Go to the explore page and find the repository that you have added a topic to (notice that the topic is not displayed)
6. Click on the repository to go to its repository page (notice that the topics were added successfully)

## Screenshots
Screenshot_2020-08-04 MyGit
Screenshot_2020-08-04 theme-eighty

### PR DESCRIPTION
**Pull request by zeripath**
Fix #12426

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: models/topic.go [hunk 1]
```diff
@@ -211,7 +214,12 @@ func GetRepoTopicByName(repoID int64, topicName string) (*Topic, error) {
 
 // AddTopic adds a topic name to a repository (if it does not already have it)
 func AddTopic(repoID int64, topicName string) (*Topic, error) {
-	topic, err := GetRepoTopicByName(repoID, topicName)
+	sess := x.NewSession()
```
Comment (lunny) [inline models/topic.go:217]: defer sess.Close()

Comment (zeripath) [reply models/topic.go:217]:
```suggestion
	sess := x.NewSession()
	defer sess.Close()
```

**Review by lafriks — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by lafriks** [comment]
🚀
