### PR TITLE
Fix job status aggregation logic

### LINKED ISSUE #34821: Action behavior inconsist with Github Action when first job fail
### Description

When running multiple jobs in a workflow, the action status is mark failed as soon as first fail happend, this cause following problems
1. remaining jobs can only be cancelled by rerun all jobs(only when there's no failure in an action show cancel buttom)
2. remaining job status require refresh the website to update

This behavior is not consistant with Gitea v1.21.1(my previous version) and Github Action, following is the reproduce workflow
```yaml
name: Gitea Action violate failing behavior demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Fail-Job:
    runs-on: ubuntu-latest
    steps:
      - name: fail the regression
        run: |
          exit 1
  Long-Running-Job:
    runs-on: ubuntu-latest
    steps:
      - name: wait for 5s then return 0
        run: |
          sleep 5
```

### Gitea Version

1.24.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

Running workflow with Github Action
Image

Running workflow with Gitea Action v1.24.2, after first job fail, the cancel icon change to rerun all, and the remaining job status only update when refresh UI
Image

### Git Version

_No response_

### Operating System

Centos

### How are you running Gitea?

Self-hosted with release binary

### Database

None

### PR DESCRIPTION
**Pull request by nienjiuntai**
Fix https://github.com/go-gitea/gitea/issues/34821 by checking if all the jobs are done before set status to fail
Image

### CODE REVIEW

**Comment by wxiaoguang** [comment]
You can add (or fix) a test case here: `run_job_status_test.go`

**Comment by TheFox0x7** [comment]
specifically modify one here: https://github.com/go-gitea/gitea/blob/182cdd337dc9b74720306c425c304990f859bf45/models/actions/run_job_status_test.go#L67-L69

I'm not sure that this is a right fix, more that github does it weirdly in this case. Unless entire workflow can recover from the failure (which I don't know if it's possible) I think we do this correctly now. 
But I guess it kind of depends what signal you're more interested in - is it the pass/fail or are there any jobs still running/pending.

I don't think the fix is complete though as there's still the case of the `waiting` and `blocked`. Logically looking if we consider `running` as not a failure, then `waiting` and `blocked` shouldn't be as well as they are before the `running` state.
It wouldn't make much sense to have overall status be failure when we have failure+blocked but running when the block converts to failure.

**Comment by wxiaoguang** [comment]
Hmm, I also have the question: should we report the failure as soon as possible?

IMO the old behavior (reporting failure as soon as possible) is better to end users.

If a job fails, then the final status must be also "failed". Reporting failure to users early can tell them "there is something" in first time, no need to wait all jobs finishes.

**Comment by wxiaoguang** [comment]
You see, the comment is still there ...

image

**Comment by lunny** [comment]
Or maybe we can introduce a new status like running with part failure.

**Comment by TheFox0x7** [comment]
I think that would be the best solution. That way UI can indicate that run has already failed BUT there's something still pending.

**Comment by nienjiuntai** [comment]
> You see, the comment is still there ...
> 
> image

Yes, I'm aware this comment, but it doesn't match the behavior tested in Github Action
Image

Fail fast property will cause a weired behavior that **user cannot cancel a workflow or get current running workflows correctly by filter after a job fail**.

**Comment by wxiaoguang** [comment]
> Fail fast property will cause a weired behavior that **user cannot cancel a workflow or get current running workflows correctly by filter after a job fail**.

It sounds a strong reason.

So I think we can write the details into comment, and use this solution, and backport. Leave more improvements to the future.

**Review by lunny — APPROVED** [review]
https://github.com/go-gitea/gitea/pull/34823#issuecomment-2997459821

This could be another PR

File: models/actions/run_job_status_test.go [hunk 1]
```diff
@@ -59,13 +59,12 @@ func TestAggregateJobStatus(t *testing.T) {
 		{[]Status{StatusCancelled, StatusBlocked}, StatusCancelled},
 
 		// failure with other status, fail fast
```
Comment (wxiaoguang) [inline models/actions/run_job_status_test.go]:
```suggestion
		// failure with other status, usually fail fast, but "running" wins to match GitHub's behavior
		// anther reason that we can't make "failure" wins over "running": it would cause a weird behavior that user cannot cancel a workflow or get current running workflows correctly by filter after a job fail.
```

**Review by wxiaoguang — APPROVED** [review]

File: models/actions/run_job_status_test.go [hunk 2]
```diff
@@ -58,14 +58,14 @@ func TestAggregateJobStatus(t *testing.T) {
 		{[]Status{StatusCancelled, StatusRunning}, StatusCancelled},
 		{[]Status{StatusCancelled, StatusBlocked}, StatusCancelled},
 
-		// failure with other status, fail fast
-		// Should "running" win? Maybe no: old code does make "running" win, but GitHub does fail fast.
+		// failure with other status, usually fail fast, but "running" wins to match GitHub's behavior
+		// anther reason that we can't make "failure" wins over "running": it would cause a weird behavior that user cannot cancel a workflow or get current running workflows correctly by filter after a job fail.
```
Comment (lunny) [inline models/actions/run_job_status_test.go]:
```suggestion
		// another reason that we can't make "failure" wins over "running": it would cause a weird behavior that user cannot cancel a workflow or get current running workflows correctly by filter after a job fail.
```

**Comment by wxiaoguang** [comment]
> I don't think the fix is complete though as there's still the case of the `waiting` and `blocked`. Logically looking if we consider `running` as not a failure, then `waiting` and `blocked` shouldn't be as well as they are before the `running` state. It wouldn't make much sense to have overall status be failure when we have failure+blocked but running when the block converts to failure.

Merged now, let's see whether we should continue changing the priority, then never make the "failure" win other status.

Maybe something related:

1. Should we "fix the bug" that a "failure" task isn't able to be cancelled or rerun? Then still make the the status "fail fast" (win other status)
2. Should we really introduce a bunch of new statuses like failed-running, or failed-waiting, etc. Or introduce a combined status mechanism like `(failure, running)`?
    * Either solution seems too complex than it should be


Open for discussion.

**Comment by lunny** [comment]
~We just need only to introduce running-failure, no other status is necessary.~
Looks like two new statuses need to be introduced if that's the right direction.

**Comment by wxiaoguang** [comment]
> We just need only to introduce running-failure, no other status is necessary.

Why? "waiting" is similar to "running" in this case and the "waiting" will be come "running" sooner or later.

**Comment by wxiaoguang** [comment]
> more that github does it weirdly in this case.

Hmm, it's also strange to me.

According to my experience, GitHub still makes failure have higher priority. It is what I have seen for the latest 1.24 branch:

1. One job fails, others are running
2. The commit status shows a red cross (failure)
3. I can click into the commit and see its jobs, others are still running, I can cancel the running ones.

I suspect there are some problems in this PR or the whole design (ps: I don't really use Actions so I can't comment more or spend more time on it)

**Comment by lunny** [comment]
> > more that github does it weirdly in this case.
> 
> Hmm, it's also strange to me.
> 
> According to my experience, GitHub still makes failure have higher priority. It is what I have seen for the latest 1.24 branch:
> 
> 1. One job fails, others are running
> 2. The commit status shows a red cross (failure)
> 3. I can click into the commit and see its jobs, others are still running, I can cancel the running ones.
> 
> I suspect there are some problems in this PR or the whole design (ps: I don't really use Actions so I can't comment more or spend more time on it)

I think other CI/CDs should have the similar problems?

**Comment by wxiaoguang** [comment]
My brief understanding of the problem is (just my guess, some of my previous comments might be not right):

GitHub has 2 kinds of "aggregation logic"

* The commit status for commit list: failure has higher priority
* The action status for action details page: running has higher priority

If I understand correctly, Gitea also has 2 kinds of "aggregation logic", the same to GitHub.

* The commit status for commit list: (need to check code's logic to confirm)
* The action status for action details page: this PR, matches GitHub now

So, overall this change should be fine.
