### PR TITLE
Increase minimal required git version to 2.0

### LINKED ISSUE #19554: [Proposal] Drop git 1.x support, or fix the IsEmpty bug
There is an obvious bug in Gitea that `IsEmpty` check always fails in git 1.x (git 1.x reports an error for that command), it makes many users only see empty repositories after they have pushed content in.

* https://github.com/go-gitea/gitea/issues/19086 
(and more)

The only reason to support git 1.x IIRC is for CentOS 7.x users.

However, CentOS 7.x is quite old, and the users could always have other solutions: upgrade git (ius/wandisco/endpoint), or use docker to run Gitea.

Since Gitea is reaching 1.17, it's time to make the decision.

* 👍 Drop git 1.x support
* 🎉 [or] Fix the `IsEmpty` bug

I prefer to drop git 1.x support.

### PR DESCRIPTION
**Pull request by wxiaoguang**
Close #19554
* #19554

This PR only upgrades the `GitVersionRequired` variable to `2.0.0`. All code for git 1.x are not changed, then if some users want to test with old git client or bypass the check, they still have a chance to edit the GitVersionRequired manually.

Code for git 1.x could be removed in a separate PR before 1.17 frozen.

And since there are a lot of CentOS 7 users, a friendly hint is added to tell them how to install latest git client.

## :warning: BREAKING :warning: 

This PR makes Gitea require git >= 2.0, follow https://git-scm.com/download/ to install latest git client if your git is too old.

### CODE REVIEW

File: modules/git/git.go [hunk 1]
```diff
@@ -20,10 +21,8 @@ import (
 )
 
 var (
-	// Prefix the log prefix
-	Prefix = "[git-module] "
```
Comment (delvh) [inline modules/git/git.go:24]: Was that simply unused?

**Review by delvh — APPROVED** [review]

File: modules/git/git.go (hunk 1 above)
Comment (wxiaoguang) [reply modules/git/git.go:24]: Yes, not used anymore. Otherwise there would be an error when compile.

**Comment by lunny** [comment]
We need also update documentation. from-binary.en-us.md

**Comment by wxiaoguang** [comment]
> We need also update documentation. from-binary.en-us.md

Where? I didn't see hard-coded git version in that document, and I think we shouldn't put hard-coded version into it either .... the error message is clear enough when gitea is running.

**Comment by wxiaoguang** [comment]
Or do you mean to change the line from 

`Check that Git is installed on the server. If it is not, install it first.`

to 

`Check that Git is installed on the server. If it is not, install it first. Gitea requires Git version >= 2.0.`

??

**Comment by 6543** [comment]
I think there are more version checks we now can remove

**Comment by wxiaoguang** [comment]
@lunny document is updated.

@6543 I prefer to keep the old code for git 1.x at the moment (in case someone still needs it). If everything works fine, the old code for git 1.x could be removed in a separate PR before 1.17 frozen.

**Review by lunny — APPROVED** [review]

**Review by 6543 — APPROVED** [review]
