### PR TITLE
Fix various problems

### LINKED ISSUE #37027: Checkbox gets over Arabic Text in Issues Description
### Description

When Writing an issue or a comment and add a checkbox it'll become over the text arabic.

### Screenshots

Image

### Gitea Version

v1.25.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows 11

### Browser Version

Chrome

### LINKED ISSUE #37028: [NIGHTLY] Window binary spawns git.exe and never cleans up on visit to repo.
### Description

Steps (after turning on `RUN_MODE=dev` and `LEVEL = trace`)

1. Open task manager. Notice no `git.exe` processes
2. Start gitea.
3. From the home page, open any repo.
4. Notice a new `git.exe` instance spawns on the host and never goes away.
5. More processes spawn as you visit more repos.

Maybe related to previous issue: https://github.com/go-gitea/gitea/issues/18734

<details>
<summary>logs</summary>

```
...
2026/03/29 09:13:37 HTTPRequest [T] router: started   POST /api/actions/runner.v1.RunnerService/FetchTask for 192.168.106.3:0
2026/03/29 09:13:37 HTTPRequest [T] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 192.168.106.3:0, 200 OK in 12.1ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2026/03/29 09:13:37 modules/process/manager.go:233:(*Manager).remove() [T] Done 69c94fb1: HTTP: POST /api/actions/runner.v1.RunnerService/FetchTask
2026/03/29 09:13:37 HTTPRequest [T] router: completed GET /user/events for 192.168.106.6:0, 200 OK in 4313.7ms @ events/events.go:18(events.Events)
2026/03/29 09:13:37 modules/process/manager.go:233:(*Manager).remove() [T] Done 69c94fad-32: HTTP: GET /user/events
2026/03/29 09:13:37 modules/process/manager.go:185:(*Manager).Add() [T] Start 69c94fb1-2: HTTP: GET /user/repo (request)
2026/03/29 09:13:37 HTTPRequest [T] router: started   GET /user/repo for 192.168.106.6:0
2026/03/29 09:13:37 services/auth/session.go:40:(*Session).Verify() [T] Session Authorization: Found user[1]
2026/03/29 09:13:37 services/auth/session.go:58:(*Session).Verify() [T] Session Authorization: Logged in user <User 1:user>
2026/03/29 09:13:37 models/repo/repo.go:406:(*Repository).LoadUnits() [T] repo.Units, ID=301, Types: [<UnitType:1:repo.code>, <UnitType:2:repo.issues>, <UnitType:3:repo.pulls>, <UnitType:4:repo.releases>, <UnitType:5:repo.wiki>, <UnitType:8:repo.projects>, <UnitType:9:repo.packages>, <UnitType:10:repo.actions>]
2026/03/29 09:13:37 .../access/repo_permission.go:388:GetUserRepoPermission.1() [T] Permission Loaded for user <User 1:user> in repo <Repository 301:user/repo>, permissions: <Permission AccessMode=owner, 8 Units, 0 UnitsMode(s): [
	units[0]: ID=2407 RepoID=301 Type=<UnitType:1:repo.code> Config={}
	units[1]: ID=2408 RepoID=301 Type=<UnitType:2:repo.issues> Config={"EnableTimetracker":true,"AllowOnlyContributorsToTrackTime":true,"EnableDependencies":true}
	units[2]: ID=2409 RepoID=301 Type=<UnitType:3:repo.pulls> Config={"IgnoreWhitespaceConflicts":false,"AllowMerge":true,"AllowRebase":true,"AllowRebaseMerge":true,"AllowSquash":true,"AllowFastForwardOnly":true,"AllowManualMerge":false,"AutodetectManualMerge":false,"AllowRebaseUpdate":true,"DefaultDeleteBranchAfterMerge":false,"DefaultMergeStyle":"merge","DefaultAllowMaintainerEdit":true,"DefaultTargetBranch":""}
	units[3]: ID=2410 RepoID=301 Type=<UnitType:4:repo.releases> Config={}
	units[4]: ID=2411 RepoID=301 Type=<UnitType:5:repo.wiki> Config={}
	units[5]: ID=2412 RepoID=301 Type=<UnitType:8:repo.projects> Config={"ProjectsMode":"all"}
	units[6]: ID=2413 RepoID=301 Type=<UnitType:9:repo.packages> Config={}
	units[7]: ID=2414 RepoID=301 Type=<UnitType:10:repo.actions> Config={"DisabledWorkflows":null,"CollaborativeOwnerIDs":null,"token_permission_mode":"permissive","override_owner_config":false}
	anonymousAccessMode: map[]
	everyoneAccessMode: map[]
	]>
2026/03/29 09:13:37 .../git/gitcmd/command.go:422:(*Command).Start() [D] git.Command: git.Run(by:gitrepo.IsReferenceExist, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" show-ref --verify -- refs/heads/main
2026/03/29 09:13:37 modules/process/manager.go:185:(*Manager).Add() [T] Start 69c94fb1-3: git.Run(by:gitrepo.IsReferenceExist, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" show-ref --verify -- refs/heads/main (from 69c94fb1-2) (normal)
2026/03/29 09:13:37 modules/process/manager.go:233:(*Manager).remove() [T] Done 69c94fb1-3: git.Run(by:gitrepo.IsReferenceExist, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" show-ref --verify -- refs/heads/main
2026/03/29 09:13:37 .../git/gitcmd/command.go:422:(*Command).Start() [D] git.Command: git.Run(by:gitcmd.(*Command).StartWithStderr, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" cat-file --batch-command
2026/03/29 09:13:37 modules/process/manager.go:185:(*Manager).Add() [T] Start 69c94fb1-4: git.Run(by:gitcmd.(*Command).StartWithStderr, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" cat-file --batch-command (from 69c94fb1-2) (normal)
2026/03/29 09:13:37 .../git/gitcmd/command.go:422:(*Command).Start() [D] git.Command: git.Run(by:git.(*Repository).hashObjectBytes, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" hash-object --stdin
2026/03/29 09:13:38 modules/process/manager.go:185:(*Manager).Add() [T] Start 69c94fb2: git.Run(by:git.(*Repository).hashObjectBytes, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" hash-object --stdin (from 69c94fb1-2) (normal)
2026/03/29 09:13:38 modules/process/manager.go:233:(*Manager).remove() [T] Done 69c94fb2: git.Run(by:git.(*Repository).hashObjectBytes, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" hash-object --stdin
2026/03/29 09:13:38 .../git/gitcmd/command.go:422:(*Command).Start() [D] git.Command: git.Run(by:gitrepo.CommitsCount, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" rev-list --count b9150d46c42ffef5b711b9325f76e37fcee0f572
2026/03/29 09:13:38 modules/process/manager.go:185:(*Manager).Add() [T] Start 69c94fb2-2: git.Run(by:gitrepo.CommitsCount, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" rev-list --count b9150d46c42ffef5b711b9325f76e37fcee0f572 (from 69c94fb1-2) (normal)
2026/03/29 09:13:38 modules/process/manager.go:233:(*Manager).remove() [T] Done 69c94fb2-2: git.Run(by:gitrepo.CommitsCount, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" rev-list --count b9150d46c42ffef5b711b9325f76e37fcee0f572
2026/03/29 09:13:38 .../git/gitcmd/command.go:422:(*Command).Start() [D] git.Command: git.Run(by:gitcmd.(*Command).StartWithStderr, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" log --name-status -c "--format=commit%x00%H %P%x00" --parents --no-renames -t -z b9150d46c42ffef5b711b9325f76e37fcee0f572 -- :(literal).gitignore :(literal)README.md :(literal)affinity :(literal)bitwarden :(literal)caddy :(literal)dev :(literal)docker-compose :(literal)excel :(literal)gitea :(literal)grist :(literal)media :(literal)memory :(literal)movies :(literal)partyparrot :(literal)personal :(literal)powershell :(literal)recordings :(literal)rss :(literal)tesla
2026/03/29 09:13:38 modules/process/manager.go:185:(*Manager).Add() [T] Start 69c94fb2-3: git.Run(by:gitcmd.(*Command).StartWithStderr, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" log --name-status -c "--format=commit%x00%H %P%x00" --parents --no-renames -t -z b9150d46c42ffef5b711b9325f76e37fcee0f572 -- :(literal).gitignore :(literal)README.md :(literal)affinity :(literal)bitwarden :(literal)caddy :(literal)dev :(literal)docker-compose :(literal)excel :(literal)gitea :(literal)grist :(literal)media :(literal)memory :(literal)movies :(literal)partyparrot :(literal)personal :(literal)powershell :(literal)recordings :(literal)rss :(literal)tesla (from 69c94fb1-2) (normal)
2026/03/29 09:13:38 .../git/gitcmd/command.go:422:(*Command).Start() [D] git.Command: git.Run(by:gitcmd.(*Command).StartWithStderr, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" log --name-status -c "--format=commit%x00%H %P%x00" --parents --no-renames -t -z 778b4b00fcaf5d18c6a2f5e84017af4d7625cdce -- :(literal).gitignore :(literal)README.md :(literal)affinity :(literal)caddy :(literal)dev :(literal)gitea :(literal)grist :(literal)media :(literal)memory :(literal)movies :(literal)partyparrot :(literal)personal :(literal)recordings :(literal)rss :(literal)tesla
2026/03/29 09:13:38 modules/process/manager.go:185:(*Manager).Add() [T] Start 69c94fb2-4: git.Run(by:gitcmd.(*Command).StartWithStderr, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" log --name-status -c "--format=commit%x00%H %P%x00" --parents --no-renames -t -z 778b4b00fcaf5d18c6a2f5e84017af4d7625cdce -- :(literal).gitignore :(literal)README.md :(literal)affinity :(literal)caddy :(literal)dev :(literal)gitea :(literal)grist :(literal)media :(literal)memory :(literal)movies :(literal)partyparrot :(literal)personal :(literal)recordings :(literal)rss :(literal)tesla (from 69c94fb1-2) (normal)
2026/03/29 09:13:38 modules/process/manager.go:233:(*Manager).remove() [T] Done 69c94fb2-3: git.Run(by:gitcmd.(*Command).StartWithStderr, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" log --name-status -c "--format=commit%x00%H %P%x00" --parents --no-renames -t -z b9150d46c42ffef5b711b9325f76e37fcee0f572 -- :(literal).gitignore :(literal)README.md :(literal)affinity :(literal)bitwarden :(literal)caddy :(literal)dev :(literal)docker-compose :(literal)excel :(literal)gitea :(literal)grist :(literal)media :(literal)memory :(literal)movies :(literal)partyparrot :(literal)personal :(literal)powershell :(literal)recordings :(literal)rss :(literal)tesla
2026/03/29 09:13:38 modules/process/manager.go:233:(*Manager).remove() [T] Done 69c94fb2-4: git.Run(by:gitcmd.(*Command).StartWithStderr, repo:.../user\repo.git): "C:\\Program Files\\Git\\bin\\git.exe" log --name-status -c "--format=commit%x00%H %P%x00" --parents --no-renames -t -z 778b4b00fcaf5d18c6a2f5e84017af4d7625cdce -- :(literal).gitignore :(literal)README.md :(literal)affinity :(literal)caddy :(literal)dev :(literal)gitea :(literal)grist :(literal)media :(literal)memory :(literal)movies :(literal)partyparrot :(literal)personal :(literal)recordings :(literal)rss :(literal)tesla
2026/03/29 09:13:38 routers/web/repo/view.go:315:renderDirectoryFiles() [D] first call to get directory file commit info
2026/03/29 09:13:38 .../fileicon/material.go:61:(*MaterialIconProvider).loadData() [D] Loaded material icon rules and SVG images
2026/03/29 09:13:38 .../access/repo_permission.go:388:GetUserRepoPermission.1() [T] Permission Loaded for user <User 1:user> in repo <Repository 301:user/repo>, permissions: <Permission AccessMode=owner, 8 Units, 0 UnitsMode(s): [
	units[0]: ID=2407 RepoID=301 Type=<UnitType:1:repo.code> Config={}
	units[1]: ID=2408 RepoID=301 Type=<UnitType:2:repo.issues> Config={"EnableTimetracker":true,"AllowOnlyContributorsToTrackTime":true,"EnableDependencies":true}
	units[2]: ID=2409 RepoID=301 Type=<UnitType:3:repo.pulls> Config={"IgnoreWhitespaceConflicts":false,"AllowMerge":true,"AllowRebase":true,"AllowRebaseMerge":true,"AllowSquash":true,"AllowFastForwardOnly":true,"AllowManualMerge":false,"AutodetectManualMerge":false,"AllowRebaseUpdate":true,"DefaultDeleteBranchAfterMerge":false,"DefaultMergeStyle":"merge","DefaultAllowMaintainerEdit":true,"DefaultTargetBranch":""}
	units[3]: ID=2410 RepoID=301 Type=<UnitType:4:repo.releases> Config={}
	units[4]: ID=2411 RepoID=301 Type=<UnitType:5:repo.wiki> Config={}
	units[5]: ID=2412 RepoID=301 Type=<UnitType:8:repo.projects> Config={"ProjectsMode":"all"}
	units[6]: ID=2413 RepoID=301 Type=<UnitType:9:repo.packages> Config={}
	units[7]: ID=2414 RepoID=301 Type=<UnitType:10:repo.actions> Config={"DisabledWorkflows":null,"CollaborativeOwnerIDs":null,"token_permission_mode":"permissive","override_owner_config":false}
	anonymousAccessMode: map[]
	everyoneAccessMode: map[]
	]>
...
```
</details>

### Gitea Version

gitea version 1.26.0+dev-605-g84daa0b8be built with go1.26.1-X:jsonv2 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

git version 2.53.0.windows.2

### Operating System

Windows 11 Pro

### How are you running Gitea?

Windows binary from nightly page, AMD64.

### Database

SQLite

### PR DESCRIPTION
**Pull request by wxiaoguang**
1. Use "margin/padding inline" 
   * Fix  #37027
2. Make DetectWellKnownMimeType fallback to system mime types
3. Make catFileBatchCommunicator close pipes
   * Old behavior in 1.25: https://github.com/go-gitea/gitea/blob/release/v1.25/modules/git/batch_reader.go#L45-L55
   * Try to fix #37028

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Image

**Review by silverwind — APPROVED** [review]

File: modules/public/mime_types.go [hunk 1]
```diff
@@ -4,31 +4,36 @@
...
+	return map[string]string{
+		".avif": "image/avif",
+		".css":  "text/css; charset=utf-8",
+		".gif":  "image/gif",
+		".htm":  "text/html; charset=utf-8",
+		".html": "text/html; charset=utf-8",
+		".jpeg": "image/jpeg",
+		".jpg":  "image/jpeg",
+		".js":   "text/javascript; charset=utf-8",
+		".json": "application/json",
```
Comment (bircni) [inline modules/public/mime_types.go:24]:
```suggestion
		".json": "application/json",
		".md":   "text/markdown; charset=utf-8",
```

maybe we could add markdown?

Comment (wxiaoguang) [reply modules/public/mime_types.go:24]: No, it doesn't affect browser behavior or rendering

**Review by TheFox0x7 — APPROVED** [review]

**Review by bircni — APPROVED** [review]
