### PR TITLE
fix multiple readme file rendering and fix #1657

### LINKED ISSUE #1657: README.md not displaying
on the initial repo screen the README.md is not being displayed instead 
README.diskdefines is being displayed. 

I tested 
https://try.gitea.io/mgregoir/testreadme

### PR DESCRIPTION
**Pull request by lunny**
will fix #1657

### CODE REVIEW

File: routers/repo/view.go [hunk 1]
```diff
@@ -54,18 +54,38 @@ func renderDirectory(ctx *context.Context, treeLink string) {
...
+		if entry.IsDir() {
+			continue
+		}
+
+		tp, ok := markup.ReadmeFileType(entry.Name())
+		if !ok {
 			continue
 		}
 
-		// TODO: collect all possible README files and show with priority.
```
Comment (sapk) [inline routers/repo/view.go:63]: That was in the TODO list. 😄

Comment (lunny) [reply routers/repo/view.go:63]: Yes. This PR will finish the TODO.

File: routers/repo/view.go [hunk 2]
```diff
@@ -54,18 +54,38 @@ func renderDirectory(ctx *context.Context, treeLink string) {
...
+		}{
+			entry.Blob(),
+			tp,
+		})
 	}
 
-	if readmeFile != nil {
+	if len(readmes) > 0 {
+		var readmeFile *git.Blob
+		for _, readme := range readmes {
```
Comment (sapk) [inline routers/repo/view.go]: Why re-loop if we stop at first ok. This could be done directly in the first loop at https://github.com/lunny/gitea/blob/d0ddef4e095a8f4e317a6163cb2e955fea254779/routers/repo/view.go#L67 for example ?

This just add an additional test if the file is a good filetype so no need to save them in an array ?

Comment (sapk) [reply routers/repo/view.go]: I found that this add another point that it default to even "bad filetype" if not one good is found.
But this could be implemented directly in the first loop.

Comment (sapk) [reply routers/repo/view.go]: For example in first loop setting directly readmeFile and do directly after
```
			if tp != "" {
				break
			}
```

Comment (sapk) [reply routers/repo/view.go]: like that https://gist.github.com/sapk/aceaf02d9d6814f0d9fecff17d31c04b

Comment (lunny) [reply routers/repo/view.go]: @sapk you are right. The `type` will check which parser could read the README file according ext name. But we also need support `README`, which should be rendered as a TEXT, so the `tp` may be empty. But `README` or `README.diskdefine` is lower priority than `README.md` or `README.org`(this will be implemented at #1527).

Comment (lunny) [reply routers/repo/view.go]: done.

**Review by sapk — APPROVED** [review]

**Comment by sapk** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM
