### PR TITLE
Remove all package data after tests

### LINKED ISSUE #21020: Package tests (as run by make test-sqlite) do not clean up after themselves
### Description

The package tests are not correctly cleaning up after running leading to incorrect reports of errors if `make test-sqlite` is run again.

```
--- FAIL: TestPackagePub (0.15s)
    testlogger.go:78: 2022/09/01 17:50:40 ...eb/routing/logger.go:99:func1() [I] [6310e2e0-36] router: completed GET /user/settings/applications for , 200 OK in 1.8ms @ setting/applications.go:24(setting.Applications)
    testlogger.go:78: 2022/09/01 17:50:40 ...eb/routing/logger.go:99:func1() [I] [6310e2e0-37] router: completed POST /user/settings/applications for , 303 See Other in 18.9ms @ setting/applications.go:34(setting.ApplicationsPost)
    testlogger.go:78: 2022/09/01 17:50:40 ...eb/routing/logger.go:99:func1() [I] [6310e2e0-38] router: completed GET /user/settings/applications for , 200 OK in 1.9ms @ setting/applications.go:24(setting.Applications)
    --- FAIL: TestPackagePub/Upload (0.06s)
        testlogger.go:78: 2022/09/01 17:50:40 ...eb/routing/logger.go:99:func1() [I] [6310e2e0-39] router: completed GET /api/packages/user2/pub/api/packages/versions/new for , 401 Unauthorized in 0.2ms @ packages/api.go:34(packages.reqPackageAccess)
        testlogger.go:78: 2022/09/01 17:50:40 ...eb/routing/logger.go:99:func1() [I] [6310e2e0-40] router: completed GET /api/packages/user2/pub/api/packages/versions/new for , 200 OK in 16.7ms @ pub/pub.go:147(pub.RequestUpload)
        testlogger.go:78: 2022/09/01 17:50:40 ...packages/packages.go:161:createPackageAndVersion() [E] [6310e2e0-41] Error inserting package: Package version already exists
        testlogger.go:78: 2022/09/01 17:50:40 ...eb/routing/logger.go:99:func1() [I] [6310e2e0-41] router: completed POST http://localhost:3003/api/packages/user2/pub/api/packages/versions/new/upload for , 400 Bad Request in 16.0ms @ pub/pub.go:160(pub.UploadPackageFile)
        api_packages_pub_test.go:92: 
            	Error Trace:	/home/andrew/src/go/gitea/integration_test.go:506
            	            				/home/andrew/src/go/gitea/api_packages_pub_test.go:92
            	            				/home/andrew/src/go/gitea/api_packages_pub_test.go:95
            	Error:      	Not equal: 
            	            	expected: 204
            	            	actual  : 400
            	Test:       	TestPackagePub/Upload
            	Messages:   	Request: POST http://localhost:3003/api/packages/user2/pub/api/packages/versions/new/upload
        api_packages_pub_test.go:92: Response: {"error":{"code":"Bad Request","message":"Package version already exists"}}

```

### Gitea Version

d74390ee39d84b24e103a049217817e22dc391d4 (if not earlier)

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

make test-sqlite

### Database

_No response_

### PR DESCRIPTION
**Pull request by KN4CK3R**
Fixes #21020

### CODE REVIEW

File: tests/integration/api_packages_test.go [hunk 1]
```diff
@@ -403,3 +426,25 @@ func TestPackageCleanup(t *testing.T) {
...
+	assert.NoError(t, db.DeleteAllRecords("package"))
+	assert.NoError(t, db.DeleteAllRecords("package_version"))
+	assert.NoError(t, db.DeleteAllRecords("package_file"))
+	assert.NoError(t, db.DeleteAllRecords("package_property"))
+	assert.NoError(t, db.DeleteAllRecords("package_blob_upload"))
+	assert.NoError(t, db.DeleteAllRecords("package_cleanup_rule"))
+
+	duration, _ := time.ParseDuration("-10h")
+
+	pbs, err := packages_model.FindExpiredUnreferencedBlobs(db.DefaultContext, duration)
```
Comment (zeripath) [inline tests/integration/api_packages_test.go]: doesn't this work on what is in the db which you have just emptied above?

File: tests/integration/api_packages_test.go [hunk 2]
```diff
@@ -403,3 +426,25 @@ func TestPackageCleanup(t *testing.T) {
...
+	assert.NoError(t, err)
+
+	contentStore := packages_module.NewContentStore()
+	for _, pb := range pbs {
+		contentStore.Delete(packages_module.BlobHash256Key(pb.HashSHA256))
+	}
```
Comment (zeripath) [inline tests/integration/api_packages_test.go]: Why not ensure it is empty in prepareTestEnv? Then you won't need to keep blob around?

File: tests/integration/api_packages_test.go (hunk 1 above)
Comment (zeripath) [reply tests/integration/api_packages_test.go]: Oh I see this requires package_blob

Comment (KN4CK3R) [reply tests/integration/api_packages_test.go]: The package blobs table was not touched, so all existing blobs are unreferenced.

File: tests/integration/api_packages_test.go (hunk 2 above)
Comment (KN4CK3R) [reply tests/integration/api_packages_test.go]: I did not want to add a burden to all other tests. Do you think it would be better placed there?

**Review by zeripath — APPROVED** [review]

File: tests/integration/api_packages_test.go (hunk 2 above)
Comment (zeripath) [reply tests/integration/api_packages_test.go]: I think adding empty fixtures to models/fixtures would probably be a good idea - then no one can make the mistake of expecting these things to be there across tests again.

I guess the question is if we can just empty the contentstore cheaply and easily in the prepareTestEnv.

Comment (KN4CK3R) [reply tests/integration/api_packages_test.go]: We do this already for the LFS files:
https://github.com/go-gitea/gitea/blob/6cb76bf1df581cf554670c533a1801b46a74909e/tests/test_utils.go#L201
so maybe `tests.PrepareTestEnv` would be a better place then? With the `storage.Clean` method the code would be shorter too because I don't need to get the package blobs.

**Review by delvh — APPROVED** [review]

**Comment by KN4CK3R** [comment]
I would like to wait for https://gitea.com/xorm/xorm/pulls/2220 because this could shrink this PR a little bit.

**Comment by delvh** [comment]
The xorm PR was merged, so this PR should be updated.

**Review by techknowlogick — DISMISSED** [review]
Blocking for xorm dep update
