### PR TITLE
Fix bug on action list deleted branch

### LINKED ISSUE #32761: Action view branch button doesn't check for deleted branch
### Description

image
Clicking on this button when branch was deleted show. In other pages branch existance is checked

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix https://github.com/go-gitea/gitea/issues/32761#issuecomment-2540946064

### CODE REVIEW

**Comment by wxiaoguang** [comment]
image

**Review by wxiaoguang — APPROVED** [review]

**Review by Zettat123 — APPROVED** [review]

**Comment by lunny** [comment]
Tests added.

**Review by silverwind — APPROVED** [review]

File: routers/web/repo/actions/actions_test.go [hunk 1]
```diff
@@ -7,6 +7,9 @@ import (
 	"strings"
 	"testing"
 
+	actions_model "code.gitea.io/gitea/models/actions"
+	"code.gitea.io/gitea/models/db"
+	unittest "code.gitea.io/gitea/models/unittest"
```
Comment (wxiaoguang) [inline routers/web/repo/actions/actions_test.go:12]:
```suggestion
	unittest "code.gitea.io/gitea/models/unittest"

```

File: routers/web/repo/actions/actions_test.go [hunk 2]
```diff
@@ -154,3 +158,20 @@ func TestReadWorkflow_WorkflowDispatchConfig(t *testing.T) {
...
+	assert.Len(t, runs, 3)
+	assert.EqualValues(t, 3, total)
+	for _, run := range runs {
+		assert.False(t, run.IsRefDeleted)
+	}
+
+	assert.NoError(t, loadIsRefDeleted(db.DefaultContext, 4, runs))
+	for _, run := range runs {
+		assert.True(t, run.IsRefDeleted)
+	}
```
Comment (wxiaoguang) [inline routers/web/repo/actions/actions_test.go:177]: I won't block it but I can't understand what you are testing.

All are "deleted"? No survivor? Isn't it exactly the old bug's phenomenon?

Comment (lunny) [reply routers/web/repo/actions/actions_test.go:177]: This is according to the test fixtures. Currently, there are only 3 action runs in the table and all of them belong to repo id 4, and no branch exists in the branch table. This can be considered an inconsistent in the fixtures table.

Comment (lunny) [reply routers/web/repo/actions/actions_test.go:177]: tests updated
