### PR TITLE
Recommend/convert to use case-sensitive collation for MySQL/MSSQL

### LINKED ISSUE #28131: MySQL/MariaDB: Unique Constraint on Branches doesn't respect casing: UQE_branch_s
### Description

In a repo with two branches `feature/test_case` and `feature\Test_Case` gitea throws a 500 exception when syncing branches as the unique constraint is violated.

`SyncRepoBranches: Error 1062 (23000): Duplicate entry '<redacted_branch_name>' for key 'UQE_branch_s'`

This error happened after an upgrade to 1.21.0 on an existing repo.

Workaround is to rename one of the branches.

Typically having this type of different branch names only based on casing is not needed (imho it's a bug ;) ) - but we shouldn't have a 500 page when accessing the repo.

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Linux

### How are you running Gitea?

Official binary

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by wxiaoguang**
Mainly for MySQL/MSSQL.

It is important for Gitea to use case-sensitive database charset collation. If the database is using a case-insensitive collation, Gitea will show startup error/warning messages, and show the errors/warnings on the admin panel's Self-Check page.

Make `gitea doctor convert` work for MySQL to convert the collations of database & tables & columns.

* Fix #28131

## :warning: BREAKING :warning:

It is not quite breaking, but it's highly recommended to convert the database&table&column to a consistent and case-sensitive collation.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Ready for review. Found a XORM bug which blocks using MSSQL case-sensitive collations. It causes errors like "mssql: Invalid object name 'SYS.INDEXES'." Actually, the object name should be lower-cased.

image

**Comment by lunny** [comment]
> Ready for review. Found a XORM bug which blocks using MSSQL case-sensitive collations. It causes errors like "mssql: Invalid object name 'SYS.INDEXES'." Actually, the object name should be lower-cased.

Can you try xorm [2a4161d7a5](https://gitea.com/xorm/xorm/commit/2a4161d7a5de6938b4bd11bdc442a6cad8e813df) ?

**Comment by wxiaoguang** [comment]
Are there still more object names? No idea how the tests pass.

image

**Comment by wxiaoguang** [comment]
> But tests PASS. The method `DBMetas` has been invoked many times which will invoke `dialect.GetIndexes`

You can try to run the SQL `select * from SYS.INDEX_COLUMNS` manually on a case-sensitive table, it also fails.


image

image

**Comment by lunny** [comment]
> > But tests PASS. The method `DBMetas` has been invoked many times which will invoke `dialect.GetIndexes`
> 
> You can try to run the SQL `select * from SYS.INDEX_COLUMNS` manually on a case-sensitive table, it also fails.
> 
> image
> 
> image

Fixed in [4992cba040](https://gitea.com/xorm/xorm/commit/4992cba040fe0232df7a036a1e827f57e1b9a56b), it also fixed the wrong tests.

**Comment by wxiaoguang** [comment]
Found another bug for MSSQL testing: Make SQL work with case-sensitivie SQLServer https://github.com/go-testfixtures/testfixtures/pull/182

**Review by lunny — APPROVED** [review]

File: tests/integration/api_branch_test.go [hunk 1]
```diff
@@ -139,6 +139,8 @@ func testAPICreateBranches(t *testing.T, giteaURL *url.URL) {
 			ExpectedHTTPStatus: http.StatusConflict,
 		},
 		// Trying to create from other branch (not default branch)
+		// ps: it can't test the case-sensitive behavior here, because on macOS, the branch can't be created by git, make the test fails quickly, before the database code
```
Comment (wxiaoguang) [inline tests/integration/api_branch_test.go]:
```suggestion
		// ps: it can't test the case-sensitive behavior here: the "BRANCH_2" can't be created by git on a case-insensitive filesystem, it makes the test fail quickly before the database code.
```

**Comment by lunny** [comment]
One review needed and Last Call @go-gitea/technical-oversight-committee

**Review by wolfogre — APPROVED** [review]
