### PR TITLE
Pooled and buffered gzip implementation

### LINKED ISSUE #4853: gitea  git clone failed when using ENABLE_GZIP for tar.gz file.
Dear all,
      I use gitea using git lfs track '*.tar.gz'.  I upload an tar file (downloaded from https://codeload.github.com/masterzen/nginx-upload-progress-module/tar.gz/v0.9.2).  Its sha256 checksum is 'b286689355442657650421d8e8398bd4abf9dbbaade65947bb0cb74a349cc497'. 
  The lfs file stored in the server is correctly. Its checksum is the same. But when ENABLE_GZIP is true,
git clone the repo , it failed.  
The terminal display:
   Downloading nginx-upload-progress-module-0.9.2.tar.gz (17 KB)
Error downloading object: nginx-upload-progress-module-0.9.2.tar.gz (b286689): Smudge error: Error downloading nginx-upload-progress-module-0.9.2.tar.gz (b286689355442657650421d8e8398bd4abf9dbbaade65947bb0cb74a349cc497): cannot write data to tempfile "/works/gitworks/2018-develop/zdd/testout/out/test-repo/.git/lfs/incomplete/b286689355442657650421d8e8398bd4abf9dbbaade65947bb0cb74a349cc497.tmp": LFS: unexpected EOF

When I change ENABLE_GZIP to false, and restart gitea, it works for git clone. 

So I think git lfs upload is correct. The problem is ENABLE_GZIP, when it's true, git clone don't works for the tar.gz file.
    ps: we can git clone for other lfs files(such as we compile lib files. when ENABLE_GZIP is true) .

### LINKED ISSUE #5182: LFS: unexpected EOF despite good integrity of the file on the server
- Gitea version (or commit ref): 
git-lfs/2.5.2
- Git version:
git version 2.17.1
- Operating system:
Ubuntu 18.04.1
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```text
git-lfs/2.5.2 (GitHub; linux amd64; go 1.10.3; git 8e3c5c93)
git version 2.17.1

$ git-lfs filter-process
Error downloading object: it/docs/jenkins/step1.jpg (c5e6043): Smudge error: Error downloading it/docs/jenkins/step1.jpg (c5e60437c9e7596445342c5adc91f6535e7565fab96ff200112ed8b2aabdbf47): cannot write data to tempfile "/home/zhongming/git/logi3/.git/lfs/incomplete/c5e60437c9e7596445342c5adc91f6535e7565fab96ff200112ed8b2aabdbf47.tmp": LFS: unexpected EOF

unexpected EOF
LFS
github.com/git-lfs/git-lfs/errors.newWrappedError
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/errors/types.go:188
github.com/git-lfs/git-lfs/errors.NewRetriableError
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/errors/types.go:363
github.com/git-lfs/git-lfs/tools.(*RetriableReader).Read
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/tools/iotools.go:99
github.com/git-lfs/git-lfs/tools.(*HashingReader).Read
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/tools/iotools.go:66
github.com/git-lfs/git-lfs/tools.(*CallbackReader).Read
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/tools/copycallback.go:73
io.copyBuffer
        /usr/local/Cellar/go/1.10.3/libexec/src/io/io.go:400
io.Copy
        /usr/local/Cellar/go/1.10.3/libexec/src/io/io.go:362
github.com/git-lfs/git-lfs/tools.CopyWithCallback
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/tools/iotools.go:39
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).download
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/tq/basic_download.go:205
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).DoTransfer
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/tq/basic_download.go:48
github.com/git-lfs/git-lfs/tq.(*adapterBase).worker
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/tq/adapterbase.go:176
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361
cannot write data to tempfile "/home/zhongming/git/logi3/.git/lfs/incomplete/c5e60437c9e7596445342c5adc91f6535e7565fab96ff200112ed8b2aabdbf47.tmp"
github.com/git-lfs/git-lfs/errors.newWrappedError
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/errors/types.go:184
github.com/git-lfs/git-lfs/errors.Wrapf
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/errors/errors.go:85
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).download
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/tq/basic_download.go:207
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).DoTransfer
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/tq/basic_download.go:48
github.com/git-lfs/git-lfs/tq.(*adapterBase).worker
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/tq/adapterbase.go:176
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361
Error downloading it/docs/jenkins/step1.jpg (c5e60437c9e7596445342c5adc91f6535e7565fab96ff200112ed8b2aabdbf47)
github.com/git-lfs/git-lfs/errors.newWrappedError
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/errors/types.go:184
github.com/git-lfs/git-lfs/errors.Wrapf
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/errors/errors.go:85
github.com/git-lfs/git-lfs/lfs.(*GitFilter).downloadFile
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/lfs/gitfilter_smudge.go:110
github.com/git-lfs/git-lfs/lfs.(*GitFilter).Smudge
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/lfs/gitfilter_smudge.go:71
github.com/git-lfs/git-lfs/commands.smudge
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:127
github.com/git-lfs/git-lfs/commands.filterCommand
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:118
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/commands/run.go:77
main.main
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35
runtime.main
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361
Smudge error
github.com/git-lfs/git-lfs/errors.newWrappedError
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/errors/types.go:184
github.com/git-lfs/git-lfs/errors.NewSmudgeError
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/errors/types.go:270
github.com/git-lfs/git-lfs/lfs.(*GitFilter).Smudge
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/lfs/gitfilter_smudge.go:80
github.com/git-lfs/git-lfs/commands.smudge
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:127
github.com/git-lfs/git-lfs/commands.filterCommand
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:118
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/commands/run.go:77
main.main
        /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35
runtime.main
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361

Current time in UTC: 
2018-10-25 14:11:01

ENV:
LocalWorkingDir=/home/zhongming/git/logi3
LocalGitDir=/home/zhongming/git/logi3/.git
LocalGitStorageDir=/home/zhongming/git/logi3/.git
LocalMediaDir=/home/zhongming/git/logi3/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/zhongming/git/logi3/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/zhongming/git/logi3/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git
GIT_PROMPT_ONLY_IN_REPO=1
GIT_BRANCH=master
__GIT_PROMPT_IGNORE_SUBMODULES__=1
__GIT_PROMPT_SHOW_CHANGED_FILES_COUNT=1
__GIT_PROMPT_SHOW_UPSTREAM=
__GIT_PROMPT_IGNORE_SUBMODULES=
__GIT_PROMPT_SHOW_UNTRACKED_FILES=normal
__GIT_PROMPT_IGNORE_STASH=
```

## Description

I have a local gitea server set up at host http://git.corp.logiocean.com:3000.

I pushed an LFS-enabled repo, named `logi` to the gitea server. Everything worked fine until I tried `git clone`, which produced the above described error.

I pushed the same repo (at the same commit) to github and `git clone` from github, everything worked.

I have verified that the git commit hash on github and on my local gitea server are exactly the same.

I have also verified that the LFS file that failed to download are intact on the server. Here is how I verified it:
- ssh into the server
- go to the lfs data directory `/home/git/data/lfs`.
- use the `oid` of the lfs file to locate the file.
- use `scp` to copy the file in question to my own desktop and verified (using diff and other tools) that the size of the file and the content of the file are indeed intact.

I have searched for similar issues across this repo and in many other places. Have not found one with exactly the same syndrome.

Posting to hopefully help others who are having the same problem.

Any help would be much appreciated! Thanks in advance.

### PR DESCRIPTION
**Pull request by zeripath**
This PR reimplements the gzip middleware implementation with a pooled and buffered gzip implementation. It more properly handles gzipped content and zipped content.

It should fix #5182 & fix #4853.

### CODE REVIEW

**Comment by lunny** [comment]
@zeripath could you add some integration tests?

**Comment by zeripath** [comment]
Thinking on, although that trick with Enable_gzip and then rerun integration tests doesn't actually fail it is remarkably inefficient in that only my integration test actually runs differently.

@lunny is the simple gzip_test sufficient or do you want integration tests. I can make it so that our integration tests actually deal with gzip'd content in general if you like.

---

I'm actually wrong here, unless we turn it off `http.Transport` will transparently ask for gzip and decompress. So the integration test is good.

Now I just need to work out what postgres is complaining about.

File: integrations/lfs_getobject_test.go [hunk 1]
```diff
@@ -0,0 +1,118 @@
+// Copyright 2018 The Gitea Authors. All rights reserved.
```
Comment (adelowo) [inline integrations/lfs_getobject_test.go]: 2019

Comment (zeripath) [reply integrations/lfs_getobject_test.go]: updated.

**Comment by zeripath** [comment]
Ah it looks like my integration test is hitting https://github.com/go-testfixtures/testfixtures/issues/39

**Comment by zeripath** [comment]
I've just rebased and squashed up some of the results.

File: models/lfs.go [hunk 2]
```diff
@@ -44,20 +44,20 @@ const (
...
 	if has {
 		m.Existing = true
-		return m, nil
-	}
-
-	sess := x.NewSession()
-	defer sess.Close()
-	if err = sess.Begin(); err != nil {
-		return nil, err
+		return m, sess.Commit()
```
Comment (lunny) [inline models/lfs.go:60]: Maybe we want to update `m` before `sess.Commit`?

**Review by lunny — CHANGES_REQUESTED** [review]

File: models/lfs.go (hunk 2 above)
Comment (zeripath) [reply models/lfs.go:60]: Hmm... This branch never updated m before. The `sess.Commit()` is only there because I've moved the opening of the transaction to as soon as we check if an LFS meta object is in the db, not just when we're creating new lfs meta objects after not finding them in the db. If we need to insert I do update m.

Checking if an object is in the db and then inserting if it's not should be a in single transaction otherwise you can have race conditions.

**Review by techknowlogick — APPROVED** [review]

**Comment by lafriks** [comment]
@lunny need your review

**Review by sapk — APPROVED** [review]

**Review by lunny — APPROVED** [review]
