### PR TITLE
Use first commit title for multi-commit PRs and fix auto-focus title field

### LINKED ISSUE #34865: Idea: Don't pre-fill pull request title with branch name
### Feature Description

When opening a pull request from a branch that has more than 1 commit, the UI will pre-fill the pull request form's title with the branch name. This is consistent with Github (except Github transforms/capitalizes the branch name), but I think it's a bad mechanism because novice users will often not change the title at all, maybe thinking it has to be that way. 

A better behaviour would be to use the title from the first commit.

Also btw, we should autofocus the title field when the form shows, like GitHub also does.

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/34865

1. When opening a PR from a branch with multiple commits, use the first (oldest) commit's title as the default title instead of the branch name
2. Add autofocus to the PR title input field for convenience

### CODE REVIEW

File: tests/integration/compare_test.go [hunk 1]
```diff
@@ -124,6 +124,39 @@ func TestCompareBranches(t *testing.T) {
...
+
+		// Open the compare page for creating a PR
+		req := NewRequest(t, "GET", fmt.Sprintf("/%s/%s/compare/main...multi-commit-branch", user1.Name, repo.Name))
+		resp := session.MakeRequest(t, req, http.StatusOK)
+		htmlDoc := NewHTMLParser(t, resp.Body)
+
+		// The title should be the first (oldest) commit's summary, not the branch name
+		titleValue := htmlDoc.GetInputValueByName("title")
+		assert.NotEqual(t, "multi-commit-branch", titleValue, "PR title should not be the branch name for multi-commit PRs")
+		assert.NotEqual(t, "Second commit title", titleValue, "PR title should not be the latest commit's title")
```
[the remark this answers is not in the document]
Comment (silverwind) [reply tests/integration/compare_test.go]: fixed in https://github.com/go-gitea/gitea/pull/36606/commits/95875195ef7ab93f7bd393caf5b27169bd68dbc0.

File: tests/integration/compare_test.go [hunk 2]
```diff
@@ -124,6 +124,39 @@ func TestCompareBranches(t *testing.T) {
...
+			AutoInit:      true,
+			DefaultBranch: "main",
+		}, true)
+		assert.NoError(t, err)
+
+		session := loginUser(t, user1.Name)
+
+		// Create a new branch and make two commits with custom summaries
+		testEditFileToNewBranch(t, session, user1.Name, repo.Name, "main", "multi-commit-branch", "README.md", "first edit\n")
+		testEditorActionEdit(t, session, user1.Name, repo.Name, "_edit", "multi-commit-branch", "README.md", map[string]string{
```
[the remark this answers is not in the document]
Comment (silverwind) [reply tests/integration/compare_test.go]: fixed in fixed in https://github.com/go-gitea/gitea/pull/36606/commits/95875195ef7ab93f7bd393caf5b27169bd68dbc0.

**Comment by silverwind** [comment]
Regarding autofocus, I see there is a `data-global-init="initInputAutoFocusEnd"` attribute which in theory should trigger `.focus()`, but it does nothing and the element never gets focused. Only HTML `autofocus` works. Investigating...

**Comment by silverwind** [comment]
Analysis by Claude:

## Why `data-global-init="initInputAutoFocusEnd"` doesn't work here

`registerGlobalInitFunc` handlers are triggered via a `MutationObserver` that watches for **DOM node additions** (`childList: true`). On page load, the observer scans all existing `[data-global-init]` elements and calls their handlers immediately, then marks them `_giteaGlobalInited = true` to prevent re-initialization.

On the PR compare page, the form is **already in the DOM** on page load, just hidden with `tw-hidden`:

```html
<div class="pullrequest-form {{if not .ExpandNewPrForm}}tw-hidden{{end}}">
  {{template "repo/issue/new_form" .}}
</div>
```

So `initInputAutoFocusEnd` fires immediately during page init — calling `el.focus()` on a **hidden element**, which is a no-op. The element is then marked as already initialized, so it never runs again.

When the user clicks "New Pull Request" to toggle the form visible, it's just a CSS class change (removing `tw-hidden`), not a DOM addition, so the `MutationObserver` doesn't fire. The toggle handler in `web_src/js/features/common-button.ts` does have a fallback that focuses `[autofocus]` elements — which is why `autofocus` is the correct attribute to use here instead of `data-global-init`.

**Comment by silverwind** [comment]
As per above, I've removed the broken `data-global-init="initInputAutoFocusEnd"`. Native `autofocus` works fine in Firefox and Chrome when opening to the Compare page and clicking the button. I assume this may be a special browser behaviour regarding hidden elements with autofocus that may have changed at some point in time.

**Review by lunny — DISMISSED** [review]

**Comment by wxiaoguang** [comment]
> As per above, I've removed the broken `data-global-init="initInputAutoFocusEnd"`. Native `autofocus` works fine in Firefox and Chrome when opening to the Compare page and clicking the button. I assume this may be a special browser behaviour regarding hidden elements with autofocus that may have changed at some point in time.

No, browsers are not that smart. I did it

image

**Comment by wxiaoguang** [comment]
> As per above, I've removed the broken `data-global-init="initInputAutoFocusEnd"`.

It isn't broken. It is designed to move the cursor to the end of the title.

When the title in the issue has a value, set the text cursor at the end of the text. (#30090)


Not only one user asks for this.

**Comment by silverwind** [comment]
> > As per above, I've removed the broken `data-global-init="initInputAutoFocusEnd"`.
> 
> It isn't broken. It is designed to move the cursor to the end of the title.
> 
> When the title in the issue has a value, set the text cursor at the end of the text. (#30090)
> 
> Not only one user asks for this.

Try on main branch, this JS autofocus is not working at all. Cursor is already at the end on this branch.

BTW I think the best autofocus variant would be with selection of the whole `<input>` so user can immediately type to write a custom title.

**Comment by wxiaoguang** [comment]
> > > As per above, I've removed the broken `data-global-init="initInputAutoFocusEnd"`.
> > 
> > 
> > It isn't broken. It is designed to move the cursor to the end of the title.
> > When the title in the issue has a value, set the text cursor at the end of the text. (#30090)
> > Not only one user asks for this.
> 
> Try on main branch, this JS autofocus is not working at all. Cursor is already at the end on this branch.

Ar you sure?

image

image


------

image

image

**Comment by silverwind** [comment]
regarless of the current issue, I question that "autofocus on end of input" is good behaviour. Is the most common use case really to append to the title? I think a much more common use case would be to replace the title, so a full selection autofous may make more sense imho. 

Personally i don't really care much about this so I can keep the "end" behaviour. in 99% of cases I keep the original PR title I had written earlier.

**Comment by wxiaoguang** [comment]
> > When the title in the issue has a value, set the text cursor at the end of the text. (#30090)
>
> I question that "autofocus on end of input" is good behaviour. Is the most common use case really to append to the title? I think a much more common use case would be to replace the title

Have you read #30090 ? 30090 is the real use case. And not only one user asked for this behavior, for example: @tyroneyeh  https://github.com/go-gitea/gitea/pull/36322 https://github.com/go-gitea/gitea/pull/36322/commits/ef649c8950727f774af3ab49d41329697d558894

**Comment by silverwind** [comment]
I think it's weak use case, but I wont chase that topic futher, so lets keep it focusing at the end of the text.

**Comment by silverwind** [comment]
Autofocus is back with `initInputAutoFocusEnd` and is now using a `IntersectionObserver`. This is needed because on the PR compare page, the `<input>` is hidden until `Compare` is clicked so `el.focus()` was a noop (hidden elements can't receive focus). Now it triggers as soon as the element becomes visible.

The behaviour of "last element" is also restored, but is not doing anything useful because issue/pr title can only be once on the page.

**Review by lafriks — DISMISSED** [review]

**Comment by silverwind** [comment]
Updated the autofocus behaviour and comment. IntersectionObserver will trigger for the last element to become visible, so we need no tracking variable.

**Comment by silverwind** [comment]
@wxiaoguang why remove `IntersectionObserver`? And why litter my PR with commented code?

**Comment by wxiaoguang** [comment]
> @wxiaoguang why remove `IntersectionObserver`? And why litter my PR with commented code?

image


You removed this FIXME. Actually it doesn't need to use IntersectionObserver. Only the caller know whether to trigger the focus logic. So `show-panel` is the right choice. https://github.com/go-gitea/gitea/pull/36606#issuecomment-3894019468

**Comment by wxiaoguang** [comment]
> And why litter my PR with commented code?

Where is the litter? https://github.com/go-gitea/gitea/pull/36606/commits/dfd9b776c29cd9482ce5b2a8d1aa936fb839c56b


image

**Comment by wxiaoguang** [comment]
> > why remove `IntersectionObserver`?
>
> You removed this FIXME. Actually it doesn't need to use IntersectionObserver. Only the caller know whether to trigger the focus logic. So show-panel is the right choice. https://github.com/go-gitea/gitea/pull/36606#issuecomment-3894019468


Let me explain why IntersectionObserver is wrong:

Suppose you have the IntersectionObserver for an element on the second page of the view port. After the whole page loads, the user focuses an element on the first page of the view port, then they scrolls, then your element will be focused incorrectly and interrupts user's operation.

**Comment by wxiaoguang** [comment]
Required by @silverwind according to discord discussion: please re-review @lunny @lafriks

**Review by lunny — DISMISSED** [review]

**Comment by silverwind** [comment]
@wxiaoguang Tested autofocus on PR Compare page after button click, does not work.

**Comment by wxiaoguang** [comment]
> @wxiaoguang Tested autofocus on PR Compare page after button click, does not work.

I have shown you the proper approach, maybe your AI can fix it.

**Review by lafriks — DISMISSED** [review]

**Comment by silverwind** [comment]
The proper approach is either the previous `IntersectionObserver` method or maybe moving the cursor in a one-time `focus` event handler.

**Comment by wxiaoguang** [comment]
You still understand nothing about the real problem . Just a waste of time again.

**Comment by wxiaoguang** [comment]
> Required by @silverwind according to discord discussion: please re-review @lunny @lafriks

Code changed, as required by @silverwind, please review again

**Comment by silverwind** [comment]
I fully understand the problem, checking with Claude.

**Comment by silverwind** [comment]
Claude proposes a solution with the native attribute and I think I have to agree because "autofocus on show" and "set cursor to end" are two separate concerns that should not be combined.

But I wont do more discussion on this, all i care about is that it works, and current branch works.

```ts
// Set cursor to end of issue title input when it receives focus.
// The "autofocus" attribute handles focus natively for both cases:
// 1. Initially visible (new issue page) - browser focuses on load
// 2. Initially hidden (compare/PR page) - onShowPanelClick focuses on reveal
const issueTitleInput = document.querySelector<HTMLInputElement>('#issue_title');
if (issueTitleInput) {
  const setEnd = () => issueTitleInput.setSelectionRange(issueTitleInput.value.length, issueTitleInput.value.length);
  if (document.activeElement === issueTitleInput) {
    setEnd(); // already focused by autofocus attribute
  } else {
    issueTitleInput.addEventListener('focus', setEnd, {once: true});
  }
}

**Comment by wxiaoguang** [comment]
> Claude proposes a solution with the native attribute and I think I have to agree because "autofocus on show" and "set cursor to end" are two separate concerns that should not be combined.

I have thought about this, whether use 2 different "attributes". For our case: these two behaviors can be combined together to make things simpler, and no side effect. #30090  and its related issues are clear enough. Although the `initInputAutoFocusEnd` is only used once, the best choice is to have this framework-level support, to support more use cases in the future (ever required by #36322 ). And it is clear that "only move cursor to end on the first autofocus, don't do that for the focusing later"

**Comment by silverwind** [comment]
> Code changed, as required by @silverwind, please review again

Review dismissal is a manual judgement that should only be considered when a PR is substantially changed. I thought I made that clear already.

**Comment by silverwind** [comment]
> > Claude proposes a solution with the native attribute and I think I have to agree because "autofocus on show" and "set cursor to end" are two separate concerns that should not be combined.
> 
> I have thought about this, whether use 2 different "attributes". For our case: these two behaviors can be combined together to make things simpler, and no side effect. #30090 and its related issues are clear enough. Although the `initInputAutoFocusEnd` is only used once, the best choice is to have this framework-level support, to support more use cases in the future (ever required by #36322 ). And it is clear that "only move cursor to end on the first autofocus, don't do that for the focusing later"

Native `autofocus` attributes has benefits, it works even when the browser has JS disabled. We should extend native autofocus, not replace it.

**Comment by silverwind** [comment]
I will rewrite to use native autofocus with HTML attributes `data-autofocus-end` and `data-autofocus-on-show` that will enable the additional behaviours.

**Comment by wxiaoguang** [comment]
> > Code changed, as required by @silverwind, please review again
> 
> Review dismissal is a manual judgement that should only be considered when a PR is substantially changed. I thought I made that clear already.

Please define what is "substantially changed", one line of core code can also cause "substantial change".

If there is no definition, there will be ongoing arguments and complains.

**Comment by wxiaoguang** [comment]
> I will rewrite to use native autofocus with HTML attributes `data-autofocus-end` and `data-autofocus-on-show` that will enable the additional behaviours.

1. Don't use IntersectionObserver
2. Don't use `data-autofocus-on-show`: according to standard, https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/autofocus , for elements like "dialog": the `autocus` elements should get focus automatically. It is already correctly done in Fomantic UI Modal and our "show-panel" handlers.

**Comment by silverwind** [comment]
There is no way to define a substantial change. If you want a dumb defintion, it would be > 50% of lines changes. But really, even a 1-line change can be substantial.

**Comment by wxiaoguang** [comment]
> There is no way to define a substantial change. If you want a dumb defintion, it would be > 50% of lines changes. But really, even a 1-line change can be substantial.

Then it will cause more arguments. What if when a few lines are changed, A thinks it is substantial but B doesn't think so:

* it indeed causes problems: A wins 
* it doesn't cause problem: B wins

In either case, A and B will argue more. Sometimes you are A I am B, sometimes you are B and I am A.

File: web_src/js/features/common-page.ts [hunk 3]
```diff
@@ -116,20 +116,36 @@ function attachInputDirAuto(el: Partial<HTMLInputElement | HTMLTextAreaElement>)
...
 }
 
-export function handleInputAutoFocusEnd(el: Element) {
-  queryElems(el, `[data-global-init="${InputAutoFocusEndInitName}"]`, doInputAutoFocusEnd);
-}
-
 export function initGlobalInput() {
   registerGlobalSelectorFunc('input, textarea', attachInputDirAuto);
-  registerGlobalInitFunc(InputAutoFocusEndInitName, doInputAutoFocusEnd);
+  registerGlobalSelectorFunc('[data-autofocus-end]', (el) => {
```
Comment (wxiaoguang) [inline web_src/js/features/common-page.ts]: I didn't use `registerGlobalSelectorFunc` because it is slower than `registerGlobalInitFunc`

Each `registerGlobalSelectorFunc` adds a new "query" call in the observer's loop.

And there are comments:

image

Comment (wxiaoguang) [reply web_src/js/features/common-page.ts]: If you don't like `data-global-init="initInputAutoFocusEnd"`, you can use `data-global-init="auto-focus-end"`

Comment (silverwind) [reply web_src/js/features/common-page.ts]: There is now `data-autofocus-end` and `data-autofocus-on-show-panel`. Provide the exact naming you want for both and I can implement.

Comment (wxiaoguang) [reply web_src/js/features/common-page.ts]: Or, another choice is to reuse the existing `registerGlobalSelectorFunc('input, textarea', attachInputDirAuto);`

Refactor and rename `attachInputDirAuto` to handle "auto focus end", then no more "registerGlobalSelectorFunc" is needed.

File: web_src/js/features/common-page.ts [hunk 4]
```diff
@@ -116,11 +116,37 @@ function attachInputDirAuto(el: Partial<HTMLInputElement | HTMLTextAreaElement>)
...
+    const panelSel = el.getAttribute('data-panel');
+    if (!panelSel) return;
+    for (const panel of document.querySelectorAll<HTMLElement>(panelSel)) {
+      if (!isElemVisible(panel)) continue;
+      const focusEl = panel.querySelector<HTMLInputElement>('[data-autofocus-on-show-panel]');
+      if (focusEl) {
+        focusEl.focus();
+        if (focusEl.hasAttribute('data-autofocus-end')) {
+          setSelectionEnd(focusEl);
+        }
```
Comment (silverwind) [inline web_src/js/features/common-page.ts]: Will try to eliminate this here so.

File: web_src/js/features/common-page.ts (hunk 3 above)
Comment (wxiaoguang) [reply web_src/js/features/common-page.ts]: > There is now `data-autofocus-end` and `data-autofocus-on-show-panel`. Provide the exact naming you want for both and I can implement.

No, don't use  `data-autofocus-on-show-panel`. `autofocus` behavior is well-defined.

https://github.com/go-gitea/gitea/pull/36606#issuecomment-3904393934


> > 2. Don't use `data-autofocus-on-show`: according to standard, https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/autofocus , for elements like "dialog": the `autocus` elements should get focus automatically. It is already correctly done in Fomantic UI Modal and our "show-panel" handlers.

File: web_src/js/features/common-page.ts (hunk 4 above)
Comment (silverwind) [reply web_src/js/features/common-page.ts]: done

File: web_src/js/features/common-page.ts [hunk 5]
```diff
@@ -116,11 +116,35 @@ function attachInputDirAuto(el: Partial<HTMLInputElement | HTMLTextAreaElement>)
...
+  // handles [data-autofocus-end], moves the cursor to end after native autofocus
+  registerGlobalSelectorFunc('[data-autofocus-end]', (el) => {
+    if (document.activeElement === el) {
+      setSelectionEnd(el as HTMLInputElement | HTMLTextAreaElement);
+    }
+  });
+
+  // handles [data-autofocus-on-show-panel], when a show-panel button is clicked, focus the element
+  // inside the shown panel. This handler runs after initGlobalButtons has already made the panel visible.
+  addDelegatedEventListener(document, 'click', '.show-panel', (el) => {
```
Comment (wxiaoguang) [inline web_src/js/features/common-page.ts]: Completely a mess and it can't be right.

I have shown you it should be done in the existing `.show-panel` handler.

**Comment by wxiaoguang** [comment]
So in the end, I am teaching your AI or teaching you? It seems that my code and comments are ignored.

File: web_src/js/features/common-page.ts (hunk 3 above)
Comment (silverwind) [reply web_src/js/features/common-page.ts]: all implemented

File: web_src/js/features/common-page.ts (hunk 5 above)
Comment (silverwind) [reply web_src/js/features/common-page.ts]: fixed already.

**Comment by silverwind** [comment]
all fixed now and tested.

**Comment by silverwind** [comment]
If you want to do more edits, do them now.

**Comment by wxiaoguang** [comment]
By your approach, the cursor flickers.

Because by using "autofocus", the element is focused in first time. But the "move to end" happens some time later after DOM ready.


-----

It's up to you

**Comment by wxiaoguang** [comment]
> Native `autofocus` attributes has benefits, it works even when the browser has JS disabled. We should extend native autofocus, not replace it.

The new changes just cause flickers. I insist on that my code is already good enough. If you don't like the "init name", you can change it to others you like. But the approach is almost the perfect one.

I don't see why you still use "JS disabled" as a reason, we all know that Gitea won't work without JS nowadays.

**Comment by silverwind** [comment]
Reverted to JS focus again, it can not be solved cleanly with native autofocus.

**Comment by silverwind** [comment]
Tested the latest changes, working as expected, so lgtm.

@lunny, @lafriks please re-review.

**Review by lafriks — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
@silverwind 

regression: Make automatic pull request title humanization optional #38317
