### PR TITLE
Don't show unnecessary citation JS error on UI

### LINKED ISSUE #28226: JavaScript WARNING/ERROR: JavaScript promise rejection
### Description

I have this https://github.com/run-llama/llama_index mirror in my gitea. And Chrome/FF shows:

image

On GitHub I can't see this Warning/Error.

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.43.0

### Operating System

Ubuntu 22.04.3 LTS x86_64

### How are you running Gitea?

gitea-1.21.0-linux-amd64

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #28226

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

File: web_src/js/features/citation.js [hunk 1]
```diff
@@ -19,9 +19,9 @@ const initInputCitationValue = async ($citationCopyApa, $citationCopyBibtex) =>
   const bibtexOutput = citationFormatter.format('bibtex', {lang});
   $citationCopyBibtex.attr('data-text', bibtexOutput);
   $citationCopyApa.attr('data-text', apaOutput);
-};
+}
```
Comment (silverwind) [inline web_src/js/features/citation.js:22]: Huh, quite an oversight that this was not async. Maybe there are lint rules to catch this.

**Review by delvh — APPROVED** [review]
