### PR TITLE
Fix error in diff html rendering

### LINKED ISSUE #13177: diff view leaks some html code
- Gitea version (or commit ref): 1.13.0+dev-593-g0db9043aa built with GNU Make 4.3, go1.15.2 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.26.2
- Operating system: gitea official docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes : https://try.gitea.io/zigg/testme/commit/9bd6915f409b3ae13dd284a716212059129c8dfe
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Diff view sometimes show additional html tag that should not be visible

## Screenshots

image

But it should be : 

```
-    print "// ", sys.argv
+    print("// ", sys.argv)
```

Note however that the extra tag is not visible in the file view : 
image

### PR DESCRIPTION
**Pull request by mrsdizzie**
Was missing an optional whitespace check in regex. Also noticed a rare case where diff.Type == Equal text would be empty and thus get a newline attached. Fixed that too.

Fixes #13177

### CODE REVIEW

File: services/gitdiff/gitdiff.go [hunk 1]
```diff
@@ -181,7 +181,7 @@ var (
 	removedCodePrefix = []byte(`<span class="removed-code">`)
 	codeTagSuffix     = []byte(`</span>`)
 )
-var addSpanRegex = regexp.MustCompile(`<span [class="[a-z]*]*$`)
+var addSpanRegex = regexp.MustCompile(`<span\s*[class="[a-z]*]*$`)
```
Comment (zeripath) [inline services/gitdiff/gitdiff.go]: Are you sure that this correct?

`[class="[a-z]*]*` seems like a very odd regexp to me

Comment (mrsdizzie) [reply services/gitdiff/gitdiff.go]: Yes it is right unfortunately  -- the only way to properly syntax highlight individual changes within a line (added/removed code class) is to syntax highlight the diffs first so the highlighting itself becomes part of the comparison for lines that have these individual changes highlighted. 

This can cause weird situations where the diff splits on syntax classes in various ways (usually when the change also involves changing the type of code/syntax) and this is to manually fix it. I added some tests for this type of thing starting here which shows how it can end up looking:

 https://github.com/go-gitea/gitea/blob/4cc8697a652a60263149fb794c46df87d19eff74/services/gitdiff/gitdiff_test.go#L45

So it should match any of these types of examples which are all points in which the code might be split for added/removed code sections:

```
<span
<span 
<span class
<span class="
<span class="p
<span class="nx
```

It is ugly but I didn't seem to find a better way within the diff code to properly syntax highlight these small inline changes since they need to be styled twice.

Comment (mrsdizzie) [reply services/gitdiff/gitdiff.go]: The alternative would be to just not syntax highlight those inline changes but it was requested in original addition of new syntax highlighting

It could be ok with me since it does feel hard to get right -- I think Github doesn't do this either probably for the same reason

Comment (zeripath) [reply services/gitdiff/gitdiff.go]: But what I mean is that isn't that group simply:

`[a-z="[]*` followed by `]*`

Comment (mrsdizzie) [reply services/gitdiff/gitdiff.go]: Sorry Im not sure I understand, what would be the full suggested change?

Comment (zeripath) [reply services/gitdiff/gitdiff.go]: I'm saying that `[class="[a-z]*]*` is equal to `[a-z="[]*]*`.

It seems like you were actually intending `(class="[a-z]*)?` ?

Comment (mrsdizzie) [reply services/gitdiff/gitdiff.go]: I think I'm still confused and not sure both what is not correct about the current one or why others would be preferred as the current one works as intended.

Sorry I feel slow today 😬

Comment (zeripath) [reply services/gitdiff/gitdiff.go]: https://play.golang.org/p/OU9jEWvG_qQ

Comment (mrsdizzie) [reply services/gitdiff/gitdiff.go]: Ah sorry, it does need to match stuff like "<span c" as well (which is in one of the tests linked above). So while the current one might match things it doesn't need to, those should never be present. I guess in some cases it might be unclear which variation of <span class it might need to match (<span c, <span cl, etc...) 

All this talk makes me dislike this feature even more.

Comment (zeripath) [reply services/gitdiff/gitdiff.go]: OK well I'm absolutely certain that you don't intend trailing `]` or internal `[` characters to match. 

```suggestion
var addSpanRegex = regexp.MustCompile(`<span\s*[a-z="]*$`)
```

If you intend `-` to match add it before the `]` in the regexp.

**Review by zeripath — APPROVED** [review]

**Comment by silverwind** [comment]
Maybe worth adding a test for?

**Review by techknowlogick — APPROVED** [review]

**Comment by zeripath** [comment]
I guess the backport for this was included in #13239

**Comment by mrsdizzie** [comment]
@zeripath indeed it was
