### PR TITLE
Use frontend fetch for branch dropdown component 

### LINKED ISSUE #14180: Slow to open a repo if there’s many branches in it
- Gitea version (or commit ref): 1.13.0
- Git version: git 2.29.2.windows
- Operating system: Windows 10 1809
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - Didn’t really try
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

The title may be a bit misleading.

I was building a local mirror of [PyTorch](https://github.com/pytorch/pytorch) manually using `git push —mirror`. And I found that opening the repo is exceptionally slow (~11 seconds). I also built a clone of gitea itself and the time to open the repo is reasonable (~2 seconds). 

I think the reason is that PyTorch has over 4000 branches in it.

### PR DESCRIPTION
**Pull request by HesterG**
- Send request to get branch/tag list, use loading icon when waiting for response.
- Only fetch when the first time branch/tag list shows.
- For backend, removed assignment to `ctx.Data["Branches"]` and `ctx.Data["Tags"]` from `context/repo.go` and passed these data wherever needed.
- Changed some `v-if` to `v-show` and used native `svg` as mentioned in https://github.com/go-gitea/gitea/pull/25719#issuecomment-1631712757 to improve perfomance when there are a lot of branches.
- Places Used the dropdown component:

     Repo Home Page
    
    Screen Shot 2023-07-06 at 12 17 51

    Commits Page

    Screen Shot 2023-07-06 at 12 18 34

    Specific commit -> operations -> cherry-pick
    
    Screen Shot 2023-07-06 at 12 23 28

    Release Page
    
    Screen Shot 2023-07-06 at 12 25 05

- Demo

    https://github.com/go-gitea/gitea/assets/17645053/d45d266b-3eb0-465a-82f9-57f78dc5f9f3

- Note:

  UI of dropdown menu could be improved in another PR as it should apply to more dropdown menus.

Fix #14180

### CODE REVIEW

File: web_src/js/components/RepoBranchTagSelector.vue [hunk 1]
```diff
@@ -1,6 +1,6 @@
 <template>
   <div class="ui floating filter dropdown custom">
-    <button class="branch-dropdown-button gt-ellipsis ui basic small compact button gt-df gt-m-0" @click="menuVisible = !menuVisible" @keyup.enter="menuVisible = !menuVisible">
+    <button class="branch-dropdown-button gt-ellipsis ui basic small compact button gt-df gt-m-0" @click="menuVisible = !menuVisible;fetchBranches()" @keyup.enter="menuVisible = !menuVisible">
```
Comment (wxiaoguang) [inline web_src/js/components/RepoBranchTagSelector.vue]: I think you need to watch the `menuVisible`

Otherwise, you already missed the `@keyup.enter` case here.

File: web_src/js/components/RepoBranchTagSelector.vue [hunk 2]
```diff
@@ -20,13 +20,13 @@
...
             <div class="two column row">
-              <a class="reference column" href="#" @click="createTag = false; mode = 'branches'; focusSearchField()">
+              <a class="reference column" href="#" @click="createTag = false; mode = 'branches'; focusSearchField(); fetchBranches()">
                 <span class="text" :class="{black: mode === 'branches'}">
                   <svg-icon name="octicon-git-branch" :size="16" class-name="gt-mr-2"/>{{ textBranches }}
                 </span>
               </a>
               <template v-if="!noTag">
-                <a class="reference column" href="#" @click="createTag = true; mode = 'tags'; focusSearchField()">
+                <a class="reference column" href="#" @click="createTag = true; mode = 'tags'; focusSearchField(); fetchBranches()">
```
Comment (wxiaoguang) [inline web_src/js/components/RepoBranchTagSelector.vue]: These two `reference column` elements need their own function now.

File: routers/web/web.go [hunk 3]
```diff
@@ -1094,6 +1094,7 @@ func registerRoutes(m *web.Route) {
 		}, context.RepoRef(), canEnableEditor, context.RepoMustNotBeArchived())
 
 		m.Group("/branches", func() {
+			m.Get("/list", repo.GetBrancheList)
```
Comment (delvh) [inline routers/web/web.go]: `GetBranche`**s**`List` or `ListBranches`

File: web_src/js/components/RepoBranchTagSelector.vue [hunk 4]
```diff
@@ -246,7 +246,27 @@ const sfc = {
         event.preventDefault();
         this.menuVisible = false;
       }
-    }
+    },
+    fetchBranchesOrTags: onInputDebounce(async function() {
+      const resp = await fetch(`${this.repoLink}/${this.mode}/list`);
+      const {results} = await resp.json();
```
Comment (delvh) [inline web_src/js/components/RepoBranchTagSelector.vue]: Should we perhaps cache the result?
So that we only query it once instead of whenever the user opens the selector?

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 1 above)
Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue]: Updated and this part is not changed.

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 2 above)
Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue]: Same as above. Now the goal of this PR is to send a request to get all branches using restful api and use loading icon while waiting for the response (like github).

File: routers/web/web.go (hunk 3 above)
Comment (HesterG) [reply routers/web/web.go]: Updated.

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 2 above)
Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue]: But still need to test the performance change first.

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 4 above)
Comment (silverwind) [reply web_src/js/components/RepoBranchTagSelector.vue]: I guess if we do caching, we should do it in a fetch wrapper shared for all fetches, and likely opt-in per consumer.

Ideally, I'd like to see a [swr-like](https://github.com/vercel/swr) caching strategy, but it must not be tied to any framework like Vue.

File: web_src/js/components/RepoBranchTagSelector.vue [hunk 5]
```diff
@@ -139,7 +139,9 @@ const sfc = {
       }
     });
   },
-
+  mounted() {
+    this.fetchBranchesAndTags();
```
Comment (wxiaoguang) [inline web_src/js/components/RepoBranchTagSelector.vue]: Is it right to do so? For the "release list" page, there are many branch selectors, each of them do a "fetch"?

File: web_src/js/components/RepoBranchTagSelector.vue [hunk 6]
```diff
@@ -246,7 +248,28 @@ const sfc = {
...
+      } 
+      if (!this.noTag) {
+        const resp = await fetch(`${this.repoLink}/tags/list`);
+        const {results} = await resp.json();
+        for (const tag of results) {
+          if (this.release) {
+            this.items.push({name: tag, url: tag, branch: false, tag: true, selected: tag === this.release.tagName});
+          } else {
+            this.items.push({name: tag, url: tag, branch: false, tag: true, selected: tag === this.defaultBranch});
+          }
```
Comment (silverwind) [inline web_src/js/components/RepoBranchTagSelector.vue]:
```suggestion
          const selected = tag === (this.release ? this.release.tagName : this.defaultBranch);
          this.items.push({name: tag, url: tag, branch: false, tag: true, selected});
```

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 5 above)
Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue]: That's true.. Maybe only fetch branches?

**Comment by HesterG** [comment]
For the filter step, I did some tests trying to figure out why sometimes the input get stuck, and I found that if use native svg instead of `svg-icon` component like in https://github.com/go-gitea/gitea/pull/25719/commits/d56f5c0f5b7e699356f7b863043ab98353299d6d, the input change will respond faster:

I am wondering if this is a proper way to improve this component (change `svg-component` to native one).

Demo (At the end of the following demos, I was deleting input at a constant speed, but the one with `svg-icon` component got stuck for about 2 - 3 seconds before deletion happened)

use `svg-icon` component:

https://github.com/go-gitea/gitea/assets/17645053/b35e6632-700c-4c4c-81f2-3e7f820bd935

use native `svg`:


https://github.com/go-gitea/gitea/assets/17645053/41e782a8-cf7e-4fdc-bd1a-0b2924ea7ef0

**Comment by wxiaoguang** [comment]
1. You need to do some profiling to figure out the key point
2. You can use "v-show" instead of "v-if" to avoid re-creating so many Vue components.

**Comment by HesterG** [comment]
I have done the profiling, and looks like the stuck time do come from vue `update` if using component:
 
Use `svg-component`, last two keydown takes 1.7s and 2.9s respectively, and the function that takes most of the time is `update` function from vue.

Screen Shot 2023-07-12 at 09 13 48

Use native `svg`,  last two keydown takes 194ms and 403ms respectively 

Screen Shot 2023-07-12 at 09 18 37

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 5 above)
Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue]: updated the fetch to be called only first time the list is shown

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 2 above)
Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue]: added the handler

**Comment by HesterG** [comment]
Updated description and the PR is ready for review now.

**Comment by silverwind** [comment]
> Use svg-component, last two keydown takes 1.7s and 2.9s respectively, and the function that takes most of the time is update function from vue.

I think this does highlight a inefficiency in the `svg-icon` component. In React, I would wrap the component in [`memo`](https://react.dev/reference/react/memo), so that it won't re-render until its props change. Does Vue have something similar?

**Comment by silverwind** [comment]
Now I guess the real question is why `svg-icon` takes so much processing time. Shouldn't vue components skip the render if all props are shallow-equal to the previous render? There appears to be `v-memo` and `v-once`, but they do seem unsuitable because they have to be set on a parent node.

**Review by lunny — APPROVED** [review]

**Comment by HesterG** [comment]
> BTW, which solution did you settle on here?

Now I used native `svg` instead of `svg-icon` component, I am not sure how to improve this if using `svg-icon` component.

**Comment by wxiaoguang** [comment]
To reproduce: prepare thousands of branches

Possible solutions:

1. symbol + use
2. v-html

**Comment by silverwind** [comment]
I have other solution ideas:

- wrap the component in a `v-memo`
- extract and memoize the `render` function using [memize](https://github.com/aduth/memize).

**Comment by wxiaoguang** [comment]
Just a guess, I think it's caused by the creation of thousands of SVG elements.

If v-memo can't avoid creating so many elements, the creating operation still hangs for seconds.

**Comment by silverwind** [comment]
For the record regarding `use` from [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use):

> For security reasons, browsers may apply the [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) on use elements and may refuse to load a cross-origin URL in the [href](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href) attribute. There is currently no defined way to set a cross-origin policy for use elements.

So unfortunately, it's not a option for gitea instances that have assets on a separate domain.

**Comment by silverwind** [comment]
> Just a guess, I think it's caused by the creation of thousands of Vue SVG elements.

If the problem is the loop, then yes, virtualization may help. Still, it sounds like when a list item is rendered because of a filter change, it would invoke the svg component rendering again, and this is definitely where `v-memo` should help, e.g. only the initial list rendering should be slow, subsequent filters should be fast.

**Comment by silverwind** [comment]
Does anyone have a repo with a lot of branches that I can mirror to my local instance?

**Comment by HesterG** [comment]
> Does anyone have a repo with a lot of branches that I can mirror to my local instance?

I used [pytorch](https://github.com/pytorch/pytorch) for test, I forked it and mirrored it to my localhost

**Comment by silverwind** [comment]
Unfortunately, I [hit another bug](https://github.com/go-gitea/gitea/issues/25909) when trying to migrate pytorch.

**Review by silverwind — APPROVED** [review]
Guess we can go with this for now until we find ways to optimize the SVG.

File: modules/context/repo.go [hunk 7]
```diff
@@ -689,24 +682,15 @@ func RepoAssignment(ctx *Context) context.CancelFunc {
...
 	// If not branch selected, try default one.
-	// If default branch doesn't exist, fall back to some other branch.
+	// If default branch doesn't exist, fall back to default branch from setting.
 	if len(ctx.Repo.BranchName) == 0 {
 		if len(ctx.Repo.Repository.DefaultBranch) > 0 && gitRepo.IsBranchExist(ctx.Repo.Repository.DefaultBranch) {
 			ctx.Repo.BranchName = ctx.Repo.Repository.DefaultBranch
-		} else if len(brs) > 0 {
-			ctx.Repo.BranchName = brs[0]
+		} else {
+			ctx.Repo.BranchName = setting.Repository.DefaultBranch
```
Comment (wxiaoguang) [inline modules/context/repo.go]: Is this change right if default branch doesn't exist?

File: routers/web/repo/repo.go [hunk 8]
```diff
@@ -621,3 +621,58 @@ func SearchRepo(ctx *context.Context) {
...
+		RepoID:          ctx.Repo.Repository.ID,
+		IsDeletedBranch: util.OptionalBoolFalse,
+		ListOptions: db.ListOptions{
+			ListAll: true,
+		},
+	}
+	branchOpts.ExcludeBranchNames = []string{ctx.Repo.Repository.DefaultBranch}
+	brs, err := git_model.FindBranchNames(ctx, branchOpts)
+	if err != nil {
+		ctx.ServerError("GetBranches", err)
```
Comment (wxiaoguang) [inline routers/web/repo/repo.go:676]: If you do so, all calls to `PrepareBranchList` should have a `if ctx.Written() { return } `

File: routers/web/repo/repo.go [hunk 9]
```diff
@@ -621,3 +621,58 @@ func SearchRepo(ctx *context.Context) {
...
+		return
+	}
+	ctx.Data["Branches"] = append(branchOpts.ExcludeBranchNames, brs...)
```
Comment (wxiaoguang) [inline routers/web/repo/repo.go]: Why you exclude a name and include it again here?

Could there be a case that DefaultBranch doesn't exist?

File: web_src/js/components/RepoBranchTagSelector.vue [hunk 10]
```diff
@@ -246,7 +246,35 @@ const sfc = {
...
+      this.createTag = mode === 'tags';
+      this.mode = mode;
+      this.focusSearchField();
+      this.fetchBranchesOrTags();
+    },
+    async fetchBranchesOrTags() {
+      if (!['branches', 'tags'].includes(this.mode) || this.isLoading) return;
+      // only fetch when branch/tag list has not been initialized
+      if (this.hasListInitialized[this.mode] ||
+      (this.mode === 'branches' && !this.showBranchesInDropdown) || (this.mode === 'tags' && this.noTag)) return;
```
Comment (wxiaoguang) [inline web_src/js/components/RepoBranchTagSelector.vue]: Need to reformat

File: web_src/js/components/RepoBranchTagSelector.vue [hunk 11]
```diff
@@ -246,7 +246,35 @@ const sfc = {
...
+      this.isLoading = true;
```
Comment (wxiaoguang) [inline web_src/js/components/RepoBranchTagSelector.vue:272]: Need a `finally` block in case network error happens

File: web_src/js/components/RepoBranchTagSelector.vue [hunk 12]
```diff
@@ -36,11 +36,11 @@
...
+      <div class="scrolling menu" :class="{'is-loading': isLoading}" ref="scrollContainer">
         <div v-for="(item, index) in filteredItems" :key="item.name" class="item" :class="{selected: item.selected, active: active === index}" @click="selectItem(item)" :ref="'listItem' + index">
           {{ item.name }}
-          <a v-if="enableFeed && mode === 'branches'" role="button" class="rss-icon ui compact right" :href="rssURLPrefix + item.url" target="_blank" @click.stop>
-            <svg-icon name="octicon-rss" :size="14"/>
+          <a v-show="enableFeed && mode === 'branches'" role="button" class="rss-icon ui compact right" :href="rssURLPrefix + item.url" target="_blank" @click.stop>
+            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="14" height="14" aria-hidden="true" class="svg octicon-rss"><path d="M2.002 2.725a.75.75 0 0 1 .797-.699C8.79 2.42 13.58 7.21 13.974 13.201a.75.75 0 0 1-1.497.098 10.502 10.502 0 0 0-9.776-9.776.747.747 0 0 1-.7-.798ZM2.84 7.05h-.002a7.002 7.002 0 0 1 6.113 6.111.75.75 0 0 1-1.49.178 5.503 5.503 0 0 0-4.8-4.8.75.75 0 0 1 .179-1.489ZM2 13a1 1 0 1 1 2 0 1 1 0 0 1-2 0Z"/></svg>
```
Comment (wxiaoguang) [inline web_src/js/components/RepoBranchTagSelector.vue]: Inline SVG doesn't need xmlns

File: web_src/js/components/RepoBranchTagSelector.vue [hunk 13]
```diff
@@ -246,7 +246,35 @@ const sfc = {
         event.preventDefault();
         this.menuVisible = false;
       }
-    }
+    },
+    handleTabSwitch(mode) {
+      this.createTag = mode === 'tags';
```
Comment (wxiaoguang) [inline web_src/js/components/RepoBranchTagSelector.vue]: The `createTag` can be computed?

File: web_src/js/components/RepoBranchTagSelector.vue [hunk 14]
```diff
@@ -246,7 +246,35 @@ const sfc = {
...
+      const resp = await fetch(reqUrl);
+      const {results} = await resp.json();
+      for (const result of results) {
+        let selected = false;
+        if (this.mode === 'branches') {
+          selected = result === this.defaultBranch;
+        } else {
+          selected = result === (this.release ? this.release.tagName : this.defaultBranch);
+        }
+        this.items.push({name: result, url: result, branch: this.mode === 'branches', tag: this.mode === 'tags', selected});
```
Comment (wxiaoguang) [inline web_src/js/components/RepoBranchTagSelector.vue]: It's not right here.

You are accessing an undetermined variable in an async function. The "this.mode" might not be the mode for the "results"

File: web_src/js/components/RepoBranchTagSelector.vue [hunk 15]
```diff
@@ -266,27 +294,15 @@ export function initRepoBranchTagSelector(selector) {
       isViewTree: false,
 
       active: 0,
-
+      isLoading: false,
+      // This means whether branch list/tag list has initialized
+      hasListInitialized: {
+        'branches': false,
+        'tags': false,
+      },
```
Comment (wxiaoguang) [inline web_src/js/components/RepoBranchTagSelector.vue:317]: These lines should be moved into the `data()` function

File: web_src/js/components/RepoBranchTagSelector.vue [hunk 16]
```diff
@@ -302,4 +318,12 @@ export default sfc; // activate IDE's Vue plugin
...
   display: inline-block;
 }
+
+.scrolling.menu.is-loading {
+  height: 200px;
+}
+
+.scrolling.menu.is-loading::after {
+  display: block !important; /* to override fomantic rule .ui.dropdown .menu .menu:after {display: none} */
+}
```
Comment (wxiaoguang) [inline web_src/js/components/RepoBranchTagSelector.vue]: Could the full selector `.ui.dropdown .menu .menu:after` be used to replace the `!important` ?

File: routers/web/repo/repo.go (hunk 8 above)
Comment (HesterG) [reply routers/web/repo/repo.go:676]: https://github.com/go-gitea/gitea/pull/25719/commits/0eb8956cbcf998fdd74997cd09fa52c5632bed7e

Not very sure why but added a commit because I am not familiar to this, I am wondering in which circumstances is `ctx.Written()` needed?

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 16 above)
Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue]: Yes changed to that https://github.com/go-gitea/gitea/pull/25719/commits/0eb8956cbcf998fdd74997cd09fa52c5632bed7e

File: routers/web/repo/repo.go (hunk 9 above)
Comment (HesterG) [reply routers/web/repo/repo.go]: This is for putting default branch on the top, and it is copied from old code, i will add a comment

```
// always put default branch on the top
```

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 11 above)
Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue:272]: Added in https://github.com/go-gitea/gitea/pull/25719/files#diff-588b4b6c148c056a96c4cb1732bb5a12b12ee31ed2e2938eaf751b44e5f9fd64

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 12 above)
Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue]: Removed in https://github.com/go-gitea/gitea/pull/25719/files#diff-588b4b6c148c056a96c4cb1732bb5a12b12ee31ed2e2938eaf751b44e5f9fd64

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 13 above)
Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue]: Moved to computed https://github.com/go-gitea/gitea/pull/25719/files#diff-588b4b6c148c056a96c4cb1732bb5a12b12ee31ed2e2938eaf751b44e5f9fd64

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 14 above)
Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue]: Added condition `if (this.isLoading) return; ` to `handleTabSwitch ` to avoid this
https://github.com/go-gitea/gitea/pull/25719/files#diff-588b4b6c148c056a96c4cb1732bb5a12b12ee31ed2e2938eaf751b44e5f9fd64

File: routers/web/repo/repo.go (hunk 9 above)
Comment (wxiaoguang) [reply routers/web/repo/repo.go]: Could there be a case that DefaultBranch doesn't exist? Then you would add a non-existing branch to the list?

File: modules/context/repo.go (hunk 7 above)
Comment (HesterG) [reply modules/context/repo.go]: I saw similar assignment is also done in [init.go](https://github.com/go-gitea/gitea/blob/d9763d605d5fef058d88cd8b894f99cb9cc06c1c/modules/repository/init.go#L267). Might need confirmation from @lunny and also for this question as well **https://github.com/go-gitea/gitea/pull/25719#discussion_r1264793053**, thanks!

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 15 above)
Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue:317]: This component does not have data() function yet as mentioned by the comment 
``` // no `data()`, at the moment, the `data()` is provided by the init code, which is not ideal and should be fixed in the future```

Comment (wxiaoguang) [reply web_src/js/components/RepoBranchTagSelector.vue:317]: > which is not ideal and should be fixed in the future

The old code was written as that because it came from legacy code by a refactoring PR (by copying&pasting to keep the old logic)

Since this PR changes a lot, maybe it's a chance for improving.

While it's not a must and it's not a block in my opinion.


----

Keep it as is if the `data()` related change would be too large.

Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue:317]: I checked this place, and I will leave this for another PR because it might need some other tests that are out of the scope of this PR.

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 10 above)
Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue]: Is there specific suggestion for reformat?

Comment (wxiaoguang) [reply web_src/js/components/RepoBranchTagSelector.vue]:
```suggestion
      if (this.hasListInitialized[this.mode] ||
        (this.mode === 'branches' && !this.showBranchesInDropdown) ||
        (this.mode === 'tags' && this.noTag)
      ) {
        return;
      }
```

File: modules/context/repo.go (hunk 7 above)
Comment (HesterG) [reply modules/context/repo.go]: For here, even if the default branch doesn't exist, it should not be handled here. Related further improvements can be done in another PR.

File: routers/web/repo/repo.go (hunk 9 above)
Comment (HesterG) [reply routers/web/repo/repo.go]: Same as above

**Comment by wxiaoguang** [comment]
Made some changes:

1. Fix the "branch" handling, do not add non-existing branch name to the list
2. Do not put "is-loading" on the "menu", use a separate element to avoid conflicting (unnecessary styles are removed)
3. There was a legacy "createTag" in Vue's data, now it's "computed", fix it
4. Use "toast" to show network errors, but, the "toast" framework itself needs more fixes, added FIXME
5. Use SVG symbol instead of hard-coded content (as my comment above https://github.com/go-gitea/gitea/pull/25719#issuecomment-1634096262)

**Review by wxiaoguang — CHANGES_REQUESTED** [review]
The merge is incorrect. It loses some fixes from #25875

**Comment by HesterG** [comment]
Done in https://github.com/go-gitea/gitea/pull/25719/commits/0ec8fd55d21e300ba02c9efc7c43326fb862bba8

**Comment by wxiaoguang** [comment]
Away from keyboard at the moment, feel free to dismiss my request change

**Review by wxiaoguang — APPROVED** [review]
dismiss request change

File: web_src/js/svg.js [hunk 17]
```diff
@@ -207,7 +208,10 @@ export const SvgIcon = {
     if (this.className) {
       classes.push(...this.className.split(/\s+/).filter(Boolean));
     }
-
+    if (this.symbolId) {
+      classes.push('gt-hidden', 'svg-symbol-container');
+      svgInnerHtml = `<symbol id="${this.symbolId}" viewBox="${attrs['^viewBox']}">${svgInnerHtml}</symbol>`;
+    }
```
Comment (silverwind) [inline web_src/js/svg.js:214]: What is this? Is it unused? I don't see this `symbolId` being used.

Comment (silverwind) [reply web_src/js/svg.js:214]: If it is intentional, could someone explain how this works?

File: web_src/js/modules/toast.js [hunk 18]
```diff
@@ -23,6 +23,8 @@ const levels = {
 async function showToast(message, level, {gravity, position, duration, ...other} = {}) {
   if (!message) return;
 
+  // FIXME: the "toast" mode shouldn't be imported asynchronously.
+  // Otherwise, network errors can't be shown because the toastify itself can't be loaded at that time.
   const {default: Toastify} = await import(/* webpackChunkName: 'toastify' */'toastify-js');
   const {icon, background, duration: levelDuration} = levels[level ?? 'info'];
```
Comment (silverwind) [inline web_src/js/modules/toast.js:27]: Just change it to a sync import above then. It is small enough to be okay.

File: web_src/js/svg.js (hunk 17 above)
Comment (wxiaoguang) [reply web_src/js/svg.js:214]: It is used, you can grep "symbol-id"

That's what I have proposed to avoid hard-coding the SVG content into Vue while still keeping good performance.

image

Comment (silverwind) [reply web_src/js/svg.js:214]: I see, well it's certainly not an ideal solution, but I guess better then hardcoding  the whole thing.

Comment (wxiaoguang) [reply web_src/js/svg.js:214]: Why it's not ideal? I think it's pretty clear and simple, and performant.

Comment (silverwind) [reply web_src/js/svg.js:214]: It's two DOM nodes, which could be one. I still think proper memoization would solve it.

Comment (wxiaoguang) [reply web_src/js/svg.js:214]: Not really.

Before:  4000 SVG nodes.

After:  1 SVG symbol container node + 4000 SVG "use" nodes, and these 4000 nodes don't need to duplicate the SVG XML anymore.


I would say it's pretty ideal.

Comment (silverwind) [reply web_src/js/svg.js:214]: From DOM size standpoint, yes it's better. I think there could even be a general solution with `use` for all vue components and vanilla JS svgs, which dynamically appends symbols to one global `<svg>`.

File: web_src/js/modules/toast.js (hunk 18 above)
Comment (HesterG) [reply web_src/js/modules/toast.js:27]: Could you help to change this? I am not familiar with webpack async/sync import.

File: web_src/js/components/RepoBranchTagSelector.vue [hunk 19]
```diff
@@ -110,12 +114,16 @@ const sfc = {
     formActionUrl() {
       return `${this.repoLink}/branches/_new/${this.branchNameSubURL}`;
     },
+    createTag() {
+      return this.mode === 'tags';
```
Comment (delvh) [inline web_src/js/components/RepoBranchTagSelector.vue]: I expected a different function name given this implementation.
What about i.e. `shouldCreateTag`?
(I know, will change some previously unaffected parts too)

File: web_src/js/modules/toast.js (hunk 18 above)
Comment (silverwind) [reply web_src/js/modules/toast.js:27]: Just remove line 28 and the comments above it and add this on top of the file:

```js
import Toastify from 'toastify-js';
```

This is a sync import, so `toastify-js` will be bundled into `index.js` after the change.

Comment (HesterG) [reply web_src/js/modules/toast.js:27]: Thanks, done in https://github.com/go-gitea/gitea/pull/25719/commits/5c5ac0aaa023b369ed41c11ea2ba21ce630637fa

File: web_src/js/components/RepoBranchTagSelector.vue (hunk 19 above)
Comment (HesterG) [reply web_src/js/components/RepoBranchTagSelector.vue]: Rename done in https://github.com/go-gitea/gitea/pull/25719/commits/5c5ac0aaa023b369ed41c11ea2ba21ce630637fa

**Review by silverwind — APPROVED** [review]
