### PR TITLE
Fix viewed files number is not right if not all files loaded

### LINKED ISSUE #35803: Incorrect viewed files counter in huge PRs
### Description

If you have a huge PR that contains large number of files, more than default limit of review page (e.g. for projects based on Unity 3D game engine), file counter of viewed files on "Files" page shows incorrect value on page load. For example, if you have limit per page is 100 files and you marked 118 of 130 files from PR as viewed then reloaded code review page, the file counter tells you "88/130" instead of "118/130" because remaining 30 files is not loaded to page (you need to click "load more" button to see the actual number of files).

This behaviour is very confusing when you reviewing a huge PRs!

Steps to reproduce:
1. Login to demo.gitea.com
2. Open this PR in my test repo: https://demo.gitea.com/didim99/test/pulls/4/files
3. Click "load more" to see all files
4. Mark some random files as viewed
5. Reload page

### Gitea Version

1.26.0+dev-91-g39c08ce4c1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Before "load more":
Image

After "load more":
Image

### Git Version

Not matters

### Operating System

Not matters

### How are you running Gitea?

Using demo.gitea.com

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix #35803

### CODE REVIEW

File: routers/web/repo/pull.go [hunk 1]
```diff
@@ -782,12 +782,16 @@ func viewPullFiles(ctx *context.Context, beforeCommitID, afterCommitID string) {
 	// as the viewed information is designed to be loaded only on latest PR
 	// diff and if you're signed in.
 	var reviewState *pull_model.ReviewState
+	var viewedFiles int
```
Comment (silverwind) [inline routers/web/repo/pull.go]: Would call this `numViewedFiles` for clarity, here and in `review_state.go`.

Comment (lunny) [reply routers/web/repo/pull.go]: 0c272c2e88

File: models/pull/review_state.go [hunk 2]
```diff
@@ -49,6 +49,19 @@ func init() {
...
+	if len(rs.UpdatedFiles) == 0 {
+		return 0
+	}
+	var viewedFiles int
+	for _, state := range rs.UpdatedFiles {
+		if state == Viewed {
+			viewedFiles++
+		}
+	}
+	return viewedFiles
```
Comment (silverwind) [inline models/pull/review_state.go]:
```suggestion
	var numViewedFiles int
	for _, state := range rs.UpdatedFiles {
		if state == Viewed {
			numViewedFiles++
		}
	}
	return numViewedFiles
```

**Review by silverwind — APPROVED** [review]

**Review by Zettat123 — APPROVED** [review]
