### PR TITLE
fix post parameter - on issue list - unset assignee

### LINKED ISSUE #7328: remove assignee on issue list return 500
- Gitea version (or commit ref): master branch
- Git version: latest build (master)
- Operating system: Linux/Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
  - [x] irrelevant
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/mgnehr/test/issues)
  - [ ] No
  - [ ] Not relevant
- Log gist:
2019/06/29 19:47:07 ...outers/repo/issue.go:1127:UpdateIssueAssignee() [E] ChangeAssignee: UpdateIssueUserByAssignee: user does not exist [uid: 0, name: , keyid: 0]

## Description

remove assignee on issue list return 500

## Screenshots

Peek 2019-06-29 19-47

### PR DESCRIPTION
**Pull request by Cherrg**
error occurred as wrong parameter were posted to server

fix #7328 - remove assignee on issue list return 500

Signed-off-by: Michael Gnehr <michael@gnehr.de>

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

File: public/js/index.js [hunk 1]
```diff
@@ -2137,12 +2137,16 @@ $(document).ready(function () {
...
-        var action = this.dataset.action
-        var elementId = this.dataset.elementId
-        var issueIDs = $('.issue-checkbox').children('input:checked').map(function() {
+        let action = this.dataset.action
+        let elementId = this.dataset.elementId
+        let issueIDs = $('.issue-checkbox').children('input:checked').map(function() {
             return this.dataset.issueId;
         }).get().join();
-        var url = this.dataset.url
+        let url = this.dataset.url
```
Comment (lafriks) [inline public/js/index.js]: missing semicolon

Comment (Cherrg) [reply public/js/index.js]: ty, fixed

**Review by lafriks — APPROVED** [review]
