### PR TITLE
Return an empty string when a repo has no avatar in the repo API

### LINKED ISSUE #31167: Incorrect API response for repositories without avatar
### Description

For repositories without an avatar, we now get this in the API response:

`"avatar_url": "https://demo.gitea.com/"`

In 1.21 this was `"avatar_url": ""`

### Gitea Version

1.23.0+dev-151-gc93cbc991e

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by kemzeb**
Resolves #31167.

https://github.com/go-gitea/gitea/pull/30885 changed the behavior of `repo.AvatarLink()` where it can now take the empty string and append it to the app data URL. This does not point to a valid avatar image URL, and, as the issue mentions, previous Gitea versions returned the empty string.

### CODE REVIEW

File: models/repo/avatar.go [hunk 1]
```diff
@@ -84,7 +84,13 @@ func (repo *Repository) relAvatarLink(ctx context.Context) string {
 	return setting.AppSubURL + "/repo-avatars/" + url.PathEscape(repo.Avatar)
 }
 
-// AvatarLink returns the full avatar url with http host. TODO: refactor it to a relative URL, but it is still used in API response at the moment
+// AvatarLink returns the full avatar url with http host or the empty string if the repo doesn't have an avatar.
+//
+// TODO: refactor it to a relative URL, but it is still used in API response at the moment
 func (repo *Repository) AvatarLink(ctx context.Context) string {
-	return httplib.MakeAbsoluteURL(ctx, repo.relAvatarLink(ctx))
```
Comment (kemzeb) [inline models/repo/avatar.go:89]: I am wondering is we should instead perform this empty string check in `MakeAbsoluteURL()` or `IsRelativeURL()`?

Comment (kemzeb) [reply models/repo/avatar.go:89]: FYI the main culprit is `url.Parse()` which exists within this function call chain: `MakeAbsoluteURL()` -> `IsRelativeURL()` -> `url.Parse()`. It accepts empty strings.

Comment (silverwind) [reply models/repo/avatar.go:89]: There are only two uses of `MakeAbsoluteURL`, so I suggest to add a `err` return value to it and use it for invalid inputs like a empty string.

```
models/repo/avatar.go:89:	return httplib.MakeAbsoluteURL(ctx, repo.relAvatarLink(ctx))
models/user/avatar.go:94:	return httplib.MakeAbsoluteURL(ctx, u.AvatarLinkWithSize(ctx, 0))
```

Comment (silverwind) [reply models/repo/avatar.go:89]: Thought it raises the question, is empty string really invalid? One could see it being valid and the function just returning the current url origin. In this case it makes sense to perform the validation at the caller site.

File: models/repo/avatar.go [hunk 2]
```diff
@@ -84,7 +84,13 @@ func (repo *Repository) relAvatarLink(ctx context.Context) string {
...
+	relLink := repo.relAvatarLink(ctx)
+	if len(relLink) > 0 {
```
Comment (wxiaoguang) [inline models/repo/avatar.go]:
```suggestion
	if relLink != "" {
```

**Review by wxiaoguang — APPROVED** [review]
Oops, I forgot that the link could be empty

File: models/repo/avatar.go (hunk 1 above)
Comment (wxiaoguang) [reply models/repo/avatar.go:89]: It's fine for "user avatar" because it could never be empty IIRC.

And empty string is valid URL. For example: `href=""` or `href="?k=v"`.

So the check should be done in `AvatarLink` function.

Comment (kemzeb) [reply models/repo/avatar.go:89]: > Thought it raises the question, is empty string really invalid? One could see it being valid and the function just returning the current url origin. In this case it makes sense to perform the validation at the caller site.

> So the check should be done in AvatarLink function.

I agree. Returning an empty URL string appears to be a pattern that is followed in the API when dealing with missing/non-existent URLs and I don't think we should force this on library code (since in the future there maybe callers that depend on the current behavior).

File: models/repo/avatar.go [hunk 3]
```diff
@@ -84,7 +84,13 @@ func (repo *Repository) relAvatarLink(ctx context.Context) string {
...
 
-// AvatarLink returns the full avatar url with http host. TODO: refactor it to a relative URL, but it is still used in API response at the moment
+// AvatarLink returns the full avatar url with http host or the empty string if the repo doesn't have an avatar.
+//
+// TODO: refactor it to a relative URL, but it is still used in API response at the moment
 func (repo *Repository) AvatarLink(ctx context.Context) string {
-	return httplib.MakeAbsoluteURL(ctx, repo.relAvatarLink(ctx))
+	relLink := repo.relAvatarLink(ctx)
+	if relLink != "" {
+		return httplib.MakeAbsoluteURL(ctx, repo.relAvatarLink(ctx))
```
Comment (wxiaoguang) [inline models/repo/avatar.go]:
```suggestion
		return httplib.MakeAbsoluteURL(ctx, relLink)
```

Comment (kemzeb) [reply models/repo/avatar.go]: Yikes not sure why I made the call to `relAvatarLink()` twice 😅

**Comment by silverwind** [comment]
Does `models/user/avatar.go:94` need the same treatment? Share a function maybe?

**Review by delvh — APPROVED** [review]

**Comment by kemzeb** [comment]
> Does models/user/avatar.go:94 need the same treatment? Share a function maybe?

After reading [this](https://github.com/go-gitea/gitea/pull/31187#discussion_r1621586053) comment and taking a gander at [this](https://github.com/go-gitea/gitea/blob/a4275951ba9635e9b7de6a91812b6cc9622c8c9b/models/user/avatar.go#L60) function, I don't believe we need to consider this as it looks like the user will always have an avatar

**Comment by jpraet** [comment]
@yardenshoham any idea what's missing to get the GiteaBot to backport this PR? Thanks

**Comment by yardenshoham** [comment]
It creates backports whenever a new commit is pushed. There were no new commits since you added the label.

**Comment by silverwind** [comment]
> It creates backports whenever a new commit is pushed. There were no new commits since you added the label.

I recall it had backported before even without any new commits, was that changed?

**Comment by yardenshoham** [comment]
No. New commits were always the only trigger.

**Comment by silverwind** [comment]
Imho, it should also watch when backport-related labels change on a merged PR.

**Comment by yardenshoham** [comment]
It's a bit of a problem because we only have one filesystem so concurrent cherry-picks would happen.

**Comment by silverwind** [comment]
Hmm, sounds like you need some form of distributed locking. A shared Redis could be used for example.
