### PR TITLE
Swift files can be passed either as file or as form value

### LINKED ISSUE #33990: Swift Package Manager Publishing using commandline throws error
### Description

There seem some error using apples swift publish command on swift package manager registry

```
swift package-registry publish -v test.Test 1.1.13
info: archiving the source at '/Users/wolfgangreithmeier/spm_test_lib'
info: publishing test.Test archive at '/Users/wolfgangreithmeier/spm_test_lib/.build/registry/publish/test.Test-1.1.13.zip' to https://127.0.0.1:8080/
info: publishing test.Test 1.1.13 to https://127.0.0.1:8080/test/Test/1.1.13
Error: failed publishing: server error 409: upload failed, package exists:test.Test-1.1.13.zip
```

using curl works without problem

```
curl -k -v -X PUT --user ....:.... \
         -H "Accept: application/vnd.swift.registry.v1+json" \
         -F source-archive=@spm_test_lib.zip \
         https://127.0.0.1:3000/api/packages/swift-repo/swift/test/Test/1.2.1
*   Trying 127.0.0.1:3000...
* Connected to 127.0.0.1 (127.0.0.1) port 3000
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: C=DE; ST=Some-State; L=Munich; O=Internet Widgits Pty Ltd
*  start date: Sep 29 16:43:04 2024 GMT
*  expire date: Sep 27 16:43:04 2034 GMT
*  issuer: C=DE; ST=Some-State; L=Munich; O=Internet Widgits Pty Ltd
*  SSL certificate verify ok.
* using HTTP/2
* Server auth using Basic with user 'admin'
* [HTTP/2] [1] OPENED stream for https://127.0.0.1:3000/api/packages/swift-repo/swift/test/Test/1.2.1
* [HTTP/2] [1] [:method: PUT]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: 127.0.0.1:3000]
* [HTTP/2] [1] [:path: /api/packages/swift-repo/swift/test/Test/1.2.1]
* [HTTP/2] [1] [authorization:  ......]
* [HTTP/2] [1] [user-agent: curl/8.6.0]
* [HTTP/2] [1] [accept: application/vnd.swift.registry.v1+json]
* [HTTP/2] [1] [content-length: 34891]
* [HTTP/2] [1] [content-type: multipart/form-data; boundary=------------------------V4sAMoUbKlnyqmUHIfSozi]
> PUT /api/packages/swift-repo/swift/test/Test/1.2.1 HTTP/2
> Host: 127.0.0.1:3000
> Authorization: Basic YWRtaW46YWRtaW5wYXNzd29yZDEyMw==
> User-Agent: curl/8.6.0
> Accept: application/vnd.swift.registry.v1+json
> Content-Length: 34891
> Content-Type: multipart/form-data; boundary=------------------------V4sAMoUbKlnyqmUHIfSozi
> 
* We are completely uploaded and fine
< HTTP/2 201 
< content-version: 1
< content-length: 0
< date: Sun, 23 Mar 2025 19:55:31 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
```

### Gitea Version

1.23.5

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/wgr1984/edb15ebabadad1c4f18cf4c0b0d2eb31

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Docker:  gitea/gitea:latest

### How are you running Gitea?

Docker compose setup

```
version: '3'

networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea_password
      # Server settings
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__ROOT_URL=https://localhost:3000/
      - GITEA__server__SSH_DOMAIN=localhost
      - GITEA__server__SSH_PORT=222
      - GITEA__server__SSH_LISTEN_PORT=22
      - GITEA__server__APP_NAME=Gitea
      # HTTPS settings
      - GITEA__server__PROTOCOL=https
      - GITEA__server__CERT_FILE=/data/ssl/gitea.crt
      - GITEA__server__KEY_FILE=/data/ssl/gitea.key
      # Skip setup page
      - GITEA__security__INSTALL_LOCK=true
      # Language settings
      - GITEA__i18n__LANGS=en-US
      - GITEA__i18n__NAMES=English
      # Authentication settings
      - GITEA__service__REQUIRE_SIGNIN_VIEW=true
      - GITEA__service__REGISTER_EMAIL_CONFIRM=false
      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
      - GITEA__openid__ENABLE_OPENID_SIGNUP=false
      - GITEA__oauth2_client__ENABLE_AUTO_REGISTRATION=false
      - GITEA__service__ENABLE_BASIC_AUTHENTICATION=true
      - GITEA__service__DISABLE_REGISTRATION=true
      # 2FA settings
      - GITEA__security__REQUIRE_SIGNIN_2FA=true
      - GITEA__security__DISABLE_2FA=false
      # Repository and package settings
      - GITEA__repository__DISABLE_REPOSITORIES=true
      - GITEA__repository__DISABLE_HTTP_GIT=true
      - GITEA__repository__DISABLE_SSH=true
      - GITEA__packages__ENABLED=true
      - GITEA__repository__DEFAULT_PRIVATE=true
      - GITEA__repository__DEFAULT_REPO_UNITS=packages
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - ./ssl:/data/ssl:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: gitea-db
    restart: always
    networks:
      - gitea
    environment:
      - MYSQL_ROOT_PASSWORD=gitea_root_password
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea_password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306" 
```

### Database

MSSQL

### PR DESCRIPTION
**Pull request by wgr1984**
Fix #33990

### CODE REVIEW

**Comment by KN4CK3R** [comment]
Alternative fix:
```diff
@@ -304,10 +304,18 @@ func UploadPackageFile(ctx *context.Context) {
 
        packageVersion := v.Core().String()
 
-       file, _, err := ctx.Req.FormFile("source-archive")
+       var file io.ReadCloser
+       multipartFile, _, err := ctx.Req.FormFile("source-archive")
        if err != nil {
-               apiError(ctx, http.StatusBadRequest, err)
-               return
+               content := ctx.Req.FormValue("source-archive")
+               if content != "" {
+                       file = io.NopCloser(strings.NewReader(content))
+               } else {
+                       apiError(ctx, http.StatusBadRequest, err)
+                       return
+               }
+       } else {
+               file = multipartFile
        }
        defer file.Close()
```
+ tests

**Comment by hiifong** [comment]
hi @wgr1984, would you be interested in continuing to complete the pr?

**Comment by wgr1984** [comment]
sure, will finish it once i find a minute to get local build running, in
order to confirm impl. and update test (in case needed)

Am Do., 3. Apr. 2025 um 12:04 Uhr schrieb hiifong ***@***.***

**Comment by wgr1984** [comment]
updated + test. Metadata looks good, too 👍 

```
curl -k --location 'https://127.0.0.1:3000/api/packages/tet/swift/test/TestLib/1.3.19' \
--header 'Accept: application/vnd.swift.registry.v1+json' \
--header 'Authorization: Basic dGV0OmRlZmF1bHQ=' \
--header 'Cookie: _csrf=BuZq7gKCTbJRLox5fIJSVlw_BNI6MTc0Mzk2NDIwODc2MTI2OTAwMA; i_like_gitea=497d7722fdfa170e'

{
   "id":"test.TestLib",
   "version":"1.3.19",
   "resources":[
      {
         "name":"source-archive",
         "type":"application/zip",
         "checksum":"3d4247adb875f627f5afd3ac860ff027ede1bb45f883059d4ceb5a8a025676df"
      }
   ],
   "metadata":{
      "@context":[
         "http://schema.org/"
      ],
      "@type":"SoftwareSourceCode",
      "name":"TestLib",
      "version":"1.3.19",
      "description":"A test Swift package",
      "keywords":[
         "test",
         "swift"
      ],
      "license":"MIT",
      "author":{
         "@type":"Person"
      },
      "programmingLanguage":{
         "@type":"ComputerLanguage",
         "name":"Swift",
         "url":"https://swift.org"
      }
   }
}

```

image

File: routers/api/packages/swift/swift.go [hunk 1]
```diff
@@ -304,10 +304,18 @@ func UploadPackageFile(ctx *context.Context) {
 
 	packageVersion := v.Core().String()
 
-	file, _, err := ctx.Req.FormFile("source-archive")
+	var file io.ReadCloser
+	multipartFile, _, err := ctx.Req.FormFile("source-archive")
 	if err != nil {
```
Comment (hiifong) [inline routers/api/packages/swift/swift.go]: The error here I think may need to be handled separately, if it's a http.ErrMissingFile error then we need to get the file content from FromValue, otherwise it just returns an error.

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
CI failure seems related.

**Review by hiifong — APPROVED** [review]

**Comment by hiifong** [comment]
I was going to run the MySQL tests locally, but very unfortunately I can't.

image

**Review by delvh — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Need to figure out the root problem and fix.

```
=== TestPackageSwift/LookupPackageIdentifiers (tests/integration/api_packages_swift_test.go:411)
--- FAIL: TestPackageSwift (0.76s)
    testlogger.go:61: 2025/04/13 23:02:49 modules/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /home/runner/work/gitea/gitea/tests/gitea-lfs-meta
    --- FAIL: TestPackageSwift/UploadMultipart (0.04s)
        testlogger.go:61: 2025/04/13 23:02:50 HTTPRequest [I] router: completed PUT /api/packages/user2/swift/test-scope/test_package/1.0.4 for test-mock:12345, 401 Unauthorized in 1.4ms @ packages/api.go:43(packages.reqPackageAccess)
        testlogger.go:61: 2025/04/13 23:02:50 HTTPRequest [I] router: completed PUT /api/packages/user2/swift/test-scope/test_package/1.0.4 for test-mock:12345, 201 Created in 16.8ms @ swift/swift.go:294(swift.UploadPackageFile)
        api_packages_swift_test.go:248: 
            	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/api_packages_swift_test.go:248
            	Error:      	Not equal: 
            	            	expected: "1.0.4"
            	            	actual  : "1.0.3"
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1 +1 @@
            	            	-1.0.4
            	            	+1.0.3
            	Test:       	TestPackageSwift/UploadMultipart
        api_packages_swift_test.go:261: 
            	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/api_packages_swift_test.go:261
            	Error:      	Not equal: 
            	            	expected: "test_package-1.0.4.zip"
            	            	actual  : "test_package-1.0.3.zip"
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1 +1 @@
            	            	-test_package-1.0.4.zip
            	            	+test_package-1.0.3.zip
            	Test:       	TestPackageSwift/UploadMultipart
        testlogger.go:61: 2025/04/13 23:02:50 .../packages/packages.go:168:createPackageAndVersion() [E] Error inserting package: package version already exists
        testlogger.go:61: 2025/04/13 23:02:50 HTTPRequest [I] router: completed PUT /api/packages/user2/swift/test-scope/test_package/1.0.4 for test-mock:12345, 409 Conflict in 5.3ms @ swift/swift.go:294(swift.UploadPackageFile)
```

**Review by wxiaoguang — DISMISSED** [review]
CI fails, need to figure out the root problem and fix.

**Comment by wgr1984** [comment]
I know why because the test cases rely on each other. To test that went
need to get the. Independent, but it's a bigger change ...

wxiaoguang ***@***.***> schrieb am Mo. 14. Apr. 2025 um 02:18:

**Comment by KN4CK3R** [comment]
Just move the upload test to the bottom or remove the package after uploading.

**Comment by wgr1984** [comment]
more fixing the symptom than the issue but sure, will do

**Comment by wxiaoguang** [comment]
Strange, it doesn't explain why only MySQL fails, other databases succeed ..... anyway we need to make the CI pass to merge .......

File: routers/api/packages/swift/swift.go [hunk 2]
```diff
@@ -290,7 +290,24 @@ func DownloadManifest(ctx *context.Context) {
...
+	}
+	if multipartFile != nil {
+		return multipartFile, nil
+	}
+
+	content := ctx.Req.FormValue(formKey)
+	if content == "" {
+		return nil, nil
+	}
+	return io.NopCloser(strings.NewReader(ctx.Req.FormValue(formKey))), nil
```
Comment (wxiaoguang) [inline routers/api/packages/swift/swift.go:307]: I made a copy-paste mistake, ->  Fix some trivial problems #34237
