### PR TITLE
fix github migration error when using multiple tokens

### LINKED ISSUE #34141: Error while migrating with multiple github token
### Description

Image

### Gitea Version

1.23.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### PR DESCRIPTION
**Pull request by TheFox0x7**
Git authorization was not taking into account multiple token feature, leading to auth failures

Closes: https://github.com/go-gitea/gitea/issues/34141

---

I made it default to first token. I'm honestly not sure if it wouldn't be better to scrap the multi token feature instead. The UI hides the tokens so it's hard to tell if no mistake was made in the input and it's the only provider "supporting" this.
I guess the intention was to somewhat speed up migration from github for a single repository which is nice too.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
IIRC "multiple tokens" are used to benefit more "access rate limit quota"? If only the first token is used, would it be more likely reach the rate limit?

File: services/migrations/github.go [hunk 1]
```diff
@@ -872,3 +872,15 @@ func (g *GithubDownloaderV3) GetReviews(ctx context.Context, reviewable base.Rev
...
 }
+
+// FormatCloneURL add authentication into remote URLs
+func (g *GithubDownloaderV3) FormatCloneURL(opts MigrateOptions, remoteAddr string) (string, error) {
+	u, err := url.Parse(remoteAddr)
+	if err != nil {
+		return "", err
+	}
+	if len(opts.AuthToken) > 0 {
+		u.User = url.UserPassword("oauth2", strings.Split(opts.AuthToken, ",")[0])
```
Comment (wxiaoguang) [inline services/migrations/github.go:886]: What about this comment?

```suggestion
		// "multiple tokens" are used to benefit more "API rate limit quota"
		// git clone doesn't count for rate limits, so only use the first token.
		u.User = url.UserPassword("oauth2", strings.Split(opts.AuthToken, ",")[0])
```

**Review by wxiaoguang — APPROVED** [review]

File: services/migrations/github_test.go [hunk 2]
```diff
@@ -429,3 +430,36 @@ func TestGitHubDownloadRepo(t *testing.T) {
...
+			desc:             "Multi Token",
+			token:            "token1,token2",
+			expectedCloneURL: "https://oauth2:token1@github.com",
+		},
+	}
+	factory := GithubDownloaderV3Factory{}
+
+	for _, tC := range testCases {
+		t.Run(tC.desc, func(t *testing.T) {
+			opts := base.MigrateOptions{CloneAddr: "https://github.com/go-gitea/gitea", AuthToken: tC.token}
```
Comment (hiifong) [inline services/migrations/github_test.go:455]: The current gitea repository is too big, maybe we can switch to a smaller repository for testing, which will speed up the testing time

**Review by hiifong — APPROVED** [review]

File: services/migrations/github_test.go (hunk 2 above)
Comment (wxiaoguang) [reply services/migrations/github_test.go:455]: It only "parses", it doesn't "clone".

**Comment by wxiaoguang** [comment]
@TheFox0x7 

https://github.com/go-gitea/gitea/issues/34141#issuecomment-2800253860

> the entire GitHub migration was failing after this fix

**Comment by wxiaoguang** [comment]
CI passes, but does it really work with GitHub oauth2?

By reading the "oauth2" code, it does `token.SetAuthHeader(req2)`, then:

image


Is it the same as your new code `u.User = url.UserPassword(...)` ?

**Comment by wxiaoguang** [comment]
If I understand correctly, the "oauth2:token" works with GitHub migration on your side, and at the moment it's unclear about how to reproduce the user's problem, right?
