### PR TITLE
fix topic bar to allow prefixes

### LINKED ISSUE #7126: Unable to create a new topic because it's a substring of an existing one
- Gitea version (or commit ref): 1.8.2 
- Git version: 2.17.1
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/iamthefij/test-tag-issue)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

After creating a topic such as `prefix-suffix` and saving (on any repo), it becomes impossible to create a new topic named simply `prefix` because Gitea forces completion to `prefix-suffix`.

### PR DESCRIPTION
**Pull request by Cherrg**
- do not select if escape is pressed
- allow prefixes by adding current request content to result list
- remove/escape html-tags before insert on page

#### Update
- sort typed word to top
- remove already present topics from dropdown list

fix #7126 (Unable to create a new topic because it's a substring of an existing one)

Signed-off-by: Michael Gnehr <michael@gnehr.de>

### CODE REVIEW

**Comment by mrsdizzie** [comment]
This looks better thank you! Would it be possible instead of (or in addition to) adding the current request to the list to also not show something that is already a tag (or been entered but not yet saved in the current session).

So as an example here:

Screen Shot 2019-06-28 at 12 57 46 PM

It shouldn't show golang as a suggestion since it has already been selected and will just disappear if you try to pick it a second time.

**Comment by Cherrg** [comment]
update:
- sort typed word to top
- remove already present topics from dropdown list

**Comment by mrsdizzie** [comment]
Still looks like it shows already selected tags as suggestions (unless I'm doing something wrong):

tags (2)

**Comment by Cherrg** [comment]
i didn't notice that there where other class names for previously present topics and new added ones.
Should be better now

**Review by mrsdizzie — APPROVED** [review]

**Comment by mrsdizzie** [comment]
That looks great thank you for all of these PRs they really add up!

Wondering if it is still necessary to add the current query to the list if we successfully remove already used tags (since there will be no conflict as reported in the original issue). I have no strong preference on that though.

File: public/js/index.js [hunk 1]
```diff
@@ -2864,18 +2865,52 @@ function initTopicbar() {
             throttle: 500,
             cache: false,
             onResponse: function(res) {
-                var formattedResponse = {
+                let formattedResponse = {
```
Comment (zeripath) [inline public/js/index.js:2868]: Hmm we don't use `let` anywhere else in index.js. Are you sure that this doesn't change our compatibility?

Comment (Cherrg) [reply public/js/index.js:2868]: `let` and `const` where introduced with ECMAScript 6 and implemented since:


Feature | Chrome | Edge | Firefox (Gecko) | Internet Explorer | Opera | Safari
-- | -- | -- | -- | -- | -- | --
Basic support | 41.0 | 12 | 44 (44) | 11 | 17 | ?

* Is there a list what minimal browser versions are targeted by gitea?
* My IDE mark all `var` with warning. 
I use `let` and `const` as they're more specific what type of variable I need. Furthermore I'm sure the variable isn't changed somewhere else in the code. (->which result in better code -> my opinion)

(If I should change this back to `var` I'll have to look for these keywords in my other PRs as well, which is no problem, i only need to know)

Comment (silverwind) [reply public/js/index.js:2868]: Usage of `let` is fine. see [here](https://github.com/go-gitea/gitea/blob/master/package.json#L13) for supported browsers, basically modern browsers and IE11, but we will eventually drop IE11 at some point, see https://github.com/go-gitea/gitea/issues/6147.

Comment (silverwind) [reply public/js/index.js:2868]: > My IDE mark all var with warning.

That should not happen if it respects `.eslintrc`. Did you run `make js` or `make npm` and have your editor configured to use eslint?

**Review by zeripath — APPROVED** [review]

File: public/js/index.js [hunk 2]
```diff
@@ -2864,18 +2865,52 @@ function initTopicbar() {
...
                     success: false,
                     results: [],
                 };
+                const escapeHtml = function (text) {
+                    let esc = document.createElement('div');
+                    esc.innerHTML = text;
```
Comment (silverwind) [inline public/js/index.js]: User-generated content should *never* be fed to `.innerHTML` for security reasons. If the goal of this is to escape HTML entities, use a function like https://stackoverflow.com/a/6234804/808699.

**Review by silverwind — CHANGES_REQUESTED** [review]

**Comment by silverwind** [comment]
Please don't land yet until above comment is resolved (seems I lack permission to block this PR via negative review).

**Review by zeripath — CHANGES_REQUESTED** [review]
As per @silverwind

**Comment by zeripath** [comment]
Don't worry I'm fairly certain our merging stuff wouldn't let us merge in any case.

File: public/js/index.js (hunk 1 above)
Comment (Cherrg) [reply public/js/index.js:2868]: `make js` runs without problems, i've added `.eslintrc` to eslint configuration of intelli/goland -> but it mark them nevertheless, but who cares ;)

File: public/js/index.js (hunk 2 above)
Comment (Cherrg) [reply public/js/index.js]: I previously used the same function as here ('https://github.com/go-gitea/gitea/pull/7225/files#diff-e70fdf29cba0fbb5a52462aed7e5c97dR3193') [1] which does the same thing as your linked method[2].
- the result: semantic js somehow parsed the content back to html code and inserted it with html element tags in preview. 
 As example i added your linked escape function. My inserted text is `<font style='color:green!important;'>colored</font>`
Peek 2019-06-29 19-11
  This way JS could be injected too.
- Therefore i used function above to escape and strip off html tags. (special letters are rejected on topics by gitea server). ~~It is safe if the element `esc` is never added to DOM~~. Pro: browser could be used for parsing html. 
- I could change this to jquery implementation mentioned here: https://stackoverflow.com/questions/5002111/how-to-strip-html-tags-from-string-in-javascript/5002157#5002157 [4] (`jQuery('<b>unsafe html here</b>').text()`)
 but this does the same thing:
grafik
   - **Image description**
     * escapeHtml1: [1] equal to suggested, tested while coding
     * escapeHtml2: [2] suggested, result in gif
     * escapeHtml3: current implementation, without jquery
     * escapeHtml4: [4] jquery implementation

     * tested escaping after function definitions

~~-> there should be no security issue with current implementation~~

Comment (silverwind) [reply public/js/index.js]: If it's never added to the DOM, it should be safe. I always get suspious on any `.innerHTML` or `.html()` usage, almost always there are better solutions.

If you just want to strip HTML tags from a string, this should be sufficient (it will of course fail on strings containing `<` and `>`, but so will the `.innerHTML` method):

```js
function stripHTMLTags (str) {
  return str.replace(/<[^>]*>?/gm, "");
}

Comment (silverwind) [reply public/js/index.js]: Actually, I do have to correct myself. Even if HTML is not appended to the DOM, scripts can still execute. Try this in your browser console:

```js
let div = document.createElement('div');
div.innerHTML = `<img src='x' onerror='alert("xss")'>`;
```

So anyways, would prefer if you can switch to a regex-only solution.

Comment (Cherrg) [reply public/js/index.js]: there is always something new to know, I didn't know this case.
I will replace it.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Should be good to go.

**Review by zeripath — APPROVED** [review]
