### PR TITLE
Fix bug on admin subcommand

### LINKED ISSUE #17532: v1.16: Runtime panic when creating user
Spotted while trying to deploy most recent dev (somewhere around 1.16.0+dev-360) via the helm chart.

Ref: 1.16.0+dev-360

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xc1c425]

goroutine 1 [running]:
code.gitea.io/gitea/models/db.GetEngine({0x0, 0x0})
	/go/src/code.gitea.io/gitea/models/db/context.go:75 +0x45
code.gitea.io/gitea/models.GetAllUsers()
	/go/src/code.gitea.io/gitea/models/user.go:242 +0x6b
code.gitea.io/gitea/cmd.runListUsers(0xc000172c60)
	/go/src/code.gitea.io/gitea/cmd/admin.go:463 +0x45
github.com/urfave/cli.HandleAction({0x226f360, 0x34e33f8}, 0x4)
	/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0x266d9c9, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x26de95d, 0xa}, {0x0, ...}, ...}, ...)
	/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:173 +0x652
github.com/urfave/cli.(*App).RunAsSubcommand(0xc00246e380, 0xc000172dc0)
	/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:405 +0x9ec
github.com/urfave/cli.Command.startApp({{0x266f8fd, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x27168de, 0xc}, {0x0, ...}, ...}, ...)
	/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:372 +0x6e9
github.com/urfave/cli.Command.Run({{0x266f8fd, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x27168de, 0xc}, {0x0, ...}, ...}, ...)
	/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:102 +0x808
github.com/urfave/cli.(*App).RunAsSubcommand(0xc00246e1c0, 0xc000172c60)
	/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:405 +0x9ec
github.com/urfave/cli.Command.startApp({{0x2678659, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x28a5eed, 0x42}, {0x0, ...}, ...}, ...)
	/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:372 +0x6e9
github.com/urfave/cli.Command.Run({{0x2678659, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x28a5eed, 0x42}, {0x0, ...}, ...}, ...)
	/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:102 +0x808
github.com/urfave/cli.(*App).Run(0xc00246e000, {0xc000100050, 0x5, 0x5})
	/go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:277 +0x705
main.main()
	/go/src/code.gitea.io/gitea/main.go:115 +0xcf3
No admin user 'gitea_admin' found. Creating now...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xc1c425]
```

### PR DESCRIPTION
**Pull request by lunny**
fix #17532

PS: looks like it's not different from `InitEngineWithMigration` and `InitInstallEngineWithMigration`. I will use only one on another PR.

### CODE REVIEW

File: cmd/cmd.go [hunk 1]
```diff
@@ -65,7 +65,7 @@ func initDBDisableConsole(disableConsole bool) error {
 	setting.InitDBConfig()
 
 	setting.NewXORMLogService(disableConsole)
-	if err := db.InitEngine(); err != nil {
+	if err := db.InitEngine(context.Background()); err != nil {
```
Comment (zeripath) [inline cmd/cmd.go]: Ideally this should use the context that comes from the installSignals function or graceful

File: cmd/doctor.go [hunk 2]
```diff
@@ -96,7 +96,7 @@ func runRecreateTable(ctx *cli.Context) error {
 	setting.Cfg.Section("log").Key("XORM").SetValue(",")
 
 	setting.NewXORMLogService(!ctx.Bool("debug"))
-	if err := db.InitEngine(); err != nil {
+	if err := db.InitEngine(context.Background()); err != nil {
```
Comment (zeripath) [inline cmd/doctor.go]: hmm... need to determine if graceful is started here - if it is this should be graceful.HammerContext() if not we should be installingSignals if possible.

**Comment by lunny** [comment]
@zeripath done.

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]
