### PR TITLE
Link OAuth2 account to 2FA enabled account (fix #1050)

### LINKED ISSUE #1050: OAuth2 linking to existing 2FA enabled account fails
- Gitea version (or commit ref): master
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

Mentioned by @geek1011 at the gitter channel and confirmed by myself on try.gitea.io

If you have setup an existing account with 2FA enabled and want to sign in with Github it fails to link the Github account to the existing account.

Steps to reproduce:
- Setup an local account and enable 2FA
- Logout the account and sign in with Github 
- On the sign-in-or-create-account page login with the existing local account with 2FA
- Login with the 2FA code
- Your Settings - External Accounts -> here should a Github entry be mentioned but isn't 
- Logout and try to login with Github again 
- The sign-in-or-create-account page is shown again instead of the user being logged in

### PR DESCRIPTION
**Pull request by willemvd**
fixes #1050 where linking an account to a 2fa enabled account failed because we forgot to really link the account when 2fa is completed

### CODE REVIEW

**Comment by strk** [comment]
LGTM

File: routers/user/auth.go [hunk 1]
```diff
@@ -219,6 +219,16 @@ func TwoFactorPost(ctx *context.Context, form auth.TwoFactorAuthForm) {
...
 		}
 
+		if ctx.Session.Get("linkAccount") != nil {
+			gothUser := ctx.Session.Get("linkAccountGothUser")
+			if gothUser == nil {
+				ctx.Handle(500, "UserSignIn", errors.New("not in LinkAccount session"))
+				return
+			}
+
+			models.LinkAccountToUser(u, gothUser.(goth.User))
```
Comment (lunny) [inline routers/user/auth.go]: handle the error?

**Review by lunny — CHANGES_REQUESTED** [review]

**Comment by geek1011** [comment]
This works for me.

**Comment by pgaskin** [comment]
This works for me. Thanks.

**Comment by bkcsoft** [comment]
Other than lunnys note, LGTM

**Comment by willemvd** [comment]
@lunny updated so errors are handled

**Review by lunny — APPROVED** [review]
