### PR TITLE
Fix checkbox bug on private/archive filter

### LINKED ISSUE #32235: Input bug on repository archive/private filter checkbox
### Description

Continuous click on checkbox makes invalid unchecked status.

## How to Reproduce 
Screenshot 2024-10-11 at 1 21 36 AM

## Valid Unchecked Status
Screenshot 2024-10-11 at 12 53 43 AM

## Invalid Unchecked Status
Screenshot 2024-10-11 at 12 54 17 AM

### Gitea Version

1.23.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

MacOSX

### Browser Version

Google Chrome 129.0.6668.100

### PR DESCRIPTION
**Pull request by cloudchamb3r**
fix #32235

### CODE REVIEW

File: web_src/js/components/DashboardRepoList.vue [hunk 1]
```diff
@@ -373,7 +373,7 @@ export default sfc; // activate the IDE's Vue plugin
               </a>
               <a class="item" @click="togglePrivateFilter()">
                 <div class="ui checkbox" ref="checkboxPrivateFilter" :title="checkboxPrivateFilterTitle">
-                  <input type="checkbox" class="hidden" v-bind.prop="checkboxPrivateFilterProps">
+                  <input type="checkbox" class="no-select hidden" v-bind.prop="checkboxPrivateFilterProps">
```
Comment (delvh) [inline web_src/js/components/DashboardRepoList.vue]:
```suggestion
                  <input type="checkbox" class="tw-pointer-events-none hidden" v-bind.prop="checkboxPrivateFilterProps">
```

File: web_src/js/components/DashboardRepoList.vue [hunk 2]
```diff
@@ -364,7 +364,7 @@ export default sfc; // activate the IDE's Vue plugin
                 <div class="ui checkbox" ref="checkboxArchivedFilter" :title="checkboxArchivedFilterTitle">
                   <!--the "hidden" is necessary to make the checkbox work without Fomantic UI js,
                       otherwise if the "input" handles click event for intermediate status, it breaks the internal state-->
-                  <input type="checkbox" class="hidden" v-bind.prop="checkboxArchivedFilterProps">
+                  <input type="checkbox" class="no-select hidden" v-bind.prop="checkboxArchivedFilterProps">
```
Comment (delvh) [inline web_src/js/components/DashboardRepoList.vue]:
```suggestion
                  <input type="checkbox" class="tw-pointer-events-none hidden" v-bind.prop="checkboxArchivedFilterProps">
```

File: web_src/js/components/DashboardRepoList.vue [hunk 3]
```diff
@@ -545,4 +545,8 @@ ul li:not(:last-child) {
 .repo-owner-name-list li.active {
   background: var(--color-hover);
 }
+
+.no-select {
+  pointer-events: none;
+}
```
Comment (delvh) [inline web_src/js/components/DashboardRepoList.vue]:
```suggestion
```

File: web_src/js/components/DashboardRepoList.vue (hunk 2 above)
Comment (wxiaoguang) [reply web_src/js/components/DashboardRepoList.vue]: No "hidden" anymore.

File: web_src/js/components/DashboardRepoList.vue [hunk 4]
```diff
@@ -362,9 +362,9 @@ export default sfc; // activate the IDE's Vue plugin
             <div class="menu">
               <a class="item" @click="toggleArchivedFilter()">
                 <div class="ui checkbox" ref="checkboxArchivedFilter" :title="checkboxArchivedFilterTitle">
-                  <!--the "hidden" is necessary to make the checkbox work without Fomantic UI js,
+                  <!--the "tw-pointer-events-none" is necessary to make the checkbox work without Fomantic UI js,
                       otherwise if the "input" handles click event for intermediate status, it breaks the internal state-->
```
Comment (wxiaoguang) [inline web_src/js/components/DashboardRepoList.vue]:
```suggestion
                  <!--the "tw-pointer-events-none" is necessary to prevent the checkbox from handling user's input,
                      otherwise if the "input" handles click event for intermediate status, it breaks the internal state-->
```

(there is no Fomantic UI for checkbox now)

**Review by wxiaoguang — APPROVED** [review]

**Review by delvh — APPROVED** [review]
