### PR TITLE
Fix branch protection priority

### LINKED ISSUE #24044: Specific branch protection doesn't (always) override wildcard protection
### Description

We have configured branch protections for lots of branches (think: all release branches).
Usually pushing on these branches should be forbidden, but during the release cycle the new release should be open to backport fixes and stuff.
So we create a wildcard protection "release/**" that denies all pushes and a specific protection "release/v1.0.0" that allows pushes from specific users.
The resulting behaviour is not always the same.

Sometimes it looks like this:
grafik
In this case, the global protection is always in place and no pushing is possible on any branch.

Sometimes the two rows of glob and specific are switched (specific first, glob second).
Then the specific protection works and the allowed user can push that branch.

To me it looks like some kind of issue with ordering the protections. But I didn't find a way to "force" some ordering by e. g. creating the protections in a specific order or by a naming scheme.

**Test Repo at try.gitea.io:** https://try.gitea.io/eNBeWe/TestFooBar

### Gitea Version

1.19.0+28-g81a995cd8

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.25.1

### Operating System

Ubuntu Linux 20.04.6

### How are you running Gitea?

Binary installation according to docs, using systemd.

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by lunny**
Fix #24044

### CODE REVIEW

File: models/git/protected_branch_list.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ func (rules ProtectedBranchRules) sort() {
 				return true
 			}
 		} else if rules[j].isPlainName {
-			return true
+			return false
```
Comment (wxiaoguang) [inline models/git/protected_branch_list.go]:
```go
	sort.Slice(rules, func(i, j int) bool {
		rules[i].loadGlob()
		rules[j].loadGlob()
		if rules[i].isPlainName != rules[j].isPlainName {
			return rules[i].isPlainName // plain name comes first, so plan name means "less"
		}
		return rules[i].CreatedUnix < rules[j].CreatedUnix
	})
```

File: models/git/protected_branch_list.go [hunk 2]
```diff
@@ -33,7 +33,7 @@ func (rules ProtectedBranchRules) sort() {
...
 		}
```
Comment (wolfogre) [inline models/git/protected_branch_list.go:33]: It could be clearer by:
```diff
-		if rules[i].isPlainName {
-			if !rules[j].isPlainName {
-				return true
-			}
-		} else if rules[j].isPlainName {
-			return false
-		}
+		if rules[i].isPlainName != rules[j].isPlainName {
+			return rules[i].isPlainName
+		}

```

**Review by wolfogre — APPROVED** [review]

File: models/git/protected_branch_list.go [hunk 3]
```diff
@@ -28,12 +28,8 @@ func (rules ProtectedBranchRules) sort() {
...
 		rules[i].loadGlob()
 		rules[j].loadGlob()
-		if rules[i].isPlainName {
-			if !rules[j].isPlainName {
-				return true
-			}
-		} else if rules[j].isPlainName {
-			return true
+		if rules[i].isPlainName != rules[j].isPlainName {
+			return rules[i].isPlainName // plain name comes first, so plan name means "less"
```
Comment (yardenshoham) [inline models/git/protected_branch_list.go]:
```suggestion
			return rules[i].isPlainName // plain name comes first, so plain name means "less"
```

**Review by silverwind — APPROVED** [review]

**Review by delvh — APPROVED** [review]
How can it both be `skip-changelog` and `backport`?
That's a paradoxon.
I think this PR shouldn't be `skip-changelog`.
