### PR TITLE
Rewrite the DiffFileTreeItem and fix misalignment

### LINKED ISSUE #25650: File tree wrong icon offset
### Description

The icon offset is different for files in dirs.

grafik

It only occurs when zooming in, 110% in my tests.
[Example](https://gitea.com/xorm/xorm/pulls/2275/files)

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix some layout / user-interaction problems and close #25650 , the code has been simplified (+46 −108)

<details>

image

</details>

### CODE REVIEW

File: web_src/js/components/DiffFileTreeItem.vue [hunk 1]
```diff
@@ -49,30 +33,19 @@ export default {
...
-        1: 'octicon-diff-added',
-        2: 'octicon-diff-modified',
-        3: 'octicon-diff-removed',
-        4: 'octicon-diff-renamed',
-        5: 'octicon-diff-modified', // there is no octicon for copied, so modified should be ok
+        1: {name: 'octicon-diff-added', classes: ['text', 'green']},
+        2: {name: 'octicon-diff-modified', classes: ['text', 'yellow']},
+        3: {name: 'octicon-diff-removed', classes: ['text', 'red']},
+        4: {name: 'octicon-diff-renamed', classes: ['text', 'teal']},
+        5: {name: 'octicon-diff-modified', classes: ['text', 'green']}, // there is no octicon for copied, so modified should be ok
```
Comment (delvh) [inline web_src/js/components/DiffFileTreeItem.vue]: I think that is semantically more a `rename` than a `modified`.
```suggestion
        5: {name: 'octicon-diff-renamed', classes: ['text', 'green']}, // there is no octicon for copied, so renamed should be ok
```

File: web_src/js/components/DiffFileTreeItem.vue [hunk 2]
```diff
@@ -1,40 +1,24 @@
...
-      >{{ item.name }}</a>
-      <SvgIcon
-        v-if="item.isFile"
-        :name="getIconForDiffType(item.file.Type)"
-        :class="['svg-icon', getIconForDiffType(item.file.Type), 'status']"
-      />
+  <!--title instead of tooltip above as the tooltip needs too much work with the current methods, i.e. not being loaded or staying open for "too long"-->
+  <a
+    v-if="item.isFile" class="item-file"
+    :class="{'selected': store.selectedItem === '#diff-' + item.file.NameHash, 'viewed': item.file.IsViewed}"
```
Comment (delvh) [inline web_src/js/components/DiffFileTreeItem.vue:5]: By the way, I'd like to introduce a small vertical padding here, i.e. `gt-py-1` or `gt-py-2`.
The main problem of that tree at the moment is that it is too cramped.

File: web_src/js/components/DiffFileTreeItem.vue [hunk 3]
```diff
@@ -1,40 +1,24 @@
...
+    :title="item.name" :href="'#diff-' + item.file.NameHash"
+  >
+    <!-- file -->
+    <SvgIcon name="octicon-file"/>
+    <span class="gt-ellipsis gt-f1">{{ item.name }}</span>
+    <SvgIcon :name="getIconForDiffType(item.file.Type).name" :class="getIconForDiffType(item.file.Type).classes"/>
+  </a>
+  <div v-else class="item-directory" :title="item.name" @click.stop="collapsed = !collapsed">
```
Comment (delvh) [inline web_src/js/components/DiffFileTreeItem.vue:13]: Same here.

Comment (delvh) [reply web_src/js/components/DiffFileTreeItem.vue:13]: Additionally, GitHub uses a `button` here which makes sense from an a11y perspective.
Perhaps we should do that too.
But let's leave that for another PR.

File: web_src/js/components/DiffFileTreeItem.vue (hunk 2 above)
Comment (wxiaoguang) [reply web_src/js/components/DiffFileTreeItem.vue:5]: There is. Feel free to fine tune the "padding"


image

File: web_src/js/components/DiffFileTreeItem.vue (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/components/DiffFileTreeItem.vue]: I do not think "renamed" is a proper icon for "copied"

Comment (delvh) [reply web_src/js/components/DiffFileTreeItem.vue]: From a semantic viewpoint, I'd argue that a `copy` action is the same as `renaming` the existing file while keeping the original file.
This can also be seen in the icon: The icon is a circled `→` for `rename`, while it is a non-descriptive circled `·` for `modified`.
I still think that rename is more fitting in this case.

**Review by delvh — APPROVED** [review]

File: web_src/js/components/DiffFileTreeItem.vue (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/components/DiffFileTreeItem.vue]: There is a "copy" svg if you like: ./public/assets/img/svg/octicon-copy.svg

Comment (delvh) [reply web_src/js/components/DiffFileTreeItem.vue]: Yes, but we can't really use it here:
Whenever we use it, users expect to copy whatever precedes it by clicking on it.
That is not the case here.

**Review by silverwind — APPROVED** [review]
