### PR TITLE
Fix various problems

### LINKED ISSUE #34707: Saving label in org settings - json returned
### Description

Image

### Gitea Version

1.25.0+dev-136-g65986f423f

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

Image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
* Fix #34707
* Fix dropdown filter handling
* Fix #27014

### CODE REVIEW

**Review by hiifong — APPROVED** [review]

**Review by lunny — APPROVED** [review]

File: cmd/serv.go [hunk 1]
```diff
@@ -212,7 +212,7 @@ func runServ(ctx context.Context, c *cli.Command) error {
 		if git.DefaultFeatures().SupportProcReceive {
 			// for AGit Flow
 			if cmd == "ssh_info" {
-				fmt.Print(`{"type":"gitea","version":1}`)
```
Comment (a1012112796) [inline cmd/serv.go:215]: a little wonder about whether this change is right. Because we hasn't full support agit protocol format. some RefPatterns are different. ref: https://github.com/alibaba/git-repo-go/blob/master/helper/proto-agit.go

Comment (hiifong) [reply cmd/serv.go:215]: Given that git-repo officially archives the repository, I would suggest that gitea officially fork it and adapt to gitea.

Comment (wxiaoguang) [reply cmd/serv.go:215]: > a little wonder about whether this change is right.

Users say it's right and it "just works"



> Because we hasn't full support agit protocol format. some RefPatterns are different. ref: https://github.com/alibaba/git-repo-go/blob/master/helper/proto-agit.go

It does't support "type: gitea" either.

----

And maybe you could also continue improving these stale "agit" PRs on Gitea side (none of my reviews is addressed)

* #31245
* #33179

Comment (hiifong) [reply cmd/serv.go:215]: ref：https://git-repo.info/en/docs/multi-repos/overview/

I'd like gitea to support the way `git repo` works, and I think a slight modification of `git-repo-go` to adapt to gitea should support it.

Comment (a1012112796) [reply cmd/serv.go:215]: > It does't support "type: gitea" either.

No, it can be support by a extern plugin name as `git-repo-helper-proto-gitea`, ref: https://github.com/alibaba/git-repo-go/blob/086849ef80643f2cf8fc109f8328990a66aa5486/helper/proto-external.go#L54

example: https://github.com/go-gitea/gitea/pull/27014#issuecomment-1719020360

Comment (wxiaoguang) [reply cmd/serv.go:215]: Feel free to propose improvements.

And since `git-repo-go` is archived and seems a dead project, it's really questionable whether we should spend more time on it.

And it's surprising that my reviews didn't get responses but this change attracts more attentions.

Comment (hiifong) [reply cmd/serv.go:215]: OK, I'll spend some time this weekend improving the code

**Comment by hiifong** [comment]
ref https://github.com/alibaba/git-repo-go/blob/086849ef80643f2cf8fc109f8328990a66aa5486/helper/proto-agit.go#L57. It seems that the latest version of the agit protocol is v3, and unfortunately there doesn't seem to be any official documentation on it.
