### PR TITLE
Fix the show/hide methods for string selector

### LINKED ISSUE #23040: Add SSH key not working
### Description

* Go to user/settings/keys
* Click Add Key

```
JavaScript error: TypeError: e.classList is undefined (http://localhost:3000/assets/js/index.js?v=1.19.0~dev-545-g7f790c7 @ 36:60982). Open browser console to see more details.
```

Caused by #22950

### Gitea Version

main (7f790c7)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Both own build and try.gitea.io

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
At that moment I made a mistake (failed to detect a JS variable type correctly)

Close #23040

Screenshot for the fix:

<details>

image

</details>

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by wolfogre — APPROVED** [review]

File: web_src/js/utils/dom.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ function assertShown(el, expectShown) {
 }
 
 function elementsCall(el, func, ...args) {
-  if (el instanceof String) {
+  if (typeof el === 'string' || el instanceof String) {
```
Comment (delvh) [inline web_src/js/utils/dom.js:22]: Okay, I have no idea why this makes a difference…
I thought that these two calls are equivalent.
The fact that they apparently aren't is disturbing and once again proves why I hate the way JS is designed.

**Review by delvh — APPROVED** [review]

File: web_src/js/utils/dom.js (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/utils/dom.js:22]: That's the dark side of JS 😭

**Comment by jolheiser** [comment]
🎺 🤖
