### PR TITLE
Don't force a password change for the admin user when creating an account via cli

### LINKED ISSUE #5376: Can not create first user (admin) with API
- Gitea version (or commit ref):  3973572 
- Git version: 2.17
- Operating system: debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

I'm working in a automated  gitea provisioning script , and the admin user and password is provided as parameter to this script. 

I've tested with as auth token the security.SECRET_KEY and security.INTERNAL_TOKEN configured in my app.ini but It doesn't work. ( as you can see below)

Which token should I use to create the first gitea user (the admin user) ?

````bash
ipasdev@ipasdev01:~/ipas-docker/gitea/gitea$ curl -i -X POST "http://git.mydomain2.org/api/v1/admin/users?access_token=P9R8gvGsZRKw4GjFQjnyUFmY00WJQA3bxzLf1BJg6hvEuzbQwc2aACBB4qwiWVS5" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"email\": \"user@example.com\", \"full_name\": \"string\", \"login_name\": \"string\", \"password\": \"string\", \"send_notify\": true, \"source_id\": 0, \"username\": \"string\"}"
HTTP/1.1 403 Forbidden
Server: nginx/1.13.12
Date: Wed, 21 Nov 2018 22:55:45 GMT
Content-Length: 0
Connection: keep-alive
Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
Set-Cookie: i_like_gitea=7050120b02bef2a4; Path=/; HttpOnly
Set-Cookie: _csrf=JgjWWByY6Bsw9w_QXcom3JhsRNQ6MTU0Mjg0MDk0NTg1MjI0MTE5MA%3D%3D; Path=/; Expires=Thu, 22 Nov 2018 22:55:45 GMT; HttpOnly
X-Frame-Options: SAMEORIGIN
````

### PR DESCRIPTION
**Pull request by adelowo**
This resolves https://github.com/go-gitea/gitea/issues/5376#issuecomment-441135845 .

If the account being created is the initial admin account, skip requesting a password change.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Review by lunny — APPROVED** [review]

File: cmd/admin.go [hunk 1]
```diff
@@ -326,6 +326,12 @@ func runCreateUser(c *cli.Context) error {
 		changePassword = c.Bool("must-change-password")
 	}
 
+	// If this is the first user being created.
+	// Take it as the admin and don't force a password update.
+	if n := models.CountUsers(); n == 0 {
+		changePassword = false
```
Comment (lafriks) [inline cmd/admin.go:328]: May be it would be better to move it up and set this as default only so that `must-change-password` would still be used if specified

**Review by lafriks — APPROVED** [review]
