### PR TITLE
Fix diffpatch API endpoint

### LINKED ISSUE #35602: diffpatch api doesn't accept patch for multiple files
### Description

The web UI which internally calls `_diffpatch` API works as expected and can take multiple file patches at once but the exposed API requires SHA, when we normally talk abou the patch, it is not necessary to only update one file at a time, we can do multiple as we can do in the web API.

### Gitea Version

1.24.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

M4 Pro

### How are you running Gitea?

I'm using the docker image

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by surya-purohit**
Updates the swagger documentation for the `diffpatch` API endpoint.

The request body is corrected from the outdated `UpdateFileOptions` to the current `ApplyDiffPatchOptions` to match the code implementation.

Closes [issue#35602](https://github.com/go-gitea/gitea/issues/35602)

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Thank you very much!

I think I made a mistake in "Refactor "change file" API (#34855)", the "diffpatch" shouldn't be in "/contents". Will make some new changes.

**Comment by wxiaoguang** [comment]
It should be right now: https://github.com/go-gitea/gitea/pull/35610/commits/fbbb1baf50a7ee7b483d98ba5d5ffa980b454c03

**Comment by surya-purohit** [comment]
> It should be right now: [fbbb1ba](https://github.com/go-gitea/gitea/commit/fbbb1baf50a7ee7b483d98ba5d5ffa980b454c03)

Thanks for the quick reply! Glad to see this is fixed.
This change will be very helpful for us once released, as we need to apply patches to multiple files 🙂.

**Review by wxiaoguang — APPROVED** [review]

File: routers/api/v1/api.go [hunk 1]
```diff
@@ -1423,6 +1423,7 @@ func Routes() *web.Router {
 					m.Get("/tags/{sha}", repo.GetAnnotatedTag)
 					m.Get("/notes/{sha}", repo.GetNote)
 				}, context.ReferencesGitRepo(true), reqRepoReader(unit.TypeCode))
+				m.Post("/diffpatch", mustEnableEditor, reqToken(), bind(api.ApplyDiffPatchFileOptions{}), repo.ReqChangeRepoFileOptionsAndCheck, repo.ApplyDiffPatch)
```
Comment (lunny) [inline routers/api/v1/api.go:1426]: So that this is a break change because the endpoint have been changed? Why should we change the endpoint?

Comment (wxiaoguang) [reply routers/api/v1/api.go:1426]: I HAVE EXPLAINED


image


image

**Review by lunny — APPROVED** [review]

**Comment by surya-purohit** [comment]
@wxiaoguang Are we gonna do a rc release, so that the `diffpatch` API can be used? Or it'll become a breaking change. Currently we use `1.25.0-rc0` which has `contents/diffpatch`

**Comment by wxiaoguang** [comment]
> @wxiaoguang Are we gonna do a rc release, so that the `diffpatch` API can be used? Or it'll become a breaking change. Currently we use `1.25.0-rc0` which has `contents/diffpatch`

It has been backported to 1.25 by " Fix diffpatch API endpoint #35613 ", but I think it isn't in the RC.

You can use 1.25-nightly (newer than RC, should be stable enough, and will be 1.25.0 soon)

* https://dl.gitea.com/gitea/1.25-nightly/
* https://hub.docker.com/r/gitea/gitea/tags?name=1.25-nightly

**Comment by surya-purohit** [comment]
> > @wxiaoguang Are we gonna do a rc release, so that the `diffpatch` API can be used? Or it'll become a breaking change. Currently we use `1.25.0-rc0` which has `contents/diffpatch`
> 
> It has been backported to 1.25 by " Fix diffpatch API endpoint #35613 ", but I think it isn't in the RC.
> 
> You can use 1.25-nightly (newer than RC, should be stable enough, and will be 1.25.0 soon)
> 
> * https://dl.gitea.com/gitea/1.25-nightly/
> * https://hub.docker.com/r/gitea/gitea/tags?name=1.25-nightly

Thanks, that worked for now 👍
