### PR TITLE
Correctly set the organization num repos

### LINKED ISSUE #11194: Wrong repository count under dashboard organizations
- Gitea version (or commit ref): 1.11.4
- Git version: doesnt matter
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

User sees all public and private repository count in Dashboard (under organizations tab), even if private repos are outside of team and user has no rights. When opening company profile then repositories that are shown are correct. User should see only public and team repositories count and not private ones that he has no access to it.

## Screenshots

image

### LINKED ISSUE #11331: [Bug] [Api] /orgs/{:orgname}/repos POST endpoint is broken
- Gitea version (or commit ref): 1.12.0+dev-87-g665d7e91a
- Git version:
- Operating system: Ubuntu 18.04.3 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/api/v1/orgs/test_org_3333/repos)
  - [ ] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/iondune/57330f7f5eb4f62b55992aab9b404d2b

## Description

I am having trouble using the POST `/orgs/<org_name>/repos` api endpoint. This is the response I'm getting (with http status 422):

```json
{"message":"org does not exist [id: 0, name: ]","url":"https://try.gitea.io/api/swagger"}
```

But if I switch to the deprecated `/org/<org_name>/repos` endpoint, it works just fine. It looks to me like the issue is that `CreateOrgRepo` is looking for the `:org` parameter [here](https://github.com/go-gitea/gitea/blob/master/routers/api/v1/repo/repo.go#L334) while the parameter in the route is named `:orgname` [here](https://github.com/go-gitea/gitea/blob/master/routers/api/v1/api.go#L861). The deprecated route is working because it uses `:org`.

### PR DESCRIPTION
**Pull request by zeripath**
Correctly set the organization num repos to the number of
accessible repos for the user

- In writing the test for this I have noticed that the API for create Org is broken in several places due to the incorrect use of :orgname when it should be :org. This PR therefore contains fixes for these.

Fix #11194
Fix #11331

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: models/user.go [hunk 1]
```diff
@@ -712,19 +712,42 @@ func (u *User) GetOwnedOrganizations() (err error) {
 
 // GetOrganizations returns paginated organizations that user belongs to.
 func (u *User) GetOrganizations(opts *SearchOrganizationsOptions) error {
-	ous, err := GetOrgUsersByUserID(u.ID, opts)
-	if err != nil {
+	sess := x.NewSession()
```
Comment (lunny) [inline models/user.go:715]: Since there is no insert/update/delete operations here, a transation is unnecessary. If you still want that, you should add `defer sess.Close()`.

Comment (zeripath) [reply models/user.go:715]:
```suggestion
	sess := x.NewSession()
	defer sess.Close()
```

File: models/user.go [hunk 2]
```diff
@@ -712,18 +712,50 @@ func (u *User) GetOwnedOrganizations() (err error) {
...
+	defer sess.Close()
+
+	schema, err := x.TableInfo(new(User))
 	if err != nil {
 		return err
 	}
+	groupByCols := &strings.Builder{}
+	for _, col := range schema.Columns() {
+		fmt.Fprintf(groupByCols, "`%s`.%s,", schema.Name, col.Name)
```
Comment (6543) [inline models/user.go:724]: do you forgot to remove debugging code?

Comment (lafriks) [reply models/user.go:724]: This generates group by string

Comment (6543) [reply models/user.go:724]: ah I got it, this way you can avoid the x.IN(select ID by ... query).Get/Del construct ...

**Comment by 6543** [comment]
@zeripath can we add a test for OrgRepoNum somewhere?

**Comment by zeripath** [comment]
Presumably there is something in `models/org_test.go` but the tests are totally opaque. There's not really anything appropriate in `integrations` - we'd literally have to create a declarative test format that would create organizations, teams, repositories, set members etc.

**Comment by 6543** [comment]
Organisations disapiear on "My Organizations" if they have no repo
Bildschirmfoto zu 2020-05-11 03-20-43

**Comment by zeripath** [comment]
@6543 presumably this is going to need a `LEFT` when joining the repostiory table.

File: models/user.go [hunk 3]
```diff
@@ -712,18 +712,50 @@ func (u *User) GetOwnedOrganizations() (err error) {
...
-	u.Orgs = make([]*User, len(ous))
-	for i, ou := range ous {
-		u.Orgs[i], err = GetUserByID(ou.OrgID)
-		if err != nil {
-			return err
-		}
+	sess.Select("`user`.*, count(`repository`.id) as org_count").
+		Table("user").
+		Join("INNER", "org_user", "`org_user`.org_id=`user`.id").
+		Join("INNER", "repository", "`repository`.owner_id = `org_user`.org_id").
```
Comment (zeripath) [inline models/user.go]:
```suggestion
		Join("LEFT", "repository", "`repository`.owner_id = `org_user`.org_id").
```

**Review by 6543 — APPROVED** [review]
🎉

**Review by 6543 — CHANGES_REQUESTED** [review]
have to look to all functions

**Review by 6543 — APPROVED** [review]

**Review by lafriks — APPROVED** [review]
