### PR TITLE
Use default values when provided values are empty

### LINKED ISSUE #20316: [BUG] index out of range [0] with length 0 at modules/setting
### Description

The function `getPostgreSQLConnectionString` in modules/setting/database.go parse the dbhost, and it works like:
```
host, port := parsePostgreSQLHostPort(dbHost)
if host[0] == '/' { // looks like a unix socket
...
```
but it just split host-string with `:`. If the provided host-string starts with `:`, the host will be "", and it will trigger an error like `index out of range [0] with length 0` 

The poc is here:
```go
package main

import "code.gitea.io/gitea/modules/setting"

func main() {
	setting.Database.Type = "postgres"
	setting.Database.Host = ":00000"
	_, _ = setting.DBConnStr()
}

```

And it crashed as :
```go
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
code.gitea.io/gitea/modules/setting.getPostgreSQLConnectionString({0x744b0d, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x743130, 0x1}, ...)
        /home/zjx/workspace/gowork/src/go-fdg-exmaples/gitea/modules/setting/database.go:158 +0x410
code.gitea.io/gitea/modules/setting.DBConnStr()
        /home/zjx/workspace/gowork/src/go-fdg-exmaples/gitea/modules/setting/database.go:122 +0x5e9
main.main()
        /home/zjx/workspace/gowork/src/go-fdg-exmaples/gitea/modules/setting/pocTest_getPostgreSQL/main.go:8 +0x8a
exit status 2
```

### Gitea Version

with git commit as ee769f7459ffba310563cd735f503d3d7576da60

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

I test the API in Gitea through go-fuzz

### Database

_No response_

### PR DESCRIPTION
**Pull request by Gusted**
- When provided values are empty like `:3000` would imply that host is empty, use the default value.
- Resolves #20316

### CODE REVIEW

**Review by KN4CK3R — APPROVED** [review]

**Review by lunny — APPROVED** [review]

File: modules/setting/database.go [hunk 1]
```diff
@@ -183,5 +189,11 @@ func ParseMSSQLHostPort(info string) (string, string) {
 	} else if len(info) > 0 {
 		host = info
 	}
+	if host == "" {
+		host = "127.0.0.1"
+	}
+	if port == "" {
+		port = "0"
```
Comment (lunny) [inline modules/setting/database.go:197]: 1433?

**Comment by lunny** [comment]
Why it's enhancement but not bug? @Gusted

File: modules/setting/database.go (hunk 1 above)
Comment (wxiaoguang) [reply modules/setting/database.go:197]: There is another  `host, port := "127.0.0.1", "0"` above.

Either both change "0" to "1433", or both keep "0".

(personally I prefer to change both "0" to "1433", while keeping use "0" is also fine).

Comment (KN4CK3R) [reply modules/setting/database.go:197]: "0" has a special meaning in this case.

Comment (wxiaoguang) [reply modules/setting/database.go:197]: MSSQL's dynamic port?

Comment (KN4CK3R) [reply modules/setting/database.go:197]: yes

**Comment by Gusted** [comment]
> Why it's enhancement but not bug? @Gusted

We're now inserting the default values when not provided, Gitea never claimed to do this and is IMO user fault for not providing all information.

File: modules/setting/database.go (hunk 1 above)
Comment (lunny) [reply modules/setting/database.go:197]: I just know when listening as a tcp server, we can use a port "0" to get a dynamic port. But here we will use as a client. Maybe the mssql driver will resolve that?

Comment (Gusted) [reply modules/setting/database.go:197]: I would like to point out that this is already the default value(see few lines up), so it should work accordingly otherwise we likely already should have received bug reports about it.

Comment (wxiaoguang) [reply modules/setting/database.go:197]: Let's add a comment here to move on.

**Review by wxiaoguang — APPROVED** [review]
