### PR TITLE
Fix for Maven Package Naming Convention Handling

### LINKED ISSUE #33672: GET Request for Maven Package maven-metadata.xml Returns 'Package Does Not Exist' after update to 1.23
## Description

After updating Gitea from version 1.22 to 1.23, we encountered an issue where newly rebuilt Maven packages maven-metadata.xml is accessible via GET request, but older packages return a 404 error package does not exist.

## Steps to Reproduce

Upgrade Gitea from version 1.22 to 1.23.

Attempt to fetch an existing Maven package maven-metadata.xml using the API:
 
       curl -X "GET" -H "Authorization: token <token>" -H "Content-Type: application/json"
       http://<gitea-instance>/api/packages/{owner}/maven/com/example/project/maven-metadata.xml

Observe that older packages return a "package does not exist", while data for newly rebuilt packages is accessible (this is one way to solve it, rebuild the older package so then the name will change to the new convention).

## Expected Behavior

Older Maven packages maven-metadata.xml should remain accessible via the API after upgrading Gitea.

## Actual Behavior

Packages stored with the previous naming convention (groupId-artifactId) are no longer accessible. The database now stores package names in the format groupId:artifactId, and queries only resolve to this new format, ignoring existing packages using the old format.

## Database Logs Analysis

Queries are resolving only to the groupId:artifactId format.
Existing packages using the groupId-artifactId format are not matched, leading to 404 errors.

## Environment

    Gitea version: 1.23.3
    Previous version: 1.22.2
    Database: PostgreSQL
    OS: Linux
    Deployment: Docker

## Possible Fix

The source code suggests that older packages should also be resolved, but there seems to be a bug preventing this from happening.

### Gitea Version

1.23.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

We are running Gitea self-hosted on Rancher in a Kubernetes pod with Linux.

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by dianaStr7**
## Description
This pull request addresses the bug reported in [#33672](https://github.com/go-gitea/gitea/issues/33672) related to the handling of Maven packages with older naming conventions. The `getVersionByPackageName` method in the `package_version`  has been updated to throw an exception ErrNotExist when no packages are found. This error already was expected for the call back mechanism for maven packages for legacy name handling.

## Changes Made

Make legacy package names could be listed and add tests

## Related Ticket
- [#33672](https://github.com/go-gitea/gitea/issues/33672)

### CODE REVIEW

File: models/packages/package_version.go [hunk 1]
```diff
@@ -139,6 +139,11 @@ func GetVersionsByPackageName(ctx context.Context, ownerID int64, packageType Ty
 		},
 		IsInternal: optional.Some(false),
 	})
+
+	if len(pvs) == 0 {
+		return nil, util.ErrNotExist
+	}
+
```
Comment (wxiaoguang) [inline models/packages/package_version.go]: Hmm, we shouldn't do that .... and other code doesn't do that either.

When a function returns empty list without error, it already means "empty" (no item exists).


So IMO the fix could be like this:

```go
pvs1, err := packages_model.GetVersionsByPackageName(ctx, ctx.Package.Owner.ID, packages_model.TypeMaven, params.toInternalPackageNameLegacy())
if err != nil {
		apiError(ctx, http.StatusInternalServerError, err)
		return
}
pvs2, err := packages_model.GetVersionsByPackageName(ctx, ctx.Package.Owner.ID, packages_model.TypeMaven, params.toInternalPackageName())
if err != nil {
		apiError(ctx, http.StatusInternalServerError, err)
		return
}
pvs := append(pvs1, pvs2...)
```

Comment (dianaStr7) [reply models/packages/package_version.go]: Got it, thank you! Will refactor then this way 👍

Comment (wxiaoguang) [reply models/packages/package_version.go]: ps: the bug fix should target to the main branch, and then backport to the stable (1.23) branch.

If you don't mind, I could help you to update the PR.

Comment (dianaStr7) [reply models/packages/package_version.go]: That would be great, thank you! Not experienced much, but it comes 😅

Comment (wxiaoguang) [reply models/packages/package_version.go]: Your issue report and code helped a lot, it points to the right direction 👍 actually that "error check" is a mistake made by me ..... I just didn't realize it until you shows the case.

----

(need some tricks to re-target to main branch and fix the bug, will force-push later)

**Comment by wxiaoguang** [comment]
And added some tests in 795b3f551e26c90cc073d81b4a341b530fb12d7f, it should be right now. Without the fix, the tests fail.

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]
