### PR TITLE
Fix upload file type check

### LINKED ISSUE #7882: No way to upload files with "text/plain; charset=utf-8" filetype
- Gitea version (or commit ref): Gitea version 1.9.1 built with GNU Make 4.2.1, go1.12.8 : bindata, sqlite, pam
- Git version: git version 2.22.1
- Operating system: Arch Linux ARM
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
Aug 15 18:40:17 dtluna.net gitea[21743]: 2019/08/15 18:40:17 ...s/repo/attachment.go:58:UploadAttachment() [I] Attachment with type text/plain; charset=utf-8 blocked from upload
```
## Description
I have 
```ini
ALLOWED_TYPES = "application/zip|application/gzip|application/x-gzip|application/x-gtar|application/x-tgz|application/x-compressed-tar|text/plain; charset=utf-8"
```
In my `/etc/gitea/app.ini`, but I still cannot upload [checksums.txt](https://github.com/go-gitea/gitea/files/3506791/checksums.txt) at https://git.dtluna.net/dtluna/fallhack/releases/edit/v1.0.1

...

## Screenshots
upload

### PR DESCRIPTION
**Pull request by lunny**
should fix #7882

### CODE REVIEW

**Review by sapk — APPROVED** [review]
This function would need a test suite and could be improved by simply using return in place of using allowed bool.

```
func VerifyAllowedContentType(buf []byte, allowedTypes []string) error {
	fileType := http.DetectContentType(buf)
	for _, t := range allowedTypes {
		t := strings.Trim(t, " ")

		if t == "*/*" || t == fileType ||
			// allowed text/plain; charset=utf-8
			strings.HasPrefix(fileType, t+";") {
			return nil
		}
	}

	log.Info("Attachment with type %s blocked from upload", fileType)
	return ErrFileTypeForbidden{Type: fileType}
}
```

But all of that is not necessary for the fix. So it allready LGTM in this state.

**Comment by lunny** [comment]
@sapk done.

**Review by sapk — APPROVED** [review]
Perfect. Thanks for the improvement.

**Comment by sapk** [comment]
By curiosity, I watch who wrote thoses lines and it was me during a refactor where I didn't optimize it. :smile:

**Review by zeripath — APPROVED** [review]

File: modules/upload/filetype.go [hunk 1]
```diff
@@ -31,19 +31,16 @@ func (err ErrFileTypeForbidden) Error() string {
...
-			allowed = true
-			break
-		}
-	}
 
-	if !allowed {
-		log.Info("Attachment with type %s blocked from upload", fileType)
-		return ErrFileTypeForbidden{Type: fileType}
+		if t == "*/*" || t == fileType ||
+			// allowed text/plain; charset=utf-8
```
Comment (silverwind) [inline modules/upload/filetype.go]: Maybe change comment to `Allow directives after type, like 'text/plain; charset=utf-8'` to make it clear it's not only for `text/plain`.

Comment (zeripath) [reply modules/upload/filetype.go]: @silverwind I think that's reasonable and I took the liberty to push that change up.

**Review by silverwind — APPROVED** [review]

**Comment by lafriks** [comment]
Please send backport
