### PR TITLE
pull: Fix CODEOWNERS absolute path matching.

### LINKED ISSUE #28107: Codeowners file doesn't support absolute paths
### Description

The codeowners support #10161 introduced in https://github.com/go-gitea/gitea/pull/24910 doesn't seem to support paths starting with `/`:

```
# works
docs/*.\\.md
# doesn't
/docs/*.\\.md
```

This is supported by Githubs syntax: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file

I thought it might be supported by gitea as well because of this example provided in the documentation:

```
!/assets/.*\\.(bin|exe|msi) @user9
```

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Binary started via systemd behind a caddy reverse proxy.

### Database

None

### PR DESCRIPTION
**Pull request by JoeGruffins**
Patterns starting with "/" (e.g. /docs/.*\.md) never matched because git returns relative paths without a leading slash. Strip the leading "/" before compiling the regex since the ^...$ anchoring already provides root-relative semantics.

closes #28107

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Worth flagging (out of scope here): after the fix, `/docs/*` and `docs/*` behave identically in Gitea, but GitHub distinguishes them — `docs/*` matches at any depth. Closing #28107 with this is fine for the narrow bug, but full GitHub parity is a design call (Gitea is regex-based, users rely on real regex features) worth its own issue.

*Comment written by Claude Opus 4.7.*

**Review by lunny — APPROVED** [review]

File: models/issues/pull_test.go [hunk 1]
```diff
@@ -339,8 +351,44 @@ func TestParseCodeOwnersLine(t *testing.T) {
...
+	}
+
+	for _, c := range cases {
+		rules, _ := issues_model.GetCodeOwnersFromContent(t.Context(), c.content)
+		if len(rules) == 0 {
+			if c.expected {
+				t.Errorf("expected rules for content %q but got none", c.content)
+			}
+			continue
+		}
```
Comment (wxiaoguang) [inline models/issues/pull_test.go]: What's the strange logic for?

Comment (bircni) [reply models/issues/pull_test.go]: @JoeGruffins

**Review by wxiaoguang — APPROVED** [review]

**Comment by bircni** [comment]
@silverwind merge?
