### PR TITLE
fix: prevent panic when GitLab release has more links than sources

### LINKED ISSUE #36292: Migrate from Gitlab fails on releases with different number of links and artifacts
### Description

There seems to be an assumption in the code on how releases are structured.
The code at gitlab.go:324 assumes that rel.Assets.Links and rel.Assets.Sources have the same length, but they don't always match in GitLab's API response.
See an example in my public repo here: https://gitlab.com/unboundsoftware/schemas/-/releases
The releases are created by GoReleaser and have 4 sources and 7 links.

### Gitea Version

1.25.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/argoyle/b56eebdad18c3f7d85125a00dd3af947

### Screenshots

_No response_

### Git Version

2.49.1

### Operating System

gitea-rootless Docker image

### How are you running Gitea?

Kubernetes deployment using the gitea-rootless image

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by argoyle**
The code incorrectly assumed rel.Assets.Links and rel.Assets.Sources arrays have equal length. This causes index out of bounds panic when migrating GitLab releases with more links than sources, which is common with GoReleaser-generated releases.

The fix sets ContentType to nil instead of using Sources[k].Format. This is safe because ContentType is not actually used when uploading release assets - the repo_model.Attachment struct has no ContentType field, so the value was being discarded anyway.

Fixes #36292

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: services/migrations/gitlab.go [hunk 1]
```diff
@@ -316,12 +316,12 @@ func (g *GitlabDownloader) convertGitlabRelease(ctx context.Context, rel *gitlab
...
 	httpClient := NewMigrationHTTPClient()
 
-	for k, asset := range rel.Assets.Links {
+	for _, asset := range rel.Assets.Links {
 		assetID := asset.ID // Don't optimize this, for closure we need a local variable
 		r.Assets = append(r.Assets, &base.ReleaseAsset{
 			ID:            int64(asset.ID),
 			Name:          asset.Name,
-			ContentType:   &rel.Assets.Sources[k].Format,
+			ContentType:   nil, // GitLab Links don't provide content type
```
Comment (wxiaoguang) [inline services/migrations/gitlab.go]: GitLab never provides the content type? Or it just sometimes doesn't provide the content type?

Any document?

Comment (argoyle) [reply services/migrations/gitlab.go]: It does for Sources but not for Links. The thing is that the content type is not used at all later in the flow (as far as Claude could find at least) and hence there is no reason for setting it.

Comment (wxiaoguang) [reply services/migrations/gitlab.go]: If it's sure that "content type is not used", is it better to completely remove this field? From the `ReleaseAsset` struct?

Comment (argoyle) [reply services/migrations/gitlab.go]: I can agree on that. Would you like me to do that change in this PR or as a followup PR?

Comment (wxiaoguang) [reply services/migrations/gitlab.go]: I think it's better to take the best approach in one PR as long as we found one.

Comment (argoyle) [reply services/migrations/gitlab.go]: Pushed another commit

Comment (wxiaoguang) [reply services/migrations/gitlab.go]: Since the field has been removed, the test is not needed anymore.

I added some comments for the removal. If we need the content type in the future, the tests should be redesigned.

**Review by wxiaoguang — APPROVED** [review]
