### PR TITLE
fix: add search to reserved usernames

### LINKED ISSUE #9061: usernames can overlap with api actions (eg: search)
- Gitea version (or commit ref): 1.11.0+dev-213-g173da1b5a
- Git version: 2.22.0
- Operating system: linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

Gitea allows you to create a user with the username "search" after creating this user, the user will not be retrievable via the api as the url for this is /api/v1/users/search which overlaps with the search action.

### PR DESCRIPTION
**Pull request by sapk**
Fix #9061

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Review by techknowlogick — APPROVED** [review]

**Review by jolheiser — APPROVED** [review]

**Comment by techknowlogick** [comment]
CI Fail

File: integrations/user_test.go [hunk 1]
```diff
@@ -90,6 +90,7 @@ func TestRenameReservedUsername(t *testing.T) {
 		"repo",
 		"template",
 		"user",
+		"search"
```
Comment (6543) [inline integrations/user_test.go]:
```suggestion
		"search",
```

Comment (sapk) [reply integrations/user_test.go]: Thanks

**Comment by 6543** [comment]
mssql thought it dont has to work ...
`git commit --allow-empty -m 'CI.restart()'` ?

**Comment by sapk** [comment]
@6543 I got the power to restart build directly.
I got the power

**Comment by 6543** [comment]
https://github.com/go-gitea/gitea/pull/9063#issuecomment-555232712

😮
