### PR TITLE
Fix avatar bugs

### LINKED ISSUE #13586: Organizations avatars are identical
- Gitea version (or commit ref): `Gitea version 1.14.0+dev-224-g586bfb9f3 built with GNU Make 4.3, go1.15.5 : bindata, sqlite, sqlite_unlock_notify`
- Git version: `git version 2.29.2.454.gaff20da3a2`
- Operating system: Arch Linux
- Built from:
  - [x] source
- Run with
  - [x] systemd
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  orgs `nuonepls` and `nuonepls2` of this user: https://try.gitea.io/poiuytre

## Description
I am not sure if this is the expected behaviour but the thing is that *some* orgs are displaying the same avatars as other orgs.
My screenshots show this behaviour for orgs by a single user, although on my instance I also have this avatar overlap with orgs of another user as well.

## Screenshots
try.gitea.io - nuonepls{,2} have the same avatar
image

my instance
image
image

### PR DESCRIPTION
**Pull request by lunny**
Fix #13586, #14199, #14176

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

File: models/user_avatar.go [hunk 1]
```diff
@@ -39,10 +39,9 @@ func (u *User) generateRandomAvatar(e Engine) error {
 		return fmt.Errorf("RandomImage: %v", err)
 	}
 
-	if u.Avatar == "" {
-		u.Avatar = HashEmail(u.AvatarEmail)
-	}
+	u.Avatar = HashEmail(seed)
```
Comment (zeripath) [inline models/user_avatar.go:42]: So you definitely intend the avatar always be overwritten if you call `generateRandomAvatar`?

Comment (6543) [reply models/user_avatar.go:42]: isnt this func only exec if no avatar afailable?

so it should be fine ...

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
Backport: #14220
