### PR TITLE
Query the DB for the hash before inserting in to email_hash

### LINKED ISSUE #15451: postgres error:  duplicate key value violates unique constraint "email_hash_pkey"
- Gitea version (or commit ref): v1.13.7 built with GNU Make 4.3, go1.16.3
- Git version: 2.26.3
- Operating system: Raspbian GNU/Linux 10, docker kunde21/gitea-arm v1.13.7-armv7 
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description
I already opened https://github.com/go-gitea/gitea/issues/14725 and also referring to https://github.com/go-gitea/gitea/pull/12577 and https://github.com/go-gitea/gitea/issues/12287
These issues are closed and a fix released, but it still doesn't fix my duplicate key violation errors.

Using gitea 1.13.7 and postgres 13.0 showing the following reoccuring errors:

2021-04-13 10:06:38.184 UTC [32] ERROR:  duplicate key value violates unique constraint "email_hash_pkey"
2021-04-13 10:06:38.184 UTC [32] DETAIL:  Key (hash)=(xxxxxxxxxxxxxxxxxxxx) already exists.
2021-04-13 10:06:38.184 UTC [32] STATEMENT:  INSERT INTO "email_hash" ("hash","email") VALUES ($1,$2)

 Schema | Name |  Type  |
-------------|----------|------------------------------
 public | email_address                    | table    |
 public | email_address_id_seq             | sequence |
 public | email_hash                       | table    |

What somebody from previous tickets told me to do, but won't fix the duplicate key violation:

- gitea doctor recreate-table
- updating sequences (although email_hash has no sequence! so this suggestion makes no sense)

### PR DESCRIPTION
**Pull request by zeripath**
Some postgres users have logging which logs even failed transactions. So
just query the db before trying to insert.

Fix #15451

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: models/avatar.go [hunk 1]
```diff
@@ -96,6 +96,11 @@ func HashedAvatarLink(email string) string {
 			// we don't care about any DB problem just return the lowerEmail
 			return lowerEmail, nil
 		}
+		has, err := sess.Where("email = ? AND sum = ?", emailHash.Email, emailHash.Hash).Get(new(EmailHash))
```
Comment (lunny) [inline models/avatar.go]:
```suggestion
    has, err := sess.Where("email = ? AND hash = ?", emailHash.Email, emailHash.Hash).Get(new(EmailHash))
```

**Review by lunny — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
make lgtm work
