### PR TITLE
Improve code diff highlight, fix incorrect rendered diff result

### LINKED ISSUE #19508: Diff highlighting doesn't always include all changes
### Description

Currently when Gitea is highlighting a diff, it's possible that not all code is correctly "diffed", this means that part of added code isn't included in the `added-code` span, but rather outside of it.

This is caused by broken spans! Gitea is diffing the code after it has been highlighted by chroma. This means we're diffing with HTML code, this causes that certain HTML elements are being split apart from each other, one part could live in the "equal" part and the other part in the "insert" this causes Broken spans, @zeripath has made [a excellent attempt](https://github.com/go-gitea/gitea/pull/14678) at fixing most cases of this broken spans, but there are still cases where this code fails to fix the broken spans:

https://try.gitea.io/Gusted/Test-repo/pulls/3/files

You can clearly see here that the `), xdg'` part also should be included into the `inserted` code part. But because of certain set of conditions we're not fixing all broken spans in this case.

### Gitea Version

https://github.com/go-gitea/gitea/commit/03eba32bd91533f090a82b62bd9cffd9e448aaa7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

N/A

### Screenshots

Actual:
image

Expected:
image

### Git Version

N/A

### Operating System

N/A

### How are you running Gitea?

https://try.gitea.io/Gusted/Test-repo/pulls/3/files

### Database

_No response_

### LINKED ISSUE #20152: Bad diff highlight
### Description

my changes:
```diff
diff --git a/core/deploy_core.sh b/core/deploy_core.sh
index ea37829..cec1cc4 100644
--- a/core/deploy_core.sh
+++ b/core/deploy_core.sh
@@ -57,7 +57,7 @@ echo "Complete. Start deploy process."
 
 PROJECT_DIR=$BASE_PATH"/$PROJECT_DIR_NAME"
 PROJECT_DEPLOY_DIR=$PROJECT_DIR"_deploy"
-FILES_FOR_DEL=("Pipfile" "Pipfile.lock" ".git" ".gitignore" ".gitmodules" "README.md" "config.sample.ini" "runserver.sh" "runserver_pipenv.sh" "supervisord.conf" "supervisord.pipenv.conf" "systemd.sample" "requirements.txt" "deploy.sh")
+FILES_FOR_DEL=(".git" ".gitignore" "README.md" "config.sample.ini" "runserver.sh" "runserver_pipenv.sh" "supervisord.conf" "supervisord.pipenv.conf" "systemd.sample" "requirements.in" "requirements.txt" "deploy.sh")
 SUPERVISORCTL_CMD='supervisorctl -c supervisord.conf '
 
 ################################# DEPLOY SCRIPT ########################################
```
how gitea displays this file:
image

`Pipfile" "Pipfile.lock` part got removed but only `Pipfile"` is red

### Gitea Version

1.17.0+rc1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.36.1

### Operating System

_No response_

### How are you running Gitea?

Locally compiled binary

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by wxiaoguang**
Try to fix: #19508
* #19508

Some tests are removed, because these were only for broken diff results. This new method doesn't generate these broken results.

Edge cases are cleared, and added more related tests.

### Screenshots

Before:

<details>

image

</details>

After:

<details>

image

</details>

### CODE REVIEW

**Comment by silverwind** [comment]
I think we can remove the `<span class="line"><span class="cl">` wrapping of each diff line like I did in https://github.com/go-gitea/gitea/pull/19967 but for regular file view. They seem pointless and less HTML output will always render faster.

**Comment by silverwind** [comment]
Seems fine to me to close the syntax class before the added/removed block, I think this also matches GH rendering.

**Comment by wxiaoguang** [comment]
> I think we can remove the `<span class="line"><span class="cl">` wrapping of each diff line like I did in #19967 but for regular file view. They seem pointless and less HTML output will always render faster.

Yup, I also think removing them is good. Updated (and now the code still support to add them back -- if it's needed)

File: services/gitdiff/gitdiff_test.go [hunk 1]
```diff
@@ -17,93 +16,27 @@ import (
...
 
-	assertEqual(t, "foo <span class=\"removed-code\">bar</span> biz", diffToHTML("", []dmp.Diff{
+	assert.Equal(t, "foo <span class=\"removed-code\">bar</span> biz", diffToHTML(nil, []dmp.Diff{
 		{Type: dmp.DiffEqual, Text: "foo "},
 		{Type: dmp.DiffDelete, Text: "bar"},
 		{Type: dmp.DiffInsert, Text: " baz"},
 		{Type: dmp.DiffEqual, Text: " biz"},
-	}, DiffLineDel).Content)
-
-	assertEqual(t, "<span class=\"k\">if</span> <span class=\"p\">!</span><span class=\"nx\">nohl</span> <span class=\"o\">&amp;&amp;</span> <span class=\"added-code\"><span class=\"p\">(</span></span><span class=\"nx\">lexer</span> <span class=\"o\">!=</span> <span class=\"kc\">nil</span><span class=\"added-code\"> <span class=\"o\">||</span> <span class=\"nx\">r</span><span class=\"p\">.</span><span class=\"nx\">GuessLanguage</span><span class=\"p\">)</span></span> <span class=\"p\">{</span>", diffToHTML("", []dmp.Diff{
```
Comment (lunny) [inline services/gitdiff/gitdiff_test.go:51]: Why deleted this test code

Comment (wxiaoguang) [reply services/gitdiff/gitdiff_test.go:51]: image

**Comment by Fogapod** [comment]
image

I've got weird diff on latest master. Does this PR address it or it's something else? Change was exactly the same for both lines but highlight differs

File: services/gitdiff/gitdiff.go [hunk 2]
```diff
@@ -555,6 +283,180 @@ func DiffInlineWithHighlightCode(fileName, language, code string) DiffInline {
...
+func (hcd *HighlightCodeDiff) collectUsedRunes(code string) {
+	for _, r := range code {
+		if hcd.isInPlaceholderRange(r) {
+			// put the existing rune (used by code) in map, then this rune won't be used a placeholder anymore.
+			hcd.placeholderTagMap[r] = ""
+		}
+	}
+}
+
+func (hcd *HighlightCodeDiff) diffWithHighlight(filename, language, codeA, codeB string) []diffmatchpatch.Diff {
```
Comment (delvh) [inline services/gitdiff/gitdiff.go]: What about calling it `oldCode, newCode` instead?

File: services/gitdiff/gitdiff.go [hunk 3]
```diff
@@ -555,6 +283,180 @@ func DiffInlineWithHighlightCode(fileName, language, code string) DiffInline {
...
+	var tagStack []string
+
+	for _, r := range diff.Text {
+		tag, ok := hcd.placeholderTagMap[r]
+		if !ok || tag == "" {
+			sb.WriteRune(r) // if the run is not a placeholder, write it as it is
+			continue
+		}
+		var tagToRecover string
+		if tag[1] == '/' {
```
Comment (delvh) [inline services/gitdiff/gitdiff.go]:
```suggestion
		if tag[1] == '/' { // Closing tag
```

File: services/gitdiff/gitdiff.go [hunk 4]
```diff
@@ -555,6 +283,180 @@ func DiffInlineWithHighlightCode(fileName, language, code string) DiffInline {
...
+
+	lineWrapperTags []string
+}
+
+func NewHighlightCodeDiff() *HighlightCodeDiff {
+	return &HighlightCodeDiff{
+		placeholderBegin:    rune(0xE000), // Private Use Unicode: U+E000..U+F8FF, BMP(0), 6400
+		placeholderMaxCount: 6400,
+		placeholderTagMap:   map[rune]string{},
+		tagPlaceholderMap:   map[string]rune{},
```
Comment (delvh) [inline services/gitdiff/gitdiff.go]: Perhaps it would be a good idea performance-wise to initialize the map with a capacity of `placeholderMaxCount` entries:
`make(map[rune]string{}, placeholderMaxCount)`
While it will waste memory in most cases, it certainly never needs to be resized (consistently), which will improve performance

**Review by delvh — COMMENTED** [review]
Okay, I think I now got the gist of what you are doing.
I still do not exactly understand why we are highlighting on styled code instead of the other way around (highlighting first and then applying the styling), but at least your approach is understandable given the circumstances.
Also, do I see correctly that diffing will fail the moment you have more than 6400 differences?

File: services/gitdiff/gitdiff.go (hunk 4 above)
Comment (wxiaoguang) [reply services/gitdiff/gitdiff.go]: It would be too large. Usually there would only be a few placeholders.

And for small maps, the pre-allocation seems not improving too much performance, especially compared to other heavy logic, the pre-allocation here seems very trivial. We can benchmark it 😊

Comment (delvh) [reply services/gitdiff/gitdiff.go]: What would you say is a typical count for small, medium, and large files respectively?
A guess is enough.
(Simply so that I can understand how often this limit will be reached)

Comment (wxiaoguang) [reply services/gitdiff/gitdiff.go]: Very small. These tags comes from Chroma's highlight styles.

And the code does diff line by line, every line only have a few styles.

So, no need to worry about the 6400 limit, it won't happen. I just put it there to make the logic complete.

File: services/gitdiff/gitdiff.go (hunk 2 above)
Comment (wxiaoguang) [reply services/gitdiff/gitdiff.go]: Well ... if not too much difference, could they be left there? 😂

You see, the diff/patch command also use a/b side.

**Comment by wxiaoguang** [comment]
> I still do not exactly understand why we are highlighting on styled code instead of the other way around (highlighting first and then applying the styling), but at least your approach is understandable given the circumstances.

Highlighting the code first is much easier than highlight it after the diff at the moment. I haven't found a clear and simple mechanism to do post-diff highlighting for Gitea. 

> Also, do I see correctly that diffing will fail the moment you have more than 6400 differences?

As explained in https://github.com/go-gitea/gitea/pull/19958#discussion_r899948331 ,  it won't happen.
Even if it happens, the diffing won't fail, the tags will be just written there without placeholder converting.
So everything could be fine.

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
Yeah, I was a bit confused about how many placeholders are converted. It sounded like it would be easy to reach the limit, i.e. each diff adds its own placeholder.
But of course, if it's only 10-30, then there is no point in overoptimizing it.

**Comment by wxiaoguang** [comment]
It seems that there is no interest to get it merged and it blocks the 1.17 release, so close it.

Feel free to pick it or propose new PRs.

**Comment by zeripath** [comment]
Sorry I didn't get round to looking at this. I think we should reopen.

**Review by lunny — APPROVED** [review]
Trust LGTM

File: services/gitdiff/gitdiff.go [hunk 5]
```diff
@@ -555,6 +283,182 @@ func DiffInlineWithHighlightCode(fileName, language, code string) DiffInline {
...
+	placeholderTagMap   map[rune]string
+	tagPlaceholderMap   map[string]rune
+
+	lineWrapperTags []string
+}
+
+func NewHighlightCodeDiff() *HighlightCodeDiff {
+	return &HighlightCodeDiff{
+		placeholderBegin:    rune(0xE000), // Private Use Unicode: U+E000..U+F8FF, BMP(0), 6400
+		placeholderMaxCount: 6400,
```
Comment (zeripath) [inline services/gitdiff/gitdiff.go]: Could be reasonable to consider using Plane 15: Supplementary Private Use Area A (U+F0000..U+FFFFD) or Plane 16: Supplementary Private Use Area B (U+100000..U+10FFFD) in addition where there are at least 64,000 points.

File: services/gitdiff/gitdiff.go [hunk 6]
```diff
@@ -555,6 +283,182 @@ func DiffInlineWithHighlightCode(fileName, language, code string) DiffInline {
...
+			if placeholder != 0 {
+				hcd.tagPlaceholderMap[tagInMap] = placeholder
+				hcd.placeholderTagMap[placeholder] = tagInMap
+			}
+		}
+
+		if placeholder != 0 {
+			res.WriteRune(placeholder) // use the placeholder to replace the tag
+		} else {
+			res.WriteString(tag) // unfortunately, all private use runes has been exhausted, no more placeholder could be used, so do not convert the tag
```
Comment (zeripath) [inline services/gitdiff/gitdiff.go]: This could/will cause broken tags and hence could result in XSS. If we can't get a placeholder we should abandon highlighting of the diff

File: services/gitdiff/gitdiff.go (hunk 5 above)
Comment (wxiaoguang) [reply services/gitdiff/gitdiff.go]: No need to use that large.
As https://github.com/go-gitea/gitea/pull/19958#discussion_r899948331

Comment (zeripath) [reply services/gitdiff/gitdiff.go]: I am aware that only the chroma tags are what are being replaced - I'm also aware that we shouldn't be running diff on a line with more than `MAX_GIT_DIFF_LINE_CHARACTERS` (5000 characters).

However, consider:

`a = "`+ a string of 3200 supplementary characters + `"` 

diffed with: 

`b = "" // `+ a string of 3200 different supplementary characters + `"` 

so long as all 6400 of the supplementary characters are included no replacements can be made. The bits before and within the supplementary characters can be tuned to cause HTML breakage. I don't think it would be easy to get arbitrary tag creation but certainly HTML breakage is possible.

Comment (wxiaoguang) [reply services/gitdiff/gitdiff.go]: I do no think the HTML breakage is serious in this case. If it's caused by mismatched tags, these tags will be corrected by browsers in the end by the surrounding `<div>` tags. Chroma only outputs `<span>` tags. Browsers can handle it correctly. If you want to make sure there is no breakage at all, the final HTML can be sanitized for tag-matching again.

And at the moment, the code in `recoverOneDiff` uses a stack to output final tags, all tags should have been paired correctly when outputing, I do not think it would output broken/mismatched HTML tags, so there should be no HTML breakage. The worst case is that the placeholders are exhausted, and the highlight doesn't work well.

Comment (wxiaoguang) [reply services/gitdiff/gitdiff.go:304]: And at the moment, the code in `recoverOneDiff` uses a stack to output final tags, all tags should have been paired correctly when outputing, I do not think it would output broken HTML tags.

File: services/gitdiff/gitdiff.go [hunk 7]
```diff
@@ -555,6 +283,182 @@ func DiffInlineWithHighlightCode(fileName, language, code string) DiffInline {
...
+	res := strings.Builder{}
+
+	firstRunForLineTags := hcd.lineWrapperTags == nil
+
+	// the standard chroma highlight HTML is "<span class="line [hl]"><span class="cl"> ... </span></span>"
+	for {
+		// find the next HTML tag
+		pos1 := strings.IndexByte(htmlCode, '<')
+		pos2 := strings.IndexByte(htmlCode, '>')
+		if pos1 == -1 || pos2 == -1 || pos2 < pos1 {
```
Comment (zeripath) [inline services/gitdiff/gitdiff.go]: We know that `pos2 > pos1` if `pos1 != pos2 != -1` because we're relying on chroma producing valid HTML.

<details><summary>If htmlCode is not valid HTML then all of this code is unsafe and this test is not enough to detect that. </summary>

For example there's nothing to ensure that detected `>` isn't within an attribute e.g.

```
<div class="I am technically invalid >< but actually most HTML parsers would tolerate me">
```

</details>

It might be prudent to add specific comments to these functions explicitly warning that it is assumed that only valid HTML can be passed in and that these sorts of cases are not being looked for.

Comment (wxiaoguang) [reply services/gitdiff/gitdiff.go]: Why should invalid htmlCode be passed into this function? These functions are private functions (lower-cased first letter), only used by internal code. (update: the new commit also makes the struct private, nobody can used it outside)

And they are covered by unit tests, if Chroma changed its behavior and breaks something, this code should also be updated.

I am not sure what comments could be clear for your cases, can you edit on this PR directly?

Comment (zeripath) [reply services/gitdiff/gitdiff.go]: If you don't clearly write what the assumptions are around a piece of code those assumptions will be forgotten and this code will almost certainly be used in an unintended fashion in future. 

One of the problems with adding checks like the referenced check is that sometimes they give the impression that this would be safe for invalid HTML. It would not be safe, as I wrote above, and although we both know this - we may not be the ones reviewing or writing code that uses this in an unsafe manner. 

I'm not saying that this code is incorrect - all I'm saying is add a warning because someone may try to use it in an incorrect way. We should explain why it would be unsafe to use this on generic "html" that was not guaranteed to be valid and why.

File: services/gitdiff/gitdiff.go (hunk 5 above)
Comment (zeripath) [reply services/gitdiff/gitdiff.go]: I've just shown how you can get to 6400 supplementary characters even within our current defaults.

My comment regarding broken tags was before I noted you'd changed lines 414-415 to simply not emit the tag which helps prevent the broken code however, we do need to consider the issue of mismatching...

Consider the above example but one that only covers 6399 supplementary characters, it will not be possible to create a placeholder for the closing tag so its closing tag will not get covered. So we're guaranteed in that case to end up with a mismatched tag.

It would be a simple case to assign the closing placeholder at the same time as the opening placeholder to prevent this.

**Review by zeripath — COMMENTED** [review]
This code doesn't account for html entities.

Chroma runs `html.EscapeString` on the contents of the line which is essentially the replacer:

```go
var htmlEscaper = strings.NewReplacer(
	`&`, "&amp;",
	`'`, "&#39;", // "&#39;" is shorter than "&apos;" and apos was not in HTML until HTML5.
	`<`, "&lt;",
	`>`, "&gt;",
	`"`, "&#34;", // "&#34;" is shorter than "&quot;".
)
```

These also need to be replaced with placeholders.

**Comment by wxiaoguang** [comment]
I can not understand what to do next, please help to design some real test cases, then I can write code to cover them.

Or you can edit on this PR directly for what you want.

File: services/gitdiff/gitdiff.go (hunk 5 above)
Comment (wxiaoguang) [reply services/gitdiff/gitdiff.go]: > So we're guaranteed in that case to end up with a mismatched tag.

* If there were `<span>` tags to do diff, then the diff might output broken tags, it has been fixed by https://github.com/go-gitea/gitea/pull/19958/commits/df5fef8a4c1e76c3a4e46c80f027222ce7fe345e
* That's impossible for placeholders to be broken, the tags are closed by the stack check.

File: services/gitdiff/gitdiff.go (hunk 7 above)
Comment (wxiaoguang) [reply services/gitdiff/gitdiff.go]: Do you mean to add a comment like "// It totally depends on Chroma's valid HTML output and its structure, do not use these functions for other purposes." ?

**Comment by wxiaoguang** [comment]
Hmm ... now I can get the point of the `html.EscapeString` problem. It seems to be more hacky to be fully resolved.

**Comment by wxiaoguang** [comment]
Changes in https://github.com/go-gitea/gitea/pull/19958/commits/90c644096b89f78cd1c5e5f1305adda9e76eb7f4

1. split the code into a new go file
2. use Plane 16: Supplementary Private Use Area B (U+100000..U+10FFFD) , 64000
3. handle html entities `&...;`
4. add comment `It totally depends on Chroma's valid HTML output and its structure, do not use these functions for other purposes.`
5. more tests.

TODO comment: when placeholders are exhausted, the html entites must be outputted as something (at the moment, 0xFFFD). since now there are 64000 placeholders, this case could be very rare.

File: services/gitdiff/gitdiff.go (hunk 5 above)
Comment (wxiaoguang) [reply services/gitdiff/gitdiff.go]: ps: "It would be a simple case to assign the closing placeholder at the same time as the opening placeholder to prevent this."

Although it's feasible, but it doesn't help much, because the opening/closing tags could still mismatch during diff.

So in any case, the closing tags should be added by the stack. Then no need to worry about there is no placeholder for closing tags.

File: services/gitdiff/highlightdiff.go [hunk 8]
```diff
@@ -0,0 +1,223 @@
...
+		// close all opening tags
+		for i := len(tagStack) - 1; i >= 0; i-- {
+			tagToClose := tagStack[i]
+			// get the closing tag "</span>" from "<span class=...>" or "<span>"
+			pos := strings.IndexAny(tagToClose, " >")
+			if pos != -1 {
+				sb.WriteString("</" + tagToClose[1:pos] + ">")
+			} // else: impossible. every tag was pushed into the stack by the code above and is valid HTML opening tag
+		}
+	}
```
Comment (zeripath) [inline services/gitdiff/highlightdiff.go:220]: This isn't right.

The return from `diffMatchPatch.DiffCleanupEfficiency` is `[]*Diff`.

Each `*Diff` represents an addition, unchanged or deletion section.

There is no guarantee that these sections have to be balanced individually.

The slice has to be balanced across the addition+unchanged or deletion+unchanged subsets all together.

Therefore you can have:

```
+ <span class="function">
- <span class="variable">
  amIaFunctionOrAVariable
+ ()
  </span>
```

Isn't this code going to result in:

```
+ <span class="function"></span>
- <span class="variable"></span>
  amIaFunctionOrAVariable
+ ()
  </span>
```

?

Comment (wxiaoguang) [reply services/gitdiff/highlightdiff.go:220]: In this case, the highlight is just lost, but the adding/removing tags are still correct. All tags are still balanced, and the last `</span>` won't be there, it should have been removed. https://github.com/go-gitea/gitea/pull/19958/files#diff-ee527c0c674cb10b21deadb5c08b523a8ff14727234ce3f752685c51d5e46b19R194-R200

I do not think there is a clear and easy way to make highlight still work perfectly in all cases, just better than before.

Comment (wxiaoguang) [reply services/gitdiff/highlightdiff.go:220]: See the demo in my last commit https://github.com/go-gitea/gitea/pull/19958/commits/9cf358b01a089fea78d476d1714265dda5f23204

It's guaranteed that tags in these sections are balanced individually.

Comment (wxiaoguang) [reply services/gitdiff/highlightdiff.go:220]: @zeripath ping. I think it is right. Do you have a real sample to break the code?

Comment (wxiaoguang) [reply services/gitdiff/highlightdiff.go:220]: @zeripath ping

**Review by silverwind — APPROVED** [review]
Seems to work well enough. I think we should land this PR and https://github.com/go-gitea/gitea/pull/19967 to streamline the code/diff renderings. After those are landed, I'd like to upgrade chroma to latest version.

**Comment by wxiaoguang** [comment]
Since there is no new suggestion since 14 days ago (with 3 pings), I will merge this PR.

I have confidence that this PR is better than before (stable behavior, no broken tags). And I will fix any bug in my code in the first time, as always.

**Comment by zeripath** [comment]
I suggest once this PR has completed being built we check results of looking at:

https://try.gitea.io/arandomer/pathological/commit/6a27858c792f20ec5789d5487362b74b9ac46411

and the parent commits to see whether anything like the problems I suggested might be occuring.

I am suspicious that there will be multiple issues resulting from this PR.

**Comment by wxiaoguang** [comment]
Now try.gitea.io is using this PR.

image

**Comment by zeripath** [comment]
Aha I've made the pathological case:

https://try.gitea.io/arandomer/pathological/commit/f98651b39614be44b15686165446502d6ce89c92

**Comment by wxiaoguang** [comment]
It's not easy (or nearly impossible) to make highlight diff work perfectly when doing post-highlight diff (https://github.com/go-gitea/gitea/pull/19958#issuecomment-1158699828), and some highlights **may** be lost or incorrect in some cases, but it won't affect the readers to see the correct diff result (IIRC I might have mentioned this before). The new code is just better than before, not perfect.

And IMO your cases are the expected outputs for this PR, and I would say that's still clear to reviewers.

For the first diff, I think readers can easily see that the `(` is moved.

For the second diff, the same, the readers can easily see that how the function name and arguments are changed.

In any case, the tags are balanced correctly.

**Comment by silverwind** [comment]
FYI, git's `diff.algorithm` also influences diff highlight. I'm a fan of `patience` as it generally produces better diffs, it's worth testing with:

```
[diff]
	algorithm = patience
```

**Comment by zeripath** [comment]
I'm sorry that both my comments here have been negative - This PR is a great idea using the unused characters to do this and the it does represent a significant improvement. 

However the problem I've pointed out is real and it will appear in real life.

There are two solutions to this:

1. The Add/delete section expands to include the semantic change.
   - e.g. in the change `fmt.Println(variableNoFunction() + "a")` to `fmt.Println(variable(NoFunction) + "a")` 
   - the add delete components are `variableNoFunction(` and `variable(NoFunction`
2. The semantic meaning crosses over the diff boundary.
   - Here one makes no attempt to fix up the elements until rendering.
   - When rendering you keep a stack and as you cross an add/delete/unchanged boundary you close all the tags before reopening them on the other side.

We need to choose one of these. I think if I interpret your replies correctly you think 2. is the right thing and it's probably the simplest thing to do. 1. is perhaps clearer to the user is closer to the patience algorithm and what we had before but honestly I don't want to argue.

**Comment by wxiaoguang** [comment]
Agree that 1 is clearer. Introducing a new "semantic change expanding" algorithm might make the result much better.

It's worth to try (I will try it if I have time later, and PRs are also welcome, let's make the code more right together).

I will open a new issue for this task.
