### PR TITLE
Avoid showing unnecessary JS errors when there are elements with different origin on the page

### LINKED ISSUE #29080: Javascript error: same origin policy
### Description

I get an error from my browser that Gitea tried to access forbidden elements to to SOP

### Gitea Version

1.21.1 (-rootless)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

portainer stack

### Database

SQLite

### PR DESCRIPTION
**Pull request by wxiaoguang**
Try to fix #29080

### CODE REVIEW

File: web_src/js/utils/dom.js [hunk 1]
```diff
@@ -59,6 +59,15 @@ export function onDomReady(cb) {
...
 
+export function isDocumentFragmentOrElementNode(el) {
+  try {
+    return el.nodeType === Node.ELEMENT_NODE || el.nodeType === Node.DOCUMENT_FRAGMENT_NODE;
+  } catch {
+    // in case the el is not in the same origin, then the access to nodeType would fail
+    return false;
+  }
+}
+
```
Comment (silverwind) [inline web_src/js/utils/dom.js:72]: Could we detect the iframe document via `el.ownerDocument !== document` and ignore those? I don't think we want to run the mutation callbacks on any iframe content (mermaid and user-configured renderers are the only cases I know of).

**Review by silverwind — APPROVED** [review]
I guess it is fine as-is, so above comment is an optional enhancement.

File: web_src/js/utils/dom.js (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/utils/dom.js:72]: done in 6299b57fd608bdd18781e5457115079ff568463c , and added more comments

**Review by lunny — APPROVED** [review]
