### PR TITLE
Fix bug filtering issues which have no project

### LINKED ISSUE #31327: Issues -> Project -> No project filter doesn't work
### Description

https://demo.gitea.com/Snuupy/test/issues?q=&type=all&sort=&state=open&labels=&project=-1&assignee=0&poster=0

all issues (even those assigned to a project) are listed (although the issue counter does update to the correct number)

label filters are working, project filter on "No project" are not.

Confirmed as a bug here: https://discord.com/channels/322538954119184384/322538954119184384/1250076856418439289

### Gitea Version

1.23.0+dev-201-g6106a61eff, 1.22.0, 1.21

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Tested on both demo.gitea.com and locally self-hosted on v1.22 and v1.21. Able to reproduce on all 3.

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix #31327
This is a quick patch to fix the bug.
Some parameters are using 0, some are using -1. I think it needs a refactor to keep consistent. But that will be another PR.

### CODE REVIEW

File: modules/indexer/issues/dboptions.go [hunk 1]
```diff
@@ -38,6 +38,12 @@ func ToSearchOptions(keyword string, opts *issues_model.IssuesOptions) *SearchOp
 		searchOpt.MilestoneIDs = opts.MilestoneIDs
 	}
 
+	if opts.ProjectID > 0 {
+		searchOpt.ProjectID = optional.Some(opts.ProjectID)
+	} else if opts.ProjectID == -1 { // FIXME: this is inconsistent from other places
```
Comment (delvh) [inline modules/indexer/issues/dboptions.go:43]: Didn't we have a constant for that?
`db.NoneID` or something like that?

Comment (lunny) [reply modules/indexer/issues/dboptions.go:43]: There is one `db.NoConditionID` which have a different meaning from here so I don't use that one to not confuse code readers.

**Review by delvh — APPROVED** [review]

**Review by kemzeb — APPROVED** [review]
