### PR TITLE
Fix bug when pushing to a pull request which enabled dismiss approval automatically

### LINKED ISSUE #25858: branch protection rules will not cancel old approvals after new commits submited
### Description

I set up branch protection rules half a month ago and checked the option "Dismiss stale pull request approvals when new commits are pushed", but this option did not take effect. Old approvals are not be canceled when there are new commits.

### Gitea Version

1.19.4

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

2a2e706d9c7394a883459b63fe5a9160
cd06ce2e6bd41fdfd001c608ccba8bbd

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker compose

### Database

MySQL

### PR DESCRIPTION
**Pull request by lunny**
Fix #25858 

The option `dissmiss stale approvals` was listed on protected branch but never implemented. This PR fixes that.

图片

图片

### CODE REVIEW

**Comment by silverwind** [comment]
Tests possible?

File: models/issues/issue.go [hunk 1]
```diff
@@ -551,7 +551,13 @@ func GetIssueWithAttrsByID(id int64) (*Issue, error) {
 
 // GetIssuesByIDs return issues with the given IDs.
 func GetIssuesByIDs(ctx context.Context, issueIDs []int64) (IssueList, error) {
-	issues := make([]*Issue, 0, 10)
+	issues := make([]*Issue, 0, len(issueIDs))
+	return issues, db.GetEngine(ctx).In("id", issueIDs).Find(&issues)
+}
+
+// GetIssuesMapByIDs return issues with the given IDs.
+func GetIssuesMapByIDs(ctx context.Context, issueIDs []int64) (map[int64]*Issue, error) {
```
Comment (wolfogre) [inline models/issues/issue.go]: It seems that the new function hasn't been used, I guess it was for `ReviewList.LoadIssues`, but you couldn't use it because of `issues.LoadRepositories(ctx)`, right?

**Review by wolfogre — APPROVED** [review]

File: models/issues/review_list.go [hunk 2]
```diff
@@ -0,0 +1,172 @@
...
+	reviews := make([]*Review, 0, 10)
+
+	sess := db.GetEngine(db.DefaultContext)
+
+	// Get latest review of each reviewer, sorted in order they were made
+	if err := sess.SQL("SELECT * FROM review WHERE id IN (SELECT max(id) as id FROM review WHERE issue_id = ? AND reviewer_team_id = 0 AND type in (?, ?, ?) AND dismissed = ? AND original_author_id = 0 GROUP BY issue_id, reviewer_id) ORDER BY review.updated_unix ASC",
+		issueID, ReviewTypeApprove, ReviewTypeReject, ReviewTypeRequest, false).
+		Find(&reviews); err != nil {
+		return nil, err
+	}
```
Comment (puni9869) [inline models/issues/review_list.go:158]: Could you write the query in separate step and error check if block in next step. 
it will easier to read and maintain.

Not a blocker  -> could you also form the query by query builder.

File: models/issues/review_list.go [hunk 3]
```diff
@@ -0,0 +1,172 @@
...
+
+	teamReviewRequests := make([]*Review, 0, 5)
+	if err := sess.SQL("SELECT * FROM review WHERE id IN (SELECT max(id) as id FROM review WHERE issue_id = ? AND reviewer_team_id <> 0 AND original_author_id = 0 GROUP BY issue_id, reviewer_team_id) ORDER BY review.updated_unix ASC",
+		issueID).
+		Find(&teamReviewRequests); err != nil {
+		return nil, err
+	}
```
Comment (puni9869) [inline models/issues/review_list.go:165]: same as above

**Review by puni9869 — APPROVED** [review]

**Comment by wxiaoguang** [comment]
If a PR focuses on refactoring, then only move necessary code.

If a PR focuses on bug fixing, then only fix the bug.

If a PR mixes code-moving and bug-fixing ..... it's really difficult to review.

File: models/issues/review_list.go (hunk 2 above)
Comment (wxiaoguang) [reply models/issues/review_list.go:158]: That's just moved from old code, I think keeping it as old is better, otherwise there might be new regression bugs.

Comment (puni9869) [reply models/issues/review_list.go:158]: Sure.

**Comment by puni9869** [comment]
> If a PR focuses on refactoring, then only move necessary code.
> 
> If a PR focuses on bug fixing, then only fix the bug.
> 
> If a PR mixes (unnecessary) code-moving and bug-fixing ..... it's really difficult to review.

Agreed.

**Comment by jpraet** [comment]
Could the participants of this PR have a look at https://github.com/go-gitea/gitea/issues/27114?
