### PR TITLE
Fix missing repo link in issue/pull assigned emails (#17183)

### LINKED ISSUE #17160: %!s() instead of repo name in email
### Gitea Version

1.15.0

### Git Version

2.30.2

### Operating System

docker Alpine Linux v3.13

### How are you running Gitea?

docker

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Description

@denis.patrakeev assigned you to the pull request #106 in repository %!s().

---
View it on Gitea: Git with a cup of tea.

### Screenshots

image

### PR DESCRIPTION
**Pull request by zeripath**
Backport #17183

There was a mistake in the template file: `templates/mail/issue/assigned.tmpl`
where the repourl was generated from a non-existent release instead of the issue.

This PR changes this to use the issue but also ensure that the issue repo is loaded.

It also slightly improves the English and the Russian locale string.

Fix #17160

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by axifive — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

File: services/mailer/mail.go [hunk 1]
```diff
@@ -344,6 +344,16 @@ func sanitizeSubject(subject string) string {
 
 // SendIssueAssignedMail composes and sends issue assigned email
 func SendIssueAssignedMail(issue *models.Issue, doer *models.User, content string, comment *models.Comment, recipients []*models.User) error {
+	if setting.MailService == nil {
+		// No mail service configured
+		return nil
+	}
+
+	if err := issue.LoadRepo(); err != nil {
+		log.Error("Unable to load rep [%d] for issue #%d [%d]. Error: %v", issue.RepoID, issue.Index, issue.ID, err)
```
Comment (6543) [inline services/mailer/mail.go]:
```suggestion
		log.Error("Unable to load repo [%d] for issue #%d [%d]. Error: %v", issue.RepoID, issue.Index, issue.ID, err)
```

**Comment by 6543** [comment]
:rocket:
