### PR TITLE
fix: media links in org files not liked to media files

### LINKED ISSUE #12831: Relative path in Org files does not link to raw files
- Gitea version (or commit ref): 1.12.4
- Git version: 2.25.1
- Operating system: Ubuntu Server 20.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (https://try.gitea.io/0Pranav/vulkan-tutorial/src/branch/master)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

In the example repo you can see org file in the master branch has the link https://try.gitea.io/0Pranav/vulkan-tutorial/src/branch/master/demo/vulkan.gif while in markdown the same link links to https://try.gitea.io/0Pranav/vulkan-tutorial/raw/branch/readme-test/demo/vulkan.gif, which results in the gif not being displayed in the org file

## Screenshots

Markdown
Screenshot from 2020-09-14 10-49-32

Org
Screenshot from 2020-09-14 10-49-41

### PR DESCRIPTION
**Pull request by 0Pranav**
In Org files, links to images and videos will be linked to "/media/" path, similar to 

https://github.com/go-gitea/gitea/blob/6a1a6332de5b5000d31ec26efaef6f78a4ee10f0/modules/markup/markdown/goldmark.go#L87-L93

Fixes #12831

### CODE REVIEW

File: modules/markup/orgmode/orgmode.go [hunk 1]
```diff
@@ -94,10 +95,23 @@ func (r *Renderer) WriteRegularLink(l org.RegularLink) {
 	}
 	switch l.Kind() {
 	case "image":
-		r.WriteString(fmt.Sprintf(`<img src="%s" alt="%s" title="%s" />`, link, description, description))
+		imageSrc := getMediaURL(link)
+		r.WriteString(fmt.Sprintf(`<img src="%s" alt="%s" title="%s" />`, imageSrc, description, description))
```
Comment (zeripath) [inline modules/markup/orgmode/orgmode.go]:
```suggestion
		fmt.Fprintf(r, `<img src="%s" alt="%s" title="%s" />`, imageSrc, description, description)
```

File: modules/markup/orgmode/orgmode.go [hunk 2]
```diff
@@ -94,10 +95,23 @@ func (r *Renderer) WriteRegularLink(l org.RegularLink) {
...
 	case "video":
-		r.WriteString(fmt.Sprintf(`<video src="%s" title="%s">%s</video>`, link, description, description))
+		videoSrc := getMediaURL(link)
+		r.WriteString(fmt.Sprintf(`<video src="%s" title="%s">%s</video>`, videoSrc, description, description))
```
Comment (zeripath) [inline modules/markup/orgmode/orgmode.go]:
```suggestion
		fmt.Fprintf(r, `<video src="%s" title="%s">%s</video>`, videoSrc, description, description)
```

File: modules/markup/orgmode/orgmode.go [hunk 3]
```diff
@@ -94,10 +95,23 @@ func (r *Renderer) WriteRegularLink(l org.RegularLink) {
...
 	default:
 		r.WriteString(fmt.Sprintf(`<a href="%s" title="%s">%s</a>`, link, description, description))
```
Comment (zeripath) [inline modules/markup/orgmode/orgmode.go]:
```suggestion
		fmt.Fprintf(r, `<a href="%s" title="%s">%s</a>`, link, description, description)
```

**Comment by zeripath** [comment]
Thanks for the PR - this looks like it would solve the problem - however, as a R is an io.Writer we should just get fmt.Fprintf to write to it directly instead of using the r.WriteString method.

**Review by zeripath — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]
