### PR TITLE
Fix signal loop in graceful manager

### LINKED ISSUE #19940: Sometimes `^C` will generate huge "shutting down" logs during integration test
```
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
    testlogger.go:78: 2022/06/11 20:14:36 ...eful/manager_unix.go:158:handleSignals() [W] PID: 13381. Background context for manager closed - context canceled - Shutting down...
```

### PR DESCRIPTION
**Pull request by wxiaoguang**
Close #19940

I think it needs a `break`

### CODE REVIEW

**Review by delvh — APPROVED** [review]
If only all problems were that easily fixable...

**Comment by wxiaoguang** [comment]
Unfortunately some are not 😭 I have spent many hours on 19930 , even then an auxiliary 19941 😂

File: modules/graceful/manager_unix.go [hunk 1]
```diff
@@ -157,6 +158,7 @@ func (g *Manager) handleSignals(ctx context.Context) {
 		case <-ctx.Done():
 			log.Warn("PID: %d. Background context for manager closed - %v - Shutting down...", pid, ctx.Err())
 			g.DoGracefulShutdown()
+			break loop
```
Comment (42wim) [inline modules/graceful/manager_unix.go]: maybe just `return` is simpler?

Comment (wxiaoguang) [reply modules/graceful/manager_unix.go]: Does `break` has some shortcoming?

I think `break` is more clear because there are nested for+select. When the context is done, stopping the context loop seems more intuitive. And breaking out will make future code more easier to be added after the for loop, logs & further process.

Comment (lunny) [reply modules/graceful/manager_unix.go]: There is another `g.DoGracefulShutdown()` above but not break?

Comment (wxiaoguang) [reply modules/graceful/manager_unix.go]: No, that's different. 

The `g.DoGracefulShutdown()` above is triggered by `case sig := <-signalChannel:`, each signal triggers a call, there is no infinite loop.

But this one is trigger by `case <-ctx.Done():`, on a closed channel, it's a infinite loop.

Comment (42wim) [reply modules/graceful/manager_unix.go]: > Does `break` has some shortcoming?
> 
> I think `break` is more clear because there are nested for+select. When the context is done, stopping the context loop seems more intuitive. And breaking out will make future code more easier to be added after the for loop, logs & further process.

It's probably personal preference, result is the same. It's just a bit confusing for me to do a break there when it just exits anyway. I'm not sure if you need to optimize for future code that will or will not happen.

Comment (lafriks) [reply modules/graceful/manager_unix.go]: in this case I would also prefer return, it would be more clear

Comment (wxiaoguang) [reply modules/graceful/manager_unix.go]: Yup, it's personal preference, result is the same. Since most people like `return` more, so there it is.

**Review by Gusted — APPROVED** [review]

**Review by 42wim — APPROVED** [review]

**Review by lafriks — APPROVED** [review]
