### PR TITLE
Cause NotifyMigrateRepository to emit a repo create webhook

### LINKED ISSUE #13996: No system webhook triggered for repository migration
- Gitea version (or commit ref): 980b0df8296cdec3692482c3efdbfa68036a1114
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (*need admin access*)
- Log gist:

## Description

System webhooks (added with https://github.com/go-gitea/gitea/pull/10546) trigger when you create a new repository but not when you migrate a repository. 

### Steps to reproduce

- Compile and run a local Gitea
- Start a web server that will log webhook attempts, e.g.

```
$ python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
```
- Go to http://localhost:3000/admin/system-hooks and add a system webhook, for all events

image

- Add a new repository, see that the web server logs them (the 501 error is expected)
```
127.0.0.1 - - [15/Dec/2020 14:30:05] code 501, message Unsupported method ('POST')
127.0.0.1 - - [15/Dec/2020 14:30:05] "POST / HTTP/1.1" 501 -
```

- Migrate a repository and observe that no request is sent and nothing is logged on the webserver.

### PR DESCRIPTION
**Pull request by zeripath**
This PR simply makes NotifyMigrateRepository emit a Create Repo webhook.
The reason for no new payload is that the information sent to
NotifyMigrateRepository is only essentially the same as
NotifyCreateRepository

Fix #13996

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: modules/notification/webhook/webhook.go [hunk 1]
```diff
@@ -122,6 +122,19 @@ func (m *webhookNotifier) NotifyDeleteRepository(doer *models.User, repo *models
 	}
 }
 
+// NotifyMigrateRepository places a place holder function
```
Comment (6543) [inline modules/notification/webhook/webhook.go]:
```suggestion
```

**Review by 6543 — APPROVED** [review]
