### PR TITLE
Clarify Actions resources ownership

### LINKED ISSUE #31707: Runner registration token via API is broken for repo level runners
### Description

While I can obtain a token through an "undocumented" API call, using it results in broken runner behavior.

1. Retrieving a token via `/repos/{owner}/{repo}/runners/registration-token`, as referenced in `${GITEA_URL}/api/swagger`, returns a 404 error.

2. By examining related API calls, I added `/actions` to the endpoint. This adjustment does return a token for a runner mapped to a repository, but it differs from the token displayed in the repository's Actions settings in the web UI.

Moreover, using this token allows the registration of a runner. However, it will **only process the first job assigned after a restart.**

### Gitea Version

1.22-rootless

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/floriankessler/b7b3a141b11edd34e8867f423ddd3acb

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

see gist

### Database

SQLite

### PR DESCRIPTION
**Pull request by wolfogre**
Fix #31707.

Also related to #31715.

Some Actions resources could has different types of ownership. It could be:

- global: all repos and orgs/users can use it.
- org/user level: only the org/user can use it.
- repo level: only the repo can use it.

There are two ways to distinguish org/user level from repo level:
1. `{owner_id: 1, repo_id: 2}` for repo level, and `{owner_id: 1, repo_id: 0}` for org level.
2. `{owner_id: 0, repo_id: 2}` for repo level, and `{owner_id: 1, repo_id: 0}` for org level.

The first way seems more reasonable, but it may not be true. The point is that although a resource, like a runner, belongs to a repo (it can be used by the repo), the runner doesn't belong to the repo's org (other repos in the same org cannot use the runner). So, the second method makes more sense.

And the first way is not user-friendly to query, we must set the repo id to zero to avoid wrong results.

So, #31715 should be right. And the most simple way to fix #31707 is just:

```diff
-	shared.GetRegistrationToken(ctx, ctx.Repo.Repository.OwnerID, ctx.Repo.Repository.ID)
+	shared.GetRegistrationToken(ctx, 0, ctx.Repo.Repository.ID)
```

However, it is quite intuitive to set both owner id and repo id since the repo belongs to the owner. So I prefer to be compatible with it. If we get both owner id and repo id not zero when creating or finding, it's very clear that the caller want one with repo level, but set owner id accidentally. So it's OK to accept it but fix the owner id to zero.

### CODE REVIEW

File: models/actions/variable.go [hunk 1]
```diff
@@ -29,39 +40,40 @@ func init() {
...
 	Name    string
 }
 
 func (opts FindVariablesOpts) ToConds() builder.Cond {
 	cond := builder.NewCond()
 	// Since we now support instance-level variables,
 	// there is no need to check for null values for `owner_id` and `repo_id`
-	cond = cond.And(builder.Eq{"owner_id": opts.OwnerID})
 	cond = cond.And(builder.Eq{"repo_id": opts.RepoID})
+	if opts.OwnerID != 0 {
```
Comment (Zettat123) [inline models/actions/variable.go]: Should be `opts.RepoID != 0` ?

Comment (wolfogre) [reply models/actions/variable.go]: Good catch. It looks like I need to carefully recheck the logic.

Comment (wolfogre) [reply models/actions/variable.go]: 95e1501575

**Review by Zettat123 — APPROVED** [review]

**Review by lunny — APPROVED** [review]
