### PR TITLE
Fix bug when review pull request commits

### LINKED ISSUE #35157: File tree in PR is not correct when a special commit is selected
### Description

Example:
https://gitea.com/gitea/tea/pulls/776/commits/988854e5ee11f63219f8c68855bb3a867ef4cc65#diff-0139b614aeec3ca16af7f2974ae2b0edd8dd6997

Access this url, and you will find the file tree is not corret.

Image

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

gitea.com

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
The commit range in the UI follows a half-open, half-closed convention: (,]. When reviewing a range of commits, the beforeCommitID should be set to the commit immediately preceding the first selected commit. For single-commit reviews, we must identify and use the previous commit of that specific commit.

The endpoint ViewPullFilesStartingFromCommit is currently unused and can be safely removed.

Fix #35157 
Replace #35184 
Partially extract from #35077

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Review by hiifong — APPROVED** [review]

File: web_src/js/components/DiffCommitSelector.vue [hunk 1]
```diff
@@ -32,6 +32,7 @@ export default defineComponent({
       locale: {
         filter_changes_by_commit: el.getAttribute('data-filter_changes_by_commit'),
       } as Record<string, string>,
+      merge_base: el.getAttribute('data-merge-base'),
```
Comment (wxiaoguang) [inline web_src/js/components/DiffCommitSelector.vue]: I don't think it is a proper naming style.

Image

File: routers/web/web.go [hunk 2]
```diff
@@ -1540,7 +1540,6 @@ func registerWebRoutes(m *web.Router) {
 			m.Post("/cleanup", context.RepoMustNotBeArchived(), repo.CleanUpPullRequest)
 			m.Group("/files", func() {
 				m.Get("", repo.SetEditorconfigIfExists, repo.SetDiffViewStyle, repo.SetWhitespaceBehavior, repo.SetShowOutdatedComments, repo.ViewPullFilesForAllCommitsOfPr)
-				m.Get("/{sha:[a-f0-9]{7,40}}", repo.SetEditorconfigIfExists, repo.SetDiffViewStyle, repo.SetWhitespaceBehavior, repo.SetShowOutdatedComments, repo.ViewPullFilesStartingFromCommit)
 				m.Get("/{shaFrom:[a-f0-9]{7,40}}..{shaTo:[a-f0-9]{7,40}}", repo.SetEditorconfigIfExists, repo.SetDiffViewStyle, repo.SetWhitespaceBehavior, repo.SetShowOutdatedComments, repo.ViewPullFilesForRange)
```
Comment (wxiaoguang) [inline routers/web/web.go]: Maybe a legacy problem, the regexp range is not right for sha256

Comment (lunny) [reply routers/web/web.go]: 2ac3e8b29c

File: web_src/js/components/DiffCommitSelector.vue (hunk 1 above)
Comment (lunny) [reply web_src/js/components/DiffCommitSelector.vue]: 2ac3e8b29c

File: web_src/js/components/DiffCommitSelector.vue [hunk 3]
```diff
@@ -179,28 +180,29 @@ export default defineComponent({
      * When a commit is clicked with shift this enables the range
      * selection. Second click (with shift) defines the end of the
      * range. This opens the diff of this range
-     * Exception: first commit is the first commit of this PR. Then
-     * the diff from beginning of PR up to the second clicked commit is
-     * opened
```
Comment (wxiaoguang) [inline web_src/js/components/DiffCommitSelector.vue:184]: Is it clear about the new logic's behavior?

File: web_src/js/components/DiffCommitSelector.vue [hunk 4]
```diff
@@ -179,28 +180,29 @@ export default defineComponent({
...
-          } else {
-            window.location.assign(`${this.issueLink}/files/${this.commits[lastCommitIdx].id}${this.queryParams}`);
-          }
+        const firstSelected = this.commits.findIndex((x) => x.selected);
+        let start: string;
+        if (firstSelected === 0) {
+          start = this.mergeBase;
+        } else {
+          start = this.commits[firstSelected - 1].id;
+        }
```
Comment (wxiaoguang) [inline web_src/js/components/DiffCommitSelector.vue]: Related to https://github.com/go-gitea/gitea/pull/35192/files#r2249149915:

What's the expected behaviors? Why "merge base" is used when the first commit is selected?

Is it consistent for various cases? For example: we have: {MergeBase}, {Commit1}, {Commit2}, {Commit3}, {Commit4}.

Then:

* Select from {Commit1} to {Commit3} means {MergeBase}...{Commit3}
* Select from {Commit2} to {Commit3} means {Commit2}...{Commit3}

???

Comment (lunny) [reply web_src/js/components/DiffCommitSelector.vue]: > Related to https://github.com/go-gitea/gitea/pull/35192/files#r2249149915:
> 
> What's the expected behaviors? Why "merge base" is used when the first commit is selected?
> 
> Is it consistent for various cases? For example: we have: {MergeBase}, {Commit1}, {Commit2}, {Commit3}, {Commit4}.
> 
> Then:
> 
> * Select from {Commit1} to {Commit3} means {MergeBase}...{Commit3}
> * Select from {Commit2} to {Commit3} means {Commit2}...{Commit3}
> 
> ???

Select from {Commit1} to {Commit3} means {MergeBase}...{Commit3}
```diff
-Select from {Commit2} to {Commit3} means {Commit2}...{Commit3}
Select from {Commit2} to {Commit3} means {Commit1}...{Commit3}
```

The first commit should always be the previous commit of the first selected commit.

File: web_src/js/components/DiffCommitSelector.vue (hunk 3 above)
Comment (lunny) [reply web_src/js/components/DiffCommitSelector.vue:184]: cbe8552a99

File: web_src/js/components/DiffCommitSelector.vue (hunk 4 above)
Comment (lunny) [reply web_src/js/components/DiffCommitSelector.vue]: cbe8552a99

**Review by wxiaoguang — APPROVED** [review]
Maybe no need to backport
