### PR TITLE
Include public repos in doer's dashboard for issue search

### LINKED ISSUE #28055: pulls/issue page very slow with >19000 repos
### Description

On my gitea instance with 19000 repositories and 3200 ogas the pulls page need

image

in 1.20.5 it was fast.

Possible SQL query changes.

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.42.0

### Operating System

Ubuntu 20.04.x

### How are you running Gitea?

gitea-1.21.0-linux-amd64

### Database

PostgreSQL

### LINKED ISSUE #28268: User Issues page no longer shows issues in all repositories
### Description

To reproduce:
* Have a Gitea instance with an existing repository
* Create a new user
* With that new user, create a new issue in the repository
* Navigate to the Issues page, "Created by you" shows no issues

If the user owns the repository or is a member of a team with access it will show the issues. But it's useful to e.g. see all bugs you reported to projects you are not a member of.

This was caused by #26545. That fixed a bug when a team is selected but probably should not have affected the case where a user is selected?

### Gitea Version

4d7c063 (latest main)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Own build.

### Database

SQLite

### PR DESCRIPTION
**Pull request by wolfogre**
It will fix #28268 .

image

image

## :warning: BREAKING :warning:

But need to give up some features:

image

However, such abandonment may fix #28055 .

## Backgroud

When the user switches the dashboard context to an org, it means they want to search issues in the repos that belong to the org. However, when they switch to themselves, it means all repos they can access because they may have created an issue in a public repo that they don't own.

image

It's a confusing design. Think about this: What does "In your repositories" mean when the user switches to an org? Repos belong to the user or the org?

Whatever, it has been broken by #26012 and its following PRs. After the PR, it searches for issues in repos that the dashboard context user owns or has been explicitly granted access to, so it causes #28268.

## How to fix it

It's not really difficult to fix it. Just extend the repo scope to search issues when the dashboard context user is the doer. Since the user may create issues or be mentioned in any public repo, we can just set `AllPublic` to true, which is already supported by indexers. The DB condition will also support it in this PR.

But the real difficulty is how to count the search results grouped by repos. It's something like "search issues with this keyword and those filters, and return the total number and the top results. **Then, group all of them by repo and return the counts of each group.**"

image

Before #26012, it was being done in the DB, but it caused the results to be incomplete (see the description of #26012).

And to keep this, #26012 implement it in an inefficient way, just count the issues by repo one by one, so it cannot work when `AllPublic` is true because it's almost impossible to do this for all public repos.

https://github.com/go-gitea/gitea/blob/1bfcdeef4cca0f5509476358e5931c13d37ed1ca/modules/indexer/issues/indexer.go#L318-L338

## Give up unnecessary features

We may can resovle `TODO: use "group by" of the indexer engines to implement it`, I'm sure it can be done with Elasticsearch, but IIRC, Bleve and Meilisearch don't support "group by".

And the real question is, does it worth it? Why should we need to know the counts grouped by repos?

Let me show you my search dashboard on gitea.com.

image

I never think the long repo list helps anything.

And if we agree to abandon it, things will be much easier. That is this PR.

## TODO

I know it's important to filter by repos when searching issues. However, it shouldn't be the way we have it now. It could be implemented like this.

image

The indexers support it well now, but it requires some frontend work, which I'm not good at. So, I think someone could help do that in another PR and merge this one to fix the bug first.

Or please block this PR and help to complete it.

Finally, "Switch dashboard context" is also a design that needs improvement. In my opinion, it can be accomplished by adding filtering conditions instead of "switching".

### CODE REVIEW

File: routers/web/user/home.go [hunk 1]
```diff
@@ -887,7 +767,9 @@ func getUserIssueStats(ctx *context.Context, filterMode int, opts *issue_indexer
 	{
 		openClosedOpts := opts.Copy()
 		switch filterMode {
-		case issues_model.FilterModeAll, issues_model.FilterModeYourRepositories:
+		case issues_model.FilterModeAll:
```
Comment (wxiaoguang) [inline routers/web/user/home.go:770]: Either remove this line or add a comment like `// no-op` ?

**Review by wxiaoguang — APPROVED** [review]
I do not need the left "repo list", so I have no objection.

But it doesn't seem good to backport such a breaking change.

File: routers/web/user/home.go (hunk 1 above)
Comment (wolfogre) [reply routers/web/user/home.go:770]: Updated: 1de6c7cc27941beaf1773b1e3167ab28168565af

**Review by lunny — APPROVED** [review]

**Comment by 6543** [comment]
if you use it less like an "issue search" and more like an "issue dashboard" the repo filter IS quite usefull ...

some could argue that the UX was bad ... yes. I'll open a new issue to bring "repo filters" back .. -> #31578
