### PR TITLE
Some refactors about GetMergeBase

### LINKED ISSUE #32018: GetCompareInfo, AddRemote: exit status 128 - error: could not lock config file config: File exists
### Description

When someone is trying to open a pull request on a repo, we're getting a 500 error :

```
Internal Server Error

Une erreur s’est produite:

GetCompareInfo, AddRemote: exit status 128 - error: could not lock config file config: File exists
fatal: could not set 'remote.1725953120549272064.url' to '/var/lib/gitea/data/gitea-repositories/tala/python-docs-fr.git'
 - error: could not lock config file config: File exists
fatal: could not set 'remote.1725953120549272064.url' to '/var/lib/gitea/data/gitea-repositories/tala/python-docs-fr.git'

Version de Gitea: 1.22.2

Si vous pensez qu'il s'agit d'un bug Gitea, veuillez consulter notre board [GitHub](https://github.com/go-gitea/gitea/issues) ou ouvrir un nouveau ticket si nécessaire.
```

On the target repo I see the lock file:

```
root@gitea1:~# ls -lah /var/lib/gitea/data/gitea-repositories/afpy/python-docs-fr.git
total 112K
drwxr-xr-x  8 git git 4.0K Sep 10 05:33 .
drwxr-xr-x 20 git git 4.0K Jul 23  2023 ..
-rw-r--r--  1 git git  134 Jul 26 09:04 FETCH_HEAD
-rw-r--r--  1 git git   21 Nov 17  2022 HEAD
drwxr-xr-x  2 git git 4.0K Nov 17  2022 branches
-rw-r--r--  1 git git  32K Jul 26 09:04 config
-rw-r--r--  1 git git  18K Jul 26 09:04 config.lock
```

Looks like the lock file is a month old.

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.30.2

### Operating System

Debian 11.11

### How are you running Gitea?

Self hosted, installed via ansible: https://git.afpy.org/AFPy/infra/src/branch/main/roles/gitea/tasks/setup.yml

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by lunny**
Maybe fix #32018

- Use `gitrepo.GetMergeBase` method instead of other two implementations.
- Add `FetchRemoteCommit` so that we don't need to add many `remote` to the git repository to avoid possible git lock conflicts. A lock will start when invoke the function, it will be invoked when cross-repository comparing. The head repository will fetch the base repository's base commit id. In most situations, it should lock the fork repositories so that it should not become a bottleneck.
- Improve `GetCompareInfo` to remove unnecessarily adding remote.
- Remove unnecessary parameters of `SignMerge`.

### CODE REVIEW

**Review by Zettat123 — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

File: modules/gitrepo/fetch.go [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+package gitrepo
+
+import (
+	"context"
+
+	"code.gitea.io/gitea/modules/git/gitcmd"
+)
+
+// FetchRemoteCommit fetches a specific commit and related commits from a remote repository into the managed repository
+// it will be checked in 2 weeks by default from git if the pull request created failure.
```
Comment (wxiaoguang) [inline modules/gitrepo/fetch.go]: * How the "check" occurs, any document?
* What does "if the pull request created failure" mean? The PR created a "failure object", or the PR is failed to be created? Any bad result if "failure" occurs?
* What if the "check" doesn't run?

File: services/issue/pull.go [hunk 2]
```diff
@@ -99,14 +80,16 @@ func PullRequestCodeOwnersReview(ctx context.Context, pr *issues_model.PullReque
 	}
 
 	// get the mergebase
-	mergeBase, err := getMergeBase(ctx, pr.BaseRepo, repo, pr, git.BranchPrefix+pr.BaseBranch, pr.GetGitHeadRefName())
-	if err != nil {
-		return nil, err
+	if pr.MergeBase == "" {
```
Comment (wxiaoguang) [inline services/issue/pull.go]: Is it safe to use `MergeBase` here? It can be out-dated because `AddTestPullRequestTask` is executed in a go-routine.

**Comment by wxiaoguang** [comment]
CI failure is also related.

Do rerun the CI multiple times before merge to ensure there is no regression.

File: services/issue/pull.go (hunk 2 above)
Comment (lunny) [reply services/issue/pull.go]: 1a51a6f

File: modules/gitrepo/fetch.go (hunk 1 above)
Comment (lunny) [reply modules/gitrepo/fetch.go]: I have updated the comment at 109e9e152eadb21c617c77cc2a6e50c9c958b0fc and in a short, `git gc` will clean them if no reference point to them. reference documentation is https://www.kernel.org/pub/software/scm/git/docs/git-gc.html

**Comment by wxiaoguang** [comment]
> CI failure is also related.
> 
> Do rerun the CI multiple times before merge to ensure there is no regression.

CI failure is still related


```
     pull_create_test.go:98: 
        	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/integration_test.go:348
        	            				/home/runner/work/gitea/gitea/tests/integration/integration_test.go:160
        	            				/home/runner/work/gitea/gitea/tests/integration/pull_create_test.go:98
        	            				/home/runner/work/gitea/gitea/tests/integration/pull_create_test.go:399
        	            				/opt/hostedtoolcache/go/1.25.5/x64/src/sync/waitgroup.go:239
        	            				/opt/hostedtoolcache/go/1.25.5/x64/src/runtime/asm_amd64.s:1693
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 500
        	Test:       	TestPullCreateParallel
        	Messages:   	Request: GET /user2/repo1/compare/master...user1/repo1:new-branch-3


    pull_create_test.go:416: 
        	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/pull_create_test.go:416
        	            				/home/runner/work/gitea/gitea/tests/integration/git_helper_for_declarative_test.go:88
        	            				/home/runner/work/gitea/gitea/tests/integration/pull_create_test.go:384
        	Error:      	Not equal: 
        	            	expected: 8
        	            	actual  : 7
        	Test:       	TestPullCreateParallel
    pull_create_test.go:417: 
        	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/pull_create_test.go:417
        	            				/home/runner/work/gitea/gitea/tests/integration/git_helper_for_declarative_test.go:88
        	            				/home/runner/work/gitea/gitea/tests/integration/pull_create_test.go:384
        	Error:      	Not equal: 
        	            	expected: 8
        	            	actual  : 7
        	Test:       	TestPullCreateParallel
```

**Comment by lunny** [comment]
> CI failure is also related.
> 
> Do rerun the CI multiple times before merge to ensure there is no regression.

Added a lock for the fetch operations to the repository and rerun the CI many times and all PASS.

**Comment by wxiaoguang** [comment]
fix(pull): sign the commit when updating a branch by merge #38441
