### PR TITLE
fix: add author.name field to Swift Package Registry API response

### LINKED ISSUE #35159: Author Field Name Inconsistency in Gitea Swift Package Registry
### Description

I am using a local Gitea server to host a Swift Package registry. I successfully uploaded a binary Swift package to the registry, but when attempting to fetch the package, the operation fails with the following error:

> Computing version for controller.Redacted
error: failed fetching controller.Redacted version 25.4100.267 release information from https://redacted/api/packages/redaced/swift: keyNotFound(CodingKeys(stringValue: "name", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "metadata", intValue: nil), CodingKeys(stringValue: "author", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"name\", intValue: nil) (\"name\").", underlyingError: nil))

Issue Details

- The error message indicates that the `"author"` field is missing the `"name"` subfield.
- When I upload metadata containing `"author.name"`, it is not reflected in the server’s response.
- If I provide `"author.givenName"` in the format specified by  [schema.org](https://schema.org/author) , it appears in the server response, but the Swift Package Manager (SPM) does not recognize it.
- By editing SPM’s source code to use `"givenName"` instead of `"name"`, everything works as expected.

Root Cause
There is a mismatch between the JSON schema references in different documentation sources:
- The Gitea [documentation](https://docs.gitea.com/usage/packages/swift) follows a schema that uses `"givenName"`, `"familyName"`, and `"additionalName"` fields for the author.
- In contrast, the Swift Package Registry [documentation](https://github.com/swiftlang/swift-package-manager/blob/main/Documentation/PackageRegistry/Registry.md#appendix-b---package-release-metadata-json-schema) specifies a simpler schema with just the `"name"` field for the author.

Expected Behavior
Gitea’s Swift Package Registry implementation should conform to the schema expected by Swift Package Manager, specifically providing an `"author.name"` field in the package metadata. Gitea [documentation](https://docs.gitea.com/usage/packages/swift) should also be updated.

Steps to Reproduce
1. Host a Swift Package Registry using Gitea.
2. Upload a binary Swift package with metadata including `"author.name"`.
`swift package-registry publish --metadata-path metadata.json scope.packageName 25.4100.267`
3.  Attempt to fetch the package using Swift Package Manager.
`swift package resolve`

### Gitea Version

1.24.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

–

### Operating System

macOS 15.5

### How are you running Gitea?

I am using self-hosted version of Gitea installed via Homebrew

### Database

None

### PR DESCRIPTION
**Pull request by ahanoff**
Fixes #35159

Swift Package Manager expects an 'author.name' field in package metadata, but Gitea was only providing schema.org format fields (givenName, middleName, familyName). This caused SPM to fail with keyNotFound error when fetching package metadata.

Changes:
- Add 'name' field to Person struct (inherited from https://schema.org/Thing)
- Populate 'name' field in API response using existing String() method
- Maintains backward compatibility with existing schema.org fields
- Provides both formats for maximum compatibility

The fix ensures Swift Package Manager can successfully resolve packages while preserving full schema.org compliance.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Maybe add some tests here ? 

https://github.com/go-gitea/gitea/blob/07347634aa70defb7820332f4c860bb24f4ada2f/tests/integration/api_packages_swift_test.go#L357

**Comment by lunny** [comment]
It seems this only resolves the issue when retrieving package information, but not when uploading a package.

**Comment by ahanoff** [comment]
> It seems this only resolves the issue when retrieving package information, but not when uploading a package.

@lunny before I finalize the fix, I want to clarify the intended behavior for the `name` field in upload package metadata:

Should it be:
1. A separate field that users can set independently
2. Always auto-generated from `givenName + middleName + familyName` 
3. A combination - use explicit `name` if provided, otherwise generate from components

Which approach aligns better with Gitea's design?

**Comment by wxiaoguang** [comment]
> A combination - use explicit `name` if provided, otherwise generate from components

I guess the design could be this one? As long as end users can provide the "name" field, then use the value provided by them.

File: modules/packages/swift/metadata.go [hunk 1]
```diff
@@ -184,11 +185,17 @@ func ParsePackage(sr io.ReaderAt, size int64, mr io.Reader) (*Package, error) {
...
 		p.Metadata.License = ssc.License
-		p.Metadata.Author = Person{
+		author := Person{
+			Name:       ssc.Author.Name,
 			GivenName:  ssc.Author.GivenName,
 			MiddleName: ssc.Author.MiddleName,
 			FamilyName: ssc.Author.FamilyName,
 		}
+		// If Name is not provided but individual name components are, generate it
+		if author.Name == "" && (author.GivenName != "" || author.MiddleName != "" || author.FamilyName != "") {
```
Comment (wxiaoguang) [inline modules/packages/swift/metadata.go]:
```suggestion
		if author.Name == "" {
```

Maybe we can simplify the `if` check to this? If `author.Name` and `author.String()` are both empty, then it is still fine to assign the "Name" field?

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]
