### PR TITLE
Batch hook pre- and post-receive calls

### LINKED ISSUE #8540: Migration of repositories with tags to organisation fails
- Gitea version (or commit ref): 1.9.4
- Git version: 1.8.3.1
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MariaDB
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
We are currently migrating all of our 230 repositories to Gitea. Here's how we do it:

1. git clone --mirror https://old-git.example.org/repo.git
2. git push --mirror https://gitea.example.org/ORG/repo.git

To keep it simple our Gitea instance has just one organisation with around 110 "Owner" team members. When we migrate repositories with more than 50 tags to that organisation, the git client pushes everything without an error, but Gitea fails when creating releases for every tag with the following message:
```
2019/10/16 11:12:42 models/webhook.go:909:DeliverHooks() [E] Get repository [235] hook tasks: dial tcp 172.xxx.xxx.xxx:3306: connect: cannot assign requested address
```
In the Gitea logfile I can see that Gitea calls `repo_permission.go` for every tag and every user of that organisation, which results in a lot of calls and presumably database queries:
```
2019/10/16 11:12:39 models/update.go:80:PushUpdate() [T] TriggerTask 'TAGNAME' by gituser
2019/10/16 11:12:39 models/pull.go:1088:AddTestPullRequestTask() [T] AddTestPullRequestTask [head_repo_id: xxx, head_branch: xxx]: finding pull requests
2019/10/16 11:12:39 modules/auth/auth.go:97:CheckOAuthAccessToken() [T] ParseOAuth2Token: signature is invalid
2019/10/16 11:12:39 ...s/context/context.go:328:func1() [D] Session ID: xxx
2019/10/16 11:12:39 ...s/context/context.go:329:func1() [D] CSRF Token: xxx
2019/10/16 11:12:39 models/pull.go:1128:AddTestPullRequestTask() [T] AddTestPullRequestTask [base_repo_id: xxx, base_branch: xxx]: finding pull requests
2019/10/16 11:12:40 ...s/repo_permission.go:154:func1() [T] Permission Loaded for 824725727744:USER1 in 824725727824:ORG/reponame
2019/10/16 11:12:40 ...s/repo_permission.go:154:func1() [T] Permission Loaded for 824729407712:USER2 in 824729407808:ORG/reponame
2019/10/16 11:12:40 ...s/repo_permission.go:154:func1() [T] Permission Loaded for 824729900800:USER3 in 824729900880:ORG/reponame
[...]
```
When migrating that same repository to a "standalone" user account, everything works as expected. All releases get created. In the Gitea logfile I can see that gitea doesn't call `repo_permission.go`, in this case:
```
2019/10/16 12:18:27 models/update.go:80:PushUpdate() [T] TriggerTask 'TAG1' by gituser
2019/10/16 12:18:27 models/pull.go:1088:AddTestPullRequestTask() [T] AddTestPullRequestTask [head_repo_id: xxx, head_branch: xxx]: finding pull requests
2019/10/16 12:18:27 modules/auth/auth.go:97:CheckOAuthAccessToken() [T] ParseOAuth2Token: signature is invalid
2019/10/16 12:18:27 ...s/context/context.go:328:func1() [D] Session ID: xxx
2019/10/16 12:18:27 ...s/context/context.go:329:func1() [D] CSRF Token: xxx
2019/10/16 12:18:27 models/pull.go:1128:AddTestPullRequestTask() [T] AddTestPullRequestTask [base_repo_id: xxx, base_branch: xxx]: finding pull requests
2019/10/16 12:18:28 models/webhook.go:898:DeliverHooks() [T] DeliverHooks [repo_id: xxx]
2019/10/16 12:18:28 models/update.go:80:PushUpdate() [T] TriggerTask 'TAG2' by gituser
[...]
```
We also tried to migrate a very large repository with around 15.000 commits and 7000 tags. Although we get an error from the git client, everything (tags, commits) gets transmitted and all releases get created by gitea when migrating to a user repository.
```
user@linux:~/repo.git$ git push --mirror https://gitea.example.org/ORG/repo.git
Counting objects: 409616, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (108168/108168), done.
Writing objects: 100% (409616/409616), 1.14 GiB | 25.52 MiB/s, done.
Total 409616 (delta 201291), reused 409611 (delta 201286)
error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
fatal: The remote end hung up unexpectedly
error: error in sideband demultiplexer
Everything up-to-date
user@linux:~/repo.git$ git push --mirror https://gitea.example.org/ORG/repo.git
Everything up-to-date
```
Long story short, when we migrate repositories with more, or way more than 50 tags to a user account, everything works. When we migrate them to an organizazion with a lot of members, Gitea gets stuck when creating releases from tags.

## Workaround
As a workaround we first migrate to a user account and then transmit the ownership of the repository to the organisation.

### PR DESCRIPTION
**Pull request by zeripath**
Whilst looking at #8540, it was noticed that our pre-receive and post-receive hooks are highly inefficient during migration. Each updated/created reference causes a separate request on the private hooks URL.

This patch batches up the updated/created references in batches up to 30 and tries to reduce the amount of duplicated requests to the db. 

Fixes #8540 - although the underlying issue with db connections potentially causing a TIME_WAIT connection explosion requires #8528. 

EDIT: dropped the batch size to 30.

### CODE REVIEW

**Comment by lunny** [comment]
Why not send only one request to internal web router when one post_receive triggered?

**Comment by zeripath** [comment]
I'm not sure I understand the question.

There's 3 options:

* Send a post-receive request for each line in the stdin. Simple, but inefficient: reasonable if you never expect more than say 10 references updated in a push.
* Send a single post-receive request for all lines in the stdin. Not quite as simple, the problem is that once you accept pushes can update large numbers of references - the post becomes unbounded. It could get arbitrarily large.
* Send them in batches, basically free once you've done the second step. A little more inefficient but theres a sort of hard bound on how big each post is and how long each one might take.

I think sending them in batches with a large enough batch size means that in most circumstances it's essentially send them all in one go. I'm not certain what the correct size for that batch is, it could be reasonable to make it 500 but setting a bound means that we know how big it could be.

**Comment by guillep2k** [comment]
From #8540 it looks like >6,000 tags and >14,000 commits are quite a real scenario. Perhaps some feedback from @mansshardt could help us decide a good batch size. One thing to take into account is that long transactions tend to:

* Lock parts of the database.
* Produce dead-locks or similar side effects (e.g. `snapshot too old`) for the same reason.

So, too large a batch size is not a good thing. Also, I think there will be a curve of diminishing returns, meaning that a batch size of 900 will not be any better than 500 (it will probably be worse), and 100 could still be overkill. I believe that a relative small number between 10 and 30 will work wonders.

**Comment by zeripath** [comment]
It would also be helpful if this actually worked though first :stuck_out_tongue_closed_eyes:

**Comment by zeripath** [comment]
OK, so with some more testing the issue is that 200 takes too long for Gitea to process in one fell swoop. If you change the batching to 50 it works - although it appears it takes 15s to process 50 tags  - I've dropped it down to 30. 

That seems rather slow to me but probably is consistent with previous code and not likely to be due to these changes.

**Comment by mansshardt** [comment]
> From #8540 it looks like >6,000 tags and >14,000 commits are quite a real scenario. Perhaps some feedback from @mansshardt could help us decide a good batch size.

@zeripath @guillep2k  I just checked out your recent changes and built again. With this build all releases got created and it's noticeably faster. So 30 seems to be a good batch number.

**Comment by zeripath** [comment]
Excellent. I'm glad that this approach does actually reduce the time. I've never actually tried to send 400 references before so was kind of horrified at how long it took.

Some thoughts:

1. I think it should be possible to prevent a timeout, better get it to predict a reasonable timeout given the amount of data to be sent, on the internal POST too. We could do that as a further PR though. 
2. Clearly the underlying action and notifywatchers functions need more optimization too - I'm a little horrified that 50 tags took 15s to process - surely some of what they're doing can be sped up or moved out of the main goroutine. (Again probably not for this PR unless there's something obvious.)

**Comment by zeripath** [comment]
The git client failing is interesting and I would be interested to know what caused it.

**Comment by mansshardt** [comment]
> The git client failing is interesting and I would be interested to know what caused it.

I'd suspect that the git client doesn't get a proper signal that everything has been transmitted as Gitea is still working on tags/releases. I think the client only gets that signal after Gitea "think's" it's finished. Which is why I got no error yesterday but Gitea stopped after creating only 190 releases. Does that make any sense to you @zeripath 

What should happen here is that Gitea sends the git client some kind of an "OK" after everything got transmitted and should proceed in the background creating releases from tags.

It should also be possible to restart the release creating process in case it fails. But thats a feature request.

**Comment by zeripath** [comment]
Hmm I had put some logging with `fmt.Fprintf(os.Stderr,...)` into the code whilst testing but I couldn't get git to emit it until the end of the push so removed it as it wasn't very helpful. 

That being said the original code never logged so I don't think that could need the logging - especially if it took even longer previously. Is there anything in the Gitea logs? I think something must be erroring somewhere near the end and that's cause.

I suspect I need to stack up the errors rather than just blindly fail when one happens.

**Comment by zeripath** [comment]
Agreed about backgrounding release creation. Most of this stuff should just be entering a queue and not happening on the main goroutine. Errors from creating a release can go in to the release.

**Comment by guillep2k** [comment]
In my experience, `log.Printf` is buffered, but there's a `log.Flush` function as well that helps with that.

I think the client simply timed out waiting for a message. If you add some feedback messages and flush them from time to time, I think the ultimate client timeout could probably be avoided.

For tests, you should be able to easily simulate the delay by aritificially adding sleep calls between operations.

**Comment by zeripath** [comment]
So in the case of the hooks within cmd/hook.go you can't just use log annoyingly - it's not running in the server process. You can log out to stderr and git will display it in the end though but it appears it caches that. Perhaps it's enough though to keep git happy?

**Comment by guillep2k** [comment]
I haven't try it, but testing that should be easy enough by adding artificial delays in the code. Some experimenting (or some Google) will be required to determine what that delay should be to make the client fail.

**Comment by guillep2k** [comment]
@zeripath This should give some hint: https://stackoverflow.com/questions/6458790/is-there-a-way-to-make-git-over-http-timeout

There might be some ssh timeout setting as well.

**Comment by mansshardt** [comment]
> Is there anything in the Gitea logs?

@zeripath I cant't see anything in the logs indicating the error on the git client side.

> I think the client simply timed out waiting for a message.

@guillep2k That's what I think as well.

**Comment by guillep2k** [comment]
[This page](https://confluence.atlassian.com/stashkb/git-ssh-push-timeout-on-large-changes-422020193.html) suggests that git will effectively timeout in ssh operations as well and proposes a fix by changing the timeout configuration.

So, pushing a message from time to time should be an effective solution for long operations like this. Git does that with "counting objects ..." etc., and I suspect it's not just to give the user some feedback but to keep the client alive.

I don't know a thing about the HTTP GIT protocol. How are partial messages sent to the client, with '206 Partial Content' blocks?

File: modules/repofiles/action.go [hunk 1]
```diff
@@ -29,187 +29,209 @@ type CommitRepoActionOptions struct {
...
-		}); err != nil {
-			return fmt.Errorf("PrepareWebhooks: %v", err)
+	if repo != nil {
+		// Change repository empty status and update last updated time.
+		if err := models.UpdateRepository(repo, false); err != nil {
+			return fmt.Errorf("UpdateRepository: %v", err)
 		}
 	}
 
+	if err := models.NotifyWatchers(actions...); err != nil {
```
Comment (zeripath) [inline modules/repofiles/action.go:286]: I wonder if we really need this to happen within the processing goroutine - or whether we could get away with sticking this a in another goroutine.

**Comment by mansshardt** [comment]
@zeripath Just tested with your latest commit:
```
Counting objects: 409817, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (108243/108243), done.
Writing objects: 100% (409817/409817), 1.14 GiB | 28.09 MiB/s, done.
Total 409817 (delta 201401), reused 409812 (delta 201396)
error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
fatal: The remote end hung up unexpectedly
error: error in sideband demultiplexer
Everything up-to-date
```

**Comment by zeripath** [comment]
Damn. Is there any way of getting git to print out the information as it is getting info? I mean the hook is now printing to stderr and we don't see it. There's ways of getting SSH to be more verbose and to get git to be more verbose.

I really don't understand what's happening differently here - it's definitely quicker than the original so why is ssh timing out? (Assuming that's what's happening)

My local tests with 403 tags don't suffer this (at least over http with sqlite). The adjusted hook cmd shouldn't be erroring as far as I can see and we only fail if there's a dB error.

**Comment by guillep2k** [comment]
`fatal: The remote end hung up unexpectedly`

That's no timeout.

**Comment by mansshardt** [comment]
> Damn. Is there any way of getting git to print out the information as it is getting info? I mean the hook is now printing to stderr and we don't see it. There's ways of getting SSH to be more verbose and to get git to be more verbose.
> 
> I really don't understand what's happening differently here - it's definitely quicker than the original so why is ssh timing out? (Assuming that's what's happening)
> 
> My local tests with 403 tags don't suffer this (at least over http with sqlite). The adjusted hook cmd shouldn't be erroring as far as I can see and we only fail if there's a dB error.

@zeripath Just to clarify thins. We're using git over http.

**Comment by guillep2k** [comment]
> 
>

**Comment by guillep2k** [comment]
@mansshardt Do you know the approximate time before it failed? (seconds? minutes? hours?) BTW, an easy way to time an operation in Linux is using `time` before our command:
```
$ time sleep 3

real    0m3.022s
user    0m0.000s
sys     0m0.003s

$ time fgrep -R no-find-string vendor

real    0m2.189s
user    0m0.065s
sys     0m0.162s
```

**Comment by mansshardt** [comment]
@guillep2k Here you go:
```
user@linux:~/repo.git$ time git push --mirror https://gitea.example.org/org/repo.git
Counting objects: 409817, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (108243/108243), done.
Writing objects: 100% (409817/409817), 1.14 GiB | 29.07 MiB/s, done.
Total 409817 (delta 201401), reused 409812 (delta 201396)
error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
fatal: The remote end hung up unexpectedly
error: error in sideband demultiplexer
Everything up-to-date

real	16m42.025s
user	0m38.338s
sys	0m7.839s
```
As mentioned, Gitea continues to create releases.

File: cmd/hook.go [hunk 2]
```diff
@@ -102,14 +104,22 @@ func runHookPreReceive(c *cli.Context) error {
...
 		if strings.HasPrefix(refFullName, git.BranchPrefix) {
 			oldCommitIDs[count] = oldCommitID
 			newCommitIDs[count] = newCommitID
 			refFullNames[count] = refFullName
 			count++
+			fmt.Fprintf(os.Stdout, "*")
+			os.Stdout.Sync()
+
 			if count >= hookBatchSize {
+				fmt.Fprintf(os.Stdout, " Checking %d branches\n", count)
```
Comment (guillep2k) [inline cmd/hook.go:127]: I was about to suggest exactly this to avoid the timeouts! 😄

Comment (guillep2k) [reply cmd/hook.go:127]: Anyway, this message will print after a line of stars and dots, is that what you intended?
```
****...*.*.***.****.*.***.****.***.*.*.*..*** Checking 30 branches
```

Comment (zeripath) [reply cmd/hook.go:127]: Yup. that's intended

Comment (zeripath) [reply cmd/hook.go:127]: if you count the preceding `*` in that line and the lines above there are 30 of them. The * indicates branches

File: models/repo_watch.go [hunk 3]
```diff
@@ -74,66 +74,143 @@ func (repo *Repository) GetWatchers(page int) ([]*User, error) {
...
+				return fmt.Errorf("insert new actioner: %v", err)
+			}
 		}
 
-		act.ID = 0
-		act.UserID = watches[i].UserID
-		act.Repo.Units = nil
+		if len(actions) == 1 {
+			// More efficient to just check the code and not cache
+			for _, watcher := range watchers {
```
Comment (guillep2k) [inline models/repo_watch.go]: I'm not very fond of handling this as a special case here. Looks quite messy; the `range` logic is broken. It's like a big `goto`. 😁

The way I see it, golang is very fast for moving around structures, slices, etc.. Querying the database, on the other hand, is the big bottleneck here. So it's very good that you've grouped the requests when there are many of them, but I don't see the point of handling the single element case separately.

File: models/repo_watch.go [hunk 4]
```diff
@@ -74,66 +74,143 @@ func (repo *Repository) GetWatchers(page int) ([]*User, error) {
...
 
-		switch act.OpType {
-		case ActionCommitRepo, ActionPushTag, ActionDeleteTag, ActionDeleteBranch:
-			if !act.Repo.checkUnitUser(e, act.UserID, false, UnitTypeCode) {
-				continue
+		if repoChanged {
+			permCode = make([]bool, len(watchers))
+			permIssue = make([]bool, len(watchers))
+			permPR = make([]bool, len(watchers))
+			for i, watcher := range watchers {
```
Comment (guillep2k) [inline models/repo_watch.go:217]: If I understand correctly, the last time it goes through this part `repoChanged` might be false, but there will still be some tasks pending.

File: models/repo_watch.go [hunk 5]
```diff
@@ -74,66 +74,143 @@ func (repo *Repository) GetWatchers(page int) ([]*User, error) {
...
+						continue
+					}
+				}
+
+				if _, err = e.InsertOne(act); err != nil {
+					return fmt.Errorf("insert new action: %v", err)
+				}
+			}
+			return nil
+		}
```
Comment (guillep2k) [inline models/repo_watch.go]: If you keep this part of the code, I think a `continue` is required here.

**Review by guillep2k — COMMENTED** [review]
I couldn't finish reading the code, but these are my comments so far.

File: cmd/hook.go [hunk 6]
```diff
@@ -87,29 +104,70 @@ func runHookPreReceive(c *cli.Context) error {
...
+
+		fmt.Fprintf(os.Stdout, " Checking %d branches\n", count)
+		os.Stdout.Sync()
+
+		statusCode, msg := private.HookPreReceive(username, reponame, hookOptions)
+		switch statusCode {
+		case http.StatusInternalServerError:
+			fail("Internal Server Error", msg)
+		case http.StatusForbidden:
+			fail(msg, "")
```
[the remark this answers is not in the document]
Comment (zeripath) [reply cmd/hook.go:169]: I've switched it to default fallthrough.

File: cmd/hook.go [hunk 7]
```diff
@@ -153,36 +221,75 @@ func runHookPostReceive(c *cli.Context) error {
...
+			count = 0
 		}
+	}
+
+	if count == 0 {
+
+		fmt.Fprintf(os.Stdout, "Processed %d references in total\n", total)
+		os.Stdout.Sync()
+
+		return nil
```
[the remark this answers is not in the document]
Comment (zeripath) [reply cmd/hook.go:287]: OK

File: models/repo_watch.go (hunk 4 above)
Comment (zeripath) [reply models/repo_watch.go:217]: Er... I don't understand what you mean.

File: models/repo_watch.go (hunk 3 above)
Comment (zeripath) [reply models/repo_watch.go]: It was about not storing things in memory - not really about speed - but it's fine I'll remove it.

File: models/repo_watch.go (hunk 5 above)
Comment (zeripath) [reply models/repo_watch.go]: len(actions) = 1 therefore it was at the end of the loop and so would have hit return nil at the end of loop in any case.

File: models/repo_watch.go (hunk 4 above)
Comment (zeripath) [reply models/repo_watch.go:217]: This block of code is simply caching the results of the permissions checks - there's no tasks to perform at this point.

line 148 iterates across the watchers and does the tasks - that's not in the `if repoChanged` block.

**Comment by guillep2k** [comment]
Would it be possible to add one or two integration tests that go full-circuit with multiple commits? Preferably generating notifications.

**Comment by oaxiento** [comment]
With Version 1.11.0+dev-169-g577241bc5 I get the following output from git when I migrate a repository with 548 tags:
```
time git push --mirror https://gitea.example.org/org/repo.git
Counting objects: 25199, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (6916/6916), done.
Writing objects: 100% (25199/25199), 94.41 MiB | 31.19 MiB/s, done.
Total 25199 (delta 12485), reused 25199 (delta 12485)
remote: **............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ..............................
remote: ........ Checking 2 branches
remote: Checked 548 references in total
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: .............................. Processing 30 references
remote: ........ Processing 8 references
remote: Processed 548 references in total
remote: 
remote: Create a new pull request for 'master':
remote:   https://gitea.example.org/org/repo/compare/xxx...master
remote: 
To https://gitea.example.org/org/repo.git
 * [new branch]        xxx -> xxx
 * [new branch]        master -> master
 * [new branch]        origin/xxx -> origin/xxx
 * [new tag]           0.0 -> 0.0
 * [new tag]           0.1 -> 0.1
 * [new tag]           0.10 -> 0.10
[...]
 * [new tag]           99 -> 99

real	3m21.681s
user	0m1.249s
sys	0m0.840s
```
So everything looks good now. Thanks @zeripath and @guillep2k for fixing this!

**Comment by zeripath** [comment]
Oh interesting - I was considering abandoning/rewriting this to instead make PushUpdate run over a graceful shuttting down queue. 

If the hacky stdout thing works - then maybe that would be enough.

**Comment by guillep2k** [comment]
> 
> 
> Oh interesting - I was considering abandoning/rewriting this to instead make PushUpdate run over a graceful shuttting down queue.
> 
> If the hacky stdout thing works - then maybe that would be enough.

@zeripath I think it's not that hacky. If you add some tests we can test it in Windows too to cover all the bases.

**Comment by zeripath** [comment]
So it will be difficult to actually create a reasonable test case for this.

The problem with timeouts is dependent on how long PushUpdate takes to run. 

In particular, I suspect that the git count-objects inefficiency is largely responsible for a lot of the timeouts - so although a noddy example with 500 tags and a single commit will show the batching - it's not really going to exactly replicate the problem that @oaxiento (I guess you've changed your username) had with the original large batch size.

I do still think we should be batching our calls to pre- and post-receive, but if we can speed up PushUpdate(s) and other parts so that they actually do their work in a queue then the logging will likely become unnecessary.

I guess we could cross that bridge when we come to it. 

I'll look at resolving the conflicts.

**Comment by guillep2k** [comment]
> 
> 
> So it will be difficult to actually create a reasonable test case for this.
> 
> The problem with timeouts is dependent on how long PushUpdate takes to run.

I just mean a test for correctness (e.g. will it break on Windows or under some unforseen condition?), and to avoid breaking functionality in the future for some regression problem. I agree that a test for performance is at the very least unreliable.

**Comment by oaxiento** [comment]
> @oaxiento (I guess you've changed your username)

That's right :)

**Comment by lunny** [comment]
Please resolve the conflicts.

**Comment by zeripath** [comment]
Rebased on the current master to fix conflicts.

It's probable that I need to fix the notifier to work on a number of refs rather than just send one. I will have a think.

File: routers/private/hook.go [hunk 8]
```diff
@@ -45,206 +34,258 @@ func HookPreReceive(ctx *macaron.Context) {
...
+						},
+					})
+					return
+				}
+				if repo.OwnerName == "" {
+					repo.OwnerName = ownerName
+				}
+
+				pullRequestAllowed := repo.AllowsPulls()
+				if !pullRequestAllowed {
```
Comment (guillep2k) [inline routers/private/hook.go]: This variable doesn't seem to be required (`repo.AllowPulls()` can be invoked in the if).

**Review by guillep2k — APPROVED** [review]
I didn't find any obvious errors but I can't claim that I undestood everything I've read. LGTM, AFAICT (don't you love acronyms?) 😄

File: routers/private/hook.go [hunk 9]
```diff
@@ -45,206 +34,258 @@ func HookPreReceive(ctx *macaron.Context) {
...
+	var repo *models.Repository
+	updates := make([]models.PushUpdateOptions, 0, len(opts.OldCommitIDs))
+
+	for i := range opts.OldCommitIDs {
+		refFullName := opts.RefFullNames[i]
+		branch := opts.RefFullNames[i]
+		if strings.HasPrefix(branch, git.BranchPrefix) {
+			branch = strings.TrimPrefix(branch, git.BranchPrefix)
+		} else {
+			branch = strings.TrimPrefix(branch, git.TagPrefix)
```
[the remark this answers is not in the document]
Comment (zeripath) [reply routers/private/hook.go:144]: This bit if code probably predates it - I will take a look and see if we can use that instead.

**Comment by lunny** [comment]
Please resolve conflicts.

File: modules/repofiles/action.go (hunk 1 above)
Comment (lunny) [reply modules/repofiles/action.go:286]: All notification could be a seperate goroutine.

**Comment by lunny** [comment]
The default branch is the first branch but not `master` when push to a new empty repository. Maybe we could change it when we found `master` and if this is the first push of this repository.

File: modules/repofiles/action.go (hunk 1 above)
Comment (zeripath) [reply modules/repofiles/action.go:286]: See #8874

**Comment by 6543** [comment]
I find the PR title a litle bit misleading

**Comment by zeripath** [comment]
@lunny Done

File: routers/private/hook.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (zeripath) [reply routers/private/hook.go:144]: Done

File: routers/private/hook.go (hunk 8 above)
Comment (zeripath) [reply routers/private/hook.go]: Done

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
Ping lgtm

File: cmd/hook.go (hunk 2 above)
Comment (rain0r) [reply cmd/hook.go:127]: Is it possible to disable these remote-messages?

Comment (lunny) [reply cmd/hook.go:127]: Please fire a new issue.
