### PR TITLE
Fix incorrect default branch when adopt a repository

### LINKED ISSUE #30521: import from gogs /github.
### Description

import from gogs/github will faill unless you set the in app.ini under [repository] the  DEFAULT_BRANCH to master

to reproduce: 

add a repository to a user  (gitea/data/gitea-repositories/user/
go in gui to user settingss -> Reposistories -> choose addapt files to import reposistory

the branch button on the imported repository  will give a error 404

now set the in app.ini under [repository] the  DEFAULT_BRANCH = master,  restart gittea and try to import another one
or remove the imported one. 

the branch button will work as expected

Don't forget to push the button  "Delete any repositories that are missing their Git files" before importing the same repository again.

maby make a note of this the docs?

### Gitea Version

1.221.11

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.25.1

### Operating System

ubuntu/linux

### How are you running Gitea?

using the lastest binary from gitea.com

### Database

None

### PR DESCRIPTION
**Pull request by yp05327**
Fix #30521

we should sync branches first, then detect default branch, or `git_model.FindBranchNames` will always return empty list, and the detection will be wrong.

### CODE REVIEW

File: services/repository/adopt.go [hunk 1]
```diff
@@ -111,7 +107,7 @@ func AdoptRepository(ctx context.Context, doer, u *user_model.User, opts CreateR
 	return repo, nil
 }
 
-func adoptRepository(ctx context.Context, repoPath string, repo *repo_model.Repository, defaultBranch string) (err error) {
+func adoptRepository(ctx context.Context, repoPath string, repo *repo_model.Repository, defaultBranch string, doer *user_model.User) (err error) {
```
Comment (lunny) [inline services/repository/adopt.go]: Looks like `doer` hasn't been used?

File: services/repository/adopt.go [hunk 2]
```diff
@@ -36,10 +36,6 @@ func AdoptRepository(ctx context.Context, doer, u *user_model.User, opts CreateR
 		}
 	}
 
-	if len(opts.DefaultBranch) == 0 {
```
Comment (lunny) [inline services/repository/adopt.go:39]: ~Why remove these lines?~

**Review by wxiaoguang — APPROVED** [review]

File: services/repository/adopt.go (hunk 1 above)
Comment (yp05327) [reply services/repository/adopt.go]: https://github.com/go-gitea/gitea/pull/30912/commits/03b37ffc017c809e16fd5c14394fe3e38b376177

File: services/repository/adopt.go [hunk 3]
```diff
@@ -143,6 +139,21 @@ func adoptRepository(ctx context.Context, repoPath string, repo *repo_model.Repo
 		}
 	}
 
+	// Don't bother looking this repo in the context it won't be there
```
Comment (lunny) [inline services/repository/adopt.go:142]: The codes are duplicated with `adoptRepository` added in #30878

File: services/repository/adopt.go (hunk 2 above)
Comment (yp05327) [reply services/repository/adopt.go:39]: This will be done here
image

File: services/repository/adopt.go (hunk 3 above)
Comment (yp05327) [reply services/repository/adopt.go:142]: Sorry, I don't understand your meanings. 🤔

**Review by lunny — APPROVED** [review]
