### PR TITLE
Fix non-ASCII search on database 

### LINKED ISSUE #18429: Search to accents not working with sqlite
### Gitea Version

1.15.10

### Git Version

git version 2.30.2

### Operating System

Alpine Linux 3.13.7

### How are you running Gitea?

Official docker image deployed with docker-compose:

```bash
$ cat docker-compose.yml
version: "3.3"
services:
  server:
    restart: always
    image: gitea/gitea:${GITEA_VERSION}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - ${DATA}:/data
      - ${ENTRYPOINT}:/usr/bin/entrypoint
    ports:
      - "${HTTP_PORT}:3000"
      - "${SSH_PORT}:22"
```
```
$ cat .env
GITEA_VERSION=1.15.10
HTTP_PORT=3000
SSH_PORT=2222
DATA=./data
ENTRYPOINT=./custom/entrypoint
```

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Description

I use a custom indexer setting to search for word fragments as well.
```bash
bash-5.1# tail -2 /data/gitea/conf/app.ini
[indexer]
ISSUE_INDEXER_TYPE = db
```
But unfortunately, accented search doesn't work without this option. (neither in the title nor in the content)

I have another gitea system installed with a postgesql database engine, the accented search works correctly there, so i think sqlite is the cause of the malfunction.

Is there any sqlite specific language option I should set?

### Screenshots

Without search:
---
image

With accent search:
---
image

With accent free search:
---
image

### PR DESCRIPTION
**Pull request by Gusted**
- Use `ToASCIIUpper` for SQLite database on issues search, this because `UPPER(x)` on SQLite only transforms ASCII letters.
- Resolves #18429

### CODE REVIEW

File: modules/strings/strings.go [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+
+package strings
+
+import (
+	"strings"
+	"unicode/utf8"
+)
+
+// ToASCIIUpper returns s with all ASCII letters mapped to their upper case.
+func ToASCIIUpper(s string) string {
```
Comment (silverwind) [inline modules/strings/strings.go]: Nothing in golang's stdlib for this?

Comment (Gusted) [reply modules/strings/strings.go]: Unfortunately not, the closes things is ToUpperSpecial, but the struct that is passed is more or less magic to me and has a unexported field. This function is a modification from `ToUpper` with the same test cases.

**Review by silverwind — APPROVED** [review]

**Comment by wxiaoguang** [comment]
It's fine to me and I have no objection.

File: modules/strings/strings.go [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+		c := s[i]
+		if c >= utf8.RuneSelf {
+			isASCII = false
+			break
+		}
+		hasLower = hasLower || ('a' <= c && c <= 'z')
+	}
+
+	// Optimize for ASCII-only strings.
+	if isASCII {
```
Comment (wxiaoguang) [inline modules/strings/strings.go]: IIRC, UTF-8 is ASCII-safe, so we could do `if 'a' <= c && c <= 'z' { c -= 'a' - 'A' }` on every byte safely directly.

Comment (Gusted) [reply modules/strings/strings.go]: Yes, we could de-duplicate but the overhead from utf8.Decode is noticeable.

Comment (wxiaoguang) [reply modules/strings/strings.go]: We do not need utf8.Decode actually. We can just do `if 'a' <= c && c <= 'z' { c -= 'a' - 'A' } ` for every byte, it's fastest.

I believe the code also pass the test cases:

```go
func ToUpperASCII(s string) string {
    b := []byte(s)
    for i, c := range b {
        if 'a' <= c && c <= 'z' { b[i] -= 'a' - 'A' }
    }
    return string(b)
}
```

Comment (wxiaoguang) [reply modules/strings/strings.go]: And maybe we can just put the code to `modules/util` package. The customized `strings` package conflicts with official `strings` package, alias is a little annoying.

Comment (Gusted) [reply modules/strings/strings.go]: We might need a new test-case then, because that code will not work on strings with certain utf8 characters, those characters can be made out of multiple bytes, whereby one of those bytes could pass the `'a' <= c && c <= 'z'` but they shouldn't.

Comment (wxiaoguang) [reply modules/strings/strings.go]: > We might need a new test-case then, because that code will not work on strings with certain utf8 characters, those characters can be made out of multiple bytes, whereby one of those bytes could pass the `'a' <= c && c <= 'z'` but they shouldn't.

It does work. One goal of UTF-8 design is: never break ASCII string functions. So it's safe to do it.

https://en.wikipedia.org/wiki/UTF-8 : Since **ASCII bytes do not occur when encoding non-ASCII code points into UTF-8**, UTF-8 is safe to use within most programming and document languages that interpret certain ASCII characters in a special way

Comment (wxiaoguang) [reply modules/strings/strings.go]: From the table, we can see that 'a' to 'z' are not used by UTF-8 multi-byte encoding

image

**Review by wxiaoguang — APPROVED** [review]
LGTM. Also hope more people to take a look at this solution. We can keep this PR open for a few more days. If nothing more to do, then we can merge it.

**Comment by Gusted** [comment]
> LGTM. Also hope more people to take a look at this solution. We can keep this PR open for a few more days. If nothing more to do, then we can merge it.

Yeah, this solution is "hacky" to be more inline with the usage of Sqlite... A problem is that, this isn't the only usage of `UPPER(xxx)`, just to happen to be the one noticed by the issue. Best-case scenario is that we can define [a collation](https://sqlite.org/c3ref/create_collation.html) trough XORM which will ensure that accents like these are properly covered.

**Review by wxiaoguang — APPROVED** [review]
