### PR TITLE
Fix initial commit page & binary munching problem

### LINKED ISSUE #13248: Diffs are rendered incompletely
- Gitea version (or commit ref): 1.12.5+25-g3dc7f2839 (Codeberg.org)
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
    - Commit that contains one PNG file and two Markdown files; only one of the two Markdown files is rendered: https://try.gitea.io/knut/incomplete-diff/commit/eb853fee9565e9d2d71dfb5f28a37a825a15feed
    - PR that shows the same effect on both the Commits and Changed Files tabs: https://try.gitea.io/knut/incomplete-diff/pulls/1
  - [ ] No

Parallel discussion at Codeberg: https://codeberg.org/Codeberg/Community/issues/313

## Description
Hi everyone!

There seems to be a bug with the rendering of diffs in Gitea. It seems to me that whenever a diff contains an image, the diff is only rendered up to that image and all other files will not be rendered, although present in the commit that is to be displayed.

This can lead to code reviews being prevented, due to maintainers being unable to see the sourcecode (for example: https://codeberg.org/Codeberg/Documentation/pulls/99).

## Screenshots
screenshot-gitea

### PR DESCRIPTION
**Pull request by zeripath**
This PR fixes two issues:

* Missing diff following binary files

There was a missing check to break out of the current file loop in ParsePatch

Fix #13248 

* 404 Errors on viewing diff for parentless commits

Unfortunately as a result of properly fixing ParsePatch the hack that
used git show <initial_commit_id> to get the diff for this failed.

This PR fixes this using the "super-secret" empty tree ref to make the
diff against.

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf — COMMENTED** [review]
this works for me.

File: services/gitdiff/gitdiff.go [hunk 1]
```diff
@@ -854,7 +856,13 @@ func GetDiffRangeWithWhitespaceBehavior(repoPath, beforeCommitID, afterCommitID
 	defer cancel()
 	var cmd *exec.Cmd
 	if (len(beforeCommitID) == 0 || beforeCommitID == git.EmptySHA) && commit.ParentCount() == 0 {
-		cmd = exec.CommandContext(ctx, git.GitExecutable, "show", afterCommitID)
+		diffArgs := []string{"diff", "--src-prefix=\\a/", "--dst-prefix=\\b/", "-M"}
+		if len(whitespaceBehavior) != 0 {
+			diffArgs = append(diffArgs, whitespaceBehavior)
+		}
+		diffArgs = append(diffArgs, "4b825dc642cb6eb9a060e54bf8d69288fbee4904")
```
Comment (lafriks) [inline services/gitdiff/gitdiff.go:860]: This probably should be beforeCommitID?

Comment (zeripath) [reply services/gitdiff/gitdiff.go:860]: Nope. That is the beforecommitid in this case

The commit has no parent so we use the magic empty tree ref.

Believe it or not this is what git uses internally to generate the "diff" on the git show in cases where the commit has no parents

Comment (zeripath) [reply services/gitdiff/gitdiff.go:860]: We can't set this as the beforecommitid as it breaks other things lower down in the function.

Comment (6543) [inline services/gitdiff/gitdiff.go:860]: what is `4b825dc642cb6eb9a060e54bf8d69288fbee4904` for ?

**Review by mrsdizzie — APPROVED** [review]

File: services/gitdiff/gitdiff.go (hunk 1 above)
Comment (zeripath) [reply services/gitdiff/gitdiff.go:860]: the "super-secret" empty tree ref

Comment (6543) [reply services/gitdiff/gitdiff.go:860]: I already guessed it is something like this, but i thin this schould be eiter a const or get a comment ... since others while reading this code will have this question too

Comment (6543) [reply services/gitdiff/gitdiff.go:860]:
```suggestion
		// append empty tree ref
		diffArgs = append(diffArgs, "4b825dc642cb6eb9a060e54bf8d69288fbee4904")
```

**Review by 6543 — APPROVED** [review]

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
sorry about that ^, will not reference PRs in this manner anymore, unless necessary ofc 🚀

**Comment by techknowlogick** [comment]
please send backports :)
