### PR TITLE
Fix SecToTime edge-cases

### LINKED ISSUE #20589: Incorrect handling of durations in SecToTime()
### Description

Pull request #18863 introduced [the following code][code]

```go
years := duration / (3600 * 24 * 7 * 4 * 12)
months := (duration / (3600 * 24 * 30)) % 12
weeks := (duration / (3600 * 24 * 7)) % 4
days := (duration / (3600 * 24)) % 7
```

This is wrong for a couple of reasons:

1. the week count reverts to zero (because of the modulus operation) after 4 weeks, which is not quite the same as a month

2. these “years” are 336 days long, which is about 11 months

The consequence is that this function displays:

* a duration of 340 days (about 11.2 months) as “1 year 11 months”

* a duration of 29 days as “1 day”

* a duration of 28 days as the empty string.

See the attached screenshot for the effect of this bug on the display of tracked time.

I suggest to instead use something along these lines:

```go
years := (duration / 86400) / 365
months := (duration / 86400 - years * 365)  / 30
weeks := (duration / 86400 - years * 365 - month * 30) / 7
days := duration / 86400 - years * 365 - month * 30 - weeks * 7
```

I am not submitting a pull request because I have zero experience with the Go programming language.

[code]: ../blob/v1.17.0/modules/util/sec_to_time.go#L21-L24

### Gitea Version

1.18.0+dev-196-ge56005f90

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

time_tracker  
Screenshot from this [test issue](https://try.gitea.io/edgar/test-repo/issues/2).

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

using https://try.gitea.io/

### Database

_No response_

### PR DESCRIPTION
**Pull request by Gusted**
- Currently there are edge-cases where the code fails to produce the correct results, this is mainly due to the misusage of the modulo operator. Well this could be fixed, it's better to use a more performant way and simply distract the previous number's cost to calculate the variables.
- Resolves #20589

### CODE REVIEW

File: modules/util/sec_to_time_test.go [hunk 1]
```diff
@@ -11,10 +11,15 @@ import (
 )
 
 func TestSecToTime(t *testing.T) {
-	assert.Equal(t, SecToTime(66), "1 minute 6 seconds")
-	assert.Equal(t, SecToTime(52410), "14 hours 33 minutes")
-	assert.Equal(t, SecToTime(563418), "6 days 12 hours")
-	assert.Equal(t, SecToTime(1563418), "2 weeks 4 days")
-	assert.Equal(t, SecToTime(3937125), "1 month 2 weeks")
-	assert.Equal(t, SecToTime(45677465), "1 year 5 months")
+	assert.Equal(t, "1 minute 6 seconds", SecToTime(66))
```
Comment (Gusted) [inline modules/util/sec_to_time_test.go]: Expected value should always be the first argument.

File: modules/util/sec_to_time.go [hunk 2]
```diff
@@ -16,12 +16,24 @@ import (
...
+	// The following three variables are calculated with taking
+	// into account the previous calculated variables, this avoids
+	// pitfalls when using remainders. As that could lead to incorrect
+	// results when the calculated number equals the quotient number.
+	months := (duration/86400 - years*365) / 30
+	weeks := (duration/86400 - years*365 - months*30) / 7
+	days := duration/86400 - years*365 - months*30 - weeks*7
+
+	// The following three variables are calculated without depending
+	// on the previous calculated variables.
```
Comment (Gusted) [inline modules/util/sec_to_time.go:36]: These are more or less stable by definition, so to avoid multiplication by huge numbers, leave it as-is.

**Review by wxiaoguang — APPROVED** [review]

File: modules/util/sec_to_time.go (hunk 2 above)
Comment (edgar-bonet) [reply modules/util/sec_to_time.go:36]: There is still an edge case, although it is not handled as badly as the ones that are being fixed here:

* 364 days are displayed as “12 months”
* 365 days are displayed as “1 year”

Not sure it is serious enough to worry about...

Comment (Gusted) [reply modules/util/sec_to_time.go:36]: 364 could be fixed by assuming a month is 31 days. As
```
365 / 30 -> ~12.16666666666666666667
364 / 30 -> ~11.77419354838709677419
```

File: modules/util/sec_to_time_test.go (hunk 1 above)
Comment (delvh) [inline modules/util/sec_to_time_test.go]:
```suggestion
	second := 1
	minute := 60 * second
	hour := 60 * minute
	day := 24 * hour
	year := 365 * day
	
	assert.Equal(t, "1 minute 6 seconds", SecToTime(minute + 6 * second))
```

File: modules/util/sec_to_time_test.go [hunk 3]
```diff
@@ -11,10 +11,15 @@ import (
...
+	assert.Equal(t, "1 hour", SecToTime(3600))
+	assert.Equal(t, "1 hour", SecToTime(3601))
+	assert.Equal(t, "14 hours 33 minutes", SecToTime(52410))
+	assert.Equal(t, "6 days 12 hours", SecToTime(563418))
+	assert.Equal(t, "2 weeks 4 days", SecToTime(1563418))
+	assert.Equal(t, "4 weeks", SecToTime(2419200))
+	assert.Equal(t, "4 weeks 1 day", SecToTime(2505600))
+	assert.Equal(t, "1 month 2 weeks", SecToTime(3937125))
+	assert.Equal(t, "11 months 1 week", SecToTime(29376000))
+	assert.Equal(t, "1 year 5 months", SecToTime(45677465))
```
Comment (delvh) [inline modules/util/sec_to_time_test.go]:
```suggestion
	assert.Equal(t, "1 hour", SecToTime(hour))
	assert.Equal(t, "1 hour", SecToTime(hour + second))
	assert.Equal(t, "14 hours 33 minutes", SecToTime(14 * hour + 33 * minute + 30 * second))
	assert.Equal(t, "6 days 12 hours", SecToTime(6 * day + 12 * hour + 30 * minute + 18 * second))
	assert.Equal(t, "2 weeks 4 days", SecToTime((2 * 7 + 4) * day + 2 * hour + 16 * minute + 58 * second))
	assert.Equal(t, "4 weeks", SecToTime(4 * 7 * day))
	assert.Equal(t, "4 weeks 1 day", SecToTime((4 * 7 + 1) * day))
	assert.Equal(t, "1 month 2 weeks", SecToTime((6 * 7 + 3) * day + 13 * hour + 38 * minute + 45 * second))
	assert.Equal(t, "11 months 1 week", SecToTime(year - 25 * day))
	assert.Equal(t, "1 year 5 months", SecToTime(year + 163 * day + 10 * hour + 11 * minute + 5 * second))
```

File: modules/util/sec_to_time.go [hunk 4]
```diff
@@ -16,12 +16,24 @@ import (
...
-	days := (duration / (3600 * 24)) % 7
+	years := (duration / 86400) / 365
+
+	// The following three variables are calculated with taking
+	// into account the previous calculated variables, this avoids
+	// pitfalls when using remainders. As that could lead to incorrect
+	// results when the calculated number equals the quotient number.
+	months := (duration/86400 - years*365) / 30
+	weeks := (duration/86400 - years*365 - months*30) / 7
+	days := duration/86400 - years*365 - months*30 - weeks*7
```
Comment (delvh) [inline modules/util/sec_to_time.go]:
```suggestion

	// The following four variables are calculated by taking
	// into account the previously calculated variables, this avoids
	// pitfalls when using remainders. As that could lead to incorrect
	// results when the calculated number equals the quotient number.
	remainingDays := duration / (60 * 60 * 24)
	years := remainingDays / 365
	remainingDays -= years * 365
	months := remainingDays / 30
	remainingDays -= months * 30
	weeks := remainingDays / 7
	remainingDays -= weeks * 7
	days := remainingDays
```

File: modules/util/sec_to_time.go [hunk 5]
```diff
@@ -16,12 +16,24 @@ import (
 // 1563418		-> 2 weeks 4 days
 // 3937125s     -> 1 month 2 weeks
 // 45677465s	-> 1 year 6 months
+//
+// Magic numbers:
+// 3600 = 60 * 60 (amount of seconds in a hour)
+// 86400 = 60 * 60 * 24 (amount of seconds in a day)
```
Comment (delvh) [inline modules/util/sec_to_time.go]:
```suggestion
```

File: modules/util/sec_to_time.go [hunk 6]
```diff
@@ -18,10 +18,22 @@ import (
...
+
+	// The following four variables are calculated by taking
+	// into account the previously calculated variables, this avoids
+	// pitfalls when using remainders. As that could lead to incorrect
+	// results when the calculated number equals the quotient number.
+	remainingDays := duration / (60 * 60 * 24)
+	years := remainingDays / 365
+	remainingDays -= years * 365
+	months := remainingDays / 30
+	remainingDays -= months * 30
```
Comment (edgar-bonet) [inline modules/util/sec_to_time.go]: We could get the correct _average_ month length like this:

```suggestion
	months := remainingDays * 12 / 365
	remainingDays -= months * 365 / 12
```

This would solve the 364-day issue.

Comment (delvh) [reply modules/util/sec_to_time.go]: I'm fine both with the current and the proposed approach.

**Review by delvh — APPROVED** [review]

**Comment by edgar-bonet** [comment]
It appears that the following test failed in modules/util/sec\_to\_time\_test.go:

```go
assert.Equal(t, "11 months 1 week", SecToTime(year-25*day))
```

This is because:

* `year-25*day` is 340 days
* 11 months is `11*365/12` = 334 days

thus, `year-25*day` is 11 months and 6 days, not quite 11 months and one week.

**Comment by delvh** [comment]
I mean, now it's at least easy to adapt the tests.
What would be preferred? Changing the expectation to `11 months`, or subtracting `24*day` instead?

**Comment by Gusted** [comment]
> I mean, now it's at least easy to adapt the tests.
> What would be preferred? Changing the expectation to `11 months`, or subtracting `24*day` instead?

Given the previous refactor new behavior, it should only display months + weeks in this case. Which means the `11 months` is technically the correct one in this case. I'll adjust the code

**Review by delvh — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]
