### PR TITLE
Fix incorrect divergence cache after switching default branch

### LINKED ISSUE #34369: Branches still compare against previous default branch after switch
#### Steps to reproduce

1. **Setup Test Repository**
   - Locally create branches:
     - `b1` (default) - 1 unique commit
     - `b2` - 2 unique commits
     - `b3` - 3 unique commits
       (All branches share the same base commit)
   - Push all branches to https://gitea.com/GWDx/bug-branch-divergence and verify `b1` is the remote default branch
2. **Initial Verification**
   Check branch divergence at: https://gitea.com/GWDx/bug-branch-divergence/branches
3. **Change Default Branch**
   Navigate to repository settings: https://gitea.com/GWDx/bug-branch-divergence/settings/branches
   Switch default branch to `b2`
4. **Verify Bug**
   Re-check branch comparisons at: https://gitea.com/GWDx/bug-branch-divergence/branches

#### Results

**Step 2**: With `b1` as default branch, all branch comparisons work as expected.

Image

**Step 4**: After switching default branch to `b2`,

- `b1` correctly compares against `b2` (new default)
- `b3` still incorrectly compares against `b1` (old default)

Image

#### Expected Behavior

- `b3` should calculate divergence against `b2` (current default)

### Gitea Version

1.23.7

### Can you reproduce the bug on the Gitea demo site?

Not yet. When executing Step 2, Gitea demo site seems down, returning HTTP 500.

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.39.5

### Operating System

Debian bookworm 6.1.0-34-amd64

### How are you running Gitea?

I have validated this issue across multiple deployment methods:

- Official Download
- Build from source
- Gitea Cloud Instance: Reproduced on https://gitea.com

### Database

SQLite

### PR DESCRIPTION
**Pull request by GWDx**
Issue: After switching the default branch, other branches are still compared against the old default branch due to outdated divergence cache.

Change: Clear the divergence cache in SetRepoDefaultBranch to ensure correct comparisons against the new default branch.

Fixes #34369

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
It's better to have a test.

**Comment by GWDx** [comment]
I’ve added an integration test to verify that branch divergence counts are correctly recalculated after switching the default branch.

File: tests/integration/change_default_branch_test.go [hunk 1]
```diff
@@ -38,3 +42,96 @@ func TestChangeDefaultBranch(t *testing.T) {
...
 	session.MakeRequest(t, req, http.StatusNotFound)
 }
+
+func checkDivergence(t *testing.T, session *TestSession, branchesURL, expectedDefaultBranch string, expectedBranchToDivergence map[string]git.DivergeObject) {
+	req := NewRequest(t, "GET", branchesURL)
+	resp := session.MakeRequest(t, req, http.StatusOK)
+
+	htmlDoc := NewHTMLParser(t, resp.Body)
+
+	branchNodes := htmlDoc.doc.Find(".gt-ellipsis").Nodes
```
Comment (silverwind) [inline tests/integration/change_default_branch_test.go]: This class selector is too unspecific. Can you maybe add a new unique class to the elements in question and select on that?

Comment (GWDx) [reply tests/integration/change_default_branch_test.go]: I added a new `.branch-name` class to branch name elements in the branch list template, and updated integration test accordingly.

Comment (yp05327) [reply tests/integration/change_default_branch_test.go]: > I added a new `.branch-name` class to branch name elements in the branch list template, and updated integration test accordingly.

I suggest left a comment like something that `branch-name` is used for tests, do not remove.

**Review by yp05327 — APPROVED** [review]

File: tests/integration/change_default_branch_test.go (hunk 1 above)
Comment (silverwind) [reply tests/integration/change_default_branch_test.go]: > I suggest left a comment like something that branch-name is used for tests, do not remove.

Not strictly needed imho, but nice to have because one will notice anyways when the test starts to fail.

**Review by silverwind — APPROVED** [review]
