### PR TITLE
Full-file syntax highlighting for diff pages

### LINKED ISSUE #21970: PHP Syntax Highlighting does not working in review mode
### Description

Hello
PHP syntax highlighting does not working in Code-Review mode.
But i see that its works for TypeScript, Kotlin etc.

Current example on try.gitea.io:
https://try.gitea.io/den/test/pulls/1/files

### Gitea Version

1.19.0+dev-135-gf047ee0a4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Windows 10 Pro

### Browser Version

Chrome 107

### LINKED ISSUE #33358: Syntax highlighting should be full-file only
### Description

Diff lines are passed individually line-by-line to chroma, which its a massive source of highlighting bugs because the highlighter needs to see the whole file to highlight correctly. We should instead:

- Highlight both the old and new files individually, store the resulting HTML in Maps of (lineText, lineHTML).
- For each content line in the diff, look into the maps and if there is an exact match, replace the line with the highlighted HTML line.

This assumes chroma does not output HTML tags that span multiple lines, but I think this may already be the case.

### PR DESCRIPTION
**Pull request by dfirebaugh**
Fix #33358, fix #21970

This adds a step in the `GitDiff` that does syntax highlighting for the entire file and then only references lines from that syntax highlighted code.  This allows things like multi-line comments to be syntax highlighted correctly.

image (4)
image (3)
image (2)
image (1)
image

### CODE REVIEW

File: services/gitdiff/highlightdiff_test.go [hunk 1]
```diff
@@ -20,11 +19,13 @@ func TestDiffWithHighlight(t *testing.T) {
 		"		run(db)\n",
 	)
 
-	expected := `		<span class="n">run</span><span class="o">(</span><span class="removed-code"><span class="k">&#39;</span><span class="o">&lt;</span><span class="o">&gt;</span><span class="k">&#39;</span></span><span class="o">)</span>`
+	expected := `		run(<span class="removed-code">'<>'</span>)
```
Comment (wxiaoguang) [inline services/gitdiff/highlightdiff_test.go]: It can't be right. By your approach, there will be XSS. Something like `<script>xxx</script>` will be rendered to the user's page.

**Review by wxiaoguang — DISMISSED** [review]
~~HTML encoding should be correctly handled, for example: `<>`~~

See new comment below https://github.com/go-gitea/gitea/pull/33766#issuecomment-2692668999

File: services/gitdiff/highlightdiff_test.go (hunk 1 above)
Comment (dfirebaugh) [reply services/gitdiff/highlightdiff_test.go]: Hey, thanks for reviewing.
I didn't change how html is encoded.

`<span class="removed-code">'<>'</span>` should render something like  `'<>'` to the page.

If I'm misunderstanding something, my apologies.


Screenshot from 2025-03-02 00-33-03
image

Comment (wxiaoguang) [reply services/gitdiff/highlightdiff_test.go]: In your test result:

```
"run(<span class="removed-code">'<>'</span>)"
```

There are 3 `<` chars. The first one is `<span` (added by the render), the second one is the one in `'<>'`

The old logic does encode the second one to `&lt;`, which is necessary to render it to browser.

But in you case, the second one is still `<`, then it will be used as "HTML tag", but not rendered as "code content"

I do not see why it could be right.

Comment (dfirebaugh) [reply services/gitdiff/highlightdiff_test.go]: oh, it's because it's no longer calling `highlight.Code(filename, language, codeA)` here. So, it's not actually "rendering" the html here.

**Comment by wxiaoguang** [comment]
It also generated incorrect diff results (actually the "diff" content is corrupted)

Old:

image

Yours:

image

File: services/gitdiff/highlightdiff_test.go (hunk 1 above)
Comment (wxiaoguang) [reply services/gitdiff/highlightdiff_test.go]: It's not really related to "rendering" or not. Let's take a simpler example below:

You made this output:

```
`a <span class="removed-code"><</span> b`
```

What "kind" of the string it is?

* If it is a HTML string, then it is invalid, the `<` shouldn't appear in HTML content. It must be encoded to `&lt;`
* If it is not a HTML string, then `<span ...>` wouldn't be rendered as HTML but just be displayed as-is, actually it is not the case because this tag is for highlighting the code as removed.

I do not see it could be right.

Comment (wxiaoguang) [reply services/gitdiff/highlightdiff_test.go]: If you think your approach is right but the tests do not work for your approach, please design correct tests, and use the existing test data to verify that the logic overall is right.

-> https://github.com/go-gitea/gitea/pull/33766#issuecomment-2692668999

**Comment by wxiaoguang** [comment]
Thank you very much. I can understand most of changes now. The idea is feasible, while there are still some details:

1. Some of the old tests should be kept, for example: `diff.Text = "OC"`, I do not see why it should be removed. It is used to make sure the `recoverOneDiff` works correctly.
1. Some of the old tests do not fit the new code:
    * If a test doesn't fit (the case won't happen), feel free to remove it.
    * New tests should cover the new behavior since the behavior of `diffWithHighlight` has changed, it only accepts HTML content
1. Some variable types should be changed to match the new behavior, use `template.HTML`
1. Some edge cases, for example, what if a file is large (Mega-bytes)? It would bloat the Gitea's memory and make it OOM.
    * I think we need to have a limit, if a file is too large, fall back to the "block" diff but not the "full file" diff.

**Comment by silverwind** [comment]
> I think we need to have a limit, if a file is too large, fall back to the "hunk block" diff but not the "full file" diff.

Sounds acceptable to have a certain byte limit above which to fall back to hunk-based diff. Maybe 5MB or so.

**Comment by dfirebaugh** [comment]
Thank you,

since we fall back to hunk-based syntax highlighting (in some cases), all of the pre-existing tests should remain.  I've reverted those to the original tests with the original test data.

for the file limit, is it enough to check line count? or should it check actual MB?
I (perhaps naively) implemented a line count check based on a variable in settings.

I also implemented some of your other comments.

It may still need more.  I'm out of time for today, but will revisit if you have more thoughts/comments.

**Comment by silverwind** [comment]
> for the file limit, is it enough to check line count? or should it check actual MB?
> I (perhaps naively) implemented a line count check based on a variable in settings.

Both are fine I guess, whatever is easier. For line count, maybe default to a value like 100k lines.

**Comment by delvh** [comment]
Well… the line count doesn't prevent the issue, i.e. if someone uploads a list of large minified JSON objects with each object occupying one line.
Also, `os.Stat`ing is probably simpler than implementing an entire line-based checker.
So, my preference would be the size instead of line based check

**Comment by wxiaoguang** [comment]
Managed to make some changes (haven't started the test case fixing):

1. Since `GetBlobLineCount` already reads the whole file content, we could simply reuse it to get "limited content"
    * only do entire-file highlighting when the file is not that large
2. Rewrite `GetComputedInlineDiffFor` to make it simpler and easier to maintain
3. Respect `DisableDiffHighlight`
4. Fallback to per-line-highlighting when the "limited content buffer" exceeds max limit.

Does it work as expected and/or look good to you?

**Comment by wxiaoguang** [comment]
After reading "GitDiff" related code, I found that the legacy code is totally a mess ...... various patches were added again and again (for example: FileOnly vs GetPullDiffStats, GetPullRequestFiles vs ToCommit). I think we need to refactor the "diff" related code before adding more patches to it.

**Comment by warasilapm** [comment]
> After reading "GitDiff" related code, I found that the legacy code is totally a mess ...... various patches were added again and again (for example: FileOnly vs GetPullDiffStats, GetPullRequestFiles vs ToCommit). I think we need to refactor the "diff" related code before adding more patches to it.

So... no syntax highlighting fix in the near future then? That'd be pretty disappointing.

**Comment by wxiaoguang** [comment]
> So... no syntax highlighting fix in the near future then? That'd be pretty disappointing.

You could try to blame the related code and read the history, there are various patches to the GetDiff related function, some of them are "performance" related.

Undoubtedly, this change will significantly affects performance (see some FIXMEs I added, I do not know how much the affect would be at the moment)

It would be quite disappointing too when the performance regression occurs and affects a lot of users.

If it could be proven that there would be no performance regression, or if there would be someone who could fix the performance regression in first them when users complain, then we can merge it now. But if no, I think we'd better to be careful for this case.

**Comment by wxiaoguang** [comment]
The first refactoring PR:  Refactor git diff #33810

**Comment by warasilapm** [comment]
> It would be quite disappointing too when the performance regression occurs and affects a lot of users.

Hey, you know - fair enough.

**Comment by wxiaoguang** [comment]
Most problems should have been resolved.

**Review by wxiaoguang — APPROVED** [review]

File: services/gitdiff/gitdiff.go [hunk 2]
```diff
@@ -283,116 +262,131 @@ type DiffInline struct {
...
+		diff1 = diffSection.getLineContentForRender(leftLine.LeftIdx, leftLine, diffSection.file.highlightedLeftLines)
+		lineHTML = util.Iif(diffLineType == DiffLinePlain, diff1, "")
 	}
+	if rightLine != nil {
+		diff2 = diffSection.getLineContentForRender(rightLine.RightIdx, rightLine, diffSection.file.highlightedRightLines)
+		lineHTML = util.Iif(diffLineType == DiffLinePlain, diff2, "")
+	}
+	if diffLineType != DiffLinePlain {
+		// it seems that Gitea doesn't need the line wrapper of Chroma, so do not add them back
+		// if the line wrappers are still needed in the future, it can be added back by "diffToHTML(hcd.lineWrapperTags. ...)"
```
Comment (wxiaoguang) [inline services/gitdiff/gitdiff.go]:
```suggestion
		// if the line wrappers are still needed in the future, it can be added back by "diffLineWithHighlightWrapper(hcd.lineWrapperTags. ...)"
```

**Comment by lunny** [comment]
When expend more codes, it result in 500

```
Render failed, failed to render template: repo/diff/blob_excerpt, error: template error: builtin(static):repo/diff/blob_excerpt:83:20 : executing "repo/diff/blob_excerpt" at <$.section.GetComputedInlineDiffFor>: error calling GetComputedInlineDiffFor: runtime error: invalid memory address or nil pointer dereference
----------------------------------------------------------------------
		{{$inlineDiff := $.section.GetComputedInlineDiffFor $line ctx.Locale}}
		                  ^
----------------------------------------------------------------------
```

**Comment by wxiaoguang** [comment]
> When expend more codes, it result in 500

Fixed in b2dbc78bfd599dfc46e6faf322f132b1740cfea9 and added more tests

**Review by silverwind — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Follow up fix:  Fix material icon & diff highlight #33844
