### PR TITLE
fix run web with -p push failed

### LINKED ISSUE #2952: ! [remote rejected] master -> master (pre-receive hook declined)
- Gitea version (or commit ref): 

gitea-1.3-linux-amd64

binary on Debian GNU/Linux 9 (stretch)

- Git version:
2.11.0

- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

- I download binary, this version:

```
~/Install/gitea$ ./gitea-1.3-linux-amd64 --version
Gitea version 4683e54 built with: bindata, sqlite
```
I ran it with 

```
$ ./gitea-1.3-linux-amd64 web -p 3500
2017/11/21 01:57:20 [T] AppPath: /home/eclipse/Install/gitea/gitea-1.3-linux-amd64
2017/11/21 01:57:20 [T] AppWorkPath: /home/eclipse/Install/gitea
2017/11/21 01:57:20 [T] Custom path: /home/eclipse/Install/gitea/custom
2017/11/21 01:57:20 [T] Log path: /home/eclipse/Install/gitea/log
2017/11/21 01:57:20 Serving [::]:3500 with pid 22540
```

Then made server reverse proxy on port 80, binding to `git.local` domain (can be used from macOS)

I then tried to create a new repository on web instance on local network, then trying to push to it according to instructions:

```
Creating a new repository on the command line
touch README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin http://git.local/davidhq/test.git
git push -u origin master
```

I tried multiple combinations and variations of everything, always the same message:

```
$ git push -u origin master
Counting objects: 3, done.
Writing objects: 100% (3/3), 216 bytes | 216.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To http://git.local/davidhq/test.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'http://git.local/davidhq/test.git'
```

This was the last try: doing it via `.local` domain, so that really nothing (Cloudflare etc.) is interfering with trying to push to the repo.

Do you have any tips how to solve the problem?

Another question: when I tried to compile `gitea`, the version is always reported as `Gitea version 1.1.0+774-gfd09d1ff`, I think it's baked into `Makefile` because here also for sure I'm compiling the latest commit from master.

### PR DESCRIPTION
**Pull request by lunny**
Will fix #2952

### CODE REVIEW

File: cmd/web.go [hunk 1]
```diff
@@ -69,6 +71,34 @@ func runWeb(ctx *cli.Context) error {
 	if ctx.IsSet("port") {
 		setting.AppURL = strings.Replace(setting.AppURL, setting.HTTPPort, ctx.String("port"), 1)
 		setting.HTTPPort = ctx.String("port")
+
+		switch setting.Protocol {
+		case setting.UnixSocket:
```
Comment (lafriks) [inline cmd/web.go:76]: This will not work for unix sockets and FCGI (see `NewContext` in `setting.go`). 
As being so close to that functionality as in NewContext, can this formatting be moved out to some common place so that it could be reused in both places?

**Review by lafriks — CHANGES_REQUESTED** [review]

File: cmd/web.go (hunk 1 above)
Comment (lunny) [reply cmd/web.go:76]: @lafriks, for unix sockets and FCGI, the port changed will not be effected, so ignored them. Currently only this place need the code and there is no other place need it.

**Review by lafriks — APPROVED** [review]

File: cmd/web.go (hunk 1 above)
Comment (lafriks) [reply cmd/web.go:76]: Sorry it was late and forgot about golang cases not being fall through by default :)

**Comment by lafriks** [comment]
LGTM

**Comment by strk** [comment]
Trusted LGTM
