### PR TITLE
Fix possible pull request broken when leave the page immediately after clicking the update button

### LINKED ISSUE #31779: "This pull request is broken due to missing fork information." after pushing
### Description

I have been using Gitea 1.20.2 for over a year now and recently I started to get "This pull request is broken due to missing fork information" on my pull requests. I can still interact with my repositories in the normal way

I then updated Gitea to 1.21.11 and the issue persisted. I have tried going to the dashboard and:
* Update the '.ssh/authorized_keys' file with Gitea SSH keys.
* Update the '.ssh/authorized_principals' file with Gitea SSH principals.
* Resynchronize pre-receive, update and post-receive hooks of all repositories.

The hooks from a repository suffering this issue are:
```
$ ls hooks
applypatch-msg.sample	   post-receive.d	  pre-merge-commit.sample    pre-receive	 proc-receive.d		    update.d
commit-msg.sample	   post-update.sample	  prepare-commit-msg.sample  pre-receive.d	 push-to-checkout.sample    update.sample
fsmonitor-watchman.sample  pre-applypatch.sample  pre-push.sample	     pre-receive.sample  sendemail-validate.sample
post-receive		   pre-commit.sample	  pre-rebase.sample	     proc-receive	 update
```

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

  No logs are generated for `gitea/log` and `log` in the gitea directory, so I'm not sure what log to include

### Screenshots

image

### Git Version

2.44.1

### Operating System

NixOS 24.05.20240803.a633d89 (Uakari)

### How are you running Gitea?

Using the gitea module from NixOS's `configuration.nix`

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by lunny**
If user leaves the page, the context will become cancelled, so that the update process maybe terminal in an unexpected status. This PR haven't resolve the problem totally. It uses a background context to not cancel the update process even if the user leaved the pull request view page.

Fix #31779

### CODE REVIEW

File: routers/web/repo/pull.go [hunk 1]
```diff
@@ -986,7 +987,9 @@ func UpdatePullRequest(ctx *context.Context) {
 	// default merge commit message
 	message := fmt.Sprintf("Merge branch '%s' into %s", issue.PullRequest.BaseBranch, issue.PullRequest.HeadBranch)
 
-	if err = pull_service.Update(ctx, issue.PullRequest, ctx.Doer, message, rebase); err != nil {
+	// The update process should not be cancelled by the user
+	// so we set the context to be a background context
+	if err = pull_service.Update(graceful.GetManager().ShutdownContext(), issue.PullRequest, ctx.Doer, message, rebase); err != nil {
```
Comment (yp05327) [inline routers/web/repo/pull.go:992]: Remove ctx as a param for this function?
ps: It is also used by API

Comment (lunny) [reply routers/web/repo/pull.go:992]: 6edc97ba64 will also update API. Keeping the first parameter of `Update` as context will make the function read easier, otherwise we need to replace every `ctx` to `graceful.GetManager().ShutdownContext()` in the function.

Comment (yp05327) [reply routers/web/repo/pull.go:992]: CI failed

**Review by yp05327 — APPROVED** [review]

**Review by hiifong — APPROVED** [review]
