### PR TITLE
A better go code formatter, and now `make fmt` can run in Windows

### LINKED ISSUE #14438: "make fmt" fails on windows
- Gitea version (or commit ref): 1.14
- Operating system: windows 10

## Description

```
C:\gitea (master -> upstream)
λ make fmt
Running go fmt...
process_begin: CreateProcess(C:\Go\bin\gofmt.exe, gofmt -s -w main.go build.go cmd/admin.go cmd/admin_auth_ldap.go cmd/admin_auth_ldap_test.go cmd/cert.go cmd/cmd.go cmd/convert.go cmd/docs.go cmd/doctor.go cmd/dump.go cmd/dump_repo.go cmd/embedded.go cmd/embedded_stub.go cmd/generate.go cmd/hook.go cmd/keys.go cmd/mailer.go cmd/manager.go cmd/migrate.go cmd/migrate_storage.go cmd/restore_repo.go cmd/serv.go cmd/web.go cmd/web_graceful.go integrations/admin_user_test.go integrations/api_admin_org_test.go integrations/api_admin_test.go integrations/api_branch_test.go integrations/api_comment_test.go integrations/api_fork_test.go integrations/api_gpg_keys_test.go integrations/api_helper_for_declarative_test.go integrations/api_issue_label_test.go integrations/api_issue_milestone_test.go integrations/api_issue_reaction_test.go integrations/api_issue_stopwatch_test.go integrations/api_issue_subscription_test.go integrations/api_issue_test.go integrations/api_issue_tracked_time_test.go integrations/api_keys_test.go integrations/api_notification_test.go integrations/api_oauth2_apps_test.go integrations/api_org_test.go integrations/api_pull_review_test.go integrations/api_pull_test.go integrations/api_releases_test.go integrations/api_repo_edit_test.go integrations/api_repo_file_create_test.go integrations/api_repo_file_delete_test.go integrations/api_repo_file_helpers.go integrations/api_repo_file_update_test.go integrations/api_repo_get_contents_list_test.go integrations/api_repo_get_contents_test.go integrations/api_repo_git_blobs_test.go integrations/api_repo_git_commits_test.go integrations/api_repo_git_hook_test.go integrations/api_repo_git_ref_test.go integrations/api_repo_git_tags_test.go integrations/api_repo_git_trees_test.go integrations/api_repo_languages_test.go integrations/api_repo_lfs_locks_test.go integrations/api_repo_raw_test.go integrations/api_repo_tags_test.go integrations/api_repo_test.go integrations/api_repo_topic_test.go integrations/api_settings_test.go integrations/api_team_test.go integrations/api_team_user_test.go integrations/api_token_test.go integrations/api_user_heatmap_test.go integrations/api_user_orgs_test.go integrations/api_user_search_test.go integrations/attachment_test.go integrations/auth_ldap_test.go integrations/benchmarks_test.go integrations/branches_test.go integrations/change_default_branch_test.go integrations/cmd_keys_test.go integrations/cors_test.go integrations/create_no_session_test.go integrations/delete_user_test.go integrations/download_test.go integrations/editor_test.go integrations/empty_repo_test.go integrations/eventsource_test.go integrations/explore_repos_test.go integrations/git_helper_for_declarative_test.go integrations/git_test.go integrations/gpg_git_test.go integrations/html_helper.go integrations/integration_test.go integrations/issue_test.go integrations/lfs_getobject_test.go integrations/links_test.go integrations/migration-test/migration_test.go integrations/nonascii_branches_test.go integrations/oauth_test.go integrations/org_count_test.go integrations/org_test.go integrations/privateactivity_test.go integrations/pull_compare_test.go integrations/pull_create_test.go integrations/pull_merge_test.go integrations/pull_review_test.go integrations/pull_status_test.go integrations/pull_update_test.go integrations/release_test.go integrations/repofiles_delete_test.go integrations/repofiles_update_test.go integrations/repo_activity_test.go integrations/repo_branch_test.go integrations/repo_commits_search_test.go integrations/repo_commits_test.go integrations/repo_fork_test.go integrations/repo_generate_test.go integrations/repo_migrate_test.go integrations/repo_search_test.go integrations/repo_test.go integrations/repo_watch_test.go integrations/setting_test.go integrations/signin_test.go integrations/signout_test.go integrations/signup_test.go integrations/ssh_key_test.go integrations/testlogger.go integrations/timetracking_test.go integrations/user_test.go integrations/version_test.go integrations/view_test.go integrations/xss_test.go models/access.go models/access_test.go models/action.go models/action_list.go models/action_test.go models/admin.go models/admin_test.go models/attachment.go models/attachment_test.go models/avatar.go models/avatar_test.go models/branches.go models/branches_test.go models/commit_status.go models/commit_status_test.go models/consistency.go models/context.go models/convert.go models/error.go models/error_oauth2.go models/external_login_user.go models/fixture_generation.go models/fixture_test.go models/gpg_key.go models/gpg_key_test.go models/helper.go models/helper_directory.go models/helper_environment.go models/issue.go models/issue_assignees.go models/issue_assignees_test.go models/issue_comment.go models/issue_comment_list.go models/issue_comment_test.go models/issue_dependency.go models/issue_dependency_test.go models/issue_label.go models/issue_label_test.go models/issue_list.go models/issue_list_test.go models/issue_lock.go models/issue_milestone.go models/issue_milestone_test.go models/issue_reaction.go models/issue_reaction_test.go models/issue_stopwatch.go models/issue_stopwatch_test.go models/issue_test.go models/issue_tracked_time.go models/issue_tracked_time_test.go models/issue_user.go models/issue_user_test.go models/issue_watch.go models/issue_watch_test.go models/issue_xref.go models/issue_xref_test.go models/lfs.go models/lfs_lock.go models/list_options.go models/log.go models/login_source.go models/main_test.go models/migrate.go models/migrations/migrations.go models/migrations/v100.go models/migrations/v101.go models/migrations/v102.go models/migrations/v103.go models/migrations/v104.go models/migrations/v105.go models/migrations/v106.go models/migrations/v107.go models/migrations/v108.go models/migrations/v109.go models/migrations/v110.go models/migrations/v111.go models/migrations/v112.go models/migrations/v113.go models/migrations/v114.go models/migrations/v115.go models/migrations/v116.go models/migrations/v117.go models/migrations/v118.go models/migrations/v119.go models/migrations/v120.go models/migrations/v121.go models/migrations/v122.go models/migrations/v123.go models/migrations/v124.go models/migrations/v125.go models/migrations/v126.go models/migrations/v127.go models/migrations/v128.go models/migrations/v129.go models/migrations/v130.go models/migrations/v131.go models/migrations/v132.go models/migrations/v133.go models/migrations/v134.go models/migrations/v135.go models/migrations/v136.go models/migrations/v137.go models/migrations/v138.go models/migrations/v139.go models/migrations/v140.go models/migrations/v141.go models/migrations/v142.go models/migrations/v143.go models/migrations/v144.go models/migrations/v145.go models/migrations/v146.go models/migrations/v147.go models/migrations/v148.go models/migrations/v149.go models/migrations/v150.go models/migrations/v151.go models/migrations/v152.go models/migrations/v153.go models/migrations/v154.go models/migrations/v155.go models/migrations/v156.go models/migrations/v157.go models/migrations/v158.go models/migrations/v159.go models/migrations/v160.go models/migrations/v161.go models/migrations/v162.go models/migrations/v163.go models/migrations/v164.go models/migrations/v165.go models/migrations/v166.go models/migrations/v70.go models/migrations/v71.go models/migrations/v72.go models/migrations/v73.go models/migrations/v74.go models/migrations/v75.go models/migrations/v76.go models/migrations/v77.go models/migrations/v78.go models/migrations/v79.go models/migrations/v80.go models/migrations/v81.go models/migrations/v82.go models/migrations/v83.go models/migrations/v84.go models/migrations/v85.go models/migrations/v86.go models/migrations/v87.go models/migrations/v88.go models/migrations/v89.go models/migrations/v90.go models/migrations/v91.go models/migrations/v92.go models/migrations/v93.go models/migrations/v94.go models/migrations/v95.go models/migrations/v96.go models/migrations/v97.go models/migrations/v98.go models/migrations/v99.go models/models.go models/models_test.go models/notification.go models/notification_test.go models/oauth2.go models/oauth2_application.go models/oauth2_application_test.go models/org.go models/org_team.go models/org_team_test.go models/org_test.go models/project.go models/project_board.go models/project_issue.go models/project_test.go models/pull.go models/pull_list.go models/pull_sign.go models/pull_test.go models/release.go models/repo.go models/repo_activity.go models/repo_avatar.go models/repo_branch.go models/repo_collaboration.go models/repo_collaboration_test.go models/repo_generate.go models/repo_generate_test.go models/repo_indexer.go models/repo_issue.go models/repo_language_stats.go models/repo_list.go models/repo_list_test.go models/repo_mirror.go models/repo_permission.go models/repo_permission_test.go models/repo_redirect.go models/repo_redirect_test.go models/repo_sign.go models/repo_test.go models/repo_unit.go models/repo_watch.go models/repo_watch_test.go models/review.go models/review_test.go models/sql_postgres_with_schema.go models/ssh_key.go models/ssh_key_test.go models/star.go models/star_test.go models/task.go models/test_fixtures.go models/token.go models/token_test.go models/topic.go models/topic_test.go models/twofactor.go models/u2f.go models/u2f_test.go models/unit.go models/unit_tests.go models/update.go models/upload.go models/user.go models/userlist.go models/userlist_test.go models/user_avatar.go models/user_follow.go models/user_follow_test.go models/user_heatmap.go models/user_heatmap_test.go models/user_mail.go models/user_mail_test.go models/user_openid.go models/user_openid_test.go models/user_test.go models/webhook.go models/webhook_test.go models/wiki.go models/wiki_test.go modules/analyze/code_langauge.go modules/auth/admin.go modules/auth/auth.go modules/auth/auth_form.go modules/auth/ldap/ldap.go modules/auth/oauth2/oauth2.go modules/auth/openid/discovery_cache.go modules/auth/openid/discovery_cache_test.go modules/auth/openid/openid.go modules/auth/org.go modules/auth/pam/pam.go modules/auth/pam/pam_stub.go modules/auth/repo_branch_form.go modules/auth/repo_form.go modules/auth/repo_form_test.go modules/auth/sso/basic.go modules/auth/sso/interface.go modules/auth/sso/oauth2.go modules/auth/sso/reverseproxy.go modules/auth/sso/session.go modules/auth/sso/sso.go modules/auth/sso/sspi_windows.go modules/auth/sso/user.go modules/auth/user_form.go modules/auth/user_form_auth_openid.go modules/auth/user_form_test.go modules/avatar/avatar.go modules/avatar/avatar_test.go modules/base/base.go modules/base/natural_sort.go modules/base/natural_sort_test.go modules/base/tool.go modules/base/tool_test.go modules/cache/cache.go modules/cache/cache_redis.go modules/charset/charset.go modules/charset/charset_test.go modules/context/api.go modules/context/api_org.go modules/context/api_test.go modules/context/auth.go modules/context/context.go modules/context/org.go modules/context/pagination.go modules/context/permission.go modules/context/repo.go modules/context/response.go modules/convert/convert.go modules/convert/git_commit.go modules/convert/git_commit_test.go modules/convert/issue.go modules/convert/issue_comment.go modules/convert/issue_test.go modules/convert/main_test.go modules/convert/notification.go modules/convert/pull.go modules/convert/pull_review.go modules/convert/pull_test.go modules/convert/release.go modules/convert/repository.go modules/convert/status.go modules/convert/user.go modules/convert/user_test.go modules/convert/utils.go modules/cron/cron.go modules/cron/setting.go modules/cron/tasks.go modules/cron/tasks_basic.go modules/cron/tasks_extended.go modules/doctor/authorizedkeys.go modules/doctor/dbconsistency.go modules/doctor/dbversion.go modules/doctor/doctor.go modules/doctor/mergebase.go modules/doctor/misc.go modules/doctor/paths.go modules/emoji/emoji.go modules/emoji/emoji_data.go modules/emoji/emoji_test.go modules/eventsource/event.go modules/eventsource/event_test.go modules/eventsource/manager.go modules/eventsource/manager_run.go modules/eventsource/messenger.go modules/generate/generate.go modules/generate/generate_test.go modules/git/batch_reader_nogogit.go modules/git/blame.go modules/git/blame_test.go modules/git/blob.go modules/git/blob_gogit.go modules/git/blob_nogogit.go modules/git/blob_test.go modules/git/command.go modules/git/command_test.go modules/git/commit.go modules/git/commit_archive.go modules/git/commit_convert_gogit.go modules/git/commit_info.go modules/git/commit_info_gogit.go modules/git/commit_info_nogogit.go modules/git/commit_info_test.go modules/git/commit_reader.go modules/git/commit_test.go modules/git/diff.go modules/git/diff_test.go modules/git/error.go modules/git/git.go modules/git/git_test.go modules/git/hook.go modules/git/last_commit_cache.go modules/git/last_commit_cache_gogit.go modules/git/last_commit_cache_nogogit.go modules/git/notes.go modules/git/notes_gogit.go modules/git/notes_nogogit.go modules/git/notes_test.go modules/git/parse_gogit.go modules/git/parse_gogit_test.go modules/git/parse_nogogit.go modules/git/pipeline/catfile.go modules/git/pipeline/lfs.go modules/git/pipeline/lfs_nogogit.go modules/git/pipeline/namerev.go modules/git/pipeline/revlist.go modules/git/ref.go modules/git/repo.go modules/git/repo_attribute.go modules/git/repo_base_gogit.go modules/git/repo_base_nogogit.go modules/git/repo_blame.go modules/git/repo_blob.go modules/git/repo_blob_gogit.go modules/git/repo_blob_nogogit.go modules/git/repo_blob_test.go modules/git/repo_branch.go modules/git/repo_branch_gogit.go modules/git/repo_branch_nogogit.go modules/git/repo_branch_test.go modules/git/repo_commit.go modules/git/repo_commitgraph_gogit.go modules/git/repo_commit_gogit.go modules/git/repo_commit_nogogit.go modules/git/repo_commit_test.go modules/git/repo_compare.go modules/git/repo_compare_test.go modules/git/repo_gpg.go modules/git/repo_hook.go modules/git/repo_index.go modules/git/repo_language_stats.go modules/git/repo_language_stats_gogit.go modules/git/repo_language_stats_nogogit.go modules/git/repo_object.go modules/git/repo_ref.go modules/git/repo_ref_gogit.go modules/git/repo_ref_nogogit.go modules/git/repo_ref_test.go modules/git/repo_stats.go modules/git/repo_stats_test.go modules/git/repo_tag.go modules/git/repo_tag_gogit.go modules/git/repo_tag_nogogit.go modules/git/repo_tag_test.go modules/git/repo_test.go modules/git/repo_tree.go modules/git/repo_tree_gogit.go modules/git/repo_tree_nogogit.go modules/git/sha1.go modules/git/sha1_gogit.go modules/git/sha1_nogogit.go modules/git/signature.go modules/git/signature_gogit.go modules/git/signature_nogogit.go modules/git/submodule.go modules/git/submodule_test.go modules/git/tag.go modules/git/tag_test.go modules/git/tree.go modules/git/tree_blob.go modules/git/tree_blob_gogit.go modules/git/tree_blob_nogogit.go modules/git/tree_entry.go modules/git/tree_entry_gogit.go modules/git/tree_entry_mode.go modules/git/tree_entry_nogogit.go modules/git/tree_entry_test.go modules/git/tree_gogit.go modules/git/tree_nogogit.go modules/git/utils.go modules/git/utils_test.go modules/gitgraph/graph.go modules/gitgraph/graph_models.go modules/gitgraph/graph_test.go modules/gitgraph/parser.go modules/graceful/context.go modules/graceful/manager.go modules/graceful/manager_unix.go modules/graceful/manager_windows.go modules/graceful/net_unix.go modules/graceful/net_windows.go modules/graceful/restart_unix.go modules/graceful/server.go modules/graceful/server_hooks.go modules/graceful/server_http.go modules/hcaptcha/hcaptcha.go modules/highlight/highlight.go modules/httpcache/httpcache.go modules/httplib/httplib.go modules/indexer/code/bleve.go modules/indexer/code/bleve_test.go modules/indexer/code/elastic_search.go modules/indexer/code/elastic_search_test.go modules/indexer/code/git.go modules/indexer/code/indexer.go modules/indexer/code/indexer_test.go modules/indexer/code/search.go modules/indexer/code/wrapped.go modules/indexer/issues/bleve.go modules/indexer/issues/bleve_test.go modules/indexer/issues/db.go modules/indexer/issues/elastic_search.go modules/indexer/issues/indexer.go modules/indexer/issues/indexer_test.go modules/indexer/stats/db.go modules/indexer/stats/indexer.go modules/indexer/stats/indexer_test.go modules/indexer/stats/queue.go modules/lfs/content_store.go modules/lfs/locks.go modules/lfs/pointers.go modules/lfs/server.go modules/log/colors.go modules/log/colors_router.go modules/log/conn.go modules/log/conn_test.go modules/log/console.go modules/log/console_test.go modules/log/console_windows.go modules/log/errors.go modules/log/event.go modules/log/file.go modules/log/file_test.go modules/log/flags.go modules/log/level.go modules/log/level_test.go modules/log/log.go modules/log/logger.go modules/log/log_test.go modules/log/multichannel.go modules/log/provider.go modules/log/smtp.go modules/log/smtp_test.go modules/log/stack.go modules/log/writer.go modules/log/writer_test.go modules/markup/common/footnote.go modules/markup/common/html.go modules/markup/common/linkify.go modules/markup/csv/csv.go modules/markup/csv/csv_test.go modules/markup/external/external.go modules/markup/html.go modules/markup/html_internal_test.go modules/markup/html_test.go modules/markup/markdown/ast.go modules/markup/markdown/goldmark.go modules/markup/markdown/markdown.go modules/markup/markdown/markdown_test.go modules/markup/markdown/meta.go modules/markup/markdown/meta_test.go modules/markup/markdown/renderconfig.go modules/markup/markdown/toc.go modules/markup/markup.go modules/markup/markup_test.go modules/markup/mdstripper/mdstripper.go modules/markup/mdstripper/mdstripper_test.go modules/markup/orgmode/orgmode.go modules/markup/orgmode/orgmode_test.go modules/markup/sanitizer.go modules/markup/sanitizer_test.go modules/matchlist/matchlist.go modules/metrics/collector.go modules/middlewares/cookie.go modules/middlewares/locale.go modules/middlewares/redis.go modules/middlewares/virtual.go modules/migrations/base/comment.go modules/migrations/base/downloader.go modules/migrations/base/error.go modules/migrations/base/issue.go modules/migrations/base/label.go modules/migrations/base/milestone.go modules/migrations/base/null_downloader.go modules/migrations/base/options.go modules/migrations/base/pullrequest.go modules/migrations/base/reaction.go modules/migrations/base/release.go modules/migrations/base/repo.go modules/migrations/base/retry_downloader.go modules/migrations/base/review.go modules/migrations/base/uploader.go modules/migrations/dump.go modules/migrations/error.go modules/migrations/git.go modules/migrations/gitea_downloader.go modules/migrations/gitea_downloader_test.go modules/migrations/gitea_uploader.go modules/migrations/gitea_uploader_test.go modules/migrations/github.go modules/migrations/github_test.go modules/migrations/gitlab.go modules/migrations/gitlab_test.go modules/migrations/gogs.go modules/migrations/gogs_test.go modules/migrations/main_test.go modules/migrations/migrate.go modules/migrations/migrate_test.go modules/migrations/restore.go modules/migrations/update.go modules/nosql/leveldb.go modules/nosql/manager.go modules/nosql/manager_leveldb.go modules/nosql/manager_redis.go modules/nosql/redis.go modules/nosql/redis_test.go modules/notification/action/action.go modules/notification/action/action_test.go modules/notification/base/notifier.go modules/notification/base/null.go modules/notification/indexer/indexer.go modules/notification/mail/mail.go modules/notification/notification.go modules/notification/ui/ui.go modules/notification/webhook/webhook.go modules/options/dynamic.go modules/options/options.go modules/options/options_bindata.go modules/options/static.go modules/password/password.go modules/password/password_test.go modules/password/pwn.go modules/pprof/pprof.go modules/private/hook.go modules/private/internal.go modules/private/key.go modules/private/mail.go modules/private/manager.go modules/private/serv.go modules/process/manager.go modules/process/manager_test.go modules/public/dynamic.go modules/public/public.go modules/public/public_bindata.go modules/public/public_test.go modules/public/static.go modules/queue/bytefifo.go modules/queue/helper.go modules/queue/manager.go modules/queue/queue.go modules/queue/queue_bytefifo.go modules/queue/queue_channel.go modules/queue/queue_channel_test.go modules/queue/queue_disk.go modules/queue/queue_disk_channel.go modules/queue/queue_disk_channel_test.go modules/queue/queue_disk_test.go modules/queue/queue_redis.go modules/queue/queue_test.go modules/queue/queue_wrapped.go modules/queue/setting.go modules/queue/unique_queue.go modules/queue/unique_queue_channel.go modules/queue/unique_queue_disk.go modules/queue/unique_queue_disk_channel.go modules/queue/unique_queue_redis.go modules/queue/unique_queue_wrapped.go modules/queue/workerpool.go modules/recaptcha/recaptcha.go modules/references/references.go modules/references/references_test.go modules/repofiles/action.go modules/repofiles/action_test.go modules/repofiles/blob.go modules/repofiles/blob_test.go modules/repofiles/commit.go modules/repofiles/commit_status.go modules/repofiles/content.go modules/repofiles/content_test.go modules/repofiles/delete.go modules/repofiles/diff.go modules/repofiles/diff_test.go modules/repofiles/file.go modules/repofiles/file_test.go modules/repofiles/repofiles.go modules/repofiles/repofiles_test.go modules/repofiles/temp_repo.go modules/repofiles/tree.go modules/repofiles/tree_test.go modules/repofiles/update.go modules/repofiles/upload.go modules/repofiles/verification.go modules/repository/adopt.go modules/repository/branch.go modules/repository/cache.go modules/repository/check.go modules/repository/commits.go modules/repository/commits_test.go modules/repository/create.go modules/repository/create_test.go modules/repository/fork.go modules/repository/fork_test.go modules/repository/generate.go modules/repository/hooks.go modules/repository/init.go modules/repository/main_test.go modules/repository/push.go modules/repository/repo.go modules/repository/update.go modules/secret/secret.go modules/secret/secret_test.go modules/session/redis.go modules/session/virtual.go modules/setting/attachment.go modules/setting/cache.go modules/setting/cors.go modules/setting/cron.go modules/setting/cron_test.go modules/setting/database.go modules/setting/database_sqlite.go modules/setting/database_test.go modules/setting/git.go modules/setting/indexer.go modules/setting/indexer_test.go modules/setting/lfs.go modules/setting/log.go modules/setting/mailer.go modules/setting/markup.go modules/setting/migrations.go modules/setting/picture.go modules/setting/project.go modules/setting/queue.go modules/setting/repository.go modules/setting/service.go modules/setting/session.go modules/setting/setting.go modules/setting/setting_test.go modules/setting/storage.go modules/setting/storage_test.go modules/setting/task.go modules/setting/webhook.go modules/ssh/ssh.go modules/ssh/ssh_graceful.go modules/storage/helper.go modules/storage/local.go modules/storage/minio.go modules/storage/storage.go modules/structs/admin_user.go modules/structs/attachment.go modules/structs/commit_status.go modules/structs/cron.go modules/structs/doc.go modules/structs/fork.go modules/structs/git_blob.go modules/structs/git_hook.go modules/structs/hook.go modules/structs/issue.go modules/structs/issue_comment.go modules/structs/issue_label.go modules/structs/issue_milestone.go modules/structs/issue_reaction.go modules/structs/issue_stopwatch.go modules/structs/issue_tracked_time.go modules/structs/lfs_lock.go modules/structs/miscellaneous.go modules/structs/notifications.go modules/structs/org.go modules/structs/org_member.go modules/structs/org_team.go modules/structs/org_type.go modules/structs/pull.go modules/structs/pull_review.go modules/structs/release.go modules/structs/repo.go modules/structs/repo_branch.go modules/structs/repo_collaborator.go modules/structs/repo_commit.go modules/structs/repo_file.go modules/structs/repo_key.go modules/structs/repo_refs.go modules/structs/repo_tag.go modules/structs/repo_topic.go modules/structs/repo_tree.go modules/structs/repo_watch.go modules/structs/settings.go modules/structs/status.go modules/structs/task.go modules/structs/user.go modules/structs/user_app.go modules/structs/user_email.go modules/structs/user_gpgkey.go modules/structs/user_key.go modules/svg/discover_bindata.go modules/svg/discover_nobindata.go modules/svg/svg.go modules/sync/exclusive_pool.go modules/sync/status_pool.go modules/sync/status_pool_test.go modules/sync/unique_queue.go modules/task/migrate.go modules/task/task.go modules/templates/base.go modules/templates/dynamic.go modules/templates/helper.go modules/templates/helper_test.go modules/templates/static.go modules/templates/templates_bindata.go modules/test/context_tests.go modules/test/utils.go modules/timeutil/language.go modules/timeutil/since.go modules/timeutil/since_test.go modules/timeutil/timestamp.go modules/translation/translation.go modules/upload/upload.go modules/upload/upload_test.go modules/uri/uri.go modules/uri/uri_test.go modules/user/user.go modules/user/user_test.go modules/util/compare.go modules/util/copy.go modules/util/path.go modules/util/remove.go modules/util/sanitize.go modules/util/sanitize_test.go modules/util/shellquote.go modules/util/shellquote_test.go modules/util/timer.go modules/util/url.go modules/util/util.go modules/util/util_test.go modules/validation/binding.go modules/validation/binding_test.go modules/validation/glob_pattern_test.go modules/validation/helpers.go modules/validation/helpers_test.go modules/validation/refname_test.go modules/validation/validurl_test.go routers/admin/admin.go routers/admin/admin_test.go routers/admin/auths.go routers/admin/emails.go routers/admin/hooks.go routers/admin/main_test.go routers/admin/notice.go routers/admin/orgs.go routers/admin/repos.go routers/admin/users.go routers/admin/users_test.go routers/api/v1/admin/adopt.go routers/api/v1/admin/cron.go routers/api/v1/admin/org.go routers/api/v1/admin/repo.go routers/api/v1/admin/user.go routers/api/v1/api.go routers/api/v1/misc/markdown.go routers/api/v1/misc/markdown_test.go routers/api/v1/misc/signing.go routers/api/v1/misc/swagger.go routers/api/v1/misc/version.go routers/api/v1/notify/notifications.go routers/api/v1/notify/repo.go routers/api/v1/notify/threads.go routers/api/v1/notify/user.go routers/api/v1/org/hook.go routers/api/v1/org/label.go routers/api/v1/org/member.go routers/api/v1/org/org.go routers/api/v1/org/team.go routers/api/v1/repo/blob.go routers/api/v1/repo/branch.go routers/api/v1/repo/collaborators.go routers/api/v1/repo/commits.go routers/api/v1/repo/file.go routers/api/v1/repo/fork.go routers/api/v1/repo/git_hook.go routers/api/v1/repo/git_ref.go routers/api/v1/repo/hook.go routers/api/v1/repo/hook_test.go routers/api/v1/repo/issue.go routers/api/v1/repo/issue_comment.go routers/api/v1/repo/issue_label.go routers/api/v1/repo/issue_reaction.go routers/api/v1/repo/issue_stopwatch.go routers/api/v1/repo/issue_subscription.go routers/api/v1/repo/issue_tracked_time.go routers/api/v1/repo/key.go routers/api/v1/repo/label.go routers/api/v1/repo/language.go routers/api/v1/repo/main_test.go routers/api/v1/repo/migrate.go routers/api/v1/repo/milestone.go routers/api/v1/repo/mirror.go routers/api/v1/repo/pull.go routers/api/v1/repo/pull_review.go routers/api/v1/repo/release.go routers/api/v1/repo/release_attachment.go routers/api/v1/repo/release_tags.go routers/api/v1/repo/repo.go routers/api/v1/repo/repo_test.go routers/api/v1/repo/star.go routers/api/v1/repo/status.go routers/api/v1/repo/subscriber.go routers/api/v1/repo/tag.go routers/api/v1/repo/topic.go routers/api/v1/repo/transfer.go routers/api/v1/repo/tree.go routers/api/v1/settings/settings.go routers/api/v1/swagger/app.go routers/api/v1/swagger/cron.go routers/api/v1/swagger/issue.go routers/api/v1/swagger/key.go routers/api/v1/swagger/misc.go routers/api/v1/swagger/notify.go routers/api/v1/swagger/options.go routers/api/v1/swagger/org.go routers/api/v1/swagger/repo.go routers/api/v1/swagger/settings.go routers/api/v1/swagger/user.go routers/api/v1/user/app.go routers/api/v1/user/email.go routers/api/v1/user/follower.go routers/api/v1/user/gpg_key.go routers/api/v1/user/key.go routers/api/v1/user/repo.go routers/api/v1/user/star.go routers/api/v1/user/user.go routers/api/v1/user/watch.go routers/api/v1/utils/hook.go routers/api/v1/utils/utils.go routers/dev/template.go routers/events/events.go routers/home.go routers/init.go routers/install.go routers/metrics.go routers/org/home.go routers/org/members.go routers/org/org.go routers/org/org_labels.go routers/org/setting.go routers/org/teams.go routers/private/hook.go routers/private/internal.go routers/private/key.go routers/private/mail.go routers/private/manager.go routers/private/manager_unix.go routers/private/manager_windows.go routers/private/serv.go routers/repo/activity.go routers/repo/attachment.go routers/repo/blame.go routers/repo/branch.go routers/repo/commit.go routers/repo/compare.go routers/repo/download.go routers/repo/editor.go routers/repo/editor_test.go routers/repo/http.go routers/repo/issue.go routers/repo/issue_dependency.go routers/repo/issue_label.go routers/repo/issue_label_test.go routers/repo/issue_lock.go routers/repo/issue_stopwatch.go routers/repo/issue_test.go routers/repo/issue_timetrack.go routers/repo/issue_watch.go routers/repo/lfs.go routers/repo/main_test.go routers/repo/middlewares.go routers/repo/migrate.go routers/repo/milestone.go routers/repo/projects.go routers/repo/projects_test.go routers/repo/pull.go routers/repo/pull_review.go routers/repo/release.go routers/repo/release_test.go routers/repo/repo.go routers/repo/search.go routers/repo/setting.go routers/repo/settings_test.go routers/repo/setting_protected_branch.go routers/repo/topic.go routers/repo/view.go routers/repo/webhook.go routers/repo/wiki.go routers/repo/wiki_test.go routers/routes/chi.go routers/routes/macaron.go routers/routes/recovery.go routers/swagger_json.go routers/user/auth.go routers/user/auth_openid.go routers/user/avatar.go routers/user/home.go routers/user/home_test.go routers/user/main_test.go routers/user/notification.go routers/user/oauth.go routers/user/profile.go routers/user/setting/account.go routers/user/setting/account_test.go routers/user/setting/adopt.go routers/user/setting/applications.go routers/user/setting/keys.go routers/user/setting/main_test.go routers/user/setting/oauth2.go routers/user/setting/profile.go routers/user/setting/security.go routers/user/setting/security_openid.go routers/user/setting/security_twofa.go routers/user/setting/security_u2f.go routers/user/task.go routers/utils/utils.go routers/utils/utils_test.go build/generate-bindata.go build/generate-emoji.go build/generate-gitignores.go build/generate-licenses.go build/gocovmerge.go build/lint.go services/archiver/archiver.go services/archiver/archiver_test.go services/comments/comments.go services/externalaccount/user.go services/gitdiff/gitdiff.go services/gitdiff/gitdiff_test.go services/gitdiff/main_test.go services/issue/assignee.go services/issue/assignee_test.go services/issue/content.go services/issue/issue.go services/issue/issue_test.go services/issue/label.go services/issue/label_test.go services/issue/main_test.go services/issue/milestone.go services/issue/status.go services/mailer/mail.go services/mailer/mailer.go services/mailer/mail_comment.go services/mailer/mail_issue.go services/mailer/mail_release.go services/mailer/mail_test.go services/mailer/main_test.go services/mirror/mirror.go services/mirror/mirror_test.go services/pull/check.go services/pull/check_test.go services/pull/commit_status.go services/pull/lfs.go services/pull/main_test.go services/pull/merge.go services/pull/patch.go services/pull/pull.go services/pull/pull_test.go services/pull/review.go services/pull/temp_repo.go services/pull/update.go services/release/release.go services/release/release_test.go services/repository/generate.go services/repository/main_test.go services/repository/push.go services/repository/repository.go services/repository/transfer.go services/repository/transfer_test.go services/webhook/deliver.go services/webhook/deliver_test.go services/webhook/dingtalk.go services/webhook/dingtalk_test.go services/webhook/discord.go services/webhook/feishu.go services/webhook/general.go services/webhook/general_test.go services/webhook/main_test.go services/webhook/matrix.go services/webhook/matrix_test.go services/webhook/msteams.go services/webhook/payloader.go services/webhook/slack.go services/webhook/slack_test.go services/webhook/telegram.go services/webhook/telegram_test.go services/webhook/webhook.go services/webhook/webhook_test.go services/wiki/wiki.go services/wiki/wiki_test.go tools/fuzz.go, ...) failed.
make (e=87): The parameter is incorrect.
make: *** [makefile:229: fmt] Error 87
```

I think the maximum length of 32,767 characters for CreateProcess command is exceeded.

### PR DESCRIPTION
**Pull request by wxiaoguang**
This PR can fix the bug (now the files are feed to the gofmt/misspell batch by batch)

* https://github.com/go-gitea/gitea/issues/14438

And we introduce a new (better) go import formatter. `gofmt`/`goimports` can not group the imports correctly, our formatter can.

### CODE REVIEW

File: cmd/dump.go [hunk 1]
```diff
@@ -21,6 +21,7 @@ import (
 	"code.gitea.io/gitea/modules/util"
 
 	"gitea.com/go-chi/session"
+
```
Comment (lunny) [inline cmd/dump.go]: unnecessary blank line.

File: cmd/web.go [hunk 2]
```diff
@@ -9,17 +9,19 @@ import (
...
+	_ "net/http/pprof" // Used for debugging if enabled and a web server is running
+
 	"code.gitea.io/gitea/modules/graceful"
 	"code.gitea.io/gitea/modules/log"
 	"code.gitea.io/gitea/modules/setting"
 	"code.gitea.io/gitea/routers"
 	"code.gitea.io/gitea/routers/install"
 
 	"github.com/urfave/cli"
+
```
Comment (lunny) [inline cmd/web.go]: as above

File: contrib/environment-to-ini/environment-to-ini.go [hunk 3]
```diff
@@ -15,6 +15,7 @@ import (
 	"code.gitea.io/gitea/modules/util"
 
 	"github.com/urfave/cli"
+
```
Comment (lunny) [inline contrib/environment-to-ini/environment-to-ini.go]: As above

File: contrib/pr/checkout.go [hunk 4]
```diff
@@ -37,6 +37,7 @@ import (
 	"github.com/go-git/go-git/v5"
 	"github.com/go-git/go-git/v5/config"
 	"github.com/go-git/go-git/v5/plumbing"
+
```
Comment (lunny) [inline contrib/pr/checkout.go]: As above

File: integrations/create_no_session_test.go [hunk 5]
```diff
@@ -17,6 +17,7 @@ import (
 	"code.gitea.io/gitea/routers"
 
 	"gitea.com/go-chi/session"
+
```
Comment (lunny) [inline integrations/create_no_session_test.go]: As above

File: integrations/gpg_git_test.go [hunk 6]
```diff
@@ -17,7 +17,9 @@ import (
 	"code.gitea.io/gitea/modules/setting"
 	api "code.gitea.io/gitea/modules/structs"
 	"code.gitea.io/gitea/modules/util"
+
 	"github.com/stretchr/testify/assert"
+
```
Comment (lunny) [inline integrations/gpg_git_test.go]: As above

File: models/db/sql_postgres_with_schema.go [hunk 7]
```diff
@@ -12,6 +12,7 @@ import (
 	"code.gitea.io/gitea/modules/setting"
 
 	"github.com/lib/pq"
+
```
Comment (lunny) [inline models/db/sql_postgres_with_schema.go]: As above

File: cmd/dump.go (hunk 1 above)
Comment (wxiaoguang) [reply cmd/dump.go]: That's necessary, they belongs to different domains in my mind.

**Review by lafriks — APPROVED** [review]

**Review by lunny — APPROVED** [review]
