### PR TITLE
Fix container range bug

### LINKED ISSUE #34792: EOF error when pushing Docker images to Gitea 1.24.1 registry (works fine in 1.24.0)
### Description

# EOF error when pushing Docker images to Gitea 1.24.1 registry (works fine in 1.24.0)

## Description  
When pushing Docker images to the Gitea registry on version 1.24.1, the push fails with an unexpected `EOF` error. The same workflow works without issues on version 1.24.0.

## Steps to reproduce  
1. Build Docker image with `docker build`  
2. Log in to the Gitea registry with `docker login`  
3. Push the image using `docker push`  
4. Push fails with `ERROR: EOF`  

## Expected behavior  
Docker image should push successfully, as it does in Gitea 1.24.0.

## Actual behavior  
Push is interrupted by an unexpected `EOF`, resulting in incomplete upload.

## Environment  
- Gitea version 1.24.1 (failing)  
- Gitea version 1.24.0 (working)  
- Docker version 28.2.2  
- Local network and storage, no MTU or network issues

Please investigate and fix this regression as it breaks CI/CD workflows relying on Docker image pushes.

### Gitea Version

1.24.1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

# Version 1.24.1

# Version 1.24.0
Version 1.24.0

### Git Version

_No response_

### Operating System

Docker Linux x86

### How are you running Gitea?

Docker Compose

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #34792 and add new tests

### CODE REVIEW

File: routers/api/packages/container/container.go [hunk 1]
```diff
@@ -386,7 +388,7 @@ func PatchBlobsUpload(ctx *context.Context) {
 		UploadUUID: uploader.ID,
 		Status:     http.StatusAccepted,
 	}
-	if contentRange != "" {
+	if uploader.Size() > 0 {
```
Comment (hiifong) [inline routers/api/packages/container/container.go:391]: ref: https://github.com/go-gitea/gitea/issues/34792#issuecomment-2991974534

Comment (wxiaoguang) [reply routers/api/packages/container/container.go:391]: What do you mean?

Comment (hiifong) [reply routers/api/packages/container/container.go:391]: Whether uploader.Size() is greater than 0 or not we need to return Range.

Comment (wxiaoguang) [reply routers/api/packages/container/container.go:391]: See my comment in code

> 	// FIXME: undefined behavior when the uploaded content is empty: https://github.com/opencontainers/distribution-spec/issues/578


Then you will get a regression bug: "Bad range" error when pushing images to the container registry #34724

Comment (hiifong) [reply routers/api/packages/container/container.go:391]: I think even if the uploaded content is empty it should return `Range: 0-0`

Comment (hiifong) [reply routers/api/packages/container/container.go:391]: image

Comment (wxiaoguang) [reply routers/api/packages/container/container.go:391]: > I think even if the uploaded content is empty it should return `Range: 0-0`

No, empty content will get "0--1" according to the spec. That's why there is bug "Bad range" error when pushing images to the container registry https://github.com/go-gitea/gitea/issues/34724

```
The <range> refers to the byte range of the chunk, and MUST be inclusive on both ends.
The first chunk's range MUST begin with 0. It MUST match the following regular expression:
   ^[0-9]+-[0-9]+$
```


**inclusive**


Please read https://github.com/opencontainers/distribution-spec/issues/578 again if you still have any question.

Comment (hiifong) [reply routers/api/packages/container/container.go:391]: Please let me try.

Comment (hiifong) [reply routers/api/packages/container/container.go:391]: image

image


I've found another issue where using docker login to gitea times out.

Comment (wxiaoguang) [reply routers/api/packages/container/container.go:391]: I don't think it's related.

Comment (wxiaoguang) [reply routers/api/packages/container/container.go:391]: Is there still any problem? The "timeout" is caused by your network?

Comment (hiifong) [reply routers/api/packages/container/container.go:391]: image

I don't think it's a network problem, I use the main branch to run the.

Comment (wxiaoguang) [reply routers/api/packages/container/container.go:391]: But it is network problem. Have you ever run that way?

why 192.168.5.132 vs localhost

Comment (wxiaoguang) [reply routers/api/packages/container/container.go:391]: Change your ROOT_URL to a URL which can be accessed on both host and container VM

Comment (hiifong) [reply routers/api/packages/container/container.go:391]: image

Comment (hiifong) [reply routers/api/packages/container/container.go:391]: I ran it through the source code

Comment (wxiaoguang) [reply routers/api/packages/container/container.go:391]: > I ran it through the source code

That's why you need to "Change your ROOT_URL to a URL which can be accessed on both host and container VM".

Gitea is running on your host. Docker is running in a VM

Comment (hiifong) [reply routers/api/packages/container/container.go:391]: I tried it. No more problems.

**Review by hiifong — APPROVED** [review]

**Review by lunny — APPROVED** [review]
