### PR TITLE
Fix footnote jump behavior on the issue page.

### LINKED ISSUE #34511: Footnote References Not Properly Scoped to Individual Comments
### description
When using footnotes in bug reports, they are not scoped to the comment. The
`^1` marker always links to the first occurrence of `^1` in the issue.

### to reproduce:
1. Open a bug report with some footnotes
```md
foo[^1][^2]

[^1]: bar
[^2]: baz
```

2. Create a comment on this bug report with a footnote
```md
qux[^1]

[^1]: thud
```

3. Compare the link on the first footnote in the issue description with the link
from the footnote from the comment. They are the same.

### expected:

Footnotes should have some context/scope like GitHub does it
- GitHub's format: `#user-content-fn-1-39ad31d95bf1bd16a061fdbe4a`
- Gitea's current format: `#fn:user-content-1`

### additional notes
Additionally, GitHub's styling is superior. In Gitea, footnotes appear small
and cramped when multiple footnotes reference the same word. The actual listing
of footnotes doesn't feel visually distinct enough compared to what users could
accomplish with typical markdown numbered lists and a `---` separator.
A smaller font size and a slight grey tone would help.

### Gitea Version

1.25.0+dev-61-g9cfcc079c7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

https://demo.gitea.com/

### Database

None

### LINKED ISSUE #34590: Navigation to footnote fragment throws JS error
### Description

When navigating to a footnote html fragment, a JS error is thrown saying the referenced id does not exist.
https://demo.gitea.com/badhezi/test-footnotes/pulls/1#fn:user-content-1

```
JavaScript error: Failed to execute 'querySelector' on 'Document': '#user-content-fn:user-content-1' is not a valid selector. (https://demo.gitea.com/assets/js/index.js?v=1.25.0~dev-90-gd5bbaee64e @ 30:70572). Open browser console to see more details.
```

I'm not sure yet why it tries to find this id (`user-content-fn:user-content-1`) when it's actually `fn:user-content-1`
discovered this when trying to reproduce https://github.com/go-gitea/gitea/issues/34511 which should probably be considered when resolving this as well.

### Gitea Version

1.25.0+dev-90-gd5bbaee64e

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Image

### Git Version

.25.0+dev-90-gd5bbaee64e

### Operating System

_No response_

### How are you running Gitea?

it's demo.gitea.com

### Database

None

### PR DESCRIPTION
**Pull request by charles7668**
Close #34511 
Close #34590 

Add comment ID to the footnote item's id attribute to ensure uniqueness.

### CODE REVIEW

File: modules/markup/html_node.go [hunk 1]
```diff
@@ -27,6 +35,32 @@ func processNodeAttrID(node *html.Node) {
 	}
 }
 
+func processFootnoteID(ctx *RenderContext, node *html.Node) {
+	for idx, attr := range node.Attr {
+		if attr.Key == "id" {
+			if !isAnchorIDFootnote(attr.Val) {
+				return
```
Comment (lunny) [inline modules/markup/html_node.go]: continue?

**Comment by lunny** [comment]
It's better to have a test.

**Comment by lunny** [comment]
Related to #34590

File: modules/markup/html_node.go (hunk 1 above)
Comment (charles7668) [reply modules/markup/html_node.go]: In a normal case, each attribute is only allowed once, so I think returning it directly is fine.

File: modules/markup/html.go [hunk 2]
```diff
@@ -320,6 +320,8 @@ func visitNode(ctx *RenderContext, procs []processor, node *html.Node) *html.Nod
 	}
 
 	processNodeAttrID(node)
+	processFootnoteID(ctx, node)
```
Comment (lunny) [inline modules/markup/html.go]: Perhaps we can merge these two functions, as they aren't used elsewhere.

Comment (charles7668) [reply modules/markup/html.go]: updated

**Review by lunny — DISMISSED** [review]

**Comment by wxiaoguang** [comment]
I think we should do it directly here, instead of the extra post-processing, and remove the "fnref:" prefix (just like GitHub):

<details>

image

</details>

**Comment by wxiaoguang** [comment]
> I think we should do it directly here, instead of the extra post-processing, and remove the "fnref:" prefix (just like GitHub):

To make backport easier, maybe we can use this approach temporarily, will make some new changes.

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]
