### PR TITLE
Fix index too many file names bug

### LINKED ISSUE #28584: search indexer broken: ...exer/code/indexer.go:128:func2() [E] Codes indexer handler: index error for repo 29: fork/exec /usr/bin/git: argument list too long
### Description

the search indexer is not working. the gitea.log gets filled with error messages:

2023/12/22 11:27:05 ...dules/git/command.go:291:Run() [D] git.Command.RunDir(/home/git/gitea-repositories/think-cell/code.git): /usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= ls-tree --full-tree -l df61ef8421d86acd35e2a2f98341646c03b87a3f -- .gitignore .gitmodules [[[[ followed by a endless list of files, part of the repository]]]]

2023/12/22 11:27:33 ...exer/code/indexer.go:128:func2() [E] Codes indexer handler: index error for repo 29: fork/exec /usr/bin/git: argument list too long

Also when we try to search in the repository we receive a 500 error message

### Gitea Version

1.21.3 (and earlier)

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.39.2

### Operating System

Debian 6.1.67-1

### How are you running Gitea?

we run the latest downloadable version.

### Database

None

### LINKED ISSUE #31884: Repeated Queue "code_indexer" failed to handle batch of 1 items error logs
### Description

Error logs appear every couple seconds constantly as app is running, appears to come with a memory leak

Setting `REPO_INDEXER_ENABLED = false` stops the errors

~~Unaware of RAM usage at the time on the machine but after thousands of these logs, the service appeared to stop itself without reason. The shutdown may not be related to this~~

Edit: Found these logs in the event viewer that align with the time gitea stopped

```
Windows successfully diagnosed a low virtual memory condition. The following programs consumed the most virtual memory: gitea.exe (8476) consumed 11716718592 bytes, MsMpEng.exe (8008) consumed 459538432 bytes, and MsSense.exe (3024) consumed 256311296 bytes.
```

```
The gitea service terminated unexpectedly.  It has done this 1 time(s).
```
Maybe this is related to https://github.com/go-gitea/gitea/issues/31565?

```
2024/08/20 10:52:43 cmd/web.go:355:listen() [I] HTTP Listener: 0.0.0.0:3000 Closed
2024/08/20 10:52:43 .../graceful/manager.go:168:doHammerTime() [W] Setting Hammer condition
2024/08/20 10:52:44 .../graceful/manager.go:184:doTerminate() [W] Terminating
2024/08/20 10:52:44 ...er/issues/indexer.go:120:2() [I] PID: 8940 Issue Indexer closed
2024/08/20 10:52:44 ...exer/code/indexer.go:112:func1() [I] PID: 8940 Repository Indexer closed
2024/08/20 10:52:44 cmd/web.go:214:serveInstalled() [I] PID: 8940 Gitea Web Finished
```

Indexer config
```
[indexer]
; ...
REPO_INDEXER_ENABLED = true
REPO_INDEXER_PATH = indexers/repos.bleve
MAX_FILE_SIZE = 1048576
REPO_INDEXER_INCLUDE = 
REPO_INDEXER_EXCLUDE = resources/bin/**
```

Error log:
```
2024/08/20 00:00:01 ...s/actions/cleanup.go:60:cleanNeedDeleteArtifacts() [I] Found 0 artifacts pending deletion
2024/08/20 00:00:03 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 75.8ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:03 ...exer/code/indexer.go:128:func2() [E] Codes indexer handler: index error for repo 78: fork/exec C:\Program Files\Git\cmd\git.exe: The filename or extension is too long.
2024/08/20 00:00:03 ...queue/workergroup.go:107:doWorkerHandle() [E] Queue "code_indexer" failed to handle batch of 1 items, backoff for a few seconds
2024/08/20 00:00:05 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 30.1ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:07 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 28.4ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:09 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 28.8ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:10 ...exer/code/indexer.go:128:func2() [E] Codes indexer handler: index error for repo 78: fork/exec C:\Program Files\Git\cmd\git.exe: The filename or extension is too long.
2024/08/20 00:00:10 ...queue/workergroup.go:107:doWorkerHandle() [E] Queue "code_indexer" failed to handle batch of 1 items, backoff for a few seconds
2024/08/20 00:00:11 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 36.6ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:13 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 62.5ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:15 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 84.1ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:17 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 58.0ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:17 ...exer/code/indexer.go:128:func2() [E] Codes indexer handler: index error for repo 78: fork/exec C:\Program Files\Git\cmd\git.exe: The filename or extension is too long.
2024/08/20 00:00:17 ...queue/workergroup.go:107:doWorkerHandle() [E] Queue "code_indexer" failed to handle batch of 1 items, backoff for a few seconds
2024/08/20 00:00:19 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 312.0ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:21 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 85.3ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:23 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 72.6ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:25 ...exer/code/indexer.go:128:func2() [E] Codes indexer handler: index error for repo 78: fork/exec C:\Program Files\Git\cmd\git.exe: The filename or extension is too long.
2024/08/20 00:00:25 ...queue/workergroup.go:107:doWorkerHandle() [E] Queue "code_indexer" failed to handle batch of 1 items, backoff for a few seconds
2024/08/20 00:00:25 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 299.5ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:27 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 60.5ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:30 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 1177.9ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:31 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 122.9ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:32 ...exer/code/indexer.go:128:func2() [E] Codes indexer handler: index error for repo 78: fork/exec C:\Program Files\Git\cmd\git.exe: The filename or extension is too long.
2024/08/20 00:00:32 ...queue/workergroup.go:107:doWorkerHandle() [E] Queue "code_indexer" failed to handle batch of 1 items, backoff for a few seconds
2024/08/20 00:00:33 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 110.7ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:35 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 639.7ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:37 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 364.4ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:39 ...eb/routing/logger.go:102:func1() [I] router: completed POST /api/actions/runner.v1.RunnerService/FetchTask for 127.0.0.1:51052, 200 OK in 277.2ms @ <autogenerated>:1(http.Handler.ServeHTTP-fm)
2024/08/20 00:00:39 ...exer/code/indexer.go:128:func2() [E] Codes indexer handler: index error for repo 78: fork/exec C:\Program Files\Git\cmd\git.exe: The filename or extension is too long.
```

### Gitea Version

1.22.1 go-git

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.45.2.windows.1

### Operating System

Windows Server 2016

### How are you running Gitea?

Windows gogit exe on prem running a service

### Database

SQLite

### PR DESCRIPTION
**Pull request by lunny**
Try to fix #31884
Fix #28584

### CODE REVIEW

File: modules/indexer/code/git.go [hunk 1]
```diff
@@ -161,15 +162,23 @@ func nonGenesisChanges(ctx context.Context, repo *repo_model.Repository, revisio
...
 			log.Warn("Unrecognized status: %c (line=%s)", status, line)
 		}
-	}
 
-	cmd := git.NewCommand(ctx, "ls-tree", "--full-tree", "-l").AddDynamicArguments(revision).
-		AddDashesAndList(updatedFilenames...)
-	lsTreeStdout, _, err := cmd.RunStdBytes(&git.RunOpts{Dir: repo.RepoPath()})
-	if err != nil {
-		return nil, err
+		if (i%50 == 0 || i == len(lines)-1) && len(updatedFilenames) > 0 {
```
Comment (yp05327) [inline modules/indexer/code/git.go]: Any reason to use 50 here? How to ensure it will not over the limit as we don't check the length of updatedFilenames?

Comment (wolfogre) [reply modules/indexer/code/git.go]: Hmm, I think it should work.

1. The limit of arguments length to execute subprocess is 32,767. See https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa#parameters
2. The limit of file full name length is 260. See https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation
3. So, `50*260 = 13000 < 32767`, bingo!

However, there's some way to [remove the limit](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#registry-setting-to-enable-long-paths) of file full name length. No idea if it's necessary to handle it.

Whatever, this PR can make things better.

**Review by wolfogre — APPROVED** [review]

File: modules/indexer/code/git.go (hunk 1 above)
Comment (lunny) [reply modules/indexer/code/git.go]: I will change it to 30 since https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation#more-information said it's 8191. 8191 / 256 = 31.9 . So maybe 30 is a good digital.

Comment (lunny) [reply modules/indexer/code/git.go]: ecdc522badea9988149306a4db90e06af8415778

**Review by yp05327 — APPROVED** [review]

File: modules/indexer/code/git.go [hunk 2]
```diff
@@ -161,15 +162,25 @@ func nonGenesisChanges(ctx context.Context, repo *repo_model.Repository, revisio
...
+			if err != nil {
+				return nil, err
+			}
+
+			updates, err1 := parseGitLsTreeOutput(lsTreeStdout)
+			if err1 != nil {
+				return nil, err1
+			}
+			changes.Updates = append(changes.Updates, updates...)
+			updatedFilenames = updatedFilenames[0:0]
```
Comment (wxiaoguang) [inline modules/indexer/code/git.go:188]: ~~Is it right?~~

OK, re-use the buffer.

File: modules/indexer/code/git.go [hunk 3]
```diff
@@ -161,15 +162,25 @@ func nonGenesisChanges(ctx context.Context, repo *repo_model.Repository, revisio
...
-	}
 
-	cmd := git.NewCommand(ctx, "ls-tree", "--full-tree", "-l").AddDynamicArguments(revision).
-		AddDashesAndList(updatedFilenames...)
-	lsTreeStdout, _, err := cmd.RunStdBytes(&git.RunOpts{Dir: repo.RepoPath()})
-	if err != nil {
-		return nil, err
+		// According to https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation#more-information
+		// the command line length should less than 8191 characters, assume filepath is 256, then 8191/256 = 31, so we use 30
+		if (i%30 == 0 || i == len(lines)-1) && len(updatedFilenames) > 0 {
```
Comment (wxiaoguang) [inline modules/indexer/code/git.go]: It is wrong here.

If many files are ignored, then `i%30==0` is true, but `updatedFilenames` is empty, and if every file on 30th is ignored, then this `if` block never be executed unless it gets a huge list on the final step.

I think it should check `len(updatedFilenames) >= 30` ?

File: modules/indexer/code/git.go [hunk 4]
```diff
@@ -161,15 +162,25 @@ func nonGenesisChanges(ctx context.Context, repo *repo_model.Repository, revisio
...
+			cmd := git.NewCommand(ctx, "ls-tree", "--full-tree", "-l").AddDynamicArguments(revision).
+				AddDashesAndList(updatedFilenames...)
+			lsTreeStdout, _, err := cmd.RunStdBytes(&git.RunOpts{Dir: repo.RepoPath()})
+			if err != nil {
+				return nil, err
+			}
+
+			updates, err1 := parseGitLsTreeOutput(lsTreeStdout)
```
Comment (wxiaoguang) [inline modules/indexer/code/git.go]: Why not simply use `err`

Comment (lunny) [reply modules/indexer/code/git.go]: Because `err` has been overridden in line 171, now it's a type `runErr git.RunStdError` but not `error`.

File: modules/indexer/code/git.go (hunk 3 above)
Comment (lunny) [reply modules/indexer/code/git.go]: e16bb63be589f15bf32262080ae3fe1b0c574eaf

**Comment by lunny** [comment]
I think all concern issues have been resolved. If there is no further reviews, I will merge this in 3 days.
