### PR TITLE
Fix error when add user has full name to team

### LINKED ISSUE #2962: Cannot add user to organization
version: 1.3.0-rc1
It's OK with v1.2.3 .

Backend: MySQL.

I can add user to the system, but when I try to add it to an organization, it says 'User does not exist.'

### PR DESCRIPTION
**Pull request by lunny**
Will fix #2962.

### CODE REVIEW

File: routers/org/teams.go [hunk 1]
```diff
@@ -76,6 +77,9 @@ func TeamsAction(ctx *context.Context) {
 			return
 		}
 		uname := ctx.Query("uname")
+		if strings.Contains(uname, "(") && strings.HasSuffix(uname, ")") {
```
Comment (ethantkoenig) [inline routers/org/teams.go]: I'm confused as to why this helps. If `uname` has parentheses, then it is not a valid username, so `GetUserByName(name)` in line 84 will just return a `ErrUserNotExist`, right?

Comment (lunny) [reply routers/org/teams.go]: @ethantkoenig Yes, that's what #2973 described.

Comment (lunny) [reply routers/org/teams.go]: Because if some user has set `FullName`, the name submitted will be `loginname (FullName)` but not `loginname`, so it will return ErrUserNotExist. This PR will accept both two kinds requests.

Comment (ethantkoenig) [reply routers/org/teams.go]: Oh I see. Could we please add a comment explaining the situation?

```
// uname may be formatted as "username (fullname)"
```

Comment (lunny) [reply routers/org/teams.go]: done.

**Comment by ethantkoenig** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
also fixed #2726
