### PR TITLE
Remove htmx

### LINKED ISSUE #35059: Proposal: drop htmx
htmx is fun and handy for a small project, but it doesn't work well for a large one.

I can see some fundamental problems due to its fragile design:

1. It supports automatically sending POST methods, but it doesn't support CSP nonce.
    * It makes the website under the XSS-like risk, attacker can inject and execute tags with `hx-xxx` attributes even if the CSP nonce is used
2. It has unclear behaviors, e.g.: when reading a `hx-xxx` on an element, we are not able to know what happens in its parents
    * `https://github.com/bigskysoftware/htmx/issues/2515`
3. Its loading & initialization behavior is quite strange, and unlikely to be fixed
    * `https://github.com/bigskysoftware/htmx/pull/3365`
4. Its "hx script"  support is fragile and unable to lint
5. Developers should always remember to call `htmx.process` when modifying `innerHTML/outerHTML`, but it is frequently forgotten
   * #33851
   * I added the `htmx.process` in #35010 (https://github.com/go-gitea/gitea/commit/a646b328b8ca79fc052c162fdcf0929a4d49e060)
   * Forgotten again https://github.com/go-gitea/gitea/pull/37045#issuecomment-4158552076

And its size is similar to jQuery (not trivial), in Gitea's code base, we only use very a few of htmx's features, which can be implement by ourselves with a better design.

### PR DESCRIPTION
**Pull request by wxiaoguang**
Close #35059

Slightly improved the "fetch action" framework and started adding tests for it.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Should be good enough.

Not too many changes when diff with ignoring spaces https://github.com/go-gitea/gitea/pull/37224/changes?w=1

File: web_src/js/features/common-fetch-action.ts [hunk 1]
```diff
@@ -312,25 +345,27 @@ function initFetchActionTrigger(el: HTMLElement) {
...
     throw new Error(`Unsupported fetch trigger: ${trigger}`);
   }
 }
 
 export function initGlobalFetchAction() {
-  // "fetch-action" is a general approach for elements to trigger fetch requests:
+  // The "fetch-action" framework is a general approach for elements to trigger fetch requests:
   // show confirm dialog (if any), show loading indicators, send fetch request, and redirect or update UI after success.
   //
+  // If you need to fine-grained control more details, sometimes it's clearer to write the logic in JavaScript, instead of using this generic framework.
```
Comment (silverwind) [inline web_src/js/features/common-fetch-action.ts]:
```suggestion
  // If you need more fine-grained control more details, sometimes it's clearer to write the logic in JavaScript, instead of using this generic framework.
```

**Review by silverwind — APPROVED** [review]

**Review by lunny — APPROVED** [review]
