### PR TITLE
Fix markdown image with link

### LINKED ISSUE #4569: Non-SVG image links don't link to intended website
- Gitea version (or commit ref): Tested on 1.2.3 and 40bbc73
- Operating system: Tested on Ubuntu 16.04.5 LTS and Arch Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
    Seems down, so I can't check. 

## Description

When embedding an image with a link like this
`[test](https://example.org)`
in a markdown file in Gitea, it correctly shows as the image and links to the intended website.

Though when the linked image is not an svg, like this
`[test](https://example.org)`
it doesn't link to the intended website, but only to the image itself.

You can see it here: https://git.eisfunke.com/Eisfunke/test/src/branch/master/README.md

On Github it works: https://github.com/Eisfunke/test/blob/master/README.md

### LINKED ISSUE #5207: Markdown Image Hyperlinking Error
- Gitea version (or commit ref): 49d666f
- Git version: N/A
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) @ https://try.gitea.io/issuetestcase1/issuetest
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When adding an image with a link using markdown, attempting to open the link opens the image instead.

I copied the discord button on [this repo](https://github.com/izy521/discord.io/blob/master/README.md)'s README to test as it works great on Github but fails on my repo (obviously I change the parameters to match my discord server).

### PR DESCRIPTION
**Pull request by LER0ever**
**This PR fixes the image with link rendering.** And therefore resolves #4569 and resolves #5207 

### Original Behavior
Images with `alt` will be put inside a link to itself, unless it's an svg-file.

The problem is that it hardcoded the svg filetype to be directly rendered in `` tag, and other file types are rendered like `<a></a>` which causes #4569 and #5207 .

### New Behavior in this PR
Images with `alt` will be put inside a link to itself, unless it's already inside a link, which is `[alt](url)`.
So we don't need to infer from filetype whether the image is a CI image or not. 
Also, this matches the Github-Flavored Markdown's behavior on images with links.

### CODE REVIEW

**Review by techknowlogick — COMMENTED** [review]
Can you add the Gitea copyright at the top of the file?

**Comment by LER0ever** [comment]
> Can you add the Gitea copyright at the top of the file?

@techknowlogick , what do you mean? This is not a new file, and the copyright is already there [markdown.go](https://github.com/go-gitea/gitea/blob/master/modules/markup/markdown/markdown.go)

**Comment by techknowlogick** [comment]
```
// Copyright 2018 The Gitea Authors. All rights reserved.
```
Needs to be added under the Gogs copyright

**Comment by LER0ever** [comment]
I see, fixed in fdd8ceb .

**Comment by lafriks** [comment]
Tests would be needed for this

**Comment by LER0ever** [comment]
@lafriks Tests added for images with links. 

Meanwhile, **although this implementation is definitely gonna work**, I still find this character locating approach a little bit dirty. 
So if anyone has a better one that also processes images with links the same way GitHub does, feel free to replace this one.

File: modules/markup/markdown/markdown.go [hunk 1]
```diff
@@ -104,22 +114,14 @@ func (r *Renderer) Image(out *bytes.Buffer, link []byte, title []byte, alt []byt
 		prefix = util.URLJoin(prefix, "wiki", "raw")
 	}
 	prefix = strings.Replace(prefix, "/src/", "/raw/", 1)
-	if len(link) > 0 {
-		if markup.IsLink(link) {
-			// External link with .svg suffix usually means CI status.
-			// TODO: define a keyword to allow non-svg images render as external link.
-			if bytes.HasSuffix(link, svgSuffix) || bytes.Contains(link, svgSuffixWithMark) {
```
Comment (techknowlogick) [inline modules/markup/markdown/markdown.go:111]: @LER0ever is it ok that the SVG case is no longer being handled?

Comment (LER0ever) [reply modules/markup/markdown/markdown.go:111]: @techknowlogick to be honest I don't see any reason to differentiate svg files with other filetypes. They could all be ci badges or normal images. So I just treated all the images the same.  Do you have any specific case where svgs needs to be handled separatedly?

**Review by techknowlogick — APPROVED** [review]

**Review by lafriks — CHANGES_REQUESTED** [review]

File: modules/markup/markdown/markdown.go (hunk 1 above)
Comment (LER0ever) [reply modules/markup/markdown/markdown.go:111]: @lafriks right, done through faade68

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
@LER0ever  @lafriks  This should be backport to v1.6
