### PR TITLE
Fix SVG size calulation, only use `style` attribute

### LINKED ISSUE #35863: Broken render of some SVGs in diff page
### Description

Some SVGs rendered as empty line in commit/PR/diff page, but at file view page shows as expected. I have no idea what the difference, but this behaviour affects many our custom SVGs exported form Adobe Illustrator. See example at this PR: https://demo.gitea.com/didim99/test/pulls/6/files
File `nonascii.svg` rendered as expected, but `off.svg` is broken. `off.svg` is rendered normally on file view page: https://demo.gitea.com/didim99/test/src/branch/svg-test/svg/off.svg

### Gitea Version

1.24.4 to 1.26.0+dev-105-g685c8c314f

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Image

### Git Version

Not matters

### Operating System

Not matters

### How are you running Gitea?

Using demo.gitea.com, self-hosted

### Database

None

### PR DESCRIPTION
**Pull request by silverwind**
Fixes: https://github.com/go-gitea/gitea/issues/35863

The old code had a conflict between using HTML attributes vs. style properties where the style was overriding the previously set HTML attributes:

```html
<img width="300" height="277.02439470988946" style="width: 275px; height: 0px;">
```

 I made it so in all cases only `style` properties are used and the previous width/height values are now set via `style`. Also I did a number of much-needed typescript improvements to the file.

### CODE REVIEW

File: web_src/js/features/imagediff.ts [hunk 1]
```diff
@@ -3,7 +3,33 @@ import {hideElem, loadElem, queryElemChildren, queryElems} from '../utils/dom.ts
 import {parseDom} from '../utils.ts';
 import {fomanticQuery} from '../modules/fomantic/base.ts';
 
-function getDefaultSvgBoundsIfUndefined(text: string, src: string) {
+type ImageContext = {
+  imageBefore: HTMLImageElement | undefined,
+  imageAfter: HTMLImageElement | undefined,
+  sizeBefore: {width: number, height: number},
+  sizeAfter: {width: number, height: number},
```
Comment (delvh) [inline web_src/js/features/imagediff.ts:10]: Shouldn't those be nullable?

File: web_src/js/features/imagediff.ts [hunk 2]
```diff
@@ -3,7 +3,33 @@ import {hideElem, loadElem, queryElemChildren, queryElems} from '../utils/dom.ts
...
+  maxSize: {width: number, height: number},
+  ratio: [number, number, number, number],
```
Comment (delvh) [inline web_src/js/features/imagediff.ts:12]: And `ratio` as well?

File: web_src/js/features/imagediff.ts [hunk 3]
```diff
@@ -102,115 +129,112 @@ class ImageDiff {
         const resp = await GET(info.path!);
         const text = await resp.text();
         const bounds = getDefaultSvgBoundsIfUndefined(text, info.path!);
+        svgBoundsInfo[index === 0 ? 'after' : 'before'] = bounds;
```
Comment (delvh) [inline web_src/js/features/imagediff.ts:132]: This reads wrong to me: `0 == after, 1 == before` is not how time works.
I think we should swap the list order around.

Comment (wxiaoguang) [reply web_src/js/features/imagediff.ts:132]: > This reads wrong to me: `0 == after, 1 == before` is not how time works.

It is right, and it works. Legacy code did so.

image

image

Comment (silverwind) [reply web_src/js/features/imagediff.ts:132]: Yes I agree, "before" should come before "after".

File: web_src/js/features/imagediff.ts (hunk 1 above)
Comment (silverwind) [reply web_src/js/features/imagediff.ts:10]: Generally I trust typescript to tell me when something needs to be nullable, but I will double check.

File: web_src/js/features/imagediff.ts (hunk 3 above)
Comment (wxiaoguang) [reply web_src/js/features/imagediff.ts:132]: > Yes I agree, "before" should come before "after".

* If it needs to backport, make minimal changes and make backport easier (for example: don't rename `sizes`, don't change the "order", etc)
* If it doesn't need to backport, using named properties instead of array index is better.

Comment (silverwind) [reply web_src/js/features/imagediff.ts:132]: Minimal backport is already done in https://github.com/go-gitea/gitea/pull/36134. We can refactor more here.

File: web_src/js/features/imagediff.ts (hunk 1 above)
Comment (delvh) [reply web_src/js/features/imagediff.ts:10]: I thought this was a refactoring.
As it is right now as a bugfix, it is fine.
I meant conceptually, it sounds like a better idea that these attributes are `null` when the corresponding image is not available instead of using some dummy data.

**Review by delvh — APPROVED** [review]

File: web_src/js/features/imagediff.ts (hunk 1 above)
Comment (silverwind) [reply web_src/js/features/imagediff.ts:10]: It is currently set to `0` as fallback. TBH, I don't want to do much more changes to this file, it's a big mess that needs to be rewritten. I just did the bare minimum changes that get it a bit into shape.

File: web_src/js/features/imagediff.ts (hunk 3 above)
Comment (silverwind) [reply web_src/js/features/imagediff.ts:132]: I guess I'm fine with merging as-is. This file is a mess to be rewritten later. Not much point in wasting time with more refactoring.

**Comment by wxiaoguang** [comment]
Made a small change for the transparent image in #35863

<details>

image

</details>

**Review by wxiaoguang — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by silverwind** [comment]
> Made a small change for the transparent image

BTW this mask image should be made darker in dark theme, I will probably follow up on that later.
