### PR TITLE
Fix required contexts and commit status matching bug

### LINKED ISSUE #34504: Branch protection with required status check
### Description

We have branch protection enabled with required status check set for "Lint yaml files / *".
Administrators must follow branch protection rules is enabled.

The required check failed on this PR. However, I was ​‌able to​‌ merge the PR.

https://gitea.psi.ch/HPCE/hashi-vault/pulls/12/commits
https://gitea.psi.ch/HPCE/hashi-vault/actions/runs/177/jobs/1

### Gitea Version

1.23.8

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

RHEL 9

### How are you running Gitea?

Docker

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by Zettat123**
Fix #34504

Since one required context can match more than one commit statuses, we should not directly compare the lengths of `requiredCommitStatuses` and `requiredContexts`

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: services/pull/commit_status.go [hunk 1]
```diff
@@ -38,20 +38,25 @@ func MergeRequiredContextsCommitStatus(commitStatuses []*git_model.CommitStatus,
...
 		for _, commitStatus := range commitStatuses {
 			if gp.Match(commitStatus.Context) {
 				requiredCommitStatuses = append(requiredCommitStatuses, commitStatus)
-				break
+				requiredContextMatched = true
 			}
 		}
+		if !requiredContextMatched {
+			allRequiredContextsMatched = false
+		}
```
Comment (wxiaoguang) [inline services/pull/commit_status.go]:
```suggestion
		allRequiredContextsMatched = allRequiredContextsMatched && requiredContextMatched
```

**Review by wxiaoguang — APPROVED** [review]

**Comment by Zettat123** [comment]
> I was unable to create a backport for 1.24. @Zettat123, please send one manually. 🍵
> 
> ```
> go run ./contrib/backport 34815
> ...  // fix git conflicts if any
> go run ./contrib/backport --continue
> ```

--> #34829
