### PR TITLE
fix(webhook): prevent tag events from bypassing branch filters targets #35449

### LINKED ISSUE #35449: Tag creation/deletion incorrectly triggers Push webhook (should only emit Create/Delete event)
### Description  
In Gitea 1.22.2, creating or deleting a tag emits a "push" webhook with `ref` set to `refs/tags/...`. 
This behavior triggers CI jobs subscribed to branch push events, even though semantically it's a tag operation.

### Expected Behavior  
Tag creation/deletion should trigger only a `create` or `delete` event—not a `push` event—so that pipelines can be scoped properly.

### Actual Behavior  
Gitea currently sends a `push` webhook for both regular branch pushes and tag events, causing unintended execution in pipelines expecting only branch triggers.

### Steps to Reproduce  
1. Configure a pipeline job with webhook:
   - Trigger On: Push Event  
   - Branch filter: `refs/heads/main`  
2. Create (or delete) a tag in Gitea.  
3. Observe that the pipeline is triggered anyway (because `ref` contains `refs/tags/...`, but the event type is still `push`).

### Proposal  
- Add differentiation in webhook logic: a tag operation should optionally trigger only the `create` or `delete` webhook.
- Or at minimum, support an optional configuration to exclude push events whose `ref` starts with `refs/tags/`.

This change would prevent branch-only pipelines from being inadvertently triggered by tag-related actions.

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.49.0

### Operating System

Windows

### How are you running Gitea?

Windows Service

### Database

None

### PR DESCRIPTION
**Pull request by Exgene**
Tag creation/deletion was triggering push webhooks even when branch
filters were configured, causing unintended pipeline executions.

This change modifies the branch filter logic to check the full ref
name directly instead of first determining if it's a "branch" event.

Fixes: Tag events now properly respect branch filters
- Add getPayloadRef() function to extract full ref names
- Update PrepareWebhook() to use direct ref matching
- Prevents refs/tags/* from matching refs/heads/* filters

Closes #35449

### CODE REVIEW

**Comment by Exgene** [comment]
Im working on adding integration tests for these to check both

- Branch based filters 
- Tags

**Comment by wxiaoguang** [comment]
I did some refactoring to use "git.RefName" type , to avoid abuses.

Now, we have a new problem, see the FIXME

File: services/webhook/webhook.go [hunk 1]
```diff
@@ -144,11 +147,12 @@ func PrepareWebhook(ctx context.Context, w *webhook_model.Webhook, event webhook
...
-	// If payload has no associated branch (e.g. it's a new tag, issue, etc.),
-	// branch filter has no effect.
-	if branch := getPayloadBranch(p); branch != "" {
-		if !checkBranch(w, branch) {
-			log.Info("Branch %q doesn't match branch filter %q, skipping", branch, w.BranchFilter)
+	// Apply the filter directly to the ref name
+	if ref := getPayloadRef(p); ref != "" {
+		// FIXME: here comes the problem, "ref" is the full ref name, but the filter
+		// But, "checkBranch" check it against "w.BranchFilter", does it make sense?
+		if !checkBranch(w, ref) {
```
Comment (wxiaoguang) [inline services/webhook/webhook.go]: In `checkBranch`, it checks the input against the "BranchFilter".

The reference for "BranchFilter" is like this: `Examples: master, {master,release*}.`, this is no `refs/heads` prefix.

Comment (Exgene) [reply services/webhook/webhook.go]: Oh right its checking the full name against the filter, I should extract the base name right?

Comment (wxiaoguang) [reply services/webhook/webhook.go]: > Oh right its checking the full name against the filter, I should extract the base name right?

It will still have a problem: what if the tag name matches the filter ...

----

I have some ideas to make it support branches & tags together, let me try.

Comment (Exgene) [reply services/webhook/webhook.go]: We could check if the ref is of type branch or tag and apply filters that way right?

**Comment by wxiaoguang** [comment]
Made some changes in https://github.com/go-gitea/gitea/pull/35567/commits/b9484cfd944a01f44a51b37d93c045de8a286d19 and added some tests:

Now, branch name and full git ref are all supported.

image

**Comment by Exgene** [comment]
Yeah cool i was thinking something along the same lines ig

Thanks i would love to contribute more.

**Review by wxiaoguang — APPROVED** [review]

**Comment by silverwind** [comment]
image

Can we make contrast of the `<code>` text a bit better? e.g. use a more intense shade of `--color-text-*`. Maybe there are also suitable `label` text colors.

**Comment by wxiaoguang** [comment]
> Can we make contrast of the `<code>` text a bit better? e.g. use a more intense shade of `--color-text-*`. Maybe there are also suitable `label` text colors.

They are already using label colors. If you don't like, please edit directly.

<details>

image

</details>

**Comment by wxiaoguang** [comment]
> > Can we make contrast of the `<code>` text a bit better? e.g. use a more intense shade of `--color-text-*`. Maybe there are also suitable `label` text colors.
> 
> They are already using label colors. If you don't like, please edit directly.

I think the current styles are right. Because ".form .help" has its own text color, intentionally we don't want much contrast here.

**Comment by silverwind** [comment]
> > > Can we make contrast of the `<code>` text a bit better? e.g. use a more intense shade of `--color-text-*`. Maybe there are also suitable `label` text colors.
> > 
> > 
> > They are already using label colors. If you don't like, please edit directly.
> 
> I think the current styles are right. Because ".form .help" has its own text color, intentionally we don't want much contrast here.

I changed it because current colors surely won't pass WICG contrast requirements. I've added label foreground color which I think looks alright:

image

**Comment by wxiaoguang** [comment]
Not sure whether it looks good to you. It's up to you.

<details>

image

image

</details>

**Comment by silverwind** [comment]
It looks acceptable. The only other idea is to introduce a new color with a slightly less intense color.

**Comment by silverwind** [comment]
Slightly tweaked it for these help texts:

image

**Review by lunny — APPROVED** [review]
