### PR TITLE
Fix missing branch in release bug

### LINKED ISSUE #3066: Release for old tag not initialized correctly in frontend
- Gitea version (or commit ref): 1.3.0
- Git version: 2.11
- Operating system: Linux amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/test/test-3066/)
  - [ ] No
  - [ ] Not relevant
- Log gist: -

## Description

When creating a release from an old tag, the description is not initialized correctly, as branch and number of commits since this release are missing. Commit hash is shown correctly.
The latest release yet shows correctly shows e.g. `5 commits to master since this release`.
The fresh created older release always shows `0 commits to since this release` (branch missing)

**Reproduce:**
* Go to "Releases" on a project wiht multiple unreleased tags
* Draft a new release 
* Select branch. fill tag name and description and release

## Screenshots
screenshot_20171202-210620

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fixes #3066. Previously, the `target` of a release would not be set if the tag already existed.

### CODE REVIEW

**Comment by lafriks** [comment]
Is it possible to add migration to fix broken data?

**Comment by ethantkoenig** [comment]
@lafriks There's no way to know what branch the releases were intended to be targeted against.

File: modules/test/context_tests.go [hunk 1]
```diff
@@ -51,6 +52,13 @@ func LoadUser(t *testing.T, ctx *context.Context, userID int64) {
 	ctx.User = models.AssertExistsAndLoadBean(t, &models.User{ID: userID}).(*models.User)
 }
 
+func LoadGitRepo(t *testing.T, ctx *context.Context) {
```
Comment (lunny) [inline modules/test/context_tests.go]: Comment or CI failed.

**Review by lunny — CHANGES_REQUESTED** [review]

File: modules/test/context_tests.go (hunk 1 above)
Comment (ethantkoenig) [reply modules/test/context_tests.go]: just fixed it

Comment (lunny) [reply modules/test/context_tests.go]: No. you didn't, it should `LoadGitRepo` not `LoadRepo`.

Comment (ethantkoenig) [reply modules/test/context_tests.go]: good catch, actually fixed now

**Comment by lafriks** [comment]
LGTM

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
@ethantkoenig please send a backport to release/v1.3
