### PR TITLE
Fix gpg wrong column types

### LINKED ISSUE #1283: MYSQL: Database error on installation
- Gitea version (or commit ref): 447c9b428f4cf50174ef7f3fbea56b5405f6bbf8
- Git version: 2.1.4
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist: https://gist.github.com/Schizopriest/d6ccdad0170812dfb5bc510f8c283d76

## Description

Getting the following Database Error when installing on a empty Database.
`Database setting is not correct: Error 1170: BLOB/TEXT column 'key_id' used in key specification without a key length`

MySQL-Server Version: `10.0.30-MariaDB-0+deb8u1`

## Screenshots
image

### PR DESCRIPTION
**Pull request by lunny**
This will fix #1283  @sapk could you confirm this will not break GPG feature?

### CODE REVIEW

**Comment by sapk** [comment]
This should be ok but I will test it in 4 hour after work.

The migration is a little hard but we don't care at this stage ^^

The test build seem broken ...

**Comment by sapk** [comment]
API work perfect but can't confirm if it fix mariadb compat prob right now. I trust you on that ^^

**Comment by fabian-z** [comment]
This fixes the issue for me on MariaDB 10.1.21

**Comment by strk** [comment]
Trusted LGTM

**Comment by strk** [comment]
Trusted LGTM

File: models/migrations/v24.go [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+		AddedUnix         int64
+		SubsKey           []*GPGKey `xorm:"-"`
+		Emails            []*EmailAddress
+		CanSign           bool
+		CanEncryptComms   bool
+		CanEncryptStorage bool
+		CanCertify        bool
+	}
+
+	if err := x.DropTables(new(GPGKey)); err != nil {
```
Comment (bkcsoft) [inline models/migrations/v24.go:45]: So you're dropping all added GPG-keys? 😱

**Review by bkcsoft — CHANGES_REQUESTED** [review]

File: models/migrations/v24.go (hunk 1 above)
Comment (sapk) [reply models/migrations/v24.go:45]: For now they shouldn't have any key in most db since the only available method is through the API.

Comment (strk) [reply models/migrations/v24.go:45]: Then why migrate at all ?

Comment (sapk) [reply models/migrations/v24.go:45]: Because if someone allready upgrade to master (with a other backend than mariadb) he will not have the same table that the one that don't ?

Comment (lunny) [reply models/migrations/v24.go:45]: Like @sapk said, no UI to do that and no body could really add a gpgkey since #1283 will refuse that. And change a column is so different between different database that drop a table and create it will a better method.

**Review by bkcsoft — APPROVED** [review]

**Comment by bkcsoft** [comment]
LGTM

File: models/migrations/v24.go (hunk 1 above)
Comment (bkcsoft) [reply models/migrations/v24.go:45]: @lunny Might be a good idea to add that to the description next time 😉
