### PR TITLE
Fix so that user can still fork his own repository to his organizations

### LINKED ISSUE #2698: Regression: no longer possible to fork own repo
(Taking the liberty to open a new issue since this was only discussed in closed issues and risks therefore to become invisible.)

- Gitea version (or commit ref): 1.2
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/bard/test (hovering on "Fork" says "You cannot fork a repository you already own")

## Description

I described the rationale for forking one's own repo back when I was using gogs in https://github.com/gogits/gogs/issues/1791#issuecomment-278899979. @lunny replied in https://github.com/gogits/gogs/issues/1791#issuecomment-278905982 that Gitea had [implemented it](https://github.com/go-gitea/gitea/pull/761) so I switched to Gitea, as it's a make-or-break feature in my case; several projects I'm working on are now arranged around this possibility. Unfortunately it was subsequently removed in https://github.com/go-gitea/gitea/issues/2019 to solve a separate issue.

I'd really like to stay on top of Gitea development, especially seeing all the goodies and fixes that went into 1.2, but for now I'm frozen at 1.1. Anything I can do to help? I'm glad to do testing; also willing to code, but since I never touched Go I'm not sure any code I'd produce would qualify as "help".

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #2698

Allows forking to organization even when user owns repository or has already forked to his user but still limits single fork per user/organization

### CODE REVIEW

File: models/repo.go [hunk 1]
```diff
@@ -634,6 +634,25 @@ func (repo *Repository) CanBeForked() bool {
...
+		return false, nil
+	}
+	if repo.OwnerID != user.ID && !user.HasForkedRepo(repo.ID) {
+		return true, nil
+	}
+	if err := user.GetOrganizations(true); err != nil {
+		return false, err
+	}
+	for _, org := range user.Orgs {
+		if !org.HasForkedRepo(repo.ID) {
```
Comment (lunny) [inline models/repo.go]: maybe 
```Go
if org.HasForkedRepo(repo.ID) {
    return false
}
}
return true

**Review by lunny — CHANGES_REQUESTED** [review]

**Comment by lunny** [comment]
Otherwise LGTM

File: models/repo.go (hunk 1 above)
Comment (daviian) [reply models/repo.go]: Not possible, since it would stop looping of all left organizations if first has already forked the repository.

Comment (lafriks) [reply models/repo.go]: @lunny No, that would not work correct. We are looking in this code to check if user has at least one organization that has **not** forked repository yet. And if user has forked && all orgs has forks than it is not possible to fork anymore - so return false

File: routers/repo/pull.go [hunk 2]
```diff
@@ -61,6 +61,8 @@ func getForkRepository(ctx *context.Context) *models.Repository {
 	ctx.Data["repo_name"] = forkRepo.Name
 	ctx.Data["description"] = forkRepo.Description
 	ctx.Data["IsPrivate"] = forkRepo.IsPrivate
+	canForkToUser := !ctx.User.HasForkedRepo(forkRepo.ID)
+	ctx.Data["CanForkToUser"] = canForkToUser
```
Comment (daviian) [inline routers/repo/pull.go]: Should a user be able to fork his own repo into his user?

**Review by daviian — CHANGES_REQUESTED** [review]

File: models/repo.go [hunk 3]
```diff
@@ -634,6 +634,25 @@ func (repo *Repository) CanBeForked() bool {
...
 
+// CanUserFork returns true if specified user can fork repository.
+func (repo *Repository) CanUserFork(user *User) (bool, error) {
+	if user == nil {
+		return false, nil
+	}
+	if repo.OwnerID != user.ID && !user.HasForkedRepo(repo.ID) {
+		return true, nil
+	}
+	if err := user.GetOrganizations(true); err != nil {
```
[the remark this answers is not in the document]
Comment (Morlinest) [reply models/repo.go]: I think `user.GetOwnedOrganizations()` can be used.

File: models/repo.go [hunk 4]
```diff
@@ -634,6 +634,25 @@ func (repo *Repository) CanBeForked() bool {
...
+		return false, err
+	}
+	for _, org := range user.Orgs {
```
Comment (Morlinest) [inline models/repo.go]: `user.OwnedOrgs` (with previous use of `user.GetOwnedOrganizations()`)

**Review by Morlinest — CHANGES_REQUESTED** [review]

File: models/repo.go (hunk 1 above)
Comment (lunny) [reply models/repo.go]: @lafriks OK. I see.

File: routers/repo/pull.go [hunk 5]
```diff
@@ -73,7 +75,19 @@ func getForkRepository(ctx *context.Context) *models.Repository {
 		ctx.Handle(500, "GetOrganizations", err)
 		return nil
 	}
-	ctx.Data["Orgs"] = ctx.User.Orgs
+	var orgs []*models.User
+	for _, org := range ctx.User.Orgs {
```
Comment (Morlinest) [inline routers/repo/pull.go]: Same as above (https://github.com/go-gitea/gitea/pull/2699/files#diff-d4e2553a87eb8b329efd7335f028903cR648) as Orgs includes also organizations where you are in team that have only read rights.

**Review by Morlinest — CHANGES_REQUESTED** [review]

**Comment by ethantkoenig** [comment]
Can we please add a test to prevent another regression?

**Comment by lafriks** [comment]
@lunny @Morlinest @daviian fixed all suggestions

**Comment by lafriks** [comment]
@ethantkoenig integration test added

File: integrations/repo_fork_test.go [hunk 6]
```diff
@@ -5,19 +5,20 @@
...
 import (
+	"fmt"
 	"net/http"
 	"testing"
 
 	"github.com/stretchr/testify/assert"
 )
 
-func testRepoFork(t *testing.T, session *TestSession) *TestResponse {
+func testRepoFork(t *testing.T, session *TestSession, ownerName, repoName, forkOwnerName, forkOwnerID, forkRepoName string) *TestResponse {
```
Comment (ethantkoenig) [inline integrations/repo_fork_test.go]: nit: instead of requiring caller to specify `forkOwnerID`, we can infer it from `forkOwnerName`:
```
forkOwner := AssertExistsAndLoadBean(t, &models.User{Name: forkOwnerName}).(*models.User)
...
forkOwner.ID
```

File: routers/repo/pull.go [hunk 7]
```diff
@@ -69,11 +71,23 @@ func getForkRepository(ctx *context.Context) *models.Repository {
...
+	var orgs []*models.User
+	for _, org := range ctx.User.OwnedOrgs {
+		if forkRepo.OwnerID != org.ID && !org.HasForkedRepo(forkRepo.ID) {
+			orgs = append(orgs, org)
+		}
+	}
+	ctx.Data["Orgs"] = orgs
+
+	if canForkToUser {
+		ctx.Data["ContextUser"] = ctx.User
```
Comment (ethantkoenig) [inline routers/repo/pull.go:87]: In both places where `getForkRepository()` is called (`Fork` and `ForkPost` in routers/repo/pull.go), `ctx.Data["ContextUser"]` is immediately overwritten after this function is called.

**Review by ethantkoenig — CHANGES_REQUESTED** [review]

File: integrations/repo_fork_test.go (hunk 6 above)
Comment (lafriks) [reply integrations/repo_fork_test.go]: @ethantkoenig thanks, done

File: routers/repo/pull.go (hunk 7 above)
Comment (lafriks) [reply routers/repo/pull.go:87]: @ethantkoenig it is not overwritten in `Fork` handler only in `ForkPost`. It is intentional so - `getForkRepository` fills in default `ctx.Data["ContextUser"]` value and in `ForkPost` it is overwritten by actually selected one from dropdown box.

Comment (ethantkoenig) [reply routers/repo/pull.go:87]: Oh, I missed that you had removed that line

**Review by ethantkoenig — APPROVED** [review]

**Comment by ethantkoenig** [comment]
LGTM

**Review by lunny — APPROVED** [review]

**Comment by lunny** [comment]
@daviian @Morlinest needs your approvals.

**Review by Morlinest — APPROVED** [review]

**Review by daviian — APPROVED** [review]

**Comment by lafriks** [comment]
Make LG-TM work again
