### PR TITLE
Fix possible ui 500 if workflow's job is nil

### LINKED ISSUE #31087: [Bug: 1.22.0-rc1] Actions interface is replaced by errors on validation fail
### Description

when having an empty jop
- the runner is acting normally in the background
- All the site is acting normally
except the actoins section of that repo which generates 500

I'm almost sure that there is an error handling that is missing in the interface

> not to mention that this error may be generated before even listing the jops so it may be related to gitea-actions too

### Screenshots

this what cased the error
> notice the two jops and the unformated yml

Screenshot_20240526_215658

those errors shouldn't appear here like this
the interface should tell that the file is invalid
Screenshot_20240526_215819

the interface go back to normal once the jop has any decendant yml
> this is a test from demo.gitea.com 1.23.0+dev-127-g2ced31e81d

Screenshot_20240526_220934

### Gitea Version

1.22.0-rc1, 1.23.0+dev

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

demo.gitea.com, dockerized

### Browser Version

Google Chrome: 125.0.6422.112 (Official Build)

### PR DESCRIPTION
**Pull request by lunny**
Fix #31087

### CODE REVIEW

**Review by Zettat123 — APPROVED** [review]

File: routers/web/repo/actions/actions.go [hunk 1]
```diff
@@ -107,7 +107,12 @@ func List(ctx *context.Context) {
 			// The workflow must contain at least one job without "needs". Otherwise, a deadlock will occur and no jobs will be able to run.
 			hasJobWithoutNeeds := false
 			// Check whether have matching runner and a job without "needs"
+			emptyJobsNumber := 0
```
Comment (yp05327) [inline routers/web/repo/actions/actions.go:110]: Do we really need this? If no job in Jobs, then we will show `no_job_without_needs` error.
IMO, only skip empty job is enough.

And maybe we need add this case in tests.

And should we move `hasJobWithoutNeeds` check into `ReadWorkflow`? As it seems that the workflows which have no job without needs, are invalid workflows?

Comment (lunny) [reply routers/web/repo/actions/actions.go:110]: It's necessary because an empty job will become a `nil` value of a map. .ie.

```yaml
on: [push]

jobs:
  jobs:
```

Comment (wolfogre) [reply routers/web/repo/actions/actions.go:110]: This PR LGTM as a quick fix.

And I also agree refactor it later, move `no_job_without_needs` and `no_job` to `ReadWorkflow`, the error is just `invalid_workflow`.

**Review by wolfogre — APPROVED** [review]

**Comment by yp05327** [comment]
> And I also agree refactor it later, move no_job_without_needs and no_job to ReadWorkflow, the error is just invalid_workflow.

emmm, don't forget doing it. Then it is ok.
