### PR TITLE
Fix a panic in NotifyCreateIssueComment (caused by string truncation)

### LINKED ISSUE #17927: A panic in `modules/notification/action/action.go:106`: runtime error: slice bounds out of range [:-1]
I just saw this, record it here (haven't analyzed yet 😂)

Gitea 1.16 main

```
2021/12/07 17:58:06 routers/web/base.go:130:1() [E] PANIC: runtime error: slice bounds out of range [:-1]
	/usr/local/go/src/runtime/panic.go:100 (0x432734)
	/build/work/gitea/modules/notification/action/action.go:106 (0x14d5b34)
	/build/work/gitea/modules/notification/notification.go:45 (0x18dd2f5)
	/build/work/gitea/services/comments/comments.go:35 (0x1cce77c)
	/build/work/gitea/routers/web/repo/issue.go:2154 (0x1d04a44)
	/build/work/gitea/modules/web/route.go:74 (0x1c84684)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/vendor/github.com/go-chi/chi/v5/mux.go:442 (0x14abf55)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/modules/web/route.go:113 (0x1c84e65)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/modules/web/route.go:113 (0x1c84e65)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/modules/web/route.go:113 (0x1c84e65)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/vendor/github.com/go-chi/chi/v5/middleware/get_head.go:37 (0x1cb10c4)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/modules/web/route.go:113 (0x1c84e65)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/modules/context/context.go:770 (0x14bd7f0)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/vendor/github.com/go-chi/chi/v5/mux.go:71 (0x14a9d8c)
	/build/work/gitea/vendor/github.com/go-chi/chi/v5/mux.go:314 (0x14ab73b)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/vendor/github.com/go-chi/chi/v5/mux.go:442 (0x14abf55)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/routers/web/base.go:169 (0x1e61cda)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/vendor/gitea.com/go-chi/session/session.go:257 (0x12869bd)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/modules/public/public.go:42 (0x132be1b)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/vendor/github.com/go-chi/chi/v5/mux.go:71 (0x14a9d8c)
	/build/work/gitea/vendor/github.com/go-chi/chi/v5/mux.go:314 (0x14ab73b)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/vendor/github.com/go-chi/chi/v5/mux.go:442 (0x14abf55)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/routers/common/middleware.go:75 (0x1cb9361)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/routers/common/logger.go:23 (0x1cb6f04)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/vendor/github.com/go-chi/chi/v5/middleware/strip.go:30 (0x1cb3e78)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/vendor/github.com/chi-middleware/proxy/middleware.go:37 (0x1cb0736)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/routers/common/middleware.go:28 (0x1cb91b9)
	/usr/local/go/src/net/http/server.go:2046 (0x77378e)
	/build/work/gitea/vendor/github.com/go-chi/chi/v5/mux.go:88 (0x14a9d41)
	/build/work/gitea/modules/web/route.go:328 (0x1c87ccd)
	/usr/local/go/src/net/http/server.go:2878 (0x776cfa)
	/usr/local/go/src/net/http/server.go:1929 (0x772867)
	/usr/local/go/src/runtime/asm_amd64.s:1581 (0x468c80)
```

### PR DESCRIPTION
**Pull request by wxiaoguang**
Close
* https://github.com/go-gitea/gitea/issues/17927

Fix #17927

### CODE REVIEW

File: modules/notification/action/action.go [hunk 1]
```diff
@@ -100,14 +101,15 @@ func (a *actionNotifier) NotifyCreateIssueComment(doer *user_model.User, repo *m
 		IsPrivate: issue.Repo.IsPrivate,
 	}
 
-	content := ""
-
-	if len(comment.Content) > 200 {
-		content = comment.Content[:strings.LastIndex(comment.Content[0:200], " ")] + "…"
-	} else {
-		content = comment.Content
+	truncatedContent, truncatedRight := util.SplitStringAtRuneN(comment.Content, 200)
```
Comment (zeripath) [inline modules/notification/action/action.go]: I think this one is intended to be bytes not runes

File: modules/util/truncate.go [hunk 2]
```diff
@@ -6,20 +6,23 @@ package util
 
 import "unicode/utf8"
 
+// in UTF8 "…" is 3 bytes so doesn't really gain us anything...
+const utf8Ellipsis = "…"
+const asciiEllipsis = "..."
```
Comment (zeripath) [inline modules/util/truncate.go:11]: I don't think these constants help clarify the code or help us to understand what's going on better.

However if you really think it helps then fine.

**Review by zeripath — APPROVED** [review]
If you're sure that this should be Runes and not Bytes then LGTM

File: modules/notification/action/action.go (hunk 1 above)
Comment (wxiaoguang) [reply modules/notification/action/action.go]: I was thinking about `varchar(10)` is rune-based. 😂

Actually using `SplitStringAtByteN` seems better and the database column is `TEXT`.

Updated.

File: modules/util/truncate.go (hunk 2 above)
Comment (wxiaoguang) [reply modules/util/truncate.go:11]: "…" and "..." are used in many places (including in unit test), so I introduce these two `const` to help, otherwise, we would copy&paste these two strings many times.

**Review by lunny — APPROVED** [review]
