### PR TITLE
Fix error when calculate the repository size

### LINKED ISSUE #22386: Failed to update size for repository by a race condition
### Description

```
2023/01/06 22:05:35 ...s/repository/push.go:100:pushUpdates() [E] [63b89b2f-14] Failed to update size for repository: updateSize: lstat /mnt/ceph-cluster/git/gitea-repositories/<user>/blog.git/refs/heads/<somefile>.lock: no such file or directory
```

There is a race condition regarding updating the repo size while processing pushes.

It is observed:
1. there is no protection in func [`GetDirectorySize`](https://github.com/go-gitea/gitea/blob/main/modules/util/path.go#L28) regarding the existence of the path. If the path does not exist, a response of size 0 would be a good response so as not to cause an error. For example, [this error 500](https://github.com/go-gitea/gitea/issues/14517) is thrown due to bad code in the caller.
1. There is no exclusion for lock files. If concurrency is not even implemented, then a straightforward solution is to exclude lock files (their existence implying a not handled race condition), allowing the wrong size to be fetched, in favour of not failing an important thread just because of the size calculation. `filepath.WalkFunc` could handle this case by checking the `os.Lstat` error and the `lock` suffix of the filename. For example [this error handling](https://github.com/go-gitea/gitea/blame/main/routers/web/user/setting/profile.go#L285) is done by another very similar code with the suggested protection but even more general than excluding non-existing lock files.
1. The Go developers suggest using `filepath.WalkDir` instead of `filepath.Walk` because [*Walk is less efficient than WalkDir, introduced in Go 1.16, which avoids calling `os.Lstat` on every file or directory visited](https://pkg.go.dev/path/filepath#Walk). The call uses a different walk function, but is very easy to adapt.

Originally reported in https://codeberg.org/forgejo/forgejo/issues/216

### Gitea Version

1.18.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

systemd

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix #22386 

`GetDirectorySize` moved as `getDirectorySize` because it becomes a special function which should not be put in `util`.

### CODE REVIEW

File: modules/util/path.go [hunk 1]
```diff
@@ -22,19 +22,7 @@ func EnsureAbsolutePath(path, absoluteBase string) string {
 	return filepath.Join(absoluteBase, path)
 }
```
Comment (wolfogre) [inline modules/util/path.go:24]:
```suggestion
```

File: modules/util/path.go [hunk 2]
```diff
@@ -22,19 +22,7 @@ func EnsureAbsolutePath(path, absoluteBase string) string {
...
-	var size int64
-	err := filepath.Walk(path, func(_ string, info os.FileInfo, err error) error {
-		if info != nil && (info.Mode()&notRegularFileMode) == 0 {
-			size += info.Size()
-		}
-		return err
-	})
-	return size, err
-}
+
```
Comment (wolfogre) [inline modules/util/path.go]:
```suggestion
```

File: modules/repository/create.go [hunk 3]
```diff
@@ -285,9 +286,30 @@ func CreateRepository(doer, u *user_model.User, opts CreateRepoOptions) (*repo_m
 	return repo, nil
 }
 
-// UpdateRepoSize updates the repository size, calculating it using util.GetDirectorySize
+const notRegularFileMode os.FileMode = os.ModeSymlink | os.ModeNamedPipe | os.ModeSocket | os.ModeDevice | os.ModeCharDevice | os.ModeIrregular
```
Comment (wolfogre) [inline modules/repository/create.go]:
```suggestion
const notRegularFileMode = os.ModeSymlink | os.ModeNamedPipe | os.ModeSocket | os.ModeDevice | os.ModeCharDevice | os.ModeIrregular
```

**Comment by strk** [comment]
LGTM thanks

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
make lgtm work

**Comment by zeripath** [comment]
Please send backport
