### PR TITLE
Fix download file wrong content-type

### LINKED ISSUE #9799: File encoding wrong in raw page and bleam page.
- Gitea version (or commit ref):1.10.2
My file is GB2312,but raw page response UTF8 code .    
`Content-Type: text/plain; charset=utf-8`

image

### PR DESCRIPTION
**Pull request by lunny**
Fix #9799

### CODE REVIEW

File: routers/repo/download.go [hunk 1]
```diff
@@ -33,7 +34,12 @@ func ServeData(ctx *context.Context, name string, reader io.Reader) error {
 	name = strings.Replace(name, ",", " ", -1)
 
 	if base.IsTextFile(buf) || ctx.QueryBool("render") {
-		ctx.Resp.Header().Set("Content-Type", "text/plain; charset=utf-8")
+		cs, err := charset.DetectEncoding(buf)
+		if err != nil {
+			log.Error("Detect raw file %s charset failed: %v, just ignored", name, err)
```
Comment (sapk) [inline routers/repo/download.go]:
```suggestion
			log.Error("Detect raw file %s charset failed: %v, using by default utf-8", name, err)
```

**Review by sapk — APPROVED** [review]
I would change the error text to be more precise but still LGTM

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@lunny waiting for the backport ;)
