### PR TITLE
Fix sorting admin user list by last login

### LINKED ISSUE #14942: Admin user listing: sort by last sign-in broken
- Gitea version (or commit ref): 1.13.4
- Git version:
- Operating system: linux
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Screenshots
grafik

also note the bad alignment of the create user button ;)

### PR DESCRIPTION
**Pull request by aceArt-GmbH**
Admin User Account list sorted via table header:

compare

`updated_unix` is not the same as "Last Sign-In"

Fixes #14942

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]
LGTM and it will replace a very old PR:
* #14947

And although the `RenderUserSearch` is shared by other pages, IMO it's fine to add these two new cases.

**Review by yardenshoham — APPROVED** [review]

File: routers/web/explore/user.go [hunk 1]
```diff
@@ -68,6 +68,10 @@ func RenderUserSearch(ctx *context.Context, opts *user_model.SearchUserOptions,
 		orderBy = "`user`.updated_unix ASC"
 	case "reversealphabetically":
 		orderBy = "`user`.name DESC"
+	case "lastlogin":
+		orderBy = "`user`.last_login_unix ASC"
+	case "reverselastlogin":
```
Comment (delvh) [inline routers/web/explore/user.go:73]: Alternatively, what about `oldestlogin`?

**Review by delvh — APPROVED** [review]

**Comment by jolheiser** [comment]
🎺 🤖
