### PR TITLE
Fix issue label delete incorrect labels webhook payload

### LINKED ISSUE #34560: Webhook label_updated contains no labels when using the web interface
### Description

Hello,
I have an issue with 2 labels `A` and `B` (`A` is exclusive but I don't think that matters). When I remove `B` via the web interface, then I get a `label_updated` webhook json with an empty `labels` array.
When I do this via the api with `DELETE /repos/{owner}/{repo}/issues/{index}/labels/{id}` I get a correct `labels` array with `A` in it.

### Gitea Version

1.23.8

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

I don't know

### Database

None

### PR DESCRIPTION
**Pull request by badhezi**
Fixes https://github.com/go-gitea/gitea/issues/34560
explanation of the bug in the issue

setting `issue.isLabelsLoaded = false` before calling `deleteIssueLabel` guarantee we will load the new state of the labels into the issue object before sending it in the webhook.

### CODE REVIEW

File: models/issues/issue_label.go [hunk 1]
```diff
@@ -201,6 +201,7 @@ func deleteIssueLabel(ctx context.Context, issue *Issue, label *Label, doer *use
 
 // DeleteIssueLabel deletes issue-label relation.
 func DeleteIssueLabel(ctx context.Context, issue *Issue, label *Label, doer *user_model.User) error {
+	issue.isLabelsLoaded = false
```
Comment (lunny) [inline models/issues/issue_label.go]: Move it to line 209?

**Review by lunny — APPROVED** [review]

**Review by hiifong — APPROVED** [review]
