### PR TITLE
Branches not at ref commit ID should not be listed as Merged

### LINKED ISSUE #9158: Closed pull requests retain no information about deleted branches
- Gitea version (or commit ref): 1.10.0
- Git version: n/a
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes: https://try.gitea.io/themightychris/test/pulls/2
  - [ ] No
  - [ ] Not relevant

## Description

When the branch behind a closed pull request gets deleted, _all_ information about the branch appears to be lost (whether the branch is deleted through Git or through the provided button in the pull request)

Observed behavior: The pull request does not retain the name of the branch, the pushed commits, or the diffs and does not offer a restore branch button

Expected behavior: A closed PR will permanently store a ref to the tip of the deleted branch, enabling its commit list and files changed views to continue working, contextual comments to continue to be read, and the branch to be restorable from the commit preserved by the PR.

## Screenshots

image

### LINKED ISSUE #9201: Gitea does not clean up old reverences on branch delete
- Gitea version (or commit ref): 1.10.0
- Git version: Docker image
- Operating system: Docker image
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (On try.gitea.io, deleted branches are not kept)
  - [ ] Not relevant
- Log gist:

## Description

Hello,

Following a Discord discussion, i create this issue about deleted branches. Sometimes i meet issues when i delete my `develop` branch and repush an other branch also named `develop`.

My global issue : 
```
I explain my situation :
I work on master and develop, and sometimes i squash develop on master, delete develop and create it again from master.
I squashed and merged with gitea, deleted branch from UI.
In local, i created develop from master. And when i pushed it on gitea, i saw in branch overview that my develop branch kept the tag "merged #4"
```

When i want to show branches : 
```
template: repo/branch/list:22:106: executing "repo/branch/list" at <.Commit.ID.String>: nil pointer evaluating *git.Commit.ID
```
@6543 advises me to create this issue to collect data and scenario about this problem. I think there is a "global" issue when you delete and recreate same naming branch.

I can not reproduce the issue on try.gitea.io, deleted branches are not kept... It is because of the public instance or the 1.11 version ? 

Update will coming :)

### PR DESCRIPTION
**Pull request by zeripath**
Once a branch has been merged if the commit ID no longer equals that of
the pulls ref commit id don't offer to delete the branch on the pull screen
and don't list it as merged on branches.

Fix #9201 

When looking at the pull page we should also get the commits from the refs/pulls/x/head

Fix #9158

### CODE REVIEW

File: routers/repo/branch.go [hunk 1]
```diff
@@ -213,11 +215,54 @@ func loadBranches(ctx *context.Context) []*Branch {
...
 		}
+		mergeMovedOn := false
 		if pr != nil {
 			if err := pr.LoadIssue(); err != nil {
 				ctx.ServerError("pr.LoadIssue", err)
 				return nil
 			}
+			if pr.BaseRepoID == ctx.Repo.Repository.ID {
+				pr.HeadRepo = ctx.Repo.Repository
+			} else 	if err := pr.LoadBaseRepo(); err != nil {
```
Comment (zeripath) [inline routers/repo/branch.go]:
```suggestion
			} else if err := pr.LoadBaseRepo(); err != nil {
```

**Comment by lafriks** [comment]
Integration tests fail as one page now returns internal error

**Comment by zeripath** [comment]
Sigh! I gotta fix an integration test...

**Comment by zeripath** [comment]
Damn that introduces a race because that's pointing to the same object.

**Comment by zeripath** [comment]
@lafriks done and fixed now.

File: routers/repo/branch.go [hunk 2]
```diff
@@ -213,11 +221,68 @@ func loadBranches(ctx *context.Context) []*Branch {
...
 			return nil
 		}
+		mergeMovedOn := false
 		if pr != nil {
 			if err := pr.LoadIssue(); err != nil {
 				ctx.ServerError("pr.LoadIssue", err)
 				return nil
 			}
+			if repo, ok := repoIDToRepo[pr.BaseRepoID]; ok {
+				pr.HeadRepo = repo
```
Comment (guillep2k) [inline routers/repo/branch.go]:
```suggestion
				pr.BaseRepo = repo
```
🤔

File: routers/repo/branch.go [hunk 3]
```diff
@@ -213,11 +221,68 @@ func loadBranches(ctx *context.Context) []*Branch {
...
+			if repo, ok := repoIDToRepo[pr.HeadRepoID]; ok {
+				pr.HeadRepo = repo
+			} else if err := pr.LoadHeadRepo(); err != nil {
+				ctx.ServerError("pr.LoadHeadRepo", err)
+				return nil
+			} else {
+				repoIDToRepo[pr.HeadRepoID] = pr.HeadRepo
+			}
+
+			if pr.HasMerged && pr.HeadRepo != nil {
```
Comment (guillep2k) [inline routers/repo/branch.go]: Can `pr.HeadRepo` be `nil` here?

File: routers/repo/branch.go [hunk 4]
```diff
@@ -230,6 +295,7 @@ func loadBranches(ctx *context.Context) []*Branch {
 			CommitsAhead:      divergence.Ahead,
 			CommitsBehind:     divergence.Behind,
 			LatestPullRequest: pr,
+			MergeMovedOn:      mergeMovedOn,
```
Comment (guillep2k) [inline routers/repo/branch.go:276]: Maybe this is an edge case and is covered elsewhere but, perhaps if we've got `ErrReferenceNotFound` we should hide the `new PR` button as well?

File: routers/repo/issue.go [hunk 5]
```diff
@@ -966,7 +966,10 @@ func ViewIssue(ctx *context.Context) {
 			ctx.Data["IsBlockedByRejection"] = pull.ProtectedBranch.MergeBlockedByRejectedReview(pull)
 			ctx.Data["GrantedApprovals"] = cnt
 		}
-		ctx.Data["IsPullBranchDeletable"] = canDelete && pull.HeadRepo != nil && git.IsBranchExist(pull.HeadRepo.RepoPath(), pull.HeadBranch)
+		ctx.Data["IsPullBranchDeletable"] = canDelete &&
+			pull.HeadRepo != nil &&
+			git.IsBranchExist(pull.HeadRepo.RepoPath(), pull.HeadBranch) &&
+			(!pull.HasMerged || ctx.Data["HeadBranchCommitID"] == ctx.Data["PullHeadCommitID"])
```
Comment (guillep2k) [inline routers/repo/issue.go:972]: I'm not sure I understand this condition. The branch is deletable if it _hasn't_ been merged or it's the same commit as the head?

File: routers/repo/branch.go (hunk 2 above)
Comment (6543) [reply routers/repo/branch.go]: I get a nil pointer exeption - if i add guillep2k suggestion it works

File: routers/repo/branch.go (hunk 3 above)
Comment (zeripath) [reply routers/repo/branch.go]: ~~Well... not the way I'd written the code... ~~

~~It can now.~~

I'm an idiot. Of course it can't be...

Comment (zeripath) [reply routers/repo/branch.go]: Line 219 only gets the PRs by HeadInfo - that is those that are in the head repo. Therefore the head repo is always going to be the ctx.Repo.Repository.

**Review by 6543 — APPROVED** [review]

File: routers/repo/branch.go (hunk 4 above)
Comment (zeripath) [reply routers/repo/branch.go:276]: Is this referring to when I thought it was possible to not get the head branch commit id? We actually always know that's there because otherwise there would have been a ServerError at line 200. So that can't happen and I've optimised that check away.

OR

is this referring to if we can't find the PR pulls head in the base repo?

I'm not sure what to do in that case. If I try to enforce that the pulls head is actually there I suspect that will break a lot of integration tests - as our fixtures do not necessarily match the ground truth. I also expect that there is a race between the db and the presence of the pull head. (We should check what happens here - the index is needed to create the pull head - so that means that the db has to have a pull request committed before we can push to the pull head.)

File: routers/repo/issue.go (hunk 5 above)
Comment (zeripath) [reply routers/repo/issue.go:972]: Yup only check that the headbranchcommitid and pullheadcommitid are the same if you've merged the PR.

it's only after merging that the two heads stop being kept in sync. Any difference in a non-merged PR could just be a race. 

I think we should probably stop updating pull heads when the PR is closed in which case we could add a third condition.

**Comment by zeripath** [comment]
of course that's now caused an integration test failure... sigh...

File: routers/repo/branch.go (hunk 4 above)
Comment (guillep2k) [reply routers/repo/branch.go:276]: I meant that `MergeMovedOn`, which has a restrictive meaning, is only set to true if both heads are found, but the restriction (which is to hide the `New PR` button) still should apply if any of the heads is missing (`ErrReferenceNotFound`). Maybe when any of  the heads is missing it should also be set to true, but then its name should be changed because it will no longer reflect the exact scenario.

File: routers/repo/issue.go (hunk 5 above)
Comment (guillep2k) [reply routers/repo/issue.go:972]: Isn't it then?:
```
ctx.Data["IsPullBranchDeletable"] = canDelete &&
			pull.HeadRepo != nil &&
			git.IsBranchExist(pull.HeadRepo.RepoPath(), pull.HeadBranch) &&
			pull.HasMerged &&
			ctx.Data["HeadBranchCommitID"] == ctx.Data["PullHeadCommitID"]
```

**Review by 6543 — CHANGES_REQUESTED** [review]
after your optimizion and the other stuff - I get a nil pointer exeption (log below)

**Comment by 6543** [comment]
```log
runtime error: invalid memory address or nil pointer dereference
/usr/lib/go/src/runtime/panic.go:199 (0x446b7b)
	panicmem: panic(memoryError)
/usr/lib/go/src/runtime/signal_unix.go:394 (0x4469b8)
	sigpanic: panicmem()
/home/maddl/git/own/gitea/models/repo.go:537 (0xe8ac08)
	(*Repository).getOwnerName: if len(repo.OwnerName) > 0 {
/home/maddl/git/own/gitea/models/repo.go:563 (0xe8aef2)
	(*Repository).mustOwnerName: if err := repo.getOwnerName(e); err != nil {
/home/maddl/git/own/gitea/models/repo.go:715 (0xe8c5fe)
	(*Repository).repoPath: return RepoPath(repo.mustOwnerName(e), repo.Name)
/home/maddl/git/own/gitea/models/repo.go:720 (0x13782dc)
	(*Repository).RepoPath: return repo.repoPath(x)
/home/maddl/git/own/gitea/routers/repo/branch.go:243 (0x13782b0)
	loadBranches: baseRepo, err := git.OpenRepository(pr.BaseRepo.RepoPath())
/home/maddl/git/own/gitea/routers/repo/branch.go:51 (0x1375055)
	Branches: ctx.Data["Branches"] = loadBranches(ctx)
/usr/lib/go/src/reflect/value.go:460 (0x491b05)
	Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/usr/lib/go/src/reflect/value.go:321 (0x4912c3)
	Value.Call: return v.call("Call", in)
```

File: routers/repo/issue.go (hunk 5 above)
Comment (zeripath) [reply routers/repo/issue.go:972]: Nope because then you can't delete unless the pull has merged.

**Comment by zeripath** [comment]
@6543 but routers/repo/branch.go:243: doesn't match that line... It's:

```go
baseGitRepo, ok := repoIDToGitRepo[pr.BaseRepoID]
```

Are you sure you've got the latest?

**Comment by 6543** [comment]
@zeripath you are so fast - i was jus going to write about my  `you should "git fetch" first`

**Review by 6543 — APPROVED** [review]
code looks-good | code works now (after fetch) :)

File: routers/repo/issue.go (hunk 5 above)
Comment (zeripath) [reply routers/repo/issue.go:972]: It would have to be:

```go
ctx.Data["IsPullBranchDeletable"] = canDelete &&
			pull.HeadRepo != nil &&
			git.IsBranchExist(pull.HeadRepo.RepoPath(), pull.HeadBranch) &&
			!(pull.HasMerged &&
			ctx.Data["HeadBranchCommitID"] != ctx.Data["PullHeadCommitID"])
```

which is no easier to understand TBH.

Comment (guillep2k) [reply routers/repo/issue.go:972]: > 
> 
> Nope because then you can't delete unless the pull has merged.

Then I misunderstood the purpose. I thought that's exactly what we wanted. Shouldn't the PR be closed at least in order to delete its branch?

Comment (zeripath) [reply routers/repo/issue.go:972]: That's dealt with at the template level:

https://github.com/go-gitea/gitea/blob/13175c012c5ed73cc600457196e57cf12c42491d/templates/repo/issue/view_content/pull.tmpl#L52-L82

and so on...

Comment (guillep2k) [reply routers/repo/issue.go:972]: Since a merged PR is also a closed PR, I'd add `IsClosed` as a condition, if only for consistency. Otherwise, LGTM.

**Review by guillep2k — APPROVED** [review]

File: routers/repo/branch.go (hunk 4 above)
Comment (zeripath) [reply routers/repo/branch.go:276]: I don't understand.

Perhaps some of what you're discussing is already fixed within the logic of the template?

If you don't have a PR already then merge moved on is of no consequence.

The head branch we already know exists because it's the branch we've provided.

If the base branch does not exist - that's a server error - although this won't show that. You shouldn't be able to delete a branch with PRs against it - (although I haven't checked that.) If the git pull head isn't there well... that's technically a server error but I think there could be a race between between a pull request being made and the ref being updated so I think we should allow it.

**Comment by 6543** [comment]
ping lgtm

**Comment by 6543** [comment]
@zeripath can you make a backport?

**Comment by zeripath** [comment]
https://github.com/go-gitea/gitea/pull/9639
