### PR TITLE
Remove "misc" scope check from public API endpoints

### LINKED ISSUE #26035: /api/v1/version should not give 403 for authenticated users/tokens
### Description

Before gitea 1.20.0, a token with the `repo` scope could access the `/api/v1/version` endpoint.

In gitea 1.20.0, a token with the `write:repository` scope cannot access the `/api/v1/version` endpoint.

Here's the partial bash script that I've used to create the token and test it:

```bash
# see https://try.gitea.io/api/swagger#/user/userCreateToken
echo "Creating Gitea $RENOVATE_USERNAME user personal access token..."
curl \
    --silent \
    --show-error \
    --fail-with-body \
    -u "$RENOVATE_USERNAME:$RENOVATE_PASSWORD" \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"name": "renovate", "scopes": ["write:repository"]}' \
    "$gitea_url/api/v1/users/$RENOVATE_USERNAME/tokens" \
    | jq -r .sha1 \
    >tmp/renovate-gitea-token.txt

# try the token.
echo "Trying the Gitea $RENOVATE_USERNAME user personal access token..."
RENOVATE_TOKEN="$(cat tmp/renovate-gitea-token.txt)"
export RENOVATE_TOKEN
curl \
    -s \
    --silent \
    --show-error \
    --fail-with-body \
    -H "Authorization: token $RENOVATE_TOKEN" \
    -H 'Accept: application/json' \
    "$gitea_url/api/v1/version" \
    | jq \
    > /dev/null
```

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

In docker, as configured in the first part of the bash script at https://github.com/rgl/my-ubuntu-ansible-playbooks/blob/main/renovate.sh

### Database

SQLite

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #26035

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Review by richmahn — APPROVED** [review]

**Review by delvh — APPROVED** [review]

File: routers/api/v1/api.go [hunk 1]
```diff
@@ -771,7 +771,7 @@ func Routes() *web.Route {
 				m.Get("/attachment", settings.GetGeneralAttachmentSettings)
 				m.Get("/repository", settings.GetGeneralRepoSettings)
 			})
-		}, tokenRequiresScopes(auth_model.AccessTokenScopeCategoryMisc))
```
Comment (lunny) [inline routers/api/v1/api.go:774]: Then `AccessTokenScopeCategoryMisc` will not be used in any other place, should we also remove it from models/auth/token_scope.go ?

Comment (lunny) [reply routers/api/v1/api.go:774]: Added a comment here.
