### PR TITLE
Fix ref links in issue overviews for tags

### LINKED ISSUE #8085: Error 404 - wrong related link in issue page
- Gitea version (or commit ref):  1.10.0+dev-145
- Git version: 2.20
- Operating system: RedHat 7.3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/mbarinc/test/src/branch/tag_001)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
If I open a Issue and relate it to a tag, when I try to go to this specific tag from the issue page by clicking the link near the issue name, I have an 404 error. This because in the url there is "branch" instead of "tag".

No errors if I create an Issue and relate it to a branch.

To reproduce the error:
1. start from https://try.gitea.io/mbarinc/test/issues
2. click on "tag_001"

### PR DESCRIPTION
**Pull request by vijfhoek**
I changed `Issue.Ref` to store the actual ref instead of (what Gitea assumes to be) the branch name, and modified all templates to deal with this. This ultimately fixes #8085.

To do this, I created a few helper functions to generate the URL (and updated `SlackLinkToRef` to them, since that's where I got them from).

This is my first PR for Gitea, so I hope I did not make any dumb mistakes.

### CODE REVIEW

File: models/issue.go [hunk 1]
```diff
@@ -1785,3 +1786,13 @@ func UpdateIssuesMigrationsByType(gitServiceType structs.GitServiceType, origina
 		})
 	return err
 }
+
+// RefEndName returns the end name of an issue's ref.
+func (issue *Issue) RefEndName() string {
```
Comment (lunny) [inline models/issue.go]: Please don't reference git module from models. It's better to put that on `services/issue` as a method.

File: modules/git/utils_test.go [hunk 2]
```diff
@@ -0,0 +1,27 @@
+package git
```
Comment (lunny) [inline modules/git/utils_test.go:5]: Copyright head missing.

**Review by lunny — DISMISSED** [review]

File: models/migrations/v105.go [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+		issues := make([]*Issue, 0, batchSize)
+		if err := sess.Limit(batchSize, start).Asc("id").Find(&issues); err != nil {
+			return err
+		}
+
+		if len(issues) == 0 {
+			break
+		}
+
+		for _, issue := range issues {
```
Comment (lafriks) [inline models/migrations/v105.go]: No need to update one by one. This can be done is single SQL command:
```sql
update `issue` set `ref` = 'refs/heads/' || `ref` where `ref` is not null and `ref` != '';
```

Comment (vijfhoek) [reply models/migrations/v105.go]: Will this be compatible with all database engines? I've looked at a bunch of other migrations for reference (v82 and v85 from the top of my head) and they did it the exact same way

Comment (lafriks) [reply models/migrations/v105.go]: Needs to be tested but this should work imho on all DB types:
```go
func prependRefsHeadsToIssueRefs(x *xorm.Engine) error {
	_, err := x.Exec("UPDATE `issue` SET `ref` = 'refs/heads/' || `ref` WHERE `ref` is not null AND `ref` != ''")
	return err
}
```

Comment (vijfhoek) [reply models/migrations/v105.go]: PostgreSQL does not support using backticks for table/column name quoting, so I left them out. They aren't keywords anyway.

I also used `<>` instead of `!=`, since `!=` is not supported by SQL92 (the standard PSQL/MySQL/MSSQL is based on) - it's a bit more standard

Comment (vijfhoek) [reply models/migrations/v105.go]: After some more research I found out that `ref` is in fact reserved in more modern SQL standards. 

Also, escaping reserved words normally is done with double quotes, but MySQL is the special one using backticks, with no support for double quotes unless you start it in ANSI mode.

Comment (guillep2k) [reply models/migrations/v105.go]: @SijmenSchoon there are a couple of migrations that are "engine aware" (e.g. the drop column function). I guess you could resort to that if necessary.

Comment (vijfhoek) [reply models/migrations/v105.go]: I opened [an xorm issue](https://gitea.com/xorm/core/issues/62) for future cases, and I just made the migration engine aware. Let's see if this works

File: models/migrations/v105.go [hunk 4]
```diff
@@ -0,0 +1,23 @@
+// Copyright 2019 The Gitea Authors. All rights reserved.
+// Use of this source code is governed by a MIT-style
+// license that can be found in the LICENSE file.
+
+package migrations
+
+import (
+	"xorm.io/xorm"
```
Comment (guillep2k) [inline models/migrations/v105.go]:
```suggestion
	"code.gitea.io/gitea/modules/setting"
	
	"xorm.io/xorm"
```

File: models/issue.go (hunk 1 above)
Comment (vijfhoek) [reply models/issue.go]: @lafriks what do you think?

**Comment by lafriks** [comment]
this can not be backported anymore

**Comment by lunny** [comment]
Please resolve the conflicts.

**Comment by SijmenSchoon** [comment]
@lunny Done

**Review by lafriks — APPROVED** [review]

**Comment by guillep2k** [comment]
How does this change in `.Ref` semantics affect other parts of the code, like...?:

https://github.com/go-gitea/gitea/blob/4a357f4188ee037d5279d198356af71a8ca102bc/models/action.go#L518-L528

**Comment by guillep2k** [comment]
MMmmm..... maybe that piece of code wasn't there yet when you started this PR. 😏

**Comment by SijmenSchoon** [comment]
@guillep2k That code indeed wasn't there yet when I started this PR :p 

I'll solve it, together with the merge conflict, as soon as I have time somewhere next week.

File: models/migrations/v109.go [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+
+	"xorm.io/xorm"
+)
+
+func prependRefsHeadsToIssueRefs(x *xorm.Engine) error {
+	var query string
+
+	switch {
+	case setting.Database.UseMSSQL:
+		query = "UPDATE `issue` SET `ref` = 'refs/heads/' + `ref` WHERE `ref` IS NOT NULL AND `ref` <> ''"
```
Comment (lunny) [inline models/migrations/v109.go]: `and ref IS NOT NULL`?

Comment (vijfhoek) [reply models/migrations/v109.go]: What do you mean? I do check for that?

**Comment by lunny** [comment]
Please resolve the conflicts.

**Comment by 6543** [comment]
can you resolve conflicts?

some **hints**:
 * mv `models/migrations/v109.go` `models/migrations/v125.go`
 * edit `models/migrations/migrations.go` (v125 -> v126)
 * rm `public/js/index.js`
 * rm `public/js/index.js.map`

**Comment by 6543** [comment]
@SijmenSchoon can you resolve conflicts?

some **hints**:
 * mv `models/migrations/v109.go` `models/migrations/v125.go`
 * edit `models/migrations/migrations.go` (v125 -> v126)
 * rm `public/js/index.js`
 * rm `public/js/index.js.map`

**Comment by 6543** [comment]
can you resolve the confilcts :sweat_smile: please

**Comment by 6543** [comment]
what's the status of this pull?

**Comment by 6543** [comment]
@SijmenSchoon what's the status of this pull?

**Comment by SijmenSchoon** [comment]
@6543 I've been busy the last weeks, but I've got some time again. Should I resolve the merge conflicts now, or is it better to wait for some merge window? I'd like to avoid any more duplication of effort in the future 🙂

**Comment by 6543** [comment]
@SijmenSchoon this is in mile 1.12 so the time should be right :)

**Comment by 6543** [comment]
and my [hints](https://github.com/go-gitea/gitea/pull/8742#issuecomment-577183492) may help you out :)

**Comment by SijmenSchoon** [comment]
Alright, I'm on it

**Comment by SijmenSchoon** [comment]
Could someone restart the test-mysql8 test? It seems to have failed randomly

**Comment by lafriks** [comment]
Restarted

File: models/migrations/v139.go [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+
+	"xorm.io/xorm"
+)
+
+func prependRefsHeadsToIssueRefs(x *xorm.Engine) error {
+	var query string
+
+	switch {
+	case setting.Database.UseMSSQL:
+		query = "UPDATE `issue` SET `ref` = 'refs/heads/' + `ref` WHERE `ref` IS NOT NULL AND `ref` <> ''"
```
Comment (6543) [inline models/migrations/v139.go:18]:
```suggestion
		query = "UPDATE `issue` SET `ref` = 'refs/heads/' + `ref` WHERE `ref` IS NOT NULL AND `ref` <> '' AND `ref` NOT LIKE 'refs/%'"
```

File: models/migrations/v139.go [hunk 7]
```diff
@@ -0,0 +1,25 @@
...
+	default:
+		query = "UPDATE `issue` SET `ref` = 'refs/heads/' || `ref` WHERE `ref` IS NOT NULL AND `ref` <> ''"
```
Comment (6543) [inline models/migrations/v139.go:20]:
```suggestion
		query = "UPDATE `issue` SET `ref` = 'refs/heads/' || `ref` WHERE `ref` IS NOT NULL AND `ref` <> '' AND `ref` NOT LIKE 'refs/%'"
```

**Review by 6543 — CHANGES_REQUESTED** [review]
prefent Truncated incorrect DOUBLE value: 'refs/heads/' if migration is running twice (this should not happen but if you downgrade without restore the database it will

**Comment by SijmenSchoon** [comment]
The XSS test failed again...

**Review by 6543 — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
@lunny need your approval

**Comment by SijmenSchoon** [comment]
Any updates?

File: services/issue/issue_test.go [hunk 8]
```diff
@@ -0,0 +1,30 @@
+// Copyright 2019 The Gitea Authors. All rights reserved.
```
Comment (techknowlogick) [inline services/issue/issue_test.go]:
```suggestion
// Copyright 2020 The Gitea Authors. All rights reserved.
```

File: modules/git/utils_test.go [hunk 9]
```diff
@@ -0,0 +1,31 @@
+// Copyright 2019 The Gitea Authors. All rights reserved.
```
Comment (techknowlogick) [inline modules/git/utils_test.go]:
```suggestion
// Copyright 2020 The Gitea Authors. All rights reserved.
```

**Comment by techknowlogick** [comment]
ping LG-TM

**Comment by kolaente** [comment]
Looks like this breaks mysql installations:

```
2020/05/15 10:37:25 ...ations/migrations.go:298:Migrate() [I] Migration[139]: prepend refs/heads/ to issue refs
2020/05/15 10:37:25 routers/init.go:74:initDBEngine() [E] ORM engine initialization attempt #2/10 failed. Error: migrate: do migrate: Error 1292: Truncated incorrect DOUBLE value: 'refs/heads/'
2020/05/15 10:37:25 routers/init.go:75:initDBEngine() [I] Backing off for 3 seconds
2020/05/15 10:37:28 routers/init.go:68:initDBEngine() [I] ORM engine initialization attempt #3/10...
2020/05/15 10:37:28 ...rm/session_schema.go:25:Ping() [I] PING DATABASE mysql
```

**Comment by kolaente** [comment]
I was able to fix it in my installation by running 
```
UPDATE `issue` SET `ref` = 'refs/heads/' || `ref` WHERE `ref` IS NOT NULL AND `ref` <> '' AND `ref` NOT LIKE 'refs/%';
```

I'll send a pr.-

**Comment by kolaente** [comment]
PR is up: https://github.com/go-gitea/gitea/pull/11419
