### PR TITLE
Fix two UI bugs: JS error in imagediff.js, 500 error in diff/compare.tmpl

### LINKED ISSUE #19414: JS error in imagediff.js
caught by https://github.com/go-gitea/gitea/pull/18971 (Show JS errors) , reported by a user.

caused by imagediff.js

```js
function getDefaultSvgBoundsIfUndefined(svgXml, src) {
  const DefaultSize = 300;
  const MaxSize = 99999;

  const svg = svgXml.rootElement; // BUG, here svg might be null, then the following `svg.width` triggers JS error

  const width = svg.width.baseVal;
  const height = svg.height.baseVal;
  if (width.unitType === SVGLength.SVG_LENGTHTYPE_PERCENTAGE || height.unitType === SVGLength.SVG_LENGTHTYPE_PERCENTAGE) {

```

image

Compiled JS, the `index.js:37:1821` is at `c=o.width`
```
o=e.rootElement,c=o.width.baseVal,y=o.height.baseVal;if(c.unitType===SVGLength.SVG_LENGTHTYPE_PERCENTAG
```

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix two UI bugs:
1. The JS error in `imagediff.js`, caused by invalid svg. Replace deprecated rootElement with documentElement.
2. 500 error in `diff/compare.tmpl`, the `$.Context` was lost.

Close #19414 (JS error in imagediff.js)

Screenshot after this fix:

image

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by wxiaoguang** [comment]
bot

File: web_src/js/features/imagediff.js [hunk 1]
```diff
@@ -4,10 +4,12 @@ function getDefaultSvgBoundsIfUndefined(svgXml, src) {
...
 
-  const svg = svgXml.rootElement;
-
-  const width = svg.width.baseVal;
-  const height = svg.height.baseVal;
+  const svg = svgXml.documentElement;
+  const width = svg?.width?.baseVal;
+  const height = svg?.height?.baseVal;
+  if (width === undefined || height === undefined) {
+    return null; // in case some svg is invalid or doesn't have the width/height
```
Comment (silverwind) [inline web_src/js/features/imagediff.js:11]: SVG without width/height is not invalid. The attributes default to `auto` which essentially means `100%` to fill the parent container:

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/width#svg

Not sure whether we should actually fill the container or default them to something more sane like `400px` maybe.

Comment (wxiaoguang) [reply web_src/js/features/imagediff.js:11]: What's your suggestion?

Comment (silverwind) [reply web_src/js/features/imagediff.js:11]: Ideally I'd render with a max-width/max-height somewhere between 40% and 50% container width and render those size-less SVGs with that size as well. Maybe it can be done in CSS only, but JS-based solutions are also an option.

Comment (silverwind) [reply web_src/js/features/imagediff.js:11]: Another simpler option may be to default to 300px width / 150px height as defined in the SVG spec here for rendering in CSS contexts:

https://svgwg.org/specs/integration/#svg-css-sizing

> If any of the sizing attributes are missing, resolve the missing ‘[svg](https://svgwg.org/svg2-draft/struct.html#SVGElement)’ element [width](https://svgwg.org/svg2-draft/geometry.html#Sizing) to '300px' and missing [height](https://svgwg.org/svg2-draft/geometry.html#Sizing) to '150px' (using CSS 2.1 replaced elements size calculation).

Comment (wxiaoguang) [reply web_src/js/features/imagediff.js:11]: Could you help to propose a PR about the refactoring?

Comment (silverwind) [reply web_src/js/features/imagediff.js:11]: I can check what can be done, but it would be helpful to have a proper testing repo. https://try.gitea.io/wxiaoguang/test/pulls/6/files seems unsuitable as is has a `namespace`-less SVG which will never properly render.

Comment (wxiaoguang) [reply web_src/js/features/imagediff.js:11]: But ` https://try.gitea.io/wxiaoguang/test/pulls/6/files` is why the bug occurs ..... end users made the mistakes. This PR just make UI more friendly to end users if they made mistakes.

What do you mean by `suitable`?

Comment (silverwind) [reply web_src/js/features/imagediff.js:11]: Suiteable in the sense that it renders something, e.g. with namespace and some visible shape data.

Comment (wxiaoguang) [reply web_src/js/features/imagediff.js:11]: I can not understand why you need that .... the purpose of this PR is to handle invalid SVG gracefully.

If you work on a correct SVG, it's not related to this problem directly.

If you need some work for some special SVG, you can just prepare it .......... it would not be too difficult to construct a SVG manually by typing `<svg> ...`

Comment (silverwind) [reply web_src/js/features/imagediff.js:11]: Yes, of course I can/will create test files myself.
