### PR TITLE
Show editorconfig warnings when viewing a malformed editorconfig

### LINKED ISSUE #20694: Error while getting .editorconfig file
### Description

I found this message in /admin/notices

`Error while getting .editorconfig file: normalization error: insert_final_newline=off is not an acceptable value. strconv.ParseBool: parsing "off": invalid syntax`

Nothing founded in gitea.log.

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

image

### Git Version

 2.25.1

### Operating System

Ubuntu 20.04.4

### How are you running Gitea?

Downloaded gitea-1.17.0-linux-amd64

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by greut**
This is a branch to test https://github.com/editorconfig/editorconfig-core-go/pull/144 - ~~which will require a proper release (e.g. 2.5.0) in order to be fully usable.~~ 2.5.1 has been released.

The _graceful_ should fail less when the `.editorconfig` file isn't properly written, e.g. boolean values from YAML or unparseable numbers (when a number is expected). As is... information is lost as the _warning_ (a go-multierror.Error) is ignored. If anybody knows how to send them to the UI as warning; any help is appreciated.

Closes #20694

### CODE REVIEW

**Comment by silverwind** [comment]
> If anybody knows how to send them to the UI as warning; any help is appreciated.

Since https://github.com/go-gitea/gitea/pull/21088, editorconfig errors should appear in the UI when viewing `.editorconfig.`

**Comment by greut** [comment]
@silverwind good; they both are probably as annoying to see; at least the rest of the config had been loaded and could be used.

**Comment by zeripath** [comment]
> This is a branch to test https://github.com/editorconfig/editorconfig-core-go/pull/144 - which will require a proper release (e.g. 2.5.0) in order to be fully usable.

So do you consider this a draft/WIP PR until that point or do you think that this should be merged in preparation for that?

If you consider that this is WIP please add the WIP: prefix to the PR title and/or mark this as a draft PR in Github

**Comment by greut** [comment]
> So do you consider this a draft/WIP PR until that point or do you think that this should be merged in preparation for that?

2.5.0 and its bugfix 2.5.1 have been released in the meantime, hence i've removed it from the Draft but forgot to change the description. I've just did it.

File: modules/context/repo.go [hunk 1]
```diff
@@ -231,9 +231,9 @@ func (r *Repository) FileExists(path, branch string) (bool, error) {
 
 // GetEditorconfig returns the .editorconfig definition if found in the
 // HEAD of the default repo branch.
-func (r *Repository) GetEditorconfig(optCommit ...*git.Commit) (*editorconfig.Editorconfig, error) {
+func (r *Repository) GetEditorconfig(optCommit ...*git.Commit) (*editorconfig.Editorconfig, error, error) {
```
Comment (zeripath) [inline modules/context/repo.go]: Probably helpful to stick names on these return values so it's clearer that the 1st error is actually a warning and the second one is the real error. e.g.

```suggestion
func (r *Repository) GetEditorconfig(optCommit ...*git.Commit) (cfg *editorconfig.Editorconfig, warning error, err error) {
```

File: modules/context/repo.go [hunk 2]
```diff
@@ -231,9 +231,9 @@ func (r *Repository) FileExists(path, branch string) (bool, error) {
...
 	if r.GitRepo == nil {
-		return nil, nil
+		return nil, nil, nil
 	}
 	var (
 		err    error
```
Comment (zeripath) [inline modules/context/repo.go]: Of course you'd then need to remove this line and reformat the var block but it's probably worth it.

**Comment by lunny** [comment]
Please resolve the conflicts.

**Comment by lunny** [comment]
Sorry, looks like the conflicts are still there.

**Comment by silverwind** [comment]
Thanks, will check this out later.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Rebased, squashed and simplified a bit more. @lunny care for a review?

**Review by lunny — APPROVED** [review]

**Comment by jolheiser** [comment]
🎺 🤖

**Review by delvh — APPROVED** [review]
