### PR TITLE
fix attachment file size limit in server backend

### LINKED ISSUE #35512: Attachment size limit in app.ini not enforced for REST API uploads
### Description

When using the REST API to upload attachments (e.g. to Pull Requests), the configured file size limits in app.ini are not enforced and the attachments > 1 MB are being uploaded. The same limits are enforced correctly in the web UI.

Configuration snippet

[attachment]
| MAX_SIZE = 1

### Gitea Version

1.24.5

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

git version 2.49.1

### Operating System

_No response_

### How are you running Gitea?

We are self-hosting Gitea using Docker (official gitea/gitea image)  in ubuntu 22.04 linux server.

### Database

SQLite

### PR DESCRIPTION
**Pull request by a1012112796**
fix #35512

### CODE REVIEW

**Comment by techknowlogick** [comment]
CI fail is related:
```

--- FAIL: TestCreateIssueAttachment (0.49s)
    testlogger.go:61: 2025/09/22 14:12:32 modules/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /home/runner/work/gitea/gitea/tests/gitea-lfs-meta
    testlogger.go:61: 2025/09/22 14:12:32 HTTPRequest [I] router: completed GET /user/login for test-mock:12345, 200 OK in 2.1ms @ auth/auth.go:184(auth.SignIn)
    testlogger.go:61: 2025/09/22 14:12:32 HTTPRequest [I] router: completed POST /user/login for test-mock:12345, 303 See Other in 5.8ms @ auth/auth.go:197(auth.SignInPost)
    testlogger.go:61: 2025/09/22 14:12:32 HTTPRequest [I] router: completed POST /user2/repo1/issues/attachments for test-mock:12345, 500 Internal Server Error in 85.8ms @ repo/attachment.go:25(repo.UploadIssueAttachment)
    attachment_test.go:47: Response:  NewAttachment: attachment size 2147483648 exceed limit 104
        
    attachment_test.go:47: 
        	Error Trace:	/home/runner/work/gitea/gitea/tests/integration/integration_test.go:354
        	            				/home/runner/work/gitea/gitea/tests/integration/integration_test.go:160
        	            				/home/runner/work/gitea/gitea/tests/integration/attachment_test.go:47
        	            				/home/runner/work/gitea/gitea/tests/integration/attachment_test.go:67
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 500
        	Test:       	TestCreateIssueAttachment
        	Messages:   	Request: POST /user2/repo1/issues/attachments
```

Also, it's probably better to have a status 413 returned if the size is too large

**Review by lunny — APPROVED** [review]

File: routers/api/v1/repo/release_attachment.go [hunk 1]
```diff
@@ -234,7 +236,7 @@ func CreateReleaseAttachment(ctx *context.APIContext) {
 	}
 
 	// Create a new attachment and save the file
-	attach, err := attachment_service.UploadAttachment(ctx, content, setting.Repository.Release.AllowedTypes, size, &repo_model.Attachment{
+	attach, err := attachment_service.UploadAttachment(ctx, content, setting.Repository.Release.AllowedTypes, setting.Attachment.MaxSize<<20, size, &repo_model.Attachment{
```
Comment (wxiaoguang) [inline routers/api/v1/repo/release_attachment.go]: There are at least 2 "attachment max size" config options.

If you always use `setting.Attachment.MaxSize`, at least one is wrong

File: services/attachment/attachment.go [hunk 2]
```diff
@@ -48,6 +62,10 @@ func UploadAttachment(ctx context.Context, file io.Reader, allowedTypes string,
 		return nil, err
 	}
 
+	if maxFileSize >= 0 && fileSize > (maxFileSize) {
+		return nil, &ErrAttachmentSizeExceed{MaxSize: maxFileSize, Size: fileSize}
```
Comment (wxiaoguang) [inline services/attachment/attachment.go]: Other Gitea errors use struct itself, but not a pointer.

File: services/attachment/attachment.go [hunk 3]
```diff
@@ -38,8 +38,22 @@ func NewAttachment(ctx context.Context, attach *repo_model.Attachment, file io.R
 	return attach, err
 }
 
+type ErrAttachmentSizeExceed struct {
```
Comment (wxiaoguang) [inline services/attachment/attachment.go]: If you'd like to introduce a new "business error", it needs to be able to unwrap to some base errors, like other Gitea errors.

File: routers/api/v1/repo/release_attachment.go (hunk 1 above)
Comment (a1012112796) [reply routers/api/v1/repo/release_attachment.go]: why? looks they are all same in curent design. hasn't found anything like `setting.Repository.Release.MaxSize`. 

ref:

https://github.com/go-gitea/gitea/blob/0b706b0825daa521859c259cba94a90412ee83b9/services/context/upload/upload.go#L90-L114

Comment (wxiaoguang) [reply routers/api/v1/repo/release_attachment.go]: ~~Oh you are right, release upload shares the same attachment max size with comment attachment, but doesn't share some other settings .....~~

~~It seems to be another (unrelated) legacy problem.~~

(Update: see next)

**Comment by lunny** [comment]
last call @go-gitea/technical-oversight-committee

File: services/attachment/attachment.go [hunk 4]
```diff
@@ -48,6 +61,10 @@ func UploadAttachment(ctx context.Context, file io.Reader, allowedTypes string,
 		return nil, err
 	}
 
+	if maxFileSize >= 0 && fileSize > (maxFileSize) {
```
Comment (6543) [inline services/attachment/attachment.go]:
```suggestion
	if maxFileSize >= 0 && fileSize > maxFileSize {
```
?

File: services/attachment/attachment.go [hunk 5]
```diff
@@ -48,6 +61,10 @@ func UploadAttachment(ctx context.Context, file io.Reader, allowedTypes string,
 		return nil, err
 	}
 
+	if maxFileSize >= 0 && fileSize > maxFileSize {
+		return nil, ErrAttachmentSizeExceed{MaxSize: maxFileSize, Size: fileSize}
```
Comment (6543) [inline services/attachment/attachment.go]: fileSize looks like an user input - how do we make sure that it's not borked?

Comment (6543) [reply services/attachment/attachment.go]: I think we should wrap `file io.Reader` into an limited reader, as copyN does:
https://cs.opensource.google/go/go/+/refs/tags/go1.25.1:src/io/io.go;l=363-373
```
file = io.LimitReader(file, maxFileSize+1024) // add 1k more to allow sidecases where encoding tells us its exactly maxFileSize but the actuall created file is >maxFileSize ...

Comment (6543) [reply services/attachment/attachment.go]: as we allow the file to have a different sice as what originally was signalled:
https://github.com/go-gitea/gitea/blob/cdc07330471a5e05466ed5351795efb5603bad16/services/attachment/attachment.go#L33

**Comment by 6543** [comment]
@a1012112796 -> https://github.com/a1012112796/gitea/pull/13

**Comment by 6543** [comment]
could push it in myselfe ...

**Review by 6543 — APPROVED** [review]

**Review by wxiaoguang — DISMISSED** [review]
No, the new changes are wrong.

`header.Size` can't lie.

**Comment by 6543** [comment]
I try to write a prove of concept

**Comment by wxiaoguang** [comment]
> I try to write a prove of concept

@6543 any proof? If no, revert

**Comment by wxiaoguang** [comment]
> > I try to write a prove of concept
> 
> @6543 any proof? If no, revert

@6543 any proof? If no, revert

**Comment by 6543** [comment]
I'll revert it for now as i did not have time to write one jet to test stuff

**Comment by wxiaoguang** [comment]
> as i did not have time to write one jet to test stuff

Even if you have 100 years, there will be no proof. Golang HTTP packages's FormFile guarantees that the `head.Size` is the real uploaded size, you can spend a few minutes to read the code, no need to spend 100 years to try.

**Comment by 6543** [comment]
well did not know/read that docu jet but I should ...
... anyway better save than sorry

**Comment by wxiaoguang** [comment]
There are still problems:

1. `CreateReleaseAttachment`: when the `body` is used as the upload stream, it should use `http.MaxBytesReader` to limit the size (fixed)
2. `ctx.Req.ParseMultipartForm(setting.Attachment.MaxSize << 20)` is not right, it will make Gitea OOM  (fixed)
3. `UploadFileToServer` doesn't check the size limit either, I just left a FIXME and didn't make more changes in this PR
    * Feel free to properly fix it

File: routers/api/v1/repo/release_attachment.go (hunk 1 above)
Comment (wxiaoguang) [reply routers/api/v1/repo/release_attachment.go]: Update: the problem I mentioned `There are at least 2 "attachment max size" config options.` is still there. See my latest comment for `UploadFileToServer`, there is no limit check either.

* https://github.com/go-gitea/gitea/pull/35519#issuecomment-3393561653

**Review by 6543 — DISMISSED** [review]
errors.Is dont work now

creating custom errors is fine and all but we should work **with** golangs error handling system witch means that we should cover unwrap and is interface

**Comment by wxiaoguang** [comment]
> errors.Is dont work now (just revert commit looked at jet)

What do you mean by "errors.Is dont work now"?

**Comment by 6543** [comment]
i will have time tomorrow, review via mobule is horrible

**Comment by wxiaoguang** [comment]
> creating custom errors is fine and all but we should work **with** golangs error handling system witch means that we should cover unwrap and is interface

Isn't it what I have done? I don't see any problem.

image

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
> > errors.Is dont work now
>
> What do you mean by "errors.Is dont work now"?
>
> > creating custom errors is fine and all but we should work **with** golangs error handling system witch means that we 
should cover unwrap and is interface
>
> Isn't it what I have done? I don't see any problem.
>
> > i will have time tomorrow, review via mobule is horrible

@6543 so where is the problem? I think you misunderstood the "golangs error handling system". If no problem, dismiss the change request.

**Comment by wxiaoguang** [comment]
> > > errors.Is dont work now
> > 
> > 
> > What do you mean by "errors.Is dont work now"?
> > > creating custom errors is fine and all but we should work **with** golangs error handling system witch means that we
> > > should cover unwrap and is interface
> > 
> > 
> > Isn't it what I have done? I don't see any problem.
> > > i will have time tomorrow, review via mobule is horrible
> 
> @6543 so where is the problem? I think you misunderstood the "golangs error handling system". If no problem, dismiss the change request.

@6543 so where is the problem? I think you misunderstood the "golangs error handling system". If no problem, dismiss the change request.

**Comment by wxiaoguang** [comment]
> > > > errors.Is dont work now
> > > 
> > > 
> > > What do you mean by "errors.Is dont work now"?
> > > > creating custom errors is fine and all but we should work **with** golangs error handling system witch means that we
> > > > should cover unwrap and is interface
> > > 
> > > 
> > > Isn't it what I have done? I don't see any problem.
> > > > i will have time tomorrow, review via mobule is horrible
> > 
> > 
> > @6543 so where is the problem? I think you misunderstood the "golangs error handling system". If no problem, dismiss the change request.
> 
> @6543 so where is the problem? I think you misunderstood the "golangs error handling system". If no problem, dismiss the change request.

@6543 If no problem, dismiss the change request.

**Review by wxiaoguang — APPROVED** [review]
