### PR TITLE
fix: use TriggerEvent instead of Event in workflow runs API response for scheduled runs

### LINKED ISSUE #37252: API: /actions/runs returns event: "push" for scheduled workflow runs
## Description

The `/api/v1/repos/{owner}/{repo}/actions/runs` endpoint returns `event: "push"` for runs triggered by a `schedule:` (cron). Inside the workflow, `gitea.event_name` correctly returns `"schedule"` (fix from #27667). Filtering `event == "schedule"` via the API makes scheduled runs appear indistinguishable from push events.

This is asymmetric: the tasks/jobs API correctly uses `run.TriggerEvent`.

### Root cause

`ActionRun` has two event fields:
- `Event` — the event that *registered* the schedule (i.e. `push` on the default branch that added the workflow). Set at [`services/actions/schedule_tasks.go:129`](https://github.com/go-gitea/gitea/blob/v1.25.5/services/actions/schedule_tasks.go#L129).
- `TriggerEvent` — the actual trigger (`schedule`). Set at [`services/actions/schedule_tasks.go:131`](https://github.com/go-gitea/gitea/blob/v1.25.5/services/actions/schedule_tasks.go#L131).

The two API converters disagree:
- [`ToActionTask` (`convert.go:239`)](https://github.com/go-gitea/gitea/blob/v1.25.5/services/convert/convert.go#L239) — tasks API: `Event: t.Job.Run.TriggerEvent` ✅
- [`ToActionWorkflowRun` (`convert.go:263`)](https://github.com/go-gitea/gitea/blob/v1.25.5/services/convert/convert.go#L263) — runs API: `Event: string(run.Event)` ❌

Bug is also present on `main` (same line numbers).

### Reproduction

1. Create a repo with `.gitea/workflows/cron.yml`:
   ```yaml
   on:
     schedule:
       - cron: "* * * * *"
   jobs:
     tick:
       runs-on: ubuntu-latest
       steps:
         - run: echo "fired by ${{ gitea.event_name }}"
   ```
2. Wait one minute for the cron to fire.
3. `GET /api/v1/repos/{owner}/{repo}/actions/runs?limit=1` → returns `event: "push"` with `trigger_actor.login: "gitea-actions"`.
4. Inside the job, `gitea.event_name` prints `schedule` — consistent with #27667 fix.

### Suggested fix

Change `convert.go:263` to match the tasks converter:
```go
Event: run.TriggerEvent,
```

## Gitea Version

1.25.5 (bug also verified on `main`)

## Can you reproduce the bug on the Gitea demo site?

No (not tested, but bug is source-verified on both `v1.25.5` and `main`)

## How are you running Gitea?

Docker (`gitea/gitea:1.25.5` official image).

## Database

PostgreSQL

### PR DESCRIPTION
**Pull request by KalashThakare**
## Summary

Fixes #37252

The `/api/v1/repos/{owner}/{repo}/actions/runs` endpoint was returning
`event: "push"` for workflow runs triggered by `schedule:` (cron), instead
of `event: "schedule"`.

## Root Cause

`ActionRun` has two separate fields:
- `Event` — the workflow registration event (e.g. `push`, set when the workflow file was first pushed)
- `TriggerEvent` — the actual event that triggered the run (e.g. `schedule`)

`ToActionWorkflowRun` in `services/convert/action.go` was serializing
`run.Event` into the API response instead of `run.TriggerEvent`, causing
scheduled runs to be indistinguishable from push events via the API.

This was already asymmetric — the tasks/jobs API correctly used `TriggerEvent`.

## Fix

Changed `ToActionWorkflowRun` to use `run.TriggerEvent` for the `event`
field in the API response, consistent with how the jobs API works.

## Before

`event: "push"` returned for all scheduled runs:

Screenshot 2026-04-19 115642

## After

`event: "schedule"` correctly returned for scheduled runs:

Screenshot 2026-04-19 121723

## Testing

- Added unit test `TestToActionWorkflowRun_UsesTriggerEvent` in
  `services/convert/action_test.go` that explicitly verifies the API
  returns `TriggerEvent` and not `Event` for a scheduled run.
- Manually verified via the API against a live Gitea instance with a
  `cron: "* * * * *"` workflow.

### CODE REVIEW

**Comment by bircni** [comment]
To make it more clear should we publish both via api?

**Comment by KalashThakare** [comment]
> To make it more clear should we publish both via api?

yes i think we should as it will eventually help consumers get more context.

**Comment by bircni** [comment]
and maybe also have a look how github behaves here - especially for api its good to have nearly the same

**Comment by KalashThakare** [comment]
> and maybe also have a look how github behaves here - especially for api its good to have nearly the same

ok i will look into it.

**Comment by silverwind** [comment]
Two minor items worth addressing:

1. Redundant assertion in `services/convert/action_test.go` — `assert.NotEqual(t, string(run.Event), apiRun.Event)` adds nothing once the preceding `assert.Equal(t, "schedule", apiRun.Event)` holds with `run.Event = "push"`. Safe to drop.

2. Integration coverage gap — this bug slipped past `tests/integration/workflow_run_api_check_test.go` because every existing `action_run` fixture has `event == trigger_event`. Adding a scheduled-run fixture where the two differ would guard against regression at the API layer, not just the converter.

---
This comment was written by Claude Opus 4.7.

**Comment by KalashThakare** [comment]
> and maybe also have a look how github behaves here - especially for api its good to have nearly the same

Github only exposes event field( actual event that triggered the run )

**Review by lunny — APPROVED** [review]

**Comment by bircni** [comment]
> Two minor items worth addressing:
> 
> 
> 
> 1. Redundant assertion in `services/convert/action_test.go` — `assert.NotEqual(t, string(run.Event), apiRun.Event)` adds nothing once the preceding `assert.Equal(t, "schedule", apiRun.Event)` holds with `run.Event = "push"`. Safe to drop.
> 
> 
> 
> 2. Integration coverage gap — this bug slipped past `tests/integration/workflow_run_api_check_test.go` because every existing `action_run` fixture has `event == trigger_event`. Adding a scheduled-run fixture where the two differ would guard against regression at the API layer, not just the converter.
> 
> 
> 
> ---
> 
> This comment was written by Claude Opus 4.7.

Did you address them?

**Comment by bircni** [comment]
@silverwind addressed your requests

File: services/convert/action_test.go [hunk 1]
```diff
@@ -107,3 +109,18 @@ func TestGetActionWorkflow_FallbackRef(t *testing.T) {
 		assert.ErrorIs(t, err, util.ErrNotExist)
 	})
 }
+
+func TestToActionWorkflowRun_UsesTriggerEvent(t *testing.T) {
+	assert.NoError(t, unittest.PrepareTestDatabase())
+
+	repo := unittest.AssertExistsAndLoadBean(t, &repo_model.Repository{ID: 2})
+	run := unittest.AssertExistsAndLoadBean(t, &actions_model.ActionRun{ID: 803})
```
Comment (lunny) [inline services/convert/action_test.go:117]: How about testing 802 directly without the change?

Comment (bircni) [reply services/convert/action_test.go:117]: 802 is for repo 5 in action_run.yml; 803 is for repo 2. I switched the test to repo 5 + 802 so we exercise the existing schedule fixture without mutating the run.

**Review by lunny — APPROVED** [review]

**Review by silverwind — APPROVED** [review]
