### PR TITLE
Fix cannot reopen after pushing commits to a closed PR

### LINKED ISSUE #22784: Cannot reopen PR after commit
### Description

If you commit to a branch of closed PR, it is not possible to reopen it and there is a notice "This pull request cannot be reopened because the branch was deleted."

Steps to reproduce:
1) create a PR
2) close it without merging nor deleting
3) now commit to the branch linked in the PR
4) PR cannot be reopened and it states the branch was deleted, even though the branch still exists (with the commit from step 3)

This was discovered on version 1.18.2 when I wanted to continue working on a PR, which was accidentally closed by my colleague, and I did not notice that. I made the changes, committed, and found out that I could not continue the PR because my branch was "deleted" even though neither I nor my colleague had done so. I tried updating to 1.18.3 and we did a simple test (same as steps above) on new branches with the same results.

Sadly, I could not reproduce the bug on the Gitea demo site due to strict network settings at my workplace. Our Gitea runs only locally behind all the firewalls, nats, proxys and whatsoever is set by our computer department.

### Gitea Version

1.18.3 (also 1.18.2)

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/lunakiller/f32476e4cbf09ae61badc37ae22088a5

### Screenshots

gitea_bug_pr_closed
gitea_bug_branch

### Git Version

2.39.1

### Operating System

Windows 10 Enterprise

### How are you running Gitea?

Prebuilt windows binary ran from cmd

### Database

MySQL

### PR DESCRIPTION
**Pull request by sillyguodong**
Close: #22784

1. On GH, we can reopen a PR which was closed before after pushing commits. After reopening PR, we can see the commits that were pushed after closing PR in the time line. So the case of [issue](https://github.com/go-gitea/gitea/issues/22784) is a bug which needs to be fixed.

2. After closing a PR and pushing commits, `headBranchSha` is not equal to `sha`(which is the last commit ID string of reference). If the judgement exists, the button of reopen will not display. So, skip the judgement if the status of PR is closed.
image

3. Even if PR is already close, we should still insert comment record into DB when we push commits.
So we should still call  function `CreatePushPullComment()`.
https://github.com/go-gitea/gitea/blob/067b0c2664d127c552ccdfd264257caca4907a77/services/pull/pull.go#L260-L282
So, I add a switch(`includeClosed`) to the `GetUnmergedPullRequestsByHeadInfo` func to control whether the status of PR must be open. In this case, by setting `includeClosed` to `true`, we can query the closed PR.
image

4. In the loop of comments, I use the`latestCloseCommentID` variable to record the last occurrence of the close comment. 
In the go template, if the status of PR is closed, the comments whose type is `CommentTypePullRequestPush(29)` after `latestCloseCommentID` won't be rendered.
image
e.g.
1). The initial status of the PR is opened.
image
2). Then I click the button of `Close`.  PR is closed now.
image
3). I try to push a commit to this PR, even though its current status is closed.
image
But in comments list, this commit do not display.This is as expected ：）
image
4). Click the `Reopen` button, the commit which is pushed after closing PR display now.
image

### CODE REVIEW

File: routers/web/repo/pull.go [hunk 1]
```diff
@@ -587,7 +587,7 @@ func PrepareViewPullInfo(ctx *context.Context, issue *issues_model.Issue) *git.C
 	ctx.Data["HeadBranchCommitID"] = headBranchSha
 	ctx.Data["PullHeadCommitID"] = sha
 
-	if pull.HeadRepo == nil || !headBranchExist || headBranchSha != sha {
+	if pull.HeadRepo == nil || !headBranchExist {
```
Comment (brechtvl) [inline routers/web/repo/pull.go]: We've run into cases where a PR had a difference in these SHAs and so was shown as broken, even when it had never been closed. But we have not been able to get a clear repro case yet.

Maybe this test can be skipped for closed PRs, but remain for open PRs? If what's shown in the PR and what's in the head branch is not the same, I think it's important to show that to avoid accidentally merging the wrong code.

Comment (sillyguodong) [reply routers/web/repo/pull.go]: okey, now skip the test when only the PR is closed

File: routers/web/repo/issue.go [hunk 2]
```diff
@@ -1622,9 +1622,14 @@ func ViewIssue(ctx *context.Context) {
 			comment.Type == issues_model.CommentTypeStopTracking {
 			// drop error since times could be pruned from DB..
 			_ = comment.LoadTime()
+		} else if comment.Type == issues_model.CommentTypeClose {
+			// record latest index of close comment.
+			latestCloseCommentIndex = i
```
Comment (wolfogre) [inline routers/web/repo/issue.go]: Why not
```suggestion
			latestCloseCommentID = comment.ID
```
?

File: templates/repo/issue/view_content/comments.tmpl [hunk 3]
```diff
@@ -1,5 +1,6 @@
 {{template "base/alert"}}
-{{range .Issue.Comments}}
+<div>
```
Comment (wolfogre) [inline templates/repo/issue/view_content/comments.tmpl]: Do we really need this new div?

**Review by wolfogre — APPROVED** [review]

**Comment by wolfogre** [comment]
Sorry, approve by accident.

**Comment by wolfogre** [comment]
Sorry, approved by accident.

File: templates/repo/issue/view_content/comments.tmpl [hunk 4]
```diff
@@ -117,6 +117,9 @@
 					{{end}}
 				</span>
 			</div>
+			{{if and .Issue.IsClosed (eq $.LatestCloseCommentID .ID)}}
```
Comment (wolfogre) [inline templates/repo/issue/view_content/comments.tmpl]: What if we post a comment for a closed PR?

**Review by wolfogre — CHANGES_REQUESTED** [review]

**Review by wolfogre — APPROVED** [review]

**Review by lunny — APPROVED** [review]

File: templates/repo/issue/view_content/comments.tmpl [hunk 5]
```diff
@@ -697,7 +697,11 @@
 				</span>
 			</div>
 		{{else if and (eq .Type 29) (or (gt .CommitsNum 0) .IsForcePush)}}
-			<div class="timeline-item event" id="{{.HashTag}}">
+			<!-- If PR is closed, the comments whose type is CommentTypePullRequestPush(29) after latestCloseCommentID won't be rendered. //-->
+			{{if and .Issue.IsClosed (gt .ID $.LatestCloseCommentID)}}
+				{{continue}}
+			{{end}}`
+			<div class="timeline-item event" id="{{.HashTag}}">`
```
Comment (brechtvl) [inline templates/repo/issue/view_content/comments.tmpl:704]: Some stray backticks ended up here, they can be seen in the timeline in the screenshots in the description.

Comment (brechtvl) [reply templates/repo/issue/view_content/comments.tmpl:704]: https://github.com/go-gitea/gitea/pull/23282
