### PR TITLE
Set default lfs content path to data/lfs

### LINKED ISSUE #2508: LFS_CONTENT_PATH defaults to ''
- Gitea version (or commit ref): 1.2.0+rc2
- Git version: not relevant
- Operating system: Win 10 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I was trying to test out the LFS support, I flipped `LFS_START_SERVER` to `true` and I got this:

```
2017/09/14 18:50:16 [...s/setting/setting.go:735 NewContext()] [E] Failed to create '': mkdir : The system cannot find the path specified.
```

Manually adding `LFS_CONTENT_PATH = data/lfs` to my app.ini makes it run as intended, updating the conf file with `LFS_JWT_SECRET` and booting up without issues.

It should either default to `data/lfs` (updating the app.ini) or quit with a descriptive error message.

### PR DESCRIPTION
**Pull request by cez81**
As title. https://github.com/go-gitea/gitea/blob/d766d0c4e064bf7f66098123f39d15c2dc67e415/conf/app.ini#L161 it's already correct in app.ini

Fix #2508

### CODE REVIEW

File: modules/setting/setting.go [hunk 1]
```diff
@@ -737,6 +737,9 @@ func NewContext() {
 	}
 
 	if LFS.StartServer {
+		if LFS.ContentPath == "" {
```
Comment (lafriks) [inline modules/setting/setting.go]: I think this needs something like:
```
	sec = Cfg.Section("lfs")
	LFS.ContentPath = sec.Key("CONTENT_PATH").MustString(path.Join(AppDataPath, "lfs"))
	if !filepath.IsAbs(LFS.ContentPath) {
		LFS.ContentPath = filepath.Join(workDir, LFS.ContentPath)
	}
```

**Review by lafriks — CHANGES_REQUESTED** [review]

File: modules/setting/setting.go (hunk 1 above)
Comment (cez81) [reply modules/setting/setting.go]: Yes, you're right. Need to check if absolute path. Think the first bit is ok tho?

Comment (lafriks) [reply modules/setting/setting.go]: To be more consistent with other code I think it should be something like I gave example. Only thing I also have wrong for FS paths better is to use `filepath` methods not `path`

Comment (cez81) [reply modules/setting/setting.go]: Fair enough 👍 I have updated accordingly :)

Comment (lafriks) [reply modules/setting/setting.go]: @cez81 did you forgot to do git push?

Comment (cez81) [reply modules/setting/setting.go]: Forgot to commit... :/

File: modules/setting/setting.go [hunk 2]
```diff
@@ -732,11 +732,16 @@ func NewContext() {
 	SSH.AuthorizedKeysBackup = sec.Key("SSH_AUTHORIZED_KEYS_BACKUP").MustBool(true)
 	SSH.ExposeAnonymous = sec.Key("SSH_EXPOSE_ANONYMOUS").MustBool(false)
 
-	if err = Cfg.Section("server").MapTo(&LFS); err != nil {
+	sec = Cfg.Section("server")
+	if err = sec.MapTo(&LFS); err != nil {
 		log.Fatal(4, "Failed to map LFS settings: %v", err)
 	}
+	LFS.ContentPath = sec.Key("LFS_CONTENT_PATH").MustString(filepath.Join(AppDataPath, "lfs"))
```
Comment (lafriks) [inline modules/setting/setting.go:747]: either move this line after `if LFS.StartServer {` or move `if ...IsAbs(...` after this line so that both these lines are together

**Review by lafriks — CHANGES_REQUESTED** [review]

File: modules/setting/setting.go (hunk 2 above)
Comment (cez81) [reply modules/setting/setting.go:747]: 👍

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
LGTM

**Comment by lafriks** [comment]
Make LG-TM work

File: modules/setting/setting.go (hunk 2 above)
Comment (bkcsoft) [reply modules/setting/setting.go:747]: Set it like this instead: https://github.com/cez81/gitea/blob/d766d0c4e064bf7f66098123f39d15c2dc67e415/modules/setting/setting.go#L116
```go
}{
  ContentPath: "data/lfs"
}
```
As seen for example here: https://github.com/cez81/gitea/blob/d766d0c4e064bf7f66098123f39d15c2dc67e415/modules/setting/setting.go#L214

Comment (lafriks) [reply modules/setting/setting.go:747]: we really need to decide how to specify default value in code. We have at least two different ways to do that that is not very good :)

Comment (cez81) [reply modules/setting/setting.go:747]: I think setting it like this is better. Don't want to hard code the data folder, right?

**Comment by lunny** [comment]
LGTM
