### PR TITLE
Return go-get info on subdirs

### LINKED ISSUE #15625: go get for modules in subdirs broken since 1.14.x
- Gitea version (or commit ref): 1.14.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

Running go get on modules where the go.mod is in a subdir instead of the root eg `http://gitea/owner/repo/subdir?go-get=1` will now always return a 404 which makes `go get` fail.

On gitea 1.13 a 200 OK was returned

### PR DESCRIPTION
**Pull request by zeripath**
This PR is an alternative to #15628 and makes the go get handler a
handler.

Fix #15625

Close #15628

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: routers/routes/goget.go [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+	"net/http"
+	"net/url"
+	"path"
+	"strings"
+
+	"code.gitea.io/gitea/models"
+	"code.gitea.io/gitea/modules/context"
+	"code.gitea.io/gitea/modules/setting"
+	"code.gitea.io/gitea/modules/util"
+	"github.com/unknwon/com"
```
Comment (jolheiser) [inline routers/routes/goget.go:17]: Just because you're already fiddling here, maybe we could replace `com.Expand` with `os.Expand`? 🙂

File: routers/routes/goget.go [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+)
+
+func goGet(ctx *context.Context) {
+	if ctx.Req.Method != "GET" || ctx.Query("go-get") != "1" || len(ctx.Req.URL.Query()) > 1 {
```
Comment (jolheiser) [inline routers/routes/goget.go:21]: Wouldn't `len(ctx.Req.URL.Query()) > 1` always be true for `?go-get=1`

Comment (zeripath) [reply routers/routes/goget.go:21]: `> 1` not `> 0` ... this is so that it only fires if there is only 1 query param - go-get=1

Comment (jolheiser) [reply routers/routes/goget.go:21]: Aha, sorry I was thinking it returned the query-string. I see it returns `url.Values`.

File: routers/routes/goget.go (hunk 1 above)
Comment (zeripath) [reply routers/routes/goget.go:17]: it's doing something different from os.Expand.

It might be better to actually change this to use a go-template instead.

Comment (jolheiser) [reply routers/routes/goget.go:17]: Both are used to expand variables in strings. A template would also work.

**Comment by lunny** [comment]
It seems this still not resolve the sub dir problem. And I think with a test is better.

**Comment by zeripath** [comment]
@lunny what do you mean it does not resolve the subdir problem?

What are you expecting and what are you testing?

**Comment by zeripath** [comment]
With this patch as it stands:

```
> curl 'http://localhost/gitea/administrator/admin/asjdaljsda?go-get=1'                      [18:40:08]
<!doctype html>
<html>
	<head>
		<meta name="go-import" content="localhost/gitea/administrator/admin git http://localhost/gitea/administrator/admin.git">
		<meta name="go-source" content="localhost/gitea/administrator/admin _ http://localhost/gitea/administrator/admin/src/branch/master{/dir} http://localhost/gitea/administrator/admin/src/branch/master{/dir}/{file}#L{line}">
	</head>
	<body>
		go get --insecure localhost/gitea/administrator/admin
	</body>
</html>
```

**Comment by 6543** [comment]
I like the refactor ... can we still get some simple tests ;)

**Comment by zeripath** [comment]
if you could tell me what this is actually supposed to return then a numbskull test would be possible but I don't understand whether it is doing the correct thing

**Review by techknowlogick — APPROVED** [review]

**Comment by zeripath** [comment]
Test case added and conflicts resolved

**Review by 6543 — APPROVED** [review]
