### PR TITLE
Fix object does not exist error when checking citation file

### LINKED ISSUE #28264: checkCitationFile() [E] GetBlobContent: object does not exist [id: cff-version:, rel_path: ]
### Description

When I open a specicif mirror I get this

```
==> gitea.log <==
2023/11/28 18:21:14 ...ers/web/repo/view.go:716:checkCitationFile() [E] GetBlobContent: object does not exist [id: cff-version:, rel_path: ]
        /source/routers/web/repo/view.go:716 (0x256dd25)
        /source/routers/web/repo/view.go:967 (0x256f8f3)
        /source/routers/web/repo/view.go:746 (0x256dea4)
        /usr/local/go/src/reflect/value.go:596 (0x4ef806)
                Value.call: call(frametype, fn, stackArgs, uint32(frametype.Size()), uint32(abid.retOffset), uint32(frameSize), &regArgs)
        /usr/local/go/src/reflect/value.go:380 (0x4ee8d8)
                Value.Call: return v.call("Call", in)
        /source/modules/web/handler.go:166 (0x1aa451b)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:176 (0x1aa45b7)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:176 (0x1aa45b7)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:176 (0x1aa45b7)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:176 (0x1aa45b7)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:176 (0x1aa45b7)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/chain.go:31 (0x1a9b4c5)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 (0x1a9e419)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:176 (0x1aa45b7)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:176 (0x1aa45b7)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:176 (0x1aa45b7)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/middleware/get_head.go:37 (0x24c3d3b)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:145 (0x1aa47c3)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:176 (0x1aa45b7)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/context/context.go:222 (0x1bb822e)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:145 (0x1aa47c3)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /go/pkg/mod/gitea.com/go-chi/session@v0.0.0-20230613035928-39541325faa3/session.go:257 (0x1b11375)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:145 (0x1aa47c3)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:73 (0x1a9c0b5)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:316 (0x1a9d99a)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 (0x1a9e419)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:73 (0x1a9c0b5)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:316 (0x1a9d99a)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 (0x1a9e419)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/routing/logger_manager.go:122 (0x1a9acf8)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:145 (0x1aa47c3)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /go/pkg/mod/github.com/chi-middleware/proxy@v1.1.1/middleware.go:37 (0x24134d3)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:145 (0x1aa47c3)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/routers/common/middleware.go:45 (0x24146f2)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:145 (0x1aa47c3)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/routers/common/middleware.go:37 (0x2414278)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:145 (0x1aa47c3)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/routers/common/middleware.go:99 (0x2413835)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /source/modules/web/handler.go:145 (0x1aa47c3)
        /usr/local/go/src/net/http/server.go:2136 (0x996948)
                HandlerFunc.ServeHTTP: f(w, r)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:90 (0x1a9c074)
        /source/modules/web/route.go:175 (0x1aa5dc7)
        /usr/local/go/src/net/http/server.go:2938 (0x99962d)
                serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
        /usr/local/go/src/net/http/server.go:2009 (0x995513)
                (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
        /usr/local/go/src/runtime/asm_amd64.s:1650 (0x473ca0)
                goexit: BYTE    $0x90   // NOP
``` 

I can reimport the mirror. But there is a bug.

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

image

### Git Version

2.43.0

### Operating System

Ubuntu 22.04.3 LTS x86_64

### How are you running Gitea?

gitea-1.21.1-linux-amd64

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by yp05327**
Fix #28264

`DataAsync()` will be called twice.
Caused by https://github.com/go-gitea/gitea/pull/27958.
I'm sorry, I didn't completely remove all unnecessary codes.

### CODE REVIEW

**Review by delvh — APPROVED** [review]

**Review by lunny — APPROVED** [review]

File: routers/web/repo/view.go [hunk 1]
```diff
@@ -713,14 +713,7 @@ func checkCitationFile(ctx *context.Context, entry *git.TreeEntry) {
...
-			blob := entry.Blob()
-			dataRc, err := blob.DataAsync()
-			if err != nil {
-				ctx.ServerError("DataAsync", err)
-				return
-			}
-			defer dataRc.Close()
-			ctx.PageData["citationFileContent"], err = blob.GetBlobContent(setting.UI.MaxDisplayFileSize)
+			ctx.PageData["citationFileContent"], err = entry.Blob().GetBlobContent(setting.UI.MaxDisplayFileSize)
 			if err != nil {
```
Comment (wxiaoguang) [inline routers/web/repo/view.go]: Could it just ignore this error to prevent from users seeing unnecessary 500 pages?

I do not think reporting such error to end users really makes sense.

Comment (yp05327) [reply routers/web/repo/view.go]: Done.

File: routers/web/repo/view.go [hunk 2]
```diff
@@ -713,17 +713,9 @@ func checkCitationFile(ctx *context.Context, entry *git.TreeEntry) {
...
-				ctx.ServerError("DataAsync", err)
-				return
-			}
-			defer dataRc.Close()
-			ctx.PageData["citationFileContent"], err = blob.GetBlobContent(setting.UI.MaxDisplayFileSize)
-			if err != nil {
-				ctx.ServerError("GetBlobContent", err)
-				return
+				log.Error("checkCitationFile: GetBlobContent: %v", err)
```
Comment (wxiaoguang) [inline routers/web/repo/view.go:716]: It should be:

```
if content, err := entry.Blob().GetBlobContent(setting.UI.MaxDisplayFileSize); err == nil {
    ctx.Data["CitiationExist"] = true
    ctx.PageData["citationFileContent"] = content
} else {
    log.Error()
}
```

Comment (yp05327) [reply routers/web/repo/view.go:716]: Done.

**Comment by yp05327** [comment]
Do we need to move `break` in to the `if` above which has been done in https://github.com/go-gitea/gitea/pull/28314/commits/05d9cff28812f5bce00b700bfab70cac16c6c480?

**Review by wxiaoguang — APPROVED** [review]
