### PR TITLE
Fix get reviewers' bug

### LINKED ISSUE #32394: PR reviewers list contains invalid options
### Description

Steps to reproduce:
1. Create a repository owned by an organization.
2. Create a team in the org with the following permissions. Note: the team has read permission for at least one unit but _not for pull requests_
Screen Shot 2024-10-31 at 1 35 54 PM

3. Add a user to this team which is not a repo collaborator or part of any other team in the org. Notably, they do not have read permission for pull requests
4. They will show up as an option in the reviewers list in a pull request within this org:
Screen Shot 2024-10-31 at 1 35 33 PM
5. If selected, they will not be added and there is no error message

```
2024/10/31 13:34:51 ...rs/web/repo/issue.go:2532:UpdatePullReviewRequest() [W] UpdatePullReviewRequest: refusing to add invalid review request for <User 12:testsamluser> to <Repository 4:AuditOrg/Test-Repo>#1: Error: Reviewer can't read [user_id: 1, repo_id: 4]
```
Notes: 
```go

func GetReviewers(ctx context.Context, repo *Repository, doerID, posterID int64) ([]*user_model.User, error) {
        ...
	cond = cond.And(builder.In("`user`.id",
		builder.Select("user_id").From("access").Where(
			builder.Eq{"repo_id": repo.ID}.
				And(builder.Gte{"mode": perm.AccessModeRead}),
		),
	))
```
The `GetReviewers` function checks the `access` table to determine review eligibility. However, this table explicit stores the _highest_ level of access for a user within a repository:

```go
// Access represents the highest access level of a user to the repository. The only access type
// that is not in this table is the real owner of a repository. In case of an organization
// repository, the members of the owners team are in this table.
type Access struct {
	ID     int64 `xorm:"pk autoincr"`
	UserID int64 `xorm:"UNIQUE(s)"`
	RepoID int64 `xorm:"UNIQUE(s)"`
	Mode   perm.AccessMode
}
```

In this case, the `access` table will show the user as having read permission incorrectly.

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

command-lin

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
This PR rewrites `GetReviewer` function and move it to service layer.

Reviewers should not be watchers, so that this PR removed all watchers from reviewers. When the repository is under an organization, the pull request unit read permission will be checked to resolve the bug of #32394 

Fix #32394

### CODE REVIEW

File: services/pull/reviewer.go [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+			Distinct("`team_user`.uid").
+			Select("`team_user`.uid").
+			Find(&additionalUserIDs); err != nil {
+			return nil, err
+		}
+		uniqueUserIDs.AddMultiple(additionalUserIDs...)
+
+		if repo.Owner.Visibility.IsLimited() && doerID == 0 {
+			return nil, fmt.Errorf("permission denied")
+		}
```
Comment (yp05327) [inline services/pull/reviewer.go]: permission check in services? not in router?

Comment (lunny) [reply services/pull/reviewer.go]: Hm, why not. Because we need to load something and then check.

File: services/pull/reviewer.go [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+// GetReviewerTeams get all teams can be requested to review
+func GetReviewerTeams(ctx context.Context, repo *repo_model.Repository) ([]*organization.Team, error) {
+	if err := repo.LoadOwner(ctx); err != nil {
+		return nil, err
+	}
+	if !repo.Owner.IsOrganization() {
+		return nil, nil
+	}
+
+	return organization.GetTeamsWithAccessToRepo(ctx, repo.OwnerID, repo.ID, perm.AccessModeRead)
```
Comment (yp05327) [inline services/pull/reviewer.go]: This seems not correct. Correct one is `GetTeamsWithAccessToRepoUnit` (read, PR)

Comment (lunny) [reply services/pull/reviewer.go:107]: 213fddb04352cc888eadb8ee315c3f9e87317151

Comment (lunny) [reply services/pull/reviewer.go]: fc1e61c845765e580b1a07cab467cfc7be48bc31

File: services/pull/reviewer.go (hunk 1 above)
Comment (yp05327) [reply services/pull/reviewer.go]: First of all, the permission check I said above is the permission of access, not the permission of edit/update/create
For the access permission, if I understand correctly, the access control is in router or the handler, not in service.
The correct logic should be something like this I think:
router -> handler     -x>            services -> ...
      ↑   or     ↑
   access check

Comment (yp05327) [reply services/pull/reviewer.go]: And the permission check can be in another way, instead of finding all possible users and then check whether doer is in the results or not, just check whether user has the permission to access the repo(and PR?) directly.

**Review by jackHay22 — COMMENTED** [review]
👍

File: services/pull/reviewer.go (hunk 1 above)
Comment (lunny) [reply services/pull/reviewer.go]: 7e073ec81195dba8df11e4e0700d673166bc7530

**Review by kdumontnu — APPROVED** [review]
Nice :100: I think this is a great fix (whereas, we were using incorrect permissions before).

**Review by Zettat123 — APPROVED** [review]

**Comment by kdumontnu** [comment]
@wxiaoguang are you okay adding back the 1.22 backport? This is a pretty clear bug fix.

**Comment by wxiaoguang** [comment]
No block from my side since you have reviewed. 🙏
