### PR TITLE
Fix #19346 - Avoid MoreThanOne error when creating a branch whose name conflicts with other ref names

### LINKED ISSUE #19346: Using web interface to create branch from existing branch with identical release name leads to error 500
### Description

Hello ! 
When using the web interface to create branch, if you create from a branch that has the same name as a tag, this leads to a 500 error (tested on try.gitea.io)

Steps using the web interface:

1. Create a branch named "testing"
2. Create a tag (with or without release) with the "testing" branch, name it "testing"
3. Now go back to branches and try to create a branch from "testing"
4. Error 500 : log says : CreateNewBranch: Push: ErrMoreThanOne Error: exit status 1: error: src refspec testing matches more than one

### Gitea Version

1.16.5 / 1.17 dev

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://try.gitea.io/99rgosse/gitlab_to_gitea/src/branch/master/log

### Screenshots

image

### Git Version

> 2.27

### Operating System

Linux

### How are you running Gitea?

From Docker 1.16.5 and also on try.gitea.io

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by 99rgosse**
This simple commit will ensure that we specify the "Branch" prefix when we want to create new branch. Fix #19346

Otherwise git would check between /refs/heads/tags and /refs/heads/branch and return 
`error: src refspec mytest matches more than one.`
`error: failed to push some refs to 'branch'`
when there is a tag sharing the same name than the branch.

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
Although I think this is worthwhile I suspect that there will be multiple other problems further down the line. Have you completely tested how Gitea behaves when there are similar branch/tag names?

File: services/repository/branch.go [hunk 1]
```diff
@@ -35,7 +35,7 @@ func CreateNewBranch(ctx context.Context, doer *user_model.User, repo *repo_mode
 
 	if err := git.Push(ctx, repo.RepoPath(), git.PushOptions{
 		Remote: repo.RepoPath(),
-		Branch: fmt.Sprintf("%s:%s%s", oldBranchName, git.BranchPrefix, branchName),
+		Branch: fmt.Sprintf("%s%s:%s%s", git.BranchPrefix, oldBranchName, git.BranchPrefix, branchName),
```
Comment (wxiaoguang) [inline services/repository/branch.go:38]: The `oldBranchName` might be checked whether is has the `BranchPrefix` already (and handle the existing prefix gracefully). Otherwise there will be another error.

----

Hmm, not a must since the old code already works. It seems that this function requires that `oldBranchName` and `branchName` shouldn't not have the prefix.

**Review by wxiaoguang — APPROVED** [review]

**Comment by 99rgosse** [comment]
> Although I think this is worthwhile I suspect that there will be multiple other problems further down the line. Have you completely tested how Gitea behaves when there are similar branch/tag names?

I tested it manually on my built instance with latest main, and it worked :
Creating branches from the problematic branch, or creating from other branches
Even creating from branch of branch of the branch that is sharing the tag name.

Also creating a new file or a pull request in the branch that is sharing the tag name, and of children.

image

From the moment the Tag is created with the same name as the branch, I have seen no problems, but well...
If you want I can try to add more tests to this ?

**Comment by zeripath** [comment]
By testing I meant general UI testing. e.g. How does open PRs from this duplicate branch work? Will do the correct thing? Can you create a PR from the tag and/or the branch? Does it just default to the branch? What happens when you view the branches page on the repository? Do the counts work correctly? How about the Tag page?

**Comment by wxiaoguang** [comment]
> By testing I meant general UI testing. e.g. How does open PRs from this duplicate branch work? Will do the correct thing? Can you create a PR from the tag and/or the branch? Does it just default to the branch? What happens when you view the branches page on the repository? Do the counts work correctly? How about the Tag page?

Some of the questions seems more general to the PR modules (not affected by this one). Some questions like `Can you create a PR from the tag and/or the branch?` I think it's correct now (I have checked all calls to the `CreateNewBranch` before, all passed-in arguments are branch names). 

Are these questions as blocker?

**Review by delvh — APPROVED** [review]

**Comment by 6543** [comment]
please send backport
