### PR TITLE
Fix markdown anchor re-clicking

### LINKED ISSUE #21680: Anchors break after clicked once
### Description

I noticed something which makes navigating documentation on gitea quite irritating: anchors break after clicked once. An anchor on every other page I've ever visited can be clicked multiple times in a row with scrolling in between, and every subsequent click will re-center the view to the anchor. Not when viewing a markdown file on Gitea however, only the **first** click works and then it just won't recenter anymore.

Try here by clicking the "Test anchor", then scrolling away with it still in view, then click it again (which should recenter the view once more and undo the scroll, but it doesn't): https://try.gitea.io/blablablablab/BlaTest/src/branch/main/README.md

### Gitea Version

1.19.0+dev-39-g2900dc90a

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

[Screencast from 11-04-2022 12:52:41 PM.webm](https://user-images.githubusercontent.com/64124388/199966708-be47c4aa-f464-4906-9cc2-9c781574d60f.webm)

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

I'm not, but this reproduces on all instances run by others that i have tested

### Database

_No response_

### PR DESCRIPTION
**Pull request by silverwind**
The hashchange event did not fire on re-click of a active anchor. Instead, use the click event which always fires.

Fixes: https://github.com/go-gitea/gitea/issues/21680

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

File: web_src/js/markup/anchors.js [hunk 1]
```diff
@@ -2,10 +2,10 @@ import {svg} from '../svg.js';
 
 const headingSelector = '.markup h1, .markup h2, .markup h3, .markup h4, .markup h5, .markup h6';
 
-function scrollToAnchor() {
-  if (document.querySelector(':target')) return;
-  if (!window.location.hash || window.location.hash.length <= 1) return;
-  const id = decodeURIComponent(window.location.hash.substring(1));
+function scrollToAnchor(hash) {
+  if (document.querySelector(':target')) return; // something else on the page matches
+  if (hash?.length <= 1) return;
```
Comment (delvh) [inline web_src/js/markup/anchors.js]:
```suggestion
  if (!hash || document.querySelector(':target')) return; // no hash given or something else on the page matches
```
Also, isn't the second condition a bug?
Why would you not scroll to another anchor if something else is already targeted through the URL?
I simply don't see where it would be useful…

Comment (silverwind) [reply web_src/js/markup/anchors.js]: 1. Our `id`s in markdown HTML never match the anchors, so if there is a match indicated by `:target` presence, we know that something else on the page has matched which is not markdown content and we generally do not want to interfere with this browser-native behaviour.
2. I kept it on separate line so the comment association works
3. `!hash` introduces a bug when hash is just `#`.

Comment (delvh) [reply web_src/js/markup/anchors.js]: I can understand 2. and 3, but isn't 1. a similar case as described in the related issue?
Why should we not scroll, when you actively click on an anchor link, even if something else already matched?

Comment (delvh) [reply web_src/js/markup/anchors.js]: see for example githubs behavior of highlighting the box of the file in a PR diff your URL points at.
I'm fairly certain that it would still scroll, despite highlighting something else already?

Comment (silverwind) [reply web_src/js/markup/anchors.js]: Take this HTML:

```html
<h2 id="user-content-toc">
  <a class="anchor" href="#toc">svg</a>
  TOC
</h2>
```

Clicking the link triggers js to scroll to `user-content-toc`. I don't know the exact reason for this mismatch but it may be security-related.

Now the spec for `:target`:

> The :target [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) [pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) represents a unique element (the target element) with an [id](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#id) matching the URL's fragment.

With our markdown anchors, `:target` can never exist, and if it does, another anchor outside markdown is active, take for example hypothetical `#toc` that would link to a TOC outside. If the same name exists as `user-content-toc`, we would scroll to the markdown anchor without this condition. I generally think our own IDs are more important than ones created in user content, so I give our own a preference in such a conflict.

**Review by delvh — APPROVED** [review]
I still rather disagree about the external anchors, but I can accept the current state.

File: web_src/js/markup/anchors.js (hunk 1 above)
Comment (silverwind) [reply web_src/js/markup/anchors.js]: The point you are missing may be that if `:target` exists, the browser-has already scrolled somewhere (without JS, at page load), so if we remove the condition, it may scroll twice, once natively, and once via JS.

Comment (silverwind) [reply web_src/js/markup/anchors.js]: I guess a point could be made for subsequent user-initiated click on conflicting anchors in markdown, but I'm not sure how we could detect such cases. I think they are currently non-existant/very uncommon.

**Comment by silverwind** [comment]
I pushed a fix so that it only aborts when `:target` exists on page load, not on subsequent clicks.

File: web_src/js/markup/anchors.js (hunk 1 above)
Comment (silverwind) [reply web_src/js/markup/anchors.js]: Fixed below, it was actually a very easy fix.

**Review by delvh — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work
