### PR TITLE
Ignore DNS error when doing migration allow/block check

### LINKED ISSUE #19565: Migration from behind proxy fails
### Description

does the migrate functionality ignore proxy settings? our k8s gitea deployment is behind a firewall so we gotta use a proxy to connect to the outside world. I saw there's a bunch of apparently relevant configs but none seem to work:
1. i've set
```yaml
config:
  proxy:
    PROXY_ENABLED: true
    PROXY_URL: "http://our.proxy.with:port"
    PROXY_HOSTS: "*.github.com"
```
however this results in the only debug/error couple of lines spat out in the logs:
```
.../web/repo/migrate.go:142:handleMigrateRemoteAddrError() [E] Error whilst updating url: migration/cloning from 'github.com' is not allowed: unknown hostname
.../s/context/context.go:204:HTML() [D] Template: repo/migrate/github
```

2. i've left just PROXY_ENABLED set to true, the rest blank, and configured:
```yaml
env:
  - name: HTTP_PROXY
    value: "http://our.proxy.with:port"
# same for HTTPS_PROXY, http_proxy and https_proxy
  - name: no_proxy
    value: "local.network.com,localhost"
```
yet again, getting unknown hostname results

3. finally i've even tried to force git config thru the container's git user as `git confg --global http.proxy http://our.proxy.with:port `, with this setup i'm able to execute a raw git clone within the container succesfully, but as far as gitea goes it makes no difference, so i guess the gitea program itself never really calls git clone behind the scenes for this particular function

the proxy settings are all def correct as i'm able to `curl https://github.com` which prints out the entire webpage into my console

Some more investigation notes:
I noticed the [handleMigrateRemoteAddrError](https://github.com/go-gitea/gitea/blob/main/routers/web/repo/migrate.go#L124) got triggered, either by line 184 or 200 in the [MigratePost function](https://github.com/go-gitea/gitea/blob/main/routers/web/repo/migrate.go#L151) (no trace beyond last call shown - even with debug logging enabled - so i had to dig thru both); 
if it was 184 - [ParseRemoteAddr](https://github.com/go-gitea/gitea/blob/main/services/forms/repo_form.go#L96) which calls to https://pkg.go.dev/net/url#Parse that literally just parses a string, returns a url pointer, it doesn't actually ping the url or anything other fancy in the process, so a remoteAddr should be returned by the ParseRemoteAddr function, but it might be the one returning an error?
in a similar vein [IsMigrateURLAllowed](https://github.com/go-gitea/gitea/blob/main/services/migrations/migrate.go#L43) might be the one spitting out the error instead - namely the call to [net.LookupIP](https://github.com/go-gitea/gitea/blob/main/services/migrations/migrate.go#L84) that looks up the [ip using the local resolver](https://pkg.go.dev/net#LookupIP) ...could this be the culprit? the local resolver is different to the one behind the proxy right? so [this resolver method](https://pkg.go.dev/net#Resolver.LookupIPAddr) looks more appropriate if an alternative resolver is set up somehow before its called...

i'm p much out of other ideas at this point and hoping that someone more familiar with the codebase knows where the fix lies, any help is much appreciated!

### Gitea Version

1.16.6

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.30.3

### Operating System

alpine3.15

### How are you running Gitea?

Using the official helm chart from https://gitea.com/gitea/helm-chart/src/branch/master/values.yaml with no modifications to the original image

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by wxiaoguang**
As the title & comment.

Try to fix #19565
* #19565

### CODE REVIEW

File: services/migrations/migrate.go [hunk 1]
```diff
@@ -81,10 +81,9 @@ func IsMigrateURLAllowed(remoteURL string, doer *user_model.User) error {
 		err = nil //nolint
 		hostName = u.Host
 	}
-	addrList, err := net.LookupIP(hostName)
-	if err != nil {
-		return &models.ErrInvalidCloneAddr{Host: u.Host, NotResolvedIP: true}
-	}
+
+	// some users only use proxy, there is no DNS resolver. it's safe to ignore the LookupIP error
+	addrList, _ := net.LookupIP(hostName)
```
Comment (lunny) [inline services/migrations/migrate.go:86]: So if it's an unknown host, this step may spend a long time?

Comment (wxiaoguang) [reply services/migrations/migrate.go:86]: no

**Review by 6543 — APPROVED** [review]

**Review by lunny — APPROVED** [review]
