### PR TITLE
fix: if Mirrors repo no content is fetched, updated time should not b…

### LINKED ISSUE #3548: Mirror: if no content is fetched, updated should not be changed
- Gitea version (or commit ref): 1.3.3
- Git version: _not relevant_
- Operating system: _not relevant_
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [x] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
_not relevant_

## Description

In continuation of https://github.com/go-gitea/gitea/issues/1329 and of https://github.com/gogits/gogs/issues/4341 (of gogs project).

I think the updated time of mirrors in explore page should only be updated when someting changed in the mirror repo. This way, the firsts repos in the explore menu are only the most recently changed one.

They did it in this commit: https://github.com/gogits/gogs/commit/8d0417497b39aa196400d39c99bbd79cfb364f9f

## Screenshots

_not relevant_

### PR DESCRIPTION
**Pull request by appleboy**
maybe fix https://github.com/go-gitea/gitea/issues/3548 and https://github.com/go-gitea/gitea/issues/1329

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

File: models/repo_mirror.go [hunk 1]
```diff
@@ -264,6 +264,21 @@ func SyncMirrors() {
 			log.Error(4, "UpdateMirror [%s]: %v", repoID, err)
 			continue
 		}
+
```
Comment (lunny) [inline models/repo_mirror.go:269]: But line 263 has updated all the columns of the records.

**Review by lunny — CHANGES_REQUESTED** [review]

File: models/repo_mirror.go (hunk 1 above)
Comment (appleboy) [reply models/repo_mirror.go:269]: yes. It only update the `NextUpdateUnix` value. Right?

Comment (appleboy) [reply models/repo_mirror.go:269]: but we need to update the `updated_unix` field of `repo` table.

File: models/repo_mirror.go [hunk 2]
```diff
@@ -264,6 +264,21 @@ func SyncMirrors() {
...
+		// Get latest commit date and compare to current repository updated time,
+		// update if latest commit date is newer.
+		commitDate, err := git.GetLatestCommitTime(m.Repo.RepoPath())
+		if err != nil {
+			log.Error(2, "GetLatestCommitDate [%s]: %v", m.RepoID, err)
+			continue
+		} else if commitDate.Before(*m.Repo.UpdatedUnix.AsTimePtr()) {
```
Comment (lafriks) [inline models/repo_mirror.go]: 1) This will not fix already invalid values
2) If mirrored repo last commit is deleted with force push, this will not update to new latest commits time

Can't this be checked so to skip only when updated_unix equals commit time?

**Review by lafriks — CHANGES_REQUESTED** [review]

File: models/repo_mirror.go (hunk 1 above)
Comment (lunny) [reply models/repo_mirror.go:269]: @appleboy. No. It should only update `NextUpdateUnix` maybe I don't know. But in fact it will update all the columns included `updated_unix`. So that your PR will update the record twice.

Comment (appleboy) [reply models/repo_mirror.go:269]: @lunny Line 263 just update the `mirror` table and this PR update `updated_unix` field on the other table `repository`

Comment (lunny) [reply models/repo_mirror.go:269]: Oh, yes you are right. And maybe you can also refactor there to use one DB connection but not get connection from cache.

File: models/repo_mirror.go (hunk 2 above)
Comment (appleboy) [reply models/repo_mirror.go]: @lafriks You are right. Removed the following check.

```go
if commitDate.Before(*m.Repo.UpdatedUnix.AsTimePtr())
```

File: models/repo_mirror.go (hunk 1 above)
Comment (appleboy) [reply models/repo_mirror.go:269]: @lunny Done. See https://github.com/go-gitea/gitea/pull/3551/commits/e5e87651732fadb31ca1be30c939f6d291f39416

**Review by lunny — APPROVED** [review]

**Comment by appleboy** [comment]
@lafriks Waiting for your response.

File: models/repo_mirror.go [hunk 3]
```diff
@@ -260,10 +262,23 @@ func SyncMirrors() {
...
 		m.ScheduleNextUpdate()
-		if err = UpdateMirror(m); err != nil {
+		if err = updateMirror(sess, m); err != nil {
 			log.Error(4, "UpdateMirror [%s]: %v", repoID, err)
 			continue
 		}
+
+		// Get latest commit date and compare to current repository updated time,
+		// update if latest commit date is newer.
+		commitDate, err := git.GetLatestCommitTime(m.Repo.RepoPath())
```
Comment (lafriks) [inline models/repo_mirror.go]: Comment should also be fixed as there is no check anymore

**Review by lafriks — CHANGES_REQUESTED** [review]

File: models/repo_mirror.go (hunk 3 above)
Comment (appleboy) [reply models/repo_mirror.go]: See https://github.com/go-gitea/gitea/pull/3551/commits/ac27f460a0b43f4daad960975b5b71718a0fa9be

**Review by lafriks — APPROVED** [review]
