### PR TITLE
Fix database deadlock when update issue labels

### LINKED ISSUE #13923: Adding multiple labels in pull / issue detail page broken
- Gitea version (or commit ref):  1.14.0+dev-290-gb1cf7f4df (current gitea.com)
- Git version: ? (current gitea.com)
- Operating system: ? (current gitea.com)

- Database (use `[x]`):  (current gitea.com)
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL): 
  - [x] No, only on gitea.com https://gitea.com/gitea/tea/pulls/285
- Log gist:

## Description
1. Opening the label dropdown and selecting more than one label applies only one of the selected labels. Sometimes two, not consistent. So far never all selected labels.

2. Doing this several times adds the remaining labels, but in the action log / comments of the issue, only the first added label is displayed.

I didn't check in detail, but 2. makes me think this was introduced by #13304.
Another recent bug related to labels is #13688

## Screenshots
grafik

### LINKED ISSUE #17469: Batch calling of `updateIssuesMeta` causes database deadlock
### Gitea Version

dev(main)

### Description

Bug:

https://github.com/go-gitea/gitea/blob/141d1a2aa5ff31267661c1985f52e6c02eafea11/web_src/js/features/repo-legacy.js#L87-L91

It causes database deadlock and results in error response (some data can not be updated correctly, and the page can not be reloaded)

```
2021/10/28 17:51:22 .../repo/issue_label.go:209:UpdateIssueLabel() [E] RemoveLabel: Error 1213: Deadlock found when trying to get lock; try restarting transaction
2021/10/28 17:51:23 Completed POST /root/test/issues/labels 500 Internal Server Error in 421.528354ms
```

### PR DESCRIPTION
**Pull request by wxiaoguang**
Close https://github.com/go-gitea/gitea/issues/17469 , Close https://github.com/go-gitea/gitea/issues/13923

This fix updates issue labels one by one, and won't cause database deadlock.

In future, we can use a batch API to update all changed labels by one request.

### CODE REVIEW

File: web_src/js/features/repo-legacy.js [hunk 1]
```diff
@@ -84,18 +84,17 @@ export function initRepoCommentForm() {
...
-          const promise = updateIssuesMeta(
-            item['update-url'],
-            item.action,
-            item['issue-id'],
-            elementId,
-          );
-          promises.push(promise);
-        });
-        Promise.all(promises).then(() => window.location.reload());
+        (async function() {
```
Comment (Gusted) [inline web_src/js/features/repo-legacy.js:88]:
```suggestion
        // TODO: Add batch functionality and make this 1 network request.
        (async function() {
```
Let's add a simple TODO, so it won't be forgot that it can be improved.

**Review by Gusted — APPROVED** [review]

**Review by silverwind — APPROVED** [review]
It's slower but safer.

**Comment by wxiaoguang** [comment]
> It's slower but safer.

I think it won't be that slower, browsers have their limitations for concurrency requests to a web site, and since there are database transaction locks, the requests are still executed one by one.

**Comment by lunny** [comment]
I would like to merge then into one request.

**Comment by wxiaoguang** [comment]
> I would like to merge them into one request.

I'd like too, but not this time ..... there are other callers to updateIssuesMeta, so the first thing we can do now is to continue to refactor the `repo-legacy.js` 😂

File: web_src/js/features/repo-legacy.js [hunk 2]
```diff
@@ -84,18 +84,18 @@ export function initRepoCommentForm() {
...
-            item['update-url'],
-            item.action,
-            item['issue-id'],
-            elementId,
-          );
-          promises.push(promise);
-        });
-        Promise.all(promises).then(() => window.location.reload());
+        // TODO: Add batch functionality and make this 1 network request.
+        (async function() {
```
Comment (silverwind) [inline web_src/js/features/repo-legacy.js:88]: You could actually drop the IIFE and just make the handler function `async`. Less indentation ftw.

**Comment by delvh** [comment]
> This fix updates issue labels one by one, and won't cause database deadlock.

I find it a bit scary that this problem, which appears to be a backend problem, exists in the first place, and our solution to it is to fix the frontend?
If I understand that correctly, this solution only treats the symptoms, not the cause of the bug.
That does not seem like the most optimal solution to me.

**Comment by wxiaoguang** [comment]
trigger bot
