### PR TITLE
Fix incorrect text content detection

### LINKED ISSUE #36325: Content of text file with "LP" after 34 bytes not show in the repository view due to Golang's http.DetectContentType
### Description

I have encounter an issue on the web interface with some basic text file not displayed in the repository content preview.
You have the message "[View Raw]" to download the file as for a binary instead of the content displayed.

After some test, I found that the following 2 lines pasted on demo.gitea.com reproduced the problem.
```
# syntax=docker/dockerfile:1
ARG ALP
```
I stored two text file on https://demo.gitea.com/mg-cloud/gitea-issue-raw with, one OK et one KO just by changing the last letter for P to E (adding a space, a new line seems to solve the issue as well).
[Test KO](https://demo.gitea.com/mg-cloud/gitea-issue-raw/src/branch/master/testKO.txt)
[Test OK](https://demo.gitea.com/mg-cloud/gitea-issue-raw/src/branch/master/testOK.txt)

See screenshot below.

### Gitea Version

1.26.0+dev-209-g26602fd207 on demo.gitea.com

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Screenshoot with the file not displayed

Image

Screenshoot of a correct display with a character changed

Image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Problem reproduced on demo.gitea.com

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #36325

### CODE REVIEW

File: modules/typesniffer/typesniffer.go [hunk 1]
```diff
@@ -119,6 +119,17 @@ func DetectContentType(data []byte) SniffedType {
 		data = data[:SniffContentSize]
 	}
 
+	const typeMsFontObject = "application/vnd.ms-fontobject"
+	if ct == typeMsFontObject && len(data) > 34 {
+		// Stupid Golang blindly detects any content with 34th-35th bytes being "LP" as font, here we try to detect it again by hiding the "LP"
```
Comment (silverwind) [inline modules/typesniffer/typesniffer.go]:
```suggestion
		// Stupid Golang blindly detects any content with 34th-35th bytes being "LP" as font, here we try to detect it again by hiding the "LP"
		// https://github.com/golang/go/issues/77172
```

Add link for reference

**Comment by silverwind** [comment]
The file extension for `application/vnd.ms-fontobject` is `.eot` as per [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/MIME_types/Common_types). I think it would be better to do this workaround only when the file extension is not `.eot` (case-insensitive), so that these files can still be detected correctly.

File: modules/typesniffer/typesniffer.go (hunk 1 above)
Comment (wxiaoguang) [reply modules/typesniffer/typesniffer.go]: The link is already in the test, I don't want to duplicate it.

**Comment by wxiaoguang** [comment]
> The file extension for `application/vnd.ms-fontobject` is `.eot` as per [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/MIME_types/Common_types). I think it would be better to do this workaround only when the file extension is not `.eot` (case-insensitive), so that these files can still be detected correctly.

Not everywhere can provide file extension. Or you can implement your proposal in another PR

**Comment by silverwind** [comment]
Yeah I understand that file extension is not a acceptable parameter for a type sniffer, so I guess if not all call sites can provide a file extension, we may have to disable this `.eot` detection. Shouldn't  really matter much if we disable this detection because it's a binary type anyways, so could not show anything meaningful on the UI?

**Comment by wxiaoguang** [comment]
You can edit this PR directly to implement your proposal

**Comment by silverwind** [comment]
No, I don't want to add a file extension parameter to the type sniffer, it's not something a type sniffer should be concerned with.

I was just wondering if the workaround could be moved to the code that calls it (where the extension is available).

**Comment by wxiaoguang** [comment]
I don't know the details of your proposal, so I can't comment more, and don't see the things to do.

To make code review more efficient, as Linus said: "show me the code" if you have better ideas.

**Comment by silverwind** [comment]
My point is you are preventing the type sniffer from detecting EOT files via file content. Likely this does not matter in the contexts where the type sniffer is used, but if it does, the file extension could be used as a alternative indicator for that type.

**Comment by silverwind** [comment]
Oh and btw I would not call golang "Stupid", they are just following the whatwg standard, and the standard is defect imho.

**Comment by wxiaoguang** [comment]
> My point is you are preventing the type sniffer from detecting EOT files via file content.

No, I didn't prevent. Please read the code, or show me a real example.

**Comment by wxiaoguang** [comment]
> Oh and btw I would not call golang "Stupid", they are just following the whatwg standard, and the standard is defect imho.

IMHO they are, since they "insist on adhering to these meaningless, rigid, and unreasonable 'standards'", close the issue without thinking, and "hurting end users, surprising developers, and wasting time on closing these duplicate reports"

**Review by TheFox0x7 — APPROVED** [review]
to be fair even if this change would block .eot files from being guessed I really don't see why would someone use this format https://caniuse.com/eot

and the check is bad in general https://www.w3.org/submissions/EOT/
hooking at x00's in version would be less error prone - https://goplay.tools/snippet/_Fp4rACHTXI

**Comment by wxiaoguang** [comment]
> to be fair even if this change would block .eot files from being guessed I really don't see why would someone use this format https://caniuse.com/eot
> 
> and the check is bad in general https://www.w3.org/submissions/EOT/ hooking at x00's in version would be less error prone - https://goplay.tools/snippet/_Fp4rACHTXI

Thank you very much for the details, I took that into the new function `isEmbeddedOpenType` and used the real eot content for testing

**Review by lunny — APPROVED** [review]
