### PR TITLE
Rework and fix stopwatch

### LINKED ISSUE #30721: Stopwatch UI regression
image

### PR DESCRIPTION
**Pull request by silverwind**
Fixes https://github.com/go-gitea/gitea/issues/30721 and overhauls the stopwatch. Time is now shown inside the "dot" icon and on both mobile and desktop. All rendering is now done by `<relative-time>`, the `pretty-ms` dependency is dropped.

Desktop:
Screenshot 2024-04-29 at 22 33 27

Mobile:
Screenshot 2024-04-29 at 22 34 19

Note for tippy:
Previously, tippy instances defaulted to "menu" theme, but that theme is really only meant for `.ui.menu`, so it was not optimal for the stopwatch popover.

This introduces a unopinionated `default` theme that has no padding and should be suitable for all content. I reviewed all existing uses and explicitely set the desired `theme` on all of them.

### CODE REVIEW

File: web_src/js/features/stopwatch.js [hunk 1]
```diff
@@ -161,6 +164,11 @@ function updateStopwatchTime(seconds) {
     const delta = Date.now() - start;
     const dur = prettyMilliseconds(secs * 1000 + delta, {compact: true});
     if (stopwatch) stopwatch.textContent = dur;
+    // refresh the tippy so that the triangle updates to the correct position
+    if (stopwatchTippy.state.isShown) {
```
Comment (silverwind) [inline web_src/js/features/stopwatch.js]:
```suggestion
    if (stopwatchTippy?.state.isShown) {
```

File: templates/base/head_navbar.tmpl [hunk 2]
```diff
@@ -82,31 +82,33 @@
...
 				<span class="only-mobile tw-ml-2">{{ctx.Locale.Tr "active_stopwatch"}}</span>
 			</a>
-			<div class="active-stopwatch-popup item tippy-target tw-p-2">
-				<div class="tw-flex tw-items-center">
-					<a class="stopwatch-link tw-flex tw-items-center" href="{{.ActiveStopwatch.IssueLink}}">
-						{{svg "octicon-issue-opened" 16 "tw-mr-2"}}
+			<div class="active-stopwatch-popup tippy-target">
+				<div class="tw-flex tw-items-center tw-gap-2 tw-p-3">
+					{{svg "octicon-issue-opened" 16}}
+					<a class="stopwatch-link tw-flex muted" href="{{.ActiveStopwatch.IssueLink}}">
```
Comment (delvh) [inline templates/base/head_navbar.tmpl]: Wait, the svg is no longer part of the link?
Why?

Comment (silverwind) [reply templates/base/head_navbar.tmpl]: I moved it because it allows me to use the parent flexbox to vertically center both the svg and the link. If we really want to make the svg clickable, then I need to `display: inline-flex` the link I guess to allow vertical centering.

**Review by delvh — APPROVED** [review]

**Comment by silverwind** [comment]
Doing some more tweaks...

**Comment by silverwind** [comment]
Ended up reworking this whole thing to `<relative-time>` and moved the time into the dot so it always shows:

**Review by delvh — APPROVED** [review]

**Comment by lunny** [comment]
Looks like the time should not be translated, otherwise

image

**Comment by silverwind** [comment]
> Looks like the time should not be translated, otherwise
> image

What do these symbols translate to?

**Comment by lunny** [comment]
> > Looks like the time should not be translated, otherwise
> > image
> 
> What do these symbols translate to?

It means `minutes` but in English it's `1m`. So I think they should not be translated. I think other languages will have the same problems.

**Comment by silverwind** [comment]
Yeah I guess chinese might work in the limited space available but we are probably better off not translating in this case because some languages might get too long.

**Comment by silverwind** [comment]
> Could we simply fix the bug and backport, instead of introducing too many unrelated changes?
> 
> Or use a separate (simple, pure-css) fix for backporting?

I see this as a low-risk backport still.

**Comment by wxiaoguang** [comment]
> > Could we simply fix the bug and backport, instead of introducing too many unrelated changes?
> > Or use a separate (simple, pure-css) fix for backporting?
> 
> I see this as a low-risk backport still. I did test all the other tippy instances.

But I can still see bugs

**Comment by silverwind** [comment]
> Looks like the time should not be translated, otherwise
> image

Fixed by setting english lang and disabling wrap:

Screenshot 2024-04-30 at 15 46 10

For the record, this is how it looked with `zh-CN` lang with no wrap:

Screenshot 2024-04-30 at 15 46 10

File: web_src/js/features/stopwatch.js [hunk 3]
```diff
@@ -124,9 +126,8 @@ async function updateStopwatch() {
 
 function updateStopwatchData(data) {
   const watch = data[0];
-  const btnEl = document.querySelector('.active-stopwatch-trigger');
+  const btnEl = document.querySelector('.active-stopwatch');
```
Comment (wxiaoguang) [inline web_src/js/features/stopwatch.js]: There are 2 elements now, why only `querySelector`?

File: web_src/js/modules/tippy.js [hunk 4]
```diff
@@ -94,6 +96,7 @@ function attachTooltip(target, content = null) {
 
 function switchTitleToTooltip(target) {
   let title = target.getAttribute('title');
+  if (target.getAttribute('data-no-tooltip')) return;
```
Comment (wxiaoguang) [inline web_src/js/modules/tippy.js]: No use?

**Comment by wxiaoguang** [comment]
I still do not think it is safe to backport.

File: web_src/js/modules/tippy.js (hunk 4 above)
Comment (wxiaoguang) [reply web_src/js/modules/tippy.js]: TBH, I see how you use it, but I have objection for doing so.

Do not show too many texts on the UI, and do not abuse relative-time and/or title/tooltip

Comment (silverwind) [reply web_src/js/modules/tippy.js]: I've removed it in https://github.com/go-gitea/gitea/pull/30732/commits/729864b0150fc919bfe499fa9be2e549073b6afc, turns out setting title to empty string results in `<relative-time>` not showing any title and therefor no tooltip is created, which is what I wanted here.

File: web_src/js/features/stopwatch.js (hunk 3 above)
Comment (silverwind) [reply web_src/js/features/stopwatch.js]: Fixed in https://github.com/go-gitea/gitea/pull/30732/commits/9c0be40547733872153fba1926fb0fe50199c9fd.

**Comment by silverwind** [comment]
Even if there are issues, those are not world-breaking and I'm sure we can fix them quickly.

**Review by wxiaoguang — APPROVED** [review]
Still I believe it should avoid unnecessary changes.
