### PR TITLE
Fix mermaid diagram height when initially hidden

### LINKED ISSUE #32392: Mermaid diagram does not work inside `<details>` tag
### Description

Wrapping a mermaid diagram into a `<details>` tag causes its height to be invalid.

To reproduce create a comment with following contents:
````markdown
<details>

```mermaid
---
title: Order example
---
erDiagram
    CUSTOMER ||--o{ ORDER : places
    ORDER ||--|{ LINE-ITEM : contains
    CUSTOMER }|..|{ DELIVERY-ADDRESS : uses
```

</details>
````

Reproduction on demo: https://demo.gitea.com/rijenkii/tjest/issues/2.

### Gitea Version

1.23.0+dev-567-g9df5ddaf44

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Demo

### Database

None

### PR DESCRIPTION
**Pull request by silverwind**
In a hidden iframe, `document.body.clientHeight` is not reliable. Use `IntersectionObserver` to detect the visibility change and update the height there.

Fixes: https://github.com/go-gitea/gitea/issues/32392

image

### CODE REVIEW

File: web_src/js/markup/mermaid.ts [hunk 1]
```diff
@@ -57,10 +57,20 @@ export async function renderMermaid() {
       btn.setAttribute('data-clipboard-text', source);
       mermaidBlock.append(btn);
 
+      const updateIframeHeight = () => {
+        iframe.style.height = `${iframe.contentWindow.document.body.clientHeight}px`;
+      };
+
+      // update height when element's visibility state changes, for example when the diagram is inside
+      // a <details> + <summary> block and the <details> block becomes visible upon user interaction
```
Comment (silverwind) [inline web_src/js/markup/mermaid.ts]:
```suggestion
      // a <details> + <summary> block and the <details> block becomes visible upon user interaction, it
      // would initially set a incorrect height and the correct height is set during this callback.
```

**Review by delvh — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
-> mermaid render error with html details tag #36515

not sure whether it is a regression of #32599, or the fix just doesn't work.

**Comment by wxiaoguang** [comment]
I think "the fix just doesn't work.", the layout problem is quite tricky, it shouldn't use iframe body's client height.

-> Fix various mermaid bugs #36547
