### PR TITLE
Correctly handle failed migrations

### LINKED ISSUE #17571: Failed mirror will be not deleted
### Gitea Version

1.15.6

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.3

### How are you running Gitea?

Self hostet

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Description

Just try to mirror an not existing project. Gitea (can be resproduce on Gitea demo site with 1.60.x too) creates a new project. Afte the error will be shown, the created project will be not remowed. If you open it in Giteate (https://try.gitea.io/somera/nethogss) than you see HTTP ERROR 500. The project could be deleted only in the admin repo view.

This bug exists (I think) since Gitea 1.15.4 or 1.15.5.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by zeripath**
There is a bug in handling failed migrations whereby the migration task gets decoupled
from the migration repository. This leads to a failure of the task to get deleted with
the repository and also leads to the migration failed page resulting in a ISE.

This PR reloads the repo before the zeroing out of the repo id from the migration task. This should mean that the repo is much more likely to get deleted but we also make
the migration handler tolerate missing tasks much nicer. 

Fix #17571

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
Now - this has the result that the reason for the failed migration may never get shown to the user.

To that end we could remove the auto repository delete from the failed migration handler.

File: modules/task/migrate.go [hunk 1]
```diff
@@ -58,11 +58,12 @@ func runMigrateTask(t *models.Task) (err error) {
 		t.EndTime = timeutil.TimeStampNow()
 		t.Status = structs.TaskStatusFailed
 		t.Message = err.Error()
-		t.RepoID = 0
-		if err := t.UpdateCols("status", "errors", "repo_id", "end_time"); err != nil {
+		if err := t.UpdateCols("status", "errors", "end_time"); err != nil {
```
Comment (zeripath) [inline modules/task/migrate.go]:
```suggestion

		_ = t.LoadRepo()

		t.RepoID = 0
		if err := t.UpdateCols("status", "errors", "repo_id", "end_time"); err != nil {
```

File: modules/task/migrate.go [hunk 2]
```diff
@@ -58,11 +58,12 @@ func runMigrateTask(t *models.Task) (err error) {
...
 			log.Error("Task UpdateCols failed: %v", err)
 		}
 
+		_ = t.LoadRepo()
+
```
Comment (zeripath) [inline modules/task/migrate.go]:
```suggestion
```

File: modules/task/migrate.go [hunk 3]
```diff
@@ -58,11 +58,12 @@ func runMigrateTask(t *models.Task) (err error) {
 		t.EndTime = timeutil.TimeStampNow()
 		t.Status = structs.TaskStatusFailed
 		t.Message = err.Error()
-		t.RepoID = 0
-		if err := t.UpdateCols("status", "errors", "repo_id", "end_time"); err != nil {
+		if err := t.UpdateCols("status", "errors", "end_time"); err != nil {
 			log.Error("Task UpdateCols failed: %v", err)
 		}
 
+		_ = t.LoadRepo()
```
Comment (zeripath) [inline modules/task/migrate.go]:
```suggestion
```

**Comment by zeripath** [comment]
Now as a follow-up to this we need to make the UI for the user to view their tasks.

**Review by lunny — APPROVED** [review]

File: modules/task/migrate.go [hunk 4]
```diff
@@ -58,6 +58,9 @@ func runMigrateTask(t *models.Task) (err error) {
 		t.EndTime = timeutil.TimeStampNow()
 		t.Status = structs.TaskStatusFailed
 		t.Message = err.Error()
+
```
Comment (Gusted) [inline modules/task/migrate.go]:
```suggestion
	// Reloads the repo before we zero out repo's ID, this is to prevent
	// that the repo cannot be deleted.
```

Let's add a comment for such "unusual" line of code.

**Review by Gusted — CHANGES_REQUESTED** [review]

File: modules/task/migrate.go (hunk 4 above)
Comment (zeripath) [reply modules/task/migrate.go]:
```suggestion
	// Ensure that the repo loaded before we zero out the repo ID from the task - thus ensuring that we can delete it
```

**Review by Gusted — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]
