### PR TITLE
Return nicer error if trying to pull from non-existent user

### LINKED ISSUE #18225: Use more friendly error message when a repository can not be accessed
Now, if users access an invalid repository (non-existing, renamed, etc), they would see:

```
$ git fetch
Gitea: Internal Server Error
Gitea: Internal Server Error
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The `Internal Server Error` is quite misleading and there is a error level message in Gitea log: 

```
...ters/private/serv.go:114:ServCommand() [E] Unable to get repository owner: org-name/repo-name Error: user does not exist [uid: 0, name: org-name, keyid: 0]
```

Since such case is not an serious error, users should not see the `Internal Server Error` or the error level log messages.

### PR DESCRIPTION
**Pull request by zeripath**
Gitea serv will currently return an 500 if we try to pull from a repository where
the owner does not exist.

This PR checks for the UserNotExist Error when checking for the user and will
return a NotFound error instead.

Fix #18225

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]
Hmm .... LGTM 

The `log.Error("Failed authentication attempt (cannot find repository:` reads a little strange ...

And in my mind the level could be Info or Warning. For example, if some crawlers or scanners try to iterate non-existing repositories, site admin would see a lot of Error messages in their log, but it's not really an error.

**Comment by zeripath** [comment]
The rest of unauth'd log messages in that file are error but you're right I'll move them to warn

**Review by delvh — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

File: routers/private/serv.go [hunk 1]
```diff
@@ -111,8 +111,17 @@ func ServCommand(ctx *context.PrivateContext) {
...
+			log.Warn("Failed authentication attempt (cannot find repository: %s/%s) from %s", results.OwnerName, results.RepoName, ctx.RemoteAddr())
+			ctx.JSON(http.StatusNotFound, private.ErrServCommand{
+				Results: results,
+				Err:     fmt.Sprintf("Cannot find repository: %s/%s", results.OwnerName, results.RepoName),
+			})
+			return
+		}
 		log.Error("Unable to get repository owner: %s/%s Error: %v", results.OwnerName, results.RepoName, err)
-		ctx.JSON(http.StatusInternalServerError, private.ErrServCommand{
+		ctx.JSON(http.StatusForbidden, private.ErrServCommand{
```
Comment (lunny) [inline routers/private/serv.go:124]: 403 means the repository is exist but user has no access and 404 means the repository is not exist? That will leak something.

Comment (wxiaoguang) [reply routers/private/serv.go:124]: The old code (below) is 

```
	if !owner.IsOrganization() && !owner.IsActive {
		ctx.JSON(http.StatusForbidden, private.ErrServCommand{
			Results: results,
			Err:     "Repository cannot be accessed, you could retry it later",
		})
		return
	}
...
...
ctx.JSON(http.StatusUnauthorized, private.ErrServCommand{
  Results: results,
  Err:     fmt.Sprintf("User: %d:%s with Key: %d:%s is not authorized to %s %s/%s.", user.ID, user.Name, key.ID, key.Name, modeString, ownerName, repoName),
})

```

It was already 401 vs 403 vs 500 (with different message) before, not too much different. To prevent from leaking, we should re-design all the response codes and messages.

Comment (zeripath) [reply routers/private/serv.go:124]: This is an internal URL endpoint. The status code is not shown to the user. Look at what cmd/serv.go does with this result instead of looking at what it is returning.
