### PR TITLE
Fix internal server error when updating labels without write permission

### LINKED ISSUE #32775: 403 Forbidden Error when updating labels via REST API
### Description

As per title, I'm getting a 403 Forbidden Error when updating labels for issues via REST API. Tried with both the issue id and name. Seems to only happen to my instance (all repositories) running version 1.22.4 in Docker, as I've tested on the demo site (v1.23.0) and cloudron (1.22.4) without any issues.

### Gitea Version

1.22.4

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/m4l0n/eb982cd419bd05cf4924e0e886672774

### Screenshots

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker installation

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by yp05327**
Fix #32775

if permission denined, `prepareForReplaceOrAdd` will return nothing, and this case is not handled.

### CODE REVIEW

File: routers/api/v1/repo/issue_label.go [hunk 1]
```diff
@@ -351,8 +351,8 @@ func prepareForReplaceOrAdd(ctx *context.APIContext, form api.IssueLabelsOption)
 	}
 
 	if !ctx.Repo.CanWriteIssuesOrPulls(issue.IsPull) {
```
Comment (yp05327) [inline routers/api/v1/repo/issue_label.go:353]: The permission check is a bit strange. Why pull request unit permission is checked?

Comment (Zettat123) [inline routers/api/v1/repo/issue_label.go]: Maybe we could check permissions before querying the labels from db, so that we can return immediately if the doer doesn't have permissions.

Comment (yp05327) [reply routers/api/v1/repo/issue_label.go]: 8e7f3669ff76675a38daa2242223c1da5067be4f

**Review by Zettat123 — APPROVED** [review]

**Review by lunny — APPROVED** [review]
