### PR TITLE
Fix URL related escaping for oauth2

### LINKED ISSUE #36409: OAuth2 Authentication Service Redirect URL Does Not Encode Apostrophes
### Description
When configuring an OAuth2 Authentication Service through the Gitea web interface, the suggested Redirect/Callback URL fails to properly encode apostrophes in the Authentication Name field.

### Steps to Reproduce
- Navigate to Site Administration → Authentication Sources
- Add a new OAuth2 authentication source
- Enter an Authentication Name containing an apostrophe (e.g., LiBER's Microsoft Entra)
- Observe the auto-generated Redirect/Callback URL

### Expected Behavior
The apostrophe character ' should be percent-encoded as %27 in the suggested Redirect/Callback URL according to RFC 3986.
Example: https://gitea.internal.liberbattery.it/user/oauth2/LiBER%27s%20Microsoft%20Entra/callback

### Actual Behavior
The apostrophe remains unencoded in the suggested URL.
Example: https://gitea.internal.liberbattery.it/user/oauth2/LiBER's%20Microsoft%20Entra/callback

### Impact
This creates an invalid URL that will cause OAuth2 callback failures when the authentication provider attempts to redirect back to Gitea. You have to change the Redirect URL manually

### Screenshots

Image

### Gitea Version

1.25.3 built with GNU Make 4.4.1, go1.25.5 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

_No response_

### Browser Version

Microsoft Edge Version 144.0.3719.82

### PR DESCRIPTION
**Pull request by wxiaoguang**
Follow up #37327. See the comments.

* Root problem: the design of OAuth2 providers is a mess, the display name is used as provider's name and used in the URL directly
* The regressions:
    * When trying to fix https://github.com/go-gitea/gitea/issues/36409 , it introduced inconsistent URL escaping for the "path" part.
* This fix: always use "path escaping" for the path part, add more tests to cover all escaping cases.

Now, frontend "pathEscape" and "pathEscapeSegments" generate exactly the same result as backend.

### CODE REVIEW

File: modules/templates/helper.go [hunk 1]
```diff
@@ -161,7 +161,14 @@ func htmlFormat(s any, args ...any) template.HTML {
...
 func queryEscape(s string) template.URL {
-	return template.URL(url.QueryEscape(s))
+	// Special case for space encoding:
+	// * RFC 3986: Uniform Resource Identifier (URI): %20
+	// * WHATWG HTML: application/x-www-form-urlencoded: +
+	// * JavaScript: encodeURIComponent() uses "%20". URLSearchParams uses "+"
+	//
+	// Actually, "%20" is always right for various cases, while "+" causes ambiguity.
+	// Unfornately, Golang's QueryEscape always uses "+" for spaces. Replace them.
+	return template.URL(strings.ReplaceAll(url.QueryEscape(s), "+", "%20"))
```
Comment (silverwind) [inline modules/templates/helper.go]: It's more nuanced:

- url.QueryEscape escapes with `+`
- url.PathEscape escapes with `%20`

So I think the correct approach may be to parse the URL and apply both function on path and query parts individually if a full URL is passed into here (but then the function is misnamed).

Comment (wxiaoguang) [reply modules/templates/helper.go]: Nope, still WIP. And need more tests.

The problem is quite complicated and we are still paying the technology debt for 1990s

**Comment by wxiaoguang** [comment]
Should be 100% correct now.

File: routers/web/auth/oauth.go [hunk 2]
```diff
@@ -36,9 +36,7 @@ import (
 
 // SignInOAuth handles the OAuth2 login buttons
 func SignInOAuth(ctx *context.Context) {
-	// the provider is escaped by backend QueryEscape and frontend urlQueryEscape
-	// so always use QueryUnescape to decode it
-	authName, _ := url.QueryUnescape(ctx.PathParamRaw("provider"))
+	authName := ctx.PathParam("provider")
```
Comment (silverwind) [inline routers/web/auth/oauth.go:39]: This switches the login entrypoint from `QueryUnescape(PathParamRaw(...))` to `PathParam(...)`, which fixes literal `+` but drops compatibility with the `/user/oauth2/<QueryEscape(name)>` URLs that current releases generate for provider names containing spaces. After an upgrade, any bookmarked or hard-coded `/user/oauth2/test+space` link now 404s, and the new integration test codifies that behavior below. Could this try the literal path-decoded lookup first and only fall back to `QueryUnescape(ctx.PathParamRaw("provider"))` when the exact name is missing?

Written by GPT-5.4.

File: tests/integration/oauth_test.go [hunk 3]
```diff
@@ -1098,19 +1099,44 @@ func TestSignInOauthCallbackSyncSSHKeys(t *testing.T) {
...
-	req := NewRequest(t, "GET", "/user/oauth2/"+url.QueryEscape(authName))
-	resp := session.MakeRequest(t, req, http.StatusTemporaryRedirect)
-	assert.Contains(t, resp.Header().Get("Location"), mockServer.URL+"/authorize")
+	req := MakeRequest(t, NewRequest(t, "GET", "/user/login"), http.StatusOK)
+	doc := NewHTMLParser(t, req.Body)
+	var oauth2Links []string
+	doc.Find(".external-login-link").Each(func(i int, s *goquery.Selection) {
+		oauth2Links = append(oauth2Links, s.AttrOr("href", ""))
+	})
+	assert.Equal(t, []string{
```
Comment (silverwind) [inline tests/integration/oauth_test.go:1131]: This assertion still depends on provider order. `GetOAuth2Providers` sorts by `Provider.Name()` in `services/auth/source/oauth2/providers.go`, and both sources added here are `openidConnect`, so ties fall back to DB/find order. That can make the test flap even though the rendered href set is correct. Sorting `oauth2Links` first or using `assert.ElementsMatch` would make it deterministic.

Written by GPT-5.4.

**Comment by silverwind** [comment]
Reviewed the current branch tip `f37d556` and left two inline comments.

1. `routers/web/auth/oauth.go`: switching the login entrypoint to pure path decoding breaks compatibility with existing `/user/oauth2/<QueryEscape(name)>` links for provider names containing spaces.
2. `tests/integration/oauth_test.go`: the new href list assertion depends on unstable provider ordering and can flap.

No additional high-confidence issues found beyond those.

File: routers/web/auth/oauth.go (hunk 2 above)
Comment (wxiaoguang) [reply routers/web/auth/oauth.go:39]: Don't understand. Nonsense review

File: tests/integration/oauth_test.go (hunk 3 above)
Comment (wxiaoguang) [reply tests/integration/oauth_test.go:1131]: Are you sure? Why you don't want fixed order here?

Comment (silverwind) [reply tests/integration/oauth_test.go:1131]: Should run test 100 times to ensure it's not flaky if this really relies on potentially unstable db ordering.

Comment (wxiaoguang) [reply tests/integration/oauth_test.go:1131]: Show me why it is flaky. Have you read the code? Don't you see the list is already sorted?

Comment (silverwind) [reply tests/integration/oauth_test.go:1131]: It's fine, I ran 100 times, no flake.

File: routers/web/auth/oauth.go (hunk 2 above)
Comment (silverwind) [reply routers/web/auth/oauth.go:39]: Verified, review is invalid.

**Review by silverwind — APPROVED** [review]

File: tests/integration/oauth_test.go (hunk 3 above)
Comment (wxiaoguang) [reply tests/integration/oauth_test.go:1131]: TBH, even if it is flaky, it means there is another bug in backend: the list should always be stable.

Otherwise, it can't be right for end users to make them sometimes see "A / B" while sometimes "B / A"

And actually, backend already sorts the list before rendering.

**Comment by silverwind** [comment]
And btw sorry for the invalid reviews from GPT-5.4. This was an experiment. It took like 10 times as long as Claude would and produced shitty results, so I will be more careful reviewing with that model in the future.

**Review by bircni — APPROVED** [review]
