### PR TITLE
Fix bug when migrating a private repository

### LINKED ISSUE #7644: [1.9.0+rc2] Migrate from Github private repo fails
- Gitea version (or commit ref): 1.9.0+rc2-14-g650fdceb5
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When trying to migrate a private Github repo, migration tool fails with following error:

`Authentication failed: Clone: exit status 128 - fatal: could not read Username for 'https://github.com': No such device or address`

I have tried following senarios:

1. Disable my two factor authentication and enter my username and password
2. Enter a Personal Access Token with full access on my account

As long as my repo is private the migrate tool fails. Finally if I make my repo public, migrate tool works as it should.

P.S. Gitea is awesome! Thank you :)

### PR DESCRIPTION
**Pull request by lunny**
Fix #7644

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

File: modules/migrations/gitea.go [hunk 1]
```diff
@@ -79,12 +80,22 @@ func (g *GiteaLocalUploader) CreateRepo(repo *base.Repository, opts base.Migrate
 		return err
 	}
 
+	var remoteAddr = repo.CloneURL
+	if len(opts.AuthUsername) > 0 {
+		u, err := url.Parse(repo.CloneURL)
```
Comment (guillep2k) [inline modules/migrations/gitea.go:85]: I think this should only be allowed if the schema is `https`. See [https://golang.org/pkg/net/url/#UserPassword](https://golang.org/pkg/net/url/#UserPassword).

**Review by zeripath — APPROVED** [review]

File: modules/migrations/gitea.go (hunk 1 above)
Comment (lunny) [reply modules/migrations/gitea.go:85]: Maybe we should show a warn message on ui if he is using a `http` but not `https`.
