### PR TITLE
Fix git.parseTagData

### LINKED ISSUE #14092: The API fails at displaying tags
- Gitea version (or commit ref): 1.14.0+dev-414-g4ef751215
- OS: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No Can't migrate expample repo

## Description

The API fails at displaying tags at https://*/api/v1/repos/nesbot/carbon/tags

### Migrated Repo to test

https://github.com/briannesbitt/Carbon.git

### Migration Error on try.gitea.io

Migrieren von https://github.com/briannesbitt/Carbon.git fehlgeschlagen.
PANIC whilst trying to do migrate task: runtime error: slice bounds out of range [130:129]

### API-Error on Self--hosted instance

PANIC: runtime error: slice bounds out of range [130:129]
/usr/local/go/src/runtime/panic.go:116 (0x43cf84)
/go/src/code.gitea.io/gitea/modules/git/tag.go:67 (0x8d2fb8)
/go/src/code.gitea.io/gitea/modules/git/repo_tag.go:104 (0x8cbde4)
/go/src/code.gitea.io/gitea/modules/git/repo_tag.go:173 (0x8cd1db)
/go/src/code.gitea.io/gitea/modules/git/repo_tag.go:208 (0x8cd6f4)
/go/src/code.gitea.io/gitea/routers/api/v1/repo/tag.go:48 (0x20973bd)
/usr/local/go/src/reflect/value.go:476 (0x4a4d26)
/usr/local/go/src/reflect/value.go:337 (0x4a4218)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xc65ed9)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xc658aa)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:126 (0xc673fc)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:116 (0x155bc08)
/go/src/code.gitea.io/gitea/modules/context/api.go:234 (0x155bbf6)
/usr/local/go/src/reflect/value.go:476 (0x4a4d26)
/usr/local/go/src/reflect/value.go:337 (0x4a4218)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:177 (0xc65ed9)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:137 (0xc658aa)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:126 (0xc673fc)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:116 (0x1510864)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/session/session.go:192 (0x151084d)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:82 (0xc67272)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:157 (0xc65bf4)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/inject/inject.go:135 (0xc65999)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/context.go:126 (0xc673fc)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:187 (0xc78d30)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/router.go:303 (0xc733e5)
/go/src/code.gitea.io/gitea/vendor/gitea.com/macaron/macaron/macaron.go:218 (0xc6c5ed)
/go/src/code.gitea.io/gitea/routers/routes/chi.go:289 (0x217d347)
/usr/local/go/src/net/http/server.go:2042 (0x1f7d2b1)
/go/src/code.gitea.io/gitea/vendor/github.com/go-chi/chi/mux.go:437 (0x1f7d2b2)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/vendor/github.com/go-chi/chi/mux.go:70 (0x1f7b04b)
/go/src/code.gitea.io/gitea/vendor/github.com/go-chi/chi/mux.go:298 (0x1f81301)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/vendor/github.com/go-chi/chi/mux.go:431 (0x1f7d2ea)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/routers/routes/chi.go:160 (0x217c231)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/routers/routes/chi.go:160 (0x217c231)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/modules/public/public.go:84 (0x13c7747)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/modules/public/public.go:84 (0x13c7747)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/routers/routes/chi.go:113 (0x217b7dd)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/routers/routes/chi.go:90 (0x217aa5c)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/vendor/github.com/go-chi/chi/middleware/realip.go:34 (0x1f8687c)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/go/src/code.gitea.io/gitea/vendor/github.com/go-chi/chi/mux.go:86 (0x1f7ae10)
/go/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0x1182bd3)
/usr/local/go/src/net/http/server.go:2042 (0x77d083)
/usr/local/go/src/net/http/server.go:2843 (0x780682)
/usr/local/go/src/net/http/server.go:1925 (0x77be8c)
/usr/local/go/src/runtime/asm_amd64.s:1374 (0x477dc0)

### PR DESCRIPTION
**Pull request by 6543**
fix #14092

### CODE REVIEW

File: modules/git/tag.go [hunk 1]
```diff
@@ -64,7 +64,7 @@ l:
 			}
 			nextline += eol + 1
 		case eol == 0:
-			tag.Message = string(data[nextline+1 : len(data)-1])
+			tag.Message = string(data[nextline : len(data)-1])
```
Comment (lunny) [inline modules/git/tag.go]: Then the first char is '\n'?

Comment (6543) [reply modules/git/tag.go]: oh right .. I have to rm the other one :)

File: modules/git/tag_test.go [hunk 2]
```diff
@@ -0,0 +1,76 @@
+// Copyright 2017 The Gitea Authors. All rights reserved.
```
Comment (6543) [inline modules/git/tag_test.go]:
```suggestion
// Copyright 2020 The Gitea Authors. All rights reserved.
```

**Comment by 6543** [comment]
@lunny thanks - good :eyes:!

File: modules/git/tag.go [hunk 3]
```diff
@@ -64,7 +64,7 @@ l:
 			}
 			nextline += eol + 1
 		case eol == 0:
-			tag.Message = string(data[nextline+1 : len(data)-1])
+			tag.Message = string(data[nextline+1:])
```
Comment (lunny) [inline modules/git/tag.go:67]: I think the panic is because of `nextline > len(data) -1`. It should not be resolved.

Comment (6543) [reply modules/git/tag.go:67]: At this point, can we use TrimSpace?

**Comment by zeripath** [comment]
We need to do something slightly different here.

The issue is a that parseTagData is sometimes passed the terminal newline and sometimes not.

I think your code potentially is correct without the terminal newline but all of the rest of the calls need to be similarly limited.

Our unit tests should probably use []byte arrays too.

**Comment by 6543** [comment]
@zeripath while test git migration from repo in reported issue ... out of 177 tags only 2 tags executed this function

So its not crear to me why this function exist ...

File: modules/git/tag.go (hunk 3 above)
Comment (zeripath) [reply modules/git/tag.go:67]: this is fine if we add LimitReaders to the appropriate places.

**Comment by zeripath** [comment]
Apply the below in addition

```diff
diff --git a/modules/git/repo_tree_nogogit.go b/modules/git/repo_tree_nogogit.go
index 416205d8a..867c3fa5a 100644
--- a/modules/git/repo_tree_nogogit.go
+++ b/modules/git/repo_tree_nogogit.go
@@ -33,7 +33,7 @@ func (repo *Repository) getTree(id SHA1) (*Tree, error) {
 
        bufReader := bufio.NewReader(stdoutReader)
        // ignore the SHA
-       _, typ, _, err := ReadBatchLine(bufReader)
+       _, typ, size, err := ReadBatchLine(bufReader)
        if err != nil {
                return nil, err
        }
@@ -41,7 +41,7 @@ func (repo *Repository) getTree(id SHA1) (*Tree, error) {
        switch typ {
        case "tag":
                resolvedID := id
-               data, err := ioutil.ReadAll(bufReader)
+               data, err := ioutil.ReadAll(io.LimitReader(bufReader, size))
                if err != nil {
                        return nil, err
                }
@@ -57,7 +57,7 @@ func (repo *Repository) getTree(id SHA1) (*Tree, error) {
                log("tag.commit.Tree: %s %v", commit.Tree.ID.String(), commit.Tree.repo)
                return &commit.Tree, nil
        case "commit":
-               commit, err := CommitFromReader(repo, id, bufReader)
+               commit, err := CommitFromReader(repo, id, io.LimitReader(bufReader, size))
                if err != nil {
                        _ = stdoutReader.CloseWithError(err)
                        return nil, err
```

**Comment by zeripath** [comment]
The function exists because most tags in that repo are not annotated tags. parseTagData only applies to annotated tags.

**Comment by zeripath** [comment]
The test is also fundamentally incorrect because the message is always trimmed and terminated with a new line with -m

**Review by zeripath — APPROVED** [review]

File: modules/git/tag_test.go [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+tagger Lucas Michot <lucas@semalead.com> 1484491741 +0100
+
+`), tag: Tag{
+			Name:      "",
+			ID:        SHA1{},
+			repo:      nil,
+			Object:    SHA1{0x3b, 0x11, 0x4a, 0xb8, 0x0, 0xc6, 0x43, 0x2a, 0xd4, 0x23, 0x87, 0xcc, 0xf6, 0xbc, 0x8d, 0x43, 0x88, 0xa2, 0x88, 0x5a},
+			Type:      "commit",
+			Tagger:    &Signature{Name: "Lucas Michot", Email: "lucas@semalead.com", When: time.Unix(1484491741, 0)},
+			Message:   "a",
```
Comment (6543) [inline modules/git/tag_test.go]: shouldn't this fail?

Comment (zeripath) [reply modules/git/tag_test.go]: damn I've used git commit -sam Again instead of git commit -sm

Comment (zeripath) [reply modules/git/tag_test.go]:
```suggestion
			Message:   "",
```

File: modules/git/tag_test.go [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+		assert.EqualValues(t, test.tag.Object, tag.Object)
+		assert.EqualValues(t, test.tag.Name, tag.Name)
+		assert.EqualValues(t, test.tag.Message, tag.Message)
+		assert.EqualValues(t, test.tag.Type, tag.Type)
+		if test.tag.Signature != nil && assert.NotNil(t, tag.Signature) {
+			assert.EqualValues(t, test.tag.Signature.Signature, tag.Signature.Signature)
+			assert.EqualValues(t, test.tag.Signature.Payload, tag.Signature.Payload)
+		} else {
+			assert.Nil(t, tag.Signature)
+		}
```
Comment (khmarbaise) [inline modules/git/tag_test.go:67]: Based on the fixture data which defined above (`testData`) this: `if test.tag.Signature != nil` is from my understanding always `nil` ? That would mean that the given `if ... else ` is not necessary... Or do I misunderstand a thing here? 
If it should not nil in some cases then some testData is missing?

File: modules/git/tag_test.go [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+		if test.tag.Tagger != nil && assert.NotNil(t, tag.Tagger) {
+			assert.EqualValues(t, test.tag.Tagger.Name, tag.Tagger.Name)
+			assert.EqualValues(t, test.tag.Tagger.Email, tag.Tagger.Email)
+			assert.EqualValues(t, test.tag.Tagger.When.Unix(), tag.Tagger.When.Unix())
+		} else {
+			assert.Nil(t, tag.Tagger)
+		}
+	}
```
Comment (khmarbaise) [inline modules/git/tag_test.go:75]: Here from my point of view the same thing because `test.tag.Tagger` would always not nil ?... WDYT?

File: modules/git/tag_test.go (hunk 5 above)
Comment (6543) [reply modules/git/tag_test.go:67]: It could be simplified a bit yes

In sort, it's a custom `assert.EqualValues(t, test.tag, tag)` ... witch would be false in any case ... :/

File: modules/git/tag_test.go (hunk 6 above)
Comment (6543) [reply modules/git/tag_test.go:75]: In short it 1. Check if value is expected ... 2. check if actual value is not nil (with assert test statement)
if expect & real is NOT nil, it checks the values
else (test already failed if expect != real, or nil is exptected - so...) test if result is nil

File: modules/git/tag_test.go (hunk 5 above)
Comment (khmarbaise) [reply modules/git/tag_test.go:67]: Ah sorry took a bit of time that you control the checking of the result of parseTagData based on the content of the fixture (testData)... now it makes sense to me... just missed that point.

**Review by khmarbaise — APPROVED** [review]
