### PR TITLE
Fix PR nil-dereference bug

### LINKED ISSUE #2190: labels: [macaron] invalid memory address or nil pointer dereference
- Gitea version (or commit ref): dde0052ca2c478f298942f6fbbe88d27259374ae
- Git version: 2.13.3
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/gitea-bigfile-test/foo/issues/1
  - [ ] No
  - [ ] Not relevant
- Log gist:
https://gist.github.com/philfry/f24d35399c2a0c470e907e6a17a00b45

## Description
when removing labels from issues the given error pops up and the labels are not getting removed.

Steps to reproduce:
1. go to issues → label
2. add a label "my label"
3. get back to issues
4. create new issue
5. select the newly created "my label" (the label should appear in this issue)
6. select "remove labels" (nothing happens)
7. profit.

The label can safely be removed when de-selecting it directly.

## Screenshots

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fixes #2190. Also adds unit tests for previously-broken methods.

### CODE REVIEW

**Comment by andreynering** [comment]
Trusted LGTM

File: models/issue.go [hunk 1]
```diff
@@ -148,6 +148,19 @@ func (issue *Issue) loadAssignee(e Engine) (err error) {
...
 }
 
+func (issue *Issue) loadPullRequest(e Engine) (err error) {
+	if issue.IsPull && issue.PullRequest == nil {
+		issue.PullRequest, err = getPullRequestByIssueID(e, issue.ID)
+		if err != nil {
+			if IsErrPullRequestNotExist(err) {
+				return err
+			}
+			return fmt.Errorf("getPullRequestByIssueID: %v", err)
```
Comment (lafriks) [inline models/issue.go]: Why reformat error here?

Comment (ethantkoenig) [reply models/issue.go]: Causality of moving code around, I'll change it back to what it previously was (`fmt.Errorf("getPullRequestByIssueID [%d]: %v", issue.ID, err)`)

File: models/issue.go [hunk 2]
```diff
@@ -148,6 +148,19 @@ func (issue *Issue) loadAssignee(e Engine) (err error) {
...
 }
 
+func (issue *Issue) loadPullRequest(e Engine) (err error) {
+	if issue.IsPull && issue.PullRequest == nil {
+		issue.PullRequest, err = getPullRequestByIssueID(e, issue.ID)
+		if err != nil {
+			if IsErrPullRequestNotExist(err) {
+				return err
+			}
+			return fmt.Errorf("getPullRequestByIssueID [%d]: %v", issue.ID, err)
```
Comment (lafriks) [inline models/issue.go:158]: But still I think it should be `loadPullRequest` in error message

Comment (ethantkoenig) [reply models/issue.go:158]: I can change it if you really want, but this is more consistent with the other `loadXYZ(..)` methods.

Comment (lafriks) [reply models/issue.go:158]: Sorry it is correct you are right

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
please force empty push
