### PR TITLE
Use async await to fix empty quote reply at first time

### LINKED ISSUE #22075: Quoting diff comments doesn't work at first
### Description

The Quote Reply Button doesn't work for comments done over a pull request diff.
In a second try, the quote works probably because at first try the editor is closed.

https://try.gitea.io/fsologureng/aria-testing/pulls/3#issuecomment-133188 

### Screenshots

image

image
image
image

### Gitea Version

	1.19.0+dev-169-g8fb1e53ca

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

_No response_

### Browser Version

Firefox 107.0

### LINKED ISSUE #23247: Javascript error when editing issue description / reply.
### Description

When editing the description or reply of a issue I get the following Javascript error:

`
JavaScript error: Uncaught TypeError: i.onChange is not a function (https://git.dionysussg.xyz/assets/js/index.js?v=1.20.0~dev-56-gde6c718b4 @ 60:408). Open browser console to see more details.
`

Console error:
```
Uncaught (in promise) TypeError: i.onChange is not a function
    at index.js?v=1.20.0~dev-56-gde6c718b4:60:408
    at easymde.9b7a25f9.js:13:3720
    at Bl (easymde.9b7a25f9.js:13:3200)
    at Ml (easymde.9b7a25f9.js:13:3477)
    at Lr (easymde.9b7a25f9.js:18:7672)
    at Bt.setValue (easymde.9b7a25f9.js:18:10623)
    at H.value (easymde.9b7a25f9.js:49:18586)
    at HTMLAnchorElement.<anonymous> (index.js?v=1.20.0~dev-56-gde6c718b4:96:3618)
    at Generator.next (<anonymous>)
    at _ (index.js?v=1.20.0~dev-56-gde6c718b4:91:7717)

Uncaught TypeError: i.onChange is not a function
    at index.js?v=1.20.0~dev-56-gde6c718b4:60:408
    at easymde.9b7a25f9.js:13:3720
    at Bl (easymde.9b7a25f9.js:13:3200)
    at Ml (easymde.9b7a25f9.js:13:3477)
    at Lr (easymde.9b7a25f9.js:18:7672)
    at HTMLDivElement.<anonymous> (easymde.9b7a25f9.js:18:10332)
```

### Screenshots

image

### Gitea Version

1.20.0+dev-56-gde6c718b4

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

_No response_

### Browser Version

Chrome 110.0.5481.178

### PR DESCRIPTION
**Pull request by HesterG**
The reason why quote reply is empty is when quote reply is clicked, it triggers the click function on `.comment-form-reply` button, and when the first time this function is triggered, easyMDE for the reply has not yet initialized, so that click handler of `.quote-reply` button in `repo-legacy.js` got an `undefined` as easyMDE, and the following  lines which put quoted reply into the easyMDE is not executed.
The workaround in this PR is to pass the replied content to '.comment-form-reply' button if  easyMDE is not yet initialized (quote reply first clicked) and put the replied content into it the after easyMDE is created.
Now quote reply on first click:

https://user-images.githubusercontent.com/17645053/221452823-fc699d50-1649-4af1-952e-f04fc8d2978e.mov

<br />

Update:
The above change is not appropriate as stated in the [comment](https://github.com/go-gitea/gitea/pull/23168#issuecomment-1445562284) 
Use await instead

Close #22075.
Close #23247.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
This change doesn't look stable. The 'click' event is a DOM native event, its handler function should follow the standard strictly, instead of adding  more customized arguments.

The code for `on('click', 'button.comment-form-reply')` could be extracted to a common async function, then make these two `click` event handler to await call that function to wait for EasyMDE ready.

**Comment by HesterG** [comment]
> This change doesn't look stable. The 'click' event is a DOM native event, its handler function should follow the standard strictly, instead of adding more customized arguments.
> 
> The code for `on('click', 'button.comment-form-reply')` could be extracted to a common async function, then make these two `click` event handler to await call that function to wait for EasyMDE ready.

Extraced the function and used await, please review again.

File: web_src/js/features/repo-issue.js [hunk 1]
```diff
@@ -418,6 +418,22 @@ function assignMenuAttributes(menu) {
   return id;
 }
 
+export async function handleReply(_this) {
+  hideElem(_this);
+  const form = _this.closest('.comment-code-cloud').find('.comment-form');
```
Comment (wxiaoguang) [inline web_src/js/features/repo-issue.js]: If `_this` is a jQuery object, its name could be `$el`? Or a clearer name?

File: web_src/js/features/repo-legacy.js [hunk 2]
```diff
@@ -607,15 +607,14 @@ function initRepoIssueCommentEdit() {
   $(document).on('click', '.edit-content', onEditContent);
 
   // Quote reply
-  $(document).on('click', '.quote-reply', function (event) {
+  $(document).on('click', '.quote-reply', async function (event) {
```
Comment (wxiaoguang) [inline web_src/js/features/repo-legacy.js:616]: If you really need this `async`, the `event.preventDefault()` should be put before any await, it's better to move it to the beginning of the function.

https://docs.gitea.io/en-us/guidelines-frontend/#async-functions

> It’s not recommended to use async event listeners, which may lead to problems. The reason is that the code after await is executed outside the event dispatch. Reference: https://github.com/github/eslint-plugin-github/blob/main/docs/rules/async-preventdefault.md

**Comment by HesterG** [comment]
Found an error say "easyMDEOptions.onChange is not a function" after merging #23173 . Not sure if this is a normal behavior, added an empty onchange function to fix this for now.

**Comment by wxiaoguang** [comment]
Sorry, maybe it's my mistake from #23135


The `easyMDEOptions?.onChange(...args);` is incorrect, it should check whether `onChange` exists ....


Could you help to do a fix for that together? Thank you very much.

**Comment by HesterG** [comment]
> Sorry, it's my mistake from #23135
> 
> The `easyMDEOptions?.onChange(...args);` is incorrect, it should check whether `onChange` exists ....
> 
> Could you help to do a fix for that together? Thank you very much.

Added a commit for this.

**Comment by wxiaoguang** [comment]
Hmm, however, I haven't understood how the error occurs. It seems one question mark is enough.

Do you have any idea?

image

image

**Comment by wxiaoguang** [comment]
OK .... I messed something on my side. I must not have woken up ..... you are right.

**Review by lunny — APPROVED** [review]

**Review by wolfogre — APPROVED** [review]

File: web_src/js/features/repo-issue.js [hunk 3]
```diff
@@ -418,6 +418,22 @@ function assignMenuAttributes(menu) {
   return id;
 }
 
+export async function handleReply($el) {
```
Comment (delvh) [inline web_src/js/features/repo-issue.js:421]:
```suggestion
// Done asynchronously as a workaround to easyMDE not being loaded yet
export async function handleReply($el) {
```

File: web_src/js/features/repo-legacy.js [hunk 4]
```diff
@@ -613,15 +613,15 @@ function initRepoIssueCommentEdit() {
...
+    event.preventDefault();
```
Comment (silverwind) [inline web_src/js/features/repo-legacy.js:617]: This `preventDefault` is still ineffective I think, see https://github.com/github/eslint-plugin-github/blob/main/docs/rules/async-preventdefault.md for an explanation. I think we should move the rest of the function body into an async IIFE or standalone async function so that `preventDefault` is executed synchronously.

Comment (wxiaoguang) [reply web_src/js/features/repo-legacy.js:617]: It is effective, because there is no `await`.

You can try it by yourself https://jsfiddle.net/te9o27rg/2/

And IIRC I have explained this problem in an old issue and in the frontend guideline before.

Comment (wxiaoguang) [reply web_src/js/features/repo-legacy.js:617]: See this one (I cleaned the document, removed some details because I thought everyone should already know this problem)

* #17386
* #17448
* #17597

https://github.com/wxiaoguang/gitea/blob/7de594d3544addfc4ea5e83a72ecd759943dff35/docs/content/doc/developers/guidelines-frontend.md


```js
async function foo() {
    func1();
    await bar();
    func2();
}
// equals to
function foo() {
    func1();
    return Promise.resolve(bar).then(() => {
         func2();
    });
}
```

Comment (silverwind) [reply web_src/js/features/repo-legacy.js:617]: Ok interesting that this works but I guess this is a common enough source of error so I guess browser vendors have made it work.

Comment (silverwind) [reply web_src/js/features/repo-legacy.js:617]: According to https://stackoverflow.com/a/37146788/808699 it is fine to call before the first `await`.

Comment (wxiaoguang) [reply web_src/js/features/repo-legacy.js:617]: No, it's not "browser vendors have made it work.", that's just how JS works.

You can always rewrite the `async` function to a `Promise` style, no `async` no `await`, then everything is clear.

Comment (wxiaoguang) [reply web_src/js/features/repo-legacy.js:617]: > According to https://stackoverflow.com/a/37146788/808699 it is fine to call before the first `await`.

I guess my issue&PR&document are far more detailed than that SO answer ..... when I was doing the refactoring at that time, I have requested reviewing from you many times ......

Comment (silverwind) [reply web_src/js/features/repo-legacy.js:617]: That function equality above is incorrect. Nothing executes synchronously inside an async function. See [this](https://gist.github.com/joeytwiddle/ff0a9cf92be0366b274e4283a8b5a935) for a better example.

Comment (wxiaoguang) [reply web_src/js/features/repo-legacy.js:617]: There is a comment: https://gist.github.com/joeytwiddle/ff0a9cf92be0366b274e4283a8b5a935?permalink_comment_id=4128782#gistcomment-4128782

> This is not exactly the truth. An async function will be executed in sync until it is converted into a Promise by reaching a return or throw statement or the execution is suspendend when a await is reached.

It just matches my example. (I didn't put error/exception in it to keep it simple).

----

OK, I didn't put another promise on `func2` and exceptions, that might be not accurate. I just want to say that `func1` is `sync`.

Comment (silverwind) [reply web_src/js/features/repo-legacy.js:617]: [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) also has a word on this:

> The body of an async function can be thought of as being split by zero or more await expressions. Top-level code, up to and including the first await expression (if there is one), is run synchronously. In this way, an async function without an await expression will run synchronously. If there is an await expression inside the function body, however, the async function will always complete asynchronously. 

The last sentence contradicts the first two, but I guess the statement is correct excluding the last sentence.

Comment (wxiaoguang) [reply web_src/js/features/repo-legacy.js:617]: I think the last sentence's meaning is also correct.

Sentence 1: `zero or more await expressions`: every `await` handles a Promise block

Sentence 2: `up to and including the first await expression .. synchronously`: that's also correct, think about an example:

```js
function () {
    data = {}
    await fetch(url, data)
}
```

The `fetch` itself is executed synchronously and returns a Promise, `await` handles a the `fetch` returned Promise


Sentence 3: `an async function without an await expression will run synchronously`: that's simply true.

Sentence 4:  `If there is an await expression ..  always complete asynchronously`:  that's also true, because after the first `await` expression, the following code is already in Promise blocks. Think  about the example above, although `fetch` (the expression) itself is executed synchronously, but after `fetch`, there is still `await`, the `await` handles the Promise asynchronously, so the function completes asynchronously.

MDN is right.

Comment (wxiaoguang) [reply web_src/js/features/repo-legacy.js:617]: And think about my `preventDefault` example above, you could even do https://jsfiddle.net/94awkvu7/

```js
$('#btn').on('click', async function(e) {
    await e.preventDefault(); // do not really do so. just to show what is async & await
})
```

Although it is anti-pattern, indeed it could also prevent the default successfully, because `e.preventDefault()` is really executed synchronously.

File: web_src/js/features/repo-issue.js (hunk 3 above)
Comment (wxiaoguang) [reply web_src/js/features/repo-issue.js:421]: That's not a workaround, but by design the EasyMDE is loaded asynchronously

File: web_src/js/features/repo-legacy.js (hunk 4 above)
Comment (silverwind) [reply web_src/js/features/repo-legacy.js:617]: You're right the important part is "complete asynchronously", even if part of it ran synchronously, the function will finish async when there is an await. I'm quite surprised the JS authors gave this so much thought, it's quite brilliant actually.

Comment (jolheiser) [reply web_src/js/features/repo-legacy.js:617]: Were there any other reservations here? Just wanted to ask quick since this is in the merge queue. 🙂

Comment (wxiaoguang) [reply web_src/js/features/repo-legacy.js:617]: IMO this PR has fixed the "quote - reply" bug and this PR also contains another important `onChange` fix, so maybe it could be merged, and then propose new fixes later (if necessary)

Comment (silverwind) [reply web_src/js/features/repo-legacy.js:617]: > Were there any other reservations here? Just wanted to ask quick since this is in the merge queue. 🙂

Not from me, the line is fine.

**Comment by jolheiser** [comment]
🎺 🤖
