### PR TITLE
Make issue suggestion work for new PR page

### LINKED ISSUE #33026: Autocomplete for issue does not work when creating a new pull request.
### Description

Whenever I create a pull request, the autocomplete for the issue to reference does not work. However, if I create a pull request, then edit it works as expected.

### Gitea Version

1.23-rc

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Screenshots are from the demo site.

## Creating Pulll Request
image

## Editing Pull Request
image

### Git Version

2.45.2

### Operating System

rocky-linux 9

### How are you running Gitea?

Docker Compose

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #33026

### CODE REVIEW

File: web_src/js/utils.ts [hunk 1]
```diff
@@ -39,8 +39,9 @@ export function parseIssueHref(href: string): IssuePathInfo {
 
 export function parseIssueNewHref(href: string): IssuePathInfo {
   const path = (href || '').replace(/[#?].*$/, '');
-  const [_, ownerName, repoName, pathType, indexString] = /([^/]+)\/([^/]+)\/(issues|pulls)\/new/.exec(path) || [];
-  return {ownerName, repoName, pathType, indexString};
+  const [_, ownerName, repoName, pathTypeField] = /([^/]+)\/([^/]+)\/(issues\/new|compare\/.+\.\.\.)/.exec(path) || [];
```
Comment (delvh) [inline web_src/js/utils.ts:42]: Why only `...`? Isn't `..` a valid comparison as well?
Also, what happened to `|pulls` and the `indexString`?

Comment (wxiaoguang) [reply web_src/js/utils.ts:42]: * `...` is for merge base, it is used for creating PR
* there is no `pulls/new`
* there is no `indexString`

**Review by lunny — APPROVED** [review]

**Review by Zettat123 — APPROVED** [review]
