### PR TITLE
Fix blank dir message when uploading files from web editor

### LINKED ISSUE #7883: Bad default commit message of file upload in root directory
- Gitea version (or commit ref):1.9.1
- Git version: 2.21.0
- Operating system: fedora 30
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/norwin/test/src/branch/master/
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Uploading a file and not entering a commit message results in a commit message like `Uploaded files to '<dir>'`.
When files are uploaded to the root directory, the content inside the quotes is empty.

## Screenshots
image

### PR DESCRIPTION
**Pull request by lunny**
Fix #7883

### CODE REVIEW

File: routers/web/repo/editor.go [hunk 1]
```diff
@@ -685,7 +685,11 @@ func UploadFilePost(ctx *context.Context) {
 
 	message := strings.TrimSpace(form.CommitSummary)
 	if len(message) == 0 {
-		message = ctx.Tr("repo.editor.upload_files_to_dir", form.TreePath)
+		dir := form.TreePath
+		if dir == "" {
+			dir = "/"
+		}
+		message = ctx.Tr("repo.editor.upload_files_to_dir", dir)
```
Comment (delvh) [inline routers/web/repo/editor.go:692]: I still don't think that localizing commit messages is a good idea.
Commits should be written in English and **only** English.
If someone wants to write them in their native language, go for it, but I don't think we should encourage an antipattern by default.
But I know this is offtopic for this PR, so my approval isn't influenced by that.

**Review by delvh — APPROVED** [review]
That 5 line fix took three years to resolve? :eyes:

File: routers/web/repo/editor.go (hunk 1 above)
Comment (lunny) [reply routers/web/repo/editor.go:692]: That could be another PR.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
> That 5 line fix took three years to resolve? 👀

Better late than never 😆
