### PR TITLE
Fix lfs management find

### LINKED ISSUE #15236: LFS file no commits found
- Gitea version (or commit ref): 1.14.0+rc2
- Git version: 2.30.2
- Operating system: using docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (**LFS not supported**)

## Description
Repo settings > LFS > "Find Commits" (of any listed file)

For the same repository:
* in 1.13.2 the commit is found
* in 1.14.0+rc2 no commit is found

URI: {repo}/settings/lfs/find

## Screenshots

1.13.2
image

1.14.0+rc2
image

### PR DESCRIPTION
**Pull request by lunny**
Fix #15236

### CODE REVIEW

File: modules/git/batch_reader.go [hunk 1]
```diff
@@ -269,6 +269,6 @@ func ParseTreeLine(rd *bufio.Reader, modeBuf, fnameBuf, shaBuf []byte) (mode, fn
 		}
 		idx += read
 	}
-	sha = shaBuf
+	sha = to40ByteSHA(shaBuf)
```
Comment (zeripath) [inline modules/git/batch_reader.go]: This will drastically slow down the repository main page.

The comment explains very carefully why this is not done:

```go
// ParseTreeLine reads an entry from a tree in a cat-file --batch stream
// This carefully avoids allocations - except where fnameBuf is too small.
// It is recommended therefore to pass in an fnameBuf large enough to avoid almost all allocations
//
// Each line is composed of:
// <mode-in-ascii-dropping-initial-zeros> SP <fname> NUL <20-byte SHA>
//
// We don't attempt to convert the 20-byte SHA to 40-byte SHA to save a lot of time
```

Don't do this.

**Review by zeripath — APPROVED** [review]

**Review by KN4CK3R — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by zeripath** [comment]
Please send backport
