### PR TITLE
Fix incorrect comment diff hunk parsing, fix github asset ID nil panic

### LINKED ISSUE #35040: Code review comment on pull request line number is wrong
### Description

The line number should start from 1 but not. It's a blank space. 

How to reproduce it?
1 Creating a file with only 1 line and push to one branch
2 Edit the file with deleting this line and add another 4 different lines and creating a pull request
3 Create a code review on the third line

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

https://demo.gitea.com/lunny/test-pr-review/pulls/1

### Screenshots

Image

### How are you running Gitea?

local development env

### LINKED ISSUE #35049: Gitbucket Releases migration - PANIC whilst trying to do migrate task: runtime error: invalid memory address or nil pointer dereference
### Description

When trying to migrate a repository from gitbucket to gitea, it fails on Releases step with `PANIC whilst trying to do migrate task: runtime error: invalid memory address or nil pointer dereference`.

The repo itselfs imports fine, but the problem occurs when trying to import Releases.

Steps to reproduce:
1. Create docker compose the same as the one I included into this report.
2. Create an empty repo on gitbucket.
3. Create a simple test git repo with a single file and a single commit, add a Tag and push it to gitbucket
4. On gitbucket create a release - attach any random .zip file to the release
5. Try to migrate the repo to gitea with all options checked (LFS,Wiki,Releases,Labels etc.....)
6. PANIC whilst trying to do migrate task: runtime error: invalid memory address or nil pointer dereference occurs.

### Gitea Version

1.24.2 built with GNU Make 4.4.1, go1.24.4 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/blazej222/6e24e4a49bcd34811054842556adff03

### Screenshots

_No response_

### Git Version

2.49.0

### Operating System

Windows with Docker

### How are you running Gitea?

Docker image, here's the whole docker compose 
```
services:
  db:
    image: postgres:16
    container_name: gitea-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: xxx
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - gitea-net

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      DB_TYPE: postgres
      DB_HOST: db:5432
      DB_NAME: gitea
      DB_USER: gitea
      DB_PASSWD: xxx
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"  
      - "222:22"   
    networks:
      - gitea-net
    depends_on:
      - db
  gitbucket:
    image: gitbucket/gitbucket:latest
    container_name: gitbucket
    ports:
      - "8080:8080"  
    volumes:
      - ./gitbucket:/gitbucket
    environment:
      - GITBUCKET_HOME=/gitbucket
    restart: unless-stopped
    networks:
      - gitea-net

volumes:
  gitea-db-data:
  gitea-data:

networks:
  gitea-net:
    driver: bridge
```

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by lunny**
* Fix missing the first char when parsing diff hunk header
* Fix #35040
* Fix #35049

----

Introduced in https://github.com/go-gitea/gitea/pull/12047/files#diff-de48c2f70e24ff5603180acf8b5ce9d0356ede8a45bfbf2a485707282ace6d6aR268

Before:

image

After:

image

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Review by silverwind — APPROVED** [review]
If possible, some test coverage for this would be nice.

**Comment by wxiaoguang** [comment]
This one:  Fix git diff hunk 0 based start line #35047 

why not fix together .....

File: modules/git/diff.go [hunk 1]
```diff
@@ -270,6 +275,11 @@ func CutDiffAroundLine(originalDiff io.Reader, line int64, old bool, numbersOfLi
 			oldNumOfLines++
 		}
 	}
+
+	// "git diff" outputs "@@ -1 +1,3 @@" for "OLD" => "A\nB\nC"
+	// FIXME: GIT-DIFF-CUT-BUG But there is a but in CutDiffAroundLine, then the "Patch" stored in the comment model becomes "@@ -1,1 +0,4 @@"
+	// It may generate incorrect results for difference cases, for example: delete 2 line add 1 line, delete 2 line add 2 line etc, need to double check.
```
Comment (wxiaoguang) [inline modules/git/diff.go:281]: @lunny  do you understand the bug now?

Comment (lunny) [reply modules/git/diff.go:281]: As I mentioned in https://github.com/go-gitea/gitea/pull/35047#issue-3221527462 , I believe it should be handled in this function, but I haven’t investigated further in time. I’m also not sure whether `git diff` can generate similar hunks that start with line number 0.

Comment (wxiaoguang) [reply modules/git/diff.go:281]: It is clearly CutDiffAroundLine's bug

Comment (wxiaoguang) [reply modules/git/diff.go:281]: > I’m also not sure whether `git diff` can generate similar hunks that start with line number 0.

If so, then there will be many users reporting the the line numbers are wrong on the "diff page".

But this bug only occurs on the "conversation" page, with "comment.Patch = CutDiffAroundLine..."

Comment (wxiaoguang) [reply modules/git/diff.go:281]: Feel free to revert if it doesn't look good to you and move the code into a separate PR

Comment (lunny) [reply modules/git/diff.go:281]: I’m okay with the changes in this PR to allow backporting. We can address the root cause in a separate PR.
