### PR TITLE
Refactor and fix archive link bug

### LINKED ISSUE #30569: JavaScript promise rejection: Cannot read properties of null (reading 'classList'). Open browser console to see more details.
### Description

when i press "download source code" in releases page, i got "JavaScript promise rejection: Cannot read properties of null (reading 'classList'). Open browser console to see more details." in chrome, and "JavaScript promise rejection: si is null. Open browser console to see more details." in firefox.

https://git.rbtr.ee/root/stress/releases

https://try.gitea.io/koicy/test/releases

### Gitea Version

1.22.0+rc0-81-g4fec3a3d44

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Screenshot 2024-04-18 at 23 11 54

Screenshot 2024-04-18 at 23 11 14

Screenshot 2024-04-18 at 23 12 19

### Git Version

2.40.1

### Operating System

Ubuntu

### How are you running Gitea?

linux-amd64 binary. mysql 5.7.44. Ubuntu 23.10.

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by wxiaoguang**
Regression of #29920
Fixes: https://github.com/go-gitea/gitea/issues/30569

Also this is a rewriting to eliminate the remaining jQuery usages from code.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
I have fully tested related changes:

1. archive link in a dropdown 
2. archive link without a dropdown 
3. network error

**Review by lunny — APPROVED** [review]

File: web_src/js/features/repo-common.js [hunk 1]
```diff
@@ -1,44 +1,42 @@
...
-    const url = this.getAttribute('href');
-    if (!url) return;
-    getArchive($(event.target), url, true);
+  queryElems('.archive-link', (el) => {
+    el.addEventListener('click', (e) => {
+      const target = e.target.closest('.archive-link');
+      if (!target?.href) return;
+      e.preventDefault();
+      downloadArchive(target, target.href);
+    });
```
Comment (silverwind) [inline web_src/js/features/repo-common.js]: Hmm, if we already have a big function body, I think I prefer `for (const el of document.querySelectorAll)`, because of the benefits of being able to `break` and `continue`.

File: web_src/js/features/repo-common.js [hunk 2]
```diff
@@ -1,44 +1,42 @@
...
-async function getArchive($target, url, first) {
-  const dropdownBtn = $target[0].closest('.ui.dropdown.button') ?? $target[0].closest('.ui.dropdown.btn');
-
+async function downloadArchive(target, url, retryCount = 0) {
+  // there are many places using the "archive-link", eg: the dropdown on the repo code page, the release list
+  const targetLoading = target.closest('.ui.dropdown') ?? target;
+  let keepLoading = false;
   try {
-    dropdownBtn.classList.add('is-loading');
+    targetLoading.classList.add('is-loading', 'loading-icon-2px');
```
Comment (silverwind) [inline web_src/js/features/repo-common.js]: Would add the second class to the element itself in templates. It's not necessary to add/remove with the loading state.

File: web_src/js/features/repo-common.js [hunk 3]
```diff
@@ -1,44 +1,42 @@
...
-    event.preventDefault();
-    const url = this.getAttribute('href');
-    if (!url) return;
-    getArchive($(event.target), url, true);
+  queryElems('.archive-link', (el) => {
+    el.addEventListener('click', (e) => {
+      const target = e.target.closest('.archive-link');
+      if (!target?.href) return;
+      e.preventDefault();
+      downloadArchive(target, target.href);
```
Comment (silverwind) [inline web_src/js/features/repo-common.js]:
```suggestion
      await downloadArchive(target, target.href);
```

Always await async function, unless there is a specific reason not to await.

Comment (wxiaoguang) [reply web_src/js/features/repo-common.js]: But there is no reason to await.

File: web_src/js/features/repo-common.js (hunk 2 above)
Comment (wxiaoguang) [reply web_src/js/features/repo-common.js]: There are a lot, and I don't see it's worth to do so.

File: web_src/js/features/repo-common.js (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/features/repo-common.js]: 1. I do not think it really needs "break"
2. It could just "return" to ignore current element like "continue"
3. I think it is more readable than a for-loop. If you prefer, feel free to rewrite it to see the difference.

Comment (wxiaoguang) [reply web_src/js/features/repo-common.js]: There are more cases for `queryElems` like this:

```
queryElems('.selector', (el) => el.disabled = true);
```

It would make the jQuery rewriting easier, and fewer bugs.

File: web_src/js/features/repo-common.js (hunk 3 above)
Comment (silverwind) [reply web_src/js/features/repo-common.js]: It's a risk for the future if someone adds code after this line. I would like to make missing await a lint error, it will be possible once we switch to typescript.

File: web_src/js/features/repo-common.js (hunk 1 above)
Comment (wxiaoguang) [inline web_src/js/features/repo-common.js]:
```suggestion
    el.addEventListener('click', async (e) => {
      const target = e.target.closest('.archive-link');
      if (!target?.href) return;
      e.preventDefault();
      await downloadArchive(target, target.href);
    });
```

File: web_src/js/features/repo-common.js (hunk 3 above)
Comment (wxiaoguang) [reply web_src/js/features/repo-common.js]: Done in 0508c20c0ba740b8a9366d7e59aea8d61bf62a57

File: web_src/js/features/repo-common.js (hunk 2 above)
Comment (silverwind) [reply web_src/js/features/repo-common.js]: ok

File: web_src/js/features/repo-common.js (hunk 1 above)
Comment (silverwind) [reply web_src/js/features/repo-common.js]: For single-line stuff, I agree, such function is nice.

Generally thought, I prefer to avoid callback in favor of for loops, reasons being the unavailable flow control statements and there are more problems like [one can not yield from a callback](https://stackoverflow.com/questions/41326217/js-how-to-use-generator-and-yield-in-a-callback).

Comment (wxiaoguang) [reply web_src/js/features/repo-common.js]: I do not see any real problem, it just works like `queryElemChildren` and `queryElemSiblings`

I would strongly prefer to introduce it, to help migrating from jQuery

**Comment by silverwind** [comment]
BTW, what was the regression?

File: web_src/js/features/repo-common.js (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/features/repo-common.js]: > Generally thought, I prefer to avoid callback in favor of for loops, reasons being the unavailable flow control statements and there are more problems like [one can not yield from a callback](https://stackoverflow.com/questions/41326217/js-how-to-use-generator-and-yield-in-a-callback).

The question is: why you need to do so? What's the real use case with `queryElems`? Even if there is a case, it could be simply rewritten to `for (const el of queryElems('.selector'))`, it is still shorter to read.

**Comment by wxiaoguang** [comment]
> BTW, what was the regression?

I have posted the problem in this comment: https://github.com/go-gitea/gitea/pull/30506#issuecomment-2059383368

**Comment by silverwind** [comment]
Ah I see, I wasn't aware of that button on the release page.

File: web_src/js/utils/dom.js [hunk 4]
```diff
@@ -65,10 +65,14 @@ export function queryElemSiblings(el, selector = '*', fn) {
 }
 
 // it works like jQuery.children: only the direct children are selected
-export function queryElemChildren(parent, selector = '*', fn) {
```
Comment (silverwind) [inline web_src/js/utils/dom.js]: Remove on line 63 as well.

Comment (wxiaoguang) [reply web_src/js/utils/dom.js]: No. They are different.

`queryElemChildren` shouldn't have `selector = '*'`, because `el.children` already provides the children.

But, there is no `el.siblings`, so the call to `queryElemSiblings` could omit the "selector", but the call to `queryElemChildren` shouldn't omit the selector (otherwise, just use children)

Comment (wxiaoguang) [reply web_src/js/utils/dom.js]: There are real calls: `hideElem(queryElemSiblings(target));`

File: web_src/js/utils/dom.js [hunk 5]
```diff
@@ -65,10 +65,14 @@ export function queryElemSiblings(el, selector = '*', fn) {
...
+export function queryElemChildren(parent, selector, fn) {
```
Comment (wxiaoguang) [inline web_src/js/utils/dom.js]:
```suggestion
export function queryElemChildren(parent, selector = '*', fn) {
```

File: web_src/js/features/repo-common.js [hunk 6]
```diff
@@ -1,44 +1,42 @@
...
-    event.preventDefault();
-    const url = this.getAttribute('href');
-    if (!url) return;
-    getArchive($(event.target), url, true);
+  queryElems('.archive-link', (el) => {
+    el.addEventListener('click', async (e) => {
+      const target = e.target.closest('.archive-link');
+      if (!target?.href) return;
+      e.preventDefault();
+      await downloadArchive(target, target.href);
```
Comment (delvh) [inline web_src/js/features/repo-common.js]:
```suggestion
      if(!el.href) return;
      e.preventDefault();
      await downloadArchive(el, el.href);
```

**Comment by silverwind** [comment]
Another problem with callback is that you can not serialize the execution with `await` involved:

```js
fn(async () => {
  await fetch();
}); 
```

This will and can only run in parallel. It's another reason why I don't like callbacks in general and avoid them wherever possible.

**Comment by wxiaoguang** [comment]
> This will and can only run in parallel. It's another reason why I don't like callbacks in general and avoid them wherever possible.
> 
> Not a problem with these click handlers, but in other code, it may as well become a problem.

Developers should know what they are writing and doing. For example, there are a lot of "async event listeners" which call "preventDefault" after await in old code, I fixed them one by one, that's why I don't like using async for event listeners, but we are still using them (and more and more)

I do not see any real bad case for using it like this for such code.

File: web_src/js/features/repo-common.js (hunk 6 above)
Comment (wxiaoguang) [reply web_src/js/features/repo-common.js]: I will rewrite all of this code block later.

**Comment by wxiaoguang** [comment]
Fully rewritten

**Review by silverwind — APPROVED** [review]

File: web_src/js/features/repo-common.js [hunk 7]
```diff
@@ -1,45 +1,35 @@
...
+import {sleep} from '../utils.js';
 
-async function getArchive($target, url, first) {
-  const dropdownBtn = $target[0].closest('.ui.dropdown.button') ?? $target[0].closest('.ui.dropdown.btn');
-
+async function onDownloadArchive(e) {
+  e.preventDefault();
+  // there are many places using the "archive-link", eg: the dropdown on the repo code page, the release list
+  const el = e.target.closest('a.archive-link[href]');
+  const targetLoading = el.closest('.ui.dropdown') ?? el;
```
Comment (silverwind) [inline web_src/js/features/repo-common.js:11]:
```suggestion
  const targetLoading = el.closest('.ui.dropdown');
```
From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest):

> The closest() method of the [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element) interface traverses the element and its parents (heading toward the document root) until it finds a node that matches the specified [CSS selector](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors).

File: web_src/js/features/repo-common.js [hunk 8]
```diff
@@ -1,45 +1,35 @@
...
-    dropdownBtn.classList.add('is-loading');
-    const response = await POST(url);
-    if (response.status === 200) {
-      const data = await response.json();
-      if (!data) {
-        // XXX Shouldn't happen?
-        dropdownBtn.classList.remove('is-loading');
-        return;
-      }
+    for (let tryCount = 0; ;tryCount++) {
```
Comment (silverwind) [inline web_src/js/features/repo-common.js:14]:
```suggestion
    let tryCount = 0;
    while (tryCount++) {
```

Seem more readable to me. Minor nit, can ignore.

File: web_src/js/features/repo-common.js (hunk 7 above)
Comment (wxiaoguang) [reply web_src/js/features/repo-common.js:11]: `el.closest('.ui.dropdown')` might return null, that's why there is a regression.

Comment (silverwind) [reply web_src/js/features/repo-common.js:11]: Ok I see the purpose is different than what I thought.

**Review by silverwind — APPROVED** [review]
