### PR TITLE
Calculate label URL on API 

### LINKED ISSUE #8028: API response for label returns empty 'url' field
- Gitea version (or commit ref):  1.10.0+dev-230-g187ae109d
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description
When fetching or creating a label, the url field in the json response is blank: 

https://try.gitea.io/api/v1/repos/bobemoe/test/issues/1/labels
```json
[
  {
    "id": 4150,
    "name": "bug",
    "color": "ee0701",
    "description": "Something is not working",
    "url": ""
  }
]
```

Expected that it will return the API url for editing the label, same as it does for an issue: 

https://try.gitea.io/api/v1/repos/bobemoe/test/issues/1
```json
{
  "id": 5668,
  "url": "https://try.gitea.io/api/v1/repos/bobemoe/test/issues/1",
  "number": 1,
  "user": {
    "id": 16866,
    "login": "bobemoe",
...
```

### PR DESCRIPTION
**Pull request by 6543**
fix #8028

### CODE REVIEW

**Comment by KN4CK3R** [comment]
Could the caches contain more then one element?

File: modules/convert/issue.go [hunk 1]
```diff
@@ -168,20 +174,64 @@ func ToTrackedTimeList(tl models.TrackedTimeList) api.TrackedTimeList {
...
+		_, ok := orgCache[label.OrgID]
+		if !ok {
+			var err error
+			orgCache[label.OrgID], err = models.GetUserByID(label.OrgID)
+			if err != nil {
+				log.Error("cant load org of label [%d]: %v", label.ID, err)
+			}
+		}
+
+		if org := orgCache[label.RepoID]; org != nil {
```
Comment (zeripath) [inline modules/convert/issue.go]:
```suggestion
		if org := orgCache[label.OrgID]; org != nil {
```

File: modules/convert/issue.go [hunk 2]
```diff
@@ -168,20 +174,64 @@ func ToTrackedTimeList(tl models.TrackedTimeList) api.TrackedTimeList {
...
+			if err != nil {
+				log.Error("cant load repo of label [%d]: %v", label.ID, err)
+			}
+		}
+
+		if repo := repoCache[label.RepoID]; repo != nil {
+			result.URL = fmt.Sprintf("%s/labels/%d", repo.APIURL(), label.ID)
+		}
+	}
+	if label.BelongsToOrg() {
```
Comment (zeripath) [inline modules/convert/issue.go]: As far as I remember labels belong either to a repo or to an org shouldn't this be an `} else if ... {` or even just `} else {` ?

File: modules/convert/issue.go (hunk 1 above)
Comment (6543) [reply modules/convert/issue.go]: this damn CP issues :/ already thought to make it generic but then I would have to work with reflections ...

**Comment by zeripath** [comment]
> Could the caches contain more then one element?

Hmm... I don't think they can here.

The labels either belong to the repo or the org. It doesn't appear to make much sense to me that we would provide a cross repo label API.

@6543 is there actually a way that this could happen?

**Comment by 6543** [comment]
Yes the endpoint to get labels of issues can return org & repo labels

**Comment by 6543** [comment]
> Could the caches contain more then one element?

yes this are edge cases but they exist

**Comment by zeripath** [comment]
hmm, let's check these:

* convert/issue.go:21:`func ToAPIIssue(issue *models.Issue) *api.Issue {`
  - L44: `Labels:   ToLabelList(issue.Labels, repoCache, nil),`
  - All of these labels must be within the same repository and same organization
* convert/issue.go:177: `ToLabel(label *models.Label, repoCache map[int64]*models.Repository, orgCache map[int64]*models.User)`
  - Called by `routers/api/v1/org/label.go` 3 times but all must be in the same org.
  - Called by `routers/api/v1/repo/label.go` 3 times but all must be in the same repo.
  - Called by `ToLabelList` - see below.
 * convert/issue.go:224:`ToLabelList`
   - Called by `ToAPIIssue` above. Same Repo/Org
   - Called by `routers/api/v1/org/label.go` ListLabels - all must be in same org.
   - Called by `routers/api/v1/repo/label.go` ListLabels - all must be in the same repo.
   - Called by `routers/api/v1/repo/issue_label.go` 3 times but all must be in the same repo or org.

@6543 where were you thinking this was called where it could be cross-repo or cross-org?

File: modules/convert/issue.go [hunk 3]
```diff
@@ -168,20 +174,63 @@ func ToTrackedTimeList(tl models.TrackedTimeList) api.TrackedTimeList {
...
 		Color:       strings.TrimLeft(label.Color, "#"),
 		Description: label.Description,
 	}
+
+	// calculate URL
+	if label.BelongsToRepo() {
+		if repoCache == nil {
+			repoCache = make(map[int64]*models.Repository)
+		}
+		_, ok := repoCache[label.RepoID]
```
Comment (lunny) [inline modules/convert/issue.go]: `repo, ok:= ` here is better.

**Review by lunny — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

File: modules/convert/issue.go [hunk 4]
```diff
@@ -25,6 +28,9 @@ func ToAPIIssue(issue *models.Issue) *api.Issue {
 	if err := issue.LoadRepo(); err != nil {
 		return &api.Issue{}
 	}
+	if err := issue.Repo.GetOwner(); err != nil {
```
Comment (delvh) [inline modules/convert/issue.go:31]: I think `err := issue.Repo.GetOwner();` is misleading, as this implies that `err` would be the owner.
After what I have seen, this function should most likely be renamed to `LoadOwner`, because that's what it does.
Returning only an error makes much more sense then.
An alternative for naming it would be `InitializeOwner()` but that seems to conflict with the current naming scheme.
When renaming it, its function comment should be changed as well as that is simply incorrect by now.
Could it be that that is a leftover from when the owner was initialized eagerly?
