### PR TITLE
[Backport] [Fix] use default avatar for ghost user (fix 500 error) (#9536)

### LINKED ISSUE #8853: Deleted user's (Ghost) avater image generates error 500
- Gitea version (or commit ref): 1.10-rc2
- Git version: 2.20.1
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL (mariadb)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No (READ DESCRIPTION)
  - [ ] Not relevant
- Log gist:

`
2019/11/06 08:19:24 ...uters/user/avatar.go:29:Avatar() [E] Requested avatar for invalid user: user does not exist [uid: 0, name: Ghost, keyid: 0]
`

## Description

When a user, who created an issue, deletes itself, the issue is re-assigned to "Ghost", who does not have an image.

https://codeberg.org/user/avatar/Ghost/-1 generates error 500

See here:

https://codeberg.org/crimeflare/cloudflare-tor/issues/16

This does not happen on try.gitea.io because someone created a Ghost user there when it was not yet blacklisted. So the avatar is there.

https://try.gitea.io/Ghost

### LINKED ISSUE #9189: template error in issues list when poster_id is -1
- Gitea version (or commit ref):  1.10.0+14-gc01afd584
- Git version: 2.20.1
- Operating system: Debian 10
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

`
template: repo/issue/list:236:26: executing "repo/issue/list" at <.Poster.ID>: nil pointer evaluating *models.User.ID
`

## Description

Deleted owners issues sometimes get poster_id=-1 in issue table, leading to a template error in ./templates/repo/issue/list.tmpl in the issue list

This happened for 5 issues on codeberg.org, in an organization where users create one-time accounts for one single interaction, then delete it (I won't comment on that, not my idea), but that fluctuation seems to make the error much more likely.

I am willing to fix the template IF you tell me that -1 is expected, if it is not then we have to find out why poster_id gets set to -1. Or is it rather a bug that deleted users poster_id do NOT get to -1?

### PR DESCRIPTION
**Pull request by 6543**
backports #9536
* [x] fix #8853 (set default avatar for ghost user (dont make a 500 error))

### CODE REVIEW

**Comment by 6543** [comment]
@techknowlogick / @lunny can you add Milestone 1.10.2 and lables?

**Review by zeripath — APPROVED** [review]

**Comment by zeripath** [comment]
I'm not much of a fan of requerying before saving - however I guess it's the simplest thing to do and we don't want posterID to be -1.

In master we should find the code that sets this and stop that

**Comment by 6543** [comment]
@zeripath I know where it come from: from loadPoster() and only API is afected becouse of the technike wich is used to update issues :(

**Comment by 6543** [comment]
We have three options:
 * first = simplest = in this PR (check if posterID <= 0 then dont change)
 * let the system habdle -1 as ghost user (we need to change some functions)
* change how the api can update issue (for each field or specify the rows somehow)

**Comment by zeripath** [comment]
If it's only loadPoster - fix that. Then make the update method log an error, but keep the sanity saving step in as we don't want to lose data.

**Comment by 6543** [comment]
@zeripath log errer as you suggest - I'll make a smal refactor on main branch wich address -1 id issue

**Comment by 6543** [comment]
@sapk backport need a review

**Comment by 6543** [comment]
@lafriks would be nice if you look at it - thanks

File: models/issue.go [hunk 1]
```diff
@@ -1731,6 +1731,13 @@ func SearchIssueIDsByKeyword(kw string, repoID int64, limit, start int) (int64,
 }
 
 func updateIssue(e Engine, issue *Issue) error {
+	if issue.PosterID <= 0 {
+		log.Error("On issue %d gitea try to set %d as PosterID", issue.ID, issue.PosterID)
```
Comment (zeripath) [inline models/issue.go]: I still think it would have been better to do the log after we tried reloading the posterID.

That way you could have two log messages:

1. Gitea has a bug and is doing a stupid thing trying to update a posterID to -1 but we were able to stop it from doing harm.
2. There's an issue out there with a posterID -1 and so your data is corrupt and you need to fix it.

**Review by zeripath — CHANGES_REQUESTED** [review]

**Review by zeripath — APPROVED** [review]
As it's a backport it's fine though

**Comment by 6543** [comment]
@zeripath #9539 is for upstream

**Comment by zeripath** [comment]
The IsGhost function in that differs quite a lot from this one, for example you're still going to update the posterID to -1 for anything that isn't Ghost in that. Is that still intended?

**Comment by 6543** [comment]
@zeripath can we switch conversation about this to #9539 ...

**Comment by 6543** [comment]
@zeripath INFO: split PR to single backport of (#9536)

because the second part differ to mouch from new PR

**Comment by 6543** [comment]
@lunny this is now a "real" backport of  #9536 - do you have time to approve?

**Review by lunny — APPROVED** [review]

**Comment by 6543** [comment]
Thanks
