### PR TITLE
Fix various trivial problems

### LINKED ISSUE #36600: Incorrect format. A different number of format items is expected while calling the 'fmt.Errorf' function
### Description

```
func DropTableColumns(...) (err error) {
  switch {
  ....
  case setting.Database.Type.IsMSSQL():
    ....
    for _, constraint := range constraints {
      if _, err := sess.Exec(fmt.Sprintf("DROP INDEX `%[2]s` ON `%[1]s`", 
        tableName, constraint)); err != nil {
        return fmt.Errorf("Drop index `%[2]s` on `%[1]s`: %v",                   // <=
          tableName, constraint, err)
      }
    }
    ....
  }
  ....
}
```

In this case, `%[1]s` points to the first argument, `tableName`, and implicitly shifts the argument number for the next placeholder by `1` from the current one—so the second argument, `constraint`, is used instead of the intended `err`.

A strange piece of code was found inside the [db.go](https://github.com/go-gitea/gitea/blob/2876800cb296ed5cf36099d46270ad183dce7026/models/migrations/base/db.go#L462) file on line 462.

### Gitea Version

...

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

...

### Database

None

### LINKED ISSUE #36601: Identical expression 'm[1]' to the left and to the right of compound assignment
### Description

```
func (s *linkifyParser) Parse(....) ast.Node {
  ....
  if m != nil {
    lastChar := line[m[1]-1]
    if lastChar == '.' {
      m[1]--
    } else if lastChar == ')' {
      ....
    } else if lastChar == ';' {
      i := m[1] - 2
        for ; i >= m[0]; i-- {
          if util.IsAlphaNumeric(line[i]) {
            continue
          }
          break
        }
        if i != m[1]-2 {
          if line[i] == '&' {
            m[1] -= m[1] – i               // <=
          }
        }
      }
    }
  ....
}
```
Obviously, subtracting its own value from `m[1]` makes no sense. 
A strange piece of code was found inside the [linkify.go](https://github.com/go-gitea/gitea/blob/2876800cb296ed5cf36099d46270ad183dce7026/modules/markup/common/linkify.go#L108) file on line 108.

### Gitea Version

...

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

...

### Database

None

### LINKED ISSUE #36915: CODEOWNERS: Unable to exclude subfolder from pattern without complex regex
### Feature Description

When configuring CODEOWNERS, there is no clean way to assign owners to all files in a folder except a specific subfolder.

For example, I want to assign @core-team to all files in core/ except files in core/webapi/.

Current Workaround:

Since Gitea uses Go's regexp engine (which doesn't support lookahead (?!...)), the only single-line solution is a complex alternation pattern:

```core/([^w].*|w[^e].*|we[^b].*|web[^a].*|weba[^p].*|webap[^i].*|webapi[^/].*) @core-team```

This is:
- Hard to read
- Hard to maintain
- Error-prone

What I've Tried:

| Approach | Result |
|---|---|
| core/.* @team + !core/webapi/.* | Rules accumulate, webapi still gets @team |
| !core/webapi/.* @team | Assigns @team to all repo files except webapi |
| Negative lookahead (?!...) | Not supported (Go regexp limitation) |
| Explicit subfolder listing | Works, but requires many lines |

### Screenshots

_No response_

### LINKED ISSUE #36919: Internal server error from /repos/{owner}/{repo}/git/trees/{sha} and method GET
### Description

Returns `500` for large enough page query parameter.

Steps to reproduce:

1. create a repository with `/user/repos POST`:
2. create a file in repository with `/repos/{owner}/{repo}/contents/{filepath} POST`:
3. try to get the tree of a repository with `/repos/{owner}/{repo}/git/trees/{sha}?page={x} GET`:
    - request requirements:
        - `{owner}` has to be the name of an existing user
        - `{repo}` has to be the name of an existing repo
        - `{sha}` has to be the hash of an existing commit
        - `{x}` can be any very large positive number, e.g. `1397053990642064600`
    - request:
        ```
        curl -i -X GET -H "Authorization: Bearer access_token" http://localhost:3001/api/v1/repos/admin/test_repo/git/trees/
        51d0de0bba6675cdce68d74bccd61e8f0dc8025e?page=1397053990642064600
        ```
    - response:
        ```
        HTTP/1.1 500 Internal Server Error
        Cache-Control: max-age=0, private, must-revalidate, no-transform
        X-Content-Type-Options: nosniff
        X-Frame-Options: SAMEORIGIN
        Date: Mon, 09 Mar 2026 13:15:46 GMT
        Content-Type: text/plain; charset=utf-8
        Transfer-Encoding: chunked

        PANIC: runtime error: index out of range [-4898558959861323816]
        /usr/local/go/src/runtime/panic.go:860 (0x492c19)
        /go/src/code.gitea.io/gitea/modules/web/routing/logger_manager.go:116 (0x1aacee4)
        /usr/local/go/src/runtime/panic.go:860 (0x492c19)
        /usr/local/go/src/runtime/panic.go:236 (0x456356)
        /usr/local/go/src/runtime/asm_amd64.s:2129 (0x49b367)
        /go/src/code.gitea.io/gitea/services/repository/files/tree.go:99 (0x28c0ed8)
        /go/src/code.gitea.io/gitea/routers/api/v1/repo/tree.go:64 (0x29bf915)
        /usr/local/go/src/reflect/value.go:586 (0x51dc05)
        /usr/local/go/src/reflect/value.go:369 (0x51cab8)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:161 (0x1ab62f6)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:168 (0x1ab6365)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:168 (0x1ab6365)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:168 (0x1ab6365)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:168 (0x1ab6365)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:168 (0x1ab6365)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:168 (0x1ab6365)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.5/chain.go:31 (0x1aad7c5)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.5/mux.go:479 (0x1ab0a6e)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:168 (0x1ab6365)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:168 (0x1ab6365)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:168 (0x1ab6365)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/services/context/api.go:238 (0x2a04547)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:125 (0x1ab67b5)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/routers/api/v1/api.go:1756 (0x2a04256)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:125 (0x1ab67b5)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.5/mux.go:73 (0x1aae382)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.5/mux.go:321 (0x1aafcda)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.5/mux.go:479 (0x1ab0a6e)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/routers/common/maintenancemode.go:40 (0x2c80822)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:125 (0x1ab67b5)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/routing/logger_manager.go:122 (0x1aacd8c)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:125 (0x1ab67b5)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/pkg/mod/github.com/chi-middleware/proxy@v1.1.1/middleware.go:37 (0x2959f2f)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:125 (0x1ab67b5)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/routers/common/middleware.go:84 (0x295c5d6)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:125 (0x1ab67b5)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/routers/common/middleware.go:99 (0x295c20f)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/src/code.gitea.io/gitea/modules/web/handler.go:125 (0x1ab67b5)
        /usr/local/go/src/net/http/server.go:2286 (0x9c8328)
        /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.5/mux.go:90 (0x1aae341)
        /go/src/code.gitea.io/gitea/modules/web/router.go:243 (0x1ab83e2)
        /go/src/code.gitea.io/gitea/modules/web/router.go:181 (0x1ab7e46)
        /usr/local/go/src/net/http/server.go:3311 (0x9e8a0d)
        /usr/local/go/src/net/http/server.go:2073 (0x9c640f)
        /usr/local/go/src/runtime/asm_amd64.s:1771 (0x49af00)
        ```

### Gitea Version

1.26.0+dev-510-g08254cf126

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Using the official Docker image.

### Database

SQLite

### PR DESCRIPTION
**Pull request by wxiaoguang**
* Fix #36915
* Fix #36919
* Close #36600
* Close #36601
* Fix incorrect oauth2 error message display

### CODE REVIEW

File: services/issue/pull.go [hunk 1]
```diff
@@ -95,7 +95,9 @@ func PullRequestCodeOwnersReview(ctx context.Context, pr *issues_model.PullReque
 	uniqTeams := make(map[string]*org_model.Team)
 	for _, rule := range rules {
 		for _, f := range changedFiles {
-			if (rule.Rule.MatchString(f) && !rule.Negative) || (!rule.Rule.MatchString(f) && rule.Negative) {
+			shouldMatch := !rule.Negative
+			matched, _ := rule.Rule.MatchString(f)
```
Comment (bircni) [inline services/issue/pull.go]: Is it wanted to ignore the error silently? - Maybe a comment would be useful?

Comment (wxiaoguang) [reply services/issue/pull.go]: Yes, error only occurs when "timeout", it should also be treated as false

The regexp itself has been successfully complied ahead, any error should have been reported when compiling.

Comment (bircni) [reply services/issue/pull.go]: you are right - forgot about that

Comment (bircni) [reply services/issue/pull.go]: resolved! thanks for the comment :-)

**Review by lunny — APPROVED** [review]

**Review by Zettat123 — APPROVED** [review]
