### PR TITLE
Fix label count

### LINKED ISSUE #8224: Wrong count of issues in labels
Gitea ver: gitea.com

Labels page showing sometime wrong open issues count.

label

Ref #8190

### PR DESCRIPTION
**Pull request by lunny**
should fix #8224

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Review by appleboy — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

File: models/issue_label.go [hunk 1]
```diff
@@ -294,7 +295,20 @@ func GetLabelsByIssueID(issueID int64) ([]*Label, error) {
...
+		).
+		SetExpr("num_closed_issues",
+			builder.Select("count(*)").From("issue_label").
+				InnerJoin("issue", "issue_label.issue_id = issue.id").
+				Where(builder.Eq{
+					"issue_label.label_id": l.ID,
+					"issue.is_closed":      true,
+				}),
+		).
+		AllCols().Update(l)
```
Comment (lafriks) [inline models/issue_label.go:311]: ~~Cols("num_issues", "num_closed_issues").Update(l)~~
Nevermind :D

**Review by lafriks — CHANGES_REQUESTED** [review]
mssql now failing with boolean being used as `false` not 0 in it. Could be bug in updated xorm?

**Comment by lunny** [comment]
@lafriks will check that.

**Review by lafriks — APPROVED** [review]
