### PR TITLE
Fix attachments list in edit comment

### LINKED ISSUE #12573: Multiple review textarea after comment code
- Gitea version (or commit ref): 12.3 +
- Git version: 
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Adding or editing a code comment causes multiple textarea fields to appear in the review button popover.

## Screenshots
image

### LINKED ISSUE #12583: While replying to an issue, changes to attachments are applied only if body is also changed
- Gitea version (or commit ref): try.gitea.io
- Git version: (irrelevent)
- Operating system: (Fedora Rawhide 33)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL (MariaDB)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/CL-Jeremy/Test/issues/1)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

As the title suggests, the OP of an issue is not affected. Only replies have to at least have a body for changes to attachments to be applied. Note that the initial upload succeeds without a body. You just cannot change it without changing the body.

See https://try.gitea.io/CL-Jeremy/Test/issues/1#issuecomment-31206, this also happens when there is already some content in body:
> 1

Newly uploaded files will not be reflected after refreshing until the body is modified (cf. https://try.gitea.io/CL-Jeremy/Test/issues/1#issuecomment-31207):
> 1
> 2

## Screenshots

cf. https://try.gitea.io/CL-Jeremy/Test/issues/1 (attachments)

### PR DESCRIPTION
**Pull request by zeripath**
#11141 broke the appearance of dropzone attachments when editting
comments causing poorly updating lists.

This PR fixes this.

Fix #12583

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
could be backported to 1.12

**Comment by zeripath** [comment]
Unfortunately I don't think this is a fix for #12573 but rather is a fix for #12583.

I'm still struggling to completely replicate #12573

File: modules/upload/upload.go [hunk 1]
```diff
@@ -75,18 +75,28 @@ func AddUploadContext(ctx *context.Context, uploadType string) {
...
 		ctx.Data["UploadMaxFiles"] = setting.Attachment.MaxFiles
 		ctx.Data["UploadMaxSize"] = setting.Attachment.MaxSize
 	} else if uploadType == "comment" {
 		ctx.Data["UploadUrl"] = ctx.Repo.RepoLink + "/issues/attachments"
 		ctx.Data["UploadRemoveUrl"] = ctx.Repo.RepoLink + "/issues/attachments/remove"
+		ctx.Data["UploadLinkUrl"] = ctx.Repo.RepoLink + "/issues/attachments"
+		ctx.Data["UploadAccepts"] = strings.Replace(setting.Attachment.AllowedTypes, "|", ",", -1)
+		ctx.Data["UploadMaxFiles"] = setting.Attachment.MaxFiles
+		ctx.Data["UploadMaxSize"] = setting.Attachment.MaxSize
+	} else if uploadType == "editcomment" {
```
Comment (silverwind) [inline modules/upload/upload.go]: does it really need a new uploadType? Why not add a optional boolean argument `isEdit` or something?

File: web_src/js/index.js [hunk 2]
```diff
@@ -996,17 +996,21 @@ async function initRepository() {
...
-            if (!$content.find('.ui.small.images').length) {
+            if (!$content.find('.dropzone-attachments').length) {
               if (data.attachments !== '') {
                 $content.append(
-                  '<div class="ui bottom attached segment"><div class="ui small images"></div></div>'
+                  `<div class="dropzone-attachments">
+                  <div class="ui clearing divider"></div>
+                  <div class="ui middle aligned padded grid">
+                  </div>
+                </div>`
```
Comment (silverwind) [inline web_src/js/index.js]: Intend like this:

```js
$content.append(`
  <div class="dropzone-attachments">
    <div class="ui clearing divider"></div>
    <div class="ui middle aligned padded grid"></div>
  </div>
`);

File: modules/upload/upload.go (hunk 1 above)
Comment (zeripath) [reply modules/upload/upload.go]: yes

* ctx.Params(":index") will not be present otherwise. 
* isEdit makes no sense for any of the other `"uploadtype"` they don't have edits.
* `"uploadtype"` is just an argument to this function - it's not set anywhere.

File: web_src/js/index.js (hunk 2 above)
Comment (zeripath) [reply web_src/js/index.js]: That's just going to insert lots of empty new lines.

What's the benefit?

File: modules/upload/upload.go (hunk 1 above)
Comment (zeripath) [reply modules/upload/upload.go]: When or if we require isEdit to have a different effect for release and repo then we can refactor this.

In the meantime it's genuinely a different type of upload.

Comment (silverwind) [reply modules/upload/upload.go]: Releases can certainly edit, but I think it's been broken or never been implemented (https://github.com/go-gitea/gitea/issues/12963).

Comment (silverwind) [reply modules/upload/upload.go]: How about still adding that boolean (as a static argument) and a `if` around setting of `UploadLinkUrl`? I prefer to avoid duplicating the whole `if` body.

Comment (zeripath) [reply modules/upload/upload.go]: I don't see how this is an improvement but fine.

Comment (silverwind) [reply modules/upload/upload.go]: It prevents unneccary overloading of the `uploadType` variable with two characteristics (its type and if it's an create/edit). I think it's easier to extend later on if we have one variable per characteristic because your concept will be hard to extend once we add a more such characteristics later on, or do you want to end up with strings like `edit-comment-issue-has-image` 😉?

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
It makes sittuation better!

but now I get this relicts after editing (no page reload):
Screenshot at 2020-10-10 23-33-20
:point_up: edit add second image

after a page reload all looks fine

**Comment by zeripath** [comment]
@6543 That's odd... are you sure your javascript is up to date?

**Comment by 6543** [comment]
I'll retest with a different browser ... lets look how this playes

**Comment by 6543** [comment]
Yes

**Comment by zeripath** [comment]
What does yes mean?

**Comment by 6543** [comment]
I have tested the this patch on a fresh browser so there should be no old java in the cache ...

**Comment by zeripath** [comment]
Check the DOM and tell me where those nodes are and what they are contained in.

**Comment by zeripath** [comment]
I've managed to reproduce ... give me a few mins.

**Comment by zeripath** [comment]
Now there's one other weird thing this PR doesn't sort which handling what happens when you remove an attachment from an empty comment...

**Comment by zeripath** [comment]
OK @6543 ready again.

**Comment by 6543** [comment]
wow - thanks!!

**Review by 6543 — APPROVED** [review]
:tada:

**Comment by zeripath** [comment]
Unfortunately backporting this is much more involved than it would at first seem. It might take a while to do.
