### PR TITLE
Fix bug when pushing mirror with wiki

### LINKED ISSUE #36736: Pushmirror from gitea to gitea throws error
### Description

If you have two repos on gitea and configure one (http://localhost:3000/org/source-repo.git) to have a push mirror on the other (http://localhost:3000/org/dest-repo.git) the first sync will success but the update may be fail:

```
PushRejected Error: remote: 
remote: error:        
remote: error: branch mirror-head is the default branch and cannot be deleted        
remote: error:        
To http://localhost:3000/org/dest-repo.wiki.git
 ! [remote rejected]   mirror-head (pre-receive hook declined)
 ! [remote rejected]   main -> main (pre-receive hook declined)
error: failed to push some refs to 'http://localhost:3000/org/dest-repo.wiki.git'
 - remote: 
remote: error:        
remote: error: branch mirror-head is the default branch and cannot be deleted        
remote: error:        
To http://localhost:3000/org/dest-repo.wiki.git
 ! [remote rejected]   mirror-head (pre-receive hook declined)
 ! [remote rejected]   main -> main (pre-receive hook declined)
error: failed to push some refs to 'http://localhost:3000/org/dest-repo.wiki.git'
: remote: 
remote: error:        
remote: error: branch mirror-head is the default branch and cannot be deleted        
remote: error:        
To http://localhost:3000/org/dest-repo.wiki.git
 ! [remote rejected]   mirror-head (pre-receive hook declined)
 ! [remote rejected]   main -> main (pre-receive hook declined)
error: failed to push some refs to 'http://localhost:3000/org/dest-repo.wiki.git'
```

Seems that has something todo with the wiki. There is an existing wiki in the dest-repo but actually the wiki is a gitea specific separate repo, right?

### Gitea Version

1.25.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Self hosted docker

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by lunny**
Fix #36736 

---
Generated by a coding agent with Codex 5.2

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

File: routers/private/hook_pre_receive.go [hunk 1]
```diff
@@ -151,7 +151,11 @@ func preReceiveBranch(ctx *preReceiveContext, oldCommitID, newCommitID string, r
 	gitRepo := ctx.Repo.GitRepo
 	objectFormat := ctx.Repo.GetObjectFormat()
 
-	if branchName == repo.DefaultBranch && newCommitID == objectFormat.EmptyObjectID().String() {
+	defaultBranch := repo.DefaultBranch
+	if ctx.opts != nil && ctx.opts.IsWiki && repo.DefaultWikiBranch != "" {
```
Comment (wxiaoguang) [inline routers/private/hook_pre_receive.go]: Why you expect it can be `nil`?

Comment (lunny) [reply routers/private/hook_pre_receive.go]: 828d78f

**Review by wxiaoguang — APPROVED** [review]
