### PR TITLE
Move serv hook functionality & drop GitLogger

### LINKED ISSUE #5478: LFS pull fails on public SSH-cloned repo
- Gitea version (or commit ref): f17524b
- Git version: 2.17.1
- Operating system: official docker image
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

The problem is that one can't even clone a repo with LFS over SSH if the repo isn't private.
'GIT_TRACE=1 GIT_CURL_VERBOSE=1 git lfs pull'
fails with
'trace git-lfs: api error: Authentication required: Authorization error: https://example.com/gitea/user/repo.git/info/lfs/objects/batch', which is indeed 'HTTP/1.1 401 Unauthorized'.

It is the case because this fragment
```
		userID, ok := claims["user"].(float64)
		if !ok {
			return nil, r, opStr, fmt.Errorf("Token user id invalid")
		}
```
in modules/lfs/server.go (parseToken) gives an error.

From the other side command
'ssh -- git@example.com git-lfs-authenticate user/repo.git download'
returns auth token without 'user' field because this condition
```
if requestedMode == models.AccessModeWrite || repo.IsPrivate || setting.Service.RequireSignInView
```
in cmd/serv.go (runServ) is false. It is even false if one has 'REQUIRE_SIGNIN_VIEW = true' in his config, because noone initializes setting.Service.RequireSignInView (setting.newService() doesn't get called I guess).
Changing repo type to private solves the problem, but here is the bug anyway.
I also think that initalizing RequireSignInView should be performed, but this is not a proper solution to the issue, since HTTPS cloning of public repo works fine with the same settings.

### LINKED ISSUE #7019: When pushing only the first branch/tag gets PR/Release marked
- Gitea version (or commit ref): 1.8.1
- Git version: 2.11.0
- Operating system: Debian 9 stretch
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/djgreg13/bugtag
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
If i push a commit in master and a tag with --all options, the front is desynchronised with my repo.
https://try.gitea.io/djgreg13/bugtag is the example, i push master and tag with --all

If i clone the repo, i see the tag, but on front no tags is shown in Releases page

If i push only a new tag, an automatic entry will be created on Releases page

I except to see in this page tag 1.0.0 (pushed with --all) and tag 1.0.1 (pushed with --tags) or i see only 1.0.1

## Screenshots
you can see on https://try.gitea.io/djgreg13/bugtag

### PR DESCRIPTION
**Pull request by zeripath**
This PR moves most of the functionality of serv and hook into private routers. This reduces the number of http calls performed by these actions and allows for better logging of these actions.

In doing so it is now possible to remove the GitLogger. The only place where there is a possible reduction in functionality is in the handling of failures in enable-pprof but these are likely to be rare and not sufficient reason to keep this around.

* Should fix #5478 
* Fixes issue whereby SSH can push to archived repositories
* Fixes #7019 

(Fixes for LFS locks on SSH were broken out as #6999 and have been merged into master.)
(Improvements to git_test were broken out as #7086  and have been merged into master.)

### CODE REVIEW

File: modules/private/key.go [hunk 1]
```diff
@@ -1,131 +1,19 @@
-// Copyright 2018 The Gitea Authors. All rights reserved.
+// Copyright 2019 The Gitea Authors. All rights reserved.
```
Comment (lunny) [inline modules/private/key.go]: This should not be changed. It will always put the year the file created.

File: routers/private/hook.go [hunk 2]
```diff
@@ -0,0 +1,196 @@
...
+import (
+	"fmt"
+	"net/http"
+	"strings"
+
+	"code.gitea.io/gitea/models"
+	"code.gitea.io/gitea/modules/git"
+	"code.gitea.io/gitea/modules/log"
+	"code.gitea.io/gitea/modules/util"
+	macaron "gopkg.in/macaron.v1"
```
Comment (lunny) [inline routers/private/hook.go:20]: blank line

File: routers/private/hook.go [hunk 3]
```diff
@@ -0,0 +1,196 @@
...
+			})
+			return
+		}
+		repo.OwnerName = ownerName
+
+		pullRequestAllowed := repo.AllowsPulls()
+		if !pullRequestAllowed {
+			ctx.JSON(http.StatusOK, map[string]interface{}{
+				"message": false,
+			})
```
Comment (lunny) [inline routers/private/hook.go:152]: return

File: routers/private/hook.go [hunk 4]
```diff
@@ -0,0 +1,196 @@
...
+				})
+				return
+			}
+			baseRepo = repo.BaseRepo
+		}
+
+		if !repo.IsFork && branch == baseRepo.DefaultBranch {
+			ctx.JSON(http.StatusOK, map[string]interface{}{
+				"message": false,
+			})
```
Comment (lunny) [inline routers/private/hook.go:171]: return

File: routers/private/serv.go [hunk 5]
```diff
@@ -0,0 +1,285 @@
...
+import (
+	"fmt"
+	"net/http"
+	"strings"
+
+	"code.gitea.io/gitea/models"
+	"code.gitea.io/gitea/modules/log"
+	"code.gitea.io/gitea/modules/private"
+	"code.gitea.io/gitea/modules/setting"
+	macaron "gopkg.in/macaron.v1"
```
Comment (lunny) [inline routers/private/serv.go:18]: blank line.

**Review by lunny — CHANGES_REQUESTED** [review]

**Comment by lunny** [comment]
The change is so big and I think we need `SSH` tests.

File: modules/private/key.go (hunk 1 above)
Comment (zeripath) [reply modules/private/key.go]:
```suggestion
// Copyright 2018 The Gitea Authors. All rights reserved.
```

File: routers/private/hook.go (hunk 2 above)
Comment (zeripath) [reply routers/private/hook.go:20]:
```suggestion

	macaron "gopkg.in/macaron.v1"
```

File: routers/private/hook.go (hunk 3 above)
Comment (zeripath) [reply routers/private/hook.go:152]:
```suggestion
			})
			return
```

File: routers/private/hook.go (hunk 4 above)
Comment (zeripath) [reply routers/private/hook.go:171]:
```suggestion
			})
			return
```

File: routers/private/serv.go (hunk 5 above)
Comment (zeripath) [reply routers/private/serv.go:18]:
```suggestion

	macaron "gopkg.in/macaron.v1"
```

**Comment by zeripath** [comment]
We already do have some basic SSH tests: `integrations/git_test.go` which do call the hooks

I could extend these to test protected branches.

**Comment by zeripath** [comment]
This also fixes a bug whereby on SSH you can push to archived repositories.

**Comment by zeripath** [comment]
This PR includes #6999

**Comment by zeripath** [comment]
@lunny have greatly improved the git_test

File: modules/lfs/locks.go [hunk 6]
```diff
@@ -44,7 +45,7 @@ func checkIsValidRequest(ctx *context.Context, post bool) bool {
 	return true
 }
 
-func handleLockListOut(ctx *context.Context, lock *models.LFSLock, err error) {
+func handleLockListOut(ctx *context.Context, repo *models.Repository, lock *models.LFSLock, err error) {
```
Comment (lunny) [inline modules/lfs/locks.go]: Why we need a second repo but not use ctx.Repo.Repository?

**Review by lunny — CHANGES_REQUESTED** [review]

File: modules/lfs/locks.go (hunk 6 above)
Comment (zeripath) [reply modules/lfs/locks.go]: ctx.Repo.Repository is not set.

File: cmd/hook.go [hunk 7]
```diff
@@ -89,37 +86,26 @@ func runHookPreReceive(c *cli.Context) error {
 		newCommitID := string(fields[1])
 		refFullName := string(fields[2])
 
+		output, errErr := git.NewCommand("rev-list", "--max-count=1", oldCommitID, "^"+newCommitID).Run()
```
[the remark this answers is not in the document]
Comment (zeripath) [reply cmd/hook.go]: For some reason that doesn't work.

[the remark this answers is not in the document]
Comment (zeripath) [reply cmd/hook.go]: Ah Git sets a temporary object dir - we'd need to send some environment across and set it ourselves:

https://github.com/git/git/blob/aa25c82427ae70aebf3b8f970f2afd54e9a2a8c6/tmp-objdir.c#L164-L168

[the remark this answers is not in the document]
Comment (zeripath) [reply cmd/hook.go]: OK done.

File: modules/lfs/locks.go (hunk 6 above)
Comment (zeripath) [reply modules/lfs/locks.go]: @lunny - ctx.Repo and ctx.Repo.Repository are only set if you use context.RepoAssignment which is inappropriate for LFS, as LFS has its own way of determining authentication.

File: docs/content/doc/advanced/logging-documentation.en-us.md [hunk 8]
```diff
@@ -180,21 +179,6 @@ which will not be inherited from the `[log]` or relevant
...
 * `PREFIX` will default to `""`
 
-### The Hook and Serv "GitLoggers"
-
-These are less well defined loggers. Essentially these should only be
-used within Gitea's subsystems and cannot be configured at present.
-
-They will write log files in:
-
-* `%(ROOT_PATH)/hooks/pre-receive.log`
```
Comment (lunny) [inline docs/content/doc/advanced/logging-documentation.en-us.md:190]: These three logs are still used when the three process invoked.

Comment (lunny) [inline docs/content/doc/advanced/logging-documentation.en-us.md:190]: These three logs are still used when the three process invoked.

**Review by lunny — CHANGES_REQUESTED** [review]

File: docs/content/doc/advanced/logging-documentation.en-us.md (hunk 8 above)
Comment (zeripath) [reply docs/content/doc/advanced/logging-documentation.en-us.md:190]: They're not - they've been completely removed.

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by gabyx** [comment]
It would be nice if, any reviewer who reviewed this ticket, could draw the attention to #8273.
