### PR TITLE
Fix remove file on initial comment

### LINKED ISSUE #20115: Upload file and click remove file has js error
### Description

Status Code: 400

response message:
```
attachment does not exist [id: 0, uuid: ]
```

### Gitea Version

1.18.0+dev-25-g55a22d113

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots
image

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

try.gitea.io

### Database

_No response_

### PR DESCRIPTION
**Pull request by Gusted**
- Store the file uuid(which is returned by Gitea in the upload file response) onto the file object, so it can be used for the remove feature to specify this file.
- Resolves #20115

### CODE REVIEW

File: web_src/js/features/common-global.js [hunk 1]
```diff
@@ -192,7 +192,8 @@ export function initGlobalDropzone() {
       thumbnailWidth: 480,
       thumbnailHeight: 480,
       init() {
-        this.on('success', (_file, data) => {
+        this.on('success', (file, data) => {
+          file.uuid = data.uuid;
```
Comment (delvh) [inline web_src/js/features/common-global.js:196]: To be more future-proof, we could also do the following:
```suggestion
          file.uuid = data.uuid || file.uuid; // Replace the local UUID with the server one if present
```

**Review by delvh — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]
The `file` is a `File` class. Although it's not good to change its properties, but that was what Dropzone did before, and the related code was already quite hacky. So it's fine to get it fixed by `file.uuid = xxx`.

File: web_src/js/features/common-global.js (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/features/common-global.js:196]: See my comment, no need to read the `file.uuid` again, and even if the `file.uuid` is read, there would be a more strange bug in the future if the `file` has an unrelated `uuid` builtin.

The code was quite dirty already, as a quick fix this PR is very suitable. To make the logic stable and clear, the file uploading related code should be all rewritten.
