### PR TITLE
Fix the error message when the token is incorrect

### LINKED ISSUE #24439: API: Requests to Org with incorrect token return empty array
### Description

I have repos under organization that I am accessing via API.

If I provide the correct token via AuthorizationHeaderToken or AccessToken, and make a call to [/users/{username}/repos] I get list of repos that are not marked private. This is expected behavior and is fine.

But, if I put in an incorrect token in either AutorizationHeaderToken or AccessToken and make the same call, I get an empty array in the body. Instead I am expecting some kind of error message. 

With incorrect username/password combination I get the correct error message with code 401 - Error: Unauthorized :
{
  "message": "user does not exist [uid: 2, name: test, keyid: 0]",
  "url": "https://dev.testsrv.com/api/swagger"
}

With incorrect token, I should expect an unauthorized error.

### Gitea Version

1.19.1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

ubuntu

### How are you running Gitea?

On ubuntu desktop, private installation.

### Database

None

### PR DESCRIPTION
**Pull request by CaiCandong**
we refactored  `userIDFromToken`  for the token parsing part  into a new function `parseToken`. `parseToken` returns the string `token` from request, and a boolean `ok` representing whether the token exists or not. So we can distinguish between token non-existence and token inconsistency in the `verfity` function, thus solving the problem of no proper error message when the token is inconsistent. 
close #24439  
related #22119

### CODE REVIEW

**Review by wxiaoguang — APPROVED** [review]

**Review by wolfogre — APPROVED** [review]

File: services/auth/oauth2.go [hunk 1]
```diff
@@ -59,31 +59,32 @@ func (o *OAuth2) Name() string {
 	return "oauth2"
 }
 
-// userIDFromToken returns the user id corresponding to the OAuth token.
-// It will set 'IsApiToken' to true if the token is an API token and
-// set 'ApiTokenScope' to the scope of the access token
-func (o *OAuth2) userIDFromToken(req *http.Request, store DataStore) int64 {
+// parseToken returns the token from request, and a boolean value
+// representing whether the token exists or not
+func (o *OAuth2) parseToken(req *http.Request) (string, bool) {
```
Comment (lunny) [inline services/auth/oauth2.go]: Looks like it could become a standalone function but not a method of OAuth2?

Comment (CaiCandong) [reply services/auth/oauth2.go]: I think so too, but I don't know where to put this function in the project. It should be a utility function ? Or just remove the receiver ?

Comment (lunny) [reply services/auth/oauth2.go]: later.

Comment (CaiCandong) [reply services/auth/oauth2.go]: I got it !

File: services/auth/shortcut.go [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+// And Shortcut solves this problem by:
+//
+//	NewGroup(
+//	    Shortcut{&OAuth2, &conan.Auth},
+//	    &OAuth2,
+//	    &auth.Basic{},
+//	    &nuget.Auth{},
+//	    &conan.Auth{},
+//	    &chef.Auth{},
+//	)
```
Comment (wxiaoguang) [inline services/auth/shortcut.go]: I didn't get the point why OAuth2 and conan.Auth duplicate

Comment (wolfogre) [reply services/auth/shortcut.go]: In summary, `Shortcut` could return a verified user, but never an error, so we have to check again to handle errors if any.

Some cases:

1. the token is for `conan.Auth.`
   1. `Shortcut[OAuth2]` return an error, `Shortcut[conan.Auth]` return a user, so `Shortcut` return the user, and stop.
2. the token is for `conan.Auth`, but it's wrong
   1. `Shortcut[OAuth2]` return an error, `Shortcut[conan.Auth]` return an error, so `Shortcut` return **nil** and continue.
   2.  `OAuth2` return an error (a nit, it should be `conan.Auth` to return an error, but the result is correct), and stop.
3. the token is for `OAuth2`, but as query string, not in `Authorization` header. And the token is wrong
   1. `Shortcut[OAuth2]` return an error, `Shortcut[conan.Auth]` return nil, so `Shortcut` return **nil** and continue.
   2. `OAuth2` return an error and stop.

Comment (wxiaoguang) [reply services/auth/shortcut.go]: Could it refactor the `Shortcut` to a `AuthGroup`?

* If any method in the group succeeds, use the method
* If any method fails and no matched method, return the first error
* If none of the methods matches, do nothing

Then no need to duplicate the methods.

Comment (wolfogre) [reply services/auth/shortcut.go]: Hmm, LGTM, and I don't think we need to define a new type, maybe just patch this logic to `Group`.

Since I already have @CaiCandong's agreement to modify this PR, I'm going to try this way.

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]

**Comment by wolfogre** [comment]
> I was unable to create a backport for 1.20. @CaiCandong, please send one manually. 🍵
> 
> ```
> go run ./contrib/backport 25701
> ...  // fix git conflicts if any
> go run ./contrib/backport --continue
> ```

@GiteaBot has already done it via #25836.
