### PR TITLE
Fix forked repo has no icon and language stat.

### LINKED ISSUE #10790: Forked repo has no icon and language stat
- Gitea version (or commit ref):1.12.0-dev
- Git version:2.11
- Operating system:Debian9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) Click into a forked repo and you can see.
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Forked repo has no icon and language stat.
It can be reproduce easily in [https://try.gitea.io](https://try.gitea.io)

### PR DESCRIPTION
**Pull request by L0veSunshine**
Fix #10790 
I'm not sure if sleep 1.5 seconds is a good method, but this method is simple enough, If the language stat indexer can't analysis code and write the result to database in 1.5 second, After you fresh the page the language stat will display.

### CODE REVIEW

**Comment by L0veSunshine** [comment]
Another solution is copy the older repo's language statistic from data base. But is a little bit troublesome. and re-index can be more accurate.

There is an unsolved issue: the original repo and the forked repo has different size on the information bar.  It has no influence, but is very strange.

File: routers/repo/pull.go [hunk 1]
```diff
@@ -237,7 +237,9 @@ func ForkPost(ctx *context.Context, form auth.CreateRepoForm) {
 		}
 		return
 	}
-
+	
+	time.Sleep(1500*time.Millisecond) //wait language stat indexer finish
```
Comment (lafriks) [inline routers/repo/pull.go]: I don't think it is good idea

**Comment by lafriks** [comment]
It would be better and faster just to copy stats from original repo

File: routers/repo/pull.go (hunk 1 above)
Comment (L0veSunshine) [reply routers/repo/pull.go]: > It would be better and faster just to copy stats from original repo

Thanks your suggestion, I will try another way.
Because i am not familiar with the repo and language stat structure, i use the most easy method.😂
May you give me some tip why the new repo and the original one's size is a little bit different. I worry that directly copy the language stat will cause errors by these difference.

**Comment by L0veSunshine** [comment]
> It would be better and faster just to copy stats from original repo

Thanks your suggestion, I will try another way.
Because i am not familiar with the repo and language stat structure, i use the most easy method.😂
May you give me some tip why the new repo and the original one's size is a little bit different. I worry that directly copy the language stat will cause errors by these difference.

**Comment by lafriks** [comment]
Size could probably be different because git mirror will not copy all refs but that just wild guess

**Comment by L0veSunshine** [comment]
One more question, thank you very much.
I am sorry i am not familiar with xorm framework,the operation in xorm is asynchronous or synchronous?
if the operations in xorm is asynchronous, how can i confirm the copy operation has done. only if the operation had finished the redirect url the language stat will be right.

**Comment by L0veSunshine** [comment]
> Size could probably be different because git mirror will not copy all refs but that just wild guess

One more question, thank you very much.
I am sorry i am not familiar with xorm framework,the operation in xorm is asynchronous or synchronous?
if the operations in xorm is asynchronous, how can i confirm the copy operation has done. only if the operation had finished the redirect url the language stat will be right.

File: routers/repo/pull.go (hunk 1 above)
Comment (L0veSunshine) [reply routers/repo/pull.go]: This sleep function is not only wait indexer but also database operation, it waits all kinds of asynchronous language statistic operation.
Only if we use a synchronous  language statistic operation, the sleep can be removed.

Comment (L0veSunshine) [reply routers/repo/pull.go]: A synchronous language statistic operation means all the language statistic information had written in database. Then execute next statement. When operating database this goroutine(func ForkPost) should be blocked.

**Comment by lafriks** [comment]
xorm operations are synchronous

**Comment by L0veSunshine** [comment]
> xorm operations are synchronous

Thanks, i will have a try.

File: models/repo_language_stats.go [hunk 2]
```diff
@@ -144,3 +144,36 @@ func (repo *Repository) UpdateLanguageStats(commitID string, stats map[string]fl
 
 	return sess.Commit()
 }
+
+func CopyLanguageStat(oldRepo,Repo *Repository) error {
```
Comment (lunny) [inline models/repo_language_stats.go]: maybe `originalRepo` and `dstRepo` is better names.

Comment (L0veSunshine) [reply models/repo_language_stats.go]: Thanks your advice.The new names are more clear. I will use the new names to replace the old.

**Comment by L0veSunshine** [comment]
All the test is passing, it is ready to review.

File: models/repo_language_stats.go [hunk 3]
```diff
@@ -144,3 +144,37 @@ func (repo *Repository) UpdateLanguageStats(commitID string, stats map[string]fl
...
 	return sess.Commit()
 }
+
+// CopyLanguageStat copy originalRepo language stat information to destRepo
+func CopyLanguageStat(originalRepo, destRepo *Repository) error {
+	sess:=x.NewSession()
+	if err := sess.Begin(); err != nil {
+		return err
+	}
+	defer sess.Close()
```
Comment (lunny) [inline models/repo_language_stats.go]: This should be moved to line 151

File: models/repo_language_stats.go [hunk 4]
```diff
@@ -144,3 +144,37 @@ func (repo *Repository) UpdateLanguageStats(commitID string, stats map[string]fl
...
+	originalRepoLang:=make(LanguageStatList, 0, 6)
+	if err := sess.Where("`repo_id` = ?", originalRepo.ID).Desc("`percentage`").Find(&originalRepoLang); err != nil {
+		return err
+	}
+	originalRepoLang.loadAttributes()
```
Comment (lunny) [inline models/repo_language_stats.go]: the returned error should be checked.

File: models/repo_language_stats.go [hunk 5]
```diff
@@ -144,3 +144,37 @@ func (repo *Repository) UpdateLanguageStats(commitID string, stats map[string]fl
...
+			RepoID:destRepo.ID,
+			CommitID:originalRepoLang[r].CommitID,
+			IsPrimary:originalRepoLang[r].IsPrimary,
+			Language:originalRepoLang[r].Language,
+			Percentage:originalRepoLang[r].Percentage,
+			CreatedUnix: timeutil.TimeStampNow(),
+		});err!=nil{
+			return err
+		}
+	}
```
Comment (lunny) [inline models/repo_language_stats.go]: We really should use batch insert.

**Review by lunny — DISMISSED** [review]

File: models/repo_language_stats.go (hunk 3 above)
Comment (L0veSunshine) [reply models/repo_language_stats.go]: Thanks, i will change.

File: models/repo_language_stats.go (hunk 4 above)
Comment (L0veSunshine) [reply models/repo_language_stats.go]: This func has no return value 😅

File: models/repo_language_stats.go (hunk 5 above)
Comment (L0veSunshine) [reply models/repo_language_stats.go]: Thanks, i will improve.

File: models/repo_language_stats.go (hunk 3 above)
Comment (6543) [reply models/repo_language_stats.go]: @L0veSunshine ping

File: modules/repository/fork.go [hunk 6]
```diff
@@ -82,6 +82,8 @@ func ForkRepository(doer, owner *models.User, oldRepo *models.Repository, name,
 	if err = repo.UpdateSize(ctx); err != nil {
 		log.Error("Failed to update size for repository: %v", err)
 	}
-
+	if err:=models.CopyLanguageStat(oldRepo,repo);err!=nil{
```
Comment (6543) [inline modules/repository/fork.go]: pleace execute `make fmt` and commit result

File: models/repo_language_stats.go [hunk 7]
```diff
@@ -144,3 +144,39 @@ func (repo *Repository) UpdateLanguageStats(commitID string, stats map[string]fl
...
+	originalRepoLang := make(LanguageStatList, 0, 6)
+	destRepoLang := make(LanguageStatList, 0, 6)
+	if err := sess.Where("`repo_id` = ?", originalRepo.ID).Desc("`percentage`").Find(&originalRepoLang); err != nil {
+		return err
+	}
+	if len(originalRepoLang) > 0 {
+		originalRepoLang.loadAttributes()
+		for i := range originalRepoLang {
+			destRepoLangItem := new(LanguageStat)
```
Comment (lunny) [inline models/repo_language_stats.go]: It's better to the following form, so that it will be filled once.
```go
var destRepoLangItem = LanguageStat{
...
}
```

Or you can

```go
var destRepoLangItem = *(originalRepoLang[i])
destRepoLangItem.ID = 0
destRepoLangItem.RepoID = destRepo.ID
destRepoLangItem.CreatedUnix = timeutil.TimeStampNow()
```

Comment (L0veSunshine) [reply models/repo_language_stats.go]: Thanks your guidence.

Comment (6543) [reply models/repo_language_stats.go]: Or copy the slice and then itterate throu ut to change parts mentioned lunny mentioned (ID, RepoID, CreatedUnix)
```go
b = make([]T, len(a))
copy(b, a)
```

Comment (L0veSunshine) [reply models/repo_language_stats.go]: I will try. Thank you.

File: models/repo_language_stats.go [hunk 8]
```diff
@@ -144,3 +144,37 @@ func (repo *Repository) UpdateLanguageStats(commitID string, stats map[string]fl
...
+
+// CopyLanguageStat Copy originalRepo language stat information to destRepo (use for forked repo)
+func CopyLanguageStat(originalRepo, destRepo *Repository) error {
+	sess := x.NewSession()
+	defer sess.Close()
+	if err := sess.Begin(); err != nil {
+		return err
+	}
+	originalRepoLang := make(LanguageStatList, 0, 6)
+	destRepoLang := make(LanguageStatList, 0, 6)
```
Comment (6543) [inline models/repo_language_stats.go]:
```suggestion
```

File: models/repo_language_stats.go [hunk 9]
```diff
@@ -144,3 +144,37 @@ func (repo *Repository) UpdateLanguageStats(commitID string, stats map[string]fl
...
+	if err := sess.Where("`repo_id` = ?", originalRepo.ID).Desc("`percentage`").Find(&originalRepoLang); err != nil {
+		return err
+	}
+	if len(originalRepoLang) > 0 {
```
Comment (6543) [inline models/repo_language_stats.go]:
```suggestion
	destRepoLang := make(LanguageStatList, 0, len(originalRepoLang))
	if len(originalRepoLang) > 0 {
```

**Review by 6543 — CHANGES_REQUESTED** [review]

File: models/repo_language_stats.go (hunk 9 above)
Comment (6543) [reply models/repo_language_stats.go]: explanation: xorm can resize the originalRepoLang so create destRepoLang afterwards already right sized

File: models/repo_language_stats.go [hunk 10]
```diff
@@ -144,3 +144,37 @@ func (repo *Repository) UpdateLanguageStats(commitID string, stats map[string]fl
...
+		originalRepoLang.loadAttributes()
+		copy(destRepoLang, originalRepoLang)
+		for i := range originalRepoLang {
+			var destRepoLangItem = *(originalRepoLang[i])
```
Comment (6543) [inline models/repo_language_stats.go]:
```suggestion
```
already done with `copy(destRepoLang, originalRepoLang)`

File: models/repo_language_stats.go [hunk 11]
```diff
@@ -144,3 +144,37 @@ func (repo *Repository) UpdateLanguageStats(commitID string, stats map[string]fl
...
+			destRepoLangItem.ID = 0
```
Comment (6543) [inline models/repo_language_stats.go]:
```suggestion
			originalRepoLang[i].ID = 0
```

File: models/repo_language_stats.go [hunk 12]
```diff
@@ -144,3 +144,37 @@ func (repo *Repository) UpdateLanguageStats(commitID string, stats map[string]fl
...
+			destRepoLangItem.RepoID = destRepo.ID
```
Comment (6543) [inline models/repo_language_stats.go]:
```suggestion
			originalRepoLang[i].RepoID = destRepo.ID
```

File: models/repo_language_stats.go [hunk 13]
```diff
@@ -144,3 +144,37 @@ func (repo *Repository) UpdateLanguageStats(commitID string, stats map[string]fl
...
+			destRepoLangItem.CreatedUnix = timeutil.TimeStampNow()
```
Comment (6543) [inline models/repo_language_stats.go]:
```suggestion
			originalRepoLang[i].CreatedUnix = timeutil.TimeStampNow()
```

File: models/repo_language_stats.go [hunk 14]
```diff
@@ -144,3 +144,37 @@ func (repo *Repository) UpdateLanguageStats(commitID string, stats map[string]fl
...
+			destRepoLang = append(destRepoLang, &destRepoLangItem)
```
Comment (6543) [inline models/repo_language_stats.go]:
```suggestion
```

**Review by 6543 — CHANGES_REQUESTED** [review]

File: models/repo_language_stats.go (hunk 14 above)
Comment (L0veSunshine) [reply models/repo_language_stats.go]: Thanks for reminding.

File: models/repo_language_stats.go [hunk 15]
```diff
@@ -144,3 +144,32 @@ func (repo *Repository) UpdateLanguageStats(commitID string, stats map[string]fl
...
+	if len(RepoLang) > 0 {
+		for i := range RepoLang {
+			RepoLang[i].ID = 0
+			RepoLang[i].RepoID = destRepo.ID
+			RepoLang[i].CreatedUnix = timeutil.TimeStampNow()
+		}
+		if _, err := sess.Insert(&RepoLang); err != nil {
+			return err
+		}
+		//update destRepo's indexer status
```
Comment (6543) [inline models/repo_language_stats.go:165]: can you update the indexer after the loop **once**? since the CommitID should be the same for all RepoLangItems

Comment (6543) [reply models/repo_language_stats.go:165]: beside this LGTM

Comment (L0veSunshine) [reply models/repo_language_stats.go:165]: > can you update the indexer after the loop **once**? since the CommitID should be the same for all RepoLangItems

Thanks. For your advice i think it is unnecessary, the function "updateIndexerStatus"  need to be executed only once--after all the language stat information was written to database. You can view the code above.(like func "UpdateLanguageStats")

Comment (6543) [reply models/repo_language_stats.go:165]: @L0veSunshine looking forward to your commit ;)

Comment (L0veSunshine) [reply models/repo_language_stats.go:165]: > @L0veSunshine looking forward to your commit ;)

I finally understand your means 😂. i had changed.

Comment (L0veSunshine) [reply models/repo_language_stats.go:165]: The commitID is the branch commitID, for every language stat item, commit is the same. Don't need to update sereval times.

Comment (6543) [reply models/repo_language_stats.go:165]: no ... but this is also right

Comment (L0veSunshine) [reply models/repo_language_stats.go:165]: Please tell me how should i do.

Comment (6543) [reply models/repo_language_stats.go:165]: ~~@L0veSunshine -> https://github.com/L0veSunshine/gitea/pull/1~~

~~I created a pull to your branch ...~~

Comment (6543) [reply models/repo_language_stats.go:165]: this code comment is to long to look at the diff nicely ....

**Review by 6543 — APPROVED** [review]
LGTM :sweat_smile:

**Comment by 6543** [comment]
@L0veSunshine thanks for your work

**Comment by L0veSunshine** [comment]
> @L0veSunshine thanks for your work

Thanks for your guidence. I am also very glad to contribute to the gitea project.

File: models/repo_language_stats.go (hunk 15 above)
Comment (6543) [reply models/repo_language_stats.go:165]: @L0veSunshine if you "resolve" this conversation - other mainteiner wont have trublle to look at the diff :)

**Comment by 6543** [comment]
if you resolve the old conversations ... https://github.com/go-gitea/gitea/pull/10791/files#r401787651

**Comment by L0veSunshine** [comment]
> LGTM 😅

Thanks. 

> if you resolve the old conversations ... https://github.com/go-gitea/gitea/pull/10791/files#r401787651

I am sorry i was newer in github😂. i had resolve it.

**Comment by 6543** [comment]
@lunny this need your review

**Review by techknowlogick — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Make lgtm work
