### PR TITLE
Fix plain readme didn't render correctly on repo home page

### LINKED ISSUE #2701: README.txt vs. README.md
Gitea 1.2.0

## Description
A plain text README.txt instead of a README.md file in the repository root directory is rendered as Markdown and displayed on the main repository web site. 
This can lead to a broken layout because multiple white space characters used for indentation or in ASCII art are replaced by single blancs. Also the font family for plain text should be monospace.

It would be nice if Gitea would render a plain text README.txt using a monospace font without any modifications.

### PR DESCRIPTION
**Pull request by lunny**
will fix #2701

### CODE REVIEW

**Comment by lafriks** [comment]
@lunny I don't know why but integration tests fail

**Comment by lunny** [comment]
@lafriks I think I find the problem, sent another commit.

File: routers/repo/view.go [hunk 1]
```diff
@@ -93,6 +93,7 @@ func renderDirectory(ctx *context.Context, treeLink string) {
 		if isTextFile {
 			d, _ := ioutil.ReadAll(dataRc)
 			buf = append(buf, d...)
+			ctx.Data["IsRenderedHTML"] = true
 			newbuf := markup.Render(readmeFile.Name(), buf, treeLink, ctx.Repo.Repository.ComposeMetas())
 			if newbuf != nil {
 				ctx.Data["IsMarkup"] = true
```
Comment (Morlinest) [inline routers/repo/view.go]: `ctx.Data["IsMarkup"]` is not needed anymore?

**Review by Morlinest — CHANGES_REQUESTED** [review]

**Comment by lunny** [comment]
@Morlinest done.

**Comment by lafriks** [comment]
LGTM

**Comment by bkcsoft** [comment]
LGTM
