### PR TITLE
Remove migration support from versions earlier than 1.6.0

### LINKED ISSUE #9953: Deprecate very old migrations
Gitea version: 1.12

I've seen many issues with users being unable to upgrade directly from their very old version into 1.9, 1.10, etc. Our usual response (which solves their problem) is to attempt migrating in smaller steps (e.g. 1.4.x -> 1.5.3, 1.5.x -> 1.6.4, etc.).

Since upgrading from such old versions seems broken, what if (just this time, not as a regular thing) we stop supporting migrating versions prior to (say) 1.6.0, and force users to use older giteas to do the intermediate steps? There's already code for that, but the bar is set at 0.6.0.

https://github.com/go-gitea/gitea/blob/bfdfa9a8b32ae331f98137169693ba1d71c25b09/models/migrations/migrations.go#L30

https://github.com/go-gitea/gitea/blob/bfdfa9a8b32ae331f98137169693ba1d71c25b09/models/migrations/migrations.go#L71-L87

https://github.com/go-gitea/gitea/blob/bfdfa9a8b32ae331f98137169693ba1d71c25b09/models/migrations/migrations.go#L330-L335

### PR DESCRIPTION
**Pull request by guillep2k**
Closes #9953 

This PR removes support for migrations earlier than 1.6.0, as per vote at #9953.

The motivation is that users migrating from versions earlier than that are getting errors due to missing tables and columns. Our usual recommendation (upgrade in steps through intermediate versions) normally works for them.

### CODE REVIEW

**Comment by jolheiser** [comment]
Now that I see this I am having second thoughts. 😅 
If we remove them outright, then users in version lower than `1.6.0` will need to apply the migrations manually without actually knowing _what_ to migrate.

Can we provide the removed migrations in another tool perhaps? It could instead run `Sync2` in between migrations (since I believe that ends up being the root cause of the problem).

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
tested if version nr changes -> stay the same so gite it a go :)

File: models/migrations/migrations.go [hunk 1]
```diff
@@ -849,6 +742,19 @@ func generateOrgRandsAndSalt(x *xorm.Engine) (err error) {
...
+	V16UnitTypeCommits                    // 4 Commits
+	V16UnitTypeReleases                   // 5 Releases
+	V16UnitTypeWiki                       // 6 Wiki
+	V16UnitTypeSettings                   // 7 Settings
+	V16UnitTypeExternalWiki               // 8 ExternalWiki
+	V16UnitTypeExternalTracker            // 9 ExternalTracker
+)
+
 // TAction defines the struct for migrating table action
 type TAction struct {
```
Comment (lafriks) [inline models/migrations/migrations.go]: this type and mostly all other below are then not used anymore. Also as functions below `fixLocaleFileLoadPanic`, `trimCommitActionAppURLPrefix`, `issueToIssueLabel`, `attachmentRefactor`, `renamePullRequestFields`, `cleanUpMigrateRepoInfo`, `generateOrgRandsAndSalt`, `convertDateToUnix`, `ldapUseSSLToSecurityProtocol` and might be also others in this file.

**Review by lafriks — CHANGES_REQUESTED** [review]

**Review by 6543 — CHANGES_REQUESTED** [review]
docs ...

**Comment by 6543** [comment]
@guillep2k I think we should leave a hint on https://docs.gitea.io/en-us/upgrade-from-gogs/#upgrading-to-most-recent-gitea-version and if there are other places witch tell about upgrading update them too

File: models/migrations/migrations.go (hunk 1 above)
Comment (guillep2k) [reply models/migrations/migrations.go]: @lafriks  Done. Removed and checked unused functions with [staticcheck](https://staticcheck.io/docs/). `v16UnitTypeIssues` was still being used by v70.go and `v16UnitTypeCode` by v76.go, so I've moved the const declarations there.

**Comment by guillep2k** [comment]
@6543 done.

**Review by 6543 — APPROVED** [review]
thx

**Review by sapk — APPROVED** [review]

**Review by bagasme — COMMENTED** [review]
Hmm, what about checking version?

**Comment by 6543** [comment]
@bagasme what do you mean, migration already checkes DB version

**Review by lafriks — APPROVED** [review]

**Comment by bagasme** [comment]
@6543 checking Gitea version

**Comment by 6543** [comment]
Not needed

File: docs/content/doc/upgrade/from-gogs.en-us.md [hunk 2]
```diff
@@ -70,9 +70,14 @@ There are some basic steps to follow. On a Linux system run as the Gogs user:
...
-Simply download the file matching the destination platform from the [downloads page](https://dl.gitea.io/gitea)
-and replace the binary.
+After successful migration from `gogs` to `gitea 1.0.x`, it is possible to upgrade `gitea` to a modern version
+in a two steps process.
+
+Upgrade to [`gitea 1.6.4`](https://dl.gitea.io/gitea/1.6.4/) first. Download the file matching
+the destination platform from the [downloads page](https://dl.gitea.io/gitea/1.6.4/) and replace the binary.
+Run Gitea at least once and check that everything works as expected.
+
+Then repeat the procedure, but this time using the [lastest release](https://dl.gitea.io/gitea/).
```
Comment (jolheiser) [inline docs/content/doc/upgrade/from-gogs.en-us.md]: Can you use the `{{< version >}}` variable maybe?  
Or perhaps point them to the FAQ for versions, since we have many questions about the download site in regards to versions and what "latest" means.

**Review by jolheiser — APPROVED** [review]
One doc nit, otherwise LGTM

File: docs/content/doc/upgrade/from-gogs.en-us.md (hunk 2 above)
Comment (guillep2k) [reply docs/content/doc/upgrade/from-gogs.en-us.md]: @jolheiser Done. 😅

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
ready to merge ?

**Comment by 6543** [comment]
ping lgtm

**Comment by lafriks** [comment]
ping it again ;)

**Comment by 6543** [comment]
Who does the merging ?
