### PR TITLE
Move git config/remote to gitrepo package and add global lock to resolve possible conflict when updating repository git config file

### LINKED ISSUE #32018: GetCompareInfo, AddRemote: exit status 128 - error: could not lock config file config: File exists
### Description

When someone is trying to open a pull request on a repo, we're getting a 500 error :

```
Internal Server Error

Une erreur s’est produite:

GetCompareInfo, AddRemote: exit status 128 - error: could not lock config file config: File exists
fatal: could not set 'remote.1725953120549272064.url' to '/var/lib/gitea/data/gitea-repositories/tala/python-docs-fr.git'
 - error: could not lock config file config: File exists
fatal: could not set 'remote.1725953120549272064.url' to '/var/lib/gitea/data/gitea-repositories/tala/python-docs-fr.git'

Version de Gitea: 1.22.2

Si vous pensez qu'il s'agit d'un bug Gitea, veuillez consulter notre board [GitHub](https://github.com/go-gitea/gitea/issues) ou ouvrir un nouveau ticket si nécessaire.
```

On the target repo I see the lock file:

```
root@gitea1:~# ls -lah /var/lib/gitea/data/gitea-repositories/afpy/python-docs-fr.git
total 112K
drwxr-xr-x  8 git git 4.0K Sep 10 05:33 .
drwxr-xr-x 20 git git 4.0K Jul 23  2023 ..
-rw-r--r--  1 git git  134 Jul 26 09:04 FETCH_HEAD
-rw-r--r--  1 git git   21 Nov 17  2022 HEAD
drwxr-xr-x  2 git git 4.0K Nov 17  2022 branches
-rw-r--r--  1 git git  32K Jul 26 09:04 config
-rw-r--r--  1 git git  18K Jul 26 09:04 config.lock
```

Looks like the lock file is a month old.

### Gitea Version

1.22.2

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.30.2

### Operating System

Debian 11.11

### How are you running Gitea?

Self hosted, installed via ansible: https://git.afpy.org/AFPy/infra/src/branch/main/roles/gitea/tasks/setup.yml

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by lunny**
Partially fix #32018 

`git config` and `git remote` write operations create a temporary file named `config.lock`. Since these operations are not atomic, they must not be run in parallel. If two requests attempt to modify the same repository concurrently—such as during a compare operation—one may fail due to the presence of an existing `config.lock` file.

In cases where `config.lock` is left behind due to an unexpected program exit, a global lock mechanism could allow us to safely remove the stale lock file when a related error is detected. While this behavior is not yet implemented in this PR, it is planned for a future enhancement.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
No, it doesn't fix #32018

**Review by wxiaoguang — DISMISSED** [review]
Don't see why it is worth or right to do so, and don't see why it fixes that issue

**Comment by lunny** [comment]
> Don't see why it is worth or right to do so, and don't see why it fixes that issue

`git config` and `git remote` write operations create a temporary file named `config.lock`. Since these operations are not atomic, they must not be run in parallel. If two requests attempt to modify the same repository concurrently—such as during a compare operation—one may fail due to the presence of an existing `config.lock` file.

In cases where `config.lock` is left behind due to an unexpected program exit, a global lock mechanism could allow us to safely remove the stale lock file when a related error is detected. While this behavior is not yet implemented in this PR, it is planned for a future enhancement.

**Comment by wxiaoguang** [comment]
So it is an improvement but doesn't "Fix #32018", right?

But does it really need the "global lock"? Is it possible that git already uses "*.lock" files by `flock` for global lock? Then Gitea shouldn't do anything more?

**Comment by lunny** [comment]
> So it is an improvement but doesn't "Fix #32018", right?
> 
> But does it really need the "global lock"? Is it possible that git already uses "*.lock" files by `flock` for global lock? Then Gitea shouldn't do anything more?

The Git command-line interface is primarily designed for human interaction. When a git config write operation is initiated and a config.lock file is created, any subsequent git config write operation will immediately fail instead of waiting for the first one to complete.

While I couldn’t find official documentation confirming this behavior, the implementation can be found in the Git source code here:
https://github.com/git/git/blob/97e14d99f6def189b0f786ac6207b792ca3197b1/config.c#L3199

Based on this, it appears that Git does not implement a locking mechanism that causes subsequent operations to wait—it simply fails fast.

I believe this change partially addresses #32018, as there are three possible causes for the issue:

- Concurrent requests attempting to compare between the same base and forked repositories.
- A Git command exits unexpectedly, leaving behind a config.lock file. I plan to implement automatic cleanup of stale config.lock files in another PR, which would help resolve this case.
- An administrator manually runs Git commands on the Gitea server. This scenario is outside the scope of this PR, and I don’t believe it’s something we can reliably handle within the application.

**Comment by wxiaoguang** [comment]
Git already does a file-based "global lock"

~~https://github.com/git/git/blob/master/lockfile.c#L104   (config.c hold_lock_file_for_update -> lockfile.c lock_file_timeout )~~

~~I do not think this PR is worth or right.~~

----

Update: git passes timeout=0, so it only locks "once"

File: modules/gitrepo/config.go [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+	releaser, err := globallock.Lock(ctx, getRepoConfigLockKey(repo.RelativePath()))
+	if err != nil {
+		return "", err
+	}
+	defer releaser()
+
+	value, _, err1 := git.NewCommand("config").
+		AddDynamicArguments(key, value).
+		RunStdString(ctx, &git.RunOpts{Dir: repoPath(repo)})
+	return value, err1
```
Comment (wxiaoguang) [inline modules/gitrepo/config.go]: Why return the `value` again

File: modules/gitrepo/config.go [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+		Run(ctx, &git.RunOpts{
+			Timeout: timeout,
+			Dir:     repoPath(repo),
+			Stdout:  stdout,
+			Stderr:  stderr,
+		})
+}
+
+// FIXME: config related? long-time running?
+func GitRemoteUpdatePrune(ctx context.Context, repo Repository, remoteName string, timeout time.Duration, stdout, stderr io.Writer) error {
```
Comment (wxiaoguang) [inline modules/gitrepo/config.go]: I don't think it is right to use global lock for long-time running commands.

Comment (lunny) [reply modules/gitrepo/config.go]: 98bc0df

**Review by hiifong — APPROVED** [review]

**Comment by lunny** [comment]
last call @go-gitea/technical-oversight-committee

File: modules/gitrepo/config.go [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+			Stdout:  stdout,
+			Stderr:  stderr,
+		})
+}
+
+// GitRemoteUpdatePrune updates the remote branches and prunes the ones that no longer exist in the remote repository.
+// No lock is needed because the remote remoteName will be checked before invoking this function.
+// Then it will not update the remote automatically if the remote does not exist.
+func GitRemoteUpdatePrune(ctx context.Context, repo Repository, remoteName string, timeout time.Duration, stdout, stderr io.Writer) error {
+	return git.NewCommand("remote", "update", "--prune").AddDynamicArguments(remoteName).
```
Comment (wxiaoguang) [inline modules/gitrepo/config.go]: Here and above, why `git remote update/prune` belongs to "config.go"?

File: modules/gitrepo/config.go [hunk 4]
```diff
@@ -0,0 +1,155 @@
...
+	}
+	return giturl.ParseGitURL(addr)
+}
+
+func SetRemoteURL(ctx context.Context, repo Repository, remoteName, remoteURL string) error {
+	releaser, err := globallock.Lock(ctx, getRepoConfigLockKey(repo.RelativePath()))
+	if err != nil {
+		return err
+	}
+	defer releaser()
```
Comment (wxiaoguang) [inline modules/gitrepo/config.go]: All these "lock" related code could be in a helper wrapper function:

```
gitConfigLock(..., func() {
   ...
})
```

File: modules/gitrepo/config.go [hunk 5]
```diff
@@ -0,0 +1,155 @@
...
+
+// GitRemoteGetURL returns the url of a specific remote of the repository.
+func GitRemoteGetURL(ctx context.Context, repo Repository, remoteName string) (*giturl.GitURL, error) {
+	addr, err := git.GetRemoteAddress(ctx, repoPath(repo), remoteName)
+	if err != nil {
+		return nil, err
+	}
+	if addr == "" {
+		return nil, nil
+	}
```
Comment (wxiaoguang) [inline modules/gitrepo/config.go]: I believe this design is problematic. 

Developers have been used to that "if err == nil, then there is a non-nil return value"

If you do so, developers would forget to check "u == nil" frequently, and the nil check introduces unnecessary code.

File: services/mirror/mirror_pull.go [hunk 6]
```diff
@@ -39,30 +39,27 @@ func UpdateAddress(ctx context.Context, m *repo_model.Mirror, addr string) error
...
 	// Remove old remote
-	_, _, err = git.NewCommand("remote", "rm").AddDynamicArguments(remoteName).RunStdString(ctx, &git.RunOpts{Dir: repoPath})
+	err = gitrepo.GitRemoteRemove(ctx, repo, remoteName)
 	if err != nil && !git.IsRemoteNotExistError(err) {
 		return err
 	}
 
-	cmd := git.NewCommand("remote", "add").AddDynamicArguments(remoteName).AddArguments("--mirror=fetch").AddDynamicArguments(addr)
-	_, _, err = cmd.RunStdString(ctx, &git.RunOpts{Dir: repoPath})
+	err = gitrepo.GitRemoteAdd(ctx, repo, remoteName, addr, "--mirror=fetch")
```
Comment (wxiaoguang) [inline services/mirror/mirror_pull.go]: Here and other places, IIRC you have defined consts, but why still use string.

File: services/mirror/mirror_pull.go [hunk 7]
```diff
@@ -371,13 +364,31 @@ func runSync(ctx context.Context, m *repo_model.Mirror) ([]*mirrorSyncResult, bo
...
 		stdoutBuilder.Reset()
-		if err := git.NewCommand("remote", "update", "--prune").AddDynamicArguments(m.GetRemoteName()).
-			Run(ctx, &git.RunOpts{
-				Timeout: timeout,
-				Dir:     wikiPath,
-				Stdout:  &stdoutBuilder,
-				Stderr:  &stderrBuilder,
-			}); err != nil {
+
+		// check whether the remote still exists before pruning to avoid prune creating a new remote
```
Comment (wxiaoguang) [inline services/mirror/mirror_pull.go]: > to avoid prune creating a new remote

What "prune"? "git remote prune" or "git remote update --prune"?

I see neither of them would "create a new remote" in the git manual. Correct me if I was wrong.

File: modules/gitrepo/config.go (hunk 3 above)
Comment (lunny) [reply modules/gitrepo/config.go]: ae3c338be3

File: modules/gitrepo/config.go (hunk 4 above)
Comment (lunny) [reply modules/gitrepo/config.go]: ae3c338be3

File: modules/gitrepo/config.go (hunk 5 above)
Comment (lunny) [reply modules/gitrepo/config.go]: ae3c338be3

File: services/mirror/mirror_pull.go (hunk 6 above)
Comment (lunny) [reply services/mirror/mirror_pull.go]: ae3c338be3

File: services/mirror/mirror_pull.go (hunk 7 above)
Comment (lunny) [reply services/mirror/mirror_pull.go]: ae3c338be3

File: services/mirror/mirror_pull.go [hunk 8]
```diff
@@ -371,13 +364,27 @@ func runSync(ctx context.Context, m *repo_model.Mirror) ([]*mirrorSyncResult, bo
...
-		if err := git.NewCommand("remote", "update", "--prune").AddDynamicArguments(m.GetRemoteName()).
-			Run(ctx, &git.RunOpts{
-				Timeout: timeout,
-				Dir:     wikiPath,
-				Stdout:  &stdoutBuilder,
-				Stderr:  &stderrBuilder,
-			}); err != nil {
+
+		// check whether the remote still exists before remote update prune
+		// this is needed because prune will not fail if the remote does not exist
```
Comment (wxiaoguang) [inline services/mirror/mirror_pull.go]: What "prune"? "git remote prune" or "git remote update --prune"?

* below does `git remote update --prune`
* `pruneBrokenReferences` does `git remote prune`

**So what are you doing here for?**

----

I see **NEITHER** of them would "create a new remote" in the git manual. Correct me if I was wrong.

Why "this is needed because prune will not fail if the remote does not exist" is a problem?

**Why you need this logic?**

Comment (lunny) [reply services/mirror/mirror_pull.go]: It said `before remote update prune ..`

Comment (wxiaoguang) [reply services/mirror/mirror_pull.go]: > It said `before remote update prune ..`

Why it needs this logic? What wrong would happen if remote doesn't exist?

Comment (lunny) [reply services/mirror/mirror_pull.go]: I updated the comment via 38c19d2c81

Comment (wxiaoguang) [reply services/mirror/mirror_pull.go]: > Why it needs this logic? What wrong would happen if remote doesn't exist?

Why the "remote" might not exist?

What's wrong with "it will appear to succeed silently, even though nothing was updated."?

If you return "false" here, what end users can see or can do?

Comment (lunny) [reply services/mirror/mirror_pull.go]: I remove these lines via a9633fd8d0

**Review by 6543 — APPROVED** [review]
looking forward to some abstraction layer to better scale

File: modules/gitrepo/remote.go [hunk 9]
```diff
@@ -0,0 +1,97 @@
...
+	if err != nil {
+		return nil, err
+	}
+	if addr == "" {
+		return nil, util.NewNotExistErrorf("remote '%s' does not exist", remoteName)
+	}
+	return giturl.ParseGitURL(addr)
+}
+
+func SetRemoteURL(ctx context.Context, repo Repository, remoteName, remoteURL string) error {
```
Comment (wxiaoguang) [inline modules/gitrepo/remote.go]: It should be named as `GitRemoteSetURL` to match other functions and the command itself `git remote set-url`

File: modules/gitrepo/remote.go [hunk 10]
```diff
@@ -0,0 +1,97 @@
...
+		Run(ctx, &git.RunOpts{
+			Timeout: timeout,
+			Dir:     repoPath(repo),
+			Stdout:  stdout,
+			Stderr:  stderr,
+		})
+}
+
+// GitRemoteUpdatePrune updates the remote branches and prunes the ones that no longer exist in the remote repository.
+// No lock is needed because the remote remoteName will be checked before invoking this function.
```
Comment (wxiaoguang) [inline modules/gitrepo/remote.go]: Where is the "remoteName will be checked"?

File: modules/gitrepo/remote.go [hunk 11]
```diff
@@ -0,0 +1,97 @@
...
+func SetRemoteURL(ctx context.Context, repo Repository, remoteName, remoteURL string) error {
+	return globallock.LockAndDo(ctx, getRepoConfigLockKey(repo.RelativePath()), func(ctx context.Context) error {
+		cmd := git.NewCommand("remote", "set-url").AddDynamicArguments(remoteName, remoteURL)
+		_, _, err := cmd.RunStdString(ctx, &git.RunOpts{Dir: repoPath(repo)})
+		return err
+	})
+}
+
+// GitRemotePrune prunes the remote branches that no longer exist in the remote repository.
+// No lock is needed because the remote remoteName will be checked before invoking this function.
```
Comment (wxiaoguang) [inline modules/gitrepo/remote.go]: Where is the "remoteName will be checked"?

File: modules/gitrepo/config.go [hunk 12]
```diff
@@ -0,0 +1,50 @@
...
+
+func GitConfigGet(ctx context.Context, repo Repository, key string) (string, error) {
+	result, _, err := git.NewCommand("config", "--get").
+		AddDynamicArguments(key).
+		RunStdString(ctx, &git.RunOpts{Dir: repoPath(repo)})
+	if err != nil {
+		return "", err
+	}
+	if len(result) > 0 {
+		result = result[:len(result)-1] // remove trailing newline
```
Comment (wxiaoguang) [inline modules/gitrepo/config.go]: Is it also true for Windows? `\r\n` or only `\n`?

File: services/mirror/mirror_push.go [hunk 13]
```diff
@@ -184,8 +175,8 @@ func runPushSync(ctx context.Context, m *repo_model.PushMirror) error {
 	}
 
 	if m.Repo.HasWiki() {
-		_, err := git.GetRemoteAddress(ctx, m.Repo.WikiPath(), m.RemoteName)
-		if err == nil {
+		u, err := gitrepo.GitRemoteGetURL(ctx, m.Repo.WikiStorageRepo(), m.RemoteName)
+		if err == nil && u != nil {
```
Comment (wxiaoguang) [inline services/mirror/mirror_push.go]: if err is nil, then u isn't nil

File: services/pull/compare.go [hunk 14]
```diff
@@ -0,0 +1,94 @@
...
+		remoteBranch string
+		tmpRemote    string
+	)
+
+	// We don't need a temporary remote for same repository.
+	if headGitRepo.Path != baseRepo.RepoPath() {
+		// Add a temporary remote
+		tmpRemote = strconv.FormatInt(time.Now().UnixNano(), 10)
+		if err = gitrepo.GitRemoteAdd(ctx, headRepo, tmpRemote, baseRepo.RepoPath()); err != nil {
+			return nil, fmt.Errorf("AddRemote: %w", err)
```
Comment (wxiaoguang) [inline services/pull/compare.go]:
```suggestion
			return nil, fmt.Errorf("GitRemoteAdd: %w", err)
```

File: services/issue/pull.go [hunk 15]
```diff
@@ -11,26 +11,27 @@ import (
...
 	tmpRemote := fmt.Sprintf("mergebase-%d-%d", pr.ID, time.Now().UnixNano())
-	if err := repo.AddRemote(tmpRemote, repo.Path, false); err != nil {
-		return "", fmt.Errorf("AddRemote: %w", err)
+	if err := gitrepo.GitRemoteAdd(ctx, repo, tmpRemote, gitRepo.Path); err != nil {
+		return "", fmt.Errorf("GitRemoteAdd: %w", err)
 	}
 	defer func() {
-		if err := repo.RemoveRemote(tmpRemote); err != nil {
-			log.Error("getMergeBase: RemoveRemote: %v", err)
+		if err := gitrepo.GitRemoteRemove(ctx, repo, tmpRemote); err != nil {
```
Comment (wxiaoguang) [inline services/issue/pull.go]: I don't think it can use `ctx` here. In this defer, the ctx might have been canceled.

File: services/pull/compare.go [hunk 16]
```diff
@@ -0,0 +1,94 @@
...
+
+	// We don't need a temporary remote for same repository.
+	if headGitRepo.Path != baseRepo.RepoPath() {
+		// Add a temporary remote
+		tmpRemote = strconv.FormatInt(time.Now().UnixNano(), 10)
+		if err = gitrepo.GitRemoteAdd(ctx, headRepo, tmpRemote, baseRepo.RepoPath()); err != nil {
+			return nil, fmt.Errorf("GitRemoteAdd: %w", err)
+		}
+		defer func() {
+			if err := gitrepo.GitRemoteRemove(ctx, headRepo, tmpRemote); err != nil {
```
Comment (wxiaoguang) [inline services/pull/compare.go]: Same as above, it can't use ctx

Comment (lunny) [reply services/pull/compare.go]: fb2b02f

File: services/issue/pull.go (hunk 15 above)
Comment (lunny) [reply services/issue/pull.go]: fb2b02f

File: services/mirror/mirror_push.go (hunk 13 above)
Comment (lunny) [reply services/mirror/mirror_push.go]: fb2b02f

File: modules/gitrepo/config.go (hunk 12 above)
Comment (lunny) [reply modules/gitrepo/config.go]: fb2b02f

File: modules/gitrepo/remote.go (hunk 11 above)
Comment (lunny) [reply modules/gitrepo/remote.go]: b40e8fd488d19518293d4c5da66a993c04be55df

File: modules/gitrepo/remote.go (hunk 10 above)
Comment (lunny) [reply modules/gitrepo/remote.go]: b40e8fd488d19518293d4c5da66a993c04be55df

File: modules/gitrepo/remote.go (hunk 9 above)
Comment (lunny) [reply modules/gitrepo/remote.go]: b40e8fd488d19518293d4c5da66a993c04be55df
