### PR TITLE
Use refname:strip-2 instead of refname:short when syncing tags

### LINKED ISSUE #28694: Incorrect tag name in mirror
### Description

After creating and syncing https://github.com/manticoresoftware/manticoresearch mirror in gitea 1.21.3, tag name shown in gitea project's tag list is `tags/6.2.12` and should be `6.2.12` like in source github repo. Choosing such tag from list throws error 500 in gitea's UI.

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.30.2

### Operating System

_No response_

### How are you running Gitea?

Compiled from source.

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by lunny**
Fix #28694 

Generally, `refname:short` should be equal to `refname:lstrip=2` except `core.warnAmbiguousRefs is used to select the strict abbreviation mode.`

ref: https://git-scm.com/docs/git-for-each-ref#Documentation/git-for-each-ref.txt-refname

### CODE REVIEW

File: modules/git/repo_tag.go [hunk 1]
```diff
@@ -112,7 +112,7 @@ func (repo *Repository) GetTagWithID(idStr, name string) (*Tag, error) {
 
 // GetTagInfos returns all tag infos of the repository.
 func (repo *Repository) GetTagInfos(page, pageSize int) ([]*Tag, int, error) {
-	forEachRefFmt := foreachref.NewFormat("objecttype", "refname:short", "object", "objectname", "creator", "contents", "contents:signature")
+	forEachRefFmt := foreachref.NewFormat("objecttype", "refname:strip=2", "object", "objectname", "creator", "contents", "contents:signature")
```
Comment (delvh) [inline modules/git/repo_tag.go]: Perhaps we should document that the `refname:strip=2` is needed as the prefix is `/refs/tags`?

Comment (lunny) [reply modules/git/repo_tag.go]: comment added on the code.

**Review by delvh — APPROVED** [review]

**Comment by KN4CK3R** [comment]
Can't you just rewrite the test data? Then it's not needed to add that parameter to `parseTagRef`.

**Review by KN4CK3R — APPROVED** [review]
