### PR TITLE
Honor delete branch on merge repo setting when using merge API

### LINKED ISSUE #35463: Merging a PR via the API does not honor the `Delete pull request branch after merge by default` setting
### Description

When merging a PR using the `/api/v1/repos/{owner}/{repo}/pulls/{index}/merge` endpoint, the PR source branch does not get deleted when `Delete pull request branch after merge by default` is set in the repository settings.

I called the API using `curl -H 'authorization: token <token>' -H 'content-type: application/json' --data '{"Do":"merge"}' https://gitea.example.com/api/v1/repos/vbrandl/test-api-merge/pulls/1/merge` and the PR got merged, but the branch does not get deleted.

Steps to reproduce:

1. create a repository
2. create a PR
3. set `Delete pull request branch after merge by default` in repository settings
4. try merging using the API

Expected behavior: the PR source branch should get deleted

Actual behavior: the PR source branch does not get deleted

I reproduced the issue in https://demo.gitea.com/vbrandl/test-api-merge/pulls/1 using the following API call:

```
$ curl -i -H 'authorization: token <snip>' -H 'content-type: application/json' --data '{"Do":"merge"}' https://demo.gitea.com/api/v1/repos/vbrandl/test-api-merge/pulls/1/merge
HTTP/2 200
alt-svc: h3=":443"; ma=2592000
cache-control: max-age=0, private, must-revalidate, no-transform
date: Thu, 11 Sep 2025 15:11:01 GMT
server: Caddy
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
content-length: 0
```

### Gitea Version

1.24.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Reproduced on demo.gitea.com and my selfhosted instance running on `gitea/gitea:latest`

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by kemzeb**
Fix #35463.

### CODE REVIEW

**Comment by kemzeb** [comment]
The logic has been implemented, but for tests I need to figure out how to work with the git database in the test environment.

Did not see issues when manual-testing the following:
* Merge with delete branch when merge **repo setting** is set
* Merge with delete branch when merge **API form field** is set
* Merge without either fields set

**Comment by kemzeb** [comment]
Update: Will get to adding the tests, just been busy.

**Comment by kemzeb** [comment]
I already written the API integration tests, just having problems with the test repos. I need to use the git hooks in `repo1` as they are used, among other things, to update pull request information.

However, I am getting "pre-receive hook declined" when the test code attempts to push back the changes to the original repo from the temp repo that is created by Gitea. Looking for solutions.

**Comment by kemzeb** [comment]
Created some integration tests covering some of the merge request API.

One thing I realized is that my changes will delete the branch after merge even if _**delete_branch_after_merge**_ is not specified as a form field. I think the form field should take precedence over the repo setting equivalent. If the form field is not defined, we turn to the repo settings to make a determination.

Though, the form field is defined as a `bool`, not as some optional type. Need to figure out how to handle this.

File: services/forms/repo_form.go [hunk 1]
```diff
@@ -540,7 +540,7 @@ type MergePullRequestForm struct {
 	HeadCommitID           string `json:"head_commit_id,omitempty"`
 	ForceMerge             bool   `json:"force_merge,omitempty"`
 	MergeWhenChecksSucceed bool   `json:"merge_when_checks_succeed,omitempty"`
-	DeleteBranchAfterMerge bool   `json:"delete_branch_after_merge,omitempty"`
+	DeleteBranchAfterMerge *bool  `json:"delete_branch_after_merge,omitempty"`
```
Comment (kemzeb) [inline services/forms/repo_form.go:543]: I do not like that I needed to change this form field, but I needed to determine if it was undefined as I currently do the following:
* If the form field is defined, it takes precedence over the repo setting equivalent
* Else, use the repo setting equivalent to make the determination

I spent some time trying to find another solution besides having to change this, but haven't found one yet. Open to other approaches

**Review by lunny — APPROVED** [review]

File: tests/integration/api_pull_test.go [hunk 2]
```diff
@@ -520,3 +624,46 @@ func TestAPIViewPullFilesWithHeadRepoDeleted(t *testing.T) {
 		})(t)
 	})
 }
+
+func creatPullRequestWithCommit(t *testing.T, user *user_model.User, token, newBranch string, repo *repo_model.Repository) *api.PullRequest {
```
Comment (wxiaoguang) [inline tests/integration/api_pull_test.go]: Duplicates:

* createFileInBranch
* doAPICreatePullRequest

File: tests/integration/api_pull_test.go [hunk 3]
```diff
@@ -186,6 +189,107 @@ func TestAPIMergePullWIP(t *testing.T) {
 	MakeRequest(t, req, http.StatusMethodNotAllowed)
 }
 
+func TestAPIMergePull(t *testing.T) {
+	doCheckBranchExists := func(user *user_model.User, token, branchName string, repo *repo_model.Repository, status int) {
```
Comment (wxiaoguang) [inline tests/integration/api_pull_test.go]: `doCheckBranchExists` needs to accept `t`. Otherwise, the errors will be reported in wrong scope (parent test but not sub test)

Comment (kemzeb) [reply tests/integration/api_pull_test.go]: Nice catch, [da4bb40](https://github.com/go-gitea/gitea/pull/35488/commits/da4bb406a873b6da859a52de0dda831708e63d89)

File: tests/integration/api_pull_test.go (hunk 2 above)
Comment (kemzeb) [reply tests/integration/api_pull_test.go]: [da4bb40](https://github.com/go-gitea/gitea/pull/35488/commits/da4bb406a873b6da859a52de0dda831708e63d89) uses `doAPICreatePullRequest()`, but I don't think I can use `createFileInBranch()` as it won't allow me to create a new branch

File: tests/integration/api_pull_test.go [hunk 4]
```diff
@@ -186,6 +189,107 @@ func TestAPIMergePullWIP(t *testing.T) {
...
+			prDTO := createPullRequestWithCommit(t, owner, newBranch, repo)
+
+			req := NewRequestWithJSON(t, http.MethodPost, fmt.Sprintf("/api/v1/repos/%s/%s/pulls/%d/merge", owner.Name, repo.Name, prDTO.Index), &forms.MergePullRequestForm{
+				Do: "merge",
+			}).AddTokenAuth(token)
+
+			MakeRequest(t, req, http.StatusOK)
+			doCheckBranchExists(t, owner, token, newBranch, repo, http.StatusOK)
+			// make sure we cannot perform a merge on the same PR
+			MakeRequest(t, req, http.StatusUnprocessableEntity)
```
Comment (wxiaoguang) [inline tests/integration/api_pull_test.go]: This test is not right. `StatusUnprocessableEntity` is caused by reused `req`, it is an error caused by client, but not the "already merged" error.

The "already merged" error code is 405 (well, it is abused ... but old code does so)

File: tests/integration/api_pull_test.go (hunk 2 above)
Comment (wxiaoguang) [reply tests/integration/api_pull_test.go]: It can be done with some small changes https://github.com/go-gitea/gitea/pull/35488/commits/64db3687831318dab7cbb036b3f8e7ae8f350e55

File: routers/api/v1/repo/pull.go [hunk 5]
```diff
@@ -1035,8 +1037,26 @@ func MergePullRequest(ctx *context.APIContext) {
...
+	if err != nil {
+		ctx.APIErrorInternal(err)
+		return
+	}
+
 	// for agit flow, we should not delete the agit reference after merge
-	if form.DeleteBranchAfterMerge && pr.Flow == issues_model.PullRequestFlowGithub {
+	// FIXME: old code has that comment above. Is that comment valid? What would go wrong if a agit branch is deleted after merge?
+	// * If a agit branch can be deleted after merge, then fix the comment and maybe other related code
+	// * If a agit branch should not be deleted, then we need to fix the logic and add more tests
```
Comment (wxiaoguang) [inline routers/api/v1/repo/pull.go]: Now we have a new question, I think it needs to be addressed.

Maybe @lunny @a1012112796  have some ideas

Comment (wxiaoguang) [reply routers/api/v1/repo/pull.go]: I answered myself by rewriting the old code, and fixed more legacy problems together.

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
->  Always honor user's choice for "delete branch after merge" #36281
