### PR TITLE
Fix broken releases when re-pushing tags (#32435)

### LINKED ISSUE #32427: Deleting a tag for a release breaks the release
### Description

The web UI does not allow deleting tags that are associated with an existing release. However, it can be done via the git client. Doing so turns the release into a draft release. Pushing the tag again does not fix the release.

### Steps to reproduce

1. Create a repository with some content and clone it locally
2. Add a tag: `git tag test`
3. Push the tag: `git push origin test`
4. Create a release for the tag
5. Delete the tag on the server: `git push origin --delete test`
6. Observe that the release is now a "draft"
7. Push the tag again: `git push origin test`
8. Observer that the release is still a "draft"

### Observations

When pushing the tag a second time, the following message is logged:
```
2024/11/05 17:48:34 ...s/repository/push.go:40:handler() [E] pushUpdate[user/example-repo] failed: PushUpdateAddDeleteTags: Insert: pq: duplicate key value violates unique constraint "UQE_release_n"
```
I can't provide more detailed logs at the moment. I can set up a test environment, though, if necessary.

This is a regression. We upgraded from 1.21.x, which did not show this behaviour. Unfortunately, I did not make note which exact version we used before.

### Use case

I realise deleting are re-creating tags from the command line seems like an odd thing to do. We do it as part of a nightly build pipe line, which builds binaries and attaches them to a moving tag and release named `latest`.

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.39.2

### Operating System

Debian GNU/Linux

### How are you running Gitea?

Official release binary, started via systemd

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by GiteaBot**
Backport #32435 by @Zettat123

Fix #32427

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: tests/integration/repo_tag_test.go [hunk 1]
```diff
@@ -117,3 +120,47 @@ func TestCreateNewTagProtected(t *testing.T) {
...
+
+		doGitClone(dstPath, u)(t)
+
+		// create and push a tag
+		_, _, err := git.NewCommand(git.DefaultContext, "tag", "v2.0").RunStdString(&git.RunOpts{Dir: dstPath})
+		assert.NoError(t, err)
+		_, _, err = git.NewCommand(git.DefaultContext, "push", "origin", "--tags", "v2.0").RunStdString(&git.RunOpts{Dir: dstPath})
+		assert.NoError(t, err)
+		// create a release for the tag
+		createdRelease := createNewReleaseUsingAPI(t, token, owner, repo, "v2.0", "", "Release of v2.0", "desc")
```
Comment (Zettat123) [inline tests/integration/repo_tag_test.go]:
```suggestion
		createdRelease := createNewReleaseUsingAPI(t, session, token, owner, repo, "v2.0", "", "Release of v2.0", "desc")
```

Comment (Zettat123) [reply tests/integration/repo_tag_test.go]: @lunny Please help apply this change. Thx.

**Review by techknowlogick — APPROVED** [review]
