### PR TITLE
Fix incorrect default branch label while switching between branches

### LINKED ISSUE #27008: Wrong `default branch` while switching between branches via the web interface
### Description

When switching between branches via the web interface, the default branch should remain unchanged.
ksnip_20230911-153517
e.g. The `default branch` should remain `main`

### Gitea Version

latest codebase

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

building Gitea from source code

### Database

None

### PR DESCRIPTION
**Pull request by yp05327**
Fix #27008

After:
image

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by puni9869 — APPROVED** [review]

**Comment by puni9869** [comment]
🚀

**Comment by yp05327** [comment]
CI failed?

**Comment by puni9869** [comment]
Ci needs a kick

File: web_src/js/components/RepoBranchTagSelector.vue [hunk 1]
```diff
@@ -190,16 +190,16 @@ const sfc = {
       }
       this.isLoading = true;
       try {
-        // the "data.defaultBranch" is ambiguous, it could be "branch name" or "tag name"
+        // the "data.defaultSelectedBranch" is ambiguous, it could be "branch name" or "tag name"
```
Comment (wxiaoguang) [inline web_src/js/components/RepoBranchTagSelector.vue]: Since you have renamed it .... why not give it a better name? Then it isn't ambiguous and such comment could be removed.

Comment (yp05327) [reply web_src/js/components/RepoBranchTagSelector.vue]: `defaultSelected`? 🤔

Comment (wxiaoguang) [reply web_src/js/components/RepoBranchTagSelector.vue]: `defaultSelectedRefName`

**Review by wxiaoguang — APPROVED** [review]
