### PR TITLE
Fix user-defined markup links targets

### LINKED ISSUE #29196: Gitea 1.21.4 adds 'user-content-' in markdown file
### Description

Hi.
I can't navigate through .md file in my repo, because all links in headers are converting from `readme.md#_toc152597800` to `readme.md#user-content-_toc152597800` and it breaks navigation through file.
I read, that it was fixed in https://github.com/go-gitea/gitea/pull/11903 but I can reproduce it in my local instance and in public Gitea instance: https://try.gitea.io/wenofib626/user-content/src/branch/main/readme.md

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.43.0

### Operating System

linux

### How are you running Gitea?

Self-hosted, systemd

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by DanielMatiasCarvalho**
This seeks to fix the bug reported on issue #29196. 

Cause: 
ID's with custom characters (- , _ , etc.), were not linking correctly in the Markdown file when rendered in the browser because the ID in the respective destinies would be different than the one in  anchor, while for IDs with only letters, the ID would be the same.

Fix:
It was suggested that to fix this bug, it should more or less like GitHub does it. While in gitea the anchors would be put in HTML like this:
```
<p dir="auto"><a href="#user-content-_toc152597800" rel="nofollow">Review</a></p>
<p dir="auto"><a href="#user-content-_toc152597802" rel="nofollow">Staging</a></p>
<p dir="auto"><a href="#user-content-_toc152597803" rel="nofollow">Development</a></p>
<p dir="auto"><a href="#user-content-_toc152597828" rel="nofollow">Testing</a></p>
<p dir="auto"><a href="#user-content-_toc152597829" rel="nofollow">Unit-tests</a></p>

```
In GitHub, the same anchor's href properties would be the same without "user-content-" trailing behind.

So my code made sure to change those anchors, so it would not include "user-content-" and then add respective Event Listeners so it would scroll into the supposed places.

Fixes: #29196

### CODE REVIEW

File: web_src/js/markup/anchors.js [hunk 1]
```diff
@@ -30,6 +30,20 @@ export function initMarkupAnchors() {
     });
     heading.prepend(a);
   }
+  for (const anchor of document.querySelectorAll('.markup [dir="auto"] > a[href^="#"][rel="nofollow"]')) {
```
Comment (silverwind) [inline web_src/js/markup/anchors.js]:
```suggestion
  for (const anchor of document.querySelectorAll('.markup a[href^="#"]')) {
```

Seems good enough and will catch nested links as well. Previous selector was far too specific.

File: web_src/js/markup/anchors.js [hunk 2]
```diff
@@ -30,6 +30,20 @@ export function initMarkupAnchors() {
...
+    const originalId = anchor.getAttribute('href').replace(/^#user-content-/, '');
```
Comment (silverwind) [inline web_src/js/markup/anchors.js]: Check first if the link matches the regexp and if it does not `continue` the loop.

File: web_src/js/markup/anchors.js [hunk 3]
```diff
@@ -30,6 +30,20 @@ export function initMarkupAnchors() {
...
+    anchor.setAttribute('href', `#${encodeURIComponent(originalId)}`);
+    const anchorDest = document.getElementsByName(originalId);
+    if (anchorDest && anchorDest.length === 1) {
```
Comment (silverwind) [inline web_src/js/markup/anchors.js]:
```suggestion
    if (anchorDest?.length === 1) {
```

**Comment by silverwind** [comment]
Oh and let's give the PR a proper description...

**Comment by DanielMatiasCarvalho** [comment]
@silverwind Do you think I need to add any more changes to this PR?

File: web_src/js/markup/anchors.js [hunk 4]
```diff
@@ -30,6 +30,24 @@ export function initMarkupAnchors() {
...
+    const anchorDest = document.getElementsByName(originalId);
+    if (anchorDest?.length === 1) {
+      anchor.addEventListener('click', () => {
+        anchorDest[0].scrollIntoView();
+      });
+    } else {
+      anchor.addEventListener('click', (e) => {
+        scrollToAnchor(e.currentTarget.getAttribute('href'), false);
+      });
+    }
```
Comment (silverwind) [inline web_src/js/markup/anchors.js:49]:
```suggestion
```

I see no difference when removing this block because once the `href` on the source link is corrected, it will work natively. Would you agree removing this part?

File: web_src/js/markup/anchors.js [hunk 5]
```diff
@@ -31,5 +33,23 @@ export function initMarkupAnchors() {
...
+    const anchorDest = document.getElementsByName(originalId);
+    if (anchorDest.length === 1) {
+      a.addEventListener('click', () => {
+        anchorDest[0].scrollIntoView();
+      });
+    } else {
+      a.addEventListener('click', (e) => {
+        scrollToAnchor(e.currentTarget.getAttribute('href'), false);
+      });
+    }
```
Comment (silverwind) [inline web_src/js/markup/anchors.js]:
```suggestion
```


I see no behaviour difference when removing this block because once the `href` on the source anchor is corrected, it will work natively. Would you agree?

**Comment by silverwind** [comment]
Did some style tweaks and added some explanatory comments to the file. Works as expected but I think above code block can be removed as we can just let those links work natively after the `href` is corrected.

File: web_src/js/markup/anchors.js (hunk 5 above)
Comment (DanielMatiasCarvalho) [reply web_src/js/markup/anchors.js]: I agree that the first branch of the code you suggested to be removed is unnecessary since the link will work natively, as you suggested. However, by removing the second branch, the markup link targets that do not use `<a name="link"></a>` will break, because we have removed "user-content-" in the links, so it would not link to the corresponding id's. I believe this event listener would solve that issue. 

I have tried my suggestion in an example, and it worked as expected. What do you think about my proposal?

Comment (silverwind) [reply web_src/js/markup/anchors.js]: You are right, please do like this:

```js
    if (document.getElementsByName(originalId).length !== 1) {
      a.addEventListener('click', (e) => {
        scrollToAnchor(e.currentTarget.getAttribute('href'), false);
      });
    }

Comment (DanielMatiasCarvalho) [reply web_src/js/markup/anchors.js]: I have committed your recommendation. I also believe this is a much better way than I had done previously. Thank you for the review.

**Review by silverwind — APPROVED** [review]

**Review by delvh — APPROVED** [review]
