### PR TITLE
Executable check always returns true for windows

### LINKED ISSUE #20636: gitea doctor --run hooks   produces warnings on windows
### Description

if gitea doctor --run hooks  (or --all) is run on a windows system, the script check fails when testing if the script is executable. This check does not make sense on windows as it stands

```
D:\gitea>gitea doctor --run hooks
[1] Check if hook files are up-to-date and executable
 - [W] old hook file D:\gitea\data\gitea-repositories\iti\internaltestinterface.git\hooks\pre-receive is not executable
 - [W] new hook file D:\gitea\data\gitea-repositories\iti\internaltestinterface.git\hooks\pre-receive.d\gitea is not executable
 - [W] old hook file D:\gitea\data\gitea-repositories\iti\internaltestinterface.git\hooks\update is not executable
 - [W] new hook file D:\gitea\data\gitea-repositories\iti\internaltestinterface.git\hooks\update.d\gitea is not executable
 - [W] old hook file D:\gitea\data\gitea-repositories\iti\internaltestinterface.git\hooks\post-receive is not executable
 - [W] new hook file D:\gitea\data\gitea-repositories\iti\internaltestinterface.git\hooks\post-receive.d\gitea is not executable
 - [W] old hook file D:\gitea\data\gitea-repositories\infra\eng_wiki.git\hooks\pre-receive is not executable
```

### Gitea Version

1.17

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

windows

### How are you running Gitea?

service 

### Database

MySQL

### PR DESCRIPTION
**Pull request by eeyrjmr**
Windows doesn't have the concept of "executable" POSIX bits so for now always return true to minimise doctor and logging noise. Fixes: #20636

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

File: modules/repository/hooks.go [hunk 1]
```diff
@@ -153,6 +154,9 @@ func createDelegateHooks(repoPath string) (err error) {
 }
 
 func checkExecutable(filename string) bool {
+	if runtime.GOOS == "windows" {
```
Comment (silverwind) [inline modules/repository/hooks.go:158]:
```suggestion
  // windows has no concept of an executable bit
	if runtime.GOOS == "windows" {
```

**Review by lunny — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
Please send backport to v1.17
