### PR TITLE
Fix "ref-issue" handling in markup

### LINKED ISSUE #31161: The PRs link in release page will get network error
### Description

IMG_2701
https://gitea.com/gitea/act_runner/releases

I will check it later. Not sure whether this is a bug now.

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

gitea.com

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
This is a follow up for #35662, and also fix #31181, help #30275, fix #31161

### CODE REVIEW

**Comment by wxiaoguang** [comment]
The "loading" state is still useful. 

When I use GitHub, when my network lags, there is no UI response (no loading) when I hover the issue links, it looks unclear to me.

----


image

----

image

**Review by lunny — APPROVED** [review]

**Comment by Yakov5776** [comment]
> The "loading" state is still useful.
> 
> When I use GitHub, when my network lags, there is no UI response (no loading) when I hover the issue links, it looks unclear to me.

GitHub doesn't highlight the issue if it doesn't exist though, so how does it look unclear?

As seen here:
https://github.com/Yakov5776/symlink-tests/issues/1

**Comment by wxiaoguang** [comment]
> > The "loading" state is still useful.
> > When I use GitHub, when my network lags, there is no UI response (no loading) when I hover the issue links, it looks unclear to me.
> 
> GitHub doesn't highlight the issue if it doesn't exist though, so how does it look unclear?

I mean **when my network lags**, I didn't change the "issue not exist" case, it can be optimized separately.

**Comment by silverwind** [comment]
Can the fetch inside `ContextPopup.vue` be moved outside? I still prefer to use dumb "render only" components where possible, it was the original idea in https://github.com/go-gitea/gitea/pull/31181.

File: web_src/js/components/ContextPopup.vue [hunk 1]
```diff
@@ -2,62 +2,53 @@
...
-onMounted(() => {
-  root.value.addEventListener('ce-load-context-popup', (e: CustomEventInit<IssuePathInfo>) => {
-    if (!loading.value && issue.value === null) {
-      load(e.detail);
-    }
-  });
+const body = computed(() => {
+  const body = issue.value.body.replace(/\n+/g, ' ');
+  return body.length > 85 ? `${body.substring(0, 85)}…` : body;
 });
```
Comment (silverwind) [inline web_src/js/components/ContextPopup.vue:24]: There is a markdown body truncation function in the backend, we shouldn't re-implement it in JS.

File: web_src/js/components/ContextPopup.vue [hunk 2]
```diff
@@ -2,62 +2,53 @@
...
 <template>
-  <div ref="root">
+  <div class="tw-p-4">
     <div v-if="loading" class="tw-h-12 tw-w-12 is-loading"/>
-    <div v-if="!loading && issue !== null" class="tw-flex tw-flex-col tw-gap-2">
-      <div class="tw-text-12">{{ issue.repository.full_name }} on {{ createdAt }}</div>
+    <div v-else-if="issue" class="tw-flex tw-flex-col tw-gap-2">
+      <div class="tw-text-12">
+        <a :href="repoLink" class="muted">{{ issue.repository.full_name }}</a>
+        on {{ createdAt }}
```
Comment (silverwind) [inline web_src/js/components/ContextPopup.vue:50]: `on` needs translation ideally.

Comment (wxiaoguang) [reply web_src/js/components/ContextPopup.vue:50]: Agree, ideally. 

But I think it doesn't need to be in this PR's scope.

Handling i18n with datetime is also tricky, especially here it is done on frontend and mixes HTML elements.

Leave it to the future (and I don't see anyone complains)

File: web_src/js/components/ContextPopup.vue (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/components/ContextPopup.vue:24]: That's the old code, I didn't change it. And I think it isn't in this PR's scope.

**Comment by wxiaoguang** [comment]
> Can the fetch inside `ContextPopup.vue` be moved outside? I still prefer to use dumb "render only" components where possible, it was the original idea in #31181.

I don't think so. If you move it out, then the "loading" indicator state will be more complex. I believe the "loading" indicator is useful. And since we haven't resolved the "non-existing issue" problem, the "not found" error is also handled there.

I think the current approach is good enough

**Comment by silverwind** [comment]
> If you move it out, then the "loading" indicator state will be more complex

Could just pass a `loading: boolean` prop to the component, but I guess it's not a big issue.

File: web_src/js/components/ContextPopup.vue (hunk 1 above)
Comment (silverwind) [reply web_src/js/components/ContextPopup.vue:24]: I know, we should fix it later.

File: web_src/js/components/ContextPopup.vue (hunk 2 above)
Comment (silverwind) [reply web_src/js/components/ContextPopup.vue:50]: I think we dealt with `on` before related to `relative-time-element`, but it's probably all backend rendering there.

**Comment by wxiaoguang** [comment]
> > If you move it out, then the "loading" indicator state will be more complex
> 
> Could just pass a `loading: boolean` prop to the component, but I guess it's not a big issue.

Then how could you switch the "loading" prop? Vue doesn't work that way.

File: web_src/js/components/ContextPopup.vue (hunk 2 above)
Comment (wxiaoguang) [reply web_src/js/components/ContextPopup.vue:50]: Nope, relative-time-element has dropped the "on" feature, it is non-translatable.

**Comment by silverwind** [comment]
Doesn't vue re-render when props change? At least that's how it works in React.

**Comment by wxiaoguang** [comment]
> Doesn't vue re-render when props change? At least that's how it works in React.

If they are all in the reactive context, yes.

But here, the component is mounted from JS by a non-reactive props object. I don't think React works in this case either.

**Comment by wxiaoguang** [comment]
image

**Comment by silverwind** [comment]
Ah yes if you create a whole vue app or react root, then those props won't be reactive. The auto-update behaviour only works when a component renders another component (which is the typical case in a SPA).

**Comment by wxiaoguang** [comment]
Any other questions?

I think this PR is good enough, it resolves many legacy problems, the code is more maintainable, nothing becomes worse.

Although there could be some improvements, but none of them is easy to implement, so the improvements can be left to the future until someone really needs them and can use some right approaches to implement them.

File: web_src/js/modules/tippy.ts [hunk 3]
```diff
@@ -209,3 +209,7 @@ export function showTemporaryTooltip(target: Element, content: Content): void {
     },
   });
 }
+
+export function getAttachedTippyInstance(el: Element): Instance | null {
+  return el._tippy ?? null;
+}
```
Comment (silverwind) [inline web_src/js/modules/tippy.ts:215]: Instead of  this, can you adjust `globals.d.ts` to add `undefined` to the property:

```ts
interface Element {
  _tippy: import('tippy.js').Instance | undefined;
}
```

And then just use `el._tippy`, typescript will then take care that the undefined case is handled.

Comment (wxiaoguang) [reply web_src/js/modules/tippy.ts:215]: It is very ugly.

I believe in we need to encapsulate the modules, but don't let caller use fragile code.

`el._tippy` is very fragile, it totally depends the undocumented 3rd party library behavior, should never be widely used.

Comment (silverwind) [reply web_src/js/modules/tippy.ts:215]: If you don't want direct `el._tippy` access, that's fine, but then these 2 cases should also use this function:

```
web_src/js/features/common-page.ts:62:              queryElems(elDropdown, '.menu > .item', (el) => el._tippy?.hide());
web_src/js/features/repo-issue-list.ts:189:        el._tippy.destroy();
```

Comment (wxiaoguang) [reply web_src/js/modules/tippy.ts:215]: > If you don't want direct `el._tippy` access, that's fine, but then these 2 cases should also use this function:
> 
> ```
> web_src/js/features/common-page.ts:62:              queryElems(elDropdown, '.menu > .item', (el) => el._tippy?.hide());
> web_src/js/features/repo-issue-list.ts:189:        el._tippy.destroy();
> ```

There are far more, these usages can be refactored later, not in this PR's scope.

image

Comment (silverwind) [reply web_src/js/modules/tippy.ts:215]: TBH, I find the typescript solution better, it does not necessitate such big refactors and is equally safe.

Comment (wxiaoguang) [reply web_src/js/modules/tippy.ts:215]: A variable starting with underscore already means it is for internal usage only, it is a widely accepted agreement across many different languages.

Using a variable with underscore prefix really doesn't seem good.

Comment (silverwind) [reply web_src/js/modules/tippy.ts:215]: It's a practical solution in case of tippy, I agree in a ideal world, properties should not be added to `Element` at all.

We should replace tippy (which is deprecated) with https://github.com/floating-ui/floating-ui.

**Review by silverwind — APPROVED** [review]
