### PR TITLE
Correctly query the primary button in a form

### LINKED ISSUE #32437: Issue editing doesn't work
### Description

When editing issue and pr, save button doesn't work. No errors, nothing

### Gitea Version

1.23.0+dev-623-g41b4ef825d

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
The "primary button" is used at many places, but sometimes they might conflict (due to button switch, hidden panel, dropdown menu, etc).

Sometimes we could add a special CSS class for the buttons, but sometimes not (see the comment of QuickSubmit)

This PR introduces `querySingleVisibleElem` to help to get the correct primary button (the only visible one), and prevent from querying the wrong buttons.

Fix #32437

### CODE REVIEW

File: web_src/js/utils/dom.ts [hunk 1]
```diff
@@ -330,3 +330,10 @@ export function animateOnce(el: Element, animationClassName: string): Promise<vo
     el.classList.add(animationClassName);
   });
 }
+
+export function querySingleVisibleElem<T extends HTMLElement>(parent: Element, selector: string) : T|null {
```
Comment (silverwind) [inline web_src/js/utils/dom.ts]:
```suggestion
export function querySingleVisibleElem<T extends HTMLElement>(parent: Element, selector: string) : T | null {
```

**Review by silverwind — APPROVED** [review]

File: web_src/js/utils/dom.ts [hunk 2]
```diff
@@ -330,3 +330,10 @@ export function animateOnce(el: Element, animationClassName: string): Promise<vo
     el.classList.add(animationClassName);
   });
 }
+
+export function querySingleVisibleElem<T extends HTMLElement>(parent: Element, selector: string) : T | null {
```
Comment (silverwind) [inline web_src/js/utils/dom.ts]:
```suggestion
export function querySingleVisibleElem<T extends HTMLElement>(parent: Element, selector: string): T | null {
```

**Review by lunny — APPROVED** [review]
