### PR TITLE
Replace Monaco with CodeMirror

### LINKED ISSUE #12171: Keep consistent syntax highlighting colors between editor and code review
As above.

### LINKED ISSUE #14776: [BUG/UI] Using the code editor is practically impossible on mobile
As a user and programmer using Gitea, it is impossible in practice to utilize the built in code editor for making quick changes on a file. Attempting to scroll through the editor results in a "right click" menu to pop up displaying keyboard shortcuts as if I'm using a mouse/keyboard, and deleting text does not seem to register at all.

IMO, Gitea is intended to be an extended toolset on top of git, making the UX of the git toolset easier to use. I think the current editor implementation is out of scope and feature bloat, and propose replacing such along the lines of:

- textarea
- shows line numbers on the left

Gitea should not be a replacement for an IDE. For reference sake, as this classifies as a separate issue nor have I tested such tools myself, Gitea should ensure it is able to cleanly integrate with existing tools such as GitPod or Theia, not implement a "half baked" alternative as currently existing. Editing files on Gitea should be for "quick fixes", such as typos or something along the line of only taking a minute or two to do.

### LINKED ISSUE #36311: Pasting code into the monaco-editor doesn't work on iPhone
Pasting code into the monaco-editor doesn't work on iPhone.

### PR DESCRIPTION
**Pull request by silverwind**
- Replace monaco-editor with CodeMirror 6
- Add `--color-syntax-*` CSS variables for all syntax token types, shared by CodeMirror, Chroma and EasyMDE
- Consolidate chroma CSS into a single theme-independent file (`modules/chroma.css`)
- Syntax colors in the code editor now match the code view and light/dark themes
- Code editor is now 12px instead of 14px font size to match code view and GitHub
- Use a global style for kbd elements
- When editing existing files, focus will be on codemirror instead of filename input.
- Keyboard shortcuts are roughtly the same as VSCode
- Add a "Find" button, useful for mobile
- Add context menu similar to Monaco
- Add a command palette (Ctrl/Cmd+Shift+P or F1) or via button
- Add clickable URLs via Ctrl/Cmd+click
- Add e2e test for the code editor
- Remove `window.codeEditors` global
- The main missing Monaco features are hover types and semantic rename but these were not fully working because monaco operated only on single files and only for JS/TS/HTML/CSS/JSON.

| | Monaco (main) | CodeMirror (cm) | Delta |
|---|---|---|---|
| **Build time** | 7.8s | 5.3s | **-32%** |
| **JS output** | 25 MB | 14 MB | **-44%** |
| **CSS output** | 1.2 MB | 1012 KB | **-17%** |
| **Total (no maps)** | 23.3 MB | 12.1 MB | **-48%** |

Fixes: #36311
Fixes: #14776
Fixes: #12171

image

### CODE REVIEW

**Comment by wxiaoguang** [comment]
One line, select all + highlight


image

**Comment by silverwind** [comment]
> One line, select all + highlight

Fixed in https://github.com/go-gitea/gitea/pull/36764/commits/37340241d114b2e8bd43a93ae7619d26b7e8a086.

File: web_src/js/modules/codeeditor.ts [hunk 1]
```diff
@@ -0,0 +1,258 @@
...
+        ...cm.autocomplete.completionKeymap,
+        cm.commands.indentWithTab,
+      ]),
+      cm.state.EditorState.allowMultipleSelections.of(true),
+      cm.language.indentOnInput(),
+      cm.language.syntaxHighlighting(cm.highlight.classHighlighter),
+      cm.language.bracketMatching(),
+      indentUnitComp.of(
+        cm.language.indentUnit.of(
+          editorOpts.indentStyle === 'tab' ? '\t' : ' '.repeat(editorOpts.indentSize || 2),
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/modules/codeeditor.ts]: *This comment was written by Claude.*

Fixed in 6aa7dab228 — changed the default from `|| 2` to `|| 4` to match the template default (`or $.CodeEditorConfig.IndentSize 4`).

File: web_src/js/modules/codeeditor.ts [hunk 2]
```diff
@@ -0,0 +1,258 @@
...
+      ),
+    });
+  });
+
+  elEditorOptions.querySelector<HTMLSelectElement>('.js-indent-size-select')?.addEventListener('change', async (e) => {
+    const target = e.target as HTMLSelectElement;
+    const cm = await importCodemirror();
+    view.dispatch({
+      effects: compartments.tabSize.reconfigure(cm.state.EditorState.tabSize.of(Number(target.value))),
+    });
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/modules/codeeditor.ts]: *This comment was written by Claude.*

Fixed in 6aa7dab228 — unified the indent style/size handlers into a shared `applyIndentSettings()` function that updates both `indentUnit` and `tabSize` together when either dropdown changes. Each handler reads the current value of the other dropdown to stay consistent.

File: web_src/js/modules/codeeditor/main.ts [hunk 3]
```diff
@@ -0,0 +1,258 @@
...
+    togglePreviewDisplay(previewableExts.has(extname(filename)));
+    const configOpts = getEditorConfigOptions(editorConfig);
+    editorOpts = {
+      ...getFileBasedOptions(filenameInput.value, lineWrapExts),
+      indentStyle: configOpts.indentStyle || 'space',
+      ...configOpts,
+    };
+  } else {
+    editorOpts = {indentStyle: 'tab', tabSize: 4, wordWrap: false};
+  }
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: *This comment was written by Claude.*

The git hook editor (the only non-file editor) doesn't render the `.code-editor-options` UI, so the fallback `{indentStyle: 'tab', tabSize: 4, wordWrap: false}` can't disagree with any visible dropdowns. No change needed here.

File: web_src/js/features/repo-settings.ts [hunk 4]
```diff
@@ -73,7 +73,7 @@ function initRepoSettingsSearchTeamBox() {
 function initRepoSettingsGitHook() {
   if (!document.querySelector('.page-content.repository.settings.edit.githook')) return;
   const filename = document.querySelector('.hook-filename')!.textContent;
-  createMonaco(document.querySelector<HTMLTextAreaElement>('#content')!, filename, {language: 'shell'});
+  createCodeEditor(document.querySelector<HTMLTextAreaElement>('#content')!, filename);
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/features/repo-settings.ts]: *This comment was written by Claude.*

Fixed in 6aa7dab228 — now passes `'hook.sh'` as a synthetic filename so CodeMirror detects shell language for syntax highlighting.

**Comment by silverwind** [comment]
many styling fixes done, here is the search panel now:

image

**Review by bircni — COMMENTED** [review]
trim_trailing_whitespace is now only done in backend - previously I think it was also done in frontend?

**Comment by silverwind** [comment]
> trim_trailing_whitespace is now only done in backend - previously I think it was also done in frontend?

CodeMirror does not have such a feature currently, but maybe it can be re-implemented.

**Comment by silverwind** [comment]
> CodeMirror does not have such a feature currently, but maybe it can be re-implemented.

Implemented in https://github.com/go-gitea/gitea/pull/36764/commits/8f09499e64752607ea0d1e84cc78b2661a7bd1cc.

**Comment by bircni** [comment]
> > CodeMirror does not have such a feature currently, but maybe it can be re-implemented.
> 
> Implemented in [8f09499](https://github.com/go-gitea/gitea/commit/8f09499e64752607ea0d1e84cc78b2661a7bd1cc).

Cool already saw it!! 😄

**Comment by silverwind** [comment]
Think I'm done and Copilot also has no complaints, so this is ready for review.

**Comment by bircni** [comment]
I also have no complaints @silverwind 😉

**Review by lunny — APPROVED** [review]

**Comment by lafriks** [comment]
While editor fixes on mobile and size reduction is nice, imho priority for editor is on desktop and monaco editor is way superior and supports more features, so I think it's step back :/

**Comment by silverwind** [comment]
Yes, Codemirror Intellisense is worse, that's the only negative here. I still think it's a necessary move. Monaco is a awkward editor because of its downstream situation with VSCode. VSCode does not care about Monaco so a lot of stuff is half-baked or broken. Especially Firefox support is very bad and mobile support is non-existant.

CodeMirror is bound to catch up eventually. The author is much more active and there is a healthy plugin ecosystem and I already enabled a lot of plugins, it's not so bad.

**Comment by silverwind** [comment]
BTW CodeMirror recently also got a LSP client (https://github.com/codemirror/lsp-client). In the future it could potentially be integrated against a `tsgo` or `gopls` LSP server embedded inside gitea.

Or maybe even against https://github.com/odvcencio/gotreesitter to enable features like "go to definition" for all languages.

**Comment by lafriks** [comment]
Other thing is keybingings, I don't think they are all the same and some are missing, if I remember correctly it did not support keybingings that was combination of two like Ctrl+K Ctrl+C for commenting line(s). And doesn't it need lang-* packages also?

**Comment by silverwind** [comment]
Recent changes:

- Added translation strings
- Added indentation lines
- Improved suggestion autocomplete

image

**Comment by silverwind** [comment]
> Other thing is keybingings, I don't think they are all the same and some are missing, if I remember correctly it did not support keybingings that was combination of two like Ctrl+K Ctrl+C for commenting line(s).

I'm checking if we can add VSCode-style chords.

> And doesn't it need lang-* packages also?

Not needed, `@codemirror/language-data` provides all languages via lazy load.

**Comment by silverwind** [comment]
> I'm checking if we can add VSCode-style chords.

There is https://github.com/replit/codemirror-vscode-keymap but it's hard to integrate as it replaces the codemirror keymap completely apparently.

**Comment by silverwind** [comment]
Ok added that plugin and restored the lost keybinds. `Mod-k Mod-x` is also implemented. @lafriks anything else you might be missing?

**Comment by silverwind** [comment]
Some more additions:

- Links can be clicked via holding Ctrl/Cmd
- Added CSS variable for line height for rendered code and editor

I think at this point, this codemirror has all the features one could imagine.

**Comment by silverwind** [comment]
I also checked CRLF behaviour:

Before: Monaco preserves CRLF, Backend converts to LF
After: Codemirror converts to LF, Backend converts to LF

So, effectively unchanged behaviour.

File: templates/repo/editor/edit.tmpl [hunk 5]
```diff
@@ -33,7 +33,10 @@
 								<div class="ui active tab tw-rounded-b" data-tab="write">
 									<textarea id="edit_area" name="content" class="tw-hidden" data-id="repo-{{.Repository.Name}}-{{.TreePath}}"
 										data-previewable-extensions="{{StringUtils.Join $.CodeEditorConfig.PreviewableExtensions ","}}"
-										data-line-wrap-extensions="{{StringUtils.Join $.CodeEditorConfig.LineWrapExtensions ","}}">{{.FileContent}}</textarea>
+										data-line-wrap-extensions="{{StringUtils.Join $.CodeEditorConfig.LineWrapExtensions ","}}"
+										{{template "repo/editor/code_editor_phrases" .}}
```
Comment (lunny) [inline templates/repo/editor/edit.tmpl]: This is unreadable. Since it's only one line, I don't think it should become a shared template.

Comment (silverwind) [reply templates/repo/editor/edit.tmpl]: It needs to be shared because that template is used in 3 places (code editor, git hook editor, git patch editor).

Comment (silverwind) [reply templates/repo/editor/edit.tmpl]: Ah, but we can just inline `{{JsonUtils.EncodeToString $.CodeEditorPhrases}}` actually.

Comment (silverwind) [reply templates/repo/editor/edit.tmpl]: Done in https://github.com/go-gitea/gitea/pull/36764/commits/151d16a7797c6a634b4da7325e7efc93ed5d5245.

File: web_src/js/utils/url.test.ts [hunk 6]
```diff
@@ -1,4 +1,36 @@
-import {pathEscapeSegments, toOriginUrl} from './url.ts';
+import {cleanUrl, findUrlAt, pathEscapeSegments, toOriginUrl, urlRawRegex} from './url.ts';
+
+function matchUrls(text: string): string[] {
+  return Array.from(text.matchAll(urlRawRegex), (m) => cleanUrl(m[0]));
+}
+
+test('urlRawRegex and cleanUrl', () => {
```
Comment (silverwind) [inline web_src/js/utils/url.test.ts]:
```suggestion
test('matchUrls', () => {
```

File: routers/web/repo/editor.go [hunk 7]
```diff
@@ -442,6 +443,7 @@ func DeleteFilePost(ctx *context.Context) {
 
 func UploadFile(ctx *context.Context) {
 	ctx.Data["PageIsUpload"] = true
+	ctx.Data["IsNewFile"] = true
```
Comment (lunny) [inline routers/web/repo/editor.go]: Upload file could be a new file or update an exist file.

Comment (silverwind) [reply routers/web/repo/editor.go]: I've removed this, it wasn't actually needed, fix is in https://github.com/go-gitea/gitea/pull/36764/commits/2ad8fc5494cf83f2bd1f42cfbdeef7da64ba53aa.

**Comment by silverwind** [comment]
So I think CodeMirror pretty much has everything Monaco had except tooltips and command palette. Tooltips were imho never really useful because there was no LSP backing them, and command pallete I'm not sure, I personally don't use it, most stuff is available in the VSCode keyboard shortcuts.

**Comment by silverwind** [comment]
Added a few more languages and extensions. Language support should be on par/better than Monaco, but I do notice a lack of a proper Makefile syntax. CMake kinda works but not ideal.

File: routers/web/repo/editor_util.go [hunk 8]
```diff
@@ -94,6 +94,40 @@ func getCodeEditorConfig(ctx *context_service.Context, treePath string) (ret Cod
...
 
+// CodeEditorPhrases returns a map of CodeMirror phrase keys to translated strings.
+// The keys must match the exact phrases used by CodeMirror's built-in extensions.
+func CodeEditorPhrases(ctx *context_service.Context) map[string]string {
+	return map[string]string{
+		"Find":                     ctx.Locale.TrString("editor.code_editor.find"),
+		"Replace":                  ctx.Locale.TrString("editor.code_editor.replace"),
+		"next":                     ctx.Locale.TrString("editor.code_editor.next"),
+		"previous":                 ctx.Locale.TrString("editor.code_editor.previous"),
+		"all":                      ctx.Locale.TrString("editor.code_editor.all"),
```
Comment (wxiaoguang) [inline routers/web/repo/editor_util.go]: I believe we should not do this.

1. It is quite fragile
2. It is unclear to translators (what are "go", "all", they are not translatable without a clear context)
3. Code editor users should know basic English, otherwise how can they edit code.

The best choice is to leave the original UI & texts as-is.

**Comment by wxiaoguang** [comment]
> One line, select all + highlight

Still, it is not readable.


image

File: routers/web/repo/editor_util.go (hunk 8 above)
Comment (silverwind) [reply routers/web/repo/editor_util.go]: hmm, previous monaco also was english only at least.

**Comment by silverwind** [comment]
Yeah I will test light mode more.

File: tests/e2e/codeeditor.test.ts [hunk 9]
```diff
@@ -0,0 +1,27 @@
+import {env} from 'node:process';
+import {expect, test} from '@playwright/test';
+import {login, apiCreateRepo, apiDeleteRepo} from './utils.ts';
+
+test.describe('codeeditor', () => {
+  const repoName = `e2e-codeeditor-${Date.now()}`;
+
+  test.beforeAll(async ({request}) => {
+    await apiCreateRepo(request, {name: repoName});
```
Comment (wxiaoguang) [inline tests/e2e/codeeditor.test.ts]: Reiterate my previous review:

If there is no prepared test fixtures, every case creates the repo & files by itself, then the CI testing will be slow.

Now you only have a few cases, so you don't feel it.

Suppose some days later, there are 200 cases, by average, each case takes 10 seconds, then it is 33 minutes.

At that time, who will be the one to improve the testing performance?

----

Take backend as example, the CI testing time increases a lot, who would improve the situation?

**Comment by silverwind** [comment]
> > One line, select all + highlight
> 
> Still, it is not readable.
> image

cannot reproduce:

image

File: tests/e2e/codeeditor.test.ts (hunk 9 above)
Comment (silverwind) [reply tests/e2e/codeeditor.test.ts]: A setup step that creates repos and such can easily be added to Playwright, I can add that another time, but not in this PR.

**Comment by silverwind** [comment]
Now there is also a command palette, it's pretty minimal but better than nothing.

image

Also I've removed all translations inside the editor frame, these will be english only. Outside UI is translated as usual.

**Comment by silverwind** [comment]
@wxiaoguang I can not reproduce your "white text" issue in light mode. Maybe something interfering? Try another browser.

Other than that, I'd say it's ready.

File: routers/web/repo/editor_util.go (hunk 8 above)
Comment (silverwind) [reply routers/web/repo/editor_util.go]: Fixed.

**Comment by wxiaoguang** [comment]
> @wxiaoguang I can not reproduce your "white text" issue in light mode. Maybe something interfering? Try another browser.
> 
> Other than that, I'd say it's ready.

Chrome is reproducible. Firefox isn't. I think you still need to test Chrome, it is more widely used than Firefox.

**Comment by silverwind** [comment]
> > @wxiaoguang I can not reproduce your "white text" issue in light mode. Maybe something interfering? Try another browser.
> > Other than that, I'd say it's ready.
> 
> Chrome is reproducible. Firefox isn't. I think you still need to test Chrome, it is more widely used than Firefox.

Fixed in https://github.com/go-gitea/gitea/pull/36764/commits/80032d2e06d0d1c95d628efe9990944234cf7255. Apparently a browser difference regarding `inherit`.

File: web_src/js/utils/url.ts [hunk 10]
```diff
@@ -1,3 +1,26 @@
...
+  // Strip trailing punctuation that's likely not part of the URL
+  url = url.replace(/[.,;:'"]+$/, '');
+  // Strip trailing closing parens only if unbalanced (not part of the URL like Wikipedia links)
+  while (url.endsWith(')') && (url.match(/\(/g) || []).length < (url.match(/\)/g) || []).length) {
+    url = url.slice(0, -1);
+  }
+  return url;
+}
+
+export function findUrlAt(doc: string, pos: number): string | null {
```
Comment (wxiaoguang) [inline web_src/js/utils/url.ts]: `findUrlAt` and `cleanUrl` seem both for special purpose, not a general util

`cleanUrl` the name doesn't match its function. "clean" means keep the meaning of the input, but it tries to guess the URL by removing some parts.

File: web_src/js/modules/codeeditor.ts [hunk 11]
```diff
@@ -0,0 +1,612 @@
...
+const isMac = /Mac/i.test(navigator.userAgent);
+const keySymbols: Record<string, string> = isMac ?
+  {Mod: '\u2318', Alt: '\u2325', Shift: '\u21E7', Up: '\u2191', Down: '\u2193', Enter: '\u23CE'} :
+  {Mod: 'Ctrl', Up: '\u2191', Down: '\u2193', Enter: '\u23CE'};
+
+function formatKeys(keys: string): string[] {
+  return keys.split(/[+ ]/).map((k) => keySymbols[k] || k);
+}
+
+function commandPalette(cm: Awaited<ReturnType<typeof importCodemirror>>) {
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor.ts]: No idea why it's worth to manually write a "commandPalette"

If it is a must, it should be split into a standalone file.

Comment (silverwind) [reply web_src/js/modules/codeeditor.ts]: Monaco users might be used to it, and I think it's a useful addition as it's also useful to learn the keyboard shortcuts.

Yes I will move it to a file.

File: web_src/js/modules/codeeditor.ts [hunk 12]
```diff
@@ -0,0 +1,612 @@
...
+  }, {decorations: (v) => v.decorations});
+
+  const handler = cm.view.EditorView.domEventHandlers({
+    mousedown(event: MouseEvent, view: EditorView) {
+      if (!(event.metaKey || event.ctrlKey)) return false;
+      const pos = view.posAtCoords({x: event.clientX, y: event.clientY});
+      if (pos === null) return false;
+      const url = findUrlAt(view.state.doc.toString(), pos);
+      if (!url) return false;
+      window.open(url, '_blank', 'noopener,noreferrer');
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor.ts]: None of them is need. IIRC.

image

File: web_src/js/modules/codeeditor.ts [hunk 13]
```diff
@@ -0,0 +1,612 @@
...
+  });
+
+  const modClass = cm.view.ViewPlugin.fromClass(class {
+    container: Element | null;
+    handleKeyDown: (e: KeyboardEvent) => void;
+    handleKeyUp: (e: KeyboardEvent) => void;
+    constructor(view: EditorView) {
+      this.container = view.dom.closest('.code-editor-container');
+      this.handleKeyDown = (e) => { if (e.key === 'Meta' || e.key === 'Control') this.container?.classList.add('cm-mod-held'); };
+      this.handleKeyUp = (e) => { if (e.key === 'Meta' || e.key === 'Control') this.container?.classList.remove('cm-mod-held'); };
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor.ts]: Why you expect it doesn't exist?

**Review by wxiaoguang — COMMENTED** [review]
It seems that the event listener management is not right.

Some listeners are only added but not removed or can be added twice.

File: web_src/js/modules/codeeditor.ts (hunk 11 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor.ts]: split and moved everything to new folder `modules/codeeditor` in https://github.com/go-gitea/gitea/pull/36764/commits/d221c04570e92508474592c25f2cc08700765544.

File: web_src/js/utils/url.ts (hunk 10 above)
Comment (silverwind) [reply web_src/js/utils/url.ts]: Fixed in https://github.com/go-gitea/gitea/pull/36764/commits/d221c04570e92508474592c25f2cc08700765544.

File: web_src/js/modules/codeeditor/main.ts [hunk 14]
```diff
@@ -0,0 +1,326 @@
...
+}
+
+export async function createCodeEditor(textarea: HTMLTextAreaElement, filenameInput?: HTMLInputElement | string): Promise<CodemirrorEditor> {
+  const filename = basename(typeof filenameInput === 'string' ? filenameInput : filenameInput?.value || '');
+  const previewableExts = new Set((textarea.getAttribute('data-previewable-extensions') || '').split(','));
+  const lineWrapExts = (textarea.getAttribute('data-line-wrap-extensions') || '').split(',');
+
+  let editorOpts: EditorOptions;
+  if (typeof filenameInput === 'object') {
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/main.ts]: Very fragile.

Why not

```
{
filenameInput:  HTMLInputElement
defaultFilename: string
}
```

File: web_src/js/modules/shortcut.ts [hunk 15]
```diff
@@ -11,11 +11,13 @@ function initShortcutKbd(kbd: HTMLElement) {
...
 function elemFromKbd(kbd: HTMLElement): HTMLInputElement | HTMLTextAreaElement | null {
-  return kbd.parentElement!.querySelector<HTMLInputElement>('input, textarea') || null;
+  const parent = kbd.closest('.global-shortcut-wrapper');
+  return parent?.querySelector<HTMLInputElement>('input, textarea') || null;
 }
 
 function kbdFromElem(input: HTMLElement): HTMLElement | null {
-  return input.parentElement!.querySelector<HTMLElement>('kbd') || null;
+  const parent = input.closest('.global-shortcut-wrapper');
+  return parent?.querySelector<HTMLElement>('kbd') || null;
```
Comment (silverwind) [inline web_src/js/modules/shortcut.ts]: fyi had to fix this, the problem was when the search box in the command palette was focused, the first `<kbd>` was hidden by this code. Now the behaviour is scoped to only occur inside `.global-shortcut-wrapper`.

Comment (wxiaoguang) [inline web_src/js/modules/shortcut.ts]: Why `?` ?

Don't break the design if you don't need to use it.

File: web_src/js/modules/shortcut.ts [hunk 16]
```diff
@@ -11,11 +11,13 @@ function initShortcutKbd(kbd: HTMLElement) {
 }
 
 function elemFromKbd(kbd: HTMLElement): HTMLInputElement | HTMLTextAreaElement | null {
-  return kbd.parentElement!.querySelector<HTMLInputElement>('input, textarea') || null;
+  const parent = kbd.closest('.global-shortcut-wrapper');
+  return parent?.querySelector<HTMLInputElement>('input, textarea') || null;
```
Comment (wxiaoguang) [inline web_src/js/modules/shortcut.ts]: `elemFromKbd` is designed to only work in `.global-shortcut-wrapper > kbd[data-shortcut-keys]`

Why you need to change it?


image

File: web_src/js/modules/shortcut.ts (hunk 15 above)
Comment (wxiaoguang) [reply web_src/js/modules/shortcut.ts]: You need to check `data-shortcut-keys` explicitly if you don't want to execute this logic in other contexts.

File: web_src/js/modules/codeeditor.ts (hunk 12 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor.ts]: fixed in https://github.com/go-gitea/gitea/pull/36764/commits/6afae35c318ea8a64f28c111c7c4f1bc2846b64f.

File: web_src/js/modules/shortcut.ts (hunk 15 above)
Comment (silverwind) [reply web_src/js/modules/shortcut.ts]: the problem was when the search box in the command palette was focused, the first `<kbd>` was hidden by this code. Now the behaviour is scoped to only occur inside `.global-shortcut-wrapper`.

So no, i don't want this logic, it was causing problems.

The DOM here is like this:

```
<input>
<kbd> <- this was hidden on input focus
<kbd>
```

File: web_src/js/modules/shortcut.ts (hunk 16 above)
Comment (silverwind) [reply web_src/js/modules/shortcut.ts]: see https://github.com/go-gitea/gitea/pull/36764#discussion_r2863700462

File: web_src/js/modules/codeeditor.ts (hunk 13 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor.ts]: Yeah I will do a pass over all these `?`, most if not all are unnecessary.

File: web_src/js/modules/codeeditor/main.ts (hunk 14 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: IIRC, this is legacy code from Monaco, but we can improve it.

File: web_src/js/modules/shortcut.ts (hunk 15 above)
Comment (wxiaoguang) [reply web_src/js/modules/shortcut.ts]: I see.

Made some changes in https://github.com/go-gitea/gitea/pull/36764/commits/30138204c89d463289f0ef1cb08091682052eb4a to make the logic stricter.

File: web_src/js/modules/codeeditor/command-palette.ts [hunk 17]
```diff
@@ -0,0 +1,227 @@
...
+          this.removeOverlay();
+        }
+      };
+    }
+
+    update(upd: ViewUpdate) {
+      for (const tr of upd.transactions) {
+        for (const e of tr.effects) {
+          if (e.is(openEffect) && !this.overlay) {
+            this.show();
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/command-palette.ts]: Why calling `show` in a loop?

File: web_src/js/modules/codeeditor/command-palette.ts [hunk 18]
```diff
@@ -0,0 +1,227 @@
...
+      if (!container) return;
+
+      this.overlay = document.createElement('div');
+      this.overlay.className = 'cm-command-palette';
+
+      this.input = document.createElement('input');
+      this.input.className = 'cm-command-palette-input';
+      this.input.placeholder = 'Type a command...';
+      this.input.addEventListener('input', () => this.filter());
+      this.input.addEventListener('keydown', (e) => this.handleKey(e));
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/command-palette.ts]: ~~Each `show` adds event listeners?~~

~~That's why you shouldn't trust AI code.~~

OK, newly created here.

File: web_src/js/modules/codeeditor/command-palette.ts (hunk 17 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/command-palette.ts]: The command palette class was ai-generated, I will review later. Likely more complex than it needs to be.

**Comment by wxiaoguang** [comment]
When pressing Esc to hide the command palette, the editor won't get focused again

**Comment by wxiaoguang** [comment]
Trivial: different padding

image

File: web_src/js/modules/codeeditor.ts (hunk 13 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor.ts]: Done in https://github.com/go-gitea/gitea/pull/36764/commits/a06532427021bb76d106eb47bfbf70fdb260bf87.

File: web_src/js/modules/codeeditor/main.ts [hunk 19]
```diff
@@ -0,0 +1,324 @@
...
+import {createElementFromHTML, onInputDebounce, toggleElem} from '../../utils/dom.ts';
+import {html, htmlRaw} from '../../utils/html.ts';
+import {svg} from '../../svg.ts';
+import {commandPalette} from './command-palette.ts';
+import {clickableUrls, trimTrailingWhitespaceFromView} from './utils.ts';
+import type {LanguageDescription} from '@codemirror/language';
+import type {Compartment} from '@codemirror/state';
+import type {EditorView, ViewUpdate} from '@codemirror/view';
+
+type EditorConfig = {
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/main.ts]: Please keep the clear name CodeEditorConfig

There are different editors, for example: MarkdownEditor.

File: web_src/js/features/repo-editor.ts [hunk 20]
```diff
@@ -169,17 +169,26 @@ export function initRepoEditor() {
   initEditPreviewTab(elForm);
 
   (async () => {
-    const editor = await createCodeEditor(editArea, filenameInput);
+    const editor = await createCodeEditor(editArea, {filenameInput});
+
+    if (editArea.hasAttribute('data-autofocus')) {
```
Comment (wxiaoguang) [inline web_src/js/features/repo-editor.ts]: Why not use `autofocus` directly but reinvent a new attribute?

File: web_src/js/modules/codeeditor/main.ts (hunk 19 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: I thought I make it match https://editorconfig.org/, but whatever you prefer.

File: web_src/js/features/repo-settings.ts [hunk 21]
```diff
@@ -72,8 +72,8 @@ function initRepoSettingsSearchTeamBox() {
 
 function initRepoSettingsGitHook() {
   if (!document.querySelector('.page-content.repository.settings.edit.githook')) return;
-  const filename = document.querySelector('.hook-filename')!.textContent;
-  createMonaco(document.querySelector<HTMLTextAreaElement>('#content')!, filename, {language: 'shell'});
+  const hookName = document.querySelector('.hook-filename')!.textContent.trim() || 'hook';
```
Comment (wxiaoguang) [inline web_src/js/features/repo-settings.ts]: Why expect `.hook-filename` doesn't have content?

Comment (silverwind) [reply web_src/js/features/repo-settings.ts]: Yeah that fallback is unneeded.

File: web_src/js/modules/codeeditor/command-palette.ts [hunk 22]
```diff
@@ -0,0 +1,227 @@
+import type {EditorView, ViewUpdate} from '@codemirror/view';
+import type {importCodemirror} from './main.ts';
+import {trimTrailingWhitespaceFromView} from './utils.ts';
+
+type PaletteCommand = {
+  label: string;
+  keys?: string;
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/command-palette.ts]: If a command doesn't have a key, it can be empty string but not undefined.

File: web_src/js/features/repo-editor.ts (hunk 20 above)
Comment (silverwind) [reply web_src/js/features/repo-editor.ts]: We need to call a CodeMirror method to focus the actual editor, autofocus does not work. If you mean putting `autofocus` on a `<div>`, I think that would be undefined browser behaviour.

File: web_src/js/modules/codeeditor/main.ts (hunk 19 above)
Comment (wxiaoguang) [reply web_src/js/modules/codeeditor/main.ts]: It isn't really from editorconfig.

This struct is fully managed by our code.

It just happens to have some same names as "editorconfig" due to history reason.

Comment (wxiaoguang) [reply web_src/js/modules/codeeditor/main.ts]: And they already have different types now

```
			ret.IndentSize, _ = strconv.Atoi(def.IndentSize)
```

image

File: web_src/js/features/repo-editor.ts (hunk 20 above)
Comment (wxiaoguang) [reply web_src/js/features/repo-editor.ts]: Why not `editArea.hasAttribute('autofocus')` ?

Comment (silverwind) [reply web_src/js/features/repo-editor.ts]: May work, but my concern is that setting `autofocus` on a un-focusable element may lead to unexpected browser behaviour (likely a noop, but you never know). Using a data attribute is safer.

Comment (wxiaoguang) [reply web_src/js/features/repo-editor.ts]: > May work, but my concern is that setting `autofocus` on a un-focusable element may lead to unexpected browser behaviour (likely a noop, but you never know). Using a data attribute is save.

It is well-defined behavior.

I have shown that how our `.show-panel` works.

* https://github.com/go-gitea/gitea/pull/36606#issuecomment-3904393934

Comment (wxiaoguang) [reply web_src/js/features/repo-editor.ts]: Including official standard behavior: `autofocus` in `dialog`.

**Comment by silverwind** [comment]
Added a button to toggle the command palette as well and did a few adjustments to native select css so they match the buttons:

image

**Comment by silverwind** [comment]
> Trivial: different padding

Adressed:

image

File: web_src/js/modules/codeeditor/command-palette.ts [hunk 23]
```diff
@@ -0,0 +1,243 @@
...
+          if (e.is(openEffect)) {
+            if (this.overlay) {
+              this.removeOverlay();
+            } else {
+              this.show();
+            }
+          }
+        }
+      }
+    }
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/command-palette.ts]: Unable to understand why it uses 2-level for-loop to "show" something.

Is it the standard approach?

File: web_src/js/modules/codeeditor/command-palette.ts [hunk 24]
```diff
@@ -0,0 +1,243 @@
...
+      container.append(this.overlay);
+
+      this.filtered = commands;
+      this.selectedIndex = 0;
+      this.renderList();
+      this.input.focus();
+
+      requestAnimationFrame(() => {
+        document.addEventListener('mousedown', this.handleClickOutside);
+      });
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/command-palette.ts]: Why it needs `requestAnimationFrame`?

File: web_src/js/modules/codeeditor/main.ts (hunk 19 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: *This comment was written by Claude.*

Reverted back to `CodeEditorConfig` in b3e09c9c32.

File: web_src/js/features/repo-editor.ts (hunk 20 above)
Comment (silverwind) [reply web_src/js/features/repo-editor.ts]: *This comment was written by Claude.*

Changed to use the standard `autofocus` attribute in both the template and JS in b3e09c9c32.

File: web_src/js/features/repo-settings.ts (hunk 21 above)
Comment (silverwind) [reply web_src/js/features/repo-settings.ts]: *This comment was written by Claude.*

Removed the unnecessary fallback in b3e09c9c32.

File: web_src/js/modules/codeeditor/command-palette.ts (hunk 22 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/command-palette.ts]: *This comment was written by Claude.*

Changed `keys` to required in b3e09c9c32. All commands already provide keys.

File: web_src/js/modules/codeeditor/main.ts (hunk 14 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: *This comment was written by Claude.*

Refactored to use a discriminated union type `{filenameInput: HTMLInputElement} | {defaultFilename: string}` in b3e09c9c32, eliminating the non-null assertions.

File: web_src/js/modules/codeeditor/command-palette.ts (hunk 17 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/command-palette.ts]: *This comment was written by Claude.*

Added early `return` after handling the effect in b3e09c9c32 so it only executes once per update.

File: web_src/js/modules/codeeditor/command-palette.ts (hunk 23 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/command-palette.ts]: Yeah seems suspicious

**Comment by wxiaoguang** [comment]
Mobile

image

**Comment by silverwind** [comment]
> Mobile

Needs min-width and likely some padding tweaks, will check.

File: web_src/js/modules/codeeditor/command-palette.ts (hunk 23 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/command-palette.ts]: It says:

> Yes, this is the standard CodeMirror pattern — ViewPlugin.update() receives a ViewUpdate containing multiple transactions, each with multiple effects. The nested loop is how you check for a specific StateEffect

It still found a way to simplify, will push that soon after doing more cleanup in the command pallette js.

Comment (silverwind) [reply web_src/js/modules/codeeditor/command-palette.ts]: Next cleanup will be:

> Yes, the whole ViewPlugin/StateEffect pattern is unnecessary here. The palette is just DOM manipulation — it doesn't need CodeMirror's state system. A simple closure approach is much cleaner.

Comment (silverwind) [reply web_src/js/modules/codeeditor/command-palette.ts]: done in https://github.com/go-gitea/gitea/pull/36764/commits/961fb0f4ca5d40190c082de7fc5bc5ec91330721.

File: web_src/js/modules/codeeditor/command-palette.ts (hunk 24 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/command-palette.ts]: was something about mouse events, but deemed unneccesary and I tested, it works without. removed in https://github.com/go-gitea/gitea/pull/36764/commits/d090b7cee18bb231babffa7fdbdbd882f1f41631.

File: web_src/js/modules/codeeditor/command-palette.ts [hunk 25]
```diff
@@ -0,0 +1,209 @@
...
+        }
+      }
+      item.append(keysEl);
+      list.append(item);
+    }
+  }
+
+  function show(view: EditorView) {
+    const container = view.dom.closest('.code-editor-container');
+    if (!container) return;
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/command-palette.ts]: Why expect it not exists?

**Comment by silverwind** [comment]
> > Mobile
> 
> Needs min-width and likely some padding tweaks, will check.

added wrap:

image

File: web_src/js/modules/codeeditor/command-palette.ts [hunk 26]
```diff
@@ -0,0 +1,209 @@
...
+      hide(view);
+      cmd.run(view);
+    };
+
+    list.addEventListener('pointerenter', (e) => {
+      const item = (e.target as Element).closest<HTMLElement>('.cm-command-palette-item');
+      if (!item) return;
+      selectedIndex = Number(item.dataset.index);
+      updateSelected();
+    }, true);
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/command-palette.ts]: Why capture?

File: web_src/js/modules/codeeditor/command-palette.ts [hunk 27]
```diff
@@ -0,0 +1,209 @@
...
+
+    list.addEventListener('mousedown', (e) => {
+      e.preventDefault();
+      const item = (e.target as Element).closest<HTMLElement>('.cm-command-palette-item');
+      if (!item) return;
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/command-palette.ts:148]: Why preventDefault before item check?

File: web_src/js/modules/codeeditor/command-palette.ts (hunk 25 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/command-palette.ts]: fixed: https://github.com/go-gitea/gitea/pull/36764/commits/b58cc55b64d3edc1a51086a67d78f9f45a34880e

File: web_src/js/modules/codeeditor/main.ts [hunk 28]
```diff
@@ -0,0 +1,332 @@
...
+    return JSON.parse(json);
+  } catch {
+    return null;
+  }
+}
+
+// export editor for customization - https://github.com/go-gitea/gitea/issues/10409
+function exportEditor(editor: EditorView): void {
+  if (!window.codeEditors) window.codeEditors = [];
+  if (!window.codeEditors.includes(editor)) window.codeEditors.push(editor);
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/main.ts]: I think `window.codeEditors` can be removed now, until someone really needs it.

Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: yeah it's pretty niche use case

File: web_src/js/modules/codeeditor/command-palette.ts (hunk 26 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/command-palette.ts]: *This comment was written by Claude.*

Changed from `pointerenter` with capture to `pointerover` which bubbles naturally and doesn't need capture for event delegation.

File: web_src/js/modules/codeeditor/command-palette.ts (hunk 27 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/command-palette.ts:148]: *This comment was written by Claude.*

Moved `preventDefault` after the item check so it only fires when clicking an actual item.

File: web_src/js/modules/codeeditor/main.ts (hunk 28 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: removed in https://github.com/go-gitea/gitea/pull/36764/commits/fbaac8fd1b848ef92c01dc3dbdff6631ef038ee5.

**Comment by silverwind** [comment]
added a stylelint rule to prevent mistake https://github.com/go-gitea/gitea/pull/36764/commits/718826e1a39f6dac44ddbfd7fe6dfe89c2f3e440 in the future.

File: web_src/js/modules/codeeditor/utils.ts [hunk 29]
```diff
@@ -0,0 +1,99 @@
...
+      return true;
+    },
+  });
+
+  const modClass = cm.view.ViewPlugin.fromClass(class {
+    container: Element;
+    handleKeyDown: (e: KeyboardEvent) => void;
+    handleKeyUp: (e: KeyboardEvent) => void;
+    handleBlur: () => void;
+    constructor(view: EditorView) {
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/modules/codeeditor/utils.ts:113]: no, intended

File: web_src/js/modules/codeeditor/command-palette.ts [hunk 30]
```diff
@@ -0,0 +1,207 @@
...
+          keysEl.append(kbd);
+        }
+      }
+      item.append(keysEl);
+      list.append(item);
+    }
+  }
+
+  function show(view: EditorView) {
+    const container = view.dom.closest('.code-editor-container')!;
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/modules/codeeditor/command-palette.ts:105]: no, intended

File: web_src/js/modules/codeeditor/utils.ts [hunk 31]
```diff
@@ -0,0 +1,99 @@
...
+    url = url.slice(0, -1);
+  }
+  return url;
+}
+
+/** Find the URL at the given character position in a document string, or null if none. */
+export function findUrlAtPosition(doc: string, pos: number): string | null {
+  for (const match of doc.matchAll(urlRawRegex)) {
+    const url = trimUrlPunctuation(match[0]);
+    if (pos >= match.index && pos <= match.index + url.length) {
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/modules/codeeditor/utils.ts]: *(comment by Claude)* Done, added the `match.index !== undefined` guard.

File: web_src/js/modules/codeeditor/main.ts [hunk 32]
```diff
@@ -0,0 +1,321 @@
...
+  trim_trailing_whitespace?: boolean,
+};
+
+type EditorOptions = {
+  indentStyle: string;
+  indentSize?: number;
+  tabSize?: number;
+  wordWrap: boolean;
+  trimTrailingWhitespace: boolean;
+};
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/main.ts]: What's the difference between `CodeEditorConfig` and `EditorOptions`?

`CodeEditorConfig` is full managed by us, don't see why it need another wrapper.

Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: combined into `CodeEditorConfig` in https://github.com/go-gitea/gitea/pull/36764/commits/c60511c72e5bf0eb6ee2c8bdb63e94a2e7cc6f35.

File: tests/e2e/codeeditor.test.ts (hunk 9 above)
Comment (silverwind) [reply tests/e2e/codeeditor.test.ts]: @wxiaoguang the problem with shared dependencies like repos is they may limit the concurrency the tests can execute in. If every test has its own unique dependencies, test cases can run with infinite concurrency theoretically.

So by adding shared repos etc, you will likely make the tests slower if you need to serialize some tests because of shared dependency.

**Review by wxiaoguang — DISMISSED** [review]

**Comment by silverwind** [comment]
I asked Claude regarding autofocus on the invisible textarea, and it identifies these concerns:

- Screen readers: Most screen readers skip elements with display: none, but autofocus tries to move focus there. The behavior is browser-dependent — some browsers may ignore autofocus on hidden elements, others may set focus to an invisible element, leaving screen reader users confused with no audible focus context.
- Keyboard users: If the browser does honor the autofocus, keyboard focus lands on an invisible element, so there's no visible focus indicator. Users won't know where they are on the page.

I will address it.

**Comment by wxiaoguang** [comment]
Some sound like AI hallucination. Unclear and/or unnecessary changes only make the situation worse.

**Comment by silverwind** [comment]
Cleaned it up in https://github.com/go-gitea/gitea/pull/36764/commits/5702b1e5a5968cf64bd6ea129909790f3707e178, no more nonsense `autofocus` attribute on textarea:

- `is_new_file` moved to `CodeEditorConfig` and now used for focus
- `CodeEditorConfig` is now set on the texarea instead of file name input
- Defaults for `CodeEditorConfig` are now completely set in backend
- Reverted git patch editor to tab indent like it had before
- `data-previewable-extensions` removed (in config only now)
- Docs added to CodeEditorConfig in frontend

File: routers/web/repo/editor_util.go [hunk 33]
```diff
@@ -67,6 +67,7 @@ func getClosestParentWithFiles(gitRepo *git.Repository, branchName, originTreePa
 
 // CodeEditorConfig is also used by frontend, defined in "codeeditor.ts"
 type CodeEditorConfig struct {
+	IsNewFile             bool     `json:"is_new_file"`
```
Comment (wxiaoguang) [inline routers/web/repo/editor_util.go]: `AutoFocus`

File: templates/repo/editor/common_breadcrumb.tmpl [hunk 34]
```diff
@@ -5,7 +5,7 @@
 	{{range $i, $v := .TreeNames}}
 		<div class="breadcrumb-divider">/</div>
 		{{if eq $i $l}}
-			<input id="file-name" maxlength="255" value="{{$v}}" placeholder="{{ctx.Locale.Tr (Iif $.PageIsUpload "repo.editor.add_subdir" "repo.editor.name_your_file")}}" data-code-editor-config="{{JsonUtils.EncodeToString $.CodeEditorConfig}}" {{Iif $.PageIsUpload "" "required"}} {{if $.IsNewFile}}autofocus{{end}}>
+			<input id="file-name" maxlength="255" value="{{$v}}" placeholder="{{ctx.Locale.Tr (Iif $.PageIsUpload "repo.editor.add_subdir" "repo.editor.name_your_file")}}" {{Iif $.PageIsUpload "" "required"}} {{if $.IsNewFile}}autofocus{{end}}>
```
Comment (wxiaoguang) [inline templates/repo/editor/common_breadcrumb.tmpl]: Remove `autofocus`

File: web_src/js/modules/codeeditor/main.ts [hunk 35]
```diff
@@ -250,15 +247,19 @@ function togglePreviewDisplay(previewable: boolean): void {
...
+  const previewableExts = new Set(editorOpts.previewable_extensions || []);
   const lineWrapExts = editorOpts.line_wrap_extensions || [];
 
   const editor = await createCodemirrorEditor(textarea, filename, editorOpts);
   setupEditorOptionListeners(textarea, editor);
 
+  // for new files, the autofocus will be on the filename input, for existing files focus the editor
+  if (editorOpts.is_new_file === false) {
+    editor.view.focus();
+  }
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/main.ts:305]:
```
if editorOpts.AutoFocus {
    editor.view.focus();
} else if opt.filenameInput {
    opt.filenameInput.focus();
}
```

File: web_src/js/modules/codeeditor/main.ts [hunk 36]
```diff
@@ -250,15 +247,19 @@ function togglePreviewDisplay(previewable: boolean): void {
...
+
+  const filenameInput = 'filenameInput' in opts ? opts.filenameInput : null;
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/main.ts]: Why

File: web_src/js/modules/codeeditor/main.ts [hunk 37]
```diff
@@ -0,0 +1,284 @@
...
+
+  // If not previewable but the "preview" tab was active (user changes the filename to a non-previewable one),
+  // then the "preview" tab becomes inactive (hidden), so the "write" tab should become active
+  if (previewTab.classList.contains('active')) {
+    const writeTab = document.querySelector<HTMLElement>('a[data-tab="write"]');
+    writeTab!.click();
+  }
+}
+
+export async function createCodeEditor(textarea: HTMLTextAreaElement, opts: {filenameInput: HTMLInputElement} | {defaultFilename: string}): Promise<CodemirrorEditor> {
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/main.ts]: Have you seen any well-designed APIs use such strange argument type, especially for "options"?

File: web_src/js/modules/codeeditor/main.ts (hunk 35 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts:305]: Hmm yeah this is cleaner.

File: web_src/js/modules/codeeditor/main.ts (hunk 36 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: I will eliminate this variable.

File: web_src/js/modules/codeeditor/main.ts (hunk 37 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: I will make it `(textarea, config)`

Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: Not so easy actually. We have 2 scenarios:

- File editor pass `filenameInput`
- Other scenarios pass `fileName` directly

The discriminated union is correct, but maybe it can be simplified.

File: routers/web/repo/editor_util.go (hunk 33 above)
Comment (silverwind) [reply routers/web/repo/editor_util.go]: https://github.com/go-gitea/gitea/pull/36764/commits/dce802f51eb2e9348e37d249a73fb763976e0db7

File: templates/repo/editor/common_breadcrumb.tmpl (hunk 34 above)
Comment (silverwind) [reply templates/repo/editor/common_breadcrumb.tmpl]: https://github.com/go-gitea/gitea/pull/36764/commits/dce802f51eb2e9348e37d249a73fb763976e0db7

File: web_src/js/modules/codeeditor/main.ts (hunk 35 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts:305]: https://github.com/go-gitea/gitea/pull/36764/commits/dce802f51eb2e9348e37d249a73fb763976e0db7

File: web_src/js/modules/codeeditor/main.ts (hunk 36 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: https://github.com/go-gitea/gitea/pull/36764/commits/dce802f51eb2e9348e37d249a73fb763976e0db7

File: web_src/js/modules/codeeditor/main.ts (hunk 37 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: adressed in https://github.com/go-gitea/gitea/pull/36764/changes/b092da726506277d249afbba08263b80b3b73e28.

File: routers/web/repo/editor_util.go [hunk 38]
```diff
@@ -67,25 +67,30 @@ func getClosestParentWithFiles(gitRepo *git.Repository, branchName, originTreePa
 
 // CodeEditorConfig is also used by frontend, defined in "codeeditor.ts"
 type CodeEditorConfig struct {
+	FilePath              string   `json:"file_path"`
```
Comment (wxiaoguang) [inline routers/web/repo/editor_util.go]: `FileBaseName`

File: web_src/js/modules/codeeditor/main.ts [hunk 39]
```diff
@@ -0,0 +1,284 @@
...
+    editor.view.focus();
+  } else if (filenameInput) {
+    filenameInput.focus();
+  }
+  if (filenameInput) {
+    togglePreviewDisplay(previewableExts.has(extname(filePath)));
+    filenameInput.addEventListener('input', onInputDebounce(async () => {
+      const newFilePath = filenameInput.value;
+      togglePreviewDisplay(previewableExts.has(extname(newFilePath)));
+      await updateEditorLanguage(editor, newFilePath, lineWrapExts);
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/main.ts]: `filenameInput` only has file base name, not "full file path"

File: web_src/js/modules/codeeditor/main.ts [hunk 40]
```diff
@@ -0,0 +1,284 @@
...
+    import(/* webpackChunkName: "codemirror" */ '@replit/codemirror-indentation-markers'),
+    import(/* webpackChunkName: "codemirror" */ '@replit/codemirror-vscode-keymap'),
+  ]);
+  return {view, state, search, language, commands, autocomplete, languageData, highlight, indentMarkers, vscodeKeymap};
+}
+
+async function createCodemirrorEditor(
+  textarea: HTMLTextAreaElement,
+  filePath: string,
+  config: CodeEditorConfig,
```
Comment (wxiaoguang) [inline web_src/js/modules/codeeditor/main.ts]: duplicate filePath

File: routers/web/repo/editor.go [hunk 41]
```diff
@@ -318,7 +318,10 @@ func EditFile(ctx *context.Context) {
 		}
 	}
 
-	ctx.Data["CodeEditorConfig"] = getCodeEditorConfig(ctx, ctx.Repo.TreePath)
+	editorConfig := getCodeEditorConfig(ctx, ctx.Repo.TreePath)
+	editorConfig.FilePath = ctx.Repo.TreePath
```
Comment (wxiaoguang) [inline routers/web/repo/editor.go]: `getCodeEditorConfig` already knows `ctx.Repo.TreePath`

File: routers/web/repo/editor_apply_patch.go [hunk 42]
```diff
@@ -20,7 +20,7 @@ func NewDiffPatch(ctx *context.Context) {
 	}
 
 	ctx.Data["PageIsPatch"] = true
-	ctx.Data["CodeEditorConfig"] = CodeEditorConfig{} // not really editing a file, so no need to fill in the config
+	ctx.Data["CodeEditorConfig"] = CodeEditorConfig{FilePath: "diff.patch", IndentStyle: "space"}
```
Comment (wxiaoguang) [inline routers/web/repo/editor_apply_patch.go]: `IndentStyle` ~~should default and~~ already defaults to `space`

Update: see https://github.com/go-gitea/gitea/pull/36764#issuecomment-3976518399

**Comment by wxiaoguang** [comment]
IIRC empty `IndentStyle` means "follow the content's style".

The editor should be able to detect which style is used by the provided source code.

File: routers/web/repo/editor_util.go (hunk 38 above)
Comment (silverwind) [reply routers/web/repo/editor_util.go]: No, it is actually a path, e.g. `repo.TreePath`, the name is correct.

File: web_src/js/modules/codeeditor/main.ts (hunk 39 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: Reworking this currently so we can eliminate the two `input` listeners.

File: routers/web/repo/editor_util.go (hunk 38 above)
Comment (wxiaoguang) [reply routers/web/repo/editor_util.go]: > No, it is actually a path, e.g. `repo.TreePath`, the name is correct.

No, passing  `repo.TreePath` is wrong. See below.

It should be FileBaseName and can only be it.

Comment (silverwind) [reply routers/web/repo/editor_util.go]: CodeMirror may need the full path to properly derive a mode, file name alone is not enough in all cases.

File: web_src/js/modules/codeeditor/main.ts (hunk 39 above)
Comment (wxiaoguang) [reply web_src/js/modules/codeeditor/main.ts]: > Reworking this currently so we can eliminate the two `input` listeners.

I only see "one" `input` listener here. Where is the other?

File: routers/web/repo/editor_util.go (hunk 38 above)
Comment (wxiaoguang) [reply routers/web/repo/editor_util.go]: If it required by CodeMirror, then more logic needs to be updated.

The proper field name could be `FileFullName` or `FullFilename`, to be clear. Or just keep `FilePath`

File: web_src/js/modules/codeeditor/main.ts (hunk 39 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: In repo-editor.ts

File: routers/web/repo/editor_util.go (hunk 38 above)
Comment (silverwind) [reply routers/web/repo/editor_util.go]: Actually, no CodeMirror only offers `matchFilename` which is designed for file names. I know that CodeMirror 5 also had an API to pass full paths, but apparently CodeMirror 6 does not anymore.

File: web_src/js/modules/codeeditor/main.ts (hunk 39 above)
Comment (wxiaoguang) [reply web_src/js/modules/codeeditor/main.ts]: > In repo-editor.ts

I don't think the one in repo-editor.ts is the one to be "eliminated". It is designed that way, unless you have a complete new design that matches the old functions.

File: routers/web/repo/editor_util.go (hunk 38 above)
Comment (wxiaoguang) [reply routers/web/repo/editor_util.go]: Decide by facts

File: web_src/js/modules/codeeditor/main.ts (hunk 39 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: My current idea is to expose a `updateFileName` from CodeEditor, to be called in that listener in repo-editor.

File: routers/web/repo/editor_util.go (hunk 38 above)
Comment (silverwind) [reply routers/web/repo/editor_util.go]: kept it to only filename in https://github.com/go-gitea/gitea/pull/36764/commits/b2b8d1fa648f517aaf3a25a2ca879e025d76bf07.

File: web_src/js/modules/codeeditor/main.ts (hunk 40 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: https://github.com/go-gitea/gitea/pull/36764/commits/b2b8d1fa648f517aaf3a25a2ca879e025d76bf07

File: routers/web/repo/editor.go (hunk 41 above)
Comment (silverwind) [reply routers/web/repo/editor.go]: https://github.com/go-gitea/gitea/pull/36764/commits/b2b8d1fa648f517aaf3a25a2ca879e025d76bf07

**Comment by silverwind** [comment]
> The editor should be able to detect which style is used by the provided source code.

Could do that with a custom function that detects the dominant indendation style in a file, codemirror does not have that.

File: routers/web/repo/editor_apply_patch.go (hunk 42 above)
Comment (silverwind) [reply routers/web/repo/editor_apply_patch.go]: It is redundant here, removed it.

File: web_src/js/features/repo-editor.ts [hunk 43]
```diff
@@ -63,6 +63,42 @@ export function initRepoEditor() {
     }
     document.querySelector<HTMLInputElement>('#tree_path')!.value = parts.join('/');
   }
+
+  const elForm = document.querySelector<HTMLFormElement>('.repository.editor .edit.form')!;
+
+  // on the upload page, there is no editor(textarea)
+  const editArea = document.querySelector<HTMLTextAreaElement>('.page-content.repository.editor textarea#edit_area');
+  if (!editArea) return;
```
Comment (wxiaoguang) [inline web_src/js/features/repo-editor.ts]: NO. It is wrong

image

File: web_src/js/modules/codeeditor/main.ts (hunk 39 above)
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: Implemented like that: https://github.com/go-gitea/gitea/pull/36764/commits/b2b8d1fa648f517aaf3a25a2ca879e025d76bf07

**Comment by wxiaoguang** [comment]
> > The editor should be able to detect which style is used by the provided source code.
> 
> Could do that with a custom function that detects the dominant indendation style in a file, codemirror does not have that.

Not in this PR's scope. Just leave all IndentStyle to empty by default.

File: web_src/js/features/repo-editor.ts (hunk 43 above)
Comment (silverwind) [reply web_src/js/features/repo-editor.ts]: It's just moved code, I didn't touch it.

Comment (wxiaoguang) [reply web_src/js/features/repo-editor.ts]: You skipped the logic in the screenshot

You can't move it

Comment (wxiaoguang) [reply web_src/js/features/repo-editor.ts]: Upload page does NOT have textarea, but it does NEED the filename input

Comment (silverwind) [reply web_src/js/features/repo-editor.ts]: Ok, I will fix that and refactor a bit more (because of the current type errors)

Comment (silverwind) [reply web_src/js/features/repo-editor.ts]: fixed https://github.com/go-gitea/gitea/pull/36764/changes/6e95b4942a8326a7c846f6b4a0054f1ab2963719.

**Comment by silverwind** [comment]
All done, I refactored into one `createCodeEditor` function instead of two previously, simpler and no type problems.

**Review by wxiaoguang — DISMISSED** [review]
Not fixed at all. https://github.com/go-gitea/gitea/pull/36764#discussion_r2867156819

Really tired of reviewing AI code

image

**Comment by wxiaoguang** [comment]
Leave for some time. Anyone who has tested and reviewed, feel free to dismiss my change request.

**Comment by silverwind** [comment]
I have no idea what you want to show me with such screenshots.

**Comment by wxiaoguang** [comment]
image

**Comment by silverwind** [comment]
Fully fixed in https://github.com/go-gitea/gitea/pull/36764/commits/04b4e6e0db754f29f33e5f83e493a140a352ba56, `filenameInput` listener runs again on upload page and I verified file upload.

File: web_src/js/features/repo-editor.ts [hunk 44]
```diff
@@ -63,6 +63,7 @@ export function initRepoEditor() {
     }
     document.querySelector<HTMLInputElement>('#tree_path')!.value = parts.join('/');
   }
+
```
Comment (silverwind) [inline web_src/js/features/repo-editor.ts]:
```suggestion
```

**Comment by silverwind** [comment]
I reverted the `repo-editor.ts` changes because the original goal of removing the two `input` listeners was not achieved.

**Comment by bircni** [comment]
Codex found these 2:

1. **[P1] Async race when filename changes can apply the wrong language mode**
   - Files: `web_src/js/features/repo-editor.ts:173-175`, `web_src/js/modules/codeeditor/main.ts:193-196`, `web_src/js/modules/codeeditor/main.ts:254-265`
   - `filenameInput` now triggers `editor.updateFilename(...)` on every input event, and `updateFilename` awaits async language loading. If multiple calls overlap, an older request can finish after a newer one and reconfigure the editor to a stale language/wrap mode.
   - Suggestion: guard with a monotonically increasing request id (or cancellation token) and only apply the latest result.

2. **[P2] Ctrl/Cmd-click URL opening should avoid `window.opener` exposure**
   - File: `web_src/js/modules/codeeditor/utils.ts:70`
   - Current code uses `window.open(url)`, which can expose `window.opener` to the opened page.
   - Suggestion: open with `noopener`/`noreferrer` (for example: `window.open(url, '_blank', 'noopener,noreferrer')`).

**Comment by silverwind** [comment]
1. Might be valid
2. Initial implementation had `noopener`, but it was removed on request. I guess I need to re-investigate the dangers of `opener`.

**Comment by silverwind** [comment]
Adressed both. MDN is pretty clear about "noopener" being needed:

https://developer.mozilla.org/en-US/docs/Web/API/Window/open#noopener

> If this feature is set, the new window will not have access to the originating window via [Window.opener](https://developer.mozilla.org/en-US/docs/Web/API/Window/opener) and returns null.

**Comment by wxiaoguang** [comment]
> Adressed both. MDN is pretty clear about "noopener" being needed:
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Window/open#noopener
> 
> > If this feature is set, the new window will not have access to the originating window via [Window.opener](https://developer.mozilla.org/en-US/docs/Web/API/Window/opener) and returns null.

It's not needed. `_blank` already means "noopener" by "browsing context", although it is not wrong

> are treated like _blank in terms of deciding whether to open a new browsing context.

So if keeping it makes people and AI feel good, then keep it.

File: web_src/js/features/repo-editor.ts [hunk 45]
```diff
@@ -170,16 +171,24 @@ export function initRepoEditor() {
 
   (async () => {
     const editor = await createCodeEditor(editArea, filenameInput);
+    filenameInput.addEventListener('input', debounce(300, () => {
```
Comment (wxiaoguang) [inline web_src/js/features/repo-editor.ts]: AI won't learn the designed library or framework: onInputDebounce

Old code also used onInputDebounce

File: routers/web/repo/editor_util.go [hunk 46]
```diff
@@ -67,25 +67,30 @@ func getClosestParentWithFiles(gitRepo *git.Repository, branchName, originTreePa
...
 
 	IndentStyle            string `json:"indent_style"`
 	IndentSize             int    `json:"indent_size"`
 	TabWidth               int    `json:"tab_width"`
 	TrimTrailingWhitespace *bool  `json:"trim_trailing_whitespace,omitempty"`
 }
 
-func getCodeEditorConfig(ctx *context_service.Context, treePath string) (ret CodeEditorConfig) {
+func getCodeEditorConfig(ctx *context_service.Context, treePath string) CodeEditorConfig {
+	ret := CodeEditorConfig{FileName: path.Base(treePath), IndentStyle: "space"}
```
Comment (wxiaoguang) [inline routers/web/repo/editor_util.go]: `IndentStyle` should default to empty

**Comment by silverwind** [comment]
> It's not needed. _blank already means "noopener" by "browsing context", although it is not wrong

I'd keep it, better be explicit and not introduce a security vulnerability.

File: web_src/js/features/repo-editor.ts (hunk 45 above)
Comment (silverwind) [reply web_src/js/features/repo-editor.ts]: Yeah sorry, I prompted "add debounce" and it took that too literal.

**Comment by wxiaoguang** [comment]
> > It's not needed. _blank already means "noopener" by "browsing context", although it is not wrong
> 
> I'd keep it, better be explicit and not introduce a security vulnerability.

It's fine to keep it, while it's also fine to trust modern browsers.

**Comment by wxiaoguang** [comment]
What do you think about the new changes

**Comment by silverwind** [comment]
Seems fine, the struct names were originally modeled after editorconfig props which do feature underscores, but I guess camelcase is more consistent and those props not only hold editorconfig values any more.

**Comment by wxiaoguang** [comment]
That's why I introduced the "CodeEditorConfig", it simplifies the code a lot, and make us able to fully control all the details.

**Comment by silverwind** [comment]
Some more minor tweaks:

- Set placeholder via native textarea `placeholder` attribute
- When F5'ing a page with an editor, a unsaved warning shows but the content was still preserved through browser's form data preservation. This was unexpected because it's useful to F5 to discard edits which now works.
- Cleaned up git hooks editor layout:

  image

**Review by wxiaoguang — DISMISSED** [review]

**Comment by lunny** [comment]
> While editor fixes on mobile and size reduction is nice, imho priority for editor is on desktop and monaco editor is way superior and supports more features, so I think it's step back :/

Is there still any feature step back? Maybe we should update the content to mention them.

**Comment by silverwind** [comment]
The only feature that could be considered missing is tooltips and go-to-definition that Monaco had, but these feature were half-baked in Monaco and only worked in the current file. Normally in VSCode, Monaco is backed by an LSP (tsserver or gopls for example) which makes these feature work cross-file.

Other than that, everything including VSCode shortcuts and command palette is there.

Tooltips and go-to-definition can be added later but it will likely require building LSP servers as WASM modules. The client side LSP [already exists](https://github.com/codemirror/lsp-client).

**Comment by silverwind** [comment]
One topic still worth checking out is https://github.com/codemirror/lint, it should be possible to get basic syntax linting in languages like JSON or YAML and Monaco did have that. I will check it out.

**Comment by silverwind** [comment]
Linting added. It's supported for these languages:

C, C++, CQL, CSS, Go, HTML, Java, JavaScript, JSX, JSON, Jinja, LESS, Liquid, Markdown, PHP, Python, Rust, Sass, SCSS, SQL, MariaDB SQL, MS SQL, MySQL, PLSQL, PostgreSQL, SQLite, TSX, TypeScript, Vue, Angular Template, WebAssembly, XML, YAML, Elixir, Nix, Svelte.

image

At the bottom is the linter panel, it's not visible by default but can be toggled with CTRL-Shift-M.

Also did some misc fixes to cursor and line-height.

**Comment by silverwind** [comment]
Here's the main missing features:

- go-to-definition
- hover types
- semantic rename

All of them need a LSP server, but all of them were also half-baked in Monaco because of missing multi-file support.

**Comment by lunny** [comment]
> Here's the main missing features:
> 
> * go-to-definition
> * hover types
> * semantic rename
> 
> All of them need a LSP server, but all of them were also half-baked in Monaco because of missing multi-file support.

Please update the pull request description.

**Comment by TheFox0x7** [comment]
> All of them need a LSP server

Is the plan here to embed LSP servers in gitea or...? Because from what I skimmed though here it's a recurring idea.

**Comment by silverwind** [comment]
added

**Comment by silverwind** [comment]
> Is the plan here to embed LSP servers in gitea or...? Because from what I skimmed though here it's a recurring idea.

It'd be nice to have, but these are all language-specific and besides gopls, none of them are written in go so can not be easily embedded. I think embedding LSPs with WASM might be possible in the future, but it's never been done yet to my knowledge.

Monaco also only had 4 LSPs (or rather, workers) shipped with it:

- TypeScript/JavaScript
- CSS/LESS/SCSS
- HTML
- JSON

All other languages in Monaco also didn't have any of these features.

**Comment by lunny** [comment]
> > All of them need a LSP server
> 
> Is the plan here to embed LSP servers in gitea or...? Because from what I skimmed though here it's a recurring idea.

I think it's almost impossible inside the Gitea itself.

**Review by lunny — DISMISSED** [review]

**Comment by lunny** [comment]
The editor syntax highlight are very different. I personally like the previous version.
Before:

image

After:

image

**Comment by silverwind** [comment]
Fenced code block highlight in markdown can probably be fixed by configuring the markdown mode correctly.

Color could be tuned a bit. I too don't like some of the color choices, but at least it's now using the same colors as the code rendering.

**Comment by wxiaoguang** [comment]
Made a mistake when dismiss my review (too many changes).

Feel free to approve @lunny

**Comment by silverwind** [comment]
Syntax higlighting colors are now much closer to Chroma color. I had to add a few language-specific overrides for JSON, YAML etc because these parsers identify tokens differently. I reviewed the top 30 languaguages for maximum compatibility.

Higlight in markdown fences also works now:

image

**Comment by lunny** [comment]
```log
Render failed, failed to render template: repo/editor/edit, error: template error: builtin(static):repo/editor/options:3:16 : executing "repo/editor/options" at <$.CodeEditorConfig.LineWrap>: can't evaluate field LineWrap in type interface {}
----------------------------------------------------------------------
{{$lineWrap := $.CodeEditorConfig.LineWrap}}
                ^
----------------------------------------------------------------------
```

**Comment by lunny** [comment]
It's still unlucky for me.

image

**Comment by silverwind** [comment]
What are you expecting there?

**Comment by lunny** [comment]
> What are you expecting there?

Wouldn't that should look like below?

image

**Comment by silverwind** [comment]
You mean the red heading color? Blue on light theme might be what is currently mapped, I will test light theme more. But besides that I can't see anything wrong in your screenshot.

**Comment by lunny** [comment]
> You mean the red heading color? Blue on light theme might be what is currently mapped, I will test light theme more. But besides that I can't see anything wrong in your screenshot.

Yes. I'm using light theme that's why my screenshot is different from yours.

**Comment by silverwind** [comment]
One thing I do know is that light and dark theme don't have the same token-to-color mapping, e.g. something red on dark could be blue on light.

Maybe it's time to design a single syntax theme that usethe same color hues just with different lightness on light and dark. There's certainly a few things I would want to change, like giving comments more contrast in diffs.

I guess I would model the new "unified" theme based on the current dark theme, with a few tweaks. Maybe take a bit of influence from GitHub's theme, but don't copy it exactly.

**Comment by lunny** [comment]
> The editor syntax highlight are very different. I personally like the previous version. Before:
> 
> image
> After:
> 
> image

But monaco in light theme have a better highlight for markdown

**Comment by silverwind** [comment]
> But monaco in light theme have a better highlight for markdown

Yes, some syntaxes are not as good as in Monaco, not something I can change, it needs to be contributed to https://github.com/lezer-parser/markdown. GitHub is in the same boat as they also use CodeMirror.

Colors I can fix, but not actual missing/bad syntax tokenization. I would help if you can show some documents that need improvement.

File: web_src/js/utils.ts [hunk 47]
```diff
@@ -27,6 +27,14 @@ export function isObject<T = Record<string, any>>(obj: any): obj is T {
   return Object.prototype.toString.call(obj) === '[object Object]';
 }
 
+/** Whether the current platform is macOS or iOS. */
+export const isMac = /Mac/i.test(navigator.userAgent);
+
+/** Platform-aware display symbols for keyboard modifier and special keys. */
+export const keySymbols: Record<string, string> = isMac ?
+  {Mod: '⌘', Alt: '⌥', Shift: '⇧', Ctrl: '⌃', Up: '↑', Down: '↓', Enter: '⏎'} :
+  {Mod: 'Ctrl', Shift: 'Shift', Alt: 'Alt', Up: '↑', Down: '↓', Enter: '⏎'};
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/utils.ts:36]: iPhone UA includes `like Mac OS X`, so this works.

[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/utils.ts:36]: *This comment was written by Claude.*

Declined — `/Mac/i` already covers the vast majority of use cases. iOS with external keyboard is an edge case that doesn't warrant the added complexity.

File: web_src/js/modules/codeeditor/utils.ts [hunk 48]
```diff
@@ -0,0 +1,100 @@
...
+/** Matches URLs, excluding characters that are never valid unencoded in URLs per RFC 3986. */
+export const urlRawRegex = /\bhttps?:\/\/[^\s<>[\]]+/gi;
+
+/** Strip trailing punctuation that is likely not part of the URL. */
+export function trimUrlPunctuation(url: string): string {
+  url = url.replace(/[.,;:'"]+$/, '');
+  // Strip trailing closing parens only if unbalanced (not part of the URL like Wikipedia links)
+  while (url.endsWith(')') && (url.match(/\(/g) || []).length < (url.match(/\)/g) || []).length) {
+    url = url.slice(0, -1);
+  }
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/modules/codeeditor/utils.ts:27]: *This comment was written by Claude.*

Declined — stripping trailing `'` is the correct heuristic. URLs rarely end in `'` but text commonly wraps URLs in single quotes like `'https://example.com'`.

File: web_src/js/modules/codeeditor/utils.ts [hunk 49]
```diff
@@ -0,0 +1,100 @@
...
+  return url;
+}
+
+/** Find the URL at the given character position in a document string, or null if none. */
+export function findUrlAtPosition(doc: string, pos: number): string | null {
+  for (const match of doc.matchAll(urlRawRegex)) {
+    const url = trimUrlPunctuation(match[0]);
+    if (match.index !== undefined && pos >= match.index && pos <= match.index + url.length) {
+      return url;
+    }
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/modules/codeeditor/utils.ts:37]: *This comment was written by Claude.*

Fixed in 86e10aa018 — changed to end-exclusive matching (`<` instead of `<=`).

File: web_src/js/modules/codeeditor/utils.test.ts [hunk 50]
```diff
@@ -0,0 +1,33 @@
...
+});
+
+test('findUrlAtPosition', () => {
+  const doc = 'visit https://example.com for info';
+  expect(findUrlAtPosition(doc, 0)).toBeNull();
+  expect(findUrlAtPosition(doc, 6)).toEqual('https://example.com');
+  expect(findUrlAtPosition(doc, 15)).toEqual('https://example.com');
+  expect(findUrlAtPosition(doc, 25)).toEqual('https://example.com');
+  expect(findUrlAtPosition(doc, 26)).toBeNull();
+});
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/modules/codeeditor/utils.test.ts:47]: *This comment was written by Claude.*

Fixed in 86e10aa018 — updated test to expect `null` at position 25 (end-exclusive). Also added direct `trimUrlPunctuation` tests.

File: web_src/js/modules/codeeditor/main.ts [hunk 51]
```diff
@@ -0,0 +1,303 @@
...
+
+  const newLanguage = cm.language.LanguageDescription.matchFilename(editorLanguages, filename);
+  view.dom.closest('.code-editor-container')!.setAttribute('data-language', newLanguage?.name.toLowerCase() || '');
+  view.dispatch(
+    {
+      effects: [
+        compartments.wordWrap.reconfigure(
+          lineWrapExts.includes(extname(filename)) ? cm.view.EditorView.lineWrapping : [],
+        ),
+        compartments.language.reconfigure(newLanguage ? await newLanguage.load() : []),
```
[the remark this answers is not in the document]
Comment (silverwind) [reply web_src/js/modules/codeeditor/main.ts]: *This comment was written by Claude.*

Fixed in 86e10aa018 — lowercased the extension before the `lineWrapExts.includes()` check.

File: routers/web/repo/editor.go [hunk 52]
```diff
@@ -319,7 +319,9 @@ func EditFile(ctx *context.Context) {
 		}
 	}
 
-	ctx.Data["CodeEditorConfig"] = getCodeEditorConfig(ctx, ctx.Repo.TreePath)
+	editorConfig := getCodeEditorConfigByEditorconfig(ctx, ctx.Repo.TreePath)
```
[the remark this answers is not in the document]
Comment (silverwind) [reply routers/web/repo/editor.go:322]: *This comment was written by Claude.*

Fixed in 86e10aa018 — clearing `editorConfig.Filename` when `isNewFile` so the directory basename isn't used for language detection.

**Comment by silverwind** [comment]
Implemented a Monaco-like context menu:

image

Besides color refactor, this is ready.

**Comment by silverwind** [comment]
Color unification done. Now light and dark use the same hue for all colors, just different lightness. Color scheme is roughtly based on dark theme, but did a number of tweaks. All colors pass WCAG AA.

Screenshot 2026-03-30 at 19 55 27
Screenshot 2026-03-30 at 19 55 01

Screenshot 2026-03-30 at 19 55 19
Screenshot 2026-03-30 at 19 55 09


Another notable change is that text in diff word highlights now uses monochrome text color, which ensures there can be no contrast problems any more.

Screenshot 2026-03-30 at 19 57 59
Screenshot 2026-03-30 at 19 57 44

**Comment by bircni** [comment]
When you're ready feel free to tag me

**Comment by silverwind** [comment]
It is ready for review. All monaco feature besides hover tooltips are implemented. Besides a few small tweaks, I don't expect any more major changes.

**Comment by bircni** [comment]
Could you update the description? it still states webpack

**Comment by lunny** [comment]
Could we disable the collapses? I think they’re always bothering me.

image

**Comment by silverwind** [comment]
> Could you update the description? it still states webpack

I will benchmark size and speed again later.

> Could we disable the collapses? I think they’re always bothering me.

Yes the fold chevrons are a bit visually distracting. I will probably make them only show when cursor hovers over that column, like in VSCode.

**Comment by silverwind** [comment]
All done:

- Fold chevrons only show on hover like in VSCode
- Fixed a rendering bug in chevrons
- Made editor loading sequence stable without content shifts
- Extracted a CSS variable for the selection color and made in brighter on dark

**Comment by bircni** [comment]
**Code review for #36764** *(by Claude Sonnet 4.6)*

**Issues to address before merging:**

- **Scoped DOM queries** — `document.querySelector('a[data-tab="preview"]')` and similar selectors (already FIXMEd) should be scoped to the editor container to avoid matching unrelated elements when multiple editors exist
- **Clipboard error handling** — `navigator.clipboard.readText()` can throw on permission denial; wrap in `try/catch`
- **Non-null assertions** — `querySelector('.js-code-find')!` will throw if the element is absent; verify these are truly guaranteed or add guards
- **JSONC detection** — `/(tsconfig|devcontainer|jsconfig)/i` is a fragile hardcoded list; will need ongoing maintenance
- **CSS missing fallbacks** — `var(--color-syntax-link)` etc. have no fallback values; elements become invisible if a theme doesn't define them
- **Brittle CSS selectors** — `.cm-panel.cm-search br + *` will silently break if CodeMirror changes its DOM structure upstream
- **Test coverage** — the single e2e test only checks textarea sync; command palette, language detection, keybindings, and indent/wrap toggles are untested

**Minor:**
- `MenuItem` union type: prefer `{type: 'separator'} | {type: 'item', ...}` over `{...} | 'separator'`
- Hard-coded `z-index: 301` on `.cm-command-palette` needs coordination with other modals
- Config assembly split between `editor_util.go` and `editor.go` (`Autofocus`, `Filename` set separately) — consolidate in one place

**Comment by silverwind** [comment]
> **Scoped DOM queries** — `document.querySelector('a[data-tab="preview"]')` and similar selectors (already FIXMEd) should be scoped to the editor container to avoid matching unrelated elements when multiple editors exist

There's only one editor per page currently. The FIXME is already there acknowledging this needs a broader refactor.

> **Clipboard error handling** — `navigator.clipboard.readText()` can throw on permission denial; wrap in `try/catch`

Fixed in 5bbf06996f.

> **Non-null assertions** — `querySelector('.js-code-find')!` will throw if the element is absent; verify these are truly guaranteed or add guards

These are inside an `if (elEditorOptions)` guard. The child elements are guaranteed by the template when the parent exists. Using `!` over `?.` is the project convention.

> **JSONC detection** — `/(tsconfig|devcontainer|jsconfig)/i` is a fragile hardcoded list; will need ongoing maintenance

This is the same approach VSCode takes. These are the well-known JSONC filenames. The regex is easy to extend if needed.

> **CSS missing fallbacks** — `var(--color-syntax-link)` etc. have no fallback values; elements become invisible if a theme doesn't define them

Both themes always define all variables. Custom themes inherit from the default themes. Fallback values would be dead code.

> **Brittle CSS selectors** — `.cm-panel.cm-search br + *` will silently break if CodeMirror changes its DOM structure upstream

Inherent to styling CodeMirror internals. These selectors are pinned to the current CodeMirror version and would be reviewed on upgrades.

> **Test coverage** — the single e2e test only checks textarea sync; command palette, language detection, keybindings, and indent/wrap toggles are untested

Valid, but a separate effort. More e2e tests can be added incrementally.

> `MenuItem` union type: prefer `{type: 'separator'} | {type: 'item', ...}` over `{...} | 'separator'`

The current form is more concise and the `=== 'separator'` check reads naturally.

> Hard-coded `z-index: 301` on `.cm-command-palette` needs coordination with other modals

It's positioned above CodeMirror's internal z-indexes (which go up to 300) and below Gitea's modal overlays. Works correctly.

> Config assembly split between `editor_util.go` and `editor.go` (`Autofocus`, `Filename` set separately) — consolidate in one place

Intentional: `editor_util.go` builds the shared config from `.editorconfig`, while `editor.go` adds route-specific overrides like `Autofocus` and `Filename` which depend on request context.

---
*This comment was written by Claude Opus 4.6.*

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/36764#issue-3996210560 is updated and includes a table of build size and performance.

**Review by bircni — APPROVED** [review]

**Review by lunny — APPROVED** [review]
