### PR TITLE
Delete unreferenced packages when deleting a package version (#20977)

### LINKED ISSUE #20969: Deleted all packages, still failed to delete the account
### Description

> error: Your account owns one or more packages; delete them first.

Gitea asked me to delete the package before deleting my account, and even if I did, it didn't work as it should.

I can reproduce the problem on try.gitea.io

### Gitea Version

1.18.0+dev-346-g94549bcd1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

https://user-images.githubusercontent.com/76462613/187001055-eba43c55-0eb4-4cf2-9c2d-41c5f3f93b18.mp4

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

https://try.gitea.io/

### Database

_No response_

### PR DESCRIPTION
**Pull request by zeripath**
Backport #20977

Delete a package if its last version got deleted. Otherwise removing the owner works only after the clean up job ran.

Fix #20969

### CODE REVIEW

File: models/packages/package_test.go [hunk 1]
```diff
@@ -0,0 +1,69 @@
+// Copyright 2022 The Gitea Authors. All rights reserved.
```
Comment (delvh) [inline models/packages/package_test.go:1]: We backport tests?

**Review by delvh — APPROVED** [review]

File: models/packages/package_test.go (hunk 1 above)
Comment (lunny) [reply models/packages/package_test.go:1]: we can

**Review by lunny — APPROVED** [review]

File: models/packages/package_test.go (hunk 1 above)
Comment (zeripath) [reply models/packages/package_test.go:1]: it's a good idea to do so!
