### PR TITLE
Fix SSH auth lfs locks

### LINKED ISSUE #3084: Git LFS Lock: credential issue when using SSH
- Gitea version (or commit ref): master (c0a7899416af728634b2dc52a27b31255285ae7e)
- Git version: 2.11.0
- Operating system: Ubuntu 17.06 / Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes, but it is not exactly the same bug... https://try.gitea.io/testzzx464c/lfs-lock-test
  - [ ] No
  - [ ] Not relevant

## Description

Hello,

I am testing the new git LFS lock feature and I have some issues.

When I try it on my own machine and server, I have the following error:

```
$ git push
Username for 'http://localhost:3000': test
Password for 'http://test@localhost:3000': 
WARNING: Authentication error: Authentication required: You must have push access to verify locks : User undefined doesn't have rigth to verify for lfs lock [rid: 1]
[...]

$ git lfs locks
Error while retrieving locks: You must have pull access to list locks : User undefined doesn't have rigth to list for lfs lock [rid: 1]
```

When I try on try.gitea.io, I have no error on push but I cannot get lock info:

```
$ git lfs lock foo.yy 
Lock failed: Repository or object not found: https://try.gitea.io/testzzx464c/lfs-lock-test.git/info/lfs/locks
Check that it exists and that you have proper access to it
```

I am probably doing it wrong, if someone can tell me where... :)

cc @sapk

### PR DESCRIPTION
**Pull request by sapk**
Mostly don't reinvent the wheel to fix #3084 by re-using func of lfs.

### CODE REVIEW

**Comment by sapk** [comment]
I extract a function parseToken of original authenticateToken and add user reference to token claim to be able to fill ctx.User if needed for creating or deleting locks.

**Comment by lafriks** [comment]
LGTM

**Comment by flozz** [comment]
The authentication seems to work for the lock feature, but I am not able to push LFS object anymore:

```
$ git lfs push origin master
Git LFS: (0 of 1 files) 0 B / 8 B                                                                        
batch response: Fatal error: Server error: http://git2.XXX.YYY/ZZZ/test-lfs.git/info/lfs/objects/batch

Errors logged to /tmp/test-lfs/.git/lfs/objects/logs/20171212T112833.900447349.log
Use `git lfs logs last` to view the log.
```

From gitea log:

```
Dec 12 11:28:33 XXX gitea[44851]: [Macaron] 2017-12-12 11:28:33: Completed POST /ZZZ/test-lfs.git/info/lfs/objects/batch 500 Internal Server Error in 1.880036ms
```

**Review by lafriks — CHANGES_REQUESTED** [review]
See comment above :)

**Comment by sapk** [comment]
@flozz thanks for the testing. Will look at it

File: models/lfs_lock.go [hunk 1]
```diff
@@ -16,23 +16,26 @@ import (
...
 func (l *LFSLock) BeforeInsert() {
 	l.OwnerID = l.Owner.ID
+	l.RepoID = l.Repo.ID
 	l.Path = cleanPath(l.Path)
 }
 
 // AfterLoad is invoked from XORM after setting the values of all fields of this object.
 func (l *LFSLock) AfterLoad() {
 	l.Owner, _ = GetUserByID(l.OwnerID)
+	l.Repo, _ = GetRepositoryByID(l.RepoID)
```
Comment (ethantkoenig) [inline models/lfs_lock.go]: Two thoughts:
1. We shouldn't ignore errors here; we should at least log them.
2. We should double-check that loading the `Owner` and `Repo` every time we read from the database is necessary. IMO, it seems a bit wasteful

File: models/lfs_lock.go [hunk 2]
```diff
@@ -71,15 +74,15 @@ func CreateLFSLock(lock *LFSLock) (*LFSLock, error) {
 }
 
 // GetLFSLock returns release by given path.
-func GetLFSLock(repoID int64, path string) (*LFSLock, error) {
+func GetLFSLock(repo *Repository, path string) (*LFSLock, error) {
```
Comment (ethantkoenig) [inline models/lfs_lock.go:86]: Why this change? Is it really worth passing the repository if the only thing we care about it the id?

File: modules/lfs/locks.go [hunk 3]
```diff
@@ -13,19 +13,25 @@ import (
 	"code.gitea.io/gitea/modules/context"
 	"code.gitea.io/gitea/modules/setting"
 	api "code.gitea.io/sdk/gitea"
-
-	"gopkg.in/macaron.v1"
 )
 
-func checkRequest(req macaron.Request, post bool) int {
+func checkRequest(ctx *context.Context, post bool) int {
```
Comment (ethantkoenig) [inline modules/lfs/locks.go]: Would it be cleaner to write responses to `ctx`, instead of returning the response status? Right now, the person calling this function needs to know that 200 is a special return value (which isn't documented anywhere)

File: models/lfs_lock.go [hunk 4]
```diff
@@ -123,24 +126,20 @@ func DeleteLFSLockByID(id int64, u *User, force bool) (*LFSLock, error) {
 }
 
 //CheckLFSAccessForRepo check needed access mode base on action
-func CheckLFSAccessForRepo(u *User, repoID int64, action string) error {
+func CheckLFSAccessForRepo(u *User, repo *Repository, reqWrt bool) error {
```
Comment (ethantkoenig) [inline models/lfs_lock.go]: Maybe it's cleaner to pass the AccessMode directly, instead of a bool?

**Review by ethantkoenig — CHANGES_REQUESTED** [review]

File: models/lfs_lock.go (hunk 1 above)
Comment (sapk) [reply models/lfs_lock.go]: I added repo during dev because I needed it at one time but this could be revert to only use repoID if it to much additional workload.

File: models/lfs_lock.go (hunk 2 above)
Comment (sapk) [reply models/lfs_lock.go:86]: Now I remember it is to use HasAccess that need a repo reference.

Comment (sapk) [reply models/lfs_lock.go:86]: Maybe I could make a func accessLevel and hasAccess that use repoID more generally for better perf ? (I think in a other PR ?)

Comment (ethantkoenig) [reply models/lfs_lock.go:86]: Ah, I must have missed the call to `CheckLFSAccessForRepo`. Yes, perhaps in another PR

Comment (sapk) [reply models/lfs_lock.go:86]: In fact after reviewing code of accessLevel, it use repo.IsPrivate that need a repo reference so.

File: integrations/pgsql.ini.tmpl [hunk 5]
```diff
@@ -26,7 +26,8 @@ SSH_DOMAIN       = localhost
 HTTP_PORT        = 3002
 ROOT_URL         = http://localhost:3002/
 DISABLE_SSH      = false
-SSH_PORT         = 22
+SSH_LISTEN_HOST  = localhost
+SSH_PORT         = 2222
```
Comment (lafriks) [inline integrations/pgsql.ini.tmpl]: Do not use same port for multiple database tests as they are run in parallel

**Review by lafriks — CHANGES_REQUESTED** [review]

File: integrations/pgsql.ini.tmpl (hunk 5 above)
Comment (sapk) [reply integrations/pgsql.ini.tmpl]: Good catch

**Comment by lafriks** [comment]
seems that ssh port change requires update in tests

File: models/lfs_lock.go [hunk 6]
```diff
@@ -12,27 +12,38 @@ import (
 	"time"
 
 	api "code.gitea.io/sdk/gitea"
+	"github.com/ngaut/log"
```
Comment (ethantkoenig) [inline models/lfs_lock.go]: import format: see https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md#styleguide

**Review by ethantkoenig — CHANGES_REQUESTED** [review]

File: models/lfs_lock.go (hunk 6 above)
Comment (sapk) [reply models/lfs_lock.go]: @ethantkoenig sorry I pass it as WIP seen I want to setup test for various git access to make that I don't break anything in future. It is my editor that setup this import, I will review my code once it works and remove WIP when ready. Sorry for the distrurb.

Comment (sapk) [reply models/lfs_lock.go]: Fixed.

**Comment by sapk** [comment]
@flozz can you re-test? It should be good now

File: modules/lfs/locks.go (hunk 3 above)
Comment (sapk) [reply modules/lfs/locks.go]: I have wrote the method.

**Comment by sapk** [comment]
Ok found my mistake in 2723ca5d82dee097e8fa4c0080a5492ec0bb44b8
This PR add integration test from git cli for http and ssh url for normal clone/commit but also lfs file and lfs lock.

**Comment by sapk** [comment]
The two last commit are to fix an other bug found by new tests. It try to write key file even when using internal ssh server.

**Comment by sapk** [comment]
Ok now I have to find why it passed tests on mysql and sqlite but not on pgsql ...

**Comment by flozz** [comment]
@sapk I made some tests, everything seems to work! :)

**Comment by sapk** [comment]
@flozz Thanks for the tests, I suspect that you don't use pgsql for the database ? 

I will try to take time to look at why lfs (lock and batch) don't seems to work with it in the specific case of clone via ssh (and if it was working before). 
But overall it's good to review (except the last commit that add -test.v for debug) so friendly ping to @lafriks and @ethantkoenig.

And if anyone as an idea for pgsql, I will gladly take it ^^.

File: Makefile [hunk 7]
```diff
@@ -159,7 +159,7 @@ test-vendor:
 
 .PHONY: test-sqlite
 test-sqlite: integrations.sqlite.test
-	GITEA_ROOT=${CURDIR} GITEA_CONF=integrations/sqlite.ini ./integrations.sqlite.test
+	GITEA_ROOT=${CURDIR} GITEA_CONF=integrations/sqlite.ini ./integrations.sqlite.test -test.v
```
Comment (sapk) [inline Makefile]: Tempory debug for having insigth of what happen inside drone tests

**Comment by flozz** [comment]
@sapk You are right, I use sqlite on my test server

**Comment by sapk** [comment]
All is working now. What fix pgsql tests should be inside #3377 or #3346.

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
@ethantkoenig need your approval

**Comment by lafriks** [comment]
@ethantkoenig we need to release 1.4.0 soon, can you please review this?

**Review by ethantkoenig — APPROVED** [review]
Apologies for delay

File: models/lfs_lock.go [hunk 8]
```diff
@@ -11,28 +11,39 @@ import (
...
 	l.OwnerID = l.Owner.ID
+	l.RepoID = l.Repo.ID
 	l.Path = cleanPath(l.Path)
 }
 
 // AfterLoad is invoked from XORM after setting the values of all fields of this object.
 func (l *LFSLock) AfterLoad() {
-	l.Owner, _ = GetUserByID(l.OwnerID)
+	var err error
+	l.Owner, err = GetUserByID(l.OwnerID)
```
Comment (ethantkoenig) [inline models/lfs_lock.go]: Will performing database queries inside `AfterLoad` lead to deadlock problems if the query that triggered `AfterLoad` is part of a transaction? See #1813

Comment (lafriks) [reply models/lfs_lock.go]: @ethantkoenig queries should not be affected by locking and will load last committed data even if update/insert is in progress

Comment (ethantkoenig) [reply models/lfs_lock.go]: I see. In #1813 the offending SQL was a write which blocked on an ongoing transaction, but if you're sure that reading won't block on ongoing transactions then this is okay.

Comment (lunny) [reply models/lfs_lock.go]: You should use
```Go
func (l *LFSLock) AfterLoad(sess *xorm.Session) {

}
```
to avoid that.

**Review by lunny — CHANGES_REQUESTED** [review]
Please follow my suggestion.

**Comment by lafriks** [comment]
@lunny need your approval

**Review by lunny — APPROVED** [review]
