### PR TITLE
[API] Fix inconsistent label color format

### LINKED ISSUE #10127: [API] Inconsistent Label Format
discoverd on gitea version: 1.10.3

https://try.gitea.io/api/swagger#/issue/issueListLabels
https://try.gitea.io/api/swagger#/issue/issueCreateLabel
there is one inconsistency on those calls
List Labels return the color without #
but Create Label requires the #
it's not a big deal but it is kinda boring for someone who uses it
Because then you get errors like this:
`
panic: Error creating label [Affects Agent e11d21 This will require a new release of TrustFactor agents]: 422 Unprocessable Entity: [{"fieldNames":["Color"],"classification":"SizeError","message":"Size"}]
`

### PR DESCRIPTION
**Pull request by 6543**
fix #10127
and format code
and fix typo

### CODE REVIEW

**Comment by 6543** [comment]
models.NewLabel() has not a single check if input match!!! we need checks before incerting to DB anyway !!!

**Comment by guillep2k** [comment]
Title suggestion:
```
[WIP] [API] Fix inconsistent label format 
```

File: routers/api/v1/repo/label.go [hunk 1]
```diff
@@ -136,6 +136,10 @@ func CreateLabel(ctx *context.APIContext, form api.CreateLabelOption) {
 	//   "201":
 	//     "$ref": "#/responses/Label"
 
+	if len(form.Color) == 6 {
```
Comment (guillep2k) [inline routers/api/v1/repo/label.go:144]: `models.NewLabel()` doesn't perform any kind of validation on the format of the label. I'd validate the format with a RegExp (`^#[0-9a-fA-F]{6}$`) (either here or at `models.NewLabel()`).

File: modules/structs/issue_label.go [hunk 2]
```diff
@@ -21,8 +21,8 @@ type CreateLabelOption struct {
 	// required:true
 	Name string `json:"name" binding:"Required"`
 	// required:true
-	// example: #00aabb
-	Color       string `json:"color" binding:"Required;Size(7)"`
+	// example: 00aabb
```
Comment (lafriks) [inline modules/structs/issue_label.go]: example can be kept as it was

**Comment by 6543** [comment]
OK this Fix and smal code reformat is now ready :)
not it Isn't a "simple solution" but all functions now validate Collor before changes go to DB :) usw ...

**Comment by 6543** [comment]
@guillep2k this is ready to revview :)

File: models/issue_label.go [hunk 3]
```diff
@@ -359,6 +366,9 @@ func updateLabel(e Engine, l *Label) error {
 
 // UpdateLabel updates label information.
 func UpdateLabel(l *Label) error {
+	if !LabelColorPattern.MatchString(l.Color) {
```
Comment (guillep2k) [inline models/issue_label.go:373]: Validation here is not required since `l.Color` is not used or related (not even in `updateLabel`).

File: routers/api/v1/repo/label.go [hunk 4]
```diff
@@ -198,6 +213,14 @@ func EditLabel(ctx *context.APIContext, form api.EditLabelOption) {
 	}
 	if form.Color != nil {
 		label.Color = *form.Color
+		label.Color = strings.Trim(label.Color, " ")
```
Comment (guillep2k) [inline routers/api/v1/repo/label.go]: Can simplify by joining with line above

File: models/issue_label.go [hunk 5]
```diff
@@ -43,7 +70,7 @@ func GetLabelTemplateFile(name string) ([][3]string, error) {
 			return nil, fmt.Errorf("line is malformed: %s", line)
 		}
 
-		if !labelColorPattern.MatchString(fields[0]) {
+		if !LabelColorPattern.MatchString(fields[0]) {
```
Comment (guillep2k) [inline models/issue_label.go]: Maybe if we have `#` optional in the API it should be optional everywhere?

File: models/issue_label.go (hunk 3 above)
Comment (6543) [reply models/issue_label.go:373]: @guillep2k updateLabel Do set colors:
https://github.com/go-gitea/gitea/pull/10129/files/730d282fd30251c23a4c3a555c2ab46fd850a86b#diff-0186cfcb4351665688ca92eaa8c6dd2dR363

File: models/issue_label.go (hunk 5 above)
Comment (6543) [reply models/issue_label.go]: and beside the api where do you mean?

Comment (guillep2k) [reply models/issue_label.go]: Resource files.

Comment (guillep2k) [reply models/issue_label.go]: custom/.../labels/{set}

Comment (6543) [reply models/issue_label.go]: I'll have a look at it

**Comment by 6543** [comment]
@guillep2k done

**Review by guillep2k — APPROVED** [review]

**Comment by 6543** [comment]
@lafriks can you look at this?

**Comment by lafriks** [comment]
Drone fails

**Comment by 6543** [comment]
@lafriks unrelated

**Comment by 6543** [comment]
@lafriks CI passed

**Review by zeripath — APPROVED** [review]
