### PR TITLE
Fix SQL Query for `SearchTeam`

### LINKED ISSUE #20829: GET /api/v1/user/teams returns null
### Description

My user (20) is in an organization (publicorg) and in this organization in a team (Frontend). I would expect `/api/v1/user/teams` to return the team as described in the swagger, but instead it just returns `null`. It doesn't matter whether the user is a public member or not. Using this endpoint would simplify [this pull request](https://github.com/oauth2-proxy/oauth2-proxy/pull/1759) a bit.

### Gitea Version

1.17.0 built with GNU Make 4.3, go1.18.4 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/Oliver-Hanikel/a279a0057dab0880a866b3180dd55ff2

### Screenshots

image
image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

I am using the official 1.17.0 docker image from docker hub.

### Database

SQLite

### PR DESCRIPTION
**Pull request by Gusted**
- Currently the function takes in the `UserID` option, but isn't being used within the SQL query. This patch fixes that by checking that only teams are being returned that the user belongs to.
- Resolves #20829

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: integrations/api_user_orgs_test.go [hunk 1]
```diff
@@ -82,8 +93,19 @@ func TestMyOrgs(t *testing.T) {
 	var orgs []*api.Organization
 	DecodeJSON(t, resp, &orgs)
 	user3 := unittest.AssertExistsAndLoadBean(t, &user_model.User{Name: "user3"})
+	user17 := unittest.AssertExistsAndLoadBean(t, &user_model.User{Name: "user172"})
```
Comment (delvh) [inline integrations/api_user_orgs_test.go]:
```suggestion
	user17 := unittest.AssertExistsAndLoadBean(t, &user_model.User{Name: "user17"})
```
typo?

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
And some unit tests seem to need an edit…

**Comment by Oliver-Hanikel** [comment]
Thanks for fixing this bug

**Comment by Gusted** [comment]
@delvh @lunny Please re-review again. Especially regarding this line: https://github.com/go-gitea/gitea/pull/20844/files#diff-3d84110fa93e421c3875fcd87a4732305131fc42b65d34d06a1b8e453bee3d80L342 This function is already specified to require organization admin in the router, so no need to specify only the teams that the user belong in

File: routers/web/org/teams.go [hunk 2]
```diff
@@ -339,7 +339,6 @@ func SearchTeam(ctx *context.Context) {
 	}
 
 	opts := &organization.SearchTeamOptions{
-		UserID:      ctx.Doer.ID,
 		Keyword:     ctx.FormTrim("q"),
```
Comment (delvh) [inline routers/web/org/teams.go:343]:
```suggestion
		// UserID is not set because the router already requires the doer to be an org admin. Thus, we don't need to restrict to teams that the user belongs in
		Keyword:     ctx.FormTrim("q"),
```
So that we have a good chance to find an error early in case this precondition ever gets changed.

**Review by delvh — APPROVED** [review]

File: routers/web/org/teams.go (hunk 2 above)
Comment (Gusted) [reply routers/web/org/teams.go:343]: Thanks!

**Review by zeripath — APPROVED** [review]

**Comment by Gusted** [comment]
Interesting CI failure:
image

**Comment by zeripath** [comment]
make lgtm work
