### PR TITLE
Fix sync fork for consistency

### LINKED ISSUE #33145: Strange behaviors of the Sync Fork feature
### Description

There is a known issue that, when in a forked repository, we use `GetUpstreamDivergingInfo->GetDivergingCommits` to see if the forked branch needs to be synced.

However the `GetDivergingCommits` will not work completely (return code 128 when the forked branch is updated) because the forked branch does not have the reference tree of the base branch in the repo path. Results in some scenarios, the `Sync fork` button is not shown as expected.

I would like to work on this issue, and the following is my fix design:

* By reference to `modules/git/repo_compare.go`'s `GetCompareInfo`, implement a temporary remote for the forked branch to make the `git rev-list` work.
* The `rev-list` for the forked branch and base branch is much alike a pull request without listing the file changes but getting the summary of the commit change.

---

This issue is related to #32769, if this is fixed, the improved `GetDivergingCommits` could help the other issue.

### Gitea Version

34dfc25

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots
Snipaste_2025-01-08_12-08-30

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

dev container from ubuntu22.04

### Database

SQLite

### PR DESCRIPTION
**Pull request by changchaishi**
Fixes #33145

An integration test could be added.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
> An integration test could be added.

I have some tests and will add them.

But I am not sure whether we should still use the "add remote" trick here, it seems fragile and I am not sure whether it is really helpful in daily usage.

**Comment by changchaishi** [comment]
> But I am not sure whether we should still use the "add remote" trick here, it seems fragile and I am not sure whether it is really helpful in daily usage.

This is really what I am concerned about before submitting the PR. 

One more bug I found on `services/repository/merge_upstream.go`:35, the current sync fork is not correct, should be base repo's defaultBranch.

https://github.com/orgs/community/discussions/11729

**Comment by wxiaoguang** [comment]
> > But I am not sure whether we should still use the "add remote" trick here, it seems fragile and I am not sure whether it is really helpful in daily usage.
> 
> This is really what I am concerned about before submitting the PR.
> 
> One more bug I found on `services/repository/merge_upstream.go`:35, the current sync fork is not correct, should be base repo's defaultBranch.
> 
> https://github.com/orgs/community/discussions/11729

If you have more ideas about the problem, feel free to take  #33148 (there are more tests, I could close my PR if you'd like to use it in your PR)

**Comment by changchaishi** [comment]
I see~

For 1. I did not notice this is the intended behavior of Gitea right now, as I am studying the code, I refer to GitHub a lot, Github has 
the Number 2 behavior, so I thought this was a kind of bug.

I think we can simplify this PR without this issue first.

> One more bug I found on services/repository/merge_upstream.go:35, the current sync fork is not correct, should be the base repo's defaultBranch.
> 
> https://github.com/orgs/community/discussions/11729

---
> If you have more ideas about the problem, feel free to take https://github.com/go-gitea/gitea/pull/33148 (there are more tests, I could close my PR if you'd like to use it in your PR)

I reviewed it, and this is nice, how can I use the test? Must you close it so that I can use it, or I can just reference it to create something like `repo_sync_fork_rest.py`

**Comment by wxiaoguang** [comment]
Actually I am not sure which behavior is better for end users. Maybe following GitHub's behavior is better since it is widely used. 🤣 

----



> > If you have more ideas about the problem, feel free to take #33148 (there are more tests, I could close my PR if you'd like to use it in your PR)
> 
> I reviewed it, and this is nice, how can I use the test? Must you close it so that I can use it, or I can just reference it to create something like `repo_sync_fork_rest.py`

Some possible choices:

* You could merge my branch into yours https://github.com/wxiaoguang/gitea/tree/improve-merge-upstream
* Or just copy the code into your PR
* Or wait for #33148 to be merged

File: services/repository/merge_upstream.go [hunk 1]
```diff
@@ -102,10 +105,29 @@ func GetUpstreamDivergingInfo(ctx context.Context, repo *repo_model.Repository,
...
+	if err != nil {
+		log.Error("GetMergeBase: %v", err)
+	}
+
+	baseBranch.CommitID, err = git.GetFullCommitID(gitRepo.Ctx, gitRepo.Path, remoteBranch)
+	if err != nil {
+		baseBranch.CommitID = remoteBranch
+	}
+
+	diff, err := git.GetDivergingCommits(gitRepo.Ctx, gitRepo.Path, baseBranch.CommitID, forkBranch.CommitID)
```
Comment (wxiaoguang) [inline services/repository/merge_upstream.go]: I think we could use another approach to detect the "DivergingCommits" without adding the temp remote:

1. call "GetDivergingCommits" to see if fork is behind base (old logic)
2. if fails, check if the base's update time is newer (old logic)
3. if the base's update time is older, check whether fork's branch contains the base's head commit
    * if fork contains base's head commit: then fork is after base (no need to sync)
    * if not contains: base has newer commits (could try to sync)

This approach should be faster and more stable IMO.

Comment (changchaishi) [reply services/repository/merge_upstream.go]: Hi, I've followed your advice not to use the temp remote for git rev-list and also added the integration test.

It just checks whether the message is shown. The more thorough tests leave for the merge-upstream PR.

**Comment by wxiaoguang** [comment]
If you don't mind, I think I can merge  #33148  here, then we do not need to use a separate PR to handle the similar tests.

**Comment by wxiaoguang** [comment]
Made some new changes:

1. merge  #33148 and reuse the tests
2. use base repo's default branch to sync (as you suggested and as GitHub does)

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]
