### PR TITLE
Fix team edit API panic

### LINKED ISSUE #6777: Edit team API fails with nil pointer dereference
- Gitea version (or commit ref): 81059a2
- Git version: 2.21.0
- Operating system: Ubuntu 18.04.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Edit team API fails with nil pointer dereference:
```
runtime error: invalid memory address or nil pointer dereference
	/snap/go/3584/src/runtime/panic.go:82
		panicmem: panic(memoryError)
	/snap/go/3584/src/runtime/signal_unix.go:390
		sigpanic: panicmem()
	~/go/src/code.gitea.io/gitea/routers/api/v1/org/team.go:192
		EditTeam: OrgID: ctx.Org.Organization.ID,
```

### PR DESCRIPTION
**Pull request by ngourdon**
fix #6777 and add tests for team API

### CODE REVIEW

File: integrations/api_team_test.go [hunk 1]
```diff
@@ -1,14 +1,17 @@
-// Copyright 2017 The Gitea Authors. All rights reserved.
+// Copyright 2019 The Gitea Authors. All rights reserved.
```
Comment (lafriks) [inline integrations/api_team_test.go]: nit: no need to update year
```suggestion
// Copyright 2017 The Gitea Authors. All rights reserved.
```

**Comment by lafriks** [comment]
Thanks for adding tests :+1:  small nit but otherwise LGTM

**Review by techknowlogick — APPROVED** [review]

**Comment by techknowlogick** [comment]
@ngourdon thanks for PR :) would you be able to backport this PR to the release/v1.8 branch?
