### PR TITLE
Fix ghost user in feeds when pushing in an actions, it should be gitea-actions

### LINKED ISSUE #34688: New tags always pushed as Ghost user
### Description

I have created following workflow to deploy new tags. Everything working fine, but, user that create new tag is alway displayed as Ghost.

Image

Here is my workflow:
```
name: 🚀 Tag and Deploy Application

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  tag-and-deploy:
    runs-on: debian-node

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🛠️ Install dependencies
        run: |
          apt-get update && apt-get install -y jq

      - name: 🔍 Get version and name from package.json
        id: get_version_name
        run: |
          VERSION=$(jq -r .version package.json)
          NAME=$(jq -r .name package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: 🏷️ Fetch all tags
        run: git fetch --tags

      - name: 🔎 Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "${{ steps.get_version_name.outputs.version }}" >/dev/null 2>&1; then
            echo "deploy_needed=false" >> $GITHUB_OUTPUT
          else
            echo "deploy_needed=true" >> $GITHUB_OUTPUT
          fi

      - name: 🆕 Create and push tag
        if: steps.check_tag.outputs.deploy_needed == 'true'
        run: |
          git config user.name "Gitea Runner"
          git config user.email "gitea.runner@domain.com"
          git tag "${{ steps.get_version_name.outputs.version }}"
          git push origin "${{ steps.get_version_name.outputs.version }}"

```

I've created new user with username **gitea.runner** and email **gitea.runner@domain.com**. Why is it still marked as Ghost user when new tag is being created? Thanks!

### Gitea Version

1.24.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Debian 12

### How are you running Gitea?

Self hosted in LXC container.

### Database

None

### PR DESCRIPTION
**Pull request by lunny**
Fix #34688 

This PR will store the `publisher_id` of `release`(tag) table as pusher's id. It could be a real userID or a system user id. If the user is deleted, ghost will be replaced.

This PR will also correct the wrong user `Ghost` in the feeds and wrong committer on tag list page if pushing a tag from an actions. Now the behavior is the same as Github. Some codes are deleted because it tries to get commit author as pusher which is not right.

### CODE REVIEW

**Review by delvh — APPROVED** [review]

File: services/repository/push.go [hunk 1]
```diff
@@ -397,21 +395,9 @@ func pushUpdateAddTags(ctx context.Context, repo *repo_model.Repository, gitRepo
...
-			author, ok = emailToUser[sig.Email]
-			if !ok {
-				author, err = user_model.GetUserByEmail(ctx, sig.Email)
-				if err != nil && !user_model.IsErrUserNotExist(err) {
-					return fmt.Errorf("GetUserByEmail: %w", err)
-				}
-				if author != nil {
-					emailToUser[sig.Email] = author
-				}
-			}
```
Comment (wxiaoguang) [inline services/repository/push.go:414]: Why deleted? Pusher doesn't mean committer.

Comment (lunny) [reply services/repository/push.go:414]: The original logic used author as pusher which is not right.

**Review by wxiaoguang — APPROVED** [review]
