### PR TITLE
Fix highlight diff result

### LINKED ISSUE #36536: word-diff coloring misses changes in webui showing diffs
### Description

The word-diff coloring misses changes in webui showing diffs:

```diff
- func FindAcceptableReviewInTimeline(user string, timeline []*models.TimelineComment, reviews []*models.PullReview) *models.TimelineComment {
+ func (bot *ReviewBot) FindAcceptableReviewInTimeline(user string, timeline []*models.TimelineComment, reviews []*models.PullReview) *models.TimelineComment {
```
Here `(bot *ReviewBot)` is not colored as addition.

```diff
-	if ReviewAccepted(t.Body) || ReviewRejected(t.Body) {
+	if bot.ReviewAccepted(t.Body) || bot.ReviewRejected(t.Body) {
```
Here the second `bot.` is not colored as addition, but the first one is.

Example you can view online (screenshot below): https://src.opensuse.org/git-workflow/autogits/pulls/105/files#issuecomment-81116
Same commit, with same problem, on demo: https://demo.gitea.com/JanZerebecki/autogits-mirror/commit/f6d2239f4dba745b4fb655dd7cea491cf731b0564fddc1e5076d3cd9b1abaff0

### Screenshots

Image

### Gitea Version

1.25.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### Browser Version

Firefox

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #36536

This fix will significantly improve the diff result.

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Screenshot is here: https://github.com/go-gitea/gitea/issues/36536#issuecomment-3858456132

File: services/gitdiff/highlightdiff.go [hunk 1]
```diff
@@ -11,16 +11,54 @@ import (
 	"github.com/sergi/go-diff/diffmatchpatch"
 )
 
-// token is a html tag or entity, eg: "<span ...>", "</span>", "&lt;"
-func extractHTMLToken(s string) (before, token, after string, valid bool) {
+// extractDiffTokenRemainingFullTag tries to extract full tag with content from the remaining string
+// e.g. for input: "content</span>reset", it returns "content</span>", "rest", true
```
Comment (TheFox0x7) [inline services/gitdiff/highlightdiff.go]:
```suggestion
// e.g. for input: "content</span>reset", it returns "content</span>", "reset", true
```

**Review by TheFox0x7 — APPROVED** [review]

File: services/gitdiff/highlightdiff.go (hunk 1 above)
Comment (wxiaoguang) [reply services/gitdiff/highlightdiff.go]: Oops, I mean "rest", AI wrote "reset" 🤣 

```suggestion
// e.g. for input: "content</span>rest", it returns "content</span>", "rest", true
```

File: services/gitdiff/highlightdiff.go [hunk 2]
```diff
@@ -11,16 +11,54 @@ import (
 	"github.com/sergi/go-diff/diffmatchpatch"
 )
 
-// token is a html tag or entity, eg: "<span ...>", "</span>", "&lt;"
-func extractHTMLToken(s string) (before, token, after string, valid bool) {
+// extractDiffTokenRemainingFullTag tries to extract full tag with content from the remaining string
+// e.g. for input: "content</span>rest", it returns "content</span>", "rest", true
```
Comment (wxiaoguang) [inline services/gitdiff/highlightdiff.go]:
```suggestion
// e.g. for input: "content</span>the-rest...", it returns "content</span>", "the-rest...", true
```

**Review by tboerger — APPROVED** [review]
LGTM

**Comment by wxiaoguang** [comment]
A following up fix: Use full-file highlighting for diff sections #36561 🙏
