### PR TITLE
Convert GitHub event on actions and fix some pull_request events.

### LINKED ISSUE #22958: action cannot be triggered when using on.pull_request
### Description

Action cannot be triggered when using `on.pull_request`.

New pr can trigger this action.

But push to pr source branch cannot trigger it.

Github can trigger it.

```yaml
# .gitea/workflows/build.yaml
name: Gitea Actions Demo
run-name: ${{ github.actor }} is testing out Gitea Actions 🚀
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
```

### Gitea Version

ca445c

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

build Gitea myself
run from command-line

### Database

SQLite

### PR DESCRIPTION
**Pull request by lunny**
Follow #22680

Partially Fix #22958, on pull_request, `opened`, `reopened`, `synchronize` supported, `edited` hasn't been supported yet because Gitea doesn't trigger that events.

### CODE REVIEW

**Review by wolfogre — APPROVED** [review]

File: modules/actions/workflows.go [hunk 1]
```diff
@@ -44,6 +44,19 @@ func ListWorkflows(commit *git.Commit) (git.Entries, error) {
 	return ret, nil
 }
 
+func converGithubEvent2GiteaEvent(evt *jobparser.Event) string {
```
Comment (KN4CK3R) [inline modules/actions/workflows.go]:
```suggestion
func convertFromGithubEvent(evt *jobparser.Event) string {
```

File: modules/actions/workflows.go [hunk 2]
```diff
@@ -85,138 +96,178 @@ func DetectWorkflows(commit *git.Commit, triggedEvent webhook_module.HookEventTy
 }
 
 func detectMatched(commit *git.Commit, triggedEvent webhook_module.HookEventType, payload api.Payloader, evt *jobparser.Event) bool {
+	if converGithubEvent2GiteaEvent(evt) != triggedEvent.Event() {
```
Comment (KN4CK3R) [inline modules/actions/workflows.go]:
```suggestion
	if convertFromGithubEvent(evt) != triggedEvent.Event() {
```

File: modules/actions/workflows.go [hunk 3]
```diff
@@ -44,6 +44,19 @@ func ListWorkflows(commit *git.Commit) (git.Entries, error) {
...
+		return string(webhook_module.HookEventPullRequest)
+	case "registry_package":
+		return string(webhook_module.HookEventPackage)
+	case "create", "delete", "fork", "push", "issues", "issue_comment", "release", "pull_request_comment":
+		fallthrough
+	default:
+		return evt.Name
+	}
+}
+
```
Comment (uvulpos) [inline modules/actions/workflows.go]: I would not write a converter Function here, I would write it in the `jobparser` package and make it publicly available. Also, this would pop out when you use Intellisense in the suggestion windows and is reusable. What do you think about it?
  
```suggestion
func (evt *jobparser.Event) ConverGithubEvent2GiteaEvent string {
	switch evt.Name {
	case "pull_request", "pull_request_target", "pull_request_review_comment", "pull_request_review":
		return string(webhook_module.HookEventPullRequest)
	case "registry_package":
		return string(webhook_module.HookEventPackage)
	case "create", "delete", "fork", "push", "issues", "issue_comment", "release", "pull_request_comment":
		fallthrough
	default:
		return evt.Name
	}
}

```

File: modules/actions/workflows.go [hunk 4]
```diff
@@ -44,6 +44,19 @@ func ListWorkflows(commit *git.Commit) (git.Entries, error) {
 	return ret, nil
 }
 
+func converGithubEvent2GiteaEvent(evt *jobparser.Event) string {
+	switch evt.Name {
+	case "pull_request", "pull_request_target", "pull_request_review_comment", "pull_request_review":
+		return string(webhook_module.HookEventPullRequest)
+	case "registry_package":
+		return string(webhook_module.HookEventPackage)
+	case "create", "delete", "fork", "push", "issues", "issue_comment", "release", "pull_request_comment":
```
Comment (uvulpos) [inline modules/actions/workflows.go]: Why are these event types simple strings? Wouldn't be an enum more sufficient?

File: modules/actions/workflows.go (hunk 3 above)
Comment (lunny) [reply modules/actions/workflows.go]: I don't think so. Because we can support to convert other sub-system events to Gitea Event. i.e. from GitLab's in future PRs.

**Comment by lunny** [comment]
@KN4CK3R done.

**Comment by KN4CK3R** [comment]
CI fail is related.

File: modules/actions/github.go [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+	githubEventDelete                   = "delete"
+	githubEventFork                     = "fork"
+	githubEventPush                     = "push"
+	githubEventIssues                   = "issues"
+	githubEventIssueComment             = "issue_comment"
+	githubEventRelease                  = "release"
+	githubEventPullRequestComment       = "pull_request_comment"
+)
+
+func converFromGithubEvent(evt *jobparser.Event) string {
```
Comment (yp05327) [inline modules/actions/github.go]:
```suggestion
func convertFromGithubEvent(evt *jobparser.Event) string {
```

File: modules/actions/workflows.go [hunk 6]
```diff
@@ -85,138 +83,178 @@ func DetectWorkflows(commit *git.Commit, triggedEvent webhook_module.HookEventTy
 }
 
 func detectMatched(commit *git.Commit, triggedEvent webhook_module.HookEventType, payload api.Payloader, evt *jobparser.Event) bool {
+	if converFromGithubEvent(evt) != triggedEvent.Event() {
```
Comment (yp05327) [inline modules/actions/workflows.go]:
```suggestion
	if convertFromGithubEvent(evt) != triggedEvent.Event() {
```

File: modules/actions/github.go [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+
+func convertFromGithubEvent(evt *jobparser.Event) string {
+	switch evt.Name {
+	case githubEventPullRequest, githubEventPullRequestTarget, githubEventPullRequestReview,
+		githubEventPullRequestReviewComment:
+		return string(webhook_module.HookEventPullRequest)
+	case githubEventRegistryPackage:
+		return string(webhook_module.HookEventPackage)
+	case githubEventCreate, githubEventDelete, githubEventFork, githubEventPush,
+		githubEventIssues, githubEventIssueComment, githubEventRelease, githubEventPullRequestComment:
```
Comment (KN4CK3R) [inline modules/actions/github.go:36]: I know it was requested but are the constants really more readable than just simple strings in switch?

Comment (lunny) [reply modules/actions/github.go:36]: They are maybe used in other places in future.

File: modules/actions/workflows.go [hunk 8]
```diff
@@ -85,138 +83,178 @@ func DetectWorkflows(commit *git.Commit, triggedEvent webhook_module.HookEventTy
...
 
 	switch triggedEvent {
-	case webhook_module.HookEventCreate:
-		fallthrough
-	case webhook_module.HookEventDelete:
-		fallthrough
-	case webhook_module.HookEventFork:
+	case webhook_module.HookEventCreate,
+		webhook_module.HookEventDelete,
+		webhook_module.HookEventFork,
```
Comment (KN4CK3R) [inline modules/actions/workflows.go:109]: These three events returned false and now true, is that correct?

Comment (lunny) [reply modules/actions/workflows.go:109]: I think yes. Because I have checked whether the name is the same in lines 86-88.

**Review by sillyguodong — APPROVED** [review]

File: modules/actions/workflows.go [hunk 9]
```diff
@@ -101,138 +99,197 @@ func DetectWorkflows(commit *git.Commit, triggedEvent webhook_module.HookEventTy
...
-			case "types":
-				for _, val := range vals {
-					if glob.MustCompile(val, '/').Match(string(prPayload.Action)) {
-						matchTimes++
-						break
-					}
+func matchPullRequestEvent(commit *git.Commit, prPayload *api.PullRequestPayload, evt *jobparser.Event) bool {
+	// with no special filter parameters
+	if len(evt.Acts) == 0 {
+		// defautly, only pull request opened and synchronized will not trigger workflow
```
Comment (yp05327) [inline modules/actions/workflows.go]:
```suggestion
		// defaultly, only pull request opened and synchronized will trigger workflow
```
