### PR TITLE
Completely quote AppPath and CustomConf paths

### LINKED ISSUE #10813: Generated authorized_keys does not work on Windows
- Gitea version (or commit ref): 1.11.3
- Git version: 2.22.0.windows.1
- Operating system: Windows Server 2019
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
gitea doesn't work on Windows with OpenSSH (not in-built ssh server). The problem is with the single quotes with the command in authorized_keys:

> command="C:/Gitea/gitea.exe --config='C:/Gitea/custom/conf/app.ini' serv key-1"

When I run this command on Windows (without any ssh in the picture) we get the following debug output:

`2020/03/25` 09:36:43 ...s/setting/setting.go:531:NewContext() [W] Custom config 'C:/Gitea/custom/'C:/Gitea/custom/conf/app.ini'' not found, ignore this if you're running first time`
`2020/03/25 09:36:43 ...s/setting/setting.go:785:NewContext() [F] failed to create 'C:/Gitea/custom/'C:/Gitea/custom/conf/app.ini'': mkdir C:\Gitea\custom\'C:: The filename, directory name, or volume label syntax is incorrect.`

There are two problems:

1. The single quotes around the --config file cause gitea on Windows to report that it cannot find the file.
2. gitea then goes ahead and tries to create "C:/Gitea/custom/'C:/Gitea/custom/conf/app.ini''. This is an invalid path and gitea aborts.

The quick fix which works for me is to manually change the command in authorized_keys to:

> command="C:/Gitea/gitea.exe --config=\\"C:/Gitea/custom/conf/app.ini\\" serv key-1"

With double quotes I can now use gitea over OpenSSH (not build-in ssh) on Windows. The problem now is that authorized_keys will be overwritten next time we create a user for example.

To fix I believe what needs to be done:

1. Change gitea to output double quotes in authorized_keys, or
2. Figure out why single quotes don't work (perhaps a go problem?)
3. Fix gitea's parsing of argv[0] so it can handle 'C:/...'

I also question why gitea would ever be creating a template app.ini when invoked with the serv command. That doesn't seem like the right thing to do.

### PR DESCRIPTION
**Pull request by zeripath**
Properly handle spaces in AppPath and CustomConf within hooks and
authorized_keys. Unfortunately here we don't seem to be able to get away
with using go-shellquote as it appears that Windows doesn't play too
well with singlequote quoting - therefore we will avoid singlequote
quoting unless we absolutely cannot get away without it, e.g. \n or !.

Fix #10813

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by lafriks** [comment]
Please fix also test `Test_CmdKeys/with_key`

File: models/ssh_key.go [hunk 1]
```diff
@@ -84,7 +84,7 @@ func (key *PublicKey) OmitEmail() string {
 
 // AuthorizedString returns formatted public key string for authorized_keys file.
 func (key *PublicKey) AuthorizedString() string {
-	return fmt.Sprintf(tplPublicKey, fmt.Sprintf(tplCommand, setting.AppPath, setting.CustomConf, key.ID), key.Content)
+	return fmt.Sprintf(tplPublicKey, util.ShellEscape(fmt.Sprintf(tplCommand, util.ShellEscape(setting.AppPath), util.ShellEscape(setting.CustomConf), key.ID)), key.Content)
```
Comment (techknowlogick) [inline models/ssh_key.go:87]: I'm having some trouble with this line. I get why the paths need to be escaped, but this looks like it is double escaping things, and can't see why it would need that.

Comment (lafriks) [reply models/ssh_key.go:87]: because command should be kept together as single value, imho

Comment (techknowlogick) [reply models/ssh_key.go:87]: ah yes, I see now. As expected I was just a touch dense. Thanks :)

**Review by techknowlogick — APPROVED** [review]

File: modules/util/shellquote_test.go [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+			"a/b/c/d",
+			"a/b/c/d",
+		}, {
+			"Prefixed tilde - with normal stuff - should not escape",
+			"~/src/go/gitea/gitea",
+			"~/src/go/gitea/gitea",
+		}, {
+			"Typical windows path with spaces - should get doublequote escaped",
+			`C:\Program Files\Gitea v1.13 - I like lots of spaces\gitea`,
+			`"C:\\Program Files\\Gitea v1.13 - I like lots of spaces\\gitea"`,
```
Comment (6543) [inline modules/util/shellquote_test.go:26]: I think windows will handle `\\` as `\` if they are not after a `:` but can we escape better?

Comment (zeripath) [reply modules/util/shellquote_test.go:26]: This code is only used in places where a reasonable shell is running - it's not trying to cope with the idiosyncrasies of cmd or powershell. It's sh, ash, dash, bash running on top of cygwin/mingw - which frankly is idiosyncratic enough.

**Review by 6543 — APPROVED** [review]
