### PR TITLE
Fix "Dashboard shows deleted comments"

### LINKED ISSUE #1956: Dashboard shows deleted comments
- Gitea version (or commit ref): 1.1.1+2-g2854c8a
- Git version: 2.12.2
- Operating system: Windows Server 2012
- Database (use `[x]`):
  - [x] MSSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes [gitpitch/code-presenting/issues/1](https://try.gitea.io/gitpitch/code-presenting/issues/1) (dashboard screenshot attached)
- Log gist: Not relevant

The Dashboard page shows activity for a deleted comment. I think this should not be shown because the comment is no longer visible on the issue. 

image

### PR DESCRIPTION
**Pull request by jonasfranz**
Fixes #1956
Adds a "CommentID" column to the action model (+migration). This is useful for deleting associated actions when a comment should be deleted. 
Adds a link to the comment in the associated feed entry.

### CODE REVIEW

File: models/action.go [hunk 1]
```diff
@@ -22,6 +22,7 @@ import (
 	"code.gitea.io/gitea/modules/base"
 	"code.gitea.io/gitea/modules/log"
 	"code.gitea.io/gitea/modules/setting"
+	"strconv"
```
Comment (lunny) [inline models/action.go]: standard lib should be at the first

Comment (jonasfranz) [reply models/action.go]: - [X] Done

File: models/migrations/v35.go [hunk 2]
```diff
@@ -0,0 +1,24 @@
+// Copyright 2017 The Gogs Authors. All rights reserved.
```
Comment (cez81) [inline models/migrations/v35.go]: Gitea authors

Comment (jonasfranz) [reply models/migrations/v35.go]: - [X] Done

File: templates/user/dashboard/feeds.tmpl [hunk 3]
```diff
@@ -63,12 +63,12 @@
...
 						<span class="text truncate issue title has-emoji">{{index .GetIssueInfos 1}}</span>
 					{{else if eq .GetOpType 10}}
-						<span class="text truncate issue title has-emoji">{{.GetIssueTitle}}</span>
+						<a href="{{.GetCommentLink}}" class="text truncate issue title has-emoji">{{.GetIssueTitle}}</a>
 						<p class="text light grey has-emoji">{{index .GetIssueInfos 1}}</p>
 					{{else if eq .GetOpType 11}}
 						<p class="text light grey has-emoji">{{index .GetIssueInfos 1}}</p>
 					{{else if (or (or (eq .GetOpType 12) (eq .GetOpType 13)) (or (eq .GetOpType 14) (eq .GetOpType 15)))}}
-						<span class="text truncate issue title has-emoji">{{.GetIssueTitle}}</span>
+						<a href="{{.GetCommentLink}}"  class="text truncate issue title has-emoji">{{.GetIssueTitle}}</a>
```
Comment (ethantkoenig) [inline templates/user/dashboard/feeds.tmpl]: I dislike using `.GetCommentLink` for actions that don't have anything to do with comments. I know that `.GetCommentLink` will return the link to the issue in this case, but it seems sloppy.

IMO, the best solution here is to add `IssueID` and `Issue` fields to the `Action` struct. This would allow us to just use `.Issue.HTMLURL` here, and `.Comment.HTMLURL` in line 66. It would also allow us to get rid of `.GetIssueInfos`, which to me seems like a hack.

Would it be possible to hold off adding these links to a separate PR? The links are unrelated to fixing the deleted-comment bug, and it seems to me that the best way to add support for the links requires some more refactoring.

File: routers/user/home.go [hunk 4]
```diff
@@ -74,6 +74,7 @@ func retrieveFeeds(ctx *context.Context, user *models.User, includePrivate, isPr
 	if ctx.User != nil {
 		userCache[ctx.User.ID] = ctx.User
 	}
+	commentCache := map[int64]*models.Comment{}
```
Comment (ethantkoenig) [inline routers/user/home.go]: As far as I can tell, there will never be two actions with the same (non-zero) `CommentID`, so I don't see any point in caching comments.

File: routers/user/home.go [hunk 5]
```diff
@@ -115,6 +129,7 @@ func retrieveFeeds(ctx *context.Context, user *models.User, includePrivate, isPr
 				return
 			}
 		}
+
```
Comment (ethantkoenig) [inline routers/user/home.go]: Please remove this blank line

**Review by ethantkoenig — CHANGES_REQUESTED** [review]

File: templates/user/dashboard/feeds.tmpl (hunk 3 above)
Comment (jonasfranz) [reply templates/user/dashboard/feeds.tmpl]: I think that the best solution is that I leave the links in place (except the link you mentioned). The .GetCommentLink function is also needed for backward-compatibility reasons. So actions that created before the update won't have a comment_id assigned. So .Comment.HTMLURL would not work. 
I think that adding these links does not need to be holed off to another PR.

File: routers/user/home.go (hunk 5 above)
Comment (jonasfranz) [reply routers/user/home.go]: Why? gofmt did not remove this line.

Comment (ethantkoenig) [reply routers/user/home.go]: Nor did gofmt add it :smile:. I'm generally opposed to unnecessary whitespace changes, particularly when they are far away from a commit's actual changes; they end up making the git history more complex (i.e. looking at a file's blame).

File: templates/user/dashboard/feeds.tmpl (hunk 3 above)
Comment (ethantkoenig) [reply templates/user/dashboard/feeds.tmpl]: Good point about backwards compatibility, I didn't think of that.

**Review by ethantkoenig — APPROVED** [review]

**Comment by lunny** [comment]
LGTM

File: models/action.go [hunk 6]
```diff
@@ -191,6 +194,38 @@ func (a *Action) GetRepoLink() string {
...
+	}
+
+	issue, err := GetIssueByID(issueID)
+
+	if err != nil {
+		return "#"
+	}
+
+	return issue.HTMLURL()
+
```
Comment (lafriks) [inline models/action.go]: Please remove unneeded newline after last return and before both `if err != nil {`

**Review by lafriks — CHANGES_REQUESTED** [review]

File: models/issue_comment.go [hunk 7]
```diff
@@ -641,5 +643,12 @@ func DeleteComment(comment *Comment) error {
 		}
 	}
 
+	//Delete associated Action
+	if _, err := sess.Delete(&Action{
```
Comment (bkcsoft) [inline models/issue_comment.go]: Please don't delete actions. Rather check in the dashboard if the comment exists or not and act accordingly.

**Review by bkcsoft — CHANGES_REQUESTED** [review]

File: models/action.go [hunk 8]
```diff
@@ -706,5 +741,12 @@ func GetFeeds(opts GetFeedsOptions) ([]*Action, error) {
 	if opts.RequestedUser.IsOrganization() {
 		sess.In("repo_id", repoIDs)
 	}
+
+	if !opts.IncludeDeletedComments {
+		// commentID != 0 AND comment exist
+		sess.And("(comment_id ISNULL OR comment_id = 0 OR EXISTS(SELECT NULL FROM comment c WHERE comment_id = c.id))")
```
Comment (lafriks) [inline models/action.go]: Select is invalid as there is no such `ISNULL`. Also selects with `OR` are very hard to optimize for dbms so mostly they are slow on large tables and this one is such. I would better prefer if there would be added new `bool` field that action has been `deleted` that would be updated to true on deleting comment etc

File: models/action.go [hunk 9]
```diff
@@ -191,6 +194,37 @@ func (a *Action) GetRepoLink() string {
...
+		return a.Comment.HTMLURL()
+	}
+	if len(a.GetIssueInfos()) == 0 {
+		return "#"
+	}
+	//Return link to issue
+	issueIDString := a.GetIssueInfos()[0]
+	issueID, err := strconv.ParseInt(issueIDString, 10, 64)
+
+	if err != nil {
```
Comment (lafriks) [inline models/action.go]: Please remove newline before `if err != nil {`

File: models/action.go [hunk 10]
```diff
@@ -191,6 +194,37 @@ func (a *Action) GetRepoLink() string {
...
+		return "#"
+	}
+
+	issue, err := GetIssueByID(issueID)
+
+	if err != nil {
```
Comment (lafriks) [inline models/action.go]: Please remove newline before `if err != nil {`

**Review by lafriks — CHANGES_REQUESTED** [review]

File: models/action.go [hunk 11]
```diff
@@ -71,20 +71,21 @@ func init() {
...
+	ID             int64 `xorm:"pk autoincr"`
+	UserID         int64 `xorm:"INDEX"` // Receiver user id.
+	OpType         ActionType
+	ActUserID      int64       `xorm:"INDEX"` // Action user id.
+	ActUser        *User       `xorm:"-"`
+	RepoID         int64       `xorm:"INDEX"`
+	Repo           *Repository `xorm:"-"`
+	CommentID      int64       `xorm:"INDEX"`
+	Comment        *Comment    `xorm:"-"`
+	CommentDeleted bool        `xorm:"default 0 not null"`
```
Comment (lafriks) [inline models/action.go]: Do not use 0 and 1 but true and false just like it is used in IsPrivate. Cant this field be reused for other optypes also?  So maybe is better call it IsDeleted?

File: models/issue_comment.go [hunk 12]
```diff
@@ -641,5 +643,7 @@ func DeleteComment(comment *Comment) error {
 		}
 	}
 
+	sess.Exec("UPDATE `action` SET comment_deleted = 1 WHERE comment_id = ?", comment.ID)
```
Comment (lafriks) [inline models/issue_comment.go]: Use xorm update function

**Review by lafriks — CHANGES_REQUESTED** [review]

**Review by bkcsoft — APPROVED** [review]

**Comment by bkcsoft** [comment]
LGTM

**Comment by lafriks** [comment]
Does migration updates deleted field for already deleted comments?

**Comment by bkcsoft** [comment]
@lafriks as discussed in Discord, we have no way of knowing since there was no link between Action and Comment before this PR :(

**Comment by jonasfranz** [comment]
@lafriks CommentID will be added by this migration. Before this, theire was no ability to identify the comment except of the column "content" that only contains a small snippet of text from the original comment. So no way to reconstruct the old comment at all. (besides searching based on the given snippet in "content") :cry:

**Comment by lafriks** [comment]
@JonasFranzDEV @bkcsoft oh right, than it is fine :+1:
