### PR TITLE
Fix adopt repository has empty object name in database

### LINKED ISSUE #31311: Internal Server Error Decoding Failed readObjectStart: expect { or n, but found <, error found in #2 when pushing
### Description

I have a new installation using Docker and have imported repositories using unadopted repositories

I'm able to push to most of them, however for a couple of repos I'm getting the following errors, and am unable to rectify:

Output from the push
```
$ git push origin master
Enumerating objects: 837, done.
Counting objects: 100% (837/837), done.
Delta compression using up to 2 threads
Compressing objects: 100% (439/439), done.
Writing objects: 100% (450/450), 108.70 KiB | 2.42 MiB/s, done.
Total 450 (delta 358), reused 5 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (358/358), completed with 322 local objects.
remote:
remote: Gitea: Internal Server Error Decoding Failed
remote: Gitea: HookPreReceive(last) failed: unable to decode error response "POST http://localhost:3000/api/internal/hook/pre-receive/clients/roadworx": readObjectStart: expect { or n, but found <, error found in #2 byte of ...|
remote: <!DOCTYPE h|..., bigger context ...|
remote: <!DOCTYPE html>
remote: <html lang="en-US" data-theme="gite|...
To ssh://gitea.xxx.xxx:222/clients/roadworx.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://gitea.xxx.xxx:222/clients/roadworx.git'
```

Logs
```
2024/06/11 07:14:41 ...eb/routing/logger.go:78:func1() [W] router: failed    POST /api/internal/hook/pre-receive/clients/roadworx for 172.27.0.2:0, panic in 8.7ms @ private/hook_pre_receive.go:105(private.HookPreReceive), err=runtime error: invalid memory address or nil pointer dereference
2024/06/11 07:14:41 ...rs/common/errpage.go:26:RenderPanicErrorPage() [E] PANIC: runtime error: invalid memory address or nil pointer dereference
```

I've looked through all past issues similar to this but couldn't find a solution.

Cheers,
Ryan

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Docker

### How are you running Gitea?

Using docker

### Database

MySQL/MariaDB

### LINKED ISSUE #31330: Push to repository results in "PANIC: runtime error: invalid memory address or nil pointer dereference"
### Description

We have been porting repositories from a legacy Gitlab instance, and have had no issues except for one particular repository. This repo could not be directly migrated by Gitea; the raw Gitlab repos (*.git) were dropped into the appropriate owner directory on Gitea and successfully adopted by Gitea using the [documented process](https://docs.gitea.com/help/faq#how-to-adopt-repositories-from-disk). Everything looks great and the repo can be successfully cloned over HTTP or SSH.

However, any sort of push operation (commit, branch delete) results in a panic from an "invalid memory address or nil pointer dereference."  The gist includes three different panic origins and their stack traces.

The repo in particular has a few large binary blobs, 17 branches, 630 commits, 235 tags, and occupies 58 MiB. I will note that the ".pack" file under objects/pack occupies 79553430 bytes. We're willing to prune out old commits and branches, but would have to do that off Gitea since push is currently broken, if that is our only option.

I would attempt to reproduce it on the Gitea demo site but the repo contains proprietary IP.

Thank you!

### Gitea Version

1.22.0+41-g3fcf865a4b

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/gmaxwell447/b45ee124ad25e04bdc39619a254d6247

### Screenshots

_No response_

### Git Version

2.39.3

### Operating System

Rocky Release 9.3 with SELinux enabled, Red Hat Server Level 1 Security Profile

### How are you running Gitea?

I have tried the downloaded 1.22.0 binary (gitea_1.22.0_dev-1092-g02d4a62e3) along with the nightly build (1.22.0+41-g3fcf865a4b). Gitea is running on a Hyper-V hosted VM (no container), launched as a systemd service (service file included in gist).

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by lunny**
Fix #31330
Fix #31311

A workaround to fix the old database is to update object_format_name to `sha1` if it's empty or null.

### CODE REVIEW

File: services/context/repo.go [hunk 1]
```diff
@@ -84,7 +84,18 @@ func (r *Repository) CanCreateBranch() bool {
...
+	}
+	if r.GitRepo != nil {
+		objectFormat, err := r.GitRepo.GetObjectFormat()
+		if err == nil {
+			return objectFormat
+		}
+		log.Error("Failed to get object format: %v", err)
+	}
+
+	return git.Sha1ObjectFormat
```
Comment (wxiaoguang) [inline services/context/repo.go]: This logic couldn't be right.

File: services/repository/adopt.go [hunk 2]
```diff
@@ -146,6 +146,12 @@ func adoptRepository(ctx context.Context, repoPath string, repo *repo_model.Repo
 	}
 	defer gitRepo.Close()
 
+	objectFormat, err := gitRepo.GetObjectFormat()
+	if err != nil {
+		return fmt.Errorf("getObjectFormat: %w", err)
+	}
+	repo.ObjectFormatName = objectFormat.Name()
+
```
Comment (wxiaoguang) [inline services/repository/adopt.go]: `SyncRepoBranchesWithRepo` already syncs object format.

File: services/context/repo.go (hunk 1 above)
Comment (lunny) [reply services/context/repo.go]: f887ed08074cc7b7723b8ba0a85c69835cc1bddd

File: services/repository/adopt.go (hunk 2 above)
Comment (lunny) [reply services/repository/adopt.go]: f887ed08074cc7b7723b8ba0a85c69835cc1bddd
I think the column has been updated twice when adopted. The first time it will be updated to the correct content, but continued steps will update it to blank again.

**Review by wxiaoguang — APPROVED** [review]

**Review by a1012112796 — APPROVED** [review]
