### PR TITLE
Fix the issue ref rendering for wiki

### LINKED ISSUE #28526: Regression in Automatic Issue/PR Referencing in Wiki Pages after Upgrading to 1.21.2
### Description

After upgrading from Gitea version 1.20.5 to 1.21.2, I encountered an issue with the automatic issue and pull request referencing feature in Wiki pages. Previously, in version 1.20.5, this functionality was operating as expected. However, since the update to 1.21.2, the feature appears to be non-functional.

I was able to reproduce this issue on a test repository: https://try.gitea.io/loncardom/test/wiki/Home.

This leads me to two questions:

1. Was this capability in Wiki pages an unintended feature in 1.20.5?
2. Is this change in functionality from version 1.20.5 to 1.21.2 a bug, or was it an intentional removal of the feature?

It's worth noting that the [official documentation](https://docs.gitea.com/usage/automatically-linked-references#issues-and-pull-requests) does not explicitly mention Wiki pages in the context of automatic linking, yet this feature was operational in the earlier version (1.20.5).

Gitea is awesome btw.
Thanks

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Running Gitea through docker, though this issue is reproducible on try.gitea.io

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #28526, regression of 
* #26365

(although the author of #26365 has recent activities, but there is no response for the regression, so I proposed this quick fix and keep the fix simple to make it easier to backport to 1.21)

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

File: modules/markup/html.go [hunk 1]
```diff
@@ -852,7 +852,9 @@ func fullIssuePatternProcessor(ctx *RenderContext, node *html.Node) {
 }
 
 func issueIndexPatternProcessor(ctx *RenderContext, node *html.Node) {
-	if ctx.Metas == nil || ctx.Metas["mode"] == "document" {
+	// FIXME: the use of "mode" is quite dirty and hacky, for example: what is a "document"? how should it be rendered?
+	// The "mode" approach should be refactored to some other more clear&reliable way.
+	if ctx.Metas == nil || (ctx.Metas["mode"] == "document" && !ctx.IsWiki) {
```
Comment (lunny) [inline modules/markup/html.go:857]: ~ctx.IsWiki?~

Comment (wxiaoguang) [reply modules/markup/html.go:857]: What do you mean?

**Review by lunny — APPROVED** [review]

File: modules/markup/html.go (hunk 1 above)
Comment (lunny) [reply modules/markup/html.go:857]: I made a mistake. Approved.

**Review by delvh — APPROVED** [review]
