### PR TITLE
Fix incorrect webhook time and use relative-time to display it

### LINKED ISSUE #24414: Webhook time will be 1970-01-01 00:00:00 UTC after click replay this webhook
### Description

image

Refresh the page will display the correct time.

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### PR DESCRIPTION
**Pull request by yp05327**
Fixes #24414
After click replay this webhook, it will display `now`
image

### CODE REVIEW

File: modules/templates/helper.go [hunk 1]
```diff
@@ -66,12 +66,13 @@ func NewFuncMap() template.FuncMap {
...
 		// time / number / format
-		"FileSize":      base.FileSize,
-		"CountFmt":      base.FormatNumberSI,
-		"TimeSince":     timeutil.TimeSince,
-		"TimeSinceUnix": timeutil.TimeSinceUnix,
-		"DateTime":      timeutil.DateTime,
-		"Sec2Time":      util.SecToTime,
+		"FileSize":       base.FileSize,
+		"CountFmt":       base.FormatNumberSI,
+		"Int64TimeSince": timeutil.Int64TimeSince,
```
Comment (wxiaoguang) [inline modules/templates/helper.go]: It doesn't look good. And the  `Delivered` is surprisingly  a bad design since 2015 ......

I would suggest to use `time.Time` to convert `Delivered` in model and then use `TimeSince` to render it directly, then no need to add this template helper function

Comment (wxiaoguang) [reply modules/templates/helper.go]: We can add a `type TimeStampNano int64` type , and add an `AsTime` function for it.

```
Delivered TimeStampNano
```

```
{{TimeSince .Delivered.AsTime}}
```

Comment (yp05327) [reply modules/templates/helper.go]: ~~Will this cause a db change? 
I didn't convert it into  `time.Time` here because I'm not sure whether this may cause a db change.~~

It seems that this will not cause a db change.

Comment (yp05327) [reply modules/templates/helper.go]: We have `timeutil.TimeStamp`, maybe we can add `timeutil.TimeStampNano`

File: modules/timeutil/timestampnano.go [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+package timeutil
+
+import (
+	"time"
+
+	"code.gitea.io/gitea/modules/setting"
+)
+
+// TimeStampNano defines a nano timestamp
+type TimeStampNano int64
```
Comment (wxiaoguang) [inline modules/timeutil/timestampnano.go:13]: I would suggest to keep this file simple and leave a comment: do not use this anymore ..... it's only for that special case. 😁 

Only the following is enough:

```go

// TimeStampNano is for nano time in database, do not use it unless there is a real requirement.
type TimeStampNano int64

func TimeStampNanoNow() TimeStampNano {
	return TimeStampNano(time.Now().UnixNano())
}

func (tsn TimeStampNano) AsTime() (tm time.Time) {
	return ....
}
```

Comment (yp05327) [reply modules/timeutil/timestampnano.go:13]: Done.

**Review by wxiaoguang — APPROVED** [review]

File: templates/repo/settings/webhook/history.tmpl [hunk 3]
```diff
@@ -21,7 +21,7 @@
 						<a class="ui primary sha label toggle button show-panel" data-panel="#info-{{.ID}}">{{.UUID}}</a>
 						<div class="ui right">
 							<span class="text grey time">
-								{{.DeliveredString}}
+								{{TimeSince .Delivered.AsTime $.lcoale}}
```
Comment (silverwind) [inline templates/repo/settings/webhook/history.tmpl]: Typo `lcoale`?

Comment (wxiaoguang) [reply templates/repo/settings/webhook/history.tmpl]:
```suggestion
								{{TimeSince .Delivered.AsTime $.locale}}
```

yes, it's typo , and actually this argument is never used by backend, so no error occurs.

**Review by silverwind — APPROVED** [review]
