### PR TITLE
Fix a UI error when folding a file content in a commit view

### LINKED ISSUE #17445: UI error when viewing a commit (clicking the down arrow)
https://try.gitea.io/ChristopherHX/actions-on-gitea/commit/eea6f360d405f8462ff2eb409b4362a049033efc

There is another bug, also record here:

Clicking the down arrow beside the number "10" of the filename triggers another error:

image

_Originally posted by @wxiaoguang in https://github.com/go-gitea/gitea/issues/17443#issuecomment-952514815_

### PR DESCRIPTION
**Pull request by wxiaoguang**
* Close #17445
* Fix a bug introduced by #16829

### CODE REVIEW

File: web_src/js/features/repo-code.js [hunk 1]
```diff
@@ -131,9 +131,8 @@ export function initRepoCodeView() {
   }
   $(document).on('click', '.fold-file', ({currentTarget}) => {
     const box = currentTarget.closest('.file-content');
-    const chevron = currentTarget.querySelector('a.chevron');
     const folded = box.dataset.folded !== 'true';
-    chevron.innerHTML = svg(`octicon-chevron-${folded ? 'right' : 'down'}`, 18);
+    currentTarget.innerHTML = svg(`octicon-chevron-${folded ? 'right' : 'down'}`, 18);
```
Comment (delvh) [inline web_src/js/features/repo-code.js:135]: I have no idea what the difference is between these two changes.
I mean, I like that we no longer have a dependency on `chevron` classes inside links. But why isn't it necessary anymore?

File: templates/repo/diff/box.tmpl [hunk 2]
```diff
@@ -59,7 +59,7 @@
 				{{$showFileViewToggle := or $isImage (and (not $file.IsIncomplete) $isCsv)}}
 				<div class="diff-file-box diff-box file-content {{TabSizeClass $.Editorconfig $file.Name}} mt-3" id="diff-{{.Index}}" data-old-filename="{{$file.OldName}}" data-new-filename="{{$file.Name}}" {{if $file.IsGenerated}}data-folded="true"{{end}}>
 					<h4 class="diff-file-header sticky-2nd-row ui top attached normal header df ac sb">
-						<div class="fold-file df ac">
+						<div class="df ac">
```
Comment (delvh) [inline templates/repo/diff/box.tmpl:62]: Do I see it correctly that this `fold-file` was removed because it is used in the `<a>` right below?

File: web_src/js/features/repo-code.js (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/features/repo-code.js:135]: That's the fix.

File: templates/repo/diff/box.tmpl (hunk 2 above)
Comment (wxiaoguang) [reply templates/repo/diff/box.tmpl:62]: That's the fix.

File: web_src/js/features/repo-code.js (hunk 1 above)
Comment (delvh) [reply web_src/js/features/repo-code.js:135]: Yeah, I thought so. But what was the bug it caused? That it did not generate the svg for some elements to which it should generate it?

**Review by delvh — APPROVED** [review]

File: web_src/js/features/repo-code.js (hunk 1 above)
Comment (wxiaoguang) [reply web_src/js/features/repo-code.js:135]: The HTML layout and CSS names were changed by "Add buttons to allow loading of incomplete diffs #16829"

**Review by lunny — APPROVED** [review]
