### PR TITLE
Fix various bugs

### LINKED ISSUE #35651: gitea returning 404 responses for theme css file, but not logging anything at server side
### Description

_No response_

### Gitea Version

1.24.6

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

The problem is a lack of logs, so there is no log to upload...

After upgrading gitea from when the default theme was "auto" to 1.24.6 where it is "gitea-auto" we started seeing a lot of issues in the web ui. further inspection revealed that the browser got 404 responses for the theme-auto.css file.

while trying to debug this i set log level up from Warn to Info and Debug. i could see the 200 responses for the web page, but nothing for the failed css files. this led me down a rabbit hole chasing why the query never arrived. 

the fix, of course, was to simply comment out the setting of THEMES and DEFAULT_THEME in the ini file.

the serious bug here is why gitea wasn't logging anything about sending out 404 responses for non-existing theme files.

### Git Version

2.47.3

### Operating System

RHEL 9.6

### How are you running Gitea?

downloaded binary originally installed using geerlingguy ansible class. the upgrade was done manually.

### Database

None

### LINKED ISSUE #35695: Debian repo does not support the multi digit epoch
## Summary
  Debian versions can start with an epoch, which Debian policy describes as an unsigned integer. Right now our validator only accepts a single digit there, so any version like `100:2.0.1` gets rejected. That’s blocking us from re-publishing a few upstream packages.

  ## Steps to Reproduce
  1. Import a Debian package whose version begins with a multi-digit epoch, e.g. `100:2.0.1`.
  2. During `ParseControlFile`, the check in `modules/packages/debian/metadata.go` fails because `versionPattern` allows only `[0-9]:`.

  ## Expected Behavior
  Versions with any valid unsigned epoch (including multi-digit values) should pass validation.

  ## Actual Behavior
  The parser throws `package version is invalid`, stopping packages with epochs greater than 9.

  ## Environment
  - gitea: current main
  - module: `modules/packages/debian/metadata.go`

Example of repo with such packages:
https://gist.github.com/sebastianwebber/2c1e9c7df97e05479f22a0d13c00aeca#install-buildah-ubuntu-2004md
```
apt-get install -y --download-only buildah=100:1.22.3-2
ls -lrt /var/cache/apt/archives/
total 8592
-rw-r--r-- 1 root root 7276300 May 24  2022 buildah_100%3a1.22.3-2_amd64.deb
-rw-r----- 1 root root       0 Aug 26  2022 lock
-rw-r--r-- 1 root root  297820 Mar 13  2023 python3-protobuf_3.6.1.3-2ubuntu5.2_amd64.deb
-rw-r--r-- 1 root root  120376 Oct 14  2023 libgpgme11_1.13.1-7ubuntu2.2_amd64.deb
-rw-r--r-- 1 root root   20720 Dec 14  2023 libyajl2_2.1.0-3ubuntu0.20.04.1_amd64.deb
-rw-r--r-- 1 root root   26016 Feb 15  2024 uidmap_1%3a4.8.1-1ubuntu5.20.04.5_amd64.deb
-rw-r--r-- 1 root root  732520 Aug 15 08:03 criu_4.1.1-3_amd64.deb
-rw-r--r-- 1 root root  251844 Aug 15 08:04 crun_100%3a1.2-2_amd64.deb
-rw-r--r-- 1 root root   52372 Oct 18 14:34 containers-common_100%3a1-22_all.deb
drwx------ 1 _apt root    4096 Oct 18 14:34 partial
```
%3a -> : 

### Gitea Version

1.24.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.49.1

### Operating System

Alpine 3.22.0

### How are you running Gitea?

Helm chart deployment. 

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by wxiaoguang**
1. Fix incorrect column in `applySubscribedCondition`, add a test
2. Fix debian version parsing, add more tests fix #35695
3. Fix log level for HTTP errors, fix #35651
4. Fix abused "panic" handler in API `Migrate`
5. Fix the redirection from PR to issue, add a test
6. Fix Actions variable & secret name validation, add more tests
    * envNameCIRegexMatch is unnecessary, removed
    * validating in "delete" function doesn't make sense, removed
7. Fix incorrect link in release email

### CODE REVIEW

File: routers/api/v1/repo/migrate.go [hunk 1]
```diff
@@ -187,35 +187,35 @@ func Migrate(ctx *context.APIContext) {
...
+			if e := recover(); e != nil {
+				log.Error("MigrateRepository panic: %v\n%s", e, log.Stack(2))
+				if errDelete := repo_service.DeleteRepositoryDirectly(ctx, createdRepo.ID); errDelete != nil {
+					log.Error("Unable to delete repo after MigrateRepository panic: %v", errDelete)
+				}
+				retErr = errors.New("MigrateRepository panic") // no idea why it would happen, just legacy code
 			}
+		}()
+
+		migratedRepo, err := migrations.MigrateRepository(graceful.GetManager().HammerContext(), doer, repoOwner.Name, opts, nil)
```
Comment (lunny) [inline routers/api/v1/repo/migrate.go]: Could you add a comment explaining why this uses the hammer context instead of the shutdown context?

Comment (wxiaoguang) [reply routers/api/v1/repo/migrate.go]: Old code uses it, I don't think it is right, but I don't want to do more unnecessary changes.

Maybe you can ask the original author: Sleep longer if request speed is over github limitation (#9335)

And yes, it's you.

image

**Review by lunny — APPROVED** [review]

File: modules/web/routing/logger.go [hunk 2]
```diff
@@ -104,7 +104,8 @@ func logPrinter(logger log.Logger) func(trigger Event, record *requestRecord) {
 		}
 		logf := logInfo
 		// lower the log level for some specific requests, in most cases these logs are not useful
-		if strings.HasPrefix(req.RequestURI, "/assets/") /* static assets */ ||
+		if 0 < status && status < 400 &&
```
Comment (delvh) [inline modules/web/routing/logger.go]:
```suggestion
		if status > 0 && status < 400 &&
```
reads more intuitively to me

**Review by delvh — APPROVED** [review]
