### PR TITLE
Edit file workflow for creating a fork and proposing changes

### LINKED ISSUE #9017: Creating fork and submit PR to origin automatically when editing file from UI with read-only permission
## versions

- Gitea version : 2.16.5
- Git version: 1.10
- Operating system: linux
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes

## Description

I'm got a site with docs as code using a static site
generator.

It gives the end user an edit button.

The edit button takes them to the repo at this URL:

https://gitea.example.com/org/project/_edit/master/docs/index.md

This opens and works fine, if the user has write access to the repo.

If the user does have write access to the repo all is well and one can
edit the doc and save to master.

If one has read access but not write to repo this however fails with a 404.

On GitLab/GitHub, instead the page renders and in the background a
fork is automatically created and a PR is submitted to origin.

### PR DESCRIPTION
**Pull request by brechtvl**
When viewing a file that the user can't edit because they can't write to
the branch, the new, upload, patch, edit and delete functionality is no
longer disabled.

If no user fork of the repository exists, there is now a page to create one.
It will automatically create a fork with a single branch matching the one
being viewed, and a unique repository name will be automatically picked.

When a fork exists, but it's archived, a mirror or the user can't write
code to it, there will instead be a message explaining the situation.

If the usable fork exists, a message will appear at the top of the edit page
explaining that the changes will be applied to a branch in the fork. The
base repository branch will be pushed to a new branch to the fork, and
then the edits will be applied on top.

The suggestion to fork happens when accessing /_edit/, so that for
example online documentation can have an "edit this page" link to
the base repository that does the right thing.

Also includes changes to properly report errors when trying to commit
to a new branch that is protected, and when trying to commit to an
existing branch when choosing the new branch option.

Resolves #9017, #20882

---

fork

not_directly_editable

archived

### CODE REVIEW

**Comment by lunny** [comment]
1 A middle page may be necessary like GH did? Looks like GH will not display a fork form page and will fork at the backend.

image

2 The branches may be fixed as `All branches` to prevent to choose a wrong branch

3 Is that really necessary to allow user to fork to an organization when forking for the edit?

4 The edit button on README file of repository home page could be displayed.

File: routers/web/repo/editor.go [hunk 1]
```diff
@@ -45,6 +46,41 @@ func canCreateBasePullRequest(ctx *context.Context) bool {
...
+	}
+
+	link := setting.AppSubURL + ctx.Req.URL.RequestURI()
+	if len(userAndOrgForks) > 0 {
+		// Redirect to user repository
+		forkRepo := userAndOrgForks[0]
+		ctx.Redirect(repo.AdaptLinkToFork(forkRepo, link))
+	} else {
+		// Redirect to create new user repository
+		ctx.Redirect(repo.Link() + "/fork/?redirect_to_edit=" + url.QueryEscape(link))
```
Comment (lunny) [inline routers/web/repo/editor.go]: The branch might be outdated, and a simple redirect may not be sufficient.

File: routers/web/repo/editor.go [hunk 2]
```diff
@@ -45,6 +46,41 @@ func canCreateBasePullRequest(ctx *context.Context) bool {
...
+	userAndOrgForks, err := repo_model.GetForksByUserAndOrgs(ctx, ctx.Doer, repo)
+	if err != nil {
+		ctx.ServerError("GetForksByUserAndOrgs", err)
+		return true
+	}
+
+	// When already on a repo the user owns, don't redirect further even if
+	// writing to the branch is not possible.
+	for _, forkRepo := range userAndOrgForks {
+		if forkRepo.ID == repo.ID {
```
Comment (lunny) [inline routers/web/repo/editor.go]: I don't quite understand the logic. All repositories on `userAndOrgForks` should be forks of `repo`, looks like it's impossible `forkRepo.ID == repo.ID`.

**Comment by brechtvl** [comment]
I rewrote the whole thing, which should hopefully address all the comments.

I think the permissions checking is rather confusing now.  Previously `ctx.Repo.CanWriteToBranch`, `ctx.Repo.CanEnableEditor` and `ctx.Repo.MustBeEditable` were easy to understand, but now that two repositories are involved it's no so simple anymore. Maybe I should add a `ctx.Repo.UserFork` into the context, so that these functions can use it? Suggestions welcome.

**Comment by lunny** [comment]
Fork repository was created after clicking the `fork the repository` button. But it redirects to 404 . And when I re edit the file, 
image

**Comment by wxiaoguang** [comment]
The "fork" logic has too much legacy patched code, it seems that it is not good to introduce more patches.

And I think it needs tests to make sure the logic is overall right.

Do we have enough time to take it into 1.24? (TBH I guess no)

File: routers/web/repo/editor.go [hunk 3]
```diff
@@ -40,37 +40,47 @@ const (
...
+	baseRepo := editRepo.BaseRepo
 	return baseRepo != nil && baseRepo.UnitEnabled(ctx, unit.TypePullRequests)
 }
 
-func renderCommitRights(ctx *context.Context) bool {
-	canCommitToBranch, err := ctx.Repo.CanCommitToBranch(ctx, ctx.Doer)
-	if err != nil {
-		log.Error("CanCommitToBranch: %v", err)
+func renderCommitRights(ctx *context.Context, editRepo *repo_model.Repository) bool {
+	if editRepo == ctx.Repo.Repository {
```
Comment (lunny) [inline routers/web/repo/editor.go]:
```suggestion
	if editRepo.ID == ctx.Repo.Repository.ID {
```

File: routers/web/repo/fork_to_edit.go [hunk 4]
```diff
@@ -0,0 +1,240 @@
+// Copyright 2016 The Gogs Authors. All rights reserved.
```
Comment (lunny) [inline routers/web/repo/fork_to_edit.go]: If this copied from Gogs?

```suggestion
// Copyright 2025 The Gitea Authors. All rights reserved.
```

File: routers/web/web.go [hunk 5]
```diff
@@ -1314,25 +1314,28 @@ func registerWebRoutes(m *web.Router) {
 	m.Group("/{username}/{reponame}", func() { // repo code
 		m.Group("", func() {
 			m.Group("", func() {
-				m.Post("/_preview/*", web.Bind(forms.EditPreviewDiffForm{}), repo.DiffPreviewPost)
```
Comment (lunny) [inline routers/web/web.go]: Why this line removed? Accidentally?

File: routers/web/repo/editor.go (hunk 3 above)
Comment (brechtvl) [reply routers/web/repo/editor.go]: Will change it here and in two other places.

File: routers/web/repo/fork_to_edit.go (hunk 4 above)
Comment (brechtvl) [reply routers/web/repo/fork_to_edit.go]: There is a bit of code moved from the existing `editor.go`, so I added an additional copyright line instead of replacing it.

File: routers/web/web.go (hunk 5 above)
Comment (brechtvl) [reply routers/web/web.go]: Ouch, removed by accident indeed. I added a test for it now.

File: services/context/repo.go [hunk 6]
```diff
@@ -67,13 +67,19 @@ type Repository struct {
...
+	return issues_model.CanMaintainerWriteToBranch(ctx, permission, branch, user)
 }
 
-// CanEnableEditor returns true if repository is editable and user has proper access level.
-func (r *Repository) CanEnableEditor(ctx context.Context, user *user_model.User) bool {
-	return r.RefFullName.IsBranch() && r.CanWriteToBranch(ctx, user, r.BranchName) && r.Repository.CanEnableEditor() && !r.Repository.IsArchived
+// CanEnableEditor returns true if the web editor can be enabled for this repository,
+// either by directly writing to the repository or to a user fork.
+func (r *Repository) CanEnableEditor() bool {
+	return r.RefFullName.IsBranch() && r.Repository.CanEnableEditor()
```
Comment (lunny) [inline services/context/repo.go]: Keep `&& !r.Repository.IsArchived`?

Comment (brechtvl) [reply services/context/repo.go]: That is now checked as part of `r.Repository.CanEnableEditor()`

**Review by lunny — APPROVED** [review]

**Review by hiifong — APPROVED** [review]

File: routers/web/repo/fork_to_edit.go [hunk 7]
```diff
@@ -0,0 +1,241 @@
...
+	return branchName, nil
+}
+
+// updateEditRepositoryIsEmpty updates the the edit repository to mark it as no longer empty
+func updateEditRepositoryIsEmpty(ctx *context.Context, editRepo *repo_model.Repository) {
+	if !editRepo.IsEmpty {
+		return
+	}
+
+	editGitRepo, err := gitrepo.OpenRepository(git.DefaultContext, editRepo)
```
Comment (wxiaoguang) [inline routers/web/repo/fork_to_edit.go]: It shouldn't use `git.DefaultContext`

File: routers/web/repo/fork_to_edit.go [hunk 8]
```diff
@@ -0,0 +1,241 @@
...
+	if err != nil {
+		log.Error("gitrepo.OpenRepository: %v", err)
+		return
+	}
+	if editGitRepo == nil {
```
Comment (wxiaoguang) [inline routers/web/repo/fork_to_edit.go]: Why it would be `nil`?

File: routers/web/repo/fork_to_edit.go [hunk 9]
```diff
@@ -0,0 +1,241 @@
...
+		return
+	}
+
+	if isEmpty, err := editGitRepo.IsEmpty(); err == nil && !isEmpty {
+		_ = repo_model.UpdateRepositoryCols(ctx, &repo_model.Repository{ID: editRepo.ID, IsEmpty: false}, "is_empty")
+	}
+	editGitRepo.Close()
```
Comment (wxiaoguang) [inline routers/web/repo/fork_to_edit.go]: It should use `defer`, or just use RequestContext, then no need to close.

File: routers/web/repo/fork_to_edit.go [hunk 10]
```diff
@@ -0,0 +1,241 @@
...
+}
+
+func forkToEditFileCommon(ctx *context.Context, editOperation, treePath string, notEditableMessage any) {
+	// Check if the filename (and additional path) is specified in the querystring
+	// (filename is a misnomer, but kept for compatibility with GitHub)
+	filePath, _ := path.Split(ctx.Req.URL.Query().Get("filename"))
+	filePath = strings.Trim(filePath, "/")
+	treeNames, treePaths := getParentTreeFields(path.Join(ctx.Repo.TreePath, filePath))
```
Comment (wxiaoguang) [inline routers/web/repo/fork_to_edit.go]: Why these two "paths" could be joint?

File: templates/repo/view_content.tmpl [hunk 11]
```diff
@@ -41,8 +41,9 @@
 		<a href="{{.Repository.Link}}/find/{{.RefTypeNameSubURL}}" class="ui compact basic button">{{ctx.Locale.Tr "repo.find_file.go_to_file"}}</a>
 	{{end}}
 
-	{{if and .CanWriteCode .RefFullName.IsBranch (not .Repository.IsMirror) (not .Repository.IsArchived) (not .IsViewFile)}}
-		<button class="ui dropdown basic compact jump button"{{if not .Repository.CanEnableEditor}} disabled{{end}}>
+	{{if and .RefFullName.IsBranch (not .IsViewFile) .Repository.CanEnableEditor}}
+		<button class="ui dropdown basic compact jump button"
```
Comment (wxiaoguang) [inline templates/repo/view_content.tmpl]: IIRC disabled button is not able to show tooltip

File: templates/repo/view_file.tmpl [hunk 12]
```diff
@@ -77,8 +77,12 @@
 				<button class="ui mini basic button unescape-button tw-mr-1 tw-hidden">{{ctx.Locale.Tr "repo.unescape_control_characters"}}</button>
 				<button class="ui mini basic button escape-button tw-mr-1">{{ctx.Locale.Tr "repo.escape_control_characters"}}</button>
 			{{end}}
-			{{if and .ReadmeInList .CanEditReadmeFile}}
-				<a class="btn-octicon" data-tooltip-content="{{ctx.Locale.Tr "repo.editor.edit_this_file"}}" href="{{.RepoLink}}/_edit/{{PathEscapeSegments .BranchName}}/{{PathEscapeSegments .FileTreePath}}">{{svg "octicon-pencil"}}</a>
+			{{if and .ReadmeInList .Repository.CanEnableEditor}}
+				{{if .CanEditReadmeFile}}
+					<a class="btn-octicon" data-tooltip-content="{{.EditReadmeFileTooltip}}" href="{{.RepoLink}}/_edit/{{PathEscapeSegments .BranchName}}/{{PathEscapeSegments .FileTreePath}}">{{svg "octicon-pencil"}}</a>
+				{{else}}
+					<span class="btn-octicon disabled" data-tooltip-content="{{.EditReadmeFileTooltip}}">{{svg "octicon-pencil"}}</span>
```
Comment (wxiaoguang) [inline templates/repo/view_file.tmpl]: Does `disabled` work with `btn-octicon`? (IIRC no ....)

File: templates/repo/editor/fork.tmpl [hunk 13]
```diff
@@ -0,0 +1,41 @@
+{{template "base/head" .}}
+<div role="main" aria-label="{{.Title}}" class="page-content repository file editor edit">
+	{{template "repo/header" .}}
+	<div class="ui container">
+		{{template "base/alert" .}}
+		<form class="ui edit form" method="post" action="{{.RepoLink}}/_fork_to_edit/{{.BranchName | PathEscapeSegments}}">
+			{{.CsrfTokenHtml}}
+			<input type="hidden" name="page_has_posted" value="{{.PageHasPosted}}">
```
Comment (wxiaoguang) [inline templates/repo/editor/fork.tmpl]: Is it used?

File: templates/repo/editor/fork.tmpl [hunk 14]
```diff
@@ -0,0 +1,41 @@
...
+					{{range $i, $v := .TreeNames}}
+						<div class="breadcrumb-divider">/</div>
+						{{if eq $i $l}}
+							<span class="section">{{$v}}</span>
+						{{else}}
+							<span class="section"><a href="{{$.BranchLink}}/{{index $.TreePaths $i | PathEscapeSegments}}">{{$v}}</a></span>
+						{{end}}
+					{{end}}
+					<input type="hidden" id="tree_path" name="tree_path" value="{{.TreePath}}" required>
+					<input type="hidden" id="edit_operation" name="edit_operation" value="{{.EditOperation}}" required>
```
Comment (wxiaoguang) [inline templates/repo/editor/fork.tmpl]: Are these `id`s used?

File: templates/repo/editor/fork.tmpl (hunk 13 above)
Comment (brechtvl) [reply templates/repo/editor/fork.tmpl]: Not used indeed, will remove.

File: templates/repo/view_file.tmpl (hunk 12 above)
Comment (brechtvl) [reply templates/repo/view_file.tmpl]: It seems to work,I see a grayed out pencil when logged out.

File: templates/repo/editor/fork.tmpl (hunk 14 above)
Comment (brechtvl) [reply templates/repo/editor/fork.tmpl]: Yes, they are used in `ForkToEditFilePost` to redirect to the appropriate editing page after the fork was created.

File: templates/repo/view_content.tmpl (hunk 11 above)
Comment (brechtvl) [reply templates/repo/view_content.tmpl]: Indeed, it seems to not show up. I'll just hide the button again when not signed in then. Slightly inconsistent with the Edit button, but it already was before.

File: routers/web/repo/fork_to_edit.go (hunk 10 above)
Comment (brechtvl) [reply routers/web/repo/fork_to_edit.go]: I copied this from `editFile`, but it doesn't seem to be needed here so will simplify to `ctx.Repo.TreePath`.

File: routers/web/repo/fork_to_edit.go (hunk 9 above)
Comment (brechtvl) [reply routers/web/repo/fork_to_edit.go]: I added `defer`.

I'm unsure about what RequestContext means here. If it's `ctx.Repo.GitRepo`, that's a different repository when editing a fork.

File: templates/repo/editor/fork.tmpl (hunk 14 above)
Comment (wxiaoguang) [reply templates/repo/editor/fork.tmpl]: But `ForkToEditFilePost` only uses `name` ,  but not `id`? If `id` is used for any purpose, only frontend really needs it.

Comment (brechtvl) [reply templates/repo/editor/fork.tmpl]: Ah, of course. I removed them now.

File: routers/web/repo/fork_to_edit.go (hunk 9 above)
Comment (wxiaoguang) [reply routers/web/repo/fork_to_edit.go]: After reading context logic, I think it could be like this?

https://github.com/go-gitea/gitea/pull/34240/commits/e78c6c463f3491b8401fcdf49f82a02fcd2eb041

Because when this function is called, we are sure that the repo is never empty.

Comment (brechtvl) [reply routers/web/repo/fork_to_edit.go]: Ah yeah, even better.

File: options/locale/locale_en-US.ini [hunk 15]
```diff
@@ -1395,6 +1395,16 @@ editor.user_no_push_to_branch = User cannot push to branch
 editor.require_signed_commit = Branch requires a signed commit
 editor.cherry_pick = Cherry-pick %s onto:
 editor.revert = Revert %s onto:
+editor.fork_create = Fork Repository to Propose Changes
+editor.fork_create_description = You can not edit this repository directly. Instead you can create a fork, make edits and create a pull request.
+editor.fork_edit_description = You can not edit this repository directly. The changes will be written to your fork <b>%s</b>, so you can create a pull request.
+editor.fork_failed_to_push_branch = Failed to push branch %s to your repoitory.
+editor.cannot_find_editable_repo = Can not find repository to apply the edit to. Was it deleted while editing?
+editor.fork_not_editable = Fork Repository Not Editable
+editor.fork_internal_error = Internal error loading repository information about <b>%s</b>.
```
Comment (wxiaoguang) [inline options/locale/locale_en-US.ini]: I think we need to remove this translation, because all "internal errors" are reported as 500 page.

Here it's better to avoid re-inventing the wheel. Will make some changes later.

File: routers/web/web.go [hunk 16]
```diff
@@ -1321,18 +1321,22 @@ func registerWebRoutes(m *web.Router) {
...
+					Post(web.Bind(forms.ForkToEditRepoFileForm{}), repo.ForkToEditFilePost)
+			}, context.MustEnableEditor())
+			m.Group("", func() {
 				m.Combo("/_cherrypick/{sha:([a-f0-9]{7,64})}/*").Get(repo.CherryPick).
 					Post(web.Bind(forms.CherryPickForm{}), repo.CherryPickPost)
-			}, context.RepoRefByType(git.RefTypeBranch), context.CanWriteToBranch(), repo.WebGitOperationCommonData)
-			m.Group("", func() {
-				m.Post("/upload-file", repo.UploadFileToServer)
-				m.Post("/upload-remove", web.Bind(forms.RemoveUploadFileForm{}), repo.RemoveUploadFileFromServer)
-			}, repo.MustBeAbleToUpload, reqRepoCodeWriter)
```
Comment (wxiaoguang) [inline routers/web/web.go]: The `reqRepoCodeWriter` permission check is missing? Then any code reader could call these route handlers?

**Comment by wxiaoguang** [comment]
Thank your your work but sorry IMO we can't go with it like this.

I think it messed up the permission system. @lunny @hiifong please review again and suggest, or correct me if I was wrong.

File: routers/web/web.go (hunk 16 above)
Comment (brechtvl) [reply routers/web/web.go]: Sorry about that, hopefully it's fixed now.

File: options/locale/locale_en-US.ini (hunk 15 above)
Comment (brechtvl) [reply options/locale/locale_en-US.ini]: I fixed this one as well, not sure it matches what you had in mind.

File: routers/web/web.go (hunk 16 above)
Comment (lunny) [reply routers/web/web.go]: The permission check should be like `reqRepoCodeWriter || (reqRepoCodeReader && reqRepoPullRequestReader)`

File: services/context/repo.go [hunk 17]
```diff
@@ -76,6 +76,58 @@ func CanWriteToBranch(ctx context.Context, user *user_model.User, repo *repo_mod
...
+
+// GetEditRepository returns the repository where the editor will actually write the
+// the edits to. This may be a fork of the repository owned by the user. If no repository
+// can be found for editing, either a reason or error is returned.
+func GetEditableRepository(ctx context.Context, user *user_model.User, repo *repo_model.Repository, branch string) (*repo_model.Repository, RepositoryNotEditableMessage, error) {
+	if CanWriteToBranch(ctx, user, repo, branch) {
+		return repo, RepositoryNotEditableMessage{}, nil
+	}
+
+	// If we can't write to the branch, try find a user fork to create a branch in instead
```
Comment (lunny) [inline services/context/repo.go]: We just need to check whether the user will be allowed to send pull request to the repository. The check could be done in the routers definition file. ref https://github.com/go-gitea/gitea/pull/34240/files#r2082805447

Comment (brechtvl) [reply services/context/repo.go]: I added this check now in `CanEnableEditor`, so that the same test can be used for both the router and templates. I also needed to check `CanWriteToBranch` instead of just can write code, so maintainers can edit files in forks.

File: routers/web/repo/editor.go [hunk 18]
```diff
@@ -869,11 +906,11 @@ func RemoveUploadFileFromServer(ctx *context.Context) {
 // It will be in the form of <username>-patch-<num> where <num> is the first branch of this format
 // that doesn't already exist. If we exceed 1000 tries or an error is thrown, we just return "" so the user has to
 // type in the branch name themselves (will be an empty field)
-func GetUniquePatchBranchName(ctx *context.Context) string {
+func GetUniquePatchBranchName(ctx *context.Context, editRepo *repo_model.Repository) string {
 	prefix := ctx.Doer.LowerName + "-patch-"
 	for i := 1; i <= 1000; i++ {
```
Comment (hiifong) [inline routers/web/repo/editor.go]: "i < 1000", it would be better if the number of branches could be used instead, although this condition is fine in most cases, but it can fail to work in some extreme cases.

**Review by hiifong — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Thank you for the update, but I think the design still breaks the Gitea's permission system, and would introduce more security problems in the future.

The problem is: all the existing logic bases on the fact that "middleware checks web ctx permissions" and "when permission check passes, the ctx contains the related targets (ctx.Repo)"

But this PR's design changes the ctx middleware behaviors, now every handler must process "GetEditableRepository" correctly and can't assume ctx.Repo is writable.

TBH I can't tell easily whether there would be more security problems, I would say no to this design, while I won't block it if you can guarantee the security is as solid as before.

File: routers/web/repo/editor.go (hunk 18 above)
Comment (brechtvl) [reply routers/web/repo/editor.go]: Agree, though this is not new code. Is it worth changing as part of this PR?

**Comment by brechtvl** [comment]
> Thank you for the update, but I think the design still breaks the Gitea's permission system, and would introduce more security problems in the future.
> 
> The problem is: all the existing logic bases on the fact that "middleware checks web ctx permissions" and "when permission check passes, the ctx contains the related targets (ctx.Repo)"
> 
> But this PR's design changes the ctx middleware behaviors, now every handler must process "GetEditableRepository" correctly and can't assume ctx.Repo is writable.

I agree this is a weakness, though I also don't have a good idea for how to do it differently. I considered switching the repos around and making `ctx.Repo` the editable one, but couldn't figure out a good way to do it.

> TBH I can't tell easily whether there would be more security problems, I would say no to this design, while I won't block it if you can guarantee the security is as solid as before.

I've tripled checked everything by now. But I'm not sure how I could guarantee something like this. The logic is fundamentally more complicated and there are more chances for something to go wrong.

File: routers/web/web.go (hunk 16 above)
Comment (lunny) [reply routers/web/web.go]: Maybe you can move the permission checking here.

Comment (brechtvl) [reply routers/web/web.go]: I'm not sure what you mean? The permission check is now in `MustBeAbleToUpload`.

`reqRepoCodeWriter` and `reqRepoCodeReader` are functions, and I don't think I can combine them with `||` and `&&` operators.

The check I added in `MustBeAbleToUpload` is also different. It requires having a repository that can be written to, which I think matches what it was before. With `reqRepoCodeReader && reqRepoPullRequestReader` a user would be able to upload files, even if they have no way to create their own repository.

Comment (lunny) [reply routers/web/web.go]: OK. I see.

**Comment by wxiaoguang** [comment]
I think I have some ideas about how to resolve the "permission check" problem and make it clear now.

The brief idea is like this:

1. Make `GET /../_edit` require "read" permission, make `POST /.../_edit` require "write" permission.
2. Use JS to handle the "edit form submit"
    * If the doer has permission to write to current repo, submit the form as-is.
    * If the doer has no permission to write:
        1. Fork the repo to the doer's user/org space
        2. Submit the form to new newly forked repo's `/.../_edit` URL

**Comment by lunny** [comment]
Could you resolve the conflicts?

**Comment by wxiaoguang** [comment]
> I think I have some ideas about how to resolve the "permission check" problem and make it clear now.
> 
> The brief idea is like this:

Should we spend time on resolving conflicts with current approach, or try to implement the new idea? @brechtvl what do you think?

**Comment by brechtvl** [comment]
The idea to improve the permission checks seems good. It might be a while until I have time to work on that. When I do, resolving the conflicts would be the first step in refactoring the code, but I guess there is not much point in me doing it right now.

Unless you were thinking to work on this yourself, which would be great but not something I should expect of course.

**Comment by wxiaoguang** [comment]
Will take a look (maybe the new idea could be simplified and work without JS).

**Comment by wxiaoguang** [comment]
I think I have a complete solution now.

1. Refactor the existing "editor" related code, de-duplicate code and use "fetch" instead of "form submit"
2. "Fork and edit" page keep the same as this PR's approach
3. Use "read" access for "GET" and "write" access for "POST"
4. When rendering the "editor" form, if doer doesn't have write access, then use the forked repo's URL as the form's action

Then everything should work.

**Comment by wxiaoguang** [comment]
> Refactor the existing "editor" related code, de-duplicate code and use "fetch" instead of "form submit"

The first one:  Refactor editor #34780 

The legacy code is quite messy, I think it's worth to completely rewrite even if there might be some regressions. Will do my best to test the new code and I think we have enough time for 1.25 release.

**Comment by wxiaoguang** [comment]
"Refactor editor #34780" has been merged, it simplifies the editor related code a lot and fixes many legacy problems.

And yes, it causes a lot of conflicts with this PR. I am going to start resolving the conflicts and apply the "fork and edit" feature here. To keep a ref to this PR's original implementation, here is the backup branch: https://github.com/wxiaoguang/gitea/tree/fork-on-edit-backup

**Comment by wxiaoguang** [comment]
Since there are huge conflicts, I made a force-push (the origin code's backup is here:  https://github.com/wxiaoguang/gitea/tree/fork-on-edit-backup)

I did my best to apply the original PR's logic (some tests are still WIP). Do the new changes look good to you?

**Comment by lunny** [comment]
When submitted a change, it will always display the branch already exists in this repository but it's in fact not.
image

**Comment by wxiaoguang** [comment]
> When submitted a change, it will always display the branch already exists in this repository but it's in fact not.

How to reproduce?

**Comment by wxiaoguang** [comment]
> > When submitted a change, it will always display the branch already exists in this repository but it's in fact not.
> 
> How to reproduce?

OK, I see the problem now (and the test has some problems), will fix

----

Update: done

**Review by lunny — APPROVED** [review]

**Comment by brechtvl** [comment]
* The `Add File` button is not visible on the base repo, only when you have permission to edit it directly.
* I'm unsure if `Cherry Pick` is supposed to work. I didn't implement support for doing that in this work flow. This new code doesn't seem to prohibit it in the router, but also doesn't expose it in the UI. 
* The `You can not edit this repository directly. The changes will be written to your fork` text is now at the bottom of the page. Was than an intentional change? Personally I think it's useful information to see before you start editing. GitHub also shows it at the top though the overall UI is different.
* When specifying e.g. `main` in the new branch name, it  succeeds even though that branch already exists.
* When I disable the "Code" unit on my fork, it lets me edit the file, but when clicking "Propose file changes" I get `Network error SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`.
* My version added tests for some features that were not previously tested. It might be useful to salvage some of those even if it's just the non-fork cases.

**Comment by brechtvl** [comment]
I don't really have anything to mention regarding the code. It's much simpler now and the hard work seems to have been done in the refactoring. Many thanks!

**Comment by wxiaoguang** [comment]
> The `Add File` button is not visible on the base repo, only when you have permission to edit it directly.

Fixed and added a test

>  I'm unsure if `Cherry Pick` is supposed to work. I didn't implement support for doing that in this work flow. This new code doesn't seem to prohibit it in the router, but also doesn't expose it in the UI.

They share the same backend logic (the same as "Apply Patch"), so I think it's fine to leave it as-is. 

We can expose it in the future if anyone really needs it.

>  The `You can not edit this repository directly. The changes will be written to your fork` text is now at the bottom of the page. Was than an intentional change? Personally I think it's useful information to see before you start editing. GitHub also shows it at the top though the overall UI is different.

Moved to the top (see the screenshot)

>  When specifying e.g. `main` in the new branch name, it  succeeds even though that branch already exists.

Fixed and added some tests.

>  When I disable the "Code" unit on my fork, it lets me edit the file, but when clicking "Propose file changes" I get `Network error SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`.

Improved the frontend error handling  (see the screenshot)

>  My version added tests for some features that were not previously tested. It might be useful to salvage some of those even if it's just the non-fork cases.

I will try to pick some tests later. And could you help to list the tests you think are important?

----

Screenshots (slightly outdated, the new commits moved the prompt to before the editor header line)

<details>

image


image

</details>

**Comment by wxiaoguang** [comment]
> > My version added tests for some features that were not previously tested. It might be useful to salvage some of those even if it's just the non-fork cases.
> 
> I will try to pick some tests later. And could you help to list the tests you think is important?

Made some refactorings to `editor_test.go` and picked most of your new tests. Are there somethings more we need to take a look at?

**Comment by brechtvl** [comment]
Looks great now, no more comments from my side.

**Comment by wxiaoguang** [comment]
Let's merge and try (and fix regressions 😁 )
