### PR TITLE
Fix regression from #14623 - use debug SVC handler only on interactive sessions

### LINKED ISSUE #15159: The service did not respond to the start or control request in a timely fashion
- Gitea version: 1.14.0-rc2 (gitea-1.14.0-rc2-windows-4.0-amd64.exe download)
- Git version: 2.7
- Operating system: Windows Server 2008 R2
- Database: SQLite

Gitea does not start up when running as a Windows service.  "The service did not respond to the start or control request in a timely fashion" .  I have set the registry option ServicesPipeTimeout to 240000 which is 4 minutes.  The gitea.exe process can be seen in the task manager, but it eventually dies.

Running gitea web, it starts up just fine.  
Version 1.13.6 starts up fine as a service on the same machine.

[gitea.log.txt](https://github.com/go-gitea/gitea/files/6206765/gitea.log.txt)
[app.ini.txt](https://github.com/go-gitea/gitea/files/6206759/app.ini.txt)

### PR DESCRIPTION
**Pull request by zeripath**
Unfortunately #14623 changed from the deprecated IsInteractiveSession to
IsWindowsService without recognising that they are the complement of
each other.

This means that Windows SVC control is not working correctly. This PR
adds some Tracing statements but also fixes the bug.

Fix #15159

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: modules/graceful/manager_windows.go [hunk 1]
```diff
@@ -68,17 +68,19 @@ func (g *Manager) start() {
...
-	isInteractive, err := svc.IsWindowsService()
+	isWindowsService, err := svc.IsWindowsService()
 	if err != nil {
-		log.Error("Unable to ascertain if running as an Interactive Session: %v", err)
+		log.Error("Unable to ascertain if running as an Windows Service: %v", err)
 		return
 	}
-	if isInteractive {
+	if !isWindowsService {
+		log.Trace("Not running a service ... using the debug SVC manager")
```
Comment (zeripath) [inline modules/graceful/manager_windows.go:83]: This is the actual bugfix

The rest of this PR is adding tracing and logging because we don't have any in this code and it really is necessary

**Review by techknowlogick — APPROVED** [review]

**Review by lafriks — APPROVED** [review]
