### PR TITLE
Fix `convert.ToTeams` on empty input

### LINKED ISSUE #28420: `orgs/{name}/teams?page={page}` return `200` with `null\n` as content instead of empty list
### Description

When I try to get teams' information using `GET` on `/orgs/{org}/teams?page={page}` with a page that do not exists, the returned status is always `200` with `null\n` as raw data instead of an empty list.

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Linux Mint, EndeavourOS

### How are you running Gitea?

Official binaries, and running from systemd and command-line

### Database

SQLite

### PR DESCRIPTION
**Pull request by KN4CK3R**
Fixes #28420

Don't return `nil` if the input was empty.

### CODE REVIEW

File: services/convert/convert.go [hunk 1]
```diff
@@ -308,40 +308,43 @@ func ToTeam(ctx context.Context, team *organization.Team, loadOrg ...bool) (*api
...
 	cache := make(map[int64]*api.Organization)
-	apiTeams := make([]*api.Team, len(teams))
-	for i := range teams {
-		if err := teams[i].LoadUnits(ctx); err != nil {
+	apiTeams := make([]*api.Team, 0, len(teams))
+	for _, t := range teams {
+		if t == nil {
+			// Could be nil if teams was created with make([]*Team, x)
+			continue
+		}
```
Comment (KN4CK3R) [inline services/convert/convert.go]: I think that was the reason for the `teams[0] == nil` check. Can't tell if that check is still necessary.

Comment (KN4CK3R) [reply services/convert/convert.go]: I did not find a place which creates arrays with size and uses `append` afterwards. Should I remove this check then? Usually we don't have such checks.

Comment (delvh) [reply services/convert/convert.go]: Especially as this check silently masks a failure somewhere else.
I'm rather against including it.
If we do make a mistake somewhere, it should panic, so that we can then fix the problem.

**Review by delvh — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]
