### PR TITLE
Fix detection of no commits when the default branch is not master

### LINKED ISSUE #18413: Error when creating new repo: branch does not have any commits
### Gitea Version

1.16.0+rc1

### Git Version

2.30.2

### Operating System

Ubuntu server 20.04.3 LTS

### How are you running Gitea?

Running on docker, config file:
```
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1004
      - USER_GID=1005
      - GITEA__SERVER__DOMAIN=git.example.com
      - GITEA__SERVER__ROOT_URL=https://git.example.com
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=password
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__FROM=noreply@example.com
      - GITEA__mailer__MAILER_TYPE=smtp
      - GITEA__mailer__HOST=smtp.example.com:465
      - GITEA__mailer__IS_TLS_ENABLED=true
      - GITEA__mailer__USER=noreply@example.com
      - GITEA__mailer__PASSWD=password
      - GITEA__service__DEFAULT_BRANCH=main
      - GITEA__security__DISABLE_GIT_HOOKS=false
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/git/.ssh/:/data/git/.ssh
    ports:
      - "8095:3000"
      - "127.0.0.1:2222:22"
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
```

### Database

PostGres

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://gist.github.com/mmoomocow/6eb9413b0d756551ebe8b225a890e730

### Description

I created a repo, and set the default branch to main
Then when attempting to view the repo it shows error 500 and the error appears in the logs.
Repo on demo site [mmoomocow/test](https://try.gitea.io/mmoomocow/test)

### Screenshots

image

### PR DESCRIPTION
**Pull request by lunny**
Fix #18413

### CODE REVIEW

**Review by silverwind — APPROVED** [review]

**Comment by zeripath** [comment]
CI failure is related because I presume the repo default branch in the test cases is "".

**Comment by lunny** [comment]
I changed to `git rev-list --all --count --max-count=1`

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
tests break on this

**Comment by wxiaoguang** [comment]
TBH, 

* https://github.com/go-gitea/gitea/pull/18426

is straight and works fine.

**Comment by mmdoogie** [comment]
> I changed to `git rev-list --all --count --max-count=1`

I like this method as it doesn't rely on parsing an error message that could potentially change and is agnostic to the default branch name altogether.

File: modules/git/repo.go [hunk 1]
```diff
@@ -80,19 +80,12 @@ func InitRepository(ctx context.Context, repoPath string, bare bool) error {
...
-	if err := NewCommandContext(repo.Ctx, "log", "-1").RunInDirPipeline(repo.Path, nil, &errbuf); err != nil {
-		defaultBranch, err := repo.GetDefaultBranch()
-		if err != nil {
-			return false, err
-		}
-		if strings.Contains(errbuf.String(), "fatal: bad default revision 'HEAD'") ||
-			strings.Contains(errbuf.String(), fmt.Sprintf("fatal: your current branch '%s' does not have any commits yet", defaultBranch)) {
-			return true, nil
-		}
+	if err := NewCommandContext(repo.Ctx, "rev-list", "--all", "--count", "--max-count=1").RunInDirPipeline(repo.Path, nil, &errbuf); err != nil {
```
Comment (mmdoogie) [inline modules/git/repo.go]: The rev-list count is returned on stdout, so also need to receive that:

add `var resbuf strings.Builder`

and change line 83 to `if err := NewCommandContext(repo.Ctx, "rev-list", "--all", "--count", "--max-count=1").RunInDirPipeline(repo.Path, &resbuf, &errbuf); err != nil {`

also the output has a newline which needs to be trimmed to avoid Atoi erroring
thus line 87 needs to become `c, _ := strconv.Atoi(strings.TrimSpace(resbuf.String()))`

may also want to check the error on the conversion as well

this passes the mirror pull integration test and the repoisempty test

**Comment by zeripath** [comment]
The default branch is HEAD therefore

```
git show-ref HEAD
```

is the correct test. 

We can either read the output where an empty path means that the branch does not exist - or - read the exit code whereby 1 means that the branch does not exist.

File: modules/git/repo.go (hunk 1 above)
Comment (lunny) [reply modules/git/repo.go]: Good catch

**Comment by lunny** [comment]
> The default branch is HEAD therefore
> 
> ```
> git show-ref HEAD
> ```
> 
> is the correct test.
> 
> We can either read the output where an empty path means that the branch does not exist - or - read the exit code whereby 1 means that the branch does not exist.

The new method could avoid to get default branch.

**Comment by wxiaoguang** [comment]
We missed a unit test for it .....

**Comment by lunny** [comment]
There are already tests before.

**Comment by wxiaoguang** [comment]
Oh I see, the new code is more general, and doesn't need new test cases. 👍
