### PR TITLE
Fix wrong identify poster on a migrated pull request when submit review

### LINKED ISSUE #8959: Add review on a migrated pull request will be considered as author
After I migrated some repository(includes git data/wiki/pull requests/issues), then when I want to add some review on some PR which was not created by me. But the review system think it's me because it didn't read the original_author on issue table.

### PR DESCRIPTION
**Pull request by lunny**
Fix #8959

### CODE REVIEW

**Review by sapk — APPROVED** [review]

File: models/issue.go [hunk 1]
```diff
@@ -440,7 +440,7 @@ func (issue *Issue) HashTag() string {
 
 // IsPoster returns true if given user by ID is the poster.
 func (issue *Issue) IsPoster(uid int64) bool {
-	return issue.PosterID == uid
+	return issue.OriginalAuthorID == 0 && issue.PosterID == uid
```
Comment (sapk) [inline models/issue.go:443]: Just to confirm from what I have understand when migrating if the user exist OriginalAuthorID  is not and set and issue.PosterID is not the doer (like it is by default) but found user ?

**Review by lafriks — APPROVED** [review]

**Comment by sapk** [comment]
@lunny please send backports

File: models/issue.go (hunk 1 above)
Comment (lunny) [reply models/issue.go:443]: If OriginalAuthorID > 0, PosterID means migrator but not poster id. `OriginalAuthorID` is an external system id not gitea user id.
