### PR TITLE
Fix possible notify watch failure because the content is too long than database can store.

### LINKED ISSUE #28193: NotifySyncPushCommits() [E] NotifyWatchers: insert new actioner: Error 1406 (22001): Data too long for column 'content' at row 1
### Description

One occurrence of
```
2023/11/24 02:07:13 ...ion/action/action.go:403:NotifySyncPushCommits() [E] NotifyWatchers: insert new actioner: Error 1406 (22001): Data too long for column 'content' at row 1
```
was caught in gitea 1.20.3 error log on mirror update.

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

2.30.2

### Operating System

Debian

### How are you running Gitea?

Compiled from sources.

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by lunny**
Fix #28193

### CODE REVIEW

File: services/feed/feed.go [hunk 1]
```diff
@@ -42,6 +45,10 @@ func GetFeeds(ctx context.Context, opts activities_model.GetFeedsOptions) (activ
 func notifyWatchers(ctx context.Context, act *activities_model.Action, watchers []*repo_model.Watch, permCode, permIssue, permPR []bool) error {
 	// Add feed for actioner.
 	act.UserID = act.ActUserID
+	if len(act.Content) > maxActionContentLength {
```
Comment (wxiaoguang) [inline services/feed/feed.go]: I do not think the `if` check is useful to end users or site admin.

If you think it is still useful to show the "warn", you could just use `EllipsisDisplayStringX` to check whether the text is truncated by checking `right!=""`

File: services/feed/feed.go [hunk 2]
```diff
@@ -34,6 +35,8 @@ func GetFeeds(ctx context.Context, opts activities_model.GetFeedsOptions) (activ
 	return activities_model.GetFeeds(ctx, opts)
 }
 
+const maxActionContentLength = 65535 // this is the max length of mysql text column, sqlite, postgres and mssql have a higher limit
```
Comment (wxiaoguang) [inline services/feed/feed.go]: I do not think we are able to show so long text in the "activity feeds"

At most, 200 or 300 runes

**Review by wxiaoguang — APPROVED** [review]

**Review by hiifong — APPROVED** [review]

**Comment by lunny** [comment]
I will not backport this as it needs to introduce many utils functions.
