### PR TITLE
API: Admin EditUser: Make FullName, Email, Website & Location optional

### LINKED ISSUE #13543: API Call /admin/users/{username} does not work without email.
- Gitea version 1.12.5
- Git version: 2.29.2
- Operating system:
  Linux Alpine Docker Image.
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes [https://try.gitea.io/api/swagger#/admin/adminEditUser](https://try.gitea.io/api/swagger#/admin/adminEditUser)
  - [ ] No

## Description
API Call [https://try.gitea.io/api/swagger#/admin/adminEditUser](https://try.gitea.io/api/swagger#/admin/adminEditUser)
does not succeed with out email:
```
{
  "active": true,
  "email": "user@example.com"
}
```

Cannot provide a test, since I the admin user on https://try.gitea.io is not known (?)

### PR DESCRIPTION
**Pull request by 6543**
make more values optional for Admin EditUser

close #13543

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

File: routers/api/v1/admin/user.go [hunk 1]
```diff
@@ -182,10 +182,22 @@ func EditUser(ctx *context.APIContext, form api.EditUserOption) {
...
+	}
+	if form.Website != nil {
+		u.Website = *form.Website
+	}
+	if form.Location != nil {
+		u.Location = *form.Location
+	}
+	if form.Email != nil {
+		u.Email = *form.Email
+	}
```
Comment (6543) [inline routers/api/v1/admin/user.go]:
```suggestion
```

**Review by zeripath — APPROVED** [review]

File: routers/api/v1/admin/user.go [hunk 2]
```diff
@@ -182,10 +182,19 @@ func EditUser(ctx *context.APIContext, form api.EditUserOption) {
...
 	u.LoginName = form.LoginName
-	u.FullName = form.FullName
-	u.Email = form.Email
-	u.Website = form.Website
-	u.Location = form.Location
+
+	if form.FullName != nil {
+		u.FullName = *form.FullName
+	}
+	if form.Email != nil {
```
Comment (lunny) [inline routers/api/v1/admin/user.go:189]: Email is required if `REGISTER_EMAIL_CONFIRM` is true?

Comment (lafriks) [reply routers/api/v1/admin/user.go:189]: but if no value is provided than field will not be updated, what this could be is missing is that if empty string is provided it should be checked to return required value error for email

File: routers/api/v1/admin/user.go [hunk 3]
```diff
@@ -182,10 +182,19 @@ func EditUser(ctx *context.APIContext, form api.EditUserOption) {
...
+		u.Email = *form.Email
```
Comment (lafriks) [inline routers/api/v1/admin/user.go:190]: this should be checked that u.Email is not empty string

**Review by lafriks — CHANGES_REQUESTED** [review]

File: routers/api/v1/admin/user.go (hunk 2 above)
Comment (6543) [reply routers/api/v1/admin/user.go:189]: @lunny the `REGISTER_EMAIL_CONFIRM` should be no concern - since it is the **admin** interface (you obvious dont have to on the Admin web UI too)

**Comment by 6543** [comment]
@lafriks done + added test to ensure it

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
:rocket:
