### PR TITLE
Use the type RefName for all the needed places and fix pull mirror sync bugs

### LINKED ISSUE #15367: [BUG] REPO_INDEXER won't index mirrored repository after sync
- Gitea version (or commit ref): 1.13.1
- Git version: Not relevant
- Operating system:docker image
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist: Not relevant

## Description

REPO_INDEXER won't index mirrored repository after sync

Related: #12380  #11200 #11479 #5329

### PR DESCRIPTION
**Pull request by lunny**
This PR replaces all string refName as a type `git.RefName` to make the code more maintainable.

Fix #15367
Replaces #23070 
It also fixed a bug that tags are not sync because `git remote --prune origin` will not remove local tags if remote removed.

We in fact should use `git fetch --prune --tags origin` but not `git remote update origin` to do the sync.

Some answer from ChatGPT as ref.

> If the git fetch --prune --tags command is not working as expected, there could be a few reasons why. Here are a few things to check:
> 
>Make sure that you have the latest version of Git installed on your system. You can check the version by running git --version in your terminal. If you have an outdated version, try updating Git and see if that resolves the issue.
> 
>Check that your Git repository is properly configured to track the remote repository's tags. You can check this by running git config --get-all remote.origin.fetch and verifying that it includes +refs/tags/*:refs/tags/*. If it does not, you can add it by running git config --add remote.origin.fetch "+refs/tags/*:refs/tags/*".
> 
>Verify that the tags you are trying to prune actually exist on the remote repository. You can do this by running git ls-remote --tags origin to list all the tags on the remote repository.
> 
>Check if any local tags have been created that match the names of tags on the remote repository. If so, these local tags may be preventing the git fetch --prune --tags command from working properly. You can delete local tags using the git tag -d command.

### CODE REVIEW

File: services/webhook/notifier.go [hunk 1]
```diff
@@ -596,7 +596,7 @@ func (m *webhookNotifier) NotifyPushCommits(ctx context.Context, pusher *user_mo
 	}
 
 	if err := PrepareWebhooks(ctx, EventSource{Repository: repo}, webhook_module.HookEventPush, &api.PushPayload{
-		Ref:          opts.RefFullName,
+		Ref:          opts.RefFullName.String(), //
```
Comment (delvh) [inline services/webhook/notifier.go]:
```suggestion
		Ref:          opts.RefFullName.String(),
```

Comment (delvh) [reply services/webhook/notifier.go]: Or a fixme like below?

File: services/repository/branch.go [hunk 2]
```diff
@@ -183,7 +184,7 @@ func DeleteBranch(ctx context.Context, doer *user_model.User, repo *repo_model.R
 	// Don't return error below this
 	if err := PushUpdate(
 		&repo_module.PushUpdateOptions{
-			RefFullName:  git.BranchPrefix + branchName,
+			RefFullName:  git.RefName(git.BranchPrefix + branchName),
```
Comment (delvh) [inline services/repository/branch.go]:
```suggestion
			RefFullName:  git.RefNameFromBranch(branchName),
```

File: services/repository/push.go [hunk 3]
```diff
@@ -107,7 +107,7 @@ func pushUpdates(optsList []*repo_module.PushUpdateOptions) error {
 		if opts.IsNewRef() && opts.IsDelRef() {
 			return fmt.Errorf("old and new revisions are both %s", git.EmptySHA)
 		}
-		if opts.IsTag() { // If is tag reference
+		if opts.RefFullName.IsTag() { // If is tag reference
```
Comment (delvh) [inline services/repository/push.go]:
```suggestion
		if opts.RefFullName.IsTag() {
```
That comment is useless. That's literally what this if says

File: services/repository/push.go [hunk 4]
```diff
@@ -123,13 +123,13 @@ func pushUpdates(optsList []*repo_module.PushUpdateOptions) error {
 				notification.NotifyPushCommits(
 					ctx, pusher, repo,
 					&repo_module.PushUpdateOptions{
-						RefFullName: git.TagPrefix + tagName,
+						RefFullName: git.RefName(git.TagPrefix + tagName),
```
Comment (delvh) [inline services/repository/push.go]:
```suggestion
						RefFullName: git.RefNameFromTag(tagName),
```

File: services/repository/push.go [hunk 5]
```diff
@@ -143,15 +143,15 @@ func pushUpdates(optsList []*repo_module.PushUpdateOptions) error {
...
 						OldCommitID: git.EmptySHA,
 						NewCommitID: opts.NewCommitID,
 					}, commits)
 
 				addTags = append(addTags, tagName)
-				notification.NotifyCreateRef(ctx, pusher, repo, "tag", opts.RefFullName, opts.NewCommitID)
+				notification.NotifyCreateRef(ctx, pusher, repo, opts.RefFullName, opts.NewCommitID)
 			}
-		} else if opts.IsBranch() { // If is branch reference
+		} else if opts.RefFullName.IsBranch() { // If is branch reference
```
Comment (delvh) [inline services/repository/push.go]:
```suggestion
		} else if opts.RefFullName.IsBranch() {
```
see above

File: modules/git/ref.go [hunk 6]
```diff
@@ -108,5 +141,24 @@ func (ref RefName) RefGroup() string {
...
 	return ""
 }
+
+// RefURL returns the absolute URL for a ref in a repository
+func RefURL(repoURL, ref string) string {
+	refName := util.PathEscapeSegments(RefName(ref).ShortName())
+	switch {
+	case strings.HasPrefix(ref, BranchPrefix):
+		return repoURL + "/src/branch/" + refName
+	case strings.HasPrefix(ref, TagPrefix):
```
Comment (delvh) [inline modules/git/ref.go]:
```suggestion
	case ref.IsTag():
```

File: modules/git/ref.go [hunk 7]
```diff
@@ -108,5 +141,24 @@ func (ref RefName) RefGroup() string {
...
+		return "for"
+	}
 	return ""
 }
+
+// RefURL returns the absolute URL for a ref in a repository
+func RefURL(repoURL, ref string) string {
+	refName := util.PathEscapeSegments(RefName(ref).ShortName())
+	switch {
+	case strings.HasPrefix(ref, BranchPrefix):
```
Comment (delvh) [inline modules/git/ref.go]:
```suggestion
	case ref.IsBranch():
```

File: modules/git/repo_branch.go [hunk 8]
```diff
@@ -16,9 +16,9 @@ const BranchPrefix = "refs/heads/"
 
 // AGit Flow
 
-// PullRequestPrefix special ref to create a pull request: refs/for/<targe-branch>/<topic-branch>
+// ForPrefix special ref to create a ref: refs/for/<targe-branch>/<topic-branch>
```
Comment (delvh) [inline modules/git/repo_branch.go]:
```suggestion
// ForPrefix special ref to create a pull request: refs/for/<target-branch>/<topic-branch>
```

File: services/release/release.go [hunk 9]
```diff
@@ -80,14 +80,15 @@ func createTag(ctx context.Context, gitRepo *git.Repository, rel *repo_model.Rel
 			commits.HeadCommit = repository.CommitToPushCommit(commit)
 			commits.CompareURL = rel.Repo.ComposeCompareURL(git.EmptySHA, commit.ID.String())
 
+			refFullName := git.RefName(git.TagPrefix + rel.TagName)
```
Comment (delvh) [inline services/release/release.go]:
```suggestion
			refFullName := git.RefNameFromTag(rel.TagName)
```

**Review by delvh — COMMENTED** [review]
Definitely a necessary step.
That's the only maintainable way to ensure that everything that needs it has the correct prefix and that nothing has 0 or 2 prefixes.

File: services/mirror/mirror_pull.go [hunk 10]
```diff
@@ -97,25 +105,28 @@ func parseRemoteUpdateOutput(output string) []*mirrorSyncResult {
...
+			refName = strings.TrimPrefix(strings.TrimSpace(refName), remoteName+"/")
+			results = append(results, &mirrorSyncResult{
+				refName:     git.RefNameFromBranch(refName),
 				oldCommitID: gitShortEmptySha,
 			})
 		case strings.HasPrefix(lines[i], " - "): // Delete reference
+			refName = strings.TrimPrefix(strings.TrimSpace(refName), remoteName+"/")
 			results = append(results, &mirrorSyncResult{
-				refName:     refName,
+				refName:     git.RefNameFromBranch(refName),
```
Comment (wolfogre) [inline services/mirror/mirror_pull.go]: What if delete a tag?

Comment (lunny) [reply services/mirror/mirror_pull.go]: good question. I have no idea.

Comment (wxiaoguang) [reply services/mirror/mirror_pull.go]: More context in #23070 (mirror sync information, it is a incomplete fro git side)

I would suggest to complete the documents and tests by #23070 first

Otherwise nobody know what happens

Comment (lunny) [reply services/mirror/mirror_pull.go]: I think I have fixed this. The code is tricky. In a word,
`- [deleted] v1.0` should be a tag and `- [deleted] origin/branch` should be a branch.

Comment (wxiaoguang) [reply services/mirror/mirror_pull.go]: Docs and tests?

Comment (lunny) [reply services/mirror/mirror_pull.go]: I have added unit tests and comments. No official documentations from git

**Comment by lunny** [comment]
It's ready to review now.

**Review by wolfogre — APPROVED** [review]

File: modules/git/ref.go [hunk 11]
```diff
@@ -108,5 +137,25 @@ func (ref RefName) RefGroup() string {
...
+	if strings.HasPrefix(refName, ForPrefix) {
+		return "for"
+	}
 	return ""
 }
+
+// RefURL returns the absolute URL for a ref in a repository
+func RefURL(repoURL, ref string) string {
+	refFullName := RefName(ref)
+	refName := util.PathEscapeSegments(refFullName.ShortName())
```
Comment (wxiaoguang) [inline modules/git/ref.go:183]: Considering that there is such code for ShortName

```
	if strings.HasPrefix(refName, ForPrefix) {
		return strings.TrimPrefix(refName, ForPrefix)
	}
```


Is there the call to ShortName right? Especally the `assume they mean a branch` part

File: modules/git/ref_test.go [hunk 12]
```diff
@@ -11,15 +11,15 @@ import (
...
 
 	// Test tag names (with and without slash).
-	assert.Equal(t, "foo", RefEndName("refs/tags/foo"))
-	assert.Equal(t, "release/foo", RefEndName("refs/tags/release/foo"))
+	assert.Equal(t, "foo", RefName("refs/tags/foo").ShortName())
+	assert.Equal(t, "release/foo", RefName("refs/tags/release/foo").ShortName())
 
 	// Test commit hashes.
-	assert.Equal(t, "c0ffee", RefEndName("c0ffee"))
+	assert.Equal(t, "c0ffee", RefName("c0ffee").ShortName())
```
Comment (wxiaoguang) [inline modules/git/ref_test.go:30]: 1. The test function name should be updated?
2. Should the `for` (and more) be tested?

File: modules/notification/base/null.go [hunk 13]
```diff
@@ -161,11 +162,11 @@ func (*NullNotifier) NotifyPushCommits(ctx context.Context, pusher *user_model.U
 }
 
 // NotifyCreateRef notifies branch or tag creation to notifiers
-func (*NullNotifier) NotifyCreateRef(ctx context.Context, doer *user_model.User, repo *repo_model.Repository, refType, refFullName, refID string) {
+func (*NullNotifier) NotifyCreateRef(ctx context.Context, doer *user_model.User, repo *repo_model.Repository, refFullName git.RefName, refID string) {
```
Comment (wxiaoguang) [inline modules/notification/base/null.go:165]: I guess you created more conflicts with your "notification refactoring" PR.

Keeping doing so, some code would be lost sooner or later.

Could these PRs not be stale for that long? I would propose to discard that stale PR.

File: modules/notification/indexer/indexer.go [hunk 14]
```diff
@@ -126,7 +125,7 @@ func (r *indexerNotifier) NotifyMigrateRepository(ctx context.Context, doer, u *
 }
 
 func (r *indexerNotifier) NotifyPushCommits(ctx context.Context, pusher *user_model.User, repo *repo_model.Repository, opts *repository.PushUpdateOptions, commits *repository.PushCommits) {
-	if setting.Indexer.RepoIndexerEnabled && opts.RefFullName == git.BranchPrefix+repo.DefaultBranch {
+	if setting.Indexer.RepoIndexerEnabled && opts.RefFullName.ShortName() == repo.DefaultBranch {
```
Comment (wxiaoguang) [inline modules/notification/indexer/indexer.go]: Such change doesn't seem right.

What if a tag's short name is also repo.DefaultBranch ?

(I would pause reviewing here, until these pending comments get resolved ....)

**Comment by wxiaoguang** [comment]
I think the design of "ShortName()" is not ideal, it would cause more abuses, because it's unclear about what the name it is. It could be a tag, or it could be a branch, but callers would keep forgetting to check whether it is a branch or it is a tag.

**Comment by lunny** [comment]
> 

Did you mean `BranchName`, `TagName` are better?

File: modules/git/ref.go (hunk 11 above)
Comment (lunny) [reply modules/git/ref.go:183]: We currently don't support that. The branch name in `For()` is the target branch name not the head branch name. For `For`, there is no head branch concept.

File: modules/notification/base/null.go (hunk 13 above)
Comment (lunny) [reply modules/notification/base/null.go:165]: The change is not too big to handle.

File: modules/notification/indexer/indexer.go (hunk 14 above)
Comment (lunny) [reply modules/notification/indexer/indexer.go]: Fixed in 5b31c36f20b746eb7d2ff6f7636c63620dab7857

Comment (wxiaoguang) [reply modules/notification/indexer/indexer.go]: There would be more such abuses in the future.

I have objection for the ShortName, I think it's a improper design.

Comment (lunny) [reply modules/notification/indexer/indexer.go]: How about a method named `BranchEqual`?

Comment (wxiaoguang) [reply modules/notification/indexer/indexer.go]: `BranchEqual` or `BranchNameEqual` either looks good to me. (although I like `BranchNameEqual` a little more because its purpose is comparing branch names)

**Comment by lunny** [comment]
@wxiaoguang please review again.

**Comment by wxiaoguang** [comment]
> I think the design of "ShortName()" is not ideal, it would cause more abuses, because it's unclear about what the name it is. It could be a tag, or it could be a branch, but callers would keep forgetting to check whether it is a branch or it is a tag.

The code `opts.RefFullName.ShortName() == repo.DefaultBranch` is worse than before (full ref compare). Sooner or later there will be more abuses.

**Comment by lunny** [comment]
> > I think the design of "ShortName()" is not ideal, it would cause more abuses, because it's unclear about what the name it is. It could be a tag, or it could be a branch, but callers would keep forgetting to check whether it is a branch or it is a tag.
> 
> The code `opts.RefFullName.ShortName() == repo.DefaultBranch` is worse than before (full ref compare). Sooner or later there will be more abuses.

Fixed

File: modules/notification/indexer/indexer.go [hunk 15]
```diff
@@ -126,7 +125,11 @@ func (r *indexerNotifier) NotifyMigrateRepository(ctx context.Context, doer, u *
 }
 
 func (r *indexerNotifier) NotifyPushCommits(ctx context.Context, pusher *user_model.User, repo *repo_model.Repository, opts *repository.PushUpdateOptions, commits *repository.PushCommits) {
-	if setting.Indexer.RepoIndexerEnabled && opts.RefFullName == git.BranchPrefix+repo.DefaultBranch {
+	if !opts.RefFullName.IsBranch() {
+		return
+	}
+
+	if setting.Indexer.RepoIndexerEnabled && opts.RefFullName.BranchName() == repo.DefaultBranch {
```
Comment (wxiaoguang) [inline modules/notification/indexer/indexer.go:132]:
```suggestion
	if setting.Indexer.RepoIndexerEnabled && opts.RefFullName.EqualBranchName(repo.DefaultBranch) {
```

Like this? Simpler than before and couldn't be misused.

File: modules/actions/workflows.go [hunk 16]
```diff
@@ -240,7 +240,7 @@ func matchPushEvent(commit *git.Commit, pushPayload *api.PushPayload, evt *jobpa
 			if err != nil {
 				break
 			}
-			if !workflowpattern.Filter(patterns, []string{refName.ShortName()}, &workflowpattern.EmptyTraceWriter{}) {
+			if !workflowpattern.Filter(patterns, []string{refName.TagName()}, &workflowpattern.EmptyTraceWriter{}) {
```
Comment (wxiaoguang) [inline modules/actions/workflows.go:243]: I guess here (and above) it needs to check `IsBranch` or `IsTag` first?

Otherwise, if the pattern is `*`, then a branch's TagName returns `""`, it matches the pattern `*` ?

(Maybe a legacy problem)

Comment (lunny) [reply modules/actions/workflows.go:243]: This has been checked, see line 236

File: modules/notification/indexer/indexer.go (hunk 15 above)
Comment (lunny) [reply modules/notification/indexer/indexer.go:132]: But sometimes, we need to send branch name as parameter but not compare the branch name. If we do that, we will have both `Branchname()` and `EqualBranchName()` and `IsBranch` still need to be kept.

File: services/agit/agit.go [hunk 17]
```diff
@@ -48,15 +48,15 @@ func ProcReceive(ctx context.Context, repo *repo_model.Repository, gitRepo *git.
...
+		if !opts.RefFullNames[i].IsFor() {
 			results = append(results, private.HookProcReceiveRefResult{
 				IsNotMatched: true,
 				OriginalRef:  opts.RefFullNames[i],
 			})
 			continue
 		}
 
-		baseBranchName := opts.RefFullNames[i][len(git.PullRequestPrefix):]
+		baseBranchName := opts.RefFullNames[i].ForBranchName()
```
Comment (wxiaoguang) [inline services/agit/agit.go:59]: When reading this line, I guess `AgitBranchName` is clearer 🤣

File: services/mirror/mirror_pull.go [hunk 18]
```diff
@@ -204,11 +222,11 @@ func runSync(ctx context.Context, m *repo_model.Mirror) ([]*mirrorSyncResult, bo
 
 	log.Trace("SyncMirrors [repo: %-v]: running git remote update...", m.Repo)
 
-	cmd := git.NewCommand(ctx, "remote", "update")
+	cmd := git.NewCommand(ctx, "fetch")
```
Comment (wxiaoguang) [inline services/mirror/mirror_pull.go:226]: Curious, `fetch` works better than old `remote update`?

Comment (lunny) [reply services/mirror/mirror_pull.go:226]: Yes, it's recommended to use `fetch`, I will add a comment here.

File: services/mirror/mirror_test.go [hunk 19]
```diff
@@ -0,0 +1,46 @@
...
+
+	assert.EqualValues(t, "refs/heads/master", results[1].refName.String())
+	assert.EqualValues(t, gitShortEmptySha, results[1].oldCommitID)
+	assert.EqualValues(t, "", results[1].newCommitID)
+
+	assert.EqualValues(t, "refs/heads/test1", results[2].refName.String())
+	assert.EqualValues(t, "", results[2].oldCommitID)
+	assert.EqualValues(t, gitShortEmptySha, results[2].newCommitID)
+
+	assert.EqualValues(t, "refs/tags/tag1", results[3].refName.String())
```
Comment (wxiaoguang) [inline services/mirror/mirror_test.go:35]: Wow, magic 👍

**Review by wxiaoguang — APPROVED** [review]

File: services/agit/agit.go (hunk 17 above)
Comment (lunny) [reply services/agit/agit.go:59]: The `refs/for/xx` is used by Gerrit first as a 3rd usage and then merged into git. So for now, both gerrit and agit will use it.

File: routers/private/hook_post_receive.go [hunk 20]
```diff
@@ -124,17 +123,16 @@ func HookPostReceive(ctx *gitea_context.PrivateContext) {
 		newCommitID := opts.NewCommitIDs[i]
 
 		// post update for agit pull request
-		if git.SupportProcReceive && strings.HasPrefix(refFullName, git.PullPrefix) {
+		// FIXME: use pr.Flow to test whether it's an Agit PR or a GH PR
```
Comment (lunny) [inline routers/private/hook_post_receive.go:126]: @a1012112796 Maybe you can give some suggestions about this condition?

**Comment by wxiaoguang** [comment]
According to #25185 , some field values are changed from "tag" to "tags", it breaks some APIs and 3rdparty systems.

**Comment by wxiaoguang** [comment]
"ref_type" also affects "branch" -> "heads" , which seems also breaking.
