### PR TITLE
Fix repository create/delete event webhooks

### LINKED ISSUE #11766: Webhook doesn't fire on creation or deletion of a repository that does not belong to an organisation
## Steps to reproduce
1. Set up a default webhook; in my case, I used a Gitea webhook with JSON POST, but I would be surprised if the details mattered.
2. Create a new repository under a user, i.e. outside of an organisation.

## Expected behaviour
A `repository` webhook event is sent to signal the creation of the new repository.

## Actual behaviour
No webhook call.

Repository creation and deletion events are only executed when the repo belongs to an organisation:

https://github.com/go-gitea/gitea/blob/2c5b3c72e8ebdf94ac764267fa78e4a0c5e93dc6/modules/notification/webhook/webhook.go#L102
https://github.com/go-gitea/gitea/blob/2c5b3c72e8ebdf94ac764267fa78e4a0c5e93dc6/modules/notification/webhook/webhook.go#L117

While that probably made sense in the past, it doesn't mix well with default webhooks nor with the new system-wide webhooks (#10546). Those should fire on all repositories.

(I have not tested system-wide webhooks, but given the code mentioned above, it should behave the same.)

## System information
- Gitea version (or commit ref): 1.11.6
- Git version: not relevant
- Operating system: unknown, but I can ask if it matters
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] Can't test currently
- Log gist: not relevant

### PR DESCRIPTION
**Pull request by jamesorlakin**
This small PR changes the webhook trigger behaviour to be more in line with what's expected. (When 'repository' events are enabled, of course)

In other words:
- For system-wide or default webhooks, repository events will now trigger said webhook. Previously it had to be under an organization for create events to be visible - a tad unexpected!
- Deleting a repository will now fire its own defined webhooks, not just organisational and system ones.

In order to enable the latter the webhook has to now be triggered before the actual repo undergoes deletion. I'm willing to tweak this to try and 'grab' the webhook model beforehand and trigger the webhook notifier directly afterwards, but this may make the code more complex for little benefit.

Closes #11766, #9180.

### CODE REVIEW

File: services/repository/repository.go [hunk 1]
```diff
@@ -64,12 +64,13 @@ func DeleteRepository(doer *models.User, repo *models.Repository) error {
 		log.Error("CloseRepoBranchesPulls failed: %v", err)
 	}
 
+	// If the repo has a webhook, we need to trigger it before deleting it...
+	notification.NotifyDeleteRepository(doer, repo)
+
 	if err := models.DeleteRepository(doer, repo.OwnerID, repo.ID); err != nil {
```
Comment (techknowlogick) [inline services/repository/repository.go]: Thanks for PR :) Seems our linter is saying that this if conditional can be changed to just `return models.DeleteRepository(doer, repo.OwnerID, repo.ID)` and the `return nil` below could also be removed.

Comment (jamesorlakin) [reply services/repository/repository.go]: Cheers, just seen! `make lint-backend` unfortunately doesn't work for me on Windows

Comment (techknowlogick) [reply services/repository/repository.go]: Awesome, thanks :) the linter has been appeased. Sorry about the developer experience on windows.

**Review by zeripath — APPROVED** [review]

**Review by CirnoT — APPROVED** [review]

File: services/repository/repository.go (hunk 1 above)
Comment (jamesorlakin) [reply services/repository/repository.go]: Aah no worries, I'll have a little poke around. I don't know whether it's Windows or Git Bash, but there's some funk going on with the slashes:
image

**Comment by jamesorlakin** [comment]
Does this want a backport?
