### PR TITLE
Prefix all user-generated IDs in markup

### LINKED ISSUE #9467: Unable to close issue
- Gitea version (or commit ref): 1.10.1 
- Git version: 2.22.0
- Operating system: Ubuntu (Linux)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/aggarwal.dev/sample/issues/1) 
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When using an Issue template with check box (like the one above), I'm unable to close issue and unable to set Label.
...

## Screenshots
Screenshot_2019-12-23 Refactor

## Comments
I guess it's a problem with dropzone.js 
Here's what console looks like:
```
downloadable font: OS/2: Bad sTypoLineGap, setting it to 0: -32 (font-family: "Dropdown" style:normal weight:400 stretch:100 src index:0) source: data:application/x-font-ttf;charset=utf-8;base64,AAEAAAALAIAAAwAwT1MvMggjB5AAAAC8AAAAYGNtYXAPfuIIAAABHAAAAExnYXNwAAAAEAAAAWgAAAA … AG0AbwBvAG4ARgBvAG4AdAAgAGcAZQBuAGUAcgBhAHQAZQBkACAAYgB5ACAASQBjAG8ATQBvAG8AbgAuAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= unknown:300:30915
JQMIGRATE: Migrate is installed, version 3.0.1 jquery-migrate.min.js:33:19
Tribute was already bound to TEXTAREA tribute.min.js:1:3479
Error: No URL provided. dropzone.js:439:15
jQuery.Deferred exception: Dropzone is not defined @https://try.gitea.io/js/index.js?v=3734fe86ac738d6b4793aa29527ce5b8:1:99673
e@https://try.gitea.io/vendor/plugins/jquery/jquery.min.js?v=3.4.1:2:29453
l/</t<@https://try.gitea.io/vendor/plugins/jquery/jquery.min.js?v=3.4.1:2:29755
 undefined jquery.min.js:2:31008
ReferenceError: Dropzone is not defined index.js:2378:4
Source map error: Error: request failed with status 404
Resource URL: https://try.gitea.io/vendor/plugins/tribute/tribute.min.js
Source Map URL: tribute.min.js.map
```

### PR DESCRIPTION
**Pull request by jolheiser**
Resolves #9467 

One thing to note with this PR, it **does not** fix the headers getting anchored, but that is for another PR. The JS changes are simply to avoid a conflicting ID.  
We no longer need to keep track of an arbitrary index because blackfriday already does so. We just need to copy the auto-generated ID for our anchor's `href`

This PR prefixes any marked up elements with a user-defined ID (including the auto-generated IDs from blackfriday) with `user-content-` in order to avoid clashing with (most) other IDs.

### CODE REVIEW

File: web_src/js/index.js [hunk 1]
```diff
@@ -2472,21 +2472,10 @@ $(document).ready(() => {
...
-      }
-      if (headers[val] === undefined) {
-        headers[val] = 1;
-      } else {
-        headers[val] += 1;
-      }
-      node = node.wrap(`<div id="${name}" class="anchor-wrap" ></div>`);
-      node.append(`<a class="anchor" href="#${name}"><span class="octicon octicon-link"></span></a>`);
+      node = node.wrap('<div class="anchor-wrap"></div>');
+      node.append(`<a class="anchor" href="#${node.attr('id')}"><span class="octicon octicon-link"></span></a>`);
```
Comment (zeripath) [inline web_src/js/index.js]:
```suggestion
      node.append(`<a class="anchor" href="#${encodeURIComponent(node.attr('id'))}"><span class="octicon octicon-link"></span></a>`);
```

**Comment by 6543** [comment]
@jolheiser I think you have to update the unit-tests

**Review by zeripath — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Review by mrsdizzie — APPROVED** [review]
