### PR TITLE
Remove heads pointing to missing old refs

### LINKED ISSUE #15155: [Gitlab to Gitea] Pull requests import is okay, but pull/heads points to invalid objects leads to no new branch or PR
Hello everyone
I began migrating repositories from my self hosted Gitlab, and every features work great, thanks !

The only downside is when I migrate the Pull Requests, I can access commits only on open PR, the closed Pull Requests don’t have any commits within (see screenshot) 
Also when trying to access files, I got an error 500.
If the PR is still open, everything work as intended.

Please let me know if there is anything I can do for help, and thanks for the great work !

- Gitea version (or commit ref): tried on Gitea 1.13.4 and 1.15.0+Dev
- Git version: 
- Gitlab Version : EE 13.9.4 and CE 12.8.0
- Operating system:
Ubuntu-bionic 18.04.5 LTS under Vagrant+VirtualBox
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes here is the test repository : https://try.gitea.io/99rgosse/gitlab_to_gitea/pulls/1
  - [ ] No : I cannot import from my private gitlab (outside intranet)
- Log gist:

    -  when clicking on page:
routers/repo/pull.go:659:ViewPullFiles() [E] GetCommit: object does not exist [id: , rel_path: ]

    - when importing:
- error: refs/pull/1488/head does not point to a valid object!        
- error: refs/pull/1507/head does not point to a valid object!

- 2021/03/25 14:36:24 ...es/pull/temp_repo.go:104:createTemporaryRepo() [E] Unable to fetch origin base branch [gitrepo/repo3:repo4/master -> base, original_base in /data/gitea/tmp/local-repo/pull.git082213367]: exit status 1:        error: refs/pull/1538/head does not point to a valid object!        error: refs/pull/1544/head does not point to a valid object!        error: refs/pull/1545/head does not point to a valid object!        error: refs/pull/1546/head does not point to a valid object!        error: refs/pull/1551/head does not point to a valid object!        error: refs/pull/1560/head does not point to a valid object!        fatal: bad object .alternate        error: /data/git/repositories/gitrepo/repo3.git did not send all necessary objects

## Description
Gitea service is directly accessible from within my intranet, linked to port 3000.
When trying a migration from gitlab to gitea, the PR are imported but of course deleted branches can't
14:35:59 Started GET /user/task/11?_csrf=

## Screenshots

PR

### PR DESCRIPTION
**Pull request by 99rgosse**
When migrating a repository that had previously deprecated heads, the migrated repository will fail to pass health check and thus it was not possible to make new branches via UI 
( [see issue #15155](https://github.com/go-gitea/gitea/issues/15155#issuecomment-907288605)

The patch basically ensure that `git log` points to a valid head when on a closed PR at the migration time.
image

Tested this on :
[x] 1.15.2 
[x] Main latest

I ensured that all PR were still working after merging, also that old PR were still ok.

Sample output in logs : 
image

For the sake of readability, I could remove the log showing the full err

Fix #15155

### CODE REVIEW

**Comment by zeripath** [comment]
Doesn't #17013 fix this?

**Comment by zeripath** [comment]
Ah this is is at a different point.

Ok, I think git log is the wrong call - certainly without a `-1`

File: modules/migrations/gitea_uploader.go [hunk 1]
```diff
@@ -689,6 +689,15 @@ func (g *GiteaLocalUploader) newPullRequest(pr *base.PullRequest) (*models.PullR
 		}
 	} else {
 		head = pr.Head.Ref
+		// Ensure the closed PR SHA still points to an existing ref
+		_, err = git.NewCommand("log", pr.Head.SHA).RunInDir(g.repo.RepoPath())
```
Comment (zeripath) [inline modules/migrations/gitea_uploader.go]: `git rev-list -1` would be better. There is almost certainly some code in modules/git that does this for you.

This as is will cause all commits and their summaries to be read in to a string to then immediately be thrown away. Thus this is a hard change request

**Review by zeripath — CHANGES_REQUESTED** [review]

File: modules/migrations/gitea_uploader.go (hunk 1 above)
Comment (99rgosse) [reply modules/migrations/gitea_uploader.go]: Thank you ! Indeed `git rev-list pr.Head.SHA -1 ` nails the problem !! 

I will look after [git/revlist](https://github.com/go-gitea/gitea/blob/main/modules/git/pipeline/revlist.go#L36) and will come back with a better thing, thank you for pointing this out !!!

Comment (zeripath) [reply modules/migrations/gitea_uploader.go]:
```suggestion
		_, err = git.NewCommand("rev-list", "-1", pr.Head.SHA).RunInDir(g.repo.RepoPath())
```

Comment (99rgosse) [reply modules/migrations/gitea_uploader.go]: Thanks for the suggstion, it works great and smooth ! 

I tried to get a look at [git/revlist](https://github.com/go-gitea/gitea/blob/main/modules/git/pipeline/revlist.go#L36) in the git modules, but this would need to catch the deprecated head to another moment and parse all PR in a channel... 
But I can check furthermore if you think this would be a better way ?
Thanks

**Review by zeripath — APPROVED** [review]

File: modules/migrations/gitea_uploader.go [hunk 2]
```diff
@@ -690,6 +690,15 @@ func (g *GiteaLocalUploader) newPullRequest(pr *base.PullRequest) (*models.PullR
 		}
 	} else {
 		head = pr.Head.Ref
+		// Ensure the closed PR SHA still points to an existing ref
+		_, err = git.NewCommand("rev-list", "-1", pr.Head.SHA).RunInDir(g.repo.RepoPath())
+		if err != nil {
+			log.Warn("Deprecated local head, removing : %v", pr.Head.SHA)
+			err = os.Remove(filepath.Join(pullHead, "head"))
```
Comment (zeripath) [inline modules/migrations/gitea_uploader.go]: Damn I think this may be the incorrect thing.

Comment (zeripath) [reply modules/migrations/gitea_uploader.go]: You need to use `git update-ref -d`

**Review by zeripath — CHANGES_REQUESTED** [review]

File: modules/migrations/gitea_uploader.go (hunk 2 above)
Comment (99rgosse) [reply modules/migrations/gitea_uploader.go]: Hello and thank you for pointing this out ! (Damn, I learn everyday with git ! :D )
Indeed the update-ref [should do the trick, but I tried this workaround in my gist](https://gist.github.com/99rgosse/b4ac3782f1b3c837b0aa01690b5b7095)

```suggestion
			relPath := "refs/pull/" + fmt.Sprintf("%d", pr.Number) + "/head"
			_, err = git.NewCommand("update-ref", "-d", relPath).RunInDir(g.repo.RepoPath())
```

but I'm not happy with it  :( :
- I cannot specify system full path in update-ref -d (thus the ugly relPath variable I put)
- If the path does not exist, update-ref will not throw an error, just move on (tried locally)
- update-ref can keep invalid sha1 pointers :

> `git fsck --full --lost-found
Checking object directories: 100% (256/256), done.
Checking objects: 100% (165029/165029), done.
error: refs/pull/20/head: invalid sha1 pointer 0000000000000000000000000000000000000000
error: refs/pull/64/head: invalid sha1 pointer 0000000000000000000000000000000000000000`

Should I keep on and find another workaround for those invalid pointers ?
Thanks in advance...

Comment (99rgosse) [reply modules/migrations/gitea_uploader.go]: I tried it with a Git version 2.33 (instead of the Git 2.17 still on ubuntu 18) 
Now update-ref gives an error for those invalid refs, but still not delete them :
`git update-ref -d refs/pull/20/head
error: cannot lock ref 'refs/pull/20/head': unable to resolve reference 'refs/pull/20/head': reference broken`

Comment (zeripath) [reply modules/migrations/gitea_uploader.go]: damn - the trouble is you can't just delete the file as the ref might be packed away. It may be that you could try using: 

```
git update-ref --no-deref -d refs/pull/20/head
```

Comment (99rgosse) [reply modules/migrations/gitea_uploader.go]: Hello and thank you ! 
 I tried --no-deref with no luck, we still keep these empty "head" files that are redirected to 40 '0'.
`git fsck --full --lost-found`
``
`Checking object directories: 100% (256/256), done.`
`Checking objects: 100% (165114/165114), done.`
``
`error: refs/pull/20/head: invalid sha1 pointer 0000000000000000000000000000000000000000`
`error: refs/pull/64/head: invalid sha1 pointer 0000000000000000000000000000000000000000`

instead, I modified to take in account these 0uid SHA1 references (that do not trigger update-ref - I checked the manpage)

Now, these 0uid were only from closed migrated PR with deleted branches or fork, so in anyway it won't be useful anymore.

Then the actual proposition uses update-ref for normal references, and a file deletion when the SHA1 is == ""

Tested with Git 2.17/2.30 and Gitea 1.15 and Dev version.

Oh and I forgot : we can add a --quiet to rev-list, as finally we throw away the correct references...

Do you agree with this ?

File: modules/migrations/gitea_uploader.go [hunk 3]
```diff
@@ -690,6 +690,21 @@ func (g *GiteaLocalUploader) newPullRequest(pr *base.PullRequest) (*models.PullR
 		}
 	} else {
 		head = pr.Head.Ref
+		// Ensure the closed PR SHA still points to an existing ref
+		_, err = git.NewCommand("rev-list", "-1", pr.Head.SHA).RunInDir(g.repo.RepoPath())
+		if err != nil {
+			if pr.Head.SHA != "" {
+				log.Warn("Deprecated local head, removing : %v", pr.Head.SHA)
+				relPath := "refs/pull/" + fmt.Sprintf("%d", pr.Number) + "/head"
```
Comment (zeripath) [inline modules/migrations/gitea_uploader.go]: `pr.GetGitRefName()` ?

```suggestion
				relPath := pr.GetGitRefName()
```

File: modules/migrations/gitea_uploader.go [hunk 4]
```diff
@@ -690,6 +690,21 @@ func (g *GiteaLocalUploader) newPullRequest(pr *base.PullRequest) (*models.PullR
...
+				_, err = git.NewCommand("update-ref", "-d", relPath).RunInDir(g.repo.RepoPath())
```
Comment (zeripath) [inline modules/migrations/gitea_uploader.go]:
```suggestion
				_, err = git.NewCommand("update-ref", "--no-deref", "-d", relPath).RunInDir(g.repo.RepoPath())
```

File: modules/migrations/gitea_uploader.go (hunk 3 above)
Comment (99rgosse) [reply modules/migrations/gitea_uploader.go]: Thanks for the suggestion ! 
I added the function in pullrequest.go 
`// GetGitRefName returns pull request relative path to head
func (p PullRequest) GetGitRefName() string {
	return fmt.Sprintf("refs/pull/%d/head", p.Number)
}`

File: modules/migrations/gitea_uploader.go (hunk 4 above)
Comment (99rgosse) [reply modules/migrations/gitea_uploader.go]: I added the "--no-deref". Everything works great,
here is a sample log :
`2021/09/29 10:02:58 ...dules/git/command.go:143:RunWithContext() [D] /home/********/gitea/data/gitea-repositories/99rgosse/*******.git: /usr/bin/git -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-list --quiet -1 41f9aa9fa4afdc8bb7fa1444a04801016e1d8685`
``
`2021/09/29 10:02:58 ...ns/gitea_uploader.go:697:newPullRequest() [W] Deprecated local head, removing : 41f9aa9fa4afdc8bb7fa1444a04801016e1d8685`
``
`2021/09/29 10:02:58 ...dules/git/command.go:143:RunWithContext() [D] /home/********/gitea/data/gitea-repositories/99rgosse/*******.git: /usr/bin/git -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= update-ref --no-deref -d refs/pull/18/head`
``
`2021/09/29 10:02:58 ...ns/gitea_uploader.go:701:newPullRequest() [W] Empty reference, removing : /home/********/gitea/data/gitea-repositories/99rgosse/*******.git/refs/pull/20`

**Review by zeripath — APPROVED** [review]

File: modules/migrations/gitea_uploader.go (hunk 4 above)
Comment (zeripath) [reply modules/migrations/gitea_uploader.go]: Cool. It's much safer to use the `update-ref` command than just blindly delete the files, so I'm happy that --no-deref fixes the problem!

File: modules/migrations/gitea_uploader.go [hunk 5]
```diff
@@ -690,6 +690,23 @@ func (g *GiteaLocalUploader) newPullRequest(pr *base.PullRequest) (*models.PullR
 		}
 	} else {
 		head = pr.Head.Ref
+		// Ensure the closed PR SHA still points to an existing ref
+		_, err = git.NewCommand("rev-list", "--quiet", "-1", pr.Head.SHA).RunInDir(g.repo.RepoPath())
+		if err != nil {
+			if pr.Head.SHA != "" {
```
Comment (lafriks) [inline modules/migrations/gitea_uploader.go:696]:
```suggestion
			if len(pr.Head.SHA) != 0 {
```

**Review by lafriks — COMMENTED** [review]
Small nit but otherwise looks good

File: modules/migrations/gitea_uploader.go (hunk 5 above)
Comment (delvh) [reply modules/migrations/gitea_uploader.go:696]: The funny thing is, as far as I have seen:
You are the only one who enforces this.
Almost everyone else uses `if str != ""`.

Comment (lafriks) [reply modules/migrations/gitea_uploader.go:696]: yeah because it was quite some time ago decided to use `len(str) == 0` so I'm manually linting it 😆

Comment (wxiaoguang) [reply modules/migrations/gitea_uploader.go:696]: I also vote for `s != ""`, although there is no difference when the code gets compiled.

* `s != ""`
* `len(s) != 0`

The first one is much shorter, and easy to read.

Comment (delvh) [reply modules/migrations/gitea_uploader.go:696]: > yeah because it was quite some time ago decided to use `len(str) == 0` so I'm manually linting it laughing

Should we have a(nother) vote on that?
I think that's the fastest way to resolve this, and then everyone knows how to handle this case in the future,

Comment (lafriks) [reply modules/migrations/gitea_uploader.go:696]: I don't mind for any of options, ex golang stdlib also uses both we just need to keep to the one in our code base.

If I remember correctly len was decided to use because you don't have to think if it's string, byte array or rune array, it will work equally good for all cases. That affects also refactoring later on.

Comment (delvh) [reply modules/migrations/gitea_uploader.go:696]: The problem however is that as far as I have seen, both are used currently inside the code.
Sometimes `str != ""` is used, and sometimes (most likely when you reviewed the PR) `len(str) != 0` is used.

Comment (wxiaoguang) [reply modules/migrations/gitea_uploader.go:696]: > because you don't have to think if it's string, byte array or rune array, it will work equally good for all cases

I think this point is not that important. When we use a `string`, we do not new `s := make()`, we do not iterate `for x := range s` , we do not update `s[k] = v`, and a `string` is immutable while array/map are mutable. They differ so much so we do not have to use `len` to all of them.

**Review by wxiaoguang — APPROVED** [review]

**Review by delvh — APPROVED** [review]

File: modules/migrations/gitea_uploader.go (hunk 5 above)
Comment (lafriks) [reply modules/migrations/gitea_uploader.go:696]: I was not the one to propose it back in the days so don't shoot the messenger 😋 I was just pointing out that that's what was agreed on and when I review and see that I just point it out. I'm used to using it myself and for myself it's easier to use len than compare to empty string as I don't have to think so much on a type used. Sadly I can't seem to find where it was discussed as it was so long ago 😂

**Comment by 99rgosse** [comment]
Sorry to disturb, should I do something in here ?

**Review by lafriks — APPROVED** [review]
