### PR TITLE
Fix missing images in editor preview due to wrong links

### LINKED ISSUE #31294: Images missing in editor markdown preview
### Description

When using the editor to edit a markdown file with images, the Preview tab no longer shows images. The images do show correctly when viewing the markdown file without the editor.

Example:
https://demo.gitea.com/brechtvl/test

It appears to be caused by #26745. The link is wrong and `/src/` should be replaced by `/media/`, which used to happen before this change.

`RenderMarkup` in `routers/common/markup.go` should probably create a `markup.Links` with `BranchPath` and `TreePath`, but I'm not sure what the best way is to achieve that.

### Gitea Version

1.22 (bbe98a3254)

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Ubuntu Linux 23.10

### How are you running Gitea?

Running own build from command line.

### Database

SQLite

### PR DESCRIPTION
**Pull request by brechtvl**
Parse base path and tree path so that media links can be correctly created with /media/.

Resolves #31294

### CODE REVIEW

**Comment by brechtvl** [comment]
This parsing of the URL seems like a hack, though it's not clear to me what else could be done without breaking the API.

**Review by silverwind — APPROVED** [review]

File: routers/common/markup.go [hunk 1]
```diff
@@ -66,6 +66,22 @@ func RenderMarkup(ctx *context.Base, repo *context.Repository, mode, text, urlPr
 		}
 	}
 
+	links := markup.Links{
+		AbsolutePrefix: true,
+		Base:           urlPrefix,
+	}
+
+	// Parse branch path and tree path, for correct media links.
+	urlElements := strings.Split(strings.TrimPrefix(urlPrefix, setting.AppURL), "/")
```
Comment (delvh) [inline routers/common/markup.go]: @wxiaoguang does `AppURL` contain `AppSubURL`?
Judging by the usage I've seen in the templates I'd assume so.
If no, then we need to trim `AppSubURL` immediately after the `AppURL`.

File: routers/common/markup.go [hunk 2]
```diff
@@ -66,6 +66,22 @@ func RenderMarkup(ctx *context.Base, repo *context.Repository, mode, text, urlPr
...
+	if len(urlElements) >= 5 && urlElements[2] == "src" {
```
Comment (delvh) [inline routers/common/markup.go]: We should document why we expect the third element to be `src`
```suggestion
	// The expected route is '<user>/<repo>/src/[branch, commit or tag]/<identifier>'
	if len(urlElements) >= 5 && urlElements[2] == "src" {
```
and yes, this feels indeed really hacky.
I can think of a few of ways that might or might not work:
- user profiles
- viewing a markdown file in a commit
- viewing a markdown file in a tag
- viewing a directory with a README file

Comment (brechtvl) [reply routers/common/markup.go]: Commit and tag should work.

The naming here is also a bit confusing because this `urlPrefix` is actually just the `Context` option for the API. And if in the future user profiles or directory READMEs were rendered with this they could construct a `Context` in the expected format for the API call.

File: routers/common/markup.go (hunk 1 above)
Comment (wxiaoguang) [reply routers/common/markup.go]: AppURL always contains AppSubURL

**Review by lafriks — APPROVED** [review]

**Comment by wxiaoguang** [comment]
@KN4CK3R would you also like to take a look?

File: routers/common/markup.go [hunk 3]
```diff
@@ -66,6 +66,23 @@ func RenderMarkup(ctx *context.Base, repo *context.Repository, mode, text, urlPr
...
+	}
+
+	// Parse branch path and tree path, for correct media links.
+	// The expected route is "{user}/{repo}/src/{branch, commit, tag]/{identifier}"
+	urlElements := strings.Split(strings.TrimPrefix(urlPrefix, setting.AppURL), "/")
+	if len(urlElements) >= 5 && urlElements[2] == "src" {
+		links = markup.Links{
+			AbsolutePrefix: true,
+			Base:           setting.AppURL + urlElements[0] + "/" + urlElements[1],
+			BranchPath:     urlElements[3] + "/" + urlElements[4],
```
Comment (wxiaoguang) [inline routers/common/markup.go]: Is it right for all cases? For example, a branch named `fix/bug-1`, then the URL is `https://.../my-corp/my-repo/src/branch/fix/bug-1/.....`, then `urlElements[3] + "/" + urlElements[4]` is not the right path.

Comment (brechtvl) [reply routers/common/markup.go]: Indeed, that's an issue. In the current code `Links` only ever concatenates `BranchPath` and `TreePath` so it works ok. But it could be a problem in the future.

If this needs to be solved, potential solutions:
* Change `markup.Links` to only store a single path instead of separate `BranchPath` and `TreePath`.
* Refactor `context.RepoRefByType` and related functions as used in routing so they can be used with an arbitrary `urlPrefix` string instead of assuming `ctx.Params`.

Comment (wxiaoguang) [reply routers/common/markup.go]: @KN4CK3R do you have some ideas? I think the new design could depend on the the plan of Rework markup link rendering (#26745)

**Comment by wxiaoguang** [comment]
Did some rewriting, I think the problems are clear now 75d5e9235237db9072ee7be3d2f2cc38192a63ab

**Comment by wxiaoguang** [comment]
Rebased with main because it needs a new method GuessCurrentHostURL

File: routers/common/markup.go [hunk 4]
```diff
@@ -7,63 +7,67 @@ package common
...
 
-	if !strings.HasPrefix(setting.AppSubURL+"/", urlPrefix) {
-		// check if urlPrefix is already set to a URL
-		linkRegex, _ := xurls.StrictMatchingScheme("https?://")
-		m := linkRegex.FindStringIndex(urlPrefix)
-		if m == nil {
-			urlPrefix = util.URLJoin(setting.AppURL, urlPrefix)
-		}
+	fields := strings.SplitN(strings.TrimPrefix(urlPathContext, setting.AppSubURL+"/"), "/", 5)
+	if len(fields) == 5 && fields[2] == "src" && fields[3] == "branch" {
```
Comment (brechtvl) [inline routers/common/markup.go]: Checking for "branch" means it won't work with commits and tags anymore.

**Review by brechtvl — COMMENTED** [review]
Thanks for improving the implementation.

File: routers/common/markup.go (hunk 4 above)
Comment (wxiaoguang) [reply routers/common/markup.go]: Let's add more .... 38dc928498149d19d72e7ae35676169ad6c3e04b

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
If nothing more to change, I am going to merge this PR  in one day.  🙏

**Review by KN4CK3R — APPROVED** [review]

**Comment by KN4CK3R** [comment]
The `/markup` and `/markdown` endpoints were problematic when I wrote #26745 because there is not much context to create a logic for every case. But as this now satisfies the old tests everything is fine.

**Comment by wxiaoguang** [comment]
I will try to backport it manually.
