### PR TITLE
Fix various problems (artifact order, api empty slice, assignee check, fuzzy prompt, mirror proxy, adopt git)

### LINKED ISSUE #33196: "Fuzzy search is disabled by default due to performance reasons" warning is delayed
### Description

The "Fuzzy search is disabled by default due to performance reasons" warning added in #33078 does not appear on the search result page. Instead, it appears on the next page you navigate to from the search results.

### Screenshots

image

### Gitea Version

1.23.1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

_No response_

### Browser Version

Firefox 128.5.2 ESR

### LINKED ISSUE #33288: Events - empty array elements as [] not null
### Description

Hi,
Currently, if a pull_request has no assignees, the event will have the following:
```
{
  "event": {
    "pull_request": {
      "assignees": null
    }
  }
  ```
  
I think it would be a better (and more intuitive) way to define arrays as empty [] rather than null (null-safe). This is also more aligned to github events.
  
Other arrays are:
topics
labels
requested_reviewers
requested_reviewers_teams

### Gitea Version

1.23.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

k8s, docker

### Database

PostgreSQL

### LINKED ISSUE #33506: Proxy settings from configuration file is not passed to push mirror operations
### Description

In mirror_pull.go, the proxy settings are retrieved and passed to git operations
https://github.com/go-gitea/gitea/blob/7e596bd7a9378cadbbd9efaf9cc622de554e056c/services/mirror/mirror_pull.go#L249-L259

However, in mirror_push.go, the environment is not passed to the underlying interface although it is supported
https://github.com/go-gitea/gitea/blob/7e596bd7a9378cadbbd9efaf9cc622de554e056c/services/mirror/mirror_push.go#L164-L169

This prevents push mirrors from using proxies.

### Gitea Version

Gitea version 1.22.4 built with GNU Make 4.3, go1.22.9 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Configure proxy.PROXY_ENABLED/PROXY_URL/PROXY_HOSTS and use push mirrors

### Database

None

### LINKED ISSUE #33521: `Network error SyntaxError:` when creating issue with assignees from issue template
### Description

One of our users has the following issue template:

```
---

name: Bug Report
about: Help improve CloudRig by submitting a bug report.
ref: "master"
title: ""
assignees: ["Mets"]
labels:

- bug

---

**System Information**
Operating system:

Blender Version: 
CloudRig Version: 

**Exact steps to reproduce the error**
Based on the human metarig or a minimal .blend file.

CC @Mets
```

The `assignees: ["Mets"]` gives error such as

Image

When a user tries to create the bug report. It seems to be related to the user not having the permissions to add such an assignee.

When I try to create the report on my Admin account it seems to work fine.

### Gitea Version

1.23.1 built with GNU Make 4.4.1, go1.23.5 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

Image
Trying to create issue as normal user

Image
Created issue successfully as admin user

### Git Version

2.47.2

### Operating System

Ubuntu 24.04

### How are you running Gitea?

Docker Compose with source of truth at https://github.com/blender/gitea

### Database

PostgreSQL

### LINKED ISSUE #33561: Gitea lockup on adopting repository with sqlite
### Description

If someone tries to adopt a repository on their instance that has a large amount of tags (tested on linux repository) the entire instance hangs.

Reproduction steps:
1. Configure gitea with sqlite
2. Copy a repository to any user directory where it can be adopted
3. Adopt the repository
4. Try to access any gitea page with browser or curl an endpoint which requires a database query - `/explore/repos` seems to work as demo

Expected behavior:
Gitea returns a page for visitor as normal and continues to adopt the repository

Actual behavior:
Entire instance doesn't respond to any requests except those which don't need database query - curl on homepage for anonymous user works but `/explore/repos` endpoint doesn't.

It does not happen with postgres, so I think it's sqlite specific - probably something to do with the entire thing being in transaction but I'm speculating at this point as I don't know enough about that area.

This does not happen with regular repository migration.

[gitea-diagnosis-20250211-173242.zip](https://github.com/user-attachments/files/18756198/gitea-diagnosis-20250211-173242.zip)

### Gitea Version

1.23.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

linux

### How are you running Gitea?

selfbuild, reproduced in container.

### Database

SQLite

### PR DESCRIPTION
**Pull request by wxiaoguang**

### CODE REVIEW

**Comment by wxiaoguang** [comment]
These changes should be not too difficult to review, and need to backport, then we don't need to open 10+ PRs

File: modules/util/slice.go [hunk 1]
```diff
@@ -71,3 +71,10 @@ func KeysOfMap[K comparable, V any](m map[K]V) []K {
 	}
 	return keys
 }
+
+func SliceNilAsEmpty[T any](a []T) []T {
```
Comment (delvh) [inline modules/util/slice.go:75]: Perhaps  `NilAsEmptySlice` would be a better name for it?

File: services/convert/pull.go [hunk 2]
```diff
@@ -94,6 +95,9 @@ func ToAPIPullRequest(ctx context.Context, pr *issues_model.PullRequest, doer *u
 		Updated:        pr.Issue.UpdatedUnix.AsTimePtr(),
 		PinOrder:       apiIssue.PinOrder,
 
+		RequestedReviewers:      []*api.User{},
+		RequestedReviewersTeams: []*api.Team{},
```
Comment (delvh) [inline services/convert/pull.go:100]: I can understand that they were previously not set -> they were excluded in the output.
But why are we setting these values to empty lists?
Shouldn't we calculate the values instead?

File: services/repository/adopt.go [hunk 3]
```diff
@@ -84,23 +90,18 @@ func AdoptRepository(ctx context.Context, doer, u *user_model.User, opts CreateR
...
 		if stdout, _, err := git.NewCommand(ctx, "update-server-info").
 			RunStdString(&git.RunOpts{Dir: repoPath}); err != nil {
 			log.Error("CreateRepository(git update-server-info) in %v: Stdout: %s\nError: %v", repo, stdout, err)
 			return fmt.Errorf("CreateRepository(git update-server-info): %w", err)
 		}
 		return nil
-	}); err != nil {
+	}(); err != nil {
+		if errDel := DeleteRepository(ctx, doer, repo, false /* no notify */); errDel != nil {
+			log.Error("Failed to delete adopt-failed repository %s: %v", repo.FullName(), errDel)
```
Comment (delvh) [inline services/repository/adopt.go]:
```suggestion
			log.Error("Failed to delete repository %s that could not be adopted (original error: %v): %v", repo.FullName(), err, errDel)
```

File: modules/util/slice.go (hunk 1 above)
Comment (wxiaoguang) [reply modules/util/slice.go:75]: It matches other `SliceXxx` util functions in this file.

File: services/convert/pull.go (hunk 2 above)
Comment (wxiaoguang) [reply services/convert/pull.go:100]: See: Events - empty array elements as [] not null #33288

>  it would be a better (and more intuitive) way to define arrays as empty [] rather than null (null-safe). This is also more aligned to github events.

File: services/repository/adopt.go (hunk 3 above)
Comment (wxiaoguang) [reply services/repository/adopt.go]: I think the rule is:

* If an error is returned, then it doesn't need to be outputed to log, it should be handled by parent callers.
* If an error is not returned, then it's better to output it into log.

This line is the first case: `err` will be returned and outputed by caller. So here we doesn't need to print it again, otherwise, duplicate.

File: services/convert/pull.go (hunk 2 above)
Comment (delvh) [reply services/convert/pull.go:100]: Ah, there.
I didn't look down far enough.
This is simply the initialization here.

File: modules/util/slice.go (hunk 1 above)
Comment (wxiaoguang) [reply modules/util/slice.go:75]: And since we only have one common "util" package, it's better to have proper "prefixes" to group these functions.

For example:

image

**Review by delvh — APPROVED** [review]

File: services/repository/adopt.go (hunk 3 above)
Comment (delvh) [reply services/repository/adopt.go]:
```suggestion
			log.Error("Failed to delete repository %s that could not be adopted: %v", repo.FullName(), errDel)
```

File: services/convert/pull.go (hunk 2 above)
Comment (wxiaoguang) [reply services/convert/pull.go:100]:
```suggestion
		// output "[]" rather than null to align to github outputs
		RequestedReviewers:      []*api.User{},
		RequestedReviewersTeams: []*api.Team{},
```

**Review by lunny — APPROVED** [review]
