### PR TITLE
Remove external service dependencies in migration tests

### LINKED ISSUE #36859: `Test_MigrateFromGiteaToGitea` fails when gitea.com is unavailable
*Written by Claude on behalf of @silverwind.*

## Description

`Test_MigrateFromGiteaToGitea` in `tests/integration/migrate_test.go` fails intermittently in CI with a timeout, causing unrelated PRs to show red CI.

## Example failure

From [PR #36858 CI run](https://github.com/go-gitea/gitea/actions/runs/22816297963/job/66181752141) (`test-sqlite` job):

```
+++ Test_MigrateFromGiteaToGitea is a slow test (run: 2m18.102875547s, flush: 87.112µs)
--- FAIL: Test_MigrateFromGiteaToGitea (138.10s)
    testlogger.go:62: 2026/03/08 07:33:40 HTTPRequest [W] router: slow      POST /api/v1/repos/migrate for test-mock:12345, elapsed 3038.6ms @ repo/migrate.go:36(repo.Migrate)
    testlogger.go:62: 2026/03/08 07:35:53 HTTPRequest [I] router: completed POST /api/v1/repos/migrate for test-mock:12345, 500 Internal Server Error in 136206.5ms @ repo/migrate.go:36(repo.Migrate)
    migrate_test.go:153: Response:  {"message":"","url":"http://localhost:3003/api/swagger"}
```

The migration call takes over 2 minutes and returns a 500 error with an empty message.

## Impact

This causes false-negative CI results on unrelated PRs, making it harder to identify real test failures.

### PR DESCRIPTION
**Pull request by silverwind**
Fix #36859

Replace live third-party API calls in migration tests with a fixture-based HTTP mock server. Fixtures are committed so tests run offline by default; live recording is gated per service on an API-token env var.

---
This PR was written with the help of Claude Opus 4.7

### CODE REVIEW

**Comment by wxiaoguang** [comment]
But you shouldn't use it to test itself.

What if the API breaks? The tests succeed, but it causes problems when released.

**Comment by silverwind** [comment]
So just write a HTTP-level mock that replicates what gitea.com currently does? I'll try that.

**Comment by wxiaoguang** [comment]
I think yes. Maybe the work can start without waiting for gitea.com, indeed there are other tests needing such feature, e.g.: gitlab, github

**Comment by TheFox0x7** [comment]
There was a tool that could record the traffic and mock the replies from the server... I'm trying to find it since it be interesting for this.

**Comment by silverwind** [comment]
I don't think we need such tools. Just a proper HTTP mock in go should do and AI can determine exactly what's needed for this test to pass.

**Comment by TheFox0x7** [comment]
Found it. Not sure if it'll be useful but linking just in case https://keploy.io/docs/keploy-explained/why-keploy/

**Comment by silverwind** [comment]
Here's the repo: https://github.com/keploy/keploy. Seems interesting but definitely out of scope for gitea right now.

**Comment by wxiaoguang** [comment]
Can be done like this https://codeberg.org/forgejo/forgejo/commits/branch/forgejo/models/unittest/mock_http.go

https://codeberg.org/forgejo/forgejo/src/branch/forgejo/models/unittest/mock_http.go

The license is still MIT, so can just copy

**Comment by silverwind** [comment]
> Can be done like this 

That server has some sort of "live mode" toggle based on the presence of an auth token where it rewrites test fixtures. Essentially it's similar to snapshot testing (but more manual), which you had rejected earlier.

Current approach now has the minimal JSON responses inline using `httptest.Server`, if think it's sufficient. But if you really want we can also implement this "live mode" stuff.

**Comment by wxiaoguang** [comment]
> Essentially it's similar to snapshot testing (but more manual), which you had rejected earlier.

Really? Which comment? I think there are some misunderstandings.

**Comment by silverwind** [comment]
> > Essentially it's similar to snapshot testing (but more manual), which you had rejected earlier.
> 
> Really? Which comment? I think there are some misunderstandings.

https://github.com/go-gitea/gitea/pull/36238#pullrequestreview-3609513620

**Comment by wxiaoguang** [comment]
> > > Essentially it's similar to snapshot testing (but more manual), which you had rejected earlier.
> > 
> > 
> > Really? Which comment? I think there are some misunderstandings.
> 
> [#36238 (review)](https://github.com/go-gitea/gitea/pull/36238#pullrequestreview-3609513620)

I think I have explained clearly:

> Because many Gitea maintainers are too lazy to write correct tests, not that experienced as typescript-go developers.

If you use "go-snaps", then the test data causing failure will just be blindly updated to make tests pass.

But here, if you have the mock server with live mode, you first test against the live servers, then capture the test data. Nobody can blindly update the test data.

They are totally different.

**Comment by silverwind** [comment]
Not that different to me, but let's see what Claude comes up if I implement that pattern.

**Comment by wxiaoguang** [comment]
The difference is whether you have a trust source which can provide the facts!!

Mocked data with live server: the live server is the trust source.

Your "go-snaps": you can blindly use the untrusted test output to update the test data without verifying them in many cases.


I hope you can understand the difference.

**Comment by silverwind** [comment]
Rewrite still in progress. Once tidbit that was noticed is the Forgejo test does not actually test the cloning of the repo so it's incomplete.

**Comment by silverwind** [comment]
Implemented that mechansim, now we can run

```
GITEA_TOKEN=<token> go test -run Test_MigrateFromGiteaToGitea ./tests/integration/ -tags='bindata sqlite sqlite_unlock_notify'
```

To record and update the test fixtures.

File: tests/integration/migrate_test.go [hunk 1]
```diff
@@ -120,24 +121,104 @@ func Test_UpdateCommentsMigrationsByType(t *testing.T) {
...
+		{"git", "-C", workDir, "-c", "commit.gpgsign=false", "commit", "--allow-empty", "-m", "initial"},
+		{"git", "-C", workDir, "tag", "V1"},
+		{"git", "-C", workDir, "-c", "commit.gpgsign=false", "commit", "--allow-empty", "-m", "second"},
+		{"git", "-C", workDir, "tag", "v2-rc1"},
+		{"git", "-C", workDir, "checkout", "-b", "6543-patch-1"},
+		{"git", "-C", workDir, "-c", "commit.gpgsign=false", "commit", "--allow-empty", "-m", "patch"},
+		{"git", "-C", workDir, "checkout", "-b", "add-xkcd-2199", "master"},
+		{"git", "-C", workDir, "-c", "commit.gpgsign=false", "commit", "--allow-empty", "-m", "xkcd"},
+		{"git", "-C", workDir, "push", "origin", "master", "6543-patch-1", "add-xkcd-2199", "V1", "v2-rc1"},
+	} {
```
Comment (wxiaoguang) [inline tests/integration/migrate_test.go]: These commands can be merged into one "fast-import"

Comment (wxiaoguang) [reply tests/integration/migrate_test.go]: And you will get fixed commit IDs, no need to do `Replacements`

Comment (silverwind) [reply tests/integration/migrate_test.go]: done in https://github.com/go-gitea/gitea/pull/36866/commits/0f6d4730b93b3958e12d91e535aef3ee0a8d5da7.

**Comment by silverwind** [comment]
I also checked other tests for external dependencies and there are a few:

| Test | File | External Service | Gate |
|------|------|-----------------|------|
| `TestGitHubDownloadRepo` | `github_test.go` | github.com | `GITHUB_READ_TOKEN` |
| `TestGitlabDownloadRepo` | `gitlab_test.go` | gitlab.com | `GITLAB_READ_TOKEN` |
| `TestGiteaDownloadRepo` | `gitea_downloader_test.go` | gitea.com | `GITEA_TEST_OFFICIAL_SITE_TOKEN` |
| `TestCodebaseDownloadRepo` | `codebase_test.go` | codebasehq.com | `CODEBASE_CLONE_USER` + 3 more |
| `TestGogsDownloadRepo` | `gogs_test.go` | try.gogs.io | `GOGS_READ_TOKEN` |
| `TestOneDevDownloadRepo` | `onedev_test.go` | code.onedev.io | HTTP reachability check |


Maybe we should also use `GITEA_TEST_OFFICIAL_SITE_TOKEN` in this test instead of `GITEA_TOKEN` (too generic name).

**Comment by silverwind** [comment]
All migration tests now follow this scheme. If a token is provided they go into live mode, otherwise they use the recorded fixtures.

- The Gogs, OneDev and Codebase fixtures were fabricated (either repo was deleted or no access)
- Gitea, GitLab and GitHub were recorded.

None of the remaining integration tests have dependencies on external services now (only local services like database etc).

**Review by lunny — APPROVED** [review]

File: services/migrations/gitlab_test.go [hunk 2]
```diff
@@ -54,63 +53,12 @@ func TestGitlabDownloadRepo(t *testing.T) {
...
-			Name:  "suggestion",
-			Color: "428bca",
-		},
-		{
-			Name:  "support",
-			Color: "f0ad4e",
-		},
-	}, labels)
+	assert.Error(t, err)
+	assert.Empty(t, labels)
```
Comment (TheFox0x7) [inline services/migrations/gitlab_test.go]: Endpoint returned 401 from what I saw in mocks (I suspect the other errors here as for the same reason). Why is that? I'm assuming the token is passed in CI currently so that's tested for and should work correct?

Comment (silverwind) [reply services/migrations/gitlab_test.go]: Might need to re-test. And no, tokens should never passed automatically, locally or on CI. Only manual.

Comment (TheFox0x7) [reply services/migrations/gitlab_test.go]: With this change yes but I'm asking if migrations are being tested in CI currently to figure out if it's a regression or if the tests weren't being ran.
I think they are from logs but I want to double check with someone who has access.

**Comment by bircni** [comment]
Updates on that?

**Review by TheFox0x7 — CHANGES_REQUESTED** [review]
@silverwind Can you rerun/fix the gitlab test so the asserts aren't removed?
Blocking until then so it won't get merged with missing asserts compared to main

**Comment by silverwind** [comment]
> @silverwind Can you rerun/fix the gitlab test so the asserts aren't removed? Blocking until then so it won't get merged with missing asserts compared to main

Done in https://github.com/go-gitea/gitea/pull/36866/changes/9c7c1d0ca302f16573702b30051184910d3ef0c0. Ready for review.

**Comment by silverwind** [comment]
@TheFox0x7 please re-check.

**Review by TheFox0x7 — COMMENTED** [review]
We get [PR 6](https://gitlab.com/gitea/test_repo/-/merge_requests/4) but test reviews on [PR 1](https://gitlab.com/gitea/test_repo/-/merge_requests/1)

I know you can't exactly control which gets pulled from gitlab but the previous one was more comprehensive and should be kept IMO - so maybe or fetch two and compare the closed and unmerged and the approved and merged one?

There's also the date change in reviews but I have no idea why it happened (both seem wrong to me) so it's probably fine.

**Comment by silverwind** [comment]
Done in https://github.com/go-gitea/gitea/pull/36866/commits/cfbe630c03b94b8cceae1d732e983eedd9d508ba and re-reviewed all other fixtures, all successful.

**Review by TheFox0x7 — APPROVED** [review]
Not exactly what I had in mind but on reading the raw gitlab test code instead of a diff I think issue assert covers what I wanted so it's fine as is IMO.
