### PR TITLE
Possible fix the webhook API creation

### LINKED ISSUE #13907: Webhooks api stopped working
- Gitea version (or commit ref): 1.14.0+dev-337-g42354dfe4
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

After upgrading from a db version 160 to 162 I get the following error when trying to add a new webhook:

`Error 1366: Incorrect integer value: 'gitea' for column git.webhook.hook_task_type`

Also Drone integration hooks are failing. Probably others too.

Maybe the migration is incomplete? https://github.com/go-gitea/gitea/pull/13664

### PR DESCRIPTION
**Pull request by lunny**
Maybe fix #13907

### CODE REVIEW

**Comment by bobemoe** [comment]
Sorry to report, still seeig the error:

```
curl -X POST "http://localhost:3000/api/v1/repos/test/test/hooks?access_token=da0c14c710e2e000fcd80d7d7b4a0b4eba9c485d" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"active\": true,  \"branch_filter\": \"master\",  \"config\": {      \"url\":\"http://test.local\",     \"content_type\":\"json\"  },  \"events\": [    \"push\"  ],  \"type\": \"gitea\"}"

{"message":"Invalid hook type: gitea","url":"http://localhost:3000/api/swagger"}
```

**Comment by bobemoe** [comment]
Is it because "Gitea" is not in the webhooks array:

https://github.com/go-gitea/gitea/blob/master/services/webhook/webhook.go#L28-L59

Previously there was a default case:

https://github.com/go-gitea/gitea/blob/v1.13.0/modules/webhook/webhook.go#L99-L138

**Comment by lunny** [comment]
@bobemoe done.

**Comment by bobemoe** [comment]
@lunny, seems to be working at fist test using curl :)  I will see if Drone is working next...

**Comment by bobemoe** [comment]
I can confirm that Drone is now able to use the API to add a webhook to a Gitea repo.

And that from Gitea I am able to successfully test delivery of the Drone webhook :)

File: services/webhook/webhook.go [hunk 1]
```diff
@@ -60,12 +60,15 @@ var (
 
 // RegisterWebhook registers a webhook
 func RegisterWebhook(name string, webhook *webhook) {
-	webhooks[models.HookTaskType(name)] = webhook
+	webhooks[models.HookTaskType(strings.TrimSpace(name))] = webhook
```
Comment (6543) [inline services/webhook/webhook.go:63]: still needed?

Comment (lunny) [reply services/webhook/webhook.go:63]: I will keep that since it's harmless.

**Review by zeripath — APPROVED** [review]

**Review by 6543 — APPROVED** [review]
