### PR TITLE
Fix ipv6 parsing

### LINKED ISSUE #7509: SSH address broken if IPv6 is used
- Gitea version (or commit ref): 1.10.0+dev-59-gf1ca8ed04
- Git version (server): 2.22.0
- Operating system: Docker (Linux 7ca71e51f279 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 Linux)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: _Not relevant_

## Description
IPv6 addresses for ssh passed as ``SSH_DOMAIN`` gets cut (on the UI side at least) to the first ``:`` presumably because the algorithm used to split the port number and address splits from left to right with no limit as to how many times it should do it. 

I'm not familiar with golang or the framework used in this case, but I think the error has something to do with this
image

## Screenshots
image

### LINKED ISSUE #10138: Improper parsing of IPv6 literals from config file
- Gitea version (or commit ref):
Gitea version 1.10.3 built with GNU Make 4.2.1, go1.13.6 : bindata, sqlite, pam
- Git version:
git version 2.25.0
- Operating system:
Arch Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
2020/02/04 11:45:59 [T] UpdatePublicKeyUpdated: http://::1:3000/api/internal/ssh/8/update
2020/02/04 11:45:59 [...io/gitea/cmd/serv.go:332 runServ()] [F] UpdatePublicKey: Post http://::1:3000/api/internal/ssh/8/update: invalid URL port ":1:3000"
```

## Description
When I try to interact with git over SSH Gitea is unable to access its internal UpdatePublicKey endpoint because of the way that it builds the URL with an IPv6 literal. The URL used is "http://::1:3000/" when it should be "http://[::1]:3000" and it looks like there is a string split happening that interprets the ":1:3000" as a port number.
```
-git pull
Verification code:
remote: Enumerating objects: 301, done.
remote: Counting objects: 100% (301/301), done.
remote: Compressing objects: 100% (258/258), done.
Gitea: Internal error4% (280/297)
UpdatePublicKey: Post http://::1:3000/api/internal/ssh/8/update: invalid URL port ":1:3000"
remote: Total 297 (delta 101), reused 0 (delta 0)
Receiving objects: 100% (297/297), 913.41 KiB | 3.18 MiB/s, done.
Resolving deltas: 100% (101/101), completed with 1 local object.
```

Error from the log file:
```
2020/02/04 11:45:59 [T] UpdatePublicKeyUpdated: http://::1:3000/api/internal/ssh/8/update
2020/02/04 11:45:59 [...io/gitea/cmd/serv.go:332 runServ()] [F] UpdatePublicKey: Post http://::1:3000/api/internal/ssh/8/update: invalid URL port ":1:3000"
```

The HTTP_ADDR in the config is set to [::1], which works for the web interface (proxied via nginx):
```
[server]
SSH_DOMAIN       = git.mydomain.com
DOMAIN           = git.mydomain.com
HTTP_PORT        = 3000
HTTP_ADDR        = [::1]
ROOT_URL         = https://git.mydomain.com/
DISABLE_SSH      = false
SSH_PORT         = 22
```
Netstat shows Gitea listening correctly on localhost:
```
tcp6       0      0 ::1:3000                :::*                    LISTEN      87006/gitea
```

I've found the relevant parts of the codebase. This line builds the internal API URL by concatentating the LocalURL setting with the API path:
https://github.com/go-gitea/gitea/blob/7dcd305424e1d3bfb1fc2b1eaa02ed47a83bddec/modules/private/serv.go#L76

Since the local URL has not been specified int he config file, this section sets the LocalURL parameter to HTTP_ADDR:HTTP_PORT/:
https://github.com/go-gitea/gitea/blob/7dcd305424e1d3bfb1fc2b1eaa02ed47a83bddec/modules/setting/setting.go#L632-L639

And this line sets the HTTP_ADDR to the value in the config file:
https://github.com/go-gitea/gitea/blob/7dcd305424e1d3bfb1fc2b1eaa02ed47a83bddec/modules/setting/setting.go#L592

The issue seems to be that when "[::1]" is parsed the brackets are dropped, which breaks the API URL building.

If I put the address in double quotes `HTTP_ADDR        = "[::1]"` the git pull succeeds but Gitea still tries to access the broken http://::1:3000/api/internal/ssh/8/update URL.

### PR DESCRIPTION
**Pull request by 42wim**
Fixes #10138

`[::1]` in the original issue is not a correct ipv6 literal. Brackets may only be placed when also specifying a port.
This PR fixes the issue when you use `::1` for the `HTTP_ADDR`

Fixes #7509

Makes sure brackets are set when needed.

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by silverwind — APPROVED** [review]

**Comment by lafriks** [comment]
🚀

File: modules/setting/setting.go [hunk 1]
```diff
@@ -627,7 +627,10 @@ func NewContext() {
 	AppSubURLDepth = strings.Count(AppSubURL, "/")
 	// Check if Domain differs from AppURL domain than update it to AppURL's domain
 	// TODO: Can be replaced with url.Hostname() when minimal GoLang version is 1.8
```
Comment (6543) [inline modules/setting/setting.go]:
```suggestion
```

**Comment by lafriks** [comment]
🚀

**Review by 6543 — APPROVED** [review]
