### PR TITLE
Fix migration v141

### LINKED ISSUE #14069: Users become "Ghost" when restoring from dump
- Gitea version (or commit ref): 1.13.0
- Git version: 2.25.1
- Operating system: Ubuntu Server 20.04 LTS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] N/A
- Log gist: N/A

## Description

Found this when testing a periodic backup. Seems that the culprit is that the last column (`keep_activity_private`) becomes `NULL` for some users in this `NOT NULL` column after upgrading to Gitea 1.13.0 from 1.12.5, which causes the exported `.sql` file to be rejected by postgresql and Gitea to display "Ghost" for those users.

### PR DESCRIPTION
**Pull request by 6543**
make filed same as in models ...

fix #14069

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
Backport: #14388

**Comment by 6543** [comment]
added migration ... @lafriks @zeripath need :eyes:

**Comment by zeripath** [comment]
I think we should add a doctor command to deal with the nulls

**Comment by lafriks** [comment]
Isn't it possible to use alter to change not null and default?

**Comment by lunny** [comment]
A recreate is dangerous that I don't think we should do that frequently. Or we could make this as an doctor command and mention user should back up some tables.

File: models/migrations/v167.go [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+		DiffViewStyle       string `xorm:"NOT NULL DEFAULT ''"`
+		Theme               string `xorm:"NOT NULL DEFAULT ''"`
+		KeepActivityPrivate bool   `xorm:"NOT NULL DEFAULT false"`
+	}
+
+	if err := x.Sync2(new(User)); err != nil {
+		return err
+	}
+
+	if _, err := x.Where(builder.Eq{"keep_activity_private": nil}).
```
Comment (lunny) [inline models/migrations/v167.go]: builder.IsNull is better

File: models/migrations/v167.go [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+package migrations
+
+import (
+	"xorm.io/builder"
+	"xorm.io/xorm"
+	"xorm.io/xorm/schemas"
+)
+
+func recreateUserTableToFixDefaultValues(x *xorm.Engine) error {
+	switch x.Dialect().URI().DBType {
```
Comment (zeripath) [inline models/migrations/v167.go]: You should set the NULL values to false before adjust constraints here.

Comment (6543) [inline models/migrations/v167.go]:
```suggestion
	if _, err := x.Where(builder.IsNull{"keep_activity_private"}).
		Cols("keep_activity_private").
		Update(User{KeepActivityPrivate: false}); err != nil {
		return err
	}

	switch x.Dialect().URI().DBType {
```

File: models/migrations/v167.go [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+		return err
+	case schemas.POSTGRES:
+		if _, err := x.Exec("ALTER TABLE `user` ALTER COLUMN keep_activity_private SET NOT NULL;"); err != nil {
+			return err
+		}
+		_, err := x.Exec("ALTER TABLE `user` ALTER COLUMN keep_activity_private SET DEFAULT false;")
+		return err
+	}
+
+	type User struct {
```
Comment (6543) [inline models/migrations/v167.go]:
```suggestion
```

File: models/migrations/v167.go [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+		ID                  int64 `xorm:"pk autoincr"`
```
Comment (6543) [inline models/migrations/v167.go]:
```suggestion
```

File: models/migrations/v167.go [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+		KeepActivityPrivate bool  `xorm:"NOT NULL DEFAULT false"`
```
Comment (6543) [inline models/migrations/v167.go]:
```suggestion
```

File: models/migrations/v167.go [hunk 6]
```diff
@@ -0,0 +1,63 @@
...
+	}
```
Comment (6543) [inline models/migrations/v167.go]:
```suggestion
```

File: models/migrations/v167.go [hunk 7]
```diff
@@ -0,0 +1,63 @@
...
+		_, err := x.Exec("ALTER TABLE `user` MODIFY COLUMN keep_activity_private tinyint(1) DEFAULT 0 NOT NULL;")
+		return err
+	case schemas.POSTGRES:
+		if _, err := x.Exec("ALTER TABLE `user` ALTER COLUMN keep_activity_private SET NOT NULL;"); err != nil {
+			return err
+		}
+		_, err := x.Exec("ALTER TABLE `user` ALTER COLUMN keep_activity_private SET DEFAULT false;")
+		return err
+	}
+
```
Comment (6543) [inline models/migrations/v167.go]:
```suggestion
```

File: models/migrations/v167.go [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+package migrations
+
+import (
+	"xorm.io/builder"
+	"xorm.io/xorm"
+	"xorm.io/xorm/schemas"
+)
+
+func recreateUserTableToFixDefaultValues(x *xorm.Engine) error {
+	if _, err := x.Where(builder.IsNull{"keep_activity_private"}).
```
Comment (6543) [inline models/migrations/v167.go]:
```suggestion
	type User struct {
		ID                  int64 `xorm:"pk autoincr"`
		KeepActivityPrivate bool  `xorm:"NOT NULL DEFAULT false"`
	}

	if _, err := x.Where(builder.IsNull{"keep_activity_private"}).
```

File: models/migrations/v167.go [hunk 9]
```diff
@@ -0,0 +1,63 @@
...
+	sess := x.NewSession()
+	defer sess.Close()
+	if err := sess.Begin(); err != nil {
+		return err
+	}
+
+	var activityPrivateUsers []int64
+	if err := sess.Select("id").Table("user").Where(builder.Eq{"keep_activity_private": true}).Find(&activityPrivateUsers); err != nil {
+		return err
+	}
```
Comment (zeripath) [inline models/migrations/v167.go]: this should be small - but there is no guarantee. Not sure whether we should just be creating a temp table column or otherwise for this.

**Review by techknowlogick — DISMISSED** [review]
Blocking as per @zeripath's feedback re: temporary column. On gitea.com we have 16k+ users, so memory usage of storing their IDs in memory isn't insignificant.
and there are other Gitea instances that are just as large (and even larger).

**Comment by 6543** [comment]
@techknowlogick now it use the `use 2x add col & 2x update & 2x drop col` algo

**Review by zeripath — APPROVED** [review]

**Comment by 6543** [comment]
@zeripath now this cause somehow a DB deadlock :/
https://drone.gitea.io/go-gitea/gitea/35207/3/5
https://drone.gitea.io/go-gitea/gitea/35207/2/14

**Comment by 6543** [comment]
.
