### PR TITLE
Instead of using routerCtx just escape the url before routing

### LINKED ISSUE #17938: WebGUI: Escape character in folder or file name prevents access
* Gitea version (or commit ref): 1.15.7 built with GNU Make 4.1, go1.16.10 : bindata, sqlite, sqlite_unlock_notify
* Git version: 2.30.2
* Operating system: Debian GNU/Linux 11 (bullseye)
* Database (use [x]):
   - [x]  PostgreSQL
   - [ ] MySQL
   - [ ] MSSQL
   - [ ] SQLite
* Can you reproduce the bug at https://try.gitea.io:
   - [x] Yes (provide example URL): https://try.gitea.io/sebveit/meta-openwrt
   - [ ] No

### Description
I've cloned a repository from GitHub that uses the percentage character (%) in file and folder names a lot. This %-char prevents the access, via the web GUI of Gitea, to the file or folder containing this char in its name.
It looks like Gitea is displaying the %-char correctly but fails to provide the correct URL when clicking on it.
When I modify the URL and try to access it, nginx answers with `400 Bad Request`.

### Example
Expected URL: https://try.gitea.io/sebveit/meta-openwrt/src/branch/master/recipes-tweaks/busybox/busybox_%.bbappend
Actual URL: https://try.gitea.io/sebveit/meta-openwrt/src/branch/master/recipes-tweaks/busybox/busybox_%25.bbappend

### Reverse Proxy
I'm using nginx (1.18) as a reverse proxy for Gitea. My config for nginx is the following:

```
server {
    listen 443 ssl;
    server_name gitea.somedomain.tld;
    ssl_certificate     /etc/nginx/ssl/gitea.somedomain.tld.crt;
    ssl_certificate_key /etc/nginx/ssl/gitea.somedomain.tld.key;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 50M;
    }
}
```

I hope that helps pinpointing the bug. Let me know if you need additional information.
BTW, Gitea is really nice and slim compared to the bloated GitLab.

### LINKED ISSUE #18060: Trailing slash leads to 404 (regression?)
### Gitea Version

3a77465e4ed252f5d92da12321613328b30b941c

### Git Version

2.30.2 (not relevant?)

### Operating System

Debian GNU/Linux 11

### How are you running Gitea?

local development via make

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Description

Release 1.15.8 might contain a regression. At Codeberg.org we were made aware by users that a trailing slash in the URL leads to a simple "404 page not found" now, breaking some links on the site. If this route is no longer to be used, a forward would be a good option instead.

I made a bisect:

~~~
3a77465e4ed252f5d92da12321613328b30b941c is the first bad commit
commit 3a77465e4ed252f5d92da12321613328b30b941c
Author: zeripath <art27@cantab.net>
Date:   Thu Dec 16 23:03:20 2021 +0000

    Prevent double decoding of % in url params  (#17997) (#18001)
~~~
So 3a77465e4ed252f5d92da12321613328b30b941c (#17997) (#18001) are relevant.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by zeripath**
A consequence of forcibly setting the RoutePath to the escaped url is that the
auto routing to endpoints without terminal slashes fails (Causing #18060.) This
failure raises the possibility that forcibly setting the RoutePath causes other
unexpected behaviours too.

Therefore, instead we should simply pre-escape the URL in the process registering
handler. Then the request URL will be properly escaped for all the following calls.

Fix #17938
Fix #18060
Replace #18062
Replace #17997

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

File: integrations/links_test.go [hunk 1]
```diff
@@ -61,16 +61,6 @@ func TestRedirectsNoLogin(t *testing.T) {
 		resp := MakeRequest(t, req, http.StatusFound)
 		assert.EqualValues(t, path.Join(setting.AppSubURL, redirectLink), test.RedirectURL(resp))
 	}
-
-	var temporaryRedirects = map[string]string{
```
Comment (lunny) [inline integrations/links_test.go:65]: But we can add a link test in line 92 of this file.

Comment (zeripath) [reply integrations/links_test.go:65]: ~~Nope it doesn't redirect anymore~~ Sorry I see what you mean.

I've just added it to the earlier test.

**Review by wxiaoguang — APPROVED** [review]
Changing `req.URL.RawPath` seems strange, but not bad.

**Review by lunny — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]
