### PR TITLE
Recognize more characters in crossreferenced repo name

### LINKED ISSUE #3412: The use of dash (-) in repository names breaks cross-referencing in issues
- Gitea version (or commit ref): 82a7b02
- Git version: ?
- Operating system: irrelevant
- Database (use `[x]`): irrelevant
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: see below
  - [ ] No
  - [ ] Not relevant
## Description

When you try to cross-reference an issue in a repository whose name contains a dash (`-˙ symbol), the automatic referencing breaks.

See here:
* [Cross-referencing when dash is used does not work](https://try.gitea.io/ZeroNet/ZeroNet/issues/3#issuecomment-1889)
* [Cross-referencing when dash is not used works](https://try.gitea.io/ZeroNet/ZeroNet/issues/3#issuecomment-1906)

Props to @lafriks for zeroing in the bug.

### PR DESCRIPTION
**Pull request by lafriks**
Fixes #3412

### CODE REVIEW

File: modules/markup/html.go [hunk 1]
```diff
@@ -43,7 +43,7 @@ var (
 	IssueAlphanumericPattern = regexp.MustCompile(`( |^|\()[A-Z]{1,10}-[1-9][0-9]*\b`)
 	// CrossReferenceIssueNumericPattern matches string that references a numeric issue in a different repository
 	// e.g. gogits/gogs#12345
-	CrossReferenceIssueNumericPattern = regexp.MustCompile(`( |^)[0-9a-zA-Z]+/[0-9a-zA-Z]+#[0-9]+\b`)
+	CrossReferenceIssueNumericPattern = regexp.MustCompile(`( |^)[0-9a-zA-Z-_\.]+/[0-9a-zA-Z-_\.]+#[0-9]+\b`)
```
Comment (thehowl) [inline modules/markup/html.go:46]: Before anyone researches this: did that already - both RegisterForm and CreateRepoForm in modules/auth use AlphaDashDot as a rule in the binding field, which in turn inside macaron is converted into "Every string that matches [this](https://sourcegraph.com/github.com/go-gitea/gitea/-/blob/vendor/github.com/go-macaron/binding/binding.go#L247) should be rejected".

**Review by thehowl — APPROVED** [review]
LGTM

**Comment by lunny** [comment]
LGTM. (Off topic: why the CI Successfully this PR?)
