### PR TITLE
Fix panic when getting notes by ref

### LINKED ISSUE #23357: Getting notes of a tag via API triggers panic
### Description

Hi,

I've been experimenting with `git notes` and noticed that notes on tags are not properly handled. See this link: https://try.gitea.io/api/v1/repos/wiktor/dks/git/notes/v1

It triggers the following panic:

```
2023/03/07 11:58:58 ...common/middleware.go:71:1() [E] [640718f2] PANIC: runtime error: invalid memory address or nil pointer dereference
	/usr/lib/go/src/runtime/panic.go:260 (0x45883c)
		panicmem: panic(memoryError)
	/usr/lib/go/src/runtime/signal_unix.go:837 (0x45880c)
		sigpanic: panicmem()
	/home/wiktor/src/open-source/gitea/modules/git/tree_entry_nogogit.go:93 (0x1019cda)
		(*TreeEntry).Blob: ID:      te.ID,
	/home/wiktor/src/open-source/gitea/modules/git/notes_nogogit.go:56 (0x1019a12)
		GetNote: blob := entry.Blob()
	/home/wiktor/src/open-source/gitea/routers/api/v1/repo/notes.go:62 (0x220f0a4)
		getNote: if err := git.GetNote(ctx, ctx.Repo.GitRepo, identifier, &note); err != nil {
```

I think the code assumes notes are only for commits and tries to get the Tree but Tags don't have it.

### Gitea Version

1.20.0+dev-101-g84a299310

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Locally and via try.gitea.io

### Database

None

### PR DESCRIPTION
**Pull request by Zettat123**
Fix #23357 .

Now the `/repos/{owner}/{repo}/git/notes/{sha}` API supports getting notes by a ref or sha (https://try.gitea.io/api/swagger#/repository/repoGetNote). But the `GetNote` func can only accept commit ID.
https://github.com/go-gitea/gitea/blob/a12f5757372f751d25f9e5ca1f168f6920ded894/modules/git/notes_nogogit.go#L18

So we need to convert the query parameter to commit ID before calling `GetNote`.

### CODE REVIEW

File: routers/api/v1/repo/notes.go [hunk 1]
```diff
@@ -58,8 +58,14 @@ func getNote(ctx *context.APIContext, identifier string) {
 		return
 	}
 
+	commitSHA, err := ctx.Repo.GitRepo.ConvertToSHA1(identifier)
+	if err != nil {
+		ctx.NotFound(err)
```
Comment (delvh) [inline routers/api/v1/repo/notes.go]: `NotFound` on error?
Not `ServerError`?
I think we should differentiate between the two when possible.

**Review by delvh — APPROVED** [review]

File: routers/api/v1/repo/notes.go (hunk 1 above)
Comment (Zettat123) [reply routers/api/v1/repo/notes.go]: Yes, you're right. I added a check to differentiate error types.

**Review by delvh — APPROVED** [review]

**Review by lunny — APPROVED** [review]
