### PR TITLE
Modify OAuth login ui and fix display name, iconurl related logic

### LINKED ISSUE #24808: Login UX – SSO login options unclear to users
### Description

I get questions all the time from new users about how to login to Gitea using our SSO, and I've concluded that the login form is just not clear about the option to login from those options.

I would suggest we can:

1. ~~Place SSO options (if configured) at the top of the form~~
2. Make the SSO options look more like buttons
3. Create a better division between them
4. Clearly show that users can logon with SSO _OR_ they can use the username/password form

### Screenshots

image

image

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

N/A

### Browser Version

N/A

### PR DESCRIPTION
**Pull request by HesterG**
Close #24808 

Co-Authour @wxiaoguang @silverwind 

1. Most svgs are found from https://worldvectorlogo.com/ , and some are from conversion of png to svg. (facebook and nextcloud). And also changed `templates/user/settings/security/accountlinks.tmpl`. 

2. Fixed display name and iconurl related logic

# After

Screen Shot 2023-06-05 at 14 09 05

On mobile

Screen Shot 2023-06-05 at 14 09 46

user/settings/security/accountlinks (The dropdown might be improved later)

Screen Shot 2023-06-01 at 10 01 44

### CODE REVIEW

**Comment by silverwind** [comment]
1. Vertical margin between the buttons can be reduced a bit
2. I think we could remove the "Sign in with" text if we put a "or" word over the divider, so when looking at the page as a whole, it still makes sense.

**Comment by denyskon** [comment]
I'm not a maintainer, just curious, what's the reason for colored background at Facebook and Twitter button? It looks a bit out-of-place to me....

**Comment by silverwind** [comment]
> I'm not a maintainer, just curious, what's the reason for colored background at Facebook and Twitter button? It looks a bit out-of-place to me....

I thought that just indicated a hover effect but on closer look, it does look to be permanent. Yes, remove it and just color the logo as per those brands' color.

**Comment by HesterG** [comment]
> > I'm not a maintainer, just curious, what's the reason for colored background at Facebook and Twitter button? It looks a bit out-of-place to me....
> 
> I thought that just indicated a hover effect but on closer look, it does look to be permanent. Yes, remove it and just color the logo as per those brands' color.

These are semantic's styles, they have themes background colors for `.ui.facebook.button` and `.ui.twitter.button`, should we overwrite the background color to white?

**Comment by HesterG** [comment]
> 1. Vertical margin between the buttons can be reduced a bit
> 2. I think we could remove the "Sign in with" text if we put a "or" word over the divider, so when looking at the page as a whole, it still makes sense.

Done in https://github.com/go-gitea/gitea/pull/25030/commits/8588001c8302b812160dfc2936a089cf09a8c9c1

Screen Shot 2023-06-01 at 15 15 35

**Comment by silverwind** [comment]
I think it may be possible to alter fomantic's build to exclude those via `variationButtonSocial`, let me check.

**Comment by silverwind** [comment]
Yes, it works. Apply this diff, then run `make fomantic`:

```diff
diff --git a/web_src/fomantic/_site/globals/site.variables b/web_src/fomantic/_site/globals/site.variables
index dcd9c2f08c..b09fb90b71 100644
--- a/web_src/fomantic/_site/globals/site.variables
+++ b/web_src/fomantic/_site/globals/site.variables
@@ -6,4 +6,5 @@
 @useCustomScrollbars: false;
 @disabledOpacity: var(--opacity-disabled);
 @variationPopupTooltip: false;
 @linkHoverUnderline: underline;
+@variationButtonSocial: false;
```

**Comment by HesterG** [comment]
> remove semantic Button Social

Thanks! Done in https://github.com/go-gitea/gitea/pull/25030/commits/753350ebf493d98f62022cfe08aaaf4dc87960c2. Is this line changes normal? Looks like a lot of `-webkit` prefix is attached as well.

File: services/auth/source/oauth2/providers_base.go [hunk 1]
```diff
@@ -24,6 +24,17 @@ func (b *BaseProvider) Image() string {
...
 }
 
+// SvgName returns svg name for this provider
+func (b *BaseProvider) SvgName() string {
+	if b.name == "github" {
+		return "octicon-mark-github"
+	}
+	if b.name == "gplus" {
+		return "gitea-google"
+	}
```
Comment (delvh) [inline services/auth/source/oauth2/providers_base.go]: Alternatively, we could symlink the files `gitea-github.svg` → `octicon-mark-github.svg`, and `gitea-gplus.svg` → `gitea-google.svg`.
That way, we don't have to do this weird edge case handling.
But it might introduce problems for Windows users as symlink support seems to be pretty recent there.

**Comment by HesterG** [comment]
> Must be something about your environment that makes fomantic output all these vendor prefixes, it does not do that for me. I rebuilt it myself and pushed it.

Thanks, this is really weird..

**Comment by silverwind** [comment]
> > Must be something about your environment that makes fomantic output all these vendor prefixes, it does not do that for me. I rebuilt it myself and pushed it.
> 
> Thanks, this is really weird..

Maybe it's related to browserslist or something. Do you have any environment vars set for it maybe?

File: services/auth/source/oauth2/providers_base.go (hunk 1 above)
Comment (silverwind) [reply services/auth/source/oauth2/providers_base.go]: Symlinks in git work, but I'd rather avoid them. I think this mapping is fine.

File: services/auth/source/oauth2/providers_base.go [hunk 2]
```diff
@@ -24,6 +24,17 @@ func (b *BaseProvider) Image() string {
 	return "/assets/img/auth/" + b.name + ".png"
 }
```
Comment (silverwind) [inline services/auth/source/oauth2/providers_base.go]: Is this unused or obsolete now?

**Comment by silverwind** [comment]
I think we should do away with the `/assets/img/auth` directory.

**Comment by silverwind** [comment]
> I think we should do away with the `/assets/img/auth` directory.

Only `openid_connect.svg` remains in that directory, and I think we can replace it with the textless version in `web_src/svg/gitea-openid.svg`.

File: services/auth/source/oauth2/providers_base.go (hunk 2 above)
Comment (HesterG) [reply services/auth/source/oauth2/providers_base.go]: It is unused, but I am not sure if it should be removed on a design level.

Comment (HesterG) [reply services/auth/source/oauth2/providers_base.go]: And `NewImagedProvider` is also not used after https://github.com/go-gitea/gitea/pull/25030/commits/ed03bf51f698db913f2889bf566390e87b0c2f32

Comment (silverwind) [reply services/auth/source/oauth2/providers_base.go]: I see no point in keeping unused methods around.

**Comment by silverwind** [comment]
Some more tweaks done:

- Add "Sign in with" to buttons, otherwise they look bare
- Increase icon size
- Exclude divider from loading state

Screenshot 2023-06-03 at 01 06 04

**Review by silverwind — APPROVED** [review]
https://github.com/go-gitea/gitea/pull/25030#discussion_r1213418986 would be nice, but no blocker I guess.

File: services/auth/source/oauth2/providers_base.go (hunk 2 above)
Comment (wxiaoguang) [reply services/auth/source/oauth2/providers_base.go]: Agree to remove it.

File: templates/user/auth/signin_inner.tmpl [hunk 3]
```diff
@@ -53,29 +53,21 @@
...
-							{{svg "gitea-openid" 40}}
-						{{else}}
-							<img
-								class="gt-object-contain"
-								width="40"
-								height="40"
-								alt="{{$provider.DisplayName}}{{if eq $provider.Name "openidConnect"}} ({{$key}}){{end}}"
-								src="{{AppSubUrl}}{{$provider.Image}}"
-							>
+					<a class="{{$provider.Name}} ui compact button silenced gt-df gt-ac gt-jc gt-py-3 oauth-login-link" href="{{AppSubUrl}}/user/oauth2/{{$key}}">
```
Comment (wxiaoguang) [inline templates/user/auth/signin_inner.tmpl]: Since this is a rewriting, I'd like to ask "what's the `silenced` for?" We don't want to color the link? Usually most links should have hover colors.

And I guess `compact` is overridden by `gt-py-3`

(just a question)

File: web_src/css/form.css [hunk 4]
```diff
@@ -309,7 +309,8 @@ textarea:focus,
   .user.reset.password form .inline.field > textarea,
   .user.link-account form .inline.field > textarea,
   .user.signin form .inline.field > textarea,
-  .user.signup form .inline.field > textarea {
+  .user.signup form .inline.field > textarea,
+  .oauth-login-link {
```
Comment (wxiaoguang) [inline web_src/css/form.css:313]: It doesn't look good to me to mix this `oauth-login-link ` with other "form elements".

Actually, I think you only need to do:

```
.oauth-login-link {
   width: 100%;
   max-width: ....;
}
```

File: templates/user/auth/signin_inner.tmpl (hunk 3 above)
Comment (wxiaoguang) [reply templates/user/auth/signin_inner.tmpl]: Tested, neither `compact` nor `silenced` has affect. Will remove them.

File: web_src/css/form.css (hunk 4 above)
Comment (wxiaoguang) [reply web_src/css/form.css:313]: I think the problem is that these "form" styles are not well designed, so maybe it's better to keep this at the moment.

File: services/auth/source/oauth2/providers_base.go (hunk 2 above)
Comment (wxiaoguang) [reply services/auth/source/oauth2/providers_base.go]: After reading the code, I think this "Image()" can't be removed. 

And I guess some PRs broke the "auth icon" system


Users could set IconURL when editing an OAuth2 auth source, that image should be used, but not the svg icon.

**Review by wxiaoguang — CHANGES_REQUESTED** [review]
It breaks the customized OAuth2 icon

File: templates/user/auth/signin_inner.tmpl (hunk 3 above)
Comment (silverwind) [reply templates/user/auth/signin_inner.tmpl]: It was for the GitHub SVG that previously turned primary color on hover, which was undesirable. I think it still does.

File: services/auth/source/oauth2/providers_base.go (hunk 2 above)
Comment (HesterG) [reply services/auth/source/oauth2/providers_base.go]: Added back `Image()` and removed `SvgName()`, but used `svg` instead of `png` as default icon images, please review again, thanks.

**Comment by wxiaoguang** [comment]
The (nearly) complete fix could be like this: 9d17b20211abfdc7c444004c065dfb29f4883dca


image

**Comment by HesterG** [comment]
This PR is ready for review again.

**Review by silverwind — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Comment by silverwind** [comment]
Actually this contains two "regressions":



- GitHub Icon does not inherit `color` because it's embedded as image instead of inline SVG.
- I think we should not show the auth soure name except for the OpenID case, so that this still says "Sign in with GitHub".

**Comment by wxiaoguang** [comment]
> * I think we should not show the auth soure name except for the OpenID case, so that this still says "Sign in with GitHub".

You can set the auth source name to GitHub.

Otherwise, if you have two GitHub sources, they would be displayed as "Sign in with GitHub" / "Sign in with GitHub", people can't know which one is which.

**Comment by silverwind** [comment]
I see. We should at least call this out in the changelog so people update their auth source names. @lunny can you update try.gitea.com and gitea.com with "GitHub" as the auth source name?

**Comment by silverwind** [comment]
I will check what's necessary to use inline SVGs instead of these unflexible `img` embeds.

**Comment by wxiaoguang** [comment]
If it needs to use inline SVG, it could use `ImageHTML()` instead of `ImageURL()`

Then `ImageHTML()` could returns `<svg>` or ``.

**Comment by silverwind** [comment]
Hmm I'm not sure how to do that, but I'll push up my WIP, so you can assist me there. The built-in icons should all use inline SVG, and if the user sets a custom one, it should use `img`.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/25171

**Comment by silverwind** [comment]
For the changelog:

OAuth Login Screen buttons now render the name of the Login Source instead of the name of the provider. If this name is undesirable, rename the login source and keep note that it will also require changing the Callback URL on the OAuth Provider.
