### PR TITLE
[Bug] [API] Add language to user api

### LINKED ISSUE #8961: [BUG] [API] GET /user "language" empty
version current gitea.com

return "language": "" eaven if English is set in profile

### PR DESCRIPTION
**Pull request by 6543**
close #8961

### CODE REVIEW

**Comment by 6543** [comment]
@lunny smal bugfix :D

File: modules/convert/convert.go [hunk 1]
```diff
@@ -257,7 +257,7 @@ func ToTeam(team *models.Team) *api.Team {
 
 // ToUser convert models.User to api.User
 // signed shall only be set if requester is logged in. authed shall only be set if user is site admin or user himself
-func ToUser(user *models.User, signed, authed bool) *api.User {
+func ToUser(user *models.User, signed bool, authed bool) *api.User {
```
Comment (jolheiser) [inline modules/convert/convert.go]: This line doesn't need to change, it's valid Go.

**Review by jolheiser — CHANGES_REQUESTED** [review]

File: modules/convert/convert.go (hunk 1 above)
Comment (6543) [reply modules/convert/convert.go]: yes thought this is more readable

Comment (6543) [reply modules/convert/convert.go]: @jolheiser yes thought this is more readable

**Review by lafriks — APPROVED** [review]

File: modules/convert/convert.go (hunk 1 above)
Comment (lafriks) [reply modules/convert/convert.go]: I agree, this is preffered:
```suggestion
func ToUser(user *models.User, signed, authed bool) *api.User {
```

**Review by jolheiser — APPROVED** [review]
Other than reverting that top line, LGTM.

File: modules/convert/convert.go (hunk 1 above)
Comment (6543) [reply modules/convert/convert.go]: OK

**Comment by 6543** [comment]
@lunny ready for merge :rocket:
