### PR TITLE
Fix bug when a user delete but assigned on issue

### LINKED ISSUE #3314: Issues - Do not bail out on non-existing users, say something like 'unknown user' instead
- Gitea version (or commit ref): 8ef1711
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
2018/01/06 21:35:02 [...outers/repo/issue.go:706 ViewIssue()] [E] LoadAssignees: user does not exist [uid: 9, name: , keyid: 0]
```
## Description

If you delete an user and that user is assigned to tickets, you cannot view/edit them as gitea bails out with an error 500

### PR DESCRIPTION
**Pull request by lunny**
wiil fix #3314

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

File: models/issue_comment.go [hunk 1]
```diff
@@ -247,14 +247,20 @@ func (c *Comment) LoadAssignees() error {
 	if c.OldAssigneeID > 0 {
 		c.OldAssignee, err = getUserByID(x, c.OldAssigneeID)
 		if err != nil {
-			return err
+			if !IsErrUserNotExist(err) {
+				return err
+			}
+			c.OldAssignee = NewGhostUser()
```
Comment (bkcsoft) [inline models/issue_comment.go:253]: Why not unassign the issue? 🤔

Comment (lafriks) [reply models/issue_comment.go:253]: Issue is unassigned afaik, this is just comment that issue was assigned to user
