### PR TITLE
Fix pull view when head repository or head branch missed and close related pull requests when delete head repository or head branch

### LINKED ISSUE #9914: View pull request 500
In a migrated repository, some pull request pages return 500 when view the page.

```
2020/01/21 20:53:09 ...vices/pull/update.go:67:GetDiverging() [T] PushToBaseRepo[11]: pushing commits to base repo 'refs/pull/661/head'
2020/01/21 20:53:09 routers/repo/pull.go:348:PrepareViewPullInfo() [E] GetDiverging: exit status 128 - fatal: ambiguous argument 'master..unknown repository': unknown revision or path not in the working tree.
	Use '--' to separate paths from revisions, like this:
	'git <command> [<revision>...] -- [<file>...]'
	
2020/01/21 20:53:09 ...s/context/context.go:139:HTML() [D] Template: status/500
```

### PR DESCRIPTION
**Pull request by lunny**
Fix #9914 

- [x] only load head information when head repository/branch valid.
- [x] close all branch related unmerged pull requests when the branch deleted
- [x] close all repository related unmerged pull requests when repo deleted
- [x] broken pull requests tests

### CODE REVIEW

**Comment by lunny** [comment]
It's ready to review now.

File: models/pull.go [hunk 1]
```diff
@@ -67,7 +67,11 @@ type PullRequest struct {
 // MustHeadUserName returns the HeadRepo's username if failed return blank
 func (pr *PullRequest) MustHeadUserName() string {
 	if err := pr.LoadHeadRepo(); err != nil {
-		log.Error("LoadHeadRepo: %v", err)
+		if !IsErrRepoNotExist(err) {
+			log.Error("LoadHeadRepo: %v", err)
+		} else {
+			log.Warn("LoadHeadRepo %d but repository is not exist: %v", pr.HeadRepoID, err)
```
Comment (guillep2k) [inline models/pull.go]:
```suggestion
			log.Warn("LoadHeadRepo %d but repository does not exist: %v", pr.HeadRepoID, err)
```

File: modules/repofiles/update.go [hunk 2]
```diff
@@ -495,9 +495,18 @@ func PushUpdate(repo *models.Repository, branch string, opts PushUpdateOptions)
 		return err
 	}
 
-	log.Trace("TriggerTask '%s/%s' by %s", repo.Name, branch, pusher.Name)
+	if opts.NewCommitID != git.EmptySHA {
+		if err = models.RemoveDeletedBranch(repo.ID, opts.Branch); err != nil {
```
Comment (guillep2k) [inline modules/repofiles/update.go:499]: Delete branch on normal push? 🤔 Maybe this goes in the `else` part.

File: modules/repofiles/update.go [hunk 3]
```diff
@@ -495,9 +495,18 @@ func PushUpdate(repo *models.Repository, branch string, opts PushUpdateOptions)
 		return err
 	}
 
-	log.Trace("TriggerTask '%s/%s' by %s", repo.Name, branch, pusher.Name)
+	if opts.NewCommitID != git.EmptySHA {
```
Comment (guillep2k) [inline modules/repofiles/update.go]:
```suggestion
	if !isDelRef {
```

File: modules/repofiles/update.go (hunk 2 above)
Comment (zeripath) [inline modules/repofiles/update.go:499]: But if the new commit id is not empty the branch has not been deleted...

Why are you deleting it here?

File: modules/repofiles/update.go [hunk 4]
```diff
@@ -544,11 +553,14 @@ func PushUpdates(repo *models.Repository, optsList []*PushUpdateOptions) error {
 			if err = models.RemoveDeletedBranch(repo.ID, opts.Branch); err != nil {
```
Comment (zeripath) [inline modules/repofiles/update.go:553]: Similarly here ...

File: modules/repofiles/update.go (hunk 2 above)
Comment (lunny) [reply modules/repofiles/update.go:499]: This will remove the deleted branch information from database, it's not to delete the branch.
The table deleted branch is designed to restore branch deletion.

Comment (lunny) [reply modules/repofiles/update.go:499]: see https://github.com/go-gitea/gitea/pull/9927#discussion_r369635383

File: modules/repofiles/update.go (hunk 4 above)
Comment (lunny) [reply modules/repofiles/update.go:553]: see https://github.com/go-gitea/gitea/pull/9927#discussion_r369635383

**Comment by lunny** [comment]
@guillep2k @zeripath done.

File: services/pull/pull.go [hunk 5]
```diff
@@ -355,3 +355,79 @@ func PushToBaseRepo(pr *models.PullRequest) (err error) {
...
 }
+
+type errlist []error
+
+func (errs errlist) Error() string {
+	if len(errs) > 0 {
+		var buf strings.Builder
+		for i, err := range errs {
+			if i > 0 {
+				buf.WriteString(",")
```
Comment (guillep2k) [inline services/pull/pull.go]:
```suggestion
				buf.WriteString(", ")
```
For readability?

File: services/pull/pull.go [hunk 6]
```diff
@@ -355,3 +355,79 @@ func PushToBaseRepo(pr *models.PullRequest) (err error) {
...
+
+	prs = append(prs, prs2...)
+	if err := models.PullRequestList(prs).LoadAttributes(); err != nil {
+		return err
+	}
+
+	var errs errlist
+	for _, pr := range prs {
+		if err = issue_service.ChangeStatus(pr.Issue, doer, true); err != nil {
+			errs = append(errs, err)
```
Comment (guillep2k) [inline services/pull/pull.go:395]: We should ignore `ErrIssueWasClosed` errors.

File: services/pull/pull.go [hunk 7]
```diff
@@ -355,3 +355,79 @@ func PushToBaseRepo(pr *models.PullRequest) (err error) {
...
+			return err
+		}
+
+		if err = models.PullRequestList(prs).LoadAttributes(); err != nil {
+			return err
+		}
+
+		for _, pr := range prs {
+			if err = issue_service.ChangeStatus(pr.Issue, doer, true); err != nil {
+				errs = append(errs, err)
```
Comment (guillep2k) [inline services/pull/pull.go:424]: Same here

File: modules/repofiles/update.go (hunk 2 above)
Comment (zeripath) [reply modules/repofiles/update.go:499]: Ah! thank you that's a remarkably badly named function.

**Comment by lunny** [comment]
@guillep2k done.

**Review by guillep2k — APPROVED** [review]
LGTM

**Review by zeripath — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
also fix #2466
