### PR TITLE
Bug fix for repo releases sorted

### LINKED ISSUE #3496: Mirrored repo releases sorted ascending order
- Gitea version (or commit ref): 2cb4649 
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/cez81/gitea-releases/releases
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
From: https://discourse.gitea.io/t/is-there-a-way-to-report-bugs-outstide-github/207

After migrating a repository to Gitea releases are sorted in ascending order. The default behavior is to sort tag create time so it seems the tags when migrating should be done in reverse.

Related to: https://github.com/go-gitea/gitea/issues/3390

## Screenshots
efbb7a32e03cfad56cad5c37e8c6c7d9747fcf6a_1_689x329

### PR DESCRIPTION
**Pull request by xwjdsh**
Fixes #3496

### CODE REVIEW

**Review by lafriks — CHANGES_REQUESTED** [review]

**Review by appleboy — APPROVED** [review]

File: routers/api/v1/repo/release.go [hunk 1]
```diff
@@ -147,6 +150,7 @@ func CreateRelease(ctx *context.APIContext, form api.CreateReleaseOption) {
 			IsPrerelease: form.IsPrerelease,
 			IsTag:        false,
 			Repo:         ctx.Repo.Repository,
+			CreatedUnix:  util.TimeStamp(time.Now().Unix()),
```
[the remark this answers is not in the document]
Comment (xwjdsh) [reply routers/api/v1/repo/release.go]: Just for this reason, so caused the issue that repo releases sorted when migrating, `xorm` save current time rather than tag created time. Test passed on local, but CI failed, could you take a look at this?

File: models/release.go [hunk 2]
```diff
@@ -134,6 +135,8 @@ func createTag(gitRepo *git.Repository, rel *Release) error {
 		if err != nil {
 			return fmt.Errorf("CommitsCount: %v", err)
 		}
+	} else {
+		rel.CreatedUnix = util.TimeStamp(time.Now().Unix())
```
Comment (appleboy) [inline models/release.go]: change to `util.TimeStampNow()`?

Comment (xwjdsh) [reply models/release.go]: Thanks, updated and the CI passed as well.

**Review by ethantkoenig — APPROVED** [review]

**Comment by ethantkoenig** [comment]
Would it be worth adding a migration (in a separate PR) to fix the `created_unix` column for existing releases?

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
@xwjdsh Can you please backport this to release/v1.4 branch?
