### PR TITLE
Fix issue suggestion bug

### LINKED ISSUE #33388: Debounced issue suggestion request makes text-expander report JS promise error
### Description

Steps:
- open new issue editor (or PR)
```
Closes #445
Closes #446
```
- then slowly press backspace until you remove `#`
Image
- see error
```
Uncaught (in promise) DOMException: Index or size is negative or greater than the allowed amount
    $l index.js:431
    getBoundingClientRect index.js:393
    positionMenu index.js:490
    activate index.js:483
    onInput index.js:575
```

### Gitea Version

1.24.0+dev-218-g7da8a01d39

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

docker

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #33388

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: web_src/js/features/comp/TextExpander.ts [hunk 1]
```diff
@@ -7,18 +7,31 @@ import {getIssueColor, getIssueIcon} from '../issue.ts';
...
+  fragment?: HTMLElement,
+}
+
+type TextExpanderChangeEvent = Event & {
+  detail?: {
+    key: string,
+    text: string,
+    provide: (result: TextExpanderProvideResult | Promise<TextExpanderProvideResult>) => void,
+  }
+}
```
Comment (silverwind) [inline web_src/js/features/comp/TextExpander.ts:21]: Side note: Should contribute those types upstream.

https://github.com/github/text-expander-element/blob/main/src/text-expander-element.ts

Maybe I will later.

File: web_src/js/features/comp/TextExpander.ts [hunk 2]
```diff
@@ -30,11 +43,37 @@ const debouncedSuggestIssues = debounce((key: string, text: string) => new Promi
...
+  const debouncedIssueSuggestions = debounce(async (key: string, text: string): Promise<TextExpanderProvideResult> => {
+    // https://github.com/github/text-expander-element/issues/71
+    // Upstream bug: when using "multiword+promise", TextExpander will get wrong "key" position.
+    // To reproduce, comment out the "shouldShowIssueSuggestions" check, use the "await sleep" below,
+    // then use content "close #20\nclose #20\close #20", keep changing the last line `#20` part from the end (including removing the `#`)
+    // There will be a JS error: Uncaught (in promise) IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 28 is larger than the node's length (27).
+    if (!shouldShowIssueSuggestions()) return {matched: false};
+    // await sleep(Math.random() * 1000); // help to reproduce the text-expander bug
+    const ret = await fetchIssueSuggestions(key, text);
+    if (!shouldShowIssueSuggestions()) return {matched: false};
```
Comment (silverwind) [inline web_src/js/features/comp/TextExpander.ts:74]: Why call `shouldShowIssueSuggestions` twice? Is it relying on side-effects of `fetchIssueSuggestions`? I'd prefer if we could make the function side-effect free, or rename it to what it actually does.

Comment (wxiaoguang) [reply web_src/js/features/comp/TextExpander.ts:74]: The first call will avoid emitting empty query in the debounced function.

The second call need to check again after the request is done.

(see the new comments)

Comment (wxiaoguang) [inline web_src/js/features/comp/TextExpander.ts]:
```suggestion
    // check the input before the request, to avoid emitting empty query to backend (still related to the upstream bug)
    if (!shouldShowIssueSuggestions()) return {matched: false};
    // await sleep(Math.random() * 1000); // help to reproduce the text-expander bug
    // check the input again to avoid text-expander use incorrect position (upstream bug)
    const ret = await fetchIssueSuggestions(key, text);
    if (!shouldShowIssueSuggestions()) return {matched: false};
```

File: web_src/js/features/comp/TextExpander.ts [hunk 3]
```diff
@@ -30,11 +43,39 @@ const debouncedSuggestIssues = debounce((key: string, text: string) => new Promi
...
+    return keyStart > lineStart;
+  };
+
+  const debouncedIssueSuggestions = debounce(async (key: string, text: string): Promise<TextExpanderProvideResult> => {
+    // https://github.com/github/text-expander-element/issues/71
+    // Upstream bug: when using "multiword+promise", TextExpander will get wrong "key" position.
+    // To reproduce, comment out the "shouldShowIssueSuggestions" check, use the "await sleep" below,
+    // then use content "close #20\nclose #20\close #20", keep changing the last line `#20` part from the end (including removing the `#`)
+    // There will be a JS error: Uncaught (in promise) IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 28 is larger than the node's length (27).
+    // check the input before the request, to avoid emitting empty query to backend (still related to the upstream bug)
```
Comment (wxiaoguang) [inline web_src/js/features/comp/TextExpander.ts]:
```suggestion
    // There will be a JS error: Uncaught (in promise) IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 28 is larger than the node's length (27).

    // check the input before the request, to avoid emitting empty query to backend (still related to the upstream bug)
```

File: web_src/js/features/comp/TextExpander.ts (hunk 2 above)
Comment (silverwind) [reply web_src/js/features/comp/TextExpander.ts:74]: Hmm ok, I hope this will be resolved upstream so we can clean up this mess.

**Review by silverwind — APPROVED** [review]

File: web_src/js/features/comp/TextExpander.ts (hunk 2 above)
Comment (wxiaoguang) [reply web_src/js/features/comp/TextExpander.ts:74]: Usually, unlikely, for example, `https://github.com/github/markdown-toolbar-element/issues/70`

File: web_src/js/features/comp/TextExpander.ts [hunk 4]
```diff
@@ -30,11 +43,40 @@ const debouncedSuggestIssues = debounce((key: string, text: string) => new Promi
...
+    // To reproduce, comment out the "shouldShowIssueSuggestions" check, use the "await sleep" below,
+    // then use content "close #20\nclose #20\close #20", keep changing the last line `#20` part from the end (including removing the `#`)
+    // There will be a JS error: Uncaught (in promise) IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 28 is larger than the node's length (27).
+
+    // check the input before the request, to avoid emitting empty query to backend (still related to the upstream bug)
+    if (!shouldShowIssueSuggestions()) return {matched: false};
+    // await sleep(Math.random() * 1000); // help to reproduce the text-expander bug
+    // check the input again to avoid text-expander use incorrect position (upstream bug)
+    const ret = await fetchIssueSuggestions(key, text);
+    if (!shouldShowIssueSuggestions()) return {matched: false};
```
Comment (wxiaoguang) [inline web_src/js/features/comp/TextExpander.ts]:
```suggestion
    const ret = await fetchIssueSuggestions(key, text);
    // check the input again to avoid text-expander use incorrect position (upstream bug)
    if (!shouldShowIssueSuggestions()) return {matched: false};
```

**Comment by wxiaoguang** [comment]
Backport:  Fix issue suggestion bug #33391

**Comment by silverwind** [comment]
FYI upstream type improvments: https://github.com/github/text-expander-element/pull/72
