### PR TITLE
Enhance GetActionWorkflow to support fallback references

### LINKED ISSUE #37169: workflow_run webhook not fired when workflow file does not exist on the default branch
## Summary

The `workflow_run` webhook event is silently dropped when a workflow is triggered (e.g. via `workflow_dispatch` API) from a branch where the workflow file exists, but the workflow file **does not exist on the repository's default branch**.

## Steps to Reproduce

1. Have a repository where the default branch (e.g. `main`) does **not** contain `.gitea/workflows/my-workflow.yml`
2. Create a feature branch that **does** contain `.gitea/workflows/my-workflow.yml`
3. Configure a repository webhook listening to the `workflow_run` event
4. Trigger the workflow via the API:
   ```
   POST /api/v1/repos/{owner}/{repo}/actions/workflows/my-workflow.yml/dispatches
   ```
5. Observe that the webhook is **never called** — neither on `requested` nor `completed`

## Expected Behavior

The `workflow_run` webhook should fire for any workflow run, regardless of whether the workflow file exists on the default branch.

## Actual Behavior

The webhook is silently dropped. The following errors appear in Gitea logs:

```
services/webhook/notifier.go:1037:(*webhookNotifier).WorkflowRunStatusUpdate() [E] GetActionWorkflow: workflow "my-workflow.yml" not found
services/actions/notifier.go:810:(*actionsNotifier).WorkflowRunStatusUpdate() [E] GetActionWorkflow: workflow "my-workflow.yml" not found
```

## Root Cause

In `services/convert/convert.go`, `GetActionWorkflow` always resolves the workflow file from the **default branch**:

```go
func GetActionWorkflow(ctx context.Context, gitrepo *git.Repository, repo *repo_model.Repository, workflowID string) (*api.ActionWorkflow, error) {
    defaultBranchCommit, err := gitrepo.GetBranchCommit(repo.DefaultBranch) // ← always default branch
    ...
    return nil, util.NewNotExistErrorf("workflow %q not found", workflowID)
}
```

This is called from `services/webhook/notifier.go` inside `WorkflowRunStatusUpdate`, which passes `run.WorkflowID` but not `run.Ref`. When the workflow file doesn't exist on the default branch, the function returns `NotExist`, causing the notifier to `return` early — swallowing the webhook event entirely.

## Suggested Fix

`GetActionWorkflow` (and its caller) should fall back to looking up the workflow file from the ref/branch of the actual run (`run.Ref`) when it is not found on the default branch. Alternatively, `WorkflowRunStatusUpdate` could pass the run's ref so the lookup can be performed against the correct commit.

## Environment

- **Gitea version:** 1.25.5
- **Triggered via:** `workflow_dispatch` API on a non-default branch

### Gitea Version

1.25.5

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/vasco-cruz/92c540681c3cf7031cd1469738266548

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

Docker

### How are you running Gitea?

**Docker compose**

```
networks:
  gitea:

services:
  gitea:
    image: gitea/gitea:${GITEA_VERSION:-1.25.5}
    container_name: gitea
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__actions__ENABLED=true
      - GITEA__webhook__ALLOWED_HOST_LIST=webhook-bridge
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_REGISTRATION_TOKEN}
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 30s


  webhook-bridge:
    image: node:${NODE_VERSION:-18}
    container_name: webhook-bridge
    working_dir: /app
    volumes:
      - ../webhook-bridge:/app
    command: >
      npm install && npm run dev
    restart: always
      - WEBHOOK_BRIDGE_PORT=${WEBHOOK_BRIDGE_PORT:-4000}
      - GITEA_TOKEN=${GITEA_TOKEN}
    networks:
      - gitea
    depends_on:
      - gitea
    ports:
      - "${WEBHOOK_BRIDGE_PORT:-4000}:${WEBHOOK_BRIDGE_PORT:-4000}"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-qO-",
          "http://localhost:${WEBHOOK_BRIDGE_PORT:-4000}/health",
        ]
      interval: 60s
      timeout: 5s
      retries: 10
      start_period: 30s

  runner1:
    image: gitea/act_runner:${ACT_RUNNER_VERSION:-0.3.1}
    container_name: gitea-runner1
    privileged: true
    networks:
      - gitea
    depends_on:
      gitea:
        condition: service_healthy
    environment:
      - GITEA_INSTANCE_URL=http://gitea:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_REGISTRATION_TOKEN}
      - GITEA_RUNNER_NAME=Runner 1
      - GITEA_RUNNER_LABELS=${GITEA_RUNNER_LABELS:-ubuntu-latest,self-hosted,linux,eds.uikit}
      - CONFIG_FILE=/data/config.yaml
    volumes:
      - ./runner-config/config.yaml:/data/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
```

### Database

SQLite

### PR DESCRIPTION
**Pull request by bircni**
If a workflow is not in default branch the hooks could not be detected

Fixes #37169

### CODE REVIEW

File: services/convert/action_test.go [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+	run("commit", "-m", "initial commit")
+
+	run("checkout", "-b", "feature")
+	wfDir := filepath.Join(tmpDir, ".gitea", "workflows")
+	err = os.MkdirAll(wfDir, 0o755)
+	require.NoError(t, err)
+	err = os.WriteFile(filepath.Join(wfDir, "my-workflow.yml"), []byte("on: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo test\n"), 0o644)
+	require.NoError(t, err)
+	run("add", ".")
+	run("commit", "-m", "add workflow")
```
Comment (wxiaoguang) [inline services/convert/action_test.go]: There is "git fast-import", can be very fast and clear.

Comment (bircni) [reply services/convert/action_test.go]: oh cool!

**Comment by wxiaoguang** [comment]
Better to ask real Actions users to review. I don't use Actions, I can only do code-level review after there are approvals.

At the moment, I know nothing about the details of "GetActionWorkflow ref".

**Comment by bircni** [comment]
@Zettat123 could you have a look?

File: services/convert/convert.go [hunk 2]
```diff
@@ -457,13 +460,13 @@ func ListActionWorkflows(ctx context.Context, gitrepo *git.Repository, repo *rep
...
-		workflows[i] = getActionWorkflowEntry(ctx, repo, defaultBranchCommit, repo.DefaultBranch, folder, entry)
+		workflows[i] = getActionWorkflowEntry(ctx, repo, defaultBranchCommit, git.RefNameFromBranch(repo.DefaultBranch), folder, entry)
 	}
 
 	return workflows, nil
 }
 
-func GetActionWorkflow(ctx context.Context, gitrepo *git.Repository, repo *repo_model.Repository, workflowID string) (*api.ActionWorkflow, error) {
+func GetActionWorkflow(ctx context.Context, gitrepo *git.Repository, repo *repo_model.Repository, workflowID string, fallbackRefs ...string) (*api.ActionWorkflow, error) {
 	defaultBranchCommit, err := gitrepo.GetBranchCommit(repo.DefaultBranch)
```
Comment (Zettat123) [inline services/convert/convert.go:470]: We currently always try to query the workflow from the default branch first. Since the workflow content can differ between the run's own branch and the default branch, I believe `GetActionWorkflow` should prioritize the specified ref when available.

Could we split the function into:

- `GetActionWorkflowByRef`: For fetching the workflow from a specific ref.
- `GetActionWorkflow`: For fetching from the default branch, acting as a wrapper around `GetActionWorkflowByRef`

**Comment by Zettat123** [comment]
I did some tests on GitHub and I believe I've found a bug of GitHub Actions. GitHub always attempts to build the workflow URL using the default branch; as a result, if the workflow doesn't exist on the default branch, `workflow.html_url` leads to a 404 page. 🤣

File: services/convert/convert.go (hunk 2 above)
Comment (bircni) [reply services/convert/convert.go:470]: fixed

**Review by Zettat123 — APPROVED** [review]

File: services/convert/convert.go [hunk 3]
```diff
@@ -469,14 +472,35 @@ func GetActionWorkflow(ctx context.Context, gitrepo *git.Repository, repo *repo_
 		return nil, err
 	}
 
-	folder, entries, err := actions.ListWorkflows(defaultBranchCommit)
+	return getActionWorkflowFromCommit(ctx, repo, defaultBranchCommit, git.RefNameFromBranch(repo.DefaultBranch), workflowID)
+}
+
+func GetActionWorkflowByRef(ctx context.Context, gitrepo *git.Repository, repo *repo_model.Repository, workflowID, ref string) (*api.ActionWorkflow, error) {
```
Comment (wxiaoguang) [inline services/convert/convert.go]: It's better to use `git.RefName` type for `ref`

**Review by wxiaoguang — APPROVED** [review]

File: services/convert/convert.go (hunk 3 above)
Comment (silverwind) [reply services/convert/convert.go]: @bircni address this please

Comment (bircni) [reply services/convert/convert.go]: on it

Comment (bircni) [reply services/convert/convert.go]: @silverwind fixed

**Comment by bircni** [comment]
@silverwind ready for merge

**Comment by silverwind** [comment]
Backport needed?

**Comment by bircni** [comment]
> Backport needed?

yep think that would be good
