### PR TITLE
Fix #9151 - smtp logger configuration sendTos should be an array

### LINKED ISSUE #9151: panic: Failed to create sublogger (smtp): json: cannot unmarshal string into Go struct field SMTPLogger.sendTos of type []string
- Gitea version (or commit ref): 1.10.0
- Operating system: ArchLinux
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When setting an smtp logger, I get this:

```
panic: Failed to create sublogger (smtp): json: cannot unmarshal string into Go struct field SMTPLogger.sendTos of type []string 
goroutine 1 [running]:
code.gitea.io/gitea/modules/log.NewLogger(0x2710, 0xc0007c13d0, 0x4, 0xc0007c13d0, 0x4, 0xc0004be600, 0xff, 0xc0007abf00)
        code.gitea.io/gitea@/modules/log/log.go:48 +0x1b3
code.gitea.io/gitea/modules/setting.newLogService()
        code.gitea.io/gitea@/modules/setting/log.go:263 +0x7a0
code.gitea.io/gitea/modules/setting.NewLogServices(0xc00182e200)
        code.gitea.io/gitea@/modules/setting/log.go:282 +0x24
code.gitea.io/gitea/modules/setting.NewServices()
        code.gitea.io/gitea@/modules/setting/setting.go:1047 +0x32
code.gitea.io/gitea/routers.NewServices()
        code.gitea.io/gitea@/routers/init.go:44 +0x24
code.gitea.io/gitea/routers.GlobalInit()
        code.gitea.io/gitea@/routers/init.go:79 +0x358
code.gitea.io/gitea/cmd.runWeb(0xc0000f0dc0, 0x0, 0x0)
        code.gitea.io/gitea@/cmd/web.go:108 +0x75
github.com/urfave/cli.HandleAction(0xdf2e200c080, 0xdf2e22a1010, 0xc0000f0dc0, 0xc0000cf300, 0x0)
        github.com/urfave/cli@v1.20.0/app.go:490 +0xca
github.com/urfave/cli.Command.Run(0xdf2df180dcf, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdf2df1afbf8, 0x16, 0x0, ...)
        github.com/urfave/cli@v1.20.0/command.go:210 +0x993
github.com/urfave/cli.(*App).Run(0xc0000b9040, 0xc0000d0000, 0x4, 0x4, 0x0, 0x0)
        github.com/urfave/cli@v1.20.0/app.go:255 +0x6ad
main.main()
        code.gitea.io/gitea@/main.go:109 +0x818
```

Under `[log.smtp]`, I’m only doing this:
```
-HOST =
+HOST = 127.0.0.1:25
-RECEIVERS =
+RECEIVERS = someuser@somedomain.com
```

### PR DESCRIPTION
**Pull request by zeripath**
The settings code for managing smtp configuration is incorrect and should generate an array of email addresses. This fixes this problem.

Fix #9151

### CODE REVIEW

File: modules/setting/log.go [hunk 1]
```diff
@@ -131,7 +131,7 @@ func generateLogConfig(sec *ini.Section, name string, defaults defaultLogOptions
 		logConfig["username"] = sec.Key("USER").MustString("example@example.com")
 		logConfig["password"] = sec.Key("PASSWD").MustString("******")
 		logConfig["host"] = sec.Key("HOST").MustString("127.0.0.1:25")
-		logConfig["sendTos"] = sec.Key("RECEIVERS").MustString("[]")
+		logConfig["sendTos"] = strings.Split(sec.Key("RECEIVERS").MustString(""), ",")
```
Comment (guillep2k) [inline modules/setting/log.go]: ~~What about a regexp? That could suport several kinds of syntaxes. What is it that we expect here? The standard full-name format for an e-mail is:
`"John Snow" <john@thewall.com>`. Entries are usually separated by `;` but `,` could also be supported.~~

Anyway, we should validate the addresses and avoid using anything that _will make the server fail_.

Validation, however is something [really tricky](https://medium.com/hackernoon/the-100-correct-way-to-validate-email-addresses-7c4818f24643).

Comment (zeripath) [reply modules/setting/log.go]: Validating email addresses is extremely non-trivial as just about the only thing you have to have is @ - possibly not even that depending on your local SMTP server config.

Even splitting potential lists of them by "," is incorrect as "," can be in there too.

In any case it can't blow up the server - SendMail will simply return an error and any error whilst logging an event just ends being printed blandly to stdout. 

See modules/log/event.go

Comment (guillep2k) [reply modules/setting/log.go]: Mmm.... not even `TrimSpace()` on each value? Anyway, this is a closed list, so admins should be responsible and use whatever Gitea supports (i.e. not e-mails with `,` in it 😄).

Comment (zeripath) [reply modules/setting/log.go]: OK, I've added the TrimSpace. If you start looking too hard we'll have to fix the:

https://github.com/go-gitea/gitea/blob/802aa6d5f306ade08438dc07d93913daecb1d3ab/modules/log/smtp.go#L84

And make it do proper quoting of email addresses - but I think that could be done in a different PR.

**Review by 6543 — APPROVED** [review]

**Review by guillep2k — APPROVED** [review]

**Comment by lunny** [comment]
Please send back port.

**Comment by 6543** [comment]
@lunny label backport done : https://github.com/go-gitea/gitea/pull/9157
