### PR TITLE
Add missing `X-Total-Count` and fix some related bugs

### LINKED ISSUE #13043: Add missing `x-total-count` header for pagination APIs
- Gitea version (or commit ref): v1.1.1
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

[User's repo list API](https://gitea.com/api/swagger#/user/userListRepos) has a `x-total-count` response header to give the total count info.

Is there any plan to add it to other pagination APIs?

- [x] https://gitea.com/api/swagger#/user/userListRepos
- [ ] https://gitea.com/api/swagger#/user/userListStarred
- [ ] https://gitea.com/api/swagger#/user/userListSubscriptions
- [ ] https://gitea.com/api/swagger#/repository/repoListStargazers
- [ ] https://gitea.com/api/swagger#/repository/repoListSubscribers

Haven't checked all APIs yet. Just find these in [GitTouch](https://github.com/git-touch/git-touch)'s development. 

Related issue: https://github.com/git-touch/git-touch/issues/106

### PR DESCRIPTION
**Pull request by qwerty287**
Adds `X-Total-Count` header to APIs that return a list but doesn't have it yet.
Fixed bugs:
* not returned after reporting error (https://github.com/qwerty287/gitea/blob/39eb82446c6fe5da3d79124e1f701f3795625b69/routers/api/v1/user/star.go#L70)
* crash with index out of bounds, API issue/issueSubscriptions

I also found various endpoints that return lists but do not apply/support pagination yet:
```
/repos/{owner}/{repo}/issues/{index}/labels
/repos/{owner}/{repo}/issues/comments/{id}/reactions
/repos/{owner}/{repo}/branch_protections
/repos/{owner}/{repo}/contents
/repos/{owner}/{repo}/hooks/git
/repos/{owner}/{repo}/issue_templates
/repos/{owner}/{repo}/releases/{id}/assets
/repos/{owner}/{repo}/reviewers
/repos/{owner}/{repo}/teams
/user/emails
/users/{username}/heatmap
```
If this is not expected, an new issue should be opened.

Closes #13043

### CODE REVIEW

**Review by zeripath — APPROVED** [review]

File: models/commit_status.go [hunk 1]
```diff
@@ -255,6 +255,19 @@ func getLatestCommitStatus(e db.Engine, repoID int64, sha string, listOptions db
...
+func CountLatestCommitStatus(repoID int64, sha string) (int64, error) {
+	return countLatestCommitStatus(db.GetEngine(db.DefaultContext), repoID, sha)
+}
+
+func countLatestCommitStatus(e db.Engine, repoID int64, sha string) (int64, error) {
+	return e.Table(&CommitStatus{}).
+		Where("repo_id = ?", repoID).And("sha = ?", sha).
+		Select("max( id ) as id").
+		GroupBy("context_hash").OrderBy("max( id ) desc").
+		Count(new(CommitStatus))
```
Comment (KN4CK3R) [inline models/commit_status.go]: This query looks strange. This should do the same but is simpler:
```go
e.Where("repo_id = ?", repoID).And("sha = ?", sha).
		GroupBy("context_hash").
		Count(new(CommitStatus))
```

File: models/issue_reaction.go [hunk 2]
```diff
@@ -103,6 +103,29 @@ func findReactions(e db.Engine, opts FindReactionsOptions) ([]*Reaction, error)
...
+	return countReactions(db.GetEngine(db.DefaultContext), FindReactionsOptions{
+		IssueID:   issue.ID,
+		CommentID: -1,
+	})
+}
+
+func countReactions(e db.Engine, opts FindReactionsOptions) (int64, error) {
+	return e.Where(opts.toConds()).
+		In("reaction.`type`", setting.UI.Reactions).
+		Asc("reaction.issue_id", "reaction.comment_id", "reaction.created_unix", "reaction.id").
```
Comment (KN4CK3R) [inline models/issue_reaction.go]: Sorting does not change the count of the result and should be removed.

File: routers/api/v1/repo/issue_subscription.go [hunk 3]
```diff
@@ -278,10 +278,17 @@ func GetIssueSubscribers(ctx *context.APIContext) {
 		ctx.Error(http.StatusInternalServerError, "GetUsersByIDs", err)
 		return
 	}
-	apiUsers := make([]*api.User, 0, len(users))
-	for i := range users {
-		apiUsers[i] = convert.ToUser(users[i], ctx.User)
+	var apiUsers []*api.User
+	for _, v := range users {
+		apiUsers = append(apiUsers, convert.ToUser(v, ctx.User))
```
Comment (KN4CK3R) [inline routers/api/v1/repo/issue_subscription.go]:
```suggestion
	apiUsers := make([]*api.User, 0, len(users))
	for _, v := range users {
		apiUsers = append(apiUsers, convert.ToUser(v, ctx.User))
```

Comment (KN4CK3R) [reply routers/api/v1/repo/issue_subscription.go]: How could the old code work? It should have crashed on the first write.

**Comment by KN4CK3R** [comment]
Have a look at the method `FindAndCount`. Maybe you don't need the new methods but just switch to `FindAndCount` in the existing methods.

File: routers/api/v1/repo/issue_subscription.go (hunk 3 above)
Comment (lunny) [reply routers/api/v1/repo/issue_subscription.go]: Golang allow that after some version.

File: models/commit_status.go (hunk 1 above)
Comment (wxiaoguang) [reply models/commit_status.go]: ~~Also, `Select("max( id ) as id")` could be replaced by `Select("context_hash")` (for meaning and performance) since we are grouping by `context_hash`~~

Oh, ignore me, in XORM `Count` should work without `Select`

**Comment by qwerty287** [comment]
@KN4CK3R rewrote it using `FindAndCount` in https://github.com/go-gitea/gitea/pull/17968/commits/1a39491a88a9738f06e5308224ce38a594e95712

**Review by KN4CK3R — APPROVED** [review]

**Comment by lunny** [comment]
make L-G-T-M work.
