### PR TITLE
Redirect to the only OAuth2 provider when no other login methods and fix various problems

### LINKED ISSUE #36846: If there is just 1 login provider configured, redirect to it
### Feature Description

If you have exactly 1 login provider enabled, the login page doesnt make much sense and only presents unnecessary step for user. See here:

Image

What user can do here is just click on the single button. When there is just one login provider configured, instead of displaying this page, please redirect right to the provider (as if user clicked the button).

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by navneet102**
Fixes: #36846 

1. When there is only on OAuth2 login method, automatically direct to it
2. Fix legacy problems in code, including:
   * Rename template filename and fix TODO comments
   * Fix legacy variable names
   * Add missing SSPI variable for template
   * Fix unnecessary layout, remove garbage styles
   * Only do AppUrl(ROOT_URL) check when it is needed (avoid unnecessary warnings to end users)

### CODE REVIEW

**Comment by wxiaoguang** [comment]
> * Added skipAutoLogin URL param to bypass this feature by including `?skipAutoLogin=true`

What will it be used for? Who will use it? Any real world use case for it?

If it is not used by our code, not clearly documented for real world use cases, then it doesn't make sense.


-----


Update: added screenshots for the UI changes:

image

**Comment by navneet102** [comment]
I included it because it was mentioned in this [comment](https://github.com/go-gitea/gitea/issues/36846#issuecomment-4011380450), it could be used if auth source is unavailable. 

What do you suggest, should I?
1. Document it.
2. Remove it.

**Comment by navneet102** [comment]
@wxiaoguang I have added some tests. Could you check this now please?

**Comment by wxiaoguang** [comment]
> > > * Added skipAutoLogin URL param to bypass this feature by including `?skipAutoLogin=true`
> >
> > What will it be used for? Who will use it? Any real world use case for it?
> >
> > If it is not used by our code, not clearly documented for real world use cases, then it doesn't make sense.
>
> I included it because it was mentioned in this [comment](https://github.com/go-gitea/gitea/issues/36846#issuecomment-4011380450), it could be used if auth source is unavailable.
> 
> What do you suggest, should I?
> 
>     1. Document it.
> 
>     2. Remove it.

I don't understand it

**Comment by navneet102** [comment]
Sorry for being vague.


> > * Added skipAutoLogin URL param to bypass this feature by including `?skipAutoLogin=true`
> 
> What will it be used for? Who will use it? Any real world use case for it?
> 
> If it is not used by our code, not clearly documented for real world use cases, then it doesn't make sense.


I think you asked here about why I included the `skipAutoLogin` URL parameter if there was no documentation for it.

In the reply, I mentioned that it was a design choice specified by @silverwind while accepting the feature proposal in this issue's (#36846 ) discussion.


> What do you suggest, should I?
> 
> 1. Document it.
> 2. Remove it.

Here I asked you, if I should remove the `skipAutoLogin` URL param or should I add documentation for it.

**Comment by wxiaoguang** [comment]
> > What do you suggest, should I?
> > 
> > 1. Document it.
> > 2. Remove it.
> 
> Here I asked you, if I should remove the `skipAutoLogin` URL param or should I add documentation for it.

As I said, I don't understand it.

You are the author so you need to propose reasonable and feasible designs.

**Comment by wxiaoguang** [comment]
You can explain your design by answering the questions:

1. For "Document it": why it is useful, in which case it will be used, how end users can know how to use it.
    * "useful when the auth source is temporarily unavailable": you already have `!EnablePasswordSignInForm` check, so users can do nothing on the login page even if the auth source is unavailable
    * I don't think such reason makes sense.
3. For "Remove it": why the extra parameter is useless, why the suggestion from silverwind (https://github.com/go-gitea/gitea/issues/36846#issuecomment-4011380450) is not right.

File: routers/web/auth/auth_test.go [hunk 1]
```diff
@@ -134,4 +135,22 @@ func TestWebAuthOAuth2(t *testing.T) {
...
+		ctx, resp := contexttest.MockContext(t, "/user/login?redirect_to=/other")
+		SignIn(ctx)
+		assert.Equal(t, http.StatusSeeOther, resp.Code)
+		expectedURL := "/user/oauth2/dummy-auth-source?redirect_to=" + url.QueryEscape("/other")
+		assert.Equal(t, expectedURL, test.RedirectURL(resp))
+
+		ctx, resp = contexttest.MockContext(t, "/user/login?redirect_to=/other&skipAutoLogin=true")
+		SignIn(ctx)
+		assert.Equal(t, http.StatusOK, resp.Code)
+	})
```
[the remark this answers is not in the document]
Comment (navneet102) [reply routers/web/auth/auth_test.go]: Cannot reuse OAuth2 source created at the start as this test requires only 1 OAuth2 source to be present. Made it a separate test function.

**Comment by silverwind** [comment]
I have to correct my request: `skipAutoLogin` only makes sense if there is more than 1 login option. If there is only 1 auto-login-able action (like only sso button), its not needed. As I understand the PR handles only the case of 1 SSO option, so we don't need it for this use case.

**Comment by navneet102** [comment]
Thank you everyone for the review, and sorry for the late reply. I have removed the `skipAutoLogin` param. Currently there is no solution for situations when OAuth service is unavailable because after being redirected (to OAuth provider) we cannot do anything until `SignInOAuthCallback` is called. The only solution would be to check for the availability of the service before redirection, which would be slow.

File: routers/web/auth/auth.go [hunk 2]
```diff
@@ -242,6 +255,19 @@ func SignIn(ctx *context.Context) {
...
 	}
 	prepareSignInPageData(ctx)
+
+	enableSSPI, _ := ctx.Data["EnableSSPI"].(bool)
+
+	// If only 1 OAuth provider is present and other login methods are disabled, redirect to the OAuth provider.
+	if !setting.Service.EnablePasswordSignInForm &&
+		!setting.Service.EnableOpenIDSignIn &&
+		!setting.Service.EnablePasskeyAuth &&
+		!enableSSPI {
```
Comment (wxiaoguang) [inline routers/web/auth/auth.go]: `EnableSSPI` and `OAuth2Providers` should be the return values of `prepareSignInPageData`, it's fragile by reading them from dynamic template data

**Comment by silverwind** [comment]
1. `performAutoLoginOAuth2` reads `OAuth2Providers` from `ctx.Data` which creates a fragile implicit dependency on `prepareSignInPageData` having been called first. As [wxiaoguang noted](https://github.com/go-gitea/gitea/pull/36901#discussion_r3015409124), these should be return values of `prepareSignInPageData` instead.

2. The test only covers the happy path (single provider + `redirect_to`). Consider adding cases for:
    1. 0 OAuth providers → should render login page
    2. 2+ OAuth providers → should render login page
    3. No `redirect_to` query param → should redirect without query string
    4. Any of `EnablePasswordSignInForm`/`EnableOpenIDSignIn`/`EnablePasskeyAuth`/SSPI enabled → should render login page, not redirect

---
*This comment was written by Claude Opus 4.6.*

File: routers/web/auth/auth.go (hunk 2 above)
Comment (navneet102) [reply routers/web/auth/auth.go]: Would it be better to do direct db calls for those? Because returning `EnableSSPI` and `OAuth2Providers` from `prepareSignInPageData` would add unrelated functionality to it?

Comment (wxiaoguang) [reply routers/web/auth/auth.go]: I will do it

**Review by wxiaoguang — APPROVED** [review]

File: routers/web/auth/auth_test.go [hunk 3]
```diff
@@ -96,6 +96,37 @@ func TestWebAuthOAuth2(t *testing.T) {
 		assert.Contains(t, ctx.Flash.ErrorMsg, "auth.oauth.signin.error.general")
 	})
 
+	t.Run("RedirectSingleProvider", func(t *testing.T) {
```
Comment (navneet102) [inline routers/web/auth/auth_test.go:99]: This test fails depending on it's position, i.e. it will fail, if run after `OIDCLogout` test (or any other test which adds additional OAuth provider, making it != 1). We could use `unittest.PrepareTestEnv` and reinitialize the providers so that there is only 1 provider when this runs, irrespective of other tests.
```suggestion
	t.Run("RedirectSingleProvider", func(t *testing.T) {
	    unittest.PrepareTestEnv(t)
	    _ = oauth2.Init(t.Context())
	    addOAuth2Source(t, "dummy-auth-source", oauth2.Source{})
```

Comment (wxiaoguang) [reply routers/web/auth/auth_test.go:99]: No, it won't fail. Intentionally, it won't and shouldn't run after OIDCLogout test

**Comment by silverwind** [comment]
Would still add those test cases mentioned in https://github.com/go-gitea/gitea/pull/36901#issuecomment-4162218910. If you like I can exercise AI on it, or you do it yourself.

**Comment by wxiaoguang** [comment]
> Would still add those test cases mentioned in [#36901 (comment)](https://github.com/go-gitea/gitea/pull/36901#issuecomment-4162218910). If you like I can exercise AI on it, or you do it yourself.

Have you read the new code by yourself?


image

**Comment by silverwind** [comment]
Ok, but a test with 2 providers is still missing it seems?

**Comment by wxiaoguang** [comment]
> Ok, but a test with 2 providers is still missing it seems?

image

**Review by silverwind — APPROVED** [review]
