### PR TITLE
Fix push message behavior

### LINKED ISSUE #32769: New pull request notification will show wrong branch in a special case
### Description

Sorry, this is a bug come from my PR #25812

Reproduce:
1. create a new repo A, create a file in it
2. fork it to repo B
3. push a commit (the most easy way is creating a new file in web) in repo A's main branch

Then you will see:
In repo A, the branch in notification is repo B's main branch, actually the expected branch is repo A's main branch.
image
In the fork (repo B), it show the repo A's main branch, actually the expected behavior is showing nothing.
image

Reason:
For newly created empty branch (based on default branch), I want to ignore the notification, so I added this in the SQL query.
image
And this cause this bug.

In repo A, it will ignore the newly pushed commit because of the condition I mentioned above, and the default branch's latest commit id is changed. So in repo B's main branch, the latest commit id is not same to the repo A's default branch's latest commit id, so it will be picked up as a recently updated branch.

Don't have a good idea about how to fix it now. If someone is interested, it is welcome to create a PR for it.

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

build

### Database

None

### PR DESCRIPTION
**Pull request by changchaishi**
Fixes #32769 by the logic from pr #33192

### CODE REVIEW

**Comment by changchaishi** [comment]
Extract/create a common function called `GetBranchDivergingInfo`, it can serve two main targets:

* Sync Fork feature (Merge Upstream)
* Recently Push Branch (Pull Request message)

 | GetBranchDivergenceInfo     | Base Branch                                   | Head Branch          |
|-----------------------------|-----------------------------------------------|----------------------|
| Sync Fork (Merge Up stream) | base's defaultBranch                          | fork repo's branch   |
| Recently Push Branch PR     | fork repo's branch / base's non-defaultBranch | base's defaultBranch |

This combination allows us to determine the divergence between the two branches interchangeably.

For the correct behavior for a recently pushed branch, the branch must be ahead of default by some commits.

File: services/repository/branch.go [hunk 1]
```diff
@@ -642,3 +643,61 @@ func SetRepoDefaultBranch(ctx context.Context, repo *repo_model.Repository, gitR
 
 	return nil
 }
+
+type BranchDivergingInfo struct {
+	BaseIsNewer   bool
```
Comment (wxiaoguang) [inline services/repository/branch.go]: I think the old name `BaseHasNewCommits` is better. Because the "base" might not be really "newer"

File: routers/web/repo/view_home.go [hunk 2]
```diff
@@ -215,10 +215,23 @@ func prepareRecentlyPushedNewBranches(ctx *context.Context) {
...
 			opts.BaseRepo.UnitEnabled(ctx, unit_model.TypePullRequests) &&
 			baseRepoPerm.CanRead(unit_model.TypePullRequests) {
-			ctx.Data["RecentlyPushedNewBranches"], err = git_model.FindRecentlyPushedNewBranches(ctx, ctx.Doer, opts)
+			var finalBranches []*git_model.RecentlyPushedNewBranch
+			branches, err := git_model.FindRecentlyPushedNewBranches(ctx, ctx.Doer, opts)
 			if err != nil {
 				log.Error("FindRecentlyPushedNewBranches failed: %v", err)
 			}
+
+			for _, branch := range branches {
```
Comment (wxiaoguang) [inline routers/web/repo/view_home.go:224]: Maybe we should only check at most 2 or 3 branches. Otherwise would there be a performance problem?

Comment (changchaishi) [reply routers/web/repo/view_home.go:224]: The return branches from `FindRecentlyPushedNewBranches` are already limited by the `opts.MaxCount` variable (default to 2), so I did not limit it further.

**Review by wxiaoguang — APPROVED** [review]

File: routers/web/repo/view_home.go [hunk 3]
```diff
@@ -215,10 +215,23 @@ func prepareRecentlyPushedNewBranches(ctx *context.Context) {
...
+				divergingInfo, err := repo_service.GetBranchDivergingInfo(ctx, branch.BranchRepo, opts.BaseRepo, branch.BranchName, opts.BaseRepo.DefaultBranch)
+				if err != nil {
+					continue
```
Comment (lunny) [inline routers/web/repo/view_home.go:231]: Maybe we could log the error here.

File: services/repository/branch.go [hunk 4]
```diff
@@ -642,3 +643,61 @@ func SetRepoDefaultBranch(ctx context.Context, repo *repo_model.Repository, gitR
...
+		// if the base's update time is before the fork, check whether the base's head is in the fork
+		baseGitRepo, err := gitrepo.RepositoryFromRequestContextOrOpen(ctx, baseRepo)
+		if err != nil {
+			return nil, err
+		}
+		headGitRepo, err := gitrepo.RepositoryFromRequestContextOrOpen(ctx, headRepo)
+		if err != nil {
+			return nil, err
+		}
+		baseCommitID, err := baseGitRepo.ConvertToGitID(baseGitBranch.CommitID)
```
Comment (lunny) [inline services/repository/branch.go]: I don't think we need to convert because `baseGitBranch.CommitID` is already a real commit id.

File: services/repository/branch.go [hunk 5]
```diff
@@ -642,3 +643,61 @@ func SetRepoDefaultBranch(ctx context.Context, repo *repo_model.Repository, gitR
...
+		if err != nil {
+			return nil, err
+		}
+		headCommit, err := headGitRepo.GetCommit(headGitBranch.CommitID)
+		if err != nil {
+			return nil, err
+		}
```
Comment (wxiaoguang) [inline services/repository/branch.go]:
```suggestion
```

File: routers/web/repo/view_home.go (hunk 3 above)
Comment (wxiaoguang) [reply routers/web/repo/view_home.go:231]: Added in the new commit.

We really need some helper functions like `MsutXxx` in the future to avoid writing a lot of `if { log.Error }`

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
1.23 lacks "reqctx" support, manually backported:  Fix push message behavior (#33215) #33317
