### PR TITLE
Remove commit status running and warning to align GitHub

### LINKED ISSUE #25776: Incorrect aggregated status of commit statuses
### Description

The commit as part of PR is marked with green check, when some workflows is still running.

### Gitea Version

v1.19.4

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

official docker image

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by CaiCandong**
Fix #25776. Close #25826.

In the discussion of #25776, @wolfogre's suggestion was to remove the commit status of `running` and `warning` to keep it consistent with github.

references:
- https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#about-commit-statuses

## :warning: BREAKING :warning:

So the commit status of Gitea will be consistent with GitHub, only `pending`, `success`, `error` and `failure`, while `warning` and `running` are not supported anymore.

### CODE REVIEW

File: services/actions/commit_status.go [hunk 1]
```diff
@@ -137,16 +137,12 @@ func toCommitStatus(status actions_model.Status) api.CommitStatusState {
...
-	case actions_model.StatusCancelled:
-		return api.CommitStatusWarning
-	case actions_model.StatusWaiting, actions_model.StatusBlocked:
+	case actions_model.StatusWaiting, actions_model.StatusBlocked, actions_model.StatusRunning:
 		return api.CommitStatusPending
-	case actions_model.StatusRunning:
-		return api.CommitStatusRunning
 	default:
-		return api.CommitStatusError
+		return api.CommitStatusFailure
```
Comment (wolfogre) [inline services/actions/commit_status.go]: I don't think so, it could happen only if `status` is an unknown typo, so convert it to `error` instead of `failure` to distinguish with `Failure` or `Cancelled`.

File: services/convert/status.go [hunk 2]
```diff
@@ -52,6 +52,10 @@ func ToCombinedStatus(ctx context.Context, statuses []*git_model.CommitStatus, r
 			retStatus.State = status.State
 		}
 	}
+	// to align with GitHub, failure if any of the contexts report as error or failure
```
Comment (wolfogre) [inline services/convert/status.go]:
```suggestion
	// According to https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#get-the-combined-status-for-a-specific-reference
	// > Additionally, a combined state is returned. The state is one of:
	// > failure if any of the contexts report as error or failure
	// > pending if there are no statuses or a context is pending
	// > success if the latest status for all contexts is success
```

**Review by wolfogre — COMMENTED** [review]
Please check also `templates/repo/commit_status.tmpl`

File: services/actions/commit_status.go (hunk 1 above)
Comment (CaiCandong) [reply services/actions/commit_status.go]: Yes, you are right.

File: models/git/commit_status.go [hunk 3]
```diff
@@ -218,6 +218,18 @@ type CommitStatusOptions struct {
 	SortType string
 }
 
+// compatibleCommitStatus compatible with old version status
+// and convert old version status to new version status
```
Comment (wolfogre) [inline models/git/commit_status.go]:
```suggestion
// Deprecated: it will be removed after v1.22.0
// compatibleCommitStatus compatible with old version status
// and convert old version status to new version status
```

**Comment by delvh** [comment]
Hmm… I'm conflicted about that decision.
Sure, it would be compatible with GitHub.
On the other hand, it would also remove functionality that GitHub is basically lacking at the moment.
(At least `running`, I haven't quite understood yet either when `warning` would be triggered)

**Comment by wolfogre** [comment]
> Hmm… I'm conflicted about that decision. Sure, it would be compatible with GitHub. On the other hand, it would also remove functionality that GitHub is basically lacking at the moment. (At least `running`, I haven't quite understood yet either when `warning` would be triggered)

I don't think people care about whether a commit status is `running` or `pending`.

Yeah, for Gitea Actions, `pending` could be `Blocked` or `Waiting`, but the commit status is not designed for Actions. For most applications, I believe it's enough to just say "it's pending".

**Comment by wolfogre** [comment]
Since it's my original idea, I won't approve it until it has been approved by the other two maintainers.

If most people are against this one and want more functionality than GitHub, maybe #25826 is a good choice.

Please feel free to approve or request changes this one or #25826

**Comment by silverwind** [comment]
From my experience GitHub UI definitely has `pending` and `warning` states, even if the API does not expose it:

- `pending`: Yellow dot, not yet started because no worker has picked it up or other dependencies not satisfied
- `warning`: Orange exclamation triangle. Happens when PRs need approval to run, like it happens on every push on https://github.com/go-gitea/gitea/pull/25396

I guess it makes some sense to be API-compatible with GitHub, but internally I guess we would still need them for above two reasons.

**Comment by CaiCandong** [comment]
> From my experience GitHub UI definitely has `pending` and `warning` states, even if the API does not expose it:

According to the github documentation:[create-a-commit-status](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status ), creating a status only accepts `error`, `failure`, `pending`, `success`. My opinion is that our status definition should be consistent with github, but the specific semantic information we can express in `description`.

**Comment by silverwind** [comment]
You're right we have to distinguish:

- [Commit status](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status) can only be error, failure, pending, success.
- [Workflow run status](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28) can be one of completed, action_required, cancelled, failure, neutral, skipped, stale, success, timed_out, in_progress, queued, requested, waiting, pending.

So I'm fine with reducing the commit status to those GitHub-compatible values.

**Comment by silverwind** [comment]
Can we ensure that for our actions workflow runs, the statuses there are correctly mapped down to those 4 values?

**Comment by wolfogre** [comment]
> Can we ensure that for our actions workflow runs, the statuses there are correctly mapped down to those 4 values?

I'm sure, but we should be aware that it could lose some detail, you know, it's “mapping down”.

**Comment by lunny** [comment]
Even if we don't reduce those two statuses, Gitea is also compatible with Github. Why these two statuses are unnecessary?

**Comment by wolfogre** [comment]
So `pending` and `running` are exactly the same now, see https://github.com/go-gitea/gitea/pull/25935#issuecomment-1643154767

**Comment by silverwind** [comment]
So I think this PR almost looks good, but I would remove this `compatibleCommitStatus` and instead add a migration to rewrite the old statuses in the DB.

**Comment by wolfogre** [comment]
> So I think this PR almost looks good, but I would remove this `compatibleCommitStatus` and instead add a migration to rewrite the old statuses in the DB.

Done 66697172c25bdc4b9d24e11c27f080d58a8c8ff9

**Review by silverwind — APPROVED** [review]

**Review by puni9869 — APPROVED** [review]

**Comment by silverwind** [comment]
There might be some remaining unused conditionals in UI now for the icon, need to check.

**Comment by jpraet** [comment]
Noticed this PR in the 1.21-rc0 changelog. I think commit status "warning" was useful for checks where you want to draw the attention of the developer, but not block the merge of the PR. e.g. sonar static code analysis has severities, and we want to block the merge for newly introduced [Blocker, Critical, Major] violations, and give a warning for [Minor] violations.
Or for example block the merge on code coverage < 50%, but give a warning on code coverage < 70%.

image

And [jenkinsci/gitea-plugin](https://github.com/jenkinsci/gitea-plugin) will also break because it uses warning to report unstable build (test failures):

image

**Comment by jpraet** [comment]
Besides jenkins, also other CI integrations use warning commit status like:
* https://github.com/woodpecker-ci/woodpecker/blob/4e1db732e9214d99f661fc8dabd593ebf447f3be/server/forge/gitea/gitea.go#L594
* https://github.com/metroline/metroline/blob/33a66b8f5f5d6f749064ebe1483deec8c47593ce/src/server/git-servers/gitea/gitea.ts#L126
* https://github.com/theSage21/jaypore_ci/blob/df1e5f62c0e2e407d43dbe87939ce846b2417e02/jaypore_ci/jci.py#L180
* ...?

**Comment by silverwind** [comment]
I guess these have to migrate to `error` now. Overall I think we're better off being compatible with GitHub, so that integrations that work against GitHub can seamlessly be ported.

**Comment by silverwind** [comment]
On second thought, `warning` does seem like a valid use case. I wonder how GitHub did avoid adding it so far. They do have inline annotations with Gitea does not have, and I think those can be both warnings and errors.

**Comment by silverwind** [comment]
I checked another data point, GitLab. Here is a table illustrating the commit statuses of each:

|                   | pending | running | cancelled | warning | failed  | success | error |
|-------------------|---------|---------|-----------|---------|---------|---------|-------|
| github and gitlab | pending | -       | -         | -       | failure | success | error |
| gitlab            | pending | running | cancelled | -       | failed  | success | error |
| gitea before      | pending | running | -         | warning | failure | success | error |

**Comment by silverwind** [comment]
I guess I agree to restoring `warning`, but do we need `running`?

**Comment by jpraet** [comment]
`running` was only introduced quite recently (in v1.19) https://github.com/go-gitea/gitea/pull/21937, so less risk of breaking any existing integrations

**Comment by silverwind** [comment]
So, partial revert of this that edits the migration as well? Of course the damage is already done for anyone using prereleases.

**Comment by harryzcy** [comment]
Do we actually want to revert this? If we do, it's better to do this earlier so the damage is minimal

**Comment by silverwind** [comment]
Yes, someone please raise a PR with the revert. We also need to disable [this part of the migration](https://github.com/go-gitea/gitea/pull/25839/files#diff-8fbceb4ab6d584ee83b11cfdc911a10bc3445c92ea130db9ecdd17b4f460d763R21).

If no one raises the revert, I can probably do it in a few days.

**Comment by delvh** [comment]
I think there is already an existing revert PR.
I simply don't know which exactly anymore.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/27504 for the partial revert.
