### PR TITLE
Do not overwrite the log mode when installing (#25203)

### LINKED ISSUE #24861: Log mode changed to console after installation
### Description

Docker image: gitea/gitea:1.19.3
Platform: x64
OS: Ubuntu 22.04.3 Server (Minimized)

Problem: the value of log__MODE changed to `console` after the initialization step.

Steps to reproduce:
1. Install the OS, docker and docker-compose
2. Draft an `docker-compose.yml` file with the following `log` related section:
```yml
      # [log]
      - GITEA__log__MODE=file
      - GITEA__log__LEVEL=Info
      - GITEA__log__ROUTER=file
      - GITEA__log__ROOT_PATH=/data/gitea/log/
      - GITEA__log__ENABLE_XORM_LOG=true #
      - GITEA__log__MAX_SIZE_SHIFT=28    # 单个日志文件最大大小，当为28时：2^28/1024^2=> 258(MB)
      - GITEA__log__FILE_NAME=gitea.log  # 即日志的路径为`/data/gitea/log/gitea.log`
      - GITEA__log__XORM=file

      # [log.file]
      - GITEA__log.file__MAX_DAYS=180 # 多少天后删除日志文件
      - GITEA__log.file__COMPRESSION_LEVEL=1 # 日志文件的压缩等级

      # [log.file.router]
      - GITEA__log.file.router__FILE_NAME=router.log

      # [log.file.xorm]
      - GITEA__log.file.xorm__FILE_NAME=xorm.log
```
3. type `docker-compose -f docker-compose.yml up -d` to start the container and open its site for initialization.
4. after filling the `Administrator Account Settings` section, using `cat <container_root>/data/gitea/conf/app.ini` to check `log` related settings, it reads:
```yml
[log]
MODE            = file
LEVEL           = Info
ROUTER          = file
ROOT_PATH       = /data/gitea/log/
ENABLE_XORM_LOG = true
MAX_SIZE_SHIFT  = 28
FILE_NAME       = gitea.log
XORM            = file
```
5. hit the `Install Gitea` button, the site would redirect to a user page, then re-check the content, it reads:
```yml
[log]
MODE            = console
LEVEL           = info
ROUTER          = console
ROOT_PATH       = /data/gitea/log/
ENABLE_XORM_LOG = true
MAX_SIZE_SHIFT  = 28
FILE_NAME       = gitea.log
XORM            = file
```

The value of `MODE` changed to `console` incorrectly.
To a personal unstandering, given in the `docker-compose.yml` it's `file` and all required values related  have given, it should remind to be `file` after the initialization.

What have I missed ?

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Using Docker images.
The full content of the `docker-compose.yml`:
```yml
version: "3"

networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local

services:
  server:
    image: gitea/gitea:1.19.3
    container_name: lovegitea.gitea
    environment:
      - APP_NAME=Gitea@lovegitea
      - RUN_MODE=prod
      - USER_UID=3001
      - USER_GID=3000
      - USER=gitea_admin

      # [database]:https://docs.gitea.io/en-us/config-cheat-sheet/#database-database
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__DB_PATH="/data/gitea/gitea.db"

      # [repository]
      - GITEA__repository__DEFAULT_PRIVATE=private

      # [Server]:https://docs.gitea.io/en-us/config-cheat-sheet/#server-server
      - GITEA__server__DOMAIN=localhost
      # Git Clone over HTTP 相关
      - GITEA__server__HTTP_ADDR=
      - GITEA__server__HTTP_PORT=3000
      # - GITEA__server__ROOT_URL=

      # Git Clone over SSH
      - GITEA__server__DISABLE_SSH=false
      # - GITEA__server__SSH_DOMAIN=
      - GITEA__server__SSH_PORT=10022
      - GITEA__server__SSH_LISTEN_PORT=22
      - GITEA__server__OFFLINE_MODE=false
      - GITEA__server__LANDING_PAGE=login

      # [Service]
      - GITEA__service__DEFAULT_USER_IS_RESTRICTED=true
      - GITEA__service__OFFLINE_MODE=true
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__REQUIRE_SIGNIN_VIEW=true
      - GITEA__service__REGISTER_EMAIL_CONFIRM=true
      - GITEA__service__ENABLE_NOTIFY_MAIL=true
      - GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION=false
      - GITEA__service__ENABLE_CAPTCHA=false
      - GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE=false
      - GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION=true
      - GITEA__service__DEFAULT_ENABLE_TIMETRACKING=true
      - GITEA__service__NO_REPLY_ADDRESS=noreply.gitea.lovegitea.io
      - GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE=true
      - GITEA__service__DEFAULT_ORG_VISIBILITY=private

      # [Admin]
      - GITEA__admin__DEFAULT_EMAIL_NOTIFICATIONS=enabled
      - GITEA__admin__DISABLE_REGULAR_ORG_CREATION=false

      # [Security]
      - GITEA__security__LOGIN_REMEMBER_DAYS=1
      - GITEA__security__PASSWORD_HASH_ALGO=pbkdf2

      # [OpenID]
      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
      - GITEA__openid__ENABLE_OPENID_SIGNUP=false

      # [Picture]
      - GITEA__picture__DISABLE_GRAVATAR=true
      - GITEA__picture__ENABLE_FEDERATED_AVATAR=false

      # [Git.Timeout]
      - GITEA__git.timeout__DEFAUlT=3600 # Git operations default timeout seconds.
      - GITEA__git.timeout__MIGRATE=3600 # Migrate external repositories timeout seconds.
      - GITEA__git.timeout__MIRROR=3600  # Mirror external repositories timeout seconds.
      - GITEA__git.timeout__CLONE=3600   # Git clone from internal repositories timeout seconds.
      - GITEA__git.timeout__PULL=3600    # Git pull from internal repositories timeout seconds.
      - GITEA__git.timeout__GC=3600      # Git repository GC timeout seconds.

      # [Other]
      - GITEA__other__SHOW_FOOTER_VERSION=false # Whether to show Gitea version on the site
      - GITEA__other__ENABLE_FEED=false         

      # [log]
      - GITEA__log__MODE=file
      - GITEA__log__LEVEL=Info
      - GITEA__log__ROUTER=file
      - GITEA__log__ROOT_PATH=/data/gitea/log/
      - GITEA__log__ENABLE_XORM_LOG=true #
      - GITEA__log__MAX_SIZE_SHIFT=28    # 2^28/1024^2 => 258(MB)
      - GITEA__log__FILE_NAME=gitea.log  # `/data/gitea/log/gitea.log`
      - GITEA__log__XORM=file

      # [log.file]
      - GITEA__log.FILE_NAME=/data/gitea/log/gitea.log
      - GITEA__log.file__MAX_DAYS=180 #
      - GITEA__log.COMPRESS=true
      - GITEA__log.file__COMPRESSION_LEVEL=1 #

      # [log.file.router]
      - GITEA__log.file.router__FILE_NAME=router.log

      # [log.file.xorm]
      - GITEA__log.file.xorm__FILE_NAME=xorm.log

    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - /docker-data/containers/lovegitea.gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "10080:3000"
      - "10022:22" # activate this line to enable SSH Clone
```

### Database

SQLite

### PR DESCRIPTION
**Pull request by GiteaBot**
Backport #25203 by @wxiaoguang

Fix #24861

### CODE REVIEW

**Review by lunny — APPROVED** [review]

**Review by delvh — APPROVED** [review]

File: routers/install/install.go [hunk 1]
```diff
@@ -453,10 +453,9 @@ func SubmitInstall(ctx *context.Context) {
 
 	cfg.Section("session").Key("PROVIDER").SetValue("file")
 
-	cfg.Section("log").Key("MODE").SetValue("console")
+	cfg.Section("log").Key("MODE").MustString("console")
 	cfg.Section("log").Key("LEVEL").SetValue(setting.Log.Level.String())
 	cfg.Section("log").Key("ROOT_PATH").SetValue(form.LogRootPath)
```
Comment (delvh) [inline routers/install/install.go:458]: By the way, shouldn't all these other keys be `MustString` either?
It seems a bit strange that only the log isn't overwritten?`

Comment (wxiaoguang) [reply routers/install/install.go:458]: Nope.

`setting.Log.Level` is from the config, so no overwritten

`form.LogRootPath` is from user input (by default is also from the config)
* if user ever changed it, then it must overwrite
* if user didn't change it, still no overwritten

Comment (delvh) [reply routers/install/install.go:458]: Well, if we simply go by values that are explicitly set here, those are still `[session].PROVIDER`, `[repository.pull-request].DEFAULT_MERGE_STYLE`, and `[repository.signing].DEFAULT_TRUST_MODEL`…

Comment (wxiaoguang) [reply routers/install/install.go:458]: Yes, there are still many legacy problems. I have searched these "SetValue" while I think we do not need to change too much at the moment.

Leave the problem to after the INI package refactoring.

And, end users could always prepare a full app.ini with "INSTALL_LOCK=true", then no overwriting problem anymore.

Comment (lunny) [reply routers/install/install.go:458]: How about to prevent user installing again from UI?

Comment (wxiaoguang) [reply routers/install/install.go:458]: 1. I have done so
    *  Improve install code to avoid low-level mistakes. #17779 
2. Some users are doing fresh installation, the "app.ini" comes from docker environment variables, they do not "install again".

Comment (silverwind) [reply routers/install/install.go:458]: I guess a backport is not the right place to discuss 😆
