### PR TITLE
Fix user avatar name

### LINKED ISSUE #8176: Delete Avatar Problem
There is a problem something like this, reproduce:

1. Create 2 organizations
2. Set their avatars as **same** image
3. Delete one organization

Then you will see other organization's avatar reset to default gitea avatar, becouse image removed from disk.

This is same:

- Organization avatar
- User avatar
- Repository avatar

My opinions for solution:

1. Check if there are other same avatar name before remote from disk
2. Check if there are other same avatar name before set avatar and give new name if there

### PR DESCRIPTION
**Pull request by masudur-rahman**
Signed-off-by: Masudur Rahman <masudjuly02@gmail.com>

Fix: #8176

### CODE REVIEW

**Comment by lunny** [comment]
@masudur-rahman we need a migration to rename all the old avatars, otherwise all users' customize avatars will be broken.

**Comment by masudur-rahman** [comment]
> @masudur-rahman we need a migration to rename all the old avatars, otherwise all users' customize avatars will be broken.

@lunny , If we rename all the old avatars, it will cause the same problem as deleting the avatar of  one user among multiple users having same avatar as there exists only one avatar in the storage. 

Although we can copy the existing avatar with new name for each user & update the database and finally delete the old avatar from storage ( as we don't know how many users uploaded same image as their avatar ).

By the way, if we leave the existing avatars unchanged, it will work like before as the previous avatar name is stored in the database like they are in the file storage.

**Comment by lunny** [comment]
@masudur-rahman yeah. So we need a migration function and copy the avatars for that repositories which has same avatars.

**Comment by masudur-rahman** [comment]
@lunny , I completed the migration.
Please take a look if everything's okay.

File: models/user.go [hunk 1]
```diff
@@ -520,7 +520,11 @@ func (u *User) UploadAvatar(data []byte) error {
 	}
 
 	u.UseCustomAvatar = true
-	u.Avatar = fmt.Sprintf("%x", md5.Sum(data))
+	// Different users can upload same image as avatar
+	// If we prefix it with u.ID, it will be separated
+	// Otherwise, if any of the users delete his avatar
+	// Other users will lose their avatars too.
+	u.Avatar = fmt.Sprintf("%d-%x", u.ID, md5.Sum(data))
```
Comment (guillep2k) [inline models/user.go]: What's the point of using the md5 hash if the user won't be having more than one avatar? Can't this be just the user ID?

Comment (masudur-rahman) [reply models/user.go]: For random avatars, user id is used as avatar name while for custom avatar, md5 hash is used for some security reasons. 
https://github.com/go-gitea/gitea/blob/1ae25c086e9e085cf44b71720211bd836300b373/models/user.go#L352-L356

Comment (guillep2k) [reply models/user.go]: @masudur-rahman but doesn't your PR add the user ID to the file name nevertheless? If the goal is to hide the user ID perhaps it can be done like this:
```
u.Avatar = fmt.Sprintf("%x", md5.Sum(fmt.Sprintf("%d-%x", u.ID, md5.Sum(data))))
```
Or something around those lines.

Comment (masudur-rahman) [reply models/user.go]: That seems reasonable. 
For migration, I checked if the avatar already has user ID prefixed with it. If not then did the migration.
But if I use md5 hash of the whole avatar name, I can't differentiate if it has user id prefixed to it. In fact as previously there was no user id prefixed with avatar name, I can just migrate all the avatar name. 

So, I am going to use the format you suggested.
```
u.Avatar = fmt.Sprintf("%x", md5.Sum([]byte(fmt.Sprintf("%d-%x", u.ID, md5.Sum(data)))))
```

Comment (masudur-rahman) [reply models/user.go]: @guillep2k let me know if it's fine.
Thanks...

File: models/migrations/v101.go [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+		oldAvatar := user.Avatar
+		newAvatar := fmt.Sprintf("%x", md5.Sum([]byte(fmt.Sprintf("%d-%s", user.ID, user.Avatar))))
+
+		if _, err := os.Stat(filepath.Join(setting.AvatarUploadPath, oldAvatar)); err != nil {
+			continue
+		}
+
+		fr, err := os.Open(filepath.Join(setting.AvatarUploadPath, oldAvatar))
+		if err != nil {
+			return err
```
Comment (guillep2k) [inline models/migrations/v101.go]: Any OS errors below this point should try to commit previous changes into the database. Also, deletion of successfully migrated entries could be attempted.

Please format the error so the user will know what was the operation that failed ("open", "read", "write", "delete", etc.).

If possible, try to commit every _n_ changes (e.g. _n_ = 100) to avoid potential problems with a big change transaction. Also, please check if the new file name is the same as the old's, in case this procedure is retried and some avatars were already migrated.

**Review by guillep2k — CHANGES_REQUESTED** [review]

File: models/migrations/v101.go (hunk 2 above)
Comment (masudur-rahman) [reply models/migrations/v101.go]: > Any OS errors below this point should try to commit previous changes into the database.

> If possible, try to commit every n changes (e.g. n = 100) to avoid potential problems with a big change transaction.

If I directly use `x.Update(...)`, I don't have to consider if the session has big change transaction and it will solve the problem, right ?

> Also, deletion of successfully migrated entries could be attempted.

Deletion of successfully migrated entries should not be attempted until the whole migration is completed. We still don't know if any user still has avatar similar with previously migrated ones.

> Please format the error so the user will know what was the operation that failed ("open", "read", "write", "delete", etc.).

Yeah, we should totally do it.

> Also, please check if the new file name is the same as the old's, in case this procedure is retried and some avatars were already migrated.

As we are adding a prefix with old avatar and then hashing it, it will never be same as the previous avatar. If we follow the new naming system, I think there's no way to know if it's already migrated.
Besides, if we migrate already migrated avatars, will it cause any problem ?

Comment (guillep2k) [reply models/migrations/v101.go]: > 
> 
> > Any OS errors below this point should try to commit previous changes into the database.
> 
> > If possible, try to commit every n changes (e.g. n = 100) to avoid potential problems with a big change transaction.
> 
> If I directly use `x.Update(...)`, I don't have to consider if the session has big change transaction and it will solve the problem, right ?

You are right in theory, and I was initially going to propose that, but we've seen a couple of cases where many consecutive transactions could cause TCP port depletion problems (e.g. #8540). That's why I think going for a safer path, with less connections, is better. But I don't feel too comfortable with using one big transaction for all the changes either, that's why processing in batches sounds better. It's a technique that is already being used in other migration steps.

> 
> > Also, deletion of successfully migrated entries could be attempted.
> 
> Deletion of successfully migrated entries should not be attempted until the whole migration is completed. We still don't know if any user still has avatar similar with previously migrated ones.

You are right about this. I have no problem with some small unconnected files remaining in case of a migration fails half-way.

> 
> > Also, please check if the new file name is the same as the old's, in case this procedure is retried and some avatars were already migrated.
> 
> As we are adding a prefix with old avatar and then hashing it, it will never be same as the previous avatar. If we follow the new naming system, I think there's no way to know if it's already migrated.

The name of the file is now normalized by hashing the content (the inner MD5) with the user ID (outer MD5), so it will always render the same hash. **But** then I realize that you're not reading the file but trusting the previous hash. Perhaps it's worth re-hashing the file to make sure the MD5 matches the content?

> Besides, if we migrate already migrated avatars, will it cause any problem ?

I'm not sure, but it seems to me that Open() --> Create() ---> Copy() on the same path should cause some trouble. We'd need to test it with Linux, Windows, network file systems, small files, big files, etc. I think it's just easier to check if we are not trying to copy the file onto itself.

Comment (masudur-rahman) [reply models/migrations/v101.go]: > The name of the file is now normalized by hashing the content (the inner MD5) with the user ID (outer MD5), so it will always render the same hash. But then I realize that you're not reading the file but trusting the previous hash. Perhaps it's worth re-hashing the file to make sure the MD5 matches the content?

@guillep2k I tried it but didn't worked. At first I thought I am doing something wrong but then after many trial and errors, realized the `md5 hash` is generated just after uploading the image and that hash value is used as avatar name but the image is saved to file storage after some preprocessing. That's why the file never generates the same hash value.
https://github.com/go-gitea/gitea/blob/1ae25c086e9e085cf44b71720211bd836300b373/models/user.go#L510-L511

https://github.com/go-gitea/gitea/blob/1ae25c086e9e085cf44b71720211bd836300b373/models/user.go#L542-L544

> > As we are adding a prefix with old avatar and then hashing it, it will never be same as the previous avatar. If we follow the new naming system, I think there's no way to know if it's already migrated.
> 
> The name of the file is now normalized by hashing the content (the inner MD5) with the user ID (outer MD5), so it will always render the same hash. But then I realize that you're not reading the file but trusting the previous hash. Perhaps it's worth re-hashing the file to make sure the MD5 matches the content?
>
> > Besides, if we migrate already migrated avatars, will it cause any problem ?

So, I think we have no option but migrate all avatars.

Comment (guillep2k) [reply models/migrations/v101.go]: OK, I see your points.

**Comment by guillep2k** [comment]
@masudur-rahman Please resolve the conflicts.

**Comment by masudur-rahman** [comment]
@guillep2k conflicts are resolved.

File: models/migrations/v101.go (hunk 2 above)
Comment (masudur-rahman) [reply models/migrations/v101.go]: > Any OS errors below this point should try to commit previous changes into the database. 

> Please format the error so the user will know what was the operation that failed ("open", "read", "write", "delete", etc.).

> If possible, try to commit every n changes (e.g. n = 100) to avoid potential problems with a big change transaction

I did those changes. Please have a look.

File: models/migrations/v103.go [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+		return err
+	}
+
+	type User struct {
+		ID     int64 `xorm:"pk autoincr"`
+		Avatar string
+	}
+
+	users := make([]User, 0)
+	if err := sess.Find(&users); err != nil {
```
Comment (lunny) [inline models/migrations/v103.go]: Assume you have thousands of users?

Comment (lafriks) [reply models/migrations/v103.go]: Yeah this this should be done in in batches, see other migrations

File: models/migrations/v103.go [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+		if _, err := os.Stat(filepath.Join(setting.AvatarUploadPath, oldAvatar)); err != nil {
+			continue
+		}
+
+		fr, err := os.Open(filepath.Join(setting.AvatarUploadPath, oldAvatar))
+		if err != nil {
+			_ = commitSession(sess)
+			return fmt.Errorf("os.Open: %v", err)
+		}
+		defer fr.Close()
```
[the remark this answers is not in the document]
Comment (masudur-rahman) [reply models/migrations/v103.go]: No problem.
Another thing: If we always have to migrate the avatars for all the users due to some failure, do we really need to commit the session with previous changes before returning the error ?
https://github.com/go-gitea/gitea/blob/8baca3992e6ce8cae9355952ddead870001b62c7/models/migrations/v103.go#L52-L57

File: models/migrations/v103.go (hunk 3 above)
Comment (masudur-rahman) [reply models/migrations/v103.go]: @lunny , @lafriks I have processed them in batches now. Do they look okay ?

File: models/migrations/v103.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (guillep2k) [reply models/migrations/v103.go]: @masudur-rahman That's what I thought before you pointed me out that you couldn't delete the avatars until finishing migrating them all. Now it doesn't seem to add much value. But it's already in the code, so removing it is a matter of cleaning up the code if you want to. In a not-so-unrelated matter, I think it would be useful to print the user's `lower_name` as part of the error messages. But it's not strictly required.

[the remark this answers is not in the document]
Comment (masudur-rahman) [reply models/migrations/v103.go]: Done.
Everything's should be okay now. @guillep2k, can you please recheck now ?

**Review by guillep2k — APPROVED** [review]

**Comment by masudur-rahman** [comment]
@lunny, I think everything's okay now. Could you please review once again ?

File: models/user.go [hunk 5]
```diff
@@ -520,7 +520,11 @@ func (u *User) UploadAvatar(data []byte) error {
 	}
 
 	u.UseCustomAvatar = true
-	u.Avatar = fmt.Sprintf("%x", md5.Sum(data))
+	// Different users can upload same image as avatar
+	// If we prefix it with u.ID, it will be separated
+	// Otherwise, if any of the users delete his avatar
+	// Other users will lose their avatars too.
+	u.Avatar = fmt.Sprintf("%x", md5.Sum([]byte(fmt.Sprintf("%d-%x", u.ID, md5.Sum(data)))))
```
Comment (jaqra) [inline models/user.go:528]: Different user can be add same image but its low probability. Instead, same user can use same image in multi time.
So what will happen if user add same image to organizations and remove one organization?
Or add same image for own avatar and own repos' avatars then delete one repo?

**Comment by 6543** [comment]
@masudur-rahman resolve conflict (migration is from v104 -> v105)

If Bakport only posible after backport of https://github.com/go-gitea/gitea/pull/8483#event-2728733779

**Comment by zeripath** [comment]
OK, sorry about merging my PR breaking the migration again.

I think we're doing the wrong thing by having to backport a migration.

For the backports we should simply stop removing avatars - we could add (yet) another admin task to just run through and clean-up.

In the 1.11 migration we simply run the cleanup task and do the name changes. The admin task can be removed at that point.

**Comment by zeripath** [comment]
Instead of changing filenames another option for the migration is to count how many times an image is referenced and keep a count - however, there could be a race-condition where these might get out of sync - so naming per-id is possibly safer.

Finally, please could we check that the repository avatars are not affected by a similar bug.

**Comment by 6543** [comment]
@lafriks can you remove lable "backport/1.9" this isn't posible because of migrations ...

**Comment by lafriks** [comment]
It's not possible to backport this to 1.10 also

File: models/user.go (hunk 5 above)
Comment (masudur-rahman) [reply models/user.go:528]: > Different user can be add same image but its low probability. Instead, same user can use same image in multi time.

We are using hash value of the user uploaded image prefixed with userID. So, if same user uploads same photo multiple time as his avatar, it will generate same hash value throughout the time. As we are prefixing the hash value with user id, the avatar name will be always same for same photo & same user.

> So what will happen if user add same image to organizations and remove one organization?

As I mentioned we are prefixing user id with the photo hash, it will not cause any problem. Organization is also like a user having different id. Every organization has different id, so it will not replace the previous image or delete other organization's avatar while deleting another organization.

> Or add same image for own avatar and own repos' avatars then delete one repo?

Repos' avatars are stored in separate directory and also they are prefixing with repo id with image hash which will not conflict with one another.
Even if both avatars are stored in same directory, they will not collide as for user avatar we are taking another hash value of `<hash>[<userid>-<image_hash>]` and for repo the final hash isn't using.

Hope I made myself clear.

**Comment by masudur-rahman** [comment]
> @masudur-rahman resolve conflict (migration is from v104 -> v105)

@6543 , I resolved the conflicts. You may take a look now.

**Comment by masudur-rahman** [comment]
> Instead of changing filenames another option for the migration is to count how many times an image is referenced and keep a count - however, there could be a race-condition where these might get out of sync - so naming per-id is possibly safer.
> 
> Finally, please could we check that the repository avatars are not affected by a similar bug.

@zeripath,for repo avatar it is already implemented.
https://github.com/go-gitea/gitea/blob/4089f680421f939ee8c6378796738d1fa2d4f6b5/models/repo.go#L2764

But there is some dissimilarity. For user avatar we are taking a final hash but for repo avatar the final hash isn't used.

**Comment by masudur-rahman** [comment]
@zeripath, could you please help me with the test failing ?
https://drone.gitea.io/go-gitea/gitea/14397/1/15

Before resolving the conflicts, tests were passing but now it's failing.
I figured you added those integration tests. That's why I thought may be you could help me with the failing test.

**Comment by 6543** [comment]
@masudur-rahman hey its funny but we have to mve migration from v104 -> v105 ...

And about https://github.com/go-gitea/gitea/pull/8547#issuecomment-544542059
can we make all avatar url generation the same way?

**Comment by 6543** [comment]
abut `<uid>-<hash>` i dont see any securety issues ...

but i dont mind if we make all avatar urls `hash(<uid>,<content-hash>)`

**Comment by masudur-rahman** [comment]
> @masudur-rahman hey its funny but we have to mve migration from v104 -> v105 ...

@6543 , I have updated the migration.

> And about [#8547 (comment)](https://github.com/go-gitea/gitea/pull/8547#issuecomment-544542059)
> can we make all avatar url generation the same way?

We can but we will need another migration to rename all the old `repo.Avatar`. Someone may have  different opinion on how and what to do.
So, I think we should just skip that part in this pr. If we really want `repo.Avatar` to be same as `u.Avatar`, we can make another pr regarding the changes.

File: models/migrations/v105.go [hunk 6]
```diff
@@ -0,0 +1,98 @@
...
+	for {
+		if err := sess.Begin(); err != nil {
+			return fmt.Errorf("session.Begin: %v", err)
+		}
+		users := make([]*User, 0, 50)
+		if err := sess.Table("user").Asc("id").Limit(50, start).Find(&users); err != nil {
+			return fmt.Errorf("select users from id [%d]: %v", start, err)
+		}
+		if len(users) == 0 {
+			break
```
Comment (lunny) [inline models/migrations/v105.go]: sess.Rollback()

**Review by lunny — CHANGES_REQUESTED** [review]

File: models/migrations/v105.go (hunk 6 above)
Comment (masudur-rahman) [reply models/migrations/v105.go]: @lunny, we don't have anything in session here. Is `sess.Find()` included in session ?

Another thing, as `sess.Close` does the `Rollback()` part if anything remains in session, do we still need to call `sess.Rollback()` ?
https://github.com/go-gitea/gitea/blob/aa7c34cf86081b71f796f6e5da60e62a3cda43ce/vendor/github.com/go-xorm/xorm/session.go#L98-L113

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@lunny what do you mean with https://github.com/go-gitea/gitea/pull/8547#discussion_r338384780
I'm still learning about xorm D:

File: models/migrations/v105.go (hunk 6 above)
Comment (lunny) [reply models/migrations/v105.go]: @masudur-rahman for the first question, I think it's OK.

But this will create serval transactions but not one transaction. So you have to Rollback manually on the `for loop`.

File: models/migrations/v105.go [hunk 7]
```diff
@@ -0,0 +1,98 @@
...
+				// we can just skip this
+				continue
+			}
+
+			if err := copyAvatar(oldAvatar, newAvatar); err != nil {
+				return fmt.Errorf("[user: %s] %v", user.LowerName, err)
+			}
+
+			user.Avatar = newAvatar
+			if _, err := sess.ID(user.ID).Update(user); err != nil {
```
Comment (lunny) [inline models/migrations/v105.go]: We only need to Update `avatar`. `sess.ID(user.ID).Cols("avatar").Update(user)`.

File: models/migrations/v105.go (hunk 6 above)
Comment (masudur-rahman) [reply models/migrations/v105.go]: Okay.
So, @lunny, do we need to use `session.Rollback()` before returning each error ? or just the section you mentioned ?

**Comment by 6543** [comment]
@masudur-rahman can you resolve conflicts

**Comment by masudur-rahman** [comment]
@6543, I am waiting for a response for https://github.com/go-gitea/gitea/pull/8547#discussion_r341840020.

I just wanted to resolve all the problems at once. :pensive:

File: models/migrations/v105.go (hunk 6 above)
Comment (lunny) [reply models/migrations/v105.go]: @masudur-rahman Yes. We could just call `session.Close()` or `session.Rollback()`. Both will rollback if you haven't called `session.Commit`.

**Comment by 6543** [comment]
@masudur-rahman migrations is now from `v109 -> v110` and you shuld rename your file to v109.go

thx

File: models/migrations/v109.go [hunk 8]
```diff
@@ -0,0 +1,102 @@
...
+	for {
+		if err := sess.Begin(); err != nil {
+			return fmt.Errorf("session.Begin: %v", err)
+		}
+		users := make([]*User, 0, 50)
+		if err := sess.Table("user").Asc("id").Limit(50, start).Find(&users); err != nil {
+			return fmt.Errorf("select users from id [%d]: %v", start, err)
+		}
+		if len(users) == 0 {
+			_ = sess.Rollback()
```
Comment (6543) [inline models/migrations/v109.go]:
```suggestion
```
this: https://github.com/go-gitea/gitea/pull/8547/files#diff-dfb9e9e80e5d8118b61bab1fc5950308R22 already take care of

File: models/migrations/v109.go [hunk 9]
```diff
@@ -0,0 +1,102 @@
...
+			if _, err := os.Stat(filepath.Join(setting.AvatarUploadPath, oldAvatar)); err != nil {
+				log.Warn("[user: %s] os.Stat: %v", user.LowerName, err)
+				// avatar doesn't exist in the storage
+				// no need to move avatar and update database
+				// we can just skip this
+				continue
+			}
+
+			if err := copyAvatar(oldAvatar, newAvatar); err != nil {
+				_ = sess.Rollback()
```
Comment (6543) [inline models/migrations/v109.go]:
```suggestion
```
same

File: models/migrations/v109.go [hunk 10]
```diff
@@ -0,0 +1,102 @@
...
+				return fmt.Errorf("[user: %s] %v", user.LowerName, err)
+			}
+
+			user.Avatar = newAvatar
+			if _, err := sess.ID(user.ID).Cols("avatar").Update(user); err != nil {
+				_ = sess.Rollback()
```
Comment (6543) [inline models/migrations/v109.go]:
```suggestion
```
same

File: models/migrations/v109.go [hunk 11]
```diff
@@ -0,0 +1,102 @@
...
+				return fmt.Errorf("[user: %s] user table update: %v", user.LowerName, err)
+			}
+
+			deleteList[filepath.Join(setting.AvatarUploadPath, oldAvatar)] = struct{}{}
+		}
+		if err := sess.Commit(); err != nil {
+			_ = sess.Rollback()
```
Comment (6543) [inline models/migrations/v109.go]:
```suggestion
```

File: models/migrations/v109.go [hunk 12]
```diff
@@ -0,0 +1,102 @@
...
+func renameExistingUserAvatarName(x *xorm.Engine) error {
+	sess := x.NewSession()
+	defer sess.Close()
+
+	type User struct {
+		ID        int64  `xorm:"pk autoincr"`
+		LowerName string `xorm:"UNIQUE NOT NULL"`
+		Avatar    string
+	}
+	deleteList := make(map[string]struct{})
```
Comment (6543) [inline models/migrations/v109.go]:
```suggestion
	var deleteList []string
```
why not use normal string slice?

File: models/migrations/v109.go [hunk 13]
```diff
@@ -0,0 +1,102 @@
...
+				return fmt.Errorf("[user: %s] %v", user.LowerName, err)
+			}
+
+			user.Avatar = newAvatar
+			if _, err := sess.ID(user.ID).Cols("avatar").Update(user); err != nil {
+				_ = sess.Rollback()
+				return fmt.Errorf("[user: %s] user table update: %v", user.LowerName, err)
+			}
+
+			deleteList[filepath.Join(setting.AvatarUploadPath, oldAvatar)] = struct{}{}
```
Comment (6543) [inline models/migrations/v109.go]:
```suggestion
			deleteList = append(deleteList, filepath.Join(setting.AvatarUploadPath, oldAvatar))
```

File: models/migrations/v109.go [hunk 14]
```diff
@@ -0,0 +1,102 @@
...
+		}
+		if err := sess.Commit(); err != nil {
+			_ = sess.Rollback()
+			return fmt.Errorf("commit session: %v", err)
+		}
+	}
+
+	for file := range deleteList {
```
Comment (6543) [inline models/migrations/v109.go]:
```suggestion
	for _, file := range deleteList {
```

**Review by 6543 — CHANGES_REQUESTED** [review]

File: models/migrations/v109.go (hunk 13 above)
Comment (6543) [reply models/migrations/v109.go]: belong to https://github.com/go-gitea/gitea/pull/8547#discussion_r347565600

File: models/migrations/v109.go (hunk 14 above)
Comment (6543) [reply models/migrations/v109.go]: belong to https://github.com/go-gitea/gitea/pull/8547#discussion_r347565600

File: models/migrations/v109.go (hunk 12 above)
Comment (masudur-rahman) [reply models/migrations/v109.go]: At first I used normal string slice but then I replaced it with map.

Several users can have same avatar name*, so if we use normal slice for storing this, duplicate entries will be stored. This will cause problems in later parts of the code.


\* Resolving the avatar name duplication is the main reason of this pr.

File: models/migrations/v109.go (hunk 8 above)
Comment (masudur-rahman) [reply models/migrations/v109.go]: @6543, you can see that I've added this in the very last commit.
You can find out why I added that part in https://github.com/go-gitea/gitea/pull/8547#discussion_r338384780 and its response.

File: models/migrations/v105.go (hunk 7 above)
Comment (masudur-rahman) [reply models/migrations/v105.go]: @lunny, I've updated the code. Could you please review it ?

File: models/migrations/v109.go (hunk 12 above)
Comment (masudur-rahman) [reply models/migrations/v109.go]: @6543, could you please provide any further feedback regarding my response ?

Comment (6543) [reply models/migrations/v109.go]: if you add a new "string" you could use `util.IsStringInSlice("string", slice)` when adding a new string - but map already do the job for you :+1:

Comment (6543) [reply models/migrations/v109.go]: would say resolved

**Review by 6543 — APPROVED** [review]

File: models/migrations/v109.go (hunk 12 above)
Comment (masudur-rahman) [reply models/migrations/v109.go]: :+1:

**Comment by 6543** [comment]
what is the status?

**Comment by lafriks** [comment]
@lunny please review

**Comment by techknowlogick** [comment]
@masudur-rahman please resolve conflicts

**Comment by techknowlogick** [comment]
@masudur-rahman I hope you don't mind that I resolved the conflicts for you

@lunny please review

File: models/migrations/v112.go [hunk 15]
```diff
@@ -0,0 +1,102 @@
...
+	for {
+		if err := sess.Begin(); err != nil {
+			return fmt.Errorf("session.Begin: %v", err)
+		}
+		users := make([]*User, 0, 50)
+		if err := sess.Table("user").Asc("id").Limit(50, start).Find(&users); err != nil {
+			return fmt.Errorf("select users from id [%d]: %v", start, err)
+		}
+		if len(users) == 0 {
+			_ = sess.Rollback()
```
Comment (lunny) [inline models/migrations/v112.go]: ~Why rollback here? Where is the normal condition to break the for loop?~

**Comment by lunny** [comment]
@masudur-rahman See my comment on https://github.com/go-gitea/gitea/pull/8547#discussion_r354269707, I think current migration will not work.

**Comment by lunny** [comment]
Please resolve the conflicts.

File: models/migrations/v112.go (hunk 15 above)
Comment (masudur-rahman) [reply models/migrations/v112.go]: > Why rollback here?

https://github.com/go-gitea/gitea/pull/8547#discussion_r338384780

> Where is the normal condition to break the for loop?

`len(users) == 0` is normal loop breaking condition. I followed this part from an existing migration.

**Comment by masudur-rahman** [comment]
@lunny, https://github.com/go-gitea/gitea/pull/8547#discussion_r358591456

**Comment by masudur-rahman** [comment]
@lunny, conflicts are resolved and also checkout https://github.com/go-gitea/gitea/pull/8547#discussion_r358591456 .

**Comment by masudur-rahman** [comment]
And resolved the conflicts for the second time in a single day. Hope it will be processed before another conflict.

**Comment by 6543** [comment]
code in migration often causes conflicts ...

**Review by lunny — APPROVED** [review]

**Review by lunny — CHANGES_REQUESTED** [review]
~And maybe we should store as `<userid>-<file_md5_hash>` but not a hash of that string.
Because we could check if the files have been moved.~

EDIT: this may leak user's id.

**Review by lunny — APPROVED** [review]

**Review by lunny — CHANGES_REQUESTED** [review]
Sorry for changing my opinion again.

Once the migration was failed on the middlew. You have to run it again. It will always change the md5
hash(<userid>-hash(<userid>-<file_md5_hash>)). Maybe we have to calculate the md5 from the file but not get from the database.

**Comment by guillep2k** [comment]
> 
> 
> Sorry for changing my opinion again.
> 
> Once the migration was failed on the middlew. You have to run it again. It will always change the md5
> hash(-hash(-<file_md5_hash>)). Maybe we have to calculate the md5 from the file but not get from the database.

So we should use the same method as in `UploadAvatar()`:

```
u.Avatar = fmt.Sprintf("%x", md5.Sum([]byte(fmt.Sprintf("%d-%x", u.ID, md5.Sum(data)))))
```

We will need to read the file into memory. That should not be a problem as we do that for all avatars anyway.

**Comment by masudur-rahman** [comment]
@lunny & @guillep2k, sorry for being late.

I've used avatar file hash for new avatar instead of old avatar from database as you suggested.

Hope it's okay.

**Review by lunny — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@masudur-rahman can you **'update branch'**

**Comment by masudur-rahman** [comment]
> @masudur-rahman can you **'update branch'**
> 
> or allow changes to it for maintainers?

@6543, I've updated the branch and also allowed edits from maintainers.

File: models/migrations/v115.go [hunk 16]
```diff
@@ -0,0 +1,107 @@
...
+	start := 0
+	for {
+		if err := sess.Begin(); err != nil {
+			return fmt.Errorf("session.Begin: %v", err)
+		}
+		users := make([]*User, 0, 50)
+		if err := sess.Table("user").Asc("id").Limit(50, start).Find(&users); err != nil {
+			return fmt.Errorf("select users from id [%d]: %v", start, err)
+		}
+		if len(users) == 0 {
```
Comment (zeripath) [inline models/migrations/v115.go]: Er... What if you have 0 mod 50 users?

File: models/migrations/v115.go [hunk 17]
```diff
@@ -0,0 +1,107 @@
...
+				return fmt.Errorf("[user: %s] %v", user.LowerName, err)
+			}
+
+			user.Avatar = newAvatar
+			if _, err := sess.ID(user.ID).Cols("avatar").Update(user); err != nil {
+				_ = sess.Rollback()
+				return fmt.Errorf("[user: %s] user table update: %v", user.LowerName, err)
+			}
+
+			deleteList[filepath.Join(setting.AvatarUploadPath, oldAvatar)] = struct{}{}
```
Comment (zeripath) [inline models/migrations/v115.go:72]: What if there is a failure half-way through this migration and so you rerun it?

It looks like in that case you will delete all of the previously migrated newAvatars?

Shouldn't you be testing that the oldAvatar != newAvatar?

File: models/migrations/v115.go [hunk 18]
```diff
@@ -0,0 +1,107 @@
...
+}
+
+// copyOldAvatarToNewLocation copies oldAvatar to newAvatarLocation
+// and returns newAvatar location
+func copyOldAvatarToNewLocation(userID int64, oldAvatar string) (string, error) {
+	fr, err := os.Open(filepath.Join(setting.AvatarUploadPath, oldAvatar))
+	if err != nil {
+		return "", fmt.Errorf("os.Open: %v", err)
+	}
+	defer fr.Close()
```
Comment (zeripath) [inline models/migrations/v115.go:95]: In the case of reruning the migration because it failed half-way through this will cause windows to throw an exception because it won't be able to write to the same file.

It might be worth moving the newAvatar line higher and checking if it is the same as the oldAvatar.

File: models/migrations/v115.go [hunk 19]
```diff
@@ -0,0 +1,107 @@
...
+
+	data, err := ioutil.ReadAll(fr)
+	if err != nil {
+		return "", fmt.Errorf("ioutil.ReadAll: %v", err)
+	}
+
+	newAvatar := fmt.Sprintf("%x", md5.Sum([]byte(fmt.Sprintf("%d-%x", userID, md5.Sum(data)))))
+
```
Comment (6543) [inline models/migrations/v115.go:106]:
```suggestion

	it oldAvatar == newAvatar {
		return newAvatar, nil
	}

```

Comment (6543) [reply models/migrations/v115.go:106]: (if migration happend ... dont overwrite)

File: models/migrations/v115.go [hunk 20]
```diff
@@ -0,0 +1,107 @@
...
+				// we can just skip this
+				continue
+			}
+
+			newAvatar, err := copyOldAvatarToNewLocation(user.ID, oldAvatar)
+			if err != nil {
+				_ = sess.Rollback()
+				return fmt.Errorf("[user: %s] %v", user.LowerName, err)
+			}
+
```
Comment (6543) [inline models/migrations/v115.go:65]:
```suggestion

			if oldAvatar == newAvatar {
				// avatar is already migrated
				// we can just skip this
				continue
			}
			
```

Comment (6543) [reply models/migrations/v115.go:65]: (if migration already happend ... skip)

File: models/migrations/v115.go (hunk 17 above)
Comment (6543) [reply models/migrations/v115.go:72]: https://github.com/go-gitea/gitea/pull/8547/files#r361710833

https://github.com/go-gitea/gitea/pull/8547/files#r361710313

should fix this @zeripath ?

Comment (masudur-rahman) [reply models/migrations/v115.go:72]: Thanks. when I wrote this, every time the newAvatar would become different. so back then it wasn't necessary. But now it's not good. I will update as soon as possible. 
Thanks for your suggestion.

Comment (zeripath) [reply models/migrations/v115.go:72]: yeah those would fix it.

File: models/migrations/v115.go (hunk 19 above)
Comment (masudur-rahman) [reply models/migrations/v115.go:106]: Thanks, I'll update as soon as possible.

File: models/migrations/v115.go (hunk 17 above)
Comment (zeripath) [reply models/migrations/v115.go:72]: NP I'll do it for you.

**Comment by zeripath** [comment]
We can also delete the files as soon as the session commits - so I'll do that too.

File: models/migrations/v115.go (hunk 18 above)
Comment (6543) [reply models/migrations/v115.go:95]: would say this is outdated now

**Review by 6543 — APPROVED** [review]
lgtm again as it handles **newAvatar == oldAvatar**

**Comment by zeripath** [comment]
I guess it's just a migration and if there is excess left over data after a fail that's fine.

What we cannot have is that there is a failure we lose data and we're now at the point that we cannot lose data whereas previously we could have. 

So I'll take another quick look after the build has done it's job and if I can't think another way to break this then it can be merged.

Sorry that this has taken so long @masudur-rahman - this has been unexpectedly complex.

**Comment by 6543** [comment]
@zeripath yes - would say ready to merge :rock: from my side :+1: 

@masudur-rahman thanks !
sometimes a PR needs a bit of patience

**Comment by masudur-rahman** [comment]
> I guess it's just a migration and if there is excess left over data after a fail that's fine.
> 
> What we cannot have is that there is a failure we lose data and we're now at the point that we cannot lose data whereas previously we could have.
> 
> So I'll take another quick look after the build has done it's job and if I can't think another way to break this then it can be merged.
> 
> Sorry that this has taken so long @masudur-rahman - this has been unexpectedly complex.

It's okay. Thanks for handling the last faults for me.

**Comment by masudur-rahman** [comment]
> @zeripath yes - would say ready to merge  from my side 
> 
> @masudur-rahman thanks !
> sometimes a PR needs a bit of patience

Thanks to you too. Although it took a long bit of patience, I hope it was worth.

**Comment by masudur-rahman** [comment]
> ~We can also delete the files as soon as the session commits - so I'll do that too.~
> 
> oh damn we can't
Yeah, we can't delete the the migrated avatars yet. I almost thought you've  changed that part.

**Comment by lunny** [comment]
This should also be back port to v1.10. But since there is a migration, it's some difficult.
