### PR TITLE
Fix PR toggle WIP

### LINKED ISSUE #34919: Remove WIP button disappears
### Description

Upon opening a WIP pull request Remove WIP button appears for a fraction of a second and disappears

### Screenshots

Image

### Gitea Version

1.24.2

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

win

### Browser Version

edge 137

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #34919

### CODE REVIEW

**Comment by wxiaoguang** [comment]
image

image

**Review by lunny — APPROVED** [review]

**Review by delvh — APPROVED** [review]

File: web_src/js/features/repo-issue.ts [hunk 1]
```diff
@@ -416,25 +417,20 @@ export function initRepoIssueWipNewTitle() {
...
-        throw new Error('Failed to toggle WIP status');
-      }
-      window.location.reload();
-    } catch (error) {
-      console.error(error);
+    const params = new URLSearchParams();
+    params.append('title', title?.startsWith(wipPrefix) ? title.slice(wipPrefix.length).trim() : `${wipPrefix.trim()} ${title}`);
+    const response = await POST(updateUrl, {data: params});
+    if (!response.ok) {
+      showErrorToast('Failed to toggle WIP status');
```
Comment (delvh) [inline web_src/js/features/repo-issue.ts]:
```suggestion
      showErrorToast('Failed to toggle 'work in progress' status');
```

Comment (wxiaoguang) [reply web_src/js/features/repo-issue.ts]: Hmm ... single quote in single quote ...

```suggestion
      showErrorToast(`Failed to toggle 'work in progress' status`);
```
