### PR TITLE
Fix some mirror bugs

### LINKED ISSUE #18652: Mirror information missed in repository setting page
image

### PR DESCRIPTION
**Pull request by lunny**
This PR introduces a new git URL parse package to parse git URL.
It will fix mirror repository UI display problem.

Fix #18652

### CODE REVIEW

File: modules/git/url/url.go [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+	case 1:
+		return fmt.Sprintf("%s@%s:%s", u.User.Username(), u.Host, u.Path)
+	case 2:
+		return u.Path
+	default:
+		return ""
+	}
+}
+
+var scpSyntaxRe = regexp.MustCompile(`^([a-zA-Z0-9_]+)@([a-zA-Z0-9._-]+):(.*)$`)
```
Comment (wxiaoguang) [inline modules/git/url/url.go]: 1. The `name` part might contain dash `-`
2. The `host` part might be IPv6

File: modules/git/url/url.go [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+	if err == nil {
+		extraMark := 0
+		if u.Scheme == "" && u.Path != "" {
+			u.Scheme = "file"
+			extraMark = 2
+		}
+		return &URL{URL: u, extraMark: extraMark}, nil
+	}
+
+	if !strings.Contains(err.Error(), "first path segment in URL cannot contain colon") {
```
Comment (wxiaoguang) [inline modules/git/url/url.go]: Does this case really help the parsing? If it doesn't help, maybe we can skip the hard-coded string check.

File: modules/git/url/url.go [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+import (
+	"fmt"
+	"net/url"
+	"regexp"
+	"strings"
+)
+
+// URL represents a git remote URL
+type URL struct {
+	*url.URL
```
Comment (wxiaoguang) [inline modules/git/url/url.go]: It's ambiguous to read `url.URL` in code. It looks like the Golang built-in `url.URL`

Should we call it `giturl.GitURL`?

File: modules/git/url/url.go [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+	extraMark int // 0 no extra 1 scp 2 file path with no prefix
```
Comment (wxiaoguang) [inline modules/git/url/url.go:25]: Could we use `URL.Schema` directly without introducing `extraMark`?
* URL.Schema="file": file
* URL.Schema="ssh":  user@host:path
* URL.Schema="http"/"https": ...

File: modules/git/url/url.go (hunk 2 above)
Comment (lunny) [reply modules/git/url/url.go]: It's really help when parsing `git@gitea.com:gitea/gitea.git` .

File: modules/git/url/url.go (hunk 4 above)
Comment (lunny) [reply modules/git/url/url.go:25]: We can't, we need to know the difference between `file:///root` and `/root`.

File: modules/git/url/url.go (hunk 2 above)
Comment (wxiaoguang) [reply modules/git/url/url.go]: > It's really help when parsing `git@gitea.com:gitea/gitea.git` .

I know, but could we just skip this check and let the code below to continue to parse? Then we do not need to hard code the magic string.

File: modules/git/url/url.go (hunk 4 above)
Comment (wxiaoguang) [reply modules/git/url/url.go:25]: What's the difference?

File: modules/git/url/url.go (hunk 3 above)
Comment (lunny) [reply modules/git/url/url.go]: I don't think it's necessary. A similar form makes users know it quickly.

File: modules/git/url/url.go (hunk 1 above)
Comment (lunny) [reply modules/git/url/url.go]: 1 resolved
2 I don't really think we can support that.

File: modules/git/url/url.go (hunk 2 above)
Comment (wxiaoguang) [reply modules/git/url/url.go]: At least, we can check `@` and `://` first, if the URL string doesn't contain `://` but contains `@`, then we do not use `url.Parse`, then we do not need to hard code any error string.

Indeed we can predict all cases:

1. A string contains `://`: use `url.Parse`
2. else if it contains `@`: use SSH parse
3. else check if it is a local path

Then everything is under control.

File: modules/git/url/url.go (hunk 1 above)
Comment (wxiaoguang) [reply modules/git/url/url.go]: 1. it seems `~` or `.` wouldn't appear in the unix names (it doesn't do harm either, so it's fine)
2. reason?

File: modules/git/url/url.go (hunk 2 above)
Comment (lunny) [reply modules/git/url/url.go]: And filepath may also contains `@`.

Comment (wxiaoguang) [reply modules/git/url/url.go]: Yup, so there is the step 3 `else` if step 2 fails.

File: modules/git/url/url.go [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+// Parse parse all kinds of git remote URL
+func Parse(remote string) (*URL, error) {
+	u, err := stdurl.Parse(remote)
+	if err == nil {
+		extraMark := 0
+		if u.Scheme == "" && u.Path != "" {
+			u.Scheme = "file"
+			extraMark = 2
+		}
+		return &URL{URL: u, extraMark: extraMark}, nil
```
Comment (zeripath) [inline modules/git/url/url.go]: I guess the question here is what could be being passed into this function...

`ssh://git@github.com/go-gitea/gitea.git` would parse as an url here.

as would `ftp://...` and `gopher://` and `smb://` etc.

but also: `git@github.com` and `gitea:admin/private.git`

File: modules/git/url/url.go (hunk 2 above)
Comment (zeripath) [reply modules/git/url/url.go]: Although I would usually agree that hard coding the error seems distasteful it is the correct thing to do. This is the error string that go reports.

I would say that we should use strings.HasSuffix(": first path ...")  with the colon and the space, or use

```go
	urlBadPathError := errors.New("first path segment in URL cannot contain colon")

	if err != nil && errors.As(err, &urlBadPathError) {
```

File: modules/git/url/url.go [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+	}
+
+	if !strings.Contains(err.Error(), "first path segment in URL cannot contain colon") {
+		return nil, err
+	}
+
+	if results := scpSyntaxRe.FindStringSubmatch(remote); results != nil {
```
Comment (zeripath) [inline modules/git/url/url.go]: an SCP "url" is:

```
[<user>@]host:[<path>]
```

where host can be ip6 wrapped in `[` `]`

I suspect we may just want to detect the ipv6 paths directly,

File: modules/git/url/url.go (hunk 2 above)
Comment (lunny) [reply modules/git/url/url.go]: Code outdated.

File: modules/git/url/url.go (hunk 5 above)
Comment (lunny) [reply modules/git/url/url.go]: I don't want to support `ftp://` because it has been depreciated from Git . Currently only the four protocols of `ssh`(scp), `file`, `http(s)`, `git`  are supported. I think it's enough.

File: modules/git/url/url.go (hunk 1 above)
Comment (lunny) [reply modules/git/url/url.go]: removed regex

File: modules/git/url/url.go (hunk 4 above)
Comment (lunny) [reply modules/git/url/url.go:25]: We don't know if it's a scp path or a file path after parsed. So why this mark is necessary.

File: modules/git/url/url.go (hunk 5 above)
Comment (6543) [reply modules/git/url/url.go]: you always can clone such edgecases and push manualy to the gitea instance you want ... so agree

File: modules/templates/helper.go [hunk 7]
```diff
@@ -916,20 +916,35 @@ type remoteAddress struct {
...
+		var err error
+		remoteURL, err = git.GetRemoteURL(ctx, m.RepoPath(), remoteName)
+		if err != nil {
+			log.Error("GetRemoteURL %v", err)
+			return a
+		}
+	}
 
-	u, err := git.GetRemoteAddress(ctx, m.GetRepository().RepoPath(), m.GetRemoteName())
+	u, err := url.Parse(remoteURL)
```
Comment (6543) [inline modules/templates/helper.go]:
```suggestion
	u, err := giturl.Parse(remoteURL)
```
?

**Review by wxiaoguang — APPROVED** [review]
LGTM (maybe some consts can be used for extraMark)

File: modules/git/url/url_test.go [hunk 8]
```diff
@@ -0,0 +1,155 @@
...
+				extraMark: 1,
+			},
+		},
+		{
+			kase: "git@[fe80:14fc:cec5:c174:d88%2510]:go-gitea/gitea.git",
+			expected: &GitURL{
+				URL: &url.URL{
+					Scheme: "ssh",
+					User:   url.User("git"),
+					Host:   "[fe80:14fc:cec5:c174:d88%2510]",
```
Comment (wxiaoguang) [inline modules/git/url/url_test.go]: One more thing, this behavior is not the same as url.Parse. It should be:

```golang
func main() {
	u, _ := url.Parse("https://[fe80:14fc:cec5:c174:d88%2510]:20")
	println(u.Host)
	println(u.Hostname())
}

// the '%' should be unescaped
// [fe80:14fc:cec5:c174:d88%10]:20
// fe80:14fc:cec5:c174:d88%10

```

File: modules/git/remote.go [hunk 9]
```diff
@@ -6,14 +6,15 @@ package git
...
 	"context"
-	"net/url"
+
+	giturl "code.gitea.io/gitea/modules/git/url"
 )
 
-// GetRemoteAddress returns the url of a specific remote of the repository.
-func GetRemoteAddress(ctx context.Context, repoPath, remoteName string) (*url.URL, error) {
+// GetRemoteURL returns remote url of git repository in the repoPath with special remote name
+func GetRemoteURL(ctx context.Context, repoPath, remoteName string) (string, error) {
```
Comment (zeripath) [inline modules/git/remote.go]: This should be GetRemoteAddress and the other one GetRemoteURL

File: modules/git/remote.go [hunk 10]
```diff
@@ -24,11 +25,20 @@ func GetRemoteAddress(ctx context.Context, repoPath, remoteName string) (*url.UR
...
 
 	if len(result) > 0 {
 		result = result[:len(result)-1]
 	}
-	return url.Parse(result)
+	return result, nil
+}
+
+// GetRemoteAddress returns the url of a specific remote of the repository.
+func GetRemoteAddress(ctx context.Context, repoPath, remoteName string) (*giturl.GitURL, error) {
```
Comment (zeripath) [inline modules/git/remote.go]: This is returning an URL (albeit a new GitURL) so it should be GetRemoteURL - the string returning thing should be the GetRemoteAddress

File: modules/git/url/url.go [hunk 11]
```diff
@@ -0,0 +1,90 @@
...
+
+// Parse parse all kinds of git URL
+func Parse(remote string) (*GitURL, error) {
+	if strings.Contains(remote, "://") {
+		u, err := stdurl.Parse(remote)
+		if err != nil {
+			return nil, err
+		}
+		return &GitURL{URL: u}, nil
+	} else if strings.Contains(remote, "@") && strings.Contains(remote, ":") {
```
Comment (zeripath) [inline modules/git/url/url.go:50]: The SCP target path parsing is found here: https://github.com/openssh/openssh-portable/blob/16ea8b85838dd7a4dbeba4e51ac4f43fd68b1e5b/misc.c#L767-L834

1. If there is a `'['` then we can split by the first `':'` after `']'` 
   - note this `':'` has to be immediately after the `]` otherwise the whole parse fails and it's a path.
2. Otherwise split by the first `':'`
3. We split by this `':'` into `<host_user> ':' <path>` 
   - if `<path>` is empty set to `"."`. If no `':'` set all to `<path>`
4. Split `<host_user>` by `'@'` into `<user> '@' <host-to-clean>`. 
   - if no `'@'` set all to `<host-to-clean>`
5.  `<host-to-clean>` - strip off `'['` and `']'` if present to form the `<host>`

**Review by zeripath — APPROVED** [review]
Although the scp url parsing isn't exactly the same as that in ssh it appears almost equivalent.

**Comment by lunny** [comment]
make L-G-T-M work

**Comment by lunny** [comment]
Removed backport because the changes too big to cherry pick.

File: modules/templates/helper.go [hunk 12]
```diff
@@ -971,20 +972,35 @@ type remoteAddress struct {
 	Password string
 }
 
-func mirrorRemoteAddress(ctx context.Context, m repo_model.RemoteMirrorer) remoteAddress {
+func mirrorRemoteAddress(ctx context.Context, m *repo_model.Repository, remoteName string) remoteAddress {
 	a := remoteAddress{}
+	if !m.IsMirror {
+		return a
+	}
```
Comment (mohsek) [inline modules/templates/helper.go:979]: @lunny  I saw an issue here, the push mirrors URL are no longer displayed on the UI

image

I think we should return  empty remoteAddress when the repo  is a mirror not the opposite

``` go
	if m.IsMirror {
		return a
	}
```
