### PR TITLE
Fix bug when upload on web

### LINKED ISSUE #13611: remove upload: remove
When using the file upload function of gitea, an error occurred. How can I solve this? Going back to the warehouse page, you can see that the file upload was successful, but the upload cache file deletion failed. 
The error message is:
remove upload: remove C:/Program Files/gitea/data/tmp/uploads/a/d/ad727a50-7d9d-4ae4-bcef-25f4e58fd2d6: The process cannot access the file because it is being used by another process.

### PR DESCRIPTION
**Pull request by lunny**
Fix #13611

### CODE REVIEW

File: modules/repofiles/upload.go [hunk 1]
```diff
@@ -191,6 +189,7 @@ func UploadRepoFiles(repo *models.Repository, doer *models.User, opts *UploadRep
 				// Can't clean up the store, once uploaded there they're there.
 				return cleanUpAfterFailure(&infos, t, err)
 			}
+			file.Close()
```
Comment (kdumontnu) [inline modules/repofiles/upload.go]: Isn't this equivalent to `defer file.Close()` in line 184?

Comment (garfeng) [reply modules/repofiles/upload.go]: please refer to https://github.com/go-gitea/gitea/issues/13611

to see why we must use `file.Close() ` instead of `defer file.Close()`

@kdumontnu

Comment (jolheiser) [reply modules/repofiles/upload.go]: This could cause an issue if `file.Close` is called twice.  
https://golang.org/pkg/os/#File.Close

I agree this is needed, as defers in a loop are usually bad news. 
The defer should be removed in favor of this.

Comment (kdumontnu) [reply modules/repofiles/upload.go]: @garfeng I see. Didn't notice the for loop. 
@jolheiser Good call. Looks like `defer file.Close()` can be removed if `file.Close()` is added to the err catch above.

File: modules/repofiles/upload.go [hunk 2]
```diff
@@ -191,6 +189,7 @@ func UploadRepoFiles(repo *models.Repository, doer *models.User, opts *UploadRep
 				// Can't clean up the store, once uploaded there they're there.
 				return cleanUpAfterFailure(&infos, t, err)
```
Comment (6543) [inline modules/repofiles/upload.go]:
```suggestion
				file.Close()
				return cleanUpAfterFailure(&infos, t, err)
```
& rm L184

**Review by kdumontnu — APPROVED** [review]
👍

**Review by jolheiser — APPROVED** [review]

**Comment by kdumontnu** [comment]
CI looks like legitimate failure

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
Backports:
 * #15054
 * #15055
