### PR TITLE
Fix serving of raw wiki files other than .md

### LINKED ISSUE #4395: Pictures in wiki acting just like pictures in main project.git
Allow Picture in the WIKI #4376

No I did not mean to make it easier. I did indeed upload pictures to the wiki via git and referenced those pictures with MD in the wiki files. This resulted in a logon popup to be displayed while accessing that page. When moving the same image and md file to my main project.git directory I was not prompted for a logon.

### LINKED ISSUE #4690: Images in Wiki repo not showing in Gitea Wiki
- Gitea version (or commit ref): 1.5.0 & master built on 13 Aug 2018
- Git version: 2.18.0
- Operating system: Arch linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/bkahlerventer/wiki_test/wiki/Home
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Not much to describe.  Image is in main repository to view.  Image in wiki repository main folder, image subfolder, images subfolder, raw subfolder.  None of the images are displayed in the wiki.

## Screenshots
Not neccessary, view page on  https://try.gitea.io/bkahlerventer/wiki_test/wiki/Home

### PR DESCRIPTION
**Pull request by gabrielsimoes**
Closes #4690.
Closes #4395.

This is a step towards #574, but maybe a GUI could also be implemented.

Signed-off-by: Gabriel Silva Simões <simoes.sgabriel@gmail.com>

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by zeripath** [comment]
Is there any easy way you can write a test of this functionality? 

(I suspect you've got the same problem I have in #5787 for making tests.)

**Review by lunny — CHANGES_REQUESTED** [review]
The code includes some repeated lines. It maybes more clear?

**Review by kolaente — APPROVED** [review]

**Comment by gabrielsimoes** [comment]
Sorry for the force push, hope it didn't mess up anything. I simplified the code, @lunny, please check if that is ok for you. I feel like if I simplified it further things would get a little confused.

EDIT: I'll try working on a test.

**Comment by gabrielsimoes** [comment]
Added tests. Had to update macaron due to a bug that made `SetParams("*", "something")` not work.

File: models/wiki.go [hunk 1]
```diff
@@ -22,7 +22,7 @@ import (
 )
 
 var (
-	reservedWikiNames = []string{"_pages", "_new", "_edit"}
+	reservedWikiNames = []string{"_pages", "_new", "_edit", "raw"}
```
Comment (zeripath) [inline models/wiki.go:25]: Heya, why do we need to add `_raw` here?

Comment (zeripath) [reply models/wiki.go:25]: oh dear... it's not so much that raw but raw/*... hmm...

Comment (zeripath) [reply models/wiki.go:25]: It's sort of a shame to prevent calling something `raw` though. We've already banned `_edit` so `/raw/_edit` is unambiguous to mean edit. The issue is that delete is also not reserved - perhaps that needs to be `_delete` and then we could allow `raw`

**Review by zeripath — APPROVED** [review]

**Comment by gabrielsimoes** [comment]
@lunny, I think it is all set, except for the changes you requested.

**Review by lunny — APPROVED** [review]
