### PR TITLE
GetFeeds must always discard actions with dangling repo_id (#19598)

### LINKED ISSUE #19631: NPE in routers/web/feed/profile.go:37 on 1.16.7 following failed migration
Extract from a comment in #19613 

```
2022/05/05 20:06:26 ...s/graceful/server.go:61:NewServer() [I] Starting new Web server: tcp:0.0.0.0:3000 on PID: 16
2022/05/05 20:06:46 Started GET / for 10.###.###.###:0
2022/05/05 20:06:46 routers/web/base.go:130:1() [E] PANIC: runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:220 (0x457635)
/usr/local/go/src/runtime/signal_unix.go:818 (0x457605)
/go/src/code.gitea.io/gitea/routers/web/feed/profile.go:37 (0x1fbb59c)
/go/src/code.gitea.io/gitea/routers/web/user/home.go:134 (0x1fd20d2)
/go/src/code.gitea.io/gitea/routers/web/home.go:41 (0x2034770)
/go/src/code.gitea.io/gitea/modules/web/route.go:74 (0x1e47d44)
/usr/local/go/src/net/http/server.go:2084 (0x7ac6ce)
/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 (0x1656dd5)
/usr/local/go/src/net/http/server.go:2084 (0x7ac6ce)
...
```

The migration consists of pushing cloned repo's from GitHub into Gitea, the repo's are created using the API and data transferred using Git https.

Now that I have migrated a few more repo's, the 500 error on the landing page is gone. Presumably because whatever was causing it is not longer shown on it.

_Originally posted by @number42net in https://github.com/go-gitea/gitea/issues/19613#issuecomment-1119134431_

### PR DESCRIPTION
**Pull request by singuliere**
Backport of https://github.com/go-gitea/gitea/pull/19598

```
Co-authored-by: Loïc Dachary <loic@dachary.org>
(cherry picked from commit b536b65189319544939da9b6537919a4fc838d71)

Conflicts:
        models/action_test.go
	  The GetFeeds function does not have a Context argument in 1.16.
	models/action.go
	  The SQL statement is essentially the same in 1.16 but
	  structured differently. The Join() was copied and the
   	  created_unix field prefixed with `action`.
	models/action_list.go
	  in 1.16 the loadRepoOwner method did not exist and
	  it was done in the RetrieveFeeds method of web/feed/profile.go.
          The safeguard to skip when act.Repo == nil was moved there.
```

Fix #19631

### CODE REVIEW

File: routers/web/feed/profile.go [hunk 1]
```diff
@@ -34,6 +34,9 @@ func RetrieveFeeds(ctx *context.Context, options models.GetFeedsOptions) []*mode
 	}
 
 	for _, act := range actions {
+		if act.Repo == nil {
+			continue
+		}
```
Comment (zeripath) [inline routers/web/feed/profile.go:39]: This could just push the NPE further downstream if the downstream function still assumes that the repo is extant.

Have we checked the downstream functions here? Would it make more sense to censor and remove actions that have non-extant repos?

**Review by zeripath — APPROVED** [review]

File: routers/web/feed/profile.go (hunk 1 above)
Comment (zeripath) [reply routers/web/feed/profile.go:39]: Hmm it looks like this should be fine as these cases should not occur.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@singuliere please update branch

**Comment by singuliere** [comment]
make l-g-t-m work
