### PR TITLE
Various Merge Base fixes

### LINKED ISSUE #10766: [Bug] Merged PRs have their commits and files changed metadata 'zeroed'... sometimes.
- Gitea version (or commit ref): v1.11.3
- Git version: 2.24.1
- Operating system: Ubuntu 18.04 (used as a Docker host for Gitea)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: N/A

## Description
As of recent (within the last month I'd estimate), many PRs have their commits and files changed counters zeroed out after merging. This happens most of the time _but weirdly not always_ on my instance now. Deleting the branch afterwards doesn't make seem to make a difference if that makes a difference.

I'm not sure how a lot of the internal Git plumbing works for Gitea so I haven't managed to take a look at the code directly. I know that #10618 seemed to be somewhat relevant - and the linked PR example in there does indeed show the behaviour below! I'm confused as to why this is shown for me as both branches definitely still exist.

## Screenshots
image

### PR DESCRIPTION
**Pull request by zeripath**
* Allow PRs with deleted base branches to still show diff
* Fix broken merge base migration in v128 for merged PR.  Related to #10766

### CODE REVIEW

File: models/migrations/v132.go [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+	for {
+		prs := make([]PullRequest, 0, 50)
+		if err := x.Limit(limit, i).Asc("id").Where("has_merged = ?", true).Find(&prs); err != nil {
+			return fmt.Errorf("Find: %v", err)
+		}
+		if len(prs) == 0 {
+			break
+		}
+
+		i += 50
```
Comment (lunny) [inline models/migrations/v132.go]: i += len(prs)

**Review by lunny — DISMISSED** [review]

**Comment by lunny** [comment]
It's better to add some tests.

File: models/migrations/v132.go (hunk 1 above)
Comment (bagasme) [reply models/migrations/v132.go]: @lunny what did you mean?

Comment (techknowlogick) [reply models/migrations/v132.go]: as it may not be 50 that is added to `i` each time, for example if there are only 48 PRs in system, then I shouldn't add an additional 50 to count.

Comment (zeripath) [reply models/migrations/v132.go]: Then the length of the next prs will equal 0 either way.

i is not used in the loop

Comment (zeripath) [reply models/migrations/v132.go]: I mean I'll change it but an SQL compliant DB will always return the full 50 results if it can. If it returns 48 then the that's the end of the results - it doesn't matter if you ask for the next 50 from that point, the point 2 places after or 2000 places after it.

**Comment by zeripath** [comment]
Tests? Where can we put them? I'd love it if we had tests for migrations but we don't have infrastructure for them. I'm happy to begin doing that but it's going to be a huge PR.

**Comment by lunny** [comment]
We can add a function on `modules/git` named `CalculateMergebase` And add some tests on that package.

**Comment by zeripath** [comment]
This function should only be used in the migration otherwise we should simply be storing the actual MergeBase used for PRs. There's no reason to have to recalculate it.

Ideally this fixed migration would only run on PRs that were merged before v128 was run.

**Review by lafriks — APPROVED** [review]

File: models/migrations/v132.go [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+
+			gitRefName := fmt.Sprintf("refs/pull/%d/head", pr.Index)
+
+			parentsString, err := git.NewCommand("rev-list", "--parents", "-n", "1", pr.MergedCommitID).RunInDir(repoPath)
+			if err != nil {
+				log.Error("Unable to get parents for merged PR ID %d, Index %d in %s/%s. Error: %v", pr.ID, pr.Index, baseRepo.OwnerName, baseRepo.Name, err)
+				continue
+			}
+			parents := strings.Split(strings.TrimSpace(parentsString), " ")
+			if len(parents) < 3 {
```
Comment (guillep2k) [inline models/migrations/v132.go]: I think we should consider handling PRs with only one merge base at this point in case a previous version of 128.go would have left some wrong info and one of the bases disappeared in the meantime. But maybe I'm talking nonsense.

Comment (zeripath) [reply models/migrations/v132.go]: 128 has always been correct if you have a single parent.

Comment (zeripath) [reply models/migrations/v132.go]: It's about the parent of the merge commit.

If the commit A has two parents B and C and you ask git to provide the mergebase between A^ i.e. the parent of A and B it will simply reply B, instead of finding the mergebase between B & C.

In the case where there is one parent the calculated mergebase should be correct.

**Review by mrsdizzie — APPROVED** [review]

File: models/migrations/v132.go (hunk 2 above)
Comment (guillep2k) [reply models/migrations/v132.go]: I meant that there may have been two parents when 128.go was run (so 128.go could have produced wrong results), but one of the parents is deleted after the fact. But I don't understand this issue very well, so I could be taking it all wrong.

Comment (zeripath) [reply models/migrations/v132.go]: Then the merge commit SHA ID would change. These are in git... You can't get rid of the parents without breaking the entire Merkle tree.

**Comment by zeripath** [comment]
@lunny needs your review

**Comment by lafriks** [comment]
Please resolve conflicts

File: models/migrations/v132.go (hunk 2 above)
Comment (guillep2k) [reply models/migrations/v132.go]: Oh, I see, this doesn't care about references (i.e. branches, tags, etc.), it only cares about actual commit IDs. Sorry. 😄

**Comment by zeripath** [comment]
conflicts resolved.

**Comment by lafriks** [comment]
not anymore :P

**Comment by zeripath** [comment]
eurgh we need a better way of doing migrations!

**Comment by zeripath** [comment]
conflicts resolved again ... :stuck_out_tongue:

File: models/migrations/v132.go (hunk 2 above)
Comment (zeripath) [reply models/migrations/v132.go]: no prob

**Comment by lafriks** [comment]
@lunny need your approval

**Comment by lafriks** [comment]
Just tested migration v134.go on copy of my production server and it does fix broken PR's that I had

**Comment by lafriks** [comment]
Please send backport
