### PR TITLE
Fix mermaid-related bugs

### LINKED ISSUE #21427: Mermaid code blocks in markdown showing error
### Description

When I create a mermaid code block in a markdown file, error banners are shown on each character input.
Also, in the preview tab, the height of the mermaid diagram is broken.

This is working properly on v1.17 but breaking on dev.

Stacktrace:
```python
22:32:03.497 Uncaught Error: Language id "vs.editor.nullLanguage" is not configured nor known

F@https://try.gitea.io/assets/js/monaco.943e8892.js:135:7465
getLanguageConfiguration@https://try.gitea.io/assets/js/monaco.943e8892.js:135:7221
getLanguageConfiguration@https://try.gitea.io/assets/js/monaco.943e8892.js:154:21355
getWordAtPosition@https://try.gitea.io/assets/js/monaco.943e8892.js:154:21664
getWordAtPosition@https://try.gitea.io/assets/js/monaco.943e8892.js:163:10576
Ue@https://try.gitea.io/assets/js/monaco.943e8892.js:251:5156
./node_modules/monaco-editor/esm/vs/editor/contrib/inlineCompletions/browser/ghostText.contribution.js/rt/<@https://try.gitea.io/assets/js/monaco.943e8892.js:251:3900
./node_modules/monaco-editor/esm/vs/editor/contrib/inlineCompletions/browser/ghostText.contribution.js/X/<@https://try.gitea.io/assets/js/monaco.943e8892.js:250:6704
X@https://try.gitea.io/assets/js/monaco.943e8892.js:250:6467
rt@https://try.gitea.io/assets/js/monaco.943e8892.js:251:3856
./node_modules/monaco-editor/esm/vs/editor/contrib/inlineCompletions/browser/ghostText.contribution.js/update/</Kt</<@https://try.gitea.io/assets/js/monaco.943e8892.js:251:525
./node_modules/monaco-editor/esm/vs/editor/contrib/inlineCompletions/browser/ghostText.contribution.js/X/<@https://try.gitea.io/assets/js/monaco.943e8892.js:250:6704
X@https://try.gitea.io/assets/js/monaco.943e8892.js:250:6467
./node_modules/monaco-editor/esm/vs/editor/contrib/inlineCompletions/browser/ghostText.contribution.js/update/</Kt<@https://try.gitea.io/assets/js/monaco.943e8892.js:251:473
T@https://try.gitea.io/assets/js/monaco.943e8892.js:28:79091
./node_modules/monaco-editor/esm/vs/editor/contrib/inlineCompletions/browser/ghostText.contribution.js/update/<@https://try.gitea.io/assets/js/monaco.943e8892.js:251:467
./node_modules/monaco-editor/esm/vs/editor/contrib/inlineCompletions/browser/ghostText.contribution.js/X/<@https://try.gitea.io/assets/js/monaco.943e8892.js:250:6704
X@https://try.gitea.io/assets/js/monaco.943e8892.js:250:6467
update@https://try.gitea.io/assets/js/monaco.943e8892.js:251:345
./node_modules/monaco-editor/esm/vs/editor/contrib/inlineCompletions/browser/ghostText.contribution.js/ve/this.updateSoon<@https://try.gitea.io/assets/js/monaco.943e8892.js:250:10076
doRun@https://try.gitea.io/assets/js/monaco.943e8892.js:28:83100
onTimeout@https://try.gitea.io/assets/js/monaco.943e8892.js:28:83040
    unexpectedErrorHandler https://try.gitea.io/assets/js/monaco.943e8892.js:30
monaco.943e8892.js:30:12
```

### Gitea Version

dev

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

image
image
image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Docker Image: `gitea/gitea:dev`

### Database

SQLite

### PR DESCRIPTION
**Pull request by silverwind**
1. Apparently, mermaid 9.1.7 no longer sets a `height` attribute on the SVG it produces. Workaround by extracting height from `viewBox` instead.
2. Filter out unresolvable Monaco errors from error display.

Fixes: https://github.com/go-gitea/gitea/issues/21427
Ref: https://github.com/microsoft/monaco-editor/issues/2962
Ref: https://github.com/mermaid-js/mermaid/issues/3659

### CODE REVIEW

File: web_src/js/bootstrap.js [hunk 1]
```diff
@@ -7,9 +7,18 @@ import {joinPaths} from './utils.js';
 // This file must be imported before any lazy-loading is being attempted.
 __webpack_public_path__ = joinPaths(window?.config?.assetUrlPrefix ?? '/', '/');
 
+const ignoreErrors = [
+  /vs\.editor\.nullLanguage/, // https://github.com/microsoft/monaco-editor/issues/2962
+];
+
```
Comment (wxiaoguang) [inline web_src/js/bootstrap.js]: This block could be put into `showGlobalErrorMessage`.

Because usually (most time) there is no error, then no need to prepare this array for every page loading, slightly saves browser CPU

**Review by zeripath — APPROVED** [review]
As per @wxiaoguang but otherwise lgtm

File: web_src/js/bootstrap.js (hunk 1 above)
Comment (silverwind) [reply web_src/js/bootstrap.js]: adjusted

File: web_src/js/bootstrap.js [hunk 2]
```diff
@@ -10,6 +10,7 @@ __webpack_public_path__ = joinPaths(window?.config?.assetUrlPrefix ?? '/', '/');
 export function showGlobalErrorMessage(msg) {
   const pageContent = document.querySelector('.page-content');
   if (!pageContent) return;
+
```
Comment (wxiaoguang) [inline web_src/js/bootstrap.js]:
```suggestion
```

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
I just found that `processWindowErrorEvent` is the better place to handle such error 😁 , and the error message is clear so it could be tested with a substring directly.
