### PR TITLE
Fix missing commit status in PR which from forked repo

### LINKED ISSUE #23347: Missing commit status in the PR that comes from forked repo
### Description

When I push a commit to the fork repository, the `Actions` works and display success in the commits list.
But when I create a PR to upstream reopsitory, the status of the commit miss both in the PRs list and the commits list of the PR, although the `Actions` looks work well.

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

In upstream Repo, missing commit status:
image

image

But In fork Repo, display commit status:
image

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

build

### Database

PostgreSQL

### PR DESCRIPTION
**Pull request by sillyguodong**
close: #23347

### Reference and Inference
According to Github REST API [doc](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#list-commit-statuses-for-a-reference):
 1. The `Drone CI` that can create some commit status by [API](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status) is enabled in `go-gitea/gitea`. So I tried to call the API to get a commit status list of a PR which is commited to upstream repo(`go-gitea/gitea`).  As a result, the API returned a array of commit status.
image
 2.  Then I tried to call the API to get commit status list of the reference which of the `SHA` is the same as step 1 in the repo which is forked from `go-gitea/gitea`. But I got a empty array.
image

So, I believe it that：
1. The commit status is not shared between upstream repo and forked repo.
2. The coomit status is bound to a repo that performs actions. (Gitea's logic is the same)

### Cause
During debugging, I found it that commit status are not stored in the DB as expected.
So, I located the following code:
https://github.com/go-gitea/gitea/blob/8cadd51bf295e6ff36ac36efed68cc5de34c9382/services/actions/commit_status.go#L18-L26
When I create a PR, the type of `event` is `pull request`, not `push`. So the code return function directly.

### Screenshot
image
image
image

### Other 
In this PR,  I also fix the problem of missing icon which represents running in PRs list. 
image
image

### CODE REVIEW

File: services/actions/commit_status.go [hunk 1]
```diff
@@ -21,35 +21,54 @@ func CreateCommitStatus(ctx context.Context, job *actions_model.ActionRunJob) er
 	}
 
 	run := job.Run
-	if run.Event != webhook_module.HookEventPush {
+	if run.Event != webhook_module.HookEventPush && run.Event != webhook_module.HookEventPullRequest {
```
Comment (lunny) [inline services/actions/commit_status.go]: It's better to use switch

Comment (sillyguodong) [reply services/actions/commit_status.go]: got it

**Review by a1012112796 — APPROVED** [review]

**Review by wolfogre — APPROVED** [review]

**Comment by jolheiser** [comment]
🎺 🤖
