### PR TITLE
Fix profile render when the README.md size is larger than 1024 bytes

### LINKED ISSUE #25094: It's inconsistent between README rendering and user profile rendering
### Description

image
image

### Gitea Version

v1.20+

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

./gitea web

### Database

MySQL

### PR DESCRIPTION
**Pull request by yp05327**
Fixes https://github.com/go-gitea/gitea/issues/25094

`GetBlobContent` will only get the first 1024 bytes, if the README.md size is larger than 1024 bytes,
We can not render the rest of them.
After this fix, we should provide the limited size to read when call `GetBlobContent`.

After:
image

### CODE REVIEW

**Comment by silverwind** [comment]
I think we should instead add a `limit` parameter to `GetBlobContent` that defaults to `0` and is passed as `1024` for the existing use cases of it (if it makes sense there). No need to duplicate and leave this deceiving function in-place imho.

**Comment by silverwind** [comment]
Are we certain we can change the previous use cases from 1024 to 0? I imagine this might have been done for performance reasons in cases where the exact content was not needed.

File: services/repository/files/content.go [hunk 1]
```diff
@@ -203,7 +203,7 @@ func GetContents(ctx context.Context, repo *repo_model.Repository, treePath, ref
 	} else if entry.IsLink() {
 		contentsResponse.Type = string(ContentTypeLink)
 		// The target of a symlink file is the content of the file
-		targetFromContent, err := entry.Blob().GetBlobContent()
+		targetFromContent, err := entry.Blob().GetBlobContent(1024)
```
Comment (silverwind) [inline services/repository/files/content.go:206]: Should investigate closer what this does, but does not have to be in this PR. It might be that this is another undiscovered bug and it should actually use `0` here.

**Review by silverwind — APPROVED** [review]

File: routers/web/user/profile.go [hunk 2]
```diff
@@ -107,7 +107,7 @@ func Profile(ctx *context.Context) {
 		}
 		blob, err := commit.GetBlobByPath("README.md")
 		if err == nil {
-			bytes, err := blob.GetBlobContent()
+			bytes, err := blob.GetBlobContent(0)
```
Comment (wxiaoguang) [inline routers/web/user/profile.go]: It should respect something like `MAX_DISPLAY_FILE_SIZE`

File: modules/git/blob.go [hunk 3]
```diff
@@ -21,15 +21,22 @@ func (b *Blob) Name() string {
...
 	if err != nil {
 		return "", err
 	}
 	defer dataRc.Close()
-	buf := make([]byte, 1024)
-	n, _ := util.ReadAtMost(dataRc, buf)
-	buf = buf[:n]
+
+	var buf []byte
+	if limit == 0 {
```
Comment (wxiaoguang) [inline modules/git/blob.go]: Why it needs to support `ReadAll`? If attackers upload some large files, it could DoS the server, make it OOM.

**Review by lunny — APPROVED** [review]

**Comment by wxiaoguang** [comment]
Sorry I didn't mean make `GetBlobContent` use `MaxDisplayFileSize`, but I mean `GetBlobContent(MaxDisplayFileSize)`

Let callers decide how much data they would like to read at most.

**Review by wxiaoguang — CHANGES_REQUESTED** [review]
Need more fine tunes

File: services/repository/files/content.go [hunk 4]
```diff
@@ -203,7 +203,7 @@ func GetContents(ctx context.Context, repo *repo_model.Repository, treePath, ref
 	} else if entry.IsLink() {
 		contentsResponse.Type = string(ContentTypeLink)
 		// The target of a symlink file is the content of the file
-		targetFromContent, err := entry.Blob().GetBlobContent()
+		targetFromContent, err := entry.Blob().GetBlobContent(setting.UI.MaxDisplayFileSize)
```
Comment (wxiaoguang) [inline services/repository/files/content.go]:
```suggestion
		targetFromContent, err := entry.Blob().GetBlobContent(1024)
```

Here it only reads a link name, I think it doesn't need to be that large. 1024 or 4096 or other either is fine, while 1024 is large enough (I do not think GItea could render a path on UI that long .....)

File: modules/git/blob.go [hunk 5]
```diff
@@ -21,15 +20,17 @@ func (b *Blob) Name() string {
...
+	if limit <= 0 {
+		return "", nil
+	}
 	dataRc, err := b.DataAsync()
 	if err != nil {
 		return "", err
 	}
 	defer dataRc.Close()
-	buf := make([]byte, setting.UI.MaxDisplayFileSize)
+	buf := make([]byte, limit)
```
Comment (wxiaoguang) [inline modules/git/blob.go]: Here is a nit: since default MaxDisplayFileSize is 8M, so each `GetBlobContent` allocates 8M memory, but in most cases it only reads hundreds or thousands of bytes. It wastes memory. But it can be fixed later.

**Review by wxiaoguang — APPROVED** [review]

File: modules/git/blob.go (hunk 5 above)
Comment (yp05327) [reply modules/git/blob.go]:
``` golang
size := b.Size()
if limit > size  {
  limit = size
}
buf := make([]byte, limit)
```
Is this better?

Comment (wxiaoguang) [reply modules/git/blob.go]: Done in 0e2e0d8382123728fd8dd99e4e71b7a88f5f259e (force pushed with lint fix)
