### PR TITLE
Do not show monaco JS errors

### LINKED ISSUE #30861: Editing text in Safari/macOS gives JavaScript error: undefined is not an object (evaluating 'navigator.clipboard write')
### Description

On typing, the web page displays the above JavaScript clipboard error with eg `(http://rad.gitea:12080/assets/js/monaco.14c11225.js @ 415:16905)`.

This appears to relate to the update of **monaco-editor** from 0.44.0 to 0.45.0 in ce55a74374aa1fe07cfb79ceeb8554aa7a2abce2

I suspect this only occurs when serving **over http** rather than https as the error does not occur on https://try.gitea.io/ 

Presumably monaco-editor is now using the async clipboard API. See https://webkit.org/blog/10855/async-clipboard-api/

### Gitea Version

1.22.0-rc1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

Screenshot 2024-05-05 at 4 47 14 PM copy

### Git Version

2.40.1

### Operating System

Ubuntu 23.10

### How are you running Gitea?

Dockerised on Proxmox 8.2

### Database

MySQL/MariaDB

### PR DESCRIPTION
**Pull request by wxiaoguang**
Fix #30861

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: web_src/js/bootstrap.js [hunk 1]
```diff
@@ -6,13 +6,20 @@
...
 
-export function showGlobalErrorMessage(msg) {
-  const pageContent = document.querySelector('.page-content');
-  if (!pageContent) return;
+function shouldIgnoreError(err) {
+  const ignorePatterns = [
+    '/assets/js/monaco.', // https://github.com/go-gitea/gitea/issues/30861 , https://github.com/microsoft/monaco-editor/issues/4496
+  ];
+  for (const pattern of ignorePatterns) {
+    if (err.stack.includes(pattern)) return true;
```
Comment (KN4CK3R) [inline web_src/js/bootstrap.js]: In line 65 `stack?.` is used. Should we have the null check here too?

Comment (wxiaoguang) [reply web_src/js/bootstrap.js]: According to MDN, all browsers support it (we have checked `if (err instanceof Error)` ahead)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack#browser_compatibility

To keep old behavior, we can add the `?` back.


```suggestion
    if (err.stack?.includes(pattern)) return true;
```

**Review by KN4CK3R — APPROVED** [review]
