### PR TITLE
Report structurally invalid workflows to users

### LINKED ISSUE #37115: Some invalid workflow are not reported as invalid
### Description

I noticed that since #23275, Gitea have been able to report invalid workflows to user. However, I've encountered issue with an ill-formed workflow file like this:

```yaml
Name: invlalid workflow
jobs:
  test:
    steps:
      - run: |

          echo "Hello."
```

This might be a valid yaml (I tested on several online yaml validator), and Gitea is not reporting error for it. But in fact Gitea would have trouble processing that blank line right after `- run: |`.

```
Apr 05 18:47:53 machine_name gitea[70048]: 2026/04/05 18:47:53 .../actions/notifier_helper.go:364:handleWorkflows() [E] jobparser.Parse: SetJob: yaml: line 42: did not find expected key
```

The log is from a self-host instance and from a different workflow file, so the line number is unrelated.

The error message `did not find expected key` can also be confusing, until one realize it's a sign of yaml parsing error.

Since this workflow has a `on: { workflow_dispatch: }`, we can even click to run it, but will only got a 500 error.

---

I've create a repo containing two files on gitea.com:
https://gitea.com/kLiHz/test-invalid-workflow/src/branch/main/.gitea/workflows

[another.yml](https://gitea.com/kLiHz/test-invalid-workflow/src/branch/main/.gitea/workflows/another.yml) is actually an invalid yaml which has wrong indentation, and Gitea is reporting that error. (though it may take some time for people to realize what that error mean)

[invalid.yml](https://gitea.com/kLiHz/test-invalid-workflow/src/branch/main/.gitea/workflows/invalid.yml) actually seems to be an valid yaml, but Gitea doe not seem to be telling me about that.

### Gitea Version

1.25.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

.

### Database

None

### PR DESCRIPTION
**Pull request by bircni**
`model.ReadWorkflow` succeeds for YAML that is syntactically valid but fails deeper parsing in `jobparser.Parse` (e.g. blank lines inside `run: |` blocks cause a SetJob round-trip error). Add `ValidateWorkflowContent` which runs the full `jobparser.Parse` to catch these cases, and use it in the file view, the actions workflow list, and the workflow detection loop so users see the error instead of silently getting a 500 or a dropped workflow.

Fixes #37115

### CODE REVIEW

**Review by lunny — APPROVED** [review]

File: modules/actions/workflows.go [hunk 1]
```diff
@@ -129,6 +136,9 @@ func DetectWorkflows(
 
 		// one workflow may have multiple events
 		events, err := GetEventsFromContent(content)
+		if err == nil {
+			err = ValidateWorkflowContent(content)
+		}
```
Comment (wxiaoguang) [inline modules/actions/workflows.go]: Why? `GetEventsFromContent` already does something.

image

File: routers/web/repo/actions/actions.go
Comment (Zettat123) [inline routers/web/repo/actions/actions.go:322]:
```suggestion
			}
			if err := actions.ValidateWorkflowContent(job.WorkflowPayload); err != nil {
				runErrors[run.ID] = ctx.Locale.TrString("actions.runs.invalid_workflow_helper", err.Error())
				break
			}
```

Comment (Zettat123) [reply routers/web/repo/actions/actions.go:322]: Can we use `ValidateWorkflowContent` to check `job.WorkflowPayload` ?

Comment (bircni) [reply routers/web/repo/actions/actions.go:322]: done

**Review by Zettat123 — APPROVED** [review]

**Review by wxiaoguang — APPROVED** [review]

**Comment by wxiaoguang** [comment]
By the way, removed the `(#issue)` from title, otherwise the backport message would be too complex: `title (#issue) (#origin-pr) (#backport-pr)`
