### PR TITLE
Increase size of the language column in language_stat

### LINKED ISSUE #12379: Language column in language_stat table is too small (needs to be at least 34)
- Gitea version (or commit ref): 1.12.3
- Git version: 2.25.1
- Operating system: Linux nuc-mini-server 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x]  Not relevant
- Log gist:

```
2020/07/31 11:33:25 ...m.io/xorm/core/tx.go:157:QueryContext() [I] [SQL] INSERT INTO "language_stat" ("repo_id","commit_id","is_primary","language","size","created_unix") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id" [786 dd0f55d6cee3bcf7d483522684933dc73f6b1831 true Glyph Bitmap Distribution Format 141557 1596188005] - 259.548µs
2020/07/31 11:33:25 ...o/xorm/session_tx.go:46:Rollback() [I] [SQL] ROLL BACK [] - 133.808µs
2020/07/30 19:20:46 ...dexer/stats/queue.go:24:handle() [E] stats queue idexer.Index(786) failed: pq: Wert z                                                                                               u lang für Typ character varying(30)
2020/07/31 11:33:25 ...dexer/stats/queue.go:24:handle() [E] stats queue idexer.Index(786) failed: pq: Wert zu lang für Typ character varying(30)
```

Enry v2 can detect languages with names longer than the currently provided maximum of 30 characters.

A quick look at Enry's source code demonstrates that the current maximum length for a detected language is 34 characters (see below code).

We therefore need to provide a migration to increase the size of this column or consider forcibly shortening Enry's detected language.

---

```go
package main

import (
	"fmt"

	"github.com/go-enry/go-enry/v2/data"
)

func main() {
	maxLangLen := 0
	maxLang := ""
	for lang := range data.ExtensionsByLanguage {
		if len(lang) > maxLangLen {
			maxLang = lang
			maxLangLen = len(lang)
		}
	}
	for _, vals := range data.LanguagesByExtension {
		for _, lang := range vals {
			if len(lang) > maxLangLen {
				maxLang = lang
				maxLangLen = len(lang)
			}
		}
	}
	for lang := range data.LanguagesLogProbabilities {
		if len(lang) > maxLangLen {
			maxLang = lang
			maxLangLen = len(lang)
		}
	}
	fmt.Println("Max", maxLangLen, maxLang)
}
```

### LINKED ISSUE #13013: Gitea crash when indexer is run (database error, data too long for column language)
- Gitea version (or commit ref): Gitea version 1.12.5 built with GNU Make 4.1, go1.14.9 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.28.0
- Operating system: Ubuntu 18.04.5 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
```
./gitea.log:2562:2020/10/02 09:12:07 ...dexer/stats/queue.go:24:handle() [E] stats queue indexer.Index(24) failed: Error 1406: Data too long for column 'language' at row 1
```

## Description
I've upgraded Gitea today the usual way by stopping the service, replacing binary and starting the service again. (From 1.12.4 to 1.12.5)

Gitea crashes when indexer runs. I have no idea why this happened. Maybe failed database migration on my end? That's the only relevant log I could find above.

I've disabled repo indexer and things started working again.

### PR DESCRIPTION
**Pull request by zeripath**
In #12379 it was discovered that enry v2 has a maximum language length
of 34 characters which is larger than the 30 previously provided.

This PR updates the language column to 50.

Fix #12379
Fix #13013

Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by zeripath** [comment]
Contains #12395

File: models/migrations/v145.go [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+
+package migrations
+
+import (
+	"code.gitea.io/gitea/modules/timeutil"
+	"xorm.io/xorm"
+)
+
+func increaseLanguageField(x *xorm.Engine) error {
+	// THIS MUST BE THE FULL DEFINITION FOR recreateTable TO WORK CORRECTLY
```
Comment (silverwind) [inline models/migrations/v145.go]: Does it really need to recreate?

Can't we do the equivalent of `alter table <table> alter column <column> varchar(50)`?

Comment (zeripath) [reply models/migrations/v145.go]: If I could have made that work I would have.

**Comment by zeripath** [comment]
So actually thinking on, because sqlite doesn't need to change schema - varchar is mapped to text -  I think we might be able to get away with just using ALTER TABLE in this case. 

I'll keep this code though and add a doctor command that will allow you to recreate tables from the schema - that will finally allow us to be able to get rid of the weird warning messages about defaults having changed.

File: models/migrations/v145.go (hunk 1 above)
Comment (zeripath) [reply models/migrations/v145.go]: OK because we don't have to change the type of sqlite's column so we don't have to deal with its constraint changes, and because we don't have to deal with constraint changes in general we can simplify a lot.

File: models/migrations/v102.go [hunk 2]
```diff
@@ -11,5 +11,8 @@ import (
 func dropColumnHeadUserNameOnPullRequest(x *xorm.Engine) error {
 	sess := x.NewSession()
 	defer sess.Close()
-	return dropTableColumns(sess, "pull_request", "head_user_name")
+	if err := dropTableColumns(sess, "pull_request", "head_user_name"); err != nil {
```
Comment (lunny) [inline models/migrations/v102.go]: You have to add `sess.Begin` if you add `sess.Commit`.

**Review by lunny — CHANGES_REQUESTED** [review]

File: models/migrations/v102.go (hunk 2 above)
Comment (zeripath) [reply models/migrations/v102.go]: This was an irrelevant commit - so I've removed it - it belongs in a different PR where I've fixed the issue.

**Comment by zeripath** [comment]
Finally I think I've solved (again) all the issues with the different dialects.

**Review by lafriks — APPROVED** [review]
Would be nice if this code could be moved to function like rename column but otherwise looks good

**Comment by zeripath** [comment]
@lafriks unfortunately a general solution is not very easy at all. In particular SQLite poses a particular problem here. 

SQLite doesn't have a mechanism for changing the type of a column and you can't create a column with a unique not null constraint on an already existing table. So you're limited to copying the table and adding the column. 

In reality the simplest thing to do is to recreate the table in its entirety from bean definition - I've provided that as another PR.

A general method that keeps the previous columns would be possible but I suspect that it may not be worth it.

File: models/migrations/v145.go [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+// Use of this source code is governed by a MIT-style
+// license that can be found in the LICENSE file.
+
+package migrations
+
+import (
+	"fmt"
+
+	"code.gitea.io/gitea/modules/setting"
+	"xorm.io/xorm"
```
Comment (lunny) [inline models/migrations/v145.go:12]: blank line.

**Comment by lunny** [comment]
Otherwise LGTM

**Review by lunny — APPROVED** [review]

File: models/migrations/v145.go (hunk 3 above)
Comment (zeripath) [reply models/migrations/v145.go:12]:
```suggestion

	"xorm.io/xorm"
```

**Comment by zeripath** [comment]
make lg-tm work

**Comment by silverwind** [comment]
Hmm it seems this migration is giving me some against MariaDB:

```
routers/init.go:71:initDBEngine() [I] ORM engine initialization attempt #3/10...
...rm/session_schema.go:25:Ping() [I] PING DATABASE mysql
...ations/migrations.go:310:Migrate() [I] Migration[145]: Increase Language field to 50 in LanguageStats
routers/init.go:77:initDBEngine() [E] ORM engine initialization attempt #3/10 failed. Error: migrate: do migrate: Error 1062: Duplicate entry 'JavaScript' for key 'UQE_language_stat_s'
routers/init.go:78:initDBEngine() [I] Backing off for 3 seconds
```

```
mysql  Ver 15.1 Distrib 10.4.13-MariaDB, for Linux (x86_64) using readline 5.1
```
