### PR TITLE
Fix unittest and repo create bug

### LINKED ISSUE #33060: Cannot select "Initialize Repository" when creating a repo
### Description

Cannot select "Initialize Repository"

image

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

https://demo.gitea.com/

### Database

None

### PR DESCRIPTION
**Pull request by wxiaoguang**
1. `StatDir` was not right, fix the FIXME
2. Clarify the test cases for `IsUsableRepoName`
3. Fix regression bug in `repo-new.ts`

Fix #33060

### CODE REVIEW

File: modules/repository/init.go [hunk 1]
```diff
@@ -81,7 +81,7 @@ func LoadRepoConfig() error {
 		if isDir, err := util.IsDir(customPath); err != nil {
 			return fmt.Errorf("failed to check custom %s dir: %w", t, err)
 		} else if isDir {
-			if typeFiles[i].custom, err = util.StatDir(customPath); err != nil {
+			if typeFiles[i].custom, err = util.ListDirRecursively(customPath, &util.ListDirOptions{SkipCommonHiddenNames: true}); err != nil {
```
Comment (wxiaoguang) [inline modules/repository/init.go:84]: Here is the old behavior: "includeDir=false, skipCommonName=true"

**Review by Zettat123 — APPROVED** [review]

**Review by delvh — APPROVED** [review]
