### PR TITLE
fix: /repos/{owner}/{repo}/actions/{runs,jobs} requiring owner permissions

### LINKED ISSUE #36268: GET /repos/{owner}/{repo}/actions/{runs,jobs} requires more than just read permissions
### Description

Hello,

#33964 introduced multiple new APIs for interacting with actions, but I think the permissions checks for actions/jobs and actions/runs is too tight.

They currently requires the caller to be the owner of the repository due to these API being declared via `addActionsRoutes` that either `reqOwner()` or `reqOrgOwnership()` which seems logic for the other much more sensitive routes in this function, but for `/runs` and `/jobs`, I think read permission is enough.

This is also not matching github requirements for this endpoint: "Anyone with read access to the repository can use this endpoint." (https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-repository)

The code in question:
https://github.com/go-gitea/gitea/blob/17715693005678e3145c19e95b0282bc2bea0853/routers/api/v1/api.go#L930

### Gitea Version

v1.25.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Self hosted

### Database

None

### PR DESCRIPTION
**Pull request by OptionalValue**
Hi,

This PR fixes the issue reported [here](https://github.com/go-gitea/gitea/issues/36268). 

The REST endpoints:
`/repos/{owner}/{repo}/actions/runs`
`/repos/{owner}/{repo}/actions/jobs`

currently require repository/organisation owner permissions, even though in GitHub they only need simple "read" permissions on the repo.
In the web interface this is implemented correctly, where anyone with "read" permissions can see the list of action runs.

---
Resolves #36268

### CODE REVIEW

**Comment by wxiaoguang** [comment]
Check how `addActionsRoutes` is used. You can't simply add `reqRepoReader` here. There is no "repo" for "org"

Maybe you need a new argument for addActionsRoutes

**Comment by OptionalValue** [comment]
@wxiaoguang Thanks for the quick reply!
Did not notice that, so thank you.
I've added a new param `readReqChecker` to `addActionsRoutes` 
It now is called with:
* `reqRepoReader(unit.TypeActions)` for repositories
* `reqOrgMembership()` for organisations

File: routers/api/v1/api.go [hunk 1]
```diff
@@ -895,34 +895,35 @@ func Routes() *web.Router {
 
 	addActionsRoutes := func(
 		m *web.Router,
-		reqChecker func(ctx *context.APIContext),
+		readReqChecker func(ctx *context.APIContext),
+		ownerReqChecker func(ctx *context.APIContext),
```
Comment (wxiaoguang) [inline routers/api/v1/api.go]: I think the names should be `reqOwnerCheck` and `reqReaderCheck` to match other name patterns ..... 🤣

Comment (OptionalValue) [reply routers/api/v1/api.go]: Sure, I've renamed the params.

**Review by wxiaoguang — APPROVED** [review]

**Review by lunny — APPROVED** [review]
